### ISSUE TITLE
Custom signatures

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1]
I want to have custom signatures that are appended to messages I send. These should probably be configurable per-account, so I can have a different signature at work versus my personal address.

**Comment by axeltaylor** [comment]
+1 maybe this feature could be implemented as a plugin.

**Comment by bengotow** [comment]
Hey—thanks for the feature request. This could definitely be a plugin.

To keep track of core feature and package ideas, we're creating a public Trello board. I've moved this there—feel free to upvote it: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap
