### ISSUE TITLE
list of existing plugins?

### ISSUE THREAD

**Issue by matthewmueller** [nylas/N1#100]
Just got an invite to N1 and I'm extremely impressed! I noticed there are great docs on how to build a plugin, but not on existing community plugins. Not sure if this is just me missing something or because the platform is super new, but I haven't been able to find them.

**Comment by Envo** [comment]
+1

**Comment by rawjam** [comment]
+1

**Comment by grinich** [comment]
https://github.com/nylas/n1-plugins

you can also PR this repo and add links to your own :)

**Comment by jallen0927** [comment]
This link doesn't exist now.

**Comment by grinich** [comment]
It's in the main GitHub readme of this project: https://github.com/nylas/N1/blob/master/README.md

**Comment by Maggew** [comment]
Here is direct link -- https://github.com/nylas/N1/blob/master/README.md#bundled-plugins

**Comment by jeffmcneill** [comment]
I want to add that it is unclear where plugins are or can be found. The website is full of rotating gifs and no links out. It really isn't helpful if one wants to know more about any specific aspect/function/feature of Nylas N1. Can we have a little more text and some more links with more text on the linked pages? More is more, and less is less informative.

**Comment by nickbuddendotcom** [comment]
Now it's here: https://github.com/nylas/nylas-mail#plugin-list
