### ISSUE TITLE
Ubuntu installation via Software Manager displays bad package warning

### ISSUE THREAD

**Issue by koustuvsinha** [nylas/N1#1000]
Hi! I am trying to install N1.deb by Software Center, and Ubuntu displays a "bad package" warning. The message is as follows : 

```
Lintian check results for /home/koustuv/Downloads/N1.deb:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_IN.ISO8859-1"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
E: nylas: control-file-has-bad-permissions postinst 0775 != 0755
E: nylas: control-file-has-bad-permissions postrm 0775 != 0755
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.
```
![screenshot from 2016-01-14 00 56 31](https://cloud.githubusercontent.com/assets/5122822/12305254/c2ec591a-ba59-11e5-8559-6a446dfa38c0.png)

I really want to try it out. Is it a false alarm and should I proceed installation via dpkg?

System information : 
* Ubuntu 14.04 LTS 64Bit 3.13.0-74-generic

**Comment by bengotow** [comment]
Hi @koustuvsinha — thanks for filing this. We're going to try to get this fixed today. Stay tuned! (Merging as dup of #710 )

**Comment by bengotow** [comment]
Hi @koustuvsinha — can you try this build and see if it resolves the issue for you?

https://edgehill.s3.amazonaws.com/0.3.43-c8dcab5%2Flinux-deb%2Fx64%2FN1.deb

It should address the permissions issue - just want to check and make sure you don't encounter any other errors before we ship an update.

**Comment by koustuvsinha** [comment]
@bengotow yeah the issue is resolved! thanks :)

**Comment by koustuvsinha** [comment]
btw are u guys planning to setup a Debian package repository?

**Comment by bengotow** [comment]
Hey @koustuvsinha — yep, we run one! I believe it's `apt.nylas.com`. It should get added to your repos in a postinstall script.

**Comment by koustuvsinha** [comment]
awesome! :smile:
