### ISSUE TITLE
Main Window Loses State on Restart

### ISSUE THREAD

**Issue by JohnSandel** [nylas/N1#1001]
It's preferable for the main window to remember its placement and size on restart. C'est possible?

**Comment by jstejada** [comment]
Hi @JohnSandel, thanks for the report. We already do this and it should definitely work. Is it never remembering window state, or is there a specific case where this happens?

**Comment by JohnSandel** [comment]
Sorry, I could've been more detailed. I see this behavior on every restart, on a Chromebook (Intel 3205U 1.5 GHz) running Elementary OS Freya 0.3.2, on Ubuntu 14.04, updated Nylas to 0.3.43.

On my Mac running OS 10.10.5, N1 remembers its previous window state on every restart.

(BTW, you guys are absolutely killing it with the design of this app. I'm not a coder, so I won't be writing any plugins … it's just very useful out of the box.)

**Comment by ThePsionic** [comment]
I'm on Linux Mint 64-bit 17.03 Cinnamon and the main issue I have right now in
terms of positioning is that the app doesn't start fully maximised, as in it
doesn't take up the entirety of the screen, showing the resize mouse icons
when hitting the sides. It's not a major problem, I just can't slam my mouse
into the top-right corner and click to close the app :P

> On Jan 13 2016, at 10:00 pm, JohnSandel &lt;notifications@github.com&gt;
wrote:  

>

> Sorry, I could've been more detailed. I see this behavior on every restart,
on a Chromebook (Intel 3205U 1.5 GHz) running Elementary OS Freya 0.3.2, on
Ubuntu 14.04, updated Nylas to 0.3.43.

>

> On my Mac running OS 10.10.5, N1 remembers its previous window state on
every restart.

>

> (BTW, you guys are absolutely killing it with the design of this app. I'm
not a coder, so I won't be writing any plugins … it's just very useful out of
the box.)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1001#issuecomment-171430778).![](https://github.com/notifications/bea
con/AAzZYGmSOf7VuLuz1grsOnKKPqRDWBUTks5pZrJUgaJpZM4HEVwE.gif)

**Comment by jstejada** [comment]
Closing as stale, please re open if the issue persists.

**Comment by idodialog** [comment]
Nylas never remembers the window state. Linux Mint 18.
Very annoying.
