### ISSUE TITLE
Suggestion: Todoist Integration

### ISSUE THREAD

**Issue by G3-Logic** [nylas/N1#1002]
Would be awesome to see a Todoist plugin for N1. Used to be one for Postbox but no longer. Would fill a huge void and probably attract a bunch of Todoist users.

**Comment by enoversum** [comment]
Actually, that would prove quite handy for some integrations, for me it would be Trello. Is there a recommended way of suggesting such integrations, @mbilker ?

**Comment by mbilker** [comment]
Currently, the only way is to post an issue on here and then the Nylas team will post it onto the Trello page.

**Comment by mbilker** [comment]
Any plugin related issue is tagged as `plugin` to make it easier to find when searching through the N1 issue list. Any issues with the plugin should be filed at the plugin's repository.

**Comment by enoversum** [comment]
@mbilker Okay, thank you for directing me, will open up an 'issue' then for Trello integration, so you can put it up on … Trello :laughing: .

**Comment by mbilker** [comment]
@enoversum Actually, I am just a contributor, not a member of the Nylas team. I help with issue tagging and I submit PR's for any code issues I can fix.

This issue is fine for the suggestion. I am going to prepend the title with `Suggestion: `.

**Comment by enoversum** [comment]
@mbilker I just saw you around here a lot, tagging, asking, answering and stuff, so I figured you might somehow be involved, or at least a bit more in the know than us usual people ;).

**Comment by mbilker** [comment]
I am more involved and the best way to get more involved is to join the Slack group (the #n1-help and #n1-developers channels specifically) to become more in the loop.

Beware of #n1-developers, every single issue opened and closed is posted there.

**Comment by enoversum** [comment]
@mbilker Thank you for letting me know, my time is currently strictly limited even though I stick to reporting in here, so I had better not join the Slack channels at this point in time :smile: .

**Comment by anopensourceguy** [comment]
@enoversum  @G3-Logic - I have made such a plugin - :+1: https://github.com/anopensourceguy/TodoistN1

**Comment by grinich** [comment]
@anopensourceguy can you add some screenshots to the Readme and I'll include this in our plugin directory?

**Comment by anopensourceguy** [comment]
@grinich  done good sir

**Comment by enoversum** [comment]
@anopensourceguy Looks good (even though I do not use Todoist at all :wink: )! You don’t happen to love and use Trello as well and consider a similar plugin :heart: ?

**Comment by anopensourceguy** [comment]
Well why not.let the nylas team consider this first and I will surely be
looking into other valid integrations

**Comment by anopensourceguy** [comment]
@grinich added the screens

**Comment by grinich** [comment]
thanks! :)

**Comment by hans-zen** [comment]
What I really like to see is an evernote plugin. That's the only reason that stops me to fully migrate from postbox.

**Comment by alexfruehwirth** [comment]
hey guys, 
i got inspired by @anopensourceguy but looked for a bit more features. As i'm not really into that coffeescript part, i decided to rewrite the plugin from scratch, with N1Todoist as a starting point. 

it's still in development and i'm eager to add some more features and refactor parts, but if you want, you can already use it and give feedback. Plugin currently supports Add/Complete/Uncomplete/Remove tasks, changing the tasks text and adds a label for added emails. 

https://github.com/alexfruehwirth/N1TodoistIntegration

:+1: for @anopensourceguy :) hope you don't mind i decided to go my own way!

**Comment by joshcossey** [comment]
@alexfruehwirth Keep. It. Going.    :+1:

**Comment by ddecock** [comment]
I can't get this either of the plugins working. Information I'm missing is how to get it working with todoist.
You need to add an application to todoist? A redirect URL ?

**Comment by anopensourceguy** [comment]
@ddecock yes , you need to create an application on todoist developer website, get the api key , client secret and also the recirect url and then edit the message-sidebar file and add the relevant api information where its mentioned 

I hope it helps

**Comment by ddecock** [comment]
Thanks.

Still have some issues with login in. I believe there is a problem in the login.jsx code, in the handleLoginClick. I believe the first line is missing a 'var ' keyword. I also believe you don't need to create a new browerWindow on the second line but reuse the global one?
