### ISSUE TITLE
Mails in deleted conversations doubled when a new message is added

### ISSUE THREAD

**Issue by ThePsionic** [nylas/N1#1003]
Steps to reproduce:
1) Have a conversation of 2+ mails.
2) Delete this conversation.
3) Have the other party reply to this conversation again.

What will happen is that mails that appeared in the conversation before it was deleted will be duplicated and minimised. I'll add a screenshot when I next encounter it.

**Comment by jstejada** [comment]
thanks for reporting this @ThePsionic , I'm merging this into duplicate #117

**Comment by jstejada** [comment]
thanks for reporting this @ThePsionic , I'm merging this into duplicate #1813
