### ISSUE TITLE
Feature Request: Single click on draft to bring up editor view

### ISSUE THREAD

**Issue by AndrewTHuang** [nylas/N1#1005]
Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)
Mac
Gmail

In the Inbox, single clicking an email brings up the email view where you can type a message.

In Drafts, I can only double-click a draft which opens a new window to edit the message in. Would love to see the draft open in the same window just like any other email (i.e. in two panels if you're using the two panel layout).

**Comment by mbilker** [comment]
:+1: I also agree with the double-clicking on a draft. I am often confused why a single-click does nothing and I proceed to open the DevTools to check if a caught exception occurred.

**Comment by jackiehluo** [comment]
Closing out of inactivity—we use double-clicking because that's usually standard behavior on Mac for opening a new window!
