### ISSUE TITLE
Add layout and theme preferences to View dropdown in toolbar

### ISSUE THREAD

**Issue by AndrewTHuang** [nylas/N1#1007]
Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)
Mac
Gmail

Would be nice to have some more customization options available without having to go into Preferences.

**Comment by bengotow** [comment]
![image](https://cloud.githubusercontent.com/assets/1037212/15131224/fd294f5c-1602-11e6-8f28-5a6a57452728.png)

![image](https://cloud.githubusercontent.com/assets/1037212/15131226/001f5918-1603-11e6-9b74-5cf7b07ba517.png)

We've been expanding the menus and I think this is taken care of now. Cheers!
