### ISSUE TITLE
Bug: Vertical scrollbar in sidebar

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#1008]
![screenclip 8](https://cloud.githubusercontent.com/assets/8190174/12309888/6495cd58-ba4d-11e5-80a8-ab4c13a900f7.png)

As the screenshot hopefully is able to show, there now is a vertical scrollbar in the left pane where folders and the account switcher resides. Being on Windows 10 :stuck_out_tongue: .

Edit: Obviously it is not the amount of folders that provokes it. Plus I tried out both the Taiga and the default light theme, they have both the phenomenon on display ;).

**Comment by mbilker** [comment]
I experience this in the default light theme as well.

_First picture is from [nylas/N1](https://github.com/nylas/N1) build and second picture is from [mbilker/N1](https://github.com/mbilker/N1) build with proprietary packages added_
![2016-01-13-18-47-19_204x849](https://cloud.githubusercontent.com/assets/1266541/12311636/6c984e94-ba26-11e5-84bc-8e6fb7912d51.png)
![2016-01-13-18-49-26_214x925](https://cloud.githubusercontent.com/assets/1266541/12311637/6c984584-ba26-11e5-8452-61e82a5ef669.png)

**Comment by Iain-Stevenson** [comment]
I guess they mean that the scroll bar is showing when not needed.

Me too, Windows 10 latest release. Scroll bar is just there and does not scroll with small number of folders, scrolls normally with excess folders for view, or when window size is reduced sufficiently.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. Does this happen for you immediately when the app is launched? Or only after you resize the window / switch accounts, etc? I haven't been able to reproduce it yet.

**Comment by mbilker** [comment]
It only appears if I hover the mouse cursor over the area where the scroll bar is. My window is maximized at launch to my screen's sized by the tiling window manager.

**Comment by enoversum** [comment]
It does not depend on resizing or small window size. Start N1 as you want, resize as you want, have folders as many or few you could imagine, the scrollbar is there when you hover the area :wine_glass: .

**Comment by mbilker** [comment]
I have not checked if this is present in older versions.

**Comment by mbilker** [comment]
This issue is present in `0.3.36` as well. I used the official `deb` file and used the [N1 AUR](https://aur.archlinux.org/n1) to build an Arch Linux package using the `deb`.

**Comment by enoversum** [comment]
@jackiehluo Closed? I still the scrollbar in the left pane. It has stayed loyally throughout the last version :smile: .
![screenclip](https://cloud.githubusercontent.com/assets/8190174/13723338/b065019e-e861-11e5-8941-6120d223bd69.png)

**Comment by DavidChouinard** [comment]
@enoversum you still get the scrollbars under master?

**Comment by jackiehluo** [comment]
@enoversum That's the production build! It should be fixed, pending release.

**Comment by enoversum** [comment]
@DavidChouinard @jackiehluo Oh well, yes, using the normal update routine, i.e. no pedings :smile: . Thanks for letting me know, I’ll make sure next time around to pay more attention.

**Comment by mbilker** [comment]
@enoversum The update worked when you had no pending actions?

**Comment by enoversum** [comment]
@mbilker No, I meant: I use the production version of N1, i.e. no pending/nightly versions, haha :laughing: .

**Comment by mbilker** [comment]
@enoversum That makes much more sense. I was wondering if that was a valid strategy for people to update more successfully using the built-in updater on OS X and Windows. Some people have a hard time updating and it often fails with no indication that the update failed or failed to restart N1.

**Comment by enoversum** [comment]
@mbilker I am one of the lucky persons who never had an issue updating on Windows so far :wink: .
