### ISSUE TITLE
Feature Request: Support for Exchange Web Services (EWS) and not just ActiveSync

### ISSUE THREAD

**Issue by brocktoon** [nylas/N1#1009]
The Exchange implementation supports ActiveSync (typically used for mobile) as opposed to EWS.  It would be great if EWS were also supported.  Microsoft seems to be encouraging most developers to go the EWS route as opposed to ActiveSync.

**Comment by mbilker** [comment]
Please post this over at [nylas/sync-engine](https://github.com/nylas/sync-engine). This repository is only for the N1 client.
