### ISSUE TITLE
Feature request: Trello integration

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#1010]
Creating tickets from e-mails (with ability to edit title, body and file attachments) would be rad!

**Comment by mbilker** [comment]
Oh. This is what you mean't by Trello integration. Sorry about earlier!

**Comment by bengotow** [comment]
That would be rad!

**Comment by mbilker** [comment]
From my estimates, this would be similar in complexity to my PGP plugin. Most of the state for this plugin can be stored in custom objects as part of a `NylasStore` and interface with a `message:BodyHeader` extension component.

**Comment by kilokill** [comment]
@mbilker Has there been any movement on this? Adding e-mails as Trello Cards is something I can probably help contribute towards.

**Comment by mbilker** [comment]
I am not developing this. If someone wants to develop this they can. The
Nylas team has enough on their plate with bug fixing.

**Comment by enoversum** [comment]
@mbilker Too bad, I had hopes you would give it a go. Thanks for letting us know.
Unfortunately I am not able to develop plugins of any kind.

**Comment by bengotow** [comment]
Moving this to the plugin ideas list here: https://trello.com/c/G8fz9ITX/65-trello-integration
