### ISSUE TITLE
On Linux, English spellchecking is disabled for `en-GB`

### ISSUE THREAD

**Issue by bengotow** [nylas/N1#1011]
We are only detecing `en-US` for the english spelling dictionary. We should look for anything with the `en-` prefix.

**Comment by mbilker** [comment]
This also depends if the Hunspell `en-GB` spelling dictionary is installed.

On my Arch Linux computer, the `en-GB` dictionaries are installed alongside the `en-US` ones:
```
[~]── - ls -lh /usr/share/hunspell/en_{US,GB}*
lrwxrwxrwx 1 root root   15 Jun  6  2015 /usr/share/hunspell/en_GB.aff -> en_GB-large.aff
lrwxrwxrwx 1 root root   15 Jun  6  2015 /usr/share/hunspell/en_GB.dic -> en_GB-large.dic
-rw-r--r-- 1 root root 3.1K Jun  6  2015 /usr/share/hunspell/en_GB-large.aff
-rw-r--r-- 1 root root 858K Jun  6  2015 /usr/share/hunspell/en_GB-large.dic
-rw-r--r-- 1 root root 3.1K Jun  6  2015 /usr/share/hunspell/en_US.aff
-rw-r--r-- 1 root root 531K Jun  6  2015 /usr/share/hunspell/en_US.dic
```

**Comment by mbilker** [comment]
By default, `node-spellchecker` only contains the Hunspell `en_US` dictionary. Maybe fork `node-spellchecker` and add the other dictionaries in according to their license?

**Comment by bengotow** [comment]
I'm tagging this as a good stater issue. The problem is somewhere in our implementation here: https://github.com/nylas/N1/blob/unified-inbox/src/nylas-spellchecker.coffee#L79. It'd be great to investigate what `spellchecker.getAvailableDictionaries()` returns on Linux. It might be that we're looking for `en-GB`, when the spellchecker library is returning `en_GB`, or something like that.

**Comment by mbilker** [comment]
I actually have no spellchecker functionality. I do not compose many messages and do not make many mistakes, but I checked one time and I found many errors.

Here is output from the JS console:
```javascript
var Spellchecker = require('spellchecker');
Spellchecker.getAvailableDictionaries();
-> []
$n.NylasSpellchecker.getAvailableDictionaries()
-> []
```

The `$n.NylasSpellchecker.getAvailableDictionaries()` returning `[]` is odd because of that implementation.

**Comment by mbilker** [comment]
Wow. This is an obscure bug with the CoffeeScript. It tests `!"en_US"` which is always false.
```
NylasSpellchecker.prototype.getAvailableDictionaries = function() {
      var arr, _ref, _ref1;
      if (process.platform === 'linux') {
        arr = spellchecker.getAvailableDictionaries();
        if (_ref = !"en_US", __indexOf.call(arr, _ref) >= 0) {
          arr.push('en_US');
        }
        return arr;
      } else {
        return (_ref1 = spellchecker.getAvailableDictionaries()) != null ? _ref1 : [];
      }
    };
```

**Comment by bengotow** [comment]
Hmm this is really strange. It'd probably be good to dig down a bit and see why node-spellchecker is returning no dictionaries for you, when in fact (it appears) adding en_US and then asking it to spellcheck works fine!

**Comment by mbilker** [comment]
@bengotow It returns an empty array because it does not check for existence at https://github.com/atom/node-spellchecker/blob/master/src/spellchecker_hunspell.cc#L46-L48.

**Comment by jstejada** [comment]
merging into #1392
