### ISSUE TITLE
Bad DEB Package Quality

### ISSUE THREAD

**Issue by kamiller42** [nylas/N1#1012]
When installing the the Debian package, the software center installer reports the following:

The package is of bad quality

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /home/kmiller/Downloads/N1.deb:
E: nylas: control-file-has-bad-permissions postinst 0775 != 0755
E: nylas: control-file-has-bad-permissions postrm 0775 != 0755
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.

My OS is 64-bit Ubuntu 14.04.

**Comment by mbilker** [comment]
Fixed with #710
