### ISSUE TITLE
Shortcut '#' focus the search-field and is not deleting email (win10 64bit GER)

### ISSUE THREAD

**Issue by ZaidoR1** [nylas/N1#1014]
If I press '#' when Email is selected, it is not deleted as desired.
It is focusing the Search-Textfield.

@update
I have found the problem. I have a german keyboard so I have to press "Shift+3".
Possible Solution: Don't use the keycode, use the ascii characters to check the pressed key.

**Comment by jstejada** [comment]
hi @ZaidoR1 I'm merging into #976
