### ISSUE TITLE
Can't choose N1 as default application for E-Mail in windows 10

### ISSUE THREAD

**Issue by ZaidoR1** [nylas/N1#1016]
In windows 10 you can choose a default email application. But N1 is not showing there, so it is not possible to choose it. Take a look at the screenshot. Thanks.

![2016-01-14 09_53_37-einstellungen](https://cloud.githubusercontent.com/assets/16700058/12319762/cbd31c26-baa4-11e5-93c4-10c6667b0369.png)

**Comment by jstejada** [comment]
merging into duplicate #417
