### ISSUE TITLE
Start composer via command line

### ISSUE THREAD

**Issue by koterpillar** [nylas/N1#1018]
Most email clients have an option to start composing an email via the command line, e.g. `thunderbird -compose`, Evolution start composing just given an address (`evolution address@example.com`). N1 should support the same.

**Comment by bengotow** [comment]
Hi @koterpillar — command-line compose isn't on the roadmap, but you're welcome to submit a pull request! On most platforms, you can open a new N1 composer with just a mailto link (on the Mac OS X command line, `open mailto://address@example.com`.

**Comment by koterpillar** [comment]
I'm not talking about the _command line composer_. Rather, at least on Linux, running either `xdg-open mailto:a@example.com` or `nylas mailto:a@example.com` does nothing.

**Comment by bengotow** [comment]
This should be possible in the next release via:

`nylas mailto:bengotow@gmail.com`

or

`nylas /path/to/file/to/attach.txt`

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
