### ISSUE TITLE
N1 does not work with BetterTouchTool

### ISSUE THREAD

**Issue by JunniH** [nylas/N1#1020]
I can't maximize Nylas N1 with the BetterTouchTool action, when snapping it to the top of my screen. It doesn't do anything.

**Comment by bengotow** [comment]
Thanks for filing this @JunniH —I'm not familiar with how BetterTouchTool works. It may be best to reach out to the developers of that app and see if they can offer any insight.

**Comment by joshvickerson** [comment]
Curious if there's any update on this funcitonality. I use Magnet as my window manager and it doesn't work either (presumably it works similarly to BTT to determine the actual window, but I thought I'd mention it as a window manager).

**Comment by JunniH** [comment]
I'm not sure which update it was, but N1 does integrate with BetterTouchTool at this point.

**Comment by joshvickerson** [comment]
Hm... I've also tried Better Snap Tool, which I would assume works the same as BTT, but it can't snap N1's window either.

**Comment by jackiehluo** [comment]
Going to close this issue since apparently it's working now—if there are problems with other apps, let us know.
