### ISSUE TITLE
Feature Request: Sync colored flags from Apple Mail or Thunderbird

### ISSUE THREAD

**Issue by Salamafet** [nylas/N1#1024]
Like Mail on Mac or Thunderbird, the possibilities to Flag or attach a label to the mail with different color and sync with the server.

Example:
If I flag a mail in purple on my Mac (on N1). I can't see this flag on my PC (on N1).

**Comment by grinich** [comment]
We unfortunately can't get this from the server.

**Comment by Salamafet** [comment]
I think you don't have understand my request.

I want to add colored flag on my mail but sync the flag with the Nylas server. Not with Apple server or other mail server.

If I flag a mail in red on PC1 with Nylas the PC2 and PC3 with Nylas client too automatically flag the chosen mail in red.

Sorry I don't have a good English

**Comment by grinich** [comment]
Gotcha. This is something that should probably be created as a plugin and use a separate external datasource for mapping that metadata (such as Firebase).
