### ISSUE TITLE
Unread count off by 5 (displays -5 with empty inbox)

### ISSUE THREAD

**Issue by malonehedges** [nylas/N1#1028]
I have tried deleting that account and re-adding it with no success. I have two other accounts on N1 and both display the correct unread count. 

If I have 6 unread messages, it will display a 1 in the unread count.

I am happy to provide logs / anything to help debug but don't know what I should post here. Please let me know.

Thanks for the help.

![image](https://cloud.githubusercontent.com/assets/12092296/12342330/cdbc94da-bae6-11e5-9998-514c04a4a25b.png)

**Comment by mbilker** [comment]
Hey @malonehedges. This issue appeared in older versions of N1, but it should have been fixed in recent versions of N1. Which version of N1 are you using?

**Comment by malonehedges** [comment]
I am using `Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)`  
  

Malone Hedges

> On Jan 15 2016, at 12:14 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Hey [@malonehedges](https://github.com/malonehedges). This issue appeared in
older versions of N1, but it should have been fixed in recent versions of N1.
Which version of N1 are you using?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1028#issuecomment-172057284).![](https://github.com/notifications/bea
con/ALiDiOpC4jjPwODYIUwLyWG3L_zMEorJks5paTyMgaJpZM4HFYY4.gif)

**Comment by jstejada** [comment]
Hey guys, thanks for reporting this. I'm going to merge it into duplicate #759
