### ISSUE TITLE
Exchange Signatures

### ISSUE THREAD

**Issue by jbrooksuk** [nylas/N1#103]
Is it possible to add a signature for an Exchange account? I can't see anything to suggest that you can.

**Comment by stagfoo** [comment]
Currently Custom Signature are on the road map, https://trello.com/b/hxsqB6vx/n1-open-source-roadmap
But an alternative I am currently i am setting up a template (Stored as html files) and just calling the template each time i send an email.

**Comment by bengotow** [comment]
Hey folks—signatures are landing in a release later this afternoon (0.3.26). Going to go ahead and close this issue. Enjoy!

**Comment by mykebates** [comment]
sweeeeet nectar!
