### ISSUE TITLE
Delete a folder only greys out

### ISSUE THREAD

**Issue by Yerlix** [nylas/N1#1032]
After creating a folder and deleting it again, the folder won't be gone. It's only greyed out.
On my exchange server, the folder is gone, only in N1 it isn't.

**Comment by mbilker** [comment]
Thanks for the bug report. If you restart N1, does the folder disappear?

**Comment by Yerlix** [comment]
Sorry for the late reply.

After restarting the folders were still there. Even after a full restart off my mac.
However, after relinking my exchange account (due to company password policies I needed to relink it), the deleted folders where actually gone.

**Comment by jstejada** [comment]
hey @Yerlix can you let me know if you are able to reproduce this again. The folder will initially be grayed out initially but should be cleared from the list in a moment or two

**Comment by Yerlix** [comment]
I tried it. But the deleted folder won't go away. It greys out but that's it.
According to N1 I'm running the latest version
![image](https://cloud.githubusercontent.com/assets/3891388/12701365/ff56a7c8-c807-11e5-9237-3629fea9004a.png)

**Comment by Yerlix** [comment]
After updating N1 to 0.4.5-b0ec335, the test folder was gone. So I've tried it again, but I can't even create a new folder.
The activity window gives error code 400:
![image](https://cloud.githubusercontent.com/assets/3891388/12880177/24609fb0-ce3e-11e5-9e77-4ca3b66a4008.png)

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (0.4.47) that should fix this issue—let us know if you see it again! Thanks!
