### ISSUE TITLE
Email sent via N1 is displayed in Times New Roman in Outlook

### ISSUE THREAD

**Issue by jbrooksuk** [nylas/N1#1033]
As the title says, any email sent from N1 and viewed in Outlook seems to use Times New Roman?

**Comment by mbilker** [comment]
Thanks for the report @jbrooksuk. Currently, N1 sends the message with no font specified for the text. N1 sets the default font for rendering messages to its own proprietary font.

A raw HTML message sent with N1 looks like:
```html
<head></head><body>testing font in raw headers</body>
```

**Comment by mbilker** [comment]
Outlook's default rendering font is Times New Roman when the message body does not specify a font, or the font is not found in Windows' font store.

**Comment by jbrooksuk** [comment]
Is this something that will change in the future?

**Comment by mbilker** [comment]
Paging @bengotow

**Comment by foxgeere** [comment]
+1

PLEASE have it specify a font. Outlook using Times is not pretty and makes emails look unprofessional.

**Comment by bliswebagency** [comment]
Sooo... any plans to address this? Anything that forces a sans serif font across all email platforms would be amazing.

**Comment by molstrangler** [comment]
Totally agree, at the very least try to use a web font, just host your font and point towards that.

I've mentioned this before and shown it's possible to create better signatures using web fonts in #1791 this doesn't add any signifiant delay to displaying the email.

In my book, there's not much point in an email client that's only concerned with how it look to its own users this is very inward looking and self congratulatory.  N! has a very small user based and I would suggest that 99.99% of emails sent from N1 would be rendered  & read by a different email client.

By it's very nature, N1's performance and increased popularity in the world is how it looks to people who are not already paying users.  And that means people reading emails created by N1 by N1 users.  And the best free add is to make email look fabulous to users of other email clients.

So please experiment with using the font you install for use by N1 as the default webfont.  Then we can work on other webfonts like fixed width for plain text fonts.

**Comment by jbrooksuk** [comment]
Or, at the very least, just use a sans-serif font by default.

**Comment by emailwizardry** [comment]
+1 for this. 

I love N1, but this is the thing holding me back from using it for my business. Agree with @foxgeere that it makes you look unprofessional to people using Outlook.

**Comment by jackiehluo** [comment]
Merging into #1087!
