### ISSUE TITLE
Display labels in Split message list

### ISSUE THREAD

**Issue by ZaidoR1** [nylas/N1#1035]
It should be possible to color each label (gmail) in N1.
So that you can see in e.g. Inbox each email with the specified labels/colors.
Like in the screenshot.

![2016-01-15 11_59_04-nylas](https://cloud.githubusercontent.com/assets/16700058/12351691/d2253ca4-bb7f-11e5-8286-d00e16a95c6f.png)

**Comment by mbilker** [comment]
Thanks for the report @ZaidoR1. Oh wow, this is actually a bug. The Gmail labels are not displayed in the split view. Here is a screenshot of the other message view where labels are displayed:

![2016-01-15-14-06-08_378x309](https://cloud.githubusercontent.com/assets/1266541/12362404/242febc8-bb91-11e5-96a8-31a8b521658b.png)

**Comment by bengotow** [comment]
This has been fixed on master and will ship in the next release later this month. Sorry it took so long! Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/1037212/12995492/adeb3a88-d0dc-11e5-81fd-34fd520d66ce.png)
