### ISSUE TITLE
N1 apm rewrites the Atom apm

### ISSUE THREAD

**Issue by yriveiro** [nylas/N1#1040]
N1 is rewritting the apm binary of Atom.

If Atom is installed and the apm shell command too, N1 rewrites the apm symlink to N1 apm. To put Atom's apm work again is necessary reinstall it ...

![screenshot 2016-01-15 15 34 30](https://cloud.githubusercontent.com/assets/934763/12357016/9de52af8-bb9d-11e5-8bc6-e810ff165285.png)

**Comment by mbilker** [comment]
Dupe of #39
