### ISSUE TITLE
Feature Request: SSL support for adding Exchange Accounts (Linux)

### ISSUE THREAD

**Issue by gabacosta** [nylas/N1#1043]
Right now N1 allegedly supports Exchange accounts for I have found this to be false. Every time I try to add my company's exchange account N1 refuses to add it. I talked to my IT department and they said the issue lies in the fact that N1 does not support SSL connections.

**Comment by mbilker** [comment]
Is your company's Exchange server available only to the intranet? If so, the hosted Nylas Sync Engine will not be able to access your company's Exchange server.

**Comment by gabacosta** [comment]
@mbilker No, the Exchange server is not only available to the intranet. Again, I talked to my ITS department and they came to the conclusion that the issue has to do with this app. If you read other people's post regarding Exchange issue, they will tell you the same thing. That being said, I would really appreciate any kind of help regarding this issue, and if the issue is really related to the app itself then just let me know, I can wait for a fix. Thanks.

**Comment by mbilker** [comment]
The Exchange server must be available to the internet if you want to use it
with N1. This is how N1 is designed with a Sync Engine managing the
connection to the mail servers and N1 connects to the Sync Engine.

**Comment by bengotow** [comment]
Hi @gabacosta — it sounds like you should be able to add this account. We support SSL with Exchange (in fact I think we might require it!) Do you have two-factor auth enabled on your exchange account? In that case, you need to add an Application Password for N1 (See https://nylas.zendesk.com/hc/en-us/articles/216108867-Does-N1-support-2-factor-auth-).

If that doesn't resolve the issue, could you email support@nylas.com, and include the email address you're having trouble with? We'll likely need a bit more information about your Exchange setup to fix the problem. Cheers!
