### ISSUE TITLE
Downloading Attachment Always Opens Finder Window in OS X

### ISSUE THREAD

**Issue by JohnSandel** [nylas/N1#1044]
In OS 10.10.5, Nylas N1 0.3.43-b95f1f7 (0.3.43-b95f1f7), with: 

Preferences > General > Attachments > Download attachment for new mail

set to "Manually": 

After the download finishes, N1 automatically opens a new Finder window to reveal the attachment's location.

If this is a feature & not a bug, it's preferable to allow the user the choice to invoke the Finder reveal, rather than require the Finder window to open automatically every time.

Have I missed a setting for this?

**Comment by mbilker** [comment]
Thanks for the report @JohnSandel. You did not miss any setting. Currently, N1 shows the file in the default file explorer after downloading an attachment (source [here](https://github.com/nylas/N1/blob/7bbcbbe29a83860b0b2e5b04b669d4cbeaa0de67/src/flux/stores/file-download-store.coffee#L221)). This applies to all platforms.

**Comment by JohnSandel** [comment]
Hmm. Opening a window every time, without giving the user a toggle to prevent it, forces the user to interrupt what they're doing & contend with the new task; an odd choice. After all, when I click on the download button in the message, the OS asks me where to put the file. To then immediately show me the location of the file seems redundant.

I suppose one could argue the other default—requiring the user to locate the downloaded file—is arbitrarily equal; same number of steps. But the latter is the usual behavior in the OSes I've used & at least in its passivity gives the user the power of decision, including whether to deal with the file now or later.

If it's okay here, I'll just change my issue into a feature request for the toggle.

**Comment by bengotow** [comment]
I agree we should change this behavior - will get this on deck.

**Comment by JohnSandel** [comment]
My hero—!

**Comment by JeroenBoersma** [comment]
Make it a option in preferences, where files get saved by default and if one wants there explorer/finder/whatever opened after saving.

When I want to safe a attachment most of the times I just save it to my Downloads directory and move it along from there on I moment I choose.

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
