### ISSUE TITLE
Issue: words with polish characters are underlined in red

### ISSUE THREAD

**Issue by michalpaszkowski** [nylas/N1#1046]
As the title says, some proper polish words (only) with polish characters are underlined in red to that character.
![zrzut ekranu 2016-01-15 o 23 00 19](https://cloud.githubusercontent.com/assets/13875746/12366501/d8f85fbe-bbdb-11e5-84f6-e08301b9dd98.png)

N1 version: 0.3.43-b95f1f7

**Comment by mbilker** [comment]
Thanks for the report @michalpaszkowski. Great, another spellchecker bug. The spellchecker appears to not account for accented characters that are not normally used in the English language.

**Comment by bengotow** [comment]
Hi @michalpaszkowski — do you know what the primary language preference is on your system? On Mac OS X, N1 should properly spellcheck in Polish if it's set as your system language. Unfortunately, if your system language is English (or another language), spellcheck will always run in that language. We aren't able to do any language detection yet.

**Comment by michalpaszkowski** [comment]
Hi, Mac's system spell check is set to Polish, and actually spell checking works for some words, but for the ones with polish chars (not all) it is underlining these words red to the polish character. It's weird.

**Comment by jstejada** [comment]
merging into #1392
