### ISSUE TITLE
Feature Request: Multiple Signatures / Global Signatures, better signature management

### ISSUE THREAD

**Issue by jerryevo** [nylas/N1#1047]
Sometimes it is useful to have more than one signature for account.

**Comment by InvisibleOrdinary** [comment]
+1… 
actually, sometimes it's necessary

**Comment by christopherg** [comment]
+1...
agreed. this would be a really helpful feature.

**Comment by itisNathaniel** [comment]
+1

**Comment by fstrube** [comment]
+1

**Comment by amig** [comment]
+1

**Comment by jackiehluo** [comment]
Hey! We added this feature in `0.4.47`! Let us know what you think. Thanks!
