### ISSUE TITLE
Calendar invite response sending to incorrect address.

### ISSUE THREAD

**Issue by HarleyKwyn** [nylas/N1#1048]
I'm on N1 version Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)

When responding to a calendar invite from an exchange e-mail use at `first.last@company.com` It attempt to send to `last@company.com` instead of `first.last@company.com` and the exchange server sends a bounce back e-mail. It was working before the last update. 

Wonder what changed. I can look into it later but I thought I'd report it for now.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
