### ISSUE TITLE
Send Later / Schedule Emails / Postpone Sending

### ISSUE THREAD

**Issue by macneo** [nylas/N1#105]
I wish we could send drafts at a specific day/time. I don't know why gmail doesn't have it by default.

**Comment by bengotow** [comment]
Hi @macneo — I'd really like to see this as well. I've added it to our open source roadmap on Trello: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap. Feel free to track it and upvote it there if you have a Trello account!

**Comment by emorikawa** [comment]
I'm reopening this issue as the master thread for the Send Later / Scheduling emails plugin idea.

**Comment by emorikawa** [comment]
See #275, #1183, and #290 as duplicates.

**Comment by jstejada** [comment]
this has landed in the latest release! enjoy!
