### ISSUE TITLE
Feature Request: Explicit Label Toast When Changing Label on Thread

### ISSUE THREAD

**Issue by xasos** [nylas/N1#1050]
When I delete a message, a toast pops up that says "changed label on 1 thread" - however, this doesn't provide enough info to the user. I believe these notifications should be for visual confirmation ("did I *actually* want to send this thread to the trash?"). If it was changed to "Sent 1 item to trash" it would make for a better visual confirmation about the action you performed with that specific email thread.

**Comment by jackiehluo** [comment]
Closing because we made this change, I think!
