### ISSUE TITLE
Move plugin list to separate repository/readme

### ISSUE THREAD

**Issue by xasos** [nylas/N1#1052]
As the # of plugins for N1 grows, it may be appropriate to move them from the [readme](https://github.com/nylas/N1#plugin-list) to another repository (titled "awesome-n1-plugins" or something along those lines) or a separate readme file.

**Comment by grinich** [comment]
I had it in a separate repo but nobody could find it. 

We're going to make an index within N1 sometime in the next couple of months to list packages.
