### ISSUE TITLE
I can't add gmail account?

### ISSUE THREAD

**Issue by joanysavignon** [nylas/N1#1053]
<img width="869" alt="screen shot 2016-01-16 at 9 51 53 pm" src="https://cloud.githubusercontent.com/assets/16739659/12375671/920e8bbc-bc9b-11e5-9f21-43fbbf807467.png">

**Comment by mbilker** [comment]
Have you contacted support@nylas.com as well?

**Comment by joanysavignon** [comment]
Yes, I did
