### ISSUE TITLE
OSX Keyboard Commands [] + [0], [] + [-] & [] + [+] don't work within Nylas

### ISSUE THREAD

**Issue by pkortge** [nylas/N1#1054]
Since upgrading to Version 0.3.43-b95f1f7 (0.3.43-b95f1f7) have random instances where the contents of the Nylas window is enlarged due to sudden mouse movements.

And the Apple Keyboard command for reducing Window content size back to normal [] + [0] doesn't work, and neither does [] + [-] (to reduce size of screen content) and [] + [+] (to enlarge size of screen content).

Am running OSX v10.11.4 Beta (15E27e).

**Comment by bengotow** [comment]
Hi @pkortge — thanks, could you send me a screenshot of what the UI looks like for you? There's a new feature in Mac OS X El Captain where the mouse cursor gets very large when you move it suddenly (so you can find it.) Maybe it has something to do with that?

**Comment by pkortge** [comment]
Hi @bengotow -

Have attached a screenshot of what occasionally happens when using Nylas - i.e. I get an "enlarged" view.

To rectify this in OSX you would use the keyboard command  [] + [0] to make the screen contents go back to normal size.

However, unlike other OSX apps, the OSX screen content resize keys [] + [0]. [] + [-] and [] + [+] don't work in Nylas :-(

It would also be great if OSX Contextual Keys - see [Contextual Menus](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/ContextualMenus.html) - which are accessed by "right-clicking" would work within Nylas to access applicable actions - like [Archive], [Move to Trash] etc. 

![20_01_2016__12_43_pm](https://cloud.githubusercontent.com/assets/2783565/12438893/cb8f1888-bf76-11e5-9609-f9e8f08f104c.png)

**Comment by Bizzi-Body** [comment]
I am also experiencing this issue.  The only way to resolve the zoomed state is to restart N1.  I do not believe I have accidentally pressed a keyboard combination and certainly not pressed CMD+0 or - or +

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
