### ISSUE TITLE
Moving Labels in Gmail doesn't remove old location

### ISSUE THREAD

**Issue by himmAllRight** [nylas/N1#1059]
In gmail I moved some labels to sublabels. In nylas, both the old locations and the new locations of the labels show up. When I try to delete the locations in nylas, I am informed that they cannot be deleted (probably because they are not there I am guessing).

I am running this under Fedora 23.

**Comment by bengotow** [comment]
Hi @himmAllRight — this definitely sounds like a sync-engine issue. We'll take a look. (cc @khamidou)

**Comment by khamidou** [comment]
Hi @himmAllRight,

We've released a fix for this issue (https://github.com/nylas/sync-engine/commit/dd2fcc740c643a58c3fb0bda04a591b46f29d8ff) --- can you test again and tell me if it solved your problem?

regards,

Karim

**Comment by khamidou** [comment]
@himmAllRight --- can you currently reproduce the issue? If not I'll close this issue.

k
