### ISSUE TITLE
About UI translation

### ISSUE THREAD

**Issue by malsony** [nylas/N1#1060]
Hi I wonder if the UI can be localized? It will be great if the text strings can be translated into other languages and let the user change the preferred UI language. Thanks!

**Comment by everhopingandwaiting** [comment]
唉 ，无视你这个

**Comment by everhopingandwaiting** [comment]
this UI is so beautiful ,there is no need to add others！😍😍😍😍😍😍😍

**Comment by jstejada** [comment]
Hi @malsony , thanks for your suggestion. We are definitely looking into it. I'm going to merge into duplicate #24

**Comment by everhopingandwaiting** [comment]
@malsony   support++;
