### ISSUE TITLE
On mail account is frozen with mails from Dec 25

### ISSUE THREAD

**Issue by saneef** [nylas/N1#1061]
I have added three gmail accounts in N1. Out of it, one account doesn't show any new emails. I have one email in the inbox; it will be there even if I delete it. 

But, I'm able to send email from this problematic account.

**Comment by bengotow** [comment]
Hi @saneef — thanks for reporting this. Can you send an email to `support@nylas.com` and include the email address that you're having trouble with? We can follow up there and make sure it gets resolved.
