### ISSUE TITLE
adding a gmail account

### ISSUE THREAD

**Issue by Yomi0** [nylas/N1#1062]
I can't seem to add a gmail account to N1. 
Firefox will open and redirect me to a page asking if I want to allow N1 to access my google account. After allowing access, N1 just freezes and eventually throws up a window explaining that N1 isn't responding. 

Where could I find logs to try and get this issue solved? 

N1 Version: 0.3.43.r8.g74e21bc-1
OS: Arch Linux

**Comment by bengotow** [comment]
Hi @Yomi0 — this is unfortunately a known compatibility issue with Arch Linux, N1 and Firefox. Closing as duplicate of #620.

**Comment by Yomi0** [comment]
Ah, I'll take a look there.
