### ISSUE TITLE
Have an option to not select the first message in the list when selecting a folder

### ISSUE THREAD

**Issue by sentientredstripe** [nylas/N1#1066]
Bit long-winded with the title, sorry.  Currently when you select a folder (ie Inbox, Starred, School, etc.) the first message in the folder is automatically displayed.  I find this somewhat annoying and it would be great if there was an option to disable this behavior.

**Comment by bengotow** [comment]
Hey @sentientredstripe — thanks for filing this. I'll see if we can get this resolved in a future update.

**Comment by jstejada** [comment]
merging into #1461
