### ISSUE TITLE
xpc service failing to initialize

### ISSUE THREAD

**Issue by samdeane** [nylas/N1#1073]
launchd is trying and failing to spawn a Nylas daemon every couple of seconds. This is happening whether or not Nylas itself is running.

```
19/01/2016 18:44:50.556 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt[98611]) Service could not initialize: 15C50: xpcproxy + 12644 [1472][13E77DA5-3602-31BF-B074-49D4EE27E9D8]: 0xd
19/01/2016 18:44:50.556 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
19/01/2016 18:44:52.562 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt[98612]) Service could not initialize: 15C50: xpcproxy + 12644 [1472][13E77DA5-3602-31BF-B074-49D4EE27E9D8]: 0xd
19/01/2016 18:44:52.562 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
19/01/2016 18:44:54.571 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt[98613]) Service could not initialize: 15C50: xpcproxy + 12644 [1472][13E77DA5-3602-31BF-B074-49D4EE27E9D8]: 0xd
19/01/2016 18:44:54.571 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
19/01/2016 18:44:56.579 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt[98614]) Service could not initialize: 15C50: xpcproxy + 12644 [1472][13E77DA5-3602-31BF-B074-49D4EE27E9D8]: 0xd
19/01/2016 18:44:56.579 com.apple.xpc.launchd[1]: (com.nylas.nylas-mail.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
```

**Comment by bengotow** [comment]
Hey @samdeane — hmm, this is strange... ShipIt is the process created by https://github.com/Squirrel/Squirrel.Mac, the update framework we use. It looks like it tried to check for updates or install an update, and is now in some sort of infinite loop. (We definitely only check for updates when you run the app.)

Can you see if there are any "User Diagnostic Reports" in Console.app for `com.nylas.nylas-mail.ShipIt` or `ShipIt`? There might be more log information in there.

**Comment by samdeane** [comment]
Nothing there I'm afraid.

I managed to stop it using launchctl, and it hasn't come back after restarting / re-launching Nylas, but I'll keep an eye on it.

Where does the process normally live? Since it seemed to be out-living Nylas, I was looking for it in /Library/LaunchDaemons, but I guess it's probably an XPC service buried inside the app bundle, as it didn't seem to be there.

**Comment by samdeane** [comment]
Ah, I spoke too soon. I relaunched Nylas and it's back. 

There was an update available, which I've clicked on to install. I don't think that the xpc failure started until I'd done that, but I may be wrong. I'll try to wait next time, and see if it's searching for the update or installing it that triggers the problem.

As you can see, launchd is continuing to try to relaunch something, even though Nylas isn't running:

![screen shot 2016-01-20 at 11 17 14](https://cloud.githubusercontent.com/assets/206306/12447310/2f40373c-bf67-11e5-88ad-5dfb48d564dc.png)

**Comment by samdeane** [comment]
More information:

Quitting Nylas isn't enough to stop the problem, but logging out and in again is. In other words, it **doesn't** require a full system restart.

**Comment by samdeane** [comment]
I should also have said that I'm on version 0.3.29-1904c6f (0.3.29-1904c6f), and 10.11.2 (15C50).

**Comment by samdeane** [comment]
After re-logging in and re-launching Nylas, the problem starts again after a delay, with no other user interaction. It didn't need an update to be waiting (there isn't one, currently), and it therefore didn't require me to click "Install Now".

**Comment by samdeane** [comment]
Further update :)

What I said above isn't true. The problem does start on it's own, it just takes a little while.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
