### ISSUE TITLE
Mail rules should ignore trash folder (or at least have the option to…)

### ISSUE THREAD

**Issue by danielbayley** [nylas/N1#1075]
I can’t delete (trash) anything that’s been moved to a folder according to a matching rule since it just fetches it from the trash and puts it straight back into the folder again.

**Comment by bengotow** [comment]
Ahh man this is a great one—it sounds like we're evaluating mail rules when messages / threads are modified as well as created. We should definitely fix this in the next release.

**Comment by danielbayley** [comment]
Maybe they should ignore sent items by default also…

**Comment by bengotow** [comment]
Merging into #1076, same underlying sync-engine issue.
