### ISSUE TITLE
Updating the Account Label field causes the newsletter field to reload

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#1079]
**Version**: 0.3.43-master
**OS**: Arch Linux 2016.01.19

**Actual Result:** When changing the value of the `Account Label` for a mail account in `Preferences`, the checkbox next to the `Notify me...` shows a loading circle for a split second.

**Expected Result:** The newsletter checkbox does not change when editing the `Account Label`.

**Comment by jstejada** [comment]
this has been fixed with the latest merge from `unified-inbox` branch. reopen if necessary
