### ISSUE TITLE
Archive action does not work with Gmail

### ISSUE THREAD

**Issue by jaimeiniesta** [nylas/N1#108]
When I archive a message on N1, it disappears from the N1 inbox but is not archived in Gmail. Shouldn't it sync in Gmail and be archived as well there?

**Comment by bmathews** [comment]
Seems to be working for me.

**Comment by jaimeiniesta** [comment]
Weird. It keeps failing for me. All that it says is "changed labels for..." but the message is still on the Gmail inbox.

**Comment by bengotow** [comment]
Hi @jaimeiniesta — thanks for reporting this issue. Could you open the "Activity Window" in N1 by choosing `Developer > Open Activity Window` from the menu? Click on the button that says "Queue Length" and see if there are any failed tasks there, or requests under the "Requests" tab. That'll help narrow down the issue.

**Comment by jaimeiniesta** [comment]
There is a failed request, with status 401. It appears there every time I launch N1:

```
curl -X GET  "https://edgehill.nylas.com/metadata/(...)/"
```

**Comment by jaimeiniesta** [comment]
If I re-run the requests, it says:

```
$ /Users/jaime/.nylas/curl.command ; exit;
Invalid username/password combinationlogout
```

**Comment by bengotow** [comment]
Hey @jaimeiniesta — that request is a red herring, unfortunately (though I'm looking into it now and will fix it.) Could you send a quick email to `support@nylas.com` with the email address you're having trouble with? We can see if we've been running into any issues syncing back with Gmail on our end.

**Comment by mbilker** [comment]
I got 403 errors down the board, but I realized it was because I changed my Gmail accounts security settings, wiping all application authorizations from my account.

**Comment by jaimeiniesta** [comment]
It's working fine today, maybe the servers were overloaded the past days. Gotta try it with my own sync-engine instance.

Closing this, thanks for the hard work!
