### ISSUE TITLE
Can't click 'cc' on linux on first try

### ISSUE THREAD

**Issue by perry-mitchell** [nylas/N1#1080]
When writing a new email, I am able to enter an address (or many) in the To field, but when I click the 'CC' button, it never activates and always goes to Subject.

I am on Ubuntu 14.04 64bit.

![n1_cc_click](https://cloud.githubusercontent.com/assets/3869469/12531029/893ca826-c1f9-11e5-8965-86b580a10a55.gif)

**Comment by Yerlix** [comment]
I have the same problem on Mac (OSX 10.10.5)
When clicking "cc" the cursor goes to the subject field. Then I need to re-select the "To" field and then I can add "cc" recipients.

**Comment by perry-mitchell** [comment]
This seems to work on 0.4.9.

**Comment by bengotow** [comment]
Thanks for closing this!

**Comment by Yerlix** [comment]
I still have this issue, even after updating to 0.4.9.
I'm using OSX 10.10.5
