### ISSUE TITLE
Number of unread messages in accounts drop-down list

### ISSUE THREAD

**Issue by crxdelsol** [nylas/N1#1081]
When I click the down-arrow next to my current mailbox to view a list of mailboxes, it would be handy to show the number of unread messages per mailbox there to see directly which mailbox has unread messages.

I sometimes have to click through 4 mailboxes to notice there is no mail.

**Comment by bengotow** [comment]
Hey @crxdelsol — thanks for filing this! We'll be fixing this with a new unified inbox feature launching next month. It's still in development on the `unified-inbox` branch, but the sidebar will look something more like this:

![pasted image at 2016_01_19 02_58 pm](https://cloud.githubusercontent.com/assets/1037212/12458950/1a07fe0a-bf61-11e5-8090-f071d7ce3129.png)

Stay tuned!

**Comment by bengotow** [comment]
(Going to go ahead and close this since it'll be resolved soon)

**Comment by crxdelsol** [comment]
The unified inbox looks great! Can't wait!
You're app is growing in popularity, great to see how everything comes together to be the best mail app.
