### ISSUE TITLE
Blockquote missing from message body

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1084]
A blockquoted block in a message is missing.

N1 Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)
OS X El Capitan 10.11.2 (15C50)

Gmail:

<img width="385" alt="a" src="https://cloud.githubusercontent.com/assets/27594/12453930/6ed5a2aa-bf63-11e5-9767-246ad314d12e.png">

N1:

<img width="326" alt="screenshot_1_20_16__11_03_am" src="https://cloud.githubusercontent.com/assets/27594/12454439/840e79e2-bf65-11e5-8c7c-8ebc3d755518.png">

**Comment by emorikawa** [comment]
Hey @markbao! Yeah, that looks like an issue with our quoted text engine. Could you do me a favor and forward me that email (with garbage text is fine) so I can take a look at the HTML structure of it?

**Comment by markbao** [comment]
@emorikawa sure thing, evan at nylas?

**Comment by emorikawa** [comment]
Yep. Thanks!
