### ISSUE TITLE
Syncing extremely slow during occasional use

### ISSUE THREAD

**Issue by willwhitney** [nylas/N1#1085]
Today is the first time I've opened N1 in a month or so, and it's been syncing for a good 10-15 minutes. Only a couple of emails that are actually currently in my inbox have loaded, and dozens that are not are still there.

I figure this might be something you haven't noticed, as most people who post issues are frequent users. However, this is a serious issue. It means that I and other potential users of your product who check in occasionally will have a consistently bad experience.

By contrast, I installed CloudMagic just now and it was ready to go in seconds.

All emails actually in my inbox right now are from this month, but here's the date column of my inbox in N1:

<img width="112" alt="screenshot 2016-01-20 12 27 30" src="https://cloud.githubusercontent.com/assets/597829/12457229/6d905da0-bf71-11e5-91a6-80654c20ad78.png">

**Comment by willwhitney** [comment]
Actually all of those are now still there after a complete sync. This is incorrect.

**Comment by bengotow** [comment]
Hey @willwhitney — thanks for reaching out. This is really interesting. Can you reach out to support@nylas.com and include the email address you're having trouble with, along with the screenshot above? That should help our platform team dig deeper into the issue.

**Comment by grinich** [comment]
@willwhitney how long was the delay? 

For accounts that are inactive for > 1 month, we pause the actual sync engine until N1 reconnects, so it often needs to "catch up". I'd like to investigate how slow this actually was and ways we can improve the experience

**Comment by willwhitney** [comment]
30-45 minutes, maybe longer.
