### ISSUE TITLE
Quick preview for attachments

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#1086]
Plus a keyboard shortcut (like spacebar).

**Comment by crxdelsol** [comment]
+1 for 'spacebar' to use the native QuickLook functionality of OSX.

**Comment by codisms** [comment]
+1

**Comment by ianawilson** [comment]
+1 I am always wishing I could do this with PDFs

**Comment by mistryrakesh** [comment]
+1

**Comment by VictorCano** [comment]
+1 !

**Comment by davidpmccormick** [comment]
+1, yo1

**Comment by dannysmith** [comment]
+1 for this.

**Comment by porkchop999** [comment]
+1

**Comment by Sendarg** [comment]
+!

**Comment by jackiehluo** [comment]
Another request in #2680!

**Comment by hisamentri** [comment]
+1 for quick repviews of any kind of attachments.

**Comment by bengotow** [comment]
Another request via support today:  "Would it be possible to show like a small preview (just like Gmail) or let me open it in preview-mode?"

**Comment by onlinelaser** [comment]
+1 for spacebar quicklook on the OSX client, good attachment handling is so important!

**Comment by jstejada** [comment]
hi folks, we've released this (only available in macOS) in version 0.4.204!

**Comment by nrzonline** [comment]
The inline images are resized to fit the width of the message column, which us usually too small for the image to be readable. Any possibility to click an inline image to show on original size as popup/zoom (or preference option to show images in actual size by default)?
