### ISSUE TITLE
BUG: No emails appearing

### ISSUE THREAD

**Issue by benrulz** [nylas/N1#1090]
Version: 0.3.32-b11131d
OS: Mac
Account type: Gmail

@jstejada I've never done log files before. Hope this is it:
![screen shot 2016-01-18 at 7 40 38 pm](https://cloud.githubusercontent.com/assets/10630365/12393414/7c8164dc-be1b-11e5-9dd6-11245345dc82.png)

@grinich: 
Step 1: Open mail app.
Step 2: Nothing loads.

**Comment by Wittionary** [comment]
If you change a label on an email, does the label stick or immediately remove/add itself back?

**Comment by mbilker** [comment]
Thanks for the report. This is very similar to #863.

To fix this:
1. Close N1
2. Remove `~/.nylas/edgehill.db*`
3. Upgrade to 0.3.43
4. Relaunch N1 and wait for everything to resync

If you have any mail rules, you will need to readd them as they are stored in `~/.nylas/edgehill.db`. Did you run out of space while running N1?
