### ISSUE TITLE
BUG: Two-factor authentication breaks N1

### ISSUE THREAD

**Issue by Wittionary** [nylas/N1#1092]
#### Symptoms
* can't take actions on emails (e.g. clicking trash can icon removes the email for a moment but then it pops back up)
* no new emails

_It was a couple days before I figured out that this was because I turned on 2FA._ :scream:

#### What I expected
* persistent error message saying my account cannot be synced or authentication has been lost
* link to re-authorize

#### What I'm experiencing
* even after removing and re-adding my gmail account, N1 behaves the same
* actions taken on emails immediately revert back
* it will say it's syncing in the lower, left-hand corner, but I receive none of the new emails that I see in my GMail web client

**Comment by jstejada** [comment]
hey @Wittionary , thanks for reporting this. Can you send an email to support@nylas.com and include the email address that you're having trouble with? We can follow up there and make sure it gets resolved.
