### ISSUE TITLE
Links fail to open with exception thrown

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#1093]
**Version:** 0.3.46-master
**OS:** Arch Linux 2016.01.21

**Description:**
Clicking on a link does nothing from the message view. Right clicking the link and clicking `Open Link` causes an exception to be thrown and the DevTools Javascript console pops up with the exception shown.

**Expected Result:**
Link opens in my web browser

**Actual Result:**
Link does not open with left click or right click to open

![2016-01-21-11-37-42_1243x40](https://cloud.githubusercontent.com/assets/1266541/12487047/74b4ddc8-c033-11e5-85fc-ba72f326157e.png)

This is caused by https://github.com/nylas/N1/commit/11c0af653df66311e6b880a99d5958763837197e#diff-88390509a68038d3318c999d65075e26R153

**Comment by emorikawa** [comment]
@mbilker, good catch. Fixing now

**Comment by emorikawa** [comment]
Fixed in c8305cc

**Comment by bengotow** [comment]
:+1: nice catch @mbilker !

**Comment by jstejada** [comment]
:candy: !
