### ISSUE TITLE
Integration with Google Chat (GChat) or other IM / Messenger services

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#1094]

**Comment by grinich** [comment]
![glasses-off-omg](https://cloud.githubusercontent.com/assets/92417/12490488/b44a9fe4-c02a-11e5-8bc6-594514cdac6d.gif)

**Comment by bherila** [comment]
IMHO, IM should be a separate application :)

**Comment by bengotow** [comment]
Moving to https://trello.com/c/QqRn3sLR/63-integration-with-google-chat-gchat-or-other-im-messenger-services
