### ISSUE TITLE
Emails with different to: header do not show up

### ISSUE THREAD

**Issue by rdig** [nylas/N1#1095]
Hi there.

As the title says, I kind of have an edge case. 

I combined multiple accounts into one, at the server level, and ended up with some email in the inbox that have different headers for the "to:" address than the know owning account.

Now the only emails that are being shown are the ones that have the same header as the current account.

I've tested this with multiple email clients, to see how each handles them - not shown (N1, Cloudmagic), shown (Thunderbird, Geary, Roundcube)

I don't really know if this is a bug, or quite possibly a feature. (*It would make sense from some perspective as a security feature*)

Version: 0.3.43-b95f1f7
Platform: Linux (*Also tried on a Windows machine with the same results*)
Account type: IMAP

**Comment by mbilker** [comment]
Thanks for the report @rdig. This seems like an edge case for IMAP accounts on the Sync Engine. I know aliases are a thing, but I do not believe they cover incoming mail to the Sync Engine.

Paging @bengotow and @grinich for more information.

**Comment by grinich** [comment]
@rdig can you tell us more details about your IMAP server configuration?

**Comment by rdig** [comment]
It started with a [Mail-in-a-box](https://github.com/mail-in-a-box/mailinabox)
standard config that I extended further.

  

It's running Postfix SMTP / Dovecot for IMAP on a SSL connection, and
everything is running on an Ubuntu 14.04 virtual machine.

  

I don't think the server is at fault here, but more the way I merged the email
accounts:

  

Basically copy-paste. I rsynced the email files into a new account's folder
than fixed the permissions.

  

If you need anything more specific please let me know.

  

> On Jan 23 2016, at 10:38 pm, Michael Grinich
&lt;notifications@github.com&gt; wrote:  

>

> [@rdig](https://github.com/rdig) can you tell us more details about your
IMAP server configuration?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1095#issuecomment-174219399).![](https://github.com/notifications/bea
con/ABI1BiHTOibkmYH02apw5YFHHGitNQJ9ks5pc9w-gaJpZM4HJ0qN.gif)

**Comment by grinich** [comment]
It might be this copy action didn't register these new messages with UIDs and trigger IDLE, or similar. Please create a new bug if you can have steps to reproduce. Thanks !
