### ISSUE TITLE
Mark as Unread conflicting with Split view.

### ISSUE THREAD

**Issue by louim** [nylas/N1#110]
With using the split view layout, clicking on the "Mark as Unread" will only toggle for a fraction of second the "Unread" on the message, since the message is in view and it will be considered read immediately.

**Comment by grinich** [comment]
known bug-- working on it

**Comment by ecki** [comment]
have the same problem, it works when selecting multiple messages.

**Comment by gsouf** [comment]
:+1:

**Comment by gabrielso** [comment]
:heavy_plus_sign:

**Comment by bengotow** [comment]
This has been fixed in ede7eda3c43dc0d2044c381d8de7dac42c6d3ca3 and will be included in the next release. Enjoy!
