### ISSUE TITLE
Transparent window on launch

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1100]
A user is reporting that upon launching N1 for the first time, the main setup window is shown as transparent. Here's a screenshot of the issue.

![screen 20shot 202016-01-21 20at 208 25 03 20pm](https://cloud.githubusercontent.com/assets/92417/12501071/19e08272-c06e-11e5-99c8-9c832aff6985.png)

**Comment by bengotow** [comment]
Closing since we haven't been able to reproduce and a lot has changed since this was filed.
