### ISSUE TITLE
Icons on toolbar not showing.

### ISSUE THREAD

**Issue by herrowna** [nylas/N1#1101]
This is happening on Ubuntu 14.04 LTS.
![76ad2a07-ab41-4732-aa04-97cc0a0f5aa1](https://cloud.githubusercontent.com/assets/6374909/12505756/a5117944-c124-11e5-912a-0c648ef8be0d.png)

**Comment by jstejada** [comment]
hey @herrowna , this is possibly related to #805 #732 . Can you try that and see if it helps?

**Comment by bengotow** [comment]
Closing as dup of #732.
