### ISSUE TITLE
microsoft exchange: allow to use ip address in the "exchange server" input

### ISSUE THREAD

**Issue by mnewmedia** [nylas/N1#1103]
Looked so promising, but sadly it's not working at all for me.

In Apple Mail and N1 I could enter all the same configurations but only the "Exchange Server (Optional)" Field doesn't accept an IP-Adress.

**Comment by bengotow** [comment]
This has been fixed in 306440dd3836ed265c510f2bde844ee1f9028d94 and will be released very soon. Stay tuned!
