### ISSUE TITLE
emails with <img ...> in footer will not send

### ISSUE THREAD

**Issue by jacob-ogre** [nylas/N1#1104]
N1 Version 0.3.45-3b5880e
OSX 10.11.1
Exchange (365) account

Emails will not send if I tryeither a reply or a new message that has my standard work footer; I get the "Sending email..." notification, but after a few minutes it errors out as a connection lost.  That footer includes a couple of image tags, e.g., 
```
<td rowspan="2" style="width: 88px; padding: 0in; height: 16.2pt;" width="25%">
  <span><img alt="http://www.XXXXXXXX.org/signatures/XXXXXX.gif" height="49" id="#######"  src="http://www.XXXXXXXX.org/signatures/XXXXXX.gif" width="58" />&nbsp;</span>
</td>
```
Removing this and the other `<img>` tag allows the email to send without any problems.  It would be nice to include the organization's logo in my messages.  Perhaps related to #839 (but the errant "/" is not present here...)?

**Comment by bengotow** [comment]
Hi @jacob-ogre — wow, this is really interesting. We don't do much HTML validation before sending, so it /should/ be possible to send just about anything. Could you do me a favor and email me the full raw HTML of your signature as a text file to ben@nylas.com? I think the issue might be some sort of illegal character in the HTML that can't be encoded and causes the message to be rejected by the mailserver (or something like that...)

**Comment by jacob-ogre** [comment]
Thanks @bengotow.  I emailed the HTML of the signature a few days ago to the provided address; did it make it to you? If so, did you happen to spot anything odd?

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
