### ISSUE TITLE
Feature Request: Launch in tray

### ISSUE THREAD

**Issue by marko-lazic** [nylas/N1#1105]
How do i startup application so that it show up in tray but not open as new window?

command `/usr/share/nylas/nylas %U` opens new window.

**Comment by bengotow** [comment]
Hi @marko-lazic — there's no way to do this currently. Do you know of another mail client that does this on Linux? (And if so, how does it usually work?)

**Comment by marko-lazic** [comment]
Well i guess that you need to have separate binary that is only for tray, or to have argument that when it is passed to command line only runs app and show up in try but doesn't open window.

**Comment by tgalopin** [comment]
I think this has just been fixed: https://github.com/nylas/N1/issues/832#event-530277234

**Comment by marko-lazic** [comment]
How do you know?

**Comment by tgalopin** [comment]
I checked the commit and it includes a `--background` option. However it is still only in github, there is no build with it

**Comment by jstejada** [comment]
this is indeed added with https://github.com/nylas/N1/commit/67edcc836fbf3629b449bf14041e6d433ca3b89d, so I'm closing this. We will release a new update soon! Stay tuned!

**Comment by parsedarweb** [comment]
Where's the option to activate in order to put the Nylas into tray on startup time?!

Distro: Archlinux
Desktop: KDE Plasma
