### ISSUE TITLE
Feature request: selectively (un)subscribe particular folders on server

### ISSUE THREAD

**Issue by minyang** [nylas/N1#1106]
Thanks for developing a great product, especially on Linux!  I have been using Thunderbird for many years on Linux, but it recently became a bit unstable.  Nylas has been working great so far!  Hope it will be THE email client for Linux (and possibly for Mac as well).

Just a couple suggestions to improve usability:

- Ability to specify the default archive folder (e.g., some people may desire to archive emails by year, instead of just "archives" folder).
- Ability to selectively (un)subscribe particular folders on server
- Ability to select a set of emails to perform actions (e.g., mark as unread, mark as read, move to folder)

**Comment by bengotow** [comment]
Hey @minyang — I think the first one is a dup of #978, and you should be able to select many threads by shift-selecting or command/ctrl selecting (though there is #388, which might be the issue?). I'm going to rename this issue to just address the second one. Cheers!

**Comment by jackiehluo** [comment]
Closing this issue because it's not in the scope of our project—but of course you're always free to build it on your own!
