### ISSUE TITLE
Feature request: several usernames per ONE account

### ISSUE THREAD

**Issue by scani** [nylas/N1#1107]
Great job so far, dear Nylas N1 team!
This is so important!
Please make it possible to create several usernames in one account so I can choose from them the one I want to appear in the 'Sender' box. I correspond in several languages and I need to be able to choose how and in what language my name is being displayed!
Big thanks for implementing new email rules.
Stasia

**Comment by grinich** [comment]
This is already implemented as "aliases". Check them out under the preferences!

**Comment by scani** [comment]
Awesome.
