### ISSUE TITLE
Drag file to dock icon (or menu bar icon) to open new message with file as attachment

### ISSUE THREAD

**Issue by messengerinternational** [nylas/N1#1108]
Similar to the behavior of Apple's default mail client, but it would be great to be able to drag a file(s) from Finder to the Dock icon (or menu bar icon) and have a new message box open up with the dragged file(s) attached to the message.

**Comment by bengotow** [comment]
Hmm that's cool—I never noticed Mail.app did that. We'll see if we can get this in to a future release.

**Comment by bengotow** [comment]
I'm tagging this as a good starter issue. On the Mac, I think we need to implement code at https://github.com/nylas/N1/blob/unified-inbox/src/browser/application.coffee#L333 which would take the file URL and pass it into the app, similar to how we pass in mailto links (https://github.com/nylas/N1/blob/unified-inbox/src/browser/application.coffee#L501)

**Comment by bengotow** [comment]
This has been fixed in b515a5e0e26f96e42bc3efd6ebd948f029f3f5de

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!

**Comment by messengerinternational** [comment]
@bengotow AWESOME! works flawlessly for me. Thanks for adding this into Nylas as this is a major part of my workflow.
