### ISSUE TITLE
Cursor disappears when using Shift+Return in Editor

### ISSUE THREAD

**Issue by natarius** [nylas/N1#1109]
When I hit Shift+Return in the editor to get a soft return (instead of a hard return) the cursor disappears.

Its seems that the editor form looses focus. When I click back in the cursor shows up again. 

Happeneing on OSX

**Comment by bengotow** [comment]
Hey @natarius — thanks for reporting this, I'll see if we can get this resolved in the next update. (@emorikawa is this a quick fix?)

**Comment by mihaisrbn** [comment]
Hey @bengotow - any updates? I am using shift+return a lot when writing emails and this bug is really annoying :(

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
