### ISSUE TITLE
N1 email verification is broken

### ISSUE THREAD

**Issue by ryanpcmcquen** [nylas/N1#111]
I am unable to send an email to a `.dental` url because N1 thinks it is invalid.

```
Cannot Send
XXXXX@XXXXXXXXX.dental is not a valid email address - please remove or edit it before sending.
```

**Comment by bmathews** [comment]
The regex that triggers this is here: 
https://github.com/nylas/N1/blob/7787e0bc4b4da40e1d31a5d6b4ef6a8c73bd5132/src/regexp-utils.coffee#L14

```new RegExp(/([a-z.A-Z0-9%#_~$&*+;=:-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/g)```

The issue is that `{2,4}`. It should be replaced with `{2,}` or `{2,63}`

This link describes it: http://www.regular-expressions.info/email.html
