### ISSUE TITLE
Couldn't reach API

### ISSUE THREAD

**Issue by alvr** [nylas/N1#1111]
Hello, I installed N1 for the first time and after the welcome message I get an error:

> Sorry, we could not reach the Nylas API. Please try again, or email us if you continue to have trouble. (undefined)

I disabled my firewall but nothing and after a few tries I get the same window without any message.

Using Windows 8.1 x64.

**Comment by mbilker** [comment]
Please see http://status.nylas.com/incidents/fhbmkfljkcmc
