### ISSUE TITLE
Desktop Icon Appears After Each Upgrade

### ISSUE THREAD

**Issue by TheConnMan** [nylas/N1#1112]
On initial install I selected no desktop icon and that worked correctly. Since then on every update N1 adds it's icon to my Windows desktop. I of course delete it and go through the same process next update.

Not a huge deal, more of an FYI.

Windows 10
Nylas ~0.3.29-0.3.45

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
