### ISSUE TITLE
Feature Request: Add option to reply without previous

### ISSUE THREAD

**Issue by ThePsionic** [nylas/N1#1115]
Currently, when for instance replying to GitHub e-mails, the previous thread automatically gets added to the end of the e-mail, creating quite a mess on GitHub's web view. Previous replies in a thread are not always wanted, and it would be nice to have an option to delete them in one click instead of having to remove the blockquoted text that appears when clicking the "Show previous" button.

**Comment by zlatkobijelic** [comment]
+1

**Comment by bengotow** [comment]
Closing as dup of #2323
