### ISSUE TITLE
Menu bar doesn't obey theme colours

### ISSUE THREAD

**Issue by Bugsbane** [nylas/N1#1119]
When the dark theme is selected, everything goes dark with light writing... except for the menu bar, which stays the reverse colours of everything else.

This looks very incongruous and distracting.

Expected:
The menu bar uses the same colours as the theme.

**Comment by mbilker** [comment]
Could you provide a screenshot?

**Comment by Bugsbane** [comment]
Actually, I just figured this out, although I'm not sure if it's something you can do anything about. The issue came down to that I'm using the KDE Plasma desktop and the default Gnome theme was set to Orion, which seems to be a light coloured theme. Thus all of Nylas, except for the menu bar, was getting it's theme from Nylas' settings, but the menu bar gets it's colour settings from Gnome.

Here's how it looked with the Gnome Orion theme:
![nylas-screenshot](https://cloud.githubusercontent.com/assets/401733/12535331/1f30fc08-c24d-11e5-8036-4f07ffc0b0ff.png)

,,,and whe I changed the default Gnome theme to Oxygen-GTK:
![nylas-oxygen-gtk](https://cloud.githubusercontent.com/assets/401733/12535341/844a7da8-c24d-11e5-92b9-2ffd666e1d52.png)

Is it possible for Nylas to take over theming the menu bar at all? While I understand this is not really your issue at a technical level, from a user experience perspective it still comes across as a bug when you choose a dark theme in an app, and parts of the app stay on a light theme..

**Comment by mbilker** [comment]
I am glad you figured this out. Unfortunately, Xorg window decorating is done by the window manager. The GTK themes are usually user selected, and N1 follows this convention.

In my opinion, I like this standard because it means a theme is applied across many applications consistently.
