### ISSUE TITLE
"Official" Download Location

### ISSUE THREAD

**Issue by adidalal** [nylas/N1#1124]
Hey there, I'm one of the maintainers of [Homebrew Cask](https://github.com/caskroom/homebrew-cask) and we have a [nylas-n1 Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/nylas-n1.rb) to make installing as easy as `brew cask install nylas-n1`

Just wanted to know which link was preferred:
`https://edgehill.s3-us-west-2.amazonaws.com/0.3.45-3b5880e/darwin/x64/N1.dmg` (from the site)
or
`https://github.com/nylas/N1/releases/download/0.3.45/N1-0.3.45.dmg` (from GitHub)

We prefer the one which is updated, but the GitHub URL allows us to detect updates (via `appcast`). If you have a canonical appcast URL, we can add that in instead.

Thanks.

**Comment by grinich** [comment]
We don't actively use GitHub for releases, so you should use the S3 link. 

You can also link to https://edgehill.nylas.com/download?platform=darwin which will 302 to the latest version. We may change this in the future, though.

**Comment by adidalal** [comment]
Thanks, updated in https://github.com/caskroom/homebrew-cask/pull/17448

This will still rely on someone noticing an update and submitting a PR, as  I don't see an active appcast URL (changelog, RSS feed, Sparkle appcast, etc) to detect updates, but is totally fine for the time being.

**Comment by grinich** [comment]
the app auto-updates so it's probably ok

**Comment by adidalal** [comment]
Ah, will add in an `auto_updates` flag, so we don't clobber an updated version with an older one by accident. Thanks for the fast response!
