### ISSUE TITLE
Gmail spam filter ignored

### ISSUE THREAD

**Issue by azariah001** [nylas/N1#1125]
I've logged into my Gmail account and... the client is totally ignoring the folders in the gmail account. Primarily the spam folder but I presume all of the other filters are being ignored as well. It's like N1 is trying to be a stand alone server like Microsoft's Outlook program used to try to be. :|

So what I've got is a totally unusable list of emails with all the cruft from the spam folder thrown in with my standard emails. I know the client has it's own spam system but..... If the server has a spam filter it should be respected and used. Really not sure how this is happening as every other email client I've used on Android, Linux, Windows doesn't have this problem but.... :/ it is a beta so eh. Room for improvement. :) Please fix. Otherwise it's a great program so far.

**Comment by mbilker** [comment]
Hey @azariah001. From my experience, N1 does not ignore the Gmail spam filter. All of my spam email goes to the Spam folder. Where are these emails showing up in N1? Do you use a mail filter in N1?

**Comment by azariah001** [comment]
Spam folder in N1
![screenshot 2016-01-24 14 24 56](https://cloud.githubusercontent.com/assets/5634872/12534495/91efa20a-c2af-11e5-9a18-d4ba62a90aae.png)

Same folder in Gmail.... (ugh disgusting)
![screenshot 2016-01-24 14 26 05](https://cloud.githubusercontent.com/assets/5634872/12534497/96ccaa02-c2af-11e5-9ffd-58db0c1206ad.png)

And when I go to my inbox in N1 I can see obvious Spam mixed in with my email. I don't expect things like the social filter to transfer over but.... the auto Spam filter is obviously not working the way N1 assumes it should. :|

**Comment by grinich** [comment]
@azariah001 is this still the case for you? I can see that we were still syncing your mailbox (see screenshot) and we sync the spam folder last.

![image](https://cloud.githubusercontent.com/assets/92417/12566104/cb5e710c-c36c-11e5-8c5f-6ea3f0aeb2e4.png)

**Comment by azariah001** [comment]
Well how much of my email account are you guys syncing and where is it syncing too that it's taking so long?! Again I've used quite a few email apps over the years and I've never had the sync take more than a few seconds to a couple of minutes because they only ever fetch maybe the last 20 odd emails at a time and then get the other stuff on an as needed basis.

I've had it open for a few minutes now and I still don't have the last few days of emails since I last opened it..... That and that syncing mailbox thing doesn't look like it's  properly animating on my system at all it's just a static cog sooooo yeah I'd ignored it as an unimplemented status thing.

Meh I'm gonna remove the account and re-add it. See what happens.

**Comment by grinich** [comment]
ok i'm going to reopen and we'll look into it more

**Comment by mbilker** [comment]
Should this be renamed to something that makes more sense?

**Comment by azariah001** [comment]
Ok that's bizzar just relogged in and everything was there. No waiting no messing around with syncing...... Bleh apparently I found a one in x glitch. Sorry guys. Appears to be working just fine now.

**Comment by azariah001** [comment]
Actually when I re-logged in the only permission it wanted was offline access like it missed it when I first authorised the account.... maybe that was causing the problem??? I really don't know.

I did some Android dev for UNI last year and I'm fully aware of how flaky and abstract the Google API's are so might just have one of those glitches holding up the works. :( Sorry about wasting your time.

**Comment by grinich** [comment]
the "offline" permission is super confusing, but pretty much it just means that you already authorized the app and it just needs a new access token.

**Comment by azariah001** [comment]
Lols sounds about right. I was using the fitness API's and it needed the location permission to access the distance walked as opposed to just the steps (both stats provided by the API by Google) but I had to basically tell the user that I was going to use their GPS location even though I was just accessing an inbuilt interpretation of the step count..... yeah.....

Then they update the API without updating the documentation and you're trying to use documentation that everyone is saying hasn't worked for 6 months... You have my sympathy and respect for getting this working. :+1:

**Comment by grinich** [comment]
> Then they update the API without updating the documentation and you're trying to use documentation that everyone is saying hasn't worked for 6 months 

lol that is pretty much the story of building the IMAP sync engine :stuck_out_tongue:

**Comment by petersaints** [comment]
I have the same problem. I just did a fresh install of Nylas N1 (I'm a new user trying it out), however I just can't read any messaged that are on the Spam folder. It's always empty.

I also tried removing and adding the account again as @azariah001 suggested butI'm still unable to access the Spam folder.
