### ISSUE TITLE
Render mails with the servo layout engine ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [nylas/N1#1126]
The servo layout engine is the successor of gecko, it will be 50X more Faster for rendering. It is not stable currently for complex web page but I think that for mails it could be. 
This will give a huuge jump in perf. And thunderbird will probably do the same move. It is also far more secure and efficient. And it can be embedded with the chromium embedded framework. 

https://github.com/servo/servo

**Comment by grinich** [comment]
N1 is entirely built on the Electron projects, which uses Chromium/Blink and NodeJS. We'll consider switching when Servo is released and demonstrably faster than our current stack. Thanks!
