### ISSUE TITLE
No way to select all the threads

### ISSUE THREAD

**Issue by lokesh1729** [nylas/N1#1127]
Hi,

I want to select all the threads, I found select all in Edit, but I can't with it. I tried shift + Down Arrow Key... which selects the below thread, but I need to press down key for infinite times to select all threads.Help me out with this. OS Linux Mint 17.2

Regards,
Lokesh Sanapalli.

**Comment by jstejada** [comment]
Hi @lokesh1729 , thanks for reporting this. I'm merging into duplicate #886
