### ISSUE TITLE
Spec Suite failures for nylas N1

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1129]
I ran N1 spec about 5 times and these two tests failed every single time. There are few that are transient failures but these are consistent. What information would you need to diagnose it? 

![image](https://cloud.githubusercontent.com/assets/2344626/12540952/e45da1da-c2dd-11e5-964f-6bd620a27dc9.png)

**Comment by mbilker** [comment]
These are uncommon errors, but expected on a desktop platform.

One error is about window size of the spec testing window. Do you run a window manager that forces the sizing of windows?

The other error is not as likely to appear, but it is failing on a XHR request to `nylas://account-sidebar/package.json`. I have seen this error appear in spec tests run from my laptop, so I do not find them surprising when running in the GUI spec test mode.

**Comment by bashok001** [comment]
@mbilker, Please feel free to close the issue if you think that both of them are expected.

**Comment by mbilker** [comment]
This error is important. It does not appear in CI test runs, but it does appear even when running the tests on my personal computer.

![2016-01-25-09-56-25_431x242](https://cloud.githubusercontent.com/assets/1266541/12554349/030a8d3e-c34a-11e5-9d15-0810369ef942.png)

**Comment by bengotow** [comment]
Hey folks—In that first error, it looks like your window manager is causing the test to fail by making the spec window fullscreen rather than 400px high.

That second error is definitely interesting. We should look at how that test is structured and see if anything could be conflicting. Maybe it doesn't work if you have another copy of N1 running? Or it could be based on relative file paths (to a package) being correct, and they're different when you run it this way?

**Comment by bashok001** [comment]
@bengotow The spec is failing with `Gnome` window manager. It is not full screen per se. Anyway, it passed when I switched window manager to `i3`.

**Comment by mbilker** [comment]
Huh. My run failed running under `i3` with the error above.

**Comment by bashok001** [comment]
Sorry for the confusion, @mbilker. I was only referring to Resizing spec. Other one fails either way.

**Comment by bengotow** [comment]
Hey folks—hmm, interesting. Sounds like these are definitely platform-related. I'm going to go ahead and close this and we'll see if we can make our specs more resilient in the future!
