### ISSUE TITLE
Chinese input conflict

### ISSUE THREAD

**Issue by Voyga** [nylas/N1#1130]
![bug](https://cloud.githubusercontent.com/assets/9929523/12542330/da87321e-c35c-11e5-8ea9-dea5b15666a3.gif)

**Comment by mbilker** [comment]
This is a resurgence of #590

**Comment by emorikawa** [comment]
This was fixed by 71abd8b

The spellchecker extension was causing the composition event to be cancelled.

We want to treat composition events as atomic inputs. As a result, we now don't run extension events in the middle of composition events.
