### ISSUE TITLE
Unread state/missing sent e-mails

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#1131]
Since the latest version, I am having (even more) problems with e-mails being handled by N1. This is what I observe:

1. E-mails arriving in the inbox, I read and archive or leave them there. Other e-mail clients still show them in my inbox for days, unread (e.g. smartphone notifies me of new mail I had been handling days ago).
2. I create a new e-mail, send it, it even arrives at the recipient’s mailbox, but it does not show up in my own sent mail or archive. Neither on other e-mail clients. 
It appears first again when I get a reply, stuffed with my original mail (i.e. conversation is showing complete with all single interactions).

Has there been a change in the engine? Or a ghost, perhaps?

As usual: Using the latest version on Windows 10.

**Comment by enoversum** [comment]
Didn’t occur since then again, but today it is the very same. Sent e-mails not visible in N1 or other clients sent folder, e-mails still appear as unread in the inbox, even though I read and archived them with N1. 
Glitches in the engine? Last time around I really feared messages would not have been delivered at all.

**Comment by brooth** [comment]
Same issue. N1 v0.4.45-7637265 for Ubuntu (16.04). Sent messages folder is empty

**Comment by jgrizou** [comment]
Similar issue, but only for an OVH hosted e-mail. Sent e-mail via Nylas N1 are not stored on the server and I cannot see them anywhere. Yet, they show up in mail thread when someone reply. They must be somewhere..

So where are the e-mail stored? Is it possible to store them in a 'Sent Messages' folder on the server? (I tried with Mail on OSX and it stores sent messages automatically on the server for that particular e-mail and in a 'Sent Messages' folder )

But sent messages are stored correctly for all other accounts Gmail, Hotmail, and two other university address I use. Maybe the OVH server handles e-mail is a very basic/old/odd manner..N1 does not seem to know how to handle this. 

In the 'All accounts', there is a 'Sent Mail' tab, all my account are there except the OVH one. Which might explain the issue.

Similar thing with the 'Bin' folder that only shows 3 out of my 5 accounts. Resulting in no 'Move to Trash' button for the 2 other accounts. Quite annoying. 

In which way those account might differ? Any way to setup custom rules for: 1) What happen to sent e-mail (put them in this or that remote folder), and 2) what happen to e-mail after for 'Move to Trash' button (put them in this or that remote folder)?

**Comment by jackiehluo** [comment]
For these issues, want to email us at support@nylas.com? We can investigate them better that way!
