### ISSUE TITLE
[Gmail] Messages with spam or trash should be only shown when viewing their specific folder, and hidden otherwise

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1135]
N1 needs to handle Spam and Trash a bit differently to mirror how Gmail works.

Right now threads are shown via the union of all labels on that thread. This seems like a pretty obvious model of how Gmail works and how they advertised the feature. If you create a label "Homework" and a label "Taxes" and tag messages in a thread as both, that thread will show up in both places. N1 works like this right now.

However, it turns out that Spam and Trash behave differently in Gmail. The behavior of the Spam folder is to only show *messages* which include the spam tag (not the entire thread), and then hide the spam messages from the thread view in other locations. And likewise for trash. If I "delete" a single message from a thread in Gmail (by move to trash), that single message will appear in my trash folder, without the rest of the non-trash messages in the thread. 

We probably didn't catch this in testing because usually spam/trash are applied to all the messages in the thread. But we've had increasing reports of this and it looks really confusing. Here's a simple example of what weird stuff you can see in your Inbox:

![image](https://cloud.githubusercontent.com/assets/92417/12567238/eeb72968-c372-11e5-8888-7cd43e637aef.png)

**Here's what we need to fix:**
- [ ] Don't show "spam" or "trash" label chips in the threadlist and update the thread message count to not include the spam/trash messages.
- [ ] In non-spam or trash views (i.e. most places), hide messages that have the spam or trash labels. This includes the Sent folder.
- [ ] In Spam and Trash views, only show the *individual messages* which have been labeled spam or trash.
- [ ] (ideally) show a footer that tells the user there are additional messages in the trash. (Not sure if we should also do this for spam messages.) Gmail shows this: 
![image](https://cloud.githubusercontent.com/assets/92417/12567753/d6bc8594-c375-11e5-867f-bff85aed9c01.png) 

**Related bugs:**
- #409 "Spam appears in Sent Items" by @mbilker 
- #973 "Spams in Sent [GMAIL]" by @akshar26
- #349 "Trashed items showing in Inbox" by @malaparte, @Glark, @jackiehluo, @hostmaster, @plainspace, @strumpet, @framerate
- #1037 "GMAIL: All messages" has emails with label "trash" by @ZaidoR1 
- #795 "Messages that have the Trash "label" shouldn't show in other labels" by @hirozed
- #708 "Trash label applied to drafts" by @vaanijyadmin 

Another example:

<img width="376" alt="41c43af8-b60b-11e5-9730-6a8f287ca8f3" src="https://cloud.githubusercontent.com/assets/92417/12568062/dfca2d9c-c377-11e5-9cde-a030d369fa29.png">

**Comment by bengotow** [comment]
From a support ticket:

Hey Nylas team!

Can I suggest that you have an option to not show labels for conversations 
that are in the Inbox.

The problem that I see if I'm a cc'd participant on a conversation that really 
gets going, and I delete some of the messages, and then other people reply 
again, Nylas is showing me the "Trash" label. It would be nice to be able to 
hide those labels for conversations in my Inbox.

Thanks!

Take a look at this picture for reference:



![image](https://cloud.githubusercontent.com/assets/1037212/13188266/376947fe-d705-11e5-9fab-f2c5717efced.png)

**Comment by bengotow** [comment]
(This is addressed by internal diff D2662. Will land in the next release.)

**Comment by hostmaster** [comment]
:+1:

**Comment by bashok001** [comment]
@bengotow @jstejada Can I consider this label issue fixed, if I am using 0.4.14 release. If so, can you please see this. Now my inbox is littered with `Sent Mail` labels for all the mail threads I initiated.

![screenshot from 2016-03-25 09-57-00](https://cloud.githubusercontent.com/assets/2344626/14045447/c295369a-f270-11e5-9e13-07b695b272fe.png)

Do you think this is unrelated and should be opened as another bug?
