### ISSUE TITLE
CMD + K on Mac to create hyperlink (like in gdocs)

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1136]
Like in Google Docs, highlight a text or a link then `CMD K` to generate the hyperlink. If you're selecting text that looks like a link, it should auto-fill the link box

**Comment by grinich** [comment]
We just shipped this literally 2 hours ago :) https://github.com/nylas/N1/issues/836

Will go out in the next release

**Comment by jweinstein** [comment]
😻
