### ISSUE TITLE
any space typed after "cancelled" bullet list activates bullet again

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1137]
![bullets](https://cloud.githubusercontent.com/assets/92417/12570220/91025460-c38a-11e5-91aa-3473c1d96b34.gif)

bullet activates when i type space after "this"

happens in latest N1

**Comment by emorikawa** [comment]
This got fixed in eb3223580b28411da82147842ce7e7304c39eaef
See issues #1064 and #585
