### ISSUE TITLE
images rendering before they're fully downloaded?

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1138]
I've seen this a couple of times, where an image will be displayed seemingly before it's been fully downloaded. If I click to manually save the image the full thing is there. But it only partially shows up in the message. A couple of examples:

<img width="836" alt="screen shot 2016-01-24 at 6 00 01 pm" src="https://cloud.githubusercontent.com/assets/92417/12571072/1fdb2480-c392-11e5-8a74-2d422d84e47d.png">
<img width="878" alt="screen shot 2016-01-24 at 6 00 15 pm" src="https://cloud.githubusercontent.com/assets/92417/12571073/1ff9fe14-c392-11e5-82c5-239eee42d7c3.png">

**Comment by enoversum** [comment]
Most of the times, when I open an e-mail for the first time, be it there a few minutes already or not, embedded images are not being shown at all. I have to open them a second time in order to see the images. I think this came in one of the latest releases. Using the Windows version.

**Comment by bengotow** [comment]
This should be fixed in the latest release. We re-worked this (and also added a loading spinner for inline images), and it should ship in the next few days.

**Comment by bengotow** [comment]
Hey! This was fixed in version 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!
