### ISSUE TITLE
N1 crashing on Ubuntu due to Out Of Memory (OOM Kill)

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1139]
![bitemyapp_2016-jan-25](https://cloud.githubusercontent.com/assets/92417/12574110/b62f8fca-c3b5-11e5-8c9a-572a9ed0ff67.jpg)

From https://twitter.com/bitemyapp

**Comment by bitemyapp** [comment]
It does this:

```
Jan 26 00:47:23 dodona kernel: [532243.561796] Out of memory: Kill process 11732 (nylas) score 393 or sacrifice child
Jan 26 00:47:23 dodona kernel: [532243.561798] Killed process 11732 (nylas) total-vm:2414196kB, anon-rss:1112604kB, file-rss:8172kB
```

over and over.

**Comment by grinich** [comment]
Were you ever able to log in, or did this happen on first launch?

**Comment by bitemyapp** [comment]
Pre-crash

![screenshot from 2016-01-26 00-52-00](https://cloud.githubusercontent.com/assets/320177/12574179/051fe34e-c3c7-11e5-91a0-2500a1e6859a.png)

Highlighted process cycles from 90mb used to 1+gb

![screenshot from 2016-01-26 00-52-44](https://cloud.githubusercontent.com/assets/320177/12574185/21975f5c-c3c7-11e5-9f9b-61a8aafcd727.png)
 used, then gets OOM'd and restarts.

**Comment by bitemyapp** [comment]
I have to kill it now because it's freezing my computer.

**Comment by bitemyapp** [comment]
@grinich it runs...for about 15 seconds at a time. Never gets as far as downloading mail, but I see my inbox.

**Comment by grinich** [comment]
if you delete `~/.nylas` (local cache+settings) does it show the first screen without OOM killing?

**Comment by mbilker** [comment]
Are there any messages from the log that indicate why this is happening?

**Comment by bitemyapp** [comment]
@mbilker you're asking if logs indicate why one of the app processes are leaking memory? Why would it? I didn't see anything about leaking file descriptors or anything like that and it's going too fast for it to be that, syscalls would've put a brake on the heap thrashing.

**Comment by bengotow** [comment]
Hi @bitemyapp — N1 creates a set of log files in your `tmp` folder (eg: `/tmp/Nylas-N1-23805.log`.) Can you look and see if there's a log file for that process that gobbled up memory? The last five digits should be the PID you see in the activity monitor. I'm really curious to see if we're stuck in a hard loop in JavaScript or if something lower-level is causing Chromium to crash.

**Comment by bitemyapp** [comment]
@bengotow is there any sensitive data in the logs?

**Comment by mbilker** [comment]
@bitemyapp There is sensitive data in the log files related to account ids. I would suggest you email @bengotow directly so he can take a look at it.

**Comment by bengotow** [comment]
Hey folks—there shouldn't be anything sensitive in the logs (account and object IDs aren't very sensitive). There's a small chance exceptions could include your email addresses, etc, but it's mostly debug information related to event traffic through the app and database query performance. Could you send them to me directly via email? I'm `ben@nylas.com`. Thanks!

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
