### ISSUE TITLE
can't right click misspellings in subject line

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1140]
![image](https://cloud.githubusercontent.com/assets/547354/12593401/bf366e02-c425-11e5-9931-06bac723b7de.png)

**Comment by Kersheh** [comment]
Just tested this on OS X, bug only applies to the subject field

**Comment by bengotow** [comment]
Thanks for filing this - will be fixed once a patch gets through review. Cheers!

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
