### ISSUE TITLE
Feature request: `?` to show keyboard shortcut cheat sheet

### ISSUE THREAD

**Issue by marioy47** [nylas/N1#1144]
One of the things that I love about Jira is that when I press the '?' key, a modal dialog appears with the most used keyboard shortcuts. Gmail also has this feature.

![](https://design.atlassian.com/images/patterns/keyboard-shortcuts/keyboard-shortcuts.png)

It would be great if I'm  not composing a message, when I press '?' a modal dialog appears with keyboard help

**Comment by emorikawa** [comment]
@marioy47 I definitely like the idea of pulling up a generic help from a keyboard shortcut.

For now, we do have a list of keyboard shortcuts inside of preferences -> shortcuts.

I think there are several other help/how-to related things that people would want to see in such a dialog beyond just keyboard shortcuts. I'm going to rename this issue to encompass the boarder idea of a help / tutorial dialog accessible from a keyboard shortcut

**Comment by marioy47** [comment]
:+1:

**Comment by pelletencate** [comment]
I would love to see this as well!

**Comment by bengotow** [comment]
This should be resolved in the next release. Stay tuned!

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
