### ISSUE TITLE
Mark all as read

### ISSUE THREAD

**Issue by lordgiotto** [nylas/N1#1147]
Hi, it would be great to implement a button to mark all the email of a specific folder  as read.
Thank you!

**Comment by Shmuwol** [comment]
:+1:

**Comment by emorikawa** [comment]
Yes! Marking as duplicate however of #1077 and #1148

**Comment by visualintent** [comment]
Definitely need this feature as well!

**Comment by painejake** [comment]
Really sweet mail app but missing this feature!

**Comment by barriem** [comment]
do itttttt
