### ISSUE TITLE
Mark as (un)read for single messages in thread

### ISSUE THREAD

**Issue by Frique** [nylas/N1#1149]
Mark as (un)read while viewing a message thread currently applies to the entire thread. It it sometimes desired to only mark one (such as only the last) of the messages as read/unread.

**Comment by bengotow** [comment]
Thanks for the feedback - I'll see if we can get this added in an upcoming release. It's a bit tricky because we don't currently display per-message unread status anywhere, but I think we could.

**Comment by jstejada** [comment]
merging into dupe #829
