### ISSUE TITLE
Support all gmail shortcuts

### ISSUE THREAD

**Issue by aks** [nylas/N1#115]
There are more than just a few gmail shortcuts.  If you wish to encourage long-time Gmail users to use N1, a good starting point is to support all the gmail shortcuts.

For example, '#' => delete, 'e' => archive, 'j' => next-message, 'k' => prev-message, etc.

The complete list of Gmail short-cuts is described here: 
https://support.google.com/mail/answer/6594?hl=en

The ones I use all the time: #, e, l, v, j, k, c, !, x, gi, gc, gs, gt, gl<label>.

**Comment by jgavris** [comment]
:+1: This is the first thing I plan to hack on.

**Comment by grinich** [comment]
please vote up here! :) https://trello.com/b/hxsqB6vx/n1-open-source-roadmap
