### ISSUE TITLE
[Feature Request] Multi-Profile/Custom Profile Folder Path

### ISSUE THREAD

**Issue by DaAwesomeP** [nylas/N1#1152]
Adding a setting for putting all of N1's date in another folder would allow for the following:
 - Encryption drives/folders (e.g. with VeraCrypt)
 - Use the same data in multi-boot systems (use the same profile across multiple OSes)
 - Flashdrive, making the profile mobile
 - Cloud storage to sync it
 - Network drive storage
 - There isn't currently a "multi-profile" system, but this would allow for it later

Basically, there would be a file (always in the same place), that can name the profiles and record their paths. The paths could be anything valid in the OS. Starting N1 with an argument would bring up a chooser that can add new profiles and update profiles' names and paths.

For backwards compatibility, if no profiles file is found, then it will look in the default (currently used) path. However, for new and upgraded installations, a profile file with be created.

This is basically the Mozilla profile system.

I'd be willing to help with this.

Thanks!

**Comment by grinich** [comment]
Why not just make a symlink?

This seems like a pretty specific/niche compared to a lot of the other bugs and feature requests. Is there a workaround you can use for now?

**Comment by jackiehluo** [comment]
Closing this issue because it's not in the scope of this project!
