### ISSUE TITLE
Some HTML emails, like TripIt, seem to be truncated

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1153]
I can scroll by dragging and selecting text inside the window.

<img width="766" alt="screenshot_1_28_16__8_23_pm" src="https://cloud.githubusercontent.com/assets/27594/12664384/1061a44e-c5fd-11e5-97f3-0b5ed4cdf555.png">

N1 Version 0.3.45-3b5880e (0.3.45-3b5880e)
OS X El Capitan 10.11.2 (15C50)

**Comment by emorikawa** [comment]
Oh man @markbao that's no good. These seem to happen intermittently and with promotional emails. I'm going to fold this issue in with #425. In the meantime, can you click the invisible button between the message's timestamp and the reply dropdown then click "Report Issue: Rendering" so I can get a look at the HTML of the non-forwarded email?

**Comment by markbao** [comment]
Ha, cool hidden feature! Done.
