### ISSUE TITLE
Create a system to let report screenshots and automatically strip out personal data & text

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#1154]
So people don't need to open MS Paint or Photoshop or whatever to carefully black out info before they report. May help lower the barrier to see screenshots.

**Comment by grinich** [comment]
like a [hipster ipsum](http://hipsum.co/) plugin?

**Comment by mbilker** [comment]
I agree with this entry. I dislike having to use GIMP to black out parts of the screen. I prefer to publish full-screen screenshots instead of parts of the screen.

**Comment by jstejada** [comment]
good idea!

**Comment by bengotow** [comment]
Oh man guys—we can totally do this. :sunglasses:

**Comment by bengotow** [comment]
@mbilker  how about this — d61becc549a1cb6aedcac6891d328f3b63f65601. Adds Developer > Toggle Screenshot Mode.

![image](https://cloud.githubusercontent.com/assets/1037212/12692044/0286da24-c6a7-11e5-9682-3a71c83c303a.png)

**Comment by jstejada** [comment]
:heart_eyes:
