### ISSUE TITLE
Input Source Change Causes N1 Crash

### ISSUE THREAD

**Issue by khamidou** [nylas/N1#1158]
One of our users reports:

"If N1 is open and running on OSX, and the user opens up their keyboard
preferences and adds a new input source ( in my case, Swedish ) the app
immediately crashes. Once I completely exited the application and restarted,
all was well."

I couldn't reproduce the issue by adding a US keyboard to my French MacOS machine.

**Comment by jstejada** [comment]
this seems to be the same issue as #895, so I'm merging it in.
