### ISSUE TITLE
renderer sandbox disabled?

### ISSUE THREAD

**Issue by diracdeltas** [nylas/N1#1159]
Electron disables the renderer sandbox here: https://github.com/atom/electron/blob/9a707b7c69cb0d1a78dfcc56c8e0978f142acc56/atom/app/atom_main_delegate.cc#L109. This should be a security concern for any Electron app that loads or can be tricked into loading remote content. See also discussion in https://github.com/atom/electron/issues/1753. 

Does N1 mitigate this issue in any way?

**Comment by bengotow** [comment]
Hi @diracdeltas — I'll check this out. As far as I know, these issues don't apply to N1 because we load all Javascript off disk and specify a Content-Security-Policy on the page that forbids all other scripts:

```
  <meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self'; style-src * 'unsafe-inline';">
```

**Comment by mbilker** [comment]
I wish `<webview>` supported modifying the content.

**Comment by mbilker** [comment]
Webview at least runs the content in a separate renderer process, but a pool would be needed to cycle the messages.

**Comment by diracdeltas** [comment]
> As far as I know, these issues don't apply to N1 because we load all Javascript off disk and specify a Content-Security-Policy on the page that forbids all other scripts. Do you know if that'd do the trick?

if i understand correctly, this only helps if the JS you're loading doesn't have any untrusted input. for instance, a local script that runs `eval` on something from a remote source would still be vulnerable.

**Comment by bengotow** [comment]
Good point @diracdeltas — it's still possible that we could download and `eval` malicious code. I don't /think/ we `eval` anywhere, but with so many layers of dependencies it could definitely be going on somewhere. Would be interesting to see if we can use an Electron preload script to stub and remove `eval` from the JavaScript environment.

@mbilker Unfortunately I don't think we can use `<webview>` to sandbox all third party content. We could sandbox HTML message bodies, but that's only one of many places third party data can be displayed, and each webview gets it's own process in Chromium, so we could inadvertently end up with many, many processes, which might also be a bad thing...

**Comment by bengotow** [comment]
It looks like we can override `eval` (in spite of http://stackoverflow.com/questions/2566973/how-override-eval-function-in-javascript/2567051#2567051), and N1 still functions as expected. Surprisingly, none of our plugins or dependencies are using eval at the moment. We'll keep an eye on it, but this seems like a good additional step to take toward securing our JavaScript environment.

**Comment by bengotow** [comment]
Hey! Going to go ahead and close this issue. The last few releases have shipped with very restrictive CSP rules for scripts and we've disabled `eval` entirely. If there's more we should be doing, please open another issue!
