### ISSUE TITLE
Specific emails only display a fraction of the content

### ISSUE THREAD

**Issue by oeed** [nylas/N1#1160]
Version: 0.3.45-3b5880e
Platform: OS X 10.11.2
Account: iCloud

I received an email from Survey Monkey and only a fraction of it is appearing, as below. I tried a forgotten password email from them too and it did the same thing. I've tried folding it & unfolding it and reopening the app but the problem persists.

![](http://puu.sh/mONuB/d858b81a9a.png)

On the online iCloud mail client it appears in full.

![](http://puu.sh/mONKr/e2bf1aa011.png)

It seems like it might be similar to #839, although that has HTML rendering as text so it might be unrelated.

**Comment by mbilker** [comment]
Fixed in 6620779ee2f66b780dba0900fd483de608aad239
