### ISSUE TITLE
No notifications on ubuntu

### ISSUE THREAD

**Issue by steelbrain** [nylas/N1#1165]
- N1 version: `0.3.45-3b5880e`
- Ubuntu 15.10 + Unity Desktop environment
- Confirmed zenity is installed
- Confirmed libappindicator1 is installed
- Notifications enabled 

![screenshot](https://cloud.githubusercontent.com/assets/4278113/12695668/c14baae6-c712-11e5-87a4-7573d7e6c2fc.png)

**Comment by steelbrain** [comment]
I am not sure if this is distro specific as I installed Ubuntu-GNOME today and it had GNOME instead of Unity. I still don't see any notifications, the fun part is that this works when written in dev tools
```
new Notification("test")
```

If I had to guess, it's not something wrong with linux or it's compat, but with the app itself

**Comment by steelbrain** [comment]
Nevermind, the notifications seem to be working on Ubuntu GNOME

**Comment by tsbarnes** [comment]
On the current alpha of Ubuntu 16.04, I get notifications but they aren't the OSD popups, they're full dialog boxes.  I know that's what notify-osd has started doing for notifications that have actions set on them, and the proper solution is to check whether the notification service reports supporting actions (which notify-osd does not).  I can't say for sure that it's the same reason they weren't showing up at all on Unity in 15.10 for @steelbrain, but I suspect it is.

**Comment by mcg** [comment]
16.04 appears notification issues appear to be more than just N1, https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1547448

**Comment by steelbrain** [comment]
Please note that this issue was reported on Ubuntu 15.10 and while reporting this issue, I confirmed from the N1 dev console that HTML5 notifications were working well, like I said in my second comment

**Comment by koterpillar** [comment]
Should "Message boxes instead of notifications" be reported separately? I am getting them on Arch Linux with `zenity` installed.

**Comment by luispabon** [comment]
Same here, getting a dialog box titled "electron" with notifications, instead of Unity's notification system.

**Comment by luispabon** [comment]
Definitely not a N1 issue though for what I can see on launchpad.

**Comment by mcg** [comment]
It's and Electron issue, which seems to have been fixes. Also some workarounds, until the fix makes it downstream. See electron/electron/#465

**Comment by geekgonecrazy** [comment]
I can confirm this work around works on Ubuntu 16.04 LTS:
```
sudo touch /usr/lib/libunity-electron_notification_fix
```

Afterwards just have to completely exit Nylas.  Then works as expected

**Comment by bengotow** [comment]
Hey folks - this should be fixed now that we've pulled the latest version of Electron into N1. Cheers!
