### ISSUE TITLE
Account label reset to initial every few seconds

### ISSUE THREAD

**Issue by steelbrain** [nylas/N1#1166]
- N1 version: `0.3.45-3b5880e`
- Ubuntu 15.10 + Unity Desktop environment

If I try to edit account labels, it seems like they reset after an interval. I worked around it by writing the label in a text editor, copying it and then pasting it and focusing something other than input box quickly. I believe this to be a bug

**Comment by mbilker** [comment]
Thanks for the report @steelbrain.  Was the mailbox syncing when you were trying to edit the text?

**Comment by steelbrain** [comment]
@mbilker Yes it was. I have several k messages in my accounts so it took a while for me

**Comment by mbilker** [comment]
So you can change the Account Label after the initial mail sync?

**Comment by steelbrain** [comment]
@mbilker but why does it have to keep replacing the label?

**Comment by mbilker** [comment]
N1 stores its state in many specialized areas. The Account Label is committed to this area after the text box is unfocused. That data store is updated every few seconds when the initial mail sync occurs. This causes it to refresh its state from the main store, including the Account Label.

**Comment by steelbrain** [comment]
@mbilker Thank you for the explanation. I still think this is a bug, and the view handler should check if the input is in focus and if it's in focus, it should not change it's value

**Comment by jstejada** [comment]
hey @steelbrain , this is related to #838. We are going to release an update soon. If you keep experiencing this issue, feel free to reopen this and let us know. Thanks!

**Comment by steelbrain** [comment]
Awesome, Thanks @jstejada
