### ISSUE TITLE
Download button on main site does nothing.

### ISSUE THREAD

**Issue by Disar** [nylas/N1#1167]
The only download button that works is the one in the footer bar.

**Comment by emorikawa** [comment]
@disar, that's no good! I'm having trouble reproducing this. It looks like all of the buttons on https://nylas.com/N1 are currently correctly redirecting to https://invite.nylas.com/download/, which should start a download based on your current platform.

Do you get at 404? a 500? What platform are you on?

**Comment by Disar** [comment]
No error number. Just nothing happens. Im on windows 10 -  Chrome

**Comment by emorikawa** [comment]
Bizzare. I booted up my Windows 10 machine, went to the site on Chrome and was successfully redirected to https://invite.nylas.com/download/ after clicking the buttons in the middle and top nav. It automatically started downloading in the bottom-left corner.

Were you able to get to the page that says "Welcome to N1. Your download will begin shortly", or did it just never get there?

We do have link tracking on that button and it's possible a Chrome extension is interacting weirdly with that. Do you have any extensions that you think might be doing that?

Is N1Setup.exe in your Downloads folder?

**Comment by Disar** [comment]
It just does nothing. The only time I got a download was when I clicked the button in the top right corner. Perhaps my profile+plugins in chrome is messing up.

Probably needs a different ticket but N1 fails to start as well. Not sure if it's related to my gmail account.

**Comment by bengotow** [comment]
This has been fixed - turned out the download button was being broken / incorrectly blocked by ad blockers.

**Comment by Disar** [comment]
Ah yes, I'm using ad blocker indeed. Good job!
