### ISSUE TITLE
Duplicate drafts created in the thread for sent messages.

### ISSUE THREAD

**Issue by brettgerry** [nylas/N1#117]
When replying to a message on a thread, and sending, two copies of the message show up in the thread.
http://img.mtrc.in/db7U

**Comment by colincalnan** [comment]
This is a pretty critical bug.

I was just writing a pretty length reply and ended up with 9 drafts, being interrupted constantly as I typed, and the cursor being moved to the new draft and the beginning of the reply text so I was typing over what I had already typed. then when I tried to send, it sent an old version of the draft. It's not possible to write email this way.

**Comment by ethanve** [comment]
+1 getting this too and it's making it impossible to write emails on N1

**Comment by colincalnan** [comment]
Looks like this may have been fixed on the most recent update. Doesn't seem to
be happening any more.

> On Nov 10 2015, at 9:33 pm, Ethan Veres &lt;notifications@github.com&gt;
wrote:  

>

> +1 getting this too and it's making it impossible to write emails on N1

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/117#issuecomment-155671819).![](https://github.com/notifications/beac
on/AAOss1C1xU65N-BOHtECbH4DuHYHO2D2ks5pEsqogaJpZM4GTbSZ.gif)

**Comment by grinich** [comment]
I'm going to close this as stale, since I haven't seen it reappear. Thanks!

**Comment by jcouturier** [comment]
I'm seeing this happen with increasing frequency on both OSX and Windows versions.

**Comment by jstejada** [comment]
I'm reopening this issue since a lot of people have been reporting it recently

**Comment by jstejada** [comment]
hi @jcouturier , are you still seeing this on the latest version?

**Comment by jcouturier** [comment]
@jstejada Looks like this has been resolved in v0.4.16. Thanks!

**Comment by pauloschilling** [comment]
I'm having this issue in **0.4.25**-a22631a on **Arch Linux**, ironically or not, happened when sending an email to N1 support about labels being out of sync.

http://i.imgur.com/bKLrZN8.png (N1 drafts folder)

In my case it's a **Gmail** account.
