### ISSUE TITLE
N1 doesn't snap to edges

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#1172]
I'm on Fedora 23 and I would like to be able to snap my N1 window to the edges like all the other applications I have on my desktop. When I try to snap nothing happens. I have tried this on both Cinnamon and GNOME.

My system:

> Linux tinodesk 4.3.3-303.fc23.x86_64 #1 SMP Tue Jan 19 18:31:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
