### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by trgcyln** [nylas/N1#1173]
When will you start to support custom languages ? Such as russian, turkish, german, french  ...
I want to use this app in my office  but not all our employees know English.

**Comment by emorikawa** [comment]
@trgcyln Coming soon! i18n and localization is definitely highly requested. We're keeping track of that on #24. I'm going to merge into that (and added `localization` into the subject for better searching). We definitely may be asking for volunteers soon.

**Comment by trgcyln** [comment]
Sign me up for Turkish Translation.
