### ISSUE TITLE
Snooze Mail

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#1179]
Should be possible soon thanks to the pending metadata service

**Comment by mbilker** [comment]
Will this metadata service be open source?

**Comment by grinich** [comment]
We really haven't built it or figured out the details yet, so we're not really not even sure what it will be.

**Comment by emorikawa** [comment]
Closing as duplicate in favor of #71

**Comment by mbilker** [comment]
@grinich Thanks for the update. I saw @bengotow write in another issue that the metadata service most likely will be part of the Sync Engine.
