### ISSUE TITLE
Change global font size in settings

### ISSUE THREAD

**Issue by rotvulpix** [nylas/N1#118]

**Comment by bengotow** [comment]
Thanks for downloading N1. This is definitely something we're hoping to implement soon—you can currently do this by changing the `font-size-base` in `ui-variables.less`, so we just need to build the UI for it and make sure everything changes consistently.

Feel free to track this over on our open-source project board: https://trello.com/c/RqLwnRpf/11-ability-to-change-font-sizes. We'd be happy to accept pull requests for this as well!

**Comment by jcguinea** [comment]
How can I change or know the font style is using Nylas?

**Comment by kelleychambers** [comment]
@jcguinea @bengotow mentioned it could be done in the source code. Look at his notation just above yours.

**Comment by kelleychambers** [comment]
It's on line 97 @jcguinea ....

**Comment by kelleychambers** [comment]
What I need to know is after the change is made, how do I create the installer file so I can apply that change to my Mac installation?

**Comment by joshlewis** [comment]
Any answer to @kelleychambers's question?
