### ISSUE TITLE
Todo List / Note to self integration

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#1180]
Many people use email as a todo list, frequently by emailing themselves notes. Lots of potential plugin ideas around better ways to manage this.

**Comment by khanshakeeb** [comment]
Have any one start worked on this plugin? As I am also looking forward to see such plugin. But there is a lot of todo app so do we need to make it our own? Or integrate with some famous todo app?

**Comment by bengotow** [comment]
Moving to the plugin list at https://trello.com/c/c9LsDrMy/64-todo-list-note-to-self-integration. We'd love to see this contributed as a plugin!
