### ISSUE TITLE
No spam folder for Exchange Account

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#1185]
In Exchange accounts, the folder with display name `Junk Email` is used for spam, but it is not being assigned as the standard `spam` folder (with `name='spam'`) as per https://nylas.com/docs#folders, so it is not being displayed in the standard accounts section

**Comment by bherila** [comment]
+1, although the Junk Email folder *does* appear.

![image](https://cloud.githubusercontent.com/assets/1422004/12831486/7513a116-cb49-11e5-8384-835988fa27fa.png)

**Comment by logandavis** [comment]
A fix for this landed last Friday.

**Comment by itsyache** [comment]
yh like wtf, no junkmail folder for me
