### ISSUE TITLE
Add accounts to local sync engine via gui

### ISSUE THREAD

**Issue by andysaini** [nylas/N1#1186]
Is there a way to add accounts to a locally running sync engine via N1(gui)?

**Comment by bengotow** [comment]
Hi @andysaini — there's not currently a UI for doing this. You'd need to edit your N1 config.cson file manually. Unfortunately this isn't part of the roadmap, but we'd welcome a pull request that makes manual setup easier!

**Comment by andysaini** [comment]
will probably write a plugin for this!
