### ISSUE TITLE
Some emails do not display fully

### ISSUE THREAD

**Issue by geekgonecrazy** [nylas/N1#1192]
I notice this primarily with name.com emails.

![image](https://cloud.githubusercontent.com/assets/51996/12762252/f51afb9e-c9b3-11e5-8d43-3c3d5e1eb740.png)

Displays in:
* Reply / Forward
* Print

![image](https://cloud.githubusercontent.com/assets/51996/12762298/270e8242-c9b4-11e5-86be-c54b537f0d8c.png)

The content of the box is scrollable.  Looks like the height is being improperly identified. Being set to 24px tall.

Here is the contents of the email body:

https://gist.github.com/geekgonecrazy/a24089cb21f10af6aa67

**Comment by emorikawa** [comment]
Yes! This is a known issue and recently got fixed in 6620779ee2f66b780dba0900fd483de608aad239
It will go out in the next release.
In the meantime see https://github.com/nylas/N1/issues/425

**Comment by geekgonecrazy** [comment]
@emorikawa perfect!  I looked but missed that.  Thanks!
