### ISSUE TITLE
Removing themes

### ISSUE THREAD

**Issue by sadalavoaoj** [nylas/N1#1194]
Hi there,

How can i remove themes? i have uninstaled the program and installed it again but it stays with themes installed by me.

Could someone tell me where is the folder where themes probably stay installed? i just want default themes like in a clan instalation.

best regards,

**Comment by bengotow** [comment]
Hey @sadalavoaoj — yep, there's a folder called `~/.nylas` where N1 keeps temporary files and installed packages. Here's a full list of file locations used by the app https://nylas.zendesk.com/hc/en-us/articles/216837327-How-do-I-uninstall-N1-

**Comment by sadalavoaoj** [comment]
Hi friend,

Worked like a charm.
Best regards
