### ISSUE TITLE
Archive and Next not working correctly. 

### ISSUE THREAD

**Issue by mataal** [nylas/N1#1195]
When in single pane view and with a message open, I use Archive and Next or what is referred to as "Remove from view and Next". 
However, often, pressing this the first time has no effect than a screen flicker. Pressing again has desired effect
Video [link](https://dl.dropboxusercontent.com/u/12419/double_press_for_archive_and_next_%22%5B%22.mov). 

Keyboard shortcuts chosen- Gmail. 
Nylas version - Version 0.3.45-3b5880e (0.3.45-3b5880e)

**Comment by mbilker** [comment]
Video link does not work.

**Comment by mataal** [comment]
It did for me. 
Here's [another link](https://dl.dropboxusercontent.com/u/12419/double_press_for_archive_and_next_%22%5B%22%20480p.mov) with a different format file.

**Comment by jstejada** [comment]
hey @mataal , this should be fixed in the next release. Re open if you are still having issues. Thanks!
