### ISSUE TITLE
Inactive "data detector" and misaligned "lookup" popup on Mac

### ISSUE THREAD

**Issue by strob** [nylas/N1#1196]
"Look up & data detectors" (as they seem to be called) are not working properly.

1. the "data detector" part isn't working, so dates and links and other such tokens aren't grouped together on hover;
2. and the "lookup" part is rendering in on the top left of the screen suspiciously matching the diagonal between the link and the top of the message.

Here's a (redacted) screenshot. I expected the entire link to highlight and open the webpage inline, instead of a Wikipedia lookup of the acronym:

<img width="1440" alt="bad-data-detector" src="https://cloud.githubusercontent.com/assets/208551/12771570/7ec14a8a-ca2a-11e5-93e9-af7d16857eda.png">

I am running Version 0.3.45-3b5880e (0.3.45-3b5880e) on an MBP with El Capitan. 

Others are unlikely to run into or be able to reproduce bug 2 (let's call "1" a feature request) unless they've enabled the (essential!) trackpad gesture:

<img width="657" alt="screen shot 2016-02-03 at 4 06 42 am" src="https://cloud.githubusercontent.com/assets/208551/12771721/a41f3e1c-ca2b-11e5-8e6e-41d48cc5a67b.png">

Thanks! Great work

**Comment by bengotow** [comment]
Hey! It looks like this has been resolved in Electron. Can you try in the latest release (0.4.40) and I'll re-open if it's still a problem? Thanks!
