### ISSUE TITLE
Show Previous and then Hide Previous leaves empty space

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#1199]
**N1 Version:** 0.4.2-master
**OS:** Arch Linux

_Description:_
I checked to see if a thread participant responded to the original message, or my reply to that original message. I followed the procedure under _Expected Result_ and found the message height to not return to its previous height.

_Expected Result:_
1. Click `Show Previous`
2. Previous message shown
3. Click `Hide Previous`
4. Message body height does not collapse back to original height

_Actual Result:_
1. Click `Show Previous`
2. Previous message shown
3. Click `Hide Previous`
4. Message body height collapses back to original height

**Comment by bengotow** [comment]
Hey @mbilker — is this still an issue? I'm not 100% sure, but I'm not able to reproduce this. Are the step 4's correct above? I think they might be flipped.

**Comment by mbilker** [comment]
This does not occur anymore from my experience in 0.4.10.

**Comment by molstrangler** [comment]
I have the same issue on my Lenovo X250 & Windows10.  Though I can two-finger scroll up and down nothing happens for left & right.
