### ISSUE TITLE
Building on 10.10.5 fails

### ISSUE THREAD

**Issue by Jarred-Sumner** [nylas/N1#12]
<img width="697" alt="screen shot 2015-10-05 at 12 30 35 pm" src="https://cloud.githubusercontent.com/assets/709451/10291136/e4d4084e-6b5c-11e5-81b7-510f820fb4f5.png">

I'm probably doing something dumb, e.g. maybe it's failing because my version of Node is super old?

I tried manually installing electron via `brew cask install electron` and then running `./N1.sh`.

It still said:
> Cannot locate electron. Be sure you have run script/bootstrap first from /Users/jarredsumner/N1

Just to check, I ran `exec $SHELL` and it still reported the same message.

If node is the issue, I can't upgrade it without hassle because this is my work computer and stuff depends on it

**Comment by justjanne** [comment]
Try using nodejs 0.10 again. (Your version is too young – it works with 0.10)

**Comment by chrise86** [comment]
So this only works with older versions of Node?

**Comment by spang** [comment]
For now, yes. This is due to the version of Electron we're currently building on top of—we periodically upgrade to newer versions, and later upgrades will include support for more recent node.

**Comment by Nijikokun** [comment]
Using `0.10.29` it does not work.

Please put inside of the `package.json` the specific version of node to build with. This is completely possible and would prevent all of these issues being opened and provide users with the appropriate error message.

https://docs.npmjs.com/files/package.json#engines

**Comment by chrise86** [comment]
What version of 0.10 is actually supported?

**Comment by Nijikokun** [comment]
`0.10.40` delete the `node_modules` folder in `apm` and `build` before retrying.
