### ISSUE TITLE
Invite code input - error message has html garbage

### ISSUE THREAD

**Issue by bslayton** [nylas/N1#120]
Accidentally posted my invite link instead of the invite code in the textbox. This nice error appeared. Thought you'd like to know.

<img src="https://cloud.githubusercontent.com/assets/646334/10657590/8630c44a-7853-11e5-8443-72955783c63e.png" width="50%" />

**Comment by bengotow** [comment]
Hey—thanks for reporting this, we'll get this fixed in the next update.

**Comment by grinich** [comment]
I believe this was just a transient error. Please re-open if it persists.
