### ISSUE TITLE
[Feature Request] Always move to folder/ignore conversation

### ISSUE THREAD

**Issue by bherila** [nylas/N1#1201]
Outlook/Exchange supports the notion of "Always move messages in this conversation" which is very useful for ignoring conversations (always move to trash) or auto-archiving ("muting") threads. It would be great to support this in Nylas!

**Comment by bherila** [comment]
Here is how you do it: 
```xml
 <ItemOperations xmlns="ItemOperations:">
   <Move>
     <ConversationId>...</ConversationId>
     <DstFldId>DeletedItems-Folder-ID</DstFldId>
     <Options>
       <MoveAlways/>
     </Options>
   </Move>
 </ItemOperations>
```

(the `<MoveAlways/>` element does the trick) 

Reference: https://msdn.microsoft.com/en-us/library/ee237708%28v=exchg.80%29.aspx?f=255&MSPPError=-2147217396

**Comment by jackiehluo** [comment]
Merging into #764!
