### ISSUE TITLE
Unified Inbox: Action does not "show up" or re-render the message thread list

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#1202]
**N1 verision:** 0.4.2-master
**OS:** Arch Linux

_Description:_
When I do an action from the message thread list (i.e. Archive, Change Label, or Trash), the action does not cause the result of the action to show. For Archiving or Trashing a message, the message does not disappear from the list, and clicking the message causes the message view to show up.

_Expected Result:_
1. Message disappears from message list

_Actual Result:_
1. Message stays in the message list
2. Can still do more actions on the message
3. The message disappears if I switch to a different message list view, for example Sent Mail, and then back again due to a re-render of the message list

**Comment by bengotow** [comment]
This should be fixed in c82ad7ee868dc312e46aeea0edf9c0ae358cbcbb. It turns out that an update to data that arrived but did not impact the result set, which arrived while the query subscription was re-building it's result set caused it not to trigger with any update at all.
