### ISSUE TITLE
Ctrl/Cmd+0 does not go back to All Accounts view

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#1203]
**N1 Version:** 0.4.2-master
**OS:** Arch Linux

_Description:_
N1 presents a new menu instead of the account switch in the latest master. It present keyboard shortcuts in a well understood manner, but the <kbd>Ctrl + 0</kbd> shortcut does not work in the current revision.

From my investigation it appears from a lack of implementation of the shortcut in [keymaps/base.cson](https://github.com/nylas/N1/blob/14edd8a7c7d0806d8730169dce52bccdb5ce0a3e/keymaps/base.cson#L58).

**Comment by jstejada** [comment]
good catch, thanks!
