### ISSUE TITLE
Sudden Restart of App

### ISSUE THREAD

**Issue by krishnaguragain** [nylas/N1#1205]
N1 verision: latest
OS: Windows 10
When i have got a email attached a photo (might be around 8MB) in my email and when i just open the  email tab, app crashes and restart continuously.

**Comment by bengotow** [comment]
Hi @krishnaguragain — I think this is the same issue that we were having in #415, but I thought it was resolved! Do you know if you're running the latest version of N1?

**Comment by krishnaguragain** [comment]
I don't think so, we have to check on other windows os too.

**Comment by krishnaguragain** [comment]
And I want to request to add new feature "auto startup at windows "

**Comment by bengotow** [comment]
Hey! This should have been fixed earlier this month by changes in Chromium upstream. Going to go ahead and close this. Cheers!
