### ISSUE TITLE
Hard crash on OS X "Nylas N1 Quit Unexpectedly" 

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1208]
<img width="1117" alt="screen shot 2016-02-04 at 7 49 11 pm" src="https://cloud.githubusercontent.com/assets/92417/12860617/e544c892-cc12-11e5-88ed-31836e6a3217.png">

Here's the [full OS X crash log](https://github.com/nylas/N1/files/119938/n1-crash.txt)

**Comment by bengotow** [comment]
EXC_CORPSE_NOTIFY... that's a new one. This looks like it's related to system integrity protection, so it might be something further down in Chromium we should escalate to Electron.

**Comment by bengotow** [comment]
We haven't seen this one in a long time, so I'm gonna go ahead and close this. There are other crashes, but none with this particular stack trace.
