### ISSUE TITLE
Version 0.4.4 wants to downgrade to 0.3.45

### ISSUE THREAD

**Issue by alexnederlof** [nylas/N1#1211]
I don't think this is intentional. I just upgraded from 0.3.45 to 0.4.4 and when the app restarted, it suggested I "upgrade" from from 0.4.4 to 0.3.45

![screen shot 2016-02-06 at 10 38 20](https://cloud.githubusercontent.com/assets/992615/12865989/3d27ea34-ccbe-11e5-8e2a-520bec26630e.png)

On OSX 10.11.3

**Comment by alexnederlof** [comment]
Restarting the app "fixed" it

**Comment by jimrory** [comment]
me too

**Comment by BetterTimes** [comment]
Same here. After starting n1 the update.exe runs every time and tries to istall  0.3.45. Platform Win 10 x64.

**Comment by jipiboily** [comment]
Yeah, same here on Mac, and I actually clicked on it by accident (don't ask) and there is no way to get back to 0.4.4...even deleting it and downloading it from scratch...help? I was so happy to see a unified inbox...

**Comment by 5paceToast** [comment]
In my case (Win 10 x64), it fails to restart and try installing, so relaunching just keeps it on 0.4.4 (and asks again to downgrade).

**Comment by bengotow** [comment]
Hey folks—this should be fixed in an hour or so. We ran into some issues with the 0.4.4 rollout and stopped the automatic updaters for a few hours. Sorry for the hassle!

**Comment by bengotow** [comment]
Should be fixed now. Cheers—
