### ISSUE TITLE
Prevent automatic list formatting after typing the first dash + space

### ISSUE THREAD

**Issue by Frique** [nylas/N1#1212]
When you type "- " (dash + space) while composing a message N1 automatically reformats it into a bullet list. I'm used to signing my emails with a dash followed by my name so this is an issue.

Commonly the automatic formatting of a bullet list starts with the 2nd bullet (after creating a dash + space + line of text and pressing Enter). That would be a solution and the expected behavior.

**Comment by bengotow** [comment]
Merging with #252
