### ISSUE TITLE
Add spam filtering integration (spam sieve)

### ISSUE THREAD

**Issue by droplab** [nylas/N1#1213]

**Comment by mbilker** [comment]
Would this be more of a responsibility of the mail provider?

**Comment by grinich** [comment]
Yeah this is really something done at the mail provider level (e.g. Gmail, Cyrus, Dovecot, etc.)

**Comment by paperscissors** [comment]
it would be nice to be able to add even some rudimentary level of it though; not all provider spam filtering is created equal.

there are actually node.js libraries for spam assassin, for what it's worth.

e.g. https://www.npmjs.com/package/node-spamd

it could be too much for most folks, but possibly a nice addition as a plugin.

**Comment by PwnArt1st** [comment]
+1

**Comment by Bergg** [comment]
I see this issue is closed, meaning there is no intention to have some level of spam filtering in N1. My provider does not provide any spam filtering unfortunately so this is a serious issue for me.

**Comment by iangrantphoto** [comment]
This is somewhat of a deal breaker for me guys, need the spam filtering or at least have a some sort of plan beyond passing the buck.
