### ISSUE TITLE
Error Themes Nylas n1

### ISSUE THREAD

**Issue by cristianfb1989** [nylas/N1#1214]
Hello, I tested a few days ago, differents themes within N1 and i'm checking that combining different themes within ".nylas \ packages" folder, the same program works with different options of each of the themes (colors, fluency navigation, etc). Is it right that the email client makes that combination? Sorry for my English. I am from Argentina. My email is cristian.fb@hotmail.com

**Comment by bengotow** [comment]
Hi @cristianfb1989 — you can install as many themes as you want, and choose theme you'd like to enable from Preferences > General within the app. While it's technically possible to apply several themes at once, our UI only allows you to choose one at a time. They apply CSS and other changes to the app.

Hope that helps!

**Comment by bengotow** [comment]
Hi—going to go ahead and close this. Feel free to re-open if it didn't address your question!
