### ISSUE TITLE
Error - N1-Solarized-Dark 

### ISSUE THREAD

**Issue by cristianfb1989** [nylas/N1#1215]
Hi @NSHenry i found a error with the theme Solarized Dark N1 and other themes. This blocks access to "General" .
![cakrfq-weaavjgw](https://cloud.githubusercontent.com/assets/16965222/12868522/16bbfae2-cce7-11e5-836d-a6031147a169.png)

  10 hours ago, I delete all the themes in the folder ".nylas \ packages" and the problem was solved

**Comment by bengotow** [comment]
Hi @cristianfb1989 — thanks for posting this. Could you open this as an issue on the themes issues page instead: https://github.com/NSHenry/N1-Solarized-Dark. Thanks!

**Comment by cristianfb1989** [comment]
Alright!
