### ISSUE TITLE
Keyboard shortcuts don't work when 'focused' on mail message

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1216]
I usually use the keyboard shortcut Command+Shift+R to reply-all to a message. However, sometimes I have to click in the message itself, to select some text or something, and after I do that, the keyboard shortcut no longer works.

Video: https://vid.me/wVwc - at the end, I click in the message area but can't use the shortcut key (no effect).

N1 0.4.4
OS X El Capitan 10.11.3 (15D21)

February 8, 2016 — Continues to be an issue as of Version 0.4.5-b0ec335 (0.4.5-b0ec335)

**Comment by laughedelic** [comment]
+1 
I also have such problem with other shortcuts. Same versions of OS/N1.

**Comment by jstejada** [comment]
This should be addressed in #915 , also related to #1282

**Comment by markbao** [comment]
Awesome :+1:

**Comment by markbao** [comment]
As of 0.4.25, this is working correctly. Thanks!
