### ISSUE TITLE
Nylas N1 PPA for Debian/Ubuntu/Mint

### ISSUE THREAD

**Issue by digitalextremist** [nylas/N1#1218]
I'm excitedly installing `0.4.4` right now by manual download, but in the future it would be awesome if there were a PPA entry we could add so that `apt-get update && apt-get update` would automatically update `N1`. Not just for the convenience, but because every time a new `.deb` file is downloaded, for some reason the package management system doesn't seem to see it's a replacement of a prior version.

**Comment by mbilker** [comment]
@digitalextremist there is an APT repository from Nylas, but I do not know how often it is updated.

**Comment by digitalextremist** [comment]
Thanks @mbilker. Do you know where I can find out about it?

**Comment by mbilker** [comment]
Unlike most APT repositories, you cannot view the directory and file structure which makes it near impossible to view which packages are provided. It is available from `api.nylas.com` if I recall correctly.

**Comment by bengotow** [comment]
Hey folks—yep, we run `apt.nylas.com`. I think the latest version should get pushed to that soon and you can do `apt-get update`. We register the apt repository when you install the app. I'll see if we can get everything pushed faster in the future. Cheers!

**Comment by digitalextremist** [comment]
Awesome -- thank you both.

**Comment by digitalextremist** [comment]
Having trouble adding this repository. Do you mind posting the command to use? :cry:

**Comment by mbilker** [comment]
Check `/etc/apt/sources.list.d`

**Comment by digitalextremist** [comment]
I'm familiar :) What I mean is, is it `stable main` or `trusty main` or `wily main` or what? I've tried all the above to no avail.

**Comment by mbilker** [comment]
@digitalextremist I am not familiar with it.

@bengotow could you shed some light on the situation. Is it possible to make `http://apt.nylas.com` directory listable.

**Comment by simon-lifelike** [comment]
@digitalextremist when you manually install the deb (`sudo dpkg -i N1.deb`), the apt repository will be automatically added as `/etc/apt/sources.list.d/nylas.list`.

**Comment by simon-lifelike** [comment]
@digitalextremist When you manually install the deb (`sudo dpkg -i N1.deb`) the repository should be automatically added at `/etc/apt/sources.list.d/nylas.list`.

The content of my file (on Ubuntu Gnome 15.10) is
```sh
deb [arch=i386,amd64] http://apt.nylas.com/ubuntu vivid main
```

Hope that helps.

**Comment by digitalextremist** [comment]
Thank you @simon-lifelike, that did help. Manually installing did not add a repository automatically.

By the way, I needed to add the repository's public key which I obtained by an error message.

**Comment by mradzinski** [comment]
Just in case someone comes across this, I had the same issue after manually install Nylas in Mint 17.3. Had to manually add the repo by adding `http://apt.nylas.com/ubuntu trusty main` and obtain the public key using the error message that pops up when trying to refresh the cache.

**Comment by digitalextremist** [comment]
Ah, I discovered the problem with this. It's that I'm using `Mint` and not `Ubuntu` or `Debian` ... upon upgrade ( after manually adding the repository, per this thread ) I see this after `apt-get upgrade` runs:

```
You are not running Debian or Ubuntu.  Not adding Nylas repository.
```

**Comment by nothor84** [comment]
Well I have tried to add this repository in Ubuntu 15.10 but i have no idea how to add the public key...
I have done the following:
`$ sudo add-apt-repository "deb http://apt.nylas.com/ubuntu wily main"`

But when I do the `sudo apt-get update` I obtain the message that there is no PublicKey ("NO_PUBKEY"), so I can't update Nylas.

Is there something I did wrong?

**Comment by nothor84** [comment]
I update my answer:

To obtain the public key, you have to do it manually. Copy the `PUBKEY` obtained when we update and execute the following code.

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys <PUBKEY>`

Where `<PUBKEY>` is the code obtained in the update, for example `48BC3A164D4BCF2B`

**Comment by mbilker** [comment]
@digitalextremist Could you post the output of `lsb_release -s -i`?

The [postinst](https://github.com/nylas/N1/blob/master/build/resources/linux/debian/postinst) controls when the repostiory is added.

**Comment by digitalextremist** [comment]
@mbilker it returns: `LinuxMint`

**Comment by kitpierce** [comment]
Also running `LinuxMint` (specifically 17.2) and would like to add the repo for auto-updates.  Ideally through the `dpkg -i N1.deb` method, but more than happy to manually add it with some guidance on which Ubuntu build to peg this to.

**Comment by light2yellow** [comment]
So, I installed the previous version with `dpkg` and it didn't show any updates. Moreover, `apt.nylas.com` looks like a dead page. There is absolutely no way to provide convenient updates?

**Comment by fcastilloec** [comment]
Has there been any updates? I tried adding http://apt.nylas.com/ubuntu xenial main, but I received an error not related to keys, so I can't move pass that. The error is as follows:
E: The repository 'http://apt.nylas.com/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Has anybody been able to add the repository?

**Comment by adambullmer** [comment]
@fcastilloec I think the latest version I could find was a wily release. Try replacing the text `xenial` with `wily` in your `/etc/apt/sources.list.d/nylas.deb` file.

**Comment by alexanderadam** [comment]
Just FYI: as [the original Nylas Mail / N1 (so *this* project here) is dead](https://github.com/nylas/nylas-mail/issues/3621) there are some forks where still process is going on.
The IMHO most promising and free fork [will probably have a repository with Debian packages as well](https://github.com/nylas-mail-lives/nylas-mail/issues/77#issuecomment-331444791).
@Mezzle is currently working on it.
