### ISSUE TITLE
Launch at startup not saving

### ISSUE THREAD

**Issue by pcjl** [nylas/N1#1219]
Everytime I click the option "Launch at system start" and leave the page, it doesn't seem to save. When I go back to my preferences, the option becomes unchecked again. I tried checking other options on the same preferences page (Workspace) and they all seem to persist,

I am on Windows 10 running Version 0.4.4.

**Comment by EZTEQ** [comment]
This bug is reproducable on my side. (0.4.4 on Windows 10)

**Comment by bengotow** [comment]
Hey folks! Thanks for filing this - can you see if you still run into this problem with the latest release (0.4.14)? It should be fixed, unless you're running into another edge case we haven't seen.

**Comment by pcjl** [comment]
I no longer have this issue.
