### ISSUE TITLE
Is there any plan to support Gmail alias?

### ISSUE THREAD

**Issue by jacobbubu** [nylas/N1#122]
Or someone already requested as a feature-request?

**Comment by bengotow** [comment]
Hi @jacobbubu — thanks for checking out N1. I'd love to have this as well, and it's on our open source roadmap here: https://trello.com/c/KO2UHr0i/24-send-using-aliases. Feel free to upvote it there if you have a Trello account.

**Comment by jstejada** [comment]
referencing #414
