### ISSUE TITLE
Bug: A new menubar icon appears each time N1 is Reloaded

### ISSUE THREAD

**Issue by michalkopanski** [nylas/N1#1223]
When Reloading N1, a new menubar icon appears for each time the app is reloaded. Seems to go away on it's own after about a minute.

_OSX 10.11.3_
_N1 Version 0.4.4-db467a5_
_Gmail Account x 3_

**Comment by mbilker** [comment]
I can attest to this issue on Linux as well. Sometimes reloading the app is treated as closing the window.
