### ISSUE TITLE
Account Switch Dropdown

### ISSUE THREAD

**Issue by dominikzogg** [nylas/N1#1226]
I liked the preview account switch look'n'feel more intuitiv. Would be cool we could use the feature all accounts or selected account with the old look, cause it was much easier to see which account is active.

**Comment by grinich** [comment]
the new design shows your account label at the top. you can also cycle through with keyboard shortcuts. 

![image](https://cloud.githubusercontent.com/assets/92417/12880373/a78e355e-cdf4-11e5-82e0-79679877455c.png)

**Comment by dominikzogg** [comment]
@grinich yeah i understand that, but the word "Work" in you case is less readable than before. The new feature is great, only the readability is worse in my point of view.

**Comment by grinich** [comment]
you can change that to whatever in the settings... 
![image](https://cloud.githubusercontent.com/assets/92417/12880411/270cbd0a-cdf5-11e5-99ca-0b4297e499bb.png)

**Comment by dominikzogg** [comment]
![old-account-layout](https://cloud.githubusercontent.com/assets/1011217/12880441/f2ac7072-ce40-11e5-8ca3-ec1c599c4080.png)

it was much easier to see the account name and type within the old design. As i told, the feature set is better now. But less readable

**Comment by dominikzogg** [comment]
@grinich please tell me if the explanation is bad, or you have another oppinion about that. if its the first one, i try it to make it better
