### ISSUE TITLE
Send emails don't go to 'Send' folder"

### ISSUE THREAD

**Issue by iamIcarus** [nylas/N1#1229]
Im using Nylas on MacBook (Yosemite). My email is configured with Exchange server , and successfully synchs , sends and receives email.

When using the Nylas client to send a **NEW** email , it sends the email successfully but i cannot see it in the client "Send" folder.
I can see that the "Send" folder successfully synchs because when i use another client to send a new email , Nylas has it on the "Send" folder too

**Comment by jacobmischka** [comment]
Related to #869 probably, sent email state is pretty much entirely broken in exchange.

**Comment by jstejada** [comment]
yes, merging into #869

**Comment by basma-b** [comment]
I found this solution [here](https://github.com/nylas/nylas-mail/issues/1457) 

So ugly hack that work well, go to :
-     ~/.nylas-mail/random_number.sqlite
-     open dabase with a [gui](https://apps.ubuntu.com/cat/applications/natty/sqlitebrowser/) when nylas is closed
-     open tables folders and add **role** to your folder (inbox, trash, sent, drafts, spam)
-     save database
-     restart nylas
