### ISSUE TITLE
All inboxes - joint mailbox for all accounts

### ISSUE THREAD

**Issue by meric426** [nylas/N1#123]
I would like an "all inboxes" option to see all emails from all accounts i've added

**Comment by rawjam** [comment]
Plus on with this one. Super important.

**Comment by GEverding** [comment]
:+1: love to see this

**Comment by jackiehluo** [comment]
:+1:

**Comment by theinterned** [comment]
:+1:

**Comment by bengotow** [comment]
Hey folks! Thanks for downloading N1. "Unified inbox" is definitely on the roadmap. We've created a card for it on our open source Trello board, and you can track it there. Feel free to upvote it there if you've got a Trello account: http://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by ssnanda** [comment]
This one is show stopper i can abandon mac mail app as soon this one is implemented

**Comment by mactexan** [comment]
N1 is soooooooo close to perfect. A unified inbox is all that's missing. It's the only feature keeping me on Apple Mail. I mean, c'mon! Who has just one email account any more?

**Comment by Omeryl** [comment]
I don't quite understand, I'd think it'd make more sense if every feature had a card in Trello and an open issue here...? I see a number of other feature requests with an open Issue that are discussed on the trello board.

**Comment by fteem** [comment]
While the devs implement this, on OSX you can change the active account with cmd + the number of the mailbox in the list. i.e. cmd + 2

**Comment by tommydangerous** [comment]
Need the unified inbox before I can use...

**Comment by enderahmetyurt** [comment]
@fteem thank for information.

**Comment by aly006** [comment]
:+1: only thing keeping me from using Nylas as my mail client as well
