### ISSUE TITLE
Grouped labels not showing up.

### ISSUE THREAD

**Issue by tobiassnall** [nylas/N1#1231]
I can't access my labels from Gmail. I've grouped them in Gmail and all that's showing up in N1 is the group name.

<img width="213" alt="screen shot 2016-02-08 at 09 58 08" src="https://cloud.githubusercontent.com/assets/17120869/12882583/90f7340c-ce4a-11e5-99dc-0e7a7022f555.png">

**Comment by bengotow** [comment]
Hi @tobiassnall — is the group name `•`? This generally works, so it may be caused by the character... I'll see if I can reproduce.

**Comment by tobiassnall** [comment]
It is, But I have other folders with standard names.  

But it seems to be related to the theme I had activated. Once I switched back to the standard theme I could access the labels without any problem.

**Comment by tobiassnall** [comment]
@bengatow

**Comment by kav-ya** [comment]
That's good to hear, let us know if you run into any other issues!
