### ISSUE TITLE
When selecting different account newest email is always marked 'read'

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#1236]
If you have multiple accounts set-up when you click between the accounts the newest email is automatically highlighted and marked are read.

I believe this behaviour is undesirable; for example then read receipt function is added.

Also it's really annoying,.

I think no email should be highlighted at all and let the user decide.  Maybe instead display stats where the body of the email should be:

  Last email arrived 1hr 24 mins ago
  Last connection to the service was 4 mins ago
  You've received 37 emails today; replied to 22 and forwarded 6 and 9 unread
  Yesterday you had 19 email, 2 have not been opened

  This account is occupying 546mb on your hard disk

etc...

Maybe the email unread can link to a pre-defined search to display the email in question.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we've changed this behavior in 0.4.25 so that N1 no longer auto-focuses the first message in a view when you switch views.
