### ISSUE TITLE
Draft reply disappears during composition

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1237]
Related to #1235. During compose, after a minute or two, my reply disappears and appears in drafts, *under a different email account* (my secondary email account with an alias).

Reproduce:

1. Use Unified Inbox
2. Select message in Account A and reply
3. Type some stuff, wait a minute
4. Reply disappears
5. Find message in Drafts, note that it's actually now replying from Account B

Video demonstration: https://vid.me/nDbU

Note that the reply is from the wrong account:

<img width="800" alt="screenshot_2_8_16__1_41_pm" src="https://cloud.githubusercontent.com/assets/27594/12895278/a4558b9c-ce69-11e5-85f6-7938a18fb63d.png">

**Comment by markbao** [comment]
As mentioned in #1235, issue persists even when the alias is deleted... it continues using that alias. Curious.

**Comment by jstejada** [comment]
possibly related to #1175

**Comment by jstejada** [comment]
hey @markbao I haven't been able to reproduce this. is this still happening to you?

**Comment by Bergg** [comment]
This is happening to me too. The message is saved as a draft, which I can only retrieve in the draft folder of "All accounts" but not the folder in the account I used for the reply. N1-04.10 on Fedora.

**Comment by Bergg** [comment]
Just saw a workaround in the slack chat : when replying, use a pop-out window by right-clicking reply on the sender's name,  instead of the "write a reply" which opens a composer in N1 which then disappears.

**Comment by bengotow** [comment]
This is a really strange one.

I think N1 is queueing a SyncbackDraftTask, which saves the draft you're working on back to the server. In the response to that API request, we update the `thread id` on the draft. It could be that the thread id is coming back different.

The SyncbackDraftTask also runs code to check that the draft is being saved to the correct account (in case you changed the from address.) If you changed the from address, it deletes the old draft and saves a new draft to the correct account. We fixed a bug in this code in 0.4.10, where you could not send from aliases you'd configured until you restarted N1. Maybe that could have been the issue?

We'll keep digging. Thanks guys—

**Comment by Bergg** [comment]
Concerning the workaround I mentioned: you can't do a reply-all with it, only a reply to the sender.

**Comment by bengotow** [comment]
Hey! This should be fully resolved in 0.4.14. We've temporarily disabled server syncback of drafts to IMAP and Gmail while we work on a few edge case issues. Thanks -
