### ISSUE TITLE
Signature does not change when selecting different email in Compose

### ISSUE THREAD

**Issue by Tiopy** [nylas/N1#1239]
When composing a new email, the signature seems to stay on the first account's signature, versus switching to correct signature when selecting a different account to send the email from.

**Comment by jarias** [comment]
The same is happening to me

Arch Linux
N1 Version: 0.4.5-b0ec335

**Comment by Tiopy** [comment]
Some specs. 

N1: Version 0.4.5-b0ec335 (0.4.5-b0ec335)

OSX: El Capitan 10.11.3

**Comment by zsiegel** [comment]
Having the same problem as well.

**Comment by diego-vieira** [comment]
+1 
Version 0.4.5-b0ec335 (0.4.5-b0ec335)
OSX 10.11.3

**Comment by cfriedline** [comment]
Same here: 

N1 = Version 0.4.6-c9c5af6 (0.4.6-c9c5af6)
OS X = 10.11.4 Beta (15E33e)

**Comment by psoiree** [comment]
+1

also, signature output wrong html. For example, in this signature text doesn't align to middle (height) while it does on simple .html file:


>   <div style="width: 60px; margin:0;float:left;" class="logo">
>     <a style="text-decoration:none" href="http://www.eighty9.pl" class="clink logo-container">
>         <img src="https://htmlsigs.s3.amazonaws.com/logos/files/000/422/614/landscape/LOGO.png" alt="EIGHTY9" border="0" class="sig-logo">
>     </a>
> </div>
>     <div style="width: 250px; height: 37px; margin:auto;float:left; border: 1px solid rgb(190, 190, 190); text-align: center;" class="logo2">  
>       <p style="font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 14px; margin-bottom: 10px;">
>       <a class="link email signature_email-target sig-hide" href="mailto:contact@eighty9.pl" style="color: rgb(181, 59, 58); text-decoration: none; display: inline;">contact@eighty9.pl</a>
>         
>       <span style="font-weight: bold; color: rgb(190, 190, 190); display: inline;" class="txt signature_companyname-target sig-hide">/</span>
>         
>       <a class="link signature_website-target sig-hide" href="http://www.eighty9.pl" style="color: rgb(181, 59, 58); text-decoration: none; display: inline;">www.eighty9.pl</a>      
>   </p>
> </div>
> 
> <div style="width: 100%; margin-top: 20px; float: left;" class="disclaimer">
> <p style="font-family: Helvetica, Arial, sans-serif; color: rgb(190, 190, 190); font-size: 8px; line-height: 10px;">Ta wiadomość i jakiekolwiek pliki przesłane wraz z nią, są poufne i przeznaczone wyłącznie do użytku osób i jednostek, do których wiadomość została adresowana. Jeśli wiadomość została otrzymana pomyłkowo, prosimy zawiadomić administratora systemu. Ta wiadomośc zawiera informacje poufne i jest przeznaczona wyłącznie dla wymienionej osoby. Jeśli nie jesteś wymienionym adresatem tej wiadomości, nie powinieneś jej rozpowszechniać, rozsyłać ani kopiować. Prosimy o natychmiastowe powiadomienie, za pośrednictwem poczty elektronicznej, nadawcy o pomyłkowym otrzymaniu tej wiadomości i usunięcie jej z komputera. Jeśli nie jesteś zamierzonym odbiorcą tej wiadomości, informujemy, że jej ujawnianie, kopiowanie, przesyłanie lub podejmowanie jakichkolwiek działań w związku z treścią tej wiadomości jest surowo wzbronione.</p>
> 
> <p style="font-family: Helvetica, Arial, sans-serif; color: rgb(190, 190, 190); font-size: 8px; line-height: 10px;">This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager.This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this email. Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibitet</p>
> </div>

**Comment by psoiree** [comment]
Ok, I've just added another 4 e-mail accounts to Nylas and THIS THING drives me crazy! You must manually get into one's folder and then make new e-mail because otherwise You won't be able to put Your signature in it.

**Comment by jstejada** [comment]
hey everyone, this will be fixed in the next release
