### ISSUE TITLE
Deleting non-empty folder causes an error but no alert within N1

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1244]
Should ask the user whether they want to delete all the messages in that folder, or move them to the archive (or cancel). You can currently only delete folders if they are empty.

Attempting to delete a non-empty folder returns 403 with 
```
{
  "message": "Folder 82b545lj3823b9xc40n3gy9tz cannot be deleted because it contains messages.",
  "type": "api_error"
}
```

**Comment by grinich** [comment]
@bengotow Shouldn't we tell the user why it can't be deleted?

**Comment by bengotow** [comment]
This should be fixed now:

![image](https://cloud.githubusercontent.com/assets/1037212/15193848/c0b442a2-1774-11e6-98af-2926053e206f.png)
