### ISSUE TITLE
Emails stuck in inbox

### ISSUE THREAD

**Issue by mhelvey** [nylas/N1#1247]
I have 5 emails that seem to be permanently stuck in the inbox. I tried removing the label, archiving, deleting, removing my account, uninstalling the app, deleting the cache directory. and starting from scratch. those suckers are still stuck in my inbox. help please!

**Comment by jsumnersmith** [comment]
Also seeing this issue. This is happening for emails for my gmail account that I have responded to but have not yet received an additional response back. Other email interfaces (Gmail and iOS mail) show the email as archived.

**Comment by mhelvey** [comment]
Now that I have had some time to really look into it. It actually seems to be a problem with sync. Nylas has not received any of my emails since december 28th. and these are the 5 emails that were in my inbox on that date... I went to the archive and I have ni emails later than this date. Any suggestions there?

**Comment by mfid** [comment]
I'm having a slightly different, but possibly related problem, on Exchange.

Emails that I'm reading, marking as read and archiving are behaving as they should in my Nylas inbox, but when I check my emails via my mobile client, or Office 365 web view, emails are still in my inbox, and marked as unread.

**Comment by akshaynhegde** [comment]
Am facing the same exact issue. Few emails are just stuck there. Also, am not receiving any new emails! The latest email Nylas showing is from Jan 15. I reinstalled the app, removed all the cache and hidden directories. But nothing helps.

Here is a small screen capture that shows the problem. - https://app.box.com/s/8kmh3buz8yb61dd1egyc2pqyk0xsjsuu

**Comment by jstejada** [comment]
Hi all, are you still experiencing issues? I'm going to merge into #2059
