### ISSUE TITLE
Gmail sync problem

### ISSUE THREAD

**Issue by hydrogo** [nylas/N1#1248]
Hi all. Todal i reinstalled application and for IMAP protocol inboxes sync works well, but for gmail it does not work - there are few old emails in list (maybe at the moment i already deleted Nylas from PC and deny it access to my google profile). Reloading the app and reconnection to gmail doesnt help.

**Comment by keevitaja** [comment]
I am experiencing the same issues.

**Comment by laughedelic** [comment]
+1

**Comment by keevitaja** [comment]
I am wondering, if it has (i did not experience this today) something to do with the nylas sync engine?

**Comment by nicklooijmans** [comment]
I have the same issue with my @gmail.com account. I have another (Google Apps) account that works perfectly.

**Comment by nicholasbutlin** [comment]
same - just started today with Gmail, other G-Apps accounts are OK

**Comment by jackiehluo** [comment]
Hey! This issue should be fixed now, so I'm going to close it—let us know if you see it again! Thanks!
