### ISSUE TITLE
No mails after password change

### ISSUE THREAD

**Issue by pvamshi** [nylas/N1#1249]
I changed my password on December 25. My inbox is stuck there , there is no way to get latest mails. Am I missing something here ?

**Comment by bengotow** [comment]
Hi @pvamshi — you'll need to remove the account from N1 and add it again using your new password. We're working on the ability to change your password and other account settings within N1, but it's been a low priority so far. Feel free to re-open if you run into any trouble!

**Comment by pvamshi** [comment]
Hi,
Thanks for the reply . I tried it but it somehow got all the old details back. 
Dont know how to hard delete the account.

**Comment by abarrand** [comment]
I had the same problem as well.  I ended up having to uninstall the app and reinstall again.  It was not a pleasant experience.

**Comment by bonaldi** [comment]
Same here — remove the account (it was my only account) and add it back I just get exactly the same old emails and no new syncing. Seems worrying that removing my account doesn't remove all the emails too.

**Comment by bonaldi** [comment]
(Could this be reopened please?)

**Comment by pvamshi** [comment]
I stopped using N1 because of this issue, might be a good idea to reconsider.
