### ISSUE TITLE
On windows, new "launch on system start" checkbox is not sticking

### ISSUE THREAD

**Issue by brittyazel** [nylas/N1#1252]
In windows, the new "launch on system start" option is not saving when I close out of the preferences menu and go back in.

**Comment by brittyazel** [comment]
I was on Windows 10 x64 btw. Also, the option doesn't work at all. It isn't just a visual issue, it functionally doesn't work.

**Comment by France82** [comment]
Same here.
Windows 10 x64

**Comment by bengotow** [comment]
(@emorikawa can you confirm this was fixed in 0.4.9?)

**Comment by cuddylier** [comment]
@bengotow How do I get the latest github version? I'm using the latest publicly available download, 0.4.5 which of course has this issue.

**Comment by ThePsionic** [comment]
I filed #1358 and can confirm that it is working in 0.4.10. Awesome work guys :)
