### ISSUE TITLE
Exchange sync issue

### ISSUE THREAD

**Issue by zellerda** [nylas/N1#1253]
When I configure my account I have this message

> Successfully logged in but could not sync mail. Please contact your Exchange administrator

What's the problem ? Any logs ?

Thanks for help

**Comment by ChristopheLux** [comment]
Hello @zellerda 
If you have access through a browser to you mail trough Outlook Web Acces
Go there go to Options All options

![options](https://cloud.githubusercontent.com/assets/11833461/12910419/f46bd888-cf0a-11e5-8c23-8b550b4e8763.png)

And make sure that you do not have more than 8 phones/others things registered (standard limit is 10 but depends on your Exchnage Administrator and Nylas needs 2 )

Regards

**Comment by zellerda** [comment]
Ok thank for your help I found the problem.
I had two Connection labeled as "iPhone" and I don't know who is it (wipe state by me). It was Nylas.
I think you need to rename the device name to "Nylas" if is it possible.
