### ISSUE TITLE
Gmail messages taking long time to show up

### ISSUE THREAD

**Issue by brittyazel** [nylas/N1#1255]
I understand that N1 doesn't use the typical "refresh" style that other mail clients do things, but I have two Gmail accounts tied to N1, my university and personal accounts, and while my university account is updating regularly, my personal account hasn't updated in 30 minutes. I can see the new messages on  the gmail website, but not on N1 (and yes I'm looking in the proper folder). Also, closing N1 and reopening does not solve this issue.

**Comment by keevitaja** [comment]
It is related to #1257

**Comment by keevitaja** [comment]
Also it does not add sent items. The mail is sent and present in web client, but not in N1 client.

**Comment by brittyazel** [comment]
It has been hours now, and I am not getting any email updates. What N1 is showing me is hours out of date

**Comment by jackiehluo** [comment]
Merging into #1868!
