### ISSUE TITLE
Rules: Color message in message list

### ISSUE THREAD

**Issue by codisms** [nylas/N1#1256]
Please add the ability to add color to the message list based on rules and/or account.  With the unified inbox (huge addition!), it's impossible to tell which account an email comes from in the list.  I also use color to identify sources of emails (mailings lists vs family) on top of by account.

**Comment by Cu8eR** [comment]
you mean labels?

**Comment by codisms** [comment]
Labels don't provide color, and they move items out of the inbox.

**Comment by mbilker** [comment]
If you are willing, what client do you use that allows you to color messages based on sender and account received? I am genuinely interested as I face the same issue.

**Comment by codisms** [comment]
Mac Mail.

**Comment by mbilker** [comment]
Ohh, I think I get it now. It is tagging of messages like Finder file and directory tagging with a color.

**Comment by codisms** [comment]
Correct.

**Comment by bengotow** [comment]
Merging into #1963 since it includes pictures.
