### ISSUE TITLE
Gmail account not adding

### ISSUE THREAD

**Issue by iDuuck** [nylas/N1#1257]
I recently (re)added my gmail account to my N1 (was there before, too). After the success message, the account just not popped up in the app. I have another one (using Google Apps through my company account) that is working fine (and an iCloud account).

**Comment by brittyazel** [comment]
I don't think that #1255 is related to this on at all

**Comment by iDuuck** [comment]
@keevitaja It's not the messages, but the whole account isn't showing up anywhere in the application.

**Comment by iDuuck** [comment]
Update on this: Seems like it's showing up, but I needed to reload the window.

**Comment by jstejada** [comment]
hey @iDuuck , this was probably related to the big update that went out recently, which requires a full resync of a user's mailbox. We're working on better strategies for handling big updates like this on our backend going forward. In the meantime, this performance loss should subside over today. Hang in there, and thanks for using N1! feel free to reopen if the issue persists.
