### ISSUE TITLE
Image not being downloaded from Gmail

### ISSUE THREAD

**Issue by crxdelsol** [nylas/N1#1259]
Sometimes I receive an e-mail with image attachments. When I view this email on the Gmail website, it shows properly.
When I open it in N1, there is no image and this is shown in the inspector window:

`GET file:///Users/jelle/.nylas/downloads/1t6vs6dq8m8r5l1f7kgv25z5o/image002.jpg net::ERR_FILE_NOT_FOUND`

OSX 'El Capitan'
N1 version 0.4.5-b0ec335 (0.4.5-b0ec335)

**Comment by bengotow** [comment]
Hi @crxdelsol — can you do me a favor and open the activity panel of N1 (from Developer > Toggle Activity Window)? I'm curious whether the app made an API request to fetch the attachment or not. That should help narrow this down.

**Comment by joelabair** [comment]
This seems related - I;m seeing broken images in my gmail on N1 as well.  

![Screen Shot](https://cloud.githubusercontent.com/assets/3341315/12952058/315b0092-cfe3-11e5-8cfd-1e398b27c91f.png)

**Comment by crxdelsol** [comment]
@bengotow 
I used the activity window. From another e-mail client I resend myself a message from client which does not show images in their signature.

What I can see in the source which is being requested (had to prettify the JSON result and HTML content), HTML content contains 'Mso' stuff, so this must be send by Outlook, since it uses Microsoft Word rendering.

Images are stored in the e-mail using 'cid' keys. (For inline attachments).
In the attributes > files section I see the CID keys also; example:

```{
    "content_id": "image008.jpg@01D163F9.34836D50",
    "filename": "image008.jpg",
    "id": "6tqp9gsuowa4kjmajgeci8tss",
    "content_type": "image/jpeg",
    "size": 1058
},```

It does have a size 1058 bytes (?) which is roughly 1 KB.
This specific file is also showing up in the console tab of the inspector pane:

```Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/jelle/.nylas/downloads/g9jnws5gcu9en8u13s6nqjx7/image008.jpg@01D163F9.34836D50```

content_id matches.

How this helps.

**Comment by ghost000cs** [comment]
Not sure if the issue is the same, I do encounter similar issue.

![image](https://cloud.githubusercontent.com/assets/17288831/13103030/b42fb5e4-d58d-11e5-8ddb-53236738d2a6.png)

after I change the setting from "when read" to "Manually", the image will stop showing. But if I change back to "when read", the image still be loading again.

Seems like the inline images are treated as "Attachments" to the email, so the setting for "Automatically load images in viewed messages" is not in use????

**Comment by bengotow** [comment]
I think this is the same issue as #621, so I'm merging these together.
