### ISSUE TITLE
Feature request: POP3 support

### ISSUE THREAD

**Issue by NikolaZornic** [nylas/N1#1261]
Is it possible to add POP3 support?

I can't add my company mail directly to N1 (it's working with other programs like Thunderbird, Outlook, ...). I had to import it to Gmail, and than add Gmail to N1.
It works this way, but mail is checked only once in an hour (limitation by Gmail).

Thank you in advance!

**Comment by rittbys** [comment]
If I understand correctly you might be able to host your own instance of the Sync Engine https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine

**Comment by bengotow** [comment]
Hi @NikolaZornic — thanks for checking out N1! I don't think POP3 support is currently on the sync engine roadmap, but you should open a GitHub issue on that project (https://github.com/nylas/sync-engine) or upvote it there if it exists. Sorry for the hassle!
