### ISSUE TITLE
After upgrade I see weird screen for composing email

### ISSUE THREAD

**Issue by khanshakeeb** [nylas/N1#1262]
Hi,

I have upgrade N1 but when I tried to write a new message so I have button with blank label. Kindly find attached screenshot for this

Thanks
![bug-after-ugrade-n1](https://cloud.githubusercontent.com/assets/303037/12911216/9bcadf94-cf32-11e5-886f-668030669fff.png)

**Comment by bengotow** [comment]
Hi @khanshakeeb thanks for upgrading N1! Do you know if the app was running while you updated it by any chance? Does restarting the app resolve the issue? I think we've seen this happen before if you move the app on disk while it's running.

**Comment by khanshakeeb** [comment]
This bug was came to first time when I had upgraded but now its working fine so I am going to close it

Thanks
