### ISSUE TITLE
Accounts (seemingly) lost, stuck in onboarding

### ISSUE THREAD

**Issue by peeinears** [nylas/N1#1265]
When I opened my computer after it was asleep, Nylas was just an empty interface. I quit Nylas and reopened it to find myself back at the onboarding screens, despite having been using Nylas with 5 Gmail accounts for weeks. More, it won't even let me reauthorize my accounts to start over. I get "Something went wrong! Please try to connect your account again."

**Comment by bengotow** [comment]
Hey @peeinears - that's no good. Do you know if you happened to be out of disk space when your computer woke back up? This could be related to #897.

**Comment by peeinears** [comment]
I didn't see the usual "startup disk is almost full" dialog, but looking at my system.log it looks I did run out of disk space. I have 8+ gigs free now after restart, but must have filled up with swap and saved state when my computer went to sleep. Dang!

Is there a fix?

**Comment by jstejada** [comment]
cool, feel free to reopen this if the issue persists. thanks!
