### ISSUE TITLE
download save should remember last location

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1268]
Currently the download folder is always set to ~/Downloads, would prefer it default to last saved location.

**Comment by bengotow** [comment]
Hey! I don't think this is standard Mac behavior (which is lame) but I think it'd be a good idea to implement. As a side note, you can get this behavior in all Mac apps using http://www.stclairsoft.com/DefaultFolderX/.

**Comment by bengotow** [comment]
This has been fixed in 7219dd91d749f02f7d482501c08c46a7a4cb0df7 and will land in the next release. :+1:
