### ISSUE TITLE
Inconsistent Sidebar in Single panel and Two Panel

### ISSUE THREAD

**Issue by scottix** [nylas/N1#1269]
In single panel mode I get the Sidebar which is good and emails in the Panel which is what I want.
When I click on an email the Sidebar disappears. Why does it disappear?
In two panel I have the Sidebar and list and preview pane. When I click a message the sidebar doesn't disappear.

What is going on with the sidebar and why does one option affect the other? Can I have an option to always display Sidebar?

**Comment by jstejada** [comment]
hey @scottix thanks for reporting this. do you mean the left sidebar or the right sidebar? could you send a screenshot? thanks!

**Comment by scottix** [comment]
So in Single Panel the top view includes the sidebar on the left.
![nylas_075](https://cloud.githubusercontent.com/assets/435727/12926752/b5fb9bb0-cf19-11e5-8a5d-4919dd5ef568.png)

When I click on an email the sidebar on the left disappears.
![nylas_076](https://cloud.githubusercontent.com/assets/435727/12926759/b9d73e10-cf19-11e5-9f63-fd45e7fbcc38.png)

I understand some people may want this but I want to keep the sidebar pinned all the time.

**Comment by bengotow** [comment]
Ahh I see—thanks for the screenshots! Closing as a dup of #101
