### ISSUE TITLE
Erase deleted items

### ISSUE THREAD

**Issue by alesf** [nylas/N1#127]
In Mail.app you delete items and they still stay in folder with special flag marking them as hidden/deleted.
In N1 they are still shown.
If I run "Erase Deleted Items ..." in Mail.app the messages in N1 also disappear.

**Comment by bengotow** [comment]
In N1, moving a message to the trash just moves it to the "Trash" folder on your IMAP account, or to "all mail" on Gmail. We currently don't have plans to add an "Erase Deleted Items" feature (where mail is permanently deleted from the IMAP server) but I've added it to our open source roadmap here: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap. Feel free to upvote it if you've got a Trello account!

Also—if you Erase Deleted Items in Mail.app, it should definitely sync both ways with N1. Hope that helps in the meantime!
