### ISSUE TITLE
confusing copy: "Sending draft... (1)" 

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1275]
Odd copy: "Sending draft... (1)" 

![image](https://cloud.githubusercontent.com/assets/547354/12933985/3379460c-cf40-11e5-91c6-d9b193b53c62.png)

**Comment by bengotow** [comment]
Hmm should it say "Sending message..." or something else entirely?

**Comment by jweinstein** [comment]
"Sending message" is clearer. "draft" is the odd word.
