### ISSUE TITLE
There's no way to see where N1 is getting Contact information.

### ISSUE THREAD

**Issue by rittbys** [nylas/N1#1276]
There's some really silly and outdated info showing up under the sidebar contact display, and I've got no idea where it's coming from. Any way to manually set that or at least see where it's getting that info from?

EDIT: OK so I found where it's getting the info (I think) but there's still no way to update it because it's very outdated.

**Comment by jackiehluo** [comment]
@rittbys You can go to FullContact's website to [file a claim](https://www.fullcontact.com/privacy/claim/)! Once you verify your email address, you can make edits to the contact information, and we'll start pulling the right data.

**Comment by rittbys** [comment]
Thank you!

**Comment by rittbys** [comment]
It would be great if we could edit this locally to set others' contacts manually, instead of relying on them to have a claimed FullContact.
