### ISSUE TITLE
Full 64 bits version on Windows

### ISSUE THREAD

**Issue by wget** [nylas/N1#1277]
Wrt [the discussion we had on Twitter](https://twitter.com/nylas_crew/status/697193198381199360), it would be great if N1 could be provided as a native 64 bits version for Windows.

You may want to say, as Windows x64 does support 32 bits apps this isn't a problem. But what about Windows Server user using the system as a Terminal Server with SysWOW64 disabled? :-)

**Comment by mbilker** [comment]
Electron includes support for Windows x64, so this should not be blocked on Electron for support. This requires an overhaul of the build system to account for building on Windows x64 and ia32.

**Comment by bengotow** [comment]
Re: `Windows Server user using the system as a Terminal Server with SysWOW64 disabled`

Is this common? We've put off updating our build process simply because it seemed like 32/64 bit didn't matter much to most Windows users, and the app wouldn't benefit significantly from 64-bit architecture.

**Comment by wget** [comment]
@bengotow This begins to become common at Windows Server sysadmins who are conscious of security. But as soon as the end users require a 32 bits app like N1, we need to reenable SysWOW64: rather annoying and this is loosing interested.

We can also cite the ability to have [full ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization#Microsoft_Windows). Since GPG is being integrated to Nylas, this could help preventing the keys from being stolen with ease.

You have also the ability of recovering some space: removing a bunch of Gio when disabling SysWOW64.

I'm not a Windows sysadmin. Gonna ask other sysadmins at my company who are more focused on the Windows platform, if they have more idea.

But if you had to choose between prioritizing this bug or #1278, I would prefer having the latter implemented instead of the current one.

**Comment by mbilker** [comment]
@wget I will say there "may" be GPG on Windows, but it will be implemented through the GPG command line like I have it done now. ASLR is important, but that does not protect against running a command.

**Comment by wget** [comment]
@mbilker Ok. This is what I thought. My argument for ASLR is not valid in this case as the GPG management will not happen in the N1 process. ;-)

**Comment by mbilker** [comment]
Still it is important to build N1 for multiple architectures.

**Comment by mbilker** [comment]
Also, my plugin runs GPG from a separate process from the rest of N1.

**Comment by KevinMartin** [comment]
Any updates on adding a 64-bit version?

**Comment by jackiehluo** [comment]
Closing this issue for now—at least currently not in the scope of this project!

**Comment by wget** [comment]
@jackiehluo Common. You like learning new things. Porting to x64 should be a great challenge for you :-)
