### ISSUE TITLE
Email/Message has no body (body height 0)

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1280]
Hard to reproduce but it feels like if you open a message just as it hits your inbox, it doesn't load the body in the email thread view. If I open it a few seconds later, the body is there.

**Comment by martnu** [comment]
I see this as well, the height of the iframe that displays the message gets set to 0 pixels.

**Comment by olofsellgren** [comment]
+1
0.4.5-b0ec335

**Comment by akmcbroom** [comment]
+1 as well. Version 0.4.5-b0ec335 (0.4.5-b0ec335)

**Comment by bonaldi** [comment]
+1, although for me it's not related to the time the message has arrived: it will happen to me with old messages as well.

**Comment by MosheZada** [comment]
+1 for me, OS X el capitan `Version 0.4.5-b0ec335 (0.4.5-b0ec335)`

**Comment by madole** [comment]
+1 I see this too on Ubuntu. Version 0.4.5-b0ec335

**Comment by jstejada** [comment]
Another incidence on Zendesk: https://nylas.zendesk.com/agent/tickets/3976

**Comment by emorikawa** [comment]
Margaret just reported this as well. Apparently all of Chews emails consistently show this behavior.

**Comment by jackiehluo** [comment]
Another incidence from @grinich.

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
