### ISSUE TITLE
cycling past email list 

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1281]
You can cycle past the last message in your inbox into a weird non selected state for 1 position then it cycles to the top message. I'm using gmail shortcut `j` to do this

**Comment by bengotow** [comment]
Hmm - I'm not able to get this to cycle. It /should/ just stop on the last item. Do you know how many items (roughly) are in the list you're viewing?

**Comment by jweinstein** [comment]
Can't repro, will close for now
