### ISSUE TITLE
Exchange connection not removed on account remove

### ISSUE THREAD

**Issue by zellerda** [nylas/N1#1285]
Hi I found an other issue with Exchange.
When you delete an Exchange account in Nylas app, the connection between Nylas website API and Exchange OWA still persist and cannot be deleted, if I delete it in Options > Phone it reappear a few seconds later.

![issue](https://cloud.githubusercontent.com/assets/140013/12940330/28d1cc50-cfc8-11e5-83a8-9c5833954cad.jpg)

**Comment by bengotow** [comment]
Hi @zellerda — thanks for filing this. The sync-engine will continue syncing your mailbox (in case you had other N1 installs or re-connected the account) and should stop connecting after about a week.

**Comment by manilx** [comment]
Same issue here. Connected an IMAP account. Didn't like the app and deleted the account and the app. It's still connecting to our server. This is no good!!!!!

**Comment by manilx** [comment]
Blocked the IP for now.

**Comment by jackiehluo** [comment]
You can now delete accounts on the Nylas Pro dashboard!
