### ISSUE TITLE
[FEATURE] Show unread count in menu mar 

### ISSUE THREAD

**Issue by joshhornby** [nylas/N1#129]
Similar to how Airmail displays an unread count. Much easier for people who have the docs hidden by default to see if they have mail.

<img width="244" alt="screenshot 2015-10-22 08 57 21" src="https://cloud.githubusercontent.com/assets/5455767/10659857/eed370fa-789a-11e5-848b-4b8e7c552f9d.png">

**Comment by bengotow** [comment]
Oh man—this would be really cool. I think that you could implement this as a plugin pretty easily using Electron's "Tray" API (should really be called "status bar" API on Mac OS X) https://github.com/atom/electron/blob/master/docs/api/tray.md. 

I'll add this to the open-source roadmap under plugin ideas: https://trello.com/c/yU5t6M8E/29-menu-bar-status-bar-widget-displaying-unread-count. If you're interested in putting it together, I'd be happy to help on our community slack channel.

**Comment by jstejada** [comment]
hey @joshhornby , we released this feature on our latest update! thanks.
