### ISSUE TITLE
account setup with webfaction mailbox shows: Error connecting to the server.

### ISSUE THREAD

**Issue by jfunez** [nylas/N1#1292]
Hi people,

I'm trying to setup my webfaction mailbox with Nylas N1 email client, selecting:

1. IMAP / SMTP Setup
2. Name: my name, Email: my email
3. Configure incoming email: IMAP server: mail.webfaction.com Port: 993, SSL: check, username and password retrieved form my.webfaction.com
4. Configure outgoing email:SMTP server: smtp.webfaction.com Port: 465, SSL: check, username and password retrieved form my.webfaction.com
5. Add account, -> shows: **Error connecting to the server**

I've tried several times in the last week, also double checked the credentials, server hosts, and ports, creating a new account on mozilla thunderbird and Kmail, both in the same computer, without problems. It doesn't work only with n1 app.

Anyone with the same problem?

**Comment by bengotow** [comment]
Hi—thanks for filing this. Going to close as a dup of #1288 because I think they're the same underlying issue.
