### ISSUE TITLE
Minimum window height

### ISSUE THREAD

**Issue by Scott-Fischer** [nylas/N1#1293]
Hey there, great project!

I was wondering what your methodology is for setting the minimum window height of the application frame? For an email client that is so hackable, it seems odd to me that I can only resize the height to a certain extent. 

My daily workflow on OSX requires a number of open application windows, which I have organized specifically and would love to be able to just see my top 3-4 latest emails. 

I haven't tried N1 on linux, but if the same situation applies, I can only assume that it would cause issues with some hybrid mouse/keyboard tiling window managers.

**Comment by bengotow** [comment]
Hey @Scott-Fischer — I think the minimum height of the main window was chosen arbitrarily. We can make it smaller, but there's definitely a "minimum useful height" so we probably won't make it 0.
