### ISSUE TITLE
My Exchange mail doesn't receive mails since last update

### ISSUE THREAD

**Issue by CyanBalloon** [nylas/N1#1294]
Since last update, I can't receive mails from my Exchange mail configured on GoDaddy.

**What works**
- When I add the Exchange mail, it works as expected. The credential system works.
- I can send e-mails.

**What doesn't work**
- I don't receive incoming mails and can't fetch those who are already in my inbox.

**Comment by bengotow** [comment]
Hi @CyanBalloon — thanks for filing this. We're investigating an issue with some exchange accounts where mail fetch became backlogged, and after a few hours N1 caught up. Definitely shouldn't happen, but could you try leaving N1 running in the background for an hour or two and see if your mail eventually appears?

**Comment by CyanBalloon** [comment]
I did let it run for a couple hours, and it fixed the problem, seems like we can close this one.
