### ISSUE TITLE
When sending, attachment causing 5.7.0 Google Security Issue displays no error

### ISSUE THREAD

**Issue by fthuin** [nylas/N1#1296]
Hello eveyone,

I was trying to send an email with a .zip attachment containing source code and .jar files. Nylas N1 was showing "Sending draft..." looping forever... So I tried with thunderbird and this error comes out, it looks like it is not handled with N1: 

5.7.0 This message was blocked because its content presents a potential
5.7.0 security issue. Please visit
5.7.0  https://support.google.com/mail/answer/6590 to review our message
5.7.0 content and attachment content guidelines. i2sm4459913wjx.42 - gsmtp.

When an error occurs, it would be good to have a pop-up saying it

Keep up the good work

**Comment by bengotow** [comment]
Hi @fthuin —thanks for reporting this! We fixed this in 0.4.10, and confirmed the fix by trying to attach an exe file to a Gmail draft. Enjoy!
