### ISSUE TITLE
Different errors with "Launch on system start"

### ISSUE THREAD

**Issue by cristianfb1989** [nylas/N1#1297]
Images:
![error 1](https://cloud.githubusercontent.com/assets/16965222/12966509/be1715de-d03d-11e5-9c41-f22d3561610c.PNG)
![error2](https://cloud.githubusercontent.com/assets/16965222/12966510/c2c85fc0-d03d-11e5-8ceb-fa59a53dcab3.PNG)
![error3](https://cloud.githubusercontent.com/assets/16965222/12966512/c53a9fde-d03d-11e5-8007-fa76574fd7e6.PNG)
![error4](https://cloud.githubusercontent.com/assets/16965222/12966514/c7024a92-d03d-11e5-8cfe-7442660299cd.PNG)
![error5](https://cloud.githubusercontent.com/assets/16965222/12966516/c8d3927c-d03d-11e5-9a1a-324eaeac25e1.PNG)

**Comment by mbilker** [comment]
Thanks for the report @cristianfb1989. The `setState(...)` warnings and the `EventEmitter memory leak` are known issues, but do not impact the functionality of N1.

The error with `reportError` is new. Could you post a full screenshot of the stack trace showing all the line numbers. An example of a full stack trace is:

![2016-02-10-22-19-29_1873x122](https://cloud.githubusercontent.com/assets/1266541/12968770/602a5646-d044-11e5-8caf-8e7615c4ba3e.png)

**Comment by cristianfb1989** [comment]
ok, when I appear that mistake again, I'll post it here, in this issue.

**Comment by cristianfb1989** [comment]
The error with "reportError" showme this:
![1](https://cloud.githubusercontent.com/assets/16965222/12990771/dc7433e2-d0ea-11e5-9418-8f669b0fc075.PNG)
![2](https://cloud.githubusercontent.com/assets/16965222/12990776/e28b8d3e-d0ea-11e5-99a2-1ecd897d5ab4.PNG)

Nothing more.

**Comment by bengotow** [comment]
Hey @emorikawa think this related to the other issue with launch-on-start? Want to merge it?

**Comment by mbilker** [comment]
@bengotow The `reportError` may be related to network stuff.

**Comment by bengotow** [comment]
Merging into #1252
