### ISSUE TITLE
Cannot add IMAP+SMTP account, with no auth on SMTP

### ISSUE THREAD

**Issue by Michael-A-D** [nylas/N1#1299]
The IMAP/SMTP account is my office account, on a private IMAP/SMTP server. I tried adding my IMAP/SMTP credentials, exactly as they are in thunderbird, the only difference is that SMTP settings in N1 do not allow "no authentification" mode, which is the mode I apparently use in thunderbird (the SMTP server is only accessible from local network, I guess that's why). Here are the settings I used:

IMAP server: mail.mycompany.fr
Port: 993
Use SSL: yes
Username/Password: correct IMAP server ones

SMTP server: mail.mycompany.fr
Port: 25
Use SSL: tried yes and no
Username/Password: correct IMAP server ones (if any login information exists on the SMTP server, that will be the same one)

When finalizing the IMAP/SMTP, N1 tries to connect to server (IMAP? SMTP? both?), and fails with error message: "Error connecting to the server", without any more information.

I don't know where to find any more verbose error log, please notify me if that's pssible!

**Comment by mbilker** [comment]
Thanks for the report @Michael-A-D. Is the mail server accessible from the public internet or only from inside your office. If it is available from the public internet without authentication, then that is a serious security threat.

**Comment by Michael-A-D** [comment]
Nah, it's only accessible from local network, for the obvious reasons we're thinking off. ;)

**Comment by mbilker** [comment]
@Michael-A-D Unless you run your own [Sync Engine](https://github.com/nylas/sync-engine), by default N1 will not be able to access your email account.

N1 hosts its own Sync Engine which connects to mail servers over the public internet.

**Comment by Michael-A-D** [comment]
Get it! Doesn't seem like that much trouble to set up a local sync engine, but how much will our sysadmin want to kill me?

Out of curiosity, what happens when N1 default sync engine is down?

**Comment by mbilker** [comment]
@Michael-A-D Nobody gets their Email, but that hasn't happened yet. I haven't even noticed downtime for upgrades.

**Comment by mbilker** [comment]
I doubt the sysadmin will kill you. A local Sync Engine does not support Exchange, but you only need IMAP and SMTP. It does not contact the outside world when using the IMAP/SMTP provider. It stores all of the email it downloads locally.

**Comment by mbilker** [comment]
If you run it on your machine it will consume a big deal of computing power as it polls the IMAP server to see if there is new mail.

**Comment by Michael-A-D** [comment]
Ok well, I guess I won't be using nylas for this account for now, I can't waste much computing power, and I'd understand that maintaining a sync engine on our servers is overkill in that case. Plus I'm not 100% certain I can tell that there is no security threat doing that.

Anyway, thanks for your time and answers, and keep up the good work! I guess I can close the ticket, and sum up the cause:

By default, N1 won't be able to sync up mails from an IMAP server that is not accessible from public internet.

**Comment by mbilker** [comment]
Same goes for Exchange servers.
