### ISSUE TITLE
Deleting mail from trash restores it to Inbox.

### ISSUE THREAD

**Issue by YarmoM** [nylas/N1#1300]
Deleting mail from trash restores it to Inbox. This is, of course, not the expected result. Anyone else annoyed by this?

**Comment by bengotow** [comment]
Hey @YarmoM — currently the delete / backspace key is tied to a shortcut called "Remove from View" which is based on a Gmail behavior. Maybe we should limit that one to users who choose the Gmail keybindings and only tie it to `y`?

As a side note, if we change this behavior, pressing delete / backspace in the trash will do nothing. N1 does not provide a way to permanently delete your mail #599

**Comment by jstejada** [comment]
Hi @YarmoM , this will be addressed int #1460, which is currently in progress. Thanks!
