### ISSUE TITLE
Nylas crash when click to Send (Windows)

### ISSUE THREAD

**Issue by Salamafet** [nylas/N1#1303]
Since the last update when I click to send, Nylas crash (no error from windows).
When I restart Nylas, the mail is send.

Sorry for my bad English.

**Comment by bengotow** [comment]
Hi @Salamafet — do you know if this happens when you add attachments, or if there's anything specific about the message you're sending?

**Comment by Salamafet** [comment]
Hi @bengotow,
This happens only when I create a new message. If I respond to an email everything works correctly.

**Comment by Salamafet** [comment]
For the first time since the last update I have send an email without crash.

**Comment by Salamafet** [comment]
No more crash since the last update.
