### ISSUE TITLE
Plugin returns "cannot find module underscore"

### ISSUE THREAD

**Issue by rittbys** [nylas/N1#1306]
I'm not sure if this is the right place to put this, but I don't really see what's causing this issue. I'm developing ![this plugin](https://github.com/rittbys/N1-YouTubePlugin), and it's telling me that "underscore cannot be found" when it's required in youtube-sidebar.coffee (yes I'm aware that everything says sidebar but it's drawing a button). I don't understand this as it works almost identically in the "View it on GitHub" internal package. I'm also declaring it as a dependency in package.json. Some help on this issue would be appreciated (and any other bugs you may find), or at least direction to the correct place to post this.

**Comment by bengotow** [comment]
Hey @rittbys! Thanks for filing this—when you install a plugin by choosing "Install a Plugin Manually..." from the menu it copies it into the packages folder and also installs the dependencies listed in the `package.json` file.

If you just added the dependency to your package.json file, or if you dragged the package into the packages folder manually, you'll need to enter that directory and run `npm install` to install underscore. (Even though it's used in the core app, packages still need to require it individually).

We'll be improving this process a lot in the future - sorry for the hassle!

**Comment by rittbys** [comment]
I added it to the dependencies listed in my package before I installed it
manually from the directory. My package was being developed while it was
sitting in .nylas/dev/packages, and I installed it from there using the
"Install package manually..." button within N1; this made a copy in
.nylas/packages. Do I still have to run npm install if I installed the plugin
after the dependency was listed?

**Comment by mbilker** [comment]
I assume you switched out of developer mode in N1.

You do not need to run `npm install` if you installed the plugin after you added the dependency to `package.json`.
