### ISSUE TITLE
type in search bar, hit enter... it removes some of the text before search

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1307]
![screen capture on 2016-02-11 at 11-14-18](https://cloud.githubusercontent.com/assets/547354/12987531/6170c36a-d0b1-11e5-82ad-47b3cc6c6a03.gif)

**Comment by bengotow** [comment]
Ahh good catch—I think this is what @khamidou was reporting as well. At the moment, the only fix is to wait a moment for the suggestions to "catch up" before submitting your query. Willfix.
