### ISSUE TITLE
Do not auto-capitalize email addresses

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1308]
![screen capture on 2016-02-11 at 11-56-12](https://cloud.githubusercontent.com/assets/547354/12988659/8afeed2e-d0b6-11e5-916b-d8f606bd4efb.gif)

Odd that it shows as `F` rather than `f`

**Comment by bengotow** [comment]
Ahh man that's super weird. I've noticed this doing strange things in other places as well. Going to rip out the autocapitalization and we'll put it back in a more moderate way if anyone complains.
