### ISSUE TITLE
N1 quits after attempting upgrade

### ISSUE THREAD

**Issue by iamkirbatron** [nylas/N1#1309]
When trying to upgrade from 0.3.45-3b5880e to 0.4.5-b0ec335, Finder asks permission to install helper, which then displays the update ribbon in Nylas. Clicking 'Install Now' causes Nylas to close without upgrading.

OS X 10.11.3 El Capitan

**Comment by davidangel** [comment]
Any workaround for this problem? Seems to survive manual re-install/updates.

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
