### ISSUE TITLE
Can't send emails to proper addresses.

### ISSUE THREAD

**Issue by psychonaut** [nylas/N1#131]
Verification for email addresses is too aggressive. I can't send emails to addresses which are valid but probably not covered by regex check. For example "ars.vision" is valid domain and I've got:

![zrzut ekranu z 2015-10-22 11-04-07](https://cloud.githubusercontent.com/assets/807289/10661303/5dd00786-78ad-11e5-8b29-222c1ddec2fe.png)

**Comment by bengotow** [comment]
Hi @psychonaut  - this was actually resolved yesterday in a926f84bc1a7728e93e63bb7222a3e7186555f85, so it should be fixed in the next update. Stay tuned!

**Comment by psychonaut** [comment]
Thank you! :+1:
