### ISSUE TITLE
Quoted Text sections not always collapsed into "Show Previous" button correctly

### ISSUE THREAD

**Issue by bherila** [nylas/N1#1312]
"On Feb 11..." text should be collapsed into the "Show Previous" section. 

Example: (truncated to protect user's privacy)

![image](https://cloud.githubusercontent.com/assets/1422004/12989311/c2112e14-d0b9-11e5-8a76-e45013962f0c.png)

Also, sometimes, the ENTIRE message is collapsed!

Example:

![image](https://cloud.githubusercontent.com/assets/1422004/12989329/ebdcfcfa-d0b9-11e5-950d-f7eb3270334f.png)

**Comment by emorikawa** [comment]
@bherila I just fixed the quoted text parsing in e7ebf0ba2cb3a6abb4c958fa3ccf7812988a0dbc

It should go out in the next release.
