### ISSUE TITLE
can't open main app when compose opened via mailto link

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1314]
1. N1 open but minimized to dock
2. launch compose via mailto
3. can't open main app via click or cmd-tab

**Comment by mbfrydman** [comment]
Same behaviour if you're in N1 main app, launch a separate composition window and then close the main app.

There is no easy way to get the main window back without closing the mail you'e writting.

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
