### ISSUE TITLE
Email is hidden when clicking on an unread mail.

### ISSUE THREAD

**Issue by spetz83** [nylas/N1#1315]
Ubuntu 15.10

After the latest update, when I get a new email and click on it to view it in the right-hand pane, the body of the email will disappear. The only way to get it back is to click on a different email and then click back to the email I was originally trying to read.

**Comment by loganwedwards** [comment]
Same on Mac OSX 10.11.3.
Version 0.4.5-b0ec335 (0.4.5-b0ec335)

**Comment by niklasfrykholm** [comment]
Also on Windows. Happens somewhat randomly.

**Comment by mbilker** [comment]
I experienced the same phenomenon recently with a recent message. The message appears to download and display correctly, but then quickly disappears as if caused by a `MessageBodyProcessor.resetCache`.

**Comment by bpartridge83** [comment]
Exact same experience here, maybe 30% of the time.  Going back to the email appears to be visible.

**Comment by omonk** [comment]
+1 on this, Mac 10.11.12, seems to be more often than not with me.

**Comment by vrcca** [comment]
1+ Elementary OS 0.3.2 Freya (64-bit)

**Comment by davidstagg** [comment]
This is also happening for me, roughly 95% of the time:

OS X Yosemite v 10.10.5
Nylas Version 0.4.5-b0ec335 (0.4.5-b0ec335)

Quick GIF of the issue:
http://i.imgur.com/gPT7Clf.gif

**Comment by jstejada** [comment]
hey, this has been fixe in the latest release. enjoy!
