### ISSUE TITLE
"Smart zoom" OSX "double-tap with two fingers" gesture causes the application to be zoomed

### ISSUE THREAD

**Issue by yamadapc** [nylas/N1#1316]
I accidentally tapped the touchpad with two fingers with the _"Smart zoom"_ OSX gesture enabled and this happened:

<img width="1458" alt="screenshot 2016-02-11 19 44 49" src="https://cloud.githubusercontent.com/assets/3923654/12992118/b7bed75a-d0f9-11e5-8d0e-e814ce5ba71d.png">

**Comment by bengotow** [comment]
Hey @yamadapc —I believe this was fixed just before the last release - can you check that you're running 0.4.5?

**Comment by yamadapc** [comment]
Hey @bengotow; I'm running 0.4.5-b0ec335

**Comment by bengotow** [comment]
Thanks @yamadapc — do you know if you have interface zoom on in the app's settings? (Where you can choose 80% / 120%, etc.) I haven't been able to reproduce yet.

**Comment by bengotow** [comment]
This should be resolved in 0.4.14. Let me know if the issue persists!
