### ISSUE TITLE
pasting in To: line overwrites text

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1317]
![screen capture on 2016-02-11 at 14-43-54](https://cloud.githubusercontent.com/assets/547354/12993297/19c0d70e-d0ce-11e5-95d9-160486543c9f.gif)

Pasting should append rather than overwrite. 

with `esting` on the clipboard, and `iamt` in the To: line, it should be `iamtesting` after paste but paster overwrites and just has `esting`

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
