### ISSUE TITLE
Feature request: Add option to remove conversations view

### ISSUE THREAD

**Issue by CyanBalloon** [nylas/N1#1318]
Hi there, 

I love N1, it's the best e-mail manager I've seen yet. Thing is, there's one feature that's been tormenting me ever since I've started using it. **The "gmail conversation" view**.

I'd love to have an option to disable that and **see each e-mail separately**. Managing "conversations" instead of simple mails is tortuous.

Thanks for the consideration!

**Comment by grinich** [comment]
This would be pretty insanely hard for us to do at this point, since the entire app is really designed around threads (like other modern mail apps). 

Not on any immediate roadmap.

**Comment by CyanBalloon** [comment]
Fair enough, no problem about that, it's still very good. If the Nylas members would rather close this, go ahead.

**Comment by bengotow** [comment]
Closing as a dup of #439 - there's a longer explanation there if you're curious.

**Comment by rml1111** [comment]
I tried Nylas again after relaunch as Nylas Mail. Unfortunately, the inability to disable conversations is deal-breaker for me. I subsequently tried Newton as suggested in this forum and will proceed with using that as my default mail client. Overall Nylas is impressive and would be my preferred choice, but the ability to disable thread view is an absolute requirement in a mail client.
