### ISSUE TITLE
When changing the theme in preferences, menu bar disappears.

### ISSUE THREAD

**Issue by herrowna** [nylas/N1#1319]
I realise this is happening when a new line is added to `theme` in the `config.cson` file,  while the old theme is not removed, therefore there are 2 themes defining the UI. 

This makes the menu bar on top disappear, and I have to manually remove the theme from my terminal in order to access the menu again.

**Comment by mbilker** [comment]
Thanks for the report @herrowna. Could you take a screenshot of this occurrence?

This is not typical and you  should change the theme through `Preferences -> General`.

**Comment by herrowna** [comment]
Hi @mbilker,

Terribly sorry for the late reply.

![08ca6ed7-6a9f-4a1a-b918-457e3b596715](https://cloud.githubusercontent.com/assets/6374909/13133536/1ba04d8e-d637-11e5-9bbc-2d7562fb507f.png)
![808ed6f6-a8b1-4fdf-bbbb-8e03912332bb](https://cloud.githubusercontent.com/assets/6374909/13133535/1b9e304e-d637-11e5-9b19-d675de0e3dc3.png)

Yes, I changed the theme using `Preferences -> General`.

**Comment by jackiehluo** [comment]
Hey, @herrowna! There should always be two themes defining the UI: the active theme and the base theme, Light, so that's expected. Which OS are you using, and have you updated to the latest versions of N1 and the theme for Ido?

**Comment by herrowna** [comment]
Hi @jackiehluo, I am using Ubuntu 14 LTS. And yes, I have the latest version of both the Ido theme and N1, granted Ido must still be unstable. We can close this issue and I will report on Ido instead.
