### ISSUE TITLE
Can't Connect to Exchange server

### ISSUE THREAD

**Issue by waynew** [nylas/N1#132]
When I put in my name, address, and username I just get an 'Error connecting to the server'

Anonymized data:

Name: Wayne Werner
Email: me@example.com
Username (tried both with, and without): example\me
Password: ********* ( :trollface: )

In Mail.app on mac, I do have to adjust my internal server to mail3.example.com

**Comment by smitec** [comment]
Having the same issue, also I suspect due to not being able to set the server.

**Comment by chauncey** [comment]
I have this issue as well. Our Exchange server handles 2 domains and the server's url is not the same domain as my email address. And since we don't have autodiscover setup, most clients will try to auto-configure and then prompt me for the server's address.

**Comment by nbostrom** [comment]
I can confirm. N1 doesn't seem to support this atm. Having different domains for email address and mail server seems to be a common case for people at work.

**Comment by bogem** [comment]
Same with gmail

**Comment by WimDeMeester** [comment]
I also have this problem on Linux (fedora 22). However, I don't have this problem on my mac, there everything seems to work.

**Comment by bogem** [comment]
I have this bug on mac with gmail though

**Comment by waynew** [comment]
Looks like the newest update has an exchange server option... but still no dice. Still get 'Error connecting to the server'.

When I open the activity window, it looks like it's trying to connect to `"https://:@api.nylas.com/auth?client_id=thisisnotreallyit"` and gets a 404 in response...

**Comment by waynew** [comment]
Further update - when I copied the command and ran it myself, I got this response:

`{"message": "Error connecting to the server", "type": "auth_error", "error": "connection_error"}`

So, it looks like Nylas is trying to connect to my company Exchange server, and on the other end it's giving an auth error?

**Comment by smitec** [comment]
The latest update has fixed this issue for me

**Comment by dtauer** [comment]
Yep, this updated worked for me too.

**Comment by WimDeMeester** [comment]
Tried the latest update (0.3.20) and still not able to connect to my exchange account using Linux. Mac still works fine.

**Comment by chauncey** [comment]
It took a couple of tries with the same account information for the Exchange to connect and be happy. It's brought down email and is notifying me of messages.

64bit Arch Linux

**Comment by waynew** [comment]
Still no dice for me. What's super weird - I can connect to `https://mail3.example.com/ews/exchange.asmx` using Chrome just fine. It asks me for my username and password, and I put `me` in there (from `example\me`) and my password and it gives me a great big ol' honking WSDL file. It seems like maybe the issue is between Nylas and my exchange server?

**Comment by ChristopheLux** [comment]
Hello

Looping on adding account never ending...anywhere i could look into the log 
Ubuntu 64-bit
and for information Nylas is connecting as Iphone for exchaneg and taking 2 phones slot out of 10 out of the box

Thanks for the great tool btw it is cool to see competition in email client

**Comment by tiann** [comment]
0.3.25-c174641 (0.3.25-c174641)  still has the problem, log:
```
{"host":"weishu-mbp","timestamp":"2015-11-27T06:13:01.197Z","payload":{"error":{"stack":"Error: ETIMEDOUT\n    at /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/request/request.js:808:15","message":"ETIMEDOUT","code":"ETIMEDOUT","connect":false},"response":{"statusCode":0},"requestOptions":{"path":"/auth?client_id=eco3rpsghu81xdc48t5qugwq7","method":"POST","body":{"settings":{"password":"xxxxxxxxxxxxxx","eas_server_host":"xxxxxxxxxxx","username":"xxxxxxxxx"},"name":"xxxxxxxxx","email":"xxxxxxxxxx","provider":"exchange"},"returnsModel":false,"timeout":30000,"auth":{"user":"","pass":"","sendImmediately":true},"url":"https://api.nylas.com/auth?client_id=eco3rpsghu81xdc48t5qugwq7","json":true,"startTime":1448604751156},"statusCode":0,"name":"APIError","message":"Error: ETIMEDOUT"}}
```

**Comment by ChristopheLux** [comment]
In fact it is working after restarting Nylas....should be a good idea to have some kind of indicators of progress on synchronizing

**Comment by backslash451** [comment]
My version on N1 is 0.3.32-b11131d, and on Mac (OS X El Capitan) N1 cannot connect to my company exchange server.

```json
{"host":"MacBook-di-Roberto.local","timestamp":"2015-12-30T13:42:45.722Z","payload":["ActionBridge: onboarding Action Bridge Broadcasting: didMakeAPIRequest"]}
{"host":"MacBook-di-Roberto.local","timestamp":"2015-12-30T13:42:45.723Z","payload":{"error":{"stack":"Error: ETIMEDOUT\n    at /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/request/request.js:761:15","message":"ETIMEDOUT","code":"ETIMEDOUT","connect":false},"response":{"statusCode":0},"requestOptions":{"path":"/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=6a8279f7-5255-4660-b92c-d0a1f77cd439","method":"POST","body":{"settings":{"username":"*****","password":"*****","eas_server_host":"https://ews.rai.it/ews/exchange.asmx"},"name":"Roberto Belardo","email":"roberto.belardo@rai.it","provider":"exchange"},"returnsModel":false,"timeout":30000,"auth":{"user":"","pass":"","sendImmediately":true},"url":"https://api.nylas.com/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=6a8279f7-5255-4660-b92c-d0a1f77cd439","json":true,"startTime":1451482935710},"statusCode":0,"name":"APIError","message":"Error: ETIMEDOUT"}}
{"host":"MacBook-di-Roberto.local","timestamp":"2015-12-30T13:42:45.737Z","payload":[{"eventName":"Auth Failed","eventArgs":{"errorMessage":"Request Aborted","provider":"exchange","platform":"darwin","version":"0.3.32-b11131d","n1_id":"6a8279f7-5255-4660-b92c-d0a1f77cd439","token":"9a2137b80c098b3d594e39b776ebe085","mp_lib":"node"}}]}
```

**Comment by kav-ya** [comment]
Folks - thanks for the report!
Could you please email support@nylas.com with the email addresses you're attempting to connect? Since this is personal information, we ask that you email us rather than posting here. We'll take a look.
