### ISSUE TITLE
Unable remove "unread" icon and delete emails.

### ISSUE THREAD

**Issue by MrSassyBritches** [nylas/N1#1325]
When I click some emails the "unread" indications will not go away. 
![image](https://cloud.githubusercontent.com/assets/7945291/13018565/782a8bbe-d187-11e5-858a-59eda76fce66.png)

And if I click delete, then the emails just pop back up withing seconds. The only way I can delete is through my browser or another email application.

**Comment by bengotow** [comment]
Hey! I think this was related to an issue we fixed in `0.4.25`, where the thread list would become detached from the database. Give the latest version a shot and let me know if you still see this problem!
