### ISSUE TITLE
QuerySubscription: duplicate IDs error

### ISSUE THREAD

**Issue by cristianfb1989** [nylas/N1#1327]
![1](https://cloud.githubusercontent.com/assets/16965222/13021426/de7e5968-d1b9-11e5-84ac-7e2e6a432ae1.PNG)
![2](https://cloud.githubusercontent.com/assets/16965222/13021428/e1257b56-d1b9-11e5-86a2-313cd274f346.PNG)

**Comment by cristianfb1989** [comment]
Hi everyone! In addition to the errors shown in the pictures, the mail client reaches a point where it is re loading

**Comment by mbilker** [comment]
The first error is a warning from Node regarding an EventEmitter having more than 51 listeners and is not related to your error.

The second error is related to your issue and I experienced this. I solved it by closing N1, deleting `~/.nylas/edgehill.db*`, and then restarting N1 and allowing it to redownload all of the data.
