### ISSUE TITLE
Features missing from messages found using N1 Search

### ISSUE THREAD

**Issue by bherila** [nylas/N1#1328]
When I find a message using N1 Search, it shows in "All Mail" and I can't do any of the following things: 

* Delete the message (either from the results view or from the individual message view)
* Move the message (dragging to a folder like "Deleted Items" actually appears to work, but doesn't actually seem to do anything)
* See what folder/label the message was contained within

**Comment by bengotow** [comment]
Hey! We've fixed these issues in the last two releases - give it a shot and let me know what you think! Going to go ahead and close.
