### ISSUE TITLE
Inconsistent buttons position when selecting 1 or more emails

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#1329]
This issue is pretty annoying on big screens. If I select 1 email, the option/action buttons appear on the top left
![screen shot 2016-02-13 at 1 00 59](https://cloud.githubusercontent.com/assets/2094957/13024560/32b7d1d8-d1ee-11e5-83f8-c1ba9cc43286.png)

But if I select more, the action buttons appear on top left.

![screen shot 2016-02-13 at 1 01 07](https://cloud.githubusercontent.com/assets/2094957/13024570/525535bc-d1ee-11e5-8a38-1afaca6bf9b4.png)

I understand this is because preview, but why not leave the search field just to the right and always have the action buttons on the same position?

**Comment by tinybigstudio** [comment]
Always leave the action buttons on top

**Comment by tino** [comment]
Yes, this annoys me as well. Also, with some IMAP accounts the "Delete" button is not visible at all? Therefore in multi-account view the button is always hidden :/

**Comment by bengotow** [comment]
Hey folks—hmm, we've been thinking about redesigning this as well. Currently the action buttons are placed above the content they reference, but that space really doesn't have enough room for the content.

**Comment by grinich** [comment]
merging into #370
