### ISSUE TITLE
Cannot delete email on Exchange account

### ISSUE THREAD

**Issue by sebz** [nylas/N1#133]
Hi,

I've just installed N1 for Linux and I cannot delete emails on my Exchange account.
`DEL` key does nothing, `BACKSPACE` archives.

Any idea?
Thanks!

**Comment by bengotow** [comment]
Hey @sebz — thanks for filing this. Do you  have an "Archive" folder in your Exchange account? We added support for deleting emails on accounts with an "Archive" folder + Gmail in 4f34c8403fdf312ef4e5ff8efd1b6f7117bfd1bb, so I think this will be resolved for you in the next release. Stay tuned!

**Comment by sebz** [comment]
@bengotow yes I do. Great! But how is it related?
Do you have any idea when it'll be released ? :stuck_out_tongue:

**Comment by grinich** [comment]
deletion landed today :)
