### ISSUE TITLE
Implement OSX Keyboard Commands [] + [ [ ], [] + [ ] ]

### ISSUE THREAD

**Issue by p1gmale0n** [nylas/N1#1332]
it would be good support of OSX commands:
[] + [ [ ] = backward
[] + [ [ ] = forward

**Comment by bengotow** [comment]
Hmm - wasn't aware of these ones! I've added them to the Apple Mail shortcut preset.

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
