### ISSUE TITLE
...i686

### ISSUE THREAD

**Issue by handicraftsman** [nylas/N1#1333]
How much i must wait for i686 .deb package!? I am waiting for MONTHS! It's just SOME ARGUMENTS to add to implement i686!!!

**Comment by RaitoBezarius** [comment]
Why don't you build yourself?

**Comment by mbilker** [comment]
First of two, dupe of #254. Second of two, Travis is a 64-bit environment for both OS X and Linux. This is why there are 64-bit binaries for those platforms. Under AppVeyor for Windows, the build system uses the 32-bit compiler to build the native modules for N1. This is why the binaries for Windows are 32-bit.

**Comment by handicraftsman** [comment]
But you can use jenkins. Add some plugins and it will fit any language. It fully fits Vala, for example.

**Comment by mbilker** [comment]
@handicraftsman The Nylas team used Jenkins before switching to Travis, but from what I heard, the build system became out of date and was unable to be updated and Travis is a better platform for what they needed.
