### ISSUE TITLE
Mac Sharing Option with Nylas Unavailable

### ISSUE THREAD

**Issue by aaryanbatra** [nylas/N1#1334]
Dear Nylas N1 Developers,

I have a Mac Book Air and I am on version 10.11.3. OSX El Capitan. There has been a logn standing problem when sharing using the Nylas N1 app. Nylas N1 is my default mail client just to say. I think it'll be better to show pictures...

![problem 1](https://cloud.githubusercontent.com/assets/16775401/13032691/d4624b06-d33f-11e5-932b-cec7d74ffff9.png)
Above ^ Lets say I want to send this picture to my friend without going to Nylas and pasting it in there. Usually I would go to share and choose the option for mail. As you can see there is a more button.
![problem 2](https://cloud.githubusercontent.com/assets/16775401/13032690/d460cf92-d33f-11e5-9ce4-e96db987aaa0.png)
Above ^ After pressing the more button I come across finding out that Apple acknowledges that Nylas is an extension or a third party app, and it is clearly checked, but greyed out.

I did some searching online and I came across this forum: https://discussions.apple.com/thread/6995684?tstart=0

I'm pretty sure that I've pinpointed the problem you need to fix. It isn't apple's fault it's greyed out. If apple mail was my client then it wouldn't be greyed out... 

![problem 3](https://cloud.githubusercontent.com/assets/16775401/13032728/681b1d22-d341-11e5-96f8-fa789febb7ff.png)
Apple can't do anything about it because they can't change the developers apps only the developers can do it. Can you fix this problem? I really trust everyone at Nylas because truly you guys are awesome always trying to make history in the email world. I don't know if you will contact me on Git Hub, but if you need to just contact me on email

Stay Awesome,
Aaryan

**Comment by aaryanbatra** [comment]
When will this problem start getting reviewed on? I'm asking because everyone at Nylas has a lot of problems and bugs to debug so how long would this take?

**Comment by bengotow** [comment]
Hi @aaryanbatra — thanks for filing this and providing the images! This is something we're working on and should be in an update later this spring. There's a GitHub issue tracking it here: #483 so I'm going to merge this into that. Stay tuned!

**Comment by aaryanbatra** [comment]
Awesome!  
  

Regards,

Aaryan Batra

> On Feb 26 2016, at 4:56 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Closed [#1334](https://github.com/nylas/N1/issues/1334).

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1334#event-567065273).![](https://github.com/notifications/beacon/AP_
46VR_sSKXmGccSADpnax_4BJSPsuGks5pn_zBgaJpZM4HZ0vm.gif)
