### ISSUE TITLE
Deleting single email from discussion thread not possible

### ISSUE THREAD

**Issue by grahovam** [nylas/N1#1336]
I just tried your email client for the first time. I wanted to delete a single email from a conversation thread. It seems like, when I hit the delete button, the whole conversation thread gets deleted. So, I can either keep the whole conversation thread, or delete it. I can not delete a single email from it.

OS: Windows 8
Version: 0.4.5

**Comment by jstejada** [comment]
hi @grahovam , thanks for reporting this. I'm merging into duplicate #1263
