### ISSUE TITLE
in inbox message preview, display space for new lines 

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1340]
Email looks like:
![image](https://cloud.githubusercontent.com/assets/547354/13058045/302b85fc-d3d5-11e5-918d-4d382a062832.png)

Nylas inbox
![image](https://cloud.githubusercontent.com/assets/547354/13058061/4ae90de2-d3d5-11e5-8a74-27489897e662.png)

Gmail adds the spaces
![image](https://cloud.githubusercontent.com/assets/547354/13058068/5cad641a-d3d5-11e5-9f5e-1317b5d6737c.png)

**Comment by bengotow** [comment]
Hey @jweinstein thanks for reporting this. This is definitely something we should be doing. I'm going to transfer this to the sync-engine and we'll resolve it there.
