### ISSUE TITLE
Feature Request: Change font size, style, etc. in the composer

### ISSUE THREAD

**Issue by F7** [nylas/N1#1343]
Can I change font size for my email with style?
My colleague got my email and suprised "letters are too big."
I just request as the regular HTML email composing option.
Glad if I could see the preview when it's arrived.

**Comment by bengotow** [comment]
Hey @F7  - we'll be making the font size a bit smaller in the next release. It seems it was often just a bit too big. Stay tuned!

**Comment by F7** [comment]
@bengotow Cool. Looking forward to the release!

**Comment by chriscostuna** [comment]
Does this mean we will be able to determine the typeface and size ourselves soon?

**Comment by F7** [comment]
@chriscostuna Actually my request was not to decorate my text sent, but just make my text sent smaller when it's shown to reader.
As confirming that achived in the latest build, now I can use this again and start sending emails to other people.

@bengotow Thanks for the update. Can I close this issue because I confirmed that my request has already been supported?

**Comment by jackiehluo** [comment]
Merging into #1087!

**Comment by Havok182** [comment]
Hi, I just stumbled here while I was also searching for solution. I am in windows and I did try other method of scaling workspace in config.json but whenever I click emails the font would resize to orginal.Luckily for me I use my monitor on 125% dpi. On windows 10 you can force nylas.exe in compatibility tab of its executable Properties to override the dpi scaling for the application, finally worked like a charm.
