### ISSUE TITLE
Gmail account wont update

### ISSUE THREAD

**Issue by MrSassyBritches** [nylas/N1#1344]
Looks like my google account isn't updating in N1.

I'm on Windows 10 (fully updated)

**Comment by bengotow** [comment]
Hi @MrSassyBritches — can you try re-adding the account to N1? Maybe your Google authentication token was revoked or you changed your password?

**Comment by MrSassyBritches** [comment]
I have recently changed my password, maybe like a week ago. And I have continuously signed out  then back in multiple times since then. Still wont work :/

**Comment by stevedude** [comment]
I may be having the same issue, only I can't even setup my Gmail account. It must have worked before because Nylas N1 is in my Google Account App List of accepted applications, however, when I try to add my account in N1, a window pops up to sign into my Google account but there is nothing for me to do and the account is not added in N1.

**Comment by axed** [comment]
Same here since Version 0.4.10-4e3595b (0.4.10-4e3595b) (Mac OSX 10.11.3)

**Comment by bengotow** [comment]
Hey folks! Could you download the 0.4.14 release and try again? If your account is still not syncing, you should see a bar at the top of the screen asking you to go through the sign in flow again.

**Comment by auvos** [comment]
Nylas won't sync any emails from my gmail account since March 8th. Running the latest 0.4.14 and using Ubuntu 16.04.

Inbox, Sent etc. - sync doesn't work for any folders.

**Comment by rodduenez-wt** [comment]
Since I updated to the latest version, every morning I come to work my google apps account stops syncing. The only way to get it to work again is to remove the account and re-add again. Seems like the login token is not being updated or something.

**Comment by AndPlagueFlowers** [comment]
I am still having this issue as well

**Comment by ftudisco** [comment]
I have the same issue. Nylas version 0.4.33, Ubuntu 16.04. 
No way my gmail account syncs ancy nre email. I can send but I dont receive the new messages!

**Comment by agustincordes** [comment]
Same problem, and I've tried reauthenticating the account several times. It's a Google Apps account.

This issue needs to be addressed ASAP -- I want to evaluate N1 Pro but it doesn't speak well if such a critical problem remains unfixed for months. I tested the trial version a while ago and still bumped into unreliable syncing issues.

**Comment by brchristian** [comment]
Running N1 04.45 on OS X 10.11.5. Haven’t been able to sync my gmail account since May 15th. Re-authenticating did not seem to help.

**Comment by agustincordes** [comment]
I stopped using this thing already. Very poor support and communication.

**Comment by jackiehluo** [comment]
Merging into #1868!
