### ISSUE TITLE
Nylas keeps loosing its configuration on OSX

### ISSUE THREAD

**Issue by brasilikum** [nylas/N1#1348]
I am using OSX El Capitan.
I started to try N1 a few weeks ago. When I first setup my accounts, not all where accepted, but the two that worked, worked well.
Then came the update a few days ago. The update worked, but N1 forgot everything I previously entered. I reentered all account information, this time it worked with all 3 of my accounts.
Today I tried to write an email, but I could only select one of my 3 accounts as sender. I restarted N1 and all account information is lost again. I would be willing to enter it a third time, but only if I know it will be the last time.
Please let me know which info you need for debugging. I would be pretty happy to leave ugly Thunderbird behind, but only if I know that N1 is stable enough.

**Comment by bengotow** [comment]
Hey @brasilikum — is there any chance you're out of disk space? This might be #897.

**Comment by brasilikum** [comment]
Nope, 40% left.

**Comment by bengotow** [comment]
Thanks—I'll see if we can narrow this down.

**Comment by bengotow** [comment]
This should be resolved in 5691fc88caf6047179d65ca0833f91578d6fbac5, which will ship in a patch this evening.

**Comment by brasilikum** [comment]
Unfortunately not. What can I do to help you reproduce?

**Comment by jstejada** [comment]
hi @brasilikum, this should be fixed with for #1133. Let me know if you are still having issues!

**Comment by brasilikum** [comment]
I do, this time it worked for some days. Then I installed the markdown plugin and enabled the developer mode. It did not show up so I closed N1. Now the configuration is lost again. Frustrating when you use 4 Accounts...
