### ISSUE TITLE
Exchange not syncing email reading/archiving

### ISSUE THREAD

**Issue by mfid** [nylas/N1#1349]
Apologies if this is a beta specific problem, but I have had the same issue for the past 2 updates. Currently on 0.4.5-b0ec335.

Only have one Exchange account, and I'm finding that new emails are being shown as they should, but after I read and archive in N1, they still remain unread and in my inbox on all other email clients.

**Comment by bengotow** [comment]
Hey @mfid—thanks for filing this. Could you email support@nylas.com and include the email address that you're having trouble with? That sounds like something we definitely need to fix. Thanks!

**Comment by jeancornic** [comment]
I am also experiencing the same issue.

**Comment by carlosingles** [comment]
I have the same issue as well, whenever I try to Archive an email on my Exchange account, it only gets moved in N1, when I check my phone or my emails through any other client, they are still in my Inbox.

N1 Version: 0.4.14-53cd69b (0.4.14-53cd69b)
Mac OSX Version: 10.11.3 (15D21)
