### ISSUE TITLE
Clicking link in feedback window does nothing

### ISSUE THREAD

**Issue by chadxz** [nylas/N1#135]
![screen shot 2015-10-22 at 8 38 14 am](https://cloud.githubusercontent.com/assets/309219/10666624/60101690-7898-11e5-84f2-a7d167de459c.png)

When I try to click any of the links on this page, nothing happens.

**Comment by alonisser** [comment]
+1

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. It's been resolved in 9ff6c4912c438898715c3afe69f97f061d6a51d5 and should be fixed in the next release.
