### ISSUE TITLE
Support Self-Hosted Nylas Sync Engine

### ISSUE THREAD

**Issue by pizzaops** [nylas/N1#1351]
Hi there! I'm toying with the idea of self-hosting my Nylas sync-engine, and ideally, I'd be able to point N1 at it via the GUI for the client.

Did a cursory search of open issues and didn't see this in there, but it's likely I just didn't think of the right search terms :smile:

**Comment by bengotow** [comment]
Hey! Yep—you can totally do that. Check out https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine to get started. I'll see if we can break that out into a separate file so it's easier to find!

**Comment by pizzaops** [comment]
Hi @bengotow, note that I said, "via the GUI for the client" :smile: 

So this issue isn't actually resolved, although if it's a wontfix in favor of the config file that's fine too I guess.

**Comment by joostrijneveld** [comment]
So, is this actually a `wontfix` in favor of the config file?

Is 'self hosting the sync engine' not something that you want to promote so prominently? Alternatively, a link to `configuration.md` (_"Self-hosted sync engine?"_) could already be helpful.
