### ISSUE TITLE
Add print preview and print settings

### ISSUE THREAD

**Issue by France82** [nylas/N1#1352]
For my use an important feature is some kind of print settings, and a print preview. I need to print mail for work and i need to know what i am printing.
A simple settings dialog (like gmail's webmail) is sufficient.
What do you think about?

**Comment by bengotow** [comment]
Hi @France82 — what do you currently see when you choose print? You should get a standard print dialog, like this:

![image](https://cloud.githubusercontent.com/assets/1037212/13092454/e6695274-d4b4-11e5-8ac6-9c07b3ddbd88.png)

**Comment by France82** [comment]
Hi @bengotow 
This is what I see in Windows 10. I can't choose headnote/footnote, I can't hide nylas' logo and I can't choose fit-to-page or zoom. The print preview is "under" the print dialog and I can't select it, I can only move the print dialog and scroll with mouse wheel, no zoom, no fullscreen.

![print](https://cloud.githubusercontent.com/assets/17158802/13103923/35beecee-d55a-11e5-8afb-e73dd023f330.jpg)

**Comment by darrenkenny** [comment]
It would be great if this could be (optionally) a two step process - i.e. print first brings up the preview, and from there you can decided if it's what you want, maybe make some minor changes, such as toggling some parts being printed, or page layout, etc. and see what it will look like before printing.

When you're finally happy with that, then click a 'send to printer' button to actually do print to paper.

**Comment by France82** [comment]
> It would be great if this could be (optionally) a two step process - i.e. print first brings up the preview, and from there you can decided if it's what you want, maybe make some minor changes, such as toggling some parts being printed, or page layout, etc. and see what it will look like before printing.
When you're finally happy with that, then click a 'send to printer' button to actually do print to paper.

Yes, I think this can be the way!
This is crucial for me and also for my colleagues.

**Comment by bengotow** [comment]
Thanks folks - I think we can break this into a two step process. For what it's worth, the way it's currently designed what you see is what you get. So the print out will have the same expanded / collapsed areas that you see in the main window.
