### ISSUE TITLE
Send button disappears when responding

### ISSUE THREAD

**Issue by Kashura** [nylas/N1#1353]
Click on an email -> click reply -> click on "show previous" to see the previous conversation, and the send button disappears. The only way to bring it back is to click on the addressee field and use a pop-out to continue the email in a separate window.

**Comment by bengotow** [comment]
Whoa that's no good. Any chance it's scrolling offscreen, and there's just not a clear affordance for the scrollbar? What platform are you using?

**Comment by Kashura** [comment]
Ben, 

I am on El Capitan 10.11.3 (clean install as well). I just tried to reproduce it, and seems to be an inconsistent bug, as this time the button scrolled off the screen. 
However, this issue brings up an additional request: how come signature doesn't get populated when following the above steps. No button to add the signature, and it is not being auto added, even though it is registered in the settings. 

Thanks!

**Comment by emorikawa** [comment]
@Kashura I have a strong feeling that some inadequate design for our send button may be contributing to this. I'm merging all of these issues into #1083.

Regarding the signature, make sure that you're sending from the account you set the signature for. We save one signature per email account. If you can see your signature in Preferences -> Signatures -> youemail@address.com, and it still doesn't show up when you create a new message from that account, please let me know and re-open an issue for that.

Thanks
