### ISSUE TITLE
PKGBUILD for sync engine?

### ISSUE THREAD

**Issue by andysaini** [nylas/N1#1357]
It'd be great to run the sync engine without the VM!

**Comment by darrenkenny** [comment]
Agreed, would really love to be able to build this natively on the version of Linux (or even Solaris?) that I've installed - primarily a list of dependencies would be useful and less dependency on apt only and support yum (RH) too for instance.

From what I can see it's primarily Python code, but there may be some of the dependencies that
are more OS specific? But at least you should be able to support most of the main Linux distros.

Vagrant is great for prototyping, but maybe it's time to move forward to providing a build that could maybe even be automatically included in the package repositories of leading-edge distros like Debian, Ubuntu or Fedora (I'm sure there are more, but they would be the main ones I've used)?

**Comment by bengotow** [comment]
Hey folks! Could you transfer this over to the https://github.com/nylas/sync-engine repository? (There may be an existing issue there, actually - I'm not sure.) The sync engine is primarily built to run on servers and running the open-source version locally has some side effects (like exposing all of your mail on port 5555), so we haven't encouraged people to install it. Would be good to ask that team though!
