### ISSUE TITLE
Launch on system start not working

### ISSUE THREAD

**Issue by ThePsionic** [nylas/N1#1358]
Windows 10, version 0.4.5. When checking the option and leaving the preferences menu, the box auto-unticks when coming back into the menu. Seems like the preference is not being saved.

**Comment by bengotow** [comment]
Hey! Thanks for filing this @ThePsionic —I think @emorikawa addressed this a few days ago and it'll be fixed in the next update. Evan can you confirm?

**Comment by bengotow** [comment]
Merging into #1252
