### ISSUE TITLE
Not using Gmail Image for Multiple Accounts

### ISSUE THREAD

**Issue by GEverding** [nylas/N1#136]
I have multiple gmail accounts with different images but the different images aren't showing up. Its using the first gmail account image for each additional account.

**Comment by bengotow** [comment]
Hey @GEverding — thanks for reporting this. The images used in the account switcher are currently the Gravatar images for each account. I've created a card on our open-source roadmap for pulling the Gmail avatars for Gmail accounts. Sounds like that's what you're looking for. Feel free to track the progress of the ticket there, or upvote it!

https://trello.com/c/xjQ5IWKI/38-pull-gmail-avatars-for-gmail-accounts-not-gravatars
