### ISSUE TITLE
[BUG] When deleting mail from trash.

### ISSUE THREAD

**Issue by rba-odoo** [nylas/N1#1361]
Hello there, Please find below details of issue.

OS: Ubuntu 12.04

Steps to reproduce:
1. Delete a mail from inbox via delete key or delete button
2. then try to delete a mail from trash. 

Current Behaviour:
 - The mail will again go back to Inbox

Expected Behaviour:
 - Mail should be deleted permanently.

Let me know if I am doing anything wrong

Regards,
Ronak Baxi
Odoo Developer
India

**Comment by jstejada** [comment]
hey @rba-odoo. we currently do not support deleting from trash as specified here: #599. Right now we are following the logic of the `remove-from-view` Gmail shortcut which moves to inbox while in trash, however, you are right in that the behavior of backspace/delete in the trash probably shouldn't move back to inbox.

I'm going to merge into #599, and this logic should be updated soon.
