### ISSUE TITLE
Shortcuts triggered while writing responses (v0.4.5)

### ISSUE THREAD

**Issue by rhoconlinux** [nylas/N1#1363]
I found a very serious issue in which, while I was writing the response of an email in the two panel view, the keyboard shortcuts were triggered, first deleting my response, then archiving the email. 
Thanks for your efforts.

**Comment by grinich** [comment]
Did you get a new message on the thread while composing your draft?





On Wed, Feb 17, 2016 at 9:12 AM -0800, "rhoconlinux" <notifications@github.com<mailto:notifications@github.com>> wrote:


I found a very serious issue in which, while I was writing the response of an email in the two panel view, the keyboard shortcuts were triggered, first deleting my response, then archiving the email.
Thanks for your efforts.

-

**Comment by rhoconlinux** [comment]
I got the message archived the first time. Then there was another shortcut that I don't know what was about to do, luckily I had a very slow connection, I just closed the app cause it was an important mail. 
I removed everything, reinstalled, and until now never happened again. 
cheers,

**Comment by bengotow** [comment]
Hey! This should be fixed now.
