### ISSUE TITLE
Collapsed participant state loses To/CC/BCC things

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1365]
This: 

![image](https://cloud.githubusercontent.com/assets/92417/13128141/8da1e744-d588-11e5-8e98-5d8addabbf8c.png)

When collapsed, now looks like this:

![image](https://cloud.githubusercontent.com/assets/92417/13128149/9adad93e-d588-11e5-806a-6ed61c96fa45.png)

But it should say `To: Rick Armbrust, CC: Jenny Haeg`

I believe this is a regression

**Comment by bengotow** [comment]
Hmm the Gmail behavior (which we previously copied) is to do `Rick, Jenny, Bcc: Ben`. It appears To: and Cc: are treated as a single set and not prefixed. We could certainly change the behavior though.

**Comment by jstejada** [comment]
closing this since its being punted for revision later
