### ISSUE TITLE
Unable to create new email

### ISSUE THREAD

**Issue by perry-mitchell** [nylas/N1#1366]
Using version **0.3.45-3b5880e**, I am unable to send a new email from any of my accounts (1 self-hosted, 1 gmail). Ctrl-N, the new message button and File->New do not open the New Email dialog.

I'm on Ubuntu 14.04 with nothing special going on.

**Comment by bengotow** [comment]
Hey @perry-mitchell — can you update to 0.4.5 and let me know if the issue persists?

**Comment by perry-mitchell** [comment]
Hi @bengotow, I've tried purging and removing in the software center, but when I install from the 0.4.5 deb release, all my settings and accounts are still present, and the icons are still broken.

What's more, is that the version doesn't change:
![n1_old_version](https://cloud.githubusercontent.com/assets/3869469/13169715/2f91a784-d6f0-11e5-89a0-43a39b5d4fb5.png)

**Comment by perry-mitchell** [comment]
This seems to be fixed in 0.4.9.
