### ISSUE TITLE
Shortcut icons missing in interface

### ISSUE THREAD

**Issue by perry-mitchell** [nylas/N1#1367]
Using version **0.3.45-3b5880e**, I'm missing several shortcut icons:

![n1_buttons](https://cloud.githubusercontent.com/assets/3869469/13138280/e934aa78-d62e-11e5-92f5-9831081ad909.png)

I'm on ubuntu 14.04, using the dark theme.

**Comment by VinceWilkie** [comment]
This shows up properly for me. Mac OS X Yosemite 10.10.5, using version **0.4.5-b0ec335 (0.4.5-b0ec335)**

**Comment by perry-mitchell** [comment]
Mine has further progressed into decay today when either the star or tag icon disappeared (don't remember which). I've been updating when N1 notifies me.

**Comment by bengotow** [comment]
Hey @perry-mitchell — hmm, that's really interesting. Is it possible that N1 updated while you were running it? We've seen this problem a few times on Linux but haven't been able to track it down. I believe it happens when N1 or it's resources are moved while the app is running...

**Comment by bengotow** [comment]
Gonna merge this into #732.
