### ISSUE TITLE
Labels and draft missing

### ISSUE THREAD

**Issue by taniadaniela** [nylas/N1#1368]
Hi. I'm using N1 in OS X, with a gmail account. But my drafts and labels aren't show in the client? any ideas?

Thanks.

**Comment by bengotow** [comment]
Hi @taniadaniela — can you try launching N1 again and see if your mail has appeared? Initial sync can take a while for some mailboxes.

**Comment by taniadaniela** [comment]
yes, I did that and it works. thanks.
