### ISSUE TITLE
New e-mail account in INBOX shows previous email's content

### ISSUE THREAD

**Issue by psoiree** [nylas/N1#1369]
When You create new e-mail accountand click on it in the INBOX section, it shows previous email's content, not the new one:

![screen shot 2016-02-18 at 2 25 45 pm](https://cloud.githubusercontent.com/assets/16561052/13144708/78447fa0-d64c-11e5-9d4b-412efc8224c3.png)

**Comment by jackiehluo** [comment]
Closing because this issue should be fixed!
