### ISSUE TITLE
Sidebar contact info is stale.

### ISSUE THREAD

**Issue by louim** [nylas/N1#137]
I haven't checked in depth how the contact infos are fetched, but when I look at mine in the right sidebar, they appear to be from a couple months ago (around august). Which is weird since I just installed N1 this week.

**Comment by bengotow** [comment]
Hey @louim! That sidebar pulls data from FullContact (https://www.fullcontact.com/) and we really need to switch to something better. It's stale fairly often, and also returns strange things for email addresses which are shared between individuals (like support@company.com). I'll see if we can get it swapped out for something else soon.

**Comment by grinich** [comment]
I'm going to close this since it's more a bug with FullContact than us. We're still planning on subbing this out for something better soon!
