### ISSUE TITLE
Cant delete mail item in search

### ISSUE THREAD

**Issue by krzkrzkrz** [nylas/N1#1371]
I have the following in `~/keymap.cson`:

```
'/': 'application:focus-search'
'd': 'application:delete-item'
```

When I search for mail. I have an item highlighted from the search results, but pressing `d` does not delete the item.

In preferences. If you have the option to delete messages with the backspace key. Pressing the backspace key on a searched item does not move the item to the trash.

I believe actions do not execute on searched items? Would be great if they did

**Comment by VinceWilkie** [comment]
The only way I got around this was by dragging searched items to my trash folder. No shortcuts worked. Delete button is missing from the top right action menu.

**Comment by bashok001** [comment]
About to open this. No option to delete present.

**Comment by jstejada** [comment]
hey everyone, this is related to #1460, and will be addressed with that issue, so I'm merging it in. Thanks!
