### ISSUE TITLE
Email get send without me actually clicking 'send'

### ISSUE THREAD

**Issue by natarius** [nylas/N1#1372]
I have had this happen now two times that I am still writing an email and it suddenly sends itself!

This is a major issue since its sending emails that I am still drafting to business contacts! So far I simply got super lucky that nothing embarrassing slipped through!

**Comment by grinich** [comment]
Can you check whether the email actually sent or was just marked as sent in N1? (Check gmail/etc. sent folder)

**Comment by natarius** [comment]
fuck! you are correct...it didn't actually send the email, but just flag it as
send :(

> On Feb 18 2016, at 1:16 pm, Michael Grinich &lt;notifications@github.com&gt;
wrote:  

>

> Can you check whether the email actually sent or was just marked as sent in
N1? (Check gmail/etc. sent folder)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1372#issuecomment-185925908).![](https://github.com/notifications/bea
con/AAlEY6nLW5-cRN9D4G277p2i39GHdRo9ks5pliwmgaJpZM4HddN1.gif)

**Comment by natarius** [comment]
I had checked the nylas send folder though and it showed up as send

> On Feb 18 2016, at 1:18 pm, Matthias Wagner
&lt;matthias.wagner.office@gmail.com&gt; wrote:  
fuck! you are correct...it didn't actually send the email, but just flag it as
send :(

>

>> On Feb 18 2016, at 1:16 pm, Michael Grinich
&lt;notifications@github.com&gt; wrote:  

>>

>> Can you check whether the email actually sent or was just marked as sent in
N1? (Check gmail/etc. sent folder)

>>

>> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1372#issuecomment-185925908).![](https://github.com/notifications/bea
con/AAlEY6nLW5-cRN9D4G277p2i39GHdRo9ks5pliwmgaJpZM4HddN1.gif)

**Comment by jstejada** [comment]
this is probably the same issue as #1175, so I'm merging it in
