### ISSUE TITLE
[Feature Request] Hide addresses from Unified Inbox

### ISSUE THREAD

**Issue by YarmoM** [nylas/N1#1375]
I do not know of any other clients that do this, but then again, Unified Inbox is rarely implemented...

So, as the title implies, I think it would be great if I could flip a switch per account under "Manage Accounts" to either show or hide it in the Unified Inbox.

I think this would be a great addition and a handy time-saver as I do not need to constantly keep an eye on ALL of my addresses, a few important ones is more than enough.

**Comment by bengotow** [comment]
Closing as dup of #1355
