### ISSUE TITLE
The thread appears only on the original folder (e.g "sent" or "inbox") even when there is a conversion

### ISSUE THREAD

**Issue by alonisser** [nylas/N1#138]

**Comment by alonisser** [comment]
recreate:
send an email
get a reply

choose sent folder
verify you can see the specific email thread 
change to inbox folder
verify you can't see the specific email thread

(checked with outlook.com)

**Comment by grinich** [comment]
Is it possible these messages aren't being threaded together?

The 'get a reply' results in a new message in the Inbox folder on Outlook.com?

**Comment by alonisser** [comment]
I'm not sure now about this result. It happened before, but now I do see the threaded messages (when they are one day ago) I'll check again with messages from today..

**Comment by grinich** [comment]
Closing as stale. Please re-open if you have steps to reproduce!
