### ISSUE TITLE
adding spelling to right click menu in search bar

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1384]
![image](https://cloud.githubusercontent.com/assets/547354/13192423/90b3696e-d720-11e5-9d3a-f2d1f10c8786.png)

**Comment by oldhickory30** [comment]
Totally agree we need that!!

**Comment by bengotow** [comment]
This is in review internally and should land on master Monday. Cheers!

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
