### ISSUE TITLE
Spellcheck not working - OSX 10.11.3

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#1388]
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [ ] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- [x] What operating system are you using? Mac OSX 10.11.3

- [x] What version of N1 are you using? Version 0.4.5-b0ec335 (0.4.5-b0ec335)

**Bug?**
- [x] Do you have any third-party plugins installed? Yes

![plugins](https://cloud.githubusercontent.com/assets/16170272/13203530/e81a9d6e-d877-11e5-9761-d3b0cbdc83cd.jpg)

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? It's affecting both of my accounts, Zoho, Fastmail

- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

**Feature Request?**
- [x] Does this feature exist in another mail client or tool you use?

**Comment by oldhickory30** [comment]
Nylas does not appear to be spell checking? It used to but no longer, This is something fundamental that we should have working in an email client.

**Comment by mbilker** [comment]
Thanks for the report, but please fill in the template. To fix this issue the Nylas team needs to know information about your environment.

**Comment by oldhickory30** [comment]
Sorry hopefully that helps!

**Comment by oldhickory30** [comment]
I filled it out....sorry about that!

  

> On Feb 21 2016, at 8:40 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Thanks for the report, but please fill in the template. To fix this issue
the Nylas team needs to know information about your environment.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1388#issuecomment-186846065).![](https://github.com/notifications/bea
con/APa9IEWl7SdaV6jB9IX95x19TJ_31gRPks5pmdH6gaJpZM4He-6B.gif)

**Comment by mbilker** [comment]
Thank you! This has been an issue on older versions. What language are you writing in and what languages did you add in System Preferences.

**Comment by oldhickory30** [comment]
Should be English, I do not even see language preeferance within Nylas?

> On Feb 21 2016, at 8:57 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Thank you! This has been an issue on older versions. What language are you
writing in and what languages did you add in System Preferences.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1388#issuecomment-186849278).![](https://github.com/notifications/bea
con/APa9IBvJhJdnGwwSf_Iq54mw0k0TFobeks5pmdXygaJpZM4He-6B.gif)

**Comment by mbilker** [comment]
Since you are on Mac OS X, N1 uses the OS X Spellchecking API and OS X's language preferences. There is an issue with using multiple languages at once where `node-spellchecker` is unable to check if a certain word is correct for each language.

**Comment by oldhickory30** [comment]
Language is set correctly in my OS, other clients are working as well in
regards to spell check.

Nylas was running spell check earlier but just sppears to stop work completley
now I just get "learn spelling."

> On Feb 21 2016, at 9:33 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Since you are on Mac OS X, N1 uses the OS X Spellchecking API and OS X's
language preferences. There is an issue with using multiple languages at once
where node-spellchecker is unable to check if a certain word is correct for
each language.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1388#issuecomment-186855125).![](https://github.com/notifications/bea
con/APa9INiBqk90msKO0ec1C-0dYRVR-wXLks5pmd5rgaJpZM4He-6B.gif)

**Comment by oldhickory30** [comment]
How do I find out if I'm running multiple spell checks, doesn't appear that I was and again it was working at one point. Very frustrating!

**Comment by oldhickory30** [comment]
Ok, very strange spell check does appear t be working however I no longer get a red line under the misspelled word. Suggestions?

**Comment by oldhickory30** [comment]
Finally had to uninstall Nyles! The spell check would work work for about a minute or two then stop even after a clean installation. Then it started to duplicate emails and sending out the same email multiple times. Seems like is is getting more bug ridden, and, since I use email for business, I will have to hold off until you're ready for prime time.

**Comment by jstejada** [comment]
hi @oldhickory30, can you specify the case where you get the same email sent multiple times? could you open a new issue for that with any details you can provide? Thanks!

Regarding the spellcheck issue, we are looking into it

**Comment by oldhickory30** [comment]
I am no longer getting multiple emails, not sure how or why I was getting them
however, what matter is it's no longer happing.

  

The spell check is still happing when the view is set to 80% in the latest
version. Thanks for checking!

  
![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/865a34898ac341f591ae
8c4e74f2cc09)

> On Feb 26 2016, at 1:00 pm, Juan &lt;notifications@github.com&gt; wrote:  

>

> hi [@oldhickory30](https://github.com/oldhickory30), can you specify the
case where you get the same email sent multiple times? could you open a new
issue for that with any details you can provide? Thanks!

>

> Regarding the spellcheck issue, we are looking into it

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1388#issuecomment-189457758).![](https://github.com/notifications/bea
con/APa9IMnA56WcBjbl4RoozFHAqDGLnxmaks5poKZbgaJpZM4He-6B.gif)
