### ISSUE TITLE
Error when communicating with update server

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1389]
I was definitely online.
<img width="532" alt="screen shot 2016-02-19 at 11 40 50 pm" src="https://cloud.githubusercontent.com/assets/92417/13204910/f3c95136-d8a0-11e5-9e06-5810b0149275.png">

**Comment by bengotow** [comment]
I think this might be happening because you're connected to staging and there was a bug in the update checker code. Should be fixed today.
