### ISSUE TITLE
32-bit deb builds

### ISSUE THREAD

**Issue by RedHatter** [nylas/N1#139]
I just got my invitation code and am so exited to try it out, but the .deb package I got looks to be amd64 only and I have an i386 system.

The exacte error when running `sudo dpkg -i N1.deb` was:

    dpkg: error processing archive N1.deb (--install):
     package architecture (amd64) does not match system (i386)
    Errors were encountered while processing:
     N1.deb

**Comment by grinich** [comment]
working on it!

**Comment by nyex** [comment]
how can we get the 32-bit version once it is available? i got the invitation code as well but could not install the downloaded package because of the architecture. waiting anxiously!

**Comment by sadalavoaoj** [comment]
hi there, 

it is not PC architecture. it is the s.o version. i hope that people dont make the misktake of thinkin that is the hardware PC architecture like AMD or intel.

**Comment by Revod** [comment]
+1 :+1: for this

**Comment by Leo2807** [comment]
:+1: Just curious: what's the roadmap for 32-bit builds? (i.e. what needs to be done/todo list)

**Comment by mbilker** [comment]
This could be done in a Docker build on Travis. Atom has a `Dockerfile` for a Debian deb build at https://github.com/atom/atom/blob/master/build/debian/Dockerfile.

**Comment by bengotow** [comment]
Merging into #254
