### ISSUE TITLE
Nylas N1 App: Google Forms Can't Be Answered

### ISSUE THREAD

**Issue by aaryanbatra** [nylas/N1#1394]
I am using a Version 10.11.3 OS X El Capitan

I am using version 0.4.5-b0ec335 (0.4.5-b0ec335) on Nylas N1

**Bug?**
- [  In Nylas I have only built in plugins (Translation, Phishing Detection) ]

- [  Yes this is related to Google Forms, Gmail ]

- [ This happens with all google forms I try to write in in Nylas N1 ]

**Feature Request?**
- [ I think this is a feature request, but find a way to let me be able to successfully answer a google form on the Nylas N1 App ]

**Comment by bengotow** [comment]
Thanks for filing this @aaryanbatra — I think this used to work, so it might be a recent regression. I'll investigate and let you know.

**Comment by aaryanbatra** [comment]
Thanks  
  

Regards,

Aaryan Batra

> On Feb 23 2016, at 9:29 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Thanks for filing this [@aaryanbatra](https://github.com/aaryanbatra) — I
think this used to work, so it might be a recent regression. I'll investigate
and let you know.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1394#issuecomment-187451866).![](https://github.com/notifications/bea
con/AP_46VmEY8v0GqwN6KFCX3HLevzp32Ivks5pm59jgaJpZM4HfXE5.gif)

**Comment by bengotow** [comment]
Hey! Jut tested this today with a Google Form, and it looks like it's working properly. It does throw an error in the console because we block the email from running JavaScript, but it navigates to the success URL and logs the response. We musth have fixed this inadvertently over the last few months. Cheers!

![image](https://cloud.githubusercontent.com/assets/1037212/15132422/692ba5e6-160e-11e6-9c31-bb749257b907.png)

**Comment by aaryanbatra** [comment]
Awesome, I really appreciate all the work you and your team do!

On Tue, May 10, 2016 at 9:49 AM, Ben Gotow <notifications@github.com> wrote:

> Hey! Jut tested this today with a Google Form, and it looks like it's
> working properly. It does throw an error in the console because we block
> the email from running JavaScript, but it navigates to the success URL and
> logs the response. We musth have fixed this inadvertently over the last few
> months. Cheers!
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1037212/15132422/692ba5e6-160e-11e6-9c31-bb749257b907.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nylas/N1/issues/1394#issuecomment-218031092>
>



-- 
Best Regards,
Aaryan Batra | Filmmaker & Designer
