### ISSUE TITLE
Unable to run N1 [TypeError: Cannot read property 'getVersion' of undefined]

### ISSUE THREAD

**Issue by vsagar9944** [nylas/N1#1399]
Getting following error when trying to run ./N1.sh --test command
```
App threw an error when running [TypeError: Cannot read property 'getVersion' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'getVersion' of undefined
    at parseCommandLine (/home/ist-116/MyProjects/NodeJS/Nylas/N1/src/browser/main.js:107:18)
    at start (/home/ist-116/MyProjects/NodeJS/Nylas/N1/src/browser/main.js:17:12)
    at Object.<anonymous> (/home/ist-116/MyProjects/NodeJS/Nylas/N1/src/browser/main.js:148:3)
    at Object.<anonymous> (/home/ist-116/MyProjects/NodeJS/Nylas/N1/src/browser/main.js:150:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/home/ist-116/.nvm/versions/node/v0.12.7/lib/node_modules/electron-prebuilt/dist/resources/default_app/main.js:246:23)
    at Module._compile (module.js:434:26)
```

**Comment by mbilker** [comment]
You ran `./script/bootstrap` not as root. Correct? NVM should work fine with N1. I ran that command and it worked just fine.

```
Finished in 38.003 seconds
1485 tests, 3250 assertions, 0 failures, 0 skipped
```

**Comment by handicraftsman** [comment]
@bilker, tried to run ./script/bootstrap again (not as root, like in previous start), but it not helped - again see this error.

**Comment by mbilker** [comment]
Okay. I do not get the error when I run `./N1.sh --test` after running `./script/boostrap`. Could you run the following commands so I can get an idea of what your system environment is?

```
uname -a
lsb_release -a
```

If you are on Debian or Ubuntu, please run `nodejs` instead of `node`:
```
node --version
npm --version
```

**Comment by mbilker** [comment]
The output of these commands on my end are:
```
uname -a:
Linux mbilker-lappy 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux

lsb_release -a:
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

node --version:
v5.7.0

npm --version:
3.7.3
```

**Comment by mbilker** [comment]
Also, this may be related to atom/electron#4017. Could you run:
```
npm remove electron (for local)
npm remove electron -g (for global)
```

`node-electron` from `npm` is a separate project and interferes with N1 resolving the builtin `electron` module.

**Comment by vsagar9944** [comment]
I had installed nodejs ,previously in system there is only node
on executing script/bootstrap it works file  with out put 
**script/bootstrap completed successfully. You can start
N1 via ./N1.sh --dev, or run tests with ./N1.sh --test**

when i tries to start N1 using ./N1.sh --dev it ggives me following error

Error opening app
The app provided is not a valid electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/master/docs

Error: Cannot find module '

**For system configuration refer following details**
 
uname -a command output
Linux ist116 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:12:08 UTC 2015 i686 i686 i686 GNU/Linux

lsb_release -a command output 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

nodejs --version
v0.10.25

npm --version
3.5.2

**Comment by vsagar9944** [comment]
Working fine ,By removing  my electron-prebuilt and setting ELECTRON_PATH variable to eletron module inside N1 app

**Comment by handicraftsman** [comment]
... Why not reading referenced topics? https://github.com/nylas/N1/issues/1415
