### ISSUE TITLE
Inbox indicates one new email

### ISSUE THREAD

**Issue by chrisberthe** [nylas/N1#140]
All emails have been read, yet the inbox notifies me of one new email.

This was not a problem when originally syncing and setting up my Gmail account. However, I started up N1 a couple days ago, it randomly appeared and has not gone away yet.

Re-installing the application and re-syncing my account hasn't helped.

**Comment by bengotow** [comment]
Hi @chrisberthe —thanks for reporting this. Are you seeing "1" on the unread badge of the app and beside the "Inbox" in the sidebar, or is there actually a message in your inbox that does not appear in Gmail? I'll talk to our platform team and see if there have been any sync issues.

**Comment by chrisberthe** [comment]
Hi @bengotow, no problem. I see the unread badge in both the app icon and beside the "Inbox" within the sidebar.

I tried connecting to my account through inbox.google.com and Gmail and do not see any unread emails.

While this isn't a viable solution, how can I fully delete N1 from my system and re-install from scratch? I attempted to remove the application manually and re-add my account but that doesn't seem to work.

**Comment by chrisberthe** [comment]
I should note that I am still receiving the latest emails and notifications. It just seems like the badge indicates the "real number of unreal emails" + 1.

**Comment by alex-bender** [comment]
I also have this badge.

**Comment by gilbitron** [comment]
:+1: I get this too

**Comment by danharms** [comment]
I have this happening with an exchange account. My gmail account is fine.

**Comment by zlatkobijelic** [comment]
This is happening for me as well, I have double checked gmail to make sure and all of my messages are READ, but seeing a "1" on my N1 app. Also shows a "1" in the actual side panel (check attachment
<img width="213" alt="screen shot 2015-12-01 at 7 37 57 pm" src="https://cloud.githubusercontent.com/assets/2780549/11521642/1be4237c-9863-11e5-9900-8435f585b9a0.png">

**Comment by Dylan-Buth** [comment]
This is happening to me as well. Two read emails in my inbox yet the sidebar/dock-icon indicate two unread emails.

**Comment by zlatkobijelic** [comment]
Has this been fixed or just added to trello?

**Comment by grinich** [comment]
It was merged here: https://github.com/nylas/N1/issues/489

**Comment by fonnesbeck** [comment]
I am getting a re-ocurrence of this behavior. My Gmail account shows 1 unread, when there are no messages at all in my inbox. Re-installing does not fix the issue, nor does removing and re-adding the account.

**Comment by jstejada** [comment]
hi @fonnesbeck , thanks for reporting this. You can follow up on this issue at #759
