### ISSUE TITLE
Sent mail appears as draft

### ISSUE THREAD

**Issue by tobiassnall** [nylas/N1#1403]
I'm getting a weird issue with sent emails. They send as normal also appears as drafts after they've been sent.

I'm on OS X 10.11.3

/T

**Comment by jstejada** [comment]
hey @tobiassnall , thanks for reporting this. I'm merging into duplicate #869

**Comment by jstejada** [comment]
@tobiassnall , are you using Gmail or Exchange? Could you email support@nylas.com with your email address so we can check your account?
