### ISSUE TITLE
Dark theme makes it hard to read text in setup wizzard

### ISSUE THREAD

**Issue by Petur06** [nylas/N1#1406]
I run N1 with a dark theme. When I remove my email account, the client is restarted and the wizzard starts. After I select which account I want to add (gmail) and authorize it, this view is displayed:

![n1_dark](https://cloud.githubusercontent.com/assets/731005/13278591/e8d55b16-dad1-11e5-892d-4a6ac698efe6.PNG)

Which is pretty much **unreadable**. The same goes for the next screen where you can choose some plugins.

- Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)
    - Haven't found.

- What operating system are you using?
    - Windows 7

- What version of N1 are you using?
    - 0.4.5

**Bug?**
- Do you have any third-party plugins installed?
    - No

- Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
    - No

- Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.
    - No

**Comment by bengotow** [comment]
Hmm - in taking a look at this, I'm not sure what we should do. We can correctly style that UI to use theme variables, but it looks like some of the other parts of the auth flow (specifically the screens with the gradients) wouldn't work well. We could also force this window to always use the default theme, since it's rarely seen once a theme has been installed.

**Comment by locksmithdon** [comment]
When you address this issue, it would also be great to ensure the mouse cursor is more visible (at least on OS X) when the dark theme is selected. When over a mail message and the cursor is an i-beam, it's really difficult to see. Thanks!

**Comment by bengotow** [comment]
Hey folks - for the time being, we've opted to disable themes in the onboarding window: ba0a2f0294fc44a1d011d85fa445b04ec0540203. We'll revisit this, but we decided it's 1) important that the onboarding window always match the N1 brand, and 2) isn't likely to be reviewed by theme designers as they create themes. Cheers—

**Comment by jstejada** [comment]
hey all, https://github.com/nylas/N1/commit/ba0a2f0294fc44a1d011d85fa445b04ec0540203 has landed in the latest release, so closing this now
