### ISSUE TITLE
Office 365 can't sync

### ISSUE THREAD

**Issue by AGhost-7** [nylas/N1#1407]
If I try to add my office 365 account to N1, I get the following error message: "Successfully logged in but could not sync mail."

Additional information:
- I don't have any plugins.
- The version I'm using is 0.4.5 (currently says its the latest if I try to update).
- Using on a mac OS

**Comment by AGhost-7** [comment]
*bump*

**Comment by jstejada** [comment]
Hi @AGhost-7, thanks for reporting this. Are you still unable to connect?

**Comment by CExJBoudreau** [comment]
Yea seems like it.

**Comment by AGhost-7** [comment]
Unfortunately yes. It was working fine for a while then it stopped working again.

**Comment by MissOgra** [comment]
Same here. I even tried this here, it didn't work either: https://github.com/nylas/N1/issues/532

**Comment by jackiehluo** [comment]
Send us an email at support@nylas.com if you experience this issue!
