### ISSUE TITLE
Feature Request: Hovering Send Button

### ISSUE THREAD

**Issue by xasos** [nylas/N1#1408]
When threads get long, it takes a long time to scroll to hit the send button. A send button that hovers at the bottom of the window (and stays locked there) would be great.

**Comment by grinich** [comment]
do you have examples of other mail apps that do this?

**Comment by grinich** [comment]
Or why not just use the keyboard shortcut?

**Comment by emorikawa** [comment]
@xasos There is definitely room to design a better send button. We've had several people post issues with the same thought. I'm merging all of these send button fix issues into #1083. You can track the status and discussion of this there.
