### ISSUE TITLE
Gmail message deleted goes to archive

### ISSUE THREAD

**Issue by davidcafor** [nylas/N1#1411]
Hi,

I'm using OSX 10.11.3 and the latest version of Nylas  0.4.5-b0ec335.

When I click on the "detele" button from the main menu bar on a GMAIL message it moves to the archive folder instead of the trash.
That only happens with gmail. I got 2 more accounts configurated on the app and everything works fine.
I want to clarify that I click on the delete button, not on the backspace or return (keyboard).
That's happening since the last update I think, because in the past I didn't notice anything working wrong.

**Comment by davidcafor** [comment]
After today's update (0.4.9-575c091), the problem still continues.
Here you can see what I'm talking about.
When I delete a gmail message it goes to trash with the "trash" label but it appears in the archive folder too.
![captura de pantalla 2016-02-26 a las 9 25 00](https://cloud.githubusercontent.com/assets/5927093/13347047/3ee76a72-dc6b-11e5-8887-b1e31a893bfa.png)
![captura de pantalla 2016-02-26 a las 9 25 14](https://cloud.githubusercontent.com/assets/5927093/13347048/3eecc0bc-dc6b-11e5-9267-6e3815b7c4eb.png)

**Comment by jstejada** [comment]
hi @davidcafor, we've updated how we handle gmail labels in our last release. Let me know if this is still an issue for you

**Comment by jstejada** [comment]
feel free to reopen if you are still seeing this behavior

**Comment by felixsanz** [comment]
@jstejada I have this problem in 0.4.56. I fixed the keyboard shortcut changing `Trash -> #` for `Trash -> Del`, but this should be default!
