### ISSUE TITLE
fastmail request timed out

### ISSUE THREAD

**Issue by abrasmelin** [nylas/N1#1412]
Hello I am using ArchLinux and using n1 version 0.4.5-2 (without plugins) I can not setup my fastmail account with n1 because it always gives "request timed out" error. What is the problem? Is this a known issue? Thank you.

**Comment by bparsons** [comment]
I am able to set up Fastmail with N1 and Arch (using the package from the AUR) and I do not get this error adding my fastmail account and using the servers listed on the fastmail help page (https://www.fastmail.com/help/technical/servernamesandports.html) - but not being able to set the IMAP prefix makes the folder structure look/act funky.

**Comment by bengotow** [comment]
Hi @abrasmelin — are you still running into this problem? Could you try setting up your Fastmail account again?

**Comment by abrasmelin** [comment]
yes now its working thanks!
