### ISSUE TITLE
emoji in account name doesn't show up

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1413]
<img width="168" alt="screen shot 2016-02-24 at 9 45 44 pm" src="https://cloud.githubusercontent.com/assets/92417/13311031/0844630c-db40-11e5-8132-08b5dacd81a5.png">

<img width="161" alt="screen shot 2016-02-24 at 9 45 47 pm" src="https://cloud.githubusercontent.com/assets/92417/13311032/0847f6e8-db40-11e5-8877-c87988ced5b2.png">

**Comment by bengotow** [comment]
Same issue as on #806, blocked on support for bold emoji in Chromium.

**Comment by bengotow** [comment]
Closing as dup
