### ISSUE TITLE
Progress bar & Notification

### ISSUE THREAD

**Issue by orkhanfarmanli** [nylas/N1#1417]
There should be a progress bar if you upload any attachment to the email. And a toast message that confirms the email has been sent.

**Comment by bengotow** [comment]
Hi @orkhanfarmanli, if you go to your Drafts view, you can see a progress bar there in the latest release. We currently play a sound but do not display a toast when the message has been sent. That said, in the lower left it should say "Sending message..." until the message is sent. Does that help?

**Comment by orkhanfarmanli** [comment]
Yes, thanks a lot!

> On Feb 26 2016, at 1:25 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@orkhanfarmanli](https://github.com/orkhanfarmanli), if you go to your
Drafts view, you can see a progress bar there in the latest release. We
currently play a sound but do not display a toast when the message has been
sent. That said, in the lower left it should say "Sending message..." until
the message is sent. Does that help?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1417#issuecomment-188995094).![](https://github.com/notifications/bea
con/ANcdjVbLlD-JxWfkrIdG848quFaNGQMKks5pn2jWgaJpZM4HjLoG.gif)
