### ISSUE TITLE
Signatures don't switch when changing address

### ISSUE THREAD

**Issue by lleger** [nylas/N1#1418]
When I compose a new email address and switch to any of the other address I have configured in N1, the signatures don't change.

Here's a gif showing the problem:

![n1_signature_issue](https://cloud.githubusercontent.com/assets/52359/13335449/cb4cdb18-dbd6-11e5-9130-258dc020389e.gif)

- [x] Are there any related issues? **No**
- [x] What operating system are you using? **Mac OS X 10.10.5**
- [x] What version of N1 are you using? **0.4.5-b0ec335 **

**Bug?**
- [x] Do you have any third-party plugins installed? **No, just built in ones**
- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? **No**
- [x] Is the issue reproducible with a particular attachment, message, signature, etc? **Yes, it happens every time I compose a new message.**

**Comment by jstejada** [comment]
@lleger merging into #1239 . this will be shipped in the next release!

**Comment by lleger** [comment]
Ah, I didn't search *closed* issues, my apologies. Thanks. :+1:
