### ISSUE TITLE
0.4.9 regression : System Tray

### ISSUE THREAD

**Issue by 5paceToast** [nylas/N1#1422]
As of 0.4.9 on Windows 10 (version 1511, build 10586.104), the Tray Icon no longer appears. However, the process is still present after closing the window, creating zombie processes.

No third party plugins, 100% reproduction on my system.

This is a regression from 0.4.5 to 0.4.9, after a brief read through the commits, it may be related to 7ec30d0c7b622c70ba894a11293f896aaa8fa844, whose test plan is manual and has only been reviewed by @bengotow, who may not have Windows 10 to test the changeset on.

**Comment by Feichtmeier** [comment]
I can confirm this with Linux! The tray icon is gone! :(

**Comment by varlesh** [comment]
Confirm on Ubuntu 16.04 with Unity

**Comment by BraisGz** [comment]
Confirmed on Ubuntu 15.10 with Unity !

**Comment by 5paceToast** [comment]
Seeing as the regression seems to affect more than just Windows 10, updated title.

**Comment by France82** [comment]
Same here in Windows 10 64bit. It work but i can't see the icon.
![tray](https://cloud.githubusercontent.com/assets/17158802/13356963/6401e494-dca8-11e5-831e-764c7d29d8b7.jpg)

**Comment by mbilker** [comment]
Working on this.

**Comment by mbilker** [comment]
It is related to `7ec30d0c7b622c70ba894a11293f896aaa8fa844` [here](https://github.com/nylas/N1/commit/7ec30d0c7b622c70ba894a11293f896aaa8fa844#diff-3d0aaae115b07debe8f9a5c86861b284R41) with the `tray-icon.png` file empty on Linux.

Looking into possible fixes.

**Comment by mbilker** [comment]
Diagnosed on Linux. `this._icon.toPng()` returns an empty array.
![2016-02-26-11-18-30_303x82](https://cloud.githubusercontent.com/assets/1266541/13357938/ca927e9a-dc7a-11e5-95bf-7ed99523d588.png)

**Comment by mradzinski** [comment]
Linux fails to open the tray-icon.png... corrupted file?

**Comment by mbilker** [comment]
@mradzinski The file is empty. It is because `SystemTrayStore` uses the wrong path for the image. PR inbound in 5min.

**Comment by reimax** [comment]
Confirmed on Ubuntu 14.04 with Unity!

**Comment by parkersonik** [comment]
Confirm on Windows 10 and 8.1 x64 after the update 0.4.5 to 0.4.9

**Comment by mbilker** [comment]
Fix included with 0.4.10.

**Comment by parkersonik** [comment]
I saw that the icon was blank

**Comment by mbilker** [comment]
@parkersonik on 0.4.10? A fix was merged and 0.4.10 was released only a few hours ago after 0.4.9 had some substantial bugs that crept up out of minimal testing on Linux and Windows.

**Comment by parkersonik** [comment]
Yes all true, the icon appeared!

thank You for a wonderful product  📫

![](http://media0.giphy.com/media/4GRRBtKrdiFDa/100.gif)  

  
![](https://link.nylas.com/open/6znsacpwfj3vcfbpidg7779uo/c22ea75154ef49d68447
94753e5d16d1)

> On Feb 27 2016, at 7:16 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> [@parkersonik](https://github.com/parkersonik) on 0.4.10? A fix was merged
and 0.4.10 was released only a few hours ago after 0.4.9 had some substantial
bugs that crept up out of minimal testing on Linux and Windows.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1422#issuecomment-189578407).![](https://github.com/notifications/bea
con/ACPaCnd1JCpnC-ZsU8mDZ1B_t-SFUUg-ks5poSi7gaJpZM4Hjfc-.gif)
