### ISSUE TITLE
Mac none focus close

### ISSUE THREAD

**Issue by AgentSource** [nylas/N1#1423]
Mac 10.11.3 just installed Version 0.4.9-575c091 (0.4.9-575c091) and having issue minimizing and closing unless window is focused. 

When app window is focused no issues what so ever.

**Comment by thebearjew** [comment]
I decided to test this as well. Does this roughly explain what the issue is.

https://gfycat.com/SevereAlarmedCanvasback

Note: I was focused in the Safari app, moved the mouse to the minimize button, and then clicked. Repeated this several times in the video

**Comment by AgentSource** [comment]
@thebearjew thats the behavior!

**Comment by bengotow** [comment]
Hey! This will be resolved when we switch to system-native window controls. Closing as dup of #1886

**Comment by thebearjew** [comment]
Awesome! Glad to hear that
