### ISSUE TITLE
Can't add an alias (Mac 0.4.9-575c091)

### ISSUE THREAD

**Issue by samrayner** [nylas/N1#1428]
Running 0.4.9-575c091 on Mac 10.11.3

![Issue](https://i.imgflip.com/zuytr.gif)

No third party plugins installed.
Only encountered with Gmail in my testing but haven't tried other providers.

The above GIF shows an email address I obviously don't own but the same problem occurs with ones I do own and have a Gmail alias set up for on the account.

Can't see anything appear in the logs when it happens.

Perhaps related:
- N1 is currently syncing
- Renaming an account label resets to the current name as I type every second or two
- Was able to rename an account by pasting and submitting the field quickly between refreshes

**Comment by nhr** [comment]
Confirmed same behavior on Fedora 23

**Comment by lalitkapoor** [comment]
+1

**Comment by lleger** [comment]
I have the same issue as well. The console outputs the following error:

> Uncaught TypeError: Cannot read property 'concat' of undefined
> preferences-account-details.jsx:78

**Comment by emorikawa** [comment]
Yes, we're looking into this now.

**Comment by jstejada** [comment]
this is fixed with https://github.com/nylas/N1/commit/7ba13d0f0a98faab11b44fea4a968ea8e86c071b

**Comment by nhr** [comment]
Awesome. How long will this take to land in the .rpm / .deb packages?

**Comment by jstejada** [comment]
probably today

**Comment by nhr** [comment]
You == the man.
