### ISSUE TITLE
Dark color scheme checkbox nonfunctional

### ISSUE THREAD

**Issue by mbolivar** [nylas/N1#143]
When I choose File > Preferences > Appearance and check "Use dark color scheme", the color scheme changes, but then reverts to the bright color scheme about half a second later.

This is repeatable.

(FWIW, other buttons in the preferences, like the list view / split view "radio" option, seem to do the same thing, but when clicking them again, they take effect)

I'm running 64-bit Ubuntu 14.04.

Nylas info:

lozenge: ~ mbolivar$ apt-cache show nylas
Package: nylas
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 209628
Maintainer: Nylas Team <support@nylas.com>
Architecture: amd64
Version: 0.3.17
Depends: git, gconf2, gconf-service, libgtk2.0-0, libudev0 | libudev1, libgcrypt11, libnotify4, libxtst6, libnss3, python, gvfs-bin, xdg-utils
Suggests: libgnome-keyring0, gir1.2-gnomekeyring-1.0
Description: An extensible, open-source mail client built on the modern web.
 Nylas N1 is an extensible, open source mail client built on the modern web.
Description-md5: aadf2d3f60b3f0dbc1efdd482a7ce243

**Comment by bengotow** [comment]
Hi there—it sounds like the app may not be able to write it's preferences file. Can you check the permissions on `~/.nylas/config.cson`?

**Comment by mbolivar** [comment]
lozenge: ~ mbolivar$ ls -lh ~/.nylas/config.cson  
-rw-rw-r-- 1 mbolivar mbolivar 1.1K Oct 22 18:31 /home/mbolivar/.nylas/config.cson  

  

> On Oct 22 2015, at 6:28 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi there—it sounds like the app may not be able to write it's preferences
file. Can you check the permissions on `~/.nylas/config.cson`?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/143#issuecomment-150373754).![](https://github.com/notifications/beac
on/AACJEL2or10MBT4uGF0Igb6tBEurZplwks5o-VqZgaJpZM4GUG9Z.gif)

**Comment by mbolivar** [comment]
Update: quitting the app and reopening it resolved the issue (the ls output
was after reopening).

  

Perhaps a repro test would do a fresh install, then check permissions? Not
sure.

> On Oct 22 2015, at 6:32 pm, Marti Bolivar &lt;mbolivar@leaflabs.com&gt;
wrote:  
lozenge: ~ mbolivar$ ls -lh ~/.nylas/config.cson  
-rw-rw-r-- 1 mbolivar mbolivar 1.1K Oct 22 18:31 /home/mbolivar/.nylas/config.cson  

>

>  

>

>> On Oct 22 2015, at 6:28 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>>

>> Hi there—it sounds like the app may not be able to write it's preferences
file. Can you check the permissions on `~/.nylas/config.cson`?

>>

>> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/143#issuecomment-150373754).![](https://github.com/notifications/beac
on/AACJEL2or10MBT4uGF0Igb6tBEurZplwks5o-VqZgaJpZM4GUG9Z.gif)
