### ISSUE TITLE
Read emails are not getting marked as read in Gmail / Google Inbox

### ISSUE THREAD

**Issue by nrutman** [nylas/N1#1430]
I'm using 0.4.9-575c091 on El Capitan.

Because I'm using N1 on my desktop (but Gmail / Google Inbox on my phone). I'm noticing that even hours after I've read / archived messages in N1, they are not read and archived in Gmail / Google Inbox. I have verified that this is not a simple phone sync issue by logging into these services in my browser. The messages are still in the inbox and unread even after hours of having them archived in N1.

I believe this is a regression. When I started using N1 (about 2 weeks ago) the accounts stayed in very tight sync. But recently I've experienced this on two different N1 installs (with two different email / Gmail accounts).

**Comment by mfid** [comment]
I'm having exactly the same problem in Exchange. Reported several times. Tweeted, emailed, no responses to say the issue is being assessed or even acknowledged.

**Comment by nrutman** [comment]
@mfid, odd...I wonder if it's the same problem. I'm seeing messages that I send, so I know there isn't an auth problem. It's just seems that reading, archiving, and deleting don't work properly.

**Comment by mfid** [comment]
Apparently an issue they’ve known for a while:
https://github.com/nylas/N1/issues/781

On Fri, 26 Feb 2016 at 21:05 Nate Rutman

<
mailto:Nate Rutman <notifications@github.com>
> wrote:

https://github.com/mfid
, odd...I wonder if it's the same problem. I'm seeing messages that I send, so I know there isn't an auth problem. It's just seems that reading, archiving, and deleting don't work properly.

**Comment by shravanpn7** [comment]
Changing labels, mark as read doesn't work in Exchange but it works fine in Gmail.

Here's the the output for the unread task on exchange from activity window.

`ChangeUnreadTask (ID: b351) SUCCESS (PROCESSING REMOTE)
{"unread":false,"threads":[{"client_id":"local-xxxx","server_id":"xxxx","object":"thread","account_id":"xxxx","metadata":[],"snippet":"xxxx","subject":"xxxx","unread":false,"starred":false,"version":0,"categories":[{"server_id":"xxxx","account_id":"xxxx","name":"inbox","display_name":"Inbox","id":"xxx"}],"categoriesType":"folders","participants":[{"account_id":"xxx","name":"xxxx","email":"xxxxx","thirdPartyData":{}},{"account_id":"xxxxx","name":"xxxx","email":"xxxx","thirdPartyData":{}}],"has_attachments":false,"last_message_received_timestamp":1458842924,"in_all_mail":true,"id":"xxxx"}],"messages":[{"client_id":"local-xxxx","server_id":"xxxx","object":"message","account_id":"xxxx","metadata":[],"to":[{"account_id":"xxxx","name":"xxxx","email":"xxxx","thirdPartyData":{}}],"cc":[],"bcc":[],"from":[{"account_id":"xxxx","name":"xxxx","email":"xxxx","thirdPartyData":{}}],"reply_to":[],"date":1458842924,"files":[],"uploads":[],"unread":false,"events":[],"starred":false,"snippet":"","thread_id":"xxxx","subject":"xxxx","draft":false,"categories":[{"server_id":"xxxx","account_id":"xxxx","name":"inbox","display_name":"Inbox","id":"xxxx"}],"id":"xxxx","file_ids":[]}],"_rememberedToCallSuper":true,"id":"local-cxxxx","sequentialId":xxxx,"queueState":{"isProcessing":false,"localError":null,"localComplete":true,"remoteError":null,"remoteAttempts":1,"remoteComplete":true,"status":"SUCCESS","debugStatus":"PROCESSING REMOTE"},"__constructorName":"ChangeUnreadTask","_locked":null,"_restoreValues":{"xxxx":{"unread":true},"xxxx":{"unread":true}}}`

**Comment by fonnesbeck** [comment]
I am getting this in Exchange as well. I have it set to "instant", but changing to other delay times does not fix the issue either.

**Comment by jackiehluo** [comment]
Merging into #781!
