### ISSUE TITLE
Default alias for answer

### ISSUE THREAD

**Issue by reimax** [nylas/N1#1431]
In the settings section accounts I added some aliases for mail on gmail. This box is going to mail from other accounts. Upon receipt of the letter to the address equal to one of aliases, if I start to write an answer to this letter, the sender field substitutes the default alias rather than the one that received a letter. This is a bug?

ubuntu 14.04
N1 version 0.4.5-b0ec335
no plugins installed
email provider - Gmail

**Comment by jstejada** [comment]
hey @reimax , yes, we currently have not implemented this behavior. I'm merging into #800
