### ISSUE TITLE
Manage Template

### ISSUE THREAD

**Issue by csimonmoi** [nylas/N1#1433]
OS: Windows 10
N1 version: 0.4.9 (last one on Feb 26th 2016)

In new message, Manage Template does not do anything at all when you click on it.
I have to go in Pref. > Quick Replies.
Thanks

**Comment by csimonmoi** [comment]
New version, no spell checker in Italian, English or whatever other language you choose. Known issue very well from me and other people.
Win10
Version: 0.4.9

**Comment by jstejada** [comment]
this is fixed and will be released soon.
