### ISSUE TITLE
New message windows are not available in the Window menu

### ISSUE THREAD

**Issue by nrutman** [nylas/N1#1435]
I'm using 0.4.9-575c091 on El Capitan.

When I create new messages a new window is opened, but there's no easy way to switch between windows in the application. The `Window` menu does not contain a list of my composer windows, and the only way I have to find them is by moving other windows around until I can visibly see them on the screen.

![window_menu](https://cloud.githubusercontent.com/assets/165184/13355369/f5f9f6ec-dc6d-11e5-880f-01763f79695c.png)

**Comment by standage** [comment]
Indeed. The typical ⌘-backslash combo for toggling between windows within an application doesn't seem to work. I always thought that was an OS-level feature, so I'm wondering whether the key combo is being overridden by N1?

**Comment by bengotow** [comment]
This was partially fixed in the last release and will be fully resolved by 1347654bbf2d1ac8cbbc8225f9bc7cf226481971. Stay tuned!

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
