### ISSUE TITLE
Message flashes and disappears when opened

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1438]
Opening an email from notification center or quickly going through emails in inbox results in something as shown below. The email message flashes rapidly and disappears and becomes the small rectangle as shown. The only way to read that email is to click back to the inbox and coming in again. When we do that message is shown properly. Does not happen every single time but happens very frequently enough to notice. Most probable to happen when there is an image in the email. Didn't notice this much with text only emails. (Not saying it never happened.)

![screenshot from 2016-02-26 10-26-10](https://cloud.githubusercontent.com/assets/2344626/13356995/42199b6a-dc76-11e5-9f20-12fa98593716.png)

- [x] Are there any related issues? 
I didn't find any. But I think I could not come up with good search terms for this.

- [x] What operating system are you using?
Arch Linux

- [x] What version of N1 are you using?
0.4.5 b0ec335

**Bug?**
- [x] Do you have any third-party plugins installed?
Yes, one theme. https://github.com/edipox/n1-ido

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No. Happens in both gmail and Exchange.

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

Shown above.

**Comment by bashok001** [comment]
Happened again and I captured console output for you this time. **Almost** always I see something similar to this when this happens. The last modify message thing is almost a minute after I opened the message.
![screenshot from 2016-02-26 10-57-16](https://cloud.githubusercontent.com/assets/2344626/13357428/36c5e258-dc78-11e5-8327-f5a110b03d65.png)

**Comment by matthewbassett** [comment]
+1 this one, happens fairly regularly, but doesn't seem to be consistent at all. It will load the correct email for about 1 second and then blank it out. closing the email and selecting it again from the inbox will load things correctly.

**Comment by bashok001** [comment]
@jstejada or Nylas team, please take a look at this one. Still happening. I am on the latest version now.

**Comment by jackiehluo** [comment]
Hey! This issue should be fixed now, so I'm going to close it—let us know if you see it again! Thanks!
