### ISSUE TITLE
Gmail Important Tag Persistently Present

### ISSUE THREAD

**Issue by craigeley** [nylas/N1#1439]
Using Nylas  0.4.9-575c091 on OS X 10.11.3, the official Gmail "Important" tag is showing up on emails again, even though I have the Show Important Markers preference unchecked, and I *also* have Unchecked "show label in IMAP" from my Gmail settings on the web.

I also tried removing the account and re-adding it.

Note: this is the capitalized, "official" Important tag, not the lowercase tag that has been reported in #1225 (I think.)

![](http://d.pr/i/1lIgV+)

**Comment by jstejada** [comment]
hey @craigeley , I'm merging into duplicate #1225 . thanks!

**Comment by craigeley** [comment]
Cool. Thanks!
