### ISSUE TITLE
"Reply" widget in split view input is buggy

### ISSUE THREAD

**Issue by mbolivar** [nylas/N1#144]
In the split view, I click "write a reply" and starting to type a response in the text box that appears.

The resulting text box randomly splits into multiple response messages, some of which don't contain text boxes which appear to accept input.

**Comment by bengotow** [comment]
Hey @mbolivar — thanks for filing this. What platform / email provider are you using? There are some error cases where the app creates a new draft to make sure that your work isn't lost. Sounds like you must be hitting that again and again.

**Comment by mbolivar** [comment]
I'm using a GMail account; Nylas is running on Ubuntu 14.04 64-bit.

  

I checked my drafts folder and it was indeed had multiple things in there that
were attempts on my part to respond.

> On Oct 22 2015, at 6:28 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hey [@mbolivar](https://github.com/mbolivar) — thanks for filing this. What
platform / email provider are you using? There are some error cases where the
app creates a new draft to make sure that your work isn't lost. Sounds like
you must be hitting that again and again.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/144#issuecomment-150373603).![](https://github.com/notifications/beac
on/AACJEMzC4GTIURbSugMCyBchGfMr6uOUks5o-VpvgaJpZM4GUIkK.gif)

**Comment by grinich** [comment]
also @mbolivar what keyboard shortcuts do you have enabled? Sometimes folks accidentally turn on the Gmail shortcuts which include `r` for creating drafts.

**Comment by grinich** [comment]
@mbolivar I'm going to close this as stale, since we've made a bunch of changes to the reply system since October. Please re-open if you can reproduce the issue using latest!
