### ISSUE TITLE
Reply button looks broken (works fine)

### ISSUE THREAD

**Issue by mirisuzanne** [nylas/N1#1443]
I'm using Version 0.4.9-575c091 on El Capitan 10.11.4 Beta, and the reply button looks like this:

![reply](https://dl.dropboxusercontent.com/s/arsp16a4tvz8kb0/Screenshot%202016-02-26%2009.59.16.png?dl=0)

I see that on all messages, across the board.

**Comment by jstejada** [comment]
hey @mirisuzanne , thanks for reporting. I can't see you image. Are you using the Taiga theme by any chance? If so, you should update it to its latest version and the styling issue should be fixed

**Comment by mirisuzanne** [comment]
oh, I am! How do you update a theme?

**Comment by jstejada** [comment]
basically just re download it from its repo and reinstall it. thanks!
