### ISSUE TITLE
Security & Privacy w/ Nylas?

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#1444]
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [ ] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- [x] What operating system are you using?

- [x] What version of N1 are you using?

**Bug?**
- [ ] Do you have any third-party plugins installed?

- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

**Feature Request?**
- [ ] Does this feature exist in another mail client or tool you use?

**Comment by oldhickory30** [comment]
I have read much on the web regarding the fact that my email is going through a 3rd party server when using Nylas, is this correct/ If so, what guarantees my privacy and security?

**Comment by bengotow** [comment]
Hi @oldhickory30 — this is explained a bit in the onboarding screens when you first download N1. N1 is powered by the Nylas Sync Engine (https://github.com/nylas/sync-engine/), a cloud service similar to the one Mailbox used. It connects to your email account, syncs metadata, and enables new features like link tracking and read receipts.

You can read more about our security policies here: https://nylas.com/security/.

**Comment by bengotow** [comment]
I've created a knowledgebase article for this here: https://support.nylas.com/hc/en-us/articles/217518207
