### ISSUE TITLE
Can't Archive using Gmail shortcuts ('e')

### ISSUE THREAD

**Issue by orky** [nylas/N1#1446]
Running the new update 0.4.9-575c091 (0.4.9-575c091)

**Comment by jstejada** [comment]
Hey @orky , thanks for reporting this. I can't reproduce. Do you have Gmail shortcuts enabled in `Preferences -> Shortcuts`?

If you do, do you see any errors in the Console? In the menu, pick `Developer ->  Toggle Developer Tools` to open the console.

Thanks

**Comment by orky** [comment]
Thanks for the quick reply. When trying to debug, I notice that it works in the specific account view but not in the Unified Inbox view. Not seeing anything in the console.

**Comment by bengotow** [comment]
Hey @orky thanks—is there any chance the thread you're trying to archive belongs to an account that doesn't have an Archive folder? I think if you use Gmail's "remove from view" shortcut instead (`y`) it may do what you want.

**Comment by jstejada** [comment]
hey @orky , if you are still having trouble, I'm pretty sure this is the same issue as #1460 so I'm merging it in
