### ISSUE TITLE
Read receipts and Link Tracking do not work

### ISSUE THREAD

**Issue by jcguinea** [nylas/N1#1449]
I had tried the read receipts and link tracking but they do not work.
I attach screenshots:
<img width="1280" alt="captura de pantalla 2016-02-26 a las 11 41 43 a m" src="https://cloud.githubusercontent.com/assets/12300966/13360426/de856dc8-dc7e-11e5-8d56-018e2e5f2e7c.png">
<img width="1280" alt="captura de pantalla 2016-02-26 a las 11 42 53 a m" src="https://cloud.githubusercontent.com/assets/12300966/13360427/de88e552-dc7e-11e5-9f7f-fbfc3d67ea84.png">

**Comment by dregitsky** [comment]
Hey @jcguinea, thanks for reporting this! Can you forward your test email message to n1-support@nylas.com? The links in the message will help us to figure out what went wrong. Thanks!

**Comment by entropylabs** [comment]
I can confirm the same here - can't get Read Receipts working here either. But LOVE the new update. Using is across Windows and OS X and it's a HUGE improvement on the last version.

**Comment by mariosant** [comment]
Read receipt works in Ubuntu, not link tracking, unfortunately.

**Comment by AlbertoCG** [comment]
Both are working for me on Fedora 23. What Nylas version are you using?

**Comment by mariosant** [comment]
@AlbertoCG 0.4.10-4e3595b. Would you like to post a demo screenshot? I might be missing something here. :)

**Comment by AlbertoCG** [comment]
@mariosant I'm using the same version. Opening the message on Gmail Web to make sure it's not working only within N1

Just sent
![screenshot from 2016-02-28 07-53-29](https://cloud.githubusercontent.com/assets/5740892/13379331/e060dc90-ddf0-11e5-8480-d2b495557928.png)

Clicked Link & Clicked Link
![screenshot from 2016-02-28 07-54-04](https://cloud.githubusercontent.com/assets/5740892/13379334/e067b498-ddf0-11e5-8654-0329fe678ecb.png)

But that was on the second try. The first time I tried, the message got copied twice to my "Sent" folder and only one of them showed the tracking icons and the tracking didn't work on this.
![screenshot from 2016-02-28 07-54-49](https://cloud.githubusercontent.com/assets/5740892/13379333/e06707a0-ddf0-11e5-8407-fa5a7464bc4e.png)

**Comment by mariosant** [comment]
I was expecting something else. Checked again and this works! Thanks @AlbertoCG!

**Comment by Salamafet** [comment]
Link tracking doesn't work for me on Windows

**Comment by jstejada** [comment]
hi all, if any of you are still having issues with these plugins, please forward the affected message to n1-support@nylas.com and also include the following debug info: Inside the message, click the space to the left of the Reply button and select `Copy debug info to clipboard`, like this:

<img width="418" alt="screen shot 2016-03-02 at 9 45 40 am" src="https://cloud.githubusercontent.com/assets/1271509/13469310/ac5bf43a-e05b-11e5-8ee6-49e484a42c28.png">

Thanks!
