### ISSUE TITLE
Gmail 2-factor authentication not working

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#1450]
Running OS X 10.11.3, Nylas N1 0.4.9-575c091

When activating 2-factor authentication for my Gmail account, N1 is no longer able to use the account (which I expected), but it simply sit in a "Syncing your mailbox" state indefinitely. If I remove the Gmail account and re-add it, I am never asked for 2-factor -- N1 happily adds the account, but is unable to sync it.

**Comment by fonnesbeck** [comment]
Interestingly, when I try completely removing N1 by trashing the preference files, caches and application support files, re-installing N1 brings back all of my previous accounts. Not sure where that is all being stored!

**Comment by jstejada** [comment]
hey @fonnesbeck , thanks for reporting this! I'm going to merge into duplicate issue #1241

**Comment by fonnesbeck** [comment]
Thanks. Any idea regarding the persistent accounts after trashing the support files?

**Comment by chrisjrob** [comment]
Having wasted two hours failing to get Gmail working, I do feel the priority should be to ensure that no more Gmail 2FA accounts are added without some warning being displayed.
