### ISSUE TITLE
Images not rendering - RAW html onscreen

### ISSUE THREAD

**Issue by joelabair** [nylas/N1#1452]
Fedora Linux OS
Nylas N1 version 0.4.9-575c091

**Screenshot**
![image](https://cloud.githubusercontent.com/assets/3341315/13366654/b6386d62-dcaa-11e5-907e-2a88b7b7e031.png)

Message Body Source
[message-source.txt](https://github.com/nylas/N1/files/149014/message-source.txt)

**Comment by jstejada** [comment]
thanks for reporting this @joelabair, I'm merging into duplicate #839
