### ISSUE TITLE
Reply/forward button looks skewed

### ISSUE THREAD

**Issue by soundofsilver** [nylas/N1#1453]
N1 0.4.9
OS X 10.11.3

**Illustration**
<img width="220" alt="screen shot 2016-02-26 at 22 11 35" src="https://cloud.githubusercontent.com/assets/17501190/13366878/fa289666-dcd5-11e5-9df4-405e3d986d0f.png">

**Comment by bengotow** [comment]
Hey @soundofsilver — this is an issue with an old version of the N1-Taiga theme. If you update to the latest version available at https://github.com/noahbuscher/N1-Taiga it'll be fixed. Cheers!

**Comment by jstejada** [comment]
dupe of #1443

**Comment by soundofsilver** [comment]
@bengotow Thanks! Didn't realize extensions had to be manually updated.
