### ISSUE TITLE
IMAP folders not being imported

### ISSUE THREAD

**Issue by crxdelsol** [nylas/N1#1454]
For my company mail, I have an regular IMAP account.
In previous e-mail clients I have used, the folders were imported correctly. In N1 I don't see any folders.

(Latest version of 25th of Februari)

**Comment by bengotow** [comment]
Hi @crxdelsol — thanks for posting. Can you email support@nylas.com and include the email address you're trying to sync?

**Comment by crxdelsol** [comment]
Message send.

**Comment by crxdelsol** [comment]
By the way, in N1 I created a folder, which showed up in my webmail and other clients. (This is now the only folder I have in N1)
When I move an e-mail in another application to that folder, the e-mail is never to be found in N1. Not in the 'folder' nor my inbox.
