### ISSUE TITLE
Why is the N1 team sending spam?

### ISSUE THREAD

**Issue by ntwb** [nylas/N1#1455]
This morning I awoke to 3 unsolicited emails aka spam in 3 of my email inboxes. Two of the emails accounts that this spam was sent to are email accounts that I have tested N1 with and the third email account is an account that I tried to test with N1 but it does not actually work with N1.

At the bottom of the email it states: `You're receiving this email because you expressed interest in InboxApp, the Nylas Developer Program, or registered as a developer.`

No, I did not express interest in and InboxApp or Developer program with any of those 3 email accounts, my primary email account which is not one of those three accounts I could possibly say yes to that question but no, categorically not any of those 3 email accounts.

I have lost all forms of trust in N1, Nylas, and any affiliated products, services, or companies.

I have now deleted my N1 fork, unsubscribed from your spam to each of my three email accounts and removed all traces of N1 from computer.

**Comment by grinich** [comment]
Hi Stephen-- you were probably added to our newsletter when you signed up with your address(es). 

We need to update that footer. InboxApp was the name of the company a couple of years ago.

If you've unsubscribed and you're no longer using N1, then you won't receive anymore more product updates or announcements.

**Comment by ntwb** [comment]
@grinich It is disappointing that you could not even take the time to read what I wrote. As I stated the third email account that received your spam does not work with N1, I tried to create an email account for it in N1 and it did not work, though now you have subscribed it to your mailing list without permission.

**Comment by grinich** [comment]
Sorry about that-- it sounds like a bug in our newsletter sign-up system. We'll look into it.

**Comment by ntwb** [comment]
From the FCC [CAN SPAM Act](https://consumercomplaints.fcc.gov/hc/en-us/article_attachments/202922636/canspam.pdf): `For commercial email: Your consent may be oral or written.`

My consent was *not* given for any of the 3 email accounts, I would also suggest that the vast majority of the users you added to this mailing list also did not give consent.

1. Your steps to resolve this issue should involve reopening this issue so it is clearly listed as a bug and available for other users of your product to view as an "open issue" and not buried in the "closed issues"

2. You should send a follow up email to the entire mailing list explaining to the users why you signed them up to a mailing list without consent and state that you have now removed them from the mailing list.
