### ISSUE TITLE
Feature request: iOS client

### ISSUE THREAD

**Issue by martellalex** [nylas/N1#1458]
N1 iOS client with unified inbox and swipe snooze.

Doesn't even have to be native, I'd take a web client.  Dying for an iOS client for N1.

At the moment I'm using Outlook for iOS which is ok but the snooze function is very primitive and archiving / snoozing etc. conflicts with N1 so I find myself having to re-archive and/or re-snooze emails that I have already dealt with.

I appreciate this is probably a big feature request but would be awesome if it were up on the trello board.

And thanks tons, N1 is making my life so much easier already.  Really love what you guys are doing.  I would even pay for it.

I say that not altruistically but because I've come to the view that "free" software isn't really free.  There's always a risk the developers or owners will shut down the service.  Less likely if it's making money :)

**Comment by patrickheeney** [comment]
FYI this was proposed https://github.com/nylas/N1/issues/311#issuecomment-153166028 but was marked as `wontfix`.

**Comment by bengotow** [comment]
Merging with #311 - will change the subject of that to include more keywords :-)
