### ISSUE TITLE
Misaligned buttons 

### ISSUE THREAD

**Issue by tcn33** [nylas/N1#1459]
Buttons with an associated pulldown (Reply, Send etc) are misaligned with respect to the pulldown arrow. This persists past a restart of N1. Occurs across all email messages.

Example: https://dl.dropboxusercontent.com/u/24247/Screen%20Shot%202016-02-27%20at%202.55.05%20PM.png

OS X 10.11.3, N1 0.4.10-4e3595b.

**Comment by grinich** [comment]
hi @tcn33 -- this is probably because you have an old version of Taiga. Can you download the newest version and install it?

**Comment by tcn33** [comment]
@grinich ah, yep - that was it. Thanks :)
