### ISSUE TITLE
Dark color scheme: some preferences hard to read

### ISSUE THREAD

**Issue by mbolivar** [nylas/N1#146]
![nylas-dropdown-dark](https://cloud.githubusercontent.com/assets/35088/10680469/1d073828-78ee-11e5-9765-ee33dee329a2.png)

As shown above, some of the styling (e.g. for dropdown choices) is hard to read when using the dark scheme.

**Comment by agudulin** [comment]
@mbolivar I fixed this issue here: https://github.com/nylas/N1/pull/113. Try to build the latest version from master and tell me if the issue is still there.
