### ISSUE TITLE
When selecting a new account the first email is selected and auto marked 'read'

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#1461]
Fix this please.  You should not be automatically selecting the latest email when changing account.

**Comment by bengotow** [comment]
Hey! This was fixed in version 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!
