### ISSUE TITLE
Open email into new seperate window

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#1462]
I would like to be able to double click on an email (in the message list) and have it open in a separate window.  This allows me to have many email windows open at once.  I can do this with all other email clients and would suggest N1 needs to allow this also.

There are many reasons having email in individual windows is useful.

**Important:** I would also like N1 to remember the emails opened in separate windows so when I restart they are re-opened.

**Comment by jstejada** [comment]
Hi @molstrangler , I'm merging into duplicate #779
