### ISSUE TITLE
Feature Request: Streamline setup of custom accounts

### ISSUE THREAD

**Issue by brasilikum** [nylas/N1#1465]
I use several custom accounts an I think the process of adding new custom accounts could be streamlined:

<img width="329" alt="step one" src="https://cloud.githubusercontent.com/assets/3106990/13372378/51306284-dd41-11e5-8ea1-1b854d841dda.png">

After the user filled in his name and Email, prefill the domain an the username on the next page:

<img width="328" alt="step two" src="https://cloud.githubusercontent.com/assets/3106990/13372379/51319aaa-dd41-11e5-93e9-77f6ec035cea.png">

After the user added the password (and maybe changed the username and domain) prefill the next page:

<img width="330" alt="step three" src="https://cloud.githubusercontent.com/assets/3106990/13372377/512fe75a-dd41-11e5-9ae5-11d7a8e50619.png">

What is the strategy for adding smaller email providers? Add them to the list or define prefill-rules for custom email?

**Comment by khamidou** [comment]
Good point! We definitely want to add something like this in the future.

**Comment by bengotow** [comment]
Hey folks! This has been significantly improved in the latest release, which overhauled custom IMAP setup. Going to go ahead and close this. Cheers!
