### ISSUE TITLE
Indicator is missing on Ubuntu 14.04 from nylas  0.4.9 version

### ISSUE THREAD

**Issue by loserock** [nylas/N1#1466]
Ubuntu 14.04 latest LTS x64

After upgraded to Nylas **0.4.9** (from the package manager), there is no Nylas N1 indicator in the Ubuntu Unity notification bar (the small icon on the top panel).
I has **worked perfectly** in version **0.4.5**.

When i close the window, nylas processes run in the background, but I can't awake it, I have to kill and restart the app.

Of course i use this settings:
 - [x] Show icon in menubar
 - [x] Show notifications for new unread messages

I have two e-mail accounts (a gmail and an exchange) and use the most of the standard plugins well.

Anyway, the best would be a messaging menu integration.

**Comment by sergiuprt** [comment]
I have the same problem on **ubuntu 15.10**, after upgrade from terminal with apt-get upgrade.
It run in the background and i can awake it from launcher, but no indicator on the top panel...

**Comment by Spurlos** [comment]
This have been allready reported here https://github.com/nylas/N1/issues/1422 and fix is available in **0.4.10**

**Comment by loserock** [comment]
You have absolutely right, **0.4.10** fixes it. It is available today.
I think we can close this thread.
