### ISSUE TITLE
Limiting the stored offline period

### ISSUE THREAD

**Issue by cuddylier** [nylas/N1#1473]
Hi

I think it would be great if you're able to limit how far back is synced with an email account as syncing email accounts with GBs worth of emails isn't good for low storage devices. A configuration option to select e.g. download 1 month's worth of emails then delete any emails stored offline longer than the set period so the emails kept downloaded any one time don't exceed the time limit set.

**Comment by spawnrider** [comment]
+1 for this feature. 
I have so many old mails in my inbox.

**Comment by bengotow** [comment]
Closing as dup of https://github.com/nylas/N1/issues/1198
