### ISSUE TITLE
Feature Request: Ability to create (protocol) link to email message or thread

### ISSUE THREAD

**Issue by mgroves84** [nylas/N1#1475]
Hello, please consider adding the ability to retrieve a link to a specific message. I couldn't find an obvious way to do this via the API. 

n1://messageid

Scenario:

New email message comes and I know I need to do some work before I respond to the message, so I want to create a task within my task management system with a link back to the mail message. When I complete the task I can use the link to open the message from the email archive and respond to the message. 

This feature exists within Airmail 2. airmail:://message?account&messageid=<id>

Thanks.
Mark

**Comment by NickChristensen** [comment]
Second this, it would open up a lot of possibilities for integration plugins.

**Comment by bengotow** [comment]
This is definitely on the roadmap. Stay tuned—

**Comment by jackiehluo** [comment]
This feature pretty much exists now with the threadsharing plugin we just released!
