### ISSUE TITLE
Plugin: "Send / save to Evernote"

### ISSUE THREAD

**Issue by hans-zen** [nylas/N1#1476]
This is one feature i find really useful in Postbox.

When you click on the evernote button  ![Evernote button](https://cloud.githubusercontent.com/assets/6634296/13374375/c00cc5ba-dd48-11e5-95fd-c0479d286e5e.png)
 the evernote desktop app automaticly creates a new note with the content  or selected content of the email.

![Evernote Function](https://cloud.githubusercontent.com/assets/6634296/13374371/9813ceb4-dd48-11e5-842f-331356ba8be1.gif)

**Comment by mbilker** [comment]
This requires access to Evernote's API, which is public with an API key.

Documentation available at https://dev.evernote.com/doc/

**Comment by bengotow** [comment]
Moving to https://trello.com/c/OhuoJ7nr/59-send-save-to-evernote

**Comment by hans-zen** [comment]
Prfct, thanks :+1:
