### ISSUE TITLE
Updating IMAP/SMTP endpoints is not permitted

### ISSUE THREAD

**Issue by dspangenberg** [nylas/N1#1477]
Hello,

I tried to setup my imap-accout with N1 and get the message "Updating IMAP/SMTP endpoints is not permitted". I thought data would be deleted, if someone disconnect his account from N1? BTW: Safe Harbor isn't valid anymore...

Greetings
Danny Spangenberg

**Comment by Erdou** [comment]
+1
I had to remove and reconfigure my account (only for a password change btw). And now I've got this exact same issue.

**Comment by sfalatko** [comment]
I have a similar issue - and I can't add an outlook.com account (with a custom domain) even when I use an outlook.com alias.

**Comment by seekr** [comment]
I'm trying to add a zoho mail account (setup with my own domain) and it gives out this error.

**Comment by kxr** [comment]
+1

**Comment by fabern** [comment]
Same error message for me when trying an email-account from webfaction.com:
https://docs.webfaction.com/user-guide/email_clients/other.html

**Comment by Porco-Rosso** [comment]
+1

**Comment by lcdss** [comment]
The same here while trying add the second zoho mail account (with custom domain). The fisrt works :sake:

**Comment by Chinney** [comment]
![nylas](https://cloud.githubusercontent.com/assets/5702231/13661728/6e0e8e6e-e695-11e5-94b2-d7de419a8eda.png)

**Comment by Porco-Rosso** [comment]
I only got this problem after I had tried to connect to my provider by exchange. When that didn't work because my provider does not support mobile devices according to the link below. I ran into the issue we are all describing. Such a shame, I really need access to this email.

https://support.nylas.com/hc/en-us/articles/217349727-I-m-getting-Successfully-logged-in-but-your-email-could-not-be-synced-at-this-time-when-connecting-an-Exchange-account

**Comment by Chinney** [comment]
Here's a little workaround that worked for me: I still had the corresponding email account set-up and working on another PC. So I just copied the `~/.nylas` folder onto my other machines and voilà, everything worked again. This was on linux. It'll be probably the same for mac, dunno where local data is stored on Windows though.

**Comment by Porco-Rosso** [comment]
I just tried clearing my .nylas folder to the default and trying to reconnect. Still getting the same error. Are you sure copying ~/.nylas worked for you?

**Comment by logandavis** [comment]
Hi all,

I've added an FAQ to the Nylas support website to address this issue. You can find it here: [https://support.nylas.com/hc/en-us/articles/218006767](https://support.nylas.com/hc/en-us/articles/218006767)

The short version is: this error message appears when N1 determines that your email address has already been registered with a different set of IMAP/SMTP host/port information than what you're providing to N1. For security reasons, we can't let any user change where their auth request goes after the first successful auth, so if you're sure the new information is correct, please email support@nylas.com and we'll have a look at changing the information in our backend. Thanks!

**Comment by Porco-Rosso** [comment]
@logandavis 
Thank you for clarifying the issue. I was able to add the account using the old smtp address. 

However at the moment I am using smtp.live.com, which unfortunately changes the "from address".

Is there any way I can update the smtp address to use my university's provided smtp server? I understand the security concerns with allowing changes.

**Comment by logandavis** [comment]
@Porco-Rosso: If you email us at support@nylas.com with the information for the account you want to update (email address, old host/port, new host/port), we can make that change for you, but as of right now there is no way for you to do it yourself.

**Comment by Chinney** [comment]
What if we just want to change the password? You want us to email you our passwords aswell?

**Comment by logandavis** [comment]
Hm? No, it's totally possible to change your password without emailing support. If you change your password with your email provider (e.g. Gmail, Yahoo), N1 should detect that you've changed the password and prompt you to reauthenticate.

**Comment by Chinney** [comment]
Well, it didn't.

**Comment by Erdou** [comment]
Same for me. Well, I wish you good luck for your beautiful product but I had to change mail client as this is not less than making your client unusable.

**Comment by logandavis** [comment]
@Chinney Would you be willing to email support@nylas.com with your email address so that we can try to diagnose your issue? (If you successfully changed your password with the provider, how could N1 have continued to work? The Sync Engine's requests should've caused authentication errors if your password changed, so your suggestion that N1 didn't detect the change is confusing to me.)

In the meantime, you should be able to change your password by going to "Nylas N1" -> "Add Account" (or to Manage Accounts) and simply signing in again with the new password. If the sign-in succeeds (i.e. the password you give N1 matches the password you use to sign in directly with your provider), N1 will update your credentials.

**Comment by Chinney** [comment]
N1 did not continue to work (at least for that account). It just didn't sync anymore. No prompt asked me for a new password or anything. I clicked through all menus for like half an hour, there was simply no option to change the password. All I could do was deleting the account and setting up a new one. The result of this attempt is well described in this issue.

**Comment by Chinney** [comment]
@Porco-Rosso Sorry, saw your question just now. Yes I am sure replacing the `~/.nylas` folder was what fixed my issue. But before I replaced it, I tried to simply delete it and all N1 related data (`/usr/share/nylas`) and reinstall N1. That however did not work.

**Comment by Chinney** [comment]
Please fix this issue already. Why should I pay for a pro account if n1 does not support simple actions such as changing the password for an account?
