### ISSUE TITLE
System tray icon appears as blank field in kde panel. Arch Linux KDE Desktop.

### ISSUE THREAD

**Issue by diptaks** [nylas/N1#1478]
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [ ] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- [ ] What operating system are you using?
Archlinux 64 bit, KDE Plasma Version: 5.5.4, Qt Version: 5.5.1, Kernel Version: 4.4.1-2-ARCH
- [ ] What version of N1 are you using?

  Version 0.4.9-1

**Bug?**
- [ ] Do you have any third-party plugins installed?
   Yes
- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
   No
- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.
It is reproducible as I start nylas n1 every time. The system tray icon on kde panel just appears to be blank.

**Feature Request?**
- [ ] Does this feature exist in another mail client or tool you use?
Firefox via addon like minimizetotray or firetray.

**Comment by mbilker** [comment]
Upgrade to 0.4.10
