### ISSUE TITLE
Feature Request: Edit Name

### ISSUE THREAD

**Issue by tonynlin123** [nylas/N1#1479]
Gmail has a really useful feature where you are able to change the name you send mail as (under Settings --> Accounts --> Send mail as). My university formats our Google Apps email names strangely (all lower caps, etc.), and it would be really nice if Nylas had similar functionality and supported changing the name with which your emails are sent.

**Comment by jstejada** [comment]
Hi @tonynlin123, I believe you can achieve this with email aliases. You can add aliases by going to `Preferences -> Accounts`. Feel free to reopen this issue if this is not what you are looking for. Thanks!

**Comment by tonynlin123** [comment]
Ah that worked!! I thought you had to specify another email address for an alias, but I guess not! Thank you!
