### ISSUE TITLE
Search bar text in dark color theme is dark

### ISSUE THREAD

**Issue by mbolivar** [nylas/N1#148]
![nylas-dark-view-search-bar](https://cloud.githubusercontent.com/assets/35088/10680649/96148436-78ef-11e5-8ae9-579e66a3e49d.png)

As shown above, the search text input box has dark text in the dark color theme.

**Comment by bengotow** [comment]
Hey—if you're interested in fixing these, there's a bit of info here about doing theme development (it's all just CSS): https://github.com/nylas/N1/issues/74. Pull requests welcome!

**Comment by mbolivar** [comment]
OK, I'll take a look if I find some time. Thanks for the pointer.

**Comment by bengotow** [comment]
Sounds good! The dark theme definitely needs some help :-). Feel free to reach out to me directly on the community slack channel (http://slack-invite.nylas.com) if you need any help getting started.

**Comment by mbolivar** [comment]
Thanks!

By the way, I don't see build instructions for the entire client in the
repo -- I assume that's currently unsupported?

**Comment by bengotow** [comment]
You're welcome to build from source (but you may not need to!) You can find instructions here—https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#getting-started. If you check out the repo, run `script/bootstrap` and then `./N1.sh --dev`, you should be up and running!
