### ISSUE TITLE
Allow Mail rules to move mail to local folders

### ISSUE THREAD

**Issue by joshholt** [nylas/N1#1483]
Many IMAP accounts have quotas, being able to setup up mail rules to move mail to local folders would make N1 a viable option for those types of accounts.

**Comment by bengotow** [comment]
Hey @joshholt - thanks for filing this! Unfortunately N1 does not support local folders and it's unlikely we'll add support for offline storage or mail backup / export because they'd require fundamental changes to the nylas/sync-engine project as well. Sorry for the hassle!
