### ISSUE TITLE
Can't remove label [Mailbox]

### ISSUE THREAD

**Issue by Nosenation** [nylas/N1#1484]
Hi,
I just recently migrated from Mailbox to N1. I deleted all [Mailbox] labels in Gmail web app. I noticed that in N1 after synchronization it still shows empty [Mailbox] label. I can't delete it or rename it.

![n1-mailbox issue](https://cloud.githubusercontent.com/assets/1431712/13378875/0968ba4e-de15-11e5-9486-59d4b5b56b16.png)

I'm using OS X 10.11.1 and N1 0.4.10-4e3595b.

Other:
- Do you have any third-party plugins installed?
Yes only N1-Filters

- Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only use Gmail account.

**Comment by bengotow** [comment]
Thanks for filing this @Nosenation — I'll see if we can reproduce this and keep you posted.

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/rafaelrinaldi/status/748642559770107905

**Comment by jackiehluo** [comment]
Hey! This issue should be fixed now, so I'm going to close it—let us know if you see it again! Thanks!
