### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by federicoiosue** [nylas/N1#1485]
**OS**: Linux Manjaro
**N1 version**: 0.4.10
**Bug description**:  Just create a new mail and try to add a link, the following image is what I got. Also disabling **all** the plugins and moving back to the default light theme doesn' help. Nothing is reported into the log.
![selezione_071](https://cloud.githubusercontent.com/assets/487104/13382186/6fc8b97a-de6e-11e5-96a5-106d31385551.png)

**Comment by bengotow** [comment]
Hi @federicoiosue — If it's nothing personal, could you share the link  you were trying to insert? Does it happen with all links?

**Comment by federicoiosue** [comment]
I didn't inserted any link yet, it crashes just by opening the _add link_
dialog, both by shortcut or selecting text and then using the add link action
on the dialog that appears.  
![](https://link.nylas.com/open/7vjrx0c0tcxineb9xy9cu8dii/7c5c028df6044474a527
42ccc2228bd3)

> On Feb 29 2016, at 8:28 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@federicoiosue](https://github.com/federicoiosue) — If it's nothing
personal, could you share the link you were trying to insert? Does it happen
with all links?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1485#issuecomment-190346519).![](https://github.com/notifications/bea
con/AAduwHOUmXE572Cxdc_VkRjSJM_Nk3D6ks5po0H1gaJpZM4Hk9Ov.gif)

**Comment by oatmealraisin** [comment]
I have also encountered this problem.  Linux, using version 0.4.14, replying to/from a gmail account.

**Comment by federicoiosue** [comment]
Still broken on version 0.4.19

**Comment by jackiehluo** [comment]
Hey! This issue should be fixed now, so I'm going to close it—let us know if you see it again! Thanks!
