### ISSUE TITLE
Gmail account stoped syncing

### ISSUE THREAD

**Issue by Slepice1** [nylas/N1#1486]
My Gmail account just stoped syncing, I'm using N1 on both Linux (Elementary OS) and Windows 10 and oin both OS it just stoped. When I remove the account and add it again it works for day or two and then stop again.

**Comment by AlbertoCG** [comment]
Do you have any more information about the circumstances required to reproduce it?

It stops on both? Windows 10 and Linux?

Is there a syncing message or you don't see it at all?

**Comment by Slepice1** [comment]
It stops on both, and there is no syncing message.

**Comment by tsunammis** [comment]
same for me ... I just seeing old gmail messages when I tried nylas few months ago.

**Comment by jstejada** [comment]
Hey @tsunammis, if your account was inactive for a long while it may take up to an hour to resync it completely. if you continue having trouble syncing your mail email support@nylas.com with your account details. Thanks!

**Comment by jstejada** [comment]
@Slepice1, it is probably best if you email support@nylas.com with your account details so we can diagnose the problem. 
Thanks!

**Comment by tsunammis** [comment]
@jstejada Email sent :)

**Comment by Petur06** [comment]
Same problem here, gmail stopped syncing. No sync messages displayed.
Running v 0.4.10 on Win 7 x64

**Comment by MaxSong24** [comment]
Same to me,  MacBook Pro Retina bought I month ago.
