### ISSUE TITLE
Icon in taskbar is gone

### ISSUE THREAD

**Issue by Johnytian** [nylas/N1#1487]
N1 is running well before today. The icon in taskbar were gone when I updated to 0.4.10. It is not a big issue but it looks uncomfortable. The operating system is Win10 x64 English.

**Comment by BigOz** [comment]
I've run into the same problem on Linux...when I updated to 0.4.9 from I believe 0.4.5, icon has disappeared. I have rebooted my machine several times since. The space in the taskbar is there...sometimes clicking on that space brings up the options you'd expect...but sometimes not.

**Comment by Johnytian** [comment]
This issue has appeared in 0.4.16 version. The operating system is Win10 x64 English.

**Comment by bengotow** [comment]
Hey folks! his should be fixed in the latest release (0.4.40). Can you see if it's working for you now? If it's still an issue, we can re-open this issue. Cheers!
