### ISSUE TITLE
Feature Request: Sync account configuration between machines

### ISSUE THREAD

**Issue by Johnytian** [nylas/N1#1488]
could you please add account information backup feature? Many people have more than one PC or Mac, and sometimes we have to reinstall N1 when the N1 has some problem or the operating system is reinstalled. If the account information can be backed up, it will save much time to add the account again. This feature can be found in Foxmail and other apps I think.

**Comment by cvburgess** [comment]
Mailbox used to do this via Dropbox. Knowing that is OSS, I would love to see a simple config file that contains account info that you could sync with any provider (Dropbox, iCloud, Box, etc) and the user just re-enter sensitive information (passwords) when setting up a new client.

I would be happy to contribute if someone outlines a spec for this!

**Comment by cvburgess** [comment]
A pile-on comment: signatures and preferences could also be synced for an optimal user experience

**Comment by jackiehluo** [comment]
Merging into #2484 now that we have Nylas IDs!
