### ISSUE TITLE
Mailbox Syncing

### ISSUE THREAD

**Issue by garethgreenaway** [nylas/N1#1489]
I've setup an email account in N1 as an IMAP account, following the setup the mailboxes are synced and mail begins to show up.  There are certain folders that show as empty in N1, folders that definitely have email in them.  Is there a way to force a sync for these folders or a way to see why they're not syncing?

**Comment by b-connect** [comment]
Same to me. Mail server is an axigen.

**Comment by marshallmcmullen** [comment]
Same for me as well. I see this behavior with normal gmail accounts and imap accounts as well.

**Comment by b-connect** [comment]
Seems to be a duplicate https://github.com/nylas/N1/issues/1338

**Comment by bengotow** [comment]
Hey folks - closing as a dup of #1338.
