### ISSUE TITLE
Launch on system start issue

### ISSUE THREAD

**Issue by dkouvdis** [nylas/N1#1490]
Hi

I have the "Launch on system start" enabled. Every time I switch on my Mac, I see two N1 running.

Sent me instructions if you need me to debug further

![screenshot 2016-02-29 09 48 12](https://cloud.githubusercontent.com/assets/2727196/13391025/fc4fe6a6-dec9-11e5-8004-05f0dffb7aff.png)

**Comment by bengotow** [comment]
This should be fixed in the next release now that we're using `app.makeSingleInstance. Cheers!

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
