### ISSUE TITLE
Edit accounts

### ISSUE THREAD

**Issue by Wikunia** [nylas/N1#1494]
Sometimes it's quite annoying if there is an error in your account and you're not able to edit it.
It's only possible to delete the account and create a new one.
Sometimes means:
- You changed your mail password
- You misspelled something

I am using N1 v0.4.10
Linux 4.4.1-2-ARCH

**Comment by jstejada** [comment]
Hi @Wikunia, thanks for reporting this! I'm merging into duplicate #230
