### ISSUE TITLE
Hide phishing message for GitHub mails

### ISSUE THREAD

**Issue by iDuuck** [nylas/N1#1495]
**OS:** OS X El Capitan (10.11)
**Version Number:** 0.4.10-4e3595b (0.4.10-4e3595b)
**Screenshot:** https://www.dropbox.com/s/hlatujaz2zz6bhd/Screenshot%202016-02-29%2012.29.29.png?dl=0

*Reproduceable by receiving a message from github.*

**Comment by bengotow** [comment]
Thanks @iDuuck — we really need to revisit that phishing detection plugin. It's a really nice example plugin because the code is simple, but it has very basic logic for identifying phishing emails.

**Comment by bengotow** [comment]
Merging into https://github.com/nylas/N1/issues/1321
