### ISSUE TITLE
Negative read counters

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#1496]
On two of my email accounts I have negative unread email counts.  I'm running the latest release on Windows10.

![unread count](https://cloud.githubusercontent.com/assets/4201518/13393781/0ca53500-defd-11e5-9197-5597ecf0f717.jpg)

**Comment by jstejada** [comment]
Hi @molstrangler, thanks for reporting this. This is indeed a known issue and we are working to fix it. I'm merging this issue into duplicate #759. As a temporary solution, you can remove the `.nylas` directory in your home directory and restart N1.
Thanks!
