### ISSUE TITLE
The window in Windows is offscreen

### ISSUE THREAD

**Issue by ericrange** [nylas/N1#150]
The window in Windows is offscreen! Cant move it elsewhere. Its in the left upper corner auf my screen.
I tested it with 2 device, same behaviour!

i tried several tricks to move the window, but it all didnt work out.

**Comment by ericrange** [comment]
Today i got the invitation email with my invitationcode. just clicked on the installer.
I didnt do anything else.

**Comment by ericrange** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/1785416/10686401/0959f4b6-7964-11e5-96b4-f61c2b470876.png)

**Comment by antitim** [comment]
the same problem
windows 10

**Comment by antitim** [comment]
@ericrange 
temporarily solution

alt + space + m
and arrows

**Comment by kyungmi** [comment]
I have the same problem too.
@antitim Thanks a lot!

**Comment by bengotow** [comment]
Whoa that's no good. Thanks for reporting this. We'll take a look at this today and see if we can get a patch out. Once you use @antitim's temporary solution, do other windows in the app work alright?

**Comment by ericrange** [comment]
once u do the alt + space + m trick, all other windows show work correctly

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. We've tracked this down to this line (https://github.com/nylas/N1/blame/master/src/atom.coffee#L431), which results in a divide-by-zero when we try to animate the window's position. It'll be fixed in a small patch later today. Thanks for reporting this issue.

**Comment by antitim** [comment]
@bengotow , yes, other windows work alright
