### ISSUE TITLE
Markdown > HTML converts rich-text signature to plain text

### ISSUE THREAD

**Issue by rasterbate** [nylas/N1#1500]
In the composer window, clicking the Markdown > HTML button in the bottom menu bar in removes all styling from a rich-text signature. 

Nylas version 0.4.10-4e3595b (0.4.10-4e3595b) 
OS X 10.11.2

### Before
![_screenshot 2016-02-29 at 9 43 28 am redacted](https://cloud.githubusercontent.com/assets/3334478/13397810/8e60f55e-dec9-11e5-9607-3434c45cbd08.png)

### After
![_screenshot 2016-02-29 at 9 43 44 am redacted](https://cloud.githubusercontent.com/assets/3334478/13397831/a0a1c52c-dec9-11e5-96fa-958415d4f161.png)

*redacted for paranoia*

**Comment by jstejada** [comment]
Hi @rasterbate, what markdown plugin are you using? I believe the plugin you are using is from a third party and the issue should be filed in its own repo, so I'm closing this issue.
Thanks!
