### ISSUE TITLE
IMAP/SMTP errors when connecting account

### ISSUE THREAD

**Issue by bchar** [nylas/N1#1502]
Not sure this is an issue may be user error. Trying to set up both my gmx & Mail accounts and having IMAP/SMTP errors. Any ideas? Mac OS X 10.9.5, N1: Version 0.4.10-4e3595b.. Testing is available in Windows 10/8.1/7, Ubuntu 15.10LTS & Android 6.0/5.01, iOS 9/8/7/6. I am open to helping out in near future as a taste tester. This project is interesting to me and want to see it succeed.

**Comment by jstejada** [comment]
Hi @bchar, thanks for reporting this. This knowledge base article might help you: https://support.nylas.com/hc/en-us/articles/216118977-What-are-the-limitations-of-IMAP-SMTP-support-

There are also a couple of similar issues where you can find some reference for your problem:  #47, #322.

If you continue to have problems authenticating generic IMAP accounts that use IMAP/SMTP-specific credentials, please email support@nylas.com.

Thanks for your patience!
