### ISSUE TITLE
Can´t see Gmail Sub-tags

### ISSUE THREAD

**Issue by jcguinea** [nylas/N1#1505]
In the Tags list doesn´t appear the sub-tags of GMAIL
<img width="1280" alt="captura de pantalla 2016-02-29 a las 9 43 20 a m" src="https://cloud.githubusercontent.com/assets/12300966/13405187/dc7b474e-dee2-11e5-8ea2-78c228e3ec16.png">
<img width="1124" alt="captura de pantalla 2016-02-29 a las 9 43 34 a m" src="https://cloud.githubusercontent.com/assets/12300966/13405188/dc7e682a-dee2-11e5-9edb-84d9ea3a483f.png">

**Comment by bengotow** [comment]
Hi @jcguinea — thanks for filing this. I think this is related to the mailsync issue where labels are being marked as deleted. Will check it out!

**Comment by jackiehluo** [comment]
Oh, wait, I'm pretty sure this issue's related to #1346, since Taiga doesn't have the disclosure triangles that allow you to view nested inboxes, labels, etc. Merging it, but it should work for other themes (and we're looking at how to add them back into Taiga).
