### ISSUE TITLE
Button icons missing on latest linux update

### ISSUE THREAD

**Issue by vpakg** [nylas/N1#1507]
Version 0.4.5 on Linux, missing icons on buttons (Installed in two different computers - Ubuntu and Elementary OS, and they are both presenting the same issue).

![screenshot](http://i.imgur.com/nDErxif.png)

**Comment by mbilker** [comment]
Have you restarted N1 after installing the update? This occurs because the `app.asar` file changes while N1 is running. Please make sure you quit N1 and not close the window.

**Comment by vpakg** [comment]
Hi @mbilker , it seems to be the case. I didn't realise that by closing the application it would still be running in the background, seems to have fixed itself after rebooting the system this morning.

**Comment by DavertMik** [comment]
Thanks for creating this issue. This advice was useful to me
