### ISSUE TITLE
N1 will not launch without `sudo` following AUR upgrade

### ISSUE THREAD

**Issue by phsmith** [nylas/N1#1508]
Hi! After upgrading to N1 0.4.10 on Archlinux x86_64, the program don't open as normal user, only opens as root.

The following error is showed:
Streaming log data to /tmp/Nylas-N1-1645.log
[1]    1645 segmentation fault (core dumped)  /usr/share/nylas/nylas

That log don't show anything, it's empty. 

After execute the dmesg command, I've found the following error:
[ 4060.501395] nylas[1645]: segfault at 7ffdcd12ea20 ip 00007fbcd770dbc4 sp 00007ffdcd12ea00 error 6 in libfreetype.so.6.12.3[7fbcd76aa000+b9000]

The N1 on Archlinux is provided from AUR repository and it's based in the Debian package.

**Comment by bengotow** [comment]
Hi @phsmith — any chance this is due to the way you upgraded the program? We don't publish an official AUR build so I'm not sure what it does. If it sets the permissions incorrectly on the app, this could definitely happen.

**Comment by mbilker** [comment]
This appears to be an error in the `freetype` library, which Chromium depends on for fonts. Is there any chance there is a problem with that?

I use `freetype2-infinality-ultimate` on my system because the Infinality patches provide better font rendering on both my desktop computer and laptop in almost every application I use.

**Comment by phsmith** [comment]
@mbilker, the error is exactly with freetype, but I'm using the default so there's no relation with freetype2-infinality-ultimate.

And @bengotow, I've checked the permissions and apparently are all OK. Are the same from N1 older version.

**Comment by mbilker** [comment]
@phsmith Do you use Slack native on Linux or Atom on Linux?

If those apps crash the same way as N1, then there is an issue with the way we package N1. N1 currently uses the prebuilt Electron, which is compatible with most Linux platforms.

**Comment by mbilker** [comment]
Are you running the non-stock Arch kernel (rt, grsec, zen)?

**Comment by phsmith** [comment]
@mbilker I have Atom installed, but not tested if it's working. I'm on the work now...
And I use a non-stock kernel too, the CK Kernel.

**Comment by mbilker** [comment]
What version of `fontconfig` and `freetype2` do you have on your computer?

I have `fontconfig 2.11.1` and `freetype2 2.6.2`.

```
[~] pacman -Q fontconfig-infinality-ultimate 
fontconfig-infinality-ultimate 2.11.1-30

[~] pacman -Q freetype2-infinality-ultimate 
freetype2-infinality-ultimate 2.6.2-4

**Comment by phsmith** [comment]
Mine is:
fontconfig 2.11.1-2
freetype2 2.6.3-1

**Comment by mbilker** [comment]
@phsmith If you run `fc-cache -fv`, does it crash the same way?

**Comment by phsmith** [comment]
@mbilker crashed the same way, even after fc-cache command.

**Comment by mbilker** [comment]
Oops, I misphrased. Does the `fc-cache` command crash?

**Comment by mbilker** [comment]
This is blocked on extenal packages.

https://github.com/atom/electron/issues/4513

**Comment by phsmith** [comment]
No! Worked 100%.

**Comment by mbilker** [comment]
Do you use the `testing` repositories in Arch?

**Comment by mbilker** [comment]
@phsmith From reading the bug report on Electron, it appears to be fixed in recent versions of Electron where they now compile `electron-prebuilt` with a patched `harfbuzz` to solve this issue with `freetype2 2.6.3`.

**Comment by phsmith** [comment]
No, I'm not use testing repository! 
And I've just downgrade the freetype2 to version 2.6.2-1 and the crash persists.

**Comment by mbilker** [comment]
That is odd that the crash persists. It should work with `freetype2 2.6.2`. Try rebooting.

**Comment by phsmith** [comment]
Continues to crash, even after reboot.

**Comment by phsmith** [comment]
I've just found the problem....

I'm changed the font from my desktop environment, XFCE, to Dejavu Sans and the program opened normally again.

I closed the program and changed the font back to my default, Aller, and it opened without problem too. 

So, think that the problem was solved.

**Comment by phsmith** [comment]
Ah! Another thing that I've made before the get the problem solved was, backup my ~/.fonts folder, create it again, put only my preferred font inside the folder, and execute fc-cache -fv.

I think that some old fonts caused the problem.

**Comment by jackiehluo** [comment]
Closing this issue because it looks like it was resolved!
