### ISSUE TITLE
Add support for high resolution screen

### ISSUE THREAD

**Issue by princeofgiri** [nylas/N1#151]
The interface looks very small in high resolution screen. I use 3200 x 1800 on my laptop.

**Comment by grinich** [comment]
Hi @princeofgiri can you paste a screenshot of it running in high-res? The app is designed for "Retina" on Mac. What laptop do you have?

**Comment by princeofgiri** [comment]
![cuplikan layar dari 2015-10-24 07-02-47](https://cloud.githubusercontent.com/assets/837709/10707489/46ea3e62-7a1d-11e5-8ed2-672a75a1894a.png)

I'm using linux (debian based distribution)

**Comment by psychonaut** [comment]
This is electron/chromium bug: [https://github.com/atom/electron/issues/1228]

**Comment by nicoseb** [comment]
Hi, I see on that post that this issue in electron has supposed to be fixed...
I am running elementary-os, with chromium 45.x and still need to use the "force-rescale-factor" hack to get it to look OK.
I tried the same hack in nylas but this does not work :(
Looks beautiful but unusable given the tiny font (as shown by princeofgiri)

Any news?
Thanks

**Comment by bengotow** [comment]
Hi @nicoseb — we pulled Electron upstream a few days ago, not sure if you were building from the repo or using the last released version. It should be fixed in the next update, but I'd love if you could try it and let us know.

**Comment by nicoseb** [comment]
Oh I see, thanks!
I first build from repo, but then just had a "N1" splash screen and nothing else, so I just went with the latest Deb file... ;-)

Sounds good, I'll wait for the update :)

Thanks
Nick

**Comment by nicoseb** [comment]
Hi @bengotow the last deb file (0.4.24 or something like that...) ended up breaking N1 the same way I had it when compiling it myself... So I guess everything was "OK" when I built it.
It crashes during loading, complaining that a path is set to empty...
Do you know if you guys plan on a new "deb" release soon?
Otherwise I might have to go back to building from source again!
Thank you,
N

**Comment by nicoseb** [comment]
@bengotow , of course... I should not have posted my last message ! ;)
0.3.26 fixed both issues, everything looks good!
Thank you

**Comment by bengotow** [comment]
Glad it's fixed!
