### ISSUE TITLE
/auth endpoint 401/403 errors cause "you need to sign out" message in main window

### ISSUE THREAD

**Issue by bengotow** [nylas/N1#1510]
This appears if you open onboarding and fail to sign in to a new account:

![image](https://cloud.githubusercontent.com/assets/1037212/13414000/d636f092-df03-11e5-86e9-66919a22a489.png)

**Comment by grinich** [comment]
@bengotow is this a backend auth bug?

**Comment by bengotow** [comment]
This was fixed in 0.4.14. Enjoy!
