### ISSUE TITLE
tab doesn't complete emoji selection

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1511]

**Comment by jackiehluo** [comment]
@grinich Should it insert the emoji on tab? I'm not sure how useful it is to complete the word (like in Slack).

**Comment by grinich** [comment]
Yeah I think it should just complete with the selected one





On Mon, Feb 29, 2016 at 6:01 PM -0800, "Jackie Luo" <notifications@github.com<mailto:notifications@github.com>> wrote:


@grinich<https://github.com/grinich> Should it insert the emoji on tab? I'm not sure how useful it is to complete the word (like in Slack).

-
