### ISSUE TITLE
Not responsive after adding Exchange Account

### ISSUE THREAD

**Issue by alpipego** [nylas/N1#1512]
After adding an Exchange account I can't use N1 anymore. Both panes are simply displaying the loading animation and I can't open preferences to remove/disable accounts/plugins. 

I have attached the complete console output.
I am on __OS X 10.11.3__ using __Version 0.4.10-4e3595b (0.4.10-4e3595b)__

[nylas-n1.txt](https://github.com/nylas/N1/files/152338/nylas-n1.txt)

(This version has been installed via homebrew cask, I have also tried installing it via zip from your website, but no changes there.)

What's the best way of removing all configuration and starting with a "blank" app?

**Comment by jstejada** [comment]
hey @alpipego thanks for your report. I'll look into this

**Comment by jackiehluo** [comment]
Send us an email at support@nylas.com if you experience this issue!
