### ISSUE TITLE
openSUSE RPM issue

### ISSUE THREAD

**Issue by tuxtard** [nylas/N1#1513]
N1 0.4.10 failes to start on both openSUSE Leap 42.1 and openSUSE Tumbleweed with the following message:

`Can't find the Electron executable at /usr/local/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/local/bin or set the ELECTRON_PATH environment variable.`

**Comment by alexandru-calinoiu** [comment]
I am running Thumbleweed and I have no issue with the latest release I grabbed from here.

**Comment by tuxtard** [comment]
Have you installed any additional dependencies?

**Comment by mbilker** [comment]
Use the `/usr/share/nylas/nylas` or `/usr/local/share/nylas/nylas` command to start N1. A PR to fix this is pending a merge.
