### ISSUE TITLE
Local Date Format for Snooze Input

### ISSUE THREAD

**Issue by nagelflorian** [nylas/N1#1515]
Hey there,

I just ran into this minor UX issue:

Being in Germany and having my system language and region set to the corresponding options, I expect the snooze input to use my local date format (Day-Month-Year). Instead it is currently using your crazy American system (Month-Day-Year). 😉

![snooze](https://cloud.githubusercontent.com/assets/7649376/13426825/5c78be9a-dfb0-11e5-8554-4c267bf1fd3e.png)

**Comment by jstejada** [comment]
hi @nagelflorian thanks for reporting this! totally missed it. Will update this in an upcoming release

**Comment by nagelflorian** [comment]
Wow @jstejada that was quick! Very much appreciated. 👍
