### ISSUE TITLE
Keyboard shortcut for snooze

### ISSUE THREAD

**Issue by eibrahim** [nylas/N1#1516]
I understand how to add custom keyboard shortcuts.  What I don't know is how do I get the list of commands available to me that I can map shortcuts to?

say I want to map something like this:

```
'body':
  't' : 'message:snooze-tomorrow'
```
where do I find the appropriate command to use?

**Comment by mbilker** [comment]
Dupe of #1424 

Keyboard shortcuts for snoozing are not available yet. Only gestures are supported on compatible platforms.

**Comment by eibrahim** [comment]
thanks, but i guess my main question is, where do i find the list of available commands to me, so I can customize the key bindings?

**Comment by kinshuk4** [comment]
Hi Nylas Team, thank you for the awesome product. Please let me know if there is any specific menu option for snoozing, so that I can customize it using Mac's keyboard shortcut approach, meanwhile you guys can take your time and implement the key bindings in the App itself. Thanks.

**Comment by devonzuegel** [comment]
@eibrahim You can find the list of the default keymaps here: github.com/nylas/N1/blob/master/keymaps/base.cson. You can find the keymap templates for GMail, Inbox, Apple Mail, and Outlook defaults here: github.com/nylas/N1/tree/master/keymaps/templates.

**Comment by eibrahim** [comment]
Thanks @devonzuegel I saw that already but it doesn't seem like there is a way to map snooze to a shortcut.  Unless I am missing something!!!

**Comment by cmwoo** [comment]
@eibrahim Ah all righty, I thought you were asking for all available commands. As far as I know, those are the only ones available right now. I'm also looking forward the `snooze-commands` key binding.

**Comment by devonzuegel** [comment]
@eibrahim Ah all righty, I thought you were asking for all available commands. As far as I know, those are the only ones available right now. I'm also looking forward the `snooze-commands` key binding.

**Comment by tommydangerous** [comment]
The snooze commands via key binding would be ultra helpful

**Comment by aTherkildsen** [comment]
Where are we on this - it's one of the key features I'm still missing from N1.

**Comment by HemalR** [comment]
+1 for this - thanks for the awesome app!

**Comment by kjwierenga** [comment]
+1 for this too - trying to leave Polymail for Nylas N1

**Comment by manicmarvin** [comment]
This should be re-opened.

**Comment by kriskhaira** [comment]
@manicmarvin This issue is a duplicate of #1424, which is still open.
