### ISSUE TITLE
N1 reset all my accounts

### ISSUE THREAD

**Issue by Jeremy-Walton** [nylas/N1#1518]
I know https://github.com/nylas/N1/issues/735 exists, but I know for a fact that the solution for that is not the same as my case. I do not have a full disk so it can't be that.

I am using OSX El Capitan and using Nylas N1 Version 0.4.10-4e3595b (0.4.10-4e3595b)
I have one theme plugin, but other than that, i'm using built in plugins

**Bug**
I noticed that one of my gmail accounts was not updating correctly so I closed N1 completely and restarted it. When it turned back on, all my accounts had been reset and I had to add them back (3 gmail, 1 smtp setup).

**Comment by bengotow** [comment]
Hey @Jeremy-Walton — sorry you ran into this bug! That's definitely not good. I'll take a look and see if we can narrow this down.

**Comment by brasilikum** [comment]
Might be related to #1348

**Comment by jstejada** [comment]
hi @Jeremy-Walton, this should have been fixed by now (#1133, #1348). Let me know if you are still having issues!

**Comment by Jeremy-Walton** [comment]
I haven't had it happen since. I believe it was https://github.com/nylas/N1/issues/1133 because I do remember running the specs.
