### ISSUE TITLE
App icon source file

### ISSUE THREAD

**Issue by alecive** [nylas/N1#1519]
Hey, I was looking for a high-resolution, possibly scalable version of your app icon, but I didn't find it in the repo. Do you have some link to refer me to? I would like to port the app icon to my iconset (i.e. github.com/alecive/FlatWoken ) but I would like to start from the best source file you have.

Related to #683

**Comment by mbilker** [comment]
Here ya go! https://github.com/nylas/N1/blob/master/build/resources/nylas.png

**Comment by mbilker** [comment]
It is 512x512 as the largest size for an OS X icon is 512x512.

**Comment by alecive** [comment]
Thank you!
