### ISSUE TITLE
mailto: links are tracked and don't work

### ISSUE THREAD

**Issue by ridem** [nylas/N1#1525]
First of all, **congrats** for the link tracking feature, it's the first time that I see such a cool feature on a desktop client, neat integration!

At [https://github.com/nylas/N1/blob/master/internal_packages/link-tracking/lib/link-tracking-composer-extension.es6#L30](https://github.com/nylas/N1/blob/master/internal_packages/link-tracking/lib/link-tracking-composer-extension.es6#L30), you're converting all href attributes to tracked links. I think you should only match http* links. Getting a new browser window for mailto: links is quite bad user experience.

On top of it, the server side can't handle mailto: links, which makes the feature broken.

I can try to PR if needed.

**Comment by bengotow** [comment]
Hey! Ahh good catch—that's definitely something we need to fix. If you want to take a pass at improving the regexp, pull requests are definitely welcome!

**Comment by adenix** [comment]
This issue is closed, however, I am seeing this issue in Version 1.0.30 (1.0.30) on macOS Sierra Version 10.12 Beta (16A313a)
