### ISSUE TITLE
Feature: Add "spacebar" to keymap for shortcuts

### ISSUE THREAD

**Issue by stffndtz** [nylas/N1#1534]
I would love to have the spacebar as a valid key to be used for shortcuts. I couldn't find a definition for the spacebar in the input-resets and wasn't able to hook up any action on either "space" or "spacebar".

This shortcut exists in Mail Pilot (http://mindsense.co/mailpilot/) and I found it highly usable for archiving items.

~~If someone could point me into the right direction, I am sure I could be able to implement it myself.~~ Any help and suggestions are highly appreciated!

**Comment by bengotow** [comment]
This actually works now! In our new Shortcuts panel, you can use Space as a modifier key and assign it to a shortcut:

![image](https://cloud.githubusercontent.com/assets/1037212/17234582/243ce16e-54ef-11e6-935d-9eb888e62062.png)

Cheers!
