### ISSUE TITLE
Cannot recursively fetch N1.git

### ISSUE THREAD

**Issue by marshallmcmullen** [nylas/N1#1537]
I'm trying to recursively fetch nylas git repo and all its submodules as part of integrating N1 into a proper Gentoo ebuild. It's git eclass tries to recursively fetch all submodules. Unfortunately this fails:

>>> Unpacking source...
Initialized empty Git repository in /usr/portage/distfiles/git3-src/nylas_N1.git/
 * Fetching https://github.com/nylas/N1.git ...
git fetch https://github.com/nylas/N1.git +HEAD:refs/git-r3/HEAD
remote: Counting objects: 28496, done.
remote: Compressing objects: 100% (2351/2351), done.
remote: Total 28496 (delta 1584), reused 0 (delta 0), pack-reused 26081
Receiving objects: 100% (28496/28496), 28.58 MiB | 581.00 KiB/s, done.
Resolving deltas: 100% (20795/20795), done.
From https://github.com/nylas/N1
 * [new ref]                    -> refs/git-r3/HEAD
 * [new tag]         0.3.23     -> 0.3.23
 * [new tag]         0.3.25     -> 0.3.25
 * [new tag]         0.3.29     -> 0.3.29
 * [new tag]         0.3.32     -> 0.3.32
 * [new tag]         0.3.36     -> 0.3.36
 * [new tag]         0.3.38     -> 0.3.38
 * [new tag]         0.3.43     -> 0.3.43
git symbolic-ref refs/git-r3/mail-client/nylas-n1/0/__main__ refs/heads/master
 * Fetching git@github.com:nylas/edgehill.git ...
git fetch git@github.com:nylas/edgehill.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
**Permission denied (publickey).
fatal: Could not read from remote repository.
**

**Comment by grinich** [comment]
yeah "edgehill" is a private subtree with stuff like typefaces that we cannot open source, hence it will fail.

**Comment by marshallmcmullen** [comment]
Alright, that makes sense. I'll have to find a way to workaround this then.

Thanks for the quick response... feel free to close this.

**Comment by mbilker** [comment]
@grinich What typeface is NylasPro?
