### ISSUE TITLE
Bug on hover

### ISSUE THREAD

**Issue by orkhanfarmanli** [nylas/N1#1538]
Hello there. I want to inform you about an issue in Ubuntu 15.10. There is no File menu while hovering over the window. I don't know if it is feature or a bug but here is a screenshot of it for you to check.

http://imgur.com/FOoatlu

**Comment by jstejada** [comment]
Hi @orkhanfarmanli , thanks for reporting this. This seems like a duplicate of #911, so I'm merging it in.
