### ISSUE TITLE
Unread count label

### ISSUE THREAD

**Issue by cipriota** [nylas/N1#1539]
OS: Ubuntu 15.10
N1: 0.4.10
Source: gmail

My inbox indicates that there are 2 unread messages, but Gmail web interface has no new e-mail.

![image](https://cloud.githubusercontent.com/assets/1589885/13456037/eb301a68-e058-11e5-8ad4-50850c23f632.png)

**Comment by bengotow** [comment]
Hi @cipriota — thanks for filing this! We'll get this fixed soon. Closing as a dup of #1379
