### ISSUE TITLE
Sent emails appear as drafts

### ISSUE THREAD

**Issue by YanuFreaky** [nylas/N1#154]
All the mails I sent with my exchange mail adress with another mail client appeared after including it to N1 as drafts and not as sent messages. Furthermore, all my drafts appear as sent emails. So you should "just" swap those 2 categories with each other and everything should be fine.

**Comment by grinich** [comment]
Hi @YanuFreaky. This is happening with the left sidebar items? Can you still edit the drafts?

**Comment by YanuFreaky** [comment]
@grinich Yeah exactly. Those mails in "Sent Items" got a small pen above the title and when I open them, they are yellow coloured and got a "Send" button beneath them. There's no button showing "Write a reply", so the layout is different from the Items i sent with N1.

I can also edit the (sent) messages in the "Drafts" folder.

**Comment by jacobmischka** [comment]
I am also experiencing this.

**Comment by grinich** [comment]
@YanuFreaky can you email me the address this is having issues with? Sounds like it's a problem for how we map folders to those with only drafts. I'm mg@nylas.com

**Comment by DaveFlynn** [comment]
I am also experiencing this issue.

It only occurs in my Exchange email account. Gmail and Hotmail are fine.

**Comment by raulzito234** [comment]
Same here.

**Comment by khwerhahn** [comment]
Same here (gmail). I have no drafts in gmail, but N1 shows 40+ "Drafts"

**Comment by DaveFlynn** [comment]
I found that adding the exchange account manually as an IMAP account, rather than choosing Microsoft Exchange, solved the issue for me.

**Comment by jacobmischka** [comment]
This is the only thing keeping me from using N1 as my default mail client :(

**Comment by rdewolff** [comment]
Same here! Anyone taking care of this annoying bug preventing us from using Nylas?

**Comment by rdewolff** [comment]
Related to https://github.com/nylas/N1/issues/471

**Comment by jstejada** [comment]
merging into #869

**Comment by jacobmischka** [comment]
Why merge this into that one if this one is much older and has a lot more people subscribed?

**Comment by rdewolff** [comment]
Thought the same :)

On 30 décembre 2015 at 22:14:25, Jacob Mischka (notifications@github.com) wrote:

Why merge this into that one if this one is much older and has a lot more people subscribed?

**Comment by agumartina** [comment]
The same here on Gmail, after send an email appears a draft on N1 and Gmail.

**Comment by Ozcrossbow** [comment]
Having the same issue. Compose and send email via Gmail, email is sent and stored in "Sent Mail" but also a copy is placed into drafts. 
Really like the clean appearance of N1 so want to use as default client but this is an impediment.

**Comment by rdewolff** [comment]
+1 Ozcrossbow

Plus during my last test, reinstalled the whole version (deleting all preferences) and after 1-2 test, the application crashed.
