### ISSUE TITLE
Feature - Email Stats

### ISSUE THREAD

**Issue by khwerhahn** [nylas/N1#1542]
I haven't seen this feature somewhere in action, but it would be nice, to have some email stats to track yourself. This really helps to optimise your workflows and see if you can improve yourself. Maybe even add some gamification?

**KPIs:**
Emails sent in a given time (i.e. today)
Emails received in a given time
AVG Time to reply
Spam Emails
.....

**Comment by bengotow** [comment]
Thanks for filing this! I'm moving this to the plugin ideas board here: https://trello.com/c/sXKZUrue/66-email-stats
