### ISSUE TITLE
Software update does not work on Linux

### ISSUE THREAD

**Issue by jvanz** [nylas/N1#1543]
N1 is not being updated to the newest version as on Windows does.

**Comment by mbilker** [comment]
Software update on Linux is through your package manager. Squirrel updater (from Atom) and used by many Electron projects does not support Linux.

**Comment by jvanz** [comment]
Do you have plans to add the N1 package in mainstream distros repos?

**Comment by mbilker** [comment]
@jvanz Nylas provides their own (weird) APT repository for Debian and Ubuntu-type distributions that use `dpkg`.

**Comment by jvanz** [comment]
Do you have plan to a RedHat like distributions? Fedora to be more specific.

**Comment by bengotow** [comment]
Hey! We run `apt.nylas.com` for auto-updates on Ubuntu / debian. From my understanding it's the best way to do it on Linux (one of our platform engineers is a Debian contributor and set it up!)

You should be prompted to download the RPM build of N1 if you visit https://invite.nylas.com/download from a Linux machine. If you don't see the option, you can also get the latest RPM build from our GitHub releases: https://github.com/nylas/N1/releases

We don't have any auto-updater support for Fedora and I'm not sure what the most native way to do it would be. Any ideas would be appreciated, but I think we have fairly few .rpm users at the moment.

**Comment by jvanz** [comment]
All Linux distribution, at least all I know, have package manager. Debian and Ubuntu are apt-based distribution. Fedora and OpenSUSE are RPM-based distribution. As far I know, to allow allow the auto-update for rpm-based distros you need to create a similar package repository as you already did for Debian.

**Comment by perry-mitchell** [comment]
N1 has updated from apt for me on a couple of machines, accidentally, and it has started breaking the application (missing assets, eventually clicking Send does not work). I understand we have to update N1 from the releases here, but is there any way to prevent updates from apt? They seem to conflict with N1 quite seriously.

**Comment by mbilker** [comment]
@perry-mitchell Restart N1 using `File -> Quit`

**Comment by mbilker** [comment]
Bug with Electron attempting to load from the ASAR archive, but it was updated by APT.

**Comment by perry-mitchell** [comment]
I think is definitely warrants a bug.. I've created a new issue for it -> #1742. I will try to close the process if it's still running, but there is no file menu (broken).
