### ISSUE TITLE
Searching returns no result since 0.4.10-4e3595b (or one version earlier)

### ISSUE THREAD

**Issue by bnsblue** [nylas/N1#1544]
I noticed that the searching stops working since I installed 0.4.10-4e3595b (or one version earlier). No matter what I put in the search box, N1 almost always returns nothing after a while of spinning.

I experienced this issue on both of my ubuntu 14.04 and my Mac OS X 10.11
The only third-party plugin I installed is the markdown-composer, but that was a while ago installed. 
The above issue just showed up pretty recently (since last week or so).

Any help is much appreciated.

**Comment by bengotow** [comment]
Hi @bnsblue — thanks for posting this, I haven't been able to track this down yet. Could you try going to your inbox and searching for a thread which is obviously right there? If that doesn't yield any results either, I think it'll narrow this down quite a bit.

It'd also be really helpful if you could open the activity window (Cmd-Option-W) on a Mac, go to "requests" and try copy-pasting one of the search requests into your terminal and running it. Does it return any results there? (Note: N1 doesn't actually use cURL, we just format the requests that way for convenience!)

**Comment by BigOz** [comment]
I have this same problem off-and-on. I could be searching for something that is RIGHT there, and the item will appear in the search suggestions, so I click on it...then it takes me to an empty box saying "no items found" or something like that...even though I clicked on something that it had found in search-suggestions!

I've noticed that the problem only seems to come up when I'm offline...as soon as I have a connection, search seems to work as you'd expect.

**Comment by bnsblue** [comment]
Hi @bengotow -- Thanks for the reply and the suggestions.
I did both of the steps you provided:
1. I searched for the latest email I received, but I got empty results. I noticed in the activity window, the status of the request shows ETIMEDOUT.
2. I did curl, and got the results I want.

**Comment by bengotow** [comment]
Ahh that's really interesting. I'll talk with our backend team and see why that's timing out. Thanks for the update.

**Comment by kristianlam** [comment]
I tried the same and got this response:

{
    "type": "api_error",
    "message": "Server Error"
}

It timeout in the activity window in Nylas.

**Comment by bnsblue** [comment]
The issue is resolved after a reboot of my laptop.

  

I had tried completely closing the app and restarted it for several times, but
the issue was still there. However, now it seems to work after I rebooted the
laptop. I apologize for forgetting to try rebooting before posting the issue.
I'll keep watching it.

  

Thanks for the time and the help!

  

> On Mar 2 2016, at 6:49 pm, kristianlam &lt;notifications@github.com&gt;
wrote:  

>

> I tried the same and got this response:

>

> {  
"type": "api_error",  
"message": "Server Error"  
}

>

> It timeout in the activity window in Nylas.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1544#issuecomment-191498483).![](https://github.com/notifications/bea
con/ABcrvCFOP_DxcLgmfzE2j6f9te91Wx8aks5ppiIegaJpZM4Hn2oS.gif)

**Comment by kristianlam** [comment]
Rebooting doesn't work for me.

10.11.4 Beta (15E49a)
Version 0.4.10-4e3595b (0.4.10-4e3595b)

**Comment by matthewbassett** [comment]
I am experiencing the same issues 0.4.14. Running 10.11.3
However I will add one caveat that may help in running down the issue. If I am in inbox and run a search for an email I know is there but I have placed into one of my folders/labels, I get no results. However If I click on the inbox again, and run the exact same search, I get all the expected results. Very odd indeed!

**Comment by djevrek** [comment]
not working for me with any of tricks explained here. I'm on custom IMAP server (not gmail etc)

**Comment by olivierlacan** [comment]
I'm seeing this issue as well in `0.4.14-53cd69b`. I can search for XOXO Slack which returns two matches in Airmail (same accounts) and the search times out with `ETIMEDOUT` in N1.

**Comment by jstejada** [comment]
hi everyone, I am going to merge this into #750 to keep track of all the search problems in a single issue. Post any updates there!
