### ISSUE TITLE
Auto send while composing a reply. :(

### ISSUE THREAD

**Issue by TheFearlessHeart** [nylas/N1#1546]
Hello 
I have an issue with Nylas sending my message while I am composing a reply messages and as soon as I pause for a couple minutes it sends before I even finish my message. The client is amazing so far I only have this problem.

Version #0.4.10
OS: Windows 8.1

**Comment by jstejada** [comment]
hi @TheFearlessHeart, thanks for reporting this! I'm pretty sure that this is the same issue as #1175 **(Drafts suddenly appear as sent, but are not actually sent)**, so I'm merging it in. We are working on a fix! If the message was actually sent, feel free to reopen this issue and let us know
