### ISSUE TITLE
No Junk folders on any account

### ISSUE THREAD

**Issue by entreprenik2** [nylas/N1#1548]
I've got 4 accounts added (1 iCloud, 2 Google Apps, 1 Gmail) and all mail *seems* to be sync. However, there are no junk folders for any of the accounts in the sidebar even though I can see those folders and junk mail in them if I log in through the web interface.

OSX 10.10.5

N1 0.4.10-4e3595b

There's nothing special or custom about the Junk folders (i.e., stock) and other email clients show them just fine.

**Comment by bengotow** [comment]
Hi @entreprenik2 — do you see a unified "Spam" item in the sidebar? I think we may merge "Spam" and "Junk" folders into a unified "Spam".

**Comment by entreprenik2** [comment]
Nope, not even a unified one!

> On Mar 3 2016, at 8:50 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

>

> Hi [@entreprenik2](https://github.com/entreprenik2) — do you see a unified
"Spam" item in the sidebar? I think we may merge "Spam" and "Junk" folders
into a unified "Spam".

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1548#issuecomment-191932976).![](https://github.com/notifications/bea
con/AF61FvbfUc3wVHrAD3Ky30W6NQxmz5rbks5ppzuAgaJpZM4HoNB5.gif)

**Comment by entreprenik2** [comment]
@bengotow 
Clarification: When looking at individual inbox views, I see iCloud's Junk folder and Gmail's Spam folder. When looking at unified inbox, the spam/junk folder is missing. Just noticed this now since I was looking at unified the whole time.

**Comment by bengotow** [comment]
Ahh awesome! Yes we need to add a unified spam folder :-) Going to merge this into #1625
