### ISSUE TITLE
[Feature Request] Recognize Spam folder, provide button / keyboard shortcut for "Mark as Spam"

### ISSUE THREAD

**Issue by dombarnes** [nylas/N1#1549]
There appears to be no function via right-click menu, button or keyboard shortcut to flag a message as spam. This is pretty standard for most web-based email accounts. The only way currently appears to be to drag a message to the Spam folder in the sidebar.

**Comment by bengotow** [comment]
Thanks for reporting this @dombarnes — we aren't planning to build our own spam detection into N1, but we should definitely add better support for existing "Spam" folders (in Gmail, moving to the spam label is equivalent to saying "flag as spam" from the Gmail web UI.) We'll get this on the roadmap - stay tuned.

**Comment by jcuenod** [comment]
Is this related to #765?

**Comment by dombarnes** [comment]
Yes looks like it, but this also covers a interface button to do this.

**Comment by PwnArt1st** [comment]
+1

**Comment by jackiehluo** [comment]
We added this a while ago! 🎉

**Comment by ask** [comment]
What's the keyboard shortcut?

**Comment by paweleck** [comment]
I can't find any way to setup the keyboard shourtcut.
