### ISSUE TITLE
Fetching old email archives prevents receiving new email

### ISSUE THREAD

**Issue by askielboe** [nylas/N1#155]
I noticed that N1 does not seem to prioritize fetching the Inbox.

This is an issue when you start using the app with a large backlog of emails. After initiation a backlog sync (e.g. by selecting the 'All Mail' folder in a Gmail account) you will be unable to receive new email in the Inbox before All Mail has finished syncing - which can take hours for a large Gmail account.

Would it be possible to prioritize the fetching of folders such that N1 doesn't become unusable. Or maybe better: add parallel fetching?

**Comment by grinich** [comment]
The sync system should first fetch all of the threads in your inbox, and then sync All Mail, while also getting new mail. Is this not the experience you've had? This should really be an issue on https://github.com/nylas/sync-engine since N1 just consumes the updates from that.

**Comment by askielboe** [comment]
I can confirm that N1 did not receive any new email until after syncing of All Mail had finished. I will be happy to reopen the issue at https://github.com/nylas/sync-engine, and do more testing if needed.

**Comment by enoversum** [comment]
I can confirm partly for the Windows version; on one machine one account received new e-mails, while on the other the single account connected there gets quite a few e-mails from the starred and Trash queue, while inbox, the big archive and any other label remains empty, even on new mail. Inbox and labels/folders mentioned are all appearing empty. No sync indication as well, and network activity indicating no sync is taking place at all.

**Comment by rhoconlinux** [comment]
Yeap, same here. Ubuntu 14.04. 
I doesn't fetch new emails (I have 14gb in "all mail", so...)

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
