### ISSUE TITLE
Snooze, send later and read receipts don't work with locally hosted sync engine

### ISSUE THREAD

**Issue by mandarvaze** [nylas/N1#1550]
I'm using "local" server, and when snoozed, I see the following error

> Sorry, we were unable to save your snooze settings. 404: Not Found

- [ ] What operating system are you using?
OSX El Capitan

- [ ] What version of N1 are you using?
Version 0.4.10-4e3595b

**Comment by bengotow** [comment]
Hi @mandarvaze — thanks for reporting this. Snooze, send later and read receipts are powered by our cloud infrastructure and don't work if you're running the backend locally. We'll improve the messaging around this in the next update.

**Comment by marshallmcmullen** [comment]
That's really too bad. I recently switched to the local server option too and would love to continue using snooze. It would be nice if that would work with the local server rather than just the hosted server setup...

**Comment by mandarvaze** [comment]
FYI, I noticed that an empty folder "N1-Snoozed" got created on my IMAP server

**Comment by bengotow** [comment]
Hey folks! We've added a notice into the latest release so the app will notify you when you try to use these features that they require the hosted infrastructure.

Unfortunately snoozed mail is actually un-snoozed server-side, and "send later" mail is sent server-side, so your client doesn't need to be running for the actions to take place. We may open source these services in the future, but right now they're running on a separate part of our infrastructure and still under active development.

**Comment by jrk** [comment]
I would really love to see these open sourced in the future. The opaque incompatibility between every different client's snooze backend is a major frustration today. (I personally have messages snoozed with a Gmail script + labels—for the Gmail web UI/alternate clients—Outlook/iOS, and Nylas. I've also used Mailbox, Google's Inbox, Spark, and others.) Being able to push at least some more things, including custom tools and automation scripts, to a common snooze backend that was open source, extensible, and self-hostable would be extremely valuable.

Something to consider: it would be nice to see this as a general scheduled task feature in or atop the core Nylas API—both centralized and self-hosted.

**Comment by HammyHavoc** [comment]
I'd like to see these open-sourced too, bit off-putting to have commercial options in an open-source client by default.

**Comment by KevinMartin** [comment]
Being that the client is open-source, anyone else (including yourself) can create a plugin that does this.
