### ISSUE TITLE
Required IMAP STARTTLS not supported error when configuring IMAP

### ISSUE THREAD

**Issue by GijsGoudzwaard** [nylas/N1#1551]
I'm getting this error when i'm configuring my IMAP account 'Required IMAP STARTTLS not supported.'

I'm using OSX El Captian, i'm on version 0.4.10

**Comment by logandavis** [comment]
Hi Gijs,

That probably means that you had the "require SSL" checkbox ticked when you tried to log in to N1, but your mail server doesn't support encrypted connections (e.g. SSL or STARTTLS). Can you paste your mailserver setup information (host, port, and preferably encryption protocol if you can find it)?

**Comment by GijsGoudzwaard** [comment]
Hi @logandavis,

There is no 'require SSL' checkbox, does N1 support no SSL?
My host requires non-ssl for connection.
