### ISSUE TITLE
Email text is cutoff at the start of sentence.

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1552]
From the time I installed the latest version of N1, I see a lot of my messages are cut off at the start of the sentence as shown below. Observe the beginning of each sentence.

![screenshot from 2016-03-03 08-11-09](https://cloud.githubusercontent.com/assets/2344626/13495442/cae79752-e118-11e5-9f57-39d0523f287d.png)

- [x] Are there any related issues? 
Not sure if #376 is related. It was images and needs scaling. This is just plain text.

- [x] What operating system are you using?
Arch Linux

- [x] What version of N1 are you using?
0.4.10

- [x] Do you have any third-party plugins installed?
No.

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Observed in my Exchange account. Not sure if it is only specific to that or not.

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
   See above

**Comment by jackiehluo** [comment]
Going to close this issue for now because it's likely installation-specific—if you're still seeing it, send us an email at support@nylas.com!
