### ISSUE TITLE
open a email chain, reply, message not marked as read

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1555]
On Mac, latest version. Can't repro 100% but very frequent.

**Comment by emorikawa** [comment]
@jweinstein If you change Preferences -> When reading messages mark as read to "Instant" does this still occasionally happen?

I'll try and reproduce too. That's very strange.

**Comment by jweinstein** [comment]
So far so good, feels like user error. Will update you if I notice it again.

> On Mar 4 2016, at 6:51 am, Evan Morikawa &lt;notifications@github.com&gt;
wrote:  

>

> [@jweinstein](https://github.com/jweinstein) If you change Preferences -&gt;
When reading messages mark as read to "Instant" does this still occasionally
happen?

>

> I'll try and reproduce too. That's very strange.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1555#issuecomment-192308372).![](https://github.com/notifications/bea
con/AAhaGvRh_vIJcgtkqICMBRD_KhNZYJbFks5pqEbxgaJpZM4HouY7.gif)

**Comment by fonnesbeck** [comment]
I am getting this too. [Here is a screen capture of the behavior](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Recording-2016-03-09-16-08-44.mp4).

**Comment by giacaglia** [comment]
Having the same problem.

**Comment by emorikawa** [comment]
Hey, this looks related to an ongoing issue with marking as read we're addressing now. I'm consolidating this into: https://github.com/nylas/N1/issues/1298
