### ISSUE TITLE
Search Within Emails

### ISSUE THREAD

**Issue by scottnuma** [nylas/N1#1557]
Is there a way to implement a search function within email? Sometimes email chains get very long, and I'd like to skip to  a specific part that I know has a certain keyword. I'm thinking of search similar to browser's command-f function, rather than searching through all the emails in All Mail. Thanks.

**Comment by bengotow** [comment]
Hey @scottnuma — thanks for reporting this! We're actually adding this in the next release, and it landed on master yesterday: https://github.com/nylas/N1/commit/800f3a041bef69e14014827b2f5a337a50359347. Stay tuned!

**Comment by jstejada** [comment]
@scottnuma , this has landed in the latest release! enjoy!

**Comment by oldhickory30** [comment]
What i the status of the search issue? When I run a search, the correct email will show up as I type the words, however then when I click on the correct result, no results come up. This is a huge shortcoming!
