### ISSUE TITLE
N1 not loading until I switch to its virtual desktop

### ISSUE THREAD

**Issue by koterpillar** [nylas/N1#1560]
I have configured my window manager (XMonad) to automatically place N1 onto another virtual desktop, wherever it's launched from. Now, when I launch N1, it is correctly placed onto its virtual desktop, but the tray icon doesn't appear and I get no new email notifications unless I switch to that desktop. When I do, whether immediately or in an hour, N1 shows the "Loading" screen for a while, and only after that displays my mail, the tray icon and starts giving me notifications.

Steps to reproduce via Devil's Pie, should work on any X desktop environment:

* Install `devilspie`.
* Put this into `~/.devilspie/n1.ds`:
```
(if
(is (window_class) "Nylas N1")
(begin
(set_workspace 2)
(maximize)
)
)
```
* Run `devilspie`.
* Run N1.
* Wait for enough time for N1 to load normally.
* Switch to N1's workspace.

Expected results:

* Tray icon is shown before switching to N1's workspace.
* When switched to N1's workspace, it is already displaying mail.

Actual results:

* Tray icon is not shown unless switched to N1's workspace.
* When switched to N1's workspace, the loading screen is displayed.

**Comment by mbilker** [comment]
This means N1 does not complete its loading routine until the window is focused on. I wonder if this is an Electron bug.

**Comment by jackiehluo** [comment]
Closing because this issue isn't in the scope of this project!
