### ISSUE TITLE
Changing the sender address should replace existing signature

### ISSUE THREAD

**Issue by jamiewilson** [nylas/N1#1561]
When composing a new email, if you decide to send from a different address, the new sender's signature is added below the first sender's signature when it should replace the original one.

**Screencast of the issue:** http://quick.as/lzooc6b9p

- Mac OS X El Capitan 10.11.3
- Nylas Version 0.4.10-4e3595b (0.4.10-4e3595b)
- [Darkside Theme](https://github.com/jamiewilson/darkside), Send Later, and Quick Replies enabled

**Comment by jstejada** [comment]
wow thanks for reporting this @jamiewilson , this is no good. I haven't been able to reproduce it though. Could you send me the body of that message with your signature and with both of the signatures to juan at nylas? thanks!

**Comment by jstejada** [comment]
hey @jamiewilson thanks for sending me your signatures. I was able to track this down -- there was an error with the regex. This should be fixed in the next release!
