### ISSUE TITLE
an empty message in email chain

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1562]
Super odd. I've confirmed it's not a draft.

![image](https://cloud.githubusercontent.com/assets/547354/13515057/19fabeec-e163-11e5-997a-e9af1dde7da4.png)

**Comment by bengotow** [comment]
Wow that's an interesting one... Could you do me a favor and click the area between the Reply button and the timestamp "9:35PM", and choose `Copy Data to Clipboard` from that menu and paste it here? We can check out what's going on server-side.

**Comment by jweinstein** [comment]
DM'd that info :)

**Comment by bengotow** [comment]
Linked to platform https://phab.nylas.com/T6705

**Comment by jmfederico** [comment]
This is also happening to me.
I can confirm that when an empty meesage is show, an actual message exists but is not shown by Nylas.
If I click on "show original" form the menu next to the timestamp, I can see that Nylas has the message.

In my case they all correspond to failed deliveries notifications. But NOT all fail delivery messages are shown as blank.

Using OS X 10.11.4 with Nylas 0.4.19-d41e72c only using builtin plugins.

Debug info:

AccountID: 4t56hvu9628r7th4k0rcxs3e9
Message ID: 96n675mpg6a8z73e2rdjeoqdv
Message Metadata: []
Thread ID: c7ahhbhn0ttrqor35jg1jn1w
Thread Metadata: []

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4218

**Comment by jackiehluo** [comment]
Going to merge this into #2642, since it looks like they might be related!
