### ISSUE TITLE
Black backround and black font when opeing a drop down box

### ISSUE THREAD

**Issue by SICS-projects** [nylas/N1#1567]
- [ ] What operating system are you using?
Ubuntu 14.04

- [ ] What version of N1 are you using?
0.4.10-4e3595b

**Bug?**
- [ ] Do you have any third-party plugins installed?
Yes

- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.
It happens always

**Feature Request?**
- [ ] Does this feature exist in another mail client or tool you use?
No
![bug1](https://cloud.githubusercontent.com/assets/1690949/13536817/3228af6c-e242-11e5-9c26-4f6722f43a92.jpg)

**Comment by bengotow** [comment]
Closing as a dup of #1163 (gonna fix the name of that to make it easier to search for.) This seems to be a Linux issue. We just use Chromium's standard `<select>` inputs so I'm not sure how this is possible!
