### ISSUE TITLE
Composer: Link formatting is malformed

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1569]
Gmail screenshot. The first one is malformed, the second one is correctly formatted.

![image](https://cloud.githubusercontent.com/assets/27594/13542881/1ab2c588-e234-11e5-9d33-186a1e1f6909.png)

This seems to be an issue with how N1 does formatting with `<span>`s.

Original HTML for first link (decoded from base64)

```html
<div>I've written up this solution - let me know if it works. Instructions on how to use it are included.</div>
<div><span style="line-height: 1.4;"><br></span></div><div><span style="line-height: 
1.4;">https://sites.google.com/a/</span>redacted<span style="line-height: 
1.4;">.columbia.edu/</span>redacted<span style="line-height: 1.4;">/</span>mouselab-code-
snippets</div>
```

Compare to HTML from the second link:

```html
<div>https://redacted.columbia.edu/redacted/content.php<br>
```

- [x] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- [x] What operating system are you using? OS X El Capitan 10.11.3 (15D21)

- [x] What version of N1 are you using? Version 0.4.10-4e3595b (0.4.10-4e3595b)

**Bug?**
- [x] Do you have any third-party plugins installed? N1-Jiffy

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

**Comment by mbilker** [comment]
There should be a fix for this in the new version IIRC.

**Comment by markbao** [comment]
@bengotow @mbilker  I believe this is fixed in the new version; just tried composing a new message and using the same link that I used before, and it is displaying correctly in N1 as well as in Gmail web. Thanks!

**Comment by markbao** [comment]
Reopening since this is still an issue when using a link of form https://x.x.columbia.edu/x.

Gmail:

![image](https://cloud.githubusercontent.com/assets/27594/13857510/76d4a982-ec37-11e5-8a93-99cd525ef2d1.png)

N1:

![image](https://cloud.githubusercontent.com/assets/27594/13857570/a967fc00-ec37-11e5-952a-9c977491e0d0.png)

**Comment by mbilker** [comment]
Could you provide the HTML source like your original example?

**Comment by markbao** [comment]
Good call, thanks @mbilker.

```html
<div><span style="line-height: 1.4;">https://</span>redacted<span style="line-height: 1.4;">.</span>redacted<span style="line-height: 1.4;"><a href="http://.columbia.edu/redacted/redacted" target="_blank" title="http://.columbia.edu/redacted/redacted">.columbia.edu/redacted</a>?</span>q<span style="line-height: 1.4;">=1</span></div>
```

**Comment by bengotow** [comment]
Hey folks! We totally replaced the `autolinker` library which was auto-linkifying message bodies (For other reasons... it was parsing HTML with regexp...) and I've verified that the ` https://x.x.columbia.edu/x.
` style link now works. Enjoy!

**Comment by markbao** [comment]
Thank you!
