### ISSUE TITLE
[feature request] merged inbox of multiple/all accounts

### ISSUE THREAD

**Issue by ViliamKopecky** [nylas/N1#157]
Having multiple accounts means switching among their inboxes all the time. Would be nice to have a view, where messages from all (or better if you could select them to groups) inboxes were shown in one stream.

**Comment by grinich** [comment]
Please vote this feature up here:

**Comment by stereoplegic** [comment]
This is a critical feature for me. Without it, I'm going back to Thunderbird (delays and all).

**Comment by markogresak** [comment]
:+1: on this. @grinich vote where?

**Comment by Igor1201** [comment]
Yeah, I need this too, where can we vote?

**Comment by clemsos** [comment]
status ? https://trello.com/c/5pIfWaN3/3-unified-inbox-view
