### ISSUE TITLE
File Notification 

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#1570]
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [ ] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- [x] What operating system are you using?
MAC 10.11.3
- [x] What version of N1 are you using?
0.4.10

**Bug?**
- [ ] Do you have any third-party plugins installed?
Yes

- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.
No

**Feature Request?**
- [x] Does this feature exist in another mail client or tool you use?

**Comment by oldhickory30** [comment]
This is the way my file tree appears, inbox sent? along with numbers next to it that don't make sense.
Should it not be sent, junk, in box, archive? It does this with all my accounts? Am I missing something?![error](https://cloud.githubusercontent.com/assets/16170272/13544073/de8dfc76-e22e-11e5-85a4-ba5840a0eb37.jpg)

**Comment by mbilker** [comment]
The `INBOX.` prefix is the IMAP folder name. N1 uses that to display the name because the name can vary by localization and the email provider. The number next to them is the unread messages in those folders.

To disable the unread counter for every folder, but display the counter for the inbox folder for all accounts, go to `Preferences -> General -> Workspace -> Show unread counts for all folders / labels` and turn that option off. Then, you should see only the unread counters for the inbox folder.

**Comment by oldhickory30** [comment]
Perfect...Thanks!  
![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/377b3db55b90480e9c97
3614a9b9dbec)

> On Mar 4 2016, at 8:45 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> The INBOX. prefix is the IMAP folder name. N1 uses that to display the name
because the name can vary by localization and the email provider. The number
next to them is the unread messages in those folders.

>

> To disable the unread counter for every folder, but display the counter for
the inbox folder for all accounts, go to Preferences -&gt; General -&gt;
Workspace -&gt; Show unread counts for all folders / labels and turn that
option off. Then, you should see only the unread counters for the inbox
folder.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1570#issuecomment-192564797).![](https://github.com/notifications/bea
con/APa9IId3Pj6m5xd_6TrTLOWP_vYEnV5aks5pqPxkgaJpZM4Hp2Nj.gif)

**Comment by mbilker** [comment]
Did that fix your issue? If so, could you close the issue?
