### ISSUE TITLE
Wrong contact name displayed when writing a message

### ISSUE THREAD

**Issue by seanmangar** [nylas/N1#1571]
I'm seeing automatic contact names being assigned in Nylas and cannot change them. This one is clearly wrong and seems to be based on an email I received.
<img width="637" alt="screen shot 2016-03-05 at 12 35 43" src="https://cloud.githubusercontent.com/assets/6080053/13546715/d958ac0a-e2cf-11e5-8fc0-04cba821f4ad.png">

- [ ] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)
No related issues

- [ ] What operating system are you using?
Mac OS X 10.11.3

- [ ] What version of N1 are you using?
Version 0.4.10-4e3595b 

**Bug?**
- [ ] Do you have any third-party plugins installed?
No
- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure

- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.
No

**Feature Request?**
- [ ] Does this feature exist in another mail client or tool you use?
No

**Comment by jkmaxwell** [comment]
+1, causing a lot of problems for my team as an address is autocorrecting to someone no longer with the company (who uses support@ourdomain.com) whenever I cc. Can someone at Nylas please suggest an alternate manual fix we can employ in the meantime?

**Comment by jackiehluo** [comment]
Merging into #1081!
