### ISSUE TITLE
github messages looks suspicious?

### ISSUE THREAD

**Issue by simonbcn** [nylas/N1#1572]
Arch Linux 64 bits
N1 0.4.10-4e3595b
Gmail account

N1 classifies  the messages from github like suspicious.
![seleccion_002](https://cloud.githubusercontent.com/assets/428231/13547052/c9f4b118-e2c1-11e5-972f-ddcd57215ae2.png)

**Comment by jackiehluo** [comment]
Hey, @simonbcn! I'm going to merge this issue into #1321, since that's about the logic we use in our phishing detection plugin that we're planning to rework at some point.
