### ISSUE TITLE
Gmail Send mail as...

### ISSUE THREAD

**Issue by sbwp** [nylas/N1#1573]
I use Gmail to check on all my POP3 accounts with the option to reply from the same address the message was sent to. I see that this is not yet possible in this app.
When I compose the default e-mail address is my main gmail address but in gmail I use a different one.

Thank you.

**Comment by mbilker** [comment]
This is possible if you add an alias to N1 in `Preferences -> Accounts` and select the account you that has the Gmail sending and click the + under Aliases.

**Comment by sbwp** [comment]
Thank you!

I think this should be extended to make some rules when to use an alias.
If the mail is sent to username1@domain-name.com use that alias to reply.

**Comment by jstejada** [comment]
thanks for the suggestion @sbwp, that is part of #800, So i'm going to close this issue for now.
