### ISSUE TITLE
Screenshot mode doesn't obscure full email message

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1577]
Running 0.4.10-4e3595b

![screen shot 2016-03-05 at 1 11 53 pm](https://cloud.githubusercontent.com/assets/92417/13550510/3a1bbc36-e2d4-11e5-8993-211dfff5f618.png)

**Comment by bengotow** [comment]
This is deliberate for the moment because folks often want to report an issue with a particular message while hiding the rest of their mailbox. Will leave for now.
