### ISSUE TITLE
Deleted messages are staying in inbox with a Trash label.

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1578]
When I delete messages on Gmail's mobile app or web interface and come back to n1, few of them stay back in the inbox with trash label showing. When I open the message, N1 will show two labels on them, inbox and trash. In few seconds, inbox label will disappear automagically and when I go back to inbox, that message is moved to trash. I have screen capped this with 3 messages. Messages 1 and 3 will show this bug clearly. I think Message 2 is more up the alley of #1135. 

I will have to **DM the screen capture**. Not interested to post it on this public forum as it contains emails. Please let me know who should I send it to.

- [x] Are there any related issues? 
Looks similar to #1135. But not quite the same.

- [x] What operating system are you using?
Arch Linux

- [x] What version of N1 are you using?
0.4.10

- [x] Do you have any third-party plugins installed?
No

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail
- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
Happens frequently enough in a day. Not repro every single time.

**Comment by bengotow** [comment]
Hey! Thanks for filing this—we've actually fixed this on master and it'll be rolled out in the next release. Now messages in the thread that you've previously marked "spam" or "trash" will be hidden by default. Stay tuned!

**Comment by bashok001** [comment]
Hey @bengotow, I am pretty sure you're talking about #1135 fix. Are you? The problem as I understand there is that messages marked as Trash are shown in Inbox if there is another message in the thread. Here the bug I am facing is that the message with no thread continuation (sometimes) marked as Trash remains in Inbox as long as I don't open it. I can send you screen cap and see if that helps you understand my point.

**Comment by jstejada** [comment]
hey @bashok001 this should be fixed in the latest release, feel free to reopen if you still have trouble with this.
