### ISSUE TITLE
Feature Request: Manage themes in a separate settings view

### ISSUE THREAD

**Issue by htaidirt** [nylas/N1#1580]
Hi all,

This is a feature request: Be able to manage the themes (search them, install, apply and uninstall) in a separate settings view, instead of a dropdown list in the settings General view.

This is especially useful when we want to delete a theme after testing. Actually, we have to go through the console and delete folders in the ~/.nylas directory.

As an example, the Atom editor app (also open sourced) allows this.

Hope it will help.

**Comment by jackiehluo** [comment]
Hey, @htaidirt! We just landed a visual theme picker that launches from the menu on master, and we're working on making it much easier to uninstall themes (i.e., like it is for plugins) and find new themes and packages.

**Comment by jackiehluo** [comment]
For the other part of your request, I'm going to merge this issue into #770!
