### ISSUE TITLE
Sent mail does not appear in "Sent Mail"

### ISSUE THREAD

**Issue by arpitchauhan** [nylas/N1#1581]
I've seen this happen with N1 0.4.10 on Windows 10 1511 -- if I reply to an e-mail chain, it does not appear in the Sent Mail section.

However, I am able to locate it if I visit the thread by searching my inbox.

I have two Google Apps accounts configured -- also, the sent mail appear in a perfectly fine manner in the Sent Mail section of the web app (Gmail).

**Comment by markbao** [comment]
+1. When I compare my Sent Mail view in Gmail, they are completely different than my Sent Mail view in N1.

**Comment by jstejada** [comment]
is there any chance the messages are being moved to the Drafts section like in this issue: #869?

**Comment by arpit10i** [comment]
No. However, what I noticed that after a day or two, the mails appeared in N1's sent mail (they had appeared in Gmail's sent mail instantly).

**Comment by jstejada** [comment]
@markbao  @arpitchauhan also, is it possible that the sorting order of the threads inside "Sent Mail" is different between N1 and Gmail?

**Comment by arpitchauhan** [comment]
@jstejada Yes, I can confirm that.

**Comment by markbao** [comment]
@jstejada I can also confirm that. From a cursory check, it seems that the sorting order of the threads in "Sent Mail" is based on when the last message in the thread was receipved, not the time that I sent the mail.

**Comment by jstejada** [comment]
great thanks guys. So your sent mail /is/ in N1, just not in the correct order, right? We'll ship a fix to order sent mail correctly soon cc @bengotow

**Comment by jstejada** [comment]
merging into #890
