### ISSUE TITLE
White links when switching to dark theme & back to light.

### ISSUE THREAD

**Issue by lukealford** [nylas/N1#1583]
- [ ] What operating system are you using? - Windows 10

- [ ] What version of N1 are you using? - 0.4.10

As title says, when you switch from the dark theme back to light I get a bug where my links are white and no one can see them without highlighting the text. 

There should be a option to set your Anchor colour in preferences as even with dark theme I was getting the problem as well, since it sends a white link my recipient get's a white link and can't see it because the recipients email client doesn't have a dark theme.

**Comment by bengotow** [comment]
Hey! I haven't been able to reproduce this today, and it looks like there have been a bunch of improvements to the theme picker since March. Can you try again in the latest release? I'll re-open if the issue persists.
