### ISSUE TITLE
Replies appear like they sent twice, one reply being incomplete

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1585]
This has been a persistent issue. I draft a reply, then send it. Then I look at the mail in another view (like *All Mail*) and it looks like it sent twice, one being incomplete. However, checking Gmail web app, it was only sent once. This happens constantly, and sometimes even drafts pile up. Not sure if this is due to interaction with another mail app that has access to my account or not, so curious to see if others are having the same issue.

<img width="836" alt="screenshot_3_7_16__1_12_am" src="https://cloud.githubusercontent.com/assets/27594/13562092/386b20fa-e402-11e5-8ca4-04a4ecd351f6.png">

- [x] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- [x] What operating system are you using? OS X El Capitan 10.11.3 (15D21)

- [x] What version of N1 are you using? Version 0.4.10-4e3595b (0.4.10-4e3595b)

**Bug?**
- [x] Do you have any third-party plugins installed? Jiffy

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? Not sure

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?

**Comment by jstejada** [comment]
hi @markbao, this seems to be the same issue as #1175, so I'm going to merge it in. Also possibly related #933
