### ISSUE TITLE
Unified inbox temporarily loses accounts

### ISSUE THREAD

**Issue by jackiehluo** [nylas/N1#1587]
N1 version 0.4.10, running on Mac OSX El Capitan (10.11.3). Jiffy and Weather installed.

Experiencing a bug where N1 will temporarily lose some of my accounts in the unified inbox view. They no longer appear in the account sidebar, and the emails in those accounts also disappear from the inbox. However, I can still switch to the accounts with the dropdown for "All Accounts," and when I go to the accounts tab in the preferences, all of the accounts are still present.

<img width="323" alt="screen shot 2016-03-06 at 3 46 53 pm" src="https://cloud.githubusercontent.com/assets/8452682/13562366/bbdebe26-e3ec-11e5-810a-66856b79b7f2.png">

**Comment by alordmg** [comment]
I have the same problem on my laptop. I need to go in Preferences > Accounts tab and then when I go back to Nylas all my accounts are visible.

**Comment by taniadaniela** [comment]
also having the same issue.

**Comment by alordmg** [comment]
I'm now on version Version 0.4.32-1de17e7 (0.4.32-1de17e7) and I still have the same problem everyday .

**Comment by bboymatt** [comment]
I have the same issue on Windows 10. Nylas v4.4.5.

**Comment by jackiehluo** [comment]
Another incidence from @sdewith!

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/6434

**Comment by emorikawa** [comment]
Fixed with 0.4.400 release
