### ISSUE TITLE
Select All (Ctrl +A)  #Feature Request

### ISSUE THREAD

**Issue by Senasum** [nylas/N1#1589]
**Feature Request?**
- [x] Does this feature exist in another mail client or tool you use? Yes it does

In the Mail pane I cannot use Ctrl+A to select all mails. I wanted to delete all the mails from Deleted Items folder and tried this but it didn't work. I hat to use Shift+Select to select all the mails. 

If we can enable Ctrl+A to select all visible mails it will be more user friendly.

Regards
Senasum.

**Comment by g105b** [comment]
Just came here to request the same thing. Ctrl+A highlights the mail address of the currently selected email, not the expected behaviour of selecting all emails.

**Comment by emorikawa** [comment]
Hey, yes, unfortunately this is a known issue we're working on right now. I'm merging this issue into #886. All of the select-all issues are related to an ongoing fix to better address keymaps and menus. We'll be updating #886 with the status of that fix.

**Comment by Senasum** [comment]
Thanks, we look forward to use a more developed version soon.

**Comment by Razva** [comment]
Any news? If ctrl+a / cmd+a is hard to implement at least a "select all button"?
