### ISSUE TITLE
**Feature Request?** change the location of Send button for forwarded messages

### ISSUE THREAD

**Issue by Senasum** [nylas/N1#1590]
User Friendliness can be improved by putting send button for forwarded messages near the place where user write recipient address. 
Because in a forwarded message user does not need to scroll to the bottom to find the send button since he does not edit anything in the already existing message. 
![image](https://cloud.githubusercontent.com/assets/15521008/13565261/e1bad3c0-e403-11e5-88a9-b083a6425881.png)

place where it needed to be added. 

![image](https://cloud.githubusercontent.com/assets/15521008/13565364/81eaa91a-e404-11e5-8966-9928676d87d2.png)

**Comment by emorikawa** [comment]
@Senasum There is definitely room to design a better send button. The Forwarding case is a particularly good example of that. I'm merging all of these send button fix issues into #1083. You can track the status of this there. For now I'm closing this issue in favor of #1083.
