### ISSUE TITLE
No spam folder for gmail account

### ISSUE THREAD

**Issue by carlotrimarchi** [nylas/N1#1591]
Hello,
I'm on a Mac and I'm using Nylas Version 0.4.10-4e3595b (0.4.10-4e3595b). 

I added two gmail accounts and I don't see any spam folder for neither of them. Is there a way to add it?

**Comment by emorikawa** [comment]
@carlotrimarchi This is likely an issue syncing your mail. Could you email support@nylas.com with the email address you're seeing this with (as well as any mail settings if it's IMAP), so we can better diagnose what might be going on with your specific account.

I'm going to close this GitHub issue in favor of individually diagnosing your account.

**Comment by carlotrimarchi** [comment]
I actually discovered later that on the left sidebar I can switch from All accounts to all the different single accounts. When doing this, I can see the spam folder for that account.

The action is different from clicking on the different mailboxes listed under the All account section. This is confusing, to say the least, also because the option to show only one account is not very prominent in the interface.

**Comment by davidpmccormick** [comment]
I'm also seeing this – when I had only added one GMail account, the spam folder showed up for that account, but when I added a second, neither spam folders appeared (until, as @carlotrimarchi pointed out I selected an individual account from the account switcher select box).

**Comment by PwnArt1st** [comment]
+1 same here
