### ISSUE TITLE
Feature Request: Gmail "Undo Send"

### ISSUE THREAD

**Issue by jcguinea** [nylas/N1#1593]
It will be great to add a plugin to undo when we send emails like it is on GMAIL
<img width="948" alt="captura de pantalla 2016-03-07 a las 11 30 18 a m" src="https://cloud.githubusercontent.com/assets/12300966/13577446/1af7e98a-e458-11e5-9642-d81c099d0032.png">

**Comment by Kevin-Ferret** [comment]
Same request here, I use that quite often & found it missing in N1 for now :s

**Comment by hallamoore** [comment]
Another request for this: https://nylas.zendesk.com/agent/tickets/4167

**Comment by jondcoleman** [comment]
This is a must have for me.

**Comment by grinich** [comment]
This has actually been added in N1!
