### ISSUE TITLE
Error: Updating the Exchange endpoint is not permitted

### ISSUE THREAD

**Issue by AnjoMan** [nylas/N1#1595]
Conditions for bug:

Windows: changed the server / username / password for exchange account (our office switched to a new server) and now N1 refuses the account saying that changing the endpoint is not permitted.

Ubuntu: trying to set up the same exchange account on a different Ubuntu user, get the same error. It seems.

Things I attempted to do to fix:

Reinstall N1 -> same error.

Windows: Delete Nylas folders under ....\AppData and reinstall Nylas -> same error.

**Comment by AnjoMan** [comment]
Here is the error at sign-in. ![image](https://cloud.githubusercontent.com/assets/2414360/13581604/aa27f254-e475-11e5-98ea-5483a5a94d87.png)

**Comment by Bergg** [comment]
I got this error when I used a working alias in the Email field, instead of my server email, when setting up the exchange account on N1.

**Comment by fonnesbeck** [comment]
I get the same problem on OS X 10.11.3.

**Comment by jackiehluo** [comment]
Hey! Sorry for the super late reply here—we don't allow users to change their endpoints for security reasons. If you want to do that, you have to contact Nylas support (per the error message).
