### ISSUE TITLE
Feature Request: Hide labels in list pane

### ISSUE THREAD

**Issue by denyk** [nylas/N1#1596]
From a design perspective, I think labels should default to a neutral color and let users select the color per label/label group. The auto-generated, random colors serve to distinguish the labels but I dont think it's needed—label text itself is enough.

I would like the ability to hide all labels from the middle pane (or make them more subtle ala gmail light gray).

**Comment by bengotow** [comment]
Hi @denyk — thanks for filing this! This is something we'd like to see implemented as a theme. You can create CSS styles for N1 that would override the default appearance of labels, or hide them in the middle pane entirely.

(Implementation note: our labels get their randomly-assigned colors from inline styles, but your stylesheet can still override the inline values using the CSS `!important` tag. A bit nasty but effective.)

**Comment by kaifeichen** [comment]
Hi @bengotow, can you point me to the variable to override to **hide labels in the middle pane entirely**? I'm looking at all ui variables here: https://github.com/nylas/N1-theme-starter/blob/master/styles/ui-variables.less, but cannot find the one to do it.
