### ISSUE TITLE
Sent Mail doesn't match gmail's Sent Mail

### ISSUE THREAD

**Issue by joelabair** [nylas/N1#1598]
I'm noticing an item in my "Sent Mail" folder that does not appear in my Sent Mail folder with other clients (gmail web app, and thunderbird).  I can however locate the item in my Spam folder in other clients.  Message src attached.

- [x] What operating system are you using?
Fedora Linux

- [x] What version of N1 are you using?
4.10

**Bug?**
- [x] Do you have any third-party plugins installed?
no

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
gmail

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
unsure

[Spam_10511.txt](https://github.com/nylas/N1/files/162262/Spam_10511.txt)

**Comment by jstejada** [comment]
hey @joelabair thanks for reporting this. I'm going to merge into duplciate #1581. Thanks!
