### ISSUE TITLE
Deprecation Warnings Lack Origin Plugin Information

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#1599]
N1 has had many API changes over the past few versions and deprecation helps plugin developer's know if they need to upgrade their plugin to the new API. Unfortunately, the deprecation warnings only state what needs to be upgraded, but not what class in the source or what plugin.

I noticed this in N1 related to `ComposerExtension`.
```
Deprecation warning! ComposerExtension.onFocus is deprecated and will be removed soon. Use ComposerExtension.onFocus(args = {editor, ...}) instead.
Deprecation warning! ComposerExtension.onBlur is deprecated and will be removed soon. Use ComposerExtension.onBlur(args = {editor, ...}) instead.
```

**Comment by jstejada** [comment]
thanks for bringing this up @mbilker, I added an update to display the location in the code where the deprecation warning was caused
