### ISSUE TITLE
Spell Check not working in Subject Line

### ISSUE THREAD

**Issue by GEverding** [nylas/N1#1600]
Issue: I'm not able to select spell check options for underlined words in the subject line. 
Version 0.4.10-4e3595b on Mac
Theme: Darkside (not sure if this matters

Steps to Repeat:
1. Compose new email
2. Enter subject with wrong spelling
3. Right click on highlighted word. Only options are cut copy paste.

Let me know if you need more information.

**Comment by mbilker** [comment]
I do not believe that spellcheck corrections are enabled for the subject line, which would explain this annoying issue.

**Comment by GEverding** [comment]
Is there a reason why?

Garrett




On Mon, Mar 7, 2016 at 8:49 PM -0800, "Matt Bilker" <notifications@github.com> wrote:












I do not believe that spellcheck corrections are enabled for the subject line, which would explain this annoying issue.

**Comment by bengotow** [comment]
There's a patch in review that will fix this - stay tuned!

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
