### ISSUE TITLE
Accounts missing after system reboot

### ISSUE THREAD

**Issue by mmatthews** [nylas/N1#1601]
**Operating System** Ubuntu 14.04 / 4.2.0-30-generic
**N1 Version** 0.4.10-4e3595b

**Issue**
The accounts that were set up previously were Gmail and Namecheap.
After rebooting my computer, the two mail accounts I had set up were missing. I had ran "Run N1 Specs" from the *Developer* menu shortly before rebooting. Where do my credentials get stored, and how can I "resync" my N1 install to get my accounts back?
Thanks!

**Comment by brasilikum** [comment]
might be related to #1348

**Comment by bengotow** [comment]
Hey folks - I think this is actually due to #1133. I'm going to see if we can fix this right now and merge this in.

**Comment by mmatthews** [comment]
Like clockwork - thanks @bengotow !
