### ISSUE TITLE
Messages labeled Bin should be available only in the Bin?

### ISSUE THREAD

**Issue by Kerruba** [nylas/N1#1603]
Importing email from Gmail, lot of them are labeled "Bin". But they're not in the "Bin folder" as main folder, but spread all over the original folders.
Shouldn't them be just in the Bin folder, as Gmail does?

**Comment by bengotow** [comment]
Hi @Kerruba — thanks for filing this! I believe this is a dup of #349  and will be fixed in the next release. Stay tuned!

**Comment by jstejada** [comment]
hey @Kerruba  this should be fixed in the latest release, feel free to reopen if you still have trouble with this.
