### ISSUE TITLE
Write and send a message leave it as "Draft" on Gmail

### ISSUE THREAD

**Issue by Kerruba** [nylas/N1#1604]
I've the default send method as "Send", but when I'm sending a message from Nylas through my Gmail account, on the server I find the sent email and also a draft

**Comment by koichirose** [comment]
Same issue here, Version 0.4.10-4e3595b
If I write/reply to an email quickly enough I can prevent it. Otherwise the draft will be saved (forever, apparently) even though the message is sent.

**Comment by bengotow** [comment]
Hey folks—thanks for filing this! We've identified a race condition that could cause this to happen if you had the link tracking or open tracking plugins turned on and it'll be fixed in the next release. Stay tuned!

**Comment by jstejada** [comment]
this has been fixed in the latest release. If you are still experiencing this please feel free to reopen. Thanks!
