### ISSUE TITLE
Negative unread counter

### ISSUE THREAD

**Issue by alordmg** [nylas/N1#1605]
Hello,

I noticed this morning when I started my computer that my unread count is negative. That's even better than Inbox Zero but I though maybe that's a bug.

I currently have 0 unread message in my inbox, the it's still -3.

![capture d ecran 2016-03-08 a 10 22 12](https://cloud.githubusercontent.com/assets/11218493/13606061/6b55b2ac-e518-11e5-8c21-8b702eeb5648.png)

Menu bar:

![capture d ecran 2016-03-08 a 10 29 27](https://cloud.githubusercontent.com/assets/11218493/13606113/aa9af292-e518-11e5-96ce-5b033ab75f68.png)

**Comment by jackiehluo** [comment]
Thanks for opening the issue, @alordmg! I'm going to merge it into #759.
