### ISSUE TITLE
Dark theme welcome screen has black text on dark background

### ISSUE THREAD

**Issue by askielboe** [nylas/N1#1606]
Steps to reproduce:

1. Activate dark theme
1. Remove all accounts
1. (N1 will now restart and show the onboarding screens with black text on dark background)

![screen shot 2016-03-08 at 16 42 20](https://cloud.githubusercontent.com/assets/52106/13606718/642f85c2-e54d-11e5-8a7b-75399ecd0833.png)

Platform: OS X 10.11.3
Version: 0.4.10-4e3595b

**Comment by jackiehluo** [comment]
Hey, @askielboe! We've fixed this problem on master, and I'm going to merge the issue into #1406.
