### ISSUE TITLE
Spell Check Not Appearing on Down-Scaled UI

### ISSUE THREAD

**Issue by MacroMackie** [nylas/N1#1607]
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [ ] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)
**I could not find any issues relating UI Scaling and Spell Check.**

- [x] What operating system are you using? 
**OSX El Capitan - 10.11.3 (15D21)**

- [x] What version of N1 are you using? 
**Latest - 0.4.10-4e3595b**

**Bug?**
- [ ] Do you have any third-party plugins installed? 
**No**

- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? 
**I don't believe so.**

- [ ] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.
**See Below.**

The issue seems to be related to the scaling size. I prefer to use 80% scaling, but when I write emails in 80% scaling mode, there is no "red line" underneath misspelled words.

<img width="753" alt="100 scaling" src="https://cloud.githubusercontent.com/assets/6835779/13610483/e768748e-e52b-11e5-979b-8e0988cd3f48.png">

<img width="802" alt="80 scaling" src="https://cloud.githubusercontent.com/assets/6835779/13610489/ed2572b4-e52b-11e5-8d4d-51f978cacac8.png">

There was no issues at 100%, 120%, or 140% scaling.
I could reproduce the issue consistently at both 80% and 60% scaling.

**Comment by bengotow** [comment]
Hey @MacroMackie! We've decided to remove the `zoom` option from N1's preferences UI and make it strictly a configuration option. It causes small visual issues we unfortunately don't have the bandwidth to test for (like this one!)

In the next release, we'll be making the zoom config option accept any integer value (default: 1), so that you can get it just right, and documenting it here: https://github.com/nylas/N1/blob/master/CONFIGURATION.md#other-config-options

Hope that helps! We'll try to fix this specific issue in the future by changing the way we render the underline in the next release as well, since this is a pretty major one.

**Comment by jakedeg** [comment]
@bengotow Are you saying that by making zoom level a config integer value, it should fix this spelling underline issue? Or it will just make it more difficult for the average user to zoom, so less people are likely to experience it?

**Comment by bengotow** [comment]
Yep—for now, we've decided to make custom zoom level an "advanced config setting". We can fix the spellcheck underline issue specifically, but zooming out causes other little problems in the UI—attachments lose their 1px border, sometimes you can't see the draggable dividers between the panels, etc. It's definitely still useful, but more of a hacker-level feature than something we can advertise as a core option.

**Comment by jakedeg** [comment]
Got it. Thanks for the clarification. I was definitely getting used to the 80% version, but maybe I'll try 100% and see if I can get used to that too. Where I miss the down-scaling the most is the labels list where I have to to much more scrolling to see my labels. But maybe the ability to drag labels around to create a custom display order would help with this. I'll submit that as another Feature Request.

And if you are able to fix the spelling underline as a 1-off, that would be great too and might allow some of us to stick wth 80% scaling, and live with some of the other less impactful UI glitches. 

Thanks! And thanks for your responsiveness. It is so exciting to see such active open-source development happening on a such a promising mail client. I have been trying out others for a while and just have not been satisfied.
