### ISSUE TITLE
Request: Mail Merge

### ISSUE THREAD

**Issue by michael-montano** [nylas/N1#1608]
Related issues: none.
My system: Macbook Pro 15" running OS X 10.11.3 El Capitan.
My Nylas: Version 0.4.10-4e3595b

Feature Request: Mail Merge

1. I want to be able to run a mail merge within N1 in order to personalize batch emails. I imagine this happening by running a variable contained within an outgoing email, such as {!FirstName}, against a list of names with matched email addresses (and potentially other details run against variables within the email).
2. Ideally, a user would have two options for connecting their mail merge name list. Option 1: they could import a CSV file of names and email addresses. Option 2: they could invoke the name of a Group within OS X's built-in Contacts app.

I would be willing to work with others as the designer on this project.

**Comment by mbilker** [comment]
This is possible with the current API to send the messages to each outgoing email address.

The composer would need to be hooked to prevent the message from actually sending. My guess is to set the outgoing email address to something that can be tracked using a `ComposerExtension`.

**Comment by DavidChouinard** [comment]
@michael-montano, I'm curious if you have a design perspective of [this mail merge implementation demo](http://static.davidchouinard.com/mail-merge-is-a-%F0%9F%9A%86-wreck/). The integration with OS X Contacts is an interesting idea.

**Comment by michael-montano** [comment]
@DavidChouinard – Great work!

- Even though it depends on the availability of a reasonably large display, your inline approach with drag-and-drop column headers is a smart one. It's certainly an improvement over Word and Yesware's wizards, though I'd retain the option to use braces with typed header names for fast-moving users. (The brace-enclosed header names could convert to bubble references when the closing brace is applied, which would in itself create a check against errors.)
- The ability to drag and drop a CSV is a nice touch. You kind of flash past it in the video, but I love the speed of that option (though one should also have the ability to open a list file directly within the mail merge feature). Even better might be to link N1 to a repository (or repositories) of lists so they are readily accessible via a drop down within the mail merge feature. (One such repository could be Contacts and its Groups.)
- Down the road: Maybe the one good thing about Word's approach is that users can see all the merged docs simultaneously after running the merge. In your implementation, as with Yesware's, users have to take a bit of a mental leap of faith because they can't see all of their merged emails simultaneously, though they can click forward through them. I'd make a Wordl-style simultaneous view an option, too.

What's next?

**Comment by michael-montano** [comment]
@mbilker – Matt—I'm not an engineer, and I don't fully follow your comment, but it looks like @DavidChouinard and I have some clarity about where to go with this if you're interested in working together.

**Comment by amit777** [comment]
The video demonstrates the best UI/Ux of a mail merge tool. I'm brand new to N1. How feasible is it to create a plugin like this?

**Comment by DavidChouinard** [comment]
@amit777 The UI part seems reasonable. It'd be a composer extension and the drawer could go in the `Sheet:Main:Footer` region.

We'd ideally want batch messages to be queued and sent out server-side, but that would require integration from Nylas. Client-side, seems like it's possible for a plugin to programmatically generate many drafts and have them queued up to be sent. (queuing `SendDraftTask`s; [this test](https://github.com/nylas/N1/blob/master/spec/tasks/send-draft-task-spec.es6) shows how it's done)

**Comment by bengotow** [comment]
Hey folks! Thanks for all the input—this has been shipped in `0.4.32`. We went with a UI that was very similar to @DavidChouinard's and will continue to work on mail merge as a core feature of N1. Cheers!

**Comment by DavidChouinard** [comment]
Nice!

**Comment by matthewdewstowe** [comment]
Hello.  How do I get mailmerge plugin runing on Mac?

**Comment by mbilker** [comment]
@matthewdewstowe Built in to official release.

@bengotow Is this a Pro only feature?

**Comment by matthewdewstowe** [comment]
I cannot seem to drag a variable, like {{firstname}} into subject line.  This is good for personalisation, but also avoids the problems with current threading.  I send the same mail to lots of people and it is all threaded together despite them all being different mails and having different responses.  @mbilker If you can help apprecaited!

**Comment by mbilker** [comment]
Unfortunately, I don't use the Pro version of N1. I stick to a modified
open source version.

**Comment by hadifarnoud** [comment]
this feature existed in N1 but not available in Nylas Mail. I do have Pro subscription btw
