### ISSUE TITLE
Overview Panel for Email Opens – Feature Request

### ISSUE THREAD

**Issue by michael-montano** [nylas/N1#1609]
Related issues: none.
My system: Macbook Pro 15" running OS X 10.11.3 El Capitan.
My Nylas: Version 0.4.10-4e3595b

**Feature Request: Overview Panel for Email Opens**

*Current Status*
N1 allows users to track when a recipient opens a sender's email. Currently, you have to open individual emails to know their history.

*Proposal*
Instead, I propose that N1 have an overview panel that shows interaction activity across all tracked emails simultaneously. In effect, this would be a mini-notification center for email tracking.

*Example*
The Yesware extension's horizontal top bar is one example of how to implement such a system. 

*Design Hypothesis*
However, my intuition is that in the N1 case, a tracking pane would be better placed within the left hand column of N1, atop the folders and tags. This would mean bifurcating the left column so that only half would be available for folders and tags, but I could imagine the new pane being adjustable in height, entirely collapsible, or removable altogether via the plugins page or View menu.

*Offer*
I am happy to work on the design elements of this proposal.

**Comment by bengotow** [comment]
@jackiehluo is on it!

**Comment by bengotow** [comment]
Hey! Thanks for filing this and offering to help. We've added a "notification center" style view to the top left corner of N1 in `0.4.32`. Right now, it's a simple chronological view of all your open / link tracking events, but we plan to add more features (graphs, etc.) in the future. Cheers!

**Comment by michael-montano** [comment]
I saw! Totally great that y'all moved to quickly on this. I will remain a
paying user when the free version ends for existing users in a year.

On May 3 2016, at 10:38 am, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey! Thanks for filing this and offering to help. We've added a
"notification center" style view to the top left corner of N1 in `0.4.32`.
Right now, it's a simple chronological view of all your open / link tracking
events, but we plan to add more features (graphs, etc.) in the future. Cheers!

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1609#issuecomment-216569674)![](https://github.com/notifications/beac
on/ABdOV-uEL1HfTJeSYmIWFn8AQgUpvm-Dks5p92wGgaJpZM4HsJJw.gif)

**Comment by michael-montano** [comment]
One thing I noticed: the email open panel registers even when I open a tracked
email myself. Was this a conscious decision or something that you intend to
remove later?

On May 3 2016, at 10:40 am, Michael Montaño &lt;michael.montano@gmail.com&gt;
wrote:  

> I saw! Totally great that y'all moved to quickly on this. I will remain a
paying user when the free version ends for existing users in a year.

>

> On May 3 2016, at 10:38 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

>> Hey! Thanks for filing this and offering to help. We've added a
"notification center" style view to the top left corner of N1 in `0.4.32`.
Right now, it's a simple chronological view of all your open / link tracking
events, but we plan to add more features (graphs, etc.) in the future. Cheers!

>>

>> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1609#issuecomment-216569674)![](https://github.com/notifications/beac
on/ABdOV-uEL1HfTJeSYmIWFn8AQgUpvm-Dks5p92wGgaJpZM4HsJJw.gif)

**Comment by jackiehluo** [comment]
@michael-montano It shouldn't be happening, but I think there's still an edge case where emails that have quoted text with the tracking pixel in them are still counting as opens! We're working on that and other fixes for the future.
