### ISSUE TITLE
Support right-click contextual menu on search field

### ISSUE THREAD

**Issue by mnquintana** [nylas/N1#161]
I just tried to right click to paste something in the search input instead of using the keyboard shortcut (for some reason) and was surprised to see that there was no context menu - it would be :cool: if there was a context menu for more components (including individual emails in the list view, for instance).

Awesome work on N1 though! :beers:

**Comment by bengotow** [comment]
This has been resolved in 50576e59e3ab46639ce71782759982e2554e0a4c. In the next release, you'll be able to right-click all inputs to get basic cut/copy/paste. Maybe we can add more contextual menu items in the future, but it looks like we don't get anything for free with Electron.
