### ISSUE TITLE
Emails keep sending infinately for Zoho Mail

### ISSUE THREAD

**Issue by raeesiqbal** [nylas/N1#1610]
I've searched for this and did not find a similar reported issue. I'm using "[Deepin Linux 15.1 x64](https://www.deepin.org/?language=en)" which is based on Debian with Nylas N1 0.4.10.4e3595b but had this issue with the previous version too. I dont have third-party plugins installed.

I have my emails hosted with [Zoho Mail](https://mail.zoho.com/) and issue is related to Zoho Mail only. Its not caused by any particular attachment, message or other thing.
#### The Issue
When you send an email to anyone. It will keep sending the email again and again until you manually remove it from the Drafts folder.
#### Possible Cause
The issue is most likely caused by both the email client and Zoho placing a copy of sent email in the "Sent" folder.
#### Possible Fix
[The Zoho Mail representative offers a fix](https://forums.zoho.com/topic/getting-duplicate-messages-saved-to-sent-folder#2266000002608322) by disabling the client behavior of placing a copy of sent emailsin the "Sent" folder.

**Comment by bengotow** [comment]
Hi @raeesiqbal — if it's not sensitive, could you post the email address you're seeing this behavior with? We can check our backend logs for anything unusual.

**Comment by raeesiqbal** [comment]
`joyce@hermangroup.com` is one of the email addresses I sent an email to.

**Comment by raeesiqbal** [comment]
`1katesheridan@gmail.com` was the address where more than 200 copies of the same email were sent.

**Comment by bengotow** [comment]
Hey! We've fixed this on the backend—can you double check that you're not seeing this behavior anymore in the latest update (0.4.19?)
