### ISSUE TITLE
List view: Label box disappears on selected message

### ISSUE THREAD

**Issue by codisms** [nylas/N1#1611]
When selecting a message, the label assigned to the message sort of disappears from the highlighted text.  I say "sort of", because it appears the text might still be there (although very difficult to see), but the box itself is gone.

**Comment by bengotow** [comment]
Hi @codisms — do you know if this is happening in a particular theme? In the stock app, it should look like this:

![image](https://cloud.githubusercontent.com/assets/1037212/13651919/601106d0-e5fe-11e5-9098-b7de0e3e658a.png)

**Comment by codisms** [comment]
Ah.  It is the theme.  n1-ido

**Comment by bengotow** [comment]
Glad that helped! Feel free to file this over at https://github.com/edipox/n1-ido
