### ISSUE TITLE
Shift-J & and Shift-K not selecting messages

### ISSUE THREAD

**Issue by mariosant** [nylas/N1#1613]
I am using the Inbox keyboard shortcut schema and I am experiencing this issue.

While `j` & `k` navigate through messages, `shift-j` & and `shift-k` in not selecting messages. `up` and `down` arrow keys do work as well and so does `shift-up` & `shift-down`.

The expected behavior here is `shift-j` & `shift-k` to select multiple messages.

- [ ] What operating system are you using?. Linux (XFCE desktop), I have confirmed that on OSX 10.10 as well

- [ ] What version of N1 are you using? 0.4.10-4e3595b

**Bug?**
- [ ] Do you have any third-party plugins installed? Only the builtin that N1 came with.

**Comment by bengotow** [comment]
Hey! Thanks for filing this. This is fixed in 9b34ce73ec6910449214b08d71415e193113b3aa and will be included in the next release.

**Comment by bengotow** [comment]
Oh definitely - good catch!

**Comment by mariosant** [comment]
Thank you! :blush:
