### ISSUE TITLE
How to have a list while composing the email?

### ISSUE THREAD

**Issue by qbektrix** [nylas/N1#1614]
I am using 0.4.10-4e3595b (0.4.10-4e3595b) on a OS X 10.11.3.

I wanted to know how to have a numbered list while composing an email. I would like to know more about all the features in the built-in editor.

I only saw an issue regarding a plugin for an advanced editor. Just wanted to know the limit of the current editor.

**Comment by jstejada** [comment]
Hi @qbektrix, if you type `1.` followed by a space, you will insert a numbered list. When you press enter you will create new items in the list. Let me know if this is helpful

**Comment by qbektrix** [comment]
@jstejada thanks. Some further question. How do I do an un-ordered list? And how to I have a mixed list? Like a numbered followed by a alphabet list? Is there a page with all the formatting options of the editor?
