### ISSUE TITLE
Problems with accents in labels from Gmail

### ISSUE THREAD

**Issue by pebs74** [nylas/N1#162]
Labels containing accented chars are shown incorrectly. E.g.: "Estefanía" is shown as "Estefan&AO0-a".

Gmail: http://i.imgur.com/PQVXWFI.png
Nylas: http://i.imgur.com/lfL5tUm.png

On other parts of the UI, accents seem to show up correctly.

**Comment by shawnzvinis** [comment]
I am finding this with other Unicode characters as well. It almost appears that the labels get duplicated because the server doesn't encode them correctly and then treats them as two different labels. May be causing some out-of-sync labels for me. I may add it as a new bug.

**Comment by Israphel** [comment]
I had this problem too. Went to gmail to remove the accent and now I have three labels.

**Comment by bengotow** [comment]
Hi folks—support for labels with accent characters and foreign symbols was fixed in 0.3.24. Enjoy!
