### ISSUE TITLE
N1 should store account tokens in the system keychain

### ISSUE THREAD

**Issue by john-goldsmith** [nylas/N1#1623]
I bumped into this -- https://github.com/martinoj2009/stealNylasAccount -- and was wondering if it was a cause for concern.  It's hard to tell from looking at `config.cson` if the `nylas.accounts[].id` fields (or any other pieces data) are considered sensitive or not.  Thanks!

**Comment by bengotow** [comment]
Hey @john-goldsmith — thanks for reporting this. N1 stores your account IDs and tokens (which are returned from our API during the login flow) in `~/.nylas/config.cson`. If your machine is compromised, a user can swipe the contents of that file and make authenticated Nylas API requests from another computer. (Some folks actually symlink `~/.nylas/` into their Dropbox so their accounts, templates, etc. are shared between their computers.)

I'm not 100% sure that script is cause for concern - a malicious attacker with access to your filesystem could upload anything they want, like `~/Library/Mail` (Mail.app's database). We are planning to move the account tokens to the system keychain in a future release, which will make it more difficult to access them. Hope that helps!

**Comment by john-goldsmith** [comment]
Fair point.  I suppose if I've left my computer unlocked and open to malicious people, I'll have bigger problems than just my Nylas data.  Feel free to close this, I just wanted to increase awareness and visibility.  :+1:

**Comment by bengotow** [comment]
Hey! Thanks for the follow up—it looks like we don't have a public ticket about moving tokens to the system keychain, so I'm going to rename this so we can track that. Cheers!

**Comment by mbilker** [comment]
With a native module on OS X, this is possible. Electron already depends on `libgnome-keychain` on Linux and, from my knowledge, allows storing authentication tokens.

**Comment by bengotow** [comment]
Yep—we can use https://github.com/atom/node-keytar to do this cross-platform, I think!

**Comment by bengotow** [comment]
We've addressed this in 734a52aa6a059bf833eed259467a101fb83c51f1 by moving tokens to the system keychain. Before we can release this, we'll need to test on Linux. @mbilker can you see if `master` works alright for you? We added the dependency to the Fedora / Debian configs, but need to check that it worked.

**Comment by mbilker** [comment]
I will check this out now. Was trying to fix an issue with atom/electron#4733

**Comment by mbilker** [comment]
This works! That is really cool.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!

**Comment by mqudsi** [comment]
Has this changed the behavior of the initial configuration of a custom/local sync engine install? i.e. is one supposed to still initially configure an account by setting the `accountTokens` value in `config.cson`?
