### ISSUE TITLE
Feature Request: change print logo

### ISSUE THREAD

**Issue by mikesitox** [nylas/N1#1624]
Add a simple option to customize print logo or nylas should read the custom logo that I use in my email account of Google Apps for business.

**Comment by bengotow** [comment]
Hey! Thanks for filing this—for the time being we've decided not to add support for custom logos, but we may revisit this in the future, or remove the logo altogether. Thanks!

**Comment by ronilaukkarinen** [comment]
Hello. As a paying subscription user, the logo in prints is quite frustrating. Is there any way to remove it?

**Comment by ronilaukkarinen** [comment]
Any progress with this? as a monthly paying user, I find Nylas logo in every PDF very annoying. Please.
