### ISSUE TITLE
Feature request: unified spam folder

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#1625]
Having spam as a unified folder across accounts alongside the others in the sidebar would be very useful. I often get false-positives in my spam folders, and like to be able to go in and remove them from time to time.

**Comment by PwnArt1st** [comment]
+1

**Comment by sanjeevverma1** [comment]
Unified spam folder for all accounts + the ability to empty all spam folder with one click

**Comment by sanjeevverma1** [comment]
Released! thank you @bengotow & team 👍

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
