### ISSUE TITLE
Phantom email in my Inbox

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1626]
I see one phantom message in my inbox with nothing in it. No sender / receiver / subject / data and no such corresponding email in my Gmail inbox.

Screenshots.
**Inbox View:**
![screenshot from 2016-03-10 18-11-08](https://cloud.githubusercontent.com/assets/2344626/13687961/9bf95438-e6ec-11e5-9198-b24daa6de3c9.png)

**Message View:**
![screenshot from 2016-03-10 18-12-39](https://cloud.githubusercontent.com/assets/2344626/13687962/9bfacec6-e6ec-11e5-96d8-6c892a7dd0de.png)

**Print View:** (See how it says  **_undefined_** . Normal messages show thread participants there)
![screenshot from 2016-03-10 18-13-51](https://cloud.githubusercontent.com/assets/2344626/13687990/c7dde348-e6ec-11e5-9e34-afee3a5e1540.png)

- [x] Are there any related issues? 
No

- [x] What operating system are you using?
Arch Linux

- [x] What version of N1 are you using?
0.4.10

- [x] Do you have any third-party plugins installed?
No

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
Found only one message.

**Comment by bengotow** [comment]
Merging with #1562. This is definitely a strange one...
