### ISSUE TITLE
Can't sync with local sync engine 

### ISSUE THREAD

**Issue by marshallmcmullen** [nylas/N1#1627]
I just pulled the latest changes from github (v0.4.13-3630a14) and I am unable to get any email from my local open source sync engine. When I open the activity log I see pages and pages of:

16:49:00  RunCopycurl -X GET "http://4x3gip90eb8c0q90c0z327mhz:@localhost:5555/metadata?limit=200&offset=0"
404

They're all getting 404 error. If I try that locally in my web browser I see the same thing:

{
    "message": "404: Not Found",
    "type": "api_error"
}

I assume there are some changes needed in the local sync engine code. I updated to the latest git version as well but it's still not working.

**Comment by bengotow** [comment]
Hey @marshallmcmullen — thanks for reporting this. We recently changed the initial sync logic to pull metadata for API objects, and this was introduced then. I'll see if we can fix this real quick before the next release goes out.

**Comment by bengotow** [comment]
Hi—could you pull down master and try again? This should be fixed in https://github.com/nylas/N1/commit/a24f67398e25b6763fd54b14adfc4150b94200c7

**Comment by marshallmcmullen** [comment]
SWEET that fixed it. Thanks so much for knocking out such a quick fix. You guys are amazing as always.
