### ISSUE TITLE
View -> "Toggle menu" doesn't toggle the menu

### ISSUE THREAD

**Issue by itsravenous** [nylas/N1#163]
Running on Ubuntu 15.10, tried inspecting using dev tools but seems the menu is outside the WebKit "canvas". No errors in dev console or stdout when clicking the menu item.

**Comment by john-landgrave** [comment]
+1 on this. I'm on Linux Mint 17. I would prefer for this toggle to work, but if it couldn't, I would settle for having the fonts adjusted properly for HiDPI screens. I'm on a 4k monitor and it makes the text get super blown up.

**Comment by grinich** [comment]
@itsravenous does the keyboard shortcut work? It should be the same keyboard shortcut as linux https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/shortcuts

**Comment by itsravenous** [comment]
It's not the dev tools we're having trouble toggling, it's the menubar (sorry if I'm misunderstanding)

**Comment by bengotow** [comment]
Hey folks—I've confirmed that the "Toggle Menu Bar" menu item on Linux is broken (actually, it's not tied to anything at all... must have been lost in a refactor at some point.) I'll see if we can get this fixed.

**Comment by stuartwesterman** [comment]
+1 toggle menu bar is not tied to anything.

**Comment by felipetavares** [comment]
Any temporary fixes?

**Comment by bengotow** [comment]
Hey folks—we temporarily pulled `Toggle Menu Bar` from the menu entirely. Going to go ahead and close this.
