### ISSUE TITLE
Use elasticsearch for N1 search

### ISSUE THREAD

**Issue by geekpete** [nylas/N1#1633]
A fit for purpose search component and would be great as an optional plugin/config for hosting your own N1 Server or even for all the users of the Nylas hosted cloud.

**Comment by bengotow** [comment]
Hey! We actually experimented with elasticsearch-powered search internally but we haven't deployed it to our production environment. We'll almost definitely be revisiting this in the near future. Stay tuned!

**Comment by Kerruba** [comment]
Are you developing something also for Apache SolR?

**Comment by bengotow** [comment]
Hey folks! I'm going to go ahead and close this. When we improve search later this summer, we may use elasticsearch and we may not. Either way, improved search for non gmail accounts is definitely on the way.
