### ISSUE TITLE
Label update is not reflected in the sidebar count

### ISSUE THREAD

**Issue by Kerruba** [nylas/N1#1636]
Nylas N1 Version 0.4.14-53cd69b, Mac OsX El Capitan, one Gmail account.

I've just updated an email removing a label (it had one label only). It was also the only email in the label-folder. When I removed the label, the sidebar count related to the folder has not been updated
<img width="1440" alt="nylas label issue" src="https://cloud.githubusercontent.com/assets/2854782/13699115/446165c4-e770-11e5-9833-846e1596ac5b.png">

**Comment by jstejada** [comment]
hey @Kerruba , thanks for reporting this. I'm merging itno duplicate #759
