### ISSUE TITLE
Add option for count badge to represent all emails rather than just unread

### ISSUE THREAD

**Issue by jcalifa** [nylas/N1#1639]
People who subscribe to Inbox Zero don't care which emails they read. If it's not archived—it's relevant.

This is how Mailbox worked.

**Comment by zombxx** [comment]
:+1:

**Comment by bengotow** [comment]
Hey folks! We're looking to implement this very soon. Anyone have screenshots, references for what this option looks like in other apps? Want to make sure I follow the expected naming of the option, etc. but don't use inbox zero myself.

**Comment by jcalifa** [comment]
I think a simple naming scheme could be:
- Badge should reflect unread emails.
- Badge should reflect all emails in inbox / all unarchived emails.

I don't think Mailbox even gave the option. It just defaulted to all unarchived emails.

**Comment by DavidChouinard** [comment]
@bengotow I wanted this too and have a half working solution on my local build. It seems like a reasonable approach is having `ThreadCountsStore` keep count of both unread and totals. It exposes a `unreadCountForCategoryId`/`totalCountForCategoryId` and `UnreadBadgeStore` picks the right one.

(this computes both values irrelevant of the setting, but unread values are needed in the sidebar and I can imagine eventually wanting to show totals in the message listing)

**Comment by osakkers** [comment]
I'd also love this feature. What is the status of this update? Still doesn't seem to be operational...

**Comment by courajs** [comment]
Here's the options for this in OSX Polymail:
<img width="616" alt="screen shot 2016-05-31 at 2 39 56 pm" src="https://cloud.githubusercontent.com/assets/1588273/15686298/a8123e24-273d-11e6-8b38-11dbdd702c23.png">

**Comment by mscottford** [comment]
I also took a peek at implementing this in a plugin, but there didn't seem to be a great extension point for it.

**Comment by jackiehluo** [comment]
Should be added in https://github.com/nylas/N1/commit/58e1ed57ee2397d1067738b2d87774987bc4474d!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
