### ISSUE TITLE
manual sync

### ISSUE THREAD

**Issue by lithstud** [nylas/N1#164]
Hi, is it possible to manually sync / refresh the emails?
I have to wait for a couple of minutes until it appears in my email list.

**Comment by bengotow** [comment]
Hey @lithstud — thanks for checking out N1. The app connects to a streaming endpoint on the sync engine, so your mail appears as quickly as it's synced from the mail server. It looks like the average delay has gone up a bit in the last few days as we've sent out tons of invites, but it should be within ~15 seconds. If it's consistently slow for you, shoot an email to `support@nylas.com` with your email address and our platform team can dig in!

**Comment by lithstud** [comment]
@bengotow thanks for explaining. I'll wait for some time to see if it gets better and will drop you an email if it doesn't.
