### ISSUE TITLE
Web Forms Issue (Linux)

### ISSUE THREAD

**Issue by BraisGz** [nylas/N1#1640]
Hi ! I'm using Ubuntu 15.10 with the 0.4.10 nylas version. 
I only have installed the "send later" plugin. So....
When i want to send any mail by a web form, nylas opens but dont load the form with the pre-written fields. 
(sorry if I didn't express myself very well... i'm writting from spain...)

**Comment by mbilker** [comment]
Are you referring to the templates plugin?

**Comment by bengotow** [comment]
Hi—I think this might be talking about clicking a `mailto://` link - @BraisGz could you right click the link and paste the URL here? Might allow us to create a failing test case.
