### ISSUE TITLE
Unread badge does not disappear when mail is read

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#1641]
Despite the fact that there are no unread emails in my inbox, the badge persists. [Here is a screenshot](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Shot-2016-03-11-10-11-20.png). The badge also appears in the dock.

Running Version 0.4.14-53cd69b (0.4.14-53cd69b) on OS X 10.11.3.

**Comment by fonnesbeck** [comment]
Specifically, this appears to occur with my [Gmail account](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Shot-2016-03-11-10-19-38.png).

**Comment by jstejada** [comment]
hey @fonnesbeck , thanks for reporting this. I'm merging into duplicate issue #759
