### ISSUE TITLE
Expanding collapsed participants field in composer requires two clicks, doesn't stay open

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1643]
Demo: https://vid.me/5sRe

When you click the collapsed participants field in the composer, it quickly expands and then collapses again, and only stays open if you click it once more. So it requires two clicks to expand the participants field.

- [x] Are there any related issues?

- [x] What operating system are you using? OS X El Capitan 10.11.3 (15D21)

- [x] What version of N1 are you using? Version 0.4.14-53cd69b (0.4.14-53cd69b)

- [x] Do you have any third-party plugins installed? None

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

**Comment by bengotow** [comment]
Hey! This should be fixed in 0.4.25 - we overhauled the code that did the expanding collapsing of these because it tried to control the focus within the composer, which was a bit tricky. Can you let me know if you still have this problem in 0.4.25?
