### ISSUE TITLE
N1 creates new icon in GNOME dock

### ISSUE THREAD

**Issue by Bensonhurst** [nylas/N1#165]
On Gnome 3.18, I have N1 in my favorites in the dock, yet when I click on it, it does not nest under that icon and creates a new entry called "Nylas" with a question mark icon.

**Comment by itsravenous** [comment]
Have a similar issue in GNOME 3.16; typing "Nylas" into the search shows the Nylas N1 entry with the app icon, but when launched the dock icon is the "unknown" icon.

Screenshots:

[Imgur](http://i.imgur.com/Mhemx7K.png)
[Imgur](http://i.imgur.com/5oDJ48H.png)

**Comment by jacobmischka** [comment]
This can be fixed by adding a StartupWMClass property in N1's .desktop file: `StartupWMClass=Nylas N1`

![screenshot from 2015-10-26 09-28-26](https://cloud.githubusercontent.com/assets/3939997/10731550/f05d6e22-7bc3-11e5-90e9-4af9d984ea06.png)

**Comment by Bensonhurst** [comment]
Fantastic, thank you. I can confirm that this fix does indeed work. It's the same issue that Google Chrome has, then.

**Comment by jacobmischka** [comment]
This is a relatively common thing, and it's the exact reason for this key in the desktop spec!

**Comment by mbilker** [comment]
Hey thanks for the issue! This was fixed in 5d0e0201bbf5f38b148ea73098a22cff619a9790.
