### ISSUE TITLE
Cannot create Exchange account

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#1652]
I am unable to create an Exchange account in N1, despite following the posted instructions. I have followed the `MYCORP\bob` format for the user name, but to no avail. I get the following error:

"Could not log into your exchange server based on the credentials provided"

I have 2 other clients on this machine that successfully accept the same Exchange credentials, so I can confirm that it is not my account or server that has an issue.

Running Version 0.4.14-53cd69b (0.4.14-53cd69b) on OS X 10.11.3.

**Comment by fonnesbeck** [comment]
At the most recent attempt, the app hangs. When asked to wait or close the app, closing results in a crash. [Here is the log](http://fonnesbeck-dropshare.s3.amazonaws.com/note-8ip6TlQuLn.html).

**Comment by mbilker** [comment]
@fonnesbeck That log is very difficult to read. Is there a way to get the line breaks in there, especially for the stack traces for each thread.

**Comment by fonnesbeck** [comment]
Sorry about that. I just cut and pasted to Dropshare. Will get you a better one next time it happens.

**Comment by mbilker** [comment]
Alright then. Thank you anyway for the crash log.

**Comment by jstejada** [comment]
hi @fonnesbeck , are you still unable to add your exchange account? If so please email support@nylas.com. thanks!
