### ISSUE TITLE
Error message for Exchange setup is not copyable

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#1654]
When (unsuccessfully) setting up my Exchange account on N1, I get error messages like the following:

![error](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Shot-2016-03-11-15-24-20.png)

however, the URL can neither be clicked directly, or selected and copied, making it very difficult to navigate to the page for help.

Running Version 0.4.10-4e3595b (0.4.10-4e3595b) on OS X 10.11.3

**Comment by bengotow** [comment]
Hey! Thanks for filing this—the URL should be clickable if you update to `0.4.14`. We should make it copy-pastable as well though..
