### ISSUE TITLE
OSX toolbar buttons cut off

### ISSUE THREAD

**Issue by travisnewman** [nylas/N1#1655]
Every version that I've used, the close, minimize, and maximize buttons are cut off on the edges.

Every theme except for the new Darkside theme (which changes the shape of these buttons altogether) has this issue.

OSX El Capitan, Nylas N1 version 0.4.14-53cd69b

No plugins installed

When the window is inactive:
![image](https://cloud.githubusercontent.com/assets/3768622/13717280/81e868e6-e7ae-11e5-8d10-e59cee9288a4.png)

When the window is active: 
![image](https://cloud.githubusercontent.com/assets/3768622/13717287/8d1855d2-e7ae-11e5-8a15-5572063f1e2a.png)

I searched around for this bug but couldn't find it, so I'm sorry if this is a duplicate.

**Comment by mbilker** [comment]
Thank you for posting this @travisnewman ! The traffic lights are actually images that mimic the native OS X ones because of incompatibilities with OS X and Electron.

Does your Mac have a Retina display? This could be related to scaling.

**Comment by travisnewman** [comment]
It does not have a Retina display, it's a 1080p external monitor. However
the same thing happens on the laptop screen itself, a non retina MacBook
Pro.

On Friday, March 11, 2016, Matt Bilker <notifications@github.com> wrote:

> Thank you for posting this @travisnewman <https://github.com/travisnewman>
> ! The traffic lights are actually images that mimic the native OS X ones
> because of incompatibilities with OS X and Electron.
>
> Does your Mac have a Retina display? This could be related to scaling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylas/N1/issues/1655#issuecomment-195652806>.
>


--

**Comment by travisnewman** [comment]
OK, so I think you were on to something with the scaling thing, but not due to retina. I just nuked my whole .nylas directory because it wasn't syncing at all, and now it's working fine. 

The odd thing is that all the screen elements are now larger than they've ever been for me. I had thought that the default text was kinda small, but now it looks like what I'd expect.

So for some reason my profile had everything scaled way down, regardless of theme. No clue why, but here we are, it's working now.

Are there any settings buried in the prefs that would scale down text like that?

**Comment by mbilker** [comment]
There is a setting to scale down the UI available from `Preferences -> General -> Workspace -> Override standard interface scaling`.

![2016-03-12-15-17-33_344x166](https://cloud.githubusercontent.com/assets/1266541/13725075/a49ae06e-e865-11e5-8ef6-d98442c79a9f.png)

**Comment by travisnewman** [comment]
OK that has helped narrow down what's happening. Apparently at some point I set that to 80%. I'm not sure if I did that intentionally or not, but that's what was causing it.

On 100% and 140% the traffic lights look normal. On 60%, 80%, and 120% they look like the images I posted.

**Comment by grinich** [comment]
We're actually going to deprecate the view zoom modes, so I'm going to close this.
