### ISSUE TITLE
When a snoozed thread receives a new message, snooze state should be removed (unsnoozed)

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#1658]

**Comment by bengotow** [comment]
I think it might be sufficient to make the snooze label only visible within the snoozed perspective.

**Comment by jackiehluo** [comment]
@bengotow Would a person be able to snooze it again or archive/delete it if it were still technically snoozed?

**Comment by jstejada** [comment]
they should

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
