### ISSUE TITLE
Bugs on Windows

### ISSUE THREAD

**Issue by ihorvorotnov** [nylas/N1#166]
Just received invitation, downloaded and installed (well, kind of). And found some bugs right away. OS: Windows 10 x64.

Missing icon in font on welcome screen:

![2015-10-23_18-42-26](https://cloud.githubusercontent.com/assets/1066083/10698970/4b8e7c0a-79bc-11e5-8525-549b902c4b59.png)

Window is positioned off-screen, top left corner, like window center is set to 0,0 (see #150)

![2015-10-23_18-43-06](https://cloud.githubusercontent.com/assets/1066083/10699035/adb333b2-79bc-11e5-94da-a5358aa33394.png)

3. Tried installing plugins, and the spinners are running for like an hour, literally. With no progress (see #152):

![2015-10-23_19-25-23](https://cloud.githubusercontent.com/assets/1066083/10699059/d427b766-79bc-11e5-847c-4d1d1d4d6a75.png)

**Comment by ihorvorotnov** [comment]
Relaunching the app fixed 3rd issue - works, plugins were installed.

**Comment by bengotow** [comment]
Hey folks—1 and 2 were fixed in the last few commits, and @emorikawa is working on a fix to the third issue. We'll be releasing a small patch so new users don't run into these.

Thanks for reporting!

**Comment by ihorvorotnov** [comment]
@bengotow Thanks for the info! So far, the app looks tasty and I really like it, so, I'm gonna use it on a daily basis from now on. If I'll run into something nasty again - I'll post a new issue(s). Hope there will be not many of them :)

**Comment by grinich** [comment]
Closing this, since the third point is tracked here https://github.com/nylas/N1/issues/152
