### ISSUE TITLE
What are the formatting options of the inbuilt editor?

### ISSUE THREAD

**Issue by qbektrix** [nylas/N1#1660]
@jstejada, just to follow up from [https://github.com/nylas/N1/issues/1614](https://github.com/nylas/N1/issues/1614)
How do I do an un-ordered list? And how to I have a mixed list? Like a numbered followed by a alphabet list? Is there a page with all the formatting options of the editor?

**Comment by jackiehluo** [comment]
Use a dash (-) to start an unordered list! You can't do mixed lists yet, and that's been requested at #1541.

**Comment by alrick** [comment]
hey there!

I can't create unordered list as you described, did something changed?

**Comment by jackiehluo** [comment]
@alrick It's not working on the current release, unfortunately, but the fix is on master now and should be shipped soon!

**Comment by alrick** [comment]
Okay, thank you
