### ISSUE TITLE
Unread count never decreases

### ISSUE THREAD

**Issue by eshansingh** [nylas/N1#1665]
I currently have 0 unread messages in my inbox. However the label on the left is still showing the amount of emails that I deleted. When a new email comes in, the count gets added, but when I delete it, it doesn't decrease.

![Screenshot](http://imgur.com/f4MWIuu.png)

- [x] Are there any related issues? 
No, there don't seem to be.

- [x] What operating system are you using?
Mac OSX El Capitan 10.11.3b.

- [x] What version of N1 are you using?
0.4.14-53cd69b

**Bug?**
- [x] Do you have any third-party plugins installed?
I have the Material theme installed. Though when I remove it, the issue doesn't fix.

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have a Gmail account, so I'm not sure.

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.
No.

**Comment by jstejada** [comment]
hi @eshansingh thanks for reporting this. I'm merging into duplicate #759
