### ISSUE TITLE
Black fill in pop up menus

### ISSUE THREAD

**Issue by eldarkg** [nylas/N1#1667]
Today I noticed that content is filled black in pop up menus.
![bug](https://cloud.githubusercontent.com/assets/5782069/13725228/82242cec-e8ac-11e5-86ca-cb3bc4775810.png)
Nylas: 0.4.14
OS: Ubuntu 15.10

**Comment by jackiehluo** [comment]
@eldarkg Hm... that's really strange. I'm assuming you're using the Light theme. Is it persistent if you restart the app?

**Comment by jstejada** [comment]
hey everyone, going to merge into duplicate #1163

**Comment by eldarkg** [comment]
@jackiehluo Today all Ok without any changes
![ok](https://cloud.githubusercontent.com/assets/5782069/13728120/47efe210-e91e-11e5-983d-cacd93e140e3.png)
Maybe it was after updating adobe flash

**Comment by shubham12101** [comment]
Hey, I download N1 today, and I facing the same issue:
![screenshot from 2016-03-25 01 03 25](https://cloud.githubusercontent.com/assets/6473299/14029008/9872751c-f225-11e5-8f29-18243aaa73f0.png)
N1 version: 0.4.16-8cb7748
OS: elementaryOS

**Comment by gonzamontiel** [comment]
Hi, I'm having the same issue not only on dropdowns:
![screenshot from 2016-07-15 11 49 37](https://cloud.githubusercontent.com/assets/4713407/16878539/52e5141c-4a83-11e6-9f1c-c4851912a8cd.png)

Also toggling Dev tools (Ctrl+Alt+I):
![screenshot from 2016-07-15 11 58 10](https://cloud.githubusercontent.com/assets/4713407/16878578/6cba208a-4a83-11e6-9661-dd1dfe01c5fc.png)

Note: I'm able to see Dev tools in Chrome and Chromium.

N1 version: 0.4.45
Elementary OS Freya

**Comment by thompsondc** [comment]
Same issue. Linux Mint (Cinnamon) 18.1. I've tried multiple color themes in Nylas, but always results in solid black dropdowns (assuming black text as well, as I can randomly try options and get different values based on where in the dropdown I click - so it works, just invisible text).
Screenshot on default theme:
![image](https://cloud.githubusercontent.com/assets/2481359/25184011/38a49412-24e7-11e7-94d5-cecdcb6946d2.png)

Screenshot on dark theme:
![image](https://cloud.githubusercontent.com/assets/2481359/25184028/4757eafe-24e7-11e7-866d-3f890884dbe5.png)

Note: toggling developer tools creates a large white area in the default theme:
![image](https://cloud.githubusercontent.com/assets/2481359/25184139/8c9cb72a-24e7-11e7-903e-c49041699471.png)
Same white region with dark theme.
