### ISSUE TITLE
Frozen On IMAP/SMTP Account Setup

### ISSUE THREAD

**Issue by BradRuderman** [nylas/N1#1668]
Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [x] Are there any related issues? **No**

- [x] What operating system are you using? **Mac OS X v10.11.03**

- [x] What version of N1 are you using? **Version 0.4.14-53cd69b (0.4.14-53cd69b)**

**Bug?**
- [x] Do you have any third-party plugins installed? **No**

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? **No**

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot. **No**

I am trying to setup an IMAP/SMTP account. I am using google as an imap and a 3rd party as smtp. I choose IMAP/SMTP, then I enter my username and settings for imap. I am using gmail for imap. Then I add my SMTP setting and I click continue, and the spinner freezes, causing me to have to force quit the app. I tried reloading the app with debug flags and opening Chrome developer tools or trying to open the "Detailed Logs" but I am unable to do so or find where this is erroring. The SMTP server I am connecting with is under TLS so it shouldn't be a problem and works fine in both Apple Mail and Thunderbird.

Thanks!

**Comment by BradRuderman** [comment]
It looks like I figured it out. I had to enable "Less Secure Apps" on gmail. https://support.google.com/accounts/answer/6010255?hl=en

I need to test if generating an app specific password removes Gmail from thinking that N1 isn't secure.

**Comment by mbilker** [comment]
Thanks for the report @BradRuderman ! N1 normally authorizes with Gmail for an OAuth token to use for IMAP and SMTP, but I know in this case you use your own SMTP server. Please do test with an app specific token to see if it gets around this limitation.

**Comment by BradRuderman** [comment]
@mbilker  Whats going on I am now getting this message:

<img width="309" alt="screenshot_3_13_16__8_24_pm" src="https://cloud.githubusercontent.com/assets/2366784/13734293/99bfcb92-e959-11e5-88f8-deb7d463de47.png">

**Comment by mbilker** [comment]
@BradRuderman The hosted Sync Engine already has you in their system. They require you to message them to change the endpoint.

**Comment by BradRuderman** [comment]
@mbilker  Gotcha thanks. Yes, if your company supports 2 factor authentication, and you enable it then you can generate an app specific password and that seems to avoid the error. However I believe the bug here should be throw a better error message then just to freeze. In addition I think there should be a feature request to control SMTP outbound independently of the inbound. So I could use google oauth for inbound and smtp for outbound. 

Thanks!

**Comment by jackiehluo** [comment]
Closing this issue for now since it looks resolved—let me know if you see it again!
