### ISSUE TITLE
Swipe to archive is now swipe to trash in Gmail accounts

### ISSUE THREAD

**Issue by rakeshdas1** [nylas/N1#1669]
On the latest version of N1 (0.4.14-53cd69b), when I swipe to the right on my MacBook with the touchpad,  the archive option is no longer present as it was in previous version and is instead a trash option. I have tested this on both of my Gmail-only inboxes (not the unified inbox) and they are yielding the same response. I can still archive all of my mail in my Gmail accounts via the `e` key shortcut. 

Is this an intended feature that I happened to miss in the changelogs? think the swipe to trash function is appropriate for non-Gmail account inboxes, but it seems necessary for Gmail accounts.

<img width="433" alt="screen shot 2016-03-12 at 6 15 00 pm" src="https://cloud.githubusercontent.com/assets/6901641/13726131/6b118aea-e87f-11e5-9584-a6f5d2d889e9.png">

**Comment by jackiehluo** [comment]
@rakeshdas1 Did you change your preferences (in "General" under "Reading") to use backspace/delete to move messages to trash? The swiping functionality is currently bound to that option.

**Comment by rakeshdas1** [comment]
@jackiehluo That did, thanks!
