### ISSUE TITLE
After recent update, the label "sent" shows up in every exchanged email 

### ISSUE THREAD

**Issue by pulka** [nylas/N1#1671]
- [ ] What operating system are you using?
ElementaryOs

- [ ] What version of N1 are you using?
0.4.14-53cd69b

**Bug?**

- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
only happens with Gmail

**Comment by patrickheeney** [comment]
Same thing happens to me. Relayed to #1225 maybe?

**Comment by jstejada** [comment]
Hey guys, this slipped past me in the next release. Pushed a fix, and it hsould be available in the next release, thanks!

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
