### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by THPubs** [nylas/N1#1672]
Is there a way to export the account settings and import them into another machine? I have N1 in two machines and I have added my mail accounts in one. I need to take them to my other machine without adding one by one. Is it possible?

**Comment by mbilker** [comment]
Thanks for the question @THPubs ! It is possible to copy the whole `~/.nylas` folder to another computer to copy the accounts between the computers.

**Comment by THPubs** [comment]
@mbilker Great! Does it work between different platforms? For example, if we copy a folder from Windows to Linux?

**Comment by mbilker** [comment]
@THPubs Yes it will work cross platform.

**Comment by mbilker** [comment]
If N1 does have an error when copying, delete `edgehill.db`.

**Comment by THPubs** [comment]
Perfect! Thanks @mbilker :+1:
