### ISSUE TITLE
Increase timeout limit

### ISSUE THREAD

**Issue by anchitjain1234** [nylas/N1#1673]
- [x] What operating system are you using? Ubuntu 14.04

- [x] What version of N1 are you using? 0.4.14-53cd69b

**Bug?**
- [ ] Do you have any third-party plugins installed? No

- [ ] Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No

Yesterday I updated nylas to version 0.4.14, after that I started facing issues in sync.
I tried to look at activity window and saw that most the requests were being timed out, but when I tried the same request using curl on terminal they were working fine. 
So is there any way through which I can increase timeout limit of Nylas?

**Comment by bengotow** [comment]
Hey! Thanks for filing this—we're addressing this by increasing timeouts  and also throttling roll out of versions which require lots of re-sync API requests. Cheers!
