### ISSUE TITLE
Interface scaling

### ISSUE THREAD

**Issue by federicoiosue** [nylas/N1#1674]
I'd like to reduce a little the application's interface and it's great to have an option for this but actually a 20% step seems to me a little too much.
Maybe reducing the step to 10% could easily fit better? Or maybe by using an analogic progress bar widget?

Thanks for your work

**Comment by molstrangler** [comment]
+1 Yes please.

Essential for more conformable viewing on Windows computers where the choice of different displays than Apple.  The current selections may suit OS X retina displays but not for us Windows users,

**Comment by jackiehluo** [comment]
Merging into #1322!

**Comment by bengotow** [comment]
Hey folks! We're going to actually remove this option from preferences and make it strictly a configuration option because it causes small visual issues we don't have the bandwidth to support, but we'll make it accept any zoom value. Docs coming soon.

**Comment by bengotow** [comment]
See https://github.com/nylas/N1/blob/master/CONFIGURATION.md#other-config-options
