### ISSUE TITLE
Email Disappearing

### ISSUE THREAD

**Issue by VMat21** [nylas/N1#1678]
Good afternoon,

I am a new user of N1, I found this software very nice, and the configuration of most of my email acounts was really easy and fast.
I have a strange problem only using one particular email account, basically the issue is that all the email stored in every other folder except the imbox (sent, drafts and other subfolders) disappear after a couple of minutes or are not displayed at all.

Here is some technical data:
I have this problem using the last version of N1 (0.4.14).
I am using windows 10 and the configuration parameters for the email account are:
Incoming mail server (IMAP): imap.uni-regensburg.de
Port 993
SSL encryption
Outgoing Mail Server (SMTP): mail.uni-regensburg.de
Port 587
TLS encryption

Has anyone any idea about the origin of this problem and a solution for it?
Please let me know if you need some other information,
Thank you very much in advance.

Matteo Villa

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know at support@nylas.com if it's not.
