### ISSUE TITLE
Negative Email Counts

### ISSUE THREAD

**Issue by pizzaops** [nylas/N1#1679]
My inbox for my personal mail (which is still Google Apps, not gmail.com) is showing a negative email count, and as I "archive" messages, the negative count goes "up" (or down, I suppose, technically).

Inbox at `-2`:
![alt text](https://i.imgur.com/W0TlCDF.png "Inbox at -2")
Archived message, inbox now at `-3`:
![alt text](https://i.imgur.com/wN6fvMh.png "Inbox at -3")

I'd be happy to provide detailed logs directly to the N1 team but would prefer not to post them into this issue, as they appear to contain some private information (e.g. email addresses of my contacts).

---

Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- [x] Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

Not as far as I can tell.

- [x] What operating system are you using?

OSX 10.11

- [x] What version of N1 are you using?

Version 0.4.14-53cd69b (0.4.14-53cd69b)

**Bug?**
- [x] Do you have any third-party plugins installed?
No

- [x] Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not as far as I can tell.

- [x] Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

N/A

**Comment by jackiehluo** [comment]
Merging into #759.

**Comment by pizzaops** [comment]
@jackiehluo ah I'm sorry! I swear I searched for similar bugs before I submitted this!

**Comment by jackiehluo** [comment]
@pizzaops Oh, no worries! We're working on a fix, and thanks for reporting it!
