### ISSUE TITLE
Can't manage accounts on OS X

### ISSUE THREAD

**Issue by gaogaigar4** [nylas/N1#1680]
Running 0.4.14-53cd69b and I ran into the bug where it shows Gmail has unread e-mail when it really doesn't.  I tried deleting Nylas and the relevant directories and then reinstalling to try to fix the problem as suggested elsewhere.  That didn't work, and now I get multiple accounts for the same Gmail account.  When I go to try to manage accounts I get:

```
/Applications/Nylas N1.app/Contents/Resources/app.asar/internal_packages/preferences/lib/tabs/preferences-account-details.js:243
Uncaught TypeError: Cannot read property 'split' of undefined
```

**Comment by jackiehluo** [comment]
This bug should be fixed now!
