### ISSUE TITLE
Deleting data from the Nylas server

### ISSUE THREAD

**Issue by ndastur** [nylas/N1#1681]
Having looked at the Activity window it became very apparent that Nylas is not a traditional MUA. Via Google I found issue #1082 and I am concerned.  Can you please advise how I go about stopping use of Nylas and making sure that all data you have obtained about me is deleted. I should add that this collection of data and storage on third party servers was not with my consent.

**Comment by grinich** [comment]
Hi @ndastur -- if you send a note to support@nylas.com from the account you signed up with, we can delete the data for you.

More info in our FAQ. The last screen in the signup flow links to information about our cloud sync engine as well. You can read more here: https://nylas.com/n1/faq
