### ISSUE TITLE
Recent threads in contact sidebar should use BOTH subject and snippet

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1683]
Important for messages that actually have no subject line. Example: 

![image](https://cloud.githubusercontent.com/assets/92417/13732553/aa9295ec-e942-11e5-811b-3dfa0f6f31a0.png)

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
