### ISSUE TITLE
Included Darkside theme has incorrectly sized window buttons on OS X

### ISSUE THREAD

**Issue by AlexPoulsen** [nylas/N1#1687]
Included Darkside theme has incorrectly sized window buttons on OS X
Included:
<img width="155" alt="screen shot 2016-03-13 at 10 52 42 pm" src="https://cloud.githubusercontent.com/assets/9259671/13733903/be07b2fc-e96e-11e5-8a0e-e0998f5e6597.png">
From GitHub a few weeks ago:
<img width="174" alt="screen shot 2016-03-13 at 10 56 09 pm" src="https://cloud.githubusercontent.com/assets/9259671/13733917/ec25a9dc-e96e-11e5-8ca7-fc8cbd1e0ba4.png">
Also the mark as unread button is clipped on all included themes (and many non-included) except Darkside. Clipped by one+ pixel(s) on the right side.
Light:
<img width="55" alt="screen shot 2016-03-13 at 10 58 57 pm" src="https://cloud.githubusercontent.com/assets/9259671/13733945/435790c6-e96f-11e5-83e3-400376e97656.png">
Dark:
<img width="55" alt="screen shot 2016-03-13 at 10 59 09 pm" src="https://cloud.githubusercontent.com/assets/9259671/13733944/4345429a-e96f-11e5-8c37-d613a591cec2.png">
Darkside:
<img width="54" alt="screen shot 2016-03-13 at 10 59 18 pm" src="https://cloud.githubusercontent.com/assets/9259671/13733943/433143bc-e96f-11e5-8999-0c21deb83c84.png">
Taiga:
<img width="57" alt="screen shot 2016-03-13 at 10 59 23 pm" src="https://cloud.githubusercontent.com/assets/9259671/13733942/4304411e-e96f-11e5-885b-e481e40daf09.png">

**Comment by bengotow** [comment]
This was addressed in #1861. Cheers!
