### ISSUE TITLE
Main Window Loses State on Restart (Linux)

### ISSUE THREAD

**Issue by JohnSandel** [nylas/N1#1689]
N1 (0.4.10-4e3595b) forgets its window state on every restart, on a Chromebook (Intel 3205U 1.5 GHz) running Elementary OS Freya 0.3.2, on Ubuntu 14.04.

On my Mac running OS 10.10.5, N1 (0.4.14-53cd69b) remembers its previous window state on every restart.

On 1/13/16, I posted this (as Issue #1001).
On 2/11/16, @jstejada closed this issue as "stale." Per his suggestion, I'm reopening it because the issue persists.

**Comment by mbilker** [comment]
OS X stores its own window state independent of N1. N1 attempts to store its window state on other platforms.

**Comment by jstejada** [comment]
hey @JohnSandel , thanks for the report. Merging into #1831
