### ISSUE TITLE
Show read receipts "eye" in the thread list of 2-pane mode

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1691]
Right now it only shows in single-pane mode in the sent folder.

![image](https://cloud.githubusercontent.com/assets/92417/13737627/ec8a2c92-e97b-11e5-9011-03976a8bf1d6.png)

vs. 

![image](https://cloud.githubusercontent.com/assets/92417/13737635/f68dc492-e97b-11e5-8593-c2501005f3c1.png)

**Comment by jstejada** [comment]
addressed in https://github.com/nylas/N1/commit/3cdd831e226426c2086a60a192a0b758b5cbb4f5

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
