### ISSUE TITLE
composer popout icon should be visible all the time

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1692]
Currently it's only visible when editing participants or the subject.

![image](https://cloud.githubusercontent.com/assets/92417/13737653/327dcd62-e97c-11e5-9e8f-a81b16362077.png)

versus

![image](https://cloud.githubusercontent.com/assets/92417/13737674/498f7f50-e97c-11e5-8bbf-8ba6c8b206fe.png)

**Comment by bengotow** [comment]
Will be fixed by https://phab.nylas.com/D2766

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
