### ISSUE TITLE
Clicking reply/forward button should not create a second draft in reply to the same message if there already exists a draft

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1694]
![two-drafts](https://cloud.githubusercontent.com/assets/92417/13737853/b45d762e-e97d-11e5-86d9-ecc09b36c6eb.gif)

The expected behavior is that clicking reply a second time will effectively be a no-op. The reply button should not allow you to create a second draft as a reply to _same_ message. If you click "Reply" and then click "Reply All" from the dropdown, the participants on the first draft message should be updated as the correct reply-all participants, but nothing else altered about the draft.

Similar behavior should happen with choosing to forward a message. If there is already a draft in reply to that message, it's participants and subject line should be replaced with those of a forward draft. In the forward case, the body should remain the same to preserve anything the user had typed.

Note that multiple drafts should indeed be allowed if they are replies to _different_ messages.

Gmail is the reference implementation of this behavior.

**Comment by bengotow** [comment]
I think it used to work this way and we changed it? Can't remember why..

**Comment by grinich** [comment]
Huh, I don't remember that but you might be right. Could been from the era when we only allowed a single draft on a thread.

I think we should do it the Gmail way regardless.

**Comment by bengotow** [comment]
Ok — in Google Inbox you can only have one /empty/ reply to a message at once. As soon as you type anything, pressing the Reply button allows you to create another one. I'm going to make both the button and the Cmd-R shortcut work this way.

**Comment by bengotow** [comment]
Also appears that pressing Forward /always/ creates a new message in Google Inbox. Intending to copy that behavior too.

**Comment by bengotow** [comment]
Adressed in c265cf0dfac24801e0dd7d11aba3a58f91a807a9

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
