### ISSUE TITLE
Drafts should be shown with "unfocused" state for non-active windows

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1695]
![image](https://cloud.githubusercontent.com/assets/92417/13737990/ba4f43c2-e97e-11e5-9b09-861fdd718c8d.png)

should be triggered to this state when the window becomes inactive: 

![image](https://cloud.githubusercontent.com/assets/92417/13737992/c267fa04-e97e-11e5-84fa-f27205266b48.png)

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
