### ISSUE TITLE
First account setting textbox should become focused

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1696]
<img width="351" alt="screenshot_3_14_16__12_51_am" src="https://cloud.githubusercontent.com/assets/92417/13738017/fa6e7f18-e97e-11e5-8b2b-be6d24b7c0a2.png">

**Comment by djevrek** [comment]
also on next screen (imap/pop3), focus should be on first textbox, in this case server IP/address

**Comment by bengotow** [comment]
This should be fixed by 9aba847a92932180b61d11303db35926c22f955b

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
