### ISSUE TITLE
updated menu bar icons

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1698]
Original assets available in Dropbox > Design > Desktop Client > Current Masters > Assets > Menu Bar

- [x] Use `MenuItem-Inbox-Full` if there are > 0 messages in the inbox folder.
- [x] Show this as blue in the menu bar if new mail has been received since the last time the app was in the foreground.
- [x] Use `MenuItem-Inbox-Zero` if there are no messages in the inbox. This will obviously never be blue.

**Comment by jstejada** [comment]
landed in https://github.com/nylas/N1/commit/ded7c20fba0d78447f535f249b8876b8fcb1abe4

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!

**Comment by Eldorado234** [comment]
Hey. I see that the new icons are a lot more obvious in showing the current state of the inbox. On the other hand they look quite generic IMHO and have no relation to N1. Liked the old ones better. Just my two cents.

Cheers
