### ISSUE TITLE
Send from Gmail support.

### ISSUE THREAD

**Issue by bilby91** [nylas/N1#170]
Any plan on adding `send from` feature that gmail has ?

Thanks! N1 is awesome!

**Comment by andreaolivato** [comment]
+1 really useful if you have multiple aliases in a single account

**Comment by bilby91** [comment]
Is this something that can be implemented on N1 ?

Martín

@bilby91

**Comment by imlazyone** [comment]
:+1: really need this!

**Comment by notsu** [comment]
:+1: need this too!  

I had been using that feature in everyday and hope to see this in N1 :smile:

**Comment by coagmano** [comment]
:+1:

**Comment by grinich** [comment]
these are also known as "Aliases" and they're coming soon! :)

**Comment by dbpolito** [comment]
Looking forward to this too... GREAT JOB on this app btw, looking awesome!

**Comment by bengotow** [comment]
Hey! Thanks for your interesting N1—this is on the roadmap, feel free to upvote it over here if you have a Trello account: https://trello.com/c/KO2UHr0i/24-send-using-aliases

**Comment by jstejada** [comment]
referencing #414
