### ISSUE TITLE
Capital file extensions break preview icon detector

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1700]
These should actually be case insensitive. JPEG isn't different from jpg. Example using DOCX vs docx: 

![image](https://cloud.githubusercontent.com/assets/92417/13738222/7f1d8582-e980-11e5-80b8-a46733e46bf4.png)

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
