### ISSUE TITLE
Add forward button to bottom of message list where large reply button is

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1703]
<img width="645" alt="show_number_of_messages_in_thread_as_small_box_with_number_instead_of_ _3_ __similar_to_the_sourcelist_unread_count_ _issue__1702_ _nylas_n1" src="https://cloud.githubusercontent.com/assets/92417/13738433/3a868c1e-e982-11e5-9a21-506bfcf72640.png">

Get design asset from SDW.

**Comment by bengotow** [comment]
@sdewith

**Comment by sdewith** [comment]
Makes no sense to have a forward button in the reply text area. We have a forward button at the top of the message, where it is attached to the message. The 'write a reply' area is basically inline with where the new composer is created.
