### ISSUE TITLE
Add emoji picker button to composer footer

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1706]
<img width="583" alt="screenshot_3_14_16__1_21_am" src="https://cloud.githubusercontent.com/assets/92417/13738575/307a6244-e983-11e5-89bf-fb8ca6c828fe.png">

Similar to the fantastic one that Slack has implemented. 

![image](https://cloud.githubusercontent.com/assets/92417/13738594/46cceeae-e983-11e5-9991-7dfa7e83f688.png)

**Comment by bengotow** [comment]
I still think this should go in a separate bar, because the bottom bar is all actions on the draft, not actions on the text (bold, underline, etc.) @sdewith do you have any thoughts?

**Comment by grinich** [comment]
I see this not so much as an action on the text, but a content insertion. Similar to inserting an attachment.

**Comment by sdewith** [comment]
Agreed that it should be down there -- the icon has already been designed for it. For point-insertion, it can also be in the content style popup. 

This'll need design -- I'll do some research on current standard pickers, but for now let's begin to implement and have it open the system standard picker.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
