### ISSUE TITLE
Deprecate interface scaling mode

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1707]
Would be useful to have in a config file somewhere though. (I use it for taking large screenshots.)

<img width="514" alt="investigate_spell_checking_in_all_available_languages_all_the_time_ _issue__1392_ _nylas_n1" src="https://cloud.githubusercontent.com/assets/92417/13738671/c97c2e8c-e983-11e5-8ae7-4fb3fb1dc4dd.png">

**Comment by bengotow** [comment]
This has landed in dbf3610c884540a9a7734f1a9252c7855f0b61d8

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
