### ISSUE TITLE
Prompt to move to applications folder if launched elsewhere on Mac

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1708]
Example: 

<img width="580" alt="screen shot 2016-02-23 at 1 52 38 pm" src="https://cloud.githubusercontent.com/assets/92417/13738762/5c42b5b0-e984-11e5-8a23-dc7d56dd5717.png">

This is definitely a good idea!

**Comment by emorikawa** [comment]
I'm merging this into the much more serious issue of using the DMG here: https://github.com/nylas/N1/issues/1708

**Comment by grinich** [comment]
@emorikawa what issue? You just linked to this one...

**Comment by jackiehluo** [comment]
I think https://github.com/nylas/N1/issues/826?

**Comment by emorikawa** [comment]
We no longer serve the .dmg file. Mac users are instead given a .zip. See https://github.com/nylas/edgehill-server/commit/33d20c0ca1a24ffa254f90cee816aeee5991da60

For users that have already launched from the .dmg, we now automatically move to `/Applications`. See https://github.com/nylas/N1/commit/5231b4f556be1f31340cd07f26f037eb456a98d9

Users who unzip inside of `~/Downloads` (or anywhere else) will now get prompted to move N1 inside of `/Applications`. See https://github.com/nylas/N1/commit/5231b4f556be1f31340cd07f26f037eb456a98d9
