### ISSUE TITLE
Reply From ( alias ) address receiving message.

### ISSUE THREAD

**Issue by digitalextremist** [nylas/N1#1709]
When I receive a message on one of my aliases, then reply -- the default alias for the account is used, not the address of the alias which received the message.

The correct behavior, in my opinion, would be to check if an alias exists with the address `TO:` or `CC:` or `BCC` contains, and if so, reply from that address by default.

If multiple aliases with the same address exist, then also compare the name as well as the address given, or default to the first matching alias address.

If no alias address exists on the account... *then* and only then use the default alias for the account.

**Comment by jstejada** [comment]
Hi @digitalextremist , thanks for reporting this, I'm going to merge into duplicate #800

**Comment by digitalextremist** [comment]
Ah, thanks -- I looked for a duplicate beforehand and evidently missed it.
