### ISSUE TITLE
Add view mode switches to menu bar

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1710]
![image](https://cloud.githubusercontent.com/assets/92417/13738795/924f6a04-e984-11e5-8cac-cba777692455.png)

Should have options to switch to single-pane mode or dual-pane mode.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
