### ISSUE TITLE
Add account option in menu switcher

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1711]
Insert "Add Account..." option above "Manage Accounts..."

Several reports from users who can't figure out what tiny button they need to click to add an account.

![image](https://cloud.githubusercontent.com/assets/92417/13738925/34eecafc-e985-11e5-9c17-bf5c1aef0600.png)

**Comment by jstejada** [comment]
https://github.com/nylas/N1/commit/06d7c05aa8d138d02f745600096188014789f7db

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
