### ISSUE TITLE
Smaller show quoted text button

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1712]
Current: 

![image](https://cloud.githubusercontent.com/assets/92417/13739009/ce34d29c-e985-11e5-8da0-4cd6c4bab084.png)

Remove the "Show previous" text and change the following CSS attribute
```
.quoted-text-control {
    padding: 1px 4px;
    letter-spacing: 1px;
}
```

So it looks like this:

![image](https://cloud.githubusercontent.com/assets/92417/13739159/bbda9c98-e986-11e5-9315-cc340281566b.png)

Include the words "Show quoted text" as a tooltip on the button.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
