### ISSUE TITLE
Add default signature for newly added accounts

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1713]
![image](https://cloud.githubusercontent.com/assets/92417/13739225/3808fc4c-e987-11e5-831f-769057556819.png)

Link to `https://nylas.com/n1?ref=n1`

**Comment by bengotow** [comment]
https://phab.nylas.com/D2735

**Comment by bengotow** [comment]
Landed in cff2f71d18268b27d71d337a3ff04c693528f12a.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
