### ISSUE TITLE
Two-finger swipe to go back

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1714]
Add two finger swipe right here to go back to the main view. Similar to Chrome.

![image](https://cloud.githubusercontent.com/assets/92417/13739276/7c2465f6-e987-11e5-9abe-afdadc92a8fc.png)

Make sure it work with emails that are wide enough they cause horizontal scrolling in this window.

**Comment by bengotow** [comment]
[Internal: to do this right we need to refactor the way sheets are managed in N1 so the animation is controlled by Javascript and not done in CSS, so the sheet can track the gesture.]
