### ISSUE TITLE
UI shows "Nothing to display" when search times out

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1719]
Should say something much more instructive and also retry! 

<img width="562" alt="screen shot 2016-03-14 at 10 27 54 am" src="https://cloud.githubusercontent.com/assets/92417/13753261/764533ca-e9cf-11e5-9e69-7c64bdb68384.png">

**Comment by olivierlacan** [comment]
I'm seeing similar issues with simple search terms that should return matches (and do in Airmail).

**Comment by jstejada** [comment]
related to #750

**Comment by jstejada** [comment]
addressed in https://github.com/nylas/N1/commit/e56f866551c12e4e195380849061d28384d0b689

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
