### ISSUE TITLE
Sentry Error: QuerySubscription: Applied all changes and result set contains duplicate IDs.

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#1720]
Still getting a large number of reports of this error on Sentry, and is probably corrupting result sets and causing UI issues like: #1523, #1385, #1451, #1740, #1862

**Comment by bengotow** [comment]
This should be taken care of now! At least, we're seeing very few occurrences of this in 0.4.25.

**Comment by rawjam** [comment]
I seem to be getting these messages quite frequently
<img width="783" alt="screen shot 2016-06-30 at 21 48 57" src="https://cloud.githubusercontent.com/assets/95224/16503770/7e432d42-3f0c-11e6-9e50-00a787869c18.png">
. Screenshot attached...
