### ISSUE TITLE
Move 'Next / Previous Thread' arrows to be grouped with thread controls rather than sidebar

### ISSUE THREAD

**Issue by sdewith** [nylas/N1#1721]
In single-pane view, the  'Next / Previous Message' arrows are grouped with the sidebar button rather than the buttons that control the thread (archive, trash, etc.) 

![screen shot 2016-03-14 at 10 58 46 am](https://cloud.githubusercontent.com/assets/13399516/13754310/be0266de-e9d3-11e5-8570-a67cb2bf8af6.png)

Move them here:

![screen shot 2016-03-14 at 10 59 01 am](https://cloud.githubusercontent.com/assets/13399516/13754339/dd1a7aac-e9d3-11e5-9677-c09c4b4d22a7.png)

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
