### ISSUE TITLE
Can't reply on a thread while a message is sending.

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1722]
It removes the bottom large "Reply" button as well as the top right reply/reply-all/fwd buttons

**Comment by bengotow** [comment]
You actually can reply, you just can't reply to the last message. I'm not sure what the expected behavior is here. Shortcuts should still work, along with clicking Reply on a message in the thread which is not sending?

**Comment by grinich** [comment]
I want to be able to reply to the last message on the thread i.e. the one I just sent





On Mon, Mar 14, 2016 at 5:08 PM -0700, "Ben Gotow" <notifications@github.com<mailto:notifications@github.com>> wrote:


You actually can reply, you just can't reply to the last message. I'm not sure what the expected behavior is here. Shortcuts should still work, along with clicking Reply on a message in the thread which is not sending?

-

**Comment by bengotow** [comment]
Hmm... we should really consider moving to a model where the sync-engine accepts client-assigned message IDs. It's going to be a bit of a mess to allow messages to be `in reply to` not-yet-sent messages. Doable, but unnecessarily shitty.
