### ISSUE TITLE
Wrong Unread count

### ISSUE THREAD

**Issue by natarius** [nylas/N1#1723]
As you can see in the screenshot, I am getting a false unread message count.

![screen shot 2016-03-14 at 11 46 34 am](https://cloud.githubusercontent.com/assets/607331/13755953/d649f30e-e9da-11e5-8cf4-6cbd35bd38d3.png)

I already tried to restart N1 and reconnect the affected account but the count is still wrong :(

**Comment by jackiehluo** [comment]
Hey! Going to merge this issue into #759.
