### ISSUE TITLE
N1 version 0.4.14 does not update/refresh email notifications. 

### ISSUE THREAD

**Issue by sarasibylle** [nylas/N1#1725]
Hi,

Ever since i updated to N1 Version 0.4.14-53cd69b my email notifications do not update. So if I've deleted or read an email, the notification number does not change. I've tried refreshing and restarting the software multiple times to no success. I can't find any new emails marked with the blue circle either even when the notification is stuck on a number (such as 7 new emails)

I'm using OSX 10.11 (OSX El Capitan).
I don't have any third-party plugins installed with it, it's pretty much a stock N1 update. 

Thanks! 
![n1 - notifications dont update](https://cloud.githubusercontent.com/assets/17835704/13757844/cdcc7522-e9fc-11e5-8617-c9fbb9964c8a.png)

**Comment by jackiehluo** [comment]
I think this issue is the same one as #759! Merging it into there.
