### ISSUE TITLE
Cannot quit the Nylas N1 application

### ISSUE THREAD

**Issue by RichoHan** [nylas/N1#173]
When I try to quit the application, it stuck (both from the menu and using "cmd + Q").
Here's my OS version: OS X El Capitan (10.11.1).
I installed the application when I got my invitation code, and the error happened when I tried to quit the application after received the update notification.  

I've found the error messages, here they are:
```
2015/10/24 上午11:37:59.508 Nylas[31400]: Error: Calling a callback of released renderer view
  at BrowserWindow.ret (/Applications/Nylas N1.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:97:21)
  at emitOne (events.js:77:13)
  at BrowserWindow.emit (events.js:169:7)
```
```
2015/10/24 上午11:38:15.784 Nylas[31400]: ErrorReporter: Shipping Logs. Exception occurred
```
```
2015/10/24 上午11:38:16.233 Nylas[31400]: Running log ship: /var/folders/7w/cm3sj3f535520tmrg9y3vfch0000gn/T/, edgehill-31400[.0-9]*.log$
```
```
2015/10/24 上午11:42:55.443 Nylas[31400]: Skipping update check... update ready to install, or updater unavailable.
```
```
2015/10/24 上午11:50:40.957 Nylas[31400]: Error: Object has been destroyed
  at Error (native)
  at AtomWindow.module.exports.AtomWindow.isMinimized (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/atom-window.js:359:33)
  at WindowManager.showMainWindow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/window-manager.js:101:30)
  at Application.module.exports.Application.openWindowsForTokenState (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/application.js:219:28)
  at Application.openWindowsForTokenState (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/application.js:3:61)
  at EventEmitter.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/application.js:511:17)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)
```

**Comment by RichoHan** [comment]
After I force quit the application and restarted(update) it, the application works fine now.

**Comment by tung-dang** [comment]
I have the same problem. It always happens every time I open the app. Therefore, I must kill process of this app to force it close completely.

**Comment by shawnzvinis** [comment]
Also experiencing this on Mac OS 10.11.1.

**Comment by lukehefson** [comment]
> After I force quit the application and restarted(update) it, the application works fine now.

Same. This happened to me on initial launch, but then after a force quit, relaunching and quitting is working as it should.

**Comment by joeellis** [comment]
Experiencing this on 10.10.4 as well

**Comment by hmaesta** [comment]
Same here. 
<img width="564" alt="screen shot 2015-10-27 at 13 42 06" src="https://cloud.githubusercontent.com/assets/741969/10769390/e95afad6-7ccc-11e5-9382-f25d1c62ed08.png">

**Comment by sean-hill** [comment]
Experiencing this as well, just downloaded the app a few minutes ago.

**Comment by amonshiz** [comment]
Same.

**Comment by bengotow** [comment]
Hey folks—thanks for filing this. This is by far the most common error coming in to our error collection system. We've contributed a small patch back to Electron to make this issue easier to debug and we'll be collecting reports in the next release which will allow us to resolve the issue.

**Comment by RichoHan** [comment]
Great! :+1:

**Comment by fallenpegasus** [comment]
Still happening.

**Comment by plingampally** [comment]
Can confirm that this is still happening. 
N1 Version: 0.3.27 
OSX 10.10.5

**Comment by MariusMasalar** [comment]
Still seeing this on OS X 10.11.2 as well, N1 version 0.3.29.

**Comment by mbilker** [comment]
Is this issue still present under N1 0.3.32?

**Comment by MariusMasalar** [comment]
Not for me, no.

**Comment by mbilker** [comment]
Closing this issue since it may be fixed in recent versions.
