### ISSUE TITLE
Automatic linking doesn't work properly

### ISSUE THREAD

**Issue by jackiehluo** [nylas/N1#1733]
Weirdness with links, probably because we switched from Autolinker. Some detected links (i.e., the links to diffs on Phabricator) aren't clickable, even though they look like they should be, and some arbitrary strings are detected as links.

<img width="457" alt="screen shot 2016-03-14 at 8 33 13 pm" src="https://cloud.githubusercontent.com/assets/8452682/13767052/4f3dae24-ea24-11e5-9d3b-c05dd48907b4.png">

Here, the first link will launch `%20spacings-sub-double.` in Chrome, and the second goes to `%20sure.`.

**Comment by bengotow** [comment]
Whoa that's super weird! Let's look at this tomorrow...

**Comment by bengotow** [comment]
Fixed in 92e8a2a7d47504195cb2a2f24f825bd83852a3d1

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
