### ISSUE TITLE
Local IMAP with STARTTLS and Self signed certificate

### ISSUE THREAD

**Issue by abides** [nylas/N1#1735]
Hello,

Im using n1 0.4.14 on windows. I have a local mail server. When i try to connect my local server via imap using Thunderbird its detect 143 port for IMAP with STARTTLS and 587 port SMTP with STARTTLS then its ask "Confirm Security Exception" for Self Signed Certificate and then its add account without problem. It works.

When i try to add this account to N1 its timeout without any more detailed information about why.

I can give you more details but i don't know where can i see that.

Best regards

**Comment by bengotow** [comment]
Hi @abides—when you say "local", do you mean on your local network? N1 is cloud based and requires that the sync engine be able to reach the mail server at the domain / IP address you provide.

**Comment by abides** [comment]
OH! i believe i totally missed that point. I just think i can use it like thunderbird.

You mean N1 need internet and its backend working on the cloud and need to connect my local server from internet? which is not possible because my local mail server does not allow connection from outside.

Then you can easily close this issue because its not even an issue :) Since i use it for my yandex email and its work like a charm.

Best regards.

**Comment by bengotow** [comment]
Hey! Yep that's correct :-) N1 is more like Mailbox where it offloads some sync logic to the cloud - we also use backend services to implement snooze / send later, etc. Sorry for the confusion!
