### ISSUE TITLE
Telephone highlighting misses first number

### ISSUE THREAD

**Issue by fatherb** [nylas/N1#1736]
First number of a phone number is not highlighted in an html email. eg.  0333 320 1030  - in this case the 0 is not part of the phone link, so obviously won't work when clicked.

I'd attach a screenshot to show you but no idea how to. 

Thanks for taking the time to file an issue! If you have general question or a problem with your email account, take a quick look at the N1 Knowledge Base to see if you question is addressed there:

https://support.nylas.com/hc/en-us/sections/203638587-N1_

Our team tries to respond to all GitHub issues. To make sure your issue is
actionable, try to include the following information:

- Are there any related issues? Try searching for both open and closed issues here: https://github.com/nylas/N1/issues?q=is%3Aissue. Keep in mind that email features are often described differently on different platforms. (Conversations == threads, shortcuts == hotkeys, etc.)

- What operating system are you using?

- What version of N1 are you using?

**Bug?**
- Do you have any third-party plugins installed?

- Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

- Is the issue reproducible with a particular attachment, message, signature, etc?
   Try to provide an example as a file attachment or a screenshot.

**Feature Request?**
- Does this feature exist in another mail client or tool you use?

**Comment by bengotow** [comment]
Hey! It looks like this is working on master following a bunch of changes we made on Friday to the way we linkify content in emails. Should be fixed in the next release!

Just to make sure, I've added another test case with more phone-related tests: 84b9741fa6d8a5b93da3ed0e0005bd99b5380dfb

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
