### ISSUE TITLE
Can't send any message with SMTP

### ISSUE THREAD

**Issue by Alcarendor** [nylas/N1#1737]
I am using Linux (Ubuntu 15.10) and a IMAP/SMTP mail. The mail is properly synchronized, but i can't send nothing, an error appears always: 

> Sorry, this message could not be sent. Please try again, and make sure your message is addressed correctly and is not too large.

Even if I wrote an empty mail with one character. 

I'm not using any third party plugin and the version of N1 is 0.4.14-53cd69b

**Comment by bengotow** [comment]
Hi @Alcarendor — can you send an email to `support@nylas.com` and include the email address you're having trouble with? Once we've got the right email address we can load logs off our backend to figure out what's going on. Thanks!

**Comment by jeromecovington** [comment]
I'm having this issue too, sending support email.
