### ISSUE TITLE
HTML formatting of reply and forward quoted text

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1746]
Right now we indent the quoted text along with the "On X wrote.." line like so. 

![image](https://cloud.githubusercontent.com/assets/92417/13788517/41fa39fc-ea9d-11e5-8140-c472b0d3b587.png)

We should not quote the line we are adding. Here's how it shows in Gmail.

![image](https://cloud.githubusercontent.com/assets/92417/13788498/30a6a4e2-ea9d-11e5-8e42-182627fb3b41.png)

We should also not quote the HTML when it is forwarded. This screws up a lot of formatting in HTML messages.

![image](https://cloud.githubusercontent.com/assets/92417/13788434/f89867f2-ea9c-11e5-96d8-1b1a150dc4d0.png)

Versus Gmail: 

![image](https://cloud.githubusercontent.com/assets/92417/13788480/1f3c4a7c-ea9d-11e5-9ed8-fd37f680d74e.png)

**Comment by bengotow** [comment]
Haha this was actually just changed because of a ticket complaining that the On:... line was /not/ included in quoted text. We'll juts need to do it conditionally.

**Comment by grinich** [comment]
What ticket? I haven't found another mail app with that behavior.

**Comment by bengotow** [comment]
https://github.com/nylas/N1/issues/1312

**Comment by grinich** [comment]
Ah I see. I guess the problem here is that we're wrapping the quoted text using the blockquote or similar. The [... Show previous] button should be above the non-indented "On Tues, Mar 15..."

**Comment by bengotow** [comment]
Will be fixed in https://phab.nylas.com/D2750.
