### ISSUE TITLE
Fix atrociously misaligned app icon (OS X)

### ISSUE THREAD

**Issue by sdewith** [nylas/N1#1747]
The app icon is currently disgustingly misaligned with system standard OS X icons:

<img width="870" alt="screen shot 2016-03-15 at 10 59 08 am" src="https://cloud.githubusercontent.com/assets/13399516/13788527/4be35624-ea9d-11e5-9130-fc6c3d63d0ca.png">

This heinous deviation must be exterminated. 

Insert the new, updated App Icon.icns from the design repo in the next build.

**Comment by grinich** [comment]
![1796948_10100237151203886_723465725_o](https://cloud.githubusercontent.com/assets/92417/13792463/31027a9e-eaaf-11e5-8ed4-379f8c63eeb9.jpg)
