### ISSUE TITLE
[UI Bug/Size Provisioning] Email account doesn't fit properly in window

### ISSUE THREAD

**Issue by CameronHall** [nylas/N1#175]
Please refer to image. Perhaps replace overflow with ellipses?
![image](https://cloud.githubusercontent.com/assets/7316093/10708815/4546b984-7a61-11e5-9bc9-7a785c49d984.png)

**Comment by bengotow** [comment]
Hey Cameron—thanks for reporting this. I've pushed a fix for this in 2ddfb1595a793684b2b5f2d4b0f161df6dadc141
