### ISSUE TITLE
Active email indicator invisible

### ISSUE THREAD

**Issue by adeloscope** [nylas/N1#1751]
OS X 10.11.3
Version 0.4.14-53cd69b (0.4.14-53cd69b)

Gmail shortcuts set to on.  (been using this in past versions)

j/k shortcut seems to work.  Selected email can be changed, and then 'x' shortcut (for example) can be used to select.  But there is no indicator as to which email is selected (that I can see...)

**Comment by jackiehluo** [comment]
@adeloscope Which theme are you using?

**Comment by adeloscope** [comment]
good call.  N1-Taiga.  Changed themes and it shows.

**Comment by jackiehluo** [comment]
Interesting... Even on Taiga, you should be able to see the selected email. What does it look like for you?

Here's it on mine:

<img width="304" alt="screen shot 2016-03-15 at 6 22 26 pm" src="https://cloud.githubusercontent.com/assets/8452682/13799255/e94a85a8-eada-11e5-9040-1c91d19bc91e.png">

**Comment by bengotow** [comment]
Hey @jackiehluo this one might be referring to thin blue marker that is used in list mode. 

![image](https://cloud.githubusercontent.com/assets/1037212/13889242/b9518f02-ed02-11e5-98bd-1420e60ca41f.png)

It looks like it's hidden in Taiga, which is super strange...

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
