### ISSUE TITLE
Hidden composer area when replying to message in trash

### ISSUE THREAD

**Issue by jmfederico** [nylas/N1#1759]
When in the trash folder and replying to a conversation that has been sent to the trash, the composer area is hidden under the "There is one more message in this thread that is not spam or trash".
One has to click the "Show all messages" to be able to write the response.

How to reproduce:
Go to your trash, select any conversation and click the reply button.

Cheers

- What operating system are you using?
OSX 10.11.3 (15D21)

- What version of N1 are you using?
Version 0.4.14-53cd69b (0.4.14-53cd69b)

- Do you have any third-party plugins installed?
No

- Email provider?
Gmail

**Comment by bengotow** [comment]
Closing as a dup of #2026
