### ISSUE TITLE
[Feature request] Proxy Support

### ISSUE THREAD

**Issue by JinweiClarkChao** [nylas/N1#176]
It seems N1 does not support proxy settings now, but in some cases it would be a great feature. Since the app is built on Electron, I don't know the best way to add proxy, but socks5 or http would either be great.

**Comment by buhe** [comment]
yeah!
It is very usefully for fxxk GFW.

**Comment by JinweiClarkChao** [comment]
It seems this issue is similar to https://github.com/nylas/N1/issues/104

**Comment by edwinyzh** [comment]
Please! Please!

**Comment by bengotow** [comment]
Merging into #104
