### ISSUE TITLE
Bug: deleted mail goes back to folder where are applied mail rules

### ISSUE THREAD

**Issue by erichstark** [nylas/N1#1761]
Hello,

At first here is my spec:
OS: MAC OS X 10.11.3
N1: 0.4.14-53cd69b (0.4.14-53cd69b)
I dont have any plugins.

I have folder for projects and created rules for them. If I delete mail which use one of these rules it goes back to the folder after "Mail processing". I think it is a bug, because mail rules should avoid mail from deleted folder. Not sure if it is only for Exchange or problem is in Gmail too.

<img width="898" alt="screen shot 2016-03-16 at 09 50 09" src="https://cloud.githubusercontent.com/assets/1123805/13806545/8a969452-eb5c-11e5-82d8-e8c87c8b2110.png">

**Comment by bengotow** [comment]
This should be fixed in 0.4.40—we switched the behavior of "Process All" so it only processes mail currently in the Inbox. Cheers!
