### ISSUE TITLE
Feature Request: Horizontal Panels in Two Panel View

### ISSUE THREAD

**Issue by Tsmith18256** [nylas/N1#1765]
On some monitors, when emails don't fit nicely within the width of the two panel view, it is nice to be able to split the main viewing area so that the two panels are on top of each other. Having to horizontally scroll is just awkward, and shrinking the messages list panel hides message previews.

This is a feature seen in other email clients, such as Thunderbird, where you can have the list of messages at the top of the window, and the message preview at the bottom.

This is just a really old picture I found on Google images, but it shows the split screen that I am talking about:
https://static.lwn.net/images/ns/mua/mozilla/thunderbird.png

**Comment by jackiehluo** [comment]
Hey! Going to merge this issue into #461.
