### ISSUE TITLE
Handoff support on OS X?

### ISSUE THREAD

**Issue by danielbayley** [nylas/N1#1766]
I wonder if it would be possible for N1 to handle [Handoff](http://www.apple.com/uk/osx/continuity/?cid=wwa-uk-kwg-mac) instead of Apple Mail?

**Comment by mbilker** [comment]
Thanks for the suggestion @danielbayley ! That sounds interesting, but Apple designed Handoff to be supported between the same app on iOS and Mac. This does not allow for Handoff to be supported.

**Comment by bengotow** [comment]
Yep! We'd love to do this but N1 would only be able to handoff to an N1 mobile app, not other mobile apps like the official Mail.app. We may do it at some point, but it's safe to say it's a long, long way off :-). Closing for now.

**Comment by koenpunt** [comment]
> but N1 would only be able to handoff to an N1 mobile app

@bengotow I don't think this is true, e.g. Chrome on my Mac has handoff in both ways to Safari on my iPhone. So I expect this to be possible with emailclients too.

**Comment by koenpunt** [comment]
Further investigation tells me that `NSUserActivityTypeBrowsingWeb` is a special type, whereas such a type doesn't exist for mail.

**Comment by koenpunt** [comment]
However, from Nylas to a device might work by using the `message://` URL scheme.
