### ISSUE TITLE
Visual bug with phishing detection plugin

### ISSUE THREAD

**Issue by Cilusse** [nylas/N1#1767]
Hello N1 team!

First of all thank you for your awesome app, I really appreciate it, it changed my email life ^^

I just want to report a little visual bug which is simple : the phishing detection plugin doesn't support long email addresses in his warning notification. Nothing dangerous because it's working fine anyway.

Look at the screenshots to better understand :)

![screen shot 2016-03-16 at 20 41 20](https://cloud.githubusercontent.com/assets/17030645/13826763/6c1ab7c6-ebb9-11e5-893f-a8a139596b9b.png)
![screen shot 2016-03-16 at 20 18 49](https://cloud.githubusercontent.com/assets/17030645/13826770/74c26c48-ebb9-11e5-9186-313408fc379d.png)

As you can see, the second email address is off-screen.

OS : Mac OS X 10.11.3 El Capitan
N1 version : 0.4.14-53cd69b
Plugin incriminated : Phishing detection
Bug showing on every mail provider

Yours,

**Comment by Eldorado234** [comment]
Hey Cilusse,

thanks for reporting (even though I'm not maintaining this repo). I fixed this bug with PR https://github.com/nylas/N1/pull/1648.

Cheers

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
