### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by ryan10876** [nylas/N1#1768]
I am using El Capitan OSX - 10.11.3 and was using Nylas N1(Version 0.4.14-53cd69b) fine, started to play around with it and in doing so, installed some themes which worked until I installed the Material theme which when i tried activating, hadn't appeared in the themes selection and caused N1 to crash, I restarted it and the below appeared, it doesn't get past the 'Loading N1...' stage. I have tried re-installing,  restarting my mac, clearing cache of the app, deleting all files attached to it be no luck.

<img width="807" alt="n1_error" src="https://cloud.githubusercontent.com/assets/17888070/13827038/79fff47a-ebb2-11e5-92e6-f10e51ea2283.png">

<img width="645" alt="n1_error_2" src="https://cloud.githubusercontent.com/assets/17888070/13827068/949bd984-ebb2-11e5-9f07-313f2511ae87.png">

**Comment by jackiehluo** [comment]
@ryan10876 Hey! Sorry about the confusion. The version of Material Theme that's on master is built around the version of N1 that's on master (not the production version), so you should delete that directory from `~/.nylas/packages` and install the [release](https://github.com/jackiehluo/n1-material/releases) of Material instead. I'll reword the instructions in that README to make it more clear. Let me know if you still have problems!
