### ISSUE TITLE
Snoozed emails don't come back into inbox at set time

### ISSUE THREAD

**Issue by flareau** [nylas/N1#1769]
I can snooze emails, but they just sit in the Snoozed folder and don't get put back into the inbox at the set time.

OS X 10.10.5, time locale French - Canada.

**Comment by jstejada** [comment]
hey @flareau , do the emails ever come back? It might be the case that there is a small delay (< 15min)
if that's not the case, let me know.
We are working on a fix to remove this delay

**Comment by flareau** [comment]
I see. Yes, after about 20 minutes it came back.

**Comment by jstejada** [comment]
thanks!

**Comment by saffad** [comment]
I've also got this issue. It has never worked for me.

**Comment by flareau** [comment]
Now snoozing doesn't work at all for me. Even days later, the snoozed emails don't come back. Things that have changed lately in my setup:

- I have Nylas configured to use the same email account on two different machines. Snoozed emails don't come back on either machine.
- My Gmail account used to be set to redirect to Inbox. I have disabled that in my Google account. I started having snooze problems with Nylas on that day.

I tried deleting the app, the .nylas folder in my home, and the one in Application Support (Mac OS X), deleting the N1-Snoozed label, and then reinstalling. It worked once, and then stopped working again.

**Comment by bengotow** [comment]
Hey folks—we've dedicated more server resources to running through the unsnooze queue and it seems to have resolved this issue. @flareau — what do you mean by "Redirect to Inbox"? I'm not sure whether that option changes the behavior of snooze (it probably shouldn't), but I haven't heard of it before.

Could you try snoozing mail again?

**Comment by flareau** [comment]
@bengotow, I meant that logging into Gmail"s website would redirect me to Google's Inbox website. I mentioned it because I noticed that when it worked, snoozed emails came back even when I wasn't using N1, so I thought you might be using some server side functionality provided by Google.

Now snoozing woks as expected. Thanks!

**Comment by saffad** [comment]
are we supposed to expect a notification for when a snoozed email returns to inbox? The snoozed mails seem to be returning fine. The menu bar icon lights up but I don't receive any notification. Is this expected?

**Comment by ceilican** [comment]
I have been experiencing this issue for a few days now... Snoozed emails are never coming back to inbox.
