### ISSUE TITLE
Swipe right archives, not deletes

### ISSUE THREAD

**Issue by samjau** [nylas/N1#1770]

**Comment by jackiehluo** [comment]
Hey! Right now, the swipe functionality is bound to what your delete key does. If you want to change it, you can go to the preferences and check the box below.

<img width="425" alt="screen shot 2016-03-16 at 4 24 00 pm" src="https://cloud.githubusercontent.com/assets/8452682/13831797/843d14fa-eb93-11e5-8d1d-2376c741abac.png">

**Comment by adambrault** [comment]
This setting's language is quite confusing given the ability to swipe. 

I think it should instead just be a toggle between "delete" and "archive" actions.

**Comment by jackiehluo** [comment]
Agreed! We'll likely change it at some point, either the language or the functionality.

**Comment by adambrault** [comment]
:+1: :heart:
