### ISSUE TITLE
Some folders / labels lack empty state graphics

### ISSUE THREAD

**Issue by sdewith** [nylas/N1#1771]
When viewing Drafts, Trash, Sent, Starred, Snoozed and Archived messages, a graphic should be displayed when there are no items to show to give the user context:

<img width="584" alt="screen shot 2016-03-16 at 5 33 17 pm" src="https://cloud.githubusercontent.com/assets/13399516/13832849/5929bf0c-eb9d-11e5-9318-295e13a6a10d.png">

Assets are in Design Repository: /Master/Assets/Empty States/

**Comment by jstejada** [comment]
addressed in https://github.com/nylas/N1/commit/e56f866551c12e4e195380849061d28384d0b689

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!
