### ISSUE TITLE
Cannot Swipe to Archive

### ISSUE THREAD

**Issue by mykecheckonetwo** [nylas/N1#1774]
Swipe right only allows me to send an email to the trash. It doesnt allow me to send an email to archive.

**Comment by jackiehluo** [comment]
@mykecheckonetwo The swipe functionality is bound to the delete key. You should be able to change this box in preferences to archive on swipe.

![image](https://cloud.githubusercontent.com/assets/8452682/13836798/36cb0d24-ebc2-11e5-9220-deea8cce0458.png)

Let me know if that doesn't work!
