### ISSUE TITLE
Ability to deselect a message

### ISSUE THREAD

**Issue by aryehdesigns** [nylas/N1#1776]
Hey N1 team,

Firstly, awesome work so far!

Have a small Feature Request: Would like the ability to deselect a message so that no message is left 'open' (in the Two-Panel layout). I like to leave important emails in my inbox, but don't want to have them open when not in use -- just a blank left panel when nothing is selected.

**Comment by bengotow** [comment]
Hey! Sorry, missed this somehow. If you want, you can actually command-click the selected email in the thread list to deselect it. (Not sure what platform you're on, but it's a Mac OS X convention.) Cheers!
