### ISSUE TITLE
UPN login does not work in N1

### ISSUE THREAD

**Issue by Fr3llD** [nylas/N1#1778]
I am working with the N1 client, but if i use my UPN name (user@domain.com instead of my domain name (domain\user), i can't make an connection because it times out. 

- I checked  on;
https://support.nylas.com/hc/en-us/sections/203638587-N1_
https://github.com/nylas/N1/issues?q=is%3Aissue. 
but no hits, so im creating an issue.
- I am on Ubuntu 15.10
- I am using the latest N1 version delivered with Ubuntu 15.10. 
- I am using Exchange 2016. 
- The issue is reproducable on my system.

**Comment by jackiehluo** [comment]
Not sure what the exact issue is—closing for now, but send us an email if it's still a problem.

**Comment by Fr3llD** [comment]
Huh? So tell me what you want to know more about this issue, i thaught i made it clear.

Everywhere we use upn names so i would like this issue resolved.

Met vriendelijke groet,
Regards,
Dennis.

Verzonden vanaf een mobiele telefoon.

On 1 Oct 2016, at 07:00, Jackie Luo <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what the exact issue is-closing for now, but send us an email if it's still a problem.

-
