### ISSUE TITLE
Message count glitched after deleting a message while offline

### ISSUE THREAD

**Issue by steelbrain** [nylas/N1#1780]
I marked a message as read while N1 was disconnected from the internet. I thought it wasn't working so I tried deleting the message, deletion worked but even after reconnecting to the internet now the `1` in unread count is not going away. Any ideas how can I debug this further?

#### Are there any related issues?
No

#### What operating system are you using?

Mac OS X

#### What version of N1 are you using?
0.4.14-53cd69b

**Bug?**
#### Do you have any third-party plugins installed?
No

#### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only use GMail not sure if it's specific to it

#### Is the issue reproducible with a particular attachment, message, signature, etc?
See the top of the bug report

**Comment by mbilker** [comment]
This should be fixed by fe5b75b32a8c9096603feb95c0e38bf243645e2f and recent changes to the Sync Engine

**Comment by steelbrain** [comment]
Great, can't wait for the release

**Comment by steelbrain** [comment]
I just got an update that fixed thanks. Thanks everyone
