### ISSUE TITLE
Phising detection should check email case insensitive

### ISSUE THREAD

**Issue by ariefbayu** [nylas/N1#1784]
Take a look at this screenshot.
<img width="822" alt="phising" src="https://cloud.githubusercontent.com/assets/55084/13871987/8b4f2684-ed19-11e5-8fc6-c97d0939be2d.png">

**Comment by bengotow** [comment]
Fixed in ead866fc065eafab159cb43ae831d11e76e10275

**Comment by jackiehluo** [comment]
We've pushed an update that resolves this issue (0.4.51). Let us know if you run into any bugs!
