### ISSUE TITLE
Swipe to archive "bounces back" and then removes after a delay.

### ISSUE THREAD

**Issue by howardroark** [nylas/N1#1786]
I find that on occasion when I swipe emails to archive them they "bounce back" into place and don't remove themselves until after a delay.  Sometimes they don't ever remove themselves.  If I restart the application this behaviour goes away and it acts as expected.

##### What operating system are you using?
OSX

##### What version of N1 are you using?
0.4.14-53cd69b

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly, it's a gmail account.

**Comment by jackiehluo** [comment]
Hey! Thanks for reporting. Looks like it's the same issue as #1385, so merging it into there!

**Comment by bengotow** [comment]
Hey! Going to re-open this. It sounds like something is causing access to N1's sqlite database to be sluggish. Possible that initial sync was still running, maybe?

**Comment by howardroark** [comment]
Not really sure. There was a time delay of many seconds for each one.

**Comment by jackiehluo** [comment]
Merging into #781!
