### ISSUE TITLE
Labels duplicating and not syncing

### ISSUE THREAD

**Issue by shawnzvinis** [nylas/N1#179]
Gmail labels with accents or non-standard characters are being duplicated and not syncing with what is actually in Gmail. Also, some emails are being distributed among these labels (i.e. some emails are in one format of the same label and others are in another format of the same label).

<img width="210" alt="screen shot 2015-10-24 at 10 57 07" src="https://cloud.githubusercontent.com/assets/5586373/10710058/2f314628-7a3e-11e5-8fcb-a5b415a5c6a0.png">

**Comment by shawnzvinis** [comment]
Actually, I've been trying to debug this further. It appears that it is all Gmail labels. If you change a label in Gmail, N1 sees it as a new label completely. There are two issues: 1) characters are not being escaped properly and 2) labels do not have a GUID and/or are treated only as strings.

**Comment by jeejkang** [comment]
:+1: I have the same issue, deleted labels are showing up and not going away. Having control in the app to delete or add label would be great!

**Comment by shawnzvinis** [comment]
@jeejkang I'm not sure if that's the right approach for now. N1 should just sync with whatever mail protocol you're using, so the bug needs to be solved first. But, yes, two-way control would be nice.

**Comment by bengotow** [comment]
Hey folks! Our backend team has fixed these issues (labels with special characters were duplicated, and renaming labels also duplicated them) , but you may need to remove and re-add your account from N1 for the duplicate labels to be deleted. Enjoy!

**Comment by Israphel** [comment]
deb package is updated often or it's the same?
