### ISSUE TITLE
One-click download for all attachments in an email 

### ISSUE THREAD

**Issue by ahmedsaoudi** [nylas/N1#1792]
Sometimes I receive emails with multiple attachments to them that I want to download easily (without having to click the overlay arrow-button every time.). 

In Gmail, they have a "download all attachments" button that lets you get all the files in a zipped format. 

Can we get this in N1 too? 

Thanks!

**Comment by bengotow** [comment]
Thanks for filing this! We're actually working on this next week :-). Closing as dup of #905
