### ISSUE TITLE
GoogleInbox -> Inbox by Gmail

### ISSUE THREAD

**Issue by grinich** [nylas/N1#1796]
![image](https://cloud.githubusercontent.com/assets/92417/13900240/e7be7ce4-edbe-11e5-8adc-a1d59d0b5417.png)

I think we should also change Gmail -> Gmail Classic

**Comment by rittbys** [comment]
Where is this menu?

**Comment by grinich** [comment]
In the setup "tour" screens before adding your first account.

**Comment by bengotow** [comment]
How on earth did that get in there... @rittbys if you want to fix it, I think those options are drawn from the file names in keymaps/templates/

**Comment by rittbys** [comment]
Is GoogleInbox.cson not used anywhere else? I couldn't find any trace of it.

**Comment by bengotow** [comment]
Hey! There may be a few users who have chosen it as their preset, and changing the name of it will unfortunately reset the keymappings for them. I think if we change the filename to `Inbox by Google`, that's probably enough, but it might also be nice to put a short-term patch into https://github.com/nylas/N1/blob/master/src/keymap-manager.coffee#L35 that would change the GoogleInbox preset to "Inbox by Google" and re-save the config setting with the new value. We could remove that after a release or two :-)

**Comment by rittbys** [comment]
#1808

**Comment by bengotow** [comment]
This has been landed.
