### ISSUE TITLE
Don't revert failed API requests, enqueue them and retry until successful

### ISSUE THREAD

**Issue by kg4lod** [nylas/N1#1801]
Jsteder wrote: "If you take a look at our tasks, e.g. ChangeMailTask, performLocal immediately saves the changes to the database, which in turn triggers and re renders the UI. When performRemote completes, it will revert those changes if the request fails."

This makes the entire premise of Nylas worthless (e.g. it won't work offline). If I have to be online with a very stable connection, why not just use Gmail (or other webmail)?

You should handle offline, delayed, or errored calls the way other email programs handle it -- they enqueue and retry when you come back online, and keep retrying until successful or manually resolved (cleared by user, reverted by user, etc). This feature is usually called "outbox".

**Comment by jstejada** [comment]
Hi @kg4lod , thanks for the comments! We indeed do this. If you check the code for the some of the tasks or the task queue, we handle different type of API failures, like permanent (e.g. incorrect input, or forbidden actions) and non permanent errors, and resolve our Tasks accordingly: e.g. `Task.Status.Failed`, `Task.Status.Retry`. If a task resolves with a status of Retry, for example when you are offline, the task will continue retrying until it succeeds.

Let me know if this helps!
