### ISSUE TITLE
Mail rules for archiving doesn't work

### ISSUE THREAD

**Issue by purezen** [nylas/N1#1802]
##### Are there any related issues?

https://github.com/nylas/N1/issues/1074

##### What operating system are you using?
Mac OS X El Capital

##### What version of N1 are you using?
Version 0.4.16-8cb7748 (0.4.16-8cb7748)

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I am using Gmail. Don't know about others.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screen shot 2016-03-21 at 6 14 00 pm](https://cloud.githubusercontent.com/assets/3036093/13919259/71fe5abc-ef92-11e5-9839-872ce96de61d.png)

**Feature Request?**
No

##### Does this feature exist in another mail client or tool you use?
Yes.

**Comment by bengotow** [comment]
Hi @purezen — you may need to change that first dropdown from "If All of the conditions are met" to "If Any..." Cheers!

**Comment by purezen** [comment]
Ah, that works! :+1:
