### ISSUE TITLE
Multiple accounts issue

### ISSUE THREAD

**Issue by taniadaniela** [nylas/N1#1806]
I'm using N1 0.4.16-8cb7748 with 2 gmail accounts and everytime I open the client I just see the emails of one of them until I hit preferences -> accounts and there the emails appear. I'm not using any third party plugins.

**Comment by jackiehluo** [comment]
Hey, @taniadaniela! Thanks for reporting. Do you think it might be the same issue as #1587?

**Comment by taniadaniela** [comment]
@jackiehluo ohh yes is the same..

**Comment by jackiehluo** [comment]
Cool, merging into that!
