### ISSUE TITLE
Allow "background opening" of links while holding system-default modifier key (cmd/ctrl)

### ISSUE THREAD

**Issue by thephilipjones** [nylas/N1#181]
Most clients (that I'm familiar with, mostly on OS X) allow a link to be opened in the background (i.e. without switching application focus to the browser) while browsing an email full of links. Seems like a good idea to me!

**Comment by bengotow** [comment]
Hey! This is a great idea. I've opened a ticket on Electron (https://github.com/atom/electron/issues/3224) and I'll see if we can build support for this soon.

**Comment by thephilipjones** [comment]
Great, thanks

**Comment by koenpunt** [comment]
@grinich ping! [@atom/electron](https://github.com/atom/electron) does now have support for it :) And I've created a PR: #1637

**Comment by arturogh** [comment]
+1
