### ISSUE TITLE
[Feature-Request] Signature Switcher

### ISSUE THREAD

**Issue by TheRojam** [nylas/N1#1812]
I have many identities on one account i would like to change the signature by choosing an id.
at the moment i can't do this.

**Comment by jstejada** [comment]
Hi rojam, do you mean you want to have a signature per alias? If so, this is a duplicate of #848

**Comment by TheRojam** [comment]
@jstejada in outlook you can switch signatures while you write a mail this is a feature i like to have it.
#848 could also be a option. :) :+1:

**Comment by jstejada** [comment]
oh I see, what does this feature look like? could you send a screenshot?

**Comment by knireis** [comment]
+1

**Comment by bengotow** [comment]
Merging into https://github.com/nylas/N1/issues/1047!
