### ISSUE TITLE
Duplicate Messages on Exchange

### ISSUE THREAD

**Issue by brandondeweese** [nylas/N1#1813]
Every message is coming through twice. see attached.
<img width="688" alt="screen shot 2016-03-22 at 4 45 59 pm" src="https://cloud.githubusercontent.com/assets/18017918/13971452/9f30abfa-f04d-11e5-8979-cf625cdd9fc6.png">

**Comment by jstejada** [comment]
Hi @brandondeweese , thanks for reporting this, I'm merging into duplicate issue #117 
Thanks!

**Comment by jstejada** [comment]
Hi @brandondeweese , thanks for reporting this. This is actually a different issue from #117. Do you have any more details about how the messages got duplicated? thanks!

**Comment by khamidou** [comment]
@brandondeweese Can you email support@nylas.com with the email address you're seeing this? It would be super helpful to debug this issue. 

Thanks!

**Comment by brandondeweese** [comment]
brandon@iriscreative.co


[http://iriscreative.co/img/iris-icon.png]<http://iriscreative.co>
Brandon DeWeese . principal
740 572 2274 . brandon@iriscreative.co

On Mar 23 2016, at 10:41 am, Karim Hamidou <notifications@github.com> wrote:

@brandondeweese<https://github.com/brandondeweese> Can you email support@nylas.com<mailto:support@nylas.com> with the email address you're seeing this? It would be super helpful to debug this issue.

Thanks!

**Comment by jstejada** [comment]
merging into duplicate #1734
