### ISSUE TITLE
Spellcheck breaks on åäö characters

### ISSUE THREAD

**Issue by OskarWastensson** [nylas/N1#1814]
When I type in a word containing the characters å, ä, ö, spellchecker marks the portion of the word following the character as misspelled. Just the wavy line - no spell suggestions or other effects on changes in the contextual menu. 

##### Are there any related issues?
Couldn't find any..

##### What operating system are you using?
OSX El Capitan - 10.11.3 (15D21)

##### What version of N1 are you using?
Version 0.4.16-8cb7748 (0.4.16-8cb7748)

##### Do you have any third-party plugins installed?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so, but all my accounts are on Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Happens anytime I compose a message

**Comment by jstejada** [comment]
Hi @OskarWastensson thanks for reporting this. I'm merging into larger spellcheck issue: #1392
