### ISSUE TITLE
no trash option, only archive (for one gmail account)

### ISSUE THREAD

**Issue by annalee07** [nylas/N1#1815]
Hi,

I just downloaded Nylas and have 3 Gmail accounts that I use -- but while Trash and Archive work perfectly on 2 of them, the third one only archives and even after archiving stays in my inbox. Is this a bug or is there someone who might know how to fix this? I'm on Windows 10 Pro.

Any help would be greatly appreciated -- thank you!
Cheers,
Anna

**Comment by jstejada** [comment]
Hi @annalee07, thanks for reporting this. This seems to be the same issue as #872, so I'm merging it in. Can you email support@nylas.com with the email address you're seeing this? It would be super helpful to debug this issue.

Thanks!
