### ISSUE TITLE
Move/Add folders inside other folders - Feature Request

### ISSUE THREAD

**Issue by andyjh07** [nylas/N1#1816]
**Feature Request?**
Outlook and probably every other email client out there allow folders to be dragged and dropped into other folders. Is it possible for us to have this in N1 as it seems like quite a basic requirement, or at least a way to add folders inside folders?

Andy

**Comment by jstejada** [comment]
hey @andyjh07 , thanks for reporting this! I'm merging into duplicate issue: #1243
