### ISSUE TITLE
Creating "~" in home on load

### ISSUE THREAD

**Issue by simontong** [nylas/N1#1817]
Whenever I load up N1 it creates a folder "~" in my home directory.

##### What operating system are you using?
Ubuntu 15.10

##### What version of N1 are you using?
N1-0.4.16

**Comment by mbilker** [comment]
On Linux, a tilde ("~") character references the home directory. It does create the `.nylas` folder in home directory.

**Comment by simontong** [comment]
Yes "~" does represent home but it is actually creating it as a directory IN home.so you could go to "/home/simon/~"

**Comment by bengotow** [comment]
Hmm that's really strange - I don't think we've seen that one before... Is there anything else unique about your setup? You aren't overriding NYLAS_HOME right?

**Comment by mbilker** [comment]
From my experience, running a command like `OVERRIDDEN_VAR="~" ./command` causes `OVERRIDDEN_VAR` to be `~` not `/home/user` like one would expect. If you are overriding the `NYLAS_HOME` variable from an issue from N1 0.3.x, I recommend you remove the override.

**Comment by simontong** [comment]
Nope, I'm not overridding NYLAS_HOME

**Comment by simontong** [comment]
I just realised I had set:
npm config set prefix "~/.npm-global" 

so it was my bad.

You can close this ticket.

**Comment by mbilker** [comment]
Wow that is a weird issue, but N1 uses `npm` internally through `apm` so this makes sense.
