### ISSUE TITLE
Search Fails To Retrive 

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#1818]
##### Are there any related issues?

...

##### What operating system are you using? MAC 10.3.11
...

##### What version of N1 are you using?  0.4.16-8cb7748 (0.4.16-8cb7748)...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? Zoho, Fastmail, Gmail
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? No!
...

**Comment by oldhickory30** [comment]
I as well as others have reported this in the past, not sure if it's been resolved.
However I have three different mail providers and unable to retrieve any valid results when I search.  This is really becoming challenging to say the least, typically I have to switch to a different client or login to my web version to run a search! With all the great features, the fact that Nylas is open source, why is something so fundamental, so difficult to resolve?

**Comment by entreprenik2** [comment]
iCloud, Gmail, and GApps here. Search failing is the norm rather than the exception. The silliest thing is that I can see an email from Etsy in my unified inbox, search for 'etsy', and after 10 seconds of loading - no results.

**Comment by bengotow** [comment]
Hey folks! We're working on some IMAP search issues and thing should be improved in the latest release (0.4.19). Among other things, we're also waiting longer now. It turns out that for some search queries (especially on Exchange), 10 seconds is actually too short! Stay tuned... definitely something we're looking to completely overhaul this summer...

**Comment by jstejada** [comment]
hey everyone, I'm merging into duplicate #750
