### ISSUE TITLE
Move thread bewteen gmail accounts

### ISSUE THREAD

**Issue by dariosm** [nylas/N1#1819]
Before I start digging into this, I was wondering if there are any limitations or requirements to develop a plugin to make possible moving/copying emails/threads between two different gmail accounts.

**Comment by bengotow** [comment]
Hey! Unfortunately there's a hard limitation with the sync-engine project that prevents objects from being moved between accounts. I believe it's because IMAP allows you to create / delete items from folders arbitrarily, but Exchange does not. Sorry for the hassle!

**Comment by dariosm** [comment]
Thanks for your answer. It's better to know the limitation you've mentioned, rather than wasting time trying something that won't ever work (given the current sync-engine limitations). Hope this gets some improvements in the future.

**Comment by alloylab** [comment]
I had high hopes for nylas... until I saw this.... this is a disappointing limitation and I think this is going to be a sticking point for many that look at migrating to nylas. Guess I am back to Outlook.

**Comment by adriaanmol** [comment]
This is indeed a basic Mail client feature I'm also missing.
