### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by varlesh** [nylas/N1#1821]
Antergos x86_64 Gnome 3.18 (Archlinux packages)
n1  0.4.14
n1  0.4.16
No plugins installed.

Please see video bug preview:
https://youtu.be/aZB44j3IIY0

Logs attached.
[logs.zip](https://github.com/nylas/N1/files/188729/logs.zip)

**Comment by bengotow** [comment]
Hmm that's no good - looks like you've run into #1529 - going to merge this into that.
