### ISSUE TITLE
[UI UX]Suggestion : the inbox button in the manage account view needs to be brighter in DarkSide Theme (its otherwise almost invisible)

### ISSUE THREAD

**Issue by dHRUSHIT** [nylas/N1#1823]
##### Are there any related issues?

...Do not think so. I searched with keyword "inbox button"

##### What operating system are you using?
...
Windows
##### What version of N1 are you using?
...
Latest
--

**Bug?**
##### Do you have any third-party plugins installed?
...No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...Totally

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...Not Really

**Comment by jackiehluo** [comment]
Hey, @dHRUSHIT! If you mean the preferences view, @jamiewilson's already fixed that, and it'll be out this release.

**Comment by dHRUSHIT** [comment]
Hi Jackie,

Thanks for the quick reply.

Actually just as I submitted the issue, I got notified about the latest 4.16 version. So I installed it after submitting.

However, it is not showing any change in 4.16 version(just installed). Do I have to restart the computer for the changes to occur?

Herewith I have attached a screenshot. Hope it helps =)
On Mar 25 2016, at 10:44 am, Jackie Luo <notifications@github.com> wrote:

Hey, @dHRUSHIT<https://github.com/dHRUSHIT>! If you mean the preferences view, @jamiewilson<https://github.com/jamiewilson>'s already fixed that, and it'll be out this release.

**Comment by jackiehluo** [comment]
@dHRUSHIT It's not in the production build yet, but it's done! You should expect to see it super soon when we push the next update to everyone.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from the menu or download the new version directly from the releases section of the project. Enjoy!

**Comment by dHRUSHIT** [comment]
Hey Ben,

Is it an issue that the UI elements(icons) in linux do not appear properly every time but always does in windows?

On Mar 26 2016, at 5:08 am, Ben Gotow <notifications@github.com> wrote:

Closed #1823<https://github.com/nylas/N1/issues/1823>.
