### ISSUE TITLE
Make menu bar icon on OSX white when selected

### ISSUE THREAD

**Issue by michalkopanski** [nylas/N1#1824]
##### What operating system are you using?
OSX 10.11.3

##### What version of N1 are you using?
0.4.16-8cb7748

--

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![](http://kpnsk.me/fWMz/Image%202016-03-25%20at%205.47.06%20AM.png)
![](http://kpnsk.me/fWOG/Screen%20Shot%202016-03-25%20at%206.01.49%20AM.png)

**Comment by jstejada** [comment]
related to #1396 and #588

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. I've submitted a patch to Electron to fix this (https://github.com/atom/electron/pull/4924) and we'll get it released as soon as that's merged.

**Comment by jackiehluo** [comment]
That happens now! Whoo.
