### ISSUE TITLE
Latest version (0.4.19) still not synching correctly

### ISSUE THREAD

**Issue by larrymcj** [nylas/N1#1827]
I try every new build, hoping this issue will be fixed, but it's still not. I'm using Gmail with N1 and Apple Mail and when I compare the two inboxes, N1 "always" displays three or four messages that have been recently deleted using Apple Mail. With IMAP, changes made to Gmail via any mail app should appear in other clients at least in a few minutes, but it's not happening with N1.

**Comment by ArNz8o8** [comment]
I have the same issue

**Comment by larrymcj** [comment]
I hope someone from Nylas can comment here so I can either wait for a fix or just forget about N1, which I'd hate to do. But what good is an email client that will not correctly sync with Gmail.

**Comment by jstejada** [comment]
hey @larrymcj, @ArNz8o8. Could you send us the email address of the affected account to support@nylas.com so we can take a look at what is going on?

This is the same issue as #1451 right? I'm going to merge it into that one.  

Thanks!

**Comment by larrymcj** [comment]
@jstejada, It doesn't seem like the same issue to me. If I open Apple Mail, N1 and a couple other email clients they're all displaying the exact same inbox but N1 is way different. It's not showing some messages that have been deleted and display as deleted in the other email apps. IOW it's not acting like an IMAP email client.

**Comment by Ekomak** [comment]
I have the same issue.
N1 don't sync folder and mails with mail account.
I try to check with thunderbird everything is OK
Folder and mails are sync in thunderbird and my mail provider but not in N1
