### ISSUE TITLE
Inbox Zero artwork gone

### ISSUE THREAD

**Issue by ArNz8o8** [nylas/N1#1829]
##### What operating system are you using?
OSX10.11.4

##### What version of N1 are you using?
0.4.19

--

**Bug?**
##### Do you have any third-party plugins installed?
NO

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
NO

In the changeling for 0.4.1.9 it says
Inbox Zero: Beautiful new inbox zero artwork and a refined tray icon on Mac OS X!

That inbox zero artwork worked (with the palm trees and all ) for one day... now it's gone. How?

<img width="697" alt="schermafbeelding 2016-03-27 om 08 49 27" src="https://cloud.githubusercontent.com/assets/17308965/14064186/fd2279b0-f3f8-11e5-9aea-ce72a795cc2e.png">

**Comment by ArNz8o8** [comment]
Deleting everything and reinstalling did not work..

**Comment by jstejada** [comment]
hi @ArNz8o8, thanks for reporting this! this seems to be a problem with one specific animation. The animations vary from day to day, so you should be able to see a new one tomorrow. We will push a fix for this soon anyway.

**Comment by ArNz8o8** [comment]
Thanks! Looking forward to it 😊

**Comment by ArNz8o8** [comment]
It is working today.. yes!

**Comment by ragnar321** [comment]
Just in case it's helpful in identifying which animations cause issues, I'm getting the same issue today. 0.4.19-d41e72c release, on Mac OSX 10.11.4.

**Comment by ArNz8o8** [comment]
Yep, same here :)  
  

Greetz,

Arnold

  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On apr. 1 2016, at 6:09 pm, Ragnar &lt;notifications@github.com&gt; wrote:  

> Just in case it's helpful in identifying which animations cause issues, I'm
getting the same issue today. 0.4.19-d41e72c release, on Mac OSX 10.11.4.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1829#issuecomment-204453143)![](https://github.com/notifications/beac
on/AQgdJSOURxmojZbCMndO8EBafRPIrnDNks5pzUM9gaJpZM4H5Z3R.gif)

**Comment by bengotow** [comment]
Hey folks! This has shipped in 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!
