### ISSUE TITLE
X-Windows Error under Archlinux

### ISSUE THREAD

**Issue by shibumi** [nylas/N1#183]
Hello,
I've received the following Error with N1 with archlinux:

```
The program 'electron' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 9429 error_code 2 request_code 12 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Name           : xorg-server
Version        : 1.17.2-4

I am running DWM. A tiling Windowmanager. if you need more stacktrace message me

**Comment by bengotow** [comment]
Hi @shibumi — can you look at the discussion on these issues and see if anything resolves the issue? We don't officially ship an ArchLinux build of the app, and our team may not be able to help out much.

- https://github.com/atom/atom/issues/6496
- https://github.com/atom/atom/issues/4213

**Comment by mbilker** [comment]
Are you still having issues? I use `i3` on Arch Linux and have not had any problems with mine. Is this still issue still appearing in recent version of N1?

**Comment by mbilker** [comment]
I am going to close this as N1 was updated to a newer version of Electron and I do not see this issue between many Linux distributions.
