### ISSUE TITLE
Search fails for iCloud account

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#1835]
For most searches, I receive a notice from N1 that the "search has failed for one or more accounts", and my iCloud account is shown as the account in question. The account seems to retrieve mail just fine, and I can see no other errors reported elsewhere.

Running Version 0.4.19-d41e72c (0.4.19-d41e72c) on OS X 10.11.3

**Comment by jstejada** [comment]
hi @fonnesbeck, thanks for reporting this. I'm going to merge into duplicate issue #750
