### ISSUE TITLE
Moom window management fails with N1

### ISSUE THREAD

**Issue by bbashy** [nylas/N1#1838]
##### Are there any related issues?
Not that I can see

##### What operating system are you using?
OS X 10.11.4

##### What version of N1 are you using?
Version 0.4.19-d41e72c

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

--

I'm using Moom v3.2.3 (latest) - https://manytricks.com/moom/ and it doesn't function on N1 client. Any reason why this is not working or something you can look into supporting?

**Comment by mbilker** [comment]
_I am **not** a mac user_

N1 does not use the native traffic light buttons on OS X so the mouse control using the traffic light window management icons will not work with Moom. If you use keyboard control with Moom, it should work better.

**Comment by bbashy** [comment]
@mbilker Thanks for the info. Don't really want to have to set a keyboard shortcut for it. Any good reason for the custom buttons?

**Comment by mbilker** [comment]
They have the search bar and actions in the top bar. Electron does not allow for customization outside of having a separate menu bar that makes the app lose the feel of a native application.

**Comment by bbashy** [comment]
@mbilker Thanks. Great info and didn't think of Electron.

**Comment by kevbost** [comment]
I can confirm that Moom and N1 do not play well -- however -- if I click the green button to open in full screen, then undo that, they keyboard bindings work perfectly after that. @bbashy to answer your question on why to use keyboard shortcuts because CMD+ALT+UP is a really fast way to maximize without going to full screen, etc. Almost identical to the native windows method of moving window location.

**Comment by bpartridge83** [comment]
@kevbost I found that full screen hack as well, to enable the Moom keyboard bindings. 

It seems like if the keyboard bindings work after the hack operation, then it should be possible to make the keyboard bindings work on application launch.
