### ISSUE TITLE
N1 creates a new icon in Windows Taskbar

### ISSUE THREAD

**Issue by PlugaruT** [nylas/N1#184]
![n1](https://cloud.githubusercontent.com/assets/6437932/10712771/155068ba-7aac-11e5-9c4c-02b4b597849f.PNG)
I have pinned N1 to taskbar, and I open it it appears another icon.

**Comment by mspoehr** [comment]
I have the same issue.  Kind of annoying, most likely due to the shortcut actually opening an updater which in turn opens N1.

**Comment by bengotow** [comment]
This will be fixed in the next release. Sorry for the hassle!
