### ISSUE TITLE
Medium links not appearing correctly.

### ISSUE THREAD

**Issue by arturogh** [nylas/N1#1840]
Medium links are not rendering correctly. The link stops at "Medium.com" when an "@" appears in the link.
<img width="767" alt="screen shot 2016-03-29 at 5 18 21 pm" src="https://cloud.githubusercontent.com/assets/7030831/14128078/492908b2-f5d2-11e5-885c-965bb27dc840.png">

##### What operating system are you using?
OS X El Capitan 10.11.4

##### What version of N1 are you using?
Version 0.4.19-d41e72c (0.4.19-d41e72c)

--

**Bug?**
##### Do you have any third-party plugins installed?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Attaching screenshot.

--

**Comment by jstejada** [comment]
merging into #1842

**Comment by bengotow** [comment]
Hey folks—this has been addressed in c836310fac42296be48b57870b3d3c0d75aced2b. Cheers!
