### ISSUE TITLE
Links don't display correctly in message (e.g. Twitter, Medium) (Autolinker)

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#1842]
![image](https://cloud.githubusercontent.com/assets/547354/14129682/1e1b1b56-f5e1-11e5-824d-239308649e64.png)

likely others?

**Comment by KevinMartin** [comment]
Similar to #1840

**Comment by jstejada** [comment]
hey guys, thanks for reporting this. I'm merging #1840 into this one and renaming it. We'll look into it

**Comment by arturogh** [comment]
Great! Thanks guys!

**Comment by koterpillar** [comment]
HTTP links with port in them don't link correctly either, e.g. http://example.com:8080/path/ only links http://example.com.

**Comment by bengotow** [comment]
Hey folks—thanks! I've incorporated these into new test cases and fixed our autolinker in  c836310fac42296be48b57870b3d3c0d75aced2b. Cheers!

**Comment by mscain** [comment]
I encountered a similar issue today with partial linking: https://www.example.ly/path only linked to https://www.example 
When I was composing the message, the "ly" part got underlined as a spelling error, which may be related

**Comment by bengotow** [comment]
Hey folks! A fix for these link-parsing issues shipped in 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!
