### ISSUE TITLE
Crash message when N1 is quit from the menu bar

### ISSUE THREAD

**Issue by vikrantvm** [nylas/N1#1843]
When I quit the app from the menu bar icon, the app shuts down but I get a crash message from the system. 

```
Process:               Nylas [48786]
Path:                  /Applications/Nylas N1.app/Contents/MacOS/Nylas
Identifier:            com.nylas.nylas-mail
Version:               0.4.19-d41e72c (0.4.19-d41e72c)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Nylas [48786]
User ID:               501

Date/Time:             2016-03-29 20:50:48.020 -0700
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        FEC3443A-8AC5-9087-B71F-61B572A33E81

Sleep/Wake UUID:       3DA524A8-9BC4-4DA0-980E-834DE2BEF176

Time Awake Since Boot: 340000 seconds
Time Since Wake:       3500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x18:
--> 
    __TEXT                 000000010b6ee000-000000010b6ef000 [    4K] r-x/rwx SM=COW  /Applications/Nylas N1.app/Contents/MacOS/Nylas

Application Specific Information:
objc_msgSend() selector name: isMenuOpen

```

##### Are there any related issues?

...

##### What operating system are you using?
OSX El Capitan 10.11.4

##### What version of N1 are you using?
0.4.19-d41e72c (0.4.19-d41e72c)

--

**Bug?**
Yeah, looks like one.

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

No

##### Does this feature exist in another mail client or tool you use?
...

**Comment by vikrantvm** [comment]
I still get this problem on the updated version. Hope to see it fixed soon?

**Comment by jackiehluo** [comment]
Closing this issue for now since there haven't been any reports—let us know if that still happens!
