### ISSUE TITLE
Search not looking in message body

### ISSUE THREAD

**Issue by mharding7va** [nylas/N1#1846]
##### What operating system are you using?
OSX 10.11.3

##### What version of N1 are you using?
0.4.19-d41e72c

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

The search feature only search the email address for the search text.  I search for words and names in the email body the they are NOT found.

**Comment by jstejada** [comment]
Hi @mharding7va , thanks for reporting this. I'm going to reference our the maim search issue #750, but I'm leaving this open since it's slightly different. We are working on adding client side search and several backend search improvements which will hopefully make search better. Thanks!

**Comment by jstejada** [comment]
merging into #750
