### ISSUE TITLE
Swipe gestures not working after touchscreen calibration

### ISSUE THREAD

**Issue by baydam** [nylas/N1#1848]
##### Are there any related issues?

No

##### What operating system are you using?
Archlinux

##### What version of N1 are you using?
0.4.19

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Any

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Thanks for filing an issue. In order for our team to investigate and fix this, we'll need a bit more information. Were gestures working before? Are gestures working in other apps? Have you restarted your computer since calibration?
