### ISSUE TITLE
Can't undo while editing signature

### ISSUE THREAD

**Issue by subhankar94** [nylas/N1#1850]
##### Are there any related issues?

Can't find any

##### What operating system are you using?
Mac OS X 10.11.3 

##### What version of N1 are you using?
(0.4.19-d41e72c)

--

**Bug?**

I tried pasting text into the signature box and was unable to undo using either the keyboard shortcut or from the menu

##### Do you have any third-party plugins installed?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes
...

**Comment by bengotow** [comment]
Closing as dup of #940
