### ISSUE TITLE
Emoji popup is mostly empty

### ISSUE THREAD

**Issue by reflog** [nylas/N1#1851]
![image](https://cloud.githubusercontent.com/assets/109876/14169213/4093c17a-f72f-11e5-91ee-2ad37283b0d2.png)

Console has the following errors:

`Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/AppData/Local/nylas/app-0.4.19/resources/app.asar/static/images/composer-emoji/missing-emoji/flag-yt.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/AppData/Local/nylas/app-0.4.19/resources/app.asar/static/images/composer-emoji/missing-emoji/flag-za.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/AppData/Local/nylas/app-0.4.19/resources/app.asar/static/images/composer-emoji/missing-emoji/flag-zm.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/AppData/Local/nylas/app-0.4.19/resources/app.asar/static/images/composer-emoji/missing-emoji/flag-zw.png Failed to load resource: net::ERR_FILE_NOT_FOUND
`

##### What operating system are you using?

Windows

##### What version of N1 are you using?
0.4.19

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
On all messages

**Comment by jackiehluo** [comment]
Hey! Thanks for reporting. This issue should be fixed on master already, and you'll see it in the next release. The main issue is just that the emoji render differently on all operating systems, so we're thinking of better way to implement them.

**Comment by reflog** [comment]
Superb, thanks!
Eagerly awaiting the release

**Comment by orschiro** [comment]
Dear all, 

Will this problem be fixed in the next Linux release as well?

I can reproduce the same issue on Ubuntu Linux.

Thankfully,

~Robert
![smiley](https://cloud.githubusercontent.com/assets/170947/14468874/2e4dcfb2-00e2-11e6-8a3c-ad99698efc66.png)
