### ISSUE TITLE
Broken embedded images on Windows

### ISSUE THREAD

**Issue by reflog** [nylas/N1#1853]
Every embedded image is shown as a broken icon.

Console has the following errors:

`
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/.nylas/downloads/3ie9ge8lcnx9p5fw7aokrpxux/image002.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/.nylas/downloads/76ls9scbgyiv394652rwr7yxj/image003.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/.nylas/downloads/97x8h9trl0ebtwupv894km14v/image004.png Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/reflo/.nylas/downloads/90lum2htkbjj1v47gfl7wchlk/image005.png Failed to load resource: net::ERR_FILE_NOT_FOUND
C:\Users\reflo\AppData\Local\nylas\app-0.4.19\resources\app.asar\src\nylas-env.js:318 Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at Error (native)
    at HTMLImageElement.<anonymous> (C:\Users\reflo\AppData\Local\nylas\app-0.4.19\resources\app.asar\src\components\evented-iframe.js:324:39)
`

##### What operating system are you using?

Windows

##### What version of N1 are you using?
0.4.19

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
On all messages

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. If you move away from the thread and then go back, to the images load the second time? I think this is actually https://github.com/nylas/N1/commit/d49c205dc8d3b057c37cda32f614be48cc31c556, which we fixed this morning.

**Comment by reflog** [comment]
Yup. Second time it shows ok. Good catch, thanks!
