### ISSUE TITLE
Not receiving emails

### ISSUE THREAD

**Issue by Kashura** [nylas/N1#1854]
##### Are there any related issues?

...

##### What operating system are you using?
OSX 10.11.4

##### What version of N1 are you using?
Version 0.4.19-d41e72c (0.4.19-d41e72c)

**Bug?**
I received an email to a Gmail for work account, from another Gmail for work account, and I can see it in my Gmail and in my Outlook for iPhone app, however it does not appear in Nylas at all. This is the first time I have seen it happen. 

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure

**Comment by bengotow** [comment]
Hey! Thanks for reporting this — can you send an email to `support@nylas.com` and include the email address you're having trouble with? Our sync team can take a look—

Cheers—

Ben

**Comment by SreckoM** [comment]
I am having same issue on Ubuntu. Three gmail accounts, and two are not receiving emails. Was working when installed and it just stopped at some point. BTW love Nylas :dancer:

**Comment by ftudisco** [comment]
I have the same problem with ubutnu 16. It was working and suddenly stopped. I am not receiving emails on my gmail account on nylas.
