### ISSUE TITLE
Icon for Attachments

### ISSUE THREAD

**Issue by orky** [nylas/N1#1858]
##### What operating system are you using?
Mac OS X 10.11.3 (15D21)

##### What version of N1 are you using?
Version 0.4.19-d41e72c (0.4.19-d41e72c)

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I would like to see if attachments are provided in the email while viewing the list of emails in the Single Panel view.

**Comment by bengotow** [comment]
Hey @orky thanks for reporting this. It looks like this is a regression. We'll get this fixed ASAP.

**Comment by bengotow** [comment]
Hey! This has shipped in 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!

**Comment by orky** [comment]
Looks great. Nice job!
