### ISSUE TITLE
Download Attachments Design Enhancements

### ISSUE THREAD

**Issue by orky** [nylas/N1#1859]
##### Are there any related issues?

...

##### What operating system are you using?
...
Mac OS X 10.11.3 (15D21)

##### What version of N1 are you using?

Version 0.4.19-d41e72c (0.4.19-d41e72c)

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

When downloading attachments, the button says "Open" but it should say "Save". Also I should have the option to add "New Folder" in the download dialog box.

**Comment by jackiehluo** [comment]
This issue's been fixed on Electron! 🎉
