### ISSUE TITLE
Removing right bar

### ISSUE THREAD

**Issue by cangoktas** [nylas/N1#186]
After opening an e-mail, a right bar appears with sender information. I think it's useless (at least for me) and it takes so much space. There should be an option to remove it.

**Comment by bengotow** [comment]
Hey! It's definitely not for everyone, but a lot of plugins add things
there. You can actually remove it by clicking the small icon in the very
far right of the top toolbar. In the next update, your choice will be
remembered through restart.

**Comment by cangoktas** [comment]
Ohh sorry for that, I've mistaken for that button to switch to gmail-ish layout. That's fine now. You guys rock.
