### ISSUE TITLE
N1 is comically small on OS X

### ISSUE THREAD

**Issue by jerzygangi** [nylas/N1#1860]
##### What operating system are you using?
OS X El Capitan 10.11.3 (15D21)

##### What version of N1 are you using?
Version 0.4.19-d41e72c (0.4.19-d41e72c)

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

##### Description of bug
In the latest update to N1, the UI has become comically small on OS X. The entire N1 window appears to be at 1/2 or 3/4 size. I am attaching a screenshot for review. 

<img width="1680" alt="screen shot 2016-04-02 at 11 19 11 am" src="https://cloud.githubusercontent.com/assets/1406581/14228299/7af7c234-f8c5-11e5-8993-4320cd5d83ba.png">

**Comment by jackiehluo** [comment]
Thanks for reporting, @jerzygangi! I'm not sure I understand the issue. Is resizing by dragging on the window edges not working to make it bigger for you?

**Comment by jerzygangi** [comment]
It's not the size of the window that's the problem, it's the size of the content. Look at the size of the menu bar (where the 3 red, yellow, and green circles are), compared with safari. Everything in the N1 window is half sized. If I had to guess, it's a retina display issue.

**Comment by jerzygangi** [comment]
Look at the size of the N1 window -- the menu bar, the fonts, the buttons -- with the other OS X applications.

<img width="1920" alt="compare n1 with other windows in picture" src="https://cloud.githubusercontent.com/assets/1406581/14229337/fbaf24c4-f8e5-11e5-8905-2f4237189986.png">

**Comment by jackiehluo** [comment]
Ahhh, got it, the interface scaling is off. Could you check in `~/.nylas/config.cson` to see if there's a value for the `interfaceZoom` under `core.workspace`?

**Comment by jerzygangi** [comment]
Yes, the value was 0.8. I took a guess and changed it to 1.0, and now everything looks normal again.

This happened when I upgraded N1 a few weeks ago. I don't use N1 very often, so I didn't notice right away.

Thanks for your help @jackiehluo

**Comment by jackiehluo** [comment]
@jerzygangi Great, glad it worked! Strange... there's no reason the update should have changed that, but we'll keep an eye on it.

**Comment by rmcsharry** [comment]
I just noticed that ~/.nylas/config.json no longer has interfaceZoom entry after a clean install? Was it removed and is it okay for me to add it back so I can scale the UI up?
