### ISSUE TITLE
Open mailto links?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1864]
Dear all, 

Clicking on mailto links does not open a new compose window but only brings the main window to the front. 

Would it be possible to open a new compose window if one clicks on a mailto link?

Thankfully,

~Robert

**Comment by twonth** [comment]
Seconded. This appears to be the same issue reported as https://github.com/nylas/N1/issues/403

**Comment by reflog** [comment]
For me it currently opens GMail :)

**Comment by orschiro** [comment]
Dear @twonth,

  

Thanks for referencing #403!

  

I will follow this thread.

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 5 2016, at 4:10 pm, Eli Yukelzon &lt;notifications@github.com&gt;
wrote:  

> For me it currently opens GMail :)

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1864#issuecomment-205826862)![](https://github.com/notifications/beac
on/AAKbw6CSSNokKjNYWxcAFDaBBusdCMSfks5p0m1HgaJpZM4H-h0A.gif)

**Comment by jstejada** [comment]
hi everyone, merging into #403
