### ISSUE TITLE
Change downloading inline images to opt in, is now opt out

### ISSUE THREAD

**Issue by schlypel** [nylas/N1#1865]
This is more of a feature request/change request.

I did a search and it did not turn up an issue about this, if this intended to be this way (which i dont hope) feel free to "wont fix" it.

I'm on Linux/Ubuntu and used version v0.36.7.

---

After installing and setting up an account with nylus N1 the first mail on top of my list was opened and it  was spam, and as it did load the images directly it confirmed me reading the mail / the existence of my address.

I did find a setting to disable this behaviour, but i think it should be something to enable rather then have to disable it.

To make this more user friendly, it could be set on opening the first mail with embedded stuff (little bar on top), something like "this mail has embeded images, showing them leaks private information, but might be prettyier, shall i show them? yes|no|always|never

**Comment by bengotow** [comment]
Hi @schlypel — I think this preference may do what you want: 
![image](https://cloud.githubusercontent.com/assets/1037212/14333363/2ddb9ed0-fc03-11e5-954b-b61e101e70e7.png)

If you disable it, N1 will prompt you like this when you view an email:

![image](https://cloud.githubusercontent.com/assets/1037212/14333369/37cf0fe4-fc03-11e5-96dd-0475107f7552.png)

Feel free to re-open if I misunderstood.
