### ISSUE TITLE
No load - Linux

### ISSUE THREAD

**Issue by franlinux** [nylas/N1#1866]
N1 does not load the home screen in Antergos Gnome 3.20, any solution?

![captura de pantalla de 2016-04-03 14-02-18](https://cloud.githubusercontent.com/assets/17429459/14233660/087c9668-f9a5-11e5-8ebd-7050f8b6e806.png)

**Comment by mbilker** [comment]
Could you provide a log from Developer -> Toggle Developer Tools to see if there was an error loading N1?

**Comment by franlinux** [comment]
You mean this?

![captura de pantalla de 2016-04-04 07-30-05](https://cloud.githubusercontent.com/assets/17429459/14245376/523f1cfc-fa37-11e5-844a-1bd2c99077a6.png)

**Comment by mbilker** [comment]
Yes that. It looks like N1 is in a refresh loop. What version of N1 are you on? What version of `freetype2` do you have?

To check the version of `freetype2` do `pacman -Q freetype2`. There is a bug with Electron that causes an infinite "boot" loop with `freetype2` 2.6.3.

**Comment by franlinux** [comment]
Ok, N1 version 0.4.19 and freetype2 2.6.3-1

Any solution?

**Comment by mbilker** [comment]
Yes I do have a solution. Please follow the instructions at https://github.com/nylas/N1/issues/1529#issuecomment-201290291.

It tells how to downgrade freetype2 until N1 upgrades the Electron version.

**Comment by jstejada** [comment]
merging into #1529
