### ISSUE TITLE
Not Working Linux (Debian)

### ISSUE THREAD

**Issue by soycamiloypunto** [nylas/N1#1867]
##### Are there any related issues?

Not Working
![capturadeepin20160403134328](https://cloud.githubusercontent.com/assets/16060744/14234214/a58a0ee6-f9cc-11e5-80b7-8f9c1e79e07a.png)

##### What operating system are you using?
Debian (Unstable) -> Deepin OS 15.1.1

##### What version of N1 are you using?
0.4.19

**Bug?**
##### Do you have any third-party plugins installed?
...
NOT
I download and install. 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
Not Working: Gmail, IMAP, Outlook.

**Comment by 24mu13** [comment]
Same problem in Debian Stable.

**Comment by sidney108** [comment]
I am reporting the same issue on Debian Jessie Stable here... Gmail account created, verification seemed to have passed ok, but still wants to be verified again and again, no emails loaded or folders. The same with an IMAP account, I have tried so far...

**Comment by 24mu13** [comment]
I am thinking about some missing dependency... like keyring something... pls help

**Comment by 24mu13** [comment]
I can confirm it: install gnome-keyring and N1 works correctly.
I have this problem for 6 months: nobody from Nylas could help me. Incredible.

**Comment by msameer** [comment]
Same issue on Kubuntu 16.10

**Comment by jstejada** [comment]
hi all, sorry for the delay in getting back to you. On linux, the issue should definitely be fixed by installing `gnome-keyring` as outlined here: https://github.com/nylas/N1/issues/2062. There is also an open issue about improving messaging regarding missing Nylas IDs: #2771. Going to close this issue for now. Thanks!
