### ISSUE TITLE
Should remember which inbox to show on launch

### ISSUE THREAD

**Issue by bensk** [nylas/N1#1869]
I’d like to be able to launch to “All Accounts.”

**Comment by jackiehluo** [comment]
@bensk Interesting! It should open with the last inbox view you had when it closed. And, in any case, the unified inbox view is the default. What's happening for you?

**Comment by bensk** [comment]
It’s open to the first account configured in settings. :cry:

**Comment by jackiehluo** [comment]
And does it go back to that every time you launch, no matter where you are when you close the app?

**Comment by bensk** [comment]
Yep. I'm probably doing something dumb.

On Apr 3 2016, at 10:10 pm, Jackie Luo &lt;notifications@github.com&gt; wrote:  

> And does it go back to that every time you launch, no matter where you are
when you close the app?

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1869#issuecomment-205103519)![](https://github.com/notifications/beac
on/AHGwhB3K3PNHaQF2bMA3W5m8Hv82aHpeks5p0HMRgaJpZM4H-shx.gif)

**Comment by XNBlank** [comment]
Same thing happens here.

**Comment by jstejada** [comment]
hi everyone, I'm pretty sure this is the same issue as #1831, so I'm merging it in. Thanks for reporting it!
