### ISSUE TITLE
Compose window crashes when I try to attach a png image

### ISSUE THREAD

**Issue by dHRUSHIT** [nylas/N1#1871]
##### Are there any related issues?

...

##### What operating system are you using?
...Windows

##### What version of N1 are you using?
...0.4.19

--

**Bug?**
##### Do you have any third-party plugins installed?
...No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...I tried it with gmail and hotmail. both have the same problem

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...Yes. Go to the compose window and attach a png file(in my case 2.8MB)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
![issue-nylas-1](https://cloud.githubusercontent.com/assets/6815551/14251498/fa8fb56a-faa0-11e5-92d0-144f1e6d56d7.png)

**Comment by jackiehluo** [comment]
Hey! This issue should be fixed now, so I'm going to close it—let us know if you see it again! Thanks!
