### ISSUE TITLE
Forwarding an email exposes BCC recipients in forwarded text

### ISSUE THREAD

**Issue by markbao** [nylas/N1#1873]
1. Write an email to yourself, BCCing other people.
2. Hit forward on the sent email.
3. See that the BCC recipients are SHOWN in the forwarded message.

<img width="722" alt="banners_and_alerts" src="https://cloud.githubusercontent.com/assets/27594/14256893/022eabd8-fa69-11e5-8070-eecd65a28cd2.png">

Gmail does **not** include the BCC when forwarding on web.

##### Are there any related issues?
No

##### What operating system are you using?
OS X El Capitan 10.11.4

##### What version of N1 are you using?
Version 0.4.19-d41e72c (0.4.19-d41e72c)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

See above

**Comment by bengotow** [comment]
Hey! Ahh man good catch—thanks for reporting this. I'll throw this onto the QA stack for today's release and we'll get it fixed ASAP.

**Comment by bengotow** [comment]
Hey folks! This has shipped in 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!

**Comment by markbao** [comment]
Fantastic. Thank you for the fast turnaround!
