### ISSUE TITLE
Subjects with emojis not rendering at all

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1874]
##### Are there any related issues?
None I could dig up

##### What operating system are you using?
Arch Linux

##### What version of N1 are you using?
0.4.19
--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Received this email on Gmail  and bug is seen only there so far. I could not test it on exchange because when I forwarded it to my exchange from Gmail, the subject line is changing to add Fwd: and during that time, I think is being reformatted by google. So, that is not a reliable test. For the record, the subject showed up properly.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screenshot from 2016-04-04 13-15-13](https://cloud.githubusercontent.com/assets/2344626/14256913/14478e20-fa69-11e5-94ee-7242dd7906d6.png)

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
