### ISSUE TITLE
No download option anymore ?

### ISSUE THREAD

**Issue by ShalokShalom** [nylas/N1#188]
The Github Homepage means, that precompiled packages for Linux and OS X exist, while the download page itself seems to provide currently only a mail subscription offer.

Where can we find a list of dependencys, in order to compile by ourself, please ?

**Comment by bengotow** [comment]
Hi @ShalokShalom — you can follow the instructions on https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#getting-started to check out the repo and build N1 from source. Note that you'll also need to run your own instance of the Sync Engine (another open source project) if you haven't received an invitation code.
