### ISSUE TITLE
Account randomly unsyncs, forcing me to completely re-add account

### ISSUE THREAD

**Issue by jamesaspence** [nylas/N1#1880]
Basically, I left work last night with my email working completely fine. I was able to send / receive email promptly last night. However, on restart this morning (subsequent restarts / closes didn't resolve), my email would not sync. I was unable to send / receive emails without a full removal / recreation of my mail account through N1.

##### Are there any related issues?

https://github.com/nylas/N1/issues/1854
https://github.com/nylas/N1/issues/1627

##### What operating system are you using?
Mac OSX 10.11.3

##### What version of N1 are you using?
0.4.19-d41e72c

--

**Bug?**
##### Do you have any third-party plugins installed?
Only the ones enabled by default.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
It might be specific to GoDaddy email - I've had issues with other mail apps (stock Mail) before.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not that I've found.

--

**Comment by demizer** [comment]
I am also experiencing this problem. I have one outlook.office365.com account (IMAP) and one Gmail account. When the Office365 account has troubles, the Gmail account is in-accessible. The only remedy is to remove the Office365 account and re-add.

Thanks!

**Comment by jstejada** [comment]
hi @jamesaspence , are you still having this issue after readding your account? sorry for the hassle!

**Comment by jamesaspence** [comment]
I haven't had any issues with syncing since I re-added it. And no worries, it's been overall a pretty good experience with n1 :)

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
