### ISSUE TITLE
icon notification n1 not working in ElementaryOS 0.3.2 Freya

### ISSUE THREAD

**Issue by soycamiloypunto** [nylas/N1#1882]
##### Are there any related issues?

icon notification n1 not working in ElementaryOS 0.3.2 Freya

##### What operating system are you using?
Elementary OS Freya 0.3.2

##### What version of N1 are you using?
0.4.19

**Bug?**
##### Do you have any third-party plugins installed?
Not

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not Working 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![Uploading Captura de pantalla de 2016-04-05 12:10:20.png…]()

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Closing as a duo of #408

**Comment by xejarque** [comment]
Same problem here!, why close it as a duo? Is not the same.

In Ubuntu the n1 indicator works properly, I think that it should work in elementaryos.
