### ISSUE TITLE
URL links are not rendering as links

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#1883]
##### Are there any related issues?
Could not find any
##### What operating system are you using?
Arch Linux
##### What version of N1 are you using?
0.4.19

**Bug?**
##### Do you have any third-party plugins installed?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No. Happening on both Exchange and Gmail
##### Is the issue reproducible with a particular attachment, message, signature, etc?
URL that is failing to convert into links is:

https://store.bitdefender.com/myaccount/?e=test%40test.com&t=1457766018&h=t52tesT6tests3tesT6T2teStKR%2Ft4tesTtestT9teSTtests4eTEsTTeST%3D 

Gmail Web is properly rendering it as link. So does outlook web.

**Comment by jstejada** [comment]
hey @bashok001, thanks for reporting. I'm merging into duplicate #1842
