### ISSUE TITLE
Option to hide the sidebar?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1884]
Dear all, 

Inspired by Google Inbox, would it be possible to add an option that hides the sidebar containing the labels and make it only visible upon the click on a button, e.g. next to the compose icon in the top left?

Thankfully,

~Robert

**Comment by bengotow** [comment]
Closing as dup of #851

**Comment by orschiro** [comment]
Dear Ben,

  

Thank you for pointing me to the right resource and apologies for creating
this duplicate.

  

I will follow the other conversation!

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 5 2016, at 10:55 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Closed [#1884](https://github.com/nylas/N1/issues/1884).

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1884#event-615803450)![](https://github.com/notifications/beacon/AAKb
wwFegiXGrGz6DU6qy36maTmRH5o6ks5p0sxagaJpZM4IAVmE.gif)
