### ISSUE TITLE
Mail rules: perform action to send from <alias>

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1885]
Dear all,

Following use case:

1. I receive forwarded emails which are originally addressed to another email address
2. I don't want to reply to these emails which my default alias but another custom one
3. Thus I would need a mail rule that says: if message contains the name of my custom alias, then send my reply from this custom alias (which is added to Nylas)

Is that useful to others, too?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14296101/cc27ca22-fb78-11e5-9b18-a0de618de000.png)

**Comment by bengotow** [comment]
Hi @orschiro — in the next update, we'll auto-detect the correct alias to send a reply from, so if an email is addressed to "Ben Alias <ben@nylas.com>", N1 will automatically choose Ben Alias. I think that should resolve this!

**Comment by orschiro** [comment]
Dear @Ben,

  

That's fantastic news which will solve a bunch of problems.

  

Thank you!

  

Do you already know when you will release this version?

  

Thankfully,

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 6 2016, at 11:22 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hi [@orschiro](https://github.com/orschiro) — in the next update, we'll
auto-detect the correct alias to send a reply from, so if an email is
addressed to "Ben Alias [ben@nylas.com](mailto:ben@nylas.com)", N1 will
automatically choose Ben Alias. I think that should resolve this!

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1885#issuecomment-206575767)![](https://github.com/notifications/beac
on/AAKbw9eXlUPZC90007YyqPtXY6ssS_HSks5p1CQRgaJpZM4IAbjR.gif)

**Comment by dzek69** [comment]
>  in the next update, we'll auto-detect the correct alias to send a reply from, so if an email is addressed to "Ben Alias ben@nylas.com", N1 will automatically choose Ben Alias.

This is nice, but I'd have a small request here. **None** of available mail clients have that and this would be a best-feature-ever for me.

N1 could create an alias if it detects that I've got an e-mail on an address I don't have alias for. It should take the name for the alias from "From" header. Such action could be performed after confirmation (or by default setting maybe?) when Reply window is opened and after declining - should not ask again, BUT - it'd be great to have a button on the reply to create it if I decide to do that later.

Use cases:
I love catch-all feature, so I'm using unique e-mail addresses everywhere? Registering on a forum? New address! Telling a friend to mail you something? New address, just for him. Filling a inquiry on some company's contact form? New address! In all those use cases I'm generally first receiving a message, then writing one, so mail client would spare me that boring task of creating just-another-alias.

Please create an idea on your road map from this and also tell me what do you think (so I'd know if it's even worth dreaming about this feature)

**Comment by bengotow** [comment]
Hey folks! This has shipped in `0.4.25`, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!

(@dzek69—thanks for the feedback! I'm going to create a separate feature idea for that.)

**Comment by orschiro** [comment]
Dear @bengotow,

What great news!

If I understand your previous comment correctly, then I don't have to even create a mail rule since N1 does all the magic automatically?

Thankfully,

~Robert

**Comment by orschiro** [comment]
Dear all, 

To follow-up on this, I assume my use case is not covered yet. 

I guess what I need is the following rule possibility:

> If email contains certain keywords, then send email response from alias <x> to email <y>

For me this has to do that I receive many forwarded emails that are addressed to my primary alias. However, I don't want to respond from this primary alias but an alias that is mentioned in the forwarded email body. Moreover, this body also contains the recipient's email.

Below an excerpt from my email body:

![nimbus-image-1460664301086](https://cloud.githubusercontent.com/assets/170947/14541994/f8bcf588-028c-11e6-8b17-eb21c033eb68.png)
