### ISSUE TITLE
Feature request: separate unread count for each account

### ISSUE THREAD

**Issue by mrjhalford** [nylas/N1#1887]
I have used DockStar with Apple Mail, and it would be great to have similar functionality in N1 - the ability to display separate color coded unread counts in the menu bar for each email account. So, for example, if I have one unread email in my work account and two unread emails in my Gmail account, I could have the menu bar display a blue 1 and a red 2.

##### Are there any related issues?

...

##### What operating system are you using?
OS X Yosemite 10.10.5

##### What version of N1 are you using?
0.4.19-d41e72c

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
This feature exists in DockStar, which can be used with Apple Mail.

**Comment by bengotow** [comment]
![image](https://cloud.githubusercontent.com/assets/1037212/14308046/4f46937a-fb88-11e5-8e10-03ada61b10c5.png)

**Comment by bengotow** [comment]
Hey—thanks for filing this. I think this would be a great feature, but it's something we'd like to see implemented as a plugin rather than being part of N1 core. Going to leave it open, but tag it as a plugin idea. Cheers!

**Comment by bengotow** [comment]
Moving to https://trello.com/b/hxsqB6vx/n1-open-source-roadmap
