### ISSUE TITLE
Inbox is in all caps

### ISSUE THREAD

**Issue by typkrft** [nylas/N1#1889]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...On the left hand sidebar the Inbox folder is listed in all caps. "INBOX"

**Comment by mbilker** [comment]
This is because your IMAP provider has the Inbox stored as INBOX. This is to facilitate localization and any custom names from IMAP.

**Comment by typkrft** [comment]
http://i.imgur.com/rMGkaqL.png I don't think this is correct.
