### ISSUE TITLE
Windows 10 installation failed

### ISSUE THREAD

**Issue by zdimalm** [nylas/N1#1892]
Related to #285 ?
Tried to reinstall a working instance of N1 with a last version.
No third party plugins.

See attached log.

[SquirrelSetup.zip](https://github.com/nylas/N1/files/205958/SquirrelSetup.zip)

**Comment by mbilker** [comment]
From the log, the installer was unable to access `C:\Users\Mirek\AppData\Local\nylas\app-0.4.16` to write the necessary files for installation. Can you check to see that `C:\Users\Mirek\AppData\Local\nylas` does not exist?

**Comment by zdimalm** [comment]
OK, \nylas folder was present. Installation completed without any problems after I deleted it. Thanks for your advice. However I think the N1 install script should handle this situation in some better way.

**Comment by dubbeeh** [comment]
I've deleted the \nylas and \SquirrelTemp folders but it's still giving me an error.

**Comment by TedHawkins** [comment]
No joy on Windows 10
[SquirrelSetup.txt](https://github.com/nylas/N1/files/320256/SquirrelSetup.txt)

**Comment by jackiehluo** [comment]
Merging into https://github.com/nylas/N1/issues/2345. Probably not the same specific error, but we're investigating the Windows permissions-related installation errors as a whole.
