### ISSUE TITLE
Offline search not available

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1893]
Dear all, 

I noticed that I cannot search my emails while being offline:

![nylas-search](https://cloud.githubusercontent.com/assets/170947/14311616/7f258460-fbe8-11e5-9caa-0b890188fa79.png)

Is offline search generally not supported?

I tested this feature on Ubuntu 15.10 and Nylas 0.4.19.

Thankfully,

~Robert

**Comment by bengotow** [comment]
Hy @orschiro — this will land in the next release. Cheers!

**Comment by orschiro** [comment]
Hi Ben,

  

I sense that the next release will be a very exciting one.

  

Thanks for all your work! :-)

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 6 2016, at 11:20 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hy [@orschiro](https://github.com/orschiro) — this will land in the next
release. Cheers!

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1893#issuecomment-206574895)![](https://github.com/notifications/beac
on/AAKbw0dI67YuD8fCyXLVPbiwq9lSIaZXks5p1COCgaJpZM4IA4or.gif)

**Comment by bengotow** [comment]
Hey folks! This has shipped in `0.4.25`, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!

**Comment by orschiro** [comment]
Offline search works great. Thank you!

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 13 2016, at 2:46 am, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey folks! This has shipped in 0.4.25, which will be hitting the auto-
updaters soon. (If you want you can grab the update now on the Releases page.)
Give it a spin, and feel free to re-open if you run into the issue again.
Cheers—enjoy the update!

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1893#issuecomment-209168393)![](https://github.com/notifications/beac
on/AAKbw-_0jT-7RfOPSH4y-5j_w6p9tlx4ks5p3DzOgaJpZM4IA4or.gif)
