### ISSUE TITLE
Signature Double Line Spacing on Send

### ISSUE THREAD

**Issue by meismyles** [nylas/N1#1895]
Seem to be having an issue where there is double line spacing, i.e. a blank line between every line, in my signature.

The signature looks correct in the signatures settings area, and also when I am composing an email. Just when it is received by the recipient it has double line spacing.

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.

**Comment by Jusaus** [comment]
Having this problem on 2.0.32, nylas add extra spaces after clicking send button.
