### ISSUE TITLE
Change Password for Exchange...how?

### ISSUE THREAD

**Issue by zeg-io** [nylas/N1#1896]
##### Are there any related issues?

...

##### What operating system are you using?
OS X

##### What version of N1 are you using?
0.4.19

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...So basically, I had to change my password at work... but there wasn't an intuitive way to change the password in N1.  So I had to delete the account and add a new one with the new password! yuck.

**Comment by mbilker** [comment]
Merging into #230
