### ISSUE TITLE
Nylas N1 notifications use zenity instead of libnotify on Ubuntu 16.04

### ISSUE THREAD

**Issue by Feichtmeier** [nylas/N1#1897]
I do not know if this is intended or not but I liked the libnotify notifcations more.

I guess it is a bug so as the title says: Ubuntu 16.04 -> not libnotify notifications -> zenity notifcation pops up and a window pushes itself into the focus with a notifcation of the new mail

**Comment by bengotow** [comment]
Hi — unfortunately we currently use zenity because Electron uses it upstream. This might be what you're looking for? https://github.com/electron/electron/issues/465

**Comment by mbilker** [comment]
Zenity notifications pop up if the notification manager uses it. I use the MATE Notification Manager, which relies on Zenity. Depending on how `libnotify` processes notifications and what daemon is accepting notifications, the notification manager could use Zenity to display a notification.

Ubuntu uses `notify-osd` by default with Unity, but sometimes it can be overridden.

**Comment by CrazyLemon** [comment]
It's super annoying if you get a lot of emails. Any idea when we'll see this in N1? I think they merged those patches.

**Comment by mbilker** [comment]
@CrazyLemon I will check

**Comment by mbilker** [comment]
@CrazyLemon Try running N1 with `ELECTRON_USE_UBUNTU_NOTIFIER=1`

**Comment by CrazyLemon** [comment]
@mbilker yup that works.

**Comment by mbilker** [comment]
@CrazyLemon It overrides a check [here](https://github.com/electron/brightray/blob/bc9c496a6185e37e792c10bfc5b49ea779b27cd3/browser/linux/libnotify_notification.cc#L33).

Forces it to use a regular notification with no actions, found [here](https://github.com/electron/brightray/blob/bc9c496a6185e37e792c10bfc5b49ea779b27cd3/browser/linux/libnotify_notification.cc#L102-L104)

**Comment by Feichtmeier** [comment]
Tested and worked :) Thanks for the workaround!  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr. 18 2016, at 4:53 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

> [@CrazyLemon](https://github.com/CrazyLemon) It overrides a check [here](htt
ps://github.com/electron/brightray/blob/bc9c496a6185e37e792c10bfc5b49ea779b27c
d3/browser/linux/libnotify_notification.cc#L33).

>

> Forces it to use a regular notification with no actions, found [here](https:
//github.com/electron/brightray/blob/bc9c496a6185e37e792c10bfc5b49ea779b27cd3/
browser/linux/libnotify_notification.cc#L102-L104)

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1897#issuecomment-211413209)![](https://github.com/notifications/beac
on/AOno1iulIrVvFWGN5BIWtI-FDsnk1ny6ks5p45rQgaJpZM4IBVE-.gif)

**Comment by CrazyLemon** [comment]
Just FYI.. found a better solution and its this one https://github.com/electron/electron/issues/465#issuecomment-206582829
Why better? I didn't find a nice way to autostart N1 with that _USE_UBUNTU argument.

**Comment by bengotow** [comment]
Marking this as done-pending-release because #2050 has been addressed upstream in Electron.

**Comment by bengotow** [comment]
Hey! Thanks again—this has been shipped in `0.4.32`.
