### ISSUE TITLE
"Show sidebar" selection state not maintained after quitting the application

### ISSUE THREAD

**Issue by jadchaar** [nylas/N1#190]
Whenever I open up Nylas, I have to constantly unselect "Show sidebar" (I personally don't have a huge need for it at the moment). It would be awesome if the selection state can be maintained even after quitting and restarting the app. What I mean by this is that if someone unselects "Show sidebar" (hides sidebar), then on restart it will stay this way and not reopen the sidebar on each restart.

Thanks.

**Comment by bengotow** [comment]
Hey @jadchaar —thanks for reporting this. Looks like we forgot to persist that setting to the app's preferences. I've pushed a fix up in c7cf2f1e1861e1419d0548dcb0ec0a3f88c1dd0b, so it'll be fixed in the next update!

**Comment by jadchaar** [comment]
Thanks for the fix @bengotow!
