### ISSUE TITLE
N1 crashed & now starts as new install

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#1900]
This morning I changed:`interfaceZoom: .7` in `config.cson` cuz I changed my Windows scaling and everything seemed OK for an hour or so.  Then Windows 10 crashed, which is not common for my laptop, now when I start-up N1 it's like a new install and asking me to setup new mail accounts.

I'm not sure where you keep or how to extract the logs, so some help is needed

##### Are there any related issues?

...

##### What operating system are you using?
Windows 10 (build 10240)

##### What version of N1 are you using?
The latest release

--

**Bug?**
##### Do you have any third-party plugins installed?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
All

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No idea

--

**Comment by molstrangler** [comment]
I changed `interfaceZoom: 1` and N1 starts OK now.  It worked for a while on `.7` but maybe worth looking at.

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
