### ISSUE TITLE
Save as... PDF, HTML, plain text

### ISSUE THREAD

**Issue by rayfoss** [nylas/N1#1902]
##### Does this feature exist in another mail client or tool you use? 

Yes. This feature does exist when using the Gapps mail client online with chrome, as chrome handles the PDF generation using PDF.js.

This is a very important feature for someone I recommended N1 to. They often get emails with information they attach as a PDF to Quickbooks, but they can't generate a PDF on N1 like they can on Chrome.

**Comment by KevinMartin** [comment]
There is a print button when viewing an email. Click the print button, then choose "Save as PDF" from the dialog.

**Comment by RayFoss** [comment]
That method is quite OS dependent. She did not have a save as file button on Windows 7.

**Comment by cybertk** [comment]
+1

**Comment by jackiehluo** [comment]
Closing this issue for now—the print button is on all operating systems, and as far as I know, Windows also supports saving to PDF from printing. Saving an email as plain text is out of the scope of this project!
