### ISSUE TITLE
Show/Hide trimmed content

### ISSUE THREAD

**Issue by melkir** [nylas/N1#1906]
I have a long conversation and everything contain the list of 50 previous messages, can you add an option to hide previous messages in every mails ?

**Comment by mbilker** [comment]
N1 does already do this, but detection depends if it can recognize the format of the previous messages.

**Comment by bengotow** [comment]
Hey folks—it also depends if the messages are read or unread. N1 will collapse all the /read/ messages in the thread Gmail-style, but any unread messages are expanded. So fi you're viewing a long thread for the first time, you'll see the whole thread. Maybe this shouldn't be the default behavior?

**Comment by Kevin-Ferret** [comment]
IMO, there are 2 things : 
1. Displaying the "thread" and collapsing each individual message that was already read, Gmail-style -> this is working for me, and definitely a great thing to have.
2. Within the message, collapse all content from previous messages (see attached picture).

Is this ticket about #1 or #2 (or both) ? 
As I said, I see #1 working for me, but I am also looking for #2, so I can open that request if needed.

Thanks !
<img width="1201" alt="screen_shot_2016-04-13_at_4_51_15_pm" src="https://cloud.githubusercontent.com/assets/18296629/14512925/5b350fac-0198-11e6-89f7-5b022bd4baf2.png">

**Comment by melkir** [comment]
Thank Kevin-Ferret.
This situation occur when someone click on "reply" and doesn't remove the "trimmed content"
This functionnality is nammed "Show/Hide trimmed content" in Gmail.

**Comment by grinich** [comment]
By "trimmed" do you mean quoted?

**Comment by melkir** [comment]
I mean when you have an contact that answer with quoted mail you have this little 3 dots
![capture](https://cloud.githubusercontent.com/assets/3305685/14899948/9da3ad92-0d8e-11e6-9350-330ebc0e0722.JPG)

**Comment by bengotow** [comment]
Hey folks — N1 already implements this. I think the issue is just that for certain emails, we're unable to properly detect the content that should be trimmed / folded into the dots. There are a couple other GH issues for those cases. Cheers!
