### ISSUE TITLE
iCloud two factor auth doesn't allow Nylas to sign in

### ISSUE THREAD

**Issue by Jamesking56** [nylas/N1#1911]
Hello,

I enabled to factor authentication on my iCloud account and it cause Nylas N1 to say that it couldn't sync with my @me.com email account.

I then decided to delete and re-add the account to see if that makes a difference, I now get the error `Invalid credentials. Please check that your IMAP username and password are correct.`

My credentials are valid, Nylas just doesn't seem to support the second factor.

I'm using Mac OS X 10.11.4 and Nylas N1 0.4.19-d41e72c and I have n1-ido-master theme and n1-unsubscribe installed.

**Comment by rgruyters** [comment]
You probable need to create app specific password. This can be done on the appleid.apple.com website.

**Comment by jackiehluo** [comment]
Closing this issue—you do need an app password. Let us know if you used that and it still didn't work!
