### ISSUE TITLE
Keyboard shortcut reply all broken with Google Inbox shortcut setting

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1912]
Dear all, 

- I selected to use the keyboard shortcuts from "Google Inbox"
- I selected to use "Reply All" as the default behaviour
- However, pressing "r" does only trigger "Reply to one person" instead of all

Can someone else reproduce this?

Thankfully,

~Robert

**Comment by bengotow** [comment]
Hi @orschiro — the "Reply" vs "Reply All" setting does not change the behavior of the shortcuts (I don't think it does on Inbox either, but I'm not sure...) It only changes the defaults for buttons in the app:

![image](https://cloud.githubusercontent.com/assets/1037212/14392428/254b92ba-fd76-11e5-807f-ed55651bf9aa.png)
![image](https://cloud.githubusercontent.com/assets/1037212/14392432/2a9de376-fd76-11e5-981b-8990b8cd354b.png)

**Comment by orschiro** [comment]
Dear Ben,

  

You are absolutely right. Confusion on my side, sorry!

  

I was convinced that Inbox' default behaviour was to reply to all if hit the
"r".

  

However, since you already provide the "a" shortcut to reply to all, my
problem is solved.

  

Thanks for your help!

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 8 2016, at 7:39 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hi [@orschiro](https://github.com/orschiro) — the "Reply" vs "Reply All"
setting does not change the behavior of the shortcuts (I don't think it does
on Inbox either, but I'm not sure...) It only changes the defaults for buttons
in the app:

>

> [![image](https://cloud.githubusercontent.com/assets/1037212/14392428
/254b92ba-fd76-11e5-807f-
ed55651bf9aa.png)](https://cloud.githubusercontent.com/assets/1037212/14392428
/254b92ba-fd76-11e5-807f-ed55651bf9aa.png)  
[![image](https://cloud.githubusercontent.com/assets/1037212/14392432/2a9de376
-fd76-11e5-981b-8990b8cd354b.png)](https://cloud.githubusercontent.com/assets/
1037212/14392432/2a9de376-fd76-11e5-981b-8990b8cd354b.png)

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1912#issuecomment-207531741)![](https://github.com/notifications/beac
on/AAKbwzhJQaOgmFEer9nht_o_9VJrwMPzks5p1pLdgaJpZM4IDCrp.gif)
