### ISSUE TITLE
E-mail Not Deleting In Search Results

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#1913]
##### Are there any related issues?

Don't see anything related to what I'm seeing when searching delete search.

##### What operating system are you using?

Fedora 23

##### What version of N1 are you using?

0.4.40

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by martinoj2009** [comment]
When I search for e-mail (e.g. IGN) and select the e-mails I don't want from IGN Deals and press delete nothing happens, the e-mail stays in the list. When I drag that e-mail to the trash nothing happens. So I'm not sure if the e-mail is deleted or not.

**Comment by martinoj2009** [comment]
I did another search and I see the e-mails I tried to delete didn't delete. I selected multiple e-mails and tried to delete them. I changed the title to match what I've found.

**Comment by jstejada** [comment]
hey @martinoj2009 thanks for reporting this, I'm merging into #1888
