### ISSUE TITLE
App freezes after checking the "all mail" folder

### ISSUE THREAD

**Issue by addonis1990** [nylas/N1#1914]
I have started using Nylas N1 a few months ago but it is only now that I noticed this problem. Whenever I go to the "all mail" folder, the app shows only one mail (the most recent one) and then freezes. I still can select the other folders though but nothing happens. I had to force quit the app whenever this happens. However, when I do so and then reopen the app again, it doesn't open the inbox folder. It is goes to the draft and shows nothing (which is not the case since I have a few draft emails)

I am currently using Version 0.4.19-d41e72c (0.4.19-d41e72c) on macbook air with OS X El Capitan.

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—let us know if it's not.
