### ISSUE TITLE
Hotmail account not syncing

### ISSUE THREAD

**Issue by FerranBueno** [nylas/N1#1915]
Hi guys, as many of us, I am experiencing problems with syncing my Hotmail account. It seems my folders appear but inside the folders there's no email displayed nor in the incoming folder. For my other accounts such as Gmail and Yahoo I have not experienced any troubles so far.

I hope you guys can give me a hand solving this issue and thanks for the great program!

Cheers,

Ferran

##### Are there any related issues?

Yes, but not solved.

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.19

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Hotmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by paper9oll** [comment]
Is your issue similar to this [#1903](https://github.com/nylas/N1/issues/1903)?

**Comment by insane-dreamer** [comment]
I'm having the same problem. I can link me @live.com account without problem and it creates my folder structure, but the inbox/folders are all empty and it's not picking up any incoming box.

**Comment by dirigarays** [comment]
I do not sync hotmail accountI do not sync hotmail account

**Comment by jackiehluo** [comment]
Merging into #1868!
