### ISSUE TITLE
Not remembering learned words

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1918]
Dear all, 

Can someone else reproduce the problem that learned words not being remembered?

I tried it with the word "Wikipedia".

1. It was shown to me as being misspelled
2. I clicked on "learn spelling"
3. The red underline goes away...
4. ...but reappears as soon as I relaunch Nylas N1 and/or receive an email that contains another instance of the word "Wikipedia"

Any ideas on this issue?

The problem concerns version 0.4.19 on Ubuntu 15.10.

Thankfully,

~Robert

**Comment by jstejada** [comment]
hi @orschiro thanks for reporting this. I'm going to merge into a larger spell check issue: #1392

**Comment by orschiro** [comment]
Dear Juan,

  

I guess that reference makes sense.

  

Thank you!

  

~Robert

  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 12 2016, at 7:50 pm, Juan &lt;notifications@github.com&gt; wrote:  

> Closed [#1918](https://github.com/nylas/N1/issues/1918).

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1918#event-624543701)![](https://github.com/notifications/beacon
/AAKbw-GXbPlwBRK0dYjRD2BmC6Pu3QRaks5p29tagaJpZM4IDpES.gif)
