### ISSUE TITLE
Domains containing unicode characters

### ISSUE THREAD

**Issue by safaariman** [nylas/N1#1920]
Hello,

First of all, I really like N1 and I am using it everyday. You really did a cool e-mail client.

A few days ago, I bought a new domain which contains unicode characters (arıman.com). I added MX record to use it from Yandex.Mail service and everything was working just fine. But when I want to send an e-mail from N1 with my old e-mail account to my new e-mail address with that domain, I realized that N1 consider that e-mail address as invalid. It should handle this kind of a situation. It is just a unicode-ascii conversion work. I tried sending e-mail from Thunderbird and it was working without any problem. I wish you to add this feature as soon as possible. I have to use ascii version of the domain name now and it is kinda difficult to remember it.

Thank you.

**Comment by bengotow** [comment]
Hi @safaariman — thanks for reporting this. We currently use a regular expression to validate email addresses across our stack (both in backend processing and also in N1). It looks like validating email addresses containing unicode characters is possible but very complex, so we may try to avoid validating addresses at all. Stay tuned—

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
