### ISSUE TITLE
Coredump/Crash Loop on Startup

### ISSUE THREAD

**Issue by MrOats** [nylas/N1#1926]
N1 has been crashing repeatedly upon start up after the initial user set up the past few revisions. It results in systemd printing coredumps to the journal and N1 attempting to restart. [This is what sytemd-coredump produces.](https://gist.github.com/MrOats/2ddc1ffff9d7e4690e737170569a3b2a) 

Starting N1 from the terminal gives me this:
```
Streaming log data to /tmp/Nylas-N1-19309.log
App load time: 547ms
Gkr-Message: received an invalid, unencryptable, or non-utf8 secret
Gkr-Message: call to daemon returned an invalid response: (null).(null)()
WindowManager: Preparing a new 'composer' window
WindowManager: Preparing a new 'composer' window
```
During the WindowManager portion N1 begins to crash.

#### Please note that I have tried deleting all configurations and reinstalling the software and another user has reported the same issue.

-----

##### Are there any related issues?

N/A

##### What operating system are you using?
OS: Manjaro Linux x64-bit (Rolling-Release, Bleeding Edge distro)
Kernel version: 4.4.6-1

##### What version of N1 are you using?
Version: 0.4.19-2
[Packaged by a user on Arch User Repository](https://aur.archlinux.org/packages/n1/).
--

**Bug?**
##### Do you have any third-party plugins installed?
The ones shown from the initial set up.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't believe so.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

**Comment by zoutiyx** [comment]
Confirming that I experience this error too.

**Are there any related issues?**
N/A

**What operating system are you using?**
OS: Arch Linux
Kernel version: 4.4.6-1

**What version of N1 are you using?**
Version: 0.4.19-2

**Comment by chendaniely** [comment]
this seems like a dup of #1529 and #1579

**Comment by MrOats** [comment]
Ah, I should probably close it then. Sorry for the dupe.
