### ISSUE TITLE
[UX] The hover text on the star action reads 'Star All', even though it only affects a single thread

### ISSUE THREAD

**Issue by chiragraman** [nylas/N1#1927]
As the title suggests, the hover text on the 'Star' action button implies that it will affect multiple threads, which is not the case.

##### Are there any related issues?
None that I could find.

##### What operating system are you using?
OSX Yosemite 

##### What version of N1 are you using?
Version 0.4.19-d41e72c

**Bug?**
##### Do you have any third-party plugins installed?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?
In 2 pane view, hover on the star button above any thread.
Observe the hover text.

**Comment by bengotow** [comment]
Hey! Thanks again—this has been shipped in `0.4.32`.
