### ISSUE TITLE
Inbox doesn't refresh unless I click on "Inbox" in side panel

### ISSUE THREAD

**Issue by arpitchauhan** [nylas/N1#1928]
I use N1 0.4.19 on either Windows 10 or Ubuntu 15.10 (with all updates applied). 

I have two Google Apps mailboxes configured and use two-panel layout. When I'm reading messages in some thread and new messages arrive they don't show up in the inbox unless I click on "Inbox" in the left side panel.

I know this happens with the all inboxes in one view, not sure about other views.

**Comment by bengotow** [comment]
Hey! This should be fixed in 0.4.25. Can you try out that version and let me know if you're still having the issue?
