### ISSUE TITLE
Hotmail Account Activity

### ISSUE THREAD

**Issue by DaveFlynn** [nylas/N1#193]
I added a Hotmail account and now there is account activity from the the IP 54.187.114.34. Why is this?

![account_activity](https://cloud.githubusercontent.com/assets/128156/10720783/e678e5d2-7bd5-11e5-9525-85c449740e5d.jpg)

**Comment by bengotow** [comment]
Hey @DaveFlynn — our hosted version of the Nylas Sync Engine (http://github.com/nylas/sync-engine) runs on a private network in Amazon's Oregon data center, so you're seeing our sync worker connecting to your account. Nothing to worry about :-) If you're interested, you can read more about how we secure our cloud infrastructure here: http://nylas.com/security
