### ISSUE TITLE
Can't get out of full screen mode.

### ISSUE THREAD

**Issue by Xparx** [nylas/N1#1930]
I'm running ubuntu 15.10
nylas version 0.4.19-d41e72c

I'm currently fighting a loosing battle, and have been for some time, of trying to get out of fullscreen mode.
I went in to the menu and clicked fullscreen (or show fullscreen or whatever) and since this moment haven't been able to start nylas without it being in fullscreen. The menu to get out of fullscreen is not avilible in this mode and there is now visible button to get out of full screen (with some window acrobatics it's been possible though). 
Just now I started nylas and can't even find the menu button to get out of full screen any more, 

How do I permanently get out of full screen mode, what file do I edit?

**Comment by bengotow** [comment]
Hey! Thats no good at all... if you delete the file `~/.nylas/main-window-state.json`, it should forget it's previous size and you can launch it again. Do you know why the menu isn't visible? I'm not familiar with how full screen works on Linux unfortunately.

**Comment by Xparx** [comment]
Thanks for your quick answer.

I removed the file and it looks like it keeps me from going in to fullscreen when starting. It does also look like it is removing all window dropdown menues as well. They are not really important so I'll live for now.

About the fullscreen window.
The ubuntu unity DE has a global menu. Either you can maximise the window as on any other OS with a button in the window top boarder, which keeps the global menu visible, or for some apps, like video or image you can go full screen which places the window ontop of the global menu and fills the screen. This seems to be the function of nylas fullscreen button. To get back out of fullscreen usually I double click the window or press escape (such as in google-chrome) or something similar, however this is not working in nylas.
The other problem is that the global menu or window menu is not accessible in fullscreen mode unless alt-tabbing to another window, only then can I reach the window menu options to click out of full screen.
Not really a technical explanation but I hope it is somewhat clear enough.

I'm using the ppa for Ubuntu so not sure how up to date I am with your development, but let me know if there is some more info I can give to make these things easier to solve.

**Comment by jstejada** [comment]
this is possibly related to #1442

**Comment by Xparx** [comment]
Possibly related, yes. Although some symptoms are not relevant for me, screen resolution shouldn't matter as you can't cover the global menu with a regular window. Also Alt +drag works to move the window when not in full screen. 

I get the feeling that it's an issue with the window boarder or how the window menus are handled by ubuntu/nylon as it seems to act a bit random. Sometimes I have a developer menu and sometimes it's the regular one and currently it's no menus in the window top bar. 
Of course it might just be me. 
Again, if you need me to test something I'm happy to help.

I should also mention that I have no fullscreen toggle that I can see on the interface.

**Comment by bengotow** [comment]
Merging into #2051
