### ISSUE TITLE
Can't authenticate Fastmail account

### ISSUE THREAD

**Issue by BrianTait** [nylas/N1#1937]
I have several FastMail accounts. My primary account is working appropriately. I can't add my secondary account, even though the login credentials are correct.

See here --> http://note.io/1RRYPP3

**Comment by khamidou** [comment]
This looks like a Fastmail problem --- are you sure your fastmail account has IMAP support? (Some of them don't).

**Comment by robn** [comment]
> This looks like a Fastmail problem --- are you sure your fastmail account has IMAP support? (Some of them don't, unless you pay extra).

All FM account types have IMAP support.

**Comment by khamidou** [comment]
@robn My bad, you're right!

**Comment by BrianTait** [comment]
Any guesses fellas as to what's wrong?
 
 
On Tue, Apr 12, 2016, at 10:12 PM, Karim Hamidou wrote:
> @robn[1] My bad, you're right!
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[2]
>
 

Links:

  1. https://github.com/robn
  2. https://github.com/nylas/N1/issues/1937#issuecomment-209194275

**Comment by BrianTait** [comment]
Figured it out gents. In advanced setting for security and access at the
very bottom of the page is an a toggle for imap access. Once removed,
all was right in the world.
 
 
On Tue, Apr 12, 2016, at 10:15 PM, Brian Tait wrote:
> Any guesses fellas as to what's wrong?
>
>
> On Tue, Apr 12, 2016, at 10:12 PM, Karim Hamidou wrote:
>> @robn[1] My bad, you're right!
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub[2]
>>
>>
>
 

Links:

  1. https://github.com/robn
  2. https://github.com/nylas/N1/issues/1937#issuecomment-209194275
