### ISSUE TITLE
Apply labels - multiple selection

### ISSUE THREAD

**Issue by Cu8eR** [nylas/N1#1938]
Apply labels - multiple selection, not just one by one

**Comment by jackiehluo** [comment]
@Cu8eR You should be able to do that right now, as long as the selected emails all belong to the same email!

**Comment by bengotow** [comment]
Here's how it should work (in my case I have folders and not labels, but the UI is really similar.) Hope that helps!

[apr-13-2016 10-55-02](https://cloud.githubusercontent.com/assets/1037212/14503752/437a8e6e-0166-11e6-83d7-cc16d10e689f.gif)
