### ISSUE TITLE
Offscreen position after Getting starter

### ISSUE THREAD

**Issue by mihaeltomic** [nylas/N1#194]
After I eneterd the invitation code I can't finish the next step because of the offscreen app position.

![image](https://cloud.githubusercontent.com/assets/7020915/10725817/26f9df3c-7bcf-11e5-9d5f-1bdeb6489ae2.png)

**Comment by bengotow** [comment]
Hey @mihaeltomic — can you try downloading the latest Windows build from https://edgehill.nylas.com/download?platform=win32 and let me know if this issue persists for you? We had a bunch of reports of this in 0.3.17 and fixed it on Friday in 0.3.19.
