### ISSUE TITLE
Auto logout

### ISSUE THREAD

**Issue by mxstbr** [nylas/N1#1944]
**Feature Request**

I'd love to have an auto-logout-on-close feature.

I don't want anybody to have access to all my mail accounts if my laptop is stolen, (which would give them access to almost all my online accounts) so logging me out of my email accounts but preserving the options/aliases on application close would be a very appreciated feature.

**Comment by grinich** [comment]
hey @mxstbr -- do you know of other mail apps that do this?

**Comment by mxstbr** [comment]
Well, my browser kind of does it with the [Auto Logout Chrome Extension](https://chrome.google.com/webstore/detail/auto-logout/ohlcnddhihadnalofegeookbpglgadhe), which clears the cookies on browser-close. (which logs me out of all accounts)

I haven't used a desktop client that has this feature, sadly. Would this be something that'd live in a plugin or would this have to be in the core?

**Comment by bengotow** [comment]
Hey folks! We'd like to keep sounds like a great plugin idea, but we'd like to keep this sort of functionality out of core. I'm going to move this to the ideas board: https://trello.com/c/AbQLY2p5/67-log-out-on-quit

**Comment by mxstbr** [comment]
If you point me in the right direction of how to do this as a plugin I'll write it! Any particular methods i should know of?
