### ISSUE TITLE
500 Error while trying to confirm an event at QuickSchedule Plugin

### ISSUE THREAD

**Issue by fuseprods** [nylas/N1#1946]
Hi!

I'm using Nylas N1 0.4.19 on Windows 7 (64 bits)

When I try to schedule an event with quickschedule plugin I'm sent to `https://quickschedule.herokuapp.com/event/event-id`

Then, using Google Chrome 49.0.2623.112 I try to confirm the event and I receive an internal server error.

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by fuseprods** [comment]
After trying different options, it seems to be a problem with this specific event, I can schedule other events without problem. I paste the link here just in case anyone can figure out what happened.

https://quickschedule.herokuapp.com/event/OfDmnjIBMBMpSkJhsPUv6FrOIo5sOY38zfxzY4e4YIe011QTERIeeZkSuSJBbEXxyANQuGnTzbsAvDQVMeeOlBka9185QYcuYWIL9SluCtqzP5Bn7Ljy0YQ6LSUa79Pm

**Comment by jackiehluo** [comment]
Going to close this issue for now, since we've changed so much with the Scheduler plugin!
