### ISSUE TITLE
In compose, tabbing should move between fields and ⌘-] should tab

### ISSUE THREAD

**Issue by falloutofatree** [nylas/N1#1949]
I'm used to tabbing in Gmail and here tab works like in a word processor. I guess that might be better for some people but given I selected Gmail keyboard shortcuts I would have expected this to work like Gmail.

##### What operating system are you using?
Yosemite

##### What version of N1 are you using?
Version 0.4.19-d41e72c (0.4.19-d41e72c)

##### Do you have any third-party plugins installed?
No

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Gmail

**Comment by hallamoore** [comment]
This has been fixed. You can use tab to move between fields, though tabbing in the actual message body still provides an indent, rather than having to use a different key command. Shift-tabbing from the message body will still take you back to the previous fields.
