### ISSUE TITLE
Undo send

### ISSUE THREAD

**Issue by lithstud** [nylas/N1#195]
Hi,
In gmail it is possible to have "Undo send". You can also choose the seconds after which it gets actually sent and undo is not possible anymore. This is a really helpful feature and it has saved me a lot of times. 
Is there any chance that this will get added at some point? If not by default - would it be possible to do via plugin?

**Comment by bengotow** [comment]
Hi @lithstud — yep, this is a great idea for a plugin. I think most apps that provide undo send essentially keep a queue of outbound messages, and wait for a few minutes client-side before sending. I created a card for this on our open-source roadmap: https://trello.com/c/6AFGunEh/42-undo-send-send-in-5-minutes. Feel free to upvote it there if you've got a Trello account!

**Comment by emorikawa** [comment]
Duplicate of #208
