### ISSUE TITLE
Update doesnt work

### ISSUE THREAD

**Issue by brandondeweese** [nylas/N1#1952]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
@brandondeweese Hey! Can you elaborate more on what problem you're experiencing?

**Comment by brandondeweese** [comment]
Click install. Closes Nylas and nothing updated.

**Comment by bengotow** [comment]
What platform are you using? Mac / Win / Linux? OS version? Version you're trying to upgrade from?

**Comment by brandondeweese** [comment]
Mac / Version 0.4.19-d41e72c (0.4.19-d41e72c)

**Comment by bengotow** [comment]
Hey @brandondeweese — it sounds like this might be a permissions issue on Mac OS X. We use a small helper app to install the update once the app has quit and it seems it's not able to replace the files.  I haven't seen any other reports of upgrade issues—could you download the new version manually from edgehill.nylas.com/download?platform=darwin
