### ISSUE TITLE
N1 offers to downgrade itself …?

### ISSUE THREAD

**Issue by JohnSandel** [nylas/N1#1953]
On OS X 10.10.5, upgraded N1 to 0.4.25-a22631a, which runs fine. But on launch (& relaunch, & machine reboot), N1 offers an "update" to 0.4.19-d41e72c. I can't get the update banner to go away. Screenshot attached.

![n1 wants to downgrade](https://cloud.githubusercontent.com/assets/16235437/14503642/d9ba1210-0165-11e6-93a8-bd7ead2b61b0.png)

**Comment by bengotow** [comment]
Hey—sorry for the hassle. With the 0.4.25 release we were testing an update to our auto-updaters that allow us to slowly roll out a new release across the user base. It looks like there was a bug where if you downloaded the new version manually before it was auto-assigned to you by the updater, the Mac OS X version of N1 would try to downgrade to the version it was assigned.

We've pushed 0.4.25 to everyone so this shouldn't be an issue anymore. If you quit and relaunch N1 without installing the update, you won't get the bar again. Sorry for the hassle—we'll be fixing this on the backend this week.

**Comment by JohnSandel** [comment]
Are you kidding? You guys are my heroes!  

  

\--

John Sandel

  

  
![](https://link.nylas.com/open/1agfhyvv7m51i6j1eeof12ha1/local-d5b7f833-d2b5)

On Apr 13 2016, at 10:57 am, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey—sorry for the hassle. With the 0.4.25 release we were testing an update
to our auto-updaters that allow us to slowly roll out a new release across the
user base. It looks like there was a bug where if you downloaded the new
version manually before it was auto-assigned to you by the updater, the Mac OS
X version of N1 would try to downgrade to the version it was assigned.

>

> We've pushed 0.4.25 to everyone so this shouldn't be an issue anymore. If
you quit and relaunch N1 without installing the update, you won't get the bar
again. Sorry for the hassle—we'll be fixing this on the backend this week.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1953#issuecomment-209568758)![](https://github.com/notifications/beac
on/APe7rYlkKtNa-6zk9BWXcNP01TfNfRmkks5p3S6lgaJpZM4IGpQy.gif)
