### ISSUE TITLE
Bcc Problems W/ Latest update

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#1955]
##### Are there any related issues?

...

##### What operating system are you using? OS 10.11.4
...

##### What version of N1 are you using? 0.4.25-a22631a (0.4.25-a22631a)...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
 No
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? No
...

**Comment by oldhickory30** [comment]
Every since I updated, I'm having issues with Bcc the Bcc window will not stay or open, therefore i cannot Bcc! Please fix asap!

**Comment by bengotow** [comment]
Hey! Can you explain in more detail what's happening? This is what it should look like. The fields do collapse, but your recipients are still set:

http://www.giphy.com/gifs/l3V0dPZYYleLjbAqI

**Comment by oldhickory30** [comment]
Basically I choose Bcc and the window collapses but does not give me the
opportunity or f**ield** to type in a recipients within Bcc. This was never an
issue until downloading the update earlier today. This is what it looks like
when I click on Bcc![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu
/local-936a7a9f-52e0)

On Apr 13 2016, at 3:52 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey! Can you explain in more detail what's happening? This is what it should
look like. The fields do collapse, but your recipients are still set:

>

> <http://www.giphy.com/gifs/l3V0dPZYYleLjbAqI>

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1955#issuecomment-209663406)![](https://github.com/notifications/beac
on/APa9ICIDVsEg1Ylws3munEjdkrVIREkrks5p3WWDgaJpZM4IGzlA.gif)

**Comment by oldhickory30** [comment]
Any chance that Bcc will work
soon?![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
780e7697-5fe9)

On Apr 13 2016, at 3:58 pm, waj &lt;OldHickory30@zoho.com&gt; wrote:  

> Basically I choose Bcc and the window collapses but does not give me the
opportunity or f**ield** to type in a recipients within Bcc. This was never an
issue until downloading the update earlier today. This is what it looks like
when I click on Bcc![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu
/local-936a7a9f-52e0)

>

> On Apr 13 2016, at 3:52 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

>> Hey! Can you explain in more detail what's happening? This is what it
should look like. The fields do collapse, but your recipients are still set:

>>

>> <http://www.giphy.com/gifs/l3V0dPZYYleLjbAqI>

>>

>> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/1955#issuecomment-209663406)![](https://github.com/notifications/beac
on/APa9ICIDVsEg1Ylws3munEjdkrVIREkrks5p3WWDgaJpZM4IGzlA.gif)

**Comment by bengotow** [comment]
Hey—it doesn't look like your image came through. Can you try again?

**Comment by oldhickory30** [comment]
Hopefully it worked this time!

On April 14, 2016 at 1:09:47 PM, Ben Gotow (notifications@github.com) wrote:

Hey—it doesn't look like your image came through. Can you try again?

**Comment by bengotow** [comment]
This should be fixed in 0.4.33 - can you try again and see if the issue persists?

**Comment by jackiehluo** [comment]
Merging into https://github.com/nylas/N1/issues/2754.
