### ISSUE TITLE
Spellchecker in English only

### ISSUE THREAD

**Issue by flareau** [nylas/N1#1959]
When composing, the spellcheck doesn't detect the language and only checks for English. Very annoying when most of your emails are in another language.

##### Are there any related issues?

Haven't found the same issue

##### What operating system are you using?

Mac OS 10.10.5

##### What version of N1 are you using?

Version 0.4.25-a22631a (0.4.25-a22631a)

--

**Bug**
##### Do you have any third-party plugins installed?
No

**Comment by koenpunt** [comment]
Related #535  #363 #1388 #1392 #1600
