### ISSUE TITLE
Ubuntu (unity) show unread email count

### ISSUE THREAD

**Issue by raffazizzi** [nylas/N1#196]
It would be helpful to have a count of unread emails on the N1 icon in unity.

![n1unity](https://cloud.githubusercontent.com/assets/144770/10727503/a89f38ba-7bda-11e5-8448-62cb6f499e2d.png)

**Comment by slash686** [comment]
+1, also it would be great to have integration with Ubuntu Unity system tray (top right)

**Comment by Mitsuroseba** [comment]
+1

**Comment by bengotow** [comment]
Merging this into #408
