### ISSUE TITLE
Design - delete button

### ISSUE THREAD

**Issue by Cu8eR** [nylas/N1#1965]
Add "delete" button next to archive button in email view (or make an option to use delete instead archive)

**Comment by bengotow** [comment]
Hey! You should see both delete and archive (see trash icon in the hover state and also in the top right):
![image](https://cloud.githubusercontent.com/assets/1037212/14541218/de98e562-0256-11e6-90a7-90eeec45064e.png)

The buttons might be missing if N1 didn't realize your account has a Trash folder for some reason. If you switch to the individual account view for your account (Via this picker:)

![image](https://cloud.githubusercontent.com/assets/1037212/14541240/f8d1feaa-0256-11e6-9636-ba18abddc7ae.png)


Do you see an item with the Trash can icon in the sidebar? 

![image](https://cloud.githubusercontent.com/assets/1037212/14541253/06606ff2-0257-11e6-809a-fd4d8d62be16.png)

**Comment by bengotow** [comment]
Might be related to https://github.com/nylas/N1/issues/380

**Comment by bengotow** [comment]
Merging this into https://github.com/nylas/N1/issues/872
