### ISSUE TITLE
Preferences UI Broken in Darkside (Search Bar Overlapping Icons)

### ISSUE THREAD

**Issue by thebearjew** [nylas/N1#1966]
The "Search email" bar and back navigation button overlaps the new preferences icons in Nylas version 0.4.25-a22631a (0.4.25-a22631a).

Image:
![screen shot 2016-04-14 at 1 49 11 pm](https://cloud.githubusercontent.com/assets/5200812/14543373/8bfd662e-0248-11e6-8572-3f2083ac0e26.png)

This bug is entirely reproducible on my end regardless of:
- Nylas restart
- Nylas quit
- Window resize
- OS X restart

##### Are there any related issues?

Could not find other issues discussing this specific search bar in the preferences window
...

##### What operating system are you using?

OS X El Capitan 10.11.4
...

##### What version of N1 are you using?

Version 0.4.25-a22631a (0.4.25-a22631a)

...

--

**Bug?**
##### Do you have any third-party plugins installed?

Only the darkside theme
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

It is not
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, 100% reproducible after window resize, application quit, application reinstallation, and computer restart.

...

**Comment by jackiehluo** [comment]
@thebearjew Is there any chance you're using an older version of Darkside and not the one bundled with N1? Or do you experience the same issue if you switch themes? Here's how it looks for me:

<img width="1162" alt="screen shot 2016-04-14 at 2 05 03 pm" src="https://cloud.githubusercontent.com/assets/8452682/14543641/035ce2ca-024a-11e6-8744-86b366b0a8c9.png">

**Comment by thebearjew** [comment]
yes actually. I might be.
Let me try an update (that would explain the issue persisting).

**Comment by thebearjew** [comment]
You're correct, that solve my issue. Apologize for the over-detailed Issue.

I'm guessing the [three variations of Dark Side](http://jamiewilson.io/darkside/) need to be manually edited in the SASS files

**Comment by jackiehluo** [comment]
@thebearjew Great, I'm glad to hear it!

And yeah, if you want to adjust the colors, feel free to copy `internal_packages/ui-darkside` from this repo, change the variables, and install again!

**Comment by thebearjew** [comment]
@jackiehluo One final question, my apologies, where is the `internal_packages` directory located?

Not seeing much in `~/.nylas`

**Comment by jackiehluo** [comment]
@thebearjew Oh, sorry! In this repo, the one for N1. The theme is a package, [here](https://github.com/nylas/N1/tree/master/internal_packages/ui-darkside).
