### ISSUE TITLE
Splash screen feels unnecessary. 

### ISSUE THREAD

**Issue by bensk** [nylas/N1#1967]
Splash screens feel like wallpaper over slow loading. I’d rather just...wait and then have the app appear. Maybe it’s just me.

**Comment by mbilker** [comment]
I prefer to have the splash screen so the window pops up on `i3` and I can switch to another workspace.

**Comment by YuriSolovyov** [comment]
Refs #383

**Comment by bengotow** [comment]
Hey folks—Going to merge this into #383.
