### ISSUE TITLE
Confusion about default alias use?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1969]
Dear all, 

I have a question about the alias preferences. 

As you can see in the below screenshot, I have a primary Gmail address (account label) and four supplementary aliases. I can choose one of these 4 to be my default aliases. 

However, what if I want my primary Gmail address (account label) to be my default alias?

I can't select that one from the dropdown. 

Is this intentional?

Thankfully,

~Robert

![nimbus-image-1460703881218](https://cloud.githubusercontent.com/assets/170947/14553837/2b2fd6f0-02e9-11e6-96db-5c5593e6bb89.png)

**Comment by bengotow** [comment]
Hey Robert—if you want the primary email address and name to be used, you can choose "None" from the default alias dropdown and leave your primary account as the default.

I'm going to change this dropdown so that "None" reads "None (Primary name <primary-email@gmail.com>)"

**Comment by orschiro** [comment]
Hey @bengotow,

> I'm going to change this dropdown so that None reads None (Primary name <primary-email@gmail.com>)

This will make it more clear to users. 

Thank you!

~Robert

**Comment by bengotow** [comment]
Hey folks—this should be fixed in `0.4.32`, which shipped yesterday. Cheers!
