### ISSUE TITLE
Account dropdown arrow is inverted?

### ISSUE THREAD

**Issue by alexmic** [nylas/N1#197]
The arrow should be pointing down to open, up to close?

![inverted](https://cloud.githubusercontent.com/assets/333117/10734182/e14bddc0-7bf9-11e5-9d40-77f85ba9dc6a.gif)

**Comment by frisinacho** [comment]
:+1:

**Comment by bengotow** [comment]
Hey gang—this was reported earlier and should be fixed in `0.3.19` - can you try updating the app (on Mac OS X, choose N1 > Check for Updates from the menu.) Cheers!
