### ISSUE TITLE
Problems with mails from Nylas Team

### ISSUE THREAD

**Issue by qba123** [nylas/N1#1970]
I got emails from Nylas Team but I can't remove them...

after reinstalling it, I added email accounts and I got "Nothing to display", messages aren't downloading now...

![zrzut ekranu z 2016-04-15 09 51 44](https://cloud.githubusercontent.com/assets/16326782/14554906/f46efeb4-02ef-11e6-9270-6925ad9047e6.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I think this was caused by an issue with the thread list becoming stuck and should be fixed in the latest release.
