### ISSUE TITLE
Add 32-bit version for Linux

### ISSUE THREAD

**Issue by NeoMahler** [nylas/N1#1976]
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, Thunderbird, geary and I think all other mail clients. I need a 32-bit version of this mail client. I think that this would be the solution of my problems with finding email clients for Linux (I've tried geary, but it seem that it has some bugs) but I can't install it because I use a 32-bits Linux OS (I use an old laptop and I think that a 64-bit OS would require a faster computer.

**Comment by mbilker** [comment]
Dupe of #254
