### ISSUE TITLE
Default sender broken

### ISSUE THREAD

**Issue by lmartins** [nylas/N1#1977]
##### What operating system are you using?
OS X

##### What version of N1 are you using?
Version 0.4.25-a22631a (0.4.25-a22631a)

--

**Bug?**
##### Do you have any third-party plugins installed?
n1-unsubscribe-master

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Dont think so.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I have 4 emails accounts and have selected the options to use the email address of the selected account when replying to messages. 
Despite that, when replying to any message the sender is always my first account and if I try to select a different account the dropdown only shows that same account.
When composing new email messages the dropdown shows every account as expected.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
nope

**Comment by bengotow** [comment]
Hey! I believe the "Default alias" only applies to new messages. If you're replying to messages you've received, N1 will use the alias the email was addressed to (if applicable), or the base email / phrase associated with the account. I'll see if we can improve this in the future. I think it used to apply to all email, and folks were upset that it didn't reply using the alias the message was addressed to.

**Comment by lmartins** [comment]
Ah, it makes sense although im not sure if this is just me but I sometimes need to forward or reply to messages using a different sender address and in that scenario it would be useful to be able to use a different account.

**Comment by lmartins** [comment]
Actually I noticed what appears to be an issue related to this.
Composing new message do pick the signature from the selected account but still has the email address from the first account on the email accounts list.

I have on the sidebar:
Account 1
Account 2

I select Account 2 and press Compose New Message button. The new message window has the mail signature from the correct account, but still has the email address from Account 1 in the Sender dropdown.

**Comment by lmartins** [comment]
Closed in favor of https://github.com/nylas/N1/issues/2020 which is actually more serious I think.
