### ISSUE TITLE
'sent' isn't capitalised

### ISSUE THREAD

**Issue by thosgood** [nylas/N1#1979]
As can be seen in the attached screenshot, for some reason the 'sent' folder under 'All Accounts' isn't capitalised, but all of the others are. The only email account that is listed under the sent section is my googlemail account, where the sent mail folder is called 'Sent Mail' (with capitals).

I haven't installed any plugins or anything, and I'm running the latest version of N1 (0.4.25-a22631a) on OS X 10.11.4.

<img width="118" alt="screen shot 2016-04-15 at 21 44 31" src="https://cloud.githubusercontent.com/assets/7130759/14574384/42f4d35c-0353-11e6-9836-be059a87770c.png">

**Comment by bengotow** [comment]
Hmmm - that's strange... if you expand the disclosure triangle beside `sent`, is the item inside called "sent" as well? It seems like our sync engine is reporting that the folder is called `sent` for some reason, not `Sent Mail`. 

Is this a Gmail or an old GoogleMail account? Thanks!

**Comment by thosgood** [comment]
<img width="237" alt="screen shot 2016-04-16 at 15 55 32" src="https://cloud.githubusercontent.com/assets/7130759/14581726/e42f045c-03eb-11e6-87e2-4cfdd45b24f5.png">

As you can see, the item inside is just labelled with my gmail address. I'm not too sure, I opened the account probably around 6-7 years ago, so I guess it's an old GoogleMail account?

**Comment by kav-ya** [comment]
Thanks for the report @thosgood, the issue should be resolved now. If it's not, please let us know!
