### ISSUE TITLE
A Changelog

### ISSUE THREAD

**Issue by bhardin** [nylas/N1#198]
When an update comes out, I see the "an update is available". But no way of figuring out what is in it. I would even be happy with commit messages.

**Comment by bengotow** [comment]
Hey! I definitely agree we need a changelog. We currently post the release notes onto the community slack channel, but they're not available elsewhere. I'll see if we can formalize this a bit better in the next release. Stay tuned—

**Comment by bengotow** [comment]
Hey! We've added a changelog here: https://github.com/nylas/N1/blob/master/CHANGELOG.md and we'll be pointing to it in the update notifications. Enjoy,

**Comment by bhardin** [comment]
Thanks Ben!
