### ISSUE TITLE
Delete message keeps on re-appearing in inbox

### ISSUE THREAD

**Issue by rawjam** [nylas/N1#1980]
Almsot all the time now, when I delete a message, it re-appears in a matter of seconds in the inbox. Sometimes clicking into a sub folder and then back to inbox causes it to refresh, but often cases it just stays there and I need to delete again.

Starting to get really annoying now... Is this a known issue?

**Comment by mbilker** [comment]
Check Developer -> Open Activity Monitor -> Requests. Are all the responses showing 200 on the right side?

If you do screenshot, please blur out the center column with the HTTPS requests.

**Comment by rawjam** [comment]
Yes all showing 200 (well the recent ones i saw anyway).

Not sure if this is related, but if i log into my gmail, I can see hundreds of old emails in my inbox that I thought i'd deleted ages ago via N1 and in fact, they are no longer showing in N1 (i.e. suggesting they were deleted properly) yet in Gmail and any other mail client (such as one i use on my iPhone) show hundred of emails in my inbox.

Somewhere there is a problem deleting...  is there anything else I can provide you with that might give you a clue?

**Comment by rawjam** [comment]
Are there any updates on this? I am still seeing this issue. To reproduce the steps, all i do is delete an inbox item. It then often re-appears in the inbox a few moments later.

**Comment by johanneskoester** [comment]
I have exactly the same issues. However, I get a return code of 400 for 
```
Run Copy curl -X PUT -d '{"labels":["...","...","..."]}' "https://...:@api.nylas.com/threads/..."
```

**Comment by guleifanger** [comment]
Guys, I have the same problem here. How can I help you? How can I help debug this problem?

**Comment by rawjam** [comment]
Are there any updates on this? It seems such a fundamental flaw in the platform. I delete, yet messages often pop back into the inbox a few seconds later.

Related to this - almost all emails that I delete from N1 aren't actually deleted from my gmail inbox, meaning that logging into gmail or any other mail client, presents me with hundreds of old emails that I was lead to believe i'd deleted.

This ticket is marked as needing steps to reproduce. I have answered your questions and am waiting for your follow-up. Please please can someone get back to me.

**Comment by johanneskoester** [comment]
Indeed, please at least answer our report. This will definitely prevent me from buying the pro version.
@mbilker, do you want us to perform additional tests or provide details about the mail providers involved?

**Comment by mbilker** [comment]
Nope! Looks like enough evidence to me.

@rawjam My emails do not get deleted (or relabeled technically) from my Gmail inbox as well. It annoys me and I have dropped N1 for the time being until this major issue is fixed, but I should bring it to the Nylas team in their Slack (if Slack actually upgraded their Electron version to fix the `libfreetype2` issues).

**Comment by EvNaverniouk** [comment]
I am having the same issue. Installed N1 today to try it out, but this issue is a deal breaker.

Steps to reproduce:

- Install N1 Version 0.4.45-7637265 (0.4.45-7637265)
- Add a Gmail account
- Wait for account to sync
- Go to "Inbox"
- Select an email and press the Delete button
- The email will disappear from N1 (and never reappear)
- Log into Gmail (via www.gmail.com). BUG: Email is still present in inbox in Gmail.

**Comment by jackiehluo** [comment]
Merging into #781!
