### ISSUE TITLE
mailto links not opening compose window

### ISSUE THREAD

**Issue by twonth** [nylas/N1#1981]
On Linux, mailto links bring the focus to the main N1 window, but do not open a compose window.

##### Are there any related issues?
This came up as part of issue #403 (recently closed). As reported there, a number of folks with Linux are still experiencing this bug, even after upgrading to 0.4.25.

##### What operating system are you using?
Ubuntu 15.04

##### What version of N1 are you using?
Nylas 0.4.25-a22631a

**Comment by albflo** [comment]
Also on Ubuntu 16.04 with Nylas 0.4.25-a22631a does the bug still exist.

**Comment by rittbys** [comment]
Is this referring to mailto links from within n1 or from external sources? I wasn't aware that you could assign n1 to handle mailto yet.

**Comment by albflo** [comment]
It doesn't work only from external sources, for example if I open a mailto link in my wiki or a mailto reference on a website. If I open a mailto link in a email it works perfect.

**Comment by bengotow** [comment]
Closing as dup of https://github.com/nylas/N1/issues/403

**Comment by truckingsim** [comment]
@bengotow you closed this as a dupe but its still not fixed and you didn't reopen #403.  Not sure the intention here, its obviously still a problem.
