### ISSUE TITLE
Feature Request: Only show the folders for the currently selected mailbox

### ISSUE THREAD

**Issue by timtjtim** [nylas/N1#1982]
## Feature Request

I use 4 accounts with N1 - and it's excellent. The main issue I have is the 20+ tags I have with google occupying the whole sidebar. This means I cannot see the folders for my College account. See the "Nylas Sidebar" image.

When I come to sort my college account, I have to minimise the labels for my Gmail account. This is quite annoying, as there is no reason to have my Gmail labels visible - I can't drag an email there so why keep it open?

And yes, this feature does exist in another mail client or tool I use - Windows 10's built-in Mail app has this behaviour - it only shows the folders for the account selected. See the "Windows 10 Mail" image.

[Nylas sidebar][1]

[Windows 10 Mail][2]

<sup>(Images left as links because the sidebar is very long and goes off the page)</sup>

  [1]: https://cloud.githubusercontent.com/assets/6292691/14582818/2c01413a-0407-11e6-8189-7056015050c3.png

  [2]: https://cloud.githubusercontent.com/assets/6292691/14582819/2c14320e-0407-11e6-89ce-13b622cc7c95.png

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - N1 should be remembering whether you've collapsed that section, and you should also be able to scroll down to see the others (though the scroll bar may only appear when you hover over it). Stay tuned

**Comment by timtjtim** [comment]
@bengotow Hmm, yes it does "remember" - however, I'd like it to *change* base don the one I've clicked on, rather than always be my second account dropped down (as Windows 10 Mail does). I looked into making a plugin, but Time and Coding ability limit me.

**Comment by bengotow** [comment]
Hey! I just realized I think what you might want is this dropdown: 

![image](https://cloud.githubusercontent.com/assets/1037212/15081963/2fd3b1ee-137a-11e6-8e09-1cbccd41cc17.png)

You can actually switch the sidebar to just show your one account, and use the keyboard shortcuts to quickly jump from account to account if you'd prefer. I'll see if we can also get the expanding going. Cheers!

**Comment by bengotow** [comment]
I've added b91ebd5504e554272186b4eab2997fd3c022834c, which should make the sections expand as you drag over them. Hopefully this does the trick!

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
