### ISSUE TITLE
Blank Drop Down Menus 

### ISSUE THREAD

**Issue by Crosant** [nylas/N1#1983]
Hey Guys,

on my way switching to Linux I encountered this awesome mail client.
But i noticed that the drop down menus especially the ones in the mail rules menu are completely blank.
I tried to reinstall but the problem still exists and it may be connected to the Fedora distribution.

Thank you for your Help.

**Comment by CrazyLemon** [comment]
Blank or black? If black then thats already been reported. Please check #1163

**Comment by Crosant** [comment]
They are blank not black but i could check with different themes.

**Comment by bengotow** [comment]
Seems very likely this is a dup of #1163. @Crosant let me know if the color changes to black, based on your theme!
