### ISSUE TITLE
Feature Request: Reply without quoted text

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#1986]
Dear all, 

Is it possible to disable that previous conversations are inserted as a quote on reply?

I would like to reply in a completely blank composing window without a signature (which I could disable), nor the content of the previous replies. 

Thankfully,

~Robert

**Comment by bash-horatio** [comment]
This is an annoying feature when I am reading emails from mail lists. Maybe collapse quotes will be a good improvement.

**Comment by orschiro** [comment]
Dear @bash-horatio,

> This is an annoying feature when I am reading emails from mail lists. 

You mean to see all the previous quotes? If yes, then I totally agree with you on this as well!

~Robert

**Comment by bash-horatio** [comment]
@orschiro Exactly！Imagining reading a emai from mail list with all the previous quotes……

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should allow you to remove the quoted text easily—let us know what you think! Thanks!
