### ISSUE TITLE
You should be able to change themes via the appearance pane in the settings

### ISSUE THREAD

**Issue by rakeshdas1** [nylas/N1#1987]
The current appearance pane in the settings menu only includes an option to change the layout between the single and two panel layouts. There should be a link to change the theme in this panel as well. I have attached a screenshot of the current appearance pane. 
![image](https://cloud.githubusercontent.com/assets/6901641/14588665/25e32448-0494-11e6-94dd-dc5e35f441af.png)

**Comment by bengotow** [comment]
Hey @jackiehluo maybe we should add a button here to pop up the theme picker?

**Comment by bengotow** [comment]
(Fixed in `0.4.32`)
