### ISSUE TITLE
Fix copy when archiving/deleting

### ISSUE THREAD

**Issue by xasos** [nylas/N1#1988]
Currently when deleting a message: 
<img src="http://i.imgur.com/l4CUrnb.png"><br>
Toast should read "Added 1 thread to trash" - possibly including name of thread(s) if they are similar ("added 3 threads from Joe to trash")<br>

When archiving a message:
<img src="http://i.imgur.com/KJewDkU.png"><br>
Toast should read "Archived one thread" - again possibly adding details of thread.<br>

Mac OS X 10.11.2, Nylas Version 0.4.25-a22631a

**Comment by bengotow** [comment]
Merging into https://github.com/nylas/N1/issues/1921
