### ISSUE TITLE
No delete button for Windows platform. How come?!

### ISSUE THREAD

**Issue by ihabovich** [nylas/N1#199]
Hey,
I didn`t get to any way I could delete a message neither "Delete" keyboard button nor any shortcuts available in preferences. That totally weird.

**Comment by bengotow** [comment]
Hey! That's weird indeed—are you running `0.3.19`? There was an early version of the app that didn't show a trash icon for Gmail accounts. It should appear in the top bar when you view a message, and also when you select more than one item in the thread list:

![image](https://cloud.githubusercontent.com/assets/1037212/10736891/8ec6c326-7bcc-11e5-954d-c943de559625.png)

![image](https://cloud.githubusercontent.com/assets/1037212/10736900/98e46b6a-7bcc-11e5-9730-9c318d805cdf.png)

**Comment by ihabovich** [comment]
It found to be 0.3.17. Is there away to update?
