### ISSUE TITLE
N1 only shows first email account when it is opened after reboot.

### ISSUE THREAD

**Issue by timtjtim** [nylas/N1#1993]
##### Issue

The first time I boot my computer then open N1, only my first email account (a Google Mail account) shows up. If I open Preferences and the Accounts, then go back to Inbox, the next 3 appear.

##### What operating system are you using?

Ubuntu Gnome 14.04.4 

##### What version of N1 are you using?

0.4.25-a22631a

--

##### Do you have any third-party plugins installed?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I don't *think* so...

**Comment by timtjtim** [comment]
![screenshot from 2016-04-19 01 35 57](https://cloud.githubusercontent.com/assets/6292691/14624087/4724082a-05cf-11e6-9cc5-0dfc3b57de4d.png)
![screenshot from 2016-04-19 01 32 54](https://cloud.githubusercontent.com/assets/6292691/14624088/47382d96-05cf-11e6-8912-d6bfdad56db4.png)

**Comment by jackiehluo** [comment]
@timtjtim Is there any chance that you're closing the app on that same Gmail view in the unified inbox? And when N1 opens, when you click the little dropdown arrow on the right of "Gmail," do you have the option to choose "All Accounts"?

**Comment by timtjtim** [comment]
@jackiehluo Oh look at that! Can I change the startup default or is this just a "press ctrl+1 when I open it" type fix?

I guess this should be closed now.

**Comment by jackiehluo** [comment]
Oh, cool, glad that that worked! The startup default should be the last view from when you closed the app. For instance, if you close the app while viewing just your Gmail inbox, it'll open in that view, and if you close the app while viewing the whole unified inbox, it should open there.
