### ISSUE TITLE
Hooray! A Rabbit? 

### ISSUE THREAD

**Issue by Everglide** [nylas/N1#1998]
To empty your inbox and to be greeted by a green tick was elegant enough, a reward in itself.

The rabbit and diamonds is cheap... I'm using restraint!

**Comment by grinich** [comment]
so... is this a bug?

**Comment by mbilker** [comment]
I don't think so. I am going to close this.

**Comment by mbilker** [comment]
Strange, I didn't change the title. The Inbox Zero graphics vary randomly. I find them pretty cool if I ever had inbox zero.
