### ISSUE TITLE
Web-based client?

### ISSUE THREAD

**Issue by waynerobinson** [nylas/N1#20]
I understand that N1 is currently built on Electron, but are there plans (or is it already reasonably simple) to decouple from Electron and deploy as a web-based application, rather than desktop client?

**Comment by OrKoN** [comment]
I have the same question. There are good enough desktop clients but a good web one is missing.

**Comment by bengotow** [comment]
This is a great question. Unfortunately, N1 is tightly coupled to Electron and we're not planning to create a web-only version. It'd be awesome if we could support both, but there are many, many places where we would need to maintain two versions of code (one for web, one for Electron.) The app maintains a SQLite cache on disk, saves attachments, etc., and relies on having multiple processes to offload sync work. It also has a pretty robust offline mode which we probably wouldn't need! 

If we created a web client, we'd probably want it to be a totally separate, thin wrapper around our API sharing some of our React components.

**Comment by waynerobinson** [comment]
Thanks for the clarification.

I'll just leave these couple of thoughts before I go though.

When I am using specialised features of an email tool, I want those special features to follow me everywhere. Desktop, web, mobile (iOS + Android) and tablet. If I can't have those special features everywhere I can't choose a non-standard email client. Do you have plans for mobile/tablet versions of the app too and how does that work with the choice of Electron?

Could it be worthwhile to break the extra client-side features like cache, attachments, etc into a small, client-side application server that the Electron-client accesses, making it a much thinner client and much more easily portable to web-only or even a mobile-only app (where these other features are handled server-side by a multi-tenanted version of the same client-side application server)?
