### ISSUE TITLE
Plugin idea: mental arithmetics

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2000]
Dear all, 

I would like to share a plugin idea.

Where is the best place to do so?

The Trello board, which I would consider the most appropriate place, does not seem to allow me to add a new card.

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14639168/54a7e5cc-063b-11e6-81f8-6b529c3ce653.png)

**Comment by KevinMartin** [comment]
Post your plugin idea as an issue and (after some discussion, if any) someone from the Nylas team will close the issue and put the idea on the Trello board.

**Comment by orschiro** [comment]
Dear @KevinMartin and others,

My idea for a "productivity" plugin is as follows:

Upon click of the "send" button the user is prompted with a mental arithmetics exercise. Subsequently the email is only sent if the user responded to the exercise correctly. 

As you can see, this plugin does not add any core feature but rather provides a fun and gamified solution to lazy folks who want to improve their mental arithmetic skills. :-)

Warmly,

~Robert

**Comment by bengotow** [comment]
Thanks for the idea! That sounds pretty cool. I'm going to move this over to https://trello.com/c/F4odUo89/68-require-the-user-perform-arithmetic-other-tests-before-sending-mail. Cheers!

**Comment by orschiro** [comment]
Great, thanks @bengotow! :-)

~Robert
