### ISSUE TITLE
Archiving Very Slow After Receiving Several Emails

### ISSUE THREAD

**Issue by rosslebeau** [nylas/N1#2001]
It seems that whenever I receive many emails in a short amount of time (say, 6+ within 5 minutes), Nylas has large delays when trying to archive ANY emails for a while. I'll click the archive button and nothing will happen for 20-60 seconds, and sometimes it seems to never archive.

This is on OS X 10.11.4
Nylas N1 Version 0.4.25-a22631a (0.4.25-a22631a)
The only plugin I have installed is Taiga
The only email provider I use is Gmail

**Comment by rakeshdas1** [comment]
I have the same issue on both OSX and Windows.

**Comment by renestalder** [comment]
Same issue here. I use the gmail shortcut "e" to archive several messages in a row. after the 3rd or 4th archived messages, it seems no longer to work. Notification badge, that the message was archived, shows up at the bottom, but the messages stays in the inbox.

Also seems to be similar to #2018

**Comment by jstejada** [comment]
Hey folks —this should be fixed in 0.4.32, which shipped Monday. Feel free to file a new ticket if you are still having issues with the thread list not reflecting your actions properly.
