### ISSUE TITLE
Folder delete does not work

### ISSUE THREAD

**Issue by jayachandranm** [nylas/N1#2005]
Thanks for this awesome product! Finally I can connect to Office365 using exchage protocol from Linux.

Installed Nylas N1 on Ubuntu 15.10.
Running version 0.4.25.
Email provider: Office 365 (corporate account) using Exchange protocol.

1. After adding the account, tried deleting few folders that are in the server. The folder just grays out, but is not deleted. Tried restarting Nylas, but the folder is still there. And no errors were reported.

2. Nylas created few folders and subfolders in the server,

Sync issues \ Conflicts
                    \ ..
                    \ ..
Sync issues1 \ Conflicts
                    \ ..
                    \ ..

Tried deleting those folders, but nothing happened, except that the folders were grayed out.

No third party plugins installed.

**Comment by bengotow** [comment]
Dup of #898
