### ISSUE TITLE
2 Nylas on Startup

### ISSUE THREAD

**Issue by Necmttn** [nylas/N1#2006]
When i turn on my computer 2 Nylas is starts. 
http://imgur.com/BkLHgPL
i have one Nylas installed. 
it's Started to happen after i updated my software latest vers. 

##### What operating system are you using?
... Yosemita 10.10.2

##### What version of N1 are you using?

--Version 0.4.25-a22631a (0.4.25-a22631a)
##### Do you have any third-party plugins installed?
...JIFFY

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...NO

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...NO

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...NO

**Comment by emorikawa** [comment]
@Necmttn, can you go to Preferences -> General, and uncheck "Launch on System Start" then re-check it?

**Comment by DoWhileGeek** [comment]
I'm having the same issue.

http://imgur.com/oQsztnb

**Comment by Necmttn** [comment]
i re-installed and it's solved with current version.
