### ISSUE TITLE
IMAP INBOX. prefix still exists

### ISSUE THREAD

**Issue by rgruyters** [nylas/N1#2008]
The IMAP INBOX. prefix still shows up.

##### Are there any related issues?
It should have been solved in #66 

##### What operating system are you using?
Mac OS El Capitain

##### What version of N1 are you using?
Version 0.4.25-a22631a (0.4.25-a22631a)

**Comment by chrishawes** [comment]
I'm also seeing this, using Fastmail on OS X.

Version: `0.4.25-a22631a`

**Comment by 5qian** [comment]
Same issue here. Those annoying prefixes still exist.

Version: 0.4.33

**Comment by stephenhowells** [comment]
ditto, on Fastmail

Version 0.4.33-e8f137e

**Comment by bengotow** [comment]
This is finally getting resolved in the next release. (0441acf94aa5c46118759a72fbfe21e33f41d043). Stay tuned—

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
