### ISSUE TITLE
App icon pixel distorted

### ISSUE THREAD

**Issue by ihabovich** [nylas/N1#201]
That's how the app icon look on Windows PC
![icon](https://cloud.githubusercontent.com/assets/13511260/10737975/bcedbce0-7c1d-11e5-8ff7-06aa000bf3ce.png)

**Comment by CameronHall** [comment]
I have the same issue on my laptop however it's normal on my desktop.

Desktop:
![image](https://cloud.githubusercontent.com/assets/7316093/10781331/65079a72-7d9a-11e5-9ceb-f8e8b3eb63bb.png)

Laptop:
![image](https://cloud.githubusercontent.com/assets/7316093/10781416/f301dc8e-7d9a-11e5-8ca6-948ebbd0f1a9.png)

**Comment by bengotow** [comment]
This is fixed in `ec61918634f2b6cf19060bc06de596d6095b4a74 ` and the icons should look good after the next release. Apparently our `.ico` file was missing some resolutions, so some versions of Windows displayed low-resolution versions of the icon. Enjoy!
