### ISSUE TITLE
Mailbox action could not be completed

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2010]
Dear all,

Suddenly and without any changes from my side, I am no longer able to complete any actions on my Gmail account.

Can anyone confirm this issue?

I can normally use my account on the web. 

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14684080/6e3de452-072e-11e6-80b0-c809afba67b3.png)

**Comment by bengotow** [comment]
Hey! I've talked to our backend team about this and they're looking into a solution. It looks like you hit an edge case with our load balancer and it should be fixed shortly.

**Comment by JotaC** [comment]
Hi! I have the same problem with my Gmail Account.

**Comment by orschiro** [comment]
Dear @bengotow and @JotaC,

The problem does no longer occur for me. 

Thanks for the fix!

~Robert

**Comment by iztalo** [comment]
Same problem here.
Hotmail and gmail.

**Comment by mimoo** [comment]
same problem here. With Gmail.

**Comment by payammeyer** [comment]
This has been happening for me since last week. It was the sync issue for a while and now this. I love the product, but I'm really being forced not to use it.

**Comment by jackiehluo** [comment]
@iztalo, @mimoo, and @payammeyer: Can you email support@nylas.com? We need your email addresses to investigate the problem!
