### ISSUE TITLE
Images not loaded in message

### ISSUE THREAD

**Issue by alordmg** [nylas/N1#2012]
Hello!

I noticed today that the images in my emails are not loading.

Here's a screenshot

<img width="1920" alt="screen shot 2016-04-20 at 4 00 43 pm" src="https://cloud.githubusercontent.com/assets/11218493/14688579/4c1f1570-0711-11e6-9fb6-a7fccdff69a5.png">

Even when I try to save it manually by right-clicking, I cannot save the image.

I'm using Version 0.4.25-a22631a (0.4.25-a22631a) on Mac OS X El Capitan

**Comment by jemyzhang** [comment]
inline image not loaded, waiting for solution.

**Comment by kennysmoothx** [comment]
I think it should also be noted that this happens with specific Image file types.

e.g. PNG's and JPG seem to be loading fine, however TIFF files do not load.

**Comment by jackiehluo** [comment]
Merging into #621!
