### ISSUE TITLE
Error: Could not reach the Nylas API.

### ISSUE THREAD

**Issue by drom** [nylas/N1#202]
Building v0.3.19 from git master, on OpenSuse 13.2. Getting the following error on start:

![image](https://cloud.githubusercontent.com/assets/511872/10739367/3967b45a-7bd9-11e5-9bae-12d8a40348fb.png)

**Comment by middle8media** [comment]
+1, happening for me as well.

**Comment by middle8media** [comment]
duplicate to #54

**Comment by bengotow** [comment]
Hey folks—we've disabled the invite system in the last few days so I'm going to close this issue. Enjoy N1!
