### ISSUE TITLE
Feature: Add/Customizable thread swipe actions

### ISSUE THREAD

**Issue by KevinMartin** [nylas/N1#2023]
It would be great to be able to add more swipe actions than just Archive/Delete and Snooze.

And then add the ability to customize which will be the left/right swipe actions.

I personally don't use Snooze and depending on the email, I may archive it or just delete it. At the moment, archive/delete is toggled on the preferences pane. It would be great to be able to separate these two into independent actions and then allow the user to be able to add either one (or both).

As an example, I would like left=archive and right=delete.

Some examples of other swipe actions:
- Star/Flag
- Mark Read/Unread
- Move to/Apply label
- Spam

As a further request, it would be great if this were accessible to developer by creating Swipe Actions as components so developers can add more actions (such as "Add to Evernote" if anyone were to create to an Evernote plugin or "To-Do" if someone were to create a Trello/Todoist plugin).

##### Does this feature exist in another mail client or tool you use?
Apple Mail (OS X and iOS), Boxer, and a few others

**Comment by jackiehluo** [comment]
Looks like #1448 and #1833! Merging this issue into there. Agreed that allowing swiping for plugin actions would be super cool.
