### ISSUE TITLE
Unread counts are inaccurate

### ISSUE THREAD

**Issue by jmgalanter** [nylas/N1#2024]
##### Are there any related issues?
None that I can find

##### What operating system are you using?
OS X El Capitan (10.11.4)

##### What version of N1 are you using?
Version 0.4.25-a22631a (0.4.25-a22631a)

##### Do you have any third-party plugins installed?
Only default ones

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
It looks specific to an exchange server so far.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screenshot_4_21_16__1_51_pm](https://cloud.githubusercontent.com/assets/18602830/14723910/3274be74-07c8-11e6-9d7d-84a5a05025d3.png)

The account lists 10 new messages, but I have read all messages in the folder.

**Comment by djeglin** [comment]
#759 seems relevant here. 

I, too, am still having this issue on the same version as @jmgalanter . It seems there are still some gremlins in the unread counts.

**Comment by timtjtim** [comment]
I have 1 unread message. This occurred after it couldn't connect to "api.nylas.com". I have upgraded my Ubuntu version to 16.04, retaining settings etc.

**Comment by jmgalanter** [comment]
Update...

This has happened on multiple different computers, but always with my exchange account.  Interestingly, the number of phantom new messages is different on my different computers; it is 10 on my desktop but 1 on my laptop.

Also, it doesn't go away even if I remove the account and re-add it.

**Comment by grinich** [comment]
@jmgalanter this sounds like a sync bug

**Comment by kondratk** [comment]
Same for me on version 0.4.33-e8f137e (0.4.33-e8f137e). Using Gmail accounts only.

**Comment by jackiehluo** [comment]
I think this bug should be fixed, for the most part—let us know if it's not!
