### ISSUE TITLE
Chinese name display

### ISSUE THREAD

**Issue by rgw5267** [nylas/N1#2025]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.25

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://cloud.githubusercontent.com/assets/1254990/14728648/2ee0bd98-0869-11e6-90bc-97a68ebfca94.png)
![image](https://cloud.githubusercontent.com/assets/1254990/14728667/6cd841fc-0869-11e6-87c7-cf492f7faa2c.png)
in my inbox of Google is correct, but the other Chinese is correct.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by wzm1990** [comment]
I  installed the version 0.4.40 and use Exchange in OS X.
Individual Chinese name can't be displayed, resulting to the message body can not be displayed。
Chinese name like '玥，鹍，凃' 
![image](https://cloud.githubusercontent.com/assets/2445540/15493507/fcb60b86-21b6-11e6-9e54-1a7d3e01691b.png)

**Comment by jackiehluo** [comment]
Merging into https://github.com/nylas/N1/issues/810!
