### ISSUE TITLE
Compose in trash not working

### ISSUE THREAD

**Issue by xasos** [nylas/N1#2026]
When trying to compose a message in the trash, Nylas doesn't allow a compose window to be opened directly. Instead, it creates the messages in drafts and ups the count on the message "There are [x] messages in this thread that are not in spam or trash". 

Looks like an anti-pattern of sorts. Maybe a prompt to move out of trash? Or explicit instructions that the deleted message is in the trash folder, but response is in the drafts folder?

<a href="https://streamable.com/zhga">Video</a>
OS: Mac OS X 10.11.4
Nylas: 0.4.25-a22631a

**Comment by bengotow** [comment]
Thanks for reporting this—this is definitely a bug. We'll get it fixed in the next release.

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
