### ISSUE TITLE
New message content is hidden as if it were quoted text.

### ISSUE THREAD

**Issue by vince-p** [nylas/N1#2029]
Lately many (but not all) new messages show up in N1 without any content visible until I click the "..." button to expand previous replies. In other words, it seems like N1 thinks that new content is a reply that should be hidden. See the screenshot for a demonstration. This shows the right message panel with a new message that has the message content hidden.

![screenshot 2016-04-22 15 18 53](https://cloud.githubusercontent.com/assets/3746799/14732476/7e10548e-089e-11e6-9722-5784a81d8bba.png)

This seems similar to https://github.com/nylas/N1/issues/1312

I am using N1 v0.4.25 on Windows 8.1.
There are no third-party plugins.

**Comment by hallamoore** [comment]
There have been some changes to our quoted text detection since the opening of this issue, so I'm going to close it for now. Let me know if this problem still occurs!
