### ISSUE TITLE
Rpm wont install on fedora 24 

### ISSUE THREAD

**Issue by biji** [nylas/N1#2030]
Rpm wont install on fedora 24 

Error: nothing provides libgnome-keyring0 needed by nylas-0.4.25-0.1.x86_64

Thanks

##### Are there any related issues?

...

##### What operating system are you using?
fedora 24

##### What version of N1 are you using?
nylas-0.4.25-0.1.x86_64

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by wfpaisa** [comment]
```
	libgnome-keyring0 necessary for nylas-0.4.25-0.1.x86_64
	gir1.2-gnomekeyring-1.0 necessary for nylas-0.4.25-0.1.x86_64
```

**Comment by EliverLara** [comment]
same as #1832

**Comment by bengotow** [comment]
Thanks - closing as dup of #1832

**Comment by snydox** [comment]
Same error here.
