### ISSUE TITLE
Content of email hidden after I sent it

### ISSUE THREAD

**Issue by alordmg** [nylas/N1#2032]
I wrote a reply to an email and just after it was sent, the content is hidden, except for the attachments.

If I click on another email and go back to the conversation, the content becomes visible.

<img width="1920" alt="screen shot 2016-04-22 at 9 54 04 am" src="https://cloud.githubusercontent.com/assets/11218493/14743622/63c86ff4-0870-11e6-82b8-60a9742a3926.png">

**Comment by emorikawa** [comment]
This looks like it's the same bug as https://github.com/nylas/N1/issues/1280
Gonna close this issue and merge into #1280
