### ISSUE TITLE
Can't add a Gmail account - Google Sign In does not appear

### ISSUE THREAD

**Issue by tehkraft** [nylas/N1#2034]
N1 does not trigger a browser page to login to Gmail when trying to add a new account
...

##### What operating system are you using?

Windows 10 Pro Insider Build 14328
...

##### What version of N1 are you using?

Nylas N1 0.4.25

...

--

**Bug?** Yep!
##### Do you have any third-party plugins installed?

No plugins
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A
...

--

**Feature Request?** 
Nope!
##### Does this feature exist in another mail client or tool you use?
Nope!
...

**Comment by travesto** [comment]
I've also been experiencing this problem. Using Windows 10 Build 14328. Changing default browser doesn't seem to affect anything.

**Comment by bengotow** [comment]
Hmm—between this and #2044, it looks like it's occurred on both Windows and Linux. We should look at the sentry logs and see if anything has come in. I suspect it's due to the browser as well, but so far it's unclear. Anyone that is having this problem, if you can find a browser that it /does/ work in, I'd love to know!

**Comment by delixyr** [comment]
I tried changing default browser between IE, Edge, FF and Chrome with no results

**Comment by travesto** [comment]
The Activity Window reports this whenever the "Sign in to Google in your browser" window is open. I don't really know what this means or if it's related, but maybe someone else knows.
![screenshot 6](https://cloud.githubusercontent.com/assets/14929051/15035742/468e0b12-124b-11e6-8d72-f700e38a6f09.png)

**Comment by diddledan** [comment]
Same scenario here. The activity log also shows `https://n1-auth.nylas.com/oauth/google/token?key=<ramdom-base64-encoded-string>` returning HTTP Error 404 (Not Found).

Accessing one of the oauth URLs directly reports the text "Not Found" in the browser, and removing the `key` parameter reports "No key provided".

**Comment by horaciojcfilho** [comment]
She same problem here :(

**Comment by Diliz** [comment]
Same problem, tried to add a google account on windows 10 insider too :(

**Comment by diddledan** [comment]
this is fixed with the newly minted insider-preview build of Windows 10 number 14342 - It seems the issue was a length limit of 260 characters on any URLs. Longer addresses in previous insider builds refused to open the default browser no matter what browser you have set.

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/willdayble/status/747208980594753536

**Comment by bengotow** [comment]
Saw another incidence of this today on the support channel. I think we should extend the "Login to Gmail" screen in N1 to have a small button that says ("Page didn't open?") and allow people to copy-paste the URL into their browser themselves. As long as the page opens in some browser, the rest of the flow will work.

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
