### ISSUE TITLE
List item option in hover menu?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2035]
Dear all,

How about adding the option to create (un)numbered list items from the hover menu?

![image](https://cloud.githubusercontent.com/assets/170947/14759590/7cfb490c-0928-11e6-88f1-a54dfc749d47.png)

Thankfully,

~Robert

**Comment by Maggew** [comment]
Totally agree, complimentary gmail shortcuts would be a beautiful thing too..

CTRL + SHIFT 7 = ul
CTRL + SHIFT 8 = ol

**Comment by hallamoore** [comment]
Merging into #1975
