### ISSUE TITLE
Surely an error. $7 a month for a client?

### ISSUE THREAD

**Issue by KeironO** [nylas/N1#2037]
Weird bug happened recently. Nylas gave me a error message saying that I'd have to pay $7 a month for client in the future.

Anyone else get this?

**Comment by CrazyLemon** [comment]
Yea same here. Strange really. 
On a more serious note i'd gladly pay 10-15 USD per year if that would be the case of a Pro feature/client but not ~90 USD.

**Comment by khalifeh90** [comment]
Lol. Same note here. I would pay maximum 10 $/y. Sadly going to skip my free 1 year offer and will be looking for another cheaper alternative.

**Comment by mlntr** [comment]
When they stated in the blog Pro would be "affordable", I was thinking it'd be about $10 which I would probably pay.

But $84 for N1 Pro per year? Too much, which is disappointing

**Comment by delixyr** [comment]
@KeironO @CrazyLemon @mlntr @khalifeh90 
I had raised the same issue in twitter.
Go through the replies
https://twitter.com/delixyr/status/723701287813042176

**Comment by ekevjn** [comment]
In my country it cost more than my monthly internet fee (27MB) which is 5$/month.

**Comment by CrazyLemon** [comment]
I read those twitter replies and I don't think they are targeting 'power' users.. I think they are targeting small businesses. Oh well.. We can always build our own N1 from the source.

**Comment by ekevjn** [comment]
Yup, They also do have free plan. It just cost when we use their sync API and
it seen overloaded.

On Apr 23 2016, at 9:51 pm, Dražen M. &lt;notifications@github.com&gt; wrote:  

> I read those twitter replies and I don't think they are targeting 'power'
users.. I think they are targeting small businesses. Oh well.. We can always
build our own N1 from the source.

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2037#issuecomment-213752886)![](https://github.com/notifications/beac
on/AIcl5vJR_fylD2tFGsrM31WfAccpizZEks5p6jHygaJpZM4IOJgt.gif)

**Comment by delixyr** [comment]
> We can always build our own N1 from the source.
Not for everyone.

> They have bills to pay and mouth to feed so they have to get the money invested back.
Not for everyone either. I was looking for sleek email client that works. I use pro versions of Postbox and Mailbird and am ready to pay for Nylas If it's pricing were comparable.

**Comment by grinich** [comment]
Hi folks,

N1 connects to the Nylas sync engine. The free version people have been using costs us a lot of money to run, so we are discontinuing it. (You would too if you saw our AWS bill.) $10/year wouldn't even begin to cover the infrastructure cost for a single user. Why is that?

Apps like Postbox, Mailbird, Airmail, etc. don't have a cloud sync component. While they may share some features with N1, comparing the architecture is apples and oranges. I don't even really consider those apps competitors. We're more focused on collaboration tools for teams and integrating email with other online services. 

The code for N1 will obviously still remain open source and actively developed by us. You can run the [sync engine](https://github.com/nylas/sync-engine) yourself on AWS, DigitalOcean, or even locally. It's all GPL licensed. 

If you don't want to run the open source code yourself, and you don't want to pay for a hosted version, then you're out of luck unfortunately. We can't run a [free beer](http://nylas.com/blog/nylas-pro) company and I'm committed to finding a way to monetize other than showing ads targeted using your private information.
