### ISSUE TITLE
Nylas Does Not Open

### ISSUE THREAD

**Issue by Magnacarter** [nylas/N1#2039]
OS X El Capitan 10.11.3

Nylas Version 0.4.25-a22631a (0.4.25-a22631a)

I install Nylas, move it to the App directory, open Nylas, and the following image is what it looks like when it gets hung. It seems like it's opening the Google Chrome dev console. I've uninstalled and reinstalled Nylas a bunch of times, shut down my machine a bunch of times but to no avail. 

Love Nylas, any help would be appreciated as airmail is getting on my nerves. :) 

Thank you, 
Adam

<img width="872" alt="screen shot 2016-04-23 at 9 02 12 am" src="https://cloud.githubusercontent.com/assets/5139622/14761951/06c2ffa8-0934-11e6-9c8a-e651bb4ddc8e.png">

Errors received in the Chrome console:

<img width="1275" alt="screen shot 2016-04-23 at 9 32 28 am" src="https://cloud.githubusercontent.com/assets/5139622/14762045/cf424b94-0936-11e6-862d-b560fdc64f66.png">

**Comment by Magnacarter** [comment]
Here is a screenshot of the errors that I'm seeing in the Chrome console. 

<img width="1275" alt="screen shot 2016-04-23 at 9 32 28 am" src="https://cloud.githubusercontent.com/assets/5139622/14762026/701acb00-0936-11e6-9fd6-308bc300c0f5.png">

**Comment by mbilker** [comment]
If `~/.nylas` exists, please remove it. It is throwing an error saying it wants an account, but it unable to find one.

**Comment by bengotow** [comment]
That's really interesting—would love to know (before you blow it away), what the contents of `~/.nylas/config.cson` looks like. Any chance you had a very old version installed from a while ago and just upgraded?

**Comment by jstejada** [comment]
possibly related to #2049

**Comment by bengotow** [comment]
In the next update, we're adding assertion checks to the launch process. If N1 encounters bad saved configuration, it'll do it's best to clean up and then you may have to re-link the accounts. Stay tuned!

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!

**Comment by Magnacarter** [comment]
@bengotow Thanks man!
