### ISSUE TITLE
Unable to alter IMAP/SMTP-account's settings after initial setup

### ISSUE THREAD

**Issue by bdalenoord** [nylas/N1#204]
I've received my invitation and immediately configured Nilas to pull from our Exchange-server, which actually works pretty well.

I'm however unable to send emails. The logs don't tell me anything about this failure (they probably should, but thats not my main issue). I think it has to do with the fact that our server requires STARTTLS over SMTP for sending emails, I never saw an option to select this during the initial configuration. The popup with the error contains the following:    
````
Error
Your message could not be sent at this time.
Please try again soon.
                                                                     [ Okay ]
````

I've tried altering my account to see if I could configure STARTTLS there, but I cannot find a way to edit my account. `File -> Preferences -> Accounts` shows my account, with only 1 button called `Unlink`,  I don't think that would solve my problem.

Am I overlooking something? Is it (currently) impossible to edit an existing account?

p.s. Is STARTTLS supported at all? And if it is, it might be an idea to add this to the initial configuration wizard, possibly hidden under an `Advanced`-button or something...

**Comment by Catspyjamas** [comment]
Is STARTTLS supported? :smiley_cat:
