### ISSUE TITLE
All accounts section won't update with new email

### ISSUE THREAD

**Issue by THPubs** [nylas/N1#2040]
If I keep stay in the `All Accounts` section and if an email arrives, I will get a notification but it won't show up in the mail list. If I switch to a account and come back to `All Accounts` it shows up. If I stay in the relevant account, emails are updated perfectly. Please have a look at this.

**Comment by ekevjn** [comment]
I think this cause by Cloud Sync api

**Comment by mbilker** [comment]
@ekevjn No it is a bug unfortunately.

**Comment by jstejada** [comment]
possibly related to #1720

**Comment by jackiehluo** [comment]
Should be fixed now! Closing this issue.
