### ISSUE TITLE
Ability to handle mailto links on Windows

### ISSUE THREAD

**Issue by rakeshdas1** [nylas/N1#2043]
On my Windows 10 machine, when I click on a `mailto` link in Chrome, WIndows 10 comes up with a dialog that allows me to choose which mail client I want to handle this with. But on that list, Nylas is not available as an option nor is there an option to choose a specific .exe. Nylas can handle `mailto` links on Mac OSX flawlessly, but not on Windows for some reason.

**Comment by grinich** [comment]
Definitely a bug--we'll look into it!

**Comment by bengotow** [comment]
Related to #417

**Comment by bengotow** [comment]
Closing into https://github.com/nylas/N1/issues/417
