### ISSUE TITLE
IMAP account: cannot archive email

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2045]
Dear all, 

I don't know if it is a bug or a limitation of the specific IMAP account:

I added a custom IMAP account (non Gmail I assume) for one of my clients. 

From my personal Gmail account I am used to the feature of archiving an email using the `E` key. 

This, however, does not work with conversations from that other account. 

Can anyone advise me how to use the concept of archiving for non Gmail-accounts?

Thankfully,

~Robert

**Comment by bengotow** [comment]
Merging into #1015
