### ISSUE TITLE
Nylas won't open and keeps relaunching

### ISSUE THREAD

**Issue by Federfleisch** [nylas/N1#2049]
Hi there,

Since this morning Nylas won't open and keeps trying to open. All I can see is the launching screen with the message "Please wait while we prepare new features", then it crashes. 

Before last update (0.4.25) everything was going well. I tried rebooting, running with debug flags but nothing worked... 

Is anyone else having the same issue?

**Comment by Federfleisch** [comment]
Here's the screen I have for a short time : https://cldup.com/rq63MpZkgL.png+

In fact, how can I reinstall N1 without losing my mail rules and preferences?

**Comment by mohitkhanna** [comment]
+1

Even i am facing the same issue. It keeps crashing and restarting continuously.

**Comment by fidojones** [comment]
+1 Same problem here

**Comment by mbilker** [comment]
What platform are you running N1 on? This issue appeared before on Linux because of a dependency issue, but it can also occur from a database inconsistency.

**Comment by ryanpineo** [comment]
Having this problem on Arch Linux.  Installed using this https://aur.archlinux.org/packages/n1/.  I have 2 email accounts enabled but the problem only occurs in 1, and only sometimes.

**Comment by mbilker** [comment]
@ryanpineo What version of `freetype2` is installed? You are using 0.4.25 correct, which contains a newer Electron version that fixes the `freetype2 2.6.3` issue.

**Comment by ryanpineo** [comment]
n1 version 0.4.25-1 and freetype2 version 2.6.3-1

**Comment by mbilker** [comment]
@ryanpineo Could you run `/usr/bin/nylas -f` give the in a [gist](https://gist.github.com).

**Comment by Federfleisch** [comment]
I'm on OS X El Capitan (10.11.4).

**Comment by ryanpineo** [comment]
I tried that but I only got 3 lines.  I'm assuming you were expecting more? https://gist.github.com/ryanpineo/26c111fcf97340e4196243c234e13d8d

**Comment by mbilker** [comment]
@ryanpineo Yes more output. Not the output from the `/tmp` files, but from `/usr/bin/nylas -f`.

Should be something like:
```
    at ReactEventListener.dispatchEvent (/usr/share/nylas/resources/app.asar/node_modules/react/lib/ReactEventListener.js:150:20)", source: /usr/share/nylas/resources/app.asar/src/nylas-env.js (315)
[9257:0425/112607:INFO:CONSOLE(379)] "%c %cSCAN TABLE%c Category for %cSELECT%c %c`Category`%c.%c`data`%c %cFROM%c %c`Category`%c   ", source: /usr/share/nylas/resources/app.asar/src/flux/stores/database-store.js (379)
[9257:0425/112607:INFO:CONSOLE(38)] "Backing off after sync failure. Will retry in 3 seconds.", source: /usr/share/nylas/resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker.js (38)
[9257:0425/112609:INFO:CONSOLE(18)] "Window load time: 4482ms", source: file:///usr/share/nylas/resources/app.asar/static/index.js (18)
[9257:0425/112609:INFO:CONSOLE(379)] "%c %cSCAN TABLE%c Category for %cSELECT%c %c`Category`%c.%c`data`%c %cFROM%c %c`Category`%c   ", source: /usr/share/nylas/resources/app.asar/src/flux/stores/database-store.js (379)
```

**Comment by ryanpineo** [comment]
Not seeing anything like that when I run that command.  Only thing I see is this:

```
Streaming log data to /tmp/Nylas-N1-19116.log
App load time: 720ms
WindowManager: Preparing a new 'composer' window
WindowManager: Preparing a new 'composer' window
```

**Comment by adeloscope** [comment]
Same issue -  OSX 10.11.4

**Comment by emorikawa** [comment]
Hey. Thank you everyone for the reports and debug info. We're actively looking into this now.

**Comment by jstejada** [comment]
hmm that's weird that you aren't seeing any other logs @ryanpineo. @Federfleisch or anyone else on mac, could you open a Terminal window and run the following command:
`/Applications/Nylas\ N1.app/Contents/MacOS/Nylas --enable-logging`

That should run Nylas N1 and you should see a bunch of logs in the Terminal window. Could you send those logs in a gist as @mbilker mentioned earlier?

thanks!

**Comment by mohitkhanna** [comment]
@jstejada @mbilker I ran the above command and got logs. Please find them attached. Exception at every point it crashes.
[nylas-crash.txt](https://github.com/nylas/N1/files/235979/nylas-crash.txt)

**Comment by Federfleisch** [comment]
@jstejada Here you go https://gist.github.com/Federfleisch/519e5035400495ee620293a9cef2230a

**Comment by jstejada** [comment]
thanks @mohitkhanna, @Federfleisch , will look into this

**Comment by mbilker** [comment]
@Federfleisch N1 is reporting disk I/O errors. Is anything up with your hard drive? Seems strange that N1 reported that error on your computer, but @mohitkhanna 's log does not report it.

@jstejada Do you know why people keep seeing `navigator is not defined` errors?

**Comment by mbilker** [comment]
I just realized that the `ErrorReporter` is being run from the main process and not the renderer, causing the error.

**Comment by Federfleisch** [comment]
@mbilker Just ran an Onyx test and a "S.O.S" test from Disk Utility, hard drive seems to be okay... Also repaired permissions, erased the app with AppCleaner, reinstalled it but the problem remains.

**Comment by Federfleisch** [comment]
It's weird but I tried downgrading to N1 0.4.19 and it works fine.

**Comment by mbilker** [comment]
@Federfleisch If you do not care about mail rules, nuke `~/.nylas/edgehill.db*`. There may have been an upgrade inconsistency between 0.4.19 and 0.4.25.

**Comment by jstejada** [comment]
@Federfleisch the issue actually seems to be caused by the package `N1-Filters` because it can't find the Less variable `@border-color`. This definitely should not be causing N1 to restart continously, but the N1-Filters package probably needs to be updated. What is the repo for that package? Maybe you can file a PR

**Comment by jstejada** [comment]
@Federfleisch scratch my previous disk I/O comment. I just looked at the logs more closely and it is the same issue @mohitkhanna is having, related to an invalid delta streaming cursor.

It seems N1 is continuously falling back to reading an invalid cursor from your `~/.nylas/config.cson` file causing the app to continuously clear the local database and restart. As a temporary fix, you can remove any cursor fields you have inside your `config.cson` and this should fix the issue. The cursor field should be located here in the file:
```
...
nylas:
  <accountId>:
    cursor: "..."
...
```

We will push a fix to this issue in the next release so it doesn't happen again. @Federfleisch, @mohitkhanna , let me know if this works for you.

**Comment by mohitkhanna** [comment]
@jstejada No problem. I have rolled back Nylas version so not blocked for now. Can't upgrade till the issue gets resolved.

Meanwhile I will try the temp fix you gave and report back.

**Comment by mohitkhanna** [comment]
@jstejada The workaround worked. Nylas working when I removed the cursor config. Thanks!

**Comment by Federfleisch** [comment]
@jstejada Great, works fine too. Thank you!

**Comment by jstejada** [comment]
good to know, we are addressing it in https://github.com/nylas/N1/commit/04cebd51f26540ae435643eac5e4cff51fbc28bf
