### ISSUE TITLE
Broken notifications on Ubuntu 16.04?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2050]
Dear all, 

I also reported the issue on AskUbuntu: [Electron apps no longer show notify-osd notifications on Ubuntu 16.04](https://askubuntu.com/questions/762307/electron-apps-no-longer-show-notify-osd-notifications-on-ubuntu-16-04).

Basically what has happened since my upgrade from Ubuntu 15.10 to 16.04 is that N1 notifications are no longer shown using `notify-osd` but with a default popup dialog box:

![](http://i.stack.imgur.com/RVmjn.png)

Can someone confirm this issue to help me clarify whether this is a general problem and where it stems from?

Thankfully,

~Robert

**Comment by ardhipoetra** [comment]
Ubuntu 16.04 user here, also suffering from the same issue

**Comment by orschiro** [comment]
Dear @ardhipoetra,

Thanks for confirming that!

Do you have any idea whether it's an Electron, N1 or Ubuntu issue?

~Robert

**Comment by bengotow** [comment]
It sounds like this is what you're after: https://github.com/electron/electron/issues/465. Quite an active issue over there!

**Comment by AngelMunoz** [comment]
just to be sure :) same here @bengotow  thanks for pointing that out!

**Comment by orschiro** [comment]
Dear @bengotow,

Thanks! Have you seen [this](https://github.com/electron/electron/issues/465#issuecomment-214302043) comment?

> @philippgerard I'm just going to reiterate. Just because it is fixed here (upstream) doesn't mean that the individual apps that use electron have updated to a version of electron that has the fix....

So, N1 needs to use the updated Electron?

~Robert

**Comment by CrazyLemon** [comment]
Workaround https://github.com/nylas/N1/issues/1897#issuecomment-212327030
Works like a charm and you don't need to wait for anyone to update anything :)

**Comment by bengotow** [comment]
Thanks @orschiro — looks like we've updated Electron on our side, so this should be resolved in the next update to N1 (due out this week.) Cheers!

**Comment by orschiro** [comment]
Thank you @bengotow! 

@CrazyLemon,

What does creating that file exactly do?

Thankfully,

~Robert

**Comment by CrazyLemon** [comment]
@orschiro Well doesn't do much - its a file :)..its something that electron checks if it exists is my guess and if it exits then electron knows its on unity desktop.
Some explanation here https://github.com/electron/electron/issues/465#issuecomment-209049069

**Comment by orschiro** [comment]
@CrazyLemon,

And it actually does bring back `notify-osd` notifications. 

How great! :)

~Robert

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
