### ISSUE TITLE
'Mark as Read' shortcut activated when typing capital I in reply composer

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#2054]
##### Are there any related issues?

Not that I could find using keywords 'shortcuts', 'email', and 'composer'

##### What operating system are you using?
Arch Linux 2016.04.25

##### What version of N1 are you using?
0.4.25-4d38ac63100422bb7a7e8ee303af9c842f55abb7

--

**Bug?**
##### Do you have any third-party plugins installed?
- Cypher

**Description:**
I am applying to college and needed to forward a financial aid message to my parents with a little snippet of text saying I would get to it after school. My reply is 'Will do this when I get home.'. When I typed the 'I' it activated the Gmail shortcut for Mark as Read. I did not expect this, but understand the keymap engine has been worked on since the 0.4.25 release. Please fix.

**Actual Output:**
- Open up email
- Click Forward from dropdown menu
- Enter in contacts to forward the message to
- Type up forward email to family up to a capital I
- Press <kbd>Shift + I</kbd> and the keyboard shortcut for marking as read will activate
- Screen goes back to Inbox

**Expected Output:**
- Open up email
- Click Forward from dropdown menu
- Enter in contacts to forward the message to
- Type up forward email to family
- No activation of keyboard shortcuts
- Click Send

**Comment by emorikawa** [comment]
@mbilker Thanks for the detail! We're seeing this too on our current beta build. I'm working on a fix for this now.

**Comment by mbilker** [comment]
Thanks! Glad to be of help.

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
