### ISSUE TITLE
Various bundled plugins have been removed.

### ISSUE THREAD

**Issue by v4n** [nylas/N1#2055]
Per this [commit](https://github.com/nylas/N1/commit/aab39a12da5c24b34bedf8dbf29b07d8cbac3138) the following plugins that are mentioned on the [readme file](https://github.com/nylas/N1#bundled-plugins) are no longer accessible:
- link-tracking
- open-tracking
- send-later

Is there a new location they should be linked to or should they be removed from the readme file?

**Comment by grinich** [comment]
These don't operate without specific services that we run (in addition to Nylas cloud). They actually will just fail if you build N1 from source, so we removed them to prevent confusion. 

We'll remove them from the readme too. Good eye! 😄 👀 👍
