### ISSUE TITLE
URL preview on hover

### ISSUE THREAD

**Issue by sabihmir** [nylas/N1#2056]
##### Are there any related issues?

No related issues, this is a feature request.

##### What operating system are you using?
Mac OS X El Capitan 10.11.4

##### What version of N1 are you using?
Version 0.4.25-a22631a (0.4.25-a22631a)

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
When viewing an email/thread, it would be great to have a url preview of any hyperlinks in the text. This could be either a pop-up on hover, or using bottom-aligned status bar similar to Chrome.

**Comment by grinich** [comment]
This already happens with a tooltip. Do you not see it if you hover for a few seconds?

**Comment by sabihmir** [comment]
Thanks! There is a tooltip that happens after a few seconds, but it just repeats the text of the link–it doesn't show the URL. So, it's kind of pointless...perhaps that means the feature isn't working as intended?

**Comment by sabihmir** [comment]
This is what I get...

![](https://s3.amazonaws.com/f.cl.ly/items/0b2X2T0o160O3F1j0z1f/Screen%20Shot%202016-04-25%20at%201.25.25%20PM.png)

**Comment by bengotow** [comment]
Hey! It looks like the link in your screenshot already had a `title` attribute, and our autolinker wasn't over-riding it with the link URL. This will be fixed in the next release. Cheers!

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
