### ISSUE TITLE
GTK3 integration with headerbar ?

### ISSUE THREAD

**Issue by Nikoos** [nylas/N1#2058]
Hi team,

Actually I see that Nylas N1 is not using GTK 3 Headerbar, do you plan to support this feature ?

Best regards

Nikos

**Comment by mbilker** [comment]
Are you referring to Client-side Decorations? If so, it depends if Electron gains support for GTK3.

**Comment by mbilker** [comment]
Personally I hate it since it screws with `sway` on wayland. If you know a great way to disable it I am all for it.

**Comment by Nikoos** [comment]
from what I saw on electron's github : https://github.com/electron/electron/issues/2927 there should

**Comment by mbilker** [comment]
That issue shows that `libgtk3ui` is not built and `libchromiumcontent` has basic GTK3 support. It is also an issue in main Chromium and Google Chrome so even more upstream than Electron.

Still blocked on Electron and Chromium.

**Comment by thenets** [comment]
So... It's impossible add GTK3 support? I will realy enjoy.

**Comment by mbilker** [comment]
It is impossible to add unless Chromium adds it to `libchromiumcontent`.
