### ISSUE TITLE
Feature request: copy email address instead of link

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2061]
Dear all, 

When copying a linked email address, it produces something like `mailto:email@domain.com`.

It would be great if that was just `email@domain.com` so that the user could directly paste the clipboard email into a new composing window. 

What do you think?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14808269/32d25092-0b84-11e6-9ac4-c5d58654984d.png)

**Comment by grinich** [comment]
Great suggestion!

**Comment by bengotow** [comment]
This is a great idea and easy to fix. We'll get this into the next release.

**Comment by orschiro** [comment]
Super, thanks!

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
