### ISSUE TITLE
not working on kubuntu 16.04(sync nothing)

### ISSUE THREAD

**Issue by AMirFirouzi** [nylas/N1#2062]
I recently installed kubuntu 16.04 on my laptop and after adding account to Nylas nothing gets synced and actually nothing happens! 
I don't know what is the problem. Im using Nylas version 4.25 and this works fine in ubuntu gnome 15.10.

**Comment by bengotow** [comment]
Hi—can you open the "Activity Window" from the Developer menu and then choose "Toggle Developer Tools" from the Developer menu? Do you see anything there?

**Comment by AMirFirouzi** [comment]
no! nothing! actually this is my whole body tag:


<body class="platform-linux window-type-work">
  


<nylas-popover-container><span data-reactid=".0"></span></nylas-popover-container><nylas-modal-container><span data-reactid=".1"></span></nylas-modal-container><nylas-workspace id="sheet-container" class="sheet-container theme-ui-ubuntu theme-ui-light" tabindex="-1"><div style="flex-direction:column;position:relative;display:flex;height:100%;overflow:hidden;" class="layout-mode-popout" data-reactid=".2"><div name="Toolbar" style="order:0;z-index:3;" class="sheet-toolbar" data-reactid=".2.0"><div style="position:absolute;width:100%;height:100%;z-index:1;" class="sheet-toolbar-container mode-popout" data-reactid=".2.0.$0=2Main=2toolbar"><div style="position: absolute; top: 0px; display: inherit; left: 0px; width: 808px;" class="toolbar-Center" data-column="0" data-reactid=".2.0.$0=2Main=2toolbar.$0"><div style="flex-direction:row;position:relative;display:flex;height:100%;" class="item-container" data-reactid=".2.0.$0=2Main=2toolbar.$0.0"><div name="ToolbarWindowControls" class="toolbar-window-controls alt-false" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$ToolbarWindowControls"><button tabindex="-1" class="close" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$ToolbarWindowControls.0"></button><button tabindex="-1" class="minimize" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$ToolbarWindowControls.1"></button><button tabindex="-1" class="maximize" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$ToolbarWindowControls.2"></button></div><div class="toolbar-menu-control" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$ToolbarMenuControl"><button tabindex="-1" class="btn btn-toolbar" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$ToolbarMenuControl.0"><img class=" content-mask" src="/usr/share/nylas/resources/app.asar/static/images/application-frame/windows-menu-icon@2x.png" style="-webkit-user-drag:none;zoom:0.5;-webkit-mask-image:url('/usr/share/nylas/resources/app.asar/static/images/application-frame/windows-menu-icon@2x.png');-webkit-mask-repeat:no-repeat;object-position:10000px;" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$ToolbarMenuControl.0.0"></button></div><div class="window-title" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.0:$WindowTitle">Activity</div><div class="item-spacer" style="flex:1;order:-50;" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.$spacer-50"></div><div class="item-spacer" style="flex:1;order:50;" data-reactid=".2.0.$0=2Main=2toolbar.$0.0.$spacer+50"></div></div></div></div><span data-reactid=".2.0.1"></span></div><div name="Header" style="order:1;z-index:2;" data-reactid=".2.1"><div style="flex-direction:column;position:relative;display:flex;height:100%;" class="" id="Main" data-reactid=".2.1.0"></div></div><div name="Center" style="order:2;flex:1;position:relative;z-index:1;" data-reactid=".2.2"><div name="Sheet" style="position:absolute;width:100%;height:100%;z-index:1;" class="sheet mode-popout" data-id="Main" data-reactid=".2.2.$0=2Main"><div style="flex-direction:row;position:relative;display:flex;height:100%;overflow:hidden;" data-reactid=".2.2.$0=2Main.0"><div style="flex-direction:column;position:relative;display:flex;height:100%;min-width:0;overflow:hidden;flex:1;" class="column-Center" name="Main:0" data-column="0" data-reactid=".2.2.$0=2Main.0.$Main=20"><div class="developer-bar" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar"><div class="controls" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0"><div class="btn-container pull-left" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.0"><div class="btn" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.0.0"><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.0.0.0"><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.0.0.0.0">Queue Length: </span><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.0.0.0.1">0</span></span></div></div><div class="btn-container pull-left" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.1"><div class="btn" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.1.0"><div title="Account ID 2zmpv5m10trbhvsh6jfuxeq9d - State: undefined" class="activity-status-bubble state-undefined" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.1.0.0:$2zmpv5m10trbhvsh6jfuxeq9d"></div><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.1.0.1">Delta Streaming</span></div></div><div class="btn-container pull-left" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.2"><div class="btn" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.2.0"><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.2.0.0"><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.2.0.0.0">Requests: </span><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.0.2.0.0.1">1</span></span></div></div></div><div class="expanded-section curl-history" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1"><div class="item" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f"><div class="code" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.0"><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.0.0">200</span><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.0.1"></span></div><span class="timestamp" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.1"><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.1.0">14:52:55</span><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.1.1">&nbsp;&nbsp;</span></span><a data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.2">Run</a><a data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.3">Copy</a><span data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.1.$local-a888a3bf-c46f.4">curl -X GET  "https://n1-auth.nylas.com/newsletter-subscription/firouziam%40gmail.com?name=AMir%20Firouzi"</span></div></div><div class="footer" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.2"><div class="btn" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.2.0">Clear</div><input class="filter" placeholder="Filter..." value="" data-reactid=".2.2.$0=2Main.0.$Main=20.0:$DeveloperBar.2.1"></div></div></div></div></div><span data-reactid=".2.2.1"></span></div><div name="Footer" style="order:3;z-index:4;" data-reactid=".2.3"><div style="flex-direction:column;position:relative;display:flex;height:100%;" class="" id="Main" data-reactid=".2.3.0"></div></div></div></nylas-workspace></body>

**Comment by aWdas** [comment]
I can too confirm this issue. 
I installed version "Nylas N1 v0.4.32-1de17e7" from the official .deb-File via dpkg, with no errors or missing packages being reported.

My Body tag is as follows [http://paste.ubuntu.com/16208868/](url)

**Comment by aWdas** [comment]
![image](https://cloud.githubusercontent.com/assets/6359643/14998426/23e1ab86-1184-11e6-9ea4-a56e8f555316.png)

This is the view being presented on Kubuntu 16.04

**Comment by marcociara379** [comment]
same problem here

**Comment by bengotow** [comment]
Hey folks - could you try running the commands below? Do not post your API token, just see if one is returned. I think the problem here is that N1 is trying to store your API token in the system keychain using `libgnome-keyring-dev` and it isn't working.

(Open the developer tools in the main window from Developer > Toggle Developer Tools)

```
$n.AccountStore.accounts()
>> [Account, Account, Account]
$n.AccountStore.tokenForAccountId($n.AccountStore.accounts()[0].id)
>> YOUR TOKEN
```

**Comment by rdig** [comment]
Same problem here.

Kubuntu 16.04
Nylas 0.4.33-e8f137e

Console output:
```
$n.AccountStore.accounts()
>> [Account, Account]
$n.AccountStore.tokenForAccountId($n.AccountStore.accounts()[0].id)
>> null
```

**Comment by AMirFirouzi** [comment]
no! **null** returned!

**Comment by marcociara379** [comment]
I have [account, account] as response for the `$n.AccountStore.accounts()` command, while `Null` for the  `$n.AccountStore.tokenForAccountId($n.AccountStore.accounts()[0].id)`

**Comment by Kuwshi** [comment]
Just want to mention that everything is fine on Ubuntu 16.04, Xubuntu 16.04 and Lubuntu 16.04. 

It's really something with KDE.

**Comment by aWdas** [comment]
It is to be noted that this issue does not occur in OpenSUSE 42.1 Leap running KDE 5.5.

**Comment by Lgmarini** [comment]
Same problem on Manjaro 15.12 (so it isn't limited to Kubuntu).

**Comment by BraisGz** [comment]
Any solution to this??? I have the same problem!

**Comment by phsmith** [comment]
I have the same problem, and the only solution that I've found was install gnome-keyring.
But always, on first N1 opening, the gnome-keyring requests password, what is really annoying.

**Comment by AMirFirouzi** [comment]
> phsmith
you're brilliant! that did the trick! after installing gnome-keyring N1 opens up and synchs mails. and i don't have the password problem like you mentioned.

thanks mate

**Comment by phsmith** [comment]
Thanks @AMirFirouzi! 
Now I'll try to get rid of the password prompts.

**Comment by phsmith** [comment]
If anyone have the gnome-keyring prompts every time like me, the working solution is go to Menu > Accessories > Passwords and Keys (if it doesn't exists, install seahorse), right click on the Default, under Passwords, change the password and set it to blank.

**Comment by Lgmarini** [comment]
Thanks, @phsmith! Installing `gnome-keyring` solved the problem!

**Comment by Maggew** [comment]
I too discovered this problem on Kubuntu 16.02 LTS. I launched up terminal `sudo apt-get install gnome-keyring` but still had the problem. I "Mark for reinstallation" (don't think I had to though) Nylas in Synaptic than removed existing account so I could re-add / authorize. Everything looks smooth and good to go.

Thanks @phsmith

**Comment by abrando** [comment]
Installing `gnome-keyring` and `libgcrypt20-dev` solved the problem for me

**Comment by rdig** [comment]
On my Kubuntu (16.04) install `gnome-keyring` was already installed, yet N1 was still not working.

The solution was to install `libgcrypt20-dev` (as pointed out by @abrando) and remove / re-create all the accounts.

**Comment by protechig** [comment]
Just as a note, I am having the same issues here with KDE Neon (basically a bleeding edge version of KDE built on top of Ubuntu 16.04). Installing `gnome-keyring` and `libgcrypt20-dev` seems to have done the trick. Hopefully this is something that Nylas can fix for users in the future as this obviously isn't ideal for user experience :) Great job finding a fix for this though.

**Comment by bengotow** [comment]
Hey folks—we're adding a warning to the app that tells you when this issue is the source of the problem: http://github.com/nylas/n1/commit/329ea706709401b8ca810b4008f0fc5940ce9bf8. That should make this a bit better.
