### ISSUE TITLE
How can I always launch with "All accounts" view?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2063]
Dear all, 

How can I launch N1 with "All accounts" being the default view?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14810164/c9fe21dc-0b91-11e6-8da0-9c56642849b3.png)

**Comment by jackiehluo** [comment]
You should be launching in that view if you were there when the app was last closed!

**Comment by orschiro** [comment]
Dear @jackiehluo,

Thank you! It means that once switched to "All accounts" view, this view will be preserved across start-ups?

It currently seems to be the case. Not sure why I was reporting this in the first case. I had the feeling it didn't work. 

But for now it does fortunately!

~Robert
