### ISSUE TITLE
Nylas N1 stalls when opening an attachment

### ISSUE THREAD

**Issue by Swoorup** [nylas/N1#2067]
In Linux, whenever opening a attachment, usually a pdf or a docx. I get a message saying that Nylas is not responding!

Could this be due to the single threaded nature of node's V8?

**Comment by bengotow** [comment]
Hey! I think this may actually be due to the fact that `xdg-open` is not returning.  It's been fixed upstream in Electron https://github.com/electron/electron/pull/5072 and will be fixed in the next release of N1.

**Comment by Swoorup** [comment]
That makes sense.

**Comment by bengotow** [comment]
Hey—a fix for this issue shipped in `0.4.32`. You can grab the update from the Releases page, and it should hit the auto-updaters today. Feel free to re-open if you still have trouble!
