### ISSUE TITLE
Unable To Unistall  Nylass

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2070]
##### Are there any related issues?

...

##### What operating system are you using? 10.11.4
...

##### What version of N1 are you using? 0.4.25-a22631a...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? N/A
...

**Comment by oldhickory30** [comment]
Since I'm unable get a resolution / response to my problem #2033 which has rendered Nylas useless since the last update, I am now unable to uninstall Nylas.  Insult on top of injury! When I search for  - ~/.nylas in my home folder there is nothing there hidden or otherwise! And I know its still leaving the Nylas data behind, Suggestions?

**Comment by bengotow** [comment]
Hey! That bug looks like it's been marked as `done-pending-release` so it should be fixed in the next version. You can find more info about uninstalling N1 here: https://support.nylas.com/hc/en-us/articles/216837327-How-do-I-uninstall-N1-. Cheers!

**Comment by oldhickory30** [comment]
When will the next release happen?
