### ISSUE TITLE
Add a phone number and sync with Google Contacts?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2074]
Dear all,

I just discovered N1's really cool profile sidebar widget. :-)

Is it possible to edit a profile directly in N1, e.g. adding a phone number and syncing the change back to Google Contacts?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14843549/7e618050-0c51-11e6-88c9-87e867b7cfed.png)

**Comment by jackiehluo** [comment]
Merging into #1031!

**Comment by orschiro** [comment]
Thanks for merging, @jackiehluo!
