### ISSUE TITLE
Photo Attachment is placed below Signature

### ISSUE THREAD

**Issue by kaspar-allenbach** [nylas/N1#2075]
If I ad a image to a new email it is placed below my signature. And there doesn't seem to be a way to drag the image above the signature.

And I can't even copy the signature below the image. In fact I can't write anything new below the image :(

ersion 0.4.25-a22631a (0.4.25-a22631a)

**Comment by jackiehluo** [comment]
Looks like #968! We don't support inline images in the composer yet, so that's probably the problem you're experiencing (it's only adding the image as an attachment).

**Comment by kaspar-allenbach** [comment]
I see. But that said it is missleading when the image is displayed. I would suggest that you show some sort of attachment icon instead of the real image.
