### ISSUE TITLE
Office365 deletions don't sync across multiple installs of N1

### ISSUE THREAD

**Issue by mikecole79** [nylas/N1#2076]
Are there any related issues?
None that I found.

What operating system are you using?
Ubuntu 16.04

What version of N1 are you using?
0.4.25-a22631a

I'm using N1 on 3 computers, and I use it for two accounts.  The first is my Google Apps account, the second is my work Office365 account.  The Google account appears to be syncing deletions fine across all computers, but I've found that items deleted in N1 on one computer, while being removed from my inbox on the server (when using the browser or Android app) are still appearing in my inbox on the other computers when viewed in N1.

Do you have any third-party plugins installed?
No.

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Appears to only manifest with the office365 account.

Is the issue reproducible with a particular attachment, message, signature, etc?
Any message that has been deleted from N1 on another computer.

**Comment by 3nth** [comment]
Exactly the same issue with Office365 account.

In addition to messages, I'm also seeing folders deleted elsewhere still appear. 

Used Mail.app to delete/archive/move things. Server is synced with Mail.app. N1 is not. 

No third-party plugins. 

Completely removed local N1 data and started setup again, but had no effect.

**Comment by jackiehluo** [comment]
Merging into #781!
