### ISSUE TITLE
Settings/Quick Replies should have sync enabled across computers

### ISSUE THREAD

**Issue by mikecole79** [nylas/N1#2077]
Does this feature exist in another mail client or tool you use?
No, but this would be a very powerful feature.  

Allowing quick replies, and other settings, to sync between computers would allow users to configure N1 exactly how they like on their primary machine, and as they setup the app on other machines, or make configuration changes to improve their experience, it is automatically completed on the other machines as well.  

Suggest default to sync on with an option to turn sync off for people that may want to maintain different configs on one or more machines.

**Comment by jackiehluo** [comment]
Merging into #2484!
