### ISSUE TITLE
Undo Send / Delay sending message

### ISSUE THREAD

**Issue by goeric** [nylas/N1#208]
Would like a button like Gmail Undo Send that lets you undo an email if you select it within a specified number of seconds (5, 10, 15, etc). The way this works is it doesn't actually send the email until after that specified duration, giving you a few seconds to do a final glance and undo if necessary.

**Comment by laughedelic** [comment]
+1

**Comment by zlatkobijelic** [comment]
Yes this would be great to have, Gmail recently turned this 'lab' into a feature, took them a long time, but definitely useful. 

+1

**Comment by mbilker** [comment]
What was it, 4 years for that lab? I remember that thing early after Gmail beta.

**Comment by zlatkobijelic** [comment]
Hahaha yeah it was a REALLY long time. Such a great feature, delay the message for 10 seconds, doesn't seem like it was rocket science, but I guess let google do what google does.

**Comment by bengotow** [comment]
Hey folks! We've landed "Send Later" in the latest release, and undo send will come soon (in a separate GitHub issue). Enjoy!

**Comment by jamiewilson** [comment]
@bengotow It would still be really nice to have a permanent, global delay option on all outgoing mail. I got really used to this with Airmail. Saved me from sending a few hasty and incoherent responses.

**Comment by enoversum** [comment]
@bengotow Did you mean: Undo send will be implemented soon? Don’t get the GitHub issue part, hehe :smile: .

**Comment by xasos** [comment]
@bengotow did this get pushed to a new github issue?
