### ISSUE TITLE
Archive does not actually archive

### ISSUE THREAD

**Issue by saul** [nylas/N1#2081]
Occasionally, when I try to archive selected threads from the inbox, I get the message "Changed labels on X threads". But nothing happens. The threads stay selected, and the UI does not updated to reflect this.

The same happens if I open the thread and hit archive - nothing happens. This is a really crippling bug for me that can only be fixed by restarting N1 :( 

Note that when I restart N1, the threads *have* been archived.

--

##### Are there any related issues?
None that I could find

##### What operating system are you using?
OS X

##### What version of N1 are you using?
Version 0.4.25-a22631a (0.4.25-a22631a)

--

##### Do you have any third-party plugins installed?
No third-party plugins installed.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure - I only use Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Seems to occur randomly.

**Comment by jstejada** [comment]
possibly related to #1720

**Comment by markbao** [comment]
Having a similar issue:

![mbug](https://cloud.githubusercontent.com/assets/27594/14873140/1f294d82-0cc1-11e6-8c48-5616e5220d9e.gif)

**Comment by lazyatom** [comment]
I see this too; I assumed it was some delay between changing the label and actually making the update on the server, but perhaps not.

**Comment by bengotow** [comment]
Hmm - I think there are two separate issues here. If the thread never disappears, it's a front-end UI issue. If the thread disappears and returns, it means the server has rejected the change for some reason...

**Comment by bengotow** [comment]
The first issue (thread never disappearing) should be resolved by 765d9f3. Cheers!

**Comment by bengotow** [comment]
Hey folks—the first issue has been resolved and shipped in `0.4.32`. Grab the update and let me know if you still run in to issues archiving. Cheers!

**Comment by lazyatom** [comment]
It looks like the behaviour I was seeing is also improved. Great!
