### ISSUE TITLE
Archived emails remain in Inbox

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2087]
Dear all, 

Does someone face the same problem that archived emails (i.e. Inbox label being removed) remain in the Inbox?

Below one example.

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14897648/43a14b52-0d83-11e6-8476-5b952dff29e6.png)

**Comment by grinich** [comment]
If you click to a different folder and back, are they still there?

**Comment by bengotow** [comment]
This should be resolved by https://github.com/nylas/N1/commit/765d9f30fc5be75b97e3254d37a6b57fbc341582. Cheers!

**Comment by orschiro** [comment]
So many good fixes awating one in the next release.

Great job guys! :+1: 

~Robert

**Comment by bengotow** [comment]
This should be resolved in `0.4.32`, which we released last night. Feel free to comment and re-open if you still run into this problem. Cheers!
