### ISSUE TITLE
Feature request: use standard keys for pasting without format

### ISSUE THREAD

**Issue by hfossli** [nylas/N1#2088]
In most apps (all I know of) I'm able to paste stuff with cmd+alt+shift+v. In Nylas N1 this is cmd+shift+v. Could you also support the standard one?

**Comment by bengotow** [comment]
Hey! Is this on Windows or Linux?

**Comment by bengotow** [comment]
![image](https://cloud.githubusercontent.com/assets/1037212/14898993/c8198c7c-0d3e-11e6-8eb0-1825e67d018b.png)

Looks like you're right that it's wrong on Mac OS X. Fixing now.

**Comment by hfossli** [comment]
Thank you so much
