### ISSUE TITLE
Links that contain an email address are parsed with mailto: in front of the link

### ISSUE THREAD

**Issue by tweemeterstudio** [nylas/N1#2090]
##### Are there any related issues?
I couldn't find any.
...

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4..25

--

**Bug**
##### Do you have any third-party plugins installed?
No, default install

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail, but maybe other providers have the same problem as it seems to be something that N1 does.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Send an email containing a link like this:

https://www.freecodecamp.com/unsubscribe/your-email-address@gmail.com

And the link is parsed by N1 like this: [screenshot](http://i.imgur.com/m8hoDPZ.png)

While on Gmail.com it's correct: [screenshot](http://i.imgur.com/IbmUFU6.png)

**Comment by bengotow** [comment]
Thanks! This is a dup of #2071
