### ISSUE TITLE
Windows Resizing - OS X

### ISSUE THREAD

**Issue by scratchfive** [nylas/N1#2092]
Quitting and relaunching N1 results in the window size to be reset to the default. In the two pane view, sizing is also reset. Previous versions did not seem plagued by this issue (see version information below). 

Running version 0.4.25-a22631a 

OS version: OS X 10.11.4 El Capitan

**Comment by bengotow** [comment]
Hey! Are you able to reproduce this on 0.4.32. I've been able to get this to happen, but only when forcing N1 to exit (rather than quitting it gracefully.)

**Comment by jackiehluo** [comment]
Merging into #1831!
