### ISSUE TITLE
Incorrectly display Inbox Zero page when using Inbox shortcut from Drafts

### ISSUE THREAD

**Issue by KevinMartin** [nylas/N1#2094]
##### Are there any related issues?
Not that I could find.

##### What operating system are you using?
OS X El Capitan

##### What version of N1 are you using?
0.4.25-a22631a

**Bug?**
##### Do you have any third-party plugins installed?
Yes.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
To reproduce:
1. Click on Drafts
2. Then ⌘+1

Expected Result: Highlight Inbox in sidebar, display emails in Inbox
Actual Result: Highlight Inbox in sidebar, display Inbox Zero sheet

If I click on Inbox on the sidebar, the correct expected result occurs. The problem lies with the keyboard shortcut (⌘+1) or selecting the account from the Window menu in the menubar.

I only have one account, so not sure if it happens with multi-account setups.

**Comment by bengotow** [comment]
Hey thanks for reporting this! We should be able to get this fixed for the next release tonight.

**Comment by bengotow** [comment]
This should be resolved in `0.4.32`, which we released last night. Feel free to comment and re-open if you still run into this problem. Cheers!
