### ISSUE TITLE
Feature Request: Allow color coding of email accounts so it's more apparent which email an account comes from when viewing a "unified" message list.

### ISSUE THREAD

**Issue by hickeroar** [nylas/N1#2096]
I currently have three email accounts added to N1. When I have multiple messages from each account displaying in the "unified" view, it's not immediately apparent which account an email comes from when viewing the full list.

The ability to choose a color for each account and have those messages either bordered by that color, with a light background color matching that account, or some other indicator, would be fantastic.

**Comment by jackiehluo** [comment]
Merging into #1677!
