### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by BeamerCola** [nylas/N1#21]
Gone through the bootstrapping, the package installing, but I can't get it to compile :-/

Right now getting:
```
script/grunt build
Running "build" task
Fatal error: Cannot copy non-existent electron/Electron.app to /var/folders/7v/fbqlxxbs0_30s0cbbzlcnkr80000gn/T/nylas-build/Nylas.app
```

Electron seems to be working fine

**Comment by b-e-r-t-o** [comment]
Also having this issue. Would be great if the docs could include a clear way to build/compile on Mac.

**Comment by b-e-r-t-o** [comment]
@BeamerCola Could you explain the bootstrapping and package installing?

**Comment by BeamerCola** [comment]
i poked around in there for a while.  tried a bunch of stuff.  but installed the node packages and the instructions in the /build directory.  But not sure what else to do.  Really want to start building a plugin this week!

**Comment by chibipirate** [comment]
@BeamerCola Same here.

**Comment by bengotow** [comment]
I'll expand our CONTRIBUTING.md page to include more details about compiling the app. This should do the trick:

(ensure you're using Node 0.10.x)

```
script/bootstrap
script/build
````

If you encounter errors, let me know and we can refine the scripts.

**Comment by gonchs** [comment]
I'm having the same error on OSX

```
➜  n1 git:(master) script/grunt build
Running "build" task
Fatal error: Cannot copy non-existent electron/Electron.app to /var/folders/tv/gj78ny1x0zl6b5lkn7ncbsr00000gn/T/nylas-build/Nylas.app
```

even after running:
```
script/bootstrap
script/build
```

**Comment by gonchs** [comment]
I suppose the issue is that there is not electron/Electron.app inside of the root directory because it's [ignored in .gitignore] (https://github.com/nylas/N1/blob/86b6cee8945ada77dda1b286f7bc05f39be1d205/.gitignore#L15)?

**Comment by mainiak** [comment]
@bengotow you might consider to use https://github.com/creationix/nvm or similar

**Comment by bengotow** [comment]
Hey folks,

Hmm - running script/bootstrap is supposed to install the correct version
of Electron in ./electron. It's .gitignored so the git repo doesn't grow
out of control as we upgrade to new versions of Electron (it's about 60MB!)

Does running script/bootstrap give you any errors? If it finishes and you
don't have an Electron app in that folder something is definitely up.

**Comment by sstur** [comment]
I manually downloaded Electron and dropped it in the electron directory and then the build succeded but after putting the built App into /Applications it crashed upon first open. I am running Node v0.12 so maybe I need to use v0.10 but not in a hurry to downgrade. Will use the pre-built app for now.

**Comment by gonchs** [comment]
I overlooked that it requires Node 0.10.x. Installed it and now it works.

**Comment by emorikawa** [comment]
Hey all. This actually got fixed largely due to @mbilker's pull request https://github.com/nylas/N1/pull/49 and a few other changes. `script/bootstrap` now works on Node 0.10, 0.12, and 4.x
