### ISSUE TITLE
Config.json ignored

### ISSUE THREAD

**Issue by OliverCole** [nylas/N1#2102]
##### Are there any related issues?
None that I can see!

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
Latest.

**Bug**
I'm following the instructions for a local sync engine on https://github.com/nylas/N1/blob/master/CONFIGURATION.md.

However, the N1 client doesn't seem to be affected by the contents of `%USERPROFILE%\.nylas\config.json`:

```javascript
{
 "*": {
   "env": "local",
   "nylas": {
	 "accounts": [
	   {
			"account_id": "REDACTED",
			"email_address": "REDACTED",
			"id": "REDACTED",
			"name": "Oliver Cole",
			"object": "account",
			"organization_unit": "label",
			"provider": "REDACTED",
			"sync_state": "running"
		},
	 ],
	 "accountTokens": {
	   "REDACTED": "REDACTED"
	 }
   }
 }
}
```

When I start the client I get the standard account chooser:

![nylas](https://cloud.githubusercontent.com/assets/6171713/14962730/3f54c822-1098-11e6-9c30-908b5b87c64b.png)

I'm hesistant to go through the normal setup because I don't want to authorise the Nylas cloud to my account!

`inbox-start` and `inbox-api` are running in Vagrant - notably the latter shows no traffic when I start the client.

**Comment by bengotow** [comment]
Hey! Thanks for filing this—unfortunately we updated the docs on Thursday of last week to match a change we made to the app's configuration handling, but the release hasn't shipped yet (it should ship later today.) In the meantime, you'll need to edit `config.cson`, which is the old format we're deprecating today. Sorry for the hassle!

**Comment by OliverCole** [comment]
I'll hang tight for the new version. Just run Nylas as normal for the update?

**Comment by bengotow** [comment]
Hey! This should be resolved now in 0.4.32.

**Comment by bengotow** [comment]
Hey @OliverCole  do you still get the account chooser when you start the app, or something else?

**Comment by bengotow** [comment]
Can you also be sure to delete any `config.cson` file in that folder? (Different extension)

**Comment by OliverCole** [comment]
I do, same as screenshot.
There's no config.cson in .nylas.

**Comment by bengotow** [comment]
Hey! Ahh you know what, looking at your JSON again, I think there might be a trailing comma that is causing a parse issue:
```
 "sync_state": "running"
        }, <<<
     ],
```

Can you try removing that? I'll also see if we can fix the app so that this generates a much louder error.

**Comment by OliverCole** [comment]
Yup, that was it! I honestly thought that was valid JSON.

Perhaps the ultimate solution is not to make the user mess with the config at all... I guess it depends on where this tier is really pitched :)

**Comment by bengotow** [comment]
Definitely. I just pushed 2b7f3252de888a0cc362a05fac0e08c60321de5f and in the future we'll be sure to make JSON parsing errors throw up an error box! Thanks—
