### ISSUE TITLE
No Notifications for Mac

### ISSUE THREAD

**Issue by joshzhe07** [nylas/N1#2103]
##### Are there any related issues?

...

##### What operating system are you using?
...
OSX
##### What version of N1 are you using?
...
0.402
--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
No
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Are you running the compiled version of N1? Do you see anything for N1 in System Preferences > Notifications?

**Comment by joshzhe07** [comment]
> Hey! Are you running the compiled version of N1? Do you see anything for N1 in System Preferences > Notifications?

Thanks for replying, I found out why. I was just being dumb xD. I do have one question though, will there be an iOS app? Because it doesn't mark my emails as read on my phone in the Mail app when I open them in N1 on my mac.

**Comment by markogresak** [comment]
If you've figured out your problem, you should close this issue.
As for the mobile app, it was asked many times before. Sadly, [it's not happening](https://github.com/nylas/N1/issues/311#issuecomment-153166028).

**Comment by joshzhe07** [comment]
Then is there some way to mark messages read in my mail app when I do it in Nylas?

**Comment by jstejada** [comment]
Hi @joshzhe07, your email should definitely be marked as read in your mail app when you mark it as read in N1. There have recently been an increased amount of failed sync actions, and we are tracking that issue here: #2059. So i'm merging this into that issue
