### ISSUE TITLE
Difference between Copy Link and Copy?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2105]
Dear all, 

What's the difference between Copy Link and Copy when clicking on a link?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14976401/b89a5274-110b-11e6-97f7-d830926b985f.png)

**Comment by sanjeevverma1** [comment]
Take the following hyperlink, for example: <a href="www.google.com">Google</a>

I could highlight the hyperlink and "Copy Link" if I want to add "www.google.com" to my clipboard, or I could "Copy" if I want to add "Google" to my clipboard. One is for copying a link, whereas the other is for copying the displayed text, BUT sometimes, for example with a YouTube URL like above, the link and the displayed text are the SAME...mind-blowing, I know. 

Btw @orschiro this is a better question to post on StackOverflow or in the Slack channel. Only post "issues" (bugs, feature requests, etc.) related to N1 here.

**Comment by bengotow** [comment]
Hey! Yep - I think in this case there isn't any difference, but one would be the link URL and the other would be the link text (if they were different.) I'm going to change this to say `Copy Link Address` for consistency with Chrome and other browsers - hopefully that will resolve the confusion.

**Comment by orschiro** [comment]
>  I'm going to change this to say Copy Link Address for consistency with Chrome and other browsers - hopefully that will resolve the confusion.

Yes, that does make it more clear, thank you!

~Robert
