### ISSUE TITLE
Mark as spam icons not displaying

### ISSUE THREAD

**Issue by imapirate** [nylas/N1#2107]
Same on toolbar as sidebar. Running v 0.4.32-1de17e7.

<img width="433" alt="new issue nylas-n1 safari today at 11 53 26 am" src="https://cloud.githubusercontent.com/assets/2443826/14979931/cd45b3fc-1125-11e6-8671-88868dc63232.png">

<img width="118" alt="nylas n1 nylas n1 today at 11 54 01 am" src="https://cloud.githubusercontent.com/assets/2443826/14979936/d40b131c-1125-11e6-9c0d-8794fb827f7c.png">

**Comment by jackiehluo** [comment]
@imapirate Oh, that is the icon! 😶

**Comment by bengotow** [comment]
Haha oh man—we definitely need to change that icon (cc: @sdewith).

**Comment by imapirate** [comment]
At least the "x" reminds you of nasty stuff 😄

**Comment by bengotow** [comment]
We've changed the icons to be little thumbs-up / thumbs-down, which I think will be more clear. Cheers!

![image](https://cloud.githubusercontent.com/assets/1037212/15132172/98c0beac-160b-11e6-8b21-c56241b57e29.png)


![image](https://cloud.githubusercontent.com/assets/1037212/15132173/9bc29c9c-160b-11e6-957d-17150950f032.png)
