### ISSUE TITLE
Auto-remove empty lines?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2109]
Dear all, 

Just an idea that I had:

Would it be possible for N1 to auto-detect and remove empty (useless) lines such as shown in the below example (the lines between `~Robert` and `...`)?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14988699/5c657886-1155-11e6-9918-231d3ae7047d.png)

**Comment by jackiehluo** [comment]
@orschiro I don't think there will be any lines sent there! It's just padding.

**Comment by orschiro** [comment]
Oh, that's actually great then. 

Thanks @jackiehluo! :smiley: 

~Robert
