### ISSUE TITLE
Feature request: mark email in junk folder as 'not junk'

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2112]
##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.32

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes

I have an email in my iCloud junk folder that I want to move to the inbox and make sure it is not marked as junk for future email.  Today I do not see a way to do this, though I do see a way to mark an email as junk in the inbox folder.

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!

**Comment by johnchourajr** [comment]
@jackiehluo I don't know if the "Remove from Junk" button issue has been addressed.
