### ISSUE TITLE
Bring back the Archive button on selected threads

### ISSUE THREAD

**Issue by sollymay** [nylas/N1#2114]
After the last update, the archive button dissapeared from the selected thread. I can't archive multiple messages at the same time with the convenience I used to have before.

Bring this feature back so that we can go to inbox 0 really fast!!

**Comment by jackiehluo** [comment]
@sollymay Hey! Can you add a screenshot (`Developer -> Toggle Screenshot Mode`)? You should be able to select threads and archive them as you did before!

**Comment by sollymay** [comment]
I was able to fix it.

  

Apparently there was a thread that showed on my inbox that was not
"archivable" and was not letting me archive multiple emails at the same time.

  

You can now mark it as closed.

  

Best,

  

Salomon.

  

Sent from [Nylas N1](https://link.nylas.com/link/ejg5mh00zu79xwfmhbchm8cs8
/local-4a7db21c-debe/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1), the
extensible, open source mail client.  

![](https://link.nylas.com/open/ejg5mh00zu79xwfmhbchm8cs8/local-4a7db21c-debe)

On May 3 2016, at 1:52 pm, Jackie Luo &lt;notifications@github.com&gt; wrote:  

> [@sollymay](https://github.com/sollymay) Hey! Can you add a screenshot
(Developer -&gt; Toggle Screenshot Mode)? You should be able to select threads
and archive them as you did before!

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2114#issuecomment-216610572)![](https://github.com/notifications/beac
on/AGMhuujV25discm-eYrXKQfWTqw9FqV_ks5p94s6gaJpZM4IWdWD.gif)

**Comment by jackiehluo** [comment]
Cool, sounds good!
