### ISSUE TITLE
Batch snooze emails

### ISSUE THREAD

**Issue by osakkers** [nylas/N1#2115]
I can only snooze one email at a time. Would be helpful to be able to snooze a whole batch at the same time rather than having to to do them one-by-one.

Similarly, it would be great to have a snooze shortcut - doesn't seem to be anything right now. 

Btw, snooze functionality of typing in preferred snooze time in very helpful!

**Comment by osakkers** [comment]
Also: It would be helpful to edit snooze defaults including Next Week (my week starts Sunday), Tomorrow (what time), etc. Thanks!

**Comment by jackiehluo** [comment]
@osakkers You should be able to snooze multiple emails at a time! Also, keyboard shortcut's landed on master, so you'll see that in the next release!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
