### ISSUE TITLE
Read emails on Nylas not showing up as read in Gmail

### ISSUE THREAD

**Issue by joshzhe07** [nylas/N1#2116]
I have a mac on el capitan, running nylas 0.4.32-1de17e7. When I mark something as read, it doesn't mark as read on gmail or anywhere else, just in Nylas. I can see my sent mail, that all syncs perfectly, just not marked as read. 
Thanks for helping!

EDIT: When I use Nylas to mark as unread, Gmail shows it as unread, as well as other mail applications. When they are marked read in Gmail however, Nylas does not mark them as read.

**Comment by bryan** [comment]
I'm having a different issue where I can mark the Gmail as unread and Nylas will update itself afterwards to be unread, but can't seem to archive or mark as unread in Nylas to propagate and sync with Gmail's.

**Comment by Pete5x5** [comment]
Same issue: when you read an email in Nylas it as marked as read in Nylas, but Gmail's copy (and other web email services using IMAP) remains unread.

**Comment by thrav** [comment]
This only started for me today. As far as I know, it was not the case yesterday. (El Cap 10.11.4 w/ gmail)

It seems like it may just be a lag more than a defect. As I was typing this, 2 of the read messages successfully synced to read in gmail, and the third sent nylas version back to unread to match gmail.

**Comment by Pete5x5** [comment]
Doesn't seem like lag for me.  I gave it a good 15 mins, restarted the client (Windows 10) and manually synced Gmail's inbox and refreshed page.  Still unread.  Not just Gmail though, I have the same issue with another IMAP server as well.

**Comment by loserock** [comment]
I have the same problem on Ubuntu 16.04 with Nylas N1 0.4.33-e8f137e.
The read/unread flag sync works well from Gmail to Nylas, but not from Nylas to Gmail!
However, also works well with an exchange account.

**Comment by jstejada** [comment]
Hi everyone, thanks for reporting this. This is a known issue and is currently being tracked in #2059. We are currently working on a fix. I'll leave this issue open for now and post any updates soon

**Comment by jstejada** [comment]
Hi everyone, thanks for reporting this. This is a known issue and is currently being tracked in #2059. We are currently working on a fix. I'm going to merge into #2059, and will post any updates there. Thanks! -- Sorry for the hassle
