### ISSUE TITLE
script/build fails at Running "compile-packages-slug" task

### ISSUE THREAD

**Issue by cfriedline** [nylas/N1#2118]
##### Are there any related issues?

No

##### What operating system are you using?
OSX 10.11.4
##### What version of N1 are you using?

git master a08eb3e

**Bug?**
##### Do you have any third-party plugins installed?
N/A

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
`script/build` fails at this point:

```
Running "cson:glob_to_multiple" (cson) task
>> 0 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task
Warning: Unable to read "/private/var/folders/_8/hgx0kq1j3m10dyjq912_943c0000gn/T/nylas-build/Nylas N1.app/Contents/Resources/app/internal_packages/quick-schedule/package.json" file (Error code: ENOENT). Use --force to continue.
```
Even happens if I run `script/clean` first.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
N/A

**Comment by bengotow** [comment]
Hmm - can you try deleting `internal_packages/quick-schedule`, or running `git clean -xdf` to totally reset your working copy?  That folder (`quick-schedule`) shouldn't exist anymore, so it looks like it's being thrown off by the empty directory.

**Comment by cfriedline** [comment]
Perfect - that was it: an old working copy of the repo.  `git clean -xdf` took care of it.  Thanks!
