### ISSUE TITLE
I installed the latest version 0.4.32 yesterday, I realized today that although the send later plugin is activated the software is not able to send mails later. 

### ISSUE THREAD

**Issue by jsamwini** [nylas/N1#2119]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by KevinMartin** [comment]
Dupe of #2106

**Comment by bengotow** [comment]
Closing as dup of #2106 - this will be fixed in a patch tomorrow morning!
