### ISSUE TITLE
AccountSwitcher customization

### ISSUE THREAD

**Issue by xedef** [nylas/N1#212]
I have two accounts: 
  . myname.mylastname@gmail.com
  . myname.mylastname@mycompany.com

Account switcher shows both as "myname.mylastname@..." and with the same GMail icon.

It would be great if we can change the icon and customize the label for the switcher.

**Comment by JustinTBrown** [comment]
I have this same issue also. Whether I select an account via the dropdown or use the key commands (CMD+1, CMD+2, etc.) the account label stays the same. Appears to be the same issue as #433.

**Comment by MaestroDarius** [comment]
What I feel **xedef** is suggesting is just being able to customize the names and icons of the email accounts in the switcher.

Whereas what **JustinTBrown** says is, indeed, the issue described under #433.

**Comment by jstejada** [comment]
Hey all! We've landed an option on the latest release to customize the display name or "label" for your account, so it should help you out @xedef .

**Comment by xedef** [comment]
Awesome @jstejada! I'll give this a try right away!
Thanks!
