### ISSUE TITLE
Can't click links in Windows N1

### ISSUE THREAD

**Issue by DavidCA916** [nylas/N1#2120]
##### Are there any related issues?
Not that I can find.

##### What operating system are you using?
Windows 10 Pro

##### What version of N1 are you using?
0.4.32

--

**Bug?**
##### Do you have any third-party plugins installed?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, I can't click links from Indeed.com or Quora Digest emails. I have to right-click, copy link, then paste into my browser. Clicking the link does nothing.

**Comment by jstejada** [comment]
Hi @DavidCA916 , I was testing this on a windows 10 machine but I am not able to reproduce. When I click a link it opens up Edge and loads the page. However, it doesn't bring the browser to the foreground. Is this the behavior you are having?

**Comment by DavidCA916** [comment]
@jstejada No, it doesn't open anything at all.
