### ISSUE TITLE
Feature Request: Toggle Track Views and Clicks by Default

### ISSUE THREAD

**Issue by manicmarvin** [nylas/N1#2123]
**Feature Request**

Can users set whether they _want_ their emails tracked by default or not? 

Currently, if I was a user who didn't want my emails to send me tracking information in general, I'd have to uncheck the tracking icon before sending _every_ mail.

##### Does this feature exist in another mail client or tool you use?

Polymail. But everything but this and the UI, makes Polymail somewhat unusable.
...

**Comment by jackiehluo** [comment]
@manicmarvin Interesting, what do you mean? If you toggle the open/link tracking icons in the composer, they should stay on or off. Beyond that, you can disable the plugins in the preferences if you don't think you'll ever use them.

**Comment by manicmarvin** [comment]
The behavior you describe doesn't seem to be working for me.  
  
I just tested it by:

  

  1. Composing and sending a mail to johndoe@hello.com with Open and Link tracking turned off.
  2. I composed a new mail to janesmith@goodbye.com, both Link and Open tracking were turned on when I started to type the mail. I had to turn it off manually.

[I thought maybe N1 is configured to remember my Open Tracking /Link Tracking
preferences based on **each recipient**.]

  * I tried to send a _new_ mail to johndoe@hello.com. Open tracking and Link tracking were still enabled and I had to manually turn them off again.

[Now I’m thinking maybe N1 is configured to remember my Open Tracking / Link
Tracking preferences for **each thread**.]

  * Tried to reply to my original email to johndoe@hello.com (the one with tracking disabled). Tracking was still enabled by default in my reply.

  

Is this problem with my build?

  

Avinash Kuduvalli

[avinashkuduvalli.com](https://link.nylas.com/link/dxpsv4bjo476bcij3y11ef5lh
/local-a52eed60-c83e/0?redirect=http%3A%2F%2Favinashkuduvalli.com%2F)

  
Sent from [Nylas N1](https://link.nylas.com/link/dxpsv4bjo476bcij3y11ef5lh
/local-a52eed60-c83e/1?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1),  
the extensible, open source mail client.

  

![](https://link.nylas.com/open/dxpsv4bjo476bcij3y11ef5lh/local-a52eed60-c83e)

On May 4 2016, at 12:12 pm, Jackie Luo &lt;notifications@github.com&gt; wrote:  

> [@manicmarvin](https://github.com/manicmarvin) Interesting, what do you
mean? If you toggle the open/link tracking icons in the composer, they should
stay on or off. Beyond that, you can disable the plugins in the preferences if
you don't think you'll ever use them.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2123#issuecomment-216759225)![](https://github.com/notifications/beac
on/AKcj6OgXsll9BahN9OuBXgLPTp8m-BsQks5p-D_egaJpZM4IW3Gl.gif)

**Comment by bengotow** [comment]
I can confirm that unchecking link / open tracking is not setting the defaults back to "off". Looking into it.

**Comment by bengotow** [comment]
Thanks for filing this, we'll have this fixed in a patch going out today.

**Comment by bengotow** [comment]
Hey! This has been fixed in the `0.4.33` release earlier today. Enjoy!
