### ISSUE TITLE
Unable to delete or Archive Emails using Keyboard shortcuts

### ISSUE THREAD

**Issue by spetz83** [nylas/N1#2127]
##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 16.04
##### What version of N1 are you using?

0.4.32-1de17e7
--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Merging into #2126
