### ISSUE TITLE
Add signatures

### ISSUE THREAD

**Issue by xedef** [nylas/N1#213]
It would be great to have an HTML signature per account

**Comment by bryan** [comment]
I believe they have people already working on it.
Check out their roadmap: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

Duplicate of https://github.com/nylas/N1/issues/1

**Comment by bengotow** [comment]
Hey folks—signatures are landing in a release later this afternoon (0.3.26). Enjoy!
