### ISSUE TITLE
Feature request: Replying to thread of emails

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2130]
I have a thread of emails, I reply to the last email and I get a reply email.

When I now reply N1 creates the new email but directly above this is my last response and not the latest email in the thread which is my customers last reply.  Making not so easy to refer to the response if the email are long, cuz it take scrolling up & down.

If I have a thread of emails where I've had no response I get the last email just above the new blank email.  Which is OK, cuz you need it for reference

It would be easier if the latest (no matter the sender) email is display directly above the new blank email

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.32

**Comment by bengotow** [comment]
Hey! Just want to make sure I understand correctly. Are the messages in N1 properly sorted by time, or are you seeing other sorting? You should see:

```
A: (Received Wednesday)
B: (Sent Thursday)
C: (Sent Friday)
D: Your new draft
```

Are you wanting to see this?

```
B: (Sent Thursday)
C: (Sent Friday)
A: (Received Wednesday)
D: Your new draft
```

**Comment by molstrangler** [comment]
Hi,

What I saw was:

```
B: (Sent Thursday)
C: (Sent Friday)
A: (Received Wednesday)
D: Your new draft
```

I wanted the email listed as it you suggested it should be.

I'll close this issue and if it happens again I will reopen it, cuz I can't recreate it.
