### ISSUE TITLE
Feature request: Remove gemstone Bejeweled-like checkmark for empty inbox

### ISSUE THREAD

**Issue by arisbanach** [nylas/N1#2133]
I would love it if you could remove, or add an option to remove, this check mark.

<img src="http://i.imgur.com/iIob0ZF.png">

I don't think it fits with the design at all. The graphic looks like it came from Bejeweled, while the rest of the app is amazing.

**Comment by bengotow** [comment]
Thanks for the feedback! There are five different ones and the app cycles through them. Some are more playful than others. If you want, you could create a theme to hide them but this would definitely be best implemented as a plugin.
