### ISSUE TITLE
Use something other than Slack?

### ISSUE THREAD

**Issue by HammyHavoc** [nylas/N1#2139]
Hey,

Love Nylas, but was wondering if you had considered using an open-source alternative to Slack-- considering Nylas N1 is an open-source email client, it makes sense to use something like RocketChat to talk about the project.

**Comment by bengotow** [comment]
Hey—thanks for posting this! Our team uses Slack for internal communication as well, so using it for the open source community means that the whole team actually checks it day-to-day. We'll definitely consider switching in the future if it becomes an issue for potential contributors. Cheers!

**Comment by rht** [comment]
Zulip? e.g. https://www.recurse.com/blog/112-how-rc-uses-zulip
