### ISSUE TITLE
Ubuntu Gmail 2step verification sync fail

### ISSUE THREAD

**Issue by mitjafelicijan** [nylas/N1#214]
I have 2 step verification enabled (if maybe that is an issue) and I am having problems with syncing of Gmail account. All I get is an error shown below. 

![screenshot from 2015-10-27 06-31-02](https://cloud.githubusercontent.com/assets/296714/10750320/4f6eae5c-7c74-11e5-9384-58e187b55e73.png)

**Comment by loveevelyn** [comment]
I'm on Mac, same sync error, also have 2 step verification on. Seems like the common factor.

**Comment by Typositoire** [comment]
Got the same issue here. And I do have 2factor auth. Not sure it's OS related I'm on MAC OS El Capitan.

**Comment by mitjafelicijan** [comment]
[Resolved]

  

After installation I added two accounts: Exchange and Gmail. I than removed
Gmail account because of sync error. And when my Exchange account got synced I
added Gmail account again and everything works now.

  

I guess you can only perform initial sync with one account. And as soon as one
is synced you add another. That would be my observation.

> On Oct 27 2015, at 1:50 pm, Yann David &lt;notifications@github.com&gt;
wrote:  

>

> Got the same issue here. And I do have 2factor auth. Not sure it's OS
related I'm on MAC OS El Capitan.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/214#issuecomment-151481023).![](https://github.com/notifications/beac
on/AASHCswjLeLe60RujYuhHobY3yfolkEoks5o_2qdgaJpZM4GWNp_.gif)
