### ISSUE TITLE
Dark Side Theme - Toolbar icons overlay email search

### ISSUE THREAD

**Issue by phaugstad** [nylas/N1#2140]
I changed my theme to the 'Dark Side' option.  If an email is selected, the toolbar icons to delete, archive, etc overlay the email search option.  Here is an example:

![image](https://cloud.githubusercontent.com/assets/16250438/15034880/588f23ec-1240-11e6-8bf3-a7309da9094e.png)

I have using version 0.4.33.  Please let me know if you have any questions.  Thank you.

**Comment by jackiehluo** [comment]
Cool, thanks for letting us know! Fixed and will be out in the next release.

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
