### ISSUE TITLE
How to change the behaviour of swipes on a touch-screen?

### ISSUE THREAD

**Issue by HammyHavoc** [nylas/N1#2141]
Hey,

Really starting to dig into what Nylas API is capable of, but stumped by a simple thing; looking for an option in Preferences to change what the left and right touch swipe on each email does; I want to turn archiving into deleting for a specific account, or just in general; is there a facility to do this?

**Comment by KevinMartin** [comment]
Not at the moment. There is another issue following this feature though: #1448
