### ISSUE TITLE
Debug flags do not enable without restarting

### ISSUE THREAD

**Issue by colinking** [nylas/N1#2142]
I'm attempting to install a plugin in the `~/.nylas/dev/packages` folder, however N1 doesn't appear to detect the package. I have enabled debug flags, yet the plugins preference panel doesn't appear to update to reflect this. The plugin I was attempting to install also does not show up (as seen in the photo below).

##### What operating system are you using?
Mac OS X 10.11.4

##### What version of N1 are you using?
0.4.33

##### Do you have any third-party plugins installed?
No

![image](https://cloud.githubusercontent.com/assets/2907397/15036424/93830bbe-125c-11e6-9b8c-6ec6eeb3730b.png)

**Comment by colinking** [comment]
Weird, N1 is now registering that debug flags are on. A restart may have been what fixed this issue.

**Comment by colinking** [comment]
So it seems that toggling the debug flags from the menu (which causes N1 to reload) does not cause N1 to detect new packages or update the plugin window to display that the flags are enabled. 

In order to get the debug flags to properly turn on, N1 appears to require a restart.

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
