### ISSUE TITLE
While typing a quick response, ⌘+A selects all threads in left pane

### ISSUE THREAD

**Issue by nienque** [nylas/N1#2145]
##### Are there any related issues?
Couldn't find any.

##### What operating system are you using?
El Capitan 10.11 Beta (15A279b).

##### What version of N1 are you using?
Version 0.4.33-e8f137e (0.4.33-e8f137e).

--

**Bug?**
##### Do you have any third-party plugins installed?
Only the default ones.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, it occurs with all of my accounts.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Navigate to the inbox (for example). Select a thread. Go to the quick reply text field. It doesn't matter if you've typed anything or not. Pressing ⌘+A won't select the text in the quick reply field (which is expected behaviour imo) but it selects all threads in the left pane. 

--

**Comment by bengotow** [comment]
Ahh man this is a good catch. Should be fixed in f037cf8e9ffe2a9a5d068e7e485fcccc58f596be. Thanks!

**Comment by jstejada** [comment]
Hey @nienque , v0.4.40 has shipped with a fix and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
