### ISSUE TITLE
Electron Version Mismatch

### ISSUE THREAD

**Issue by colinking** [nylas/N1#2147]
After successfully building and running N1 using `script/bootstrap` then `./N1.sh`, Electron launches then throws an error (see below). I tried different node versions, and cleaning with apm and re-installing. The following text is printed to the terminal:

```
$ ./N1.sh
App threw an error when running [Error: Module version mismatch. Expected 47, got 46.]
```

![image](https://cloud.githubusercontent.com/assets/2907397/15040772/25f8284e-1285-11e6-91b1-15c516115e2d.png)

##### What node are you using?
I tried it on 4.2, 5.11 and 6.0. I have Electron 0.37.8.

##### What operating system are you using?
Mac OSX 10.11.4

##### What version of N1 are you using?
Pulled from master

**Bug?**
##### Do you have any third-party plugins installed?
No

**Comment by bengotow** [comment]
Hey! Hmm - that's really interesting. That error message (node version mismatch) means that the native code in the node module was compiled for the wrong version of node. Usually, it means it compiled for your computer and not for Electron. Could you try cleaning your working copy ( `git clean -xdf` ) and then running `script/bootstrap` one more time? Let me know if you notice any errors during script/bootstrap, there may be something there that indicates what's going on.

**Comment by colinking** [comment]
@bengotow good call! That got it working again.
