### ISSUE TITLE
Design Personal Level Indicators

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2148]
Dear all,

I just activated "Personal Level Indicators" and thought it was broken because they all looked the same. 

But then I realised that the design between a single and a double one is just not sufficiently distinct.

Can we make them a bit more different from each other?

![image](https://cloud.githubusercontent.com/assets/170947/15041247/edf41d32-12ba-11e6-8490-447aa1f9828e.png)

![image](https://cloud.githubusercontent.com/assets/170947/15041251/f34fa3d2-12ba-11e6-8c8d-124c8263abee.png)

Thankfully,

~Robert

**Comment by bengotow** [comment]
Yeah definitely! I'll see if we can come up with better icons, right now I think those are just UTF8 characters.

**Comment by bengotow** [comment]
These will look better in the next release:

![image](https://cloud.githubusercontent.com/assets/1037212/15199920/1b2f1cee-1797-11e6-8b82-09edbeec2142.png)

**Comment by orschiro** [comment]
Love them, thanks so much! :+1: 

~Robert

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!

**Comment by orschiro** [comment]
They look fantastic. 

Great job! :smile: 

~Robert
