### ISSUE TITLE
Background start issue. Again

### ISSUE THREAD

**Issue by edshevsky** [nylas/N1#2149]
The program is not loaded in the background, as revealed in full screen. Moreover that in the settings specified '--baсkground'.

Ubuntu Gnome 16.04
N1-version 0.4.33-e8f137e

**Comment by bengotow** [comment]
(cc @emorikawa re: window manager)

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
