### ISSUE TITLE
Server only allows LAN IP access,how to set a mail via imap but not a nylas-sync server?

### ISSUE THREAD

**Issue by cielpy** [nylas/N1#215]

**Comment by bengotow** [comment]
Hi @cielpy, unfortunately this is not supported—you could run the nylas sync engine locally since it's an open source project (http://github.com/nylas/sync-engine), but our hosted infrastructure does not support connecting to mail servers behind firewalls, VPNs, or limited to LAN.

**Comment by cielpy** [comment]
Thanks.
