### ISSUE TITLE
Can someone help me fix this beautiful theme?

### ISSUE THREAD

**Issue by joshzhe07** [nylas/N1#2152]
Can someone help me make this theme with the sidebar icons? The theme is great except when you collapse a sidebar item, the icons glitch in suddenly then go away again. Thanks you so much!

Link: https://github.com/P0WW0W/less-is-more

**Comment by grinich** [comment]
Would you be interested in merging this into the master N1 project? That would make it easier for us to QA/test it across releases.

**Comment by joshzhe07** [comment]
Like make it an official theme? Sure! It's not my theme btw, credit goes to poow. Can u fix it though?

**Comment by grinich** [comment]
@P0WW0W would you be interested in that?

**Comment by P0WW0W** [comment]
@joshzhe07  @grinich Absolutely, merging into master sounds like a good idea.

**Comment by joshzhe07** [comment]
@P0WW0W Great theme btw, can't wait for it to be updated!

**Comment by grinich** [comment]
cool @P0WW0W just submit a PR :)

**Comment by P0WW0W** [comment]
Morning @grinich. I've addressed issues raised in this thread, so it can now be closed. I also submitted a PR to include the theme in internal packages.

**Comment by bengotow** [comment]
Awesome - thanks for contributing! We'll follow up on that PR :-)
