### ISSUE TITLE
Installing on Win10 Technical Preview, Adding Gmail Doesn't Open Browser

### ISSUE THREAD

**Issue by framerate** [nylas/N1#2153]
Apparently I cannot install Nylas N1 on Win10 TP? I rebooted as well. During tutorial clicking Gmail says "Sign in in your browser" but nothing happens.

##### Are there any related issues?

...
Not that I could find.
##### What operating system are you using?
...
Windows 10 Technical Preview

##### What version of N1 are you using?
...
Exe downloaded straight from the website
--

**Bug?**
##### Do you have any third-party plugins installed?
...
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for filing this — I'm trying to reproduce this now. Do you use Edge as your default browser, or something else? (Chrome, Firefox, etc...)

**Comment by bengotow** [comment]
I think this is the same issue as https://github.com/nylas/N1/issues/2120

**Comment by framerate** [comment]
I'm using Chrome. Let me know if I can test anything else!

**Comment by Chococat** [comment]
Same issue on latest TP - setting Chrome, Firefox or Edge as default browsers has no effect - the button doesn't actually seem clickable.

**Comment by Trisk3lion** [comment]
I got the exactly same issue. Cycling through different browser as default doesn't seems to do anything, tried Chrome, Firefox, Edge, IE and Brave. 
I'm on insider build 14332 at the moment.

**Comment by Trisk3lion** [comment]
Updating to Insider build 14342 seems to have fixed the problem. Chrome now opens up and let me give Nylas permissions. Though i have problems with Nylas not showing any gmails mails but it could be a different issue.

**Comment by framerate** [comment]
Confirm the button works after Win10 TP update (and fresh downloaded exe if it matters)

**Comment by bengotow** [comment]
Hey! Thanks for reporting that 14342 did the trick. Glad to hear it's not an issue on our side (though that problem with mail not appearing definitely is.) Going to go ahead and close this.
