### ISSUE TITLE
Address bar hidden behind new message header

### ISSUE THREAD

**Issue by Blackfry** [nylas/N1#2154]
Styling issue exactly per the issue title.

![screen shot 2016-05-06 at 10 47 47 am](https://cloud.githubusercontent.com/assets/10493905/15061439/a0a5a32a-1378-11e6-92a3-79377f9a038e.png)
![screen shot 2016-05-06 at 10 45 32 am](https://cloud.githubusercontent.com/assets/10493905/15061438/a0a48ab2-1378-11e6-8d9c-004dee62f25d.png)

##### What operating system are you using?
OSX El Capitan 10.11.4 (15E65)

##### What version of N1 are you using?
Nylas Version 0.4.33-e8f137e (0.4.33-e8f137e)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

**Comment by grinich** [comment]
what theme are you using

**Comment by grinich** [comment]
what theme are you using?

**Comment by Blackfry** [comment]
n1-ido-master

**Comment by bengotow** [comment]
Hey! Thanks for filing this—this seems to be a theme issue, so you'll need to post over at https://github.com/edipox/n1-ido. Cheers!
