### ISSUE TITLE
Item seperators in menu

### ISSUE THREAD

**Issue by arvislacis** [nylas/N1#2159]
This is not very big problem/bug but anyway... I'm using Nylas N1 0.4.33 on Linux Mint 17.3 and have some interesting menu item seperator behaviour in N1 main menu:

1. *Thread* menu has not necessary menu separator after item *Remove from view*;
2. *View* menu has same bug but only at the beginning of menu, before item *Toggle Full Screen* - it appears when switching between *Single Panel Mode* and *Double Panel Mode*.

**Comment by bengotow** [comment]
Hey! Thanks for posting this—we've been refactoring menu code recently and I'll see if we can get this fixed.

**Comment by jackiehluo** [comment]
@arvislacis Should be fixed! Let us know if it isn't.
