### ISSUE TITLE
Move the window controls into the program, like in Outlook 2013

### ISSUE THREAD

**Issue by ExploreNewTab** [nylas/N1#216]
It would be great to get rid of the separate "Title Bar" in Nylas on Windows. A lot of programs are moving the window controls into the programs, and it makes the program look more polished and integrated.

This looks awkward:
![title bars in composer n1](https://cloud.githubusercontent.com/assets/15165637/10751739/a40e9bf2-7cce-11e5-92bc-4734336f335d.PNG)

Mock up of how Compsoer could look like (I know, there isn't a maximize button, but I was in a hurry):
![mock up of controls](https://cloud.githubusercontent.com/assets/15165637/10751794/4692812c-7ccf-11e5-991f-f84b5ff32758.png)

**Comment by jackiehluo** [comment]
Merging into #1264!
