### ISSUE TITLE
Don't open folder after download if already opened

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2162]
Dear all, 

Whenever I save an image to my local disc, it opens the download folder. Even if the respective is already open.

This creates a number of duplicated folders in my file manager. 

Could we change this behaviour so that no new folder is opened if it's already opened?

Thankfully,

~Robert

**Comment by KevinMartin** [comment]
Are you talking about the folder window? If so, this would be something for Electron. I don't believe Electron can currently detect if a folder window is open or to re-use a folder window.

**Comment by orschiro** [comment]
Dear @KevinMartin,

Exactly, in my case, this is Nautilus File Manager. 

I end up with countless open Nautilus windows if I download a number of files within N1.

Where should we report it?

Thankfully,

~Robert

**Comment by bengotow** [comment]
Merging into https://github.com/nylas/N1/issues/1044 - there's not a great way to fix this unfortunately, but I'm going to join these conversations.
