### ISSUE TITLE
When Nylas has been hidden for a while, opening it loads the splash screen

### ISSUE THREAD

**Issue by nienque** [nylas/N1#2164]
##### Are there any related issues?
Couldn't find any.

##### What operating system are you using?
Version 10.11 Beta (15A279b).

##### What version of N1 are you using?
Version 0.4.33-e8f137e (0.4.33-e8f137e).

**Bug?**
##### Do you have any third-party plugins installed?
Only the defaults.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Whenever Nylas is brought back into view after having been hidden for a while it displays the splash screen. It didn't use to do this in previous versions.

**Comment by Zopium** [comment]
This happened to me to, I just quit it and it worked fine after.

**Comment by jackiehluo** [comment]
Closing this issue for now—that's expected behavior, unless you've noticed it taking a really long time or anything else strange!
