### ISSUE TITLE
Inbox switches to showing only first account's mail

### ISSUE THREAD

**Issue by rosslebeau** [nylas/N1#2165]
After the latest update, when I open the app, it starts in "Inbox" under "All Accounts". This is expected. Then, after some amount of time (usually 5-20 seconds), it switches to showing only the inbox for my first email account. The "Inbox" under "All Accounts" becomes un-highlighted, and I have to click it again to see all my mail.

This continues to happen, switching randomly back to only showing the first account's mail, several times after maybe 10-30 more seconds. I have run the app for a couple hours after this without it happening, but it seems to happen at least 2-3 times every time I open the app.

This is on OS X 10.11.4
Nylas N1 Version 0.4.33-e8f137e (0.4.33-e8f137e)
The only plugin I have installed is Taiga
5 of my accounts, including the first one, are Gmail. The last account is run by Inmotion Hosting.

**Comment by rakeshdas1** [comment]
Try using the shortcut CMD+number that switches the accounts. So try CMD+1, or CMD+2, etc. That usually fixes the problem for me.

**Comment by joaofl** [comment]
Same to me. Have to switch to ¨all¨ manually.

**Comment by bengotow** [comment]
Hey folks—this one turned out to be subtle. I was able to reproduce this, and it's fixed by 1b0e933977d9370dac5b0c178faf2a3c2b4027b6. Rather than writing a test for this behavior (which we may change in the near future), we're looking to see if we can get `eslint` to detect this in addition to some other underscore stuff we check for. Cheers!

**Comment by jstejada** [comment]
Hey folks, v0.4.40 has shipped with a fix and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
