### ISSUE TITLE
"Select All" not working properly

### ISSUE THREAD

**Issue by fredguth** [nylas/N1#2169]
Edit > Select All does not work
cmd + A (which is written besides Edit > Select All) also does not work.

Preferences > Keyboard shortcuts show that I am using Gmail preference and the shortcut is "* a".

Saw there is a keyboard.json, but couldn't find an example to properly use it.

##### What operating system are you using?
OSX El Capitan

##### What version of N1 are you using?
Version 0.4.33-e8f137e (0.4.33-e8f137e)

##### Do you have any third-party plugins installed?
Todoist, n1-unsubscribe

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Comment by jstejada** [comment]
hey @fredguth, I'm merging this into #886, which should be fixed in the next release!

**Comment by nisanth074** [comment]
I found a workaround for this meanwhile. I just select one email and then press the Shift + Down Arrow key multiple times to select all the other emails.

**Comment by fredguth** [comment]
actually, you can set in preferences Gmail keyboard shortcuts and then * + a

The point is that cmd+a is easier

On May 17 2016, at 1:55 pm, Nisanth Chunduru &lt;notifications@github.com&gt;
wrote:  

> I found a workaround for this meanwhile. I just select one email and then
press the Shift + Down Arrow key multiple times to select all the other
emails.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2169#issuecomment-219782189)![](https://github.com/notifications/beac
on/AAX-r1_DjaSi7nLindWXlidORXdfnDHvks5qCfMPgaJpZM4IZkfW.gif)
