### ISSUE TITLE
Select all checkbox besides search

### ISSUE THREAD

**Issue by fredguth** [nylas/N1#2170]
##### Does this feature exist in another mail client or tool you use?
Most email clients let the user select all by clicking in a checkbox in the header.  I understand that N1 tries to keep it simple.  But I believe a checkbox besides the search, wouldn't clutter the design and would improve usability.

**Comment by emorikawa** [comment]
@fredguth We do have checkboxes in split-pane mode, but not in list mode.
Select-all is an ongoing issue you can see on https://github.com/nylas/N1/issues/886

**Comment by fredguth** [comment]
ok
