### ISSUE TITLE
Poor syncing with Gmail

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#2172]
In the current N1 release (0.4.33-e8f137e) on OS X 10.11.4, my Gmail account seems unable to properly synchronize, with messages that were archived still in the inbox, and labels that had been deleted still showing in the sidebar. There are no error messages or warnings, and restarting N1 does not solve the issue. The account is properly synced on other clients (e.g. Apple Mail, Cloud Magic).

**Comment by fonnesbeck** [comment]
UPDATE: 3 days on, N1 still cannot sync with Gmail at all. Removing and re-adding the account does not fix this.

**Comment by jstejada** [comment]
thanks for filing this @fonnesbeck , I'm going to merge into #2059
