### ISSUE TITLE
Button to check email(Not getting email since last update)

### ISSUE THREAD

**Issue by lukealford** [nylas/N1#2174]
##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.33

--

**Bug?**
##### Do you have any third-party plugins installed?
All current ones available

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Normal SMTP server(cpanel/whm)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not receiving / updating inbox, webmail displays all emails fine yet this magically stopped working since the last update, worked perfect before.
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Pull mail button / check for new mail.

**Comment by bengotow** [comment]
Closing as dup of #167
