### ISSUE TITLE
Reply-to ignored if the email is from a linked account or alias

### ISSUE THREAD

**Issue by andreaolivato** [nylas/N1#2175]
Hi!

I noticed that you added a layer of security to check if the reply-to address is different from the from address and you display a warning message as shown below.

![screenshot from 2016-05-09 12-35-36](https://cloud.githubusercontent.com/assets/100728/15103900/5e099f04-15e3-11e6-8f2c-5cc2c54cc38f.png)

While this is definitely appreciated and I understand it's quite useful for certain users, I believe that changing the default reply behavior, imposing the reply to the "from" address ignoring completely the "reply-to" header is a bit too much.

Sometimes, in fact, this behavior is not suspicious, but needed. For example when you use Amazon SES as email provider for Server-side applications or mobile applications, you can not send email on behalf of users but only from your own domain. So imagine having a form on a web page that users fill to get in touch with you and you receive that on your company email: the from address must be your own, but you want to reply directly to the user instead of having to change the address every-time.

Could you please leave the warning but not change the default reply-to address? Or at least can you add an option under preferences to disable this check?

Many thanks.

Using Nylas 0.4.33 on Ubuntu Linux 16.04, no third party plugins active.

PS: Love your client!

**Comment by bengotow** [comment]
Hey! Thanks for filing this—I /think/ N1 should be respecting the "ReplyTo" header, even though it displays that warning message. (On a separate note, we're working to fix that "phishing detection" plugin to use a more sophisticated set of checks.) I'll see what's going on —

**Comment by bengotow** [comment]
Hey! I haven't been able to reproduce this problem. When a message has a ReplyTo, reply and reply-all should both use the ReplyTo. Are you seeing the reply be created to the wrong address?

**Comment by andreaolivato** [comment]
Hi @bengotow , thanks for looking into this. 

Here you can see the problem as I experience it.

1. The email shows the warning
![screenshot from 2016-05-10 10-27-24](https://cloud.githubusercontent.com/assets/100728/15133912/fd31aab6-1699-11e6-9c8e-0fdee6266cca.png)

2. These are the relevant headers

```
Delivered-To: tiffany.stone@popularchips.com
Received: by 10.25.15.104 with SMTP id e101csp1173293lfi;
        Sun, 8 May 2016 03:36:05 -0700 (PDT)
X-Received: by 10.66.118.70 with SMTP id kk6mr42326103pab.74.1462703765680;
        Sun, 08 May 2016 03:36:05 -0700 (PDT)
Return-Path: <010101548ff02904-d5d225e7-3cdf-420e-9e7a-e7b57559e4e3-000000@us-west-2.amazonses.com>
Received: from a27-123.smtp-out.us-west-2.amazonses.com (a27-123.smtp-out.us-west-2.amazonses.com. [54.240.27.123])
        by mx.google.com with ESMTPS id e89si30235618pfj.100.2016.05.08.03.36.04
        for <tiffany.stone@popularchips.com>
        (version=TLS1 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
        Sun, 08 May 2016 03:36:05 -0700 (PDT)
Received-SPF: pass (google.com: domain of 010101548ff02904-d5d225e7-3cdf-420e-9e7a-e7b57559e4e3-000000@us-west-2.amazonses.com designates 54.240.27.123 as permitted sender) client-ip=54.240.27.123;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@popularchips.com;
       dkim=pass header.i=@amazonses.com;
       spf=pass (google.com: domain of 010101548ff02904-d5d225e7-3cdf-420e-9e7a-e7b57559e4e3-000000@us-west-2.amazonses.com designates 54.240.27.123 as permitted sender) smtp.mailfrom=010101548ff02904-d5d225e7-3cdf-420e-9e7a-e7b57559e4e3-000000@us-west-2.amazonses.com
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=wltvvkyrd7z2dfq7mjuotakp3y4csbr6; d=popularchips.com;
	t=1462703761;
	h=From:Reply-To:To:Subject:MIME-Version:Content-Type:Message-ID:Date;
	bh=wX1opgAljqh0EPT53QuBzjuQ7w2pXjLWLKUBGmUvNQY=;
	b=dyHGsFVs5mVwQpRqyZNAsJzwmg4ukPNV8xLhW4o6EpMMAO8dXc5HoumH8NvAoyoA
	WHEo2Kh4eSg09HBQWTpaTTDvTuZGdzumuxAdj4Et+puZSL1avcOcHgP5u7mCAE9dWVA
	rM0pR+5Ol4hQYCZqhQom+dRnVL2gT27g4J8ZJyiM=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=gdwg2y3kokkkj5a55z2ilkup5wp5hhxx; d=amazonses.com; t=1462703761;
	h=From:Reply-To:To:Subject:MIME-Version:Content-Type:Message-ID:Date:Feedback-ID;
	bh=wX1opgAljqh0EPT53QuBzjuQ7w2pXjLWLKUBGmUvNQY=;
	b=kagYZLQkz5gFNuqmv4E635JJAE98agKAmcT7WtlRZ/FCZB16BGKPM1i0BdnNz9Ss
	MlN2YPAE+fEi7LshUE4GeDPyMKk4li7wMTGq+RNS/fFqmGzKcqSbPeR2Iv97yoZFSOF
	cBZ3E3tMfnlJuClh2BZTtvCJlPTTRLcs8iLVoVN0=
From: Popular Chips <info@popularchips.com>
Reply-To: dancoronadomtz@gmail.com
To: Tiffany Stone <tiffany.stone@popularchips.com>
Subject: New profile filled on Popular Chips
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_18198045_1324491893.1462703761671"
Message-ID: <010101548ff02904-d5d225e7-3cdf-420e-9e7a-e7b57559e4e3-000000@us-west-2.amazonses.com>
Date: Sun, 8 May 2016 10:36:01 +0000
X-SES-Outgoing: 2016.05.08-54.240.27.123
Feedback-ID: 1.us-west-2.1bJL/DyhN4y4F7lYnrAR+wcfRLEj11/Zg4VPXilh5HQ=:AmazonSES
```

3. When i click "Reply" I obtain as destination the wrong address as you can see from the next screenshot 

![screenshot from 2016-05-10 10-28-09](https://cloud.githubusercontent.com/assets/100728/15133948/432dc478-169a-11e6-8e35-0ef3e8d7d9ee.png)

4. Do you want me to send you the same exact message via email for further investigation?

**Comment by bengotow** [comment]
Hey! Thanks for sending this - that does indeed look broken. I'll see if I can make a test case tomorrow.

**Comment by bengotow** [comment]
Hey! Think I figured this out - do you have `info@popularchips.com` configured as an email address or alias in N1? I think that triggers separate logic that "helps" make sure you don't send the email to yourself, and it's causing this problem.

**Comment by bengotow** [comment]
This should be resolved in eab8cb9085a51caae0daf075d25829694d211030 - thanks!

**Comment by andreaolivato** [comment]
Hi Ben, info@popularchips.com is a real account but indeed there's an alias at work there as tiffany.stone@popularchips.com (the recipient address) is an alias of tiffany@popularchips.com, another account. 

So I believe your theory is definitely correct. 

Thanks a lot for your help, will wait for the release to test.

Have a great day ahead.

**Comment by andreaolivato** [comment]
Installed 0.4.37 this morning. I confirm everything is fixed.
