### ISSUE TITLE
Sync differences in e-mail list between Nylas and Gmail

### ISSUE THREAD

**Issue by pedropapa** [nylas/N1#218]
Hello,

I recently installed Nylas and start to use it, but in a few hours of use I just found some bugs;

1- This is my inbox mail list:
<img width="1149" alt="screenshot 2015-10-27 10 02 51" src="https://cloud.githubusercontent.com/assets/2160382/10757655/6fc39c84-7c93-11e5-9e4a-04b518cdcc5f.png">

There are a lot of "No subject" e-mails with no body written, but as you can see directly in gmail, there is other e-mails that is not showing up on Nylas and there is no e-mail with no body and subject as well:

<img width="1158" alt="screenshot 2015-10-27 10 03 40" src="https://cloud.githubusercontent.com/assets/2160382/10757682/a4032442-7c93-11e5-9b73-a07764dd2746.png">

I think it is a sync problem, but restarting Nylas or resyncing e-mail did not solve the problem.

2- I found a similar error in sent mail as well;

Nylas:
<img width="1440" alt="screenshot 2015-10-27 10 09 18" src="https://cloud.githubusercontent.com/assets/2160382/10757739/ef23bafe-7c93-11e5-9f69-77d254d8eeb7.png">

GMail:
<img width="1440" alt="screenshot 2015-10-27 10 09 50" src="https://cloud.githubusercontent.com/assets/2160382/10757741/f5052570-7c93-11e5-9524-6705c8a32755.png">

The first e-mail on Nylas has the subject "config cs", but on gmail there is not e-mail with this subject. Searching on gmail with e-mails sent with this subject I just found an e-mail conversation sent in September 9 with this subject, but why is it on the top of e-mails sent as it has been sent a long time ago?

<img width="1428" alt="screenshot 2015-10-27 10 18 45" src="https://cloud.githubusercontent.com/assets/2160382/10757815/50a2268a-7c94-11e5-97b8-24a70dede3ec.png">

Note: I have multiple accounts attached to Nylas (four).

**Comment by spang** [comment]
@pedropapa Please reopen if you're still experiencing this issue. We've made quite a few new releases since October. :)

**Comment by pedropapa** [comment]
@spang Ok, I'm not experiencing this error anymore after few updates of Nylas, I think it is solved.
