### ISSUE TITLE
Bug: Shift-click scroll Shift-click does not select multiple emails

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2180]
This issue is only evident when I scroll up (older to newer emails) I cannot reproduce the issue when scroll down (newer to older emails)

I was attempting to trash the >700 junk email by scrolling down to the oldest email and using click-shift-click to select a whole bunch of email to trash.  I wanted to scroll through the email list just in-case I spotted an email I wanted to keep.

But the shift-click failed to select a group of emails.

I haven't counted how many emails you have to scroll past for the problem to occur but the problem only happens when scrolling for a few pages and beyond.  Scrolling through a small number of email the click-shift-click works as one would expect.

I tried this on the consolidated INBOX and Junk folders and I get the same problem.

If you do this for a specific account mbox the problem does not occur and doing so resolves the problem when trying to click-shift-click on consolidated folders. Restarting N1 and the fault returns.

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.33

**Bug?**
##### Do you have any third-party plugins installed?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
All

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Select the INBOX or Junk folder
2. Scroll to the oldest email and left-click, and select any email
3. Now scroll up using either your touchpad or scroll wheel (I use a scroll wheel) two or three pages of email (not sure how far you have to scroll exactly).
4. Now shift-left-click on an email, that should select all the emails between the clicks but it does not.
5. The email will not be selected and you will not see any indication that email below (older) have been selected.

**Comment by bengotow** [comment]
Hey! Thanks for filing this. This is related to #1908.
