### ISSUE TITLE
Differentiate between emails in Inbox

### ISSUE THREAD

**Issue by hmiranda-ns** [nylas/N1#2181]
### N1 Version:
0.4.33-e8f137e (0.4.33-e8f137e)

### OS:
Mac OS X 10.11.4

### Email Accounts' providers:
Gmail
Office365 (N1 detected it as Exchange)

### Description:
There's this situation where you use more than one email account for either work, personal, product, etc, so when you receive your email, they are all shown in the Inbox tab which is a great way to see all your received email fast and easy.
However, I know you can you can go to each individual inbox, but it would be nice to have a way to identify which account the email is from by just looking at them.

#### Here are some suggestions from the top of my head:
- Add the name of the account to the email preview.
- Designate colours to each account and change title and/or recipients text color to match the designed to each account.

**Comment by bengotow** [comment]
Thanks—this is definitely something we need to add! Closing as dup of #1677
