### ISSUE TITLE
Compose field isn't focussed after hitting reply (or using reply shortcut)

### ISSUE THREAD

**Issue by elliotjaystocks** [nylas/N1#2182]
When hitting reply or initiating a reply via a shortcut, the cursor is not focussed inside the compose area — the result often being that you start typing only to look up and realise nothing has actually been written.

**Comment by bengotow** [comment]
Hey thanks for reporting this! I think this was fixed Friday, and should be corrected in the next release. Sorry for the hassle.

**Comment by enoversum** [comment]
I have that, too, plus sometimes the cursor jumps into my signature and thus I am writing text there. Since this has been done in the pending release, that occurrence is probably gone too :wink: .

**Comment by jstejada** [comment]
Hey folks, v0.4.40 has shipped with a fix and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
