### ISSUE TITLE
Exchange Shared Inbox Support

### ISSUE THREAD

**Issue by joshvickerson** [nylas/N1#2186]
##### What operating system are you using?
OS X 10.11

##### What version of N1 are you using?
0.4.33-e8f137e

**Feature Request**
Support Exchange shared inboxes. I have an Office 365 account at work and we just started using a shared inbox, but I can't seem to add it to N1.

**Comment by bengotow** [comment]
Thanks! I think this is a dup of https://github.com/nylas/N1/issues/1209 (though it was named differently...)
