### ISSUE TITLE
Syncing problem with Gmail, Yandex

### ISSUE THREAD

**Issue by hamzauzumcu** [nylas/N1#2189]
1- I deleted my test mail on gmail.
2- Sync is completed.
3- I saw deleted mail after I opened my gmail 
Why didnt update gmail, yandex?

**Comment by bengotow** [comment]
Hi - does the deleted message still appear in Gmail? It may have just taken longer than usual to sync back.

**Comment by hamzauzumcu** [comment]
Yes, its work but default mac mail app faster than nylas.
Thanks for reply.
