### ISSUE TITLE
Bug: False positive read receipts

### ISSUE THREAD

**Issue by pfista** [nylas/N1#2190]
##### What operating system are you using?

OS X 10.11.5 Beta (15F31a)

##### What version of N1 are you using?

Version 0.4.33-e8f137e (0.4.33-e8f137e)

--

**Bug?**

The activity feed shows false-positive read receipts for emails for several cases. For an email composed in Nylas with read tracking turned on, a read notification will be created when viewing that same email on inbox for iOS, inbox for web, gmail for web, etc. 

Read receipts also sometimes show up when viewing the same email in N1 on different computers. 

##### Do you have any third-party plugins installed?
![image](https://cloud.githubusercontent.com/assets/728526/15161663/ed0341ee-16b3-11e6-8746-7b33b7e61ee5.png)
![image](https://cloud.githubusercontent.com/assets/728526/15161673/f61356a2-16b3-11e6-8a1d-16d5faa29f63.png)
![image](https://cloud.githubusercontent.com/assets/728526/15161681/fc51f596-16b3-11e6-9523-3994f7255161.png)

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes. 

--

**Comment by jackiehluo** [comment]
@pfista We're working on fixing that! Right now, there isn't a good way to differentiate your opens/clicks from your recipients' when you're on another email client, although we make sure they don't register within N1.

**Comment by pfista** [comment]
@jackiehluo I've been noticing false positives that happen solely within N1 as well. If I send a message to someone, get a reply from them, and then later open that thread I'll usually get a read receipt when looking at the message again.

**Comment by jackiehluo** [comment]
@pfista Is that still happening on the latest update? I think the last time I commented, it was on master but hadn't shipped yet!

**Comment by pfista** [comment]
@jackiehluo Nope was still on Version 0.4.33-e8f137e. Didn't realize a new update came through, downloading now and will let you know if the problem persists!

**Comment by imapirate** [comment]
Think the bug is still there with 0.4.40
By mistakenly clicking on sent message from Chrome, N1 registers opened message by the recipient.

**Comment by jackiehluo** [comment]
@imapirate Triggering it from Chrome is a different issue! Right now, we remove the tracking pixel from N1—but the update that'll make it work everywhere coming soon.

**Comment by imapirate** [comment]
I see, sorry. So maybe doesn't help it's the same with all other clients I tried: Cloud Magic, Mail, Canary, Polymail and Massive. Thanks, looking forward to the upcoming fix :)

**Comment by jackiehluo** [comment]
Going to close this issue for now—should be fixed for all providers but Exchange, and it's fixed within N1 for all providers! It doesn't look like there's a way to avoid this issue for Exchange emails using other platforms (Gmail, Inbox, etc.).
