### ISSUE TITLE
What will Nylas Pro have that Nylas does not have?

### ISSUE THREAD

**Issue by Zopium** [nylas/N1#2191]
Title

**Comment by bengotow** [comment]
Nothing! N1 is becoming a paid product and a Nylas subscription (Pro, Enterprise, etc.) will be required to continue using N1 against the hosted infrastructure after the thirty-day trial window. Of course, it will still be open source, and you'll be able to run it against the open source sync engine forever without paying.

**Comment by Zopium** [comment]
Ah, but if I got it before may 1 i would get 1 year free?

**Comment by bengotow** [comment]
Hi @Zopium — yep, that's correct. We'll give existing users 1 year free. Enjoy!

**Comment by Cu8eR** [comment]
@Zopium - or just try Mailbird - 6USD/year - same features as Nylas

https://www.getmailbird.com/

**Comment by bherila** [comment]
> Of course, it will still be open source, and you'll be able to run it against the open source sync engine forever without paying.

Unless you're using Exchange/Office 365 @bengotow I am assuming?

Kind of disappointing, since $7/month is more than the whole Office desktop suite :(

**Comment by fmnoise** [comment]
> Of course, it will still be open source, and you'll be able to run it against the open source sync engine forever without paying

@bengotow The only thing I need is to read and write emails. How I can continue using free version? Why it cannot just sync my mailbox locally without all your super-ultimate-cool-mega features which I don't need at all?

**Comment by deivid11** [comment]
:( I don't need super features, i just want to keep using Nylas free version without paying for the cool stuff.

**Comment by luishdez** [comment]
@fmnoise you can't They made a low blow move , create a community, developers and designers made plugins and themes, they create confusion about the open source /free idea… As soon they had popularity they remove any change of free or non pro version…

I spent a lot of time creating some plugin based of the idea of there will be a free version or non pro but 9$ month to add some features to mails and a service that doesn't have even a mail server … ? no thanks

**Comment by Omeryl** [comment]
@luishdez If you want free, can always host it yourself pretty easily. That said, I'd much rather they take some of my money than disappear, personally (like Mailbox ..).

**Comment by luishdez** [comment]
@Omeryl It's not about free or not free , they made a community on false premises and a lot of developers and designers spent a lot of hours on themes, plugins and even nylas n1… there is like 100 contributors just to the project. 

I they said… dude it's going to be a paid product with no free or non pro option, I bet they didn't have that support from the beginning from the developer community.

**Comment by Omeryl** [comment]
@luishdez I think a lot of that was implied, though. We all knew nothing could be free forever... A company (yes, a company, like Nylas is) has to pay back their dues at some point. I don't think they ever said it'd be free forever, they did say though that it was free during beta if I recall correctly. 

The community assumed, assumptions don't make fact I fear.

**Comment by bherila** [comment]
It's not free if you need Exchange support. That killed it for me, sadly.

**Comment by adglopez** [comment]
I'm not even user if I want to use the free year early adopter code either. This license change was totally unexpected so would not be surprised if it gets more expensive anytime soon. 
After all I just want to simple mail client.

**Comment by PolishedGarbage** [comment]
Sure was a great client, now I am finding another since this is no longer free.

**Comment by thebigcako** [comment]
It was a great client, I used it for almost a year and I liked it. So moving back to the ugly Thunderbird 👎

**Comment by TaqiOfficial** [comment]
Where can i download the free version of N1?

**Comment by luishdez** [comment]
@TaqiOfficial Here from the source. You have to setup your own server and compile the app … There is not a free version of N1 that you can download and use easily.
