### ISSUE TITLE
Unable to change themes at all

### ISSUE THREAD

**Issue by breitigan** [nylas/N1#2192]
I was recently working on a custom theme and then about a week (maybe 2 weeks) ago, N1 would not allow me to change themes at all. I uninstalled and re-installed the theme several times but that did not help. I even deleted and re-downloaded the program and still nothing. When I open the 'Change theme' dialogue box, either 1 - nothing happens at all (it won't open the window to select a different theme) or 2 - it will open the window and let me see the themes but I am unable to close that window. Not sure if anyone else is having this problem or not. The app is still _usable_ but this is becoming very frustrating.

Macbook pro 2011
OSX Yosemite 10.10.5
N1 version 0.4.33-e8f137e

**Comment by jackiehluo** [comment]
@breitigan Oh, no, sorry to hear that! Are there error messages in the console when that happens?

**Comment by jackiehluo** [comment]
@breitigan Another possibility that just came to mind... Could one of the themes/theme previews you have be broken?

**Comment by bengotow** [comment]
Hi @breitigan — can you move you WIP custom theme out of `~/.nylas/packages` and see if that resolves the issue?

**Comment by breitigan** [comment]
Update on the situation:

I was getting *a ton* of errors in the console, but mostly referring to theme-picker.jsx..? I uninstalled the theme (from the plugins menu in preferences) and that does seem to help. I'm guessing there is some kind of problem in my theme code so I'm going to look into that now. Thank you all for the help!
![screen shot 2016-05-11 at 11 08 22 pm](https://cloud.githubusercontent.com/assets/6306450/15203051/f1d49ba8-17cd-11e6-9018-7b3bfd226b46.png)

**Comment by jackiehluo** [comment]
Of course! Going to close this issue for now, but let us know if you find out what the problem was... at the very least, we should be showing a more helpful error message. Also, for reference, you can see our [theme starter](https://github.com/nylas/N1-theme-starter)!
