### ISSUE TITLE
No Notification for new mail on Ubuntu 14.04 (64 bit)

### ISSUE THREAD

**Issue by miftahafina** [nylas/N1#2194]
Zenity is already installed, but there's still no ubuntu notify osd appear, when I got new mail. Only a small blue circle icon on unity system tray.

##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 14.04 LTS

##### What version of N1 are you using?
0.4.33-e8f137e
--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Closing as dup of #1165
