### ISSUE TITLE
Feature request: Allow more than one N1 instance at the same time

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2197]
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, almost all email clients allow users to open multiple emails at the same time.

Like many coming from other email clients we have lots emails open at the same, for reference, copy & paste and other reasons.  It's a personal workflow for many and getting users to pay for N1 will need some crossover UX so not to exclude a very large demographic.

I would like a new feature to open more than one instance of N1 on my laptop so I can work with many emails from different sources and not in the same thread.

So right-clicking on an email and select an option 'Open in new instance' (or an icon for the current thread) with windows title bar set to 'Nylas N1:' with the email subject it would also make it easier/faster to navigate around emails.

I know many people who have >20 emails open after a few hours.  Especially logistics people who are dealing with many different people & threads on the same subject/issue.

A more advanced method would be to look at how grouped tabs work in Firefox this could be adapted to allow users to group emails in disposable (but persistent across restarts).  I could right-click and send an email to a group and view, answer, copy & paste content.

A groups would be like a paste board of email, so users can group email on one place.

**Comment by jackiehluo** [comment]
Hey, @molstrangler! I don't think you want more than one instance of N1, just new windows for viewing threads, right? We're hoping to do that soon. Merging into #779!

**Comment by molstrangler** [comment]
ah! very poor choice of words on my part.
