### ISSUE TITLE
Bug: Full IMAP support is not enabled for this account

### ISSUE THREAD

**Issue by cybertk** [nylas/N1#2199]
##### Are there any related issues?

No

##### What operating system are you using?
OS X 10.11.4

##### What version of N1 are you using?
0.4.16-8cb7748 

--

**Bug**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
263mail, www.263.net

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="286" alt="screen shot 2016-05-12 at 14 39 17" src="https://cloud.githubusercontent.com/assets/455809/15206150/9e75df8a-184f-11e6-9d70-e763d05632b1.png">

--

**Comment by bengotow** [comment]
Hi - thanks for filing this! On this page (http://helpcenter.263.net/a/bangzhuzhongxin/remenwenti/2012/0419/31.html), they say `Tip: At present, IMAP service only 263G + provide product.`. You might need to get that product? Are you able to use other mail clients OK?

**Comment by bengotow** [comment]
Merging into https://github.com/nylas/N1/issues/1909
