### ISSUE TITLE
"Back" multitouch gesture

### ISSUE THREAD

**Issue by willwhitney** [nylas/N1#22]
In the List View theme, it'd be great to have a trackpad gesture to go back to the list view from the message view. I don't like to take my hand off the trackpad, and it's much slower to hit even a big click target.

Most apps, like Twitter and Reeder, support this.

**Comment by bengotow** [comment]
This is a great idea. To help manage feature requests, we've created a public Trello board. I'm going to go ahead and add this there: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap. Feel free to upvote it!
