### ISSUE TITLE
Possible layout confusion in the initial setup

### ISSUE THREAD

**Issue by lukehefson** [nylas/N1#220]
I love the idea behind choosing your layout in the initial setup here:
<img width="1012" alt="screen shot 2015-10-27 at 09 13 25" src="https://cloud.githubusercontent.com/assets/1469659/10758726/155cc488-7cab-11e5-936e-3ac4a0c1fad1.png">

However, a lot of folks that use email clients aren't necessarily designers or developers and therefore might have trouble understanding what `List view`, `Split view`, `single panel` or `dual panel` actually *means*.

Forcing the user to make a UX decision here (even with the help of illustrations), without actually *seeing* what it means might make the user feel uncomfortable – especially as there is no indication that they can change this later in the prefs if they want to.

I'd personally suggest either leaving this out of the initial setup altogether (and sacrificing the ability to configure early :cry:) or, not introducing the concept until the real interface can be viewed and clicking between the layouts *demonstrates* the difference.

**Comment by grinich** [comment]
We've changed the phrasing here. Thanks!
