### ISSUE TITLE
Horizontal scroll in Linux

### ISSUE THREAD

**Issue by RR1991** [nylas/N1#2200]
##### What operating system are you using?
Ubuntu 15.10
##### What version of N1 are you using?
0.4.33
--

**Issue**
When the window is scaled down, and the email and text is being cut horizontally, there is no horizontal scroll bar appearing, making it impossible to read the email. I assume the idea is that text will be scaled and/or moved down (responsive interface), but this doesn't happen either. Also the vertical overlay scrollbar doesn't appear, but scrolling just works. I don't know if it is Unity or Linux specific, but it makes multitasking on a single screen impossible.

**Comment by bengotow** [comment]
This should be fixed in the next release by 7c050fb380da23b034bef7f6303e3a4467e8724f Cheers!

**Comment by jstejada** [comment]
Hey! v0.4.40 has shipped with a fix and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
