### ISSUE TITLE
Can't get new emails

### ISSUE THREAD

**Issue by va-al** [nylas/N1#2202]
Bugreport:
I've big Inbox with summary 2.8GiB of emails. N1 stops getting new email after 2016 feb 10. No errors in the logs after clean install and run "with debug flags".
Evolution over MAPI transport still works correctly.

##### Are there any related issues?

Nope.

##### What operating system are you using?
Common: Linux.
If be exact Antergos Linux.

##### What version of N1 are you using?
Common: 0.4.33-1

Full:
Repository      : antergos
Name            : n1
Version         : 0.4.33-1
Description     : A mail client for Mac, Linux, and Windows that is built on the modern web and designed to be extended.
Architecture    : x86_64
URL             : https://nylas.com/N1/
Licenses        : MIT
Groups          : email
Provides        : None
Depends On      : gtk2  libgnome-keyring  desktop-file-utils  python2  gconf  nodejs  libnotify  libxtst  nss  alsa-lib  xdg-utils
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 55.72 MiB
Installed Size  : 229.95 MiB
Packager        : Unknown Packager
Build Date      : Thu May 5 05:24:47 2016
Validated By    : MD5 Sum  SHA-256 Sum  Signature

**Bug?**
##### Do you have any third-party plugins installed?
Nope, just clean install.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

On the my account

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
It.s bug report.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - can you post the email address you're having trouble with, or PM me on the Nylas slack channel? (nylas-chat.slack.com). Thanks—

**Comment by va-al** [comment]
Hi, Ben!

email with problem is a.vasilchenko at netris.ru

**Comment by jstejada** [comment]
Hi @va-al, I checked your account and it seems to have been throttled by Exchange. This should be a temporary issue and should recover after a while. If you continue having trouble feel free to ping us via slack (nylas-chat.slack.com).

**Comment by va-al** [comment]
Hi @jstejada , But this problem is stable reproduced from Feb 2016 to this moment on all versions of N1 what was out and in other email clients  is not have the problem.  I've access to Exchange server and there are no any errors applied to my client N1. I think there are some bug. It's very sad if you would not want research it.

**Comment by jstejada** [comment]
hi @va-al, thanks for the additional details. I will forward this to our platform team

**Comment by va-al** [comment]
Hi, guys!

Today I've delete and add again account what had problem in N1 in Evolution(MAPI) client. I've some problem in process. Exchange 2007 allow manipulate only 250 object in one time(http://www.codetwo.com/kb/adjusting-the-maximum-number-of-open-objects-that-a-mapi-client-can-use-at-the-same-time/).

Maybe problem in N1 client is relevant to this too? For example N1 stuck after check 250 objects and never didn't go to next part.

**Comment by jackiehluo** [comment]
Merging into #1868!
