### ISSUE TITLE
Not fetching new mail | Need a manual force check

### ISSUE THREAD

**Issue by theauditor** [nylas/N1#2204]
No new mails are being fetched for me too.
A message saying "Syncing your mailbox" appears when I start the application and stay for about 5 mins.

After that the message vanishes. No new mails that come to the inbox are detected or downloaded.

As there is no manual method for syncing I am left wondering at the status of the operation.

##### What operating system are you using?
Antergos Linux (Arch derivative)

##### What version of N1 are you using?
0.4.34-f2fbfbc

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No .All of them

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not even plain text emails appear.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
A manual means of initiating sync and also knowing the status of it.

**Comment by bengotow** [comment]
Hey! Can you post one of the email addresses you're having trouble with? I can check that there's nothing odd going on server-side. Also feel free to PM me on the Nylas slack channel (nylas-chat.slack.com) Cheers—

**Comment by theauditor** [comment]
Sure.   blaise@xincoz.com should do. I tried sending test mails. Seems its taking over 20mins to detect the new mail.
Also mails that were sent are still seen in the draft folder, missing in sent folder.  The mail was however received by the third party.

**Comment by jstejada** [comment]
hi @theauditor, I just checked your account and it seems to be syncing correctly, so I think you might be having the same issue as #2059. Can you try the fix suggested in that issue and let me know if you are still having problems? Thanks!

**Comment by theauditor** [comment]
Hi
First of all, thanks a lot for the help and the prompt replies. 
I went through #2059 and tried to find the config.cson anywhere in ~/.nylas file but was unable to. There was not cursor line in my config.json file.
One strange thing is, at times I get an error regarding my config.json file. Not sure if it is related but there is a high chance it could be.
![screenshot from 2016-05-14 00-32-39](https://cloud.githubusercontent.com/assets/3420004/15258953/0f568886-196c-11e6-8762-27068969d020.png)



Note: Even with this crazy issue I love N1.Hope I can fix it soon.

**Comment by theauditor** [comment]
Additionally : If I close and open the app, mail seem to sync.

**Comment by jackiehluo** [comment]
@theauditor Are you still experiencing this issue? We pushed a fix that might have resolved it.

**Comment by theauditor** [comment]
@jackiehluo  Will be updating my app tonight. Will let you know. Resetting the app had solved the issue for time being, but issue had returned.

**Comment by theauditor** [comment]
@jackiehluo  Apparently N1 is not starting now on my system.
I deleted the .nylas forlder.
Tried to start the client and the result is 
.nylas is created  with 
> .apm/      .node-gyp/ nohup.out  packages    (within it)


`/home/theauditor/.nylas/
├── .apm
│   ├── .apmrc
│   ├── _git-remotes
│   │   ├── git-github-com-emorikawa-windows-shortcuts-git-a433b2ee
│   │   │   ├── config
│   │   │   ├── HEAD
│   │   │   ├── objects
│   │   │   │   ├── info
│   │   │   │   └── pack
│   │   │   │       ├── pack-5afc13c5b629ad5daa7deaa330a440e7dd096000.idx
│   │   │   │       └── pack-5afc13c5b629ad5daa7deaa330a440e7dd096000.pack
│   │   │   ├── packed-refs
│   │   │   └── refs
│   │   │       ├── heads
│   │   │       └── tags
│   │   └── _templates
│   ├── _locks
│   ├── registry.npmjs.org
│   │   ├── async
│   │   │   └── .cache.json
│   │   ├── cheerio
│   │   │   └── .cache.json
│   │   ├── clean-css
│   │   │   └── .cache.json
│   │   ├── coffee-script
│   │   │   └── .cache.json
│   │   ├── core-js
│   │   │   └── .cache.json
│   │   ├── debug
│   │   │   └── .cache.json
│   │   ├── lodash
│   │   │   └── .cache.json
│   │   ├── minimatch
│   │   │   └── .cache.json
│   │   ├── mkdirp
│   │   │   └── .cache.json
│   │   ├── request
│   │   │   └── .cache.json
│   │   ├── rimraf
│   │   │   └── .cache.json
│   │   ├── source-map
│   │   │   └── .cache.json
│   │   ├── source-map-support
│   │   │   └── .cache.json
│   │   ├── type-detect
│   │   │   └── .cache.json
│   │   ├── underscore
│   │   │   └── .cache.json
│   │   ├── underscore.string
│   │   │   └── .cache.json
│   │   └── wordwrap
│   │       └── .cache.json
│   └── windows-shortcuts
│       └── 0.1.1
│           ├── package
│           │   └── package.json
│           └── package.tgz
├── .node-gyp
│   └── .node-gyp
│       └── 1.0.1
│           ├── common.gypi
│           ├── config.gypi
│           ├── deps
│           │   ├── http_parser
│           │   │   └── http_parser.h
│           │   ├── npm
│           │   │   └── node_modules
│           │   │       └── node-gyp
│           │   │           └── addon.gypi
│           │   ├── uv
│           │   │   ├── common.gypi
│           │   │   ├── include
│           │   │   │   ├── android-ifaddrs.h
│           │   │   │   ├── pthread-fixes.h
│           │   │   │   ├── stdint-msvc2008.h
│           │   │   │   ├── tree.h
│           │   │   │   ├── uv-aix.h
│           │   │   │   ├── uv-bsd.h
│           │   │   │   ├── uv-darwin.h
│           │   │   │   ├── uv-errno.h
│           │   │   │   ├── uv.h
│           │   │   │   ├── uv-linux.h
│           │   │   │   ├── uv-sunos.h
│           │   │   │   ├── uv-threadpool.h
│           │   │   │   ├── uv-unix.h
│           │   │   │   ├── uv-version.h
│           │   │   │   └── uv-win.h
│           │   │   ├── samples
│           │   │   │   └── socks5-proxy
│           │   │   │       ├── defs.h
│           │   │   │       └── s5.h
│           │   │   ├── src
│           │   │   │   ├── heap-inl.h
│           │   │   │   ├── queue.h
│           │   │   │   ├── unix
│           │   │   │   │   ├── atomic-ops.h
│           │   │   │   │   ├── internal.h
│           │   │   │   │   ├── linux-syscalls.h
│           │   │   │   │   └── spinlock.h
│           │   │   │   ├── uv-common.h
│           │   │   │   └── win
│           │   │   │       ├── atomicops-inl.h
│           │   │   │       ├── handle-inl.h
│           │   │   │       ├── internal.h
│           │   │   │       ├── req-inl.h
│           │   │   │       ├── stream-inl.h
│           │   │   │       ├── winapi.h
│           │   │   │       └── winsock.h
│           │   │   └── test
│           │   │       ├── benchmark-list.h
│           │   │       ├── runner.h
│           │   │       ├── runner-unix.h
│           │   │       ├── runner-win.h
│           │   │       ├── task.h
│           │   │       └── test-list.h
│           │   ├── v8
│           │   │   └── include
│           │   │       ├── libplatform
│           │   │       │   └── libplatform.h
│           │   │       ├── v8config.h
│           │   │       ├── v8-debug.h
│           │   │       ├── v8-experimental.h
│           │   │       ├── v8.h
│           │   │       ├── v8-platform.h
│           │   │       ├── v8-profiler.h
│           │   │       ├── v8-testing.h
│           │   │       ├── v8-util.h
│           │   │       └── v8-version.h
│           │   └── zlib
│           │       ├── contrib
│           │       │   ├── blast
│           │       │   │   └── blast.h
│           │       │   ├── infback9
│           │       │   │   ├── infback9.h
│           │       │   │   ├── inffix9.h
│           │       │   │   ├── inflate9.h
│           │       │   │   └── inftree9.h
│           │       │   ├── iostream
│           │       │   │   └── zfstream.h
│           │       │   ├── iostream2
│           │       │   │   └── zstream.h
│           │       │   ├── iostream3
│           │       │   │   └── zfstream.h
│           │       │   ├── minizip
│           │       │   │   ├── crypt.h
│           │       │   │   ├── ioapi.h
│           │       │   │   ├── iowin32.h
│           │       │   │   ├── mztools.h
│           │       │   │   ├── unzip.h
│           │       │   │   └── zip.h
│           │       │   └── puff
│           │       │       └── puff.h
│           │       ├── crc32.h
│           │       ├── deflate.h
│           │       ├── examples
│           │       │   └── gzlog.h
│           │       ├── gzguts.h
│           │       ├── inffast.h
│           │       ├── inffixed.h
│           │       ├── inflate.h
│           │       ├── inftrees.h
│           │       ├── trees.h
│           │       ├── zconf.h
│           │       ├── zlib.h
│           │       └── zutil.h
│           ├── installVersion
│           └── src
│               ├── async-wrap.h
│               ├── async-wrap-inl.h
│               ├── atomic-polyfill.h
│               ├── base-object.h
│               ├── base-object-inl.h
│               ├── debug-agent.h
│               ├── env.h
│               ├── env-inl.h
│               ├── handle_wrap.h
│               ├── js_stream.h
│               ├── node_buffer.h
│               ├── node_constants.h
│               ├── node_counters.h
│               ├── node_crypto_bio.h
│               ├── node_crypto_clienthello.h
│               ├── node_crypto_clienthello-inl.h
│               ├── node_crypto_groups.h
│               ├── node_crypto.h
│               ├── node_dtrace.h
│               ├── node_extern.h
│               ├── node_file.h
│               ├── node.h
│               ├── node_http_parser.h
│               ├── node_i18n.h
│               ├── node_internals.h
│               ├── node_javascript.h
│               ├── node_lttng.h
│               ├── node_lttng_provider.h
│               ├── node_lttng_tp.h
│               ├── node_object_wrap.h
│               ├── node_revert.h
│               ├── node_root_certs.h
│               ├── node_stat_watcher.h
│               ├── node_version.h
│               ├── node_watchdog.h
│               ├── node_win32_etw_provider.h
│               ├── node_win32_etw_provider-inl.h
│               ├── node_win32_perfctr_provider.h
│               ├── node_wrap.h
│               ├── pipe_wrap.h
│               ├── req-wrap.h
│               ├── req-wrap-inl.h
│               ├── spawn_sync.h
│               ├── stream_base.h
│               ├── stream_base-inl.h
│               ├── stream_wrap.h
│               ├── string_bytes.h
│               ├── string_search.h
│               ├── tcp_wrap.h
│               ├── tls_wrap.h
│               ├── tree.h
│               ├── tty_wrap.h
│               ├── udp_wrap.h
│               ├── util.h
│               ├── util-inl.h
│               └── v8abbr.h
├── nohup.out
└── packages`

**Comment by theauditor** [comment]
Just found out the process was running on pid:8881 but it seems the GUI part or a part of it never started. Is there a way to run it in debug mode so that I can post a trace?

**Comment by jackiehluo** [comment]
@theauditor Closing this issue for now because an update around that time should have fixed the client-side issue—did you get the app running?
