### ISSUE TITLE
Bug: Can't create a plugin. Always get 'Run with debug flags' dialog.

### ISSUE THREAD

**Issue by Fahrradflucht** [nylas/N1#2206]
If I click on `Create a Plugin` in the `Developer` menu I get the `Run with debug flags?` dialog even if I have the debug flags already enabled. If I click okay anyway, Nylas N1 restarts, debug flags stay enabled and if I click `Create a Plugin `again this whole thing repeats.

I think this wasn't the case a few weeks ago, so it must have been introduced in one of the recent updates.

--

##### What operating system are you using?
OSX El Cap 10.11.4

##### What version of N1 are you using?
Version 0.4.33-e8f137e

--

<img width="377" alt="screenshot 2016-05-12 22 02 51" src="https://cloud.githubusercontent.com/assets/13237661/15228613/58b6aee6-188d-11e6-82cf-3cff138814ec.png">
<img width="492" alt="screenshot 2016-05-12 22 03 03" src="https://cloud.githubusercontent.com/assets/13237661/15228614/58b6f162-188d-11e6-8862-3194a2f56be7.png">
--

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this has been fixed on master already, and should be out in a release in a few days. Cheers!
