### ISSUE TITLE
Read receipts do not work with "send later"

### ISSUE THREAD

**Issue by g105b** [nylas/N1#2207]
Operating system: Linux Ubuntu 16.04 64bit

N1: 0.4.16

No third party plugins installed for testing.

Using Gmail provider.

Not using attachments, signatures, etc.

*****

I have used the read receipts feature for a while now with no noticable issues. I always get the purple "eye" to show me that the email has been read.

However, I tried using the "send later" feature for a few messages last night. All of the emails were scheduled to send this morning, all emails were to different recipients, all emails were replied to, but none of the emails showed as read.

**Comment by bengotow** [comment]
Hey! Thanks for filing this—this /should/ work, I'll see if I can reproduce this afternoon.

**Comment by jackiehluo** [comment]
Should be fixed! Let us know if it isn't.
