### ISSUE TITLE
Non-encrypted password in activity window

### ISSUE THREAD

**Issue by j-faria** [nylas/N1#2209]
Hi,

When trying to diagnose some problems with IMAP credentials, I opened the activity window in N1 to see what it was doing.
Much to my surprise, **the log that appeared in the activity window contained my password!** No encryption was performed and apparently my password was just sent to some server somewhere just like this. 
Now, I don't know much about web security, but am I right in assuming that this is a security hazard?

**Comment by jstejada** [comment]
Hi @j-faria, thanks for bringing this up! Even though you saw your password in the Activity Window, this is not really a security hazard: N1 connects to the Nylas API over SSL, and all data sent through the wire is encrypted. The Activity Window is meant for debugging purposes, and we intentionally display there the requests in plain text, which does /not/ mean they are being sent in plain text.

However, this is a valid concern and we will look at hiding passwords in the Activity Window in a future update.

Thanks!

**Comment by p3k** [comment]
Wait a moment: why are you sending the password to the Nylas API, anyway? Even if it is sent encrypted, I assume the API (and thus, folks at Nylas) can decrypt and read the password… No?
