### ISSUE TITLE
N1 into tray Linux Mint Mate 17.2

### ISSUE THREAD

**Issue by Foxly1990** [nylas/N1#221]
Hello! Thanks for N1. How can I minimize application to tray in Linux Mint Mate 17.2? Where i can read about this?

**Comment by 0v3rth3d4wn** [comment]
If you could +1 this thread it would be great! We are asking for the same thing - https://github.com/nylas/N1/issues/217

**Comment by bengotow** [comment]
Hey @Foxly1990 —thanks for filing this. I'm going to close it as a duplicate of #217. We should be able to use the Electron Tray API (https://github.com/atom/electron/blob/master/docs/api/tray.md) to support both linux and Win32 system trays.

**Comment by Foxly1990** [comment]
Ok, thanks for the response
