### ISSUE TITLE
Bad twitter account and avatar displayed in the side-panel

### ISSUE THREAD

**Issue by prajmus** [nylas/N1#2210]
On the side-panel with the information about sender/receiver if I switch to my email I have links to twitter, facebook and linkedin. Facebook and LinkedIN take me to my actuall profiles, but Twitter doesn't. And it seems that avatar is also taken from twitter. So my sidebar looks like that:

![2016-05-13](https://cloud.githubusercontent.com/assets/1540934/15251183/7a5addba-1928-11e6-81e3-05d34e76ac1f.png)

But my actuall twitter account is: [https://twitter.com/prajmus](@prajmus)
I have account discoverability by email enabled.

##### Are there any related issues?

I haven't found any

##### What operating system are you using?
Windows 10 64-bit
##### What version of N1 are you using?
0.4.33

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't think so

**Comment by KevinMartin** [comment]
That information comes from clearbit.com.

You can go ahead and "claim" your email address and update your information here: https://claim.clearbit.com/claim

**Comment by jackiehluo** [comment]
Thanks, @KevinMartin! Yeah—we can't change the data we get, but you can modify the profile on Clearbit!
