### ISSUE TITLE
Collaboration inquiry: I can help localizing Nylas N1

### ISSUE THREAD

**Issue by Artjaazz** [nylas/N1#2212]
Hi! 
I am willing to help localizing Nylas N1 into Ukrainian and Russian languages. Pro bono
How can I get involved?
I am an IT Translator
My website: http://www.translationdesigner.com

**Comment by KevinMartin** [comment]
There is an issue you can post in and subscribe to: #24

**Comment by bengotow** [comment]
Thanks! Merging into #24.
