### ISSUE TITLE
Quick Replies Templates not editable

### ISSUE THREAD

**Issue by dtredger** [nylas/N1#2216]
When I go to the Quick Replies tab of preferences, there's a select box for the templates I've created. However, the most-recent template is always selected, and trying to choose another template causes a brief stutter to the selected template, but then goes right back to the most-recent template.

![nylas_template_issue](https://cloud.githubusercontent.com/assets/3212697/15264262/406d1e3a-1926-11e6-80d1-972e3d38218b.gif)
  
Using Version 0.4.33-e8f137e (0.4.33-e8f137e) on OSX 10.11.4
The only non-stock plugins installed are N1-Filters, -Jiffy, and -unsubscribe

**Comment by bengotow** [comment]
I've been able to reproduce this - will see if we can fix for the release today.
