### ISSUE TITLE
Bold text issue in composer

### ISSUE THREAD

**Issue by grinich** [nylas/N1#2217]
From a user:

> When I compose a message, I often make a bold heading, then I want to type some text beneath it, so I hit Ctrl-B to switch out of bold.  When I hit enter, the text continues to be bold until I backspace to the beginning of the line.

See this example video: https://www.dropbox.com/s/nlnu1maarvnfd7n/bold-bug.mov?dl=0

**Comment by bengotow** [comment]
Believe it or not, this is a dup of https://github.com/nylas/N1/issues/964

**Comment by grinich** [comment]
ahh thanks
