### ISSUE TITLE
N1 keeps creating \All label

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2218]
Dear all,

Does someone face the same issue that N1 seems to be re-creating a label called `\All`?

It reappears even after deletion.

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/15266785/f60a63b8-19af-11e6-83aa-58aded5dee6f.png)

**Comment by rouzbeh84** [comment]
Yes, this happens to me too and gets mapped to my gmail account when I'm in the browser.

**Comment by jackiehluo** [comment]
Hey! I'm not sure that that was us—is it still happening? Closing for now.

**Comment by plzh** [comment]
Yes, this still happen to me.
