### ISSUE TITLE
App shuts down after initial configuration (choose plugins screen) - Linux, Windows

### ISSUE THREAD

**Issue by noczesc** [nylas/N1#2219]
When I choose my mail service provider and select plugins after installing the app, it shuts down and needs to be turned on again. Shouldn't it stay open?

**Comment by bengotow** [comment]
Hey! Thanks for reporting this — it definitely should stay open. Can you try this with 0.4.36 and see if you still run into the problem?

**Comment by noczesc** [comment]
How can I get it? Is it the one that's on the website or do I have to compile something? I tested it on a version that was downloaded from the official website yesterday.

**Comment by jstejada** [comment]
@noczesc you should be able to get the latest version from the website

**Comment by jstejada** [comment]
hi @noczesc, does the app crash and restart? or does it it simply shut down? could you give me a bit more details regarding the circumstances that make the app crash? This might be related to #2240 or #2036.

thanks!

**Comment by MissOgra** [comment]
> Hi!! Bug report: I'm using the latest version on El Capitan. Everytime i want to use the option "propose > time to meet", the app crashes. No third-party plugins installed.

In my case, it just shuts down, no restart.

**Comment by noczesc** [comment]
@jstejada it just shuts down like it was supposed to act like that, no crash logs in the terminal.

**Comment by noczesc** [comment]
I just re-installed N1 after rebuilding Manjaro from scratch and the problem
is gone - I've installed the newest version available in AUR. I don't know if
it's solved on Windows as well, because I got rid of it.  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.

**Comment by bengotow** [comment]
Hey folks - this should be resolved in the next release. It looks like we had a timer set too short for many windows/linux machines.

**Comment by jstejada** [comment]
Glad to hear that @noczesc . In any case v0.4.40 has shipped with a fix. Let me know if you keep having issues!
