### ISSUE TITLE
keyboard shortcut to switch accounts

### ISSUE THREAD

**Issue by evanemolo** [nylas/N1#222]
I have multiple accounts linked to N1. It would be great if there was a way to quickly get to different accounts via keystrokes instead mousing over to the dropdown and selecting. Perhaps something like cmd-1 for first account, cmd-2 for the second, etc.?

**Comment by jtflynnz** [comment]
I believe this is on the Trello list already: https://trello.com/c/teIoXFQh/41-account-switcher-with-keyboard-shortcut
