### ISSUE TITLE
First syncing takes sooo much time (1-2 mails / min)

### ISSUE THREAD

**Issue by Mastersey** [nylas/N1#2221]
Hello,

I would like to use N1 for my Google Inbox account but after setting up everything well, N1 take very very much time to sync mails... Approx. 1 or 2 mail per minute !!
I restarted my computer but the problem is the same. It will take days to sync everything... Is it a known issue or ... ?

Thanks for help :-) :+1: 

##### What operating system are you using?
Windows 10 64bits

##### What version of N1 are you using?
0.4.33

##### Do you have any third-party plugins installed?
only some included plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Only Gmail/Inbox tested

**Comment by jackiehluo** [comment]
Merging into #1004!
