### ISSUE TITLE
Cannot add IMAP account

### ISSUE THREAD

**Issue by Eldair** [nylas/N1#2224]
Hello,

Here is the error message (screenshot below) I get when trying to add custom imap account. I was able to add the same account to other email apps.

OS: Windows 10
N1 version: 0.4.36

![snag-16051520025000](https://cloud.githubusercontent.com/assets/470003/15275963/2fd760a2-1ada-11e6-900b-68aaef921350.jpg)

**Comment by bengotow** [comment]
Hey! Thanks for filing this - it looks like this was broken in the 0.4.36 release, and we just shipped a patch for it in 0.4.37. You can download it directly from https://edgehill.nylas.com/download?platform=win32. Sorry for the hassle—

**Comment by Eldair** [comment]
Great! Thanks a lot, I will try it out today.

**Comment by jstejada** [comment]
Hey, v0.4.40 has shipped with a fix and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
