### ISSUE TITLE
Can't use "Read receipts" / "Link tracking" - "Please provide a valid client_id"

### ISSUE THREAD

**Issue by argamanza** [nylas/N1#2226]
I just installed Nylas N1 for the first time on my manjaro Linux OS and wanted to use two of the features that were the most appealing to me while choosing to use it - Read receipts and Link tracking.

When i'm trying to use them i get an error pop up with the following message:

**When trying to use link tracking:** 

> Unfortunately, link tracking servers are currently not available. Please try again later. Error: Please provide a valid client_id. The client_id URL parameter should be the App ID of your plugin in the Nylas Developer Portal.

**When trying to use read receipts:**

> Unfortunately, read recepits are currently not available. Please try again later. Error: Please provide a valid client_id. The client_id URL parameter should be the App ID of your plugin in the Nylas Developer Portal.

I haven't changed or installed anything except the N1 client, and i haven't changed any perference - only synced the client with my GMail account using the built-in wizard.

---------

##### Are there any related issues?

I have see issues about both read receipts and link tracking not actually working, not about these errors poping when trying to use them.

##### What operating system are you using?
Manjaro Linux x86_64 (Arch based distro)

##### What version of N1 are you using?
Version 0.4.33-e8f137e

--

**Bug?**
##### Do you have any third-party plugins installed?
Nope, only the default plugins that comes with the nylas installation at the manjaro repos.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't think so, but fyi i'm using Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The bug happens when i'm opening the "Compose new message" dialog and when i'm pressing the "Enable read receipts" / "Enable link tracking" icons at the bottom of that dialogs.

![screenshot_2016-05-15_22-45-28](https://cloud.githubusercontent.com/assets/9576019/15276366/c96844d4-1aee-11e6-9ba2-d5d9d4a95ac3.png)
![screenshot_2016-05-15_22-45-40](https://cloud.githubusercontent.com/assets/9576019/15276367/c96ac70e-1aee-11e6-9d95-8959bc3b7790.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. This is a pretty strange error. Can you open the file at ~/.nylas/config.json and look for an "environment" value? It should say "production", but it sounds like it might be set to something different. Any chance you used N1 a long time ago or installed it from source it some point?

Sorry for the hassle! Hopefully it turns out to be something easy :)

**Comment by argamanza** [comment]
@bengotow  There is no "enviroment" in the file.

I installed N1 about a month ago in another OS of "antergos" (also arch based) and it didn't work because of some bug that made it refresh indefinitely.

There's a chance this is the cause of my issue?

**Comment by argamanza** [comment]
After looking at the [**CONFIGURATION.md**](https://github.com/nylas/N1/blob/master/CONFIGURATION.md) file i added `"env": "production",` at the top of the _~/.nylas/config.json_ file, as you can see in the attached picture.
This solved it.

![screenshot_2016-05-16_16-46-17](https://cloud.githubusercontent.com/assets/9576019/15291286/c2162772-1b85-11e6-9df5-39460d083f4e.png)

I would close this issue but i first want to hear from you and maybe help you understand how did it happen, so this bug could be avoided in the future.

**Comment by jstejada** [comment]
hi @argamanza thanks for reporting this. this is actually due to an known issue regarding the config.json file. we will release a fix for this very soon. Sorry for the hassle!
