### ISSUE TITLE
The "multiple messages selected" dialog should contrast with the dark theme better

### ISSUE THREAD

**Issue by rakeshdas1** [nylas/N1#2228]
I just installed the latest version of N1, 0.4.37 and thought that I would switch over to the built-in Dark theme, but I noticed one flaw in the theme. When I select multiple messages in the inbox, there is a graphic that shows up in the message view area that informs you of the number of messages that you have selected. But, you can't see that text very well since it is a light gray and the stack of papers is white as well, see the attached screenshot for more info. I think we should make the text black so that it is more visible.
![image](https://cloud.githubusercontent.com/assets/6901641/15276916/2c1560d2-1abb-11e6-8e6d-f4a02e2094cc.png)

**Comment by bengotow** [comment]
(cc @jackiehluo )

**Comment by rakeshdas1** [comment]
Also present on certain emails, where the background is white and N1 colors the BG black, but makes the text a black-grey color. Please see the screenshot for more clarity.
![image](https://cloud.githubusercontent.com/assets/6901641/15292229/ad66182a-1b47-11e6-9720-6157f798625b.png)

**Comment by jackiehluo** [comment]
@rakeshdas1 That second one's tougher to fix—some emails have hardcoded colors for text, and we can't do too much to change that. But the first one is super doable! Will check with @sdewith on what we should do.

**Comment by rakeshdas1** [comment]
@jackiehluo Awesome! And I guess it would be janky if we overrode the email's color palette and messed around with it.

**Comment by bengotow** [comment]
Hey! Unfortunately these emails have hard-coded colors. The dark gray text color is being explicitly applied to the text by the sender, and there's not much N1 can do to properly override it (without breaking other emails where the coloring is meaningful.) We can do some smart inversion of colors, and we're going to re-enable it in e3b1120. It has some side effects, but we think it's probably the best we can do for now. Cheers!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
