### ISSUE TITLE
Accounts names turned back to full email addresses

### ISSUE THREAD

**Issue by shyukri** [nylas/N1#2230]
After latest update My accounts aliases ex. GMAIL/YAHOO was reset and it shows my full email address like nickname@gmai.com

##### Are there any related issues?
NO

##### What operating system are you using?
OSX El Capitan

##### What version of N1 are you using?
Version 0.4.37-7d5ecac (0.4.37-7d5ecac)

**Bug?**
##### Do you have any third-party plugins installed?
NO

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
NO

**Comment by bengotow** [comment]
Hey! Thanks for filing this - this has been fixed in 29fc4c80d87af13198915bd2eb577b3521c09980. We're actually shipping a patch for a few other critical issues so this will be live in 0.4.38 very soon.

**Comment by shyukri** [comment]
awesome!

**Comment by jstejada** [comment]
Hey @shyukri , v0.4.40 has shipped and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
