### ISSUE TITLE
Mail not fetching after upgrading to 0.4.37-7d5ecac

### ISSUE THREAD

**Issue by markbao** [nylas/N1#2231]
Mail will only fetch immediately after startup, but will not fetch while the app is open.

Issue only started happening after updating to 0.4.37.

##### Are there any related issues?

@2204

##### What operating system are you using?

OS X 10.11.4 (15E65)

##### What version of N1 are you using?

0.4.37-7d5ecac

--

**Bug?**
##### Do you have any third-party plugins installed?

N1-Unsubscribe

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Not sure

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

**Comment by jstejada** [comment]
hey @markbao, this is a known issue with the latest update #2227 . A fix will be released soon

**Comment by markbao** [comment]
Ah, didn't see that because the title was talking about push notifications. Thanks!
