### ISSUE TITLE
Search query stop work from certain size / complexity

### ISSUE THREAD

**Issue by pavelbinar** [nylas/N1#2234]
##### What operating system are you using?
OS X El Capitan 10.11.4

##### What version of N1 are you using?
Version 0.4.37-7d5ecac (0.4.37-7d5ecac)

--

**Bug**

I am u using Gmail like search query. Example:

`from:(OR support@everlane.com OR notifications@e.livestream.com OR notification@facebookmail.com OR marc@frontendmasters.com OR no-reply@e.udemymail.com OR hello@sidebar.io OR support@pingdom.com OR @plus.google.com)`

It works great, BUT from certain number of emails it stop work. My search query is pretty big: about 22 emails and I am going to make it even bigger later on.

The query of 22 emails works well in Gmail but do not give me any results in N1. If I decrease number of queried emails to 9 it works again. I am not sure it the 9 is the maximum number.

##### Do you have any third-party plugins installed?
N1 unsubscribe

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
All my accounts (5) are Gmail.

**Comment by jackiehluo** [comment]
Merging into #750.
