### ISSUE TITLE
New Feature request: Silent launch

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2235]
##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.38

I added the new option `--background` to N1 and hoping this would be a silent start-up option.

So can we have a `--silent` option that that loads N1 in the background:

- No slash screen
- Does not open the main window on the desktop

This would be a Windows centric option as I seem to remember OS X Finder has options to do this.  But my MacPro is not available to me for the next few months for me to test.

**Comment by bengotow** [comment]
Hi @molstrangler — this should be working via the `background` flag, as of version 0.4.40. Can you try this again?

**Comment by molstrangler** [comment]
Hi,

I'm running 0.4.40 now.  Though the slash screen has gone, I would like N1 to open minimized and not display its main window.  Right now N1 displays it's main window with the `background` open included.

Thanks.
