### ISSUE TITLE
Ubuntu - Spell checking not working at all. 

### ISSUE THREAD

**Issue by mjwhaley** [nylas/N1#2236]
Does anyone have any ideas why the spell checking function in Nylas isn't working at all. 

I'm running Ubuntu 16.04 LTS 

Any help would be appreciated.

**Comment by keyuan** [comment]
Same here. Spelling check doesn't on Ubuntu 16.04 LTS.

**Comment by vangelas** [comment]
Same here, on xubuntu. Probably a deal breaker for me :(

**Comment by CharlesAngerstein** [comment]
I can't even find a menu option to turn it on or off.  Site says it should be on by default but then doesn't mention where to find the setting.  No spell check is a pretty big deal, but for now I'll keep using it.

**Comment by annielcook** [comment]
Another incident: https://nylas.zendesk.com/agent/tickets/4563

**Comment by CharlesAngerstein** [comment]
I was able to fix this by going into the language preferences and switching the language to English (US) instead of English(Canada).  After restart everything worked as expected.  Hopefully the issue will be fixed soon but if you don't mind your spelling looking a little weird this workaround works for me.

**Comment by leolower** [comment]
Thanks @CharlesAngerstein, that worked for me too! 
Now I need to figure out how to make it work with spanish :)

**Comment by purplepixie** [comment]
Same problem for me. My language is set to English (United Kingdom) and spell checking works fine in other things that use system dictionary such as Evolution. In the console navigator.language gives en-GB and navigator.languages gives [] - which seems to be what it should be (from other threads).

**Comment by nicholasbutlin** [comment]
Same here - English (UK) not working on Ubuntu 16.04 and that would be really very useful / necessary for me!

**Comment by orschiro** [comment]
Dear all, 

I am adding myself to this conversation as I am interested in the following:

Is it possible to switch the language dictionary used when composing a message?

-Thankfully,

-Robert

**Comment by jackiehluo** [comment]
Merging into #1392! We're hoping to make some changes with spellcheck soon.
