### ISSUE TITLE
Sending wheel keeps spinning and will not stop.....

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2238]
##### Are there any related issues?

...

##### What operating system are you using?
...10.11.4

##### What version of N1 are you using?
...Version 0.4.38
--

**Bug?**
##### Do you have any third-party plugins installed? Yes

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![sendingerror](https://cloud.githubusercontent.com/assets/16170272/15292802/1cb1ed22-1b42-11e6-9282-f900653dcff0.jpg)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
No

**Comment by oldhickory30** [comment]
The sending wheel keeps spinning and will not stop unless I restart, even though the message has been sent.

**Comment by a85** [comment]
+1 Facing the same issue here.

**Comment by cpkdevries** [comment]
+1 on OSX 10.11.5 version 0.4.38

**Comment by emorikawa** [comment]
Yes, we're unfortunately still seeing with issues with this. I'm closing this and merging it into the broader issue here: https://github.com/nylas/N1/issues/2446
