### ISSUE TITLE
Preferences tool bar is partially covered by the app's chrome bar.

### ISSUE THREAD

**Issue by iamaaronmartin** [nylas/N1#2239]
It was fine on first install, but after changing the theme, it was all borked from there on after.

OS X 10.11.4
N1 Version 0.4.38-27d21d1 (0.4.38-27d21d1)
![screen shot 2016-05-16 at 10 00 02 am](https://cloud.githubusercontent.com/assets/264596/15297069/296fec48-1b4d-11e6-860d-3284f85bcd3e.png)

**Comment by jackiehluo** [comment]
@iamaaronmartin Hey! Which theme are you using?

**Comment by iamaaronmartin** [comment]
It's like this for every theme now, I can't remember the theme that triggered this though.

**Comment by jackiehluo** [comment]
@iamaaronmartin Hm... Any errors in the console if you go to `Developer -> Toggle Developer Tools`? And does the issue persist if you reload N1?

**Comment by iamaaronmartin** [comment]
The error is persistent through a reload.

Only one error returned in console:
`/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:270 INVALID PACKAGE: Your package at /Users/aam/.nylas/packages/Nylas-N1-theme-master does not have a properly formatted 'package.json'. You must include an {'engines': {'nylas': version}} property(anonymous function) @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:270`

**Comment by jackiehluo** [comment]
@iamaaronmartin Want to try removing that package in `~/.nylas/packages` to see if that fixes the problem? Looks like it might be an issue with the third-party theme.

**Comment by iamaaronmartin** [comment]
Removing all the themes fixed the problem. I'm adding themes back in one at a time and checking. I'll post again if I find the problem.

**Comment by jackiehluo** [comment]
@iamaaronmartin Sounds great! Going to close this issue for now, since it sounds like it's a problem with a third-party package, but let me know if that changes. Thanks!
