### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by leah9272** [nylas/N1#224]
where can i get the compiled version of N1? To fix my sound and alert issue. thanks.

**Comment by bengotow** [comment]
Hi @leah9272 —you can download them from our servers by clicking the link in your invitation code email. You can also get the latest versions here:

https://edgehill.nylas.com/download?platform=win32
https://edgehill.nylas.com/download?platform=darwin
https://edgehill.nylas.com/download?platform=linux
