### ISSUE TITLE
Latest Version Crashing

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2240]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jstejada** [comment]
hi @oldhickory30, thanks for reporting this. under what circumstances is N1 crashing?

Thanks!

**Comment by oldhickory30** [comment]
Reading or sending emails!

**Comment by MissOgra** [comment]
Hi!! Bug report: I'm using the latest version on El Capitan. Everytime i want to use the option "propose time to meet", the app crashes. No third-party plugins installed.

**Comment by jstejada** [comment]
thanks for the additional details @MissOgra.
@oldhickory30 , is N1 crashing and restarting by itself continually or just crashing? Does the crash occur when you try to open a new composer window or the "Propose times to meet" as @MissOgra? I just want to make sure if it is the same issue as #2036

Thanks!

**Comment by jstejada** [comment]
Hey folks, v0.4.40 has shipped and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
