### ISSUE TITLE
No archive button/action for Outlook (Exchange) account

### ISSUE THREAD

**Issue by middle8media** [nylas/N1#2242]
##### Are there any related issues?

No

##### What operating system are you using?
Mac - El Capitan

##### What version of N1 are you using?
Version 0.4.38-27d21d1 (0.4.38-27d21d1)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes

**Comment by jstejada** [comment]
hi @middle8media , this might be due to the fact that you don't have an `Archive` folder. Can you try creating a folder named `Archive`? After a while you should be able to archive. Let me know if this helps
