### ISSUE TITLE
Account Labels

### ISSUE THREAD

**Issue by arnav-gudibande** [nylas/N1#2245]
Every time Nylas N1 updates, the account label reverts back to the default.
For example, if one of my accounts was titled "Personal", after the app update, it reverts back to the full name of my personal email address.

##### What operating system are you using?
OSX 10.11.4 (MacBook Pro)

##### What version of N1 are you using?
0.4.38

**Comment by jackiehluo** [comment]
Merging into #2230—should be fixed and released soon!
