### ISSUE TITLE
Add account as POP3 not IMAP

### ISSUE THREAD

**Issue by chyupa** [nylas/N1#2247]
##### Are there any related issues?

Don't seem to find.

##### What operating system are you using?

Ubuntu 16.04

##### What version of N1 are you using?

0.4.33

**Bug?**
##### Do you have any third-party plugins installed?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

IMAP / SMTP Account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No issue.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes. Thunderbird has the option to choose between IMAP and POP3 when adding a new account. I wanted to know if N1 has this option as well because I can't seem to find it or will it become available in a future release.

Keep up the good work,
Razvan

**Comment by bengotow** [comment]
We do not support POP3. Sorry for the hassle!

**Comment by pereyrdi** [comment]
Please, one day support pop3 :)

**Comment by devyhia** [comment]
POP3 is not too bad after all ;)
