### ISSUE TITLE
Emoji's appear where images should be

### ISSUE THREAD

**Issue by koenpunt** [nylas/N1#2249]
##### Are there any related issues?

No

##### What operating system are you using?

```
OS X 10.11.5 beta
```

##### What version of N1 are you using?

```
0.4.38-27d21d1
```

See the numbered emoji's in the image below (also happened with other e-mails). Whereas this e-mail displays just fine in Gmail web for example.

![image](https://cloud.githubusercontent.com/assets/351038/15315348/3fc8ae6a-1c17-11e6-9794-ba693cd1a0a8.png)

#### Gmail web:
![image](https://cloud.githubusercontent.com/assets/351038/15315424/c92b1724-1c17-11e6-859c-1489d7b4d2e8.png)

**Comment by koenpunt** [comment]
Also here in this email from glassdoor: 

![image](https://cloud.githubusercontent.com/assets/351038/15321844/5af726c2-1c39-11e6-939d-996a66467dee.png)

**Comment by bengotow** [comment]
Hey @jackiehluo this might be the emoji regex?

**Comment by jackiehluo** [comment]
@koenpunt Any chance you still have these emails and could forward them to jackie@nylas.com? Curious to see how that might be happening!

**Comment by clempat** [comment]
The problem looks like from this: https://github.com/nylas/N1/blob/master/internal_packages/composer-emoji/lib/emoji-message-extension.jsx#L21. as they use alt="1" or alt="4" depending on the notation. 

I could suggest a PR but I did not find the specification when it should be replaced by an emoji or not using tag prop. Is there specific class ? is there no image source ?...

**Comment by koenpunt** [comment]
@jackiehluo just seeing this now, I've forwarded one.

**Comment by jackiehluo** [comment]
@koenpunt Ah, fixed now! Thanks!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
