### ISSUE TITLE
signatures from other people break quote collapsing functionality. 

### ISSUE THREAD

**Issue by quinn** [nylas/N1#2251]
##### Are there any related issues?

didn't find any

##### What operating system are you using?
OS X

##### What version of N1 are you using?

--

**Bug?**

For me, any time someone replies who has an email signature it breaks the thing that collapses the quoted email thread and leaves it open and un-collapsible. When I reply it shows it properly all collapsed but when they reply it opens it back up again. It seems to work fine if their client inserts the signature before the quoted replies rather than after. I guess it's hard to tell if they intended the quote to be a part of the email? I wonder how gmail does it :|

##### Do you have any third-party plugins installed?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
i don't know, only gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

For me, this has happened on any email where the sender has a signature and replies to an email that I am CC'd on.

**Comment by bengotow** [comment]
Closing as dup of #2064

**Comment by quinn** [comment]
@bengotow this has nothing to do with my signature, this is signatures in emails sent to me. It's about how they get quoted. These two issues don't seem related?

**Comment by quinn** [comment]
@bengotow maybe they are similar in the implementation of the fix, but the issues themselves are unrelated.

**Comment by bengotow** [comment]
Hey! Sorry you're right - I meant to close this as a dup of https://github.com/nylas/N1/issues/1426 but hit the wrong issue. Cheers!
