### ISSUE TITLE
Not possible to delete emails when using IMAP and a brand new email

### ISSUE THREAD

**Issue by andreborud** [nylas/N1#2252]
Mac with OSX el Capitan using Version 0.4.38-27d21d1 (0.4.38-27d21d1).

When using Nylas N1 with a brand new email that has no folders or labels or anything its not possible to delete or archive an email. Tried creating an archive folder and moved undesired emails there, but it filled up pretty quickly. 

Figured something was missing in my email account so I opened in once in Airmail which showed all emails I had moved to the archive folder in the main inbox. Anyway, Airmail fixed or added whatever was missing in the account. So once I open Nylas again I can now delete or archive emails. 

My guess is that Nylas doesn't create these vital parts automatically. Could be nice to have! :)

**Comment by jackiehluo** [comment]
Merging into #1457!
