### ISSUE TITLE
Send later not functioning predictably 

### ISSUE THREAD

**Issue by osakkers** [nylas/N1#2258]
I schedule a couple of emails to send later, but for some reason the scheduling is all messed up. 

When I set a specific *snooze* time, that works fine, but *send later* doesn't seem to work right.

It might be that it is snoozing according to some other time zone. I'm based in Israel, so ET +7hrs. Not clear.

In the image below, you can see the time on my computer's clock (top right 8:48PM), snooze later time (6:03PM) and time it is actually planning to sent on the message window (in 3 hours). 

<img width="1280" alt="send later malfunction" src="https://cloud.githubusercontent.com/assets/19175074/15333150/2dfa925c-1c71-11e6-8cf9-376ecfec4612.png">

I'd love for this feature to be predictable and reliable. 

Thanks!

OSX El Capitan
Version 0.4.38-27d21d1 (0.4.38-27d21d1)

**Comment by jstejada** [comment]
hey @osakkers, thanks for reporting this! This is no good. Can you tell me what time you scheduled it for specifically?

**Comment by osakkers** [comment]
6:03 PM - it's the second message in the drafts folder which you can see in the background and you can see the timestamp on the far right.

**Comment by osakkers** [comment]
Update: I checked my drafts folders again and the messages still haven't sent (even though previously it said they were due to send in 3hrs). It seems that it simply is failing to send. So it seems it's not a time zone/clock issue. See latest image:

<img width="1280" alt="nylas send later error 2" src="https://cloud.githubusercontent.com/assets/19175074/15354130/cfdbf308-1cf4-11e6-87e7-10d35e540286.png">

**Comment by jstejada** [comment]
thanks for the update @osakkers , still looking into this

**Comment by jstejada** [comment]
@osakkers could you also tell me at what time you scheduled it?

**Comment by osakkers** [comment]
Around noon if I recall correctly...

On May 19 2016, at 12:11 am, Juan &lt;notifications@github.com&gt; wrote:  

> [@osakkers](https://github.com/osakkers) could you also tell me at what time
you scheduled it?

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2258#issuecomment-220159558)![](https://github.com/notifications/beac
on/ASSWolmDKtl3ehepwY5gV1grbmEfwe3Oks5qC4CbgaJpZM4Igic_.gif)

**Comment by jstejada** [comment]
great, thanks! I think we know what is causing this, we should ship a fix soon. Thanks!

**Comment by osakkers** [comment]
Awesome. You guys are the best!

**Comment by bengotow** [comment]
Hey folks—we've dedicated more server resources to running the Send Later queue and it's resolved this issue. Cheers!

**Comment by agdfoster** [comment]
Hi, I scheduled a number of messages last night and not one of them sent this morning, despite my computer being on.

I also didn't get an alert or anything. Do I need to set reminders to check every time I send later? It's pretty disastrous if messages don't send!

Is there anything in place to ensure they get sent?

Help much appreciated.

**Comment by OFFPRICED** [comment]
send later dont work at all! The messages stay in the draft section then disappears, no one gets them, not in sent folder.

I really liked the Nylas app but the basic things are not working on this email as advertised. I really tried hard to love this app even i subscribed but I think i have to cancel my subscription now :(
