### ISSUE TITLE
Updating to 0.4.37 on OSX 10.9.5 crashes N1

### ISSUE THREAD

**Issue by michalkopanski** [nylas/N1#2259]
Since updating, the launcher crashes and relaunches indefinitely until I quit the app. I can't access N1 at all.

##### Are there any related issues?
None that I found.

##### What operating system are you using?
OSX 10.9.5

##### What version of N1 are you using?
 0.4.37

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Unknown — don't think so.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - sorry for the hassle. This should be fixed in the next update, which is coming out this afternoon. You'll need to download it from nylas.com manually, unfortunately. :-(

**Comment by michalkopanski** [comment]
:+1: Cool! Thanks for the update @bengotow.

**Comment by emphaticsunshine** [comment]
It's still crashing with 0.4.38 as well with OSX 10.11.4

**Comment by michalkopanski** [comment]
Same here. Still crashing with the new updated version.

**Comment by jstejada** [comment]
Hey folks, v0.4.40 has shipped and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!
