### ISSUE TITLE
Multiple Copies Of Messages In Conjunction w/ error #2238

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2260]
##### Are there any related issues?

...

##### What operating system are you using? 10.11.4
...

##### What version of N1 are you using? 
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by emorikawa** [comment]
Yes, we're unfortunately still seeing with issues with this. I'm closing this and merging it into the broader issue here: https://github.com/nylas/N1/issues/2446 Thank you for reporting!
