### ISSUE TITLE
Send later dialog lets the user pick a date in the past.

### ISSUE THREAD

**Issue by khamidou** [nylas/N1#2262]
If I enter a relative date, the send later UI defaults to a date in the current day. This is kind of weird if the date already happened (I'm typing this issue on May, 17 at 6pm).

![capture d ecran 2016-05-17 a 17 50 26](https://cloud.githubusercontent.com/assets/44081/15344051/de57105e-1c57-11e6-8d29-40c6fca0d5d0.png)

**Comment by grinich** [comment]
![greatscott](https://cloud.githubusercontent.com/assets/92417/15344212/f17649e6-1c59-11e6-98df-2add5a7a985e.png)

we'll get this fixed

**Comment by jstejada** [comment]
this has been fixed in v0.4.40!
