### ISSUE TITLE
Crash When Clicking "Propose times to meet" In Composer

### ISSUE THREAD

**Issue by inb4ohnoes** [nylas/N1#2263]
##### Are there any related issues?

https://github.com/nylas/N1/issues/1940 might be related

https://github.com/nylas/N1/issues/2240 references the issue but isn't mainly about this issue

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.38

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Comment by jackiehluo** [comment]
@inb4ohnoes This issue's been fixed, and we're releasing the patch soon!

**Comment by jstejada** [comment]
Hey folks, v0.4.40 has shipped and should be hitting the auto updater soon. Feel free to reopen or submit a new issue if you continue having trouble. Thanks!

**Comment by sanjnaverma** [comment]
Hey! Having the same issue on Mac OS X El Capitan
