### ISSUE TITLE
Incorrect view of the dark theme

### ISSUE THREAD

**Issue by AfftarN** [nylas/N1#2265]
After last update message body in dark theme has incorrect view. Before update everything was ok. I trying re-change theme, but no effect. Screenshots:
http://i.imgur.com/Y3xsChY.jpg
http://i.imgur.com/l7Aa3pa.png
http://i.imgur.com/fEJRySM.jpg

##### Are there any related issues?

...

##### What operating system are you using?
OS X 10.11.5
##### What version of N1 are you using?
0.4.38-27d21d1 (0.4.38-27d21d1)
--

**Bug?**
##### Do you have any third-party plugins installed?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Unfortunately these emails have hard-coded colors. The colors (sometimes images) are set by the sender, and there's not much N1 can do to properly override them without breaking other emails where the coloring is meaningful.

We used to try to invert and hue-rotate the colors to achieve a nice effect, but we turned it off after complains that some emails with background images were unacceptably inverted. However, it seems like that was the lesser of two evils. In the next update, we're going to re-enable that behavior. (e3b1120). It has some side effects, but we think it's probably the best we can do for now, and should address the scenarios you've highlighted. Cheers!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
