### ISSUE TITLE
docx files from others become corrupted

### ISSUE THREAD

**Issue by madart9** [nylas/N1#2267]
When I receive .docx files to my gmail account from other people, they become corrupted. This has happened with every .docx I have received from others (true across this and multiple previous versions). However, if I send myself a .docx file, I am able to open it.

I have not found related issues. I'm using Mac OS 10.11.4 and Nylas N1 version 0.4.38-27d21d1 (although the bug was in the two previous versions and possibly more). I have no third-party plugins and I can't test if it's true outside of gmail as that is my only account provider.

Thanks!

**Comment by Omeryl** [comment]
Hey,

Can you try to send me a docx to e@lizabeth.me?

**Comment by emorikawa** [comment]
This appears to be affecting .xlsx files too. We're looking into this further.

**Comment by jackiehluo** [comment]
Merging into #1240!
