### ISSUE TITLE
No email body

### ISSUE THREAD

**Issue by Nirjhor** [nylas/N1#2268]
##### Are there any related issues?

... No related issues I could find.

##### What operating system are you using?
... Fedora 23 64 bit

##### What version of N1 are you using?
... 0.4.38

--

**Bug?**
##### Do you have any third-party plugins installed?
... No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... Outlook

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
https://scr.hu/7zpJ16 Basically, I can't view email body, only subject and sender Sending works
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
... In every client I ever used

**Comment by bengotow** [comment]
Hey! This is very strange—can you let us know what email address you're seeing this with? It seems like N1 may not be receiving any message objects from our backend.

**Comment by Nirjhor** [comment]
Outlook. Com

**Comment by Nirjhor** [comment]
latest update doesn't fix it

**Comment by bengotow** [comment]
Merging into #2380
