### ISSUE TITLE
Office 365 sends mail but does not receive any mails or folder updates

### ISSUE THREAD

**Issue by cueamen** [nylas/N1#2273]
Hi There.

I really like your tool and thought I can use it at work. It seems that N1 is connected with the office 365 exchange server, because I can send emails.
But I can not receive any mails or Updates like an new folder. 

Any advice?

Thanks
Tobias

##### What operating system are you using?
Mac OS 10.11.5

##### What version of N1 are you using?
Version 0.4.38-27d21d1 (0.4.38-27d21d1)

**Bug?**
##### Do you have any third-party plugins installed?
Only have the includes plugins activated

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Office 365 Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yep. I already tried a new installation, restart etc.

**Comment by jackiehluo** [comment]
Closing this issue for now—for any user-specific issues, email us at support@nylas.com!
