### ISSUE TITLE
IMAP support.

### ISSUE THREAD

**Issue by jaypritchett** [nylas/N1#2274]
Hi!

I can't connect with Nylas N1 to my work mail account.

![zrzut ekranu z 2016-05-19 18-25-04](https://cloud.githubusercontent.com/assets/19264793/15401320/46abdb06-1def-11e6-9e3e-ff104b26fbe8.png)

Any other application like Thunderbird, Geary works perfectly.

**Comment by bengotow** [comment]
Hey! Can you provide more information? What is your IMAP / SMTP provider?

**Comment by njadmin** [comment]
@bengotow I met the same problem, the same as above ,my IMAP:imap.263.net ;SMTP:smtp.263.net 
Please help to solve this problem ,thanks.

**Comment by jaypritchett** [comment]
My IMAP provider is www.home.pl IMAP: promag-gaz.home.pl IMAP: promag-gaz.home.pl

**Comment by bengotow** [comment]
Hey folks—we narrowed this down and fixed it server-side on Tuesday. Can you try linking your accounts again and see if it works now? I'll re-open this if you keep having trouble, but for 90% of accounts this should work now. Cheers—
