### ISSUE TITLE
Yahoo and Google App Syncing issue

### ISSUE THREAD

**Issue by blbwd** [nylas/N1#2275]
Yahoo:
From N1 when I send any email from my Yahoo account then no items is showing in 'Sent Message' box after sending the email. Also while I checked from yahoo webmail version there is no email in 'Sent Item'. 

Google App:
From N1 I read my Google App emails but after reading those all the read emails are shown as unread while I check the same from Gmail later. IMAP is properly enabled and working fine but from N1 email status is not synced properly.

...

##### What operating system are you using?
Linux Mint

##### What version of N1 are you using?
0.4.33-edf137e

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I use Thunderbird and had never such issues.

**Comment by harbingerlabs** [comment]
+1 for google apps => was working prior to last update

**Comment by jackiehluo** [comment]
Merging into #781!
