### ISSUE TITLE
Copy/Move mail between accounts

### ISSUE THREAD

**Issue by jamestor** [nylas/N1#2276]
##### Are there any related issues?

I would like to request the ability to Copy To/Move To from one account to another, and pick which folder to copy/move to

##### What operating system are you using?
Windows 10 64 bit

##### What version of N1 are you using?
0.4.38

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes in Outlook 2016

**Comment by bengotow** [comment]
Hey! Thanks for filing this - unfortunately N1 doesn't support this and it's unlikely we'll be able to build it because it's a limitation of the sync engine. Closing as dup of #1819  so we can track interest in this feature!

**Comment by jamestor** [comment]
Thanks for your quick answer. If this functionality will not be available it does not make sense to continue using N1. I'm afraid I'll have to keep using Outlook until apear another email client that has this functionality.  Regards.
