### ISSUE TITLE
Unread box spits javascript to the page on ubuntu

### ISSUE THREAD

**Issue by madole** [nylas/N1#2277]
##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
v0.4.33-e8f137e

**Bug?** YES

##### Do you have any third-party plugins installed?
no third party apps

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I dont think it's specific to the provider but I'm only using Exchange. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Open Nylas N1
Go to Unread mail

See the screenshot for what I see 
![Imgur](http://i.imgur.com/HZh57aS.png)

**Comment by bengotow** [comment]
Wow - this is really interesting. It looks like the inbox zero graphic is rendering as plaintext? Can you look and see if it still happens after midnight? It might be related to a specific inbox zero graphic (there are 5 different ones.)

**Comment by xoniq** [comment]
I tried changing to any of them by changing the URL in the developer tools, all seem to work for me in OSX on the latest version.

**Comment by jackiehluo** [comment]
Closing because no one else has seen this issue... wondering if it's a weird one-off.
