### ISSUE TITLE
Updating to 0.4.37 on OSX 10.11.4 crashes N1 /to 0.4.40 again

### ISSUE THREAD

**Issue by Tobimahony** [nylas/N1#2279]
Since updating, the launcher crashes and relaunches indefinitely until I quit the app. I can't access N1 at all. **Also the manual download and install to version 0.4.40 doesn't work.** It's the same effect.

Are there any related issues?

None that I found.

What operating system are you using?

OSX 10.11.4

What version of N1 are you using?

0.4.40

Bug?

Do you have any third-party plugins installed?

No

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Unknown — don't think so.

**Comment by bengotow** [comment]
Hey thanks for reporting this—that's really strange. Can you try running this command, and send the logs that you see? I think that the app is crashing so fast it's not able to reach our crash reporting service, but I'd really like to get this fixed. Assuming you've installed it to /Applications, run this in a Terminal window:

`/Applications/Nylas\ N1.app/Contents/MacOS/Nylas --enable-logging`

**Comment by Tobimahony** [comment]
/Applications/Nylas\ N1.app/Contents/MacOS/Nylas --enable-logging

2016-05-21 20:43:31.001 Nylas[73969:52095623] Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-73969.log

2016-05-21 20:43:31.618 Nylas[73969:52095623] App load time: 728ms

[73969:0521/204332:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-73969.73976.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[73969:0521/204332:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-73969.73977.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[73969:0521/204332:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-73969.73975.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[73969:0521/204332:INFO:CONSOLE(18)] "Window load time: 679ms", source:
file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js
(18)

[73969:0521/204332:INFO:CONSOLE(318)] "%c Welcome to N1! If you're
exploring the source or building a plugin, you should enable debug flags.
It's slower, but gives you better exceptions, the debug version of React,
and more. Choose %c Developer > Run with Debug Flags %c from the menu.
Also, check out https://nylas.com/N1/docs for documentation and sample
code!", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/window-event-handler.js (318)

[73969:0521/204334:INFO:CONSOLE(18)] "Window load time: 1974ms", source:
file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js
(18)

[73969:0521/204334:INFO:CONSOLE(18)] "Window load time: 2080ms", source:
file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js
(18)

[73969:0521/204334:INFO:CONSOLE(35)] "Thread Search: Initializing thread
search index...", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/thread-search-index/lib/search-index-store.js
(35)

[73969:0521/204334:INFO:CONSOLE(56)] "Thread Search: Current index size is
0 threads", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/thread-search-index/lib/search-index-store.js
(56)

[73969:0521/204335:INFO:CONSOLE(306)] "Error: Delta Connection: Cursor is
invalid. Need to blow away local cache.

    at IncomingMessage.<anonymous> (/Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-long-connection.js:160:27)

    at emitOne (events.js:90:13)

    at IncomingMessage.emit (events.js:182:7)

    at IncomingMessage.Readable.read (_stream_readable.js:368:10)

    at flow (_stream_readable.js:751:26)

    at resume_ (_stream_readable.js:731:3)

    at _combinedTickCallback (internal/process/next_tick.js:74:11)

    at process._tickCallback (internal/process/next_tick.js:98:9)", source:
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js
(306)

2016-05-21 20:43:35.692 Nylas[73969:52095623] ErrorReporter: Shipping Logs.
Exception occurred

2016-05-21 20:43:35.695 Nylas[73969:52095623] /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/nylas-private-ship-logs-task

2016-05-21 20:43:35.710 Nylas[73969:52095623] Error: Delta Connection:
Cursor is invalid. Need to blow away local cache.

    at IncomingMessage.<anonymous> (/Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-long-connection.js:160:27)

    at emitOne (events.js:90:13)

    at IncomingMessage.emit (events.js:182:7)

    at IncomingMessage.Readable.read (_stream_readable.js:368:10)

    at flow (_stream_readable.js:751:26)

    at resume_ (_stream_readable.js:731:3)

    at _combinedTickCallback (internal/process/next_tick.js:74:11)

    at process._tickCallback (internal/process/next_tick.js:98:9)

[73969:0521/204335:INFO:CONSOLE(38)] "Backing off after sync failure. Will
retry in 3 seconds.", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker.js
(38)

Segmentation fault: 11

–––––––––––––––––––––––––––––––––
pressso - Beratung für Druckereien
Dipl.-Ing. (FH) Tobias Stange
Gohla Nr. 2
01683 Nossen

Tel.: 0172 / 79 51 665
Fax: 035242 / 435 089

Mitglied im Netzwerk "Die neutralen Berater"

2016-05-21 19:56 GMT+02:00 Ben Gotow <notifications@github.com>:

**Comment by emphaticsunshine** [comment]
Is this going to get fixed?

**Comment by Tobimahony** [comment]
Unfortunately not. I've downloaded the newest version und I checked for
first time the dialogbox -> open the old window and now I'm in the loop
again.

What can I do to get the first dialog box again?

Here is the log:

tobss-MacMini-2:~ tob$ /Applications/Nylas\ N1.app/Contents/MacOS/Nylas
--enable-logging

2016-06-09 10:21:45.230 Nylas[29694:36703239] Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-29694.log

2016-06-09 10:21:45.742 Nylas[29694:36703239] App load time: 605ms

[29694:0609/102146:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-29694.29696.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[29694:0609/102146:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-29694.29697.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[29694:0609/102146:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-29694.29698.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[29694:0609/102146:INFO:CONSOLE(18)] "Window load time: 497ms", source:
file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js
(18)

[29694:0609/102146:INFO:CONSOLE(318)] "%c Welcome to N1! If you're
exploring the source or building a plugin, you should enable debug flags.
It's slower, but gives you better exceptions, the debug version of React,
and more. Choose %c Developer > Run with Debug Flags %c from the menu.
Also, check out https://nylas.com/N1/docs for documentation and sample
code!", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/window-event-handler.js (318)

[29694:0609/102147:INFO:CONSOLE(18)] "Window load time: 1492ms", source:
file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js
(18)

[29694:0609/102147:INFO:CONSOLE(18)] "Window load time: 1507ms", source:
file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js
(18)

[29694:0609/102148:INFO:CONSOLE(35)] "Thread Search: Initializing thread
search index...", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/thread-search-index/lib/search-index-store.js
(35)

[29694:0609/102148:INFO:CONSOLE(56)] "Thread Search: Current index size is
0 threads", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/thread-search-index/lib/search-index-store.js
(56)

[29694:0609/102150:INFO:CONSOLE(306)] "Error: Delta Connection: Cursor is
invalid. Need to blow away local cache.

    at IncomingMessage.<anonymous> (/Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-long-connection.js:160:27)

    at emitOne (events.js:90:13)

    at IncomingMessage.emit (events.js:182:7)

    at IncomingMessage.Readable.read (_stream_readable.js:368:10)

    at flow (_stream_readable.js:751:26)

    at resume_ (_stream_readable.js:731:3)

    at _combinedTickCallback (internal/process/next_tick.js:74:11)

    at process._tickCallback (internal/process/next_tick.js:98:9)", source:
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js
(306)

2016-06-09 10:21:50.211 Nylas[29694:36703239] ErrorReporter: Shipping Logs.
Exception occurred

2016-06-09 10:21:50.213 Nylas[29694:36703239] /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/nylas-private-ship-logs-task

2016-06-09 10:21:50.224 Nylas[29694:36703239] Error: Delta Connection:
Cursor is invalid. Need to blow away local cache.

    at IncomingMessage.<anonymous> (/Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-long-connection.js:160:27)

    at emitOne (events.js:90:13)

    at IncomingMessage.emit (events.js:182:7)

    at IncomingMessage.Readable.read (_stream_readable.js:368:10)

    at flow (_stream_readable.js:751:26)

    at resume_ (_stream_readable.js:731:3)

    at _combinedTickCallback (internal/process/next_tick.js:74:11)

    at process._tickCallback (internal/process/next_tick.js:98:9)

[29694:0609/102150:INFO:CONSOLE(38)] "Backing off after sync failure. Will
retry in 3 seconds.", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker.js
(38)

[29694:0609/102150:INFO:CONSOLE(256)] "Retrieved 7 metadata objects",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/internal_packages/worker-sync/lib/nylas-sync-worker.js
(256)

[SECURITY] node-uuid: crypto not usable, falling back to insecure
Math.random()

2016-06-09 10:21:50.674 Nylas[29694:36703239] Running log ship:
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/,
Nylas-N1-29694[.0-9]*.log$

[29694:0609/102150:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-29694.29716.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[29694:0609/102150:INFO:CONSOLE(196)] "Streaming log data to
/var/folders/5t/mf_nr8ys7wjgp388lt_sdwc00000gn/T/Nylas-N1-29694.29715.log",
source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/error-logger.js (196)

[29694:0609/102151:INFO:CONSOLE(18)] "Window load time: 471ms", source:
file:///Applications/Nylas%20N1.app/Contents/Resources/app.asar/static/index.js
(18)

[29694:0609/102151:INFO:CONSOLE(318)] "%c Welcome to N1! If you're
exploring the source or building a plugin, you should enable debug flags.
It's slower, but gives you better exceptions, the debug version of React,
and more. Choose %c Developer > Run with Debug Flags %c from the menu.
Also, check out https://nylas.com/N1/docs for documentation and sample
code!", source: /Applications/Nylas
N1.app/Contents/Resources/app.asar/src/window-event-handler.js (318)

2016-06-09 10:21:51.268 Nylas[29694:36703239] undefined

2016-06-09 10:21:51.268 Nylas[29694:36703239] 503

2016-06-09 10:21:51.304 Nylas[29694:36703239] IncomingMessage {

  _readableState:

   ReadableState {

     objectMode: false,

     highWaterMark: 16384,

     buffer: [],

     length: 0,

     pipes: null,

     pipesCount: 0,

     flowing: null,

     ended: false,

     endEmitted: false,

     reading: false,

     sync: true,

     needReadable: false,

     emittedReadable: false,

     readableListening: false,

     resumeScheduled: false,

     defaultEncoding: 'utf8',

     ranOut: false,

     awaitDrain: 0,

     readingMore: false,

     decoder:

      { encoding: 'utf8',

        surrogateSize: 3,

        charBuffer: <Buffer 00 00 00 00 00 00>,

        charReceived: 0,

        charLength: 0 },

     encoding: 'utf8' },

  readable: true,

  domain: null,

  _events: { end: [Function: responseOnEnd] },

  _eventsCount: 1,

  _maxListeners: undefined,

  socket:

   TLSSocket {

     _tlsOptions:

      { pipe: null,

        secureContext: [Object],

        isServer: false,

        requestCert: true,

        rejectUnauthorized: true,

        session: undefined,

        NPNProtocols: undefined,

        ALPNProtocols: undefined,

        requestOCSP: undefined },

     _secureEstablished: true,

     _securePending: false,

     _newSessionPending: false,

     _controlReleased: true,

     _SNICallback: null,

     servername: null,

     npnProtocol: undefined,

     alpnProtocol: false,

     authorized: true,

     authorizationError: null,

     encrypted: true,

     _events:

      { close: [Object],

        end: [Object],

        finish: [Function: onSocketFinish],

        _socketEnd: [Function: onSocketEnd],

        secure: [Function],

        free: [Function: onFree],

        agentRemove: [Function: onRemove],

        drain: [Function: ondrain],

        error: [Function: socketErrorListener],

        data: [Function: socketOnData] },

     _eventsCount: 10,

     _connecting: false,

     _hadError: false,

     _handle:

      TLSWrap {

        _externalStream: {},

        fd: 58,

        _parent: [Object],

        _parentWrap: undefined,

        _secureContext: [Object],

        reading: true,

        owner: [Circular],

        onread: [Function: onread],

        writeQueueSize: 1,

        onhandshakestart: [Function],

        onhandshakedone: [Function],

        onocspresponse: [Function],

        onerror: [Function] },

     _parent: null,

     _host: 'sentry.nylas.com',

     _readableState:

      ReadableState {

        objectMode: false,

        highWaterMark: 16384,

        buffer: [],

        length: 0,

        pipes: null,

        pipesCount: 0,

        flowing: true,

        ended: false,

        endEmitted: false,

        reading: false,

        sync: false,

        needReadable: true,

        emittedReadable: false,

        readableListening: false,

        resumeScheduled: false,

        defaultEncoding: 'utf8',

        ranOut: false,

        awaitDrain: 0,

        readingMore: false,

        decoder: null,

        encoding: null },

     readable: true,

     domain: null,

     _maxListeners: undefined,

     _writableState:

      WritableState {

        objectMode: false,

        highWaterMark: 16384,

        needDrain: false,

        ending: false,

        ended: false,

        finished: false,

        decodeStrings: false,

        defaultEncoding: 'utf8',

        length: 0,

        writing: false,

        corked: 0,

        sync: false,

        bufferProcessing: false,

        onwrite: [Function],

        writecb: null,

        writelen: 0,

        bufferedRequest: null,

        lastBufferedRequest: null,

        pendingcb: 0,

        prefinished: false,

        errorEmitted: false,

        bufferedRequestCount: 0,

        corkedRequestsFree: [Object] },

     writable: true,

     allowHalfOpen: false,

     destroyed: false,

     bytesRead: 212,

     _bytesDispatched: 1791,

     _sockname: null,

     _pendingData: null,

     _pendingEncoding: '',

     server: undefined,

     _server: null,

     ssl:

      TLSWrap {

        _externalStream: {},

        fd: 58,

        _parent: [Object],

        _parentWrap: undefined,

        _secureContext: [Object],

        reading: true,

        owner: [Circular],

        onread: [Function: onread],

        writeQueueSize: 1,

        onhandshakestart: [Function],

        onhandshakedone: [Function],

        onocspresponse: [Function],

        onerror: [Function] },

     _requestCert: true,

     _rejectUnauthorized: true,

     parser:

      HTTPParser {

        '0': [Function: parserOnHeaders],

        '1': [Function: parserOnHeadersComplete],

        '2': [Function: parserOnBody],

        '3': [Function: parserOnMessageComplete],

        '4': null,

        _headers: [],

        _url: '',

        _consumed: false,

        socket: [Circular],

        incoming: [Circular],

        outgoing: [Object],

        maxHeaderPairs: 2000,

        onIncoming: [Function: parserOnIncomingClient] },

     _httpMessage:

      ClientRequest {

        domain: null,

        _events: [Object],

        _eventsCount: 1,

        _maxListeners: undefined,

        output: [],

        outputEncodings: [],

        outputCallbacks: [],

        outputSize: 0,

        writable: true,

        _last: true,

        chunkedEncoding: false,

        shouldKeepAlive: false,

        useChunkedEncodingByDefault: true,

        sendDate: false,

        _removedHeader: [Object],

        _contentLength: 1460,

        _hasBody: true,

        _trailer: '',

        finished: true,

        _headerSent: true,

        socket: [Circular],

        connection: [Circular],

        _header: 'POST /api/store/ HTTP/1.1\r\nX-Sentry-Auth: Sentry
sentry_version=5, sentry_timestamp=1465460510242,
sentry_client=raven-node/0.7.2,
sentry_key=7a32cb0189ff4595a55c98ffb7939c46,
sentry_secret=f791c3c402b343068bed056b8b504dd5\r\nContent-Type:
application/octet-stream\r\nContent-Length: 1460\r\nHost:
sentry.nylas.com\r\nConnection:
close\r\n\r\n',

        _headers: [Object],

        _headerNames: [Object],

        _onPendingData: null,

        agent: [Object],

        socketPath: undefined,

        method: 'POST',

        path: '/api/store/',

        parser: [Object],

        res: [Circular] },

     read: [Function],

     _consuming: true },

  connection:

   TLSSocket {

     _tlsOptions:

      { pipe: null,

        secureContext: [Object],

        isServer: false,

        requestCert: true,

        rejectUnauthorized: true,

        session: undefined,

        NPNProtocols: undefined,

        ALPNProtocols: undefined,

        requestOCSP: undefined },

     _secureEstablished: true,

     _securePending: false,

     _newSessionPending: false,

     _controlReleased: true,

     _SNICallback: null,

     servername: null,

     npnProtocol: undefined,

     alpnProtocol: false,

     authorized: true,

     authorizationError: null,

     encrypted: true,

     _events:

      { close: [Object],

        end: [Object],

        finish: [Function: onSocketFinish],

        _socketEnd: [Function: onSocketEnd],

        secure: [Function],

        free: [Function: onFree],

        agentRemove: [Function: onRemove],

        drain: [Function: ondrain],

        error: [Function: socketErrorListener],

        data: [Function: socketOnData] },

     _eventsCount: 10,

     _connecting: false,

     _hadError: false,

     _handle:

      TLSWrap {

        _externalStream: {},

        fd: 58,

        _parent: [Object],

        _parentWrap: undefined,

        _secureContext: [Object],

        reading: true,

        owner: [Circular],

        onread: [Function: onread],

        writeQueueSize: 1,

        onhandshakestart: [Function],

        onhandshakedone: [Function],

        onocspresponse: [Function],

        onerror: [Function] },

     _parent: null,

     _host: 'sentry.nylas.com',

     _readableState:

      ReadableState {

        objectMode: false,

        highWaterMark: 16384,

        buffer: [],

        length: 0,

        pipes: null,

        pipesCount: 0,

        flowing: true,

        ended: false,

        endEmitted: false,

        reading: false,

        sync: false,

        needReadable: true,

        emittedReadable: false,

        readableListening: false,

        resumeScheduled: false,

        defaultEncoding: 'utf8',

        ranOut: false,

        awaitDrain: 0,

        readingMore: false,

        decoder: null,

        encoding: null },

     readable: true,

     domain: null,

     _maxListeners: undefined,

     _writableState:

      WritableState {

        objectMode: false,

        highWaterMark: 16384,

        needDrain: false,

        ending: false,

        ended: false,

        finished: false,

        decodeStrings: false,

        defaultEncoding: 'utf8',

        length: 0,

        writing: false,

        corked: 0,

        sync: false,

        bufferProcessing: false,

        onwrite: [Function],

        writecb: null,

        writelen: 0,

        bufferedRequest: null,

        lastBufferedRequest: null,

        pendingcb: 0,

        prefinished: false,

        errorEmitted: false,

        bufferedRequestCount: 0,

        corkedRequestsFree: [Object] },

     writable: true,

     allowHalfOpen: false,

     destroyed: false,

     bytesRead: 212,

     _bytesDispatched: 1791,

     _sockname: null,

     _pendingData: null,

     _pendingEncoding: '',

     server: undefined,

     _server: null,

     ssl:

      TLSWrap {

        _externalStream: {},

        fd: 58,

        _parent: [Object],

        _parentWrap: undefined,

        _secureContext: [Object],

        reading: true,

        owner: [Circular],

        onread: [Function: onread],

        writeQueueSize: 1,

        onhandshakestart: [Function],

        onhandshakedone: [Function],

        onocspresponse: [Function],

        onerror: [Function] },

     _requestCert: true,

     _rejectUnauthorized: true,

     parser:

      HTTPParser {

        '0': [Function: parserOnHeaders],

        '1': [Function: parserOnHeadersComplete],

        '2': [Function: parserOnBody],

        '3': [Function: parserOnMessageComplete],

        '4': null,

        _headers: [],

        _url: '',

        _consumed: false,

        socket: [Circular],

        incoming: [Circular],

        outgoing: [Object],

        maxHeaderPairs: 2000,

        onIncoming: [Function: parserOnIncomingClient] },

     _httpMessage:

      ClientRequest {

        domain: null,

        _events: [Object],

        _eventsCount: 1,

        _maxListeners: undefined,

        output: [],

        outputEncodings: [],

        outputCallbacks: [],

        outputSize: 0,

        writable: true,

        _last: true,

        chunkedEncoding: false,

        shouldKeepAlive: false,

        useChunkedEncodingByDefault: true,

        sendDate: false,

        _removedHeader: [Object],

        _contentLength: 1460,

        _hasBody: true,

        _trailer: '',

        finished: true,

        _headerSent: true,

        socket: [Circular],

        connection: [Circular],

        _header: 'POST /api/store/ HTTP/1.1\r\nX-Sentry-Auth: Sentry
sentry_version=5, sentry_timestamp=1465460510242,
sentry_client=raven-node/0.7.2,
sentry_key=7a32cb0189ff4595a55c98ffb7939c46,
sentry_secret=f791c3c402b343068bed056b8b504dd5\r\nContent-Type:
application/octet-stream\r\nContent-Length: 1460\r\nHost:
sentry.nylas.com\r\nConnection:
close\r\n\r\n',

        _headers: [Object],

        _headerNames: [Object],

        _onPendingData: null,

        agent: [Object],

        socketPath: undefined,

        method: 'POST',

        path: '/api/store/',

        parser: [Object],

        res: [Circular] },

     read: [Function],

     _consuming: true },

**Comment by bengotow** [comment]
Hey folks - this should be fully addressed in 0.4.45. Will re-open this issue if the issue pops up again.
