### ISSUE TITLE
Allow pasting of a clipboard image into an email body

### ISSUE THREAD

**Issue by Ehesp** [nylas/N1#228]
The Gmail web client allows this making it very handy to quickly inject images into the body of your email content, by simply the commands:

Shift + CMD + Ctrl + 4 or 3

Then CMD + V to paste it.

**Comment by bengotow** [comment]
Hi @Ehesp — this should work if your keyboard is focused in the body of the email. Can you give that a try and let me know? I just double checked and it works for me, but it could be a platform-specific bug.

**Comment by Ehesp** [comment]
Hello - nope this doesn't work for me.

When trying to paste, the 'Edit' text in the toolbar does highlight, so the paste command is being picked up.

Version: 
![image](https://cloud.githubusercontent.com/assets/842078/10813527/c104f7e8-7e17-11e5-9f1e-a463a7440c92.png)
(Unable to copy the version text, might be something to do with it? Hence the image ^^)

Mac OS:
New Macbook Pro 15" (2015 model)
El Capitan
V 10.11

Tried on both an official external Mac keyboard and the built in one.

**Comment by Affyyia** [comment]
I will try it out

**Comment by bengotow** [comment]
Hey @Ehesp — just wanted to follow up on this. We've narrowed down the issue—you can paste images via `Cmd-V`, but you can't paste by right clicking and choosing Paste, which it sounds like you might be doing. I'll see if we can get this fixed.

**Comment by Ehesp** [comment]
Hello, I'll check when I'm next on the Mac however I was doing it via cmd
v, which didn't work.

Not tried in the latest updates so will let you know.

Cheers

**Comment by bengotow** [comment]
Thanks @Ehesp — I pushed a fix for "cannot paste images via right-click > paste". Feel free to re-open if you're still running into the issue, there may be something else going on.

**Comment by Ehesp** [comment]
Seems like it is working now - cheers!

**Comment by herveguetin** [comment]
Hi, this CMD+V trick is not working for me... The copied image goes as an attachment.

Here is what I do : 

. Take a screeshot
. Open the screenshot with Preview
. Select All => CMD+C
. Go to an email that is being written in Nylas
. Focus on the body of the email (the cursor is properly blinking there)
. CMD+V => bam... My image is treated as an attachment rather than being inlined :(

My Nylas version : Version 0.4.25-a22631a (0.4.25-a22631a)

Thanks a lot for your feedback!

**Comment by orschiro** [comment]
Just saw this thread while searching for something else. 

I can confirm that this is working on Ubuntu 16.04 with the latest N1. :)

~Robert

**Comment by manishie** [comment]
Yup I just noticed this as well.  On a Mac with the latest N1, the image comes in as an attachment and not inlined.
