### ISSUE TITLE
If an incoming email contains text after the quoted portion of the message the quoted portion is not properly collapsed

### ISSUE THREAD

**Issue by quinn** [nylas/N1#2281]
This is usually triggered by someone sending an email to N1 that inserts their signature after the quoted content rather than before. If they don't have a signature everything seems to work fine. Note: this has nothing to do with Nylas's signature functionality, this only has to do with how Nylas parses incoming emails. for example:

![image](https://cloud.githubusercontent.com/assets/3764/15426631/a2baa1b6-1e5d-11e6-9b73-f22de23d5191.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—unfortunately we're aware of this one. It needs to be fixed badly, but it's very difficult to tell the difference between meaningful text at the bottom of the email (ie: an inline reply with a whole paragraph at the bottom) and someone's signature. You can track this here: https://github.com/nylas/N1/issues/1426

**Comment by quinn** [comment]
@bengotow thanks for the follow-up :)
