### ISSUE TITLE
Right mouse button not working in some forms (copy/paste)

### ISSUE THREAD

**Issue by dszmaj** [nylas/N1#229]
There is no context menu when I tried to paste userid/password/host in mail configuration by clicking on the field with right mouse button. Only ctrl+c/ctrl+v works.

**Comment by dszmaj** [comment]
actually it does not work everywhere... only in email preview there is a context menu

**Comment by bengotow** [comment]
This has been fixed in 50576e59e3ab46639ce71782759982e2554e0a4c. Cheers!
