### ISSUE TITLE
Weird spacing in Activity window

### ISSUE THREAD

**Issue by khamidou** [nylas/N1#2290]
<img width="256" alt="capture d ecran 2016-05-20 a 15 14 53" src="https://cloud.githubusercontent.com/assets/44081/15443504/b3dec0ea-1e9d-11e6-9f6b-237e12b5c43b.png">

Platform: MacOS X 10.10 w/ French locale

**Comment by bengotow** [comment]
Hmm I think there are supposed to be icons there?

**Comment by ZarkBit** [comment]
same thing on the Windows release
![lyfw2bp 1](https://cloud.githubusercontent.com/assets/4160341/15466373/2976546e-20d1-11e6-9cae-80d7a89181fb.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
