### ISSUE TITLE
Fedora 24: Could not depsolve transaction

### ISSUE THREAD

**Issue by Maggew** [nylas/N1#2293]
I just visited the website, downloaded the N1.rpm file and when I (R) Click "open with software install" I get this error after I click install button.

![Imgur](http://i.imgur.com/ff8InTU.png)

##### What operating system are you using?
Fedora 24

##### What version of N1 are you using?
None

**Comment by bengotow** [comment]
Hey! I think this has been fixed in the next release, but you can follow the conversation here: https://github.com/nylas/N1/issues/1832
