### ISSUE TITLE
Nylas N1 set synchronous message number to 0, and start to sync when reboot PC at each time when upgraded to version 0.4.40

### ISSUE THREAD

**Issue by yuphone** [nylas/N1#2294]
Nylas N1 set synchronous **message number to 0**, and start to sync when reboot PC at each time after upgraded to 0.4.40, what's wrong here?

##### Are there any related issues?
Unknown.

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.40

--

**Bug?**
##### Do you have any third-party plugins installed?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No.

**Comment by bengotow** [comment]
Hey! Are you seeing N1 re-sync completely from scratch each time you launch it? What do you mean by message number? Thanks—

**Comment by yuphone** [comment]
@bengotow Well, thanks for your quick reply. Bellow is screen shot of this issue. I had never seen re-sync completely in 0.4.40.

![default](https://cloud.githubusercontent.com/assets/4560883/15449989/ebf18976-1fc0-11e6-81ca-efc99409983e.png)

**Comment by yuphone** [comment]
After I clean C:\User\xx\.nylas and reinstall N1, it is OK now. Maybe this issue was cased N1-Markdown-composer plugin which I installed but didn't take effect.

**Comment by jackiehluo** [comment]
Closing this issue since it looks like it was resolved!
