### ISSUE TITLE
Show plugin version

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2299]
Dear all, 

It would be very useful to have some kind of information about the installed plugin version.

See below example. 

What do you think?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/15463031/ee5820e2-20c6-11e6-8c60-204df7a58b53.png)

**Comment by bengotow** [comment]
Sounds good to me— fixed in 3d5b21e4b25d8482353e55f53c4ad606391c7994!

**Comment by orschiro** [comment]
Great, I just love your responsiveness to user requests. :+1: 

Thank you! :smiley: 

~Robert

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
