### ISSUE TITLE
No way to edit account settings after account creation

### ISSUE THREAD

**Issue by dszmaj** [nylas/N1#230]
There is only "unlink" option which is highly unsuitable for imap/smtp

**Comment by mishoboss** [comment]
+1

**Comment by mcescalante** [comment]
+1

I would imagine the account settings can be changed on the OS-level with configs, but I think having a GUI for it instead of just the options to "unlink" would be great.

**Comment by bengotow** [comment]
Hi @dszmaj — we verify your account credentials when you set up the account, but you're definitely right that editing them (in case they change) would be nice. I don't believe this is currently supported in our underlying sync engine (http://github.com/nylas/sync-engine) but I'll see what we can do.

**Comment by dszmaj** [comment]
It would be great if you do, Ben :)

> On Oct 28 2015, at 7:07 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@dszmaj](https://github.com/dszmaj) — we verify your account credentials
when you set up the account, but you're definitely right that editing them (in
case they change) would be nice. I don't believe this is currently supported
in our underlying sync engine ([http://github.com/nylas/sync-
engine](https://github.com/nylas/sync-engine)) but I'll see what we can do.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/230#issuecomment-151936122).![](https://github.com/notifications/beac
on/ADvjwAmGaX6xOt885dhktmmStT9jpU2Pks5pAQZWgaJpZM4GWoGF.gif)

**Comment by ruttoa** [comment]
+1

**Comment by umpirsky** [comment]
+1

**Comment by InvisibleOrdinary** [comment]
+1

**Comment by mistryrakesh** [comment]
+1

**Comment by psoiree** [comment]
+1 

When You make a mistake, for example in the name of account, You can't edit it later. You must delete it and create new one again.

**Comment by chiangqiqi** [comment]
for me, the email account is manully set up, so It's quite a pain to delete and re-link the acount

**Comment by elitan** [comment]
+1

**Comment by THPubs** [comment]
+1

**Comment by keithgould** [comment]
Not being able to manage the fundamental settings of my IMAP (non standard) accounts is a deal killer. Need to be able adjust SSL settings and update account passwords. Shame NYLAS N! looks great but I can't recommend it with this feature missing

**Comment by mishoboss** [comment]
Guys, this is really a MUST. I really hope it is baking for the next major release.

**Comment by rtpaulino** [comment]
+1

**Comment by Bassforce86** [comment]
+1

**Comment by jmcastellote** [comment]
+1

**Comment by anandrajaram** [comment]
+1 Our org policy mandates that we update password every 90 days. It'll be pretty annoying if we have to disconnect and reconnect

**Comment by thisiswangle** [comment]
+1

**Comment by renan-renger** [comment]
+1

**Comment by drdaffey** [comment]
+1

**Comment by eduardodfj** [comment]
I'm also for this. +1 or even +2

**Comment by xdutaotao** [comment]
+1, we strongly need such feature like **"update account"** to change password. Hope anyone can update it, as our exchange server ask us to change mail password for **every-month**.

**Comment by silveraignacio** [comment]
Please! Add this option to update the password! 

Definitely delete the account and link it again is not the best option!

**Comment by bengotow** [comment]
Hey folks, you can now do this in N1 0.4.40 using the "Update Account Settings" button in Account Preferences. You need to put in your connection information again, but it will allow you to update endpoints, passwords, etc.

![image](https://cloud.githubusercontent.com/assets/1037212/15555751/f6f289cc-227e-11e6-9240-e76100827e42.png)

Cheers!

**Comment by elbamos** [comment]
This doesn't appear to work, at least with the local sync engine and gmail.  In fact it looks like in some circumstances, it is just impossible to change a password.

**Comment by dcrystalj** [comment]
sorry but this is stupid that you have to enter connection information again.

**Comment by xdutaotao** [comment]
@bengotow it seems not work very well for 0.4.40. after changing password, always report 'can no longer authenticate' . could you help to check it ?

**Comment by monkeydri** [comment]
could not verify access crendentials

- nylas n1 :  Version 0.4.204-c4a286f (0.4.204-c4a286f)
- nylas-sync engine : self-hosted
- OS : macOS 10.12
