### ISSUE TITLE
Possibility to know the opening scene of the email and the various people who opened (Like Streak for gmail)

### ISSUE THREAD

**Issue by guillaumefey** [nylas/N1#2300]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
@guillaumefey If you mean seeing the individual people for opens/clicks in the activity list, that's coming soon!

**Comment by Uelb** [comment]
@jackiehluo I think he actually meant getting information related to the user agent of the person who opens or clicks an email.
Streak for Gmail has these features : 
- Geolocation of the person who opens / clicks (based on the IP address)
- Browser or the application used (based on the UA)

Here are some screenshots of such a feature
<img width="233" alt="streak city" src="https://cloud.githubusercontent.com/assets/1913426/15496955/6e2a8fb8-2198-11e6-8ce6-fa858b257133.png">
<img width="253" alt="streak computer type" src="https://cloud.githubusercontent.com/assets/1913426/15496957/71f67bd4-2198-11e6-9956-d476b89a4056.png">

**Comment by jackiehluo** [comment]
@Uelb Ohhh, got it, thanks. We'll look at that! I think a big part of the reason they show it (at least, the geolocation) is because they can't show which specific person opened it, so the location allows you to guess.

**Comment by Uelb** [comment]
Yes, and if it is pixel tracking, I guess it is the only way of guessing who opens it. Cause the same pixel has to be sent to the different users (instead if you think about sending several emails, but then we lose the recipients hierarchy (cc, to, bcc)).

**Comment by jackiehluo** [comment]
@Uelb Nope, per-recipient tracking is coming soon!

**Comment by guillaumefey** [comment]
Thank you @Jackieluo

Le mardi 24 mai 2016, Jackie Luo <notifications@github.com> a écrit :

> @Uelb <https://github.com/Uelb> Nope, per-recipient tracking is coming
> soon!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nylas/N1/issues/2300#issuecomment-221366993>
>


-- 

Pour plus d'informations ou de précisions n'hésitez pas à me contacter.

Bien cordialement

Guillaume Fey
+33 1 76 34 00 45
+33 6 37 70 30 87
guillaume@inchbase.com
www.inchbase.com

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
