### ISSUE TITLE
Openning links in background

### ISSUE THREAD

**Issue by s** [nylas/N1#2303]
Hey! 
Thanks for the awesome work! I'd like to suggest an enhancement which is ability to open links in background without switching applications back and forth. It helps me focus on the mail content and I prefer checking the links after I'm done with reading the mail.

Thanks in advance,
/Said

**Comment by bengotow** [comment]
Hey! I think on the Mac and Windows, N1 supports holding down Command/Ctrl while clicking a link to open it in the background - can you try that? Not sure what platform you're on?

**Comment by s** [comment]
Oh, had no clue about this. I was always searching for a preference on settings to set. I'm using OS X and it worked. Thank you very much and sorry for your time.

**Comment by dubstrike** [comment]
It would be great if there was a preference to open links in background by default. Having to hold ⌘ every time is a bit inconvenient.
