### ISSUE TITLE
iMail Server 12.5.3.93 "Full IMAP support is not enabled for this account"

### ISSUE THREAD

**Issue by spenserhale** [nylas/N1#2306]
**Logs**
`{
  "host": "Spenser-Mac-Mini",
  "timestamp": "2016-05-23T18:17:10.901Z",
  "payload": [
    "ActionBridge: emptyWindow Action Bridge Broadcasting: willMakeAPIRequest"
  ]
}
{
  "host": "Spenser-Mac-Mini",
  "timestamp": "2016-05-23T18:17:11.624Z",
  "payload": [
    "ActionBridge: emptyWindow Action Bridge Broadcasting: didMakeAPIRequest"
  ]
}
{
  "host": "Spenser-Mac-Mini",
  "timestamp": "2016-05-23T18:17:11.624Z",
  "payload": {
    "error": null,
    "response": {
      "statusCode": 404,
      "body": {
        "message": "Full IMAP support is not enabled for this account. Please contact your domain administrator and try again.",
        "type": "auth_error",
        "error": "further_action_required"
      },
      "headers": {
        "server": "nginx/1.6.2",
        "date": "Mon, 23 May 2016 18:17:11 GMT",
        "content-type": "text/html; charset=utf-8",
        "content-length": "179",
        "connection": "close",
        "strict-transport-security": "max-age=31536000;"
      },
      "request": {
        "uri": {
          "protocol": "https:",
          "slashes": true,
          "auth": null,
          "host": "api.nylas.com",
          "port": 443,
          "hostname": "api.nylas.com",
          "hash": null,
          "search": "?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=e603ccdb-9298-4229-a006-75a5c3dab3a8",
          "query": "client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=e603ccdb-9298-4229-a006-75a5c3dab3a8",
          "pathname": "/auth",
          "path": "/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=e603ccdb-9298-4229-a006-75a5c3dab3a8",
          "href": "https://api.nylas.com/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=e603ccdb-9298-4229-a006-75a5c3dab3a8"
        },
        "method": "POST",
        "headers": {
          "authorization": "Basic Og==",
          "accept": "application/json",
          "content-type": "application/json",
          "content-length": 317
        }
      }
    },
    "body": {
      "message": "Full IMAP support is not enabled for this account. Please contact your domain administrator and try again.",
      "type": "auth_error",
      "error": "further_action_required"
    },
    "requestOptions": {
      "path": "/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=e603ccdb-9298-4229-a006-75a5c3dab3a8",
      "method": "POST",
      "body": {
        "settings": {
          "imap_port": 143,
          "ssl_required": false,
          "smtp_port": 25,
          "imap_host": "mail.pbhs.com",
          "imap_username": "spenser@pbhs.com",
          "imap_password": "*omitted*",
          "smtp_host": "mail.pbhs.com",
          "smtp_username": "spenser@pbhs.com",
          "smtp_password": "*omitted*"
        },
        "name": "Spenser Hale",
        "email": "spenser@pbhs.com",
        "provider": "imap"
      },
      "returnsModel": false,
      "timeout": 60000,
      "auth": {
        "user": "",
        "pass": "",
        "sendImmediately": true
      },
      "url": "https://api.nylas.com/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=e603ccdb-9298-4229-a006-75a5c3dab3a8",
      "json": true,
      "startTime": 1464027430901
    },
    "statusCode": 404,
    "name": "APIError",
    "message": "Full IMAP support is not enabled for this account. Please contact your domain administrator and try again.",
    "errorTitle": "further_action_required"
  }
}
{
  "host": "Spenser-Mac-Mini",
  "timestamp": "2016-05-23T18:17:11.639Z",
  "payload": [
    {
      "eventName": "Auth Failed",
      "eventArgs": {
        "errorMessage": "Full IMAP support is not enabled for this account. Please contact your domain administrator and try again.",
        "provider": "imap",
        "n1_id": "e603ccdb-9298-4229-a006-75a5c3dab3a8",
        "platform": "darwin",
        "version": "0.4.40-85cf726",
        "accountType": "Unified",
        "distinct_id": "a2p22cv54cpsjxd2ax3xo2u1l",
        "token": "9a2137b80c098b3d594e39b776ebe085",
        "mp_lib": "node"
      }
    }
  ]
}`

##### Are there any related issues?
[https://github.com/nylas/N1/issues/1909](#1909)
Similar issue but trying to be server specific with actionable information such as debug logs.

##### What operating system are you using?
OS X El Capitan (v 10.11.4)

##### What version of N1 are you using?
0.4.40-85cf726

--

##### Do you have any third-party plugins installed?
n1-unsubscribe, however doesn't work with it not installed as well.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Provider: iMail Server 
Version: 12.5.3.93
Option: No SSL

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Trying to set up an account on an iMail Server.

**Notes**
Nylas Team,
I have logged into the iMail settings, and there isn't settings that disable / enable IMAP for individual account. We have turned on IMAP for all accounts, since there was a global setting.
Using the same configuration as I used in the logs, the mail server talks to all other mail applications. I have tested and confirmed the same configuration works in Outlook 2003 & 2007 & 2010, Mac Mail, Outlook for Mac, Windows Mail, and Thunderbird.

What I can do next to help find a resolution to this bug?

**Comment by bengotow** [comment]
Hey! This should be fixed - can you try again?

**Comment by spenserhale** [comment]
@bengotow Thank you. That last update fixed it.

**Comment by bengotow** [comment]
Great! Thank you.
