### ISSUE TITLE
When searching for labels keyboard shortcuts are triggering

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#2307]
If you open the label picker and start typing before the popout has finished and the input field focused, then the keys will be interpreted as keyboard shortcuts.

To replicate, pretend you're searching for the label "companies". Enable Gmail shortcuts, then hit "l" immediately followed by "c". This will pop open a new composer before the label has focused.

0.4.40

**Comment by jackiehluo** [comment]
Closing this issue—I think it's fixed now? I can't reproduce!
