### ISSUE TITLE
Option to show count of total mail messages instead of just unread messages

### ISSUE THREAD

**Issue by mscottford** [nylas/N1#231]
I like to keep my inbox empty, so the total number of messages is a more useful number for me than the total number of unread messages. I'd like an option to have those numbers displayed prominently. One way to do that would be to show this number where the current unread counts are displayed.

If this is something that's more suited for a plugin, I'm happy to pursue that route.

**Comment by jamiewilson** [comment]
For lack of a better way to show that I have the same request for this feature: Me too. :)

**Comment by bengotow** [comment]
Closing as dup of https://github.com/nylas/N1/issues/1639, which has a bit more context.
