### ISSUE TITLE
Clear selection button not readable

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2311]
Dear all, 

The "Clear Selection" button under `Drafts` is not really readable on Ubuntu 16.04.

Warmly,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/15501614/bed40744-21ae-11e6-815d-22e341e55902.png)

**Comment by bengotow** [comment]
Fixed in 7bdcde7f3ae00745efadf1347699cf76c14b2712

**Comment by orschiro** [comment]
Thanks also here!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
