### ISSUE TITLE
Screenshot mode bug with Japanese text

### ISSUE THREAD

**Issue by aficiomaquinas** [nylas/N1#2314]
No related issues I could find.
Mac OS X 10.10 Yosemite
Version 0.4.40-85cf726
No third party plugins

##### Bug
Screenshot mode character replacement does not work with Japanese characters. Did not test other languages.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I just use Gmail, so I'm not sure.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screenshot 2016-05-24 21 44 33](https://cloud.githubusercontent.com/assets/304489/15526624/dc91ed7e-21f8-11e6-9883-35be01128a80.png)

**Comment by aficiomaquinas** [comment]
This might be a bug of the [BLOKK font](https://github.com/nylas/N1/blob/324296eb1ca562f21acec0efc7bd9a5337099532/internal_packages/screenshot-mode/assets/font-override.css), but it seems it doesn't have a repository

**Comment by bengotow** [comment]
Hey—confirmed that there aren't any updates to BLOKK. Unfortunately you can add Japanese characters to the sample HTML on their website and the same thing happens. We'll see if we can get this addressed, but we may just remove screenshot mode entirely in the future.

**Comment by jackiehluo** [comment]
Merging into #810.
