### ISSUE TITLE
remind me in 1 hour/day/week when noone reply for an email. 

### ISSUE THREAD

**Issue by arturbukowski** [nylas/N1#2318]
Hello
We all are busy and sometimes we forget to chase something.
I think will be nice to have a possibility to have a reminder that you sent an email 1 hour ago/yesterday/week ago and you don't have any replies. That will give me a possibility to send same email again, to make sure someone received an email and task will be done on time. 
whats you opinion?

**Comment by molstrangler** [comment]
+1

**Comment by jackiehluo** [comment]
Merging into #1568!
