### ISSUE TITLE
Composing box issues

### ISSUE THREAD

**Issue by ZarkBit** [nylas/N1#2319]
![zviynwx 1](https://cloud.githubusercontent.com/assets/4160341/15539058/06dfdfee-2278-11e6-9103-0e669c29d645.gif)

Why this behavior? Hide the "From" field when clicking on the "Subject" or even the main composing field?

Another thing, the icons at the bottom of that window are barely noticeable when using a dark theme, why not set the icons to white? This is using the default themes that are included on the Windows Installation

Nylas N1 0.4.40
Windows 7 x64

**Comment by jackiehluo** [comment]
The collapsing fields are typical behavior in Gmail! It creates more space (and the To: field is usually the more relevant information).

Hm, could you try opening another composer window (or just reloading the app)? It should look like this:
<img width="459" alt="screen shot 2016-05-25 at 10 17 19 am" src="https://cloud.githubusercontent.com/assets/8452682/15549744/ebc5d732-2262-11e6-81d3-cd76d89f08c8.png">

**Comment by ZarkBit** [comment]
Oh thank you for the input, I don't use gmail, so I didn't knew it was based on that.

As for icons, reloading Nylas solved it.

Thank you once again :)

**Comment by jstejada** [comment]
I'm closing this as it appears to be solved
