### ISSUE TITLE
Keyboard shortuct to open mail message

### ISSUE THREAD

**Issue by mscottford** [nylas/N1#232]
I've gotten in the habit of using `o` to open a mail message, which is one of the ways a message can be opened in Gmail. Adding this shortcut in addition to `[enter]` would be awesome. This seems like the kind of thing that might be configurable, but I'm not yet sure of the different places to look.

**Comment by mcescalante** [comment]
You can already map your own keybinds with the `keymap.cson` file. To access this file, go to `System Preferences > Shortcuts` and then select "Edit custom shortcuts" at the bottom of the file. The `keymaps.cson` file will be highlighted in your Finder. Open this file with a text editor. Add the following lines below the comments, and hit save:

```
'body':
  'o'        : 'core:focus-item'
``` 

You should have `o` working to open messages as well as `[enter]` now :smile:

**Comment by bengotow** [comment]
Thanks for the tip @mcescalante — you're totally right. We've gone ahead and added `o` as a default Gmail shortcut in in 37e3fe0f4533ee5139cf0c27ee8cf9a008bc4ffe, along with about a dozen other Gmail shortcuts we were missing. They'll be included in the next update (0.3.21). Enjoy!
