### ISSUE TITLE
[Feature request] Rename account

### ISSUE THREAD

**Issue by Phyxion** [nylas/N1#2321]
I'd like the ability to change the visible name of the account. Currently the email address is given but I'd like to give this a custom name.

**Comment by bengotow** [comment]
Hi - if you go to N1's preferences, you should be able to do this by changing the "Account Label" for the account. Cheers!

![image](https://cloud.githubusercontent.com/assets/1037212/15549318/e1f84c0a-2260-11e6-8e2e-eb1ef7fbcfb6.png)

**Comment by Phyxion** [comment]
Totally missed this, thanks :)
