### ISSUE TITLE
[Feature Request] Reply without quoted text

### ISSUE THREAD

**Issue by luctus** [nylas/N1#2323]
It would be awesome if we could remove all the email thread when we reply to an issue via email (including the signature). Thus, we maintain a healthy and clean github repo.

**Comment by bengotow** [comment]
Thanks for the feedback—the way emails from N1 appear on GitHub is consistent with the way emails from other mail apps appear on GitHub. Replying without quoted text would be nice, so I'm going to change this request to reflect that underlying feature.

**Comment by luctus** [comment]
Totally agree. It works just as all the email clients in the market... I was
just thinking in the fact that this client is made by developers for
developers ;)  
  

\--

Gustavo G  

On May 25 2016, at 12:52 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Thanks for the feedback—the way emails from N1 appear on GitHub is
consistent with the way emails from other mail apps appear on GitHub. Replying
without quoted text would be nice, so I'm going to change this request to
reflect that underlying feature.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/2323#issuecomment-221634118)![](https://github.com/notifications/beac
on/AAWSLflYQU_86Oorz0_sEOqLrr05c1KPks5qFH45gaJpZM4Imk2h.gif)

**Comment by luctus** [comment]
Oops, here it is :p

**Comment by rahatarmanahmed** [comment]
Will this option fix what we can see in @luctus's email reply by default? Any time I reply to a github email with something as simple as a single sentence, it shows up all weird like above. I've never had this problem with Gmail and I think that still keeps the quoted text. GitHub must be stripping it, and somehow Nylas is messing up the quoted text?

**Comment by jackiehluo** [comment]
Merging into #1986!
