### ISSUE TITLE
Can't create folders

### ISSUE THREAD

**Issue by joke2k** [nylas/N1#2329]
Seems to be no a way to create a new folder.
I tried to mouse over on all icons, and right-clicking but nothing happens. 

OS: Ubuntu 16.04
N1 version: 0.4.40

![screenshot from 2016-05-25 20-18-47](https://cloud.githubusercontent.com/assets/359076/15551378/fa740260-22b5-11e6-8edd-acd193b31af2.png)

Thank you

**Comment by bengotow** [comment]
Hey @joke2k — if you scroll down a + sign appears when you hover over the folder heading. Will see if can improve the affordance for this in the future.

![image](https://cloud.githubusercontent.com/assets/1037212/15555875/a36eecfe-227f-11e6-94ce-4cb5f8fd1557.png)

**Comment by joke2k** [comment]
Why we have different names and icons for Folders?

![screenshot from 2016-05-26 03-02-51](https://cloud.githubusercontent.com/assets/359076/15560713/7b79aba2-22ee-11e6-9d5f-e389377c6431.png)

**Comment by joke2k** [comment]
@bengotow have you seen my latest screenshot?
I can't see the Folder block in my sidebar... is it a bug?

**Comment by bengotow** [comment]
Oh sorry - just hover over "Labels". Some accounts have folders, others have labels.
