### ISSUE TITLE
Dev Tools Opens When Sending an Email

### ISSUE THREAD

**Issue by smithtimmytim** [nylas/N1#2330]
##### Are there any related issues?

Not that I could find.

##### What operating system are you using?

Mac OS 10.11.5

##### What version of N1 are you using?

Version 0.4.40-85cf726 (0.4.40-85cf726)

--

**Bug?**
##### Do you have any third-party plugins installed?

Nope. Only the built-in ones.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I don't think so. I use Gmail though, just in case.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Happens with any email I try to send.

![may-25-2016 14-56-46](https://cloud.githubusercontent.com/assets/1326249/15554285/02aa7360-2289-11e6-8cd3-aa538e40ad1f.gif)

**Comment by bengotow** [comment]
Hey! Can you copy paste the output from the console at the bottom of the developer tools? You may need to click this icon to see it:

![image](https://cloud.githubusercontent.com/assets/1037212/15555518/ef013d40-227d-11e6-95b3-10c9aa387e97.png)


That'll help us get this resolved!

**Comment by smithtimmytim** [comment]
@bengotow sorry for the delay. Here are the errors.

![screenshot 2016-06-16 12 09 54](https://cloud.githubusercontent.com/assets/1326249/16125889/5ab4f95c-33bb-11e6-84f9-5ed8f1840827.png)
![screenshot 2016-06-16 12 10 13](https://cloud.githubusercontent.com/assets/1326249/16125890/5ab865e2-33bb-11e6-87b3-c85bf0c353b8.png)

**Comment by jackiehluo** [comment]
Merging into #2188!
