### ISSUE TITLE
Replying in a thread does not send the mail

### ISSUE THREAD

**Issue by orangecoloured** [nylas/N1#2331]
I've just encountered this issue a second time.

In a mail thread, when I reply, my mail in the N1 client is indicated as sent, but actually it is not.
If I check my mail on the server, there's nothing there and participants of the thread receive nothing.

**Comment by grinich** [comment]
Woah that is not good! Can you write a note to support@nylas.com with as much details as possible? Ideally the subject of the message and when it was sent. Thanks!

**Comment by jackiehluo** [comment]
Hey! Going to close this issue for now—if it's still happening, let us know, and we'll investigate further!
