### ISSUE TITLE
Unable to Lookup or Search Google for highlighted text while composing

### ISSUE THREAD

**Issue by fayimora** [nylas/N1#2332]
##### Are there any related issues?

Not one I could find.

##### What operating system are you using?
Mac OS X El Capitan(10.11.5)

##### What version of N1 are you using?
Version 0.4.40-85cf726 (0.4.40-85cf726)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Sure. Type anything in the text are and right click.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, Mail.app

My first thought was that this had something to do with electron. Below are screenshots showing what's missing.

Looks good here. 
![screenshot 2016-05-26 11 21 07](https://cloud.githubusercontent.com/assets/648684/15571751/93dfbfc4-2334-11e6-9033-df36c2646071.png)

Can't lookup or search google while composing
![screenshot 2016-05-26 11 23 43](https://cloud.githubusercontent.com/assets/648684/15571752/986025b6-2334-11e6-9521-a6748ff26f45.png)

**Comment by jackiehluo** [comment]
Closing this issue for now because it's not in the scope of our project—for us, I think it makes most sense to keep composer-specific actions to the composer right-click menu!
