### ISSUE TITLE
Email body display height being set to 0?

### ISSUE THREAD

**Issue by tamagokun** [nylas/N1#2334]
##### Are there any related issues?

Could not find any related issues

##### What operating system are you using?
Mac OSX 10.11.3

##### What version of N1 are you using?
Version 0.4.40-85cf726 (0.4.40-85cf726)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't think so

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I've only seen this happen with emails from Massdrop. It does happen consistently, though I don't remember it happening in earlier versions of N1. Only recently.

The email body shows up, and then immediately gets hidden, almost like N1 is trying to figure out the height of the email body, and then it gets set to 0.

![screen shot 2016-05-26 at 10 10 27 am](https://cloud.githubusercontent.com/assets/487333/15577516/da1b9148-232a-11e6-9f9f-b89537ffe5f7.png)

**Comment by jstejada** [comment]
Hey @tamagokun thanks for reporting this. Is there any chance you could forward me any email that has this problem to juan at nylas?

**Comment by tamagokun** [comment]
Sent one to you.

I've noticed another behavior. If I view a different email, and then come back to the buggy email, it tries to redetermine its height and a little bit of the email is showing, but still getting cut off. Repeat a few more times and the email shows a bit more each time. Perhaps it has something to do with images loading.

**Comment by jstejada** [comment]
thanks! merging this into #1280 to keep track in a single place!
