### ISSUE TITLE
Could not reach Nylas API

### ISSUE THREAD

**Issue by shubham7109** [nylas/N1#2335]
Hello, I installed N1 for the first time and after the welcome message I get an error:

#### Sorry, we could not reach the Nylas API. Please try again, or email us if you continue to have trouble. (undefined).

I'm using Ubuntu 16.04
I tried everything from rebooting to re-installing but it doesn't seem to work.
I did try contacting through email, but received no response  Please let me know the problem and the possible solution.

**Comment by phsmith** [comment]
Hi @shubham7109, please go the following issue, in the comments, and see if it could help you: #2062

**Comment by shubham7109** [comment]
The issue in #2062 its different from mine. I'm unable to even launch the application and set up my account. I have attached screenshot of the error. 


![screenshot from 2016-05-27 08-58-44](https://cloud.githubusercontent.com/assets/14892474/15608651/48dfd80a-23e9-11e6-8a34-e24655c019a0.png)

**Comment by phsmith** [comment]
You're using proxy configuration?
You could try to launch N1 from a terminal and see what happens.

**Comment by shubham7109** [comment]
No I'm not. 
I tried through terminal using sudo & su but both does not seem to work.

**Comment by shubham7109** [comment]
It used to work fine until I upgraded to Ubuntu 16.04.

**Comment by bengotow** [comment]
Hmm that's strange, can you guys try running `curl https://invite.nylas.com/status`? That's the URL the app is trying to hit, and it just returns a small JSON blob. We're actually about to remove this part of the onboarding flow because it dates back to when N1 was in beta and we were restricting the number of sign ups.

**Comment by shubham7109** [comment]
I got the following output : 
<pre>
{ 
  "restricted": false
}
</pre>

**Comment by shubham7109** [comment]
Please respond

**Comment by phsmith** [comment]
I recommend that you remove any trace of N1 configurations on the system and try to open and reconfigure it again.
You must delete, or rename, $HOME/.nylas and $HOME/.config/Nylas\ N1/

**Comment by shubham7109** [comment]
I tried what you said, but every time I launch Nylas, gives me the same error and creates the files $HOME/.nylas and $HOME/.config/Nylas\ N1/ again.

**Comment by jackiehluo** [comment]
Closing this issue for now because the flow has changed significantly—for any user-specific issues, email us at support@nylas.com!
