### ISSUE TITLE
Single, specific email won't change labels.

### ISSUE THREAD

**Issue by crystalenka** [nylas/N1#2337]
When trying to archive an email, the UI displays a success label, however the email appears in the inbox again within a few seconds. Restarting Nylas as well as the computer does not work. I've archived it in Gmail as well - and it stays archived there, but remains in my Nylas inbox no matter what I try. Incidentally, trying to snooze it or apply different labels also does not apply.

##### Are there any related issues?
Possibly #781, #2081 (but restarting Nylas does not archive the threads)

##### What operating system are you using?
Mac OS X 10.11.5 (15F34)

##### What version of N1 are you using?
Version 0.4.40-85cf726 (0.4.40-85cf726)

--

**Bug?**
##### Do you have any third-party plugins installed?
less-is-more-master
n1-unsubscribe

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
All of my email accounts are routed through Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not that I'm aware.

**Comment by jackiehluo** [comment]
Hey! Going to close this issue for now, but if you see it again, let us know at support@nylas.com, and we can take a look at your account!
