### ISSUE TITLE
"Launch on system start" should not default to on

### ISSUE THREAD

**Issue by courajs** [nylas/N1#2338]
I strongly feel options like this should be opt-in.
Someone just trying this out would probably not want this active.
I prefer to have nothing launch at startup. 

I'm using Version 0.4.40-85cf726 (0.4.40-85cf726) on OSX 10.11.5 (15F34)

**Comment by karlingen** [comment]
This seems to be a matter of taste IMHO

**Comment by courajs** [comment]
I think it's presumptuous to enable by default. It's pushy. I doubt having this off by default will annoy anyone. Having it on may annoy many people

**Comment by bengotow** [comment]
Hey! Thanks for posting this—unfortunately this is intended behavior. For better or worse, this is also the default behavior of Slack, Spotify, etc., upon installation. We may change this in the future if we hear more feedback, though. Cheers!
