### ISSUE TITLE
Label Order is Last Modified + Alpha, should be Alpha

### ISSUE THREAD

**Issue by jeffmcneill** [nylas/N1#2339]
I've edited labels in N1, and then they appear at the bottom of the label list when trying to assign a label to an email. The sidebar shows the proper order but the dropdown from the label button in an email does not.

![screen shot 2016-05-28 at 11 45 14](https://cloud.githubusercontent.com/assets/3119827/15625249/c968daae-24c9-11e6-8903-e6bb4460cbdf.png)

![screen shot 2016-05-28 at 11 44 59](https://cloud.githubusercontent.com/assets/3119827/15625250/c96f8c5a-24c9-11e6-992f-ba0b7c677afc.png)

**Comment by jeffmcneill** [comment]
May be related to Issue #192

**Comment by bengotow** [comment]
Hmm - it looks like the labels in that dropdown actually aren't being explicitly sorted at all. I'll see if we can get that fixed in the next update.

**Comment by jeffmcneill** [comment]
@bengotow the labels were identical in the sidebar and the dropdown until I edited some of them, then they got out of whack somehow. But on an initial new N1 install, they come in identical then changes seem to have them sort on last edit+alpha (I use hyphens to get those labels sorted to the top).

Also, just to reiterate, the colors are not matching and I'm not sure where they are coming from (what rhyme or reason by which colors are selected). I've got all labels as light grey in Gmail/Google Apps.

**Comment by jeffmcneill** [comment]
Ok, I understand the Google label color limitation, which is fine. I don't use label colors myself. Most of these tickets are closed around label color, but one #808 has the fine distinction of proposing a gradient (like airmail). That would be a big improvement over random. Colors mean something, so random colors are discombobulating. If I could choose a grey (like the sidebar without colors) that would be fine. A better option would be a gradient because that would inform me better about where in the list of labels I am (and I use priority + alpha sort, so it would match my mental model).

- Better: grey labels as an option or default
- Best: gradient labels as an option or default
- Superbest: choice of random color, grey, or gradient label
- Superbest++: same on the sidebar (issue #1803 )

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
