### ISSUE TITLE
additional addresses

### ISSUE THREAD

**Issue by reimax** [nylas/N1#234]
Is it possible to specify an arbitrary mail boxes of the sender? In my gmail I collect mail from several different accounts and have to answer on the mailbox for which the letter came. I have not found vozmozhnotsi even add additional addresses, only new email accounts.

**Comment by laughedelic** [comment]
+1 for this feature

**Comment by fjarrett** [comment]
If I understand this correctly, I think the correct terminology here would be Aliases?

**Comment by fjarrett** [comment]
Looks like this one is already on the roadmap and in development https://trello.com/c/KO2UHr0i/24-send-using-aliases

**Comment by jstejada** [comment]
hey guys! we recently landed the alias feature in the latest version, so I'm closing this
