### ISSUE TITLE
-b or --backround option doesn't seem to work properly

### ISSUE THREAD

**Issue by apollonaute** [nylas/N1#2340]
##### Are there any related issues?

I think https://github.com/nylas/N1/issues/673 is a related issue.

##### What operating system are you using?
I'm on Ubuntu 16.04

##### What version of N1 are you using?
N1 version is 0.4.40-85cf726

**Bug?**
Ok, so I've ticket the "Launch on system start" option. I've seen that there is, in Ubuntu startup programs, a new line : /usr/share/nylas/nylas --background %U
So I exit N1 properly, and I tried to launch N1 in my terminal : nylas -b (or nylas --backround) and N1 launch... full screen! Too bad...
 
##### Do you have any third-party plugins installed?
Oh yeah ! 
- Jiffy
- n1-ido-master
- n1-unsubscribe-master
- + almost all the buildin plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nop!

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Nop!

--

**Comment by bengotow** [comment]
Hey—this is working fine for me, can you try `--background` with a "g"?

**Comment by apollonaute** [comment]
I need to try it at home but I'm pretty sure that I already did it well (meaning well spelled).

Oh? You have closed the issue??

**Comment by apollonaute** [comment]
Ok, I'm on it. Please have a look at the screenshot below. 
![capture du 2016-05-30 19-27-28](https://cloud.githubusercontent.com/assets/8547430/15655371/dbce8d4a-269c-11e6-8dc3-5054ec8d519d.png)

There is a problem, it's still NOT in "background" but in full screen at startup.

**Comment by apollonaute** [comment]
Ok my mistake, the "%U" seems to be the source of the problem.

Without it, it works. Topic closed!
