### ISSUE TITLE
Total Unread Count for Folders (including subfolders)

### ISSUE THREAD

**Issue by balintant** [nylas/N1#2349]
I have a bunch of folders. Separating different email addresses, different projects, companies I work for and others. All my messages are filtered/moved to these folders right when they arrive onto the FastMail servers.

Some of the folders I usually keep closed. Those folders I usually review once per week, but it's important part of my workflow to see the messages as they arrive, even if they are moved there automatically. For example when I have the following folders:

- Personal (0)
  - Money (13)
  - Account Information (2)
  - Travel (1)
  - Notes (0)

I use it like a notification system. I want to know about the activity in the Money folder, so in case somebody buys a $1000 application in Family Sharing on the App Store, I can call them immediately and tell them some really awful words, that nobody should ever use. :)

So, my idea would be to have a total count on the folders if they are not opened or a whole separate count, like:

- Personal (0) (16)
  - Money (13)
  - Account Information (2)
  - Travel (1)
  - Notes (0)

What do you think?

**Comment by bengotow** [comment]
Hey! I think this is a cool idea — I'll see if we can mock up what these indicators might look like. There have also been requests for `(unread) / (total)` in a bubble, so we might want to look at all these ideas holistically.

**Comment by bengotow** [comment]
Related: #231

**Comment by bengotow** [comment]
Closing as dup of #2100

**Comment by stdcerr** [comment]
Has there ever been any progress made on this issue since 2016?

**Comment by SullyPanda76cl** [comment]
Hi, as of October 2018 this issue is still not solved.
A lot of people is asking for it, and most important **Other emails clients does have this feature**
@bengotow , do you use gmail? don't you have nested labels that are lost of your sight?

**Comment by jerm** [comment]
@SullyPanda76cl nylas-mail hasn't been under development for over a year now. Ben continues this projectover at https://getmailspring.com/ 

https://github.com/Foundry376/Mailspring
