### ISSUE TITLE
Features Inbox Google

### ISSUE THREAD

**Issue by adrianoresende** [nylas/N1#235]
3 Issues very important for me:
- Task in list email
- Postpone email and task
- Categorie group show new messages on time. Example: Categorie newsletter show news emails in 7:00 AM

**Comment by bengotow** [comment]
Hi @adrianoresende — thanks for your interest in N1! If you have a Trello account, you can upvote these ideas on the open source roadmap: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap
