### ISSUE TITLE
Sync issues with other Apps?

### ISSUE THREAD

**Issue by Kashura** [nylas/N1#2350]
It seems that ever since I began using Nylas N1, I am having all kinds of sync issues. 

If I archive, delete, or read an email, that does not translate to other apps, or even Gmail itself. In example, an email that I long deleted in Nylas is still appearing in my Gmail inbox on the Web, and mobile apps such as Outlook and Spark, and other email clients such as Apple Mail and Polymail. 

At the same time there are still emails in my Gmail inbox that I also deleted in Nylas, but they are not showing in Nylas itself.

**Comment by jstejada** [comment]
Hey @Kashura , thanks for reporting this. We've confirmed that an unusually high number of actions are failing to be transmitted to the mail provider. This is already being tracked in issue #2059, and we'll post any updates there, so I'm going to merge this in. Sorry for the hassle
