### ISSUE TITLE
UX: Message swiping + scrolling a little clumsy

### ISSUE THREAD

**Issue by courajs** [nylas/N1#2351]
Often when scrolling through the list, I will slide a single message over enough so the color pokes out. This makes me feel a little bit nervous that I'm going to accidentally delete/archive something at some point.
Less often, but the reverse also happens where I'll scroll a little bit while swiping a message.

I think other clients tend to lock scrolling/swiping in the vertical/horizontal direction once either has started. I assume they also did some experiments to tweak the angle at which scrolling registers at horizontal/vertical.

##### Are there any related issues?
Also mentioned in [this comment](https://github.com/nylas/N1/issues/1448#issuecomment-217481691)

##### What operating system are you using?
OSX 10.11.5 with a laptop trackpad

##### What version of N1 are you using?
Version 0.4.40-85cf726 (0.4.40-85cf726)

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I've used Polymail and Mailbox, on both OSX and mobile, and they felt better.
No accidental swiping of messages when scrolling, and no accidental scrolling while swiping messages.

**Comment by jackiehluo** [comment]
Merging into #1493!
