### ISSUE TITLE
Could not find https://billing-staging.nylas.com

### ISSUE THREAD

**Issue by dakra** [nylas/N1#2353]
##### Are there any related issues?

No

##### What operating system are you using?
arch linux

##### What version of N1 are you using?
git

--

After installing, I can't finish the setup because `billing-staging.nylas.com` is not available.

**Comment by jstejada** [comment]
hi @dakra , what version of N1 are you running?

**Comment by jstejada** [comment]
hi @dakra, unfortunately N1 off of `master` is not a stable version of N1. If you want to download the latest version off of https://invite.nylas.com/download/.

Hope this helps!

**Comment by dakra** [comment]
I know it's not the latest stable, but with the latest stable I'm effected by this bug: https://github.com/nylas/N1/issues/1929

btw, normally it's good practise to only commit working versions to master.

Thanks, let me know if I can help with debugging anything further.
