### ISSUE TITLE
Security feature: Ask before displaying external images

### ISSUE THREAD

**Issue by webbj74** [nylas/N1#236]
Personally I do not want to see images by default, unless I trust the sender and expected to get images from them. External images can be used for tracking/fingerprinting recipients. Some image formats like SVG have the potential for being employed in XSS attacks ([q.v. Heiderich's "The image that called me"](https://www.owasp.org/images/0/03/Mario_Heiderich_OWASP_Sweden_The_image_that_called_me.pdf))

#### Feature Request
- Preference should be added to "always display images" or "ask before displaying images"
- When "ask before displaying images" is the preference, the application should:
  - not render images
  - allow the user to click to see images in the active message at runtime
  - allow the user to click to always see images from the sender of the active message

#### Example preferences (gmail):
![screen shot 2015-10-27 at 8 08 59 pm](https://cloud.githubusercontent.com/assets/50980/10776308/abaf4fe2-7ce6-11e5-9dbc-5334f554baff.png)

#### Example presentation (gmail):
![screen shot 2015-10-27 at 8 10 30 pm](https://cloud.githubusercontent.com/assets/50980/10776333/db2690dc-7ce6-11e5-83c3-7d0a5637c43c.png)

**Comment by as-com** [comment]
+1

This should be enabled by default for the spam folder, anyway.

**Comment by jaredharley** [comment]
+1, this is how it looks/works in Thunderbird:

![screenshot of Thunderbird message with blocked images](https://cloud.githubusercontent.com/assets/1743226/10850467/750e461c-7eeb-11e5-8b80-4c2f94ed1b52.png)

[More information from Mozilla on remote content in messages](http://mzl.la/1ApHqTF).

**Comment by namxam** [comment]
+1 From my point of view a must-have feature.

**Comment by ianwalter** [comment]
+1
1. Love @as-com's idea of on by default in the spam folder.
2. A setting and button at the top of the message that allows you to load remote content is most likely all you need (i.e. OS X's Mail.app). Allowing the user to create rules that determine when to load remote content is probably not worth the complexity (at least in the core application).

**Comment by jsvini** [comment]
+1 indeed very useful

**Comment by bengotow** [comment]
Hey folks—thanks for filing this! This feature landed last week in `0.3.23`. In N1's preferences, you can disable "Automatically load images in viewed messages" and then whitelist senders you want to see images for. Enjoy!
