### ISSUE TITLE
Feature Request: Counting the number of times an email is opened by a recipient

### ISSUE THREAD

**Issue by jffrybrwn** [nylas/N1#2365]
It would be nice to see a count of the number of times an email was opened by the recipient or 3rd party, if possible. I haven't seen this in another client but it would be nice

And is there a way to track opens by IP address so that you can know how many different people/clients opened a message? These kinds of analytics would be crucial for insight during sales negotiation, for example.

I'm using Nylas N1 Version 0.4.40-85cf726 (0.4.40-85cf726) on Mac OS X 10.11.5 (15F34).

**Comment by jackiehluo** [comment]
@jffrybrwn Both of these features (message history/count and per-recipient tracking) are coming!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!

You can now click on the purple read receipts, and more details are available in the Activity view:

![image](https://cloud.githubusercontent.com/assets/1037212/16063261/14a27ed6-324d-11e6-96b1-d9fd4064edaa.png)

![image](https://cloud.githubusercontent.com/assets/1037212/16063267/1a90598a-324d-11e6-910a-d2a876bd734f.png)
