### ISSUE TITLE
Feature Request: Basic Editing

### ISSUE THREAD

**Issue by Eadword** [nylas/N1#2367]
I am basing this request off the gmail client: I think it is necessary to have at least a minor level of control over font (e.g. sans, serif, monospace), font size, font color, and background color; this is especially important because it is possible to paste and retain the formatting, but does not have an easy way to get back to the original, or modify what was pasted.

My argument is, if the core editor is going to support markup, it needs to have a way to edit what it supports to at least a basic level as part of the core features.

Also being able to insert inline images (as gmail allows for) is very convenient, though I acknowledge it may be going to far into html formatting.

![image](https://cloud.githubusercontent.com/assets/4187749/15754689/48b71f5e-28ae-11e6-909a-1dfd56d7cea3.png)

Thank you.

**Comment by bengotow** [comment]
Hey thanks! I definitely agree we need to add more editing controls. Going to merge this into #1343 and we'll go from there. Cheers!
