### ISSUE TITLE
Bug: Nothing to display, it doesn't sync with gmail

### ISSUE THREAD

**Issue by abhigenie92** [nylas/N1#2368]
I am Nylas N1 0.40-85cf726  Kubuntu 16.04 with kde plasma 5.4.3. The email I am using is gmail.

Screenshot
![image](https://cloud.githubusercontent.com/assets/12474640/15759611/0a0a3776-292d-11e6-9cfd-f24193b5b315.png)

It doesn't sync with gmail and shows no mail. I have enabled imap and pop in gmail as well. The authentication was successful at start also.

**Comment by bengotow** [comment]
Hi - thanks for posting this. If you choose the account from the little dropdown in the top left (to the right of "All Accounts"), does mail appear? Not sure we've seen this issue before.

**Comment by abhigenie92** [comment]
Yes, it does.
![image](https://cloud.githubusercontent.com/assets/12474640/15760271/038dfd94-2930-11e6-85fa-131270a4c008.png)

**Comment by abhigenie92** [comment]
Please let me know if you require any more debugging information. Thanks.

**Comment by abhigenie92** [comment]
This seems to solve it https://github.com/nylas/N1/issues/2062#issuecomment-222152960
