### ISSUE TITLE
Emails remain unarchived in Gmail inbox

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2369]
Dear all, 

I just saw that Nylas N1 and Gmail Inbox are out of sync. 

I archived all emails in my N1 inbox but all emails are still shown as unread in my Gmail Inbox. 

Is this a backend problem?

Warmly,

~Robert

**Comment by abass** [comment]
I thought I was going nuts when this started happening. Almost didn't believe it was actually happening. Now that you mention it though, it is absolutely happening.

**Comment by c0fe** [comment]
There appears to be a lot of sync problems that N1 team isn't interested in addressing apparently. This problem extends beyond just GMail but also IMAP and Yahoo accounts. The sync engine seems to be the culprit because it is just unnecessary when you are using GMail and IMAP email servers.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this folks—we've been triaging this this morning, and it looks like one of our sync instances ran out of file descriptors, which caused some actions to fail. We're working on a fix for the sync engine on https://github.com/nylas/sync-engine/tree/sync-syncback and it should be deployed this week. Stay tuned!

**Comment by abass** [comment]
Thanks for the response @bengotow! Was noticing that "starring" emails wasn't syncing either. Glad to hear your team is on it!

Keep up the awesome work!

**Comment by bartlomn** [comment]
+1 - Any updates on this issue?

Sync engine is not applying the following to my gmail inbox:
* read status
* star status
* labels

Whatever I do in the Nylas client is not carried over to google, effectively making all the messages left unread on other devices (mobile/tablet). This is kind of a showstopper.

Otherwise thumbs up for an awesome product.

**Comment by c0fe** [comment]
Bartlomn I recommend trying to run SyncEngine locally, even though doing so is a bit of a pain in the ass.

**Comment by boogah** [comment]
I've also been seeing this behavior for the past week or so. It's been jarring to open up the mail app on my phone and see a bunch of things I thought I'd triaged hours before back for me to deal with again.

Love the app, but I have to go back to the Gmail web interface until this gets sorted.

**Comment by jkudish** [comment]
> Love the app, but I have to go back to the Gmail web interface until this gets sorted.

Same here. Unfortunately a show stopper for now.

**Comment by jstejada** [comment]
same issue as #2059

**Comment by WizGnome** [comment]
Not syncing from Nylas back to Gmail for me either.

**Comment by jstejada** [comment]
Hi all, thanks for reporting this. This is a known issue, so I'm going to go ahead and merge it with #2059 so we can keep track of it in a single place
