### ISSUE TITLE
Cursor Changes position when altering search criteria 

### ISSUE THREAD

**Issue by slate1** [nylas/N1#237]
After entering someone's email in the search field you can only type one letter at a time to alter it. after each keystroke the cursor changes position to the end of the string.

**Comment by bengotow** [comment]
Hi @slate1 — thanks for reporting this. You're totally right—I was able to reproduce this, and it's fixed in dc538930a7cb64b04b2793f83b955b284ac55146. It'll be included in the next release (most likely tomorrow morning.) Cheers!
