### ISSUE TITLE
emails sended via thunderbird not show correctly

### ISSUE THREAD

**Issue by ewiggin** [nylas/N1#2370]
When I recieve email from thunderbird, i see this. But into email have a more text, i only can view it when reply.....

##### What operating system are you using?
SO: Ubuntu 16.04

##### What version of N1 are you using?
Latest: 0.4.40.x

--

**Bug?**
##### Do you have any third-party plugins installed?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://cloud.githubusercontent.com/assets/657517/15773328/9935748a-2976-11e6-9a00-c88b76d99e9c.png)

**Comment by c0fe** [comment]
Same here but this issue seems to be attached with a lot of other issues including syncing, general stability, sending emails, receiving emails. I think this specifically has to do with their "sync engine" which is something I am not sure why it exists when you are using IMAP email protocol.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. I think this is actually an issue with N1 rendering the iframe for that message too small. Going to merge this into #2334
