### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by jeffmcneill** [nylas/N1#2371]
Hello, I have a lot of website issues (issues with the website). Is there a different repository for the website? Where can I go to submit bug reports/feature requests for the website?

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—you can actually file them right here. We'll tag them for the website and get things knocked out. (The N1 website is actually the gh-pages branch of this repo: https://github.com/nylas/N1/tree/gh-pages)
