### ISSUE TITLE
Bug: Two Accounts or More

### ISSUE THREAD

**Issue by c0fe** [nylas/N1#2372]
I have noticed one thing N1 before uninstalling it is that having two or more accounts results in N1 becoming highly unstable. Both accounts were IMAP, let's call them Account A and Account B. They are both completely separate email accounts with separate domains, they are not tied to one another in anyway. Account A would show some emails but not all, Account B would show Account A's emails that are much older but not its own email. Your devs probably don't care about this bug what here it is.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—transferring this to the sync-engine project.
