### ISSUE TITLE
turn off grouping

### ISSUE THREAD

**Issue by tmdag** [nylas/N1#2373]
##### Are there any related issues?

...

##### What operating system are you using?
Centos7
##### What version of N1 are you using?
0.4.5-b0ec335
**Bug?**
##### Do you have any third-party plugins installed?
none
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
don't think so, i'm using Icloud
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I want to turn off mail grouping.
Currently new mails instead of being on top, appear somewhere on the bottom as a part of mail group.
In addition, grouped mails are being displayed from top at the moment. If you have LOTS of mails as part of a group, you have to scroll down to see new message. I would prefer to see new message straight away on very top.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - merging into #439  and #10
