### ISSUE TITLE
Search bar misalignment

### ISSUE THREAD

**Issue by mihokovic** [nylas/N1#2376]
Hello, while using Nylas I found a little graphical misalignment, still it's worth mentioning and fixing for having a pixel-perfect mail client.

Screenshot is at the link below:
http://i.imgur.com/iVQDob7.png

On the other side, I wanna take this opportunity to say that this email client is AWESOME. I've been using it for a while now, and it's definitely the simplest while most useful client out here. Not even comparable to other clients that I've been using for years, and trust me I tried them all.

##### Are there any related issues?
No

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
Latest, 0.4.40

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not relevant

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Not relevant

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—do you know if you have `interface zoom` set in N1? Could you open the console in the app (Developer -> Toggle Developer Tools) and run this command?

```
NylasEnv.config.get('core.workspace.interfaceZoom')
```

**Comment by mihokovic** [comment]
Hey Ben,

  

I checked interfaceZoom and it says "1".

I haven't messed with any settings, it's a clean install of both Nylas and
Windows. It's probably just a minor UI error.

Maybe it has something to do with screen resolution, but the misalignment
persists even if the window is resized so I don't think that's the issue.

  

I guess you only need to pull the margin -2px to the left and it should be
fine.

  
**\---**  
  
**Valentino Mihoković**  
Microsoft Certified Solutions Associate  
  
Phone: | [+385 97 675 0105](tel:+385976750105)  
---|---  
Skype: | [mihokovic.valentino](skype:mihokovic.valentino)  
  

On Jun 6 2016, at 7:32 pm, Ben Gotow &lt;notifications@github.com&gt; wrote:  

> Hey! Thanks for reporting this—do you know if you have `interface zoom` set
in N1? Could you open the console in the app (Developer -&gt; Toggle Developer
Tools) and run this command?

>  
>  
>     NylasEnv.config.get('core.workspace.interfaceZoom')

>  
>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2376#issuecomment-224029440), or
[mute the thread](https://github.com/notifications/unsubscribe
/APhyJpp9UPGt_8EFl-Po6btb0u9JMcnEks5qJFmYgaJpZM4IuTbx).![](https://github.com/
notifications/beacon/APhyJgq2HBRyiChrJxDKm22e9i8O8NQhks5qJFmYgaJpZM4IuTbx.gif)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
