### ISSUE TITLE
Add folder icon doesn't render proplerly

### ISSUE THREAD

**Issue by grinich** [nylas/N1#2378]
It's somehow missing the bottom line.

Running 0.4.40.

![image](https://cloud.githubusercontent.com/assets/92417/15809131/639dfd50-2b3e-11e6-9e2c-44c21791dd77.png)

**Comment by jackiehluo** [comment]
Fixed in https://github.com/nylas/N1/commit/311e21e615ebdb974f417759c35303c5c7be23fe!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
