### ISSUE TITLE
Message without date (Cannot read property 'format' of undefined) results in empty thread view

### ISSUE THREAD

**Issue by 7CTech** [nylas/N1#2380]
##### Are there any related issues?

...

##### What operating system are you using?
Arch Linux x86_64
...

##### What version of N1 are you using?
0.4.40
...

--

**Bug?**
##### Do you have any third-party plugins installed?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Exchange only
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

I just re-downloaded the N1 client after 2 months. I opened it, and it already had my old account in it. I let it finish syncing, and I tried to open a mail. All my emails are there, however when I click on a mail, it has 5 dots, and nothing displays. I proceeded to delete the .nylas folder, after closing N1. On my web client it opens perfectly. The first however many chars are displayed at the bottom of each message. I am capable of sending email, yet it still won't open. I also can't open sent mail.

Example:
![screenshot from 2016-06-06 18-39-47](https://cloud.githubusercontent.com/assets/16497786/15816423/12e4d7a2-2c16-11e6-9ec4-6d08f4a92a77.png)

There is definetly content in the mail, as it opens in the web browser. I can send emails, and they are received.

Details:
Provider: Exchange
Plugins: None
Console Output at Time: https://gist.github.com/7CTech/48a0ce237f798c6a9fb585670365dd82

OS: Arch Linux x86_64
N1 Version: 0.4.40

**Comment by c0fe** [comment]
Fix: Uninstall N1

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—it looks like this is a (very strange) issue we've seen a few times, where there's no date on the message object. I'll see if we can make N1 handle this more gracefully.

**Comment by bengotow** [comment]
This might be related to the timezone being undefined (https://github.com/nylas/N1/issues/1964). We should check and see, since it would explain how this could possibly happen.

**Comment by 7CTech** [comment]
I ran a spec suite, and the error of the title pops up a few times. If you could please tell me how to export it as a log, that would be great. Also I think the time zone is set.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. Do you know what timezone you're using? (For example America/Chicago). Any chance it's one of the "new" timezones that was added to the international timezone list in the last year? We were a bit behind on `moment-timezone`, and it looks like that was causing many newer timezones like "UTC +7 Barnaul, Gorno-Altaysk" to fail. (Fixed in 17d9c3d7175392538345e32e54ea871987f85c2d). Cheers—

**Comment by bengotow** [comment]
(We'll close this when the next release goes out, unless it turns out it's unrelated to #1964!)

**Comment by 7CTech** [comment]
Time zone is:

Australia/Sydney (AEST, +1000)

**Comment by bengotow** [comment]
Thanks—will see if that correlates to any of these issues.

**Comment by 7CTech** [comment]
Ok, it's a time issue. I tried changing my time zone to NYC, and after exiting and re-opening Nylas N1, it worked perfectly, and I don't get an error popup. Back to AEST, errors all round!

**Comment by 7CTech** [comment]
Ok, it's a time issue. I tried changing my time zone to NYC, and after exiting and re-opening Nylas N1, it worked perfectly, and I don't get an error popup. Back to AEST, errors all round!

**Comment by 7CTech** [comment]
Ok, it's a time issue. I tried changing my time zone to NYC, and after exiting and re-opening Nylas N1, it worked perfectly, and I don't get an error popup. Back to AEST, errors all round!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
