### ISSUE TITLE
Feature Request: Markdown editor

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2381]
Hi,

Just wanted to you look at `http://www.typora.io/` for inspiration for a possible markdown editor for n1.

It could allow you at Nylas to focus on developing the email client & sync functionality and give the user something that looks to be a very good markdown editor,

**Comment by bengotow** [comment]
Thanks! We're actively working on this but it looks like it's not in any open issues. Will leave this open until it ships :-)

**Comment by danielbayley** [comment]
[N1-Markdown-Composer](https://github.com/nylas/N1-Markdown-Composer/issues/13) is supposed to do this but stopped working a while ago 😞

**Comment by molstrangler** [comment]
Hi,

I've processed my N1 coupon for the next year and thank you for that.

I would expect when I pay for the next year to have a good markdown edit option in N1.  With N1 sending emails as HTML using webfonts and not using the default font of the client receiving the email.

As I have said before, when communicating with customers it's important the emails are displayed the way N1 users are creating emails.

I would strongly suggest you download the beta of typora and see how simple it is to edit and export to HTML pages.  I would be willing to pay for a typora plugin for N1.

TVM

**Comment by jstejada** [comment]
This has been released in v0.4.51. enjoy!

**Comment by grinich** [comment]
![beer-dance](https://cloud.githubusercontent.com/assets/92417/18283627/ff71f48c-741a-11e6-82b7-75c2925100ec.gif)
