### ISSUE TITLE
Unable to add image to email signature

### ISSUE THREAD

**Issue by fayimora** [nylas/N1#2382]
##### Are there any related issues?

None I could find

##### What operating system are you using?
Mac OSx 10.11.5

##### What version of N1 are you using?
Version 0.4.40-85cf726 (0.4.40-85cf726)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
This works fine in Mail.app. Most official signatures these days have the organisation's logo in it. This requires adding an image to the signature but unfortunately, the signature field does not allow me add one.

**Comment by bengotow** [comment]
Thanks for reporting this—closing as dup of #1025. We'll be fixing this soon!

**Comment by fayimora** [comment]
Oops I missed that. Thanks
