### ISSUE TITLE
No way to navigate to "next unread" message.

### ISSUE THREAD

**Issue by cdysthe** [nylas/N1#2386]
Hi,

I would call this a bug, but it may be a feature for some: In all other e-mail clients I've used there's a way to navigate to the **"next unread message"**. Not so in Nylas X1 for some reason unless I'm missing something obvious? It would also be great with the space bar functionality from other mail clients where it scrolls down the current message and then jumps to the next **unread** one.

**Comment by bengotow** [comment]
Closing as dup of #1287
