### ISSUE TITLE
Download link auto-starts download for OS reported by browser (bug)

### ISSUE THREAD

**Issue by jeffmcneill** [nylas/N1#2387]
There is no page that exists which someone can visit and see the different clients, that can then be downloaded. By auto-starting a download for the OS that the browser reports (e.g., OSX) there is no information or page that can be linked which someone can send to their friends with a Windows or Linux OS.

Behavior:
- Click on download link
    - Expected behavior: visit a page with links to downloads by different platforms, versions, and possibly changlog info/links and links to source
    - Actual behavior: a download of the latest version for the browser-reported OS begins

**Comment by grinich** [comment]
Bhanks for the feedback. Since this is not an issue related to N1, I am going to close this issue.

**Comment by bengotow** [comment]
Hey @jeffmcneill — if we expand the site in the future we may offer a "Downloads" page, but we've found it's very rare for people to want a copy of N1 that doesn't run on their machine. If you need these links in the interim, you can always download N1 directly from GitHub releases: https://github.com/nylas/N1/releases

**Comment by jeffmcneill** [comment]
Hi @bengotow that is frustrating to me because I know people on a different OS and want to send them a link for download (much less it took a while to even figure out that there is a version for windows). 

I think the average person who is browsing around might want to know that this is multiplatform, and also the expectation on download is to go to a download page then select the download one wants. Download menu links generally go to download pages, where there are links or buttons (and some more text) telling you what you are downloading (version, size, for which OS). 

Its just I am taken by surprise on that site, and I have no info about where to go to get that info (I have to squirrel around before I figure out it is over on github, source, versions). Really this is ok for developers, but is it even necessary to make people hunt around like that for valuable information which would take an hour to put on a page?

**Comment by jeffmcneill** [comment]
Hi @grinich I was told to file those issues here, and they would be tagged website see: #2371

If not here, then where?
