### ISSUE TITLE
Nylas website features page usability issues

### ISSUE THREAD

**Issue by jeffmcneill** [nylas/N1#2388]
There are several issues which make the features page less optimal than possible:

- Four buttons going to the same page (Download) but each with a different color. This is inconsistent and gives the impression that the download destinations are different (e.g., download each feature)
- Animations that don't stop (this is difficult for people to read)
- No links for more information about each feature, though with drawings that might be clickable to learn more 
- "Love your mailbox" is not a "feature"
- alternating left and right aligned images are harder to follow for reading
- Finally, the sparse design and visually distracting, and not very informative page on features militates against the actual product which is information-rich and highly functional
- No mention of what platforms can run this app

Recommendations for improvement

- Have a video demonstrating use with a voiceover. This is the most powerful way of showing how this works. Cover each of the features mentioned in the list, in their order of mention.
- Have the second video be the one from Brooklyn JS 
    - (label it "For developers" https://www.youtube.com/watch?v=TO9e8r6RQhE )
- For textual detail of the features:
    - Put the functions in more of a list form (can have a cute graphic to the left) but no animations
    - Start with the platform support: OSX, Windows, Linux (which flavors)
    - Provide more detail about each functionality. Not one sentence but two or three (as needed)

**Comment by grinich** [comment]
Bhanks for the feedback. Since this is not an issue related to N1, I am going to close this issue.

**Comment by jeffmcneill** [comment]
Hi @grinich I was told to file those issues here, and they would be tagged *website* see: #2371 

If not here, then where?
