### ISSUE TITLE
Nylas Website Top Menu usability

### ISSUE THREAD

**Issue by jeffmcneill** [nylas/N1#2389]
This issue is more prescriptive than descriptive. I am suggesting a variety of changes to the menu system, which would better organize and make visible the pages (and what information is on them)

- The top menu should have a link to Download (and as per Issue #2387 make the target a page listing downloads rather than autodownload).
- The submenu should be removed, and everything made top level, with the exception of:

- Open Source and Cloud APIs should go on the Developer page
- Team and About Nylas should be merged into one or the other
- Home, Features, and Security should merge into Home
- Add a contact page that lists support contact, jobs contact, address, etc.

That gives you the following menu items:

Home (incl. Features and Security)
Pricing
Download
Developers (incl. Open Source and Cloud APIs)
Support
Jobs
About (incl. Team, or vice versa)
Contact

**Comment by grinich** [comment]
Bhanks for the feedback. Since this is not an issue related to N1, I am going to close this issue.

**Comment by jeffmcneill** [comment]
Hi @grinich I was told to file those issues here, and they would be tagged *website* see: #2371 

If not here, then where?

**Comment by grinich** [comment]
The docs Ben was referring to are the technical references for building plugins on N1. (e.g. http://nylas.github.io/N1/docs/)

General website feedback can be sent to support@nylas.com. Thanks!

**Comment by jeffmcneill** [comment]
Sent
