### ISSUE TITLE
Supporting 'Customize Toolbar' on OS X

### ISSUE THREAD

**Issue by sifex** [nylas/N1#239]
Normally on OS X native apps, you're able to customise toolbars (grey window border with the traffic lights on it) with different buttons. This is not possible on N1 on OS X at the moment.

**Comment by bengotow** [comment]
Hi @sifex — thanks for filing this. Unfortunately, N1's toolbar is written entirely in HTML and CSS. It looks like the standard Mac OS X toolbar, but doesn't leverage any of Mac OS X's built-in toolbar code, so we'd have to re-implement the "customize toolbar" feature from scratch. I think it's sufficiently far down on the priority list to close as a wontfix.

It's worth mentioning that our toolbars are built using CSS flexbox, and the order of items is determined using the `order` CSS property. You can learn more about how they're designed here: https://nylas.com/N1/docs/InterfaceConcepts.html.  If you want, you can override the `order` to move items around.
