### ISSUE TITLE
bad UX when the user swipe the message to trigger an action.

### ISSUE THREAD

**Issue by hadock** [nylas/N1#2391]
When a user wants to swipe a message to snooze or archive it, in some cases it takes a long time to dissapear.
A posible reason of this issue might be some procedures (api calls and local queries) before the animation. So in my opinion you should do it as twitter or facebook does.
1.- User triggers an action (post a message, delete, move, etc)
2.- Animation (fly, dissapear, etc)
3.- Leave a thread doing this job in the baground (this should be invisible for the final user)
4.- If something fails, notify to the user and let him select an action (retry, cancel or ignore)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. This is actually the way N1 works already (open Window > Activity to see it in action). Unfortunately, it sounds like something is causing access to N1's sqlite database to be sluggish. Going to merge into #1786, which is the same issue.
