### ISSUE TITLE
Template editor doesn't support template names with unicode characters

### ISSUE THREAD

**Issue by khamidou** [nylas/N1#2392]
![image](https://cloud.githubusercontent.com/assets/44081/15866955/d878fb22-2c95-11e6-8b14-c4c52d823cfe.png)

I'm using MacOS Yosemite with the french locale.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
