### ISSUE TITLE
Offline archiving & sending emails?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2393]
Dear all,

I cannot archive emails while working offline. Emails remain in the inbox although the following notification is shown:

![image](https://cloud.githubusercontent.com/assets/170947/15868546/9a28c656-2ce8-11e6-89e2-4c7d1b51572f.png)

Moreover, I can’t seem to send emails while being offline.

Is this type of offline work generally supported?

Thankfully,

~Robert

**Comment by bengotow** [comment]
Hey Robert—this type of offline work should definitely work. Can you open the Activity Window (Window => Activity in N1 v0.4.40) and see if you see any errors in the leftmost "Task Queue" tab? It should say "pending" beside all the actions.

**Comment by orschiro** [comment]
Hey Ben, 

Thanks! Where can I find the activity window?

In the below tab menus there is no such entry.

![image](https://cloud.githubusercontent.com/assets/170947/15883812/133c063a-2d4c-11e6-95f4-0130b4a51e3c.png)

**Comment by bengotow** [comment]
Hey! You may need to download N1 0.4.45 to see it on Linux. After that, it should appear under Developer.

**Comment by orschiro** [comment]
![image](https://cloud.githubusercontent.com/assets/170947/16976233/c01d727c-4e4d-11e6-8c9e-15cd54b0ffd4.png)

![image](https://cloud.githubusercontent.com/assets/170947/16976241/cbf9ba88-4e4d-11e6-907d-27b92dc31205.png)
