### ISSUE TITLE
Select-all appears to not properly work when a message is already selected

### ISSUE THREAD

**Issue by BenMagyar** [nylas/N1#2395]
**View**: Two-Panel
**Theme**: Taiga
**N1 Version**: Version 0.4.40-85cf726 (0.4.40-85cf726)
**OS**: OS X Yosemite 10.10.5
**3rd-Party Plugins**: None

When no message is selected and I am on the inbox panel, select all appropiately selects all messages. I am able to archive all messages with one archive action.

When a message is selected and I am on the inbox panel, select all *somewhat* selects all messages. The cards showing how many messages were selected appears but is off to the bottom of the message panel. When I attempt to archive all messages it only archives the currently selected message.

**Comment by emorikawa** [comment]
@BenMagyar It looks like this is still an issue. Thank you for the extra debug info.I'm closing and merging into: https://github.com/nylas/N1/issues/2395

**Comment by BenMagyar** [comment]
@emorikawa Merged with itself? 😜
