### ISSUE TITLE
Error when using calendar feature (iCloud)

### ISSUE THREAD

**Issue by fcpwiz** [nylas/N1#2396]
##### Are there any related issues?

No

##### What operating system are you using?
Mac OS X (10.11.6)

##### What version of N1 are you using?
0.4.40-85cf726 

--

**Bug?**
##### Do you have any third-party plugins installed?
Yes: Unsubscriber

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
iCloud

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I get the error: "This account has no editable calendars. We can't create an event for you. Please make sure you have an editable calendar with your account provider." Is this just an iCloud thing?

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
@fcpwiz Yep, unfortunately we don't support iCloud calendars right now!

**Comment by fcpwiz** [comment]
@jackiehluo ahh thanks!
