### ISSUE TITLE
Stuck in onboarding using hosted sync engine

### ISSUE THREAD

**Issue by chrisjbrown** [nylas/N1#2397]
##### What operating system are you using?
OSX

##### What version of N1 are you using?
Master branch

When running 
`./N1.sh --dev --enable-logging`

I can click through onboarding but get stuck on this screen and cannot proceed.

![screen shot 2016-06-08 at 09 37 29](https://cloud.githubusercontent.com/assets/1250638/15886318/b1bfde34-2d5c-11e6-8ebd-fb7346ea760a.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we just landed some new code for onboarding and it looks like it's not compatible with the self-hosted sync engine. We'll be addressing this very soon!

**Comment by arthurlutz** [comment]
affected by this too

**Comment by chrisjbrown** [comment]
Strangely this is no longer an issue for me. I'm able to get passed the onboarding now

**Comment by jackiehluo** [comment]
@chrisjbrown That website (billing.nylas.com) wasn't live yet when you tried earlier! Closing this issue for now.
