### ISSUE TITLE
Feature Request: Swipe to delete

### ISSUE THREAD

**Issue by c-fitzmaurice** [nylas/N1#2399]
It would be great to customize the swipe feature on the inbox. Currently left being archive and right being snooze, adding the option to delete would be amazing.

**Comment by jackiehluo** [comment]
@c-fitzmaurice You can change the swipe functionality (bound to the delete key's functionality) in the preferences!

**Comment by c-fitzmaurice** [comment]
@jackiehluo Ahh, I was moving too quickly! Looked right over it.. Thanks!
