### ISSUE TITLE
Update plugin feature?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2400]
Dear all, 

I've searched existing issues but couldn't find anything related:

Would it be possible to add a button `Update` to custom plugins that on click opens the file dialog window and asks me to select the extracted folder of the plugin?

![image](https://cloud.githubusercontent.com/assets/170947/15902257/55310738-2da7-11e6-9084-78c9ca814e4d.png)

Thankfully,

~Robert

**Comment by jackiehluo** [comment]
@orschiro We do intend to implement that—hopefully soon! Merging this issue into #2144.

**Comment by orschiro** [comment]
That's great to hear!

Thank you for leaving me with the correct reference, Jackie!

Warmly,

~Robert
