### ISSUE TITLE
Windows desktop notifications not working

### ISSUE THREAD

**Issue by MouseEatsCat** [nylas/N1#2403]
##### Are there any related issues?
I searched for issues related to notifications and popups but could not find anything.

##### What operating system are you using?
Windows 7

##### What version of N1 are you using?
0.4.40

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Whenever I receive new mail, I don't get any popup notifications other than the small blue dot on the system tray icon. I would assume this isn't normal?

Thanks for your help,

Michel Descoteaux

**Comment by Lex4hex** [comment]
Not Win, but anyway... Ubuntu Gnome 16.04 (GNOME 3.20) notifications don't work.

**Comment by jackiehluo** [comment]
I think @GM-Polyakov has experienced this bug as well.

**Comment by GM-Polyakov** [comment]
@jackiehluo Confirmed -- Desktop notifications have not been working on my windows laptops. 

The icon tray will show a red dot when there is unseen mail, but no desktop notifications appear for new messages or open/link notifications.

Using Windows 10 on a Lenovo W550s and a Lenovo T450.

**Comment by bengotow** [comment]
Hi @MouseEatsCat — unfortunately, N1 only supports desktop notifications on Windows 10. Previous versions of Windows don't expose a consistent API for desktop notifications (Each app pretty much creates it's own), and we rely on desktop notification support in Electron.
