### ISSUE TITLE
Does the phishing plugin learn over time?

### ISSUE THREAD

**Issue by cdysthe** [nylas/N1#2404]
Hi,

Far too many mail including all from our internal corporate mailing lists are marked as suspicious in Nylas N1. Is there no way to teach the plug-in so that it learns legit mail over time? If not it's pretty useless since it's far too eager and tags nearly all mailing lists as suspicious. I hope I am missing something obvious! :)

**Comment by jackiehluo** [comment]
@cdysthe Nope! We're planning to make it more useful—merging into #1321.
