### ISSUE TITLE
Attachment?

### ISSUE THREAD

**Issue by oojacoboo** [nylas/N1#2406]
I believe this may be more of a UI issue, but I'm not entirely sure.  Basically, I have an email thread where, in the list view, it shows that there is an attachment, but I'm not able to easily see where that attachment is located.

The latest reply in the thread suggests that there is an attachment, but I don't see one, then the first email also has an attachment that I can see.  Because of this, I have no idea if the last reply is supposed to have one, but doesn't because of Nylas, or because it wasn't attached, etc.

Please consider adding an attachments "tab" to the right column as a way of toggling the profile details and attachments associated with a thread.  Thanks.

**Comment by jackiehluo** [comment]
If I'm understanding your question correctly, you'll see the attachment icon in the thread list whenever there's an attachment somewhere in the thread, and then you'll see it in the message list for each individual message with an attachment. If the most recent message has an attachment, you'll see it at the bottom, with some download buttons. That behavior is identical to Gmail's!

As for your request, merging into #1635.

**Comment by oojacoboo** [comment]
Hey Jackie, that does appear to be the case.  I don't use Gmail, never have.

I'd still like to see a tab on the right column with a list of all the attachments for the thread.  I think that'd be a very nice improvement.
