### ISSUE TITLE
paste kills unfinished addresses in composer

### ISSUE THREAD

**Issue by grinich** [nylas/N1#2410]
### try this:

1. copy: **google.com**
2. go to the composer and type **joe@**
3. use CMD+V to paste

what do you get?
![image](https://cloud.githubusercontent.com/assets/92417/15953992/73e98328-2e86-11e6-857a-3b8ae9227e37.png) ![image](https://cloud.githubusercontent.com/assets/92417/15953993/770f0636-2e86-11e6-9fba-bb7113bbcbbf.png)

---

### This _should_ just append it so it looks like this: 

![image](https://cloud.githubusercontent.com/assets/92417/15953999/8772d688-2e86-11e6-8f61-7e40e6c2d277.png)

and then enter or tab tokenizes it properly 

![image](https://cloud.githubusercontent.com/assets/92417/15954011/b497c2c2-2e86-11e6-9d7d-b187bfd9a297.png)

**Comment by jathpala** [comment]
I think i have come up with a fix for this (see pull request #2635).

This solves the problem more-or-less as suggested above. Pasted text is just appended to already existing text. If after pasting, the input field now looks like an email address, it will automatically be converted to a button like the last picture above (no need to press space, tab or enter). If after pasting, the input field does not look like a full address then it will remain as just text waiting for further input.

I believe this is the behaviour that most people would want and expect. There is the issue that if you wanted to send an email to 'test@email.com.au' but for some reason only copied 'email.com' to the clipboard before typing 'test@' then hitting paste, you would have to do a couple of extra steps to add the '.au' bit but that seems an unlikely scenario. It is easy enough to modify to suit this use case but I think immediate tokenization is better the majority of the time.

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
