### ISSUE TITLE
Slow and unresponsive

### ISSUE THREAD

**Issue by clifgriffin** [nylas/N1#2412]
Hey guys,

Love N1, but having a few issues now that I've been using it for a couple of months. 

I sync two Gmail accounts, and more and more frequently I'm seeing basic functionality degrade:
1. Archiving / snoozing email often takes 30 seconds to apply the labels. The email often isn't removed from the list for 30-60 seconds after the "Applying labels" notice vanishes. 
2. The Reply button will become unresponsive. After a very long time, a reply is created for every time I clicked the reply button in frustration. 
3. New emails often take a long time to show up. 

I've found myself having to reload frequently and fall back to gmail.com. 

Any ideas?? 

##### Are there any related issues?
None that I can find. 

##### What operating system are you using?
OS X 10.11.5

##### What version of N1 are you using?
0.4.40-85cf726 (0.4.40-85cf726)

**Bug?**
##### Do you have any third-party plugins installed?
Jiffy
Emoji Keyboard
Quick Replies
Send Later

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I only have my experience :)

**Comment by khamidou** [comment]
Hi @clifgriffin 

Thanks for taking the time to fill out this issue! We're working on sync-engine fixes for this --- it should get much better in the next few days!

Cheers,
k
