### ISSUE TITLE
Feature Request: Font Face

### ISSUE THREAD

**Issue by mihokovic** [nylas/N1#2413]
I'm using N1 for a while already, and it's definitely the best e-mail client out there.
However I would REALLY like to see an option to set Body Font (in settings - not per e-mail) for all e-mails including signatures.
Because when I'm previewing my e-mails in browser, they all appear in Times New Roman font, and also when I'm previewing my e-mails in Thunderbird (at work) they appear in Times New Roman as well.
That probably happens because there is no body font set, so they appear in system serif font which is usually Times New Roman.

This means that other people also mostly see my e-mails in a different font which is awful.
If there is a console hack or config.json option for this, let me know please.

##### Are there any related issues?

No.

##### What operating system are you using?

Windows 10

##### What version of N1 are you using?

Latest 0.4.40

##### Does this feature exist in another mail client or tool you use?

Yes, in most mail clients.

**Comment by jackiehluo** [comment]
@mihokovic Unfortunately, there's not currently a plugin for that, but it's on the roadmap—merging into #1033 and #1087.
