### ISSUE TITLE
Nylon Cloud server-less version?

### ISSUE THREAD

**Issue by danielbayley** [nylas/N1#2414]
What if there was a somewhat "lite" version of N1 that doesn't use Nylas Cloud, where features like _send later_ could work by simply storing pending emails in a folder and using _[launchd]_ (for example, on OS X) to actually send them at the scheduled time? Other such features could work in a similar way.

[launchd]:	http://launchd.info

**Comment by jackiehluo** [comment]
@danielbayley Hm... it's not feasible at this point to create a fully client-side version of N1, but you can run your own server (on your computer, even) with [these instructions](https://github.com/nylas/N1/blob/master/CONFIGURATION.md)!
