### ISSUE TITLE
Feature Request: Select which calendars to show in scheduler

### ISSUE THREAD

**Issue by abass** [nylas/N1#2415]
Is there a way to remove some calendars from the "propose times" screen? It shows all the calendars I have shared with me when most are not even relevant. Would be fairly basic functionality to just be able to hide them.

Also, I think I was messing around with Nylas Scheduler at one point in time creating "test meetings" and I completely cancelled them, but they seem to still be showing in the calendar area here:

![IMG](https://s3.amazonaws.com/f.cl.ly/items/0K2u2F0i2W2I0C033s3Q/Image%202016-06-10%20at%202.41.30%20PM.png?v=a05cdce3)

Not sure what is up with that though because those "Test Meetings" aren't showing up on any of my Google Calendars anywhere.

Thanks!

**Comment by jackiehluo** [comment]
Merging the incorrect part into #1217 and changing the scope of this issue!

**Comment by emadow** [comment]
+1

**Comment by jackiehluo** [comment]
Another request: https://twitter.com/samcharrington/status/761525735261626368

**Comment by emorikawa** [comment]
Another request: https://nylas.zendesk.com/agent/#/tickets/5526

**Comment by sbc** [comment]
+1

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/5585

**Comment by cwRichardKim** [comment]
+1
![image](https://cloud.githubusercontent.com/assets/5778691/18461481/00a44986-7948-11e6-9610-cc67666d9950.png)

**Comment by royle78** [comment]
+1

**Comment by jstejada** [comment]
This has been released today!
