### ISSUE TITLE
Avatar? Where Is It?

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2416]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? Yes
...

**Comment by oldhickory30** [comment]
With all the plugins, why am I not able to see a theme that allows for avatars? It should be at the very least an option!

**Comment by jackiehluo** [comment]
Merging into #660!
