### ISSUE TITLE
Email Not Displaying

### ISSUE THREAD

**Issue by krishnaguragain** [nylas/N1#2419]
Os: Ubuntu 16.04 LTS
Nylas version:- 0.4.40

![nylas](https://cloud.githubusercontent.com/assets/6104245/15989010/4440c62e-3087-11e6-9394-35441cf64247.png)

**Comment by jstejada** [comment]
Hi!, thanks for reporting this! Merging into duplicate issue #2334

**Comment by jstejada** [comment]
Hi!, thanks for reporting this! Merging into duplicate issue #1280
