### ISSUE TITLE
Icon path is not correct in .desktop file, icon is also not installed

### ISSUE THREAD

**Issue by Zeklandia** [nylas/N1#242]
After installing Nylas from an RPM, the .desktop file lists the icon as being `/usr/local/share/Nylas/resources/app/resources/nylas.png`. `Nylas/resources/app/resources` does not exist, nor is `nylas.png` actually installed.

**Comment by bengotow** [comment]
Hey! Thanks for downloading N1—I don't /think/ we publish an RPM release, so it's possible this was mispackaged. Can you link me to the binary you installed? I'll also check our build scripts and see if something is up—I believe the .deb install is working.

**Comment by Zeklandia** [comment]
You're right, I should have mentioned that originally. This was from my build (out of my fork: https://github.com/Zeklandia/N1) which you can grab here: https://www.dropbox.com/s/xla8egiiv8p368w/nylas-0.3.20-0.1.fc23.x86_64.rpm?dl=0

I might work on it a bit this weekend and then I will try to 1) replace all the mentions of `/usr/local/share/Nylas` with a lowercase version and then 2) get the rpm building as functional as I can.

**Comment by Zeklandia** [comment]
Closing, as this is a sub-issue of not having a functioning rpm build
