### ISSUE TITLE
Request: Option to Disable Conversation View

### ISSUE THREAD

**Issue by Ikaruseijin** [nylas/N1#2421]
I am using:
Nylas N1 v 0.4.40-85cf726 (0.4.40-85cf726)
Mac OS X v 10.10.5 (14F1808)

I am trying Nylas N1 for the first time.

I don't want my emails grouped by "conversation" for numerous reasons I won't go into.

My current default email application- Apple Mail, allows users to turn "conversation view" off.

If there is a method of turning off conversation view in N1, I haven't found it. If it turns out there is one, I apologize.

It is a deal breaker issue for me, if the option to turn it off isn't available to me, I will not use N1 as an email application.

Thank you for your time.

**Comment by jackiehluo** [comment]
Unfortunately, it's not possible in N1. You can see the reasoning in #439!
