### ISSUE TITLE
Nylas IMAP sync stuck causing E-Mail server blocking

### ISSUE THREAD

**Issue by rsaeks** [nylas/N1#2422]
##### Are there any related issues?
None Found
...

##### What operating system are you using?
Mac OS X
...

##### What version of N1 are you using?
0.4.40
...

**Bug?**
##### Do you have any third-party plugins installed?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Zimbra IMAP 8.0.9
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No
...
Issue:

We are finding Nylas is stuck constantly syncing a mailbox and blocking other IMAP / IMAPSSL connections from occuring. In a normal day, the mailbox.log on the server for client connections is about 40MB - now it swells to over 250MB with constant hits from "Nylas N1 Sync" e-mail client at IP address: 52.35.88.132. Once blocking the connection on the firewall the log file, IMAP connections and email lag in display goes away.

**Comment by enoversum** [comment]
Possibly the same issue? https://github.com/nylas/N1/issues/2423

**Comment by jackiehluo** [comment]
Closing this issue for now—if it's still an issue, send us an email at support@nylas.com.
