### ISSUE TITLE
Removing/reading message in Nylas doesn’t change status on server

### ISSUE THREAD

**Issue by FlorianBrinkmann** [nylas/N1#2423]
Hi!

I have the following issue. If I delete a message in Nylas, it is moved to trash—everything fine (if I read it, it’s market as unread in Nylas). But on my mail server the message stays unread in the inbox. So it seems that Nylas doesn’t sync back to the server, if I read a message or move it to another folder (for example to trash by deleting).
It wouldn’t be so bad but because of the issue I always get the notificateion for new messages on my Android smartphone even if I already have read and/or deleted them… If I delete/read a message in the Gmail App on Android, it syncs fine with the server and I think it has worked with Nylas in the past (but am not 100 percent sure).

##### Are there any related issues?
Don’t think so…

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.40

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have custom IMAP-Accounts

##### Is the issue reproducible with a particular attachment, message, signature, etc?
no

**Comment by tridnguyen** [comment]
I can confirm this also happens with the OS X version as well. Version 0.4.40-85cf726 (0.4.40-85cf726).

I'm pretty certain it was syncing fine before.

**Comment by enoversum** [comment]
This has happened some time ago, and happens again from time to time, sticking for some days. My phone constantly reports new e-mails that have been read hours ago, plus shows e-mails in my inbox that had been archived at least days ago. Together with the unread bug (e-mails get marked as unread when moving to other folders/archiving) it feels that Nylas is still more a beta than a completely pro(ductive) app/engine :wink: .

**Comment by luctus** [comment]
+1 it's really annoying to have all those emails marked as unread in the server (gmail for work). The big problem for me is that I'm in love with the app, so I can't leave it.

**Comment by abojchevski** [comment]
I have the same problem.

**Comment by jstejada** [comment]
Hi all, thanks for reporting this. Indeed this is a known issue and we are tracking it in #2059. I'm going to go ahead and merge it into that issue so we can keep track of it in a single place
