### ISSUE TITLE
HTTPS requests being routed through nylas.org?

### ISSUE THREAD

**Issue by kminehart** [nylas/N1#2427]
So I want to use N1 at work, but we block the server that nylas.com is hosted on for some reason.  (It says domain parking).  I can't use any of my accounts because N1 sends https requests to this domain, so I don't receive any mail while I'm at work.  Why does it do this?  Is there any way I can disable this?

**Comment by Omeryl** [comment]
Heh,

All mail is synced through Nylas.com infrastructure, and your mail client hits the Nylas Cloud APIs to sync to itself. It requires the sync engine to functions.

**Comment by Omeryl** [comment]
For more information, read https://support.nylas.com/hc/en-us/articles/206506058-Why-does-Nylas-store-mail-data-

**Comment by Omeryl** [comment]
Oops, so sorry. This is the correct link hah. https://support.nylas.com/hc/en-us/articles/217518207-Why-does-Nylas-N1-sync-email-via-the-cloud-

**Comment by bengotow** [comment]
Hmm can you clarify what domain you're seeing? N1 connects to `api.nylas.com` over HTTPS, but shouldn't connect to nylas.org (or anything else, like .biz or .net, etc.) N1 is a cloud mail client which syncs your mail through hosted infrastructure to do all sorts of cool stuff, like snooze and send later. Cheers!

**Comment by kminehart** [comment]
You're right, I was really tired when I wrote this and put .org instead of .com.

Okay, I was not aware that this was how it functioned!  I'll probably just have to try to get my network administrator to unblock your domain.

Thank you
