### ISSUE TITLE
Reset size of letters list panel

### ISSUE THREAD

**Issue by Chuckland** [nylas/N1#243]
How to replicate:
1. Open any list, e.g. Inbox
2. Change letters list width
3. Go to Drafts
4. Return to Inbox
5. List width is reset

Screencast: http://quick.as/d8doI3kd7

N1 Version 0.3.19-de7d1bb (0.3.19-de7d1bb)

**Comment by bengotow** [comment]
Merging as a duplicate of 97

**Comment by jstejada** [comment]
merging into #833
