### ISSUE TITLE
Add Protonmail Support

### ISSUE THREAD

**Issue by gerardon** [nylas/N1#2433]
With the recent development of PGP encryption in n1 there should be enough tools to make a protonmail integration work.

https://protonmail.com/

**Comment by jackiehluo** [comment]
@gerardon What do you mean by an integration? Looks like it says that the accounts should be compatible!

**Comment by mookerific** [comment]
Protonmail is in the middle of overhauling their PGP infrastructure, so I think it would be best to wait. Protonmail currently doesn't allow for user access to the PGP keys - either public or private - and aim to build that in soon.

**Comment by jackiehluo** [comment]
Closing this issue for now, since it's not clear what "support" entails!
