### ISSUE TITLE
Nylas ID - Invalid Verification Code

### ISSUE THREAD

**Issue by sanjeevverma1** [nylas/N1#2434]
Created a Nylas ID on the newest version of N1. Received email with email verification link. Clicked link and got an error message that said "Invalid Verification Code". Logged into my Nylas ID and resent verification link. Same issue...keeps saying "Invalid Verification Code" after clicking to verify email.

**Comment by jackiehluo** [comment]
@sanjeevverma1 Sorry to hear that! Want to send support@nylas.com an email with the email address you're trying to use? We're wondering if it's a problem with specific email addresses.

**Comment by jackiehluo** [comment]
Should be fixed!

**Comment by ErSachinVashist** [comment]
facing the same issue... can you help @jackiehluo . thanqu
