### ISSUE TITLE
Where do I enter the coupon code

### ISSUE THREAD

**Issue by abhigenie92** [nylas/N1#2436]
Hi,
I have coupon code for a free year of Nylas Pro. 
After opening Nylas, clicking on Preferences->Suscriptions->Upgrade to Nylas Pro. It opens a webpage and asks to select a plan along credit card details. There is no option to enter the coupon code.

**Comment by jackiehluo** [comment]
@abhigenie92 Hey! Sorry about the confusion. Did you receive a second email with the correct link?

**Comment by tomkeysers** [comment]
@jackiehluo I too received a coupon code, also the second one with the correct link. But following this link leads me to a form where I still have to provide credit card details. 
Is there a way to pass this credit card section? So I can just do that after my first year?

**Comment by ginfuru** [comment]
I still haven't received my coupon yet.

**Comment by joaop** [comment]
I do have a cupon, but I don't use credit cards. How can I keep using nylas for 1 year ?

**Comment by bengotow** [comment]
Hi there! Thanks for reporting this.

- If you haven't received a coupon code but were using N1 before Jun 14th, 2016, please fill out this form:  https://docs.google.com/forms/d/1nl3qhpxIOpRNCk11GohmwkyG7NCQaFW7Ygu_Q2gQYzs.

- If you have a coupon, but don't have a credit or debit card, hang tight! We're investigating ways we can support more methods of payment in the near future. You'll be able to use N1 for free until July 14th, 2016.

**Comment by zlatkobijelic** [comment]
@bengotow Bitcoin through stripe might be a good solution, they also have ACH transfer options now.

**Comment by Zn4rK** [comment]
@bengotow So, we're slowly creeping up on July 14th. How do we use the coupon without a CC?

**Comment by sebastienb** [comment]
My account go paused today July 12th :-(

**Comment by joaop** [comment]
Love this project. But I don't have a credit card.

**Comment by rtx111** [comment]
My NYLAS account was suspended today.... I have been using nylas for 10 months and was never told i would have to pay to use it. I never received a coupon code either. I followed the link posted above but it says it was only valid until the 13th.....today is the 13th and it wont let me use it saying it had expired..... and now i cant use my email. Super frustrated! I dont have a CC# and can only use paypal but I MUST access my email asap.... help! PLEASE send code for free year and another payment option for when the free year ends!!!!! Thanks

**Comment by joaop** [comment]
Ok, nobody cares about our feedback, ideas of improvements and the user on the other side. going back to thunderbird.

**Comment by pierrecarl** [comment]
I've had the same issues, have written in, no response yet!

**Comment by ArNz8o8** [comment]
Same here.. Never did receive a coupon, been using Nylas long before june.. Nor do I have a credit card. 

Program is useless now..

**Comment by araspitzu** [comment]
Still we can't use N1 without a CC?
