### ISSUE TITLE
Nothing is syncing [Manjaro Deepin]

### ISSUE THREAD

**Issue by ositanachi** [nylas/N1#2438]
Using Manjaro Deepin 64 bit. 

Don't know what happened but nothing appears to be syncing (and I cannot send emails). Others on AUR have made similar comments: https://aur.archlinux.org/packages/n1/

**Comment by jeffmcneill** [comment]
Same here on OSX (but I can send, but it doesn't actually send in the Google Apps mailbox part). Sync appears to be broken for me. See also #2457

**Comment by ositanachi** [comment]
Anyone else experiencing the same thing?

**Comment by jeffmcneill** [comment]
Apparently it was a huge backlog in the queue that caused this, and everything is (mostly) back to normal.

**Comment by ositanachi** [comment]
Thanks it seems to be working now. Don't know if I had to reinstall it but after re-authenticating my Gmail account, everything started working again.
