### ISSUE TITLE
Nylas ID - Cannot create a Nylas ID

### ISSUE THREAD

**Issue by MrHuxu** [nylas/N1#2439]
After the latest update, it requires a Nylas ID when I open the app, but as the screenshot I attached, even I fill in all the blanks, the button 'Register' is still unclickable. could you please help solve the problem?

OS: OS X 10.11.5
Nylas N1 Version: Version 0.4.45-7637265 (0.4.45-7637265)

![image](https://cloud.githubusercontent.com/assets/2713125/16067407/d096aa58-32ee-11e6-8cd0-599b48cb38ed.png)

**Comment by grinich** [comment]
Hm, that's weird. Can you try again? Is it still happening?

**Comment by MrHuxu** [comment]
Yes, I've tried so many times and it is still happening, is there any validation that blocks the submission event?

**Comment by jackiehluo** [comment]
@MrHuxu Nope, there shouldn't be... Want to try creating it on https://billing.nylas.com/register? Trying to reproduce the issue there, and it's working fine for me.

**Comment by MrHuxu** [comment]
@jackiehluo Thanks for your help and I think I found the root cause through the console of that page.

![image](https://cloud.githubusercontent.com/assets/2713125/16070615/520ef26a-3309-11e6-820d-7f3cc0198dbd.png)

It seems that my terrible network made the error happen :joy:

BTW, loading the assets from third-part cdn on a web page is correct, but from a electron developer's standpoint, app has no console and debug env after all, so I think it is better to package jQuery into Nylas N1 client inside.

**Comment by bengotow** [comment]
Wow - an SSL protocol error? That's pretty strange. Do you have any sort of network monitoring / ad blocker tools that might be doing a man-in-the-middle attack on your network connection?

I'll see if we can make the page fall back to not running validation in a more graceful way. Thanks!

**Comment by MrHuxu** [comment]
@bengotow 

Sorry I don't have any monitoring about my network...

It's said my local network has updated recently and it's conflict with some experimental private policies of Google and after that I failed to reach Google services on Chrome through the vpn of my company, but the page works well on the other browsers like Safari/Firefox, so maybe it's not a bug of yours.

That's all the info I can provide above, thanks again for your work!
