### ISSUE TITLE
Login window is shifted

### ISSUE THREAD

**Issue by laughedelic** [nylas/N1#2445]
After the last update when I open N1 and go through the features intro, I get this:

![screen shot 2016-06-15 at 12 38 13](https://cloud.githubusercontent.com/assets/766656/16077130/3937d94e-32f7-11e6-9ffb-439522397126.png)

I cannot resize it or scroll.

##### What operating system are you using?

OS X 10.11.5

##### What version of N1 are you using?

0.4.45-7637265

**Comment by bengotow** [comment]
Whoa! That's super interesting. Are you running any window management / layout customization apps?

Edit: Ahh—is there any chance you've previously configured N1 to run at larger than normal scale? If you open your `~/.nylas/config.json`, do you see a "interfaceZoom" value in there? That could do this maybe.

**Comment by laughedelic** [comment]
@bengotow yes, it was set to 80%. Setting the value in `config.json` to `1.0` solved the problem.

**Comment by laughedelic** [comment]
I don't see this in the settings now, has this feature been removed? Is it safe to edit this value in the config?
