### ISSUE TITLE
I did not receive a coupon code!

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2449]

**Comment by oldhickory30** [comment]
So how do I get a coupon code?

**Comment by Narga** [comment]
I have same question too.

**Comment by bengotow** [comment]
Hey folks! You should have received a coupon code email from us yesterday, but you may not have received a code if you:
- Have unsubscribed from the mailing list
- Have been inactive for more than 30 days
- Have requested that your account data be deleted


Sorry for the hassle! If you could fill out this Google Form, we'll send out another batch of coupons today. Note that you must have used N1 before Jun 14th to receive a coupon:

https://docs.google.com/forms/d/1nl3qhpxIOpRNCk11GohmwkyG7NCQaFW7Ygu_Q2gQYzs

**Comment by mookerific** [comment]
I entered my information in the google docs form. I've been actively using Nylas for the last two months or so, surprised that the coupon code did not come.

**Comment by xcorlett** [comment]
Me too - no coupon. I think it was because I might have disconnected and reconnected my account a few times over the course of the past few months.

**Comment by angusfretwell** [comment]
Same here 😿 have filled out the Google Form.

**Comment by materemias** [comment]
same for me, my account details are in the sheet

**Comment by memega** [comment]
@bengotow Same here. Have been using N1 since last October. Finally googled the issue of missing coupons and arrived here just to find out that there is a form, but that form has already expired. Is there still any chance to get one?

**Comment by bherila** [comment]
Same. Oh well.
