### ISSUE TITLE
Notification shown when there is no new mail

### ISSUE THREAD

**Issue by ronald-shcc** [nylas/N1#245]
The red notification icon in the dock stays active, even when there's  no new mail.

![schermafbeelding 2015-10-28 om 11 02 06](https://cloud.githubusercontent.com/assets/14944278/10785605/85b4b23a-7d65-11e5-992f-c12eb91b1583.png)

**Comment by bengotow** [comment]
Hi @ronald-shcc — thanks for filing this. I'll check this out and see if we can reproduce the issue. Just out of curiosity, did the unread mark disappear eventually?

**Comment by ronald-shcc** [comment]
No problem :) I had to force-quit the app so I could restart my mac.. after that it disappeared

**Comment by Affyyia** [comment]
I will work on it to see

**Comment by mbilker** [comment]
This may have been related to the issues with the unread count. Does this issue still appear in 0.3.32 or later?

**Comment by ronald-shcc** [comment]
I havn't seen it happening in a while, I guess it's been fixed? Thanks for your awesome work on the most awesome email client ever! :smile:
