### ISSUE TITLE
Not detecting message moved in other client

### ISSUE THREAD

**Issue by MidnightLightning** [nylas/N1#2454]
##### What operating system are you using?
OSX 10.11.5 (El Capitan)

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

I had N1 closed for several days (wasn't using that workstation) and in the interim moved messages around in my IMAP-accessed email account. When N1 was re-launched, all the messages I had Archived out of my Inbox were still shown as in my Inbox in N1 (and do not appear in the "Archives" folder of that account).

New messages appear in the inbox of N1 that I move to the Archives folder in a different email client (Thunderbird) do properly move in N1. It is only old messages that seem to not be in-sync any more.

This is somewhat related to [my comments](https://github.com/nylas/N1/issues/167#issuecomment-226256174) in #167; in theory adding some way to check the entire contents of a folder to see if old messages are still in that folder could solve this issue?

**Comment by JadoJodo** [comment]
I've seen this issue as well.

**Comment by jackiehluo** [comment]
Merging into #781!
