### ISSUE TITLE
Failed to add IMAP account without SSL

### ISSUE THREAD

**Issue by learning** [nylas/N1#2458]
We have a mail server support IMAP(no-ssl), I can use it via Apple Mail and Microsoft Outlook, but when I add this to Nylas N1, it tells me check my settings.

> Couldn't connect to the IMAP server 'mail.***.com'. Please check your IMAP settings.

I'm really sure my settings are correct.
By the way, iCloud and Gmail works fine in Nylas N1.

##### Are there any related issues?
No.

##### What operating system are you using?
OS X 10.11.5

##### What version of N1 are you using?
 0.4.45-7637265

--

**Bug?**
##### Do you have any third-party plugins installed?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/error-logger-extensions/nylas-private-er…:112 ErrorReporter: Shipping Logs. APIError
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/error-logger-extensions/nylas-private-er…:116 /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-private-ship-logs-task
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/task.js:49 [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/task.js:46 Running log ship: /var/folders/j9/_wlf_87j0qs6spy9fn1_dvph0000gn/T/, Nylas-N1-13725[.0-9]*.log$
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/task.js:46 No logs found to upload.
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/error-logger-extensions/nylas-private-er…:118 ErrorReporter: Shipped Logs.
```

And the log file is zero byte.

```
ls -al /var/folders/j9/_wlf_87j0qs6spy9fn1_dvph0000gn/T | grep Nylas-N1-13725                                                               16-06-16 - 11:09:38
-rw-r--r--    1 Learning  staff       0 Jun 15 09:45 Nylas-N1-13725.log
```

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No.

**Comment by jackiehluo** [comment]
Merging into #2498!
