### ISSUE TITLE
"Syncing mailbox.." runs forever without syncing

### ISSUE THREAD

**Issue by jetlej** [nylas/N1#246]
Syncing worked the first time I installed the app, but since it has not pulled in any new mail (Mac OSX El Capitan)

**Comment by williamgladeye** [comment]
Samesies (Yosemite)

**Comment by dgonzalezr** [comment]
Same for me.. It take looong long time with IMAP/SMTP Accounts..

**Comment by Affyyia** [comment]
It doesn't work for me. It annoys me the longer it takes.

**Comment by larfadin** [comment]
Didn't work too for gmail. No 2 etap login

**Comment by lashae** [comment]
Same here for a Gmail Account and a Google Apps mail accunt.

**Comment by ambroisemaupate** [comment]
:+1:

**Comment by pauloschilling** [comment]
Same here. Arch Linux, both Gmail and Google Apps accounts. **N1 0.3.32-1** from [here](https://aur.archlinux.org/packages/n1/) as of Jan 1.

**Comment by serieseight** [comment]
I am having this issue now too after the latest update for Gmail account

**Comment by nrutman** [comment]
I'm having this issue too...

**Comment by codingjoe** [comment]
:+1: same here

**Comment by arianit** [comment]
Same here. Gmail account.

**Comment by codingjoe** [comment]
It doesn't happen any longer. Maybe it just takes forever the first time you sync it? Does the entire mailbox get downloaded?

**Comment by chrisyeung1121** [comment]
+1, same issue. Is there any activity log where we can see and find out what it is doing?

**Comment by mbilker** [comment]
@chrisyeung1121 There is an Activity Log available from the Developer menu.

**Comment by codingjoe** [comment]
I had the same issue, but I think the initial sync is just taking a minute.
I don't think this is a bug, just a communication issue. There should be a note that the initial sync might take a while depending on your inbox size.

**Comment by alexanderadam** [comment]
Having the same problem now. Syncing never stops.
N1 runs now for a few hours and I don't have this much stuff on my accounts.

I have the sync engine running in a Docker container but the sync engine just has these two kinds of output (over and over again):
```JSON
sync-engine    | {"num_namespace_ids": 0, "level": "info", "process": 0, "timestamp": "2016-08-04T07:51:27.540309Z", "module": "inbox.transactions.actions:227", "greenlet_id": 140031734662960, "shard_id": 0, "event": "Syncback namespace_ids count"}
sync-engine    | {"level": "info", "process": 0, "timestamp": "2016-08-04T07:51:27.541807Z", "idle_workers": 500, "module": "inbox.transactions.actions:245", "greenlet_id": 140031734662960, "duration": 0.006143, "event": "Syncback completed one iteration"}

```
The only thing that changes are the timestamp and duration.

N1 isn't giving any error message or other status messages at all. Just `Please wait while we prepare your mailbox.`.

In the developer console is a  React warning and an error for the activity list:
```
Failed to activate package named 'activity-list' Error: AttributeCollection::contains (pluginMetadata) - you must provide a value
    at AttributeCollection.contains (/usr/share/nylas/resources/app.asar/src/flux/attributes/attribute-collection.js:104:15)
    at ActivityDataSource.buildObservable (/usr/share/nylas/resources/app.asar/internal_packages/activity-list/lib/activity-data-source.js:17:190)
    at ActivityListStore._getActivity (/usr/share/nylas/resources/app.asar/internal_packages/activity-list/lib/activity-list-store.js:87:37)
    at ActivityListStore.activate (/usr/share/nylas/resources/app.asar/internal_packages/activity-list/lib/activity-list-store.js:27:10)
    at Object.activate (/usr/share/nylas/resources/app.asar/internal_packages/activity-list/lib/main.js:25:31)
    at Package.module.exports.Package.activateNow (/usr/share/nylas/resources/app.asar/src/package.js:259:27)
    at /usr/share/nylas/resources/app.asar/src/package.js:245:26
    at Package.module.exports.Package.measure (/usr/share/nylas/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/usr/share/nylas/resources/app.asar/src/package.js:242:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/nylas/resources/app.asar/src/package-manager.js:587:21)
    at /usr/share/nylas/resources/app.asar/src/package-manager.js:565:29
    at Config.module.exports.Config.transact (/usr/share/nylas/resources/app.asar/src/config.js:184:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/nylas/resources/app.asar/src/package-manager.js:554:23)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/nylas/resources/app.asar/src/package-manager.js:537:46)
    at NylasEnvConstructor.module.exports.NylasEnvConstructor.startWindow (/usr/share/nylas/resources/app.asar/src/nylas-env.js:714:23)
    at /usr/share/nylas/resources/app.asar/src/nylas-env.js:731:25
```
and after that comes
```SQL
 SCAN TABLE Category for SELECT `Category`.`data` FROM `Category` 
```

When I click on the `Syncing your mailbox...` button it shows three from my four accounts. Every kind of data (Threads, Messages, Labels, Contacts, Calendars, Events etc.) is at `0 / 0`.

For me it is not even obvious whether it is a problem with N1 and/or the sync engine.

**Comment by khamidou** [comment]
@alexanderadam Did you run `bin/inbox-start` --- that's the core of the sync engine. `bin/inbox-api` is just the API.

**Comment by alexanderadam** [comment]
@khamidou makes sense. Seems that I forgot that when refactoring stuff. :wink:
Thank you!

However, it doesn't seem that it changed this much. Occasionally these log entries appear as well (besides from the stuff in the beginning:

```JSON
sync-engine    | {"total_time": 2701.53, "pending_avgs": {"1": 0.0, "5": 0.0, "15": 0.0}, "level": "info", "timestamp": "2016-08-04T15:15:37.961255Z", "module": "inbox.instrumentation:141", "times": "{'hub': 2691.81, None: 0.98}", "total_switches": 2691, "greenlet_id": 140647607166448, "event": "greenlet stats"}
```

In the opened `Syncing your mailbox` panel is no number state (`0 / 0`) anymore. Just different colours below the items.
Things like `Longconnectionstatus`, `Nextretrydelay` and `Nextretrytimestamp` sound interestering but nothing changes there. :cry:

**Comment by onlineth** [comment]
I'm having the same issue:/

**Comment by harryio** [comment]
facing this issue with 0.4.56!

**Comment by edarioq** [comment]
Still having this issue with V 1.0.21

**Comment by mephysto** [comment]
Just downloaded it to give it a try. But stuck on synching. v 1.0.21
Using Exchange / Office email account

**Comment by kirbyfan64** [comment]
For me, reinstalling it somehow fixed it.

**Comment by mephysto** [comment]
any updates on this? Still not working for me. (tried reinstalling as well)

**Comment by myedibleenso** [comment]
I'm having the same problem.

**Comment by cowboycodur** [comment]
Having the same problem

**Comment by plong0** [comment]
Having this problem on macOS Sierra 10.12.3 with Nylas Mail 1.0.32

Tried uninstalling and removing .nylas-mail folder from my home directory ... still not working after reinstall.

It's doing it with my Gmail account and also with a custom IMAP account.

**Comment by tobiasreinhard** [comment]
Still having this problem on macOS Sierra 10.12.3 with the latest version from Nylas Mail.

**Comment by Nattfodd** [comment]
Ubuntu 16.04, latest client (2.0.10) same. It stucks at syncing email & entire client stops working (can't receive new emails, can't send new email)

**Comment by alexandru-calinoiu** [comment]
Opensuse 2.0.16 the same issue, it's being running for 2 days now

**Comment by MickaelBergem** [comment]
Same here... Kind of annoying.

**Comment by simontong** [comment]
I'm having this issue now too

**Comment by timdeng2324** [comment]
After many days, the syncing finally finished. Then I reinstalled Nylas and it's been a few days. I'm sure it'll finish at some point, but taking multiple days, even weeks, to sync should definitely be considered a bug!

**Comment by vsagar9944** [comment]
Same problem in ubuntu14.04

**Comment by j-rahman** [comment]
Why is this issue `closed`? I am still facing the same problem on Ubuntu 16.04.

**Comment by eddo78** [comment]
Still having this issue on MacOS Sierra

**Comment by Jnolcox** [comment]
I too am still having this issue on Ubuntu 16.04. What changed that warranted closing the issue?

**Comment by rubenqba** [comment]
Until today, version 2.0.32 (windows) still have this issue.

**Comment by timdeng2324** [comment]
@rubenqba i am sorry to be the one to tell you this but nylas mail died months ago

**Comment by rubenqba** [comment]
No way!! I have no idea. Thanks, now I have to move on ;-)
