### ISSUE TITLE
Last update impossible on my mac

### ISSUE THREAD

**Issue by tristanlepachyderme** [nylas/N1#2460]
Hi,

I have a problem installing the last version of n1.
I am running on mac os el capitan 10.11.5.
I have currently the Version 0.4.40-85cf726 of n1.

When I enter my password to update n1, nothing happens, n1 closes and that it.

I went to see the logs and here we are : 
<img width="987" alt="capture d ecran 2016-06-16 a 00 45 04" src="https://cloud.githubusercontent.com/assets/19967168/16105839/b2168e90-335c-11e6-9681-fabc74446272.png">

I have no plug-ins installed

Please help,

Thanks

#1952

**Comment by tristanlepachyderme** [comment]
🐘 up !

**Comment by jackiehluo** [comment]
Hey! Sorry about the delay—does this issue still happen for you? What if you uninstall/reinstall?

**Comment by jackiehluo** [comment]
Going to close this issue for now, but email us at support@nylas.com!
