### ISSUE TITLE
Sent mail automatically getting deleted, Once it is sent.

### ISSUE THREAD

**Issue by rajzshkr** [nylas/N1#2463]
##### Are there any related issues?
No

##### What operating system are you using?
Mac

##### What version of N1 are you using?
0.4.45-7637265 

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
GMail, working with two account, but third one i am getting this issue

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by rajzshkr** [comment]
this occurs after the new update

**Comment by saul** [comment]
Furthermore - archiving mail in Nylas seems to only archive it in that mail client? gmail.com and Outlook on my phone both show the email as unarchived.

**Comment by jeffmcneill** [comment]
This appears to be the same issue as #2059, #2438, #2457

**Comment by jeffmcneill** [comment]
Note, I rolled back to the previous version Version 0.4.40-85cf726 (0.4.40-85cf726) and on new mail everything appears to sync properly. However, on old mail already in the system, any new actions are not reflected in Gmail/GoogleApps.

**Comment by rajzshkr** [comment]
@jeffmcneill How did you rolled back to previous version?

**Comment by jeffmcneill** [comment]
@rajzschkr I downloaded the previous version from the releases page and just overwrote the newest version (drag and drop to applications, I'm on OSX). Everything seems to work (all the settings) 0.4.40 https://github.com/nylas/N1/releases

**Comment by rajzshkr** [comment]
is there anyway to hide that orange bar at the top?? new update indication. TIA

**Comment by jackiehluo** [comment]
Is this issue still happening? I'm going to close it for now, but if it's persisting, some more information would be helpful!
