### ISSUE TITLE
Missing delete option for specific IMAP account

### ISSUE THREAD

**Issue by rgruyters** [nylas/N1#2465]
I have the issue I can't delete messages. The Trash folder is available on the IMAP server, but not matched to the Trash folder of the program. (if you know what I mean)
I can't customise the binding of folders. (Or at least I don't know how)

##### Are there any related issues?
Not that I can find

##### What operating system are you using?
Mac OS X El Capitan

##### What version of N1 are you using?
0.4.45-7637265

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
https://www.dropbox.com/s/rgi09au4x1tf9r0/Screenshot%202016-06-16%2012.41.19.png?dl=0

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Oh yeah!

**Comment by jackiehluo** [comment]
Merging into #1457!
