### ISSUE TITLE
is there anyway to hide that orange bar at the top?? new update indication. TIA

### ISSUE THREAD

**Issue by rajzshkr** [nylas/N1#2471]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
I _think_ it may close if you close and open the app again—we don't want to make it too easy to dismiss because a lot of our updates contain critical bug fixes. Closing this issue for now.
