### ISSUE TITLE
mail rule capture

### ISSUE THREAD

**Issue by pvinis** [nylas/N1#2473]
##### Related issues
#1074 

##### What operating system are you using?
osx 10.11

##### What version of N1 are you using?
0.4.45-7637265 (0.4.45-7637265)

--

**Feature Request**
##### Does this feature exist in another mail client or tool you use?
yes

--

in the mail rules, i want to have this:
lets say i have user@example.com
every mail that is directed to user+whatever@example.com should get a `whatever` or `plus/whatever` label,
every mail that is directed to user+something@example.com should get a `something` or `plus/something` label,
etc.

so what i need is a way to match the `to` address, and capture the part between `+` and `@`, and then the action would be to apply a label named `$1` or something, if `$1` is the captured part from above.

is that possible? if yes, how? if no, could we add it?

either someone add it if they know, or point me and i can give it a go. thanks.

**Comment by bengotow** [comment]
Thanks for filing this. We don't plan to support actions this complex in the built-in mail rules, but you could totally write a plugin to do this! The `unread-notifications` plugin in `internal_packages` would be a good place to start looking at the source :-)
