### ISSUE TITLE
Sent mail does not appear in any boxes

### ISSUE THREAD

**Issue by mingrammer** [nylas/N1#2474]
##### What operating system are you using?
OS X 10.11.04

##### What version of N1 are you using?
0.4.45

I've sent email, but mail does not appear in any boxes (Sent, Drafts, All)
also, the sent mail does not appear in gmail web client too.

**Comment by jackiehluo** [comment]
@mingrammer We were experiencing sync issues, but they should be fixed now—are you still seeing this problem?

**Comment by mingrammer** [comment]
@jackiehluo The problem seems to be fixed.The sent mail is appeared in 'Sent mail' box and gmail web client now.

Thanks.

**Comment by jackiehluo** [comment]
Great, glad to hear it!
