### ISSUE TITLE
Unable To Delete Folder  Does Not Appear on sever

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2475]
##### Are there any related issues?

...

##### What operating system are you using?
...10.11.4 OSX

##### What version of N1 are you using?
...Version 0.4.45-7637265 (0.4.45-7637265)
--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? No
![unabletodelete](https://cloud.githubusercontent.com/assets/16170272/16148444/df4aa6c2-3446-11e6-90a8-4d9edbe73e52.jpg)
![folder](https://cloud.githubusercontent.com/assets/16170272/16148446/e5766dc4-3446-11e6-9601-417900e61628.jpg)

I'm unable to delete the folder MailPilot, it does not show up on the server side nor in my other email clients, only within N1. Suggestions>? Contacted my email provider and thinks its certainly on the N1 side.
...

**Comment by dfv78** [comment]
I have exactly the same problem. Created a folder on N1, the folder was not created on the server (zimbra), tried to delete the folder on N1 and saw the same error message.

**Comment by oldhickory30** [comment]
Interesting mine was deleted off the server but still is appearing in N1.
Unable to remove it whatsoever!

On Jun 18 2016, at 7:55 pm, dfv78 &lt;notifications@github.com&gt; wrote:  

> I have exactly the same problem. Created a folder on N1, the folder was not
created on the server (zimbra), tried to delete the folder on N1 and saw the
same error message.

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2475#issuecomment-226974853), or
[mute the
thread](https://github.com/notifications/unsubscribe/APa9IFPjrgLGQf3zX2toUY3dLzlpujBcks5qNKGEgaJpZM4I4Pu3).![](https://github.com/notifications/beacon
/APa9IP7rPj7Eu0LIvrP-vyEoYrvB4EcQks5qNKGEgaJpZM4I4Pu3.gif)

**Comment by sumityadav** [comment]
Same problem, I was using Gmail shortcuts and accidentally it created a folder named **o** which I am not able to delete and it complains about the Folder not being empty. 

Is there a way to locate the folder in Mac and delete it directly?

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4662

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (0.4.47) that should fix this issue—let us know if you see it again! Thanks!
