### ISSUE TITLE
No mail showing at all.

### ISSUE THREAD

**Issue by x8BitRain** [nylas/N1#2476]
Hi, I'm using the latest Nylas on Mint 17.3, no emails from any accounts (gmail, yahoo) are showing up at all, it constantly says "Nothing to display".

It used to work about 3 months ago but stopped syncing mail for ages, so I stopped using it and uninstalled Nylas, now I've come back to see if it works and it it still doesn't work.

I've already tried re-authenticating, deleting the accounts, making a new Nylas account and adding them back in and creating a new Nylas account with no luck.

Any ideas?

**Comment by jmduke** [comment]
I'm running into the same issue on Mac (El Capitan):

![screenshot 2016-06-19 12 57 51](https://cloud.githubusercontent.com/assets/461046/16179529/72e18004-361d-11e6-98dd-f449b55864be.png)

**Comment by jmduke** [comment]
Here's the stack trace:

![screenshot 2016-06-19 13 00 19](https://cloud.githubusercontent.com/assets/461046/16179545/d85e930e-361d-11e6-8d0d-1f22fc07a8c6.png)

**Comment by televators** [comment]
I just installed Kubuntu (16.04 LTS x64) today and installed N1. I've got three accounts added and I'm getting the same 'Nothing to display' problem. No sign of anything going on in the background; it just doesn't work. Sucks too, because I've been using Mailbird on Windows and this is the only thing that I can find that is comparable. Install went fine, all of my other apps run fine.

**Comment by tylermenezes** [comment]
Same problem here (Arch Linux), different error:
![Uploading 2016-06-22-12:21:58.png…]()

**Comment by tylermenezes** [comment]
Same problem here (Arch Linux), different error:

![2016-06-22-12 21 58](https://cloud.githubusercontent.com/assets/173390/16280375/085858f8-3874-11e6-8257-32e6fc544f96.png)

**Comment by jackiehluo** [comment]
Closing this issue for now because it sounds like there are a lot of different issues—for any user-specific issues, email us at support@nylas.com, and we'll see what's wrong!

**Comment by ryanmaclean** [comment]
As this is the most "google-able" error regarding this problem and the tool is open source, I'll add a few tips for the "loading", "no mail to display" and "syncing mailbox forever" errors: 

 - Attempt to re-authenticate your accounts
 - Try a "reload" from the developer menu
 - Try a "run with debug launch" 
 - If you have multiple mailboxes, try each of them as one could be causing the issue, wherea the others may be fine ("Windows" menu, or cmd+[1...9])
 - Open Detailed logs to see if there are issues present

In my case, it was a SQLite issue, and involved removing then re-adding the account in question that was causing errors, but YMMV.
