### ISSUE TITLE
Don't use alt in Windows keyboard shortcuts

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#2477]
https://github.com/nylas/N1/blob/master/src/browser/application-menu.coffee#L114 is causing ctrl + alt + w (normally on Windows mapped to characters on international keyboards) to pop open the work window.

**Comment by emorikawa** [comment]
Fixed on https://github.com/nylas/N1/commit/20f9e7b3a11383b581265b41588bbb480e107f4a

**Comment by jackiehluo** [comment]
Hooray!
