### ISSUE TITLE
any plan about converting coffee scripts to es6?

### ISSUE THREAD

**Issue by roughsoft** [nylas/N1#2481]
thank you!

**Comment by amilajack** [comment]
The n1 team is working towards this goal.

**Comment by jackiehluo** [comment]
@roughsoft We've been doing it over time—it's just tens of thousands of lines of code and lots of room for error, so it'll probably be a while. Going to close this issue for now because it isn't a bug or feature request!

**Comment by joepeak** [comment]
thanks very much,i very like n1 and es6 !
