### ISSUE TITLE
Snooze feature not working for some messages

### ISSUE THREAD

**Issue by amperdan** [nylas/N1#2488]
Some messages (it tends to be threads) disappear for a second when snoozed and then just reappear straight away and are not in the Snooze folder.

This is a Gmail account but I have noticed it with others. I'm on the latest N1 version.

**Comment by amperdan** [comment]
A quick addition to this bug: It seems to be a problem applying the snooze label because other labels will also only remain for a second before vanishing.

**Comment by amperdan** [comment]
Another observation regarding this bug: This seems to happen if a label is applied when a reply is being sent or has recently been sent. It then seems to get stuck and won't **ever** apply the label / archive / snooze.

**Comment by jstejada** [comment]
Hi @amperdan, thanks for reporting this. Merging it into #2725
