### ISSUE TITLE
Ubuntu theme doesn't have window title bar for popout composer

### ISSUE THREAD

**Issue by amperdan** [nylas/N1#2489]
There doesn't seem to be a way to save the draft when composing a new message. Also, there is no way to close the window that pops up unless you hit delete in the bottom right. It would be really handy to be able to save drafts, just like with replying when the draft is saved in the thread.

**Comment by jackiehluo** [comment]
@amperdan Is it not saving the drafts for you automatically? If you compose a new message and close the window (and then go to Drafts), it should be there!

**Comment by amperdan** [comment]
@jackiehluo There wasn't an option to close the compose window. Now I have realised this is a theme issue. The Ubuntu theme does not show the top menu of the compose menu, so no close, minimise etc. Do I need to report that somewhere else?

**Comment by jackiehluo** [comment]
@amperdan Oh, whoa, can't believe we missed that! Yep, that's a theme issue—we'll put it on our list to fix for the next release.

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
