### ISSUE TITLE
Internal Error and duplicate emails

### ISSUE THREAD

**Issue by muditgarg** [nylas/N1#2490]
Hi Team,

I am often getting internal error messages after sending an email. I am also seeing that I have many emails in my trash with the same email having been sent multiple times and then deleted. I love N1 but this is making it quite unusable for me. Is there anything I can do to fix this?

The specific text of the error is "We had trouble sending this message to all recipients. Xxx@yyy.Net may not have received this email. An internal error occurred."

##### Are there any related issues?

...

##### What operating system are you using?
Mac OSX El Capitan

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by felipemillan** [comment]
I have the same problem.

The errors start after upgrading to the PRO version and sadly I had to remove my business account from Nylas as the emails was having errors all the time, sending again emails from 2 weeks ago or even more.

Please take care to fix this so I can get back to Nylas

**Comment by muditgarg** [comment]
@felipemillan Same here. These errors started after upgrading to the PRO version and I never realized but have sent about 30 - 40 duplicate emails. I was surprised to find no other issues filed for this till now.
I have stopped using the client for now as well.

**Comment by jackiehluo** [comment]
We're working on a fix right now in our back-end! Should be pushed soon. Merging this issue into #2446.
