### ISSUE TITLE
After upgrading to Pro version Nylas become USELESS and full of bugs.

### ISSUE THREAD

**Issue by felipemillan** [nylas/N1#2491]
##### Are there any related issues?

I get the internal error message maybe 60% of the time that I send an email

##### What operating system are you using?
MAC OS X 10.11.5

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

**Bug?**
##### Do you have any third-party plugins installed?
N1-Ido v0.2.1
Jiffy v0.1.9
Unsubscribe v1.5.2 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
all of them

##### Is the issue reproducible with a particular attachment, message, signature, etc?

any email will get this error, with and without attachments, using the plugins or not.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
nop

**Comment by jackiehluo** [comment]
We're working on a fix right now in our back-end! Should be pushed soon—and this issue should only happen for non-EAS providers if the message is using link/open tracking. Merging this issue into #2446.
