### ISSUE TITLE
No coupon code received

### ISSUE THREAD

**Issue by mathieufrot** [nylas/N1#2492]
Hello, 

I downloaded Nylas few days ago (the 13th of june) and finally deleted it because there was some features not present on Nylas whereas I got it in my actual mailbox. 

Now, I saw you added many features and Nylas is such better than my actual mailbox. I downloaded again Nylas few hours ago, but I did not received any coupon code to upgrade it to a full subscription (maybe you did not recognized me).

Is it possible to get the coupon code to obtain Nylas for free for one year please ? 

Here the proof that I used Nylas the 13th of june : 

![image](https://cloud.githubusercontent.com/assets/17006351/16199838/70182bcc-370b-11e6-8742-61a3b91b59ef.png)

Best Regards,

**Comment by jackiehluo** [comment]
@mathieufrot Send us an email at support@nylas.com with your email address! We can check on that.
