### ISSUE TITLE
Mail merge sends incorrect data for fields

### ISSUE THREAD

**Issue by felipemillan** [nylas/N1#2493]
The mass mail plugin it's an EPIC FAIL and I'm sad because I freaking love N1 but this gave me a MAJOR PROBLEM at work.

I have to send 55 emails saying SORRY but my email client made a mistake with the names and companies and details so SORRY.

This can't happen if you have a paid service.

Again I'm a big supporter of N1 but please take care of this issues as they are way to big for a paid service.

The main issue was that I uploaded a 55 email list with 5 columns 
name, lastname, email, company and country and after I sent the email I realize that all the emails has the same name and then all of them have the same company so everyone got a "personalized email" with a different name and company but the last name was ok.

**Comment by bengotow** [comment]
Hey! Can you clarify a bit what happened? Could you upload a screenshot of the composer with the tokens in there? Were there variables you dragged into the editor that were not converted into the values from the spreadsheet?

**Comment by jackiehluo** [comment]
Another incidence from Twitter DM:

>Hi, friends! I'm a huge fan of Nylas. I recently had an issue though—I sent out a bulk email using Mail Merge and it ended up sending the same email to all 500 people with the wrong `name` and `company name` variables. I did the drag and drop, then added the CSV and double checked everything, and it looks right. Then, when I sent, it only used the variables of the first person for all email addresses. Is this a know issue?
Now that I've sent those messages (caps made it take a full 24 hours, even as I manually went through and tried to update each wrong variable before they send from drafts) and now Nylas is running incredibly. Messages aren't archiving when I do so from another app (Spark on iOS) and messages aren't sending until I restart Nylas.

**Comment by emorikawa** [comment]
@grinich Has also reported this issue. Continuing to look into this.

**Comment by jackiehluo** [comment]
Another report from @bengotow. 😞

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
