### ISSUE TITLE
Nylas always reverts to my work email when replying

### ISSUE THREAD

**Issue by w4** [nylas/N1#2494]
Using the latest version of OS X and the latest version of Nylas, I can send an email from any email address and I can receive replies however, when replying to them replies, the email the reply is sent from is reverted to my work email without fail, Nylas will not let me change the email, either.

I'm not sure what the best way to show this is, I've tried my best to illustrate the issue below. I can click the address the email is sent from and a dropdown will come up with all my email addresses, however I cannot click any option in that dropdown list.

![](http://xn--83h.ws/oTRtXa1Sg7.png)

**Comment by jgrizou** [comment]
I have a similar issue but only when I send e-mail between two of my accounts. 

For example, me@gmail.com sends to me@hotmail.com. When I try to reply to this e-mail (so from hotmail account), it automatically replies to me@hotmail.com. But it should reply to the sender: me@gmail.com. This might be linked with the 'You' user handling.

**Comment by jackiehluo** [comment]
Merging into #2020!
