### ISSUE TITLE
Exchange account not syncing?

### ISSUE THREAD

**Issue by john-goldsmith** [nylas/N1#2495]
##### Are there any related issues?
Possibly #2466, #2476, or #2468 -- hard to tell.
Possibly [sync-engine #301](https://github.com/nylas/sync-engine/issues/301)

##### What operating system are you using?
OS X 10.11.5

##### What version of N1 are you using?
0.4.45-7637265

--

**Bug?**
After updating to the new version of Nylas last week, my previously-working Exchange account no longer seems to sync email, rendering Nylas useless.  Logging into my account via a web UI definitely shows that I have email (read, unread, etc.), but Nylas just shows the inbox zero graphic.

- Rolling back to `0.4.40` yields the same results.
- Removing and re-adding the account yields the same results.
- Quitting Nylas, nuking the `~/.nylas` directory, and restarting the app yields the same results.

With debug flags enabled, the only things that the console reports are a React deprecation warning regarding `__spread` and:

`SCAN TABLE Category for SELECT Category.data FROM Category`

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have one account added/configured (Exchange) which is being impacted, so I can't speak to other providers.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
n/a

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
n/a

**Comment by hallamoore** [comment]
Another user with an exchange account is having this problem: 
"I can add this account - that appears to go successfully - but it never syncs any mail, let me send mail etc."

Zendesk ticket: https://nylas.zendesk.com/agent/tickets/3801

**Comment by jackiehluo** [comment]
Merging into #1868!
