### ISSUE TITLE
Can't setup an account with SSL

### ISSUE THREAD

**Issue by THPubs** [nylas/N1#2498]
When setting up an account, with `require ssl` ticked, it says can't connect and check the credentials. But when I try with ssl un-ticked, it worked. Any idea how to fix it?

**Comment by sixlive** [comment]
I'm also running into this issue with both privateemail (namecheap) and zoho pro.

**Comment by enoversum** [comment]
Unfortunately, all the same here. I cannot untick SSL also, once I checked it. The account had worked before, since getting an error on this machine when using emoji I tried to completely re-install the app, but unfortunately this way I can't get through to my account anymore.

**Comment by sixlive** [comment]
Also, I noticed once checked the 'Require SSL' checkbox can not be unchecked.

**Comment by avegao** [comment]
I have the same problem. I've try with a free Zoho account with my domain.

**Comment by apopa116** [comment]
Same problem here using Zoho. When clicking the "Connect Account" button I receive the message "Error when connecting to the server. Please check your settings."

> Incoming server: imappro.zoho.com, Port: 993, SSL
> Outgoing server: smtp.zoho.com, Port: 465, SSL

**Comment by THPubs** [comment]
Any updates on this issue?

**Comment by bengotow** [comment]
Hey folks - this will be fixed in the next release.

**Comment by bengotow** [comment]
6c3bcf99adab2be6a28dd4c3c58f4701eec8a2fe

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
