### ISSUE TITLE
Scheduler 

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2499]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
@oldhickory30 Could you specify the problem you're seeing?

**Comment by oldhickory30** [comment]
Basically no calendar appears in the email.

On Jun 21 2016, at 10:52 am, Jackie Luo &lt;notifications@github.com&gt;
wrote:  

> [@oldhickory30](https://github.com/oldhickory30) Could you specify the
problem you're seeing?

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2499#issuecomment-227501599), or
[mute the
thread](https://github.com/notifications/unsubscribe/APa9IJIDhiDFzBxZmkZpkbKn_va0U4hyks5qOBa6gaJpZM4I6a7l).![](https://github.com/notifications/beacon/APa9IHEuJkDDH8XpkMMj3MxJW2zZP_3Cks5qOBa6gaJpZM4I6a7l.gif)

**Comment by jackiehluo** [comment]
Does it still not show if you're focused on the composer?

**Comment by oldhickory30** [comment]
Correct....it does not show in the
composer.![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-
21a0a3ee-
c99a?r=cmVwbHkrMDBmNmJkMjBjZWE1MzBhN2VjNmE3OWMzNTc3YjE5MWFkYjlmMGFmYTg4MzU2MjNiOTJjZjAwMDAwMDAxMTM4YzRhNTI5MmExNjljZTA5OWUzNjhjQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 29 2016, at 8:47 pm, Jackie Luo &lt;notifications@github.com&gt; wrote:  

> Does it still not show if you're focused on the composer?

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2499#issuecomment-229545964&r=cmVwbHkrMDBmNmJkMjBjZWE1MzBhN2VjNmE3OWMzNTc3YjE5MWFkYjlmMGFmYTg4MzU2MjNiOTJjZjAwMDAwMDAxMTM4YzRhNTI5MmExNjljZTA5OWUzNjhjQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/APa9IBwWepdXHSMOH95Aoh7iZOHOz1deks5qQy5SgaJpZM4I6a7l&r=cmVwbHkrMDBmNmJkMjBjZWE1MzBhN2VjNmE3OWMzNTc3YjE5MWFkYjlmMGFmYTg4MzU2MjNiOTJjZjAwMDAwMDAxMTM4YzRhNTI5MmExNjljZTA5OWUzNjhjQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/APa9IGODTtax-ImRyLiKPtrVtqZ39bkMks5qQy5SgaJpZM4I6a7l.gif)

**Comment by jackiehluo** [comment]
Oh, no, I mean—your cursor needs to be in the composer for it to be inserted properly. Any chance you can post a GIF/screencap of what you're seeing?

**Comment by oldhickory30** [comment]
Sure, strange error btw.
![ss1](https://cloud.githubusercontent.com/assets/16170272/16497699/8bb60ab4-3eb5-11e6-9435-c61ade6fcc5b.jpg)

![ss2](https://cloud.githubusercontent.com/assets/16170272/16497706/939b1152-3eb5-11e6-83a2-87cfaf791efe.jpg)

**Comment by jackiehluo** [comment]
Merging into #1940!
