### ISSUE TITLE
Microsoft Exchange server settings

### ISSUE THREAD

**Issue by jsadeli** [nylas/N1#25]
I couldn't sync to my work exchange server because they require custom server address. Would be great if there's support for entering custom server address in Nylas N1.

**Comment by bengotow** [comment]
Hi @jsadeli thanks for reporting this issue - definitely something we need to fix. I've added a card to our Trello roadmap (https://trello.com/b/hxsqB6vx/n1-open-source-roadmap) - feel free to track it there.
