### ISSUE TITLE
Opens links in Safari when default browser is Chrome

### ISSUE THREAD

**Issue by ThatGerber** [nylas/N1#250]
When I click on a link in Nylas, it opens up in Safari. My default browser is currently Chrome. It would be nice if the email client respected mac defaults or provided a setting to choose a default browser to open links in.

**Comment by bengotow** [comment]
Hey @ThatGerber —hmm, that's interesting. Can you try opening `Terminal` and typing the command below? `open http://apple.com/` That's essentially what N1 does—curious whether that opens in Safari or Chrome for you. Most of our team uses Chrome and we haven't seen any issues with it opening Safari so far.

**Comment by ThatGerber** [comment]
In true fashion, I can't reproduce it. 

I opened up the activation email and clicked on the help link and it opened in safari. When I went back to do the same process, it opened in Chrome (my default).

**Comment by neic** [comment]
I have(had) the same issue. On the first run of Nylas I added one account through Chrome (my default browser). When I wanted to add a second one it opened Safari instead. I did not complete the authentication. After a restart of Nylas N1 it opened in Chrome again and everything worked as expected.
