### ISSUE TITLE
Search results doesn't appear

### ISSUE THREAD

**Issue by jacoboAR** [nylas/N1#2503]
Hi!

I'm using Nylas for a few IMAP acounts. There is a bug in the search feature. When I'm searching mails from a specific email address, the results showed are right for a few seconds. After that, the results are completely random. 
My OS is Windows 10 and I've installed Nylas N1 0.4.45

**Comment by bengotow** [comment]
Hi @jacoboAR — thanks for reporting this. The results you see for the first few seconds are powered by our client-side seach, and the ones that come in a few seconds later are powered by your IMAP provider. It sounds like your provider may not understand searches base on email address.
