### ISSUE TITLE
Mark as read not working

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#2506]
It's inconsistent but seems happen when I open the email soon after it arrives via shortcut key or via OS notification.  Then, you can never mark it as read until app restart. **Super** annoying!

**Comment by jweinstein** [comment]
Can anyone else repro this issue?

**Comment by emorikawa** [comment]
@jweinstein Yes, I can reproduce if it's the same message. There's some bad logic around not marking as read unless you go to a completely different thread and back again. We're working on getting this fixed for the next release.

If it's more persistent then that it may also be a syncback issue with our sync engine. We've been battling failing syncback actions recently: https://github.com/nylas/N1/issues/781

I'm going to consolidate this into: https://github.com/nylas/N1/issues/1298
