### ISSUE TITLE
Avatar Icon Syncronization

### ISSUE THREAD

**Issue by beverast** [nylas/N1#251]
When I first installed N1 it grabbed my avatar icon from gravatar.com. I then went to gravatar.com and changed my avatar to a different image but N1 did not update my image. If avatar icons could be updated that would be great! Thank you.
[Since I'm not an owner/contributor to this project I can't specify labels afaik, so I would consider this a feature request to whomever reads this.]

**Comment by bengotow** [comment]
Hi @beverast —thanks for filing this. I think this may be an issue with Gravatar or N1 caching your picture. Restarting N1 might fix the issue.

Long term, we'll definitely move from Gravatar to something else which gives us a bit more control. A few folks have asked for N1 to pull their Gmail / G+ profile pictures. 

I've added a note to that ticket on our project roadmap so we can get them both fixed—feel free to upvote it there if you've got a Trello account! https://trello.com/c/xjQ5IWKI/38-pull-gmail-avatars-for-gmail-accounts-not-gravatars

**Comment by beverast** [comment]
Awesome, thanks for the quick reply!
