### ISSUE TITLE
Links in docs are indistinguishable from normal text

### ISSUE THREAD

**Issue by courajs** [nylas/N1#2515]
<img width="925" alt="screen shot 2016-06-25 at 8 02 55 pm" src="https://cloud.githubusercontent.com/assets/1588273/16359765/2d94e296-3b10-11e6-9663-0ec9ff7fb8b7.png">
(from the [Architecture page](http://nylas.github.io/N1/docs/Architecture.html))

Turns out, "Reflux" and "Flux Application Architecture" in the above text are links! It would be super lovely if they didn't have `text-decoration: none`. Even just a coloration difference would work for me, but tends to cause trouble for people with poor vision or color blindness.

**Comment by bengotow** [comment]
Hey thanks for reporting this—looks like some new styling was applied to the docs that broke the link formatting. I pushed a patch to our gh-pages branch, should be deployed very soon!

**Comment by courajs** [comment]
👍
