### ISSUE TITLE
Composer: Replies should have one blank line between the reply and the original message's date line

### ISSUE THREAD

**Issue by markbao** [nylas/N1#2516]
Alright, I'm about to out myself as totally insane, but someone needs to say something 😉

Replies should have one blank line between the reply and the original message.

When I'm in the composer of N1, and I end a message like this:

![image](https://cloud.githubusercontent.com/assets/27594/16360367/20cddf14-3b2d-11e6-9db3-5841ed2c3a4a.png)

The cursor there represents the very last character in the reply. When sent, it looks like this:

![image](https://cloud.githubusercontent.com/assets/27594/16360369/3aa4ae0e-3b2d-11e6-8c72-b3b0c2a612bb.png)

Notice how there's there's no blank line between the end of my reply and the date line? I think there should be a blank line there – which is how Gmail does it:

![image](https://cloud.githubusercontent.com/assets/27594/16360375/a7b1d814-3b2d-11e6-9d19-888278528d1e.png)

##### Are there any related issues?
No

##### What operating system are you using?
OS X El Capitan

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

See above

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Gmail

**Comment by jackiehluo** [comment]
🙏  We're going to try to fix for the next update!

**Comment by jackiehluo** [comment]
Should be fixed in https://github.com/nylas/N1/commit/897a331e2531f287503eb400bca2086b8cd67406!

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should fix this issue—let us know if you see it again! Thanks!
