### ISSUE TITLE
Windows source build: "not a valid Electron app" "Cannot find module './windows-updater'"

### ISSUE THREAD

**Issue by OliverCole** [nylas/N1#2519]
##### Are there any related issues?
None found.

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
Latest source code

I'm following the [windows instructions](https://github.com/nylas/N1/blob/master/docs/Windows.md)

Build seemed to finish successfully with: 

    script/bootstrap completed successfully. You can start
    N1 via ./N1.sh --dev, or run tests with ./N1.sh --test

But running `electron\electron.exe . --dev` results in an error message:

    The app provided is not a valid Electron app, please read the docs on how to write one:
    https://github.com/electron/electron/tree/v1.1.3/docs
    
    Error: Cannot find module './windows-updater'

**Comment by dp87** [comment]
I am seeing the same behavior here.

**Comment by OliverCole** [comment]
@dp87 Glad it's not just me. I'm no JS/Electron guy, but perhaps we need to start by comparing version and configuration to the [AppVeyor build](https://ci.appveyor.com/project/nylas/n1/history)?

Are you on Windows 10? AppVeyor is on Windows Server 2012 R2 (x64) for reference.

Incidentally, once this is fixed I can help test out #2485 and fix N1 for a whole bunch of other people...

**Comment by dp87** [comment]
Yes, I am on Windows 10 (Pro)

Just to see if we are on the same page, are you also seeing these two issues when building?

#2552
#2553

**Comment by OliverCole** [comment]
I am not seeing either issue.

For reference:

    Node: v6.2.2
    npm: v3.3.10
    Python: v2.7.9

According to the [docs](https://github.com/nylas/N1/blob/master/docs/Windows.md) only supports up to Node 4, although those docs were last updated in November 2015.

**Comment by dp87** [comment]
I tried it with Node v6 but it wouldn't work, I had to install 0.10.x as per the documentation to be able to proceed.

This is a bit weird. I could make use of some extra documentation. Let's see if somebody from the team has some updates I guess?

**Comment by bengotow** [comment]
Hey folks—was anyone able to get this resolved? I would definitely look to AppVeyor for reference—we actually inherited those Windows docs from the Atom project. They should still be accurate, but I went back in and changed the min Node version since we now require 4+.

**Comment by DanielSherlock** [comment]
Same problem, with node 4.x.
Same build success message, same error message, no visible problems during build.

    Windows 10
    Node 4.4.7 (x64)
    Python 2.7.12 (x64)
    VS 2013 (I think: it might equally be VSexpress)

**Comment by adamporter** [comment]
I'm duplicating some information from the slack channel here. I'm the user `adpo` over there.

I had the same issue until this afternoon. It appears that there's a coffeescript file that needs transpiled into javascript before things will work. Here's what worked for me:

Look in `<N1 Directory>\src\browser` and you'll see `windows-updater.coffee` in there. As a temporary fix, run that file through http://js2.coffee to create a `windows-updater.js` file and drop it into the same directory. Then run `electron\electron.exe . --dev` and it should fire up N1 for you.

**Comment by OliverCole** [comment]
That certainly results in N1 starting. It leads to some other issues, but I think it could be a good workaround.

**Comment by adamporter** [comment]
Just following up, my comment above was with Win7 x64. I've _finally_ gotten N1 installed on Win10 x64 and the same thing happened.

Exact same issue.

Exact same steps 'fixed' it.

**Comment by adamporter** [comment]
Apparently, I spoke too soon. It's going right to the email provider screen...not allowing me to select that I've got my own sync-engine to connect to instead. Interesting....

**Comment by bengotow** [comment]
Hey folks - sorry, it looks like the windows-updater file was being loaded before CoffeeScript support was initialized in the app. We've converted that file to ES2016 in 0888c5cdd0432e8496ac5b33daa0506bb89deb6d and I've confirmed that you can build and run the app with `electron\electron.exe . --dev` on Windows 10 with VS2013 and NodeJS 4.2. Should take care of this.

Also we welcome pull requests for things like this! :-)

**Comment by jarey** [comment]
Experiencing this same behaviour trying to run the compiled 0.4.40 realease tag.

I'm on win 10.

Node v.6.9.1
npm v.3.10.8
Python 2.7.11
