### ISSUE TITLE
Hyphen + space automatically converts to bullet

### ISSUE THREAD

**Issue by goeric** [nylas/N1#252]
I sign all my emails with:

**- Eric**

This automatically converts to a bullet :(

**Comment by bengotow** [comment]
Hi Eric—thanks for filing this. We've had some internal debates about this behavior (I also sign my emails with ` - Ben` and have had to start doing `— Ben` to prevent the behavior.) I'll see if we can get it fixed in a release soon.

**Comment by HeathNaylor** [comment]
I feel like a `-  ` (dash space space) would be better for a bullet or what other WYSIWYG do and have the bullet option on highlight or shortcut key (ctrl-shift-8 is common enough).

**Comment by Daniel15** [comment]
Why not put `- Eric` in a signature? :smile:

**Comment by mbilker** [comment]
Signature support was added in `0.3.32`. Is this still an issue?

**Comment by goeric** [comment]
Yes. This is an additional sign off on top of my default signature

**Comment by mbilker** [comment]
So this is still an issue by the Yes response?

**Comment by mbilker** [comment]
@goeric So this is still an issue by the Yes response?

**Comment by goeric** [comment]
Yes

On Thu, Dec 31, 2015 at 9:48 AM, Matt Bilker <notifications@github.com>
wrote:

> @goeric <https://github.com/goeric> So this is still an issue by the Yes
> response?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylas/N1/issues/252#issuecomment-168145013>.
>



-- 
Eric Posen
Co-Founder & Head of Product at Naritiv
p. 805.236.7054
t. @goeric <http://www.twitter.com/goeric>

**Comment by mbilker** [comment]
Alright then. Not closing this issue then.

**Comment by emorikawa** [comment]
Hey. After thinking about this more, we are going to leave the `hyphen + space` combo as a way to created bulleted lists in all scenarios despite it conflicting with `- Name` sign offs. There are several ways to get around this. First is using the default signature support. Also if immediately after creating a list you press `backspace`, it will undo the automatic list creation and leave you with a hyphen. You can then continue typing as normal. Furthermore if you paste a hyphen space it will not automatically create a list.
