### ISSUE TITLE
Tracking Is Causing Email To Send Same Message Repetitively ! (Beware)

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2520]
##### Are there any related issues? When Tracking Is Enabled!

...

##### What operating system are you using? OSX 10.11.5
...

##### What version of N1 are you using? 0.4.45-7637265 (0.4.45-7637265)
...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by oldhickory30** [comment]
Had several of my customers upset with me this morning because their getting the same message over and over! I've identified the problem to be with tracking which I thought was fixed! Please fixed, people are really upset at me with good reason! Please Fix ASAP!

**Comment by caner** [comment]
I've happened to too.

**Comment by jackiehluo** [comment]
Merging into #2446—we're working on it!
