### ISSUE TITLE
iMail Server 12.5.3.93 Unable to Snyc Deleted and Trash

### ISSUE THREAD

**Issue by spenserhale** [nylas/N1#2521]
##### Are there any related issues?
[https://github.com/nylas/N1/issues/2465](#2465)
[https://github.com/nylas/N1/issues/1457](#1457)
Similar issue but appear to be different email providers.

##### What operating system are you using?
OS X El Capitan (v 10.11.5)

##### What version of N1 are you using?
0.4.45-7637265

--

##### Do you have any third-party plugins installed?
n1-unsubscribe, however doesn't work without either.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Provider: iMail Server 
Version: 12.5.3.93
Option: No SSL

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Reproducible on account setup. I tried removing account and setting it up new, and both times the trash was not setup.

**Notes**
Nylas Team,
For my Email Account on our iMail Server, the trash functionality isn't working.
It appears it is not understanding the Deleted Folder. (It is the standard, unchangeable folder for iMaill.) So I am unable to trash any items to these folders, the action button isn't available.

You can see from the screenshot that the "spenser" account has no trash but Deleted Folders.

![screenshot_6_27_16__5_14_pm](https://cloud.githubusercontent.com/assets/5643366/16400010/56723088-3c8c-11e6-89a6-f4f2d1cb0523.png)

What I can do next to help find a resolution to this bug?

**Comment by bengotow** [comment]
Hey—thanks for reporting this. This looks like a folder detection bug on our end, specific to iMail. Stay tuned!

**Comment by hallamoore** [comment]
Merging into #1457!
