### ISSUE TITLE
Lxqt/plasma 5 support

### ISSUE THREAD

**Issue by ozky** [nylas/N1#2523]
Would be nice to have better integration to lxqt and plasma 5 in future.
Maybe add native qt5 theme support it would make it lot more faster in plasma 5 and lxqt.
I recommend to add support to other than gnome-keyring at least,
like lxqt_wallet it acctually supports gnome-keyring and kwallet at build time.
https://github.com/mhogomchungu/lxqt_wallet

**Comment by bengotow** [comment]
Hey—thanks for reporting this! We'd love to have a lxqt theme, and pull requests are always welcome. Since this is a general sentiment an not a specific action item for our dev team, I'm going to go ahead and close this.
