### ISSUE TITLE
PGP private key not showing as from keybase?

### ISSUE THREAD

**Issue by th3fallen** [nylas/N1#2524]
##### Are there any related issues?

No

I've seen examples of other peoples privite keys showing similarly to how my public looks showing their keybase avatar and url, the private keys im importing from keybase do not. am i missing something?

##### What operating system are you using?
Mac OSX 10.11.5

##### What version of N1 are you using?
0.4.45-7637265

--

**Bug?**
##### Do you have any third-party plugins installed?
N1-Taiga

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
no

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
yes

**Comment by logandavis** [comment]
Hi Clark,

Thanks for reporting this. If you send a test message to yourself, then decrypt it and return to the preferences page, does the information now load? There's a known issue in the Keybase plugin where the Keybase information for a private key won't load unless the key has been used (e.g. to decrypt a message) in the last 30 minutes. I've already fixed it locally and the patch should ship with the next release.

**Comment by th3fallen** [comment]
@logandavis that fixed it. 👍

**Comment by th3fallen** [comment]
Unrelated and probably needs to be a new ticket, is it known that n1 wont decrypt a signed email from facebook?

**Comment by logandavis** [comment]
Not know, but I wouldn't be surprised if Facebook butchered the formatting of the PGP message. Can you open a new ticket with a sample message from Facebook?
