### ISSUE TITLE
Error when connecting to the server. Please check your settings. - setting up account

### ISSUE THREAD

**Issue by russellharrower** [nylas/N1#2526]
I am trying to set up an IMAP mail account (cPanel)
however I am getting the following error when I try to set up the account.

`Error when connecting to the server. Please check your settings.`

I can't give you any more info than that, as I can't access the logs

**Comment by bengotow** [comment]
Hi @russellharrower — thanks for reaching out. I believe this is due to an issue with the "SSL Required" checkbox in N1. Can you try toggling it off and see if it fixes the issue? It should be fixed in a patch release early next week. Cheers!

**Comment by fanyer** [comment]
solve my problem, though tencent Inc's exmail mailbox show that ssl should be turn on.
Thank you!
