### ISSUE TITLE
Conversation window scrolls down when draft updates

### ISSUE THREAD

**Issue by Honason** [nylas/N1#253]
When I'm writing a reply in separate "popout" window to be able to see the content of the message I'm replying to, conversation view scrolls to bottom periodically as the draft at the bottom updates every xx seconds.

Screenshot should help explain the situation.

![screen shot 2015-10-28 at 11 07 02 pm](https://cloud.githubusercontent.com/assets/2352554/10804613/ae51d58e-7dc8-11e5-8027-6399c4460691.png)

**Comment by grinich** [comment]
This should be fixed now! Please re-open if you have steps to reproduce.
