### ISSUE TITLE
HTML emails are unreadable

### ISSUE THREAD

**Issue by davejlong** [nylas/N1#2531]
##### Are there any related issues?
None that I could find.

##### What operating system are you using?
Darwin Davids-MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64 i386 MacBookPro11,1 Darwin

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Have it with all HTML emails.

When I open an HTML email, it's height shrinks down to the point that it's unreadable. There's no scroll available to scroll through the message. The height of the email seems to be random every time I open the email.

<img width="831" alt="screenshot_6_29_16__10_37_am" src="https://cloud.githubusercontent.com/assets/175317/16456441/db49e60c-3de5-11e6-8019-534933cd2f59.png">

**Comment by bengotow** [comment]
Hmm this is really strange—I don't think we've seen any other reports of this. It's definitely not specific to some HTML emails an not others?

**Comment by davejlong** [comment]
After I paid more attention over the past day or so, I noticed that it seems to pretty much be Massdrop specific emails that it happens to. Next time I get one, I can upload the HTML portion of the email.

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4056

Super bizarre that this issue keeps happening to people with Massdrop emails!

**Comment by jackiehluo** [comment]
Merging this into #1280!
