### ISSUE TITLE
Better UX connecting to self-hosted Sync Engine

### ISSUE THREAD

**Issue by YurySolovyov** [nylas/N1#2536]
It should be enough to just point to custom API endpoint to get it running.
If this requires user involvement, show some UI to ask required info.

**Comment by OliverCole** [comment]
That's a good idea, but currently self-hosted sync engine seems to be completely unusable anyway, due to #2468!

**Comment by andysaini** [comment]
what about a plugin? or something on the startup?

**Comment by jackiehluo** [comment]
We're working on solving both issues together—it'll just take some time since we're working on some big projects right now!

**Comment by hallamoore** [comment]
There's a new self-hosted sync engine onboarding flow in the 0.4.47 release!
