### ISSUE TITLE
Messages in thread randomly being moved to trash

### ISSUE THREAD

**Issue by nasadorian** [nylas/N1#2538]
##### Are there any related issues?

...

##### What operating system are you using?
OS X El Capitan

##### What version of N1 are you using?
0.4.45

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="502" alt="screen shot 2016-06-30 at 3 00 29 pm" src="https://cloud.githubusercontent.com/assets/1136563/16505819/b2bcdfd4-3ed3-11e6-9287-d47c69a3758a.png">

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Merging this into https://github.com/nylas/N1/issues/2535
