### ISSUE TITLE
32-bit Linux Builds

### ISSUE THREAD

**Issue by andyforceno** [nylas/N1#254]
I received my invite today, and excitedly downloaded the .deb immediately, only to discover my architecture (32bit Intel) is not supported. Are there any plans for a .deb package compatible with 32bit processors? Is it/will it be possible to compile on 32bit Linux systems? My distro only recently switched to 64bit, but I'm not ready to re-install just yet.

**Comment by Revod** [comment]
I have the same problem, today I received my invite and download the .deb when Open it I see "Wrong architecture 'amd64'"

**Comment by dikiaap** [comment]
yeah, I agree. need update with 32bit architecture.

**Comment by Revod** [comment]
any news about that?

**Comment by dikiaap** [comment]
nothing, I also try this app. But same problem.

**Comment by arangates** [comment]
will compiling from the source help ??

**Comment by mbilker** [comment]
As Electron supports 32-bit platforms and Docker could help here, it is possible.

**Comment by Revod** [comment]
Any news? want to use this in my 32bit linux :(

Worked fine in 32bit Windows 10 but I just use windows for some works and the rest linux is my principal os

**Comment by mbilker** [comment]
It works on Windows 32-bit because N1 is compiled for for Windows 32-bit,
which is compatible with Windows 64-bit because of SYSWOW64.

There is nothing stopping you from compiling and running N1 under 32-bit
Linux. I am working on an automated Docker build for 32-bit Linux.

**Comment by mbilker** [comment]
News on the Docker front. In about 2 hours of work, I am able to build N1 under a 32-bit Ubuntu 14.04 Docker image to produce a 32-bit N1. I still need to test it, but it is building the native modules as `ia32`.

**Comment by WACMemphis** [comment]
Any chance you can offer the 32bit versions on your homepage?

**Comment by fulopm** [comment]
Is there any news about 32bit version?

**Comment by jackiehluo** [comment]
Closing for now because it's not in the scope of this project! Feel free to build your own, of course, but we're probably not going to officially support these versions.

**Comment by Bugsbane** [comment]
Well, if that's the case, then there's no way I'm installing this on any of my systems, 32 or 64bit. I want one client I can use anywhere. Hello Thunderbird.
