### ISSUE TITLE
Nylas N1 does not work on MacOS Sierra

### ISSUE THREAD

**Issue by felipemillan** [nylas/N1#2544]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS Sierra 10.12 Beta (16A201w)
##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
All of them (Google apps, Gmail, Zoho)
##### Is the issue reproducible with a particular attachment, message, signature, etc?

Emails does not load. I login by mistake to gmail and I realize that I had 20 emails unread and I check my other email accounts and the same.

It's not loading new emails no sync

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by JulianLaNeve** [comment]
I'm using macOS Sierra, and having no problems. Can you try re-installing it?

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this—it looks like we have several thousand users on Sierra already. This may be another issue. Closing until we can narrow it down a bit more.
