### ISSUE TITLE
No mark as spam icon for IMAP

### ISSUE THREAD

**Issue by cptstarling** [nylas/N1#2545]
There's no "mark as spam" icon for my IMAP-account (not Gmail) as suggested [here](https://support.nylas.com/hc/en-us/articles/217914288-Marking-messages-as-spam).

There's also no such option when right-clicking the e-mail, or a keyboard shortcut.

BTW: does Nylas "learn" what's being considered as spam and not, and does it move messages accordingly by itself, as Thunderbird does? // _edit:_ [ouch](https://github.com/nylas/N1/issues/1549#issuecomment-191932631) - would save us a lot of time though. I mean these kind of features is what's making Thunderbird unbeaten when it comes down to usability (ànd it's totally free).

**Comment by jackiehluo** [comment]
Merging into #1457!
