### ISSUE TITLE
Screenshot used in README got corrupted?

### ISSUE THREAD

**Issue by hartwork** [nylas/N1#2546]
Hi!

I think the [N1 screenshot used in the README](https://camo.githubusercontent.com/523d70b46011cac9628899f9b2a9f467d5f20a12/687474703a2f2f6e796c61732e636f6d2f4e312f696d616765732f312d312d696e697469616c2d6f75746c6f6f6b2d626173652e706e673f66656232303136) got corrupted somehow. I'm attaching a copy of what I am presented, a plain download of that file. Look's weird, right? :smiley: 

Best, Sebastian

![687474703a2f2f6e796c61732e636f6d2f4e312f696d616765732f312d312d696e697469616c2d6f75746c6f6f6b2d626173652e706e673f66656232303136-copy](https://cloud.githubusercontent.com/assets/1577132/16541126/1d5425d4-407b-11e6-83c1-d6eb5a50b18e.png)

**Comment by jackiehluo** [comment]
Hm, might be your download! 😞  Here's how it is for me: 
![687474703a2f2f6e796c61732e636f6d2f4e312f696d616765732f312d312d696e697469616c2d6f75746c6f6f6b2d626173652e706e673f66656232303136](https://cloud.githubusercontent.com/assets/8452682/16541521/2a322eea-403a-11e6-90a7-f38607e28b16.png)

**Comment by hartwork** [comment]
I get the broken image consistently (and still). I guess a CDN mirror broke then. I understand there is not much you can do then.
