### ISSUE TITLE
Can't register, register button is grey

### ISSUE THREAD

**Issue by ccming** [nylas/N1#2547]
I use surface pro 4, input name, email address, and valid password, but the register button is still grey.
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
Is there any chance it's the same as this issue?
https://github.com/nylas/N1/issues/2439

**Comment by ccming** [comment]
Maybe the same issue, I'm in Suzhou city China, when I use the office VPN ( Singapore ) it works well, both program or http://billing.nylas.com

**Comment by bengotow** [comment]
Hi @ccming — thanks for the reply. I'm going to go ahead and close this since it seems to be an issue with your machine being unable to reach the assets loaded from the CDN. In the future, we'll see if we can host these on our own servers to prevent this problem.
