### ISSUE TITLE
Archived Messages Return to Inbox immediately

### ISSUE THREAD

**Issue by protechig** [nylas/N1#2548]
The issue i'm having is whenever I archive a message (either using the shortcut or the archive button) the email returns to the inbox immediately.  I'm not sure why this is happening, but it has only started in the past couple of days. I tried uninstalling and reinstalling Nylas and the issues has persisted. 

##### Are there any related issues?
No, but I am seeing issues of old emails returning to inbox.

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?

0.4.45

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly - Google Apps for work. Verified on 2 separate accounts.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It happens on every message

**Comment by jackiehluo** [comment]
Merging into #781!
