### ISSUE TITLE
Chrome Inspector shows up after cmd-enter sending email

### ISSUE THREAD

**Issue by andrewparadi** [nylas/N1#2550]
##### Are there any related issues?

...

##### What operating system are you using?
Mac OS X 10.11.6 beta

##### What version of N1 are you using?
0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**
##### Do you have any third-party plugins installed?
Unsubscribe v1.5.1

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
All accounts are Gmail or Google for Work

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I haven't figured out a way to reproduce it but the result is visible in [screenshots here](https://www.dropbox.com/sh/43jeqrl81sqd0pe/AABa0LLibWP47JaEQPI_dbLDa?dl=0)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by pamo** [comment]
Seems to be the same issue as reported by #2188. I'm seeing similar behavior intermittently 😭

**Comment by jackiehluo** [comment]
Yes—merging into #2188!

**Comment by andrewparadi** [comment]
Awesome, thanks!

Andrew Paradi
andrewparadi@gmail.com
www.AndrewParadi.com




On Tue, Jul 5, 2016 at 1:54 PM -0400, "Jackie Luo" <notifications@github.com> wrote:












Yes—merging into #2188!
