### ISSUE TITLE
not syncing properly

### ISSUE THREAD

**Issue by sergiuprt** [nylas/N1#2551]
hi! i have a problem with syncing, i receive mails but after i have read them, they remain "unread", when i'm trying to delete them, they don't, all the messages just remain as they come, without geting "readed" or "deleted", i had tryed to "read"/delete them 5-10 times and nothing changes..

PS it keep syncing forever

UPDATE after i have readed/deleted mails from mail's web site, they get read/deleted in app, but with new mails comed after this, same storry
...

i'm on windows 10 home, Version 10.0.10586 Build 10586

version of N1 client is 0.4.45
--
i have no third-party plugins
...
it's not a issue with the mail service
...
here is a screenshot http://prntscr.com/boyg8s

**Comment by jackiehluo** [comment]
Merging into #781!
