### ISSUE TITLE
Build process on Windows fails

### ISSUE THREAD

**Issue by dp87** [nylas/N1#2553]
After building N1 on Windows 10, I get this:

```
Running "install" task
>> Failed to copy C:\Users\Daniel\AppData\Local\Temp\nylas-build\Nylas to C:\Program Files\Nylas
>> Installed Nylas into C:\Program Files\Nylas
```

So I see two issues here:

1. The error message is misleading. If the build script could not copy the Nylas folder from the Temp folder to Program Files, the script should not end saying that Nylas has been installed into C:\Program Files\Nylas (which, in fact, it hasn't, as there is nothing there).
2. If I go into C:\Users\Daniel\AppData\Local\Temp\nylas-build\Nylas and try to launch the executable from there, I get a few windows that look like this:

![2016-07-05 18_58_08-nylas n1](https://cloud.githubusercontent.com/assets/11840924/16592771/829234c2-42e2-11e6-8941-ad76c05ee7db.png)

So even if the build process seems to be complete, apparently something is going wrong.

##### Are there any related issues?
Not really, only #2552 which is something that I have encountered during the build process. It might or might not be related.

[Cannot define property:hf27lmrunllyp66r, object is not extensible. #2552](https://github.com/nylas/N1/issues/2552) 

##### What operating system are you using?
Windows 10 Pro

##### What version of N1 are you using?
0.4.45, compiled from source

**Comment by bengotow** [comment]
Hey—thanks for filing this! If you figure out a solution to this, pull requests would be really welcome. Our dev team uses Mac and Linux primarily, and we won't have the bandwidth to look into this for a bit. Cheers—

**Comment by bengotow** [comment]
Hey! Unfortunately we have a few native node modules that don't seem to build correctly with VS 2015. Our team uses VS 2013 to build N1, along with Node 4.2. Could you try using those? I believe you can run `npm config set msvs_version 2013` so `node-gyp` defaults to using VS2013 once you've installed it.

If you previously had problems building, you may have half-built or incorrectly-built node modules inside the project directory that don't get rebuilt. You can reset your working copy with `git clean -xdf` so `script/bootstrap` runs from scratch. Can you try that and let me know if you still have trouble?

Sorry, Windows is definitely the hardest platform to build Node projects on...

**Comment by dp87** [comment]
Thanks @bengotow! It took me a while to test this, but here I am with the results. I have run `npm config set msvs_version 2013` before building and installed Node 4.2. I have tried both the 32- and 64-bit versions just in case. This is what I get:

```
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\Users\Daniel\Downloads\N1-master\N1-master\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Daniel\Downloads\N1-master\N1-master\build\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Daniel\\Downloads\\N1-master\\N1-master\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "rebuild" "--msvs_version=2013" "--target=1.4.3" "--arch=ia32" "--target_platform=win32" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\Users\Daniel\Downloads\N1-master\N1-master\node_modules\better-sqlite3
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

I have completely wiped the build directory each time so I could start from a clean slate. There seems to be some progress by following your advice (all the previous steps complete without errors) but there is still something that is not quite right.

**Comment by dp87** [comment]
Installing VS 2013 and rebuilding worked, so it really looks like there is no workaround here at the moment, 2013 is mandatory.

Also, I had to run `electron\electron.exe . --dev` twice to make this work. After running it only once, the app would start but the window would look like the screenshot posted in my first message.
