### ISSUE TITLE
Feature Request: Toggle Signature Line for New Emails/Replies

### ISSUE THREAD

**Issue by sanjeevverma1** [nylas/N1#2555]
Currently in N1, if you use an email signature, it appears at the bottom of new emails as well as replies. It would be nice if you could add a toggle to the Preferences menu that allows users to only have their email signature appear for newly composed emails rather than replies to existing threads. When I'm already in an email conversation, there is little point in constantly adding my signature to the bottom of every reply, so I find myself having to manually delete the signature line every time I reply to messages. Does anyone else agree?

**Comment by jackiehluo** [comment]
Merging into #1945!
