### ISSUE TITLE
When pressing 'send' too quickly after composing, part of the message is cut off

### ISSUE THREAD

**Issue by nienque** [nylas/N1#2558]
##### Are there any related issues?
I couldn't find any.

##### What operating system are you using?
OS X El Capitan 10.11 Beta (15A279b)

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**

Whenever I click 'send' too quickly after composing my email, the last words/sentences do not actually get sent. On occasion the sent email would be blank entirely. I think it might have something to do with the way Gmail saves your message as a Draft every few seconds. Anything that gets added after the last time it was saved, doesn't get sent.

##### Do you have any third-party plugins installed?
Just the defaults.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only seem to get it with Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Compose an email to be sent with Gmail and click 'send' immediately after typing. Conversely, the problem *doesn't* occur if you wait a couple of seconds between composing the email and pressing 'send'. Having to do this every time is really annoying though.

**Comment by jackiehluo** [comment]
Merging into #2542!
