### ISSUE TITLE
Sync local email clients

### ISSUE THREAD

**Issue by thebergamo** [nylas/N1#2559]
I use Nylas in my pc at work(An Ubuntu 16.04) and in my personal pc(OSX El Capitain) and I love it!

But, I have a little problem, when I come to home after a hard day of work, when I open the N1 my emails are not synced, like I open and `archive` some emails, but in my another app the emails are not `archived`. Will be very cool, If when I login with my Nylas Account all my email clients are synced and auto load all my added email accounts in a fresh new installation.

**Comment by jackiehluo** [comment]
Merging into #781 and #2484!
