### ISSUE TITLE
"Message could not be sent because we could not save your draft" error

### ISSUE THREAD

**Issue by nkav** [nylas/N1#256]
Unfortunately a few times when I try to send a message I get this error modal that tells me that N1 has not been able to save the draft. 
<img width="419" alt="screen shot 2015-10-28 at 11 10 51 pm" src="https://cloud.githubusercontent.com/assets/4022244/10809085/4924823c-7dc9-11e5-913f-fd19c41c2608.png">

This also has the consequence of duplicating my original draft for some reason. After a few moments, however, I can finally send the draft without any errors.

**Comment by PlugaruT** [comment]
https://github.com/nylas/N1/issues/248
Same here!

**Comment by thepratt** [comment]
+1 on OS X 10.10.1 and N1 0.3.20-6bbe930. Didn't have the issue until I upgraded. I don't remember the previous version but I think it was 0.3.16.

**Comment by Treggats** [comment]
+1 on 3.19.0-31-generic #36~14.04.1-Ubuntu SMP x86_64 with N1 0.3.19-de7d1bb
Sending with a attachment like #248

**Comment by THPubs** [comment]
Im also facing the same issue! No attachments. This is the first message I tried to send through the app. Got the invite today :-)

**Comment by onnimonni** [comment]
+1 on OS X El Capitan 10.11 (15A284) and N1 Version 0.3.20-6bbe930 (0.3.20-6bbe930). Can't send any messages from gmail addresses (gmail addresses are only ones I tried) with or without attachments.

**Comment by ivgalic** [comment]
+1, OS X El Capitan 10.11.2 Beta (15C27e), N1 Version 0.3.20-6bbe930 (0.3.20-6bbe930). 

Happens most of the time when I try to send a message, although it seems to sometimes work. On GMail.

Additionally, it multiplies drafts as I'm writing (just keeps creating new draft versions and inserting them into the conversation) and keeps switching focus among them seemingly randomly. When I hit cmd+enter, it tries to send all of them at once and then fails. If I hit send on one of them, tries to send just that but also fails.

**Comment by cacyss0807** [comment]
Same problems as @ivgalic

**Comment by ephoras** [comment]
Got the same Error,
System: OSX El Capitan 10.11.1
N1: 0.3.20-7a956cd
Gmail, just text, no Attachment

**Comment by mbilker** [comment]
I got the error on Arch Linux.
N1: 0.3.23-a5256bd
Gmail, with attachment, disconnected from network, but reconnected and N1 just downloaded new mail. Restarted N1 and was able to send message and save the draft.

**Comment by Yerlix** [comment]
I've got this error as well.
It started today (yesterday it worked fine)
System: OSX Yosemite 10.10.5
N1: 0.3.26-c1ce330
The mail is from an exchange server, sending only text.

Tried restarting, reinstalling, reconnecting the network, ... nothing worked.

**Comment by jmotlong** [comment]
I've started encountering this same issue today. I've experienced it when sending email to @me.com addresses and custom-hosted gmail addresses (@redbisondesign.com - my company email addresses).

**Comment by ajaypillarisetti** [comment]
Just started having this problem this morning. OS X 10.11.1; N1: 0.3.26-c1ce330. 
![screen shot 2015-12-03 at 9 01 45 am](https://cloud.githubusercontent.com/assets/3826288/11567601/91dcadc6-999c-11e5-871f-159b805d865d.png)

**Comment by Escielenn** [comment]
Same error this morning. Started appearing late yesterday afternoon. Never seen it before.

Happens on IMAP email servers and Exchange servers. Gmail is seemingly unaffected. 

OSX: 10.10.5
N1: 0.3.26-c1ce330.

**Comment by mbilker** [comment]
What does the Activity Window display when the draft fails to save? Does it display error-ed tasks in the Queue tab? What are the response codes of the HTTPS requests made?

**Comment by Escielenn** [comment]
I’ll send this info when the error repeats. It’s not happened in the last four hours. It’s intermittent but when it starts, it’s across multiple accounts.

J

On Dec 3, 2015, at 1:32 PM, mbilker <notifications@github.com<mailto:notifications@github.com>> wrote:


What does the Activity Window display when the draft fails to save? Does it display error-ed tasks in the Queue tab? What are the response codes of the HTTPS requests made?

**Comment by mbilker** [comment]
@Escielenn I can not provide many details as I mostly use email for receive, very little sending to other people.

**Comment by tborychowski** [comment]
+1

**Comment by Olorin85** [comment]
+ 1. Just got this issue this morning.

**Comment by samruston** [comment]
Also having this issue.

**Comment by jstejada** [comment]
@Olorin85 , @samruston what version of n1 are you running?

**Comment by samruston** [comment]
@jstejada Version 0.3.32-b11131d (0.3.32-b11131d)

**Comment by Olorin85** [comment]
@jstejada Version 0.3.32-b11131d (0.3.32-b11131d) on MacOS X El Capitan version 10.11.2 (15C50). My hardware is a MacBook Pro Retina 15", i7 2.5 GHz, 16 Gb RAM.

**Comment by torstenwerner** [comment]
Same here. Fresh install. Outlook Account. I cannot send email messages at all.

**Comment by bengotow** [comment]
Hey @torstenwerner — do you see the same message as above? I think we've actually fixed the underlying issue that was causing this, maybe you could file a new ticket with the message you're seeing?
