### ISSUE TITLE
Pressing the 'Del' key archives emails

### ISSUE THREAD

**Issue by HammyHavoc** [nylas/N1#2560]
It is a little illogical in my opinion to have the 'Del' key archive emails instead of delete them; there needs to be an option-- turns out I've been archiving thousands of emails, this is going to be tedious to sort through whilst navigating important archived emails avoiding deleting them.

**Comment by jackiehluo** [comment]
@HammyHavoc There is an option in Preferences -> General! The reason we do that is because it's the same behavior that Gmail has.
