### ISSUE TITLE
Error when connecting to the server. Please check your settings

### ISSUE THREAD

**Issue by annielcook** [nylas/N1#2561]
https://nylas.zendesk.com/agent/tickets/3474

This morning I have updated my Nylas app to the new Pro version.

I was attempting to add a new email account and while the new add account 
screen is nicer, it was unable to add a new email.

I got an error saying "Error when connecting to the server. Please check your 
settings."

I have tried the exact same setting on Thunderbird and it worked there. I was 
also adding the same email previously to Nylas and it has worked. Moreover, 
I have actually tried to add a number of accounts - on the same email server 
though - and none worked.

Can you please check it out and let me know how I can debug this?

**Comment by jackiehluo** [comment]
Merging into #2572!
