### ISSUE TITLE
Scheduled send / Send later goes out at the wrong time / delayed

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#2569]
The backend send later queue is likely getting jammed up. Need to add monitoring to see how delayed this is and determine root cause. Reported by @grinich

**Comment by emorikawa** [comment]
Here's the original report from Tuan: https://nylas.zendesk.com/agent/tickets/4392 with more details.

**Comment by Zhouzi** [comment]
I confirm that the emails are not sent:

![screenshot send later](http://i.imgur.com/xBXFSty.png)

Is it something that is likely to be fixed soon or we better not rely on it for now?

I have no idea of how everything's working behind the scene but maybe it could rely on the user's system as well. It could check the drafts' send later queue regularly to send emails that have been delayed (and let the server know that those particular emails have been sent).

**Comment by hallamoore** [comment]
We've made some changes and send later should be accurate to within a minute now! Let us know if there are still issues.
