### ISSUE TITLE
Nested labels error

### ISSUE THREAD

**Issue by Leonid99** [nylas/N1#257]
In Gmail, I have a "Groups" label under "LinkedIn" label. In N1, there is an additional third-level "LinkedIn/Groups" label which doesn't exist in Gmail (see attachment). I'm not sure what's special about this specific label (there are many other nested labels, including some under the same "LinkedIn" label, all of them are displayed correctly).

<img width="257" alt="screen shot 2015-10-28 at 11 24 01 pm" src="https://cloud.githubusercontent.com/assets/754087/10809220/100f9958-7dcb-11e5-8b8a-1cb4c14275bc.png">

**Comment by bengotow** [comment]
Hi — thanks for filing this. Can you try clicking the "LinkedIn/Groups" label and seeing how many threads appear? It looks like our sync engine may have duplicated the label for some reason, and I would expect it to be empty. If both labels have threads inside them, that'll give us a bit more info.

**Comment by Leonid99** [comment]
It is, indeed, empty. No threads.

**Comment by bengotow** [comment]
Hey! Turns out this was related to a bug with renaming / editing labels. Should be fixed in the most recent builds.
