### ISSUE TITLE
Snoozing threads bouncing back immediately

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#2571]
When a thread gets snoozed it occasionally bounces back immediately. Reported by @grinich

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4122

**Comment by syabro** [comment]
Same here. Recorded a video.
http://s.syabro.com/eddg0.mp4

**Comment by jstejada** [comment]
I suspect this might be because moving the folder to the `N1-Snoozed` label failed. Does it happen every time? @syabro can you check the Activity Window for failed requests? `Window -> Activity` Thanks!

**Comment by syabro** [comment]
@jstejada actually I've just deleted N1 because I see empty inbox in it and a bunch of emails in google mail. It's really annoying
PS Removed this mails from inbox by going to Snoozed folder (they are there) and removing "Inbox" label from each.

**Comment by jstejada** [comment]
merging into duplicate #2725
