### ISSUE TITLE
Elevated Auth Errors / Login Error / Can't Login / Can't Connect Account

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#2572]
Potentially as high as 25% are encountering auth errors. Reported by @grinich 
Need to investigate distribution of auth error types and root causes.

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3542

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3704

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4005

**Comment by jackiehluo** [comment]
Another incidence—this error is "Invalid credentials. Please check that your IMAP username and password are correct."

https://nylas.zendesk.com/agent/tickets/4309

Another error people are getting is "Error when connecting to the server. Please check your settings."

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4313

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3965

**Comment by bengotow** [comment]
I think this was hot-fixed by this commit in Redwood, but it looks like it also needs to translate "Off" to false. It will be fixed in the next release of N1 as well. 

https://github.com/nylas/redwood/commit/d47dd9cd08314e815cdafc45939a97a3604f926e

**Comment by jackiehluo** [comment]
Sounds like that SSL fix is separate—this issue might have to do with custom settings getting overridden for known providers, per @pfista!

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4351

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3926

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3637

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3993

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3790

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4401

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3554

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4062

**Comment by jackiehluo** [comment]
Okay, conclusion after some investigation—a lot of these auth errors were fixed by the commit to Redwood, and the others are usually user error or an issue with the specific provider. Closing this issue for now, but we should keep an eye on it if the error rate rises again!

**Comment by paperscissors** [comment]
Definitely experiencing this, will try updating my client version!
