### ISSUE TITLE
Calendar Invites Sent using "Send a meeting request" are not appearing on Calendar

### ISSUE THREAD

**Issue by GM-Polyakov** [nylas/N1#2578]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10
##### What version of N1 are you using?
0.4.45
--

**Bug?**
##### Do you have any third-party plugins installed?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Unclear. I have an exchange calendar connected.
##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://cloud.githubusercontent.com/assets/14609676/16663480/135211d6-4431-11e6-8ebd-5acb1f5eda72.png)
![image](https://cloud.githubusercontent.com/assets/14609676/16663502/2d1f47dc-4431-11e6-806a-d49d922575a9.png)

**Comment by jackiehluo** [comment]
Merging into #1527!
