### ISSUE TITLE
Old messages are not synced

### ISSUE THREAD

**Issue by Leonid99** [nylas/N1#258]
Oldest mail seen in N1 is from Aug 24 (i.e. two months ago). There is years worth of mail that wasn't fetched.

**Comment by filipecatraia** [comment]
I've the same issue :+1:

**Comment by grovberg** [comment]
I'm not getting anything from Gmail from before installation. New message appear in the Inbox, but even "All Mail" only shows messages that just came in.

**Comment by mbilker** [comment]
Is this still an issue with the recent changes to N1 and the Sync Engine?

**Comment by Leonid99** [comment]
Yes. I don't see any mails older than this August. For example, I have a Gmail folder with files dating back years ago, but nothing newer than this April. In N1 it appears empty.

**Comment by mbilker** [comment]
Hmm. Pagin @bengotow for Sync Engine help.

**Comment by spang** [comment]
Folks, this is almost certainly an account-specific sync issue that we'll need to investigate more closely in order to figure out what's up. Please email support@nylas.com with which email address you're having trouble with. Thanks!

**Comment by Leonid99** [comment]
@spang, I emailed the support, but never received any answer.
