### ISSUE TITLE
Link not being rendered as clickable

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2582]
Dear all, 

I just noticed one link within a list of bullet points that is not being rendered:

![image](https://cloud.githubusercontent.com/assets/170947/16684812/5d93f42c-4507-11e6-95d1-218374bbb716.png)

Any ideas why this is happening?

Thankfully,

~Robert

**Comment by bengotow** [comment]
Hey—thanks for reporting this Robert. I'm not able to reproduce this with a simple link. Is there any way you could get the raw HTML of that email (maybe from a webmail client) and post the relevant part here?

![image](https://cloud.githubusercontent.com/assets/1037212/16697458/91e2a3bc-44fe-11e6-9591-1822f335ec34.png)

**Comment by orschiro** [comment]
Thanks for your help, Ben!

Maybe best if I forward you the email?

~Robert

**Comment by jackiehluo** [comment]
Closing this issue for now, since we don't have a reproducible case!
