### ISSUE TITLE
No notifications on El Capitan after reinstalling

### ISSUE THREAD

**Issue by huylv** [nylas/N1#2584]
##### Are there any related issues?

#2103

##### What operating system are you using?
Mac OS X 10.11

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

My mac has problem so I reinstalled Nylas yesterday. I removed all of its references and `~/.nylas` before reinstalling. Now it doesn't show up notifications nor has any sound. Badges still display, notification settings is set to "Banners" in System Preferences, "Show notifications for new unread messages" and "Play sound when receiving new mail" both are ticked but there's no sound nor notification when a new email arrives.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—can you try restarting your machine? This might be an issue with LaunchServices getting confused. Let me know if it's still an issue after that. Cheers!

**Comment by huylv** [comment]
I tried that several times already, it didn't help.

**Comment by huylv** [comment]
Now it works again. I'm not sure what was wrong though. Thanks for your help anyway. Cheers.
