### ISSUE TITLE
Can't sync more than 1000 Gmail Labels

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#2585]
Running Nylas N1 (Version 0.4.45 on Mac OS X 10.11.5)  
Initial sync on my Google Apps account won't sync more than 1000 labels (out of 1323).

**Comment by hallamoore** [comment]
This is a setting in Gmail! Under Settings > Forwarding and POP/IMAP, make sure this option is chosen:
![screenshot from 2016-07-28 18-01-15](https://cloud.githubusercontent.com/assets/5383890/17234387/5e6efe00-54ed-11e6-8e2b-05a3ac48188b.png)
