### ISSUE TITLE
Nylas N1 filling up RAM heavily on Win10 x64

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#2592]
Hi there,

currently, a more or less freshly installed N1 is constantly filling up RAM on my work machine (home machine is fine, though an older 'install' with latest updates) like crazy, to the extent that it forces other apps to close down due to lack of memory. I can see about 25 single Nylas processes in the task manager. 
I can reproduce it everytime I use my computer.

The behaviour: 

* System starts, N1 is in autostart
* System runs for a while
* ntoskrnl.exe ('System and compressed memory') starts filling up, drops and rises a bit, but finally rising up bit by bit until it reaches ~ 11GB of RAM after a few hours when apps start to crash
* I exit Nylas N1
* RAM usage of said process drops to healthy amout ~ 300MB

Until it reaches 11GB it was already running for some hours. 
Plugins used: 

* no additional/external
* most internal, except for the following:

* GitHub Sidebar Info
* Encryption
* View on GitHub
* Personal Level Indicators
* Phishing Detection

Anything specific I can do about it? Is this a known issue (didn't find anything on here so far)?

**Comment by emorikawa** [comment]
@enoversum Thanks for reporting this. We should not be consuming 11GB of RAM! By default we keep 4 processes running (background process, main window, hot window, worker window). We create an additional process for each composer window you have open. Those composer windows should only be a couple dozen MB of RAM each. We'll try and reproduce this on our other Windows machines to see if we can duplicate.

**Comment by enoversum** [comment]
@emorikawa Thanks for looking into it. On my home machine I have the exact four instances of N1 running, on my work machine it was definitely 25 instances. Please note that the ntoskrnl.exe was filling up, not the nylas processes. On my home machine I have an older installation, regularly updated through the updates shipping inside the app, while I had had problems with emojis on my work machine’s N1 and uninstalled and reinstalled N1 again (problem with emojis gone, RAM problems introduced). My guess is that the latest installer possibly introduced some kind of bug (couldn't add my accounts with SSL, but that is probably not related, but also something that had worked before) leading to the leak of RAM.

**Comment by vinniv** [comment]
Having the same issue.  Installed and loaded up Nylas N1 on a Windows 7 machine and it currently has 12 processes running.  Only default plugins are running.  Zero composer windows
![nylas](https://cloud.githubusercontent.com/assets/484729/16773972/f9abbf34-4827-11e6-9c40-aa5ab2f3ba56.PNG)

**Comment by enoversum** [comment]
@emorikawa Any news on this? This really eats up my work computer, and when I don't exit and restart N1 periodically, my other programs crash ungracefully due to little RAM. This happens constantly on my work computer, with the latest installer, as already mentioned.

**Comment by annielcook** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4222

**Comment by enoversum** [comment]
@annielcook Not visible from the outside :(.

**Comment by bengotow** [comment]
Another user mentioned this in a support incident: https://nylas.zendesk.com/agent/tickets/5527

**Comment by cnHeider** [comment]
+1

**Comment by enoversum** [comment]
I don’t experience this anymore. Latest version seems to have fixed it, although through holidays times I am not able to tell when exactly it was gone.

**Comment by bengotow** [comment]
Hey folks—I think the "many processes" issue was a separate problem, and is resolved by github.com/nylas/N1/commit/af278e07658d5a0ad23d6720f2adbe9c5f795855. (We were spawning a process to ship logs when exceptions occurred, and the task itself was erroring.) Gonna go ahead and close this!
