### ISSUE TITLE
E-mails archived from phone remain in inbox

### ISSUE THREAD

**Issue by bbirand** [nylas/N1#2594]
When I archive e-mails on my iPhone, the e-mails that are on Fastmail remain in the my N1 inbox. I don't see what the cause is, and I haven't noticed any correlations. 

If you can give me some steps to troubleshoot, I can try to figure out why this is happening next time.

##### Are there any related issues?

I couldn't find any specific issues related to this one.

##### What operating system are you using?
Mac OS 10.10.3

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Seems to happen with Fastmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not that I can see.

**Comment by jackiehluo** [comment]
Merging into #781!
