### ISSUE TITLE
Invitation code, can't sign into nylas again.

### ISSUE THREAD

**Issue by Tazmain** [nylas/N1#2602]
I am on arch linux, so I tend to use the AUR to packages, I had a gltich with nylas where it would start up and show me only a blank canvas, so I removed it and cleared all the files and cache. After reinstall I am suck on a login screen. None of my email address's work to reset my password for my N1 account. I got a invitation code and that is what I am have always used. Now I can't use Nylas at all, since I can't sign in.

**Comment by jackiehluo** [comment]
@Tazmain Did you create a Nylas ID before? You'll need to do that! That's distinct from the email accounts you've added to N1.

**Comment by jackiehluo** [comment]
Going to close this issue because it sounds like a specific account issue—let me know if creating a Nylas ID doesn't work.

**Comment by Tazmain** [comment]
Alright that works, but will I have to sign in on my other computer now?  Also it is stuck on signing into a company outlook account.

**Comment by jackiehluo** [comment]
@Tazmain Yes—you just need to sign into that computer with the same account! And that's not good. Are you getting a specific error (https://github.com/nylas/N1/issues/1512 or https://github.com/nylas/N1/issues/1440)?

**Comment by Tazmain** [comment]
No mine is stuck on Adding account, with the spinner. I meant my other computer that used the invite code, when I open nylas will I need to sign in or can I just continue to use it as is ?

**Comment by jackiehluo** [comment]
You will need to sign into the app!
