### ISSUE TITLE
Year coupon??

### ISSUE THREAD

**Issue by lukealford** [nylas/N1#2603]
> Nylas Identity: This month we're launching Nylas Pro.
As an existing user, you'll receive a coupon for your first year free. (Coming in the next few days via email!) Create a Nylas ID to continue using N1, and look out for a coupon email!

Been over 28 days since the launch of pro. Now Nylas is alerting me the 30 day trial is running out. What ever happen to the coupon for existing users?

**Comment by jackiehluo** [comment]
@lukealford We sent them a month ago! Send us an email at support@nylas.com, and we'll get yours to you.
