### ISSUE TITLE
Wrong search results

### ISSUE THREAD

**Issue by materemias** [nylas/N1#2606]
If I search in gmail and N1 side by side gmail gives me proper search results while there are tons of emails i cannot find with nylas. I thought the search is done through gmail api and so I expected the search results to be really similar. 
Is this the expected behaviour or can I do anything to improve search inside N1?

Let me know if you need additional details

**Comment by bengotow** [comment]
Hey @materemias — for Gmail accounts, we do use the Gmail API, but beginning a few releases back N1 also performs client-side search of the last 1000 threads in your mailbox. It sounds like those results may be incorrect (maybe you're using Gmail features, like `in:inbox` or `is:unread`?) and are polluting the results.

I'll see if we can get this fixed soon.

**Comment by materemias** [comment]
I don't search for anything fancy, just simple plain words for this test, maybe only the local search is happening...

**Comment by materemias** [comment]
I realised that this only happens in my MacBook but not on my ubuntu desktop

**Comment by HammyHavoc** [comment]
Having this issue too.

**Comment by systemeintegratedsolutions** [comment]
Same here. On Windows 10. I search for a mail I KNOW I received within the last week and it can't find it. I do a simple search using the sender email address and it finds only the last one, but not any before that. I haven't checked, but I'm pretty sure I hadn't received 1000 mails since I received the one I am looking for. Even so, I would expect it to find it using Gmail API. 

Great work so far guys. Keep it up!

**Comment by markbao** [comment]
I'm having the same issue as well - I'm letting the search complete, but search only finds items that are maybe a week or two weeks old, not more than that. I always have to go back to Gmail search to find something more than 2 weeks old.

**Comment by jackiehluo** [comment]
Another incidence: https://github.com/nylas/N1/issues/2248

**Comment by dbenic** [comment]
Search doesn't work using multiple strings or targeted emails as from:.

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5832

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/6262

**Comment by jackiehluo** [comment]
Merging into #750.
