### ISSUE TITLE
Tracking Does Not Work w/ Some Recipients 

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#2607]
##### Are there any related issues?

...

##### What operating system are you using?
...MAC OSX 10.11.4

##### What version of N1 are you using?
4.45
...

--

**Bug?**
##### Do you have any third-party plugins installed? Yes
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by oldhickory30** [comment]
Why does email tracking, not work with some recipients?

**Comment by jackiehluo** [comment]
@oldhickory30 Do you mean that they respond without triggering the open notification? That can happen with some email clients that block images.

**Comment by oldhickory30** [comment]
Yes, that is correct. I have several recipients that I email often, that do
not trigger the  open notification.

How is that possible? Will there be anyway to get around that in the future.

![](https://link.nylas.com/open/ep5x1z03l7qa2mf9l06sgbubu/local-0310f74a-
bbaf?r=cmVwbHkrMDBmNmJkMjAwZGE3YTRjMjQ3Y2NkMTI5NjA5MDcwZDEzMzllZDhkZWJkZjJiMzY2OTJjZjAwMDAwMDAxMTM5ZTM5YjE5MmExNjljZTA5ZGI1NTllQHJlcGx5LmdpdGh1Yi5jb20=)

On Jul 13 2016, at 11:17 am, Jackie Luo &lt;notifications@github.com&gt;
wrote:  

>
[@oldhickory30](https://github.com/oldhickory30&r=cmVwbHkrMDBmNmJkMjAwZGE3YTRjMjQ3Y2NkMTI5NjA5MDcwZDEzMzllZDhkZWJkZjJiMzY2OTJjZjAwMDAwMDAxMTM5ZTM5YjE5MmExNjljZTA5ZGI1NTllQHJlcGx5LmdpdGh1Yi5jb20=)
Do you mean that they respond without triggering the open notification? That
can happen with some email clients that block images.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/nylas/N1/issues/2607#issuecomment-232424223&r=cmVwbHkrMDBmNmJkMjAwZGE3YTRjMjQ3Y2NkMTI5NjA5MDcwZDEzMzllZDhkZWJkZjJiMzY2OTJjZjAwMDAwMDAxMTM5ZTM5YjE5MmExNjljZTA5ZGI1NTllQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/APa9IA_huqTHI3Bbrgjg0CUn139n3ZcHks5qVR2xgaJpZM4JLn9X&r=cmVwbHkrMDBmNmJkMjAwZGE3YTRjMjQ3Y2NkMTI5NjA5MDcwZDEzMzllZDhkZWJkZjJiMzY2OTJjZjAwMDAwMDAxMTM5ZTM5YjE5MmExNjljZTA5ZGI1NTllQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/APa9ICs7DgAR4NHw1ESxxDcCTBSdqRYfks5qVR2xgaJpZM4JLn9X.gif)

**Comment by jackiehluo** [comment]
There are some cases in which the metadata requests fail on our end, which could be avoidable (merging that into #2570), but in the cases where someone has set their email client to block images, we can't tell if the email has been opened because no request has been made to our server!

**Comment by richardabear** [comment]
![image](https://user-images.githubusercontent.com/7088147/65831012-484f7380-e2e7-11e9-9402-c0b234e755b0.png)


so far the only request ive gotten was the GET  request for the challenge token:

![image](https://user-images.githubusercontent.com/7088147/65831021-6cab5000-e2e7-11e9-8774-a1c2cd9d9a12.png)


Im not sure what im doing wrong here. i will also forward this to nylas support
