### ISSUE TITLE
Unable to mark as read in MacOS Sierra

### ISSUE THREAD

**Issue by viktorbergehall** [nylas/N1#2608]
In the latest beta of MacOS Sierra the user is unable to mark mail as read. 
To reproduce the bug use one of the following commands:
- Selecting/Clicking a unread mail.
- Swiping a unread mail to the right
- Right clicking a unread mail and selecting "Mark as unread"

The bug seems to effect the archive command as well. 

**What operating system are you using?**
MacOS Sierra Beta version 10.12-beta (16A238m)

**What version of N1 are you using?**
Latest version 0.4.45-7637265

**Do you have any third-party plugins installed?**
No

**Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**
Same bug on Gmail and Exchange

**Comment by emorikawa** [comment]
@viktorbergehall This is very likely related to: https://github.com/nylas/N1/issues/781. The underlying actions on our backend are intermittently failing causing the actions to revert.

**Comment by jackiehluo** [comment]
(Merging into #781!)
