### ISSUE TITLE
On mac, `Window` menu should include list of open windows

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#2610]
Reported from Zendesk:

The Window menu should list all open windows, i.e. composer windows, main windows, to be able to bring a specific one to the front.

**Comment by bengotow** [comment]
This should be the case now:

![image](https://cloud.githubusercontent.com/assets/1037212/16821007/d8cbb36e-4908-11e6-92a4-13efb60d8b43.png)

Can we confirm this user is running the latest version of N1?
