### ISSUE TITLE
Duplicate emails and notications on fastmail

### ISSUE THREAD

**Issue by annielcook** [nylas/N1#2612]
"I seem to be getting two copies of every emails . Is there something I can 
do to fix this?"

https://nylas.zendesk.com/agent/tickets/4338

**Comment by cliffwalker1959** [comment]
what is happening here?  I have  stopped using Nylas as support just hasn't been forthcoming. I cannot see the ZEN Desk tickets as its simply tries to log me into my own Zendesk account.

**Comment by jstejada** [comment]
hi @cliffwalker1959, I'm merging this issue into duplicate #1713, you can track its progress there

**Comment by cliffwalker1959** [comment]
still receiving two of each. Waste of time. Not fixed.



 *Mobile: *+ 598 (0) 937 79507 *Skype: *cliffwalker1959 *Email:*
 cliff@cliffwalker.com *Website:* www.wealthbeatsdebt.com[1]

                                             **Achieving Ambitious
                                             Results**



On Fri, Jul 29, 2016, at 02:32 PM, Juan wrote:
> hi @cliffwalker1959[2], I'm merging this issue into duplicate
> #1713[3], you can track its progress there
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[4], or mute the thread[5].
>


Links:

  1. http://www.wealthbeatsdebt.com/
  2. https://github.com/cliffwalker1959
  3. https://github.com/nylas/N1/issues/1713
  4. https://github.com/nylas/N1/issues/2612#issuecomment-236242990
