### ISSUE TITLE
No Mail Accounts Syncing

### ISSUE THREAD

**Issue by AndPlagueFlowers** [nylas/N1#2618]
##### Are there any related issues?

... No similar issues

##### What operating system are you using?
... Mac OSX

##### What version of N1 are you using?
... Latest version

--

**Bug?**
##### Do you have any third-party plugins installed?
... No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... No - impacts all accounts

##### Is the issue reproducible with a particular attachment, message, signature, etc?

... No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

ISSUE: None of my emails account are sending or receiving any emails.

**Comment by jackiehluo** [comment]
Should be fixed now!
