### ISSUE TITLE
Synchronization fails

### ISSUE THREAD

**Issue by MpStyle** [nylas/N1#262]
I have added a gmail account.
The first N1 synchronization concludeed correctly.
After that, I have added and applied a filter in the Gmail web client, therefor some emails were moved from "inbox" to other folders/labels. In N1, the emails remained in the inbox folder.
I was expecting that in N1 the emails were moved to the same folders/labels of Gmail. Is it correct?

**Comment by alrick** [comment]
Same sync problems here. If I move a message in the Archive in N1, the email is still in inbox on Gmail.

**Comment by bengotow** [comment]
Hey folks—this was most likely the result of scaling issues we had after the launch last month. Give N1 another try and let me know if you're still running into trouble!
