### ISSUE TITLE
Can't Authenticate with Gmail

### ISSUE THREAD

**Issue by ilgityildirim** [nylas/N1#2621]
I have been using N1 for quite awhile now. Everything was going smooth. I was just using my Gmail account. About 2 days ago, I have decided to add new e-mail accounts. Once again, everything was running just the way they were running before.

Today suddenly I realized I'm having this error;
```Nylas N1 can no longer authenticate with xxxx@gmail.com. Click here to reconnect```

There is also `Check Again` and `Reconnect` button on the right side of the message.

Needless to say, `Check Again` or `Reconnect` buttons didn't work. I have re-authorized N1 over and over again. I have removed my gmail account from N1 then removed N1 App's authorization from my Google account. I have added my gmail account again and re-authorized N1. This trick didn't work too. It is adding the mail but I still see the error on the top of the mails.

I see trying to add Gmail account via IMAP feature as a last solution but then I'd loose other cool features which comes with integrated Gmail account. Such as managing "contacts".

I really like and got used to N1, I hope it won't take long to fix this issue as doing business without a working e-mail app is very, very hard.

**Comment by herrkaefer** [comment]
same issue for me today.

**Comment by ilgityildirim** [comment]
Yeah, I thought this might be Nylas or Google related rather than user accounts.

**Comment by xdutaotao** [comment]
actually it seems that our trial is end, and need pay for upgrading to pro, or we cannot use it again. sad.

**Comment by ilgityildirim** [comment]
@xdutaotao I guess you're right. It seems I'm using Nylas Pro, trail version. I couldn't find any "downgrade" button. I don't need trail version as I really don't need anything extra than checking & replying my e-mails. I guess it would be an overkill to purchase "Pro" version just for managing contacts.

I like the interface and the looks of it though. It seems there is developer version which basically covers everything I need and it is free.

I'm hoping there would be a solution for this.

**Comment by orourkek** [comment]
This is a duplicate of #2617

**Comment by ilgityildirim** [comment]
@orourkek thanks, it was very informative. It seems this is a bug.

**Comment by diazgilberto** [comment]
Same here. This ticket should be open because is not fixed.

**Comment by ilgityildirim** [comment]
@diazgilberto are you using a paid version? If yes than you should contact Nylas, if not unfortunately now you have to pay or set-up your own.

**Comment by diazgilberto** [comment]
@ilgityildirim no I'm not paying. Is there any instructions how to set-up on my own?
