### ISSUE TITLE
Can I have a free version of Nylas N1 ?

### ISSUE THREAD

**Issue by joaop** [nylas/N1#2623]
I love this project, it's not perfect yet, but it's on the way to be. Don't have a credit card, and I want to keep using the mail client.

Is there a way to keep using it ? Maybe compiling it by my self ? Running my own sync engine ?

**Comment by ConorIA** [comment]
Precisely! You'd have to host your own sync-engine on a local machine or on a hosted server. 
https://github.com/nylas/N1/blob/master/CONFIGURATION.md

**Comment by joaop** [comment]
Will the "your 30 days trial has expired" message go away ? Now, when I delete some email, the email returns to inbox, and when I try to send an email there is a message sayign error: sorry , this message could not be sent. please try again, make sure your message address is correctly and not too large. (the email is a simple hello test).

Just running my own sync engine will fix it all ?

**Comment by ConorIA** [comment]
If you host your own sync engine, you are no longer using the Nylas hosted sync engine, so there are no more trial. There was an issue #2468 getting the sync engine to work with the new version of N1, but that was resolved with pull request #2485. You will need to make sure that you have that commit. I am not sure if it is in any release yet. Note that I, personally, am having trouble connecting two computers to a single sync-engine #2596, but I haven't seen anyone reporting issues for a single-machine sync-engine.

**Comment by jackiehluo** [comment]
@ConorIA is right! The reason we're charging for the service is because it costs us money to run sync for people—there won't be that error message from your trial expiring if you do it on your own.

**Comment by DroWnThePoor** [comment]
I'm not going to subscribe, but how do I get my e-mails un-synced/off of the Nylas servers? This kind of worries me, also how can I be sure my e-mail won't continue syncing to their servers, and just not syncing with my deactivated client?

**Comment by jackiehluo** [comment]
@DroWnThePoor We automatically delete accounts after a period of inactivity, but you can email us at support@nylas.com if you want yours deleted right now!

**Comment by ArchangeGabriel** [comment]
There is now a free version apparently. ;)
