### ISSUE TITLE
Third email account not showing in app but I still receive desktop notifications for it

### ISSUE THREAD

**Issue by davidalee** [nylas/N1#2627]
##### Are there any related issues?

...

##### What operating system are you using?
OS X (El Capitan)

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**
I have 3 Gmail accounts setup, but only the first two accounts are showing and accessible from the folders in the left pane. However, I am still receiving desktop notifications for new emails on that third account.

**Resolution**
I tried removing the account and re-adding it and viola, now it shows. But there must be a bug somewhere that prevented the third account from showing along with the rest of my accounts the first time I added it.

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Unclear at this time if the email provider is to blame for the bug although it seems unliekly. The bug is related to email accounts so I guess there's a chance it's related somehow.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I downloaded and launched N1, added 3 Gmail accounts in succession (a personal account, a professional account, and an alumni/college account). The last account is the one that's not showing.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
n/a

**Comment by jackiehluo** [comment]
Merging into #1587!
