### ISSUE TITLE
Drafts only available within Nylas

### ISSUE THREAD

**Issue by tekstrong** [nylas/N1#2628]
##### What operating system are you using?
Linux

##### What version of N1 are you using?
0.4.45-7637265

--

**Bug?**
All attempts to create a draft that also appears in my Drafts folder in Gmail fail. If the draft is created from within Gmail, the draft appears in Nylas. If the draft is created in Nylas, the draft never appears in Gmail.

This is a huge problem for me and my workflow as I often create messages and come back to them later... not always on the same device.

Ex.: If I am working on an email, save it to drafts, and then try to finish said email on my phone... no dice.

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail (Google Apps account)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes

**Comment by HammyHavoc** [comment]
Also having this issue.

**Comment by jackiehluo** [comment]
Merging into #2361—that's currently expected behavior!
