### ISSUE TITLE
Suddenly not able to delete/archive/read emails

### ISSUE THREAD

**Issue by HammyHavoc** [nylas/N1#2629]
Deleting, archiving or reading emails-- generally any change of status to an email results in it changing back to how it was a second later. Works fine in every other email app, and through the web interface, just Nylas N1 that is suddenly having problems.

##### Are there any related issues?
None that I can see.

##### What operating system are you using?
Windows 10.

##### What version of N1 are you using?
Latest.

--

**Bug?**
##### Do you have any third-party plugins installed?
Only first party plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Happens to all of them.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Happens to all emails;

**Comment by jackiehluo** [comment]
Merging into #781!

**Comment by jstejada** [comment]
Actually, merging into #2725
