### ISSUE TITLE
App crashes on macOS Sierra when submitting scheduler times in full-screen window

### ISSUE THREAD

**Issue by JEGLS** [nylas/N1#2630]
N1 Crashes when closing a tab in full screen view on Mac OS Sierra. (From creating calendar times to sending and responding emails in FS). No issues in normal windowed mode.

##### Are there any related issues?

...

##### What operating system are you using?
Version 10.12 Beta Sierra

##### What version of N1 are you using?
Version 0.4.45-7637265
--

Bug?
##### Do you have any third-party plugins installed?
Unsubscribe

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N1 Crashes when closing a tab in full screen view on Mac OS Sierra. (From creating calendar times to sending and responding emails in FS). No issues in normal windowed mode.

--

**Comment by mckernanin** [comment]
I see this issue as well, here's a crash log: https://gist.github.com/mckernanin/b76bd63abb9a81150eb735c2a0c787f3

**Comment by inb4ohnoes** [comment]
Bumping because this issue is still present in the latest update and it's driving me crazy!

**Comment by jstejada** [comment]
merging into #2792
