### ISSUE TITLE
Developer tools appear when sending emails (50% of the time)

### ISSUE THREAD

**Issue by tenleftfingers** [nylas/N1#2634]
After typing an email, pressing CTRL + Enter sends the mail, but often opens the developer tools which need to be closed.

**Comment by tenleftfingers** [comment]
It looks like this has nothing to do with shortcuts. The same thing also happens intermittently when I use the mouse to click 'Send'. 

I've noticed when the dev tools do pop out, it's with errors like: 

/usr/share/nylas/resources/app.asar/src/nylas-env.js:306 Error: Extension EmojiComposerExtension applied a transform to the draft that it could not reverse.
    at Promise.resolve.then.reverted (draft-helpers.es6:75)
    at tryCatcher (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/util.js:26)
    at Promise._settlePromiseFromHandler (/usr/share/nylas/resources/ap

**Comment by jackiehluo** [comment]
Merging into #2188!
