### ISSUE TITLE
Error when changing the Important label

### ISSUE THREAD

**Issue by keyfer** [nylas/N1#2636]
##### Are there any related issues?

Couldn't find any related issues in a quick search

##### What operating system are you using?
OS X El Capital
10.11.4

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265

**Bug?**
##### Do you have any third-party plugins installed?

Jiffy

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail, I believe.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not sure if it's reproducible, but it just happens when I try and change the label.

Here is the console error:
![https://screenshot.click/18-37-xktlu-nagij.png](https://screenshot.click/18-37-xktlu-nagij.png)

Here is the curl error:
![https://screenshot.click/18-37-r034w-bqia0.png](https://screenshot.click/18-37-r034w-bqia0.png)
--

**Comment by jackiehluo** [comment]
Hey! Is this persistent? If so, email us at support@nylas.com, and we'll take a look at your account!
