### ISSUE TITLE
Pieces of text disappears while typing the e-mail

### ISSUE THREAD

**Issue by maximefabas** [nylas/N1#264]
When I type an e-mail, it seems that the app frequently replaces the content of the e-mail with the last saved draft. After successfully typing all my e-mail, the app sent the previous draft too.

**Reproducing Steps**
Receive an e-mail
Click on forward
Type some text above the history, before sending it (take 5 or 7 mins, and write about 3 paragraphs).
Send

**Version**
0.3.19-de7d1bb (0.3.19-de7d1bb)

**OS**
Mac OS X 10.5 (14F27)

**Comment by grinich** [comment]
This should be fixed now! Please re-open if you have steps to reproduce.
