### ISSUE TITLE
Support link dead

### ISSUE THREAD

**Issue by annielcook** [nylas/N1#2641]
Could not auto-detect exchange server errors and links to a 'more help' page:
https://support.nylas.com/hc/en-us/articles/217592077

which no longer exists

linked to here: https://nylas.zendesk.com/agent/tickets/4222

**Comment by jackiehluo** [comment]
I think I just fixed that on Redwood! https://github.com/nylas/redwood/commit/7007b88f0fbbff617e13f38125bf7e7e3d30841b
