### ISSUE TITLE
Nylas suddenly started spawning hundreds of drafts in an infinite loop.

### ISSUE THREAD

**Issue by hotuan87** [nylas/N1#2643]
While writing an email response in Gmail, Nylas N1 started consuming a tremendous amount of system resources, slowing my computer to crawl. When I opened it up to see what was going on, I noticed that it had suddenly spawned 94 duplicate drafts for the email I had initially composed in Gmail. While observing it, it continued spawning new drafts (about 5 or 10 per minute). I had to force close the application and went into Gmail to delete all of the drafts.

##### What operating system are you using?
OSX El Capitan

##### What version of N1 are you using?
Version 0.4.45-7637265 (0.4.45-7637265)

--

**Bug?**
##### Do you have any third-party plugins installed?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Unclear how to reproduce the issue. I just noticed it while writing an email. It happened to be an email on a thread that I initially opened in Nylas, but then started writing to a response to in the Gmail web app.

**Comment by jackiehluo** [comment]
Merging into #2237!
