### ISSUE TITLE
A mailbox action for foo@gmail.com could not be completed. You may not be able to send or receive email

### ISSUE THREAD

**Issue by payammeyer** [nylas/N1#2649]
##### Are there any related issues?

Yes, #2010 and #1978 both of which are closed and nobody from N1 has commented on recently after folks including myself have started experiencing the issue again.

##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
0.4.25-a22631a

--

**Bug?**
##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure, I only use GMail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
You mean the client actually working consistently? Yeah, there are plenty but none as nice as N1 but I'm this close to giving up on it as there was the syncing issue a couple weeks ago and now this nonsense.

**Comment by jackiehluo** [comment]
Send us an email at support@nylas.com! We'll look into it—I'm going to close this issue for now because it's an individual problem we need to diagnose.
