### ISSUE TITLE
Closing the window should not "quit" the app

### ISSUE THREAD

**Issue by gilbitron** [nylas/N1#265]
Currently every time I close the window (red cross in OS X) and then click the app in the dock, it seems that the app has "quit" and is relaunching. Keeping the window open all the time is not feasible and N1 should follow common UX practices here.

**Comment by cschermerhorn** [comment]
I support this suggestion.  If anything, allow us the option of choosing what the close button does.

**Comment by YuriSolovyov** [comment]
definetly need an option

**Comment by bengotow** [comment]
Hey folks! On Mac OS X this should be fixed. On Windows and Linux, you can follow it here: #475. Going to go ahead and close this—enjoy N1!
