### ISSUE TITLE
Unable to connect to Gmail account

### ISSUE THREAD

**Issue by mikecole79** [nylas/N1#2650]
Unable to sign in to my Google account.  Added N1 to a new machine, and when I try to setup the Google email, I am greeted by a blank page.

Repro:
* Fresh install of N1
* When asked to setup a mail account, choose Gmail or Google Apps account
* The next page shows a message saying to sign in to your browser
* Browser opens with a blank page.  
* Logs show a whole lot of 404's for requests such as:

> 40407:59:56  RunCopycurl -X GET "https://:@n1-auth.nylas.com/oauth/google/token?key=RU6RSjACmJNurKJSCNqB_vUZAm9PSABVemFx8046KrojwEj-Rm1gnA=="
> 40407:59:54  RunCopycurl -X GET "https://:@n1-auth.nylas.com/oauth/google/token?key=RU6RSjACmJNurKJSCNqB_vUZAm9PSABVemFx8046KrojwEj-Rm1gnA=="
> 40407:59:52  RunCopycurl -X GET "https://:@n1-auth.nylas.com/oauth/google/token?key=RU6RSjACmJNurKJSCNqB_vUZAm9PSABVemFx8046KrojwEj-Rm1gnA=="
> 

##### Are there any related issues?
Unable to locate any that look the same

##### What operating system are you using?
Ubuntu 16.04 x64

##### What version of N1 are you using?
0.4.45-7637265

##### Do you have any third-party plugins installed?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Thus far, only Gmail

**Comment by bengotow** [comment]
The 404s are fine actually, N1 is just waiting for Google auth to complete and pinging our system. However, it's strange that you're seeing an empty page open in the browser, not an oauth page on Google. What browser are you using?

**Comment by mikecole79** [comment]
Closed the issue.  Found it is an issue with my browser (Google Chrome) having a penchant for opening anything that clicks to open a page to a blank.  Because why would you want to see the link you clicked on, right?  I'll work to resolve that issue locally, no issue with N1.  Worked fine when I switched my default browser to Firefox.

Thanks!

**Comment by bengotow** [comment]
That's no good! We'll have a fix in the next release though—you'll have a chance to copy the link and paste it into your browser from the "Sign in to Gmail" screen. Cheers—
