### ISSUE TITLE
中国下载这个APP非常慢

### ISSUE THREAD

**Issue by xzhangyueqian** [nylas/N1#2655]
你们好,
这个APP在中国下载非常慢(可能跟AWS有关), 
尝试了几次都失败了,
非常喜欢这个应用.
有没有别的渠道下载它?
谢谢~

**Comment by jackiehluo** [comment]
Unfortunately, there aren't really other places to download the app! You can download and run the source code from this GitHub repo, and we technically have our binary files available at https://github.com/nylas/N1/releases/tag/0.4.45, but that may or may not help.
