### ISSUE TITLE
QQ exmail provider setup issue

### ISSUE THREAD

**Issue by buhe** [nylas/N1#2656]
##### What operating system are you using?
mac os

##### What version of N1 are you using?
0.4.45-7637265 (0.4.45-7637265)
--

**Bug?**
##### Do you have any third-party plugins installed?
none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
https://exmail.qq.com/

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://cloud.githubusercontent.com/assets/650753/17044575/de3a805e-4ff3-11e6-96e4-03de198ab5e8.png)

--
alert message is "No account with ID bklqb54jw8jlylg0j49y5llzh associated with application eco3rpsghu81xdc48t5qugwq7."

**Comment by buhe** [comment]
Awesome project , I got some error when setup my account with QQ exmail provider .
BTW, QQ exmail is famous in china.

**Comment by buhe** [comment]
I try remove account and recreate account .

**Comment by shiftcruncher** [comment]
I am having the same issue and cannot fix it.  I get the message "No account with ID cbzr4y1xjlg1bp9a0n4b60522 associated with application eco3rpsghu81xdc48t5qugwq7" no matter what password I type in.

I have upgraded to Nylas Pro and this is reflected in the billing dashboard.  I have tried uninstalling and re-installing.  Oddly, the free version works but Nylas Pro is what I am having trouble with.  I need the mail merge capabilities in Nylas Pro.

Nylas support is unresponsive.  I don't know what to do.  Please help me.
