### ISSUE TITLE
N1 is telling me that my Pro trial has expired-- thought this was was free open-source?

### ISSUE THREAD

**Issue by HammyHavoc** [nylas/N1#2657]
Hey all,

Apparently my mailboxes have been paused now that my N1 trial has expired-- any info on this? Clicking the link to builds from the readme on the repository takes me to download a free trial of N1, but there's no mention of free builds being available on there without compiling from source. Am I missing something? Also can't dismiss the turqoise banner, only option is to Check Again or Upgrade to Nylas Pro...

**Comment by 6220119** [comment]
https://nylas.com/blog/nylas-pro/

> ## Isn’t Nylas N1 free software?
> 
> Nylas N1 is open source free software. People in the open source community often explain free software as “free as in free speech, not free as in free beer.” In other words, open source free software is about liberty. It gives developers freedom to extend, modify, and share a program. Nylas N1 is GPL-licensed and free as in freedom.
> But right now, Nylas N1 is also free as in free beer, and that’s a problem. Due to its popularity, the API traffic for N1 users has dramatically eclipsed the combined volume of all other apps built on the Nylas Cloud APIs. We already sync several hundred terabytes of data for our users and are adding tens of thousands of new users each month. It’s costing us real dollars.
> 
> When we launched N1, we suspected this might happen someday, but we still released N1 as a free beta so developers could quickly try the app and give us feedback. We believe strongly in the mission of N1, so we foot the bill.
> 
> However, Nylas is a startup. We’re a small venture-funded company with the goal of creating a long-term sustainable business that fuels innovation for email. We have a ton of big ideas and are still in the early days. On a long-term horizon, we see a large risk in continuing to subsidize the “free beer” version of N1. Companies like Mailbox did this and were forced to sell or shut down before finding a real business model (and before finishing the product they started). There are zero examples of sustainable email startups without a paid product. The beer unfortunately always runs out.

**Comment by HammyHavoc** [comment]
Completely understand that, and well aware of the concept of libre software stemming from GNU.

When https://nylas.com/pricing/ tells me it doesn't cost anything for developers then that leaves me feeling confused. I'm looking to commit to an open-source email client and build some useful plugins and features for it, including mobile apps, but it's looking like I'll have to continue my search elsewhere.

Aware that Nylas offers a sync engine, but this doesn't seem to have all the features that Pro does. Wouldn't mind paying a few dollars for a permanent license of the server-side software so I can self-host it, or for every major release just to keep things ticking over. Not looking for a company to sync all my emails to their servers, looking for a company committed to building a worthwhile email solution that doesn't renege on what they set out to do after people adopt it.

It's a pity, because whilst I love N1, and the touch-screen support is great, it's starting to go down a road that I'm not comfortable with ongoing fees. We already have mail servers, no need to sync it elsewhere.

**Comment by jackiehluo** [comment]
We appreciate the feedback! The reason we use the sync engine at all is that there are a lot of features we have built and will be building that require a server-side component. That's also why a subscription is necessary. We get that that's not going to be for everyone—we just want to make sure that we don't land in the long list of email clients that have been acquired/killed, and that means trying something different.

**Comment by danbovey** [comment]
Do you know of anyone running a fork that runs without the server-side component? I don't think I use any of the features that would require a subscription. Snoozing, read receipts, link tracking, send later - I may just be really uninformed but does the foundation of using N1 as a Gmail client not require any server-side component and most of the extras/plugins do. I just want a nice looking desktop client 😃

**Comment by yokodev** [comment]
@danbovey I'm exactly at the same point, just need a descent looking client(Linux for me) that the community can start working on, I'm definitively getting involve in this in the near future.

**Comment by SeAlgoAsoma** [comment]
I'm with you guys, I was about to open my own issue over getting rid of the server-side requirement. Not only don't I need or want it, it makes it impossible for me to even evaluate N1. I'm not processing my email through a third party, period (and I'm certainly not running my own server.) Makes the entire project useless to me.

**Comment by ArchangeGabriel** [comment]
The new free version looks good. Waiting to see more, but maybe the server part is close to be optional (at the cost of least features obviously) now. At least it’s not used for mail syncing anymore apparently.
