### ISSUE TITLE
system try can't find Nylas Icon on Neon Linux distro.

### ISSUE THREAD

**Issue by RomuloPBenedetti** [nylas/N1#2668]
##### Are there any related issues?
maybe  #901 is related

##### What operating system are you using?
Linux Neon, a KDE distro

##### What version of N1 are you using?
0.4.45-7637265

system try can't find Nylas Icon.

![spectacle mn9521](https://cloud.githubusercontent.com/assets/12467382/17096328/231dba64-522f-11e6-89c7-9102e6b4f77f.png)

##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?
noticed after first install of this version on the system

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
no

**Comment by bengotow** [comment]
You may have to go into N1's preferences and enable the system tray icon, but it's also quite possible this is an issue with this linux distro.

**Comment by RomuloPBenedetti** [comment]
Unfortunately it is active, I believe you're correct, as by what I can see this is not Nylas icon too...
![spectacle dt7247](https://cloud.githubusercontent.com/assets/12467382/17189274/27a6334c-5417-11e6-987c-4022eccb7ba3.png)

**Comment by RomuloPBenedetti** [comment]
Ok it appears not correct:

    $ echo $XDG_DATA_DIRS                                                                                                                                                    
    /usr/share//usr/share/xsessions/plasma:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop

**Comment by jackiehluo** [comment]
Closing this issue since it looks an issue with this specific version!
