### ISSUE TITLE
Account setup window out of reach

### ISSUE THREAD

**Issue by Johnbpo** [nylas/N1#267]
Hello hello,

So here's my issue:

On windows 10, when launching the app for the first time,
The account setup window is out of bound and there is no way to move
or resize it.
I tried restarting the app and entering my invitation code again but it's the same.

![n1_issue-compressor](https://cloud.githubusercontent.com/assets/4398512/10815995/d120e7f0-7e2f-11e5-9f59-df708d6bb6fb.png)

Thanks for looking into it :)

**Comment by bengotow** [comment]
Hi @Johnbpo — can you try downloading the very latest version from https://edgehill.nylas.com/download?platform=win32 and let me know if that resolves the issue for you? We had this problem last week but it /should/ have been fixed in release `0.3.19`.

**Comment by Johnbpo** [comment]
Hi @bengotow , I just did and it works just fine...
Sorry for the bother. I haven't been following the repo actively, so I missed the fix.
I hope there will be an update system soon..

Thank you for your time.
