### ISSUE TITLE
N1 doesn't parse URLs with ?# correctly

### ISSUE THREAD

**Issue by khamidou** [nylas/N1#2670]
For example:

<img width="774" alt="capture d ecran 2016-07-25 a 11 53 15" src="https://cloud.githubusercontent.com/assets/44081/17097528/6c5106b2-525e-11e6-996c-fc03688d8d30.png">

**Comment by sahildua2305** [comment]
@khamidou Can you please provide some pointer to where the issue may be, so that I can take it up as my first contribution?

**Comment by albertocg** [comment]
This change seems to solve it #2827 by adding '#' to the characters allowed after '?' in the URL components.

**Comment by jstejada** [comment]
The fix for this has been released today!
