### ISSUE TITLE
Question: using OSS sync engine

### ISSUE THREAD

**Issue by rstacruz** [nylas/N1#2677]
> If you want to point N1 to your self-hosted sync engine, select "Hosting your own sync engine?" under the "Get Started" button on the welcome screen.

If I'm already way past that (I got Nylas N1 already set up), how can I set up my own sync engine?

**Comment by jackiehluo** [comment]
You're going to need to delete your ~/.nylas/ directory and start fresh—your setup's authenticated against our sync engine, but when you set up your own, you need to add your email accounts to your instance of the sync engine and then link N1 to those accounts! The instructions for setup are in the onboarding flow.

**Comment by bengotow** [comment]
Also worth mentioning that we're shipping an update to the app tomorrow which adds a "Reset" button to the prefs. Will make this easier!
