### ISSUE TITLE
Allow HTTPS addresses for self-hosted onboarding

### ISSUE THREAD

**Issue by ConorIA** [nylas/N1#2681]
Currently the self-hosted onboarding interface has 'fill in the blanks' for domain and port. The protocol defaults to HTTP. I use a simple nginx server to direct https requests on a custom port to the server localhost:5555.

**Comment by audibleblink** [comment]
:+1: 

Even manually changing the `config.json` to `https:` reverts back to http after restarting the client.

For now, I'm just creating an ssh local tunnel with `ssh -L 5555:localhost:5555 $SYNCENGINE` then pointing N1 to `localhost:5555` on the client machine.

**Comment by rgruyters** [comment]
Agree, why can't we use https for self-hosted environments.

**Comment by jackiehluo** [comment]
We've pushed an update that resolves this issue (0.4.51). Let us know if you run into any bugs!
