### ISSUE TITLE
CoffeeScript in, ES6 out http://decaffeinate-project.org/repl

### ISSUE THREAD

**Issue by roughsoft** [nylas/N1#2682]
CoffeeScript in, ES6 out http://decaffeinate-project.org/repl

**Comment by roughsoft** [comment]
some code is es6,some code coffee script.
you can try the tools:
http://decaffeinate-project.org/repl 
every code is es6.

**Comment by jackiehluo** [comment]
Hey! We've tried it, but unfortunately it doesn't work well for us—we're trying to convert the code more slowly so that we don't introduce more bugs in the process. Thank you for the suggestion!
