### ISSUE TITLE
Signature layout is broken on larger signatures

### ISSUE THREAD

**Issue by JeroenBoersma** [nylas/N1#2683]
The new signature system breaks layout on larger signatures, the input will not expand or overflow.

- Operating system: Ubuntu 16.04
- Nylas version 0.4.47-3a2a94c

Screenshot

![screenshot from 2016-07-29 10-39-14](https://cloud.githubusercontent.com/assets/1163348/17242688/bf1dca34-5578-11e6-965a-2ca5249f6de5.png)

**Comment by bengotow** [comment]
Oh man that's a good one. Thanks for reporting this! Fixed in 5254589e5ee830ff84623c43c9cf4234f2c2bbc4.

**Comment by JeroenBoersma** [comment]
Would be awesome though if I could use more of the screen, my screen for example is 1080px in height and it the textarea only covers 25% of the screen.

**Comment by jackiehluo** [comment]
We've pushed an update that resolves this issue (0.4.51). Let us know if you run into any bugs!

**Comment by JeroenBoersma** [comment]
It's fixed! Thank you...
