### ISSUE TITLE
Settings window is very difficult to find

### ISSUE THREAD

**Issue by multiwebinc** [nylas/N1#2685]
It took me 4-5 minutes (including a Google search) just to find how to get to the settings. The UI should include some sort of button to open the settings dialog. Having to click on the little down arrow beside an account and then "manage accounts" to get to the settings is absurd (unless there's another way to do it, that I don't even know about).

**Comment by jackiehluo** [comment]
@multiwebinc Which OS are you running? You should be able to access the preferences through the menu bar!

**Comment by multiwebinc** [comment]
Ubuntu 14.04 64 bit.

Erm... menu bar? I don't have a menu bar and none of the [screenshots](https://www.google.com/search?q=nylas+n1+screenshots&biw=1920&bih=910&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjfw9O81pnOAhUCkx4KHV8sB_kQ_AUIBigB&dpr=1) I found seem to have one either.

**Comment by hallamoore** [comment]
The Linux version has a menu bar, but it's hidden until your mouse hovers over it. Just like for any other application on Linux! The settings are under Edit > Preferences. Hope this helps!

**Comment by hallamoore** [comment]
I'm going to go ahead and close this issue and #2686 for now. You may want to check out #1250, which requests a "hamburger" style menu instead. Feel free to add a comment there if you agree!

**Comment by multiwebinc** [comment]
@hallamoore Correction, I'm using Kubuntu, not Ubuntu. KDE doesn't have the hidden menu bar at the top of the screen like Gnome does.

**Comment by hallamoore** [comment]
Oh, interesting! Let me look into that a bit.

**Comment by hallamoore** [comment]
Do other applications, like internet browsers, have menu bars when running with KDE?

**Comment by multiwebinc** [comment]
@hallamoore Yes, depending on the application. Sometimes it has some sort of menu button with all the options.

**Comment by multiwebinc** [comment]
I'm not sure if this is related, but in the compose window I don't see any way to do more formatting than just bold, italic, underline and link.

**Comment by hallamoore** [comment]
No, that's not related, that's just all the formatting we currently support. See #1087.

So it seems that we're just not integrated enough to fully support running on KDE right now. I've created an issue for it, #2687, but we don't have much of a user base on KDE, so it might take awhile to get to. We do accept pull requests though, if you're interested in contributing!

**Comment by jezcope** [comment]
This baffled me for ages! I'm running Gnome 3 and there is no way of getting the menu bar to appear by hovering the mouse over the title bar or any other UI element. I'd just been assuming that there *was* no menu until I saw this thread, at which point I tried pressing `Alt` and finally found it.

It sounds like there are some assumptions about which desktop environment/window manager users are using which aren't borne out by reality. Let me know how I can help!

**Comment by multiwebinc** [comment]
@jezcope Try posting in https://github.com/nylas/nylas-mail/issues/2687. This issue has been closed.

**Comment by RTbecard** [comment]
I'm using elementary OS, ran into the same issue.  Most apps don't have a menu bar, but those that do always have it visible by default in my experience (or at least to my awareness).

follwing @jezcope, I can verify that Alt unhides it for me... I would have never discovered this otherwise!  Perhaps this should be made more clear in the app?
