### ISSUE TITLE
Add an "About" page

### ISSUE THREAD

**Issue by multiwebinc** [nylas/N1#2686]
This app needs an "About" page that details the version installed and any other relevant information. If it has one, I can't find it.

**Comment by jackiehluo** [comment]
Which OS are you running? You should see this:
<img width="217" alt="screen shot 2016-07-29 at 3 00 55 pm" src="https://cloud.githubusercontent.com/assets/8452682/17264650/4be0b17e-559d-11e6-970d-321876292145.png">

**Comment by hallamoore** [comment]
I don't think the Linux one has an about menu item, but you can see the version under the help menu.

**Comment by multiwebinc** [comment]
Running Ubuntu 14.04 64 bit. I don't have a menu bar or a "help menu"

![nylas2](https://cloud.githubusercontent.com/assets/901732/17264834/1162dc84-55a7-11e6-903f-3f1f38776c4a.png)

**Comment by hallamoore** [comment]
What happens if you hover over the top bar, where the menu bars would normally be?

**Comment by hallamoore** [comment]
Merging into #2687
