### ISSUE TITLE
Reply button and draft icon get broken when replying

### ISSUE THREAD

**Issue by miguelmich** [nylas/N1#2688]
##### What operating system are you using?
Linux Elementary OS Freya (Ubuntu 14.04)

##### What version of N1 are you using?
0.4.45

##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins installed

##### Is the issue reproducible with a particular attachment, message, signature, etc?
This is happening when I click on reply icon, see the screenshot:
![image](https://cloud.githubusercontent.com/assets/662930/17265670/6c0c6e84-55b6-11e6-9d9e-65f00389ea8c.png)

**Comment by jackiehluo** [comment]
Could you send a full screenshot? That might help. You can go to Developer -> Toggle Screenshot Mode to obscure the information in the app!

**Comment by miguelmich** [comment]
@jackiehluo nothing happens on the screen when I click on 'Toggle Screenshot Mode' it keeps showing all the information. This is a full screenshot:

![image](https://cloud.githubusercontent.com/assets/662930/17266035/b3ffef10-55b9-11e6-81be-fac0a0a0e562.png)

**Comment by jackiehluo** [comment]
Oh, strange... if you go to Developer -> Toggle Developer Tools, do you see any errors? There should be an icon there. Looks like you're also missing the draft icon in the message list.

**Comment by miguelmich** [comment]
Yes I have some errors:

- (node:2838) Warning: Possible EventEmitter memory leak detected. 51 trigger listeners added. Use emitter.setMaxListeners() to increase limit
- Uncaught (in promise) DOMException: Failed to load because no supported source was found.
- refused to load the script 'https://static.hsstatic.net/jquery-libs/static-1.1/jquery/jquery-1.7.1.js' because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension://react-developer-tools".
- Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension://react-developer-tools". Either the 'unsafe-inline' keyword, a hash ('sha256-k5V18IHw6qDzgEuDSFX3gsU8dyU+vTFvgjcNA6ZkIu8='), or a nonce ('nonce-...') is required to enable inline execution.
- Refused to load the script 'https://static.hsstatic.net/content_shared_assets/static-1.4020/js/public_common.js' because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension://react-developer-tools".
- Uncaught (in promise) DOMException: Failed to load because no supported source was found.

And multiple warnings about this font:
- Failed to decode downloaded font: nylas://screenshot-mode/assets/BLOKKNeue-Regular.otf

**Comment by miguelmich** [comment]
It seems to work good now, I don't know what happened but it suddenly stopped this issue.
