### ISSUE TITLE
URLs should automatically be parsed as links

### ISSUE THREAD

**Issue by multiwebinc** [nylas/N1#2689]
When sending an email that contains a URL in the message (not in the quoted message, but in the part being typed) this should automatically be parsed into an anchor tag (like `<a href="{{url}}">{{url}}</a>`) so that the recipient just has to click on the link.

**Comment by jackiehluo** [comment]
Merging into #2166!

**Comment by multiwebinc** [comment]
@jackiehluo It's similar, but not an exact duplicate. #2166 is talking about converting to link when pasting text, I'm talking more about when the email gets sent (like what Gmail and Thunderbird do).

**Comment by jackiehluo** [comment]
I think we can treat it as the same! Just linkifying any URLs in an email, whether that's on paste or on send.

**Comment by multiwebinc** [comment]
I think the difference is more along the lines of *when* the link is added. One is done when the message is being typed (i.e. when text is pasted into the message) and the other is done after the user clicks on the "Send" button.
