### ISSUE TITLE
Unresolved dependency: libgcrypt11

### ISSUE THREAD

**Issue by pankovseryi** [nylas/N1#269]
Attempting to install over a message:

```
Unresolved dependency: libgcrypt11
```

OS: Ubuntu 15.10

**Comment by larfadin** [comment]
same issue here on ubuntu 15.10 too.

**Comment by bengotow** [comment]
Hey folks—unfortunately, this is an issue with all apps that use Chromium on Ubuntu 15.10. It should be fixed soon, but in the meantime you may need to install libgcrypt11 manually.

**Comment by bengotow** [comment]
Closing as a dup of https://github.com/nylas/N1/issues/259

**Comment by pankovseryi** [comment]
Thanks man.
Setting dependencies manually solved the problem:)
