### ISSUE TITLE
How to disable signature completely?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2690]
Dear all, 

While I want to actively promote N1 to friends, I dislike that I cannot disable the default signature that is added to each email.

How can I completely disable the use of a signature?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17278248/cf7f3868-5758-11e6-8722-5cd89d659699.png)

![image](https://cloud.githubusercontent.com/assets/170947/17278247/c8e24770-5758-11e6-9d5c-382aabb262a8.png)

**Comment by yang-s-li** [comment]
You just need to create a new signature to replace the default one.

**Comment by orschiro** [comment]
Thank you! 

I just created an empty signature and made it the new default. 

That solved my problem. :-)

~Robert

**Comment by yang-s-li** [comment]
You are welcome.

**Comment by hallamoore** [comment]
Glad this was resolved!

**Comment by mazondo** [comment]
This took a bit to figure out, would be great if it was documented somewhere in the settings.

I talk you guys up quite a bit, just don't want to do so via email :)

**Comment by julienvincent** [comment]
This behavior is a bit weird. There should be a way to remove a signature without this _hacky_ method of creating a blank one.

**Comment by jackiehluo** [comment]
Yep, it's on our list of items to fix!

**Comment by julienvincent** [comment]
awesome 👍

**Comment by thearb** [comment]
This doesn't seem to have been fixed
