### ISSUE TITLE
Bug: Emails not being marked as 'read'

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2693]
I have a screen video capture (3.3mb mp4) but cannot upload into this GitHub issue. So tell me where I can upload it.

I normally have mark read after 1/2 second but switch to instant to test and the same problem exists.

##### What operating system are you using?
Windows 10 1511 (build 10586.494)

##### What version of N1 are you using?
0.4.47

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Noting extra

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
gmail

**Comment by jackiehluo** [comment]
Merging into #1298!
