### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by sirinath** [nylas/N1#27]
With GPL based license many of the extensions become also GPL. In the spirit of extension is it possible to add an exception or better still adopt a license like ASL 2.0.

**Comment by gardner** [comment]
Good point @sirinath. Joomla decided that the GPL ethos was most important for the community. You can read more here: https://docs.joomla.org/Extensions_and_GPL

According to the GNU GPL FAQ, Nylas extensions would fall under GPL requirements. You can read more here https://www.gnu.org/licenses/gpl-faq.en.html#GPLAndPlugins

It seems like something for Nylas to decide.

**Comment by bengotow** [comment]
Hey folks—thanks for bringing this up. We'll talk about this internally and figure out the best way to go. We would definitely like to allow closed-source or alternatively licensed plugins on top of N1 in the future, so we'll find a way to make that possible.

**Comment by dillonforrest** [comment]
Hey everybody, thanks for chiming in! In the interest of prioritization, I'm closing this issue for now. It might be a while before we make a decision about the license. When we do however, we'll revisit this issue!
