### ISSUE TITLE
Symantec classifying windows installer as malware

### ISSUE THREAD

**Issue by ainstushar** [nylas/N1#270]
I recently got a beta code and downloaded the installer for windows. Symantec quarantined the file because it thinks this app is malware. 

Details below:

````
Version 0.3.20
WS.Repuation.1
Hash: 7A45F88091FDC612CEC06734E0637468775AB70DADCBFA86B30F540A0E7C5626
There is strong evidence that this file is untrustworthy.
This file has been seen by fewer than 5 Symantec users.
````
Maybe look into this?

Thanks.

**Comment by bengotow** [comment]
Hey @ainstushar —thanks for reporting this. We got a Digicert Windows Authenticode certificate and the app is signed, but the installer may not be. I'll double check and see if there's anything else we can do—it seems Symantec doesn't have a simple process for resolving these sort of warnings..

**Comment by bengotow** [comment]
Just a quick update. I verified that our installer is signed with our DigiCert Authenticode certificate. Unfortunately, I'm not sure what else we can do to make Symantec happy. Any ideas?

![image](https://cloud.githubusercontent.com/assets/1037212/10829201/e26ce5bc-7e35-11e5-8ea7-10cd5747240b.png)

**Comment by ainstushar** [comment]
No idea. Just reporting this because it popped up on my end. Maybe its popping up because of heuristic? Its complaining that only 5 other people have it?

Is there a way to email them to find out?

-----Original Message-----

**Comment by alainlecluse** [comment]
Same Here, just that it now says 50 people
![image](https://cloud.githubusercontent.com/assets/11518942/10999504/a8251aa6-849c-11e5-9524-dc21c0463fec.png)

**Comment by grinich** [comment]
This should be fixed now! Please re-open if you have steps to reproduce.
