### ISSUE TITLE
Searches based on label is not working for Gmail accounts

### ISSUE THREAD

**Issue by thiruthink** [nylas/N1#2700]
##### Are there any related issues?
...did search here but no reference found

##### What operating system are you using?
...mac

##### What version of N1 are you using?
...Version 0.4.47-3a2a94c (0.4.47-3a2a94c)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...NA

--

I have multiple gmail accounts and when i search for 'label:inbox label:unread' it used to show all unread message in inbox in all account. 'label:unread' this would show all unread messages irrespective of label. This is not working any more.. whenever I do this search it doesn't show any message even though i have lot of unread messaged..

**Comment by arifb** [comment]
+1

label/advanced search, just like gmail (https://support.google.com/mail/answer/7190?hl=en), used to work great. Now I get 0 results

**Comment by stefaniwhylie** [comment]
Same for me.  I don't know that I've ever gotten it to work actually.  No third-party plugins.  

Right now I switch to gmail on the web to search, but I'd like to not have to do that. 

Version 0.4.47-3a2a94c  OSX 10.11.13

**Comment by jstejada** [comment]
Hi all, going to merge this into #750 . Currently investigating a fix
