### ISSUE TITLE
Auto mark read disable option

### ISSUE THREAD

**Issue by J-C-B** [nylas/N1#2701]
# Auto "mark as read" disable option
Hi, loving the app, but marking as read as soon as an email is touched breaks my work flow / to do list

Can a toggle be added to prevent the auto mark as read function?

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
Yes - Outlook

**Comment by jackiehluo** [comment]
@J-C-B That is a feature! If you go to Preferences -> General.

**Comment by J-C-B** [comment]
I'm so sorry - i was "that guy" - i did look but missed it, thanks so much

**Comment by jackiehluo** [comment]
Of course! 🎉

**Comment by J-C-B** [comment]
While i have you - is there a way not to have conversation view?

**Comment by jackiehluo** [comment]
@J-C-B No, there isn't!

**Comment by J-C-B** [comment]
ok, many thanks again!
