### ISSUE TITLE
Feature request: show unread messages in all folders.

### ISSUE THREAD

**Issue by albireox** [nylas/N1#2703]
##### What operating system are you using?

Mac OSX 10.11.6 on a MacBook Pro Retina.

##### What version of N1 are you using?

Version 0.4.47-3a2a94c (0.4.47-3a2a94c)

--

**Feature Request?**

I would like to be able to see the unread messages in a particular folder. Right now, it seems the unread folder on the sidebar only shoes unread messages in the inboxes. Either Unread should show unread messages for all labels or should be possible to filter by unread messages in each folder.

##### Does this feature exist in another mail client or tool you use?

Yes, Airmail has something on those lines.

**Comment by jackiehluo** [comment]
Merging into #2110.
