### ISSUE TITLE
Nylas N1 never starts up

### ISSUE THREAD

**Issue by vp2177** [nylas/N1#2713]
Using OS X El Capitan.
Installed Nylas N1, added a Gmail account, authorised it in the popup, then Nylas displays a splash screen that it's starting, but never actually goes further.

Uninstalled.

##### What operating system are you using?
MacOS X El Capitan

##### What version of N1 are you using?
latest

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
-

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail (potentially)

**Comment by jackiehluo** [comment]
Closing this issue for now—for any user-specific issues, email us at support@nylas.com!
