### ISSUE TITLE
"Mail could not be sent" error

### ISSUE THREAD

**Issue by grinich** [nylas/N1#2715]
Don't have any other details. I try to re-send and it works that time. We can do better than this and just retry under the hood once.

![image](https://cloud.githubusercontent.com/assets/92417/17527145/02c89d14-5e1f-11e6-945c-7ca83a34fcd0.png)

**Comment by jackiehluo** [comment]
Merging into #1782!

**Comment by grinich** [comment]
Agh sorry. Tried to search and didn't see the existing issue. :/

**Comment by jackiehluo** [comment]
Hahaha, it's fine. Search is awful, but I'm developing pretty much a photographic memory for GitHub issues.
