### ISSUE TITLE
Slow internet connection: cannot compose new message

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2718]
Dear all,

When connected to a very slow internet connection, the compose window doesn't open when clicking on the compose new message button, nor when pressing keyboard shortcut `c`.

Is this an obstacle with the offline mode?

Thankfully,

~Robert

**Comment by jackiehluo** [comment]
I don't think slow internet connection is related—let us know if you see it again!

**Comment by orschiro** [comment]
HI Jackie, 

I will get back to you if I see the error again!

Thanks,

-Robert
