### ISSUE TITLE
Won't sync my mail

### ISSUE THREAD

**Issue by sean-hill** [nylas/N1#272]
I'm just stuck with this, no mail is syncing!

![screen shot 2015-10-29 at 6 13 04 am](https://cloud.githubusercontent.com/assets/1205866/10819327/9e32f386-7e04-11e5-8e3d-66ff4ab84a2a.png)

**Comment by sean-hill** [comment]
After quitting and opening the application everything was resolved.

**Comment by napcae** [comment]
Please close the issue, if it is resolved.

**Comment by sean-hill** [comment]
Well it resolved itself when I quit and reboot the application, it'd be nice for it to work right after initial setup.

**Comment by strumpet** [comment]
I have the same issue and it hasn't gone away after restarting the application.  I used the 'ship detailed logs to nylas' feature but not sure what you need from me to be able to match those logs back to me...

**Comment by lucasmazza** [comment]
Had the same issue, but after restarting the app Nylas synced my Gmail labels but it didn't displayed any of my existing emails - only new emails appeared in the UI.

**Comment by strumpet** [comment]
After two more restarts some emails came in but after turning off the Gmail 'important' tagging the inbox only showed non-important emails and most labels were empty.  Tried using an Outlook account and it showed same sync error messages so I gave up and uninstalled. Will try again in a few months and see if things have improved.

**Comment by tyhatch** [comment]
Having the same issue, with two accounts. Eventually it gives up and just gives me an empty inbox. Could it be related to the amount of data syncing in an account?

**Comment by Lordgoderic** [comment]
I'm also unable to sync my gmail account.  I would assume your servers are overloaded since it seams as though you just pushed out a bunch of invites?

**Comment by pdeast** [comment]
Having the same issue. Syncing is really slow. Maybe a message every minute in the inbox for 2 different accounts.

**Comment by dougc84** [comment]
Same.

**Comment by peryn** [comment]
+++

**Comment by MatthewDailey** [comment]
+1

**Comment by ackl** [comment]
+1

**Comment by kyriacos** [comment]
Same issue it only shows new emails. Any workaround?

**Comment by qbunt** [comment]
+1 Only on 1st run.

**Comment by megraf** [comment]
Same issue, exchange, outlook, and custom smtp is all failing.

**Comment by stuartbrownstanbury** [comment]
Similar issue, after installing won't sync at all. No emails are shown, only labels sync. Tried restart of app, rebooting machine, unlinking and relinking gmail. Still no e-mails show. Windows ver 0.3.20

**Comment by bengotow** [comment]
Hi folks—unfortunately, we've been experiencing degraded sync performance due to a ton of new users that connected to N1 today. When you log in for the first time, it may take longer than usual for threads to begin appearing. 

N1 holds a streaming connection to the sync engine and is sent mailbox changes as soon as they're received. It should be really snappy once the current load issue is resolved. You can follow the issue here: status.nylas.com.
