### ISSUE TITLE
Plugin Failed to Install - Users reporting same error

### ISSUE THREAD

**Issue by KyleKing** [nylas/N1#2723]
##### Are there any related issues?

No related issues that I could find

##### What operating system are you using?

OSX El Capitan

##### What version of N1 are you using?

v0.4.47

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

Nope, only the one that I can't install

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

N/A

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Anytime you install https://github.com/colinking/n1-unsubscribe/releases/tag/1.5.5

I checked the logs and console and there is no output. There were errors initially, but I've fixed anything that popped up initially. Is there a time-out or other issue that is causing the install error? If I run `npm install` (or `apm install`) in my directory first, then install through the Nylas GUI, the plugin installs correctly, but without the pre-step, the Nylas GUI install fails When it fails to install, Nylas deactivates the package. After reloading and simply reactivating the package everything works.

Where is the apm install stdout logged to?

**Comment by emorikawa** [comment]
@KyleKing In dev mode, it should log to the terminal window you launched N1 from. On the Mac, it should also output to the Mac Console app.

**Comment by KyleKing** [comment]
Hi @emorikawa, I went through the logs and fixed two minor warnings, but I'm still getting the same "failed to install error" with no other description

**Comment by KyleKing** [comment]
The plugin is silently failing when installing all of our dev dependencies. I did a dry-run where I [removed all of the dev-dependencies](https://github.com/colinking/n1-unsubscribe/commit/50195d99442540c233b9054726b5ddf15a2aa6dc) from the package.json and the package installs smoothly. Adding the dev-dependencies back to the package.json causes the same install failure. If you want you can try it out:

[n1-unsubscribe.zip - the one without dev-dependencies that installs smoothly](https://github.com/colinking/n1-unsubscribe/files/426762/n1-unsubscribe.zip)

[n1-unsubscribe.zip - the one with dev-dependencies which fails](https://github.com/nylas/N1/files/426772/n1-unsubscribe.zip)

I think all you need to do to fix the error is to [add the `--upgrade` flag to apm install](https://github.com/atom/apm/commit/47840f9e0546aadf5389b4b4996fa85d354c5eca) [at [apm-wrapper.coffee - line 222](https://github.com/nylas/N1/blob/324296eb1ca562f21acec0efc7bd9a5337099532/src/apm-wrapper.coffee#L222)], which basically runs` npm install --production`. I submitted a PR that should work, but I'd appreciate your help testing since I don't know how to build N1 from source.

**Comment by bengotow** [comment]
This should be resolved by the PR above being merged!
