### ISSUE TITLE
Improve first name parser / don't show honorifics or name prefixes / Remove "mr, ms, dr, prof, etc"

### ISSUE THREAD

**Issue by chr-br** [nylas/N1#2726]
When viewing a message, if the from/to field is unexpanded, what should show is the first names of all the senders/recipients. But if that person has a title (Mr., Dr., Prof., etc.) it is the title which shows up. 

Here are some images:

![title2](https://cloud.githubusercontent.com/assets/2973412/17634372/4ecfc8d0-60a0-11e6-9aa8-9135c294e871.png)
![title1](https://cloud.githubusercontent.com/assets/2973412/17634373/4ee6aad2-60a0-11e6-85a4-cae342e481f3.png)

As you can see, this functionality is not useful, since I can't actually see who's emailed me without expanding it.

**Comment by CodeBytere** [comment]
@emorikawa @chr-br --> https://github.com/nylas/N1/pull/2732
