### ISSUE TITLE
Navigation buttons previous/next message?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2727]
Dear all, 

What do you think of a way to navigate between the previous, current and next message of a conversation thread?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17642429/17adef4c-6147-11e6-997f-182289ebaf28.png)

**Comment by emorikawa** [comment]
We may add UI elements in addition to keyboard shortcuts. I'm going to merge this request in with: https://github.com/nylas/N1/issues/830 for now.

**Comment by orschiro** [comment]
Great, thanks Evan for the reference! :smiley: 

~Robert
