### ISSUE TITLE
losing Nylas N1 authentication with zimbra server sporadically

### ISSUE THREAD

**Issue by Bergg** [nylas/N1#2728]
##### What operating system are you using?
Fedora 24

##### What version of N1 are you using?
N1-0.4.47.rpm

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Zimbra email server through imap/smtp

##### Does this feature exist in another mail client or tool you use?
other clients with imap/smtp work fine

Every other day I get the message "Nylas N1 can no longer authenticate with **@**.**.** Click here to reconnect" after which I have to re-enter the imap/smtp names again for the zimbra server, user name, passswords etc...

**Comment by jackiehluo** [comment]
Could you email us at support@nylas.com? Much easier to debug issues like this one with more specific information about your account!

**Comment by diazgilberto** [comment]
Same here!!

**Comment by Bergg** [comment]
Not sure why this issue got closed @jackiehluo ? I sent my server information but was any action  taken?  I just had the glitch again.

**Comment by Bergg** [comment]
The bug still happens but the message has changed. Now it is "cannot authenticate with ..@.." with the options "check again" (didn't work) or "reconnect" (a pain in the neck every time again).
