### ISSUE TITLE
IMAP/SMTP Not working with Yandex Mail

### ISSUE THREAD

**Issue by allprojectxyz** [nylas/N1#2729]
I add new account with IMAP/SMTP with yandex mail:
IMAP setting: 
- Server: imap.yandex.com
- Connection security — SSL
- Port: 993.
SMTP setting:
- Server: smtp.yandex.com
- Connection security — SSL
- Port: 465.
But i seen error: Please check that your SMTP settings are correct.
This is Log:
{"message":"Please check that your SMTP settings are correct.","type":"auth_error","error":"further_action_required"},"requestOptions":{"url":"https://api.nylas.com/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=6fss5djl1yne1765qxttppbji","method":"POST","json":true,"timeout":150000,"path":"/auth?client_id=eco3rpsghu81xdc48t5qugwq7&n1_id=6fss5djl1yne1765qxttppbji","body":{"provider":"imap","email":"admin@allprojectxyz.net","name":"Admin AllProjectxyz","settings":{"name":"Admin AllProjectxyz","type":"imap","email":"admin@allprojectxyz.net","password":"***********","imap_port":993,"imap_password":"***********","smtp_port":465,"smtp_password":"***********","ssl_required":true,"imap_host":"imap.yandex.com","imap_username":"admin@allprojectxyz.net","smtp_host":"smtp.yandex.com","smtp_username":"admin@allprojectxyz.com","username":"admin@allprojectxyz.net"}},"returnsModel":false,"auth":{"user":"","pass":"","sendImmediately":true},"startTime":1471262048119},"statusCode":404,"name":"APIError","message":"Please check that your SMTP settings are correct.","errorTitle":"further_action_required"}}
{"host":"allproject-X401A1","timestamp":"2016-08-15T11:54:14.727Z","payload":["ActionBridge: onboarding Action Bridge Broadcasting: recordUserEvent"]}

**Comment by jackiehluo** [comment]
Shoot us an email at support@nylas.com! We can't debug without more account information.
