### ISSUE TITLE
Link Tracking Causing Issues -- Domain Incorrect

### ISSUE THREAD

**Issue by nicorellius** [nylas/N1#2731]
##### What operating system are you using?

Ubuntu 12.04
...

##### What version of N1 are you using?

0.4.47-3a2a94c
...

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

Markdown plugin installed, but it doesn't work... I don't think this is causing the issue.

The issue is that some co-workers are complaining that their email clients are flagging my mail as spam. Also, some tracking is incorrect. Someone reported this to me:

> It also still seems to be adding tracking data to your link, and doing it WRONG!! It's going to www.ps.com&r=c2v0ac5qdxn0qhbyb3rlb21lc29mdhdhcmuuy29t, which doesn't work (Chrome tells me DNS lookup failed).

I'm not sure where Nylas got www.ps.com, but that domain is not even in use AFAIK. It's for sale... Did I somehow enter that string somewhere and now Nylas is using it?

I see other tracking bits, eg:

https://link.nylas.com/link/pm7fwpwuwqm5mlplmf2ohzs
7/local-f4806124-b24f/0?redirect=http%3A%2F%2Fwww.proteomesoftware.com&r=c3Vwc
G9ydEBwcm90ZW9tZXNvZnR3YXJlLmNvbQ==

But these are correct. Is this just the link tracking in **Edit > Preferences > Plugins**? "Link Tracking" and "Open Tracking"?

...

**Comment by jackiehluo** [comment]
@nicorellius Could you explain further what you were intending to link and what happened on the recipient's side?

**Comment by nicorellius** [comment]
I wasn't linking anything (in particular). This is just how all my mail looks to colleagues (who use Thunderbird). I have an HTML link in my signature, but surely this will not cause what I'm seeing, would it?

**Comment by jackiehluo** [comment]
Hm, I'm confused. You had to include a link for link tracking to happen, right? Or did it add the tracking data out of nowhere?

**Comment by nicorellius** [comment]
This is why I'm asking you. All I did was use N1. I have been using it for a couple months, and I've begun getting complaints that my mail is being interpreted and warned to be spam by other clients. Upon further examination, I discovered what I reported above. Nylas is including the link, not me... (I have no clue where the broken link I reported came from). Does Nylas track with the domain link.nylas.com? It looks to me like N1 is tracking links without telling its users...

**Comment by jackiehluo** [comment]
Got it! Link tracking on its own isn't a secret—it's just a feature we offer, and you can turn it off on an individual message by toggling the link tracking button in the composer toolbar or turning it off entirely in Preferences -> Plugins. But what you're mentioning specifically sounds like a bug! If you get any more information on broken links, let us know, and we'll look into it further.

**Comment by jackiehluo** [comment]
Merging into #2717!
