### ISSUE TITLE
Feature Request: Option to disable Unified Inbox

### ISSUE THREAD

**Issue by Bogidon** [nylas/N1#2734]
Could be done as part of #741/#1355 . If all accounts are muted, then disable Unified Inbox entirely. Otherwise just a checkbox to disable would be nice.

Trying to get a better work/life balance.

**Comment by jackiehluo** [comment]
@Bogidon You don't need to use unified inbox at all! You can use the account switcher (that dropdown arrow on the right of All Accounts) to just look at specific accounts.

**Comment by Bogidon** [comment]
@jackiehluo I was hoping to disable it completely since seeing all my unreads stresses me out. Even with the account switcher the Unified Inbox is still the default (⌘ + 1). Not high priority ¯\_(ツ)_/¯

**Comment by jackiehluo** [comment]
Ahhh, got it. And yeah—it's a pretty major change to add the ability to fully disable unified inbox, since so much of the app is built around that. But when you're in a specific account, the only count on the badge is the one for that account's unreads, right? If not, that sounds like a bug.

**Comment by Bogidon** [comment]
No bug – badge changes as expected. Figured it'd be a hassle, but maybe some day. Thanks for the help!

**Comment by Bogidon** [comment]
Found a workaround! I edited my keymap.json like so:
```json
{
	"window:select-account-1": "mod+1"
}
```

Thank goodness custom bindings override the base bindings. Now if only the account switcher dropdown could read from the resolved bindings... 😛
