### ISSUE TITLE
Export accounts and settings

### ISSUE THREAD

**Issue by xorinzor** [nylas/N1#2736]
##### Are there any related issues?
None that I could find

##### What operating system are you using?
Windows 10 x64

##### What version of N1 are you using?
0.4.47

--

How can I copy or export/import my accounts and settings to make nylas run on another computer of mine too without having to do each individual email account again?

**Comment by jackiehluo** [comment]
Merging into #2484, since it sounds like that's what you really want—right now, you can't easily export/import your accounts because we store account tokens in your system keychain.

**Comment by inuwashi** [comment]
+1
