### ISSUE TITLE
Change settings display for swipe and delete key actions

### ISSUE THREAD

**Issue by grinich** [nylas/N1#2739]
Our settings for behavior of the archive swipe action and usage of the delete key is really confusing right now.

![image](https://cloud.githubusercontent.com/assets/92417/17794285/e96e84a0-6562-11e6-946d-710c34b6e45b.png)

The line `Swipe gesture and backspace / delete move messages to trash` is such a confusing statement, made even more confusing by that slash.

We should change it to be more explicit. I also think we should separate the behavior of the delete key from what happens when you swipe the message, since it's not obviously how/why those two are connected.

I propose we change it to this:

![image](https://cloud.githubusercontent.com/assets/92417/17794256/a6b3a10e-6562-11e6-856f-1883183cd54d.png)

**Comment by emorikawa** [comment]
Yes. Much clearer. The broader issue is that we need to de-couple Backspace and Swipe-right actions. Doing that will fix this plus https://github.com/nylas/N1/issues/1833 and help with https://github.com/nylas/N1/issues/1448

**Comment by jackiehluo** [comment]
Merging into https://github.com/nylas/N1/issues/1833—the UI is super easy to fix once that logic is decoupled!
