### ISSUE TITLE
Inbox -> Drafts -> Inbox changes width of column

### ISSUE THREAD

**Issue by sean-hill** [nylas/N1#274]
In Split View, if you have it like this:

![screen shot 2015-10-29 at 7 54 28 am](https://cloud.githubusercontent.com/assets/1205866/10821995/55d89146-7e12-11e5-8bd3-d7f0bcb198bd.png)

And then click on the Drafts folder, then click back to Inbox it changes it to this:

![screen shot 2015-10-29 at 7 54 34 am](https://cloud.githubusercontent.com/assets/1205866/10822006/60bae4d8-7e12-11e5-8713-3f7e969ebcaa.png)

It should stay consistent.

**Comment by Zeklandia** [comment]
Issue #287 is the same problem, but more general.

**Comment by sean-hill** [comment]
Duplicate of #287.
