### ISSUE TITLE
N1 Webmail version

### ISSUE THREAD

**Issue by flavioeduardo** [nylas/N1#2745]
The version for Mac and Windows are great, but sometimes I'm not at my computer and I would love to can continue using Nylas N1 via webmail.
This option is also useful for those who can not or do not want to install the software on your computer or company computer.

**Comment by emorikawa** [comment]
@flavioeduardo I definitely hear you. Unfortunately we will likely not have a webmail version for a long time. We decided to focus on desktop-heavy and data-intensive use cases. As a result we make very active use of desktop features (your keychain, notifications, disk / database access, etc).
