### ISSUE TITLE
Nylas N1 can no longer authenticate withe example@example.com. Click here to reconnect.

### ISSUE THREAD

**Issue by eliasrodeloso** [nylas/N1#2746]
##### Are there any related issues?

Well, just one, is related, and happens the same!
https://github.com/nylas/N1/issues/2728

##### What operating system are you using?
Windows 10 Prop

##### What version of N1 are you using?
I'm using 0.4.49

**Bug?**
I'll say yes...

--
##### Do you have any third-party plugins installed? If so, which ones?
No, just have two themes.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so. Again: https://github.com/nylas/N1/issues/2728

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
Could you email us at support@nylas.com? We can investigate better with more information about your specific account!
