### ISSUE TITLE
Feature Request: Support 'send this later' -button

### ISSUE THREAD

**Issue by onnimonni** [nylas/N1#275]
Many people use http://www.boomeranggmail.com/ for sending messages later.

I mainly use this feature when I'm coding in the night and want to give reports to clients. It might be arguable but I feel it's more professional to have the mail send at 8:15 AM rather than 2:00 AM :smile:.

**Comment by bengotow** [comment]
Hi @onnimonni — thanks for filing this. Send later is definitely on the roadmap—if you've got a Trello account, feel free to upvote it here: https://trello.com/c/dd2q8otx/26-send-later-specific-date-time

**Comment by onnimonni** [comment]
Sorry I had missed that one on the trello!

**Comment by emorikawa** [comment]
Merged into #105

**Comment by jstejada** [comment]
this has landed in the latest release! enjoy!
