### ISSUE TITLE
Deleted threads in inbox?

### ISSUE THREAD

**Issue by elado** [nylas/N1#2750]
Mac OS X / Version 0.4.49-c9c04b7 (0.4.49-c9c04b7)  / Gmail

When I delete threads on a different client (such as Outlook for iOS), they still appear in my N1 inbox, as deleted, with this weird state:

![nylas_n1](https://cloud.githubusercontent.com/assets/51488/17865911/57ad34ae-6859-11e6-8f35-56002df8e839.png)

I guess it happens because N1 thinks only one message was deleted in the thread, but the thread contains only one message anyway.

**Comment by jackiehluo** [comment]
I think we're still investigating why that happens sometimes in our back-end—merging into #1729!
