### ISSUE TITLE
Link tracking changes redirect URLs

### ISSUE THREAD

**Issue by jackiehluo** [nylas/N1#2751]
>Here are the updated [$600 off ads](http://0b49njanxsvycu3lpbklnu3rjmnm%26r%3Dz2xlykbuewxhcy5jb20%3D/)
[Create 3D content ads](http://0b49njanxsvycvkn1anrtbnrvdjg%26r%3Dz2xlykbuewxhcy5jb20%3D/)

Links were supposed to go to a Google Drive doc with that ID. 😞

**Comment by hallamoore** [comment]
Closing due to inactivty, let us know if this should be reopened~
