### ISSUE TITLE
Clicking CC/BCC intermittently collapses fields before entering text

### ISSUE THREAD

**Issue by spetz83** [nylas/N1#2754]
##### What operating system are you using?
Windows 10 Pro

##### What version of N1 are you using?
0.4.49

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.
##### Is the issue reproducible with a particular attachment, message, signature, etc?

NA

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Basic email feature.

When I try to click on the CC or BCC section when composing a new email the To field collapses back down to the recipients list. I am never actually able to enter a CC or BCC. I also use N1 on Linux and this issue is not present there.

**Comment by jackiehluo** [comment]
@spetz83 Are you using the default Light theme?

**Comment by spetz83** [comment]
@jackiehluo Yes, I am.

**Comment by jackiehluo** [comment]
Another incidence: https://github.com/nylas/N1/issues/1955

@spetz83 Does CC/BCC never do anything when you click the buttons, or do you see them for a moment and then they collapse before you can enter content?

**Comment by spetz83** [comment]
So, I can see the BCC and CC buttons. As soon as I click on one of them they both disappear, but the text input for adding BCC or CC never actually appears.

**Comment by jackiehluo** [comment]
@khamidou just experienced this issue!

**Comment by bengotow** [comment]
This should be resolved by 01fc435a4af3d8bec9845875416cccfc3ce521af - there was a small bug in the focus management code in the key-commands-region that was causing things to become unfocused!

**Comment by rtx111** [comment]
Hi.... I cannot use CC or BCC either. I'm using OSX 10.10.5 using NYlas version  0.4.201
Clicking CC/BCC intermittently collapses fields before entering text #2754 @jackiehluo @spetz83  I see this issue was closed but I have not been able to resolve....is there something I need to do? thanks

**Comment by Laul** [comment]
Same problem there! 

More specifically:
- For new messages + previous e-mails that don't contains any Cc or Bcc: unable to see/add anything in Cc or BCc. 
- For previous e-mails: If I answer to a previous e-mail that already contains Cc or Bcc I've no problem to add some contacts in these fields.

Config:
- OS = apple sierra 10.12.2
- Nylas version: 1.0.15
- Accounts: Gmail (2 pure gmail + 1 google app)

Thanks !
