### ISSUE TITLE
Self-hosted sync engine doesn't work on 0.4.49

### ISSUE THREAD

**Issue by ebayer** [nylas/N1#2755]
Hello

With Self-hosted sync-engine and linux mint 17, N1 0.4.49 fresh install does not work for me, after the initial setup screen, account and folder list shows up but mail list bubbles keep moving and nothing happens. Also preferences window does not open too. if I uninstall 0.4.49 and remove ~/.nylas folder and install 0.4.47, everything starts working again.

Two accounts exists on sync-engine, one gmail and one imap, both seem to sync fine.

Kind Regards
Erdem Bayer

##### Are there any related issues?

...

##### What operating system are you using?
Linux mint 17

##### What version of N1 are you using?
0.4.49

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No, fresh install

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, both imap and gmail does not work

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No, no mail is visible

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by DAICHl** [comment]
The same issue happens on my side too. I need to use 0.4.47 to avoid it.

**Comment by Nipsi** [comment]
Same here on Arch Linux. Downgrade to 0.4.47 and it works again.

**Comment by ebayer** [comment]
Is there something I can provide (ie. some log file with a debug flag changed) so I can help you understand the problem?

**Comment by darrenkenny** [comment]
I'm seeing this exact issue - server-side it has the e-mails.

Client-side, I get e-mail notifications, and if I click on them I can read them, but the list of threads/e-mails is still bubbling...

**Comment by DAICHl** [comment]
The issue doesn't happen if "Open Tracking" plugin is disabled.

**Comment by jackiehluo** [comment]
Some more incidences: https://github.com/nylas/N1/issues/2760

**Comment by smcyr** [comment]
Adding "open-tracking" to "disabledPackages" section in the C:\Users\[..]\.nylas\config.json works for me too.

**Comment by sammarks** [comment]
Still doesn't work in 0.4.51. Can confirm adding `open-tracking` to the `disabledPackages` config resolves the issue.

**Comment by DAICHl** [comment]
Just upgraded to 0.4.51. It's also working with open tracking disabled.

@sammarks how about disabling all plugins?

**Comment by heroicyang** [comment]
@sammarks Try to add `link-tracking` to the `disabledPackages` config.

**Comment by bherila** [comment]
Is it possible to self-host link tracking?

**Comment by fxaguessy** [comment]
Same problem for me on 0.4.51 with self-host sync.
Disabling "Open Tracking" by adding ```"open-tracking"```to the ```disabledPackages``` in the configuration file has fixed it.

**Comment by Nipsi** [comment]
@fxaguessy are you able to send emails? When I try this "fix", the send button won't do anything.

**Comment by fxaguessy** [comment]
No, I realised after posting that I couldn't send emails, so I downgraded to 0.4.47 that is working properly...

**Comment by sammarks** [comment]
Still broken with 0.4.52. Disabling the `open-tracking` package fixes the inbox list and allows you to view emails, but the composer is still broken. Disabling `link-tracking` does nothing.

So in summary, on 0.4.52, disabling `open-tracking` will fix your inbox. I did some testing and in order to get the composer to work properly, you'll need to disable the following packages:

- Scheduler
- Mail Merge
- Link Tracking
- Send Later *The other plugin buttons disappear on the composer when this is enabled, but I can still send the email successfully. This also breaks the inline reply feature.*

You can disable these packages on the Plugins tab in the Preferences pane.

**Comment by jackiehluo** [comment]
Hey! We pushed a release today that should fix this issue—if you download `0.4.56`, you should be able to use N1 with the self-hosted sync engine. Let me know if that's not working!

**Comment by trestletech** [comment]
Confirmed closed in 4.56 for me.
