### ISSUE TITLE
Press Escape after a finished search to get back to Inbox

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2758]
Dear all, 

What do you think if the user could just press `Escape` to get back to the Inbox after having performed a search?

Currently, pressing `Escape` does not perform anything. 

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/17928853/290245f4-69fd-11e6-877c-bbc1202dc621.png)

**Comment by emorikawa** [comment]
@orschiro yes it definitely should. Filing this as a bug

**Comment by orschiro** [comment]
Thanks for addressing this as a bug, @emorikawa!

-Robert

**Comment by sahildua2305** [comment]
@emorikawa Can you provide some pointer as in where to look for? I'd like to take this up as my first contribution to N1.

**Comment by jstejada** [comment]
this was released with https://github.com/nylas/N1/commit/ebb8b45809911601b7b14f4201fdb46c380af1c8
