### ISSUE TITLE
Gmail Two-Factor Auth Missing

### ISSUE THREAD

**Issue by dougc84** [nylas/N1#276]
Hey guys, checking out the demo, and I noticed I'm unable to connect to my GMail accounts because of missing two-factor auth questioning.

**Comment by bengotow** [comment]
Hey @dougc84 — hmm... we bounce out to the browser for all Gmail auth, so you should be presented with the standard two-factor UI. Is there any chance you're using a very old build of N1? You should see this when the app bounces you to your browser:
![image](https://cloud.githubusercontent.com/assets/1037212/10828341/03e2a57e-7e31-11e5-9914-7b01f695bfca.png)

**Comment by dougc84** [comment]
I'm using the latest version.  Here's what happens - the window opens, and you're given the ability to accept permissions.  Once accepted, the two-factor auth dialog never displays, and this window stays open.

**Comment by dougc84** [comment]
I just went back and tried it again - it asked me for a second set of permissions, then all was good to go.  Just a strange bug.  Closing because I'm not sure if this is actually related to two factor.
