### ISSUE TITLE
BREAKING BUG: Sent 25 calendar invites to recipient without my consent

### ISSUE THREAD

**Issue by cwRichardKim** [nylas/N1#2761]
OS: 10.12 Sierra
Third party apps: none

I sent an email proposing meeting times and for some reason on her calendar, it looked like she accepted 11 calendar invites.  I suspect what happened is her mail client tried to load links for some reason (spam detection maybe?) and when that happens, it creates a calendar invite.  I suggest having a single confirmation step when the link is opened to prevent this. until this is fixed i can't use this feature.  Thanks!

Screenshot
![image](https://cloud.githubusercontent.com/assets/5778691/17949484/677d5370-6a0a-11e6-9f3e-2c8f5d2cfaa6.png)

edit: After clarifying with her, it seems *I* sent 11 calendar invites to her.  So perhaps it's Nylas that's opening the links?

**Comment by cwRichardKim** [comment]
update:
This is **incredibly** frustrating :(
![image](https://cloud.githubusercontent.com/assets/5778691/17951142/c1042720-6a14-11e6-97e1-f1f6982fe7ed.png)

**Comment by grinich** [comment]
This looks like the recipient clicked on every single link.

Do you know how that could have happened?

**Comment by cwRichardKim** [comment]
I don't think the recipient is clicking every link, I think every link is being clicked on **my side**.  She's getting a bombardment of cal invite emails, which suggests that the click is coming from my side.  I'm not sure, but i suspect it's some kind of automated link checker happening in someone's mail client.  Maybe checking for harmful content or to see if the link is broken or something.  That's just a guess though

**Comment by cwRichardKim** [comment]
Recipient has now received over 50 invitations. PLEASE FIX THIS!!

**Comment by cwRichardKim** [comment]
At the very least, is it possible to disconnect the calendar invitation links so that whatever automated process is clicking them can't create new ones?

**Comment by emorikawa** [comment]
@cwRichardKim I definitely here how frustrating this is. We send a cal invitation anytime the urls get accessed. Usually this only happens once when someone clicks on a link. I have a hunch that the recipient has a mail provider or email client that has some program parsing through and accessing the links in the page. Do you know what mail provider & email client (mobile and or desktop) the recipient uses? It's also possible that your mail client is setup to inspect and access links as well. What mail provider are you on?

Regardless we'll definitely be working on a fix to detect programs clicking these scheduler links.

**Comment by cwRichardKim** [comment]
@emorikawa <https://github.com/emorikawa> Right, I think it could also be a
third party app with email access.  I'm using Nylas N1 and this is through
gmail.  Not sure what she's using though.  Is it possible to disconnect the
links?  That would be a short term solution to ease the bombardment.
Thanks!

**Comment by bengotow** [comment]
Hey folks, this has been fixed for good - we know ask recipients to confirm their selection on the web before sending the invite.
