### ISSUE TITLE
"Select All" behavior is not clear.

### ISSUE THREAD

**Issue by CaninoDev** [nylas/N1#2768]
#  OS
Ubuntu 16.01 on a Macbook Pro 11,1

# N1 
0.4.49-c9c04b7

## Summary
Select All behavior doesn't work as expected, 

### Issue
When using a two panel interface, the following is observed:

#### First Panel 
Expected Behavior: Select a Mailbox->Select All == Selects all threads within selected Mailbox
Actual Behavior: None

![image](https://cloud.githubusercontent.com/assets/16412897/18012160/276796d8-6b6d-11e6-92a4-06c1098ba831.png)

#### Second Panel 
Expected Behavior: Select a thread->Select All == Select all emails within thread
Actual Behavior: Selects the texts displayed in the third panel. 

![image](https://cloud.githubusercontent.com/assets/16412897/18012179/4191b14c-6b6d-11e6-9648-e60622381db1.png)

**Comment by jackiehluo** [comment]
Merging into #886!
