### ISSUE TITLE
Unable to get emails

### ISSUE THREAD

**Issue by surdaft** [nylas/N1#2769]
I am consistently recieving an error about invalid user or password: `identity-store.es6:109 Unable to refresh IdentityStore status: auth() received invalid user or password`. Even when I try and reconnect it continues to throw the same error here.

I can confirm that this same gmail account is accessible with the OSX version of the app and so if it makes a difference, it is not my account that is at fault I don't think.

![image](https://cloud.githubusercontent.com/assets/8268249/18015032/be3eb514-6bbd-11e6-9432-b7eef0b30d1e.png)

I hope this helps. :) Unfortunately I will be needing to remove Ubuntu for other reasons and so I cannot continue to help debug this issue, sorry about that.

**Are there any related issues?**

Potentially related to issue #1867 

**What operating system are you using?**

Ubuntu 16.04 LTS

**What version of N1 are you using?**

0.4.49-c9c04b7

## Bug?

**Do you have any third-party plugins installed? If so, which ones?**

None

**Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**

I can only confirm with multiple Gmail accounts

**Comment by jackiehluo** [comment]
Are you no longer using Ubuntu? If you can provide more information, we would love to have it—just email us at support@nylas.com so that we can investigate further.

**Comment by surdaft** [comment]
I haven't switched yet, so what info would you like and I will send it over
to that email address.

**Comment by jackiehluo** [comment]
@surdaft Cool—can you go to Preferences -> Subscription? If you can, log out of your Nylas ID and log back into it. Does that help at all?

**Comment by surdaft** [comment]
@jackiehluo Signing out and back in worked like a charm. :) Thank you, so just curious what is your plan for getting around that? Just catching the error and asking a user to log in again?

**Comment by jackiehluo** [comment]
@surdaft Yep—ideally, we'll find out why that happens, but either way, the error messaging should be better so that the user has a course of action to take. Thanks for checking!
