### ISSUE TITLE
Request: Mouseover for info

### ISSUE THREAD

**Issue by Firebirdflame** [nylas/N1#277]
Very nice email client. Given the fact I'm new to this client, I'm partially confused by some of the icons and their actions. My natural action is to mouse over a second to see what they do, but nothing pops up. If there was text to describe its actions, I'm sure it would be easier to learn and understand.

**Comment by bengotow** [comment]
Hey @Firebirdflame —thanks for filing this. On Mac and Windows, you /should/ see tooltips appear beneath most buttons if you hover for ~3 seconds, but it's possible we're missing some. Can you see if these ones have show tooltips for you? That'll help determine if it's a platform specific bug.

![image](https://cloud.githubusercontent.com/assets/1037212/10828275/bf2c1cda-7e30-11e5-8913-dabb01c25504.png)

**Comment by hexaholic** [comment]
I can confirm this bug. I also installed the client today and expected tooltips, just like @Firebirdflame . Nothing appears, no matter how long I hover, the background of the button just switches to light gray:

![n1-no-tooltip](https://cloud.githubusercontent.com/assets/12293184/10831085/b14910b6-7e83-11e5-8e1e-d76fe3bdb1af.PNG)


Running version 0.3.20 on Windows 10 (64 bit).

**Comment by grinich** [comment]
Confirmed, no tooltips on Win 8.

**Comment by bengotow** [comment]
Hey folks - we've identified that this is broken upstream in the version of electron we're using. We're planning on moving to a new version in the next update and that should resolve the issue.

**Comment by bengotow** [comment]
We pulled Electron `0.35.1` this week and this has been fixed. Tooltips should work in version 0.3.25, which will be released this afternoon. Cheers!
