### ISSUE TITLE
Compiling on Arch

### ISSUE THREAD

**Issue by muhlisahhh** [nylas/N1#2774]
I'm attempting to compile N1 on Arch Linux and when I run the script/bootstrap I receive these errors: 
[mel@antergos N1]$ script/bootstrap
Node: v6.5.0
npm: v3.10.6

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/home/mel/N1/.npmrc" install --loglevel error --cwd="/home/mel/N1/build" --ignoreStdout=true 

gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download/release/v6.5.0/node-v6.5.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/npm/node_modules/request/request.js:977:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:361:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Linux 4.7.2-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mel/N1/build/node_modules/minidump
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.7.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/home/mel/N1/.npmrc" "install" "--loglevel" "error"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mel/N1/build/npm-debug.log

My npm-debug.log is here http://pastebin.com/A3QdASeQ

I have double checked that the latest node and npm are installed.  I'm unsure where to go from here.

**Comment by Nipsi** [comment]
Try using the [AUR pkgbuild](https://aur.archlinux.org/packages/n1/), works for me.

**Comment by muhlisahhh** [comment]
Thank you with the suggestion.  I'm trying to compile it myself to avoid the 30 day trial, and as that package is built from the .deb, it is considered precompiled and only allows 30 days for free.

**Comment by Nipsi** [comment]
Oh, ok.
I haven't tried building it, but maybe the [n1-git](https://aur.archlinux.org/packages/n1-git/) package could help you. I guess you can modify it in order to pull the latest release branch instead of current master.

**Comment by DAICHl** [comment]
> I'm trying to compile it myself to avoid the 30 day trial
Is this correct? I thought that only self-hosted https://github.com/nylas/sync-engine was needed to avoid it. Actually I am using self-hosted sync-engine with precompiled N1.

**Comment by muhlisahhh** [comment]
The issue here was that the node.js headers weren't updated properly.  I rolled back my node and it compiled fine.

**Comment by stkevintan** [comment]
could you explain the solution more clearly? I still run into this problem in spite of downgrading my node version to 6.3.1-1.
