### ISSUE TITLE
Low quality sending-spinner

### ISSUE THREAD

**Issue by ipsq** [nylas/N1#2776]
##### Are there any related issues?

#2205

##### What operating system are you using?
OS X 10.11.6 (15G31)

##### What version of N1 are you using?
0.4.49-c9c04b7 (0.4.49-c9c04b7)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

[sending-spinner.gif](https://github.com/nylas/N1/blob/master/static/images/onboarding/sending-spinner.gif) in combination with a Retina MBP and a dark theme.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No.

**Comment by emorikawa** [comment]
@ipsq thanks for reporting. Going to close & merge into https://github.com/nylas/N1/issues/2205
