### ISSUE TITLE
N1 won't launch using KDE menu

### ISSUE THREAD

**Issue by brancaleone** [nylas/N1#2777]
Hello,

I'm using N1 on opensuse 42.1 with a kde desktop environment. Since a couple of days, the app doesn't launch using the application menu anymore. I think this is related to the recent upgrade to plasma 5.7.4, so i'm looking for relevant informations to report to kde team. However, so far it seems to only be an issue with N1.

The menu entry is the default one, and is launching /usr/local/share/nylas/nylas. Using this command in a shell run the application fine. In kde menu options, if i select the nylas entry and check the option "run in a terminal" it works too.

What is strange, is that some process are actually running, but they seems to be stuck and produce no log output file. 

See a "ps" output after being launched from menu : 

```
squidward:~ # ps aux | grep nyl
cde      21727  0.1  0.5 1281968 93692 ?       Sl   09:07   0:00 /usr/local/share/nylas/nylas
cde      21730  0.0  0.1 315788 30952 ?        S    09:07   0:00 /usr/local/share/nylas/nylas --type=zygote --no-sandbox
cde      21749  0.0  0.2 365176 42376 ?        Sl   09:07   0:00 /usr/local/share/nylas/nylas --type=gpu-process --channel=21727.0.1500064088 --no-sandbox --window-depth=24 --supports-dual-gpus=false --gpu-driver-bug-workarounds=4,46,54 --disable-gl-extensions=GL_ARB_occlusion_query GL_ARB_occlusion_query2 --gpu-vendor-id=0x8086 --gpu-device-id=0x1616 --gpu-driver-vendor --gpu-driver-version --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
```

And it just stays like that until i kill it.

**Comment by emorikawa** [comment]
@brancaleone Thanks for the debug info. I'm going to merge this into https://github.com/nylas/N1/issues/2778. It looks like there's definitely a window management issue on some Linux versions. See if any of the methods left on #2778 work for you. Thanks.
