### ISSUE TITLE
Cannot sent emails when using HTTPS for self-hosted

### ISSUE THREAD

**Issue by rgruyters** [nylas/N1#2779]
##### What operating system are you using?
Mac OS X El Capitan

##### What version of N1 are you using?
0.4.49-c9c04b7

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't know, but I use IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes, when changing the APIRoot in config.json back to http:// it works fine. When setting it to https:// it doesn't.

--

In the [commit logs](https://github.com/nylas/N1/compare/0.4.49...master) from 0.4.49 it shows that HTTPS for self-hosted is added now.

**Comment by jackiehluo** [comment]
@rgruyters What are you experiencing? That commit isn't released yet, so you shouldn't see it unless you're building from source! The link you sent is the diff between 0.4.49 and master.

**Comment by rgruyters** [comment]
When trying to sent I get the standard popup message that couldn't be sent and that maybe message is too large.

I haven't build it from source, although on the commit logs page you can download the packages. Are those packages not the latest ones from build?

**Comment by jackiehluo** [comment]
The binaries on GitHub are the same as the released version—we don't create a prod build for each commit.
