### ISSUE TITLE
Name doesn't line up with subject and body in message list

### ISSUE THREAD

**Issue by CraigSiemens** [nylas/N1#278]
In the message list on OS X, the name is indented 2px more than subject and body

Also, on a non retina screen, the body sometimes appears to be indented 1px more than the subject but this doesn't happen on a retina screen.

![screen shot 2015-10-29 at 11 39 18 am](https://cloud.githubusercontent.com/assets/680442/10826988/f23958da-7e31-11e5-9281-f93cd0312c6f.png)

**Comment by bengotow** [comment]
Wow - you're totally right. Thanks for filing this. I've patched this in 62d45698d1a326a78ece7a9ccfe5faf4a618b67f. We'll be revisiting the narrow list view to add Gmail labels and support for custom indicators, but this will work until then. Thanks!
