### ISSUE TITLE
Gmail account not syncing, debugging pop-up upon quitting

### ISSUE THREAD

**Issue by eonnsago** [nylas/N1#2780]
I'm a relatively new N1 user. I used it successfully when I first installed it a few days ago.

Today, I opened it and found that it doesn't sync with the one account I've set it up with (Gmail). (I'm not sure where to look for "Activity" e.g., progress/loading status, etc). When I exited the program, I got this popup:

![nylas](https://cloud.githubusercontent.com/assets/865044/18071449/a87ea316-6e0a-11e6-9e73-d49c1465c2b8.png)

##### Are there any related issues?
I couldn't find related issues. I searched for "Run copy curl -X GET"
...

##### What operating system are you using?
OS X 10.11.3

##### What version of N1 are you using?
0.4.49-c9c04b7 (0.4.49-c9c04b7)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None installed.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have one account: Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

**Comment by jackiehluo** [comment]
Oh, no! Can you send us an email at support@nylas.com with more details about your account (email address, the problem you're experiencing, the error messaging you see, if any)?
