### ISSUE TITLE
Feature request: Snooze sent emails

### ISSUE THREAD

**Issue by martellalex** [nylas/N1#2781]
Often I want sent emails to appear in my inbox.  Commonly the case to see whether the person I sent the email to either replied, or completed an offline action.

I currently achieve this by snoozing sent emails, but at the moment in Nylas I can't just swipe to snooze, so instead what I do is 1) drag the sent email to the inbox, 2) switch to inbox, 3) snooze the email from the inbox.

Would be nice to cut out step 1) and 2) and instead just perform step 3) directly from the sent items.

I seem to recall Mailbox working this way which is where I developed the habit I think.

**Comment by jackiehluo** [comment]
Merging into #1779 and #1568!
