### ISSUE TITLE
Nylas Github stars spam

### ISSUE THREAD

**Issue by xorinzor** [nylas/N1#2784]
I just received an email from nylas on every, single, connected, account.. which resulted in 5x the same email, which, because of the different email adresses got treated as individual emails.

This seems like something that might want to be changed in the future

![untitled](https://cloud.githubusercontent.com/assets/4212335/18101979/25b55fe6-6ef1-11e6-8aa0-31f3188f7bf8.png)

**Comment by jackiehluo** [comment]
@xorinzor That means you subscribed with each email address when you added each account! Just uncheck the box in Preferences -> Accounts.
