### ISSUE TITLE
Cannot send emails

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2785]
Dear all, 

I am suddenly receiving the following error for all emails I am trying to send. 

Does anyone have the same problem?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18106095/6a273684-6f02-11e6-9737-0566537a3413.png)

**Comment by jackiehluo** [comment]
@orschiro Can you email us at support@nylas.com?

**Comment by orschiro** [comment]
Just done so and this email went through!
