### ISSUE TITLE
Nylas Pro subscription window is too obtrusive

### ISSUE THREAD

**Issue by zaki3d** [nylas/N1#2787]
Currently, I've set the Nylas client to appear on a custom global shortcut on my Mac. However, everytime I trigger my shortcut, this dialog appears instead of the main window:

![screen shot 2016-08-31 at 1 14 38 pm](https://cloud.githubusercontent.com/assets/1821786/18114751/0c61c584-6f7d-11e6-9560-7e797260ad8e.png)

It also appears everytime I go to Preferences to update my settings. I might be missing something, but the dialog behaviour is really obtrusive and but I can't seem to permanently dismiss it. Everytime it pops up, I'll have to reach my mouse and manually close it.

I hope there's a way I can permanently dismiss the dialog without having to sign up for a pro account.

**Comment by grinich** [comment]
What platform are you on? What version of the app are you running?

**Comment by zaki3d** [comment]
I'm running **Version 0.4.49-c9c04b7 (0.4.49-c9c04b7)** on **Mac OS X 10.11.15**.

**Comment by jackiehluo** [comment]
@zaki3d Are you running your own instance of the sync engine?

**Comment by zaki3d** [comment]
I'm not on the pro account so I guess not. Just downloaded it straight from Github. I never had a Nylas ID so I didn't bother signing in upon seeing this dialog. Just closed it and proceeded to add my accounts via **Add Account** in the menu.

**Comment by zaki3d** [comment]
Here's a recording of it if it helps: https://www.dropbox.com/s/vhfi80ar8djy6jp/nylas-obtrusive-dialog.mp4?dl=0

**Comment by bengotow** [comment]
Hey—thanks for filing this!

If you're using your own copy of our open-source sync engine, you can choose not to create a Nylas ID. On the screen in your screenshot, you can choose "Hosting your own sync engine?" at the very bottom, provide the URL of your sync engine, and you're done. When you use your own sync engine, you don't get some of the pro features that require our infrastructure, like snooze, send later, etc., but everything else works and you don't need to provide us with any information.

- If you're using our hosted sync engine, you need to create a Nylas ID. There actually shouldn't be an "X" on that "Welcome Back" screen. We use your Nylas ID to authenticate API requests to our servers, and N1 may stop working in the next week or so as we transition more of our infrastructure to use Nylas IDs.

Sorry for the hassle! Going to close this as a non-issue. The solution to the obtrusive window is just to do what it asks ;-).
