### ISSUE TITLE
Syncing contacts with Google Contacts

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2789]
Dear all, 

Does N1 sync contacts with Google Contacts?

Thankfully,

-Robert

**Comment by emorikawa** [comment]
@orschiro we pull both all of your contacts in your address book, plus the sum of all participants you've emailed. Unfortunately there's no syncback yet. We're working towards a much nicer contact management solution within N1, but for now we optimistically pull as many as we can.

**Comment by jackiehluo** [comment]
Merging into #1031!

**Comment by orschiro** [comment]
Thank you!

**Comment by pratnala** [comment]
I can't even view my google contacts when I type in the to: field. It only pulls from previously emailed people.
