### ISSUE TITLE
Please check that your SMTP settings are correct.

### ISSUE THREAD

**Issue by skeyl** [nylas/N1#279]
Just received an invite; I keep getting this error with my home server. I know that it's N1 because I can use thunderbird and have web mail setup.

I tried to troubleshoot by grepping through the source but cannot find anything to point me in the right direction except for `account-types.coffee`.

I was looking for a verbose mode but there does not seem to be one.

The dev tools do not output any relevant information either.

I should also note I'm running Xubuntu 14.04

**Comment by nicolas-t** [comment]
Same here, gmail can connect to my own smtp server but N1 fails:  
`Please check that your SMTP settings are correct.`

**Comment by skeyl** [comment]
Looks related to #47

**Comment by skeyl** [comment]
Closing this as I'm using a self-signed cert. This application needs to be able to function with self signed certs; and it needs to give feedback about that being the issue.
