### ISSUE TITLE
HTML signatures have lost formatting in 0.4.50-5321656

### ISSUE THREAD

**Issue by matiasvad** [nylas/N1#2790]
Downloading the new version this morning has thrown away all formatting on signatures. 
These are all signatures from Gmail / Google Apps, which have worked in previous Nylas versions.
When viewing signatures in preferences they appear fine.

I'm using Mac OS X 10.11.6

Nylas version 0.4.50-5321656

Third party plugins:
I have the Unsubscribe plugin installed.

Bonus info:
The formatting issue occurs after the new editor loads.
![screen-recording-2016-09-01-at-10 04-am](https://cloud.githubusercontent.com/assets/1929609/18160075/e5854e72-702b-11e6-8cb3-094ec67bddc2.gif)

**Comment by matiasvad** [comment]
Update.

Deactivating the markdown plugin resolves the issue.

**Comment by flyingclimber** [comment]
Can confirm that I'm seeing the same issue

**Comment by emorikawa** [comment]
@matiasvad Yes. Signatures are currently broken with the Markdown plugin. We're shipping a patch for this today. We're now putting the signatures beneath the email since they're usually not Markdown friendly.

**Comment by bengotow** [comment]
Hey! This has been fixed by eb87fe4745c54ff10262e2211dfd6a3369426e7b, which moves the signature and quoted text out of the markdown formatted text area.
