### ISSUE TITLE
There is no apparent way to cancel sending an email

### ISSUE THREAD

**Issue by rtaibah** [nylas/N1#2791]
##### Are there any related issues?

Couldn't really find any.
...

##### What operating system are you using?
Mac OSX 10.11

##### What version of N1 are you using?
Version 0.4.49-c9c04b7 (0.4.49-c9c04b7)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't think so.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I don't know.

--

So the issue is basically I wrote an email to a client that was a bit heavy worded, clicked send, then regretted it immediately. The email didn't go out yet, so I disconnected my LAN and Wifi, as I didn't see a cancel button. Now the email is stuck, with a loader indicating that it's trying to connect.

I sent a 'toned-down' email through the web client, but now I am locked out of N1 because I can't have it open while connected to the Internet lest the 'heavy worded' email goes out.

![screen-shot-2016-09-01-at-12 23 44-pm](https://cloud.githubusercontent.com/assets/707668/18163458/c4dbda8e-7043-11e6-8095-7d2dbf2a8cf9.png)

**Comment by jackiehluo** [comment]
@rtaibah If you go to Preferences -> General and click "Reset Email Cache," that should do it!

**Comment by jackiehluo** [comment]
(Separately, we're looking into adding "Undo Send" as a feature!)
