### ISSUE TITLE
Email selection automatically moves up list marking messages unread.

### ISSUE THREAD

**Issue by crewshin** [nylas/N1#2799]
##### Are there any related issues?
Not that I can find

##### What operating system are you using?
OSX: El Capitan

##### What version of N1 are you using?
Version 0.4.51-93ef779 (0.4.51-93ef779)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Negative. Fresh install. Tested on two machines with the same result.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail is the only provider I use. Can't answer.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It's completely random, but happens very frequently. I'd love to include a screenshot... but it involves a lot of private emails and info.

I use the split view screen and the unread inbox. I leave messages unread until I get to them (like a todo list). All of my comments are based on that assumption. 

The issue is that when I select a message, after a second or so, the selection itself starts selecting messages sequentially going up. It will usually go up about 4-5 messages marking them all read. 

Flaaaarg

**Comment by bengotow** [comment]
Thanks! Closing as dup of #2271

**Comment by crewshin** [comment]
Ah dangit. Sorry Ben my searches turned up nothin'.

Thanks though!
