### ISSUE TITLE
Manage Accounts - Window Size

### ISSUE THREAD

**Issue by kshahh** [nylas/N1#280]
If you add too many emails (7+) you can no longer add more emails, due to the fact that the add account button gets placed off screen.
<img width="518" alt="screen shot 2015-10-29 at 2 23 12 pm" src="https://cloud.githubusercontent.com/assets/15384953/10828109/fa7b4424-7e48-11e5-9b67-4181cbd6f7e8.png">

**Comment by bengotow** [comment]
Hi—thanks for downloading N1. That's a lot of accounts ;-) We're planning to improve this interface and we'll make sure it scrolls.

In the meantime, if you choose `Add Account` from the menu, you can get straight to the Add Account screen:

![image](https://cloud.githubusercontent.com/assets/1037212/10860323/b71dd6fc-7f23-11e5-859b-0ec34ea35dc8.png)
