### ISSUE TITLE
Updgrade bar position is broken in Less is More theme

### ISSUE THREAD

**Issue by michalkopanski** [nylas/N1#2808]
Unlike all other bundled themes, "Less is More" has incorrect placement of the "Upgrade to Nylas Pro" bar.

See below:

![](http://kpnsk.me/hNaD/Screen%20Shot%202016-09-06%20at%2010.20.18%20AM.png)

--

##### Are there any related issues?
Didn't find any.

##### What operating system are you using?
OSX 10.11.6

##### What version of N1 are you using?
0.4.51-93ef779

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No.

**Comment by emorikawa** [comment]
@michalkopanski We're working on a general re-design of these notification bars. We'll see about getting the themes updated when this goes out.

**Comment by jackiehluo** [comment]
Merging into #2743.
