### ISSUE TITLE
Reply Buttons Do Not Work

### ISSUE THREAD

**Issue by jhubbardsf** [nylas/N1#2810]
Hitting reply within the email or the reply to email at the bottom of the email does nothing in 0.4.51. You click them and there's literally no response, although I do get errors in the console. I can't test 0.4.49 because it didn't work with the self hosted sync-engine. I downgraded back to 0.4.47 and the reply issue seems to be working fine.

Nylas N1: 0.4.51
OS: Ubuntu 16.04

Errors:
`internal/process/warning.js:24 (node:24518) Warning: Possible EventEmitter memory leak detected. 51 trigger listeners added. Use emitter.setMaxListeners() to increase limit`

and

`/usr/share/nylas/resources/app.asar/src/nylas-env.js:306 Error: Invalid pluginId. Must be a valid string: 'undefined'`

**Comment by hummel** [comment]
Also affected.

Nylas N1: 0.4.51
OS: Linux Mint 17.3

**Comment by bengotow** [comment]
Hey folks, this should be fixed in the most recent version of N1.
