### ISSUE TITLE
Improved search capability

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2818]
Dear all,

Can the search function further be improved?

Thankfully,

-Robert

**Example:**

![image](https://cloud.githubusercontent.com/assets/170947/18342768/a8d7795c-75b0-11e6-9696-7968cf545a05.png)

![image](https://cloud.githubusercontent.com/assets/170947/18342774/b322a026-75b0-11e6-8ce3-ca41a5598ef8.png)

**Comment by jackiehluo** [comment]
Merging into #750—looks like search is broken again! 😞

**Comment by orschiro** [comment]
Merging into #750—looks like search is broken again! 😞
