### ISSUE TITLE
N1 Possibly Sends Duplicate Emails With IMAP Accounts

### ISSUE THREAD

**Issue by inb4ohnoes** [nylas/N1#2822]
##### Are there any related issues?

No

##### What operating system are you using?
macOS Sierra

##### What version of N1 are you using?
0.4.51-93ef779

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Seems to only happen with IMAP account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Happens with all emails it seems

**Comment by emorikawa** [comment]
@inb4ohnoes Could you contact support@nylas.com with the email address this is happening to so we can continue to investigate this with you.

**Comment by emorikawa** [comment]
@inb4ohnoes Also, can you confirm the messages are being received by recipients twice, or are they simply show up in your sent folder twice?

**Comment by grinich** [comment]
perhaps https://github.com/nylas/N1/issues/2695#issuecomment-239291271

**Comment by inb4ohnoes** [comment]
Yes it seems to be this as I haven't gotten any sort of report from message receivers that I'm sending duplicate emails.

**Comment by jstejada** [comment]
merging into duplicate #2695
