### ISSUE TITLE
Spam and Trash not showing up for Gmail Account

### ISSUE THREAD

**Issue by csteinlehner** [nylas/N1#2823]
##### What operating system are you using?
OS X 10.11.6

##### What version of N1 are you using?
0.4.51-93ef779

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Having it on Gmail, its the only account I'm using.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
My Spam and Trash folders appear empty in Nylas. But on the Web-Interface of Gmail, these folders are not empty.

**Comment by emorikawa** [comment]
@csteinlehner Have you recently added this account to Nylas? We sync these folders last and it may take a bit before N1 sees it.

**Comment by jackiehluo** [comment]
If this issue is still happening for you, shoot us an email so that we can debug better! support@nylas.com
