### ISSUE TITLE
No message sync before enabling "Run with debug flags"

### ISSUE THREAD

**Issue by jcnoir** [nylas/N1#2828]
I use the current N1 master (9ac730cccc1aa08f7e01c5672062071dcd9f4afa) with a self hosted nylas sync engine.
The real mail server is an IMAP dovecot.
On a fresh start (~/.nylas removed) I can configure my sync engine server but I cannot see any message (even after a long time).
An app restart has no effect.
If I click on "run with debug flags" the app restarts and then all my messages appear normally.

I use the application on Arch Linux (https://aur.archlinux.org/packages/n1-git/)

**Comment by bengotow** [comment]
Hi—thanks for reporting this. I believe this will be addressed by a few fixes in the pipeline this week. Stay tuned—

**Comment by jcnoir** [comment]
Good news ! Thanks.

**Comment by jcnoir** [comment]
I checked with the current master version (6eea9d26f1cda3712b2f6b31aa54c0d68ee27d94).
The issue is still here.

**Comment by jcnoir** [comment]
Hi,
@bengotow  : Why did you close the issue ?
I just checked with the current master (80e1c5b457248385f8c64d27162ef65c61e44783) and the issue is still there.
