### ISSUE TITLE
Not Displaying Accounts Or Sending Message

### ISSUE THREAD

**Issue by northcreativedesign** [nylas/N1#2829]
Yesterday my account stop letting me delete, and send messages I kept getting an error saying check sender information and make sure message is not to long (I was just sending a test email)

I proceeded to un-install my program and reinstall it re-set up my emails and nothing is loading now. I thought it was just the IMAP account but I also tried to import my g-mail account and it also was not loading. As a paying customer this type of malfunction is not really acceptable.

**Comment by bengotow** [comment]
Hi — thanks for reporting this! Can you email support@nylas.com and include the email addresses you're experiencing problems with? Thanks—

Ben
