### ISSUE TITLE
Can't publish package

### ISSUE THREAD

**Issue by evenh** [nylas/N1#283]
I've tried to publish my [n1-markdown](https://github.com/evenh/n1-markdown) package, using the instructions from the [FAQ](https://nylas.com/N1/docs/FAQ.html). When I try to perform the POST request, I get the following response:

```
HTTP/1.1 404 Not Found
Server: nginx/1.6.2
Date: Thu, 29 Oct 2015 20:56:47 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 501
Connection: close
X-Cascade: pass
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000;

<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  body { text-align:center;font-family:helvetica,arial;font-size:22px;
    color:#888;margin:20px}
  #c {margin:0 auto;width:500px;text-align:left}
  </style>
</head>
<body>
  <h2>Sinatra doesn&rsquo;t know this ditty.</h2>
  <img src='http://utility-util-10-77-232-17/__sinatra__/404.png'>
  <div id="c">
    Try this:
    <pre># in web.rb
class Umpire::Web
  post '/api/packages' do
    "Hello World"
  end
end
</pre>
  </div>
</body>
</html>
```

**Comment by nahtnam** [comment]
Can confirm.

**Comment by evenh** [comment]
Any progress on this @bengotow?

**Comment by evenh** [comment]
Still the case as of 2015-11-20

**Comment by grinich** [comment]
We're rebuilding the package manager and going to ship it sometime in 2016. (It's pretty complicated to get right.) For now you should (1) announce your plugins on the [community Slack channel](http://slack-invite.nylas.com/), and (2) submit a PR to link it in the N1 Readme! If you're lucky we'll also maybe feature it in our newsletter!

**Comment by orschiro** [comment]
Any progress on this with the latest release 0.4.25?

~Robert

**Comment by evenh** [comment]
I still get the same result when curl'ing at least.
