### ISSUE TITLE
Archived Folder After Beginning to Use Nylas

### ISSUE THREAD

**Issue by nicorellius** [nylas/N1#2834]
I'm writing about a Gmail account. I have a folder in my Outlook client called `Archived`. It fills up with messages, and it has been doing so ever since I started using Nylas N1. On my Ubuntu systems, where I exclusively use Nylas, this folder doesn't exist. I don't use Nylas on this Windows 7 system, where Outlook is installed.

I don't use the archive feature in Gmail.

##### What operating system are you using?
Windows 7, Ubuntu 14.04, Ubuntu 16.04

##### What version of N1 are you using?
0.4.47-3a2a94c

Outlook also in this case. Nylas is on the other systems... Ubuntu

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Maybe, but not sure.

**Comment by emorikawa** [comment]
@nicorellius When we "archive" mail in Gmail, we simply remove the "inbox" label so it shows up in "all mail" but not your inbox. For other providers we move messages into a folder called "Archive". It seems as though your Outlook client may be misinterpreting Gmail's setup and artificially creating this Archive folder. In N1 we list it as "All Mail"

**Comment by jackiehluo** [comment]
Closing this issue because it doesn't sound like an N1 issue!
