### ISSUE TITLE
Wrong contact name when I enter an email address as email recipient

### ISSUE THREAD

**Issue by stevehanson** [nylas/N1#2835]
When I type in a coworker's email address in Nylas N1, in the `To` field of a compose window, when the autocomplete occurs, his name is incorrectly showing as the name of our company. I'm trying to figure out why this is happening. When I type his email address in any of my Gmail accounts in my browser, Gmail completes with his correct name. Mail.app also gets his name correct. Additionally, I've also verified that I don't have him saved as a contact in Contacts.app. Could someone help me understand where Nylas could be finding this incorrect name so I can fix it?

I'm on a Mac, using Nylas N1 Version 0.4.51-93ef779 (0.4.51-93ef779). His name has been autofilling like this at least for the last several months.

**Comment by bengotow** [comment]
Merging this into #1031 — we'll be working on this soon!

**Comment by stevehanson** [comment]
Thanks @bengotow. Contact management would do the trick.

**Comment by AbacusPowers** [comment]
+1 for this getting fixed ASAP. My boss is labeled in N1 as "classifieds" (which I just learned is visible to other recipients), because my first interaction with him was through a job search. I'd be laughing if it wasn't happening to _me_. 
:(
