### ISSUE TITLE
Sluggish typing

### ISSUE THREAD

**Issue by nativeimaging** [nylas/N1#2837]
Just doing the Trial still, but having issues with sluggish typing response. Sometimes it takes 10-30 seconds for a letter to type after I hit the key.. Is this common?  Is Nylas sending live text input data to Nylas servers while typing?

Sometimes its so slow, I have to reboot my machine to get it to respond. I'm on Mac OS 10.5.

Loving the app so far thanks!

**Comment by grinich** [comment]
That is definitely not normal! 

Can you tell us a bit more about your system? OS? Language?

Is this for new messages or when you're replying to a long thread?

**Comment by nativeimaging** [comment]
Yes during long threads, but also on blank emails when only typing a few sentences it will get very sluggish. It seems to get better after I reboot my computer and electron helper.

OSX Yosemite 10.10.5
2.6 GHz Intel Core i5
8 GB 1600 MHz DDR3

**Comment by nativeimaging** [comment]
Aha, my apologies, its my email signature causing the sluggishness. It seems that the content input refreshes as you type and was causing my signature resources to reload each time a character was typed. I use remote files in my signature for dynamic control, so I will make sure to add the signature after I finish typing. Closing this issue. I don't know if you are able avoid that issue for email signatures with remote content.

Thanks for responding. I'm considering buying N1, but i'm hoping for the empty trash feature to be implemented soon....
