### ISSUE TITLE
Composing new messages or replies open composition window on secondary monitor.

### ISSUE THREAD

**Issue by tylerofathenry** [nylas/N1#2839]
I am running N1 0.4.52 on Ubuntu 16.10 (laptop). I am using a dual monitor setup with the launcher assigned to the primary monitor (arranged to the left of my laptop monitor).

**Issue:**
When I click to compose a new message or reply the new window is displayed on my secondary (laptop) monitor.

**Helpful Information for Developer**
I have minimal experience developing Electron applications. So, since I won't be submitting a PR, this may be helpful: https://github.com/electron/electron/blob/master/docs/api/screen.md#screengetprimarydisplay

**Comment by jackiehluo** [comment]
Merging into #58—thanks for that link!
