### ISSUE TITLE
Build completes but app won't run

### ISSUE THREAD

**Issue by ChemicalRocketeer** [nylas/N1#2842]
The bootstrap script says it completed without any issues, right after saying "Failed to copy C:\Users\ChemicalRocketeer\AppData\Local\Temp\nylas-build\Nylas to C:\Program Files\Nylas". Nylas only exists under AppData/...etc, so I tried running nylas.exe and nothing happened. So I tried running it from a command line and got this:

```
Streaming log data to C:\Users\Aaron\AppData\Local\Temp\Nylas-N1-6816.log
ELECTRON_ASAR.js:158
        return old.apply(this, arguments)
                   ^

Error: %1 is not a valid Win32 application.
\\?\C:\Users\Aaron\AppData\Local\Temp\nylas-build\Nylas\resources\app.asar.unpacked\node_modules\nslog\build\Release\nslog.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Aaron\AppData\Local\Temp\nylas-build\Nylas\resources\app.asar\node_modules\nslog\lib\nslog.js:5:11)
```

The log file is empty.

I tried rebuilding from a terminal with administrator privileges, thinking that might help with the "Failed to copy" situation, but nothing changed.

##### What operating system are you using?
Windows 10

##### What version of N1 are you using?
0.4.52

**Comment by emorikawa** [comment]
@ChemicalRocketeer That may be indicative of `script/bootstrap` not building the packages correctly. Some of our node modules require native extensions which need MSBuild to succeed properly. Furthermore, you can't just run a plain `npm install` since we need to compile against Electron's headers. The `script/bootstrap` script should do that for you (via `apm`). There have been intermittent compile issues with Visual Studio 2015. We use 2013 to build with. Did you get any errors during the `script/bootstrap` process.

**Comment by starmate** [comment]
Hi,

I tried to compile on Windows 10 without any success.

May I know which version of nodejs and visual studio you used?

Thanks,

Jon

**Comment by bengotow** [comment]
Hey folks - 0888c5cdd0432e8496ac5b33daa0506bb89deb6d  should fix this issue. Our team uses Visual Studio 2013 and NodeJS 4.2 on Windows. If you previously had problems building, you may have half-built or incorrectly-built node modules inside the project directory. You can reset your working copy with `git clean -xdf` so script/bootstrap runs from scratch. Cheers!
