### ISSUE TITLE
Sent folder isn't available

### ISSUE THREAD

**Issue by rgruyters** [nylas/N1#2843]
I just noticed that I don't have a sent folder for one of my accounts. It's linked for two other accounts, one IMAP and one Gmail, but not my personal IMAP account.
Folder structure is the same as the other IMAP account.
For the record, I have three accounts configured, two IMAP accounts and one Gmail account.

I'm running N1 version 0.4.51-9ac730c with self hosted sync engine.

Is there a way to fix this?

**Comment by emorikawa** [comment]
@rgruyters Our sync engine currently attempts to guess what we think the sent folder should be. On some IMAP configurations that code guesses incorrectly. We're working on a shortly upcoming feature to let you manually assign a "sent" folder in this case to help fix this problem. Stay tuned.

**Comment by jackiehluo** [comment]
Merging into #1457!
