### ISSUE TITLE
Trial mode bar visible when using self hosted

### ISSUE THREAD

**Issue by rgruyters** [nylas/N1#2844]
I just compiled the latest N1 release, 0.4.53-b1fb5d8, and the trial mode bar is visible when using self hosted sync engine.

https://www.dropbox.com/s/66572tswx55aa8a/Screenshot%202016-09-16%2013.09.52.png?dl=0

**Comment by emorikawa** [comment]
@rgruyters yes, on latest master is a prototype trial bar that is actually getting refactored out today. If you want the latest checkout the `0.4.52` tag on the `stable` branch.

**Comment by bengotow** [comment]
Hey folks—this has been resolved in `0.4.56` which was just released this morning. Cheers!
