### ISSUE TITLE
Option to define default from address?

### ISSUE THREAD

**Issue by orschiro** [nylas/N1#2846]
Dear all, 

What do you think of an option to define the default from address that is used in the message compose window?

Thankfully,

-Robert

**Comment by jackiehluo** [comment]
@orschiro I think the default is just the first account—which you can reorder if you want in Preferences -> Accounts!

**Comment by orschiro** [comment]
Alright, thanks! :-)

**Comment by jstejada** [comment]
@orschiro You can select the default from address inside `Preferences -> General`:

<img width="522" alt="screen shot 2016-10-17 at 10 20 17 am" src="https://cloud.githubusercontent.com/assets/1271509/19447686/6a7d3bc6-9453-11e6-88c8-49c05cd86032.png">

is this what you are looking for?

**Comment by orschiro** [comment]
Thanks, Juan!
