### ISSUE TITLE
Open tracking creating too many notifications

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#2849]
> i'm seeing way too many alerts coming in for message viewing. it looks like 
> one person touched the email and i got maybe 20 alerts mentioning all parties 
> touched the email at the same time. doubtful to that it happened that way. 
> here's a decent screenshot of the event.

https://nylas.zendesk.com/agent/tickets/6240

**Comment by samgabell** [comment]
Hey Team, I'd love an option to turn off desktop notifications for link and click tracking on Mac.

**Comment by sachinag** [comment]
Possibly related: if I send a message with open tracking from N1, then I open that thread on Gmail desktop, N1 will say that the recipient opened the message - but I'm the one who did.  So it's an open alert that's incorrect.

**Comment by jackiehluo** [comment]
Pushed a fix that should have fixed this issue.
