### ISSUE TITLE
My 163 mailbox in Thunderbird Mozilla using the same configuration can be a normal landing, but not in the N1 Nylas. 

### ISSUE THREAD

**Issue by JSW5297** [nylas/N1#2853]
My 163 mailbox in Thunderbird Mozilla using the same configuration can be a normal landing, but not in the N1 Nylas. Has prompted the SMTP setup error: `check that your SMTP settings are correct. Please`, what is the reason for this?

**Comment by jackiehluo** [comment]
Can you send an email to support@nylas.com with details for the account?
