### ISSUE TITLE
Misplaced "new feature" glowing dot

### ISSUE THREAD

**Issue by laughedelic** [nylas/N1#2856]
I see a glowing dot as for the tips and new features, but it's misplaced and I can't click it. It appears when I try to reply to a message.

<img width="278" alt="screen shot 2016-09-19 at 16 41 23" src="https://cloud.githubusercontent.com/assets/766656/18636685/02edc28e-7e8a-11e6-9bb6-38540f171d06.png">

--

##### Are there any related issues?

Didn't find

##### What operating system are you using?

Mac OS X El Capitan 10.11.6

##### What version of N1 are you using?

0.4.53-36f4801 (beta, I guess)

--

##### Do you have any third-party plugins installed? If so, which ones?

- Squirt v0.1.0
- n1-unsubscribe v0.1.0

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I use only Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I see the problem when I try to reply to a message

**Comment by emorikawa** [comment]
@laughedelic This is getting fixed now by @bengotow and will be on the next beta release.
