### ISSUE TITLE
Feature Request: Webapp

### ISSUE THREAD

**Issue by jgrizou** [nylas/N1#2860]
**A Nylas webpage where we find our Nylas account and mails as we do on our desktop?** 

Nylas is a desktop client, which is nice to work offline. It is also important to have Nylas sync our work to our mail providers so we can find emails in the same state when we have to connect from a 'random' webbrowser. But it is still annoying to go check each account one by one. Also a lot of request for Android and IOs app has been made. Having a webapp, responsive for mobile, would solve all those problems.

Is it technically feasible? without ever downloading the mails and attachements, just displaying in a nice way mails from multiple emails accounts and allow for reply.

I just don't understand how there is no proper webapp outthere to act as a mail manager online - aggreating mails from different/ugly webmails into a nice online streamlined interface like the one of Nylas.

Would anyone else be interested in such webapp? or is it just nonsense?

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Not to my knowledge but I believe it would make a difference.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this – a web version of N1 would definitely be useful, but our team is planning to focus on offering a great desktop experience. Unfortunately, N1 heavily leverages NodeJS and Electron APIs, and building a web version would take quite a bit of work! It's more likely we'll build mobile apps next. :-)
