### ISSUE TITLE
Mass Mailing : rate limiting

### ISSUE THREAD

**Issue by iam-merlin** [nylas/N1#2863]
When we used mass mailing, we have an API rate limiting... (for memo, massmailing is limiting to 500 expeditors)

<img width="803" alt="screen shot 2016-09-21 at 18 45 11" src="https://cloud.githubusercontent.com/assets/2074733/18720337/b71ec79c-802b-11e6-8461-50cb595a391d.png">

**Comment by jackiehluo** [comment]
@iam-merlin Hey! Sorry—what's the issue you're experiencing? We do cap the number of recipients for a mail merge at 500. That's expected behavior!

**Comment by iam-merlin** [comment]
no problem ;), the issue is errors in the API... not Nylas in fact :/ (have a look to the screenshot, everything is in)

**Comment by jackiehluo** [comment]
We capped mail merges to 150 recipients in the latest release, and we'll look at other options for batch emailing that don't run into the same rate-limiting problems!

**Comment by iam-merlin** [comment]
ok thx
