### ISSUE TITLE
Columns do not remember width

### ISSUE THREAD

**Issue by Zeklandia** [nylas/N1#287]
After restarting Nylas, the far left, message list, and message content views will be restored to their default sizes.

**Comment by Zeklandia** [comment]
Also happens when switching from one view to another and then back.
I.e. Inbox --> Drafts --> Inbox

**Comment by bengotow** [comment]
Merging as a duplicate of #287

**Comment by Zeklandia** [comment]
Uh... It is issue #287.

**Comment by jstejada** [comment]
merging into #833
