### ISSUE TITLE
copying participant needs space between name and email

### ISSUE THREAD

**Issue by grinich** [nylas/N1#2871]
![pasted image at 2016_09_26 04_54 pm](https://cloud.githubusercontent.com/assets/92417/18854326/90720c1c-8418-11e6-8f77-50dbc6e26648.png)

this results in the text `Person Name<theiremail@gmail.com>` instead of `Person Name <theiremail@gmail.com>`

**Comment by bengotow** [comment]
This has been fixed in 0.4.59, which we shipped earlier today. Enjoy!
