### ISSUE TITLE
Suggestion: Display N1 version in settings

### ISSUE THREAD

**Issue by emelbardis** [nylas/N1#2878]
I occasionally visit GitHub to see if a new version is released and then forget if I've already updated since the latest release. I'm running Fedora 24 and would like to see either an 'about' menu item in the tray or a version display in Nylas settings.

Thanks!

**Comment by jackiehluo** [comment]
You can see it in the menu! 
<img width="222" alt="screen shot 2016-09-29 at 5 22 21 pm" src="https://cloud.githubusercontent.com/assets/8452682/18976766/4f655370-8669-11e6-828f-954942d6c3ca.png">

**Comment by emelbardis** [comment]
Maybe in MacOS but I don't have that menu screen in Gnome on Fedora 24
![screenshot from 2016-09-29 17-28-04](https://cloud.githubusercontent.com/assets/20196908/18976887/8f2a2a8e-866a-11e6-8643-b085af81fe61.png)

![screenshot from 2016-09-29 17-29-10](https://cloud.githubusercontent.com/assets/20196908/18976889/93311926-866a-11e6-80cd-ed266a961199.png)

**Comment by hallamoore** [comment]
Possibly related to https://github.com/nylas/N1/issues/2687

**Comment by emelbardis** [comment]
Yeah. I pressed alt in Nylas and the menubar displayed. I never new it was there... :)
I can workaround and hit alt for now
