### ISSUE TITLE
Nylas will not load macOS Sierra

### ISSUE THREAD

**Issue by delahaya** [nylas/N1#2879]
Im running macOS Sierra 10.12 and version 0.4.52 of Nylas.

When I open Nylas I get this pop up window and Nylas will not load.

![screen shot 2016-09-30 at 9 42 26 am](https://cloud.githubusercontent.com/assets/19581991/18993656/4aa7d680-86f2-11e6-8ac1-87644aa0b2ba.png)

I can close the dev window but after that Nylas doesn't load.  I have performed a clean uninstall of nylas and made sure to grab every associated file.  When re-installing I get the same result.  I have also tried different view options and there is no getting around this.

**Comment by delahaya** [comment]
p.s. I also performed an archive and install of macOS Sierra.  This issue was present before and after the archive and install.

**Comment by jackiehluo** [comment]
Can you click "Console" and paste the errors you see?

**Comment by delahaya** [comment]
Sep 30 12:47:44 d-128-143-193-7 Nylas[845]: Streaming log data to /var/folders/p2/qkwwzg451t345sr_gq2yd88w0000gn/T/Nylas-N1-845.log
Sep 30 12:47:45 d-128-143-193-7 Nylas[845]: App load time: 631ms
Sep 30 12:47:47 d-128-143-193-7 Nylas[845]: ErrorReporter: Shipping Logs. Exception occurred
Sep 30 12:47:47 d-128-143-193-7 Nylas[845]: /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-private-ship-logs-task
Sep 30 12:47:47 d-128-143-193-7 Nylas[845]: Error: variable @soda-blue-dark is undefined
	    at EventEmitter._electron.ipcMain.on (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/browser/application.js:565:17)
	    at emitTwo (events.js:106:13)
	    at EventEmitter.emit (events.js:191:7)
	    at EventEmitter.<anonymous> (/Applications/Nylas N1.app/Contents/Resources/electron.asar/browser/api/web-contents.js:165:13)
	    at emitTwo (events.js:106:13)
	    at EventEmitter.emit (events.js:191:7)
Sep 30 12:47:48 d-128-143-193-7 Nylas[845]: Running log ship: /var/folders/p2/qkwwzg451t345sr_gq2yd88w0000gn/T/, Nylas-N1-845[.0-9]*.log$
Sep 30 12:47:48 d-128-143-193-7 Nylas[845]: Error uploading /var/folders/p2/qkwwzg451t345sr_gq2yd88w0000gn/T/Nylas-N1-845.850.log: status code 204
Sep 30 12:47:48 d-128-143-193-7 Nylas[845]: Error uploading /var/folders/p2/qkwwzg451t345sr_gq2yd88w0000gn/T/Nylas-N1-845.log: status code 204
Sep 30 12:47:48 d-128-143-193-7 Nylas[845]: Error uploading /var/folders/p2/qkwwzg451t345sr_gq2yd88w0000gn/T/Nylas-N1-845.849.log: status code 204
Sep 30 12:47:48 d-128-143-193-7 Nylas[845]: Error uploading /var/folders/p2/qkwwzg451t345sr_gq2yd88w0000gn/T/Nylas-N1-845.848.log: status code 204
Sep 30 12:47:48 d-128-143-193-7 Nylas[845]: ErrorReporter: Shipped Logs.
Sep 30 12:48:00 d-128-143-193-7 diagnosticd[258]: System mode client started - Console (863) - mode: 0x8

**Comment by jackiehluo** [comment]
Looks like a third-party theme you have installed isn't working properly—if you go to ~/.nylas/packages and delete it, you should be good to go!

**Comment by delahaya** [comment]
I saw that as well. Didn't know where the package location wasn.  Thank you.  Im on it.

**Comment by delahaya** [comment]
![screen shot 2016-09-30 at 12 55 40 pm](https://cloud.githubusercontent.com/assets/19581991/18999761/36fc26e8-870d-11e6-8781-e1a6f9b68bcc.png)
 Nailed it! Thanks again.
