### ISSUE TITLE
cannot enter in recipient

### ISSUE THREAD

**Issue by nativeimaging** [nylas/N1#2880]
Hello. I have to wait or click about 5-10 times before I can type text into the address recipient field.

**Comment by bengotow** [comment]
Hey! When this happens is the recipient field collapsing on you, or is your text not just being entered in the field? Maybe this is #2754 ?

**Comment by nativeimaging** [comment]
No its not the same bug as that issue #2754. Its just fussy behavior, not only the collapse part but just selecting it an typing into it. I have to try 3, 4, 5 or more times to get the email address to type in. I dont get whats so complex its just a text input field with ajax query on keydown event. Maybe N1 could postpone the ajax GET for a second or two while a user types characters to improve the performance when fetching old recipient email ID's. 


OSX 10.10.5 Yosemite
