### ISSUE TITLE
where is the mass email icon for mail merge? for el capitan and N1 trial 

### ISSUE THREAD

**Issue by apollo1244** [nylas/N1#2887]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
![screen_shot_2016-10-01_at_1_11_35_pm](https://cloud.githubusercontent.com/assets/8452682/19016763/b40a224a-87d8-11e6-8acd-164daae2a3af.png)

It's that one!
