### ISSUE TITLE
Bug: interfaceZoom setting does not stick

### ISSUE THREAD

**Issue by molstrangler** [nylas/N1#2890]
**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I noticed when upgrading to the latest release ( ) the setting would stick for a short time then N1 would reset to the default zoom level.

What I could see it it reset the default value when I clicked on an unread email folder for an account that had no emails to display and N1 displays the 'tick' graphic.

**Comment by jackiehluo** [comment]
Merging into #2873!
