### ISSUE TITLE
Sent item not appearing in send folder

### ISSUE THREAD

**Issue by hallamoore** [nylas/N1#2892]
Mail sent from N1 is successfully sent, but doesn't appear in the send folder for N1 nor gmail.

Zendesk ticket: https://nylas.zendesk.com/agent/tickets/6460

**Comment by jackiehluo** [comment]
Merging into #2798!

**Comment by hallamoore** [comment]
I thought that issue was different. The original zendesk ticket for that issue seems to imply that the email he responded to disappeared, not that the email he wrote disappeared.

**Comment by jstejada** [comment]
Re opening as these 2 are different issues

**Comment by jstejada** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/6529

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/6461

**Comment by jstejada** [comment]
Another incidence https://nylas.zendesk.com/agent/tickets/6599

**Comment by jstejada** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/6571

**Comment by jstejada** [comment]
Another incidence: https://github.com/nylas/N1/issues/2905

**Comment by hallamoore** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/6611

**Comment by jstejada** [comment]
Another incidence from @pfista

**Comment by smithtimmytim** [comment]
I have this issue too. Interestingly, the message appears in the sent folder for a second or two, then disappears.

**Comment by khamidou** [comment]
Hiya --- we've just shipped a fix for this issue! I'm going to close it now, but let me know if it happens for another Gmail account!

Cheers,
