### ISSUE TITLE
Feature Request: Desktop notifications on/off by account

### ISSUE THREAD

**Issue by sachinag** [nylas/N1#2893]
As a user, I'd like to be able to turn notifications on or off per synced email address.  In my case, I'd like to have notifications on for my work account but have them off for my personal account.  For now, it appears that notifications are all or none.

![monosnap 2016-10-03 16-16-55](https://cloud.githubusercontent.com/assets/204258/19057465/e3ad8746-8984-11e6-8673-5d0e2276e6da.png)

**Comment by jackiehluo** [comment]
Merging into #741! 🙂
