### ISSUE TITLE
Evernote is not working

### ISSUE THREAD

**Issue by unleashed13** [nylas/N1#2897]
Evernote is not working, became just a beautiful elephant icon on Nylas N1. I click on it, and nothing happens. Please advise as I need it for work. Using Mac.

##### Are there any related issues?

...

##### What operating system are you using?
Mac OS10.12.

##### What version of N1 are you using?
0.4.56...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hi @unleashed13 — I haven't heard of Evernote interacting with Nylas N1 before. Can you try opening `Console.app` and see if any messages appear when you launch N1 or Evernote? If you've recently updated to Mac OS X Sierra, it's also possible that you need to re-install or update Evernote.

**Comment by bengotow** [comment]
(Will re-open if this is still happening)
