### ISSUE TITLE
Update README.md to indicate node version requirements

### ISSUE THREAD

**Issue by gardner** [nylas/N1#29]
Multiple submitted issues are rooted in the node version requirement. Please update the README.md to include this information.

**Comment by bengotow** [comment]
Hey @gardner thanks for bringing this up. I've put a big, bold note above the instructions on  https://github.com/nylas/N1/blob/master/CONTRIBUTING.md. Hopefully that will help! I think we'll need to make more changes in the next few days as people check out the source.
