### ISSUE TITLE
New Feature: Postpone mail later

### ISSUE THREAD

**Issue by rspt** [nylas/N1#290]
The basic idea is to postpone a mail to a date in order to achieve inbox zero.
Can also be useful if we have shortcuts as tomorrow, next week and so on.

E.G.
I receive a mail for my work but it's my day off, I can postpone it to my next working day.

**Comment by bengotow** [comment]
Hi @rspt — this is a great idea. I've added it to our open source roadmap—feel free to upvote it there if you have a Trello account! https://trello.com/c/GrSQUA1P/45-snooze-mail-until-a-later-time

**Comment by rspt** [comment]
Thanks! And congrats for the work!

**Comment by emorikawa** [comment]
Merged into #105

**Comment by jstejada** [comment]
this has landed in the latest release! enjoy!
