### ISSUE TITLE
Option to view raw message

### ISSUE THREAD

**Issue by light2yellow** [nylas/N1#2901]
Please, consider adding this feature. This is a real must-have. Or I was just too stupid not to find it. What I want is to be able to view message headers etc.

**Comment by jackiehluo** [comment]
It's hidden because the vast majority of users don't need to see it, but if you click between the date stamp for a message and the reply button, you can find a little menu with "Show Original"!

**Comment by light2yellow** [comment]
Omg. Thanks, but... it is REALLY a hidden one. Maybe at least making possible to right-click onto the whole message box and showing these options additionally to 'Copy' there? I'm not insisting in any way, just some day you may get tired of replying on such questions.

**Comment by jackiehluo** [comment]
Hm, what's your use case? Why do you need to see the raw message?

**Comment by light2yellow** [comment]
I used it to send message headers to my friend, his mails are constantly getting into spam. But still. In yahoo's web view there's a button called 'More' and there is the same option. It took me about a second to find it, because it's near the 'Reply', 'Reply All' etc. I agree, this is not a commonly used feature, but still - it should be accessible. At least that 3x3 or whatever pixel area should be marked as clickable.

**Comment by ArchangeGabriel** [comment]
I, for one, often need to look at headers to check which path the mail did go through, whether SPF/DKIM/Whatever were correctly validated, etc.

**Comment by grinich** [comment]
@ArchangeGabriel how do you check they are validated?

**Comment by KevinMartin** [comment]
Some servers/software put headers in the email before storing it. Spamassassin does this. ie:

```
Authentication-Results: mx.internal.tiliq.com;
	dkim=pass (1024-bit key; unprotected) header.d=example.com header.i=@example.com header.b=dhDvzMIx;
	dkim-atps=neutral
X-Spam-Level: *
X-Spam-Status: No, score=1.1 required=5.0 tests=HTML_MESSAGE,MIME_HTML_ONLY,
	RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H4,RCVD_IN_MSPIKE_WL,SPF_PASS,TXREP,
	T_DKIM_INVALID,URI_TRY_3LD
X-Spam-Virus: No
Received-SPF: Pass (sender SPF authorized) identity=mailfrom; client-ip=208.117.52.29; helo=o1.email.example.com; envelope-from=bounces+66871-5b52@email.example.com; receiver=user@example.com 
```

`Authentication-Results` can contain info from DKIM, DMARC, SPF, etc.
`X-Spam-*` are Spamassassin specific headers.
`Received-SPF` is from SPF validation.

A lot of the popular email services use these or similar headers, as well.

Here is an example from an email in Gmail coming from Hotmail:
```
Authentication-Results: mx.google.com;
       dkim=pass header.i=@hotmail.com;
       spf=pass (google.com: domain of user@hotmail.com designates 65.55.111.163 as permitted sender) smtp.mailfrom=user@hotmail.com;
       dmarc=pass (p=NONE dis=NONE) header.from=hotmail.com
```

**Comment by KevinMartin** [comment]
On a side note: Outlook has this feature when you right click on an email message and choose View Source. Gmail also has this when you click the dropdown and choose Show Original. Thunderbird and a lot of other email clients have this. Never has hidden as Nylas has it.

Plus lots of people who use Nylas are more savvy than the average email client user. Don't see a need to have it hidden.
