### ISSUE TITLE
Email lost as well, without any sending error

### ISSUE THREAD

**Issue by light2yellow** [nylas/N1#2905]
##### Are there any related issues?

Composing new messages

##### What operating system are you using?
Arch Linux

##### What version of N1 are you using?
0.4.56-816edde (and *please* make it copyable so I don't have to remember it)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Could be, the issue has occurred with my university's mail (custom email provider).

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Open "Compose new message", then close the Nylas window under it (I mean, you will be left with this "Compose new message" window exclusively and the program will run intro tray). Send a message. Sending silently fails (however, nylas thinks everything is ok, that's why I call it "silently"). It will nor be displayed anywhere neither saved internally by Nylas. This is very bad.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
The intended behavior should be saving to drafts every second or two. The emails are important. At least Nylas should create it's own Drafts folder for every email account and save all emails being composed there. It'd be even better if Nylas detects a Draft folder of a generic email provider and syncs with it.

**Comment by light2yellow** [comment]
Sorry, it was successfully sent (but nothing looked like it was, just no footprint at all, in all folders).

**Comment by jstejada** [comment]
duplicate of https://github.com/nylas/N1/issues/2892
