### ISSUE TITLE
Propose Times to Meet ('Today' = 1 yr off (2015))

### ISSUE THREAD

**Issue by mrvs70** [nylas/N1#2906]
##### Are there any related issues?

Yes, N1 crashes when I close the calendar window
This crash might be related to "Tabs don't work on macOX Sierra
![screen shot 2016-10-06 at 09 20 03](https://cloud.githubusercontent.com/assets/22654416/19143768/4a5972a2-8ba6-11e6-8857-3f7b9c1b8d97.jpg)
"

##### What operating system are you using?
macOX Sierra

##### What version of N1 are you using?
Version 0.4.56-816edde (0.4.56-816edde)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Accept from the pre-installed: Squirt

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes,  every time!
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
Merging into #2814.
