### ISSUE TITLE
30 day trial i'm not convinced

### ISSUE THREAD

**Issue by nativeimaging** [nylas/N1#2908]
I hoped this this product was as good as it sounds on its features page, but unfortunately was not able to enjoy features due to all the simple bugs that plague this software. I have a list of about 200 bugs, most of which I have no time to contribute here towards that would be a part time job in itself... I can't see paying $90 a year for something that hasn't been fixed yet. Maybe in 12 months. Thats the main problem here is this is something that should be free or next to free. I pay less for hosting.

**Comment by jackiehluo** [comment]
Thanks for the feedback! We think there's value in creating an email client with features that make your email more useful—but we realize that not everyone feels that way! Going to close this issue because it's not an actionable bug or enhancement request.
