### ISSUE TITLE
gmail keyboard shortcuts set doesn't work like gmail

### ISSUE THREAD

**Issue by huang47** [nylas/N1#291]
more like a feature request than a bug report since N1 doesn't claim it supports full set of gmail keyboard shortcuts yet.

1. using `o` doesn't open email like gmail does
2. doesn't support "all" filter yet? for anything like `*a` which doesn't select all

**Comment by bengotow** [comment]
Gmail shortcut support was dramatically expanded in 37e3fe0f4533ee5139cf0c27ee8cf9a008bc4ffe and will be pushed out in the next release. I know this includes `o` to open emails.

We don't currently support select-all, but as soon as we do, we'll add Gmail shortcuts for that as well.
