### ISSUE TITLE
Issues with compiling N1

### ISSUE THREAD

**Issue by haydenbjyoung** [nylas/N1#2912]
##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
The current developer version, cloned directly from the git repo.

When I run `script/bootstrap` in the N1 folder, this is the output. I am not sure why this is failing, please help!

`mirukai@hayden-ubuntu1:~/N1$ script/bootstrap
Node: v6.7.0
npm: v3.3.10

---> Installing N1 build tools
     This goes inside the 'build' folder and runs 'npm install'
     It will use the system 'npm' to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via 'npm'.
     Everything else needs to be compiled against Chromium with 'apm'.

     $ npm --userconfig="/home/mirukai/N1/.npmrc" install --loglevel error --cwd="/home/mirukai/N1/build" --ignoreStdout=true 

Ignoring node_modules, which is missing.
Running "add-nylas-build-resources" task
No extra Nylas resources added

Done, without errors.

---> Installing apm
     This installs apm via N1's 'npm'
     We use this local apm copy to install all N1 dependencies & packages

     $ "/home/mirukai/N1/build/node_modules/.bin/npm" --userconfig="/home/mirukai/N1/.npmrc" --target=0.10.40 install --loglevel error --cwd="/home/mirukai/N1/apm" --ignoreStdout=true 

Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing 'gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: 'gyp' failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/mirukai/N1/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-38-generic
g'yp ERR! command "/usr/bin/nodejs" "/home/mirukai/N1/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mirukai/N1/apm/node_modules/keytar
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/home/mirukai/N1/build/node_modules/.bin/npm" "--userconfig=/home/mirukai/N1/.npmrc" "--target=0.10.40" "install" "--loglevel" "error"
npm ERR! node v6.7.0
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/mirukai/N1/apm/npm-debug.log`

Any ideas? This is the full output of the command.

**Comment by bengotow** [comment]
Hi—it looks like you may need to install `gnome-keyring-1` - can you try that and report if it's still an issue?

**Comment by haydenbjyoung** [comment]
Running `sudo apt install gnome-keyring-1` returns `E: Unable to locate
package gnome-keyring-1`...

Halpu meh?

**Comment by haydenbjyoung** [comment]
Hang on, it was libgnome-keyring-dev I needed to install... Ha... Ha...

**Comment by haydenbjyoung** [comment]
Oh, wait. After re-running it, this is the new output:

---> Cleaning apm via `apm clean`


module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mirukai/N1/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/mirukai/N1/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by haydenbjyoung** [comment]
Oh, it works when running as Sudo.

**Comment by bengotow** [comment]
Hi @haydenbjyoung glad that did the trick! If you run into trouble compiling native modules, it's sometimes also necessary to clean the working copy and start script/bootstrap again from scratch, since temp files left behind could have been built partially or incorrectly. `git clean -xdf` is a great way to do that.

Glad you got it working!
