### ISSUE TITLE
Backspace to trash

### ISSUE THREAD

**Issue by ChainsawBaby** [nylas/N1#2913]
None of the preformatted text suits my question.
Is it possible, when I press backspace, that the emails are moved to trash, rather than archive?
As I prefer to store important emails in the archive, and put the rest in trash?

Is this available?

**Comment by jackiehluo** [comment]
If you go to Preferences -> General, you can change that!

<img width="449" alt="screen shot 2016-10-09 at 11 24 08 am" src="https://cloud.githubusercontent.com/assets/8452682/19221517/ea9ca8ba-8e12-11e6-9864-bb0b06033f7d.png">

**Comment by ChainsawBaby** [comment]
Heh, would you look at that!
Completally missed that option. Thanks!
