### ISSUE TITLE
Too many IDLE processes

### ISSUE THREAD

**Issue by Artjaazz** [nylas/N1#2921]
My website hosted with SiteGround gets 500 Internal error and goes offline
The reason being too many running IDLE processes (company allows up to ~35)
 
The support suggested I adjust the settings in my email client which is Nylas..
And I can nowhere find any related option

Could you suggest a fix or add such an option?

For example, Mailbird has an option to reduce the number of concurrent processes (from 5 to 2)

Thanks

**Comment by bengotow** [comment]
Hey! I think you're talking about the number of IDLEing IMAP clients. N1 only uses three, so you should be OK. It's possible that if you're using many mail clients (on your phone, Nylas, Mailbird, etc.) that they add up to 35 and Nylas tipped you over the edge! Sorry for the hassle, but there's not much we're able to change on our end.
