### ISSUE TITLE
N1 ignores CR/LF in mailto links

### ISSUE THREAD

**Issue by pfista** [nylas/N1#2923]
##### What operating system are you using?
OSX El Capitan 10.11.6 (15G1004)

##### What version of N1 are you using?
Version 0.4.56-816edde (0.4.56-816edde)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

With N1 as the default client: clicking this link should produce a message with several separate lines, but N1 includes all the lines together, ignoring the percent encoded CR/LF characters.

[mailto:test@test.com?Subject=Test&Body=Line%20One%0ALine%20Two%0A%0ALine%20Four](mailto:test@test.com?Subject=Test&Body=Line%20One%0ALine%20Two%0A%0ALine%20Four)

**Comment by bengotow** [comment]
Does 

mailto:test@test.com?Subject=Test&Body=Line%20One%0DLine%20Two%0D%0DLine%20Four

work?

**Comment by bengotow** [comment]
I've confirmed that this does work in Mail.app:
```
open "mailto:test@test.com?Subject=Test&Body=Line%20One%0ALine%20Two%0A%0ALine%20Four" -a Mail.app
```

N1 currently treats the body as HTML, meaning line breaks have no effect, but things like `<br>` tags work: `open "mailto:test@test.com?Subject=Test&Body=Line%20One%0DLine%20Two%0D%0DLine%20Four<br>Hi"`.

I think this is nice, but it is non-standard. For backwards compatibility with other clients, we should definitely support the line breaks and treat the body as plain text when no HTML is present.
