### ISSUE TITLE
Support native tabs (macOS Sierra) in Nylas

### ISSUE THREAD

**Issue by gielcobben** [nylas/N1#2924]
##### What operating system are you using?
macOS Sierra 10.12

##### What version of N1 are you using?
Version 0.4.56-816edde (0.4.56-816edde)

--

##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="421" alt="screen shot 2016-10-14 at 17 27 05" src="https://cloud.githubusercontent.com/assets/2663212/19393057/754ee698-9233-11e6-9ce5-610f8bba48f7.png">

With the new macOS Sierra come tabs: 
_"Now it’s easy to keep windows from piling up on your desktop. Tabs work just as they do in Safari — but now they work in most apps on your Mac, and in many third-party apps as well."_

Zo when I want to create a new email the window opens in a new tab inside Nylas. There seems something wrong with the styling of the top bar. This may be related: https://github.com/electron/electron/issues/6124

<img width="1255" alt="screen shot 2016-10-14 at 17 25 53" src="https://cloud.githubusercontent.com/assets/2663212/19393023/5afaa5e8-9233-11e6-89b1-21258188212d.png">

**Comment by dubstrike** [comment]
I believe this only works for apps written in Objective-C, and not with the Electron shell.

**Comment by jstejada** [comment]
merging into #2904
