### ISSUE TITLE
N1 needs to have skin tone options for emoji

### ISSUE THREAD

**Issue by sachinag** [nylas/N1#2927]
##### Are there any related issues?

...

##### What operating system are you using?
Mac OS 10.11.6 El Capitan

##### What version of N1 are you using?
0.4.56-816edde (0.4.56-816edde)
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yup - 
https://www.dropbox.com/s/kcbgc34rliewtd9/Screenshot%202016-10-14%2015.58.12.png?dl=0

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

N1 needs to support skin tones the way that Slack does, and have a default skin tone for all emoji that support skin tones 
...

**Comment by jackiehluo** [comment]
Hey! I think we're blocked on Electron with that (https://github.com/nylas/N1/issues/72).
