### ISSUE TITLE
Portuguese language

### ISSUE THREAD

**Issue by hamiltoncolares** [nylas/N1#293]
There errors when typing in Portuguese. Accentuation does not work work properly. 
<img width="1280" alt="captura_de_tela_2015-10-29_as_22_43_34" src="https://cloud.githubusercontent.com/assets/723415/10835927/db36e596-7e8e-11e5-884e-b2903faf32e0.png">

**Comment by bengotow** [comment]
Hi @hamiltoncolares — thanks for filing this. I think this is a duplicate of https://github.com/nylas/N1/issues/62. We're working on a fix right now and it should be resolved in the next update. Stay tuned!

**Comment by hamiltoncolares** [comment]
Thanks @bengotow.
