### ISSUE TITLE
iso-2022-jp encoding emails not displaying correctly

### ISSUE THREAD

**Issue by inket** [nylas/N1#2931]
##### Are there any related issues?
Not that I'm aware of.

##### What operating system are you using?
macOS Sierra

##### What version of N1 are you using?
Version 0.4.56-816edde (0.4.56-816edde)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Yes, but they're all themes. Email still shows up incorrectly using the default theme.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure. The email is on Outlook and shows up fine on the Outlook web app though.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It's an S/MIME signed message and its content starts with
```
Content-Type: text/plain; charset="iso-2022-jp"
Content-Transfer-Encoding: 7bit
```

Here's what some of the text looks like

<img width="501" alt="screen shot 2016-10-17 at 1 15 39pm" src="https://cloud.githubusercontent.com/assets/679224/19425465/b92a5dac-946d-11e6-97d5-9aa2048f7a1d.png">

Can't provide more as it's a sensitive email.

--

**Comment by bengotow** [comment]
Wow - thanks for reporting this! I think this is definitely an issue with our underlying sync engine. I'm going to transfer this Github issue to that repo. https://github.com/nylas/sync-engine/issues/408
