### ISSUE TITLE
Links inside the messages not opening with Firefox

### ISSUE THREAD

**Issue by light2yellow** [nylas/N1#2932]
*Version*: 0.4.56-816edde

Pressing on a link in any email does nothing. However, this works with chromium. There are my preferred applications.

![screenshot_2016-10-17_14-48-09](https://cloud.githubusercontent.com/assets/10786469/19438472/68a3fa0c-947a-11e6-8e31-7dbef2707fae.png)

**Comment by bengotow** [comment]
Thanks for reporting this. It sounds like this is a recurrence of #620. I'm going to re-open that issue and merge this in, since there's more debugging and context there.
