### ISSUE TITLE
Latest beta-version has crippled composition window.

### ISSUE THREAD

**Issue by matiasvad** [nylas/N1#2935]
When replying to an email it simply halts when inputting text, and is veeeery slow at showing the input, crippling the whole process.

The styling in the window has also been degraded.
![screenshot 2016-10-18 10 20 18](https://cloud.githubusercontent.com/assets/1929609/19469664/8ca65402-951c-11e6-85b5-717ba2c20d84.png)

##### What operating system are you using?
MacOS Sierra 10.14

##### What version of N1 are you using?
Version 0.4.57-c0aad93 (0.4.57-c0aad93)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I'm using Gmail.

**Comment by grinich** [comment]
Hi @matiasvad 

You are running the Beta release, which sometimes is unstable and has bugs we are working to fix.

You can change back to the stable release in the preferences window.

![image](https://cloud.githubusercontent.com/assets/92417/19487814/30aa58ea-9519-11e6-8ebd-708b985f5586.png)
