### ISSUE TITLE
Very very slow editor

### ISSUE THREAD

**Issue by adriaanmol** [nylas/N1#2940]
Sometimes the mail editor is very very slow. Especially in long threads (I noticed). I got the feeling that in the last beta this has increased a lot.

**Comment by emorikawa** [comment]
@adriaanmol we found a bug in the latest Beta where the spellchecker on Mac was drastically slowing down the composer. This will be fixed in the next beta and stable release.

**Comment by adriaanmol** [comment]
Hi! Nice to hear that. I must say that I also had this in previous stable releases in same cases. But since the last beta it became really slow. I support it has more reasons that it's slow, or maybe this fix covers also the issues of before?

**Comment by jkmaxwell** [comment]
Can we disable anything in the meantime to prevent it?

**Comment by jackiehluo** [comment]
@jkmaxwell Disabling spellcheck should work? You can do that in the preferences!

**Comment by adriaanmol** [comment]
I really noticed the longer messages get (for example when you forward a long conversation) everything in view list/composer gets laggy and getting slow. This was also in early stable releases. The spellcheck update seems to make it even worse.

Maybe this information helps for more optimisations.

**Comment by bengotow** [comment]
Hey folks! This has been greatly improved from 0.4.58 => 0.4.59. (We added a cache over the native spellchecker APIs on Mac OS X). There are still some smaller performance issues we'll be investigating in the next release, but I'm going to go ahead and close this.

**Comment by adriaanmol** [comment]
The composer is still very slow on version 0.4.59-cae9ef1.

**Comment by samgabell** [comment]
Still unusable on Sierra with 0.4.59-cae9ef1 for me.

**Comment by jcherniak** [comment]
I'm still seeing this in the 2.x branch on Windows.  I often have to resort to typing messages in Notepad and copy/pasting them over.  Any ideas?
