### ISSUE TITLE
Add m for mute to Gmail shortcuts

### ISSUE THREAD

**Issue by sachinag** [nylas/N1#2943]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS

##### What version of N1 are you using?
Current
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Standard Gmail keyboard shortcut: https://support.google.com/mail/answer/47787?hl=en

**Comment by jackiehluo** [comment]
So the relevant issue is probably https://github.com/nylas/N1/issues/764—we can't add the shortcut for mute until we add the underlying functionality. I took a look at how Gmail implements it, and it looks like they just use a "mute" label and essentially add a mail rule that automatically adds the label on receiving an email in the muted thread.
