### ISSUE TITLE
Nylas N1 Crashes on macOS Sierra when sending message fullscreen.

### ISSUE THREAD

**Issue by elebumm** [nylas/N1#2959]
Just like the title implies. Whenever I have Nylas N1 open in fullscreen and send a message, it will cause Nylas to crash. This has been happening since I have installed macOS Sierra. More specifically I think it's because of the "tabbed" fullscreen feature that was just recently implemented in the macOS Sierra update. A couple images for anyone that's confused about the tabbed fullscreen feature I am talking about.

![screen shot 2016-10-22 at 1 38 01 pm](https://cloud.githubusercontent.com/assets/6053155/19621299/d8a7f4a8-985c-11e6-9324-fe31977025a7.png)

and on send:

![screen shot 2016-10-22 at 1 39 36 pm](https://cloud.githubusercontent.com/assets/6053155/19621308/fdc5c378-985c-11e6-941e-1ccdcfa17f76.png)

I love Nylas N1! Thank you so much for such amazing software.

**Comment by jackiehluo** [comment]
Merging into #2792. And glad you're enjoying it!
