### ISSUE TITLE
Feature request: Quick Look for attachments on macOS

### ISSUE THREAD

**Issue by xhaavardx** [nylas/N1#2961]
Using version 0.4.58-c6e4f3d

**Feature Request**
Nylas is wonderful so far! The one thing I'm missing the most however is Quick Look on attachments like you find in Apple's mail app and Polymail 2. [Here](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/Quicklook_Programming_Guide/Introduction/Introduction.html) is the link to the developer guide for Quick Look
##### Does this feature exist in another mail client or tool you use?
Polymail 2, Mail (Apple)

**Comment by bengotow** [comment]
Merging into #1086 - coming very soon!
