### ISSUE TITLE
Save emails on another gmail account

### ISSUE THREAD

**Issue by sergiootorre** [nylas/N1#2967]
Nylas need to add ability to transfer a specific email to another email account like airmail does and add colours to accounts on inbox.

**Comment by bengotow** [comment]
Thanks for the feedback! These are already github issues: #1677 and #678. Please search for existing issues! Merging into those.

**Comment by sergiootorre** [comment]
Hello!

Thank you for helping me. First time i’ve used Github and using a
smartphone for that. Next time, i will check better. Thanks!

Sérgio

Ligado 25 de outubro de 2016 no 19:46:55, Ben Gotow (
notifications@github.com) escreveu:

Closed #2967 <https://github.com/nylas/N1/issues/2967>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nylas/N1/issues/2967#event-835956449>, or mute the
thread
