### ISSUE TITLE
keyring popup disable?

### ISSUE THREAD

**Issue by abhigenie92** [nylas/N1#2971]
##### What operating system are you using?
kde-neon(ubuntu 16.04)
##### What version of N1 are you using?
The latest one from github releases

The password management error went by installing keyring. But now I get the below whenever launching nylas. ( I am using auto-login for the machine.)
![image](https://cloud.githubusercontent.com/assets/12474640/19789722/ba6cf0de-9ccf-11e6-9d15-1725bbe1c580.png)

Anyway to prevent this popup?

**Comment by bengotow** [comment]
Hi @abhigenie92 sorry for the hassle - N1 stores mail API tokens and other sensitive passwords in your system keychain. It's strange that the gnome keychain isn't already unlocked when you launch N1, but it's possible that you're not using it for anything else. It might be worth taking this up with the folks maintaining node-keytar, and see if they can fast-track support for KDE: https://github.com/atom/node-keytar/issues/17
