### ISSUE TITLE
Don't display a notification if Mail Rule will put message in folder, archive, or trash

### ISSUE THREAD

**Issue by sachinag** [nylas/N1#2974]
I will get notifications on my Mac for messages where I have a Mail Rule to automatically put the message in a folder, archive the message, or trash the message.

**Comment by hallamoore** [comment]
Merging into #2625

**Comment by sachinag** [comment]
Dammit I searched. I need to search better. Sorry!

**Comment by hallamoore** [comment]
Haha, no worries!
