### ISSUE TITLE
Set a "don't remind me again" bit when dismissing UnstableChannelNotification

### ISSUE THREAD

**Issue by emorikawa** [nylas/N1#2975]
https://nylas.zendesk.com/agent/tickets/6886

**Comment by v4n** [comment]
The pre-release channel is now showing 2 notifications: "sale-force trial" & "you are on a pre-release channel". It's incredibly annoying having to close both every-time I open the app.

**Comment by bengotow** [comment]
This should be fixed by https://github.com/nylas/n1/commit/3a8ca13. You'll still see two, but they won't re-appear every time you launch the app!

**Comment by jstejada** [comment]
This has been released today!
