### ISSUE TITLE
Double window bar bug 

### ISSUE THREAD

**Issue by reyman** [nylas/N1#2976]
##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
0.4.59 

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Nop

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Strange, this bug is random, but it exist : 

![doublerainbow](https://cloud.githubusercontent.com/assets/466329/19758473/811f175a-9c28-11e6-9261-1819cad2c059.jpg)

**Comment by bengotow** [comment]
Hey! This is actually expected behavior at the moment - see conversation here: #1250. Gonna merge this into that!
