### ISSUE TITLE
Bug: Wrong folder contents after correcting e-mail credentials

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#2977]
Hi there,

I had kind of a bit of trouble about two weeks ago with my two e-mail accounts, so I had to re-add them to N1. After putting in the wrong credentials for the second account (i.e. the credentials from the first account), e-mails from both accounts appear/stay on the second account, even though I corrected the credentials back.

I try to put it out in steps so you could reproduce and understand what happened:

1.) E-Mail account A und B got connection problems, since the provider denied access (due to a failure on their side). N1 notifies me of the problem.
2.) I got it sorted with the provider, other e-mail clients then sync well again, but N1 still reports it has no connection, even hours after having re-established the logins.
3.) Since I didn't know better, I tried to 'change' the login details for both accounts in order to be able to connect again within N1. It basically means re-adding accounts in the settings, so I did. Re-added account A and B with the former data (almost, see below). N1 begins to re-sync the mailboxes.
4.) Accidentally, I encountered I entered the wrong login username and password combination for account B, which were then the same as for account A, like this:

*Account A*
E-Mail: accountA@domain.com
User: accountA@domain.com
PW: ******
…

*Account B*
E-Mail: accountB@domain.com
User: **accountA**@domain.com
PW: ****
…

5.) This resulted in both accounts having the exact same folder and e-mail structure in the beginning. At least for the folders I looked into (see below).
6.) I realised the mistake and changed account B to the correct login credentials, but afterwards N1/Nylas doesn't wipe the wrong e-mail data off its cache, but rather keeps it and only adds new e-mail (the mail for the now correct account B) on top of it. Even on my secondary computer. Even after almost two weeks.
The thing is, it is only that way for *some* of the folders. As far as I can tell, this holds true for starred, sent mail and the inbox which are now a mix of e-mails from both accounts. The archive and my other custom folders are not affected. I would assume I possibly clicked on the three items (starred, sent, inbox) so pulled e-mail for it, or synchronising didn't get as far as the archive and my custom folders when I had put in the wrong credentials and then corrected them back (possibly interrupted the syncing).
7.) Other e-mail clients show the right content for starred, sent and inbox of account B. Nylas keeps the wrong cached data, but adds no new 'wrong' mail to account B's starred, sent and inbox folders since I corrected the credentials.

And the usual: Being on the Beta channel, using Windows 10 x64 (latest updates) 😉 .

All the best

Eno

**Comment by hallamoore** [comment]
Woah, that's an interesting one! We probably won't make any changes to the general caching behavior since this is a rare scenario, but you should be able to fix your accounts by clicking the "Reset Email Cache" button at the bottom of the general preferences tab. Let us know if that doesn't fix it!

**Comment by enoversum** [comment]
@hallamoore Hi there, thanks for taking notice of the bug 😄 . I just tried your workaround 'Reset Email Cache', but at least in the last beta, it doesn't change a thing, N1 doesn't even indicate it syncs the mailbox or anything after hitting the button in settings.

**Comment by hallamoore** [comment]
Hmm, that's a little weird. It is suspicious that you didn't see any re-syncing, but it may be possible that it just happened really fast. Do you mind sending the affected email address to support@nylas.com, so we can try to narrow down whether it's an issue with the sync backend or an application level bug? Thanks!

**Comment by enoversum** [comment]
@hallamoore Yes, I did hit that button quite hard multiple times. I have two really big e-mail accounts hosting e-mail from at least 12 years. No indication of a re-sync on both of my computers, and no change on what is visible in my inbox. Will send over the e-mail address as suggested, thank you 😄 .
