### ISSUE TITLE
In Search bar, on Dark color, the letter remain on dark color

### ISSUE THREAD

**Issue by jorosmtz** [nylas/N1#299]
When I use the Dark theme, on the Search bar, when I type the letter remain on dark color.

**Comment by artagnon** [comment]
Dark color scheme is unusable because of this:

<img width="456" alt="screen shot 2015-11-05 at 4 40 18 pm" src="https://cloud.githubusercontent.com/assets/37226/10982580/07fff656-83dc-11e5-87e1-63c3dba3d4ce.png">
