### ISSUE TITLE
Feature Request: Threads in different languages

### ISSUE THREAD

**Issue by ChainsawBaby** [nylas/N1#2992]
I have this problem where when I reply to mails, the subject becomes RE: and creates a thread.
But some of my clients, use norwegian version of RE, so it becomes SV, and then creates a separate thread. So Now I got several threads with 2 emails in it, yet it should've really been 1 thread.

So maybe you could change in the settings, which prefix replies should use?
Or add multiple version of it, so it looks from "RE" and "SV" and whatever other languages might use

**Comment by jackiehluo** [comment]
Merging into #2500.
