### ISSUE TITLE
Feedback prompt should be lifetime dismissible 

### ISSUE THREAD

**Issue by v4n** [nylas/N1#2993]
On the pre-release channel when you dismiss the prompt it goes away until you quit the app 
<img width="176" alt="screen shot 2016-10-30 at 1 44 34 am" src="https://cloud.githubusercontent.com/assets/6045161/19833458/6cda3ca4-9e42-11e6-9685-0307571b798f.png">

When you restart the app it comes back. Ideally the dismiss stick across sessions.

**Comment by bengotow** [comment]
Merging into #2975
