### ISSUE TITLE
Error when sending emails offline

### ISSUE THREAD

**Issue by JanSebastian** [nylas/N1#2994]
Hi there,

I'm getting the following error when I try to send an email while not being connected to the internet:

Error: Sorry, this message could not be sent. Please try again, and make sure your message is addressed correctly and is not too large.

It works perfectly fine, when I'm connected to the internet.

The activity window shows:

ENOTFOUND | getaddrinfo ENOTFOUND api.nylas.com api.nylas.com:44311:58:36  RunCopycurl -X POST -d '{"client_id":"xxxxx","object":"draft","account_id":"xxxx","metadata":[],"to":[{"client_id":"xxxxx","server_id":"xxxxx","object":"contact","account_id":"xxxx","name":"xxxx","email":"xxxx","thirdPartyData":{},"id":"xxxxx"}],"cc":[],"bcc":[],"from":[{"client_id":"xxxxx","account_id":"xxxxx","name":"xxxx","email":"xxxxx","thirdPartyData":{},"id":"xxxxxx"}],"reply_to":[],"date":1477825108.236,"body":"Test<br><br><signature>Sent from <a href=\"https://nylas.com/n1?ref=n1\">Nylas N1</a>, the extensible, open source mail client.</signature>","files":[],"uploads":[],"events":[],"subject":"Test","draft":true,"pristine":false,"categories":[],"id":"xxxxxx","file_ids":[]}' "https://api.nylas.com/send"

I found many incidents with similar error message but for me it only occurs when I'm offline. For some reason the client does not understand that it has to queue the email until it is online again.

Thanks for help

**Comment by bengotow** [comment]
Hey! This is currently expected behavior. Your message could not be sent, and N1 displays that dialog. A while back we decided not to hold email in an outbox queue, but we will definitely reviist that soon!

**Comment by bengotow** [comment]
Merging into #2590
