### ISSUE TITLE
Bug: Developer Tools Keeps Popping up

### ISSUE THREAD

**Issue by jcuenod** [nylas/N1#2997]
##### What operating system are you using?
Linux, 4.8.4-1-ARCH

##### What version of N1 are you using?
0.4.56-816edde

##### Bug:

Developer tools keeps popping up - it seems to do this whenever an error is logged but I can't find a way of stopping it from popping up (i.e. even if I close it, it will reopen whenever an error is logged out).

**Comment by jackiehluo** [comment]
Could you update to the latest version? This bug should be fixed!

**Comment by jcuenod** [comment]
Humblest apologies. I've upgraded, thanks :)
