### ISSUE TITLE
Ubuntu 14.04 startup error

### ISSUE THREAD

**Issue by SergeyPirogov** [nylas/N1#2998]
On ubuntu 14.04 it fails on startup with the following error:

Unable to watch path: config.json. Make sure you have permissions to
      /home/sergey/.nylas/config.json. On linux there are currently problems with watch
      sizes.

**Comment by jackiehluo** [comment]
Can you send us an email at support@nylas.com with more details?

**Comment by roelvan** [comment]
@jackiehluo  I have the same problem on Ubuntu 16.10.
![untitled window_011](https://cloud.githubusercontent.com/assets/2583837/24034402/834e43a6-0af1-11e7-93cf-36e252d1397a.png)
