### ISSUE TITLE
Nylas N1 window on app launch is off screen when using multiple screens

### ISSUE THREAD

**Issue by johnend** [nylas/N1#2999]
##### What operating system are you using?

macOS Sierra 10.12.1

##### What version of N1 are you using?

Version 0.4.59-cae9ef1
 
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Issue is reproducible on every instance of app launch including when launching on startup.

N1 window is over to the right hand side of the main desktop (see screenshot) and can only be moved by using window > zoom from the menu bar.

![screen shot 2016-10-31 at 10 16 27](https://cloud.githubusercontent.com/assets/3886057/19851202/9a76e230-9f54-11e6-8119-8a81bed4bdb4.png)

N1 is assigned to be on desktop 2 (laptop screen not the main monitor).

While this is only an inconvenience it is a little annoying to have to go through every time I start the app.

**Comment by jackiehluo** [comment]
Merging into #58!
