### ISSUE TITLE
compose window always opens on different screen

### ISSUE THREAD

**Issue by sachinag** [nylas/N1#3002]
I use 2 monitors with my computer (one is a big screen to watch movies). When I want to write a new message, Nylas N1 opens a window on the 2nd screen - always. It is annoying. I need to drag the compose window back to main screen where I have my N1 inbox.  Can you detect which window my N1 is on and only open compose window there?

**Comment by jackiehluo** [comment]
Merging into #58! Wasn't possible at the time, I think, but should be now.
