### ISSUE TITLE
No data in sidebar tree, email list view - nothing populating

### ISSUE THREAD

**Issue by harbingerlabs** [nylas/N1#3006]
##### Are there any related issues?

Not that I found

##### What operating system are you using?
MacOS Sierra 10.12.1

##### What version of N1 are you using?
0.4.59-cae9ef1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
All the accounts are Google based - 1 regular gmail - 2 Google Apps

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Accounts simply aren't populating with data. I reverified and restarted my machine, but nothing is flowing in. All account parents are visible but don't respond to expanding.

![screen shot 2016-11-01 at 7 03 56 pm](https://cloud.githubusercontent.com/assets/4561236/19912191/c9aef192-a066-11e6-8d8c-0cf46159a6c1.png)

**Comment by jackiehluo** [comment]
Can you send us an email at support@nylas.com with what you see when you go to Developer -> Toggle Developer Tools -> Console? Thanks!
