### ISSUE TITLE
Unread Emails Bug. opens automatically.

### ISSUE THREAD

**Issue by Necmttn** [nylas/N1#3009]
##### What operating system are you using?
OSX EL CAPITAN 10.11.6 (15G31)

##### What version of N1 are you using?
Version 0.4.59-cae9ef1 (0.4.59-cae9ef1)
--

When i in unread email section.  if i click one of unread emails nylas started to open each email one by one its does only one direction towerds to up. 

for make it easier to understand i record this gif. 

![image](https://cloud.githubusercontent.com/assets/5212808/19956254/2ce6ac32-a1c5-11e6-8bdc-a78176d02354.png)

seemslike i can not upload gif to github so here's the imgur link to you. 

http://imgur.com/a/Xbhmo

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
NO
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
NO

##### Is the issue reproducible with a particular attachment, message, signature, etc?

NO

--

**Comment by Necmttn** [comment]
During recording gif. i only click once and i didn't touch keyboard at all 🐑

**Comment by jackiehluo** [comment]
Merging into #2271!
