### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by ohdude** [nylas/N1#3011]
##### What operating system are you using?
ubuntu 16.04

**Bug?**

I get an config error 

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/daan/Bureaublad/N1/node_modules/keytar
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "--userconfig=/home/daan/Bureaublad/N1/.npmrc" "install" "--loglevel" "error" "--cwd=/home/daan/Bureaublad/N1/build" "--ignoreStdout=true"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daan/Bureaublad/N1/npm-debug.log

```

**Comment by bengotow** [comment]
Hey! You most likely need to install the libgnome-keyring library for Ubuntu as described here: https://github.com/atom/node-keytar/issues/18

**Comment by perry-mitchell** [comment]
@bengotow Is this covered in the docs somewhere? I was unable to find anything substantial on even setting Nylas up in development, let along instructions on requirements for installation.

I too encountered this error when building for Ubuntu. It'd be great if we could prevent people encountering it in the future :smile:

**Comment by ohdude** [comment]
/\ What he was saying
