### ISSUE TITLE
Delete do not work in localised IMAP

### ISSUE THREAD

**Issue by klaszlo** [nylas/N1#3012]
##### What operating system are you using?
I'm on Ubuntu 16.04. But the same happens on Windows 7.

##### What version of N1 are you using?
0.4.59-cae9ef1, installed from N1-0.4.59.deb, from github.

##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes. 

I'm currently evaluating a possible migration from Exchange based email server.
So I migrated from one of the account all the emails from exchange using the 
offlineimap program in maildir format.
I serve this maildir using Dovecot (imap server).
I installed also the sync-engine and set up 
(unrelated: imap no encryption (143), and smtp encryption (587) do not work. 
Either both requires ssl, or neither of it.)

Remark (not related to the problem): 
I send emails through Haraka SMTP server (Exchange server sends also through this Haraka).

As both the Exchange (server) and the outlook (clients) programs are in hungarian language (Central Europe), the folder names are also in hungarian.

English name - Hungarian name - maildir foldername
Inbox - Inbox - INBOX (it is not translated in Exchange)
Sent - Elküldött üzenetek - Elk&APw-ld&APY-tt &APw-zenetek
Drafts - Piszkozatok - Piszkozatok
Spam - Levélszemét - Lev&AOk-lszem&AOk-t
Outbox - Postázandó - Post&AOE-zand&APM-
Trash - Törölt elemek - T&APY-r&APY-lt elemek

The real issue is, there is no preference in Nylas where I could assign 
which folder should be the Sent folder, Draft folder and Trash folder.

So deleting emails do not work. I can move emails manually to the "Trash" 
(note: it is in localised name) folder, 
but neither the Delete key nor any menuitem shows Delete action.

Also I'm not sure if permanent deleting is possible (deleting emails which are already in "Trash" folder).

Displaying the hungarian names works great in Nylas, all the accents are correct, so no problem there.

##### Does this feature exist in another mail client or tool you use?
Microsoft Outlook supports it, Thunderbird supports it.

I think the correct solution would be a preference panel, 
where folder names could be assigned to this special folders.
Renaming the folders in maildir are not a real solution, because migration is not possible (I want to 3-6 months parallel access to the emails), so leave enough time to collegues to learn the new email client.

I'm willing to test, and if required I can install it from git.

**Comment by bengotow** [comment]
Thanks for reporting this! I'm gonna move this over to the sync-engine repository: https://github.com/nylas/sync-engine/issues/410
