### ISSUE TITLE
Email action icons are gone

### ISSUE THREAD

**Issue by juanscv** [nylas/N1#3017]
After update, actions for email (Star, Archive, Snooze, Etc.) are no longer visible.
![nylas n1 2016-11-04 17-39-24](https://cloud.githubusercontent.com/assets/955241/20024850/2da7ef44-a2b7-11e6-8ae6-0d0c6620f865.png)

N1 version 0.4.202 Unstable Channel
macOS Sierra

**Comment by bengotow** [comment]
hey @juanscv — does the problem get fixed if you restart? I think we've had a few reports of this happening if the app was moved while it was running, or if the resources folder was updated from under it. Strange it would happen /after/ an update, though!

**Comment by juanscv** [comment]
I restarted my laptop and the problem persists.

Another issue with the update is that opening the sidebar doesn't work correctly. I have to restart the app for it to close/open after clicking the button.

**Comment by bengotow** [comment]
Hmm thanks for the info @juanscv — what theme is this? I don't think that's one of the standard ones. It's possible that it's an issue with that theme in particular.

**Comment by ChainsawBaby** [comment]
@bengotow I have the same issue on 0.4.203
I don't know if these errors are related, but I get these errors when I open an email, though it only happens once.
http://kopy.io/fBvgV#QbThPYyC9HPkq6
![Screenshot](https://i.bratteng.xyz/pMo9WOgMx0.png)

**Comment by juanscv** [comment]
0.4.204 doesn't yet fix this.

**Comment by jstejada** [comment]
if you restart N1, do you still not see the icons? Did you move the app while it was running by any chance?
@ChainsawBaby , the error you are seeing in the console is due to an issue with https://github.com/colinking/n1-unsubscribe. I believe the issue has been posted here: https://github.com/colinking/n1-unsubscribe/issues/62

@juanscv , do you see any errors in the console?

**Comment by ChainsawBaby** [comment]
@jstejada Yes, if I restart N1, I still do not see the icons. And I did not move the app while it was running.
It was working in 0.4.201. If I disable the Unsubscribe Plugin it works, I see the icons then.

**Comment by juanscv** [comment]
Thanks @jstejada they do return if I disable the unsubscribe plugin, then reload N1.

**Comment by jackiehluo** [comment]
Closing this issue, since it's a problem with a third-party plugin—we'll look into that repo!
