### ISSUE TITLE
Labelled emails don't show up

### ISSUE THREAD

**Issue by manuelmeurer** [nylas/N1#3018]
##### Are there any related issues?

Couldn't find any.

##### What operating system are you using?

macOS

##### What version of N1 are you using?

Version 0.4.201-4cdd3ed (0.4.201-4cdd3ed)

--

**Bug?**

##### Do you have any third-party plugins installed? If so, which ones?

Nope.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Maybe.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

So I just bought and installed N1 and added my Gmail account. It synced for a while and now all my mails in my inbox are there but none of my labelled mails (those with one or more labels, not in inbox). Only the labelled emails that have arrived since I installed N1 show up.

Is there anything I can do to trigger a full sync again?

**Comment by jackiehluo** [comment]
Could you send us the details with your account info to support@nylas.com?
