### ISSUE TITLE
Nylas isn't loading the email list -- n1-unsubscribe error

### ISSUE THREAD

**Issue by spott** [nylas/N1#3022]
I just updated to the "Nylas salesforce edition" (given that there is now a salesforce menu, and it asks if I want to connect to salesforce).

The version is `0.4.203-2c6ee12` on OS X Sierra 10.12.1.

When I launch, the "looking" animation (the dots fading in from the left and fading out on the right) is made where emails would normally be listed.  However it isn't going away.  I am unable to check if I have any third party plugins, because I can't open the preferences (edit: in debug mode I can see my third party plugins, all of them are themes except for the "unsubscribe" plugin).  The left hand side of the window just updated the number of emails I have, so apparently Nylas is getting the emails, it just isn't showing them.  Clicking on different folders on the left doesn't change the situation.  This doesn't go away when I attempt to restart nylas.  Reloading nylas with debug flags fixes the problem (as in the email list loads).

I refused the salesforce integration because I don't have salesforce.

Let me know if more information is needed.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - our team is looking into this right now and we'll keep you posted. It sounds like a few folks were incorrectly upgraded to the Salesforce release channel upon upgrading.

**Comment by spott** [comment]
Thanks.

Is there a way to downgrade?  Should I just downgrade?

**Comment by derpoho** [comment]
Same here.
Since the latest Update today (Salesforce).
Debug Flags Console says: http://d.pr/i/r8Dp/2BEgJEe5

please fix asap, can't read my emails.

**Comment by jstejada** [comment]
hi folks, this seems to be caused from https://github.com/colinking/n1-unsubscribe which is a 3rd party package. you should post the issue in that repo as well. Thanks!

**Comment by spott** [comment]
I have done so. [here](https://github.com/colinking/n1-unsubscribe/issues/62) is the issue.

**Comment by derpoho** [comment]
Can confirm. After uninstall of the unsubscribe package everything is working fine again.
But @jstejada , do we have any disadvantages, now that we are in the salesforce release channel?

**Comment by nton4576** [comment]
Can someone walk me through how I can manually uninstall the plugin? I can't even get to preferences right now (forever loading)

**Comment by spott** [comment]
Go into debug mode and do it there.

-Andrew

**Comment by regenhans** [comment]
Go to /.nylas/packages and delete the "n1-unsubscribe" folder. It worked for me.

c.c @nton4576

**Comment by jackiehluo** [comment]
Closing this issue since it looks like one was filed with the third-party plugin!

**Comment by KyleKing** [comment]
Fixed! Download [v1.6.3 of N1-Unsubscribe](https://github.com/colinking/n1-unsubscribe/releases/tag/1.6.3) and you should be good to go
