### ISSUE TITLE
unable to send using Gmail (can receive)

### ISSUE THREAD

**Issue by callunacarbon** [nylas/N1#303]
It tells me to check my network, but iCloud is sending fine. Receiving e-mail works, but can't send for both my Gmail accounts.

**Comment by cacyss0807** [comment]
I had the same issue (even if my network is totally fine). Also, I realised that it creates multiples drafts as I re-try to send the email that was failing to send. After 2 or 3 retries the email finally gets sent.

**Comment by grinich** [comment]
This should be fixed now. Please re-open if you have steps to reproduce.
