### ISSUE TITLE
The “Send and Archive” setting randomly reverts to “Send”

### ISSUE THREAD

**Issue by coopr** [nylas/N1#3031]
Latest N1 client is randomly reverting the “Send and Archive” setting to “Send” - sometimes nearly immediately, sometimes after many minutes.

To reproduce:
1. Open Preferences
2. Change "Default send behavior" to "Send and Archive"
3. Return to emailing, and wait some uncertain period
4. Compose an email - note that the send button now says "Send" and the preference has reverted to "Send"

##### Are there any related issues?
Maybe https://github.com/nylas/N1/issues/3023

...

##### What operating system are you using?
MacOS 10.11.6

##### What version of N1 are you using?
Version 0.4.204-c4a286f (0.4.204-c4a286f)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not that I can tell

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not that I can tell

**Comment by jackiehluo** [comment]
@coopr Out of curiosity, does that happen with any other settings you change?

**Comment by jstejada** [comment]
this setting is being reset when you open a composer window-- looking into this now

**Comment by jstejada** [comment]
this has been fixed in https://github.com/nylas/N1/commit/26c9fffdca89491db3a382d66d3e56baf6960d04 and weill be released soon

**Comment by emorikawa** [comment]
Fixed with 0.4.400 release
