### ISSUE TITLE
Search working only for recent msg 

### ISSUE THREAD

**Issue by zicochaos** [nylas/N1#3035]
Search only work for recent msg. 

##### What operating system are you using?

macOS Sierra 10.12.1

##### What version of N1 are you using?

Version 0.4.204-c4a286f (0.4.204-c4a286f)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
NO

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

**Comment by jackiehluo** [comment]
Merging into #2990!
