### ISSUE TITLE
Persistent mail rules notification in error

### ISSUE THREAD

**Issue by 100100100100** [nylas/N1#3036]
![screen shot 2016-11-10 at 12 04 57 pm](https://cloud.githubusercontent.com/assets/23368385/20158219/fd5a11b0-a73d-11e6-8c4e-544acfb2006b.png)

The above is persistently shown in my Nylas client, even with no mail rules enforced / disabled.

##### Are there any related issues?

...

##### What operating system are you using?
Mac OSX, El Capitain

##### What version of N1 are you using?

Version 0.4.204-c4a286f (0.4.204-c4a286f)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - if you go to the Mail Rules section of N1's preferences, do you see any mail rules for any of your accounts shown in red? Typically this happens when a mail rule is actually invalid for some reason (for example, if it references a label that you've deleted).

**Comment by 100100100100** [comment]
Hi, no worries.

I currently have 1 rule enabled and it is not showing up in red. As above, the notification shows up even with all rules disabled.

**Comment by 100100100100** [comment]
I should also mention, this was ONLY and issue after the second most recent Nylas update

**Comment by 100100100100** [comment]
Hi, can confirm this issue has cleared up with new update.
