### ISSUE TITLE
Is it possible to hide menubar in N1

### ISSUE THREAD

**Issue by kiranps** [nylas/N1#304]

**Comment by bengotow** [comment]
Please re-open with more information—what version of N1 and platform (Mac/Windows/Linux) are you running?

**Comment by dustigroove** [comment]
Not the OP, but I am also curious if this is possible... to clarify, I believe the request was if there was similar functionality to how Firefox let's you hide/toggle the menubar (by pressing Alt).

N1 v0.3.32-b11131d on Linux.

**Comment by iddqdidkfa** [comment]
@bengotow 
Same here: N1 v0.3.29-1904c6f on elementary OS x64
Here is how it looks:
![n1](https://cloud.githubusercontent.com/assets/1819727/11894060/60dda6f2-a57d-11e5-981e-9eb3d96b39ba.png)

**Comment by MadcapJake** [comment]
Also would like to hide the menubar

Using v0.3.32-b11131d on Solus Project 1.0

**Comment by tito** [comment]
Same here, please reopen.
Using elementary OS 0.3, Nylas N1 0.3.45

**Comment by Hori873** [comment]
Hello. I'm using Gnome 3.18.3 and Nylas 0.4.5-1 on Arch Linux
I would also like to be able to hide the menubar. It looks totally out of place on my desktop :D It would be ideal to have AppMenu integration but I don't want to ask too much. Just being able to hide it would be enough.

**Comment by Ryuuba** [comment]
Hello, I'm a Linux user and, alike the previous post, I like N1 were able to hide the menubar. Thanks in advance.

**Comment by DroWnThePoor** [comment]
I'm on Elementary OS Freya(0.3.2 ) and on my system the Menu bar is actually hidden by default, I have to press ALT in order for it to show up. Is this not the normal behavior? How can I toggle it ot be always on?
