### ISSUE TITLE
Cannot Test or Build - Error: Module version mismatch. Expected 48, got 50.

### ISSUE THREAD

**Issue by steven-fernandez** [nylas/N1#3041]
I cannot start or build this application due to this error:

Error: Module version mismatch. Expected 48, got 50.

I'm running it on a Mac Sierra 10.12

N1 Version: 0.4.204

**Bug?**

Does not run due to error:

Error: Module version mismatch. Expected 48, got 50.

**Comment by bengotow** [comment]
Hi @steven-fernandez — can you delete your node_modules folder and then re-run `script/bootstrap`? (You need to be sure you run script/bootstrap and do not run `npm install`!)

**Comment by jackiehluo** [comment]
Closing this issue for now—let us know if it's still a problem!
