### ISSUE TITLE
N1 killing my battery life this morning

### ISSUE THREAD

**Issue by j-feld** [nylas/N1#3042]
Down from 84% in about 30 minutes :-/
![screen shot 2016-11-11 at 9 37 49 am](https://cloud.githubusercontent.com/assets/6678261/20224849/635648f0-a7f5-11e6-962e-96d66a024606.png)

##### Are there any related issues?

...

##### What operating system are you using?
MacOS Sierra
...

##### What version of N1 are you using?
Version 0.4.312-d62377f (0.4.312-d62377f)
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Merging into #2068
