### ISSUE TITLE
Compile error: Could not find pro submodule at ~/N1/script/src/pro. Skipping.**`

### ISSUE THREAD

**Issue by wilmcontreras** [nylas/N1#3043]
##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
Latest (cloned from Git Nov 11th 2016)

Issue: Basically, when running ./bootstrap, I get the following output:

````
sudo ./bootstrap 

-- Running npm install in ./build with system config --
npm WARN nylas-build@ No license field.

-- Running npm install in ./apm with apm config --
npm WARN n1-bundled-apm@ No license field.

-- Running npm dedupe in ./apm/node_modules/npm with apm config --

-- Running npm install in ./. with electron config --
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-mac-notifier@0.0.13 (node_modules/node-mac-notifier):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for node-mac-notifier@0.0.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

-- Running npm dedupe in ./. with electron config --

**-- Linking Nylas submodule resources --
Could not find pro submodule at ~/N1/script/src/pro. Skipping.**`
````

I noticed that /src is in the parent directory, so, I made a copy in /script; however, /script/src/pro is empty anyways, so, not sure what bootstrap is supposed to find there.

**Comment by jackiehluo** [comment]
That's expected behavior for the open-source project!

**Comment by wilmcontreras** [comment]
I see... but nothing happens afterwards, I'm back in the Terminal. Where do I go from there?

**Comment by wilmcontreras** [comment]
Got it sorted, had to run ` npm install -g express`

**Comment by KevinMartin** [comment]
@jackiehluo This seems to be an issue in the builds, too...

https://ci.appveyor.com/project/nylas/n1/build/job/la0tiaqbmwv195pn

**Comment by jackiehluo** [comment]
@KevinMartin I think the problem with that build is just the `node-mac-notifier` package, which we're working on fixing!

**Comment by MooShoe** [comment]
I have the same issue, but @Khashir-E's solution isn't working. I'm on Ubuntu 16.04.

**Comment by joepeak** [comment]
i am also,i'm on Windows 10 64
