### ISSUE TITLE
N1 cannot load emails after an update

### ISSUE THREAD

**Issue by light2yellow** [nylas/N1#3044]
Version: 0.4.204
N1 cannot load Inbox. The animation with 4 dots runs forever.
[log.txt](https://github.com/nylas/N1/files/587734/log.txt)

**Comment by jackiehluo** [comment]
Hey! Looks like the problem is the N1-Unsubscribe plugin—if you uninstall that, it should be fine.

**Comment by jackiehluo** [comment]
(Or update? They might have a fix for it!)

**Comment by light2yellow** [comment]
Hey. I'll try disabling it tomorrow.

**Comment by light2yellow** [comment]
N1 doesn't react on clicking the Preferences so I cannot disable this plugin from GUI. What should I do?
