### ISSUE TITLE
Compiled from source but still got trial?

### ISSUE THREAD

**Issue by wilmcontreras** [nylas/N1#3045]
Not sure if I misunderstood the information in the [Pricing](https://nylas.com/pricing/) page, but after compiling from source, it seems I still got directed to the Trial version (i.e., under Preferences -- Subscription, it says my subscription is valid until Nov 27).

Did I miss something?

**Comment by pwasiewicz** [comment]
I think this issue is related: https://github.com/nylas/N1/issues/2657

**Comment by jackiehluo** [comment]
Sorry about the confusion—you can use the built version of N1, but you need to build the sync engine (https://github.com/nylas/sync-engine) from source!
