### ISSUE TITLE
Show unread message count for labels

### ISSUE THREAD

**Issue by bryantgillespie** [nylas/N1#3048]
One thing I really miss from Gmail is knowing how many Unread message are in my labels.

I use filters pretty extensively - and certain items skip my inbox entirely. 

If you could that add that to Nylas - that would be awesome.

Gmail keeps count of the unread messages.
![screenshot 2016-11-14 15 01 50](https://cloud.githubusercontent.com/assets/23302570/20280675/69c53150-aa7b-11e6-8e81-9b1fe5aa7d3d.png)
<img width="306" alt="screenshot 2016-10-25 19 27 00" src="https://cloud.githubusercontent.com/assets/23302570/20280678/6d5c0bae-aa7b-11e6-8744-d7b086ccae68.png">

**Comment by jackiehluo** [comment]
You can change the setting in Preferences -> General!

**Comment by bryantgillespie** [comment]
Wow - awesome. Is that new?

  

Last time I submitted that to your team - they said to fill out a feature
request.

  

\--

**Bryant** from Clockwork Consulting

Ph. [412.385.7467](tel:+14123857467&r=cmVwbHkrMDE2MzkxYWFjNDYwYmZlMDZmNDZhZjQ2
MmIwYzAwZmU4MzZlM2VkNWQyOTkzMmIwOTJjZjAwMDAwMDAxMTQ0MWRiZGY5MmExNjljZTBiNDcyNj
QyQHJlcGx5LmdpdGh1Yi5jb20=)

![](https://ci5.googleusercontent.com/proxy/ZcIKU2a1JExnV_wVnyeA_crr5lCJA97DI2
FKjff3CLzEm12eOyu4sMEFAGM8VJKGMVeHJ7QsH_ismVtqR8l0MMdxt4CaHRcH-
NrnO6mxV6B5aJRsitrEwOAOC5sgSIDCiDgWpACkNM-alISLDmblESI=s0-d-e1-ft)

![](https://link.nylas.com/open/8gqja51v9y2yqc27oybukds4b/local-02394f82-5bf9?
r=cmVwbHkrMDE2MzkxYWFjNDYwYmZlMDZmNDZhZjQ2MmIwYzAwZmU4MzZlM2VkNWQyOTkzMmIwOTJj
ZjAwMDAwMDAxMTQ0MWRiZGY5MmExNjljZTBiNDcyNjQyQHJlcGx5LmdpdGh1Yi5jb20=)

  
On Nov 14 2016, at 3:09 pm, Jackie Luo <notifications@github.com> wrote:  

> Closed [#3048](https://github.com/nylas/N1/issues/3048&r=cmVwbHkrMDE2MzkxYWF
jNDYwYmZlMDZmNDZhZjQ2MmIwYzAwZmU4MzZlM2VkNWQyOTkzMmIwOTJjZjAwMDAwMDAxMTQ0MWRiZ
GY5MmExNjljZTBiNDcyNjQyQHJlcGx5LmdpdGh1Yi5jb20=).

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly, [view it on GitHub](https://github.com/nylas/N1/
issues/3048#event-858370497&r=cmVwbHkrMDE2MzkxYWFjNDYwYmZlMDZmNDZhZjQ2MmIwYzAw
ZmU4MzZlM2VkNWQyOTkzMmIwOTJjZjAwMDAwMDAxMTQ0MWRiZGY5MmExNjljZTBiNDcyNjQyQHJlcG
x5LmdpdGh1Yi5jb20=), or [mute the thread](https://github.com/notifications
/unsubscribe-auth/AWORqoruVI7ZDAqYDdop8H_c6dpwKnVFks5q-L_fgaJpZM4KxwBY&r=cmVwb
HkrMDE2MzkxYWFjNDYwYmZlMDZmNDZhZjQ2MmIwYzAwZmU4MzZlM2VkNWQyOTkzMmIwOTJjZjAwMDA
wMDAxMTQ0MWRiZGY5MmExNjljZTBiNDcyNjQyQHJlcGx5LmdpdGh1Yi5jb20=).![](https://git
hub.com/notifications/beacon/AWORqqgZQITnaTAh8XS-geCnrPcGXyJ6ks5q-
L_fgaJpZM4KxwBY.gif)

**Comment by jackiehluo** [comment]
Aw... Maybe someone misunderstood the question? That's been there!
