### ISSUE TITLE
Broken markup in buttons panel when letters are selected 

### ISSUE THREAD

**Issue by Chuckland** [nylas/N1#305]
Buttons don't have enough space in panel. Look at screenshot:
![screen shot 2015-10-30 at 12 28 02](https://cloud.githubusercontent.com/assets/1571646/10840536/0ff96178-7f02-11e5-9675-1e92dbb99a61.png)

**Comment by bengotow** [comment]
Merging this into https://github.com/nylas/N1/issues/370
