### ISSUE TITLE
Feature Request: Clear trash option

### ISSUE THREAD

**Issue by zoutiyx** [nylas/N1#3055]
A clear trash button/option in the trash would be a nifty option to clear all trash at once as opposed to on-by-one.

##### Does this feature exist in another mail client or tool you use?
Yes

**Comment by jackiehluo** [comment]
Hey! You should just be able to select all at once and then delete—does that work for you? Not the same as having one button, but I think it's more flexible (i.e., archive all, move all to folder, etc.).
