### ISSUE TITLE
Backspace archives

### ISSUE THREAD

**Issue by Yerlix** [nylas/N1#306]
Hi

I'm trying out Nylas. So far so good but I've noticed that when I use backspace to delete an email, it will be archived.

I've used Airmail before Nylas and there it has the same behaviour but I was able to change it with a simple checkbox.

When using backspace, I want my email deleted instead of archived.

Could this be resolved?

**Comment by bengotow** [comment]
Hey @Yerlix — this is definitely on the roadmap. Right now, the logic here https://github.com/nylas/N1/blob/0.3.20/internal_packages/thread-list/lib/thread-list.cjsx#L281 defaults to archive and falls back to delete when your account doesn't support archiving. We just need to add a preference for it :-) Pull request would be welcome if you're interested!

**Comment by jadchaar** [comment]
I second this. Is this request on the Trello?

**Comment by Yerlix** [comment]
I'm currently trying this out myself. But I've no experience with ReactJS so it is trial and error for me.

**Comment by Yerlix** [comment]
I've tried to add a checkbox and came up with this.

@bengotow here is my commit: https://github.com/Yerlix/N1/commit/16a275ee6c7afd612fa091350d82cd055b79230e

I'll create a pull request is this is correctly done (test have not been run yet, more info would be helpful here).

**Comment by Yerlix** [comment]
This has been merged (https://github.com/nylas/N1/pull/525).
I'm closing this issue now.
