### ISSUE TITLE
Inconsistent capitalization on left hand pane

### ISSUE THREAD

**Issue by jweinstein** [nylas/N1#3061]
After a fresh install of Nylas N1 on a new machine: `inbox` and `spam` are lowercase. Strange.

![image](https://cloud.githubusercontent.com/assets/547354/20360492/c8dd4b78-abe8-11e6-9911-6cb52ced09fc.png)

**Comment by grinich** [comment]
woah... what email provider is this for?

**Comment by jweinstein** [comment]
Regular Gmail (not apps, just @gmail)

**Comment by jweinstein** [comment]
FYI, still busted in latest production build.

**Comment by manicmarvin** [comment]
Unable to reproduce this behaviour/glitch.

**Comment by jweinstein** [comment]
Manual download of Nylas Mail fixed.
