### ISSUE TITLE
Missing toolbar

### ISSUE THREAD

**Issue by inyono** [nylas/N1#3065]
The toolbar above the mail that included actions like move to folder and snoozing isn't shown anymore for me.

<img width="1609" alt="screen shot 2016-11-17 at 08 15 08" src="https://cloud.githubusercontent.com/assets/1508477/20379835/ab97377a-ac9e-11e6-8aad-064d77131ad3.png">

##### What operating system are you using?
macOS Sierra 10.12.1 (16B2555)

##### What version of N1 are you using?
Version 0.4.204-c4a286f (0.4.204-c4a286f)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Unsubscribe v1.5.5

**Comment by lleger** [comment]
To chime in here, I was having the same issue. I also had Unsubscribe plugin installed, so I uninstalled it and it fixed the problem. There's a version 1.6.3 up for that plugin and so far it's working for me.

**Comment by inyono** [comment]
Nice, thanks!
