### ISSUE TITLE
cannot edit email in to: section

### ISSUE THREAD

**Issue by dcrystalj** [nylas/N1#3069]
##### What operating system are you using?
ubuntu 16.10
##### What version of N1 are you using?
0.4.56

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
outlook.com

![nylas n1_272](https://cloud.githubusercontent.com/assets/1460727/20410347/d7d62a2a-ad1c-11e6-8052-a1da4cafc84f.png)

**Comment by jackiehluo** [comment]
You should be able to double-click!

**Comment by dcrystalj** [comment]
thank you. could not think about it. Maybe I am not the only one who dont see this
