### ISSUE TITLE
Standard .tar.gz package for linux

### ISSUE THREAD

**Issue by Lowseling** [nylas/N1#307]
Hi,

I don't know if someone already posted this, but it would be awesome to have a .tar.gz package for linux instead of the .deb because not all linux distributions (e.g. ArchLinux) support this type of packages.

Good work! :)

**Comment by mbilker** [comment]
That would require building on Arch Linux. There are AUR packages available https://aur.archlinux.org/packages/n1/ and https://aur.archlinux.org/packages/n1-git/ .

**Comment by Lowseling** [comment]
Ok thank you :)
