### ISSUE TITLE
Enlarged Font

### ISSUE THREAD

**Issue by MsQuickTrick** [nylas/N1#3071]
I have been looking for an email program and I love yours, but if I cannot enlarge my font I will have to pass immediately.  Is there a resolution to the small font yet?  If not, could you recommend a program for multiple emails in one place?  I like Gmail as an alternative but I cannot stand the folders that separate my email.  You can never get it all and it drives me freakin crazy.

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jackiehluo** [comment]
You can use this theme!
[ui-bigger.zip](https://github.com/nylas/N1/files/600617/ui-bigger.zip)

**Comment by jackiehluo** [comment]
Let me know if that works.
