### ISSUE TITLE
Re-arrange accounts

### ISSUE THREAD

**Issue by ChainsawBaby** [nylas/N1#3076]
Is there a way I can re-arrange the position the accounts appear?
I've recently added an email account I'd like to have on the top of accounts, but so far, the only way I know to achieve this, is to remove all email accounts, and then add them again accordingly.

**Comment by grinich** [comment]
Click and drag in the preferences?

**Comment by ChainsawBaby** [comment]
Huh, indeed that works.

Though I must ask, how long has that feature been there? Because I think I tried earlier weeks/months ago, and it didn't work.

**Comment by jackiehluo** [comment]
It's been there! But maybe there was a bug at some point? Glad it's fixed now!

**Comment by ChainsawBaby** [comment]
Ah, that might be.
Well, I've re-arranged my accounts now 😎
Thanks 👍
