### ISSUE TITLE
Bug: Buttons have disappeared in latest release

### ISSUE THREAD

**Issue by nathanmfarrugia** [nylas/N1#3077]
Since the latest stable release, I have found that the buttons along the top right of the Nylas window have disappeared. This occurred when I updated a couple of weeks ago. I've resorted to using the keyboard for archiving messages. Toggling between themes does not bring the buttons back.

Have I turned them off by accident? I can't find the setting that would turn the buttons off.
   
I'm also suffering from the existing issue where "send and archive" defaults to "send."

macOS 10.12.1
Nylas N1 Version 0.4.204-c4a286f

Installed and active plugins:
Unsubscribe
Activity List
Mail Merge
Quick Replies
Link Tracking
Open Tracking
Personal Level Indicators
Phishing Detection
Send Later
Send Reminders.

I've tested with all of them off, and there's no difference.

See attached image for example.

![nylas_n1_and_new_issue_ _nylas_n1](https://cloud.githubusercontent.com/assets/2157983/20456507/e4db2bac-aecb-11e6-82bc-08b484b4c88f.jpg)

**Comment by bengotow** [comment]
Hi @nathanmfarrugia — can you try removing the unsubscribe plugin and re-installing it from their GitHub repo? I think there's an issue with older versions of the plugin causing the toolbar to disappear.

**Comment by nathanmfarrugia** [comment]
Brilliant, that worked! Thank you for your exceptionally fast reply, @bengotow.

I don't really need the Unsubscribe plugin, so I've left it uninstalled.
