### ISSUE TITLE
Feature Request: multiple signatures per account (ideally with rules)

### ISSUE THREAD

**Issue by hallpower** [nylas/N1#3078]
Who has this?
Apple Mail , Outlook and Airmail have the ability to allocate multiple signatures per Email account. 

Why do I want this?
Many companies (including mine) employ a separate condensed signature for internal communication and an extended signature for external communication. Ideally, I'd like have a 1:n relationship between signatures and accounts, with the ability to use a rule for which signature gets used (e.g. use internal signature if all emails from a domain list).

**Comment by jackiehluo** [comment]
@hallpower You can currently use different signatures in accounts if you go to Preferences -> Signatures! But we don't have signature rules yet—merging into #2978.
