### ISSUE TITLE
Viewing unread message in unread view changes selection to emails above

### ISSUE THREAD

**Issue by omonk** [nylas/N1#3079]
##### Are there any related issues?

...

##### What operating system are you using?
OS X 10.11.5

##### What version of N1 are you using?
0.4.204-c4a286f

--

**Bug?**
Clicking on any unread message in 'unread' view selects desired message then changes selected to messages above up to three times. Seems to only be when there are unread messages above.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Any email account
...

**Comment by jackiehluo** [comment]
Merging into https://github.com/nylas/N1/issues/2271!
