### ISSUE TITLE
forward draft not scrolling into view

### ISSUE THREAD

**Issue by troygoode** [nylas/N1#3080]
When I press `f` to forward an email, a new draft is created for that forward in the conversation. Roughly ~60% of the time (for the past ~month) my conversation pane does not scroll down to display the draft, instead it remains at the top of the conversation (showing the original message). I have to manually scroll down to the new draft and click into the To field – which isn't being focused by default.

--

##### What operating system are you using?
macOS Sierra – 10.12.1

##### What version of N1 are you using?
Version 0.4.204-c4a286f (0.4.204-c4a286f)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't believe so. I am using a unified inbox of two Google providers (one Gmail, one Google Apps).

##### Is the issue reproducible with a particular attachment, message, signature, etc?
The effect is frequent, but intermittent.

**Comment by troygoode** [comment]
Nevermind. I've just quite Nylas and moved onto Spark. Too. Many. Bugs...

**Comment by yan-perch** [comment]
Any updates on this? I have been experiencing this since the beginning (more than 8 months).

**Comment by LonghornRach** [comment]
yes can we re-open this? I have the same error, although mine is more consistent. Using Version 1.0.27 (1.0.27) on Sierra 10.12.3. I can most reliably reproduce it in 2-panel mode when the app is full-screen. Usually when the contact sidebar is open, although it happens when it is closed as well. Let me know if you need/want more info.
