### ISSUE TITLE
Script/bootstrap unexpected token {

### ISSUE THREAD

**Issue by nicobonne** [nylas/N1#3083]
##### What operating system are you using?
Ubuntu 16.04

##### What version of N1 are you using?
0.4.204

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://cloud.githubusercontent.com/assets/6003279/20526726/9b2ba4c2-b0c5-11e6-8bb0-ce27854a4304.png)

**Comment by KevinMartin** [comment]
What version of Node are you using?

**Comment by nicobonne** [comment]
![image](https://cloud.githubusercontent.com/assets/6003279/20529614/0ab27e0a-b0d1-11e6-88b1-4d072370a289.png)

**Comment by KevinMartin** [comment]
Object restructuring isn't supported in Node v4.x without the `--harmony-destructuring` flag. You can either run it with a flag or update to a later very of Node that supports it without a flag, such as v7.

**Comment by nicobonne** [comment]
Thank you, that seems to do the trick!

At least for starting the building procedure, then I get stuck to:

![image](https://cloud.githubusercontent.com/assets/6003279/20532374/0dada8a6-b0da-11e6-9e44-ff2bb3e40b11.png)

is `/src/request` a npm package? I have `request` already installed in `node_modules` folder in the root directory

**Comment by prijindal** [comment]
@nicobonne Using node version 6.9 instead of 7 to fix that error

**Comment by jstejada** [comment]
closing
