### ISSUE TITLE
Nylas does not check for new Emails, not getting anything

### ISSUE THREAD

**Issue by derpoho** [nylas/N1#3087]
##### Are there any related issues?
Nothing found

##### What operating system are you using?
Mac OS Latest

##### What version of N1 are you using?
0.4.400

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Can't offer more here. I Updated the the latest Version 0.4.400 today, since it restarted, i do not receive any mails for all Email Accounts.

--

**Comment by jackiehluo** [comment]
Can you send us an email (support@nylas.com) with your account information?

**Comment by derpoho** [comment]
Email has been sent. I hope it's getting to you (Not sure if sending is working right now)

**Comment by derpoho** [comment]
@jackiehluo No response from anyone! This issue is still not fixed for me!

**Comment by jackiehluo** [comment]
@derpoho Our office is closed this week for the holidays! You should get a response within a few days.
