### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by agyrafa** [nylas/N1#3089]
##### Are there any related issues?
No
...

##### What operating system are you using?
Os Sierra

##### What version of N1 are you using?
zip of master 

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screen shot 2016-11-24 at 18 30 45](https://cloud.githubusercontent.com/assets/10052533/20611687/12aac84e-b296-11e6-82e4-4ae21afa093e.png)
![screen shot 2016-11-24 at 18 30 50](https://cloud.githubusercontent.com/assets/10052533/20611690/17523062-b296-11e6-93aa-a11dbb85b625.png)

**Comment by jstejada** [comment]
Hi @agyrafa, is this happening with the latest release? To the latest zip from master but rather the latest download from www.nylas.com?

**Comment by jackiehluo** [comment]
Closing this issue for now—if it's still happening, can you send us an email at support@nylas.com with account details?
