### ISSUE TITLE
"Lockscreen" inactive protection

### ISSUE THREAD

**Issue by ghhernandes** [nylas/N1#309]
A good idea would be an option to lock the application when idle for a period of time and, require a PIN to unlock.

Gabriel.

**Comment by bengotow** [comment]
Hi @ghhernandes — thanks for filing this. Unfortunately, this isn't currently on the roadmap. This is a great package idea, though. I've added it to the package ideas section of our Trello board: https://trello.com/c/OcJWTYq3/48-lockscreen-displayed-after-the-app-is-inactive
