### ISSUE TITLE
Deleting email in thread deletes whole thread

### ISSUE THREAD

**Issue by Bergg** [nylas/N1#3093]
When opening an email in any thread, and then clicking on the delete button on top of N1, deletes the whole thread (unless I missed an option to perform that action..). 

##### What operating system are you using?
Fedora 24

##### What version of N1 are you using?

N1-0.4.400.rpm

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes

**Comment by jackiehluo** [comment]
Merging into #1263—we don't support individual message deletions right now! All of the actions at the top toolbar apply to threads.
