### ISSUE TITLE
Mobile app!

### ISSUE THREAD

**Issue by ziirahdane** [nylas/N1#311]
Obviously a feature request which I understand could be far off in the future. I'd love to not have to continue using the Mailbox app though (no exchange/outlook support ): ).

**Comment by jadchaar** [comment]
The whole appeal of Nylas on the desktop is that it is open-source built on lightweight web technologies; furthermore, the app is meant to be extensible. Because of these appeals, I feel like it will be very difficult to bring it to a closed ecosystem such as iOS. Android may work though.

Spark by Readdle for iOS is introducing Exchange support this week if you are interested.

**Comment by b8e5n** [comment]
A mobile App for ubuntu touch. 
You already have a version for ubuntu. Packaging it might be enough to get it working.
Anyway, it is something missing for ubuntu touch users.

**Comment by bengotow** [comment]
Hi folks—mobile support is not a priority for our team at the moment, and would take a very, very significant amount of work. Since the entire app is written on top of Electron and is coupled tightly to NodeJS, running it on mobile would require support for those technologies. It might be possible to run the current codebase on Ubuntu Touch though, I'm not sure!

**Comment by ziirahdane** [comment]
Thanks for responding and clarifying, guys. I totally get why it's not on the radar - keep doing what you're doing! :)

@jadchaar Thanks for recommending Spark! I think this will do nicely.

**Comment by bilby91** [comment]
Is there any iOS app that uses Nylas API ? I'm looking for a client that support all the Nylas providers.

**Comment by karloscarweber** [comment]
I would be open to working on a Mobile app for N1. At least for iOS.

**Comment by bilby91** [comment]
Me too. 

Sent from Outlook




On Mon, Dec 7, 2015 at 2:54 PM -0800, "karloscarweber" <notifications@github.com> wrote:












I would be open to working on a Mobile app for N1. At least for iOS.

**Comment by karloscarweber** [comment]
Alright! this is cool. I'll make a repo today and then invite you to collaborate on that.

**Comment by xasos** [comment]
@karloscarweber Interested as well!

**Comment by chrisenytc** [comment]
:+1:

**Comment by ajeygore** [comment]
Actually we can write a Cardova application which uses Nylas N1 server APIs. Writing it down completely is Swift or Java may be too much to ask for, but I would love this for an iPad or some tablet format. N1 has been awesome in that sense.

**Comment by mbilker** [comment]
@ajeygore React Native would be a better choice since many of the N1 components are written for React.

**Comment by jetlej** [comment]
+1 on Native React being the way to (relatively) quickly migrate to mobile

**Comment by weien** [comment]
@karloscarweber @bilby91 Is there still an iOS N1 repo out there? :smile:

**Comment by mbilker** [comment]
You could write your own N1 mobile app. There is no repo out there and the
Nylas team stated they do not support a mobile app while they focus on the
desktop app.

> On Feb 26 2016, at 11:29 am, Weien Wang &lt;notifications@github.com&gt;
wrote:  

>

> [@karloscarweber](https://github.com/karloscarweber)
[@bilby91](https://github.com/bilby91) Is there still an iOS N1 repo out
there? ![:smile:](https://assets-
cdn.github.com/images/icons/emoji/unicode/1f604.png)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/311#issuecomment-189358362).![](https://github.com/notifications/beac
on/ABNTbcUwSF7RCWoC-0M_d-QNwYahu1u8ks5poHTzgaJpZM4GY-sJ.gif)

**Comment by tuler** [comment]
Is there any app there is "compatible" with N1 snooze strategy? Or any way to make N1 compatible with another app snooze strategy?
