### ISSUE TITLE
Best way to fetch current active account?

### ISSUE THREAD

**Issue by bewallyt** [nylas/N1#3117]
Given that AccountStore.current() has been deprecated, what's the best way to fetch the current active account?

**Comment by bengotow** [comment]
Hey thanks for filing this! Since N1 supports unified inbox now, we've added the concept of a "focused mailbox perspective" that defines the collection of accounts and folders/labels that the user is viewing. This is the best way to get the account IDs:

```
// current will always return a perspective, but accountIds may be empty
FocusedPerspectiveStore.current().accountIds
``

Once you've got the account IDs you can grab  the account data from `AccountStore.accountForId`.

Hope that helps! Also, feel free to ping us on the community slack channel for more specific info if you have questions: nylas-chat.slack.com
