### ISSUE TITLE
Map DONE or SNOOZED emails from Google Inbox to N1 Labels 

### ISSUE THREAD

**Issue by cacyss0807** [nylas/N1#312]
It would be great if an email that is set as `done` or `snoozed` in Google Inbox could be mapped to an label like `done` or `snoozed`. As of now, this type of emails are only visible at the *All mail* folder in N1 client.

**Comment by bengotow** [comment]
Hi @cacyss0807 — unfortunately, we can't support the categories in Google Inbox because they aren't exposed via the Gmail API or the Gmail IMAP interface. They're only available from Google Inbox itself. If we're able to access them in the future, we'll definitely pull them into N1!
