### ISSUE TITLE
Split window support (OS X El Capitan)

### ISSUE THREAD

**Issue by Robertwilcox** [nylas/N1#313]
It would be awesome to take advantage of the new split window support in El Cap.

**Comment by bengotow** [comment]
This is blocked on us using system standard window controls (the traffic lights we show are actually DOM elements)

**Comment by mbilker** [comment]
Does Atom also use the same method? Is this because there are elements in the same bar with the traffic lights?

**Comment by grinich** [comment]
I think Atom uses the standard system ones.

**Comment by mbilker** [comment]
Atom doesn't place a search bar and icons in the header, right?

**Comment by sanjeevverma1** [comment]
Split-screen works now: 

![screenshot 2016-04-14 22 48 45](https://cloud.githubusercontent.com/assets/7389628/14550035/3cc809a6-0293-11e6-8817-cf2bd6784b15.jpg)

Close issue?

**Comment by grinich** [comment]
sweet. thanks electron!

**Comment by KevinMartin** [comment]
The problem is only half solved and has been this way since the beginning.

If the user initiate a split window with a different window then chooses Nylas, it works.
But the user cannot initiate a split window with Nylas, bc of the DOM based controls.

**Comment by sanjeevverma1** [comment]
Actually, I am able to initiate the split-screen using either N1 or a different app...

1. Here's me initiating split-screen with N1 first: https://goo.gl/0PezQd AND 
2. Here's me initiating split-screen with Safari first: https://goo.gl/2ZKYKF

In case it's not clear in the video, to initiate split-screen from Nylas N1:
1. Make N1 window full-screen
2. Open Mission Control (F3)
3. Drag other application window onto the desktop space with N1
4. Success!

**Comment by KevinMartin** [comment]
I'm also running the latest N1 (0.4.25) on El Cap (10.11.5).

That's a long way to get around it. I think by initiating another app first then dragging N1 into it is a bit shorter/faster.

By initiating, I mean holding down the green traffic light button for 3 seconds which lets you skip steps 1 and 2.

**Comment by KevinMartin** [comment]
Further discussion: #1886
