### ISSUE TITLE
Configuration being wiped

### ISSUE THREAD

**Issue by walshie4** [nylas/N1#314]
I'm running Nylas Version 0.3.20-6bbe930 (0.3.20-6bbe930) on OS X 10.10.4 and every once and a while when I restart the app I am presented with the setup screen as if I just downloaded the app and must re-enter my invitation code and email information.  I'm running with dev flags as well.

**Comment by bengotow** [comment]
Hey @walshie4 — thanks for filing this. The next time this happens, could you look and see if `~/.nylas/config.cson` exists and what it's content is? N1 is either corrupting that file or it's getting deleted outright. Very strange...

**Comment by grinich** [comment]
@walshie4 Kind of random question-- do you think you were running out of disk space when this happened?

**Comment by walshie4** [comment]
@grinich It's very possible.

**Comment by grinich** [comment]
That's really the only time we've been able to repro this issue.

**Comment by grinich** [comment]
I'm going to merge this into #897 and track there
