### ISSUE TITLE
selecting messages

### ISSUE THREAD

**Issue by Khidreal** [nylas/N1#3140]
I don't know if this has been asked for, I don't really know how to work with github, so please tell me if it has been asked.

I noticed today, while visiting my android related exclusive google account, that I had 100+ unread emails. than I went on trying to find a button or something to select all emails (as I can find on gmail) but could not find it.
is it possible to add something like that or similar to gmail (select all, unread, read, with star or without star, etc) into N1?
I think that who deals with lot's of emails every day will be glad to have that feature, and even the ones that occasionally receive them can also benefict from a feature like this... it's a bit annoying being clicking the checkbox... at least for me it was, since I had to click that checkbox exactely 174 times...

**Comment by grinich** [comment]
Thanks for the feedback!
