### ISSUE TITLE
Nylas ID account to add email accounts???

### ISSUE THREAD

**Issue by petrk94** [nylas/N1#3142]
Hello,

I would like to know why I need to make a Nylas ID just to send emails over a email account which Im already using?
Its running on Linux.

Thanks

**Comment by grinich** [comment]
There are lot of features in N1 that require having an identity component (snooze, send later, reminders, etc.) along with our paid features.

**Comment by petrk94** [comment]
I dont understand why this features require a own ID ?? I mean on my phone I can do it too ;)
I want make some tests and not use paid features.

**Comment by geeksunny** [comment]
@grinich is a Nylus ID required even if you're hosting your own sync-engine? There doesn't appear to be a *"Hosting your own sync engine?"* link as noted in `CONFIGURATION.md`.

**Comment by qazip** [comment]
Is nylas-ID still a requirement for nylas-mail?
