### ISSUE TITLE
up to 45 drafts of previously sent emails get generated

### ISSUE THREAD

**Issue by jimbroski** [nylas/N1#315]
Sometimes the Drafts will just be populated with emails I have sent a while ago. It would display the same email many times as draft.

I'm using N1 with a Google Apps Gmail account. Online I have no drafts. They are only in N1

**Comment by peroli** [comment]
I have the same issue with google apps gmail account. I use Ubuntu 14.04 operating system.

**Comment by jadchaar** [comment]
I have this issue also. It occurs with Nylas and Spark on iOS.

**Comment by mitjafelicijan** [comment]
+1 Linux

**Comment by grinich** [comment]
This should be fixed now. Please re-open if you have steps to reproduce.
