### ISSUE TITLE
Pro?

### ISSUE THREAD

**Issue by OJFord** [nylas/N1#3166]
v0.4.402 -> v1.5 (!)

The [changelog](https://github.com/nylas/N1/blob/master/CHANGELOG.md#150-11617) only says:

> Nylas N1 is now Nylas Pro. We are also introducing Nylas Mail Basic!

**"What does this mean for me if"**:
- I pay for Pro
- I leech on the free tier
- I self-host the sync-engine

and any other variation of user?

**Comment by grinich** [comment]
Hey @OJFord -- sorry about that. We're in the process of rolling some new stuff out tonight. Bear with us. It's kind of like this :
 
![indy](https://cloud.githubusercontent.com/assets/92417/22004980/a0bd7eae-dc14-11e6-9800-d2e70d77d88c.gif)

**Comment by jacobmischka** [comment]
The blog post didn't seem to clear any of this up. Can you clarify the difference between the current N1 in this repo and Nylas Mail?

**Comment by grinich** [comment]
What questions do you have? Did you see the FAQ at the bottom?

**Comment by ArchangeGabriel** [comment]
@grinich Not @jacobmischka, but my questions:

1) Are any IMAP/SMTP mail servers supported? I read only big providers under “Does Nylas Basic support all mail providers?”, but I thought Nylas Mail supported IMAP/SMTP?

2) Can it be run without sync-engine at all?

3) What changes between Nylas N1+Self-hosted sync engine vs Nylas Basic?

**Comment by OJFord** [comment]
Is this repo *both* Nylas Mail & Nylas Basic; it detects subscription-level in-app?

**Comment by ArchangeGabriel** [comment]
For 1.&2., I’m especially referring to this:
>It’s now powered by a hybrid sync engine that connects directly to your mail provider (Gmail, Exchange, etc.). Some features — such as open/link tracking, snoozing, and reminders — still require cloud operations, but the large majority of sync operations no longer require backend services.

**Comment by Spidersouris** [comment]
Thanks for making Nylas free!!

**Comment by OJFord** [comment]
Seriously 👍 💯   for "connects directly to your mail provider (Gmail, ..." though.

I decided to have everything forward to my Gmail (I pay for extra storage so..) which means I can use the labelling system which beats Exchange et al's IMAP folders IMO. Then it ocurred to me how strange it was to be using a remote 'sync engine' to provide 'modern APIs' that access... oh, Gmail's APIs? 🙂

**Comment by OJFord** [comment]
@ArchangeGabriel - my reading is that *Basic* doesn't do anything that uses the sync-engine; so self-hosting N/A. *Mail* uses hosted for Pro features, and I guess the 'coming soon' enterprise is on-premise Mail/Pro?

**Comment by jacobmischka** [comment]
Oh apologies, I must either be blind or the post was updated since I posted. Most of my questions are cleared up now with the FAQ, thanks!

**Comment by grinich** [comment]
Yep, you should do all upvoting in this repo. This is the main repo for everything Nylas Mail. We're just going to stop using the name Nylas N1.

You can actually connect any IMAP account, but be warned we have only tested a few providers. Please file detailed bug reports if you experience issues. Here's how to set up a generic IMAP account:

<img width="408" alt="_and_menubar" src="https://cloud.githubusercontent.com/assets/92417/22024370/a8792c28-dc7e-11e6-94b3-66b7c99999ee.png">


### Can it be run without sync-engine at all?

Well, how would you get your mail then? You need something to actually sync data! Today's release runs a local sync engine within the app.

It still needs to do some cloud operations for specific features (open/link tracking, snoozing, etc.) so we still have a cloud component. But it should be possible to remove those features and have something equivalent to Thunderbird or Pine-- just a vanilla old email client.

### What changes between Nylas N1+Self-hosted sync engine vs Nylas Basic?

Soon we will transition everyone to this new architecture so the default experience will connect directly to your mail provider. I'll still be open source and all that.

We focused on performance and polish for this release so there are a few open source bits currently missing in this repo, but we'll be adding those very soon as well.

**Comment by ArchangeGabriel** [comment]
@OJFord Ooh. This part was the one tricking me:  “Some features — such as open/link tracking, snoozing, and reminders — still require cloud operations, but the large majority of sync operations no longer require backend services.”. But it looks like they are not implemented currently:
>Coming soon in Nylas Basic: snoozing, reminders, and more…

>We will continue to port limited versions of Nylas Pro features to Nylas Basic including… snoozing, reminders, send later, and mail merge. Stay tuned!

So maybe current version is only local indeed.

**Comment by ArchangeGabriel** [comment]
Oh, @grinich was faster. So still partly cloud?

**Comment by ArchangeGabriel** [comment]
@grinich By no sync-engine, I meant no cloud part. Fully local. ;)

**Comment by grinich** [comment]
Yes but much much much much less cloud. We've done the large majority of the work.

**Comment by OJFord** [comment]
> This is the main repo for everything Nylas Mail.

Nylas Basic too? I'm still not clear on if they're distributed separately, or if I just login to my subscription if I have one?

**Comment by grinich** [comment]
Yep for Nylas basic too.

**Comment by grinich** [comment]
They are distributed separately (for now) but there is one repo for both.

**Comment by ArchangeGabriel** [comment]
@grinich Indeed, and I’ll thank you very much for this. :) I think this will bring you way more users. ;) Keep up the good work, and I’m eager to see this next version with cloud part being optional. :D

**Comment by ArchangeGabriel** [comment]
Supplemental question about name. Current status of “Nylas Mail” doesn’t look clear to me: seems to be the general name for both version, but the drop down “Products” menu on the home page makes it a pointer to the free version.

But download links for Linux version of Pro version at https://billing.nylas.com/download-pro are N1.deb and N1.rpm, while both Windows and MacOS ones are NylasMail…

**Comment by ronisbr** [comment]
Wow, use Nylas without any cloud operation will be amazing. Just like old vanilla clients. My question is: I couldn't find a Nylas Mail for Linux, will Linux be supported?

**Comment by ArchangeGabriel** [comment]
@ronisbr Yes, but the builds aren’t done yet. Same for Windows.

**Comment by ArchangeGabriel** [comment]
@grinich For my naming question, my main interest is “How should ArchLinux package be named?”.

**Comment by nightvisi0n** [comment]
I just cloned the repo and built nylas mail.
After startup it still prompts me to enter my nylas id.
Is there any way to use only the local sync engine part?

**Comment by OJFord** [comment]
> They are distributed separately (for now) but there is one repo for both.

Right now, the menu bar says 'N1' but the dropdown says 'About Nylas Pro' - so if I want to be on the 'Basic' tier, do I need to reinstall it?

Also - the pricing page says mail rules are added in Pro; blog post doesn't suggest they're even on the roadmap for Basic, but:
```
 * TODO: We don't have MailRules yet in Nylas Basic. Add this in when we
 * get mail rules.
```
(https://github.com/nylas/N1/blob/914ef12701a51c39d49a5de900b35da129655ffa/src/browser/nylas-pro-migrator.es6#L89-L90)

Pretty please? 👀 🦋

**Comment by aquila20** [comment]
I have the exact same question. Are re-installs necessary for the mac version, and for the Linux and Windows versions when they come out?

**Comment by OJFord** [comment]
@grinich My trial ran out, but now it refuses to connect altogether. What do I need to do to come off Pro and use the basic version? Reinstall?

(cc @aquila20)

**Comment by OJFord** [comment]
It seems a re-install of 'Nylas Mail' is necessary; so I've done so. On opening though it asks me to add email accounts again, and then errors. Screenshot in #3231 since it seems related.

**Comment by Vistaus** [comment]
I'm so interested in Nylas Mail for Linux, but I don't really understand why you push free (Basic) users to GMail even though Outlook is just as popular as GMail. Can't you add Outlook support to the Basic version as well instead of having to pay $12/month just for that?

**Comment by ArchangeGabriel** [comment]
@Vistaus What is wrong with using Outlook over IMAP?

**Comment by Vistaus** [comment]
@ArchangeGabriel Nothing, that's actually how I'm using it. But on the Nylas website it says that Outlook is only supported in the Pro version, not in the Basic version. Even though Outlook has a significant marketshare. That's why I asked if Outlook could be added to the Basic version as well.

**Comment by step21** [comment]
@ArchangeGabriel @OJFord I think problem many people had and not answered so far - what good is 'local sync' to me if I cannot actually run the app without a cloud account? This might make sense for you as a business, but f.e. can I just clone the repo and run it? Not currently I think. You/someone wrote that you 'can remove some features and run without login' (along those lines) but that would mean that it is not possible atm, right?
