### ISSUE TITLE
Gmail Hotkeys: "v" to move to folder

### ISSUE THREAD

**Issue by HackerCourtney** [nylas/N1#317]
I like to move messages into folders (or filters in Gmail) with hotkeys rather than dragging the message. In Gmail, the hotkey is "v" then a dropdown pops up and you can select where to move the message by typing the begining of the filter.

**Comment by bengotow** [comment]
This was added in 37e3fe0f4533ee5139cf0c27ee8cf9a008bc4ffe and will be included in the next release. Enjoy!
