### ISSUE TITLE
FastMail appears to have duplicate config

### ISSUE THREAD

**Issue by ocdtrekkie** [nylas/N1#3170]
Looking at the last commit that updates FastMail config, a duplicate configuration appears to have been added. Commit: https://github.com/nylas/N1/commit/c2a3dab18788312c5cedf80fe601138301eafcd1 File: https://github.com/nylas/N1/blob/master/internal_packages/onboarding/lib/common-provider-settings.json

In the commit, fastmail.fm's config was updated, and fastmail.com's config was added (line 32). But fastmail.com already had an entry at line 150. So the file contains two different configs for fastmail.com with different IMAP info, though I believe both are still valid.

Assuming I am correct, the second config, currently at line 150, should be removed from common-provider-settings.json

##### Are there any related issues?

Don't see any applicable.

##### What operating system are you using?
N/A

##### What version of N1 are you using?
N/A

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
N/A

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
FastMail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

**Comment by emorikawa** [comment]
@ocdtrekkie Yes! good catch. We have a patch in flight to fix this.

**Comment by ocdtrekkie** [comment]
I do see that the fastmail branch has updated the second copy of the config, though there are still two copies of it in that version.

**Comment by hallamoore** [comment]
The fastmail branch is stale, check out the n1-next branch instead! Here's the commit that removes the duplicate: https://github.com/nylas/N1/commit/4d690d46ab03297be84307e416fda641cf13d1d4

**Comment by ocdtrekkie** [comment]
Ah! Now I know where to explore, thank you.
