### ISSUE TITLE
Only "Send" listed in Send Behaviors

### ISSUE THREAD

**Issue by nickyhajal** [nylas/N1#3172]
##### What operating system are you using?

OSX

##### What version of N1 are you using?
v 1.0.8

--

I'd installed Nylas in the past but stopped using it. Just reinstalled to try again and found that in "Send Behavior" only "Send" is listed, there's no "Send & Archive" or anything else.

<img width="892" alt="nylas_mail" src="https://cloud.githubusercontent.com/assets/1079625/22025814/7e067e4e-dc94-11e6-8a68-375b9a3b1072.png">

**Comment by emorikawa** [comment]
@nickyhajal Send & Archive, Send Later, etc are coming soon to Nylas Mail Basic. For now, yes, that's a poor setting
