### ISSUE TITLE
Cannot auhenticate Gmail when user is already logged in to more than one account in browser

### ISSUE THREAD

**Issue by MateuszKubuszok** [nylas/N1#3177]
I weren't able to connect to Gmail similarly to https://github.com/nylas/N1/issues/2574 issue. However, after trying out several different things I was able to log in.

1. first i tried to log in using Chrome,
2. since I am logged in to 2 Google accounts at once I had to choose which one I want to use for authentication,
3. after choosing account and approving request for access I seen `Couldn't get authorization token from Google! Please try authenticating again.` communicate,
4. then I tried to log in using Firefox, where I was logged in into only one account, I was able to authenticate Nylas (after fixing `All email` label),
5. then I tried to add another Gmail account, so I logged in Firefox and authorized Nylas,
6. I saw `Couldn't get authorization token from Google! Please try authenticating again.` again,
7. I logged out of the first account and tried again to log in the the other one,
8. I succeeded.

For me it seems that authentication procedure do not handle the cases when uses is logged in to more than one account already. I guess this is hardcoded somewhere, since error about labels pointed to https://mail.google.com/mail/#settings/labels while the account I used, should use https://mail.google.com/mail/u/1/#settings/labels (notice additional u/1). Similar issue happened to me when I tried to log into Zenhub to check the issues, but I cannot tell if both sites use the same library, that makes wrong assumption or are those 2 bugs unrelated. But I think this issue might be responsible for at least some of https://github.com/nylas/N1/issues/2574 reports.

##### Are there any related issues?
https://github.com/nylas/N1/issues/2574

##### What operating system are you using?
Linux (Debian Jessie)

##### What version of N1 are you using?
1.5.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No, fresh install.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail provider

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
no

**Comment by jstejada** [comment]
Hi @MateuszKubuszok I'm merging this into duplicate issue #3179. Are you still having auth issueS?
