### ISSUE TITLE
Reminder to follow up with an email

### ISSUE THREAD

**Issue by HackerCourtney** [nylas/N1#318]
Instead of writing a to-do or setting a calender reminder, it would be cool to have a feature (similar to Boomerang: http://www.boomeranggmail.com/) where you can set a reminder to follow up on the sent email if the recipient does not respond.

**Comment by emorikawa** [comment]
@HackerCourtney another good package idea. I added it to the Trello board: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by hfossli** [comment]
This would be awesome. I think Nylas 1 is a perfect fit for this feature – having a server in between which is anyway active and dedicated.

**Comment by lotvall** [comment]
I would really like this :) - awesome idea!

**Comment by hallpower** [comment]
Would love this feature! Big part of my workflow with MailTags and Apple Mail.
