### ISSUE TITLE
Emails don't stay deleted

### ISSUE THREAD

**Issue by Naatan** [nylas/N1#3180]
Any time I delete an email it just returns in my inbox a few seconds later. Additionally it constantly says "Syncing your mailbox" at the bottom left of the app window, probably related?

It worked fine until I updated toversion 1.0.8 today.

##### What operating system are you using?

OSX 10.12.2

##### What version of N1 are you using?

1.0.8

##### Do you have any third-party plugins installed? If so, which ones?

Unsubscribe, avatars, jiffy

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I'm using Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Happens any time I delete an email

##### Does this feature exist in another mail client or tool you use?

No

**Comment by jstejada** [comment]
hi @Naatan I'm sorry to hear this! By deleting, do you mean moving to Trash?

**Comment by Naatan** [comment]
I assume so. I press the delete button at the top of the email.

**Comment by Naatan** [comment]
Worth noting my inbox is completely clean, maybe has 1 or 2 emails. It's not like it is syncing a ton of emails.

**Comment by mibanez** [comment]
Exactly the same problem, same versions of both OS and Nylas.

**Comment by jstejada** [comment]
thanks for the details @Naatan, @mibanez  ! We're working on a fix and should release a new version soon!

I'm going to merge this issue into #2706
