### ISSUE TITLE
Need an alternative to Thunderbird's feature of adding security exeptions

### ISSUE THREAD

**Issue by YuriSolovyov** [nylas/N1#319]
When trying to add internal corporate mail account, I get error message that I should check my credentials, even though they are correct, but in Thunderbird, they are accepted and the app prompts me with somehting like that:
![how-to-setup-email-on-thunderbird-09](https://cloud.githubusercontent.com/assets/2168518/10854143/ef056590-7f4a-11e5-8598-362ec3683977.png)
And then everything is working.

It would be great to have more control of security features (such as adding exceptions, tweaking crypto settings, etc.), I'm sure that is holding many people of using this great client.

**Comment by grinich** [comment]
All of that is handled in the https://github.com/nylas/sync-engine

**Comment by mbilker** [comment]
If the mail server has external access, then you should use the external access link or run your own instance of the sync engine as @grinich suggested.

**Comment by YuriSolovyov** [comment]
I'm sorry for late posting, but I not sure I understand: will this be integrated in client itself?
Or you are suggesting to write some kind of proxy with `sync-engine` to handle this?
