### ISSUE TITLE
what happened with the deb package cannot seem to download deb package anymore

### ISSUE THREAD

**Issue by NikosEfthias** [nylas/N1#3195]

**Comment by hallamoore** [comment]
Hi! We don't have a Linux build for Nylas Mail yet, but if you really want to you can check out the free trial in Nylas Pro. You can download Nylas Pro [here](https://billing.nylas.com/download-pro). The Linux build for Nylas Mail should be ready in a couple weeks, so stay tuned!

**Comment by ronisbr** [comment]
@hallamoore is there a beta tester program so that we can report bugs for linux of this new version of Nylas Mail?

**Comment by hallamoore** [comment]
@ronisbr No, not currently. Thanks for inquiring though!
