### ISSUE TITLE
Formatting Tool (Paste and Match Style)

### ISSUE THREAD

**Issue by HackerCourtney** [nylas/N1#320]
Often when you paste something into a message from a different location (copy a website link, from a Google Doc, etc) the formatting doesn't match the type font/size in the message. Gmail has a feature to format the text to plain text to make it uniform.

**Comment by emorikawa** [comment]
We currently strip the formatting from the message, but need to add the right-click option to "Paste and Match Style" still. We also will look into improving the current formatter to better match. Can you give me a specific example where the text you copied yielded output you didn't expect?

**Comment by HackerCourtney** [comment]
I haven't encountered this yet, mainly because I can't see how my messages send to the reciever. Happy to take a screenshot once I encounter this. 

My example was mostly in Gmail - the formatting gets wonky and never seems to match unless you remove the formatting.

**Comment by bengotow** [comment]
This has been fixed in 0.3.29. By default, Paste now uses more of the style / html on the pasteboard, and a new "Paste and Match Style" option (Command-Shift-V) allows you to paste as plaintext.
