### ISSUE TITLE
Nylas makes the pc almost unusable while synching

### ISSUE THREAD

**Issue by light2yellow** [nylas/N1#3202]
I experience very heavy disk load and cannot use the pc while nylas is resynching emails (after the dropped connection, see next issue). This is not the intended behaviour. Nylas shouldn't eat all the RAM (and probably even the half of it).
<img width="616" alt="screen shot 2017-01-20 at 22 42 18" src="https://cloud.githubusercontent.com/assets/10786469/22166595/1fd77fb4-df62-11e6-803e-6ef6b0288231.png">
1.0.10, sierra .2

**Comment by jstejada** [comment]
hi @light2yellow ! I'm sorry to hear this! Thanks for reporting this. We're pushing a fix out today that I think will fix this. If it doesn't feel free to reopen this issue.
I'm also referencing #3178 which is related

**Comment by jstejada** [comment]
I'm actually merging it into #3178
