### ISSUE TITLE
Nylas cannot reconnect to Yahoo account after dropped authentication

### ISSUE THREAD

**Issue by light2yellow** [nylas/N1#3203]
Nylas automatically dropped authentication (for no reason, that's another issue but I'll leave this ticket on you) with both Gmail and Yahoo and while Gmail reauthenticated successfully, Yahoo said "Request Aborted". This worked before.
<img width="529" alt="screen shot 2017-01-20 at 22 50 43" src="https://cloud.githubusercontent.com/assets/10786469/22166839/5ee97738-df63-11e6-9693-969c3a1022c5.png">
1.0.10, sierra .2

**Comment by jstejada** [comment]
Hi @light2yellow, sorry to hear you are having trouble!
We've released a couple of auth fixes and releasing a new build today. Let me know if you continue having issues after that.

Thanks!

**Comment by light2yellow** [comment]
Thank you for the response, I'll try it as soon as the new version appears through "Check for the update" button.

**Comment by jstejada** [comment]
@light2yellow  We've released v. 1.0.11. Let me know if you are still having issues!

**Comment by light2yellow** [comment]
Successfully connected, thanks.
