### ISSUE TITLE
Questions about Nylas Pro

### ISSUE THREAD

**Issue by ronisbr** [nylas/N1#3205]
Hi guys,

First of all, sorry if this is not the right channel to ask about general questions. I really did not find any other place.

After the huge sync-engine modification with Nylas N1 PRO, I am really thinking to buy this plan. However, I have a specific use case, so there are somethings that must be clarified.

First, I have some Gmails and Yahoo accounts and some IMAP accounts from my institution. For the former, I really want all those PRO features, like snooze, reminders, send latter, etc., and I don't mind if the traffic of something goes through the online sync-engine. On the other hand, the IMAP accounts from my institution usually needs to be classified and I must not let any of the message traffic goes anywhere besides the IMAP server. Fortunately, I really don't mind those PRO features on those accounts. My questions is: is this feasible? Can I completely disable the communication with the online sync-engine for just some of my e-mail accounts?

Best regards,
Ronan

**Comment by GM-Polyakov** [comment]
@ronisbr Currently the only was to do this would be to no connect your classified IMAP account to Nylas Mail Pro. 

However, we will very soon - within the next few weeks -  be releasing a version with all the features you're interested in, but without and Cloud Sync at all.
