### ISSUE TITLE
Failed on Onboarding

### ISSUE THREAD

**Issue by amicablewings** [nylas/N1#3206]
version 1.0.11

Gmail, Yahoo, iCloud Accounts are all getting stuck on sign up. Custom IMAP not functioning. 

We were unable to reach your mail provider. Please try again.

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of N1 are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by jstejada** [comment]
Hi @amicablewings , thanks for reporting this. I'm merging it into duplicate issue #3179
