### ISSUE TITLE
Nylas Pro: Archive folder included as All Mail folder in unified view

### ISSUE THREAD

**Issue by kun-zhou** [nylas/N1#3214]
##### Are there any related issues?

...Not that I can see

##### What operating system are you using?
...Arch Linux

##### What version of N1 are you using?
... Latest Pro.

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
... No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... Exchange and Gmail together.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes. Whenever I have both Exchange(Mine is office365) and Gmail accounts added to Nylas, the exchange account's Archive is included in the All Mail in the unified View. Individual View however correctly shows the the folder name Archive. As shown in the scrren show the Exchange folder under All Mail unified view All Mail folder is in fact an Archive folder. (See the icon if you don't believe me)
![nylas_bug_report](https://cloud.githubusercontent.com/assets/19158151/22237470/ff1b4d3a-e1d9-11e6-9996-35f5c1142fa0.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
It will be great if users are allowed to directly choose what folders are suppsoed to merge and what are not.

**Comment by jstejada** [comment]
Hi @kun-zhou, thanks for bringing this up. This is actually intentional because the "archive" folder is actually `All Mail` in Gmail.

Hope this helps. Thanks!

**Comment by kun-zhou** [comment]
Hello jstejada, I understand that when I archive in gmail, the mail will loose its labels and move to All Mail folder. To that end, All Mail and Archive serve the same purpose. But what bothers me and for sure other people is that gmail's All Mail actually includes all mail, but Exchange's Archive does not include all mail. However, in unified view, they are labelled as All Mail altogether. Something like 'All Mail/Archive' will work better, or maybe better just let users choose the name of the unified view folder and choose which folder should be in the unified view. Thanks!
