### ISSUE TITLE
A single email keeps being marked as "unread" even after i read it

### ISSUE THREAD

**Issue by OranShuster** [nylas/N1#3218]
##### What operating system are you using?
MacOS Sierra 

##### What version of N1 are you using?
1.0.11

this only happens on the office 365 account i have (work email)
before that it was another email which i deleted. 
steps to reproduce-
1.right click email->mark as read
2."Syncing your mailbox" will appear and the mail will disappear from "Unread" view
3.Wait a couple of minutes and the mail will reappear 

i couldn't look at the logs because of #3217

**Comment by jstejada** [comment]
Hi @OranShuster -- thanks for bringing this to our attention. We are shipping a release today which should fix this. Thanks!

**Comment by jstejada** [comment]
we've released a fix for this in 1.0.15!
