### ISSUE TITLE
IMAP and SMTP username/password cannot be different

### ISSUE THREAD

**Issue by caske33** [nylas/N1#322]
Sometimes you just want to read e-mails without sending them.

E.g. I have an office365 exchange account with a shared mailbox. I can't get it to work with the exchange option in nylas itself, so I tried with IMAP/SMTP. The imap works if you use `username@domain\shared-mailbox` as username for the IMAP. For the SMTP server however, you have to use the same username and password as for the main account. For some reason I get the error message `Please check that your SMTP settings are correct` even though my credentials are correct.

Considering I don't need the SMTP as I just want to read the e-mails, it would be nice if it were possible to skip the SMTP step.

**Comment by bengotow** [comment]
Hi @caske33 — we don't have any plans to support IMAP without SMTP, but it sounds like you may have stumbled onto an auth bug. I'll check that out and keep you posted.

**Comment by caske33** [comment]
Okay thanks.

**Comment by caske33** [comment]
@bengotow Did you find a solution for this problem?

**Comment by bengotow** [comment]
Hi @caske33 — this should be fixed now, can you give it another go and see if you can add the account?

**Comment by caske33** [comment]
It doesn't seem to work. In which version is this fixed? Maybe I'm still on the old (0.3.32-b11...)

**Comment by grinich** [comment]
@caske33 Does it work now? I think we hadn't actually pushed the fix.

**Comment by mlcdf** [comment]
I don't think so, I had the same issue yesterday.

**Comment by caske33** [comment]
@grinich I'm now on `0.3.36-e8239` and it's not working yet.

**Comment by caske33** [comment]
Still a problem on `0.3.43`

**Comment by casualformality** [comment]
I'm stoked for this feature to get included. Running `0.3.43` as well on Arch Linux and having the same problem.

**Comment by caske33** [comment]
@bengotow Still a problem on `0.3.45`.

**Comment by spang** [comment]
This is a problem in the sync engine infrastructure, so N1 app updates won't help—we're working on it!

**Comment by caske33** [comment]
Oke! :)

**Comment by logandavis** [comment]
We just deployed a backend update to fix this issue. If you continue to have problems authenticating generic IMAP accounts that use IMAP/SMTP-specific credentials, please email support@nylas.com.

Thanks for your patience!
