### ISSUE TITLE
Nylas Mail, Mac, High Energy Impact 

### ISSUE THREAD

**Issue by rubengarciam** [nylas/N1#3220]
Since I updated Nylas N1 to Mail the energy impact on my Mac's battery has gone off the roof. Way way above any other mac app, drastically affecting (obviously) the battery hours left.

Is this a known issue?

**Comment by flyingclimber** [comment]
We've been actively discussing and coming up with better ways of managing the local sync process per https://github.com/nylas/N1/issues/3178. Stay tuned for our next releases which should really help.

**Comment by jstejada** [comment]
@rubengarciam, 1.0.15 comes with some fixes to improve battery performance!

**Comment by rubengarciam** [comment]
@jstejada massive improvement in 1.0.15! Congrats
