### ISSUE TITLE
Send button not easily accessible

### ISSUE THREAD

**Issue by DonSS** [nylas/N1#323]
When forwarding an email, the 'Send' button is at the bottom of the email chain. So, if the original email happens to be long, there is a lot of scroll down to do to get to the Send button (or delete draft button). Can these be moved to the top?
Version: Windows (Split screen layout)

**Comment by grinich** [comment]
We're going to keep it at the bottom for now. Thankfully you can fold the quoted text!

**Comment by r-murphy** [comment]
I'm not able to fold the text which is being forwarded ( an html email from an airline so it's really long). 
It would be great if this could be a setting.
