### ISSUE TITLE
Feature request: unread counts for all folders and labels

### ISSUE THREAD

**Issue by axllent** [nylas/N1#327]
The folder structure doesn't show an "unread count" for any labels with the exception of Inbox & Drafts. Can this be added please? 

Currently the only "solution" seems to be to search to "is:unread", however that would probably be Gmail-specific, and isn't ideal.

**Comment by bengotow** [comment]
Hi @axllent — this landed today in b2f8b34a32d87f59c13a77d3a3d74cf5ca4c715b and will be included in the next release. Just as a side note, you need to turn on "unread counts for all labels" by going to Preferences > Workspace.

**Comment by axllent** [comment]
Awesome, looking forward to the next release! Thanks.
