### ISSUE TITLE
Composing with inline images

### ISSUE THREAD

**Issue by axllent** [nylas/N1#328]
Composing a message with inline images (such as a graphic signature) doesn't (yet?) seem to be supported. Is this planned?

**Comment by jwood803** [comment]
Didn't see this in the Trello roadmap, but I'll vote for this as well. This would help for sending screenshots and such.

**Comment by Naph** [comment]
I would like to request this feature as well. It's handy to forward and compose emails where the image remains as a visual cue inline.

**Comment by jwood803** [comment]
I may have been mistaken and found [this](https://trello.com/c/m9IFvC60/39-inline-images-in-composer) in the roadmap. Whoops! Good to see it there and with votes!

**Comment by bengotow** [comment]
Merging in to #968 since there's more conversation there.
