### ISSUE TITLE
Publish binaries in GitHub releases

### ISSUE THREAD

**Issue by IonicaBizau** [nylas/N1#33]
It would be great to publish the binaries in GitHub releases page. :sparkle:

**Comment by SamyPesse** [comment]
It might be useful: https://github.com/GitbookIO/nuts

**Comment by Pym** [comment]
+1 for the binaries!

**Comment by dillonforrest** [comment]
This is a great idea! We will definitely look into this!

**Comment by sg-s** [comment]
+1

**Comment by AlexBoorman** [comment]
+1

**Comment by cagartner** [comment]
+1

**Comment by sbilly** [comment]
+1

**Comment by IonicaBizau** [comment]
@dillonforrest And I forgot to tell you congrats for nice project! :clap: :grin:

**Comment by laughedelic** [comment]
+1

**Comment by valeriocuscuna** [comment]
+1

**Comment by bengotow** [comment]
Hey folks—we've decided not to post binaries to GitHub for the time being, but you can always download the latest builds using the links below and (soon...) a standard download page on the website:

Mac: http://edgehill.nylas.com/download?platform=darwin
Linux: http://edgehill.nylas.com/download?platform=linux (more flavors soon)
Windows: http://edgehill.nylas.com/download?platform=win32

The N1 binaries contain material that isn't in this repository, like licensed fonts and sounds, and we're not sure about the license implications of posting built versions to GitHub. N1 is also coupled to the Nylas Sync Engine, and as we move forward with feature development there won't be much of a reason to grab older releases. We've built auto-updaters into the app and hope to keep the entire community moving forward on the latest versions.

**Comment by Hronom** [comment]
+1

**Comment by DanielBocksteger** [comment]
> Am 22.10.2015 um 21:08 schrieb Ben Gotow <notifications@github.com>:
> 
> Hey folks—we've decided not to post binaries to GitHub for the time being, but you can always download the latest builds using the links below and (soon...) a standard download page on the website:
> 
> Mac: http://edgehill.nylas.com/download?platform=darwin <http://edgehill.nylas.com/download?platform=darwin>
> Linux: http://edgehill.nylas.com/download?platform=linux <http://edgehill.nylas.com/download?platform=linux> (more flavors soon)
> Windows: http://edgehill.nylas.com/download?platform=win32 <http://edgehill.nylas.com/download?platform=win32>
> The N1 binaries contain material that isn't in this repository, like licensed fonts and sounds, and we're not sure about the license implications of posting built versions to GitHub. N1 is also coupled to the Nylas Sync Engine, and as we move forward with feature development there won't be much of a reason to grab older releases. We've built auto-updaters into the app and hope to keep the entire community moving forward on the latest versions.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/nylas/N1/issues/33#issuecomment-150325346>.
> 

These Links are not reachable...

**Comment by AlexBoorman** [comment]
^ not working for me either

**Comment by bengotow** [comment]
Sorry folks—needed to be https://. I've updated the comment above—enjoy!

**Comment by brothersgroupjsrbd** [comment]
https://github.com/nylas/N1/issues/33#issuecomment-150325346

**Comment by geekpete** [comment]
+1

**Comment by geekpete** [comment]
Ok, got the binary, installed it, when running it, it's now asking for invitation code.

The link in my actual invite email telling me to download didn't work at all, which is why I came looking here.

Is there a way to extract my personal invite code from the email that was sent out?

**Comment by grinich** [comment]
Hey @geekpete -- send a note to support@nylas.com and we'll send you a new invite code.

**Comment by geekpete** [comment]
Thanks!

**Comment by geekpete** [comment]
Emailed yesterday, still haven't heard back.
