### ISSUE TITLE
Right click context menu on list items

### ISSUE THREAD

**Issue by gregwburke** [nylas/N1#330]
Would be great to see a right click menu similar to what's in Gmail right now. I often archive/delete/move emails using this feature and was disappointed when right clicking did nothing at the moment.

**Comment by tommarshall** [comment]
I'm trying Nylas as a replacement for Airmail and the lack of a context menu is causing a noticeable disruption to my usual email workflow. It'd be great to see this in Nylas.

Airmail adds additional options to the context menu that aren't present in Gmail. Adding a label is a really useful, would be good to include that as well if possible.

![Airmail context menu](http://cl.ly/image/1U0l2K170l1u)

**Comment by grinich** [comment]
@tommarshall is this a context menu when you right-click a thread in the thread list?

**Comment by tommarshall** [comment]
@grinich yes it it. Personally I think there's to much in here, but it is useful to have.

**Comment by tommarshall** [comment]
I actually personally preferred the thread context menu in sparrow:

<img width="212" alt="screen shot 2015-11-25 at 08 54 39" src="https://cloud.githubusercontent.com/assets/1125251/11392557/78aaa402-9352-11e5-8fd8-31a95f92cbf5.png">

**Comment by bengotow** [comment]
Hey folks! We added a basic context menu for thread list items in the latest release - 0.4.14. Check it out! We'll expand the menu soon to include more options.

**Comment by Cu8eR** [comment]
+1
