### ISSUE TITLE
Support "del" key out of the box

### ISSUE THREAD

**Issue by ecki** [nylas/N1#331]
When selecting one or more messages (in draft folder) the "Del" Key does not work in Windows. This is a pretty common key-usage (and should be present at least in the "Outlook" shortcut setting).

**Comment by bengotow** [comment]
Hi @ecki — can you see if you still have this issue in version 0.3.20? I think that we fixed this, but I may not be simulating the Delete key correctly in my Windows VM.

**Comment by ecki** [comment]
Yes I tested it again and now it works. Very strange I am not sure if it updated in the meantime. At least I can confirm it is fixed in 0.3.20.
