### ISSUE TITLE
Up/down arrows should scroll window, not load prev/next threads

### ISSUE THREAD

**Issue by axllent** [nylas/N1#334]
I believe that the up/down arrow keys should scroll the window up & down in the message view, and not open previous/next threads (tested on Ubuntu).

**Comment by bengotow** [comment]
Sorry this is by design—you can move up and down within a thread using the page up / page down keys.

**Comment by axllent** [comment]
In my opinion that is a very non-standard (& bad, not to mention annoying) design. Whilst I understand that not all users know about (or understand) the j/k keys, and that using the cursors would be easier, then may I propose rather using the left & right arrows to view the previous / next thread (while in the reading-message view), and restoring up/down keys to page scrolling (as it is in every other program on every OS... ever)?
