### ISSUE TITLE
Document OAUTH keys in "Running Against Open Source Sync Engine" instructions

### ISSUE THREAD

**Issue by lorenzhs** [nylas/N1#336]
Currently, when running against a self-hosted sync engine, the sync engine will use a default project for which the OAuth client secret is [public](https://github.com/nylas/sync-engine/blob/master/etc/secrets-dev.yml). This might not be the most secure approach, and it would be nice to have quick instructions on how to set up your own OAuth with Google and Microsoft (or at least a warning that the default should only be used with test accounts).

Should I file this issue with the sync engine repository as well?

**Comment by bengotow** [comment]
Hi @lorenzhs — thanks for filing this. The open source sync engine doesn't come with any security layer whatsoever out of the box, and you should definitely not host it on the open internet without adding an authentication layer and swapping out the secrets.

I've passed this on to the platform team running the sync engine, and we'll update the sync engine docs to be more explicit about the lack of security, and include some pointers for creating your own OAuth credentials.

**Comment by lorenzhs** [comment]
Thanks! I was only trying it out locally, and it looks really cool so far :)
