### ISSUE TITLE
Windows Installer Crashing

### ISSUE THREAD

**Issue by EroticD** [nylas/N1#338]
System is as follows: Fujitsu LIFEBOOK U772 
Intel® Core™ i7-3687U processor, 4 MB, 2.1 GHz, up to 3.3 GHz 
8 GB, 1 Memory slot(s) DIMM (DDR3)DDR3 - 1,600 MHz 
SSD SATA III, 256 GB, 2.5-inch 
Intel® HD Graphics 4000 with 3rd generation Core i processors 
LTE Sierra Wireless MC7710 
Intel® Centrino® 6205 802.11 a/b/g/n 

Log: http://pastebin.com/umwbxTJb

**Comment by isacikgoz** [comment]
same here, 

the error caused by: 
```
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\my.user\AppData\Local\atom\packages\RELEASES'.
```
![image](https://cloud.githubusercontent.com/assets/2153367/11056884/faf7f4ac-878e-11e5-9a62-d59fca6b6be9.png)

The file is right there, is there any problem with dots in the filepath?

**Comment by EroticD** [comment]
My path needs C:\Users\me\AppData\Local\nylas\packages and errors out there.

**Comment by isacikgoz** [comment]
That could be caused by dots or blank spaces. :confused:

**Comment by EroticD** [comment]
Could. No dots or spaces found in the log though.


Sent using CloudMagic Email<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.55&pv=5.1.1&source=email_footer_2>
On Thu, Nov 12, 2015 at 9:15 am, Ibrahim Serdar Acikgoz <notifications@github.com<mailto:notifications@github.com>> wrote:


That could be caused by dots or blank spaces. [:confused:]

-

**Comment by mbilker** [comment]
Does this still occur?

**Comment by EroticD** [comment]
No. Issue resolved.  
  

________  

= Eqal  

Kristoffer Garshol  
93007990  
  

[Helpdesk](http://eqal.no/help "http://eqal.no/help" ) | [Web](http://eqal.no
"http://eqal.no" )

> On Feb 4 2016, at 5:11 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Does this still occur?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/338#issuecomment-179922091).![](https://github.com/notifications/beac
on/AMFsmv9Jxudaa3Yye3r06bxzZFymCj9kks5pg2_JgaJpZM4GZ6gD.gif)
