### ISSUE TITLE
Auth with 163.com — Request timeout

### ISSUE THREAD

**Issue by nkuflk** [nylas/N1#339]
last week, i try to add 163 mail to my local N1 app, but i get 'request timeout'. i tried many times.

**Comment by bengotow** [comment]
Hi @nkuflk — I've filed this with our platform team. @khamidou might have some thoughts.

**Comment by trazyn** [comment]
i have the same problem :sweat:

**Comment by kav-ya** [comment]
@nkuflk, @trazyn - thanks for the report!
Could you please email support@nylas.com with the email address you're attempting to connect? (Since this is personal information, we ask that you email us rather than posting here). We'll take a look.

**Comment by JSW5297** [comment]
@nkuflk @trazyn 你们现在163邮箱能登陆上吗？我也遇到这个问题

**Comment by zjn1234** [comment]
is this problem resolved?  i have the same

**Comment by xueshichaoya** [comment]
haha, i have the same problem, my xxx@163.com can use in Thunderbird mail,but can't synchronize in Nylas. xxx@qq.com is OK both
