### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by nunofgs** [nylas/N1#34]
Any chance N1 will get Markdown support somewhere down the line?

**Comment by suchanlee** [comment]
It seems like you should be able to create a plugin for it

**Comment by bengotow** [comment]
Hey! This sounds great. I'd love to be able to type Markdown into the composer. We're creating a public Trello board to keep track of package ideas. I'm going to file this there—feel free to upvote it on Trello.

https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by evenh** [comment]
@nunofgs: I have started on a package [here](https://github.com/evenh/n1-markdown)

**Comment by nahtnam** [comment]
+1 Most email clients are missing markdown and I would willingly switch to one that supports it.

**Comment by evenh** [comment]
It's ready for public testing, but it is blocked by #283

**Comment by orschiro** [comment]
Any updates on this? 

I would love to switch from Inbox by Gmail and the fantastic [Markdown Here](https://github.com/adam-p/markdown-here) but not having support for Markdown in Nylas N1 is preventing me so far. 

Thankfully,

~Robert

**Comment by claui** [comment]
@bengotow I can’t find a card with a Markdown feature request on your Trello board.

Would you mind linking it from here? With Markdown all over the place recently, I’m curious to know how much this is in demand.

**Comment by RTbecard** [comment]
Can this issue be reopened?  The plugin referenced hasn't been updated in 2 years.  I'm using 2.0.32 and I don't see any markdown features included by default, or perhaps I'm missing something?

**Comment by laughedelic** [comment]
@RTbecard you're missing #3564
