### ISSUE TITLE
hope to auto connect imap, smtp

### ISSUE THREAD

**Issue by nkuflk** [nylas/N1#340]
you can hold a list of imap,smtp， user just select the e-mail company, don't need to fill the blank

**Comment by bengotow** [comment]
Hi @nkuflk — can you expand on what you mean? Are you wanting an IMAP/SMTP autodiscovery feature?

**Comment by nkuflk** [comment]
@bengotow Yes, i want an imap/smtp autodiscovery ferture.  Now, if i want to add a email account, i have to click many times, it's not a good experience

**Comment by kfix** [comment]
It's possible if your provider has [published SRV records](http://blog.returnpath.com/srv/) pointing to your account's IMAP and SMTP servers.

**Comment by bengotow** [comment]
Merging this into #1045
