### ISSUE TITLE
Cannot connect to Gmail (GAPS) account

### ISSUE THREAD

**Issue by ludekvodicka** [nylas/N1#346]
Nylas isn't able to connect to my gmail account. It was paired by using "Gmail" selection in Add new account.

![nylas](http://i.imgur.com/KZr7Hcl.png)

There is no error message. Only "Try again now" button on bottom left

**Comment by derappelt** [comment]
Same Problem!
Writing emails is working! @ludekvodicka  can you confirm this?

**Comment by ludekvodicka** [comment]
@derappelt  You're right. Writing and sending emails works ok.

**Comment by palogorog** [comment]
same problem!
can confirm writing and sending emails works.
syncing not!

**Comment by ishanthukral** [comment]
Took a few tries (clicking "try again now"), but eventually worked for me.

**Comment by palogorog** [comment]
get a some time and syncing is already working

**Comment by ludekvodicka** [comment]
Tried several times during a whole day without any success

**Comment by derappelt** [comment]
Din't started N1 for a few days. Now everything works fine! Probably a Nylas traffic problem?

**Comment by emfree** [comment]
Closing as stale; please reopen if you are still having issues!
