### ISSUE TITLE
How does N1 (and Sync Engine) communicate with email provider's APIs?

### ISSUE THREAD

**Issue by jimeh** [nylas/N1#35]
I've had a quick look around the docs for N1 and your [Sync Engine](https://www.github.com/nylas/sync-engine), and rather than digging into the code of N1, I figured I'd post an issue as others might be curious too.

I'd like some clarifications on the following questions:

- Does N1 communicate directly with Gmail/Yahoo/Outlook/Exchange/etc APIs? Or does it communicate with a Sync Engine instance running on your servers which in turn communicates directly with the email providers' APIs?
- If N1 does communicate via a Sync Engine instance on your servers:
    - Can Sync Engine be embedded into N1 itself?
    - Can a person/company run their own private instance of Sync Engine and have N1 connect to said instance instead of your public one?
    - What kind of data protection procedures do you have in place to protect your users' private email in the case you got hacked?

I'm not a security expert, and sure email is mostly "public" as it flows across the internet, but I'd still be more cautious about using N1 if all my email flows through a 3rd-party server.

As a final note, N1 seems really cool, aside from some syncing issues I have with it for now, I'm liking it :)

**Comment by CrisBRM** [comment]
I'm interested in this as well.

**Comment by joerocklin** [comment]
It looks like there is an open version of the sync engine at https://www.github.com/nylas/sync-engine

**Comment by jimeh** [comment]
@joerocklin Indeed, I forgot to link it to. That repo is what made me think that N1 communicates through a remote Sync Engine instance run by Nylas, rather than Sync Engine being part of N1 and running within the local app.

**Comment by jacobmischka** [comment]
Despite it being omgubuntu and not having any sources, [this](http://www.omgubuntu.co.uk/2015/10/n1-open-source-email-app-linux) answers a few of your questions.

**Comment by jimeh** [comment]
@jacobmischka Indeed it does. There doesn't seem to be any obvious Sync Engine hostname/server settings in N1 at this time though. So you probably can't use your personal instance unless you dig through the code a decent bit.

**Comment by jacobmischka** [comment]
I've tried none of this, but 

```coffeescript
    if env in ['production']
      @AppID = 'eco3rpsghu81xdc48t5qugwq7'
      @APIRoot = 'https://api.nylas.com'
    else if env in ['staging', 'development']
      @AppID = '54miogmnotxuo5st254trcmb9'
      @APIRoot = 'https://api-staging.nylas.com'
    else if env in ['experimental']
      @AppID = 'c5dis00do2vki9ib6hngrjs18'
      @APIRoot = 'https://api-staging-experimental.nylas.com'
    else if env in ['local']
      @AppID = 'n/a'
      @APIRoot = 'http://localhost:5555'
```
https://github.com/nylas/N1/blob/master/src/flux/nylas-api.coffee

It looks like you can change the environment in `~/.nylas` according to https://github.com/nylas/N1/blob/master/dot-nylas/config.cson

**Comment by bengotow** [comment]
Hey folks! @jimeh, you'll find answers to most of your questions over here: https://nylas.com/N1/faq.

N1 connects to mail providers through the Nylas Sync Engine, which handles all the old protocols, annoying variations in IMAP, etc. It exposes a nice REST API, and the mail client consumes that.

You can totally run it yourself—there are instructions at https://github.com/nylas/sync-engine/blob/master/README.md for running the sync engine. You could deploy it, but the open-source version of the sync engine doesn't include any security measures out of the box. We take security seriously—you can read about the security measures in the hosted version of the sync engine here: https://nylas.com/security.

Theoretically, you could embed the sync engine into a build of N1, but it'd be a massive app and a significant pain to update / migrate when we release new features exposing new API endpoints for search, email metadata, etc.

If you want to run the entire stack yourself, there are also instructions here for making your copy of N1 use your copy of the sync engine: https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine

**Comment by jimeh** [comment]
@bengotow It seems the navbar on the N1 website is a bit broken in Safari, which is why I completely missed the FAQ's existence. Stupid Chrome and it's CPU/battery eating forcing me into the corrupt arms of Safari :P

Regarding embedding Sync Engine, I fully understand the difficulties of doing so after having a closer look at how it's actually put together. So I wouldn't expect you to do that, or believe it to be a good solution. At least not without a complete rewrite so it's more of a library than a whole server-side app.

Anyway, thanks for the info, and keep up the good work :)

**Comment by lkraav** [comment]
One thing I still don't understand is how do I point N1 to a remote custom sync server? `~/.nylas/nylas-api.coffee`?

**Comment by jacobmischka** [comment]
It looks right to me, but I haven't read anything about it.

**Comment by lkraav** [comment]
> It looks right to me, but I haven't read anything about it.

https://github.com/nylas/N1/blob/master/src/flux/nylas-api.coffee looks super complex. I haven't found a single example on how to override individual pieces of it.

**Comment by jacobmischka** [comment]
I haven't tried anything, but my guess would just be to replace lines 149 and 150, and then set the environment to `experimental` in `~/.nylas`.
