### ISSUE TITLE
Disable keyboard shortcuts completely

### ISSUE THREAD

**Issue by singh-jaspal** [nylas/N1#350]
An option to do this can help prevent any oversight in messages that may be deleted or displaced, etc.

**Comment by bengotow** [comment]
Hi @singh-jaspal — this isn't currently on the roadmap, but pull requests are welcome!

**Comment by bengotow** [comment]
The "Apple Mail" and "Outlook" presets are both pretty limited and don't include any shortcuts activated by single keys (they're all Ctrl+<Key>). Removing all of them would likely confuse most people, so we're going to close this for now.

**Comment by singh-jaspal** [comment]
Sorry, I meant more for an option to. Not to completely remove it. That was
some poor wording on my part. Gmail offers this (although it uses single
key shortcuts).
