### ISSUE TITLE
Windows 10 shortcut / app icon are not the correct resolution

### ISSUE THREAD

**Issue by artailicous** [nylas/N1#351]
When one tries to attach the icon to the taskbar, it produces a second icon except one for the instance of N1 running. Also the icon itself is not adopted to Windows 10 resolution for icons. There are probably more things that shows that the program is not proper adopted too Windows 10.

**Comment by bengotow** [comment]
You're definitely correct - unfortunately, none of the N1 core contributors are Windows users and it shows! Pull requests welcome!
