### ISSUE TITLE
No 64 bit support

### ISSUE THREAD

**Issue by artailicous** [nylas/N1#352]
The Nylas N1 application that I got access to download is 32 bit. Hence there appear to be no 64 bit support for Windows. I have no idea of there are 64 bit support for OSX and Linux (such as Ubuntu). Hopefully there are, if not, then these operating systems need 64 bit support aswell.

**Comment by bengotow** [comment]
Hi @artailicous — we ship 64-bit builds for Mac OS X and Linux, but not for Windows. libchromiumcontent has only supported 64-bit on Windows for the last few months (#980) and I don't think there's an urgent reason to update our toolchain to use it. If there's something blocking you from using the 32-bit build, feel free to re-open and we'll get it done sooner!
