### ISSUE TITLE
Sent items showing in draft box

### ISSUE THREAD

**Issue by cgasnier** [nylas/N1#354]
Hi,

I've installed N1 yesterday (great tool, great design ! thank's) with an Exchange mailbox.
After N1 had syncing my mails with the server, I've noted that all my "Sent box items" where recorded in "Draft items" box

Thank's

**Comment by rdewolff** [comment]
Related to https://github.com/nylas/N1/issues/471

**Comment by rdewolff** [comment]
Still have that problem @cgasnier ?

**Comment by jstejada** [comment]
merging into #869
