### ISSUE TITLE
In split view, double-click thread to open in new window

### ISSUE THREAD

**Issue by kenrick95** [nylas/N1#355]
Just like Outlook split-view, double clicking the email (in the e-mail list) will pop out a new window containing the e-mail. This is for the convenience of reading the e-mail in a maximized window.

For me, the split-screen is for quick preview of the e-mail and if there are some elements that need full width to read (e.g. large image), I usually read the e-mail in a separate pop-out window (and I maximized that window).

**Comment by frenchbread** [comment]
+1

**Comment by bengotow** [comment]
Merging this into #779
