### ISSUE TITLE
Forcing the default

### ISSUE THREAD

**Issue by davidhq** [nylas/N1#356]
I ran N1, set it to default and then quit
I opened MailPlane and set this back to default but N1 kept getting back to be the default.

Then I noticed that after I quit N1, some N1 process was still running and it was periodically setting N1 as  a default email client.

1) Why is it doing this?
2) Why is something still running when I quit the app?

**Comment by bengotow** [comment]
Hi @davidhq — I assume you're on a Mac? N1 only becomes the default mail client when you check the box in preferences or the notification. However, on Mac OS X, running applications responding to mailto:// will be given preference over the default application if it's not running. (So for example, if I have Chrome running, http:// links will open in Chrome, even if Safari is set as the system default.) I imagine force-quitting that process that is stuck in the background will solve the problem.

Re: still running in the background—it sounds like this issue, which we're fixing in the next release: #173

**Comment by davidhq** [comment]
Thank you for explanation!
