### ISSUE TITLE
Reset after each update

### ISSUE THREAD

**Issue by laughedelic** [nylas/N1#357]
After each update of the client, it gets reset to the state as if it was installed from scratch, I have to enter the invitation code and activate may gmail account. I'm not sure wether this is caused only by updates, because lately it was happening more frequently: I opened the window, it was messed up (I'll make a screenshot next time), I quit, opened the app again, and it's reset (again invitation code, etc.).

**Comment by bengotow** [comment]
Hi @laughedelic — are you receiving updates via the auto-updater built into the app, or rebuilding from source? If you're building from source, I think our `cibuild` script wipes your `~/.nylas` folder, that could be the problem.

**Comment by laughedelic** [comment]
@bengotow I'm receiving updates through the auto-updater, I didn't do anything with sources.

**Comment by bengotow** [comment]
Merging this into https://github.com/nylas/N1/issues/314
