### ISSUE TITLE
Second mailbox not syncing

### ISSUE THREAD

**Issue by DonSS** [nylas/N1#358]
I have added 2 IMAP mail accounts to N1. However, only the first one is fully synced i.e. past + incoming new mails. For the second account, only new incoming mails are listed. The older emails are not getting synced. I also deleted the 2nd account and re-created it, but the result was the same.

**Comment by bengotow** [comment]
Hi @DonSS — thanks for downloading N1! This was most likely an issue with our infrastructure—we had a ton of signups in a single day a few weeks ago and encountered major sync performance degradation. Can you try opening N1 again and see if mail is available in both your accounts?

**Comment by DonSS** [comment]
Hi bengotow,
I checked again. and the second account still doesn't sync the past emails. I can confirm that the new emails are coming though. I even deleted that account and re-configured it, but same result. Am not using N1 regularly as I constantly need the older emails (so using thunderbird), so took a while to respond.

**Comment by xGreenstar** [comment]
I'm having same issue as DonSS.  I am wondering if this is a premium feature that must be paid for?  My email account is generic IMAP with same mail server as the first account so I know its not the settings.
