### ISSUE TITLE
Allow IMAP with no SMTP accounts

### ISSUE THREAD

**Issue by ecki** [nylas/N1#359]
As mentioned in Issue #344 I was not able to add the SMTP part of a custom server. However it looks like IMAP passed just fine. It would be good to add such a "read only" account, it is not unusual to have those.

**Comment by bengotow** [comment]
Hi @ecki — this isn't currently on the roadmap. Support for IMAP without SMTP would need to be added to the sync engine (http://github.com/nylas/sync-engine). Pull requests are welcome!
