### ISSUE TITLE
Add Persian language support

### ISSUE THREAD

**Issue by hadifarnoud** [nylas/N1#36]
Please add Persian (or any other RTL language) support. We can at least start with RTL support in the editor.

just like Gmail, as I start typing in an RTL language like Persian, the direction of text should change to RTL.

**Comment by dillonforrest** [comment]
Hey @hadifarnoud! We have some dialogue in #24 about adding translations. I'm closing this issue in favor of that one. Thanks for the great suggestion!

**Comment by royts** [comment]
https://github.com/nylas/N1/issues/124
