### ISSUE TITLE
Email attachment not working

### ISSUE THREAD

**Issue by DonSS** [nylas/N1#360]
When I select a file for attachment, I see a icon that shows that the attachment is getting uploaded. But it disappears after a while. And I assumed that it is hidden somewhere and went ahead and sent the email. But the receiver doesn't get any attachment. So, the attachment could have failed midway during upload, but there was no way to find that.

**Comment by jenga** [comment]
I have the same issue. I see the upload complete, then it just disappears. I tried to send the message and it warned me that there was no attachment. After several attempts to upload the file (a .tar.gz archive) I gave up.

**Comment by bengotow** [comment]
Hey folks! This was an issue we fixed in `0.3.23`—uploads taking more than 15 seconds were being cancelled by code intended to detect stalled `/send` API requests. Feel free to re-open if you're still seeing the problem!

**Comment by DonSS** [comment]
I just checked the version on my desktop (windows) - its 0.3.19. 
I am unable to find any option to update to latest version, from within the app. I had only downloaded from the website when I logged these issues.
