### ISSUE TITLE
Video tearing on Linux Mint 17.2

### ISSUE THREAD

**Issue by dmark** [nylas/N1#362]
I don't expect this is an N1 specific issue, but logging it here for good measure. As with chromium, I get a lot of video tearing effects with N1 that render the app unusable.

Linux Mint 17.2 Cinnamon edition w/default 3.13.0-37-generic kernel, Broadwell-U integrated graphics using i915 driver on a Dell Latitude E5450.

Screen capture here: https://youtu.be/rzeWd-ESKno

**Comment by mbilker** [comment]
That is weird. You said you normally get tearing artifacts in Chrome/Chromium. Do you have mesa installed along with its libgl driver. What is the result of chrome://gpu in Chromium?

**Comment by dmark** [comment]
Mesa appears to be installed along with libgl. At least, dpkg -s on a few of the related packages shows everything is in order.

I've dumped the output from chrome://gpu into a google doc here:

https://docs.google.com/document/d/1JzKCDgolXAX1z30zTlfnqWt5I48Svg6H3X6PvMasmgk/edit?usp=sharing

Chromium suffers terrible tearing on my system (I don't recall this being an issue prior to Mint 17.x). I've tried a few suggested fixes but I don't use chromium much so it hasn't been a priority. An aside but maybe related due to underlying technology: The Atom editor exhibits the same sort of video tearing effects.

**Comment by mbilker** [comment]
This would have to be an issue with Mesa or the Intel driver. Have you tried to see if the issue exists in other window managers? Are you using a compositing engine (compton, compiz)? What is the configuration for the Intel driver in X11 (/etc/X11/xorg.conf, /etc/X11/xorg.conf.d)?

This is an interesting bug and it appears Mesa is just fine. I forget if you can force vsync.

**Comment by mbilker** [comment]
Another thing. Do you have a ~/.drirc?

**Comment by dmark** [comment]
No, no .drirc file in my homedir.

**Comment by dmark** [comment]
I've fixed, or at least worked around from my perspective, the tearing issues in N1. I had previously added to my /etc/environment:

    CLUTTER_PAINT=disable-clipped-redraws:disable-culling
    CLUTTER_VBLANK=True

This was related to fixing some problems running games from Steam (in particular Half-Life and its relatives). I commented those lines out, restarted my X session and N1 is working fine now.

**Comment by mbilker** [comment]
Wow. Looks like Vsync stuff. I thought it was an issue with some configuration. Thank you for discovering this. I will think of this whenever someone else has this issue.
