### ISSUE TITLE
Spell Check Inconsistencies

### ISSUE THREAD

**Issue by jtflynnz** [nylas/N1#363]
Using 0.3.19-de7d1bb, for some reason correcting part of a word (ie replacing text in a word to fix spelling) seems to mess up the spell check highlighting. It will continue highlighting the word, starting just after the area corrected. This seems to occur most often when the beginning of the word is corrected.

**Comment by mbilker** [comment]
Screenshot possibly?

**Comment by jtflynnz** [comment]
Here:

![screenshot from 2015-11-04 16 09 08](https://cloud.githubusercontent.com/assets/5449443/10952050/cfd84b8e-830e-11e5-9645-b218164e2787.png)

The misspellings that I will attempt to fix are there, except for some reason "sme" didn't highlight until I started fixing other words (even while just fixing and re-misspelling it). Result of that below (screenshot I took previously showing that)..

![screenshot from 2015-11-04 16 08 32](https://cloud.githubusercontent.com/assets/5449443/10952236/c21cfa34-830f-11e5-881c-4571d2493d61.png)

These are the results of fixing now:

![screenshot from 2015-11-04 16 11 17](https://cloud.githubusercontent.com/assets/5449443/10952051/cfd89dbe-830e-11e5-8239-103ee28b9ca4.png)

I noticed that the "sspell" actually read itself as fixed, and that I had "ewell" correct itself the last attempt to type this out (because I tried to change the phrase a few times), but it wasn't until the last attempt that it read as corrected. The other times, by deleting the "e," it would highlight "well" as unfixed/incorrect.

The highlights on "Especially" and "didn't" are the two main examples I have seen though. Especially was corrected by deleting the extra "e", adding an "E" to the beginning, and deleting the "S" to replace with an "s". Once done, the remainder of the word would be highlighted, without the first two letters, and spelling corrections would only highlight that portion and offer related suggestions (i.e. "specifically"). It almost behaves as a second word until deleted and retyped. 

And in the case of "didn't" it shows that the program seems to read the apostrophe as the end of the word (my theory why can't, won't, etc show as correct is that can, won, etc are words; this may just be coincidence).

So mainly seems to be a bug from defining the beginning and end of a word for the spell check.

**Comment by mbilker** [comment]
Hmm. I am pulling the latest Nylas and rebuilding and will see what the results are. I appreciate the quick response.

**Comment by mbilker** [comment]
Out of curiosity, what version of Nylas N1 are you running? It is available under the Help menu.

**Comment by jtflynnz** [comment]
Sounds good, hope that helps! Let me know if you have a question!

> On Nov 4 2015, at 4:33 pm, mbilker &lt;notifications@github.com&gt; wrote:  

>

> Hmm. I am pulling the latest Nylas and rebuilding and will see what the
results are. I appreciate the quick response.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/363#issuecomment-153872648).![](https://github.com/notifications/beac
on/AFMm4-Amp3iXjBirUh-Q-s-yHLXai53Cks5pCnEtgaJpZM4GcBdW.gif)

**Comment by jtflynnz** [comment]
And version 0.3.19-de7d1bb, for Linux on Linux Mint 17.2 Cinnamon

**Comment by mbilker** [comment]
There appear to be changes to the files associated with spellchecking in commit cc61aa78119130603d8a13ffe38a26d36c8f16de. This was implemented after 0.3.19.

In my testing the errors were detected.
![2015-11-04-174253_2560x1024_scrot](https://cloud.githubusercontent.com/assets/1266541/10954508/d2b4d234-831b-11e5-8c0c-9233a623e391.png)

When I right click them I can select the correct spelling and the change is correct, but the red squiggly under the word doesn't disappear. If I type something else the squiggly disappears for any of the changed words. This appears to be a state related bug from this analysis.

**Comment by mbilker** [comment]
I was running 0.3.21-e313521

**Comment by jtflynnz** [comment]
I have updated to 0.3.20.6bbe930, but the apostrophe issue is still present, I haven't checked the other types yet.

![screenshot from 2015-11-07 11 52 04](https://cloud.githubusercontent.com/assets/5449443/11016159/53c1d952-8570-11e5-8c7c-d9606ba661ea.png)

**Comment by grinich** [comment]
I've been able to reproduce this in limited forms. It's on our radar to fix

**Comment by jstejada** [comment]
merging into #1392
