### ISSUE TITLE
Cannot delete image attachments when offline

### ISSUE THREAD

**Issue by dcposch** [nylas/N1#365]
The delete (X) button doesn't work.

**Steps to reproduce:**

* Compose a new email
* Drag an image onto the page. An image attachment appears.
* Mouse over the image. A delete (X) button appears.
* Click the delete button

**Result:**

Clicking has no effect.

This means the only way I can remove an image attachment is to discard the draft and start over.

![image](https://cloud.githubusercontent.com/assets/169280/10960988/b23a7cdc-8381-11e5-9fbf-f3426863d203.png)

N1 @ dc538930a7cb64b04b2793f83b955b284ac55146, Ubuntu 15.04

**Comment by dcposch** [comment]
On further investigation, this only happens when N1 can't reach sync-engine.

Still a bug, though. Say you're on a plane or otherwise don't have internet. N1 works, and you can write draft emails. However, attachments don't work, as described above.

**Comment by grinich** [comment]
@dcposch when you say this happens when "N1 can't reach sync-engine" does that mean when your sync engine is down or returning 500s or what?

**Comment by bengotow** [comment]
Hi @dcposch — this should be fixed in #5e777fe and will be included in the next release.
