### ISSUE TITLE
Dragging an image attachment duplicates it when offline

### ISSUE THREAD

**Issue by dcposch** [nylas/N1#366]
**Steps to reproduce:**
* Disable your internet, or turn off the Sync Engine API if you're running it locally
* Create a new draft
* Drag in an image to create an attachment
* Drag the attachment a bit to one side

![image](https://cloud.githubusercontent.com/assets/169280/10961320/67d84b66-8385-11e5-9cbe-249b17fba8e3.png)

**Result:**
This duplicates the attachment, now you have two.

![image](https://cloud.githubusercontent.com/assets/169280/10961348/a792ffbc-8385-11e5-91c6-12777f03f8ef.png)

It looks like attachment previews in the compose panel are draggabl, and the compose panel is a drop target, so users can accidentally duplicate attachments. We could probably fix this by disabling drag-n-drop on the preview image.

**Comment by grinich** [comment]
Nice bug! We'll look into getting this one fixed.

**Comment by bengotow** [comment]
Hey @dcposch — thanks for filing this. I think the issue is "Drag the attachment a bit to one side". We don't support inline attachments, and drag / drop causes another attachment with the same file path to be added to the draft. I'll get this fixed.
