### ISSUE TITLE
Duplicate Icon In WIndows 10 Taskbar

### ISSUE THREAD

**Issue by MrSassyBritches** [nylas/N1#368]
If i pin the N1 icon then duplicates the icons. I have searched for this issue and cant find anything about it happening with this program. And cant find a solution.
![capture](https://cloud.githubusercontent.com/assets/7945291/10963115/f8c8d828-835a-11e5-87fa-be3d3a12fcc9.PNG)

**Comment by bengotow** [comment]
This is an issue that Atom had as well: https://github.com/atom/atom/issues/7374. Will see if we can apply their solution.
