### ISSUE TITLE
Invite code input is missing from prompt

### ISSUE THREAD

**Issue by pfraze** [nylas/N1#37]
Hey folks.

I cloned the repo about an hour, ran the build script, and ran the app that got installed for me.

Eventually the onboarding takes me to this screen:

![screen shot 2015-10-06 at 12 24 32 pm](https://cloud.githubusercontent.com/assets/1270099/10316633/df90a7f6-6c25-11e5-91e9-bd8022bf7c5f.png)

Looking at `token-auth-page.cjsx` in the onboarding package, it looks like there's supposed to be an input at the bottom, but I don't see one! Do you know what's up?

Thanks

**Comment by bengotow** [comment]
Hey! This is super interesting—that window should definitely be taller. Did you reach this screen by continuing through the initial welcome screens?  We've actually had a few errors come in via Sentry about the window resize call to Electron failing, and haven't been able to narrow it down.

Could you try running in dev mode? (`./N1.sh --dev`) and posting the output that appears in your console? Also, what platform / screen size do you have?

**Comment by pfraze** [comment]
> Did you reach this screen by continuing through the initial welcome screens?

Yes.

>  We've actually had a few errors come in via Sentry about the window resize call to Electron failing, and haven't been able to narrow it down.

Oh fun!

> Could you try running in dev mode? (./N1.sh --dev) and posting the output that appears in your console?

Doesn't look too useful:
```
Streaming log data to /var/folders/qn/b00rwqts1z9chcw17xlcwr600000gn/T/edgehill-83647.log
2015-10-06 15:24:31.178 Electron[83647:7545682] App load time: 2270ms
Error Downloading Update: Could not get code signature for running application
2015-10-06 15:24:31.197 Electron[83647:7545682] Checking for updates...
[83647:1006/152433:INFO:CONSOLE(103)] "Streaming log data to /var/folders/qn/b00rwqts1z9chcw17xlcwr600000gn/T/edgehill-83647.83653.log", source: /Users/paulfrazee/N1/src/error-reporter.js (103)
[83647:1006/152439:INFO:CONSOLE(79)] "Window load time: 8110ms", source: file:///Users/paulfrazee/N1/static/index.js (79)
[83647:1006/152439:INFO:CONSOLE(48)] "Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of WelcomePage. See https://fb.me/react-warning-keys for more information.", source: /Users/paulfrazee/N1/node_modules/react/lib/warning.js (48)
```

> Also, what platform / screen size do you have?

Macbook Air, OSX 10.10.2, Screen is 11.6-inch (1366 x 768).

**Comment by Nijikokun** [comment]
Can confirm. Happening here as well.

**Comment by gonchs** [comment]
Same here, no input field.

**Comment by Falkirks** [comment]
Happening for me as well. I am on a Mac 10.11 Beta with a screen size of 1280 x 800. I tried rendering it on an external display with a size of 1920 x 1080 and I got the same result. Sadly restarting the app doesn't stop it from occurring.

**Comment by sbstnmsch** [comment]
Had the same issue. Just quit it, delete `~/.nylas` and it re-appears on next launch.

**Comment by bengotow** [comment]
Hey folks, sorry for the delay. We're pushing out a fix for this issue but in the meantime, It seems to occur when you reach the invite screen before the app has heard back from our invite server. Try waiting on the welcome screen for a 5-10 seconds before continuing, and see if that resolves the issue.

Sorry - I'll post the fixed download link here when it's available tomorrow.

**Comment by tonyspiro** [comment]
+1

**Comment by tonyspiro** [comment]
thanks @sbstnmsch that worked!

**Comment by joostrijneveld** [comment]
I just downloaded the packaged .app today, and this still occurs. Judging by the comments above, it could be related to the fact that the initial outgoing connection was blocked by Little Snitch when it first tried. After allowing it to connect, deleting `~/.nylas` and restarting, the input field did show up.
