### ISSUE TITLE
Toolbar icons overlap / overflow during selection in split pane mode

### ISSUE THREAD

**Issue by 2nthanh** [nylas/N1#370]
![n1_isssue](https://cloud.githubusercontent.com/assets/15673220/10972321/39aeedb8-840b-11e5-9708-b7c3c434bdaf.png)
that what menu bar looks like when selecting multiple emails with slidebar opened

**Comment by sdewith** [comment]
<img width="726" alt="screen shot 2016-03-14 at 3 10 20 pm" src="https://cloud.githubusercontent.com/assets/13399516/13761605/e40a5904-e9f6-11e5-93a1-e28c2be1a433.png">

It'd be great if we could move the controls like so so we can have more consistency between multi-selected state and regular single thread state.

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
