### ISSUE TITLE
Unable to connect to SMTP Server [Custom Email Domain]

### ISSUE THREAD

**Issue by joelwmale** [nylas/N1#374]
Hi,

Unable to connect to my servers SMTP. I know it's correct as I have a phone, and another mail client that can send mail. I've copied over the settings.

N1 just says "Error connecting to the server"

Is this a bug for emails that aren't hotmail/gmail/etc?

My server requires SSL, and authentication, but didn't see an option to use authentication.

**Comment by lmartins** [comment]
I believe this is duplicated https://github.com/nylas/N1/issues/47

**Comment by bengotow** [comment]
Merging this into #47, the larger conversation about SMTP / IMAP configurations.
