### ISSUE TITLE
Windows not showing check mark in "Run with Debug Flags" menu item

### ISSUE THREAD

**Issue by ghhernandes** [nylas/N1#375]
If Debug mode is active, Developer menu still showing "Run with Debug Flags". 

Do not is better display "Disable Debug Flags" ?

![capturar](https://cloud.githubusercontent.com/assets/7239580/10995885/66e004aa-8467-11e5-93c5-848001fd44d2.PNG)

![sem titulo](https://cloud.githubusercontent.com/assets/7239580/10995915/971c5718-8467-11e5-985c-185cb28ec3f8.png)

**Comment by bengotow** [comment]
Hi @ghhernandes — this looks like a Windows-specific issue. On other platforms, there's a check mark shown beside the menu item. I'll see if we can get that fixed!

**Comment by mbilker** [comment]
On Linux, it displayed `Run with Debug Flags` even if you were running in debug mode already. Will test against latest HEAD.
