### ISSUE TITLE
Can't see images wider than 760px

### ISSUE THREAD

**Issue by jsvini** [nylas/N1#376]
I can't find a way to see images wider than 760px
The only option is to save the image and open it with an external app.

**Comment by g105b** [comment]
:+1: Please provide Trello link so I can upvote

**Comment by grinich** [comment]
@jsvini @g105b you can't scroll the app horizontally?

**Comment by grinich** [comment]
Can you provide a screenshot?

**Comment by jsvini** [comment]
Nylas:
![image](https://cloud.githubusercontent.com/assets/4185886/12196939/4cd4fe34-b5e1-11e5-90c0-100f406769eb.png)

Gmail:
![image](https://cloud.githubusercontent.com/assets/4185886/12196960/83f348d0-b5e1-11e5-8ae4-7ba83ae91264.png)

And if you screen is small you can click to expand the image:
![image](https://cloud.githubusercontent.com/assets/4185886/12196983/b2524a5a-b5e1-11e5-9fd0-23268051f99b.png)

**Comment by bashok001** [comment]
@grinich Do you think this is the same issue I am having.
![screenshot from 2016-02-26 11-14-26](https://cloud.githubusercontent.com/assets/2344626/13357910/afa15318-dc7a-11e5-878f-c3966e0e6afc.png)

**Comment by elegos** [comment]
Plus one for this one. I was thinking about creating a plugin to create a 'zoom-in' feature, but I don't have the time right now to learn React unfortunately =\

**Comment by jackiehluo** [comment]
Closing this issue for now since it should be fixed—let us know if it's not!
