### ISSUE TITLE
Feature Request: Select text and click reply to quote a snippet

### ISSUE THREAD

**Issue by artagnon** [nylas/N1#377]
Often, I select the part that I'm replying to and hit Reply in Gmail; the quote then comes up, and I can type my reply below it. This feature is missing in N1.

**Comment by grinich** [comment]
I think what we're going to instead do here is allow you to easily format text to be a blockquote in the composer. The UX of highlight -> click reply to quote a section is not discoverable or explicit. Gmail actually [disabled this within two months of launching it](http://thenextweb.com/google/2013/01/25/google-retracts-gmails-new-quote-selected-text-feature-and-puts-it-back-into-labs-after-50-days/) to everyone.

I totally understand the need to have the ability to reply to specific sections within a message. We'll get there! :smile:

**Comment by nickyhajal** [comment]
Any updates on this? Seems like a really valuable feature!
