### ISSUE TITLE
Feature request: Inline replies

### ISSUE THREAD

**Issue by artagnon** [nylas/N1#378]
When trying to write text below the quoted text, I hit RET on the last line of the quoted text, and I'm only given the option to extend the quote, not type my own response (the left-margin line follows me wherever I go). This is crippling.

**Comment by bengotow** [comment]
Hi @artagnon — unfortunately this is a known issue. N1 does not yet support inline responses (where you mix your response into quoted text.) I've added this to our open source backlog–feel free to track it here or upvote if you have a Trello account: https://trello.com/c/TvjRaV7W/49-inline-replies-mix-reply-into-quoted-text

**Comment by cdysthe** [comment]
Not having an functioning inline response option is a show stopper for me when it comes be using N1 for work. It needs to be put very high on the feature request list!

**Comment by jstejada** [comment]
this was fixed with https://github.com/nylas/N1/commit/1de3a4707739adfbcac2df04de74b92f82a4a135 and will be available in the next release!

**Comment by eerohele** [comment]
>this was fixed with 1de3a47 and will be available in the next release!

That's fantastic — thank you!

**Comment by jackdesert** [comment]
Fix is not working for me.

Commit 1de3a47 says "You can now break up blockquotes (as in quoted text areas) by pressing
'delete' at the start of a line. This allows you to reply inline."

However, it's not working for me in version 0.4.40 on Ubuntu.

**Comment by treyhunner** [comment]
I'm having the same problem as @jackdesert. I cannot reply inline in Nylas N1 on Ubuntu. This is a pretty nasty bug for me because I need to reply inline to many of the email threads I have.
