### ISSUE TITLE
Not Generating/Finding Trash Folder for Hover.com Email

### ISSUE THREAD

**Issue by Glark** [nylas/N1#380]
Have Gmail account and that is ok.

Just imported a hover.com email account and N1 is not showing a trash button or folder for that account. I tried the same account in mail.app and it's fine there.

**Comment by bengotow** [comment]
Hi @Glark — can you send me labels that you see in the left sidebar? It sounds like we're not correctly identifying that your account has a trash folder.

**Comment by Glark** [comment]
![nylas_and_untitled](https://cloud.githubusercontent.com/assets/1977886/11010443/f1416a9c-8482-11e5-914f-5c65c969b71c.png)

**Comment by khamidou** [comment]
Hey @Glark, I'm curious --- would you happen to also have a "Sent Messages" folder?

**Comment by Glark** [comment]
No, that's everything in the screenshot.

**Comment by screendriver** [comment]
Same here. I can see trash folder, but it's empty (in Thunderbird I can see thousands of mails in it). If I move a message to the trash I can see it in N1 but not in Thunderbird.

It seems that the trash folder in N1 is **not** my IMAP trash folder.

**Comment by screendriver** [comment]
As far as I can see it also affects my `sent` folder. I can't see any of my sent mails.

**Comment by spang** [comment]
This is an odd issue indeed. @screendriver / @Glark are you able to email support@nylas.com with the affected account? We need to take a closer look to see what might be going on here.

**Comment by screendriver** [comment]
Email is on the way

**Comment by Glark** [comment]
Sorry, that email contains customer information email so I can't help you on access on this one. :\

**Comment by bengotow** [comment]
Merging this into https://github.com/nylas/N1/issues/872
