### ISSUE TITLE
How to mark email as unread and how to mark multiple emails as read?

### ISSUE THREAD

**Issue by hansaliyad1** [nylas/N1#381]
I was just trying to figure out a way to unread the read emails and mark multiple emails as read.

**Comment by uruloke** [comment]
http://i.imgur.com/lb6TO6q.png
The Icon with the envolope is mark as unread.

**Comment by hansaliyad1** [comment]
I tried that one but it makes my email marked as read when I switch to next email.

**Comment by uruloke** [comment]
Okay so I just tested it a little, the envolope does not change to mark as unread, it changes it to unread if its unread and read if it's read. If you mark multiple mails where some of them are read and others aren't  it changes them all to read.

**Comment by bengotow** [comment]
Hi folks,

Here's how you can mark multiple emails as read / unread—if the messages are mixed read/unread, clicking it once marks them all as read, and clicking it again marks them all as unread: http://www.gfycat.com/BarrenHardFoal

Hope that helps—let me know if it's not working for you.

**Comment by mbilker** [comment]
@bengotow should there be more of these kind of gifs to make a tutorial?
