### ISSUE TITLE
Dark theme minor issue

### ISSUE THREAD

**Issue by chevdor** [nylas/N1#382]
Context menu button to switch between accounts is barely visible

![4ac67db2-846c-11e5-810f-9c1a0359a82a](https://cloud.githubusercontent.com/assets/738724/11022141/b1076b1c-8657-11e5-875d-ea3ba0816a29.png)

**Comment by mbilker** [comment]
There are many issues like this one with the dark theme (#299, #148).

**Comment by mbilker** [comment]
Thank you!
