### ISSUE TITLE
Disable splash screen

### ISSUE THREAD

**Issue by zsszatmari** [nylas/N1#383]
Make it possible to disable splash screen, or even better, make it disabled by default.
While it is beautifully designed in itself, sadly, it is the easiest way to annoy a user. I start the app and would like to go on with my other duties, but I just can't because it blocks the screen!

**Comment by bengotow** [comment]
Hey @zsszatmari — thanks for downloading N1! Unfortunately the delay you see when opening the app is necessary—it's executing JavaScript the entire time that splash screen is open, and we can't even put an animated gif in there because it never has a chance to repaint.

I'll see if we can make something a little less disruptive in a future update—even though the time-to-inbox can't be fixed easily, we could make it less intrusive.

**Comment by zsszatmari** [comment]
For me, the delay itself is a non-issue. It starts faster on my machine than many other apps, including Apple Mail! My only woe is the splash screen itself :)

**Comment by jstejada** [comment]
hi @zsszatmari , by splash screen, you mean the one that says "Loading N1..."?

**Comment by zsszatmari** [comment]
Yes :)

**Comment by artailicous** [comment]
Oh the delay itself is an issue dear @zsszatmari ! What is your N1 loading time?

**Comment by zsszatmari** [comment]
Ok, I measured, it's some 23s. It's really long. But I haven't noticed it! That's because I don't really care, I just start the app and leave it there all day, so some 23s does not really matter, especially because while it's starting up I have many other things to do.
But the splash screen is distracting me.

**Comment by mbilker** [comment]
With the recently implemented `compile-cache`, this should no longer be an issue. Though, N1 now depends more on disk IO to check if the cached compile exists.

**Comment by courajs** [comment]
It sounds like @zsszatmari is complaining about a floating splash screen that blocks him from doing other activities? I don't know if that used to be the case, but for me on OSX I am able to click on another window, or cmd+tab to another app just fine.
I would also be annoyed if it was a persistent splash screen that stayed on top. Is that what was happening for you @zsszatmari?

**Comment by zsszatmari** [comment]
courejs: I was able to click away, but it was still annoying at the time.
It does not matter anymore since startup is much faster now, so this is a non-issue :)

**Comment by courajs** [comment]
Nice to hear! We can probably close the issue then?

**Comment by zsszatmari** [comment]
Yes, sure 👍
