### ISSUE TITLE
Question mark icon hides discard button when in fullscreen

### ISSUE THREAD

**Issue by g105b** [nylas/N1#385]
When replying in full screen (maximised), the question mark icon hides the discard reply button.

![image](https://cloud.githubusercontent.com/assets/358014/11066677/10634b98-87c1-11e5-8c37-cd225684547c.png)

**Comment by bengotow** [comment]
Hey folks! We've made this icon about 20% smaller and moved it closer to the corner. We'll be phasing this out over the next six months or so, so I'm going to go ahead and close this. Enjoy!

**Comment by eapearson** [comment]
Is there some reason that annoying, floating, bright, google-esque question mark icon can't just be ditched now? Once you notice it, it is almost impossible to stop staring at it!
