### ISSUE TITLE
Ctrl+F for searching text in emails

### ISSUE THREAD

**Issue by g105b** [nylas/N1#386]
Would love to be able to find some text.

Bonus points for regex searching.

**Comment by evanemolo** [comment]
+1 this would be a great feature. I currently have to copy and paste into my text editor to search

**Comment by luangch** [comment]
+1

**Comment by phoenixeliot** [comment]
+1. Preferably will search accordion-hidden "older messages" in a thread as well and expand the ones with the found text.

**Comment by jorosmtz** [comment]
+1 excellent

**Comment by jweinstein** [comment]
+1

**Comment by jackiehluo** [comment]
Shipped in the latest update!
