### ISSUE TITLE
Closing nested labels does not persist

### ISSUE THREAD

**Issue by g105b** [nylas/N1#387]
When I change my many open labels from this:

![image](https://cloud.githubusercontent.com/assets/358014/11066828/b0169262-87c1-11e5-8efa-2aa67572004c.png)

to this:

![image](https://cloud.githubusercontent.com/assets/358014/11066839/bc17338c-87c1-11e5-8b7c-c383cf5020f7.png)

they keep jumping open again on every interaction with the UI.

**Comment by bengotow** [comment]
Whoa—thanks for filing this. The collapsed state isn't yet persisted to your N1 settings, but this will be fixed in an upcoming update. Stay tuned—

**Comment by g105b** [comment]
Great thanks for letting me know. Keep up the good work, really impressed so far (after the initial launch hiccup)

**Comment by jstejada** [comment]
hey @g105b, we've fixed this and it will be available on the next release.

**Comment by g105b** [comment]
That's great to hear. :+1:
