### ISSUE TITLE
Select multiple messages using ctrl / cmd key

### ISSUE THREAD

**Issue by g105b** [nylas/N1#388]
Shift key works as expected in OS; click one mail in the list, shift-click another, and all mails in between are also selected.

Control/Command key should toggle selection of individual messages per click.

**Comment by bengotow** [comment]
This issue appears to be platform-specific. On the Mac, cmd-clicking threads selects them individually. It seems we forgot to make this work on Windows / Linux. I'm not sure what the desired behavior is on Windows—in Windows Explorer, it looks like you have to `ctrl-option-click` to extend your selection. @g105b do you have any thoughts what the correct behavior should be?

**Comment by g105b** [comment]
My platform is Ubuntu Linux, I haven't tested on Windows.

The expected behaviour is to toggle the selected status of each clicked element while Ctrl is held, with no context to other selected elements.

**Comment by nomadturk** [comment]
Can't use ctrl key on Windows either. Shift key works but when I need to add another mail from X rows below to the selection, it doesn't work.

**Comment by haidaraM** [comment]
Same for me on Ubuntu. I can't use ctrl key to select multiple threads. Shift key works perfectly

**Comment by jwoodard80** [comment]
I would like to also confirm this issue.... Ctrl behavior does not work as expected, shift key works as expected.

Linux Mint 17.3 64bit Cinnamon

**Comment by bengotow** [comment]
I'm tagging this as a good starter issue. Technically, we already support the behavior being described here. For some reason, the logic in this function is not working as you'd expect on Linux: https://github.com/nylas/N1/blob/unified-inbox/src/components/multiselect-list.cjsx#L140.

It looks like `event.metaKey` might not be the correct think to check for on Linux?

**Comment by g105b** [comment]
I can confirm that in Linux, multiple emails can be selected using the **super key**, instead of the ctrl key, as expected.

Might have a look at fixing this one myself later.

**Comment by g105b** [comment]
The event has a `ctrlKey` property, I think this should be standard on all platforms but in case I put it after the or operator as to not affect existing behaviour.
