### ISSUE TITLE
apm conflicts with Atom

### ISSUE THREAD

**Issue by neurobashing** [nylas/N1#39]
running N1 rewrites my /usr/local/bin/apm (as part of Atom) to the N1 app bundle.

**Comment by dillonforrest** [comment]
Hey there @neurobashing! Thanks for downloading N1 and sharing this issue.

Can you give us more info?

**Comment by neurobashing** [comment]
Default state: I'm using Atom
```
   λ ~ : ls -l /usr/local/bin/apm
lrwxrwxr-x  1 greggt  admin  71 Oct  6 14:33 /usr/local/bin/apm@ -> /Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm
```
Hey, let's try this N1 app out. OK, cool! But back to editing. I wonder if I need to upgrade any packages? *runs apm*
```
   λ ~ : apm
zsh: command not found: apm
```
wat?
```
   λ ~ : ls -l /usr/local/bin/apm
lrwxrwxr-x  1 greggt  admin  77 Oct  7 09:59 /usr/local/bin/apm@ -> /Applications/Nylas.app/Contents/Resources/app.asar/apm/node_modules/.bin/apm
```
Huh.

**Comment by neurobashing** [comment]
This is still occurring in the latest version.

**Comment by zclancy** [comment]
Just noticed this as well.

**Comment by grinich** [comment]
Are you building from source, or using the compiled version?

**Comment by zclancy** [comment]
I'm using the downloaded version.

**Comment by neurobashing** [comment]
Same.

**Comment by danielbayley** [comment]
Argh! Me too :-1:
```
readlink /usr/local/bin/apm
/Applications/Nylas N1.app/Contents/Resources/app.asar/apm/node_modules/.bin/apm
```
I installed via Homebrew Cask…

Temporary fix…
```
ln -sf /Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm /usr/local/bin/apm
```
