### ISSUE TITLE
Long delay between reading a message and the count of unread messages updating

### ISSUE THREAD

**Issue by louim** [nylas/N1#390]
There seems to be a long delay (around 10 seconds) between the time I click on an unread email, and the time the badge on `Inbox` updates.

The opposite is also true. Select an email, mark it as unread, it will take around 10 seconds for the sidebar to update and display the unread messages badge.

**Comment by uncleserb** [comment]
+1

**Comment by bengotow** [comment]
Hey @louim — this should be fixed now in 0.3.25+. Enjoy!
