### ISSUE TITLE
Feature request: Display raw message source.

### ISSUE THREAD

**Issue by louim** [nylas/N1#391]
This would be really handy for inspecting messages. Apple Mail (and other clients I believe) have this feature.

**Comment by kmila** [comment]
:+1:

**Comment by bengotow** [comment]
Hey folks—I totally agree. I actually use this feature in Apple Mail a lot (as we develop N1).  I'll see if we can make this an official feature soon. In the meantime, there's a secret way to do this: Click in the blank space to the left of the "Reply / Reply All" dropdown on a message. You'll see this popup menu: 

![image](https://cloud.githubusercontent.com/assets/1037212/11154694/d1bd23d2-89f5-11e5-80e8-7a024821d264.png)

`Show Original` shows the raw message source.

`Log Data` prints the N1 `Message` object to the console so you can access the object that is backing that React component.
