### ISSUE TITLE
Save / copy / download inline image

### ISSUE THREAD

**Issue by g105b** [nylas/N1#392]
When an email contains an inline image, there is no way to download the image, or even copy to the clipboard.

Right clicking the image doesn't show a context menu at all, and dragging the image out of N1 doesn't take the image data.

**Comment by g105b** [comment]
After further investigation, double-clicking the image opens the image in the system default image editor, so I would class this as a usability improvement rather than any high priority feature.

**Comment by bengotow** [comment]
Hey @g105b — thanks for filing this. What platform are you running N1 on? You should be able to click the image and see these options—this might be an issue specific to a particular kind of HTML markup, or a specific platform. Thanks!

![image](https://cloud.githubusercontent.com/assets/1037212/11154810/7c23fca6-89f6-11e5-9939-cfa5ab5d87dc.png)

**Comment by g105b** [comment]
Hi, I'm running on Ubuntu Linux, there is no context menu at all on right click.

**Comment by grinich** [comment]
I'm going to close this as stale. Please re-open if this issue is still occurring in the latest release.

**Comment by orschiro** [comment]
Dear @grinich,

Please re-open this issue. 

I can confirm that the latest N1 on Ubuntu 16.04 does not show a context menu on right mouse click on an attached image. 

Warmly,

~Robert

**Comment by g105b** [comment]
To confirm, tested today on Ubuntu 16.04:

* Inline images do have a right click context menu now.
* Attached images do not.

**Comment by orschiro** [comment]
> Attached images do not.

By my above comment I was actually refering to these images only.

Thanks for your clarification @g105b!

~Robert
