### ISSUE TITLE
First name cut off bug

### ISSUE THREAD

**Issue by mfid** [nylas/N1#393]
A little strange. The first name cut off for one of my contacts called Olivia results in her being called 'Oli'.

I haven't observed this with anyone else. I've attached both collapsed and expanded views (it's fine when expanded). I've cut the image off prematurely, but the expanded view does have both first and last names in full, as it should. Issue is with the collapsed view only, and also happens in the list of messages as well.

<img width="85" alt="screenshot at nov 11 17-37-47" src="https://cloud.githubusercontent.com/assets/7438143/11098162/0a3394be-889b-11e5-97c5-3ac176ba6349.png">

<img width="153" alt="screenshot at nov 11 17-37-05" src="https://cloud.githubusercontent.com/assets/7438143/11098163/0a33d0be-889b-11e5-8d8b-e253d6bf3e20.png">

<img width="283" alt="screenshot at nov 11 17-40-49" src="https://cloud.githubusercontent.com/assets/7438143/11098218/6289b602-889b-11e5-9949-ab8359e50cce.png">

**Comment by bengotow** [comment]
Hey @mfid — thanks for filing this. I can't believe it, but I'm able to reproduce this in my mail, and it seems to only happen with the name Olivia. Will keep you posted.

**Comment by bengotow** [comment]
So... this is my favorite bug of the week. The name "Olivia" was being caught in our parser designed to shorten phrases like "Ben Gotow via LinkedIn" to "Ben Gotow". We weren't checking that "via" was actually a distinct word. I've added three additional test cases to the suite for this logic and it will be fixed in the next release. Enjoy!

**Comment by mfid** [comment]
Awesome



On Fri, Nov 13, 2015 at 11:44 AM -0800, "Ben Gotow" <notifications@github.com> wrote:












So... this is my favorite bug of the week. The name "Olivia" was being caught in our parser designed to shorten phrases like "Ben Gotow via LinkedIn" to "Ben Gotow". We weren't checking that "via" was actually a distinct word. I've added three additional test cases to the suite for this logic and it will be fixed in the next release. Enjoy!

**Comment by thephilipjones** [comment]
Ohh, so this is why "Trivia Scheduler" was showing up as "Tri". I assumed it was the sender's error. Confirmed fixed in the latest build. Thanks!
