### ISSUE TITLE
Feature request: export messages

### ISSUE THREAD

**Issue by kmila** [nylas/N1#394]
Looking forward to a way to move the messages to a local archive, or an option to download or export the messages in any format (txt, html, eml).

**Comment by bengotow** [comment]
Hi @kmila — can you expand on what you mean by "local archive"? What archive format would be helpful? Is there an example of software you currently use to generate this archive?

If you want, you can use `~/.nylas/edgehill.db`, which is a SQLite database of your mailbox. The `Thread`, `Message`, `Contact` and `Label` tables are populated aggressively and are a complete copy of your mailbox. The `MessageBody` table is lazily fetched as you view messages.

**Comment by grinich** [comment]
Hi @kmila -- this is something that would be better built on top of the Nylas platform APIs rather than N1, since N1 doesn't deal with raw messages at all. 

More info here: https://nylas.com/docs/platform
