### ISSUE TITLE
Encoded newline ("%0D%0A") in mailto links not working correctly

### ISSUE THREAD

**Issue by moollaza** [nylas/N1#397]
I have Nylas set to my default client, and while testing a mailto link: 

e.g [multi-line mailto](mailto:infobot@example.com?body=send%20current-issue%0D%0Asend%20index) I noticed that the content after the encoded newline, `%0D%0A`, is missing in the body of the email.

When I switched my default to the Apple Mail app, the link worked as expected.

It seems that according to http://stackoverflow.com/questions/10356329/mailto-link-multiple-body-lines#10356432 the `%0D%0A` sequence is part of the 'mailto' URI scheme, so I image Nylas should be able to handle this correctly.

> More info: https://tools.ietf.org/html/rfc6068#section-6.1

**Comment by bengotow** [comment]
Good catch @moollaza — looks like our specs didn't have any mailto links with newlines. I've updated our specs and parsing code, so this will be fixed in the next release. Cheers!

**Comment by moollaza** [comment]
Glad to have helped :+1:
