### ISSUE TITLE
Running locally without invitation code

### ISSUE THREAD

**Issue by Fryie** [nylas/N1#398]
It seems that currently it's not possible to do so. [This method](https://github.com/nylas/N1/blob/master/internal_packages/onboarding/lib/token-auth-api.coffee#L11) only includes an endpoint for "development" (not "local") and it goes to another port than the 5555. Is there a way to get this running without an invitation currently?

**Comment by bengotow** [comment]
Yep, there are quite a few people running locally without an invitation code. If you follow the steps here (https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine), the last step is to populate your `config.cson` file. When the app sees that you have populated config.cson with valid accounts, it'll skip the invitation flow entirely and take you straight to the app. The add/remove/edit accounts interface in the app only works against our API and invite system, but putting accounts in confing.cson allows you to bypass it. Hope that helps! Feel free to re-open if you have any questions.

**Comment by Fryie** [comment]
Okay, then my config.cson must be somehow wrong. I'll comment in #185.
