### ISSUE TITLE
Pane widths change when moving between views

### ISSUE THREAD

**Issue by mfid** [nylas/N1#399]
When moving e.g. from Inbox to Drafts folder, or to Plugins section, and then back to Inbox, the panes revert to default width, changing the way messages are presented. Image attached because it's easier than trying to explain with words.

<img width="736" alt="screenshot at nov 12 17-29-00" src="https://cloud.githubusercontent.com/assets/7438143/11125622/e8ebd8e8-8962-11e5-84ba-61b050bb7b49.png">

**Comment by bengotow** [comment]
Merging in #97, #243

**Comment by natemhanson** [comment]
+1

**Comment by iamhenry** [comment]
+1 

Very annoying.

**Comment by hirozed** [comment]
+1 It would be great if N1 could remember the pane width even after the app is closed.  I have to change the width every time I launch the program.

**Comment by jstejada** [comment]
merging into #833
