### ISSUE TITLE
Compile instructions in the repo

### ISSUE THREAD

**Issue by crutchcorn** [nylas/N1#40]
Because many of us have no clue how to build this.

**Comment by kevinold** [comment]
I'll submit a patch for docs but you should be able to clone the repo then run this script: https://github.com/nylas/N1/blob/master/script/bootstrap

**Comment by crutchcorn** [comment]
Thank you so much for your ifo!

**Comment by bengotow** [comment]
Hi @crutchcorn — you should find what you're looking for in https://github.com/nylas/N1/blob/master/CONTRIBUTING.md. I'll see if we can make the link to that from the README more clear!
