### ISSUE TITLE
Label uppercasing is disturbing

### ISSUE THREAD

**Issue by Seldaek** [nylas/N1#401]
I have a bunch of labels that are fully lowercased like `ml.foo.bar` and they display as `Ml.Foo.Bar` which tripped me up a bit. I don't quite understand why this is a feature, I'd imagine people can uppercase labels themselves if they want to see them uppercased. Seems like over-stepping a bit.

I hope this can be reconsidered.

**Comment by bengotow** [comment]
Hey @Seldaek — I think you're correct. We've had a couple of other folks note issues with labels like MacBeth => Macbeth. It's actually just a css `text-transform` I believe. Will fix.
