### ISSUE TITLE
Scroll accounts section of preferences window

### ISSUE THREAD

**Issue by clemsos** [nylas/N1#402]
I have added 6 mail accounts and can not add any more accounts, because the "Add Account" button is hidden by the overflow of the setting box.
 
![selection_025](https://cloud.githubusercontent.com/assets/743246/11140327/99a388ae-89d9-11e5-8be2-3cc76df22f84.png)

^^^
Here should be a "Add Account" button. I can not scroll down to reach for it

( I am on Debian)

**Comment by grinich** [comment]
Working on it! We didn't design this to have so many accounts connected, but I'm I'm glad you're pushing us to! :smile:

**Comment by bengotow** [comment]
This is no longer an issue—we've changed the design of the preferences. Enjoy!
