### ISSUE TITLE
Request times out while connecting to exchange account

### ISSUE THREAD

**Issue by antonyr** [nylas/N1#405]
I am using N1 on Mac with version 0.3.20.-6bbe930

I am trying to connect to server "west.exch081.serverdata.net"

It gives out an error like Request timed out. Please try again.

**Comment by grinich** [comment]
Do you know where this server is located? Is this a Microsoft Exchange Server? It may be failing due to AutoDiscovery bugs.

**Comment by antonyr** [comment]
@grinich 
This is the server I am trying to connect to
https://west.EXCH081.serverdata.net/EWS/Exchange.asmx

**Comment by rushlife** [comment]
I have also this problem.
I cannot connect to my exchange 2010 server. I am in local subnet, I can ping my exchange server, my Evolution mail running OK (due to evolution-ews), Outlook in Windows also running without problem. I am using two mailboxes but i cannot connect to anything. I have also enable activesync and OWA.

Nylas N1 stop on error:
Error connecting to the server.

I also try couple of formats "username" , ip address instead of name and I have already tested this for couple of mailboxes.

Thx folks

**Comment by rushlife** [comment]
up
no any update ?

**Comment by protactinium** [comment]
Hey all,

This issue is blocking us from testing N1 at an entreprise level. Will be great to provide a troubleshooting. 

Melek

**Comment by callmepeanut** [comment]
Same problem as @rushlife. Request time out. But Evolution works well.

**Comment by rushlife** [comment]
Ok, but how i can test N1 without any my account ?
How I can use it? I need N1 for exchange, I have no any other interest on other accounts.

**Comment by rushlife** [comment]
with new version is the same state, no any fix

**Comment by wamicho** [comment]
Hey All 
Do we have a solution for this already ?
I just tried and still getting the same error.

**Comment by antonyr** [comment]
No, Unfortunately. It seems nobody is working on it.

**Comment by mbilker** [comment]
If the Exchange server is not accessible from the public Internet, then the hosted Nylas Sync Engine will not be able to access it. Hence the error message.

N1 does not connect to the mail server. N1 uses a separate service to connect and retrieve mail.

**Comment by antonyr** [comment]
@mbilker I can confirm this service is accessible from public internet.
https://west.EXCH081.serverdata.net/EWS/Exchange.asmx

Please let me know if you have further clarifications

**Comment by antonyr** [comment]
This has actually been resolved in the current version of the N1.
Version 0.4.5-b0ec335 (0.4.5-b0ec335)

**Comment by antonyr** [comment]
Guys please reopen it if this issue persists for you.

**Comment by dimme** [comment]
Issue persists.
