### ISSUE TITLE
Indicator/applet

### ISSUE THREAD

**Issue by sadalavoaoj** [nylas/N1#407]
Hi there,

First, let me say to you that this is the most beautifull email client that i used. Nothing is so simple like this one. 
I love it, and you can make  some nice changes like make some blur effects, and make it the faster and powerfull too.

Im using linux mint cinnamon 17.2 and my question is:
Will be a a indicator like in tunderbird email client on linux? if he could run on background would be nice but if that is impossible at least to open when asked on a indicator.. 

I´m not sure if i was clear in my question but i attach an example of what im asking for, to make this very nice email client more powerfull too.
![captura de ecra de 2015-11-15 00 05 00](https://cloud.githubusercontent.com/assets/14188908/11166486/cc9710e2-8b2c-11e5-8c8a-3575f6043d72.png)

**Comment by mbilker** [comment]
I know N1 has an icon in the status bar in the newer commits. Are you also referring to alerts when you get an email?

![2015-11-16-212911_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11201118/429e5188-8ca9-11e5-96bc-d5c7ef0527b9.png)

**Comment by davidgasquez** [comment]
I'm currently using the version `0.3.20` and it does not have an icon in the status bar under *Cinnamon*.

**Comment by mbilker** [comment]
Ok. Version `0.3.23` was just released.

**Comment by davidgasquez** [comment]
Is the `.deb` package updated?

**Comment by mbilker** [comment]
Yes it is. https://edgehill.nylas.com/download?platform=linux points to http://edgehill.s3-us-west-2.amazonaws.com/0.3.23-94e0cb9/linux/x64/N1.deb

**Comment by davidgasquez** [comment]
Thanks! I'll report after I check it out later today!

**Comment by davidgasquez** [comment]
The status bar icon is properly working under version `0.3.23`!
 :+1:

**Comment by sadalavoaoj** [comment]
Hi there, 

I got a problem now that i updated. Please check the image. 

Many thanks

![captura de ecra de 2015-11-29 00 48 41](https://cloud.githubusercontent.com/assets/14188908/11454787/0c5fa1f6-9633-11e5-8e5f-52f32aaeee0e.png)

**Comment by mbilker** [comment]
Hmm. You appear to be running `0.3.24`. It still appears the download link has not been fixed yet.

**Comment by mbilker** [comment]
Referencing #482

**Comment by mbilker** [comment]
@sadalavoaoj have you built N1 from source before?

**Comment by sadalavoaoj** [comment]
@mbilker  now i started from the scratch (Uninstaled).

Update: reboot solved the problem. 

Thanks again, and great great work. With the indicator included is one of my favorite email client by the simplicity and design.

**Comment by mbilker** [comment]
@sadalavoaoj Ok. Never mind then. I tried downloading N1 (.deb file) from their website and I still see its pointing to `0.3.24`.

**Comment by sadalavoaoj** [comment]
I installed 3.23

Tip: I think is slower loading now but im not sure.
Other thing that would be useful is to run the app on background, so you do not have to see the icon in plank to see only indicator on bar, like spotify.

**Comment by mbilker** [comment]
Ok. If you want, you can build from source to get `0.3.25`. If you are running Ubuntu (or a Debian-based OS), the building process should be like:
```
# Install dependencies
sudo apt-get install build-essential nodejs libgnome-keyring-dev git

# Clone N1 from Github
git clone https://github.com/nylas/N1

cd N1
script/build
script/grunt mkdeb
```

**Comment by sadalavoaoj** [comment]
Thanks, where can i see the updates/corrections on 3.25?

**Comment by mbilker** [comment]
@sadalavoaoj https://github.com/nylas/N1/blob/master/CHANGELOG.md

**Comment by mbilker** [comment]
Notice under Fixes: `NYLAS_HOME is defined in the renderer process on Linux (@mbilker)`

**Comment by sadalavoaoj** [comment]
Many thanks for the quick answers, will read the log and check if i should update.

**Comment by mbilker** [comment]
The biggest change is the compile-cache pulled from Atom. It reduced my start times in Dev Mode from 30s to 5s.

**Comment by sadalavoaoj** [comment]
That is a huge diference, will try it now.
