### ISSUE TITLE
Support Mac OS 10.7

### ISSUE THREAD

**Issue by grinich** [nylas/N1#410]

**Comment by mbilker** [comment]
Milestone for next version?

**Comment by jdsimcoe** [comment]
:-1: 

Sorry, @grinich nobody uses 10.7 anymore. Upgrade is free.

**Comment by mbilker** [comment]
@jdsimcoe You do realize he is the owner of the project.

**Comment by jdsimcoe** [comment]
My apologies @grinich @mbilker.

**Comment by mbilker** [comment]
No need to apologize to me. I think this app should strive for backwards compatibility. 10.6 is too old, but is the last OS to run on my mom's MacBook Pro from 2009.

**Comment by grinich** [comment]
Someone requested this via sending us a direct message. They said due to hardware constraints they can't upgrade.

**Comment by mbilker** [comment]
Ahh. Makes more sense.

**Comment by bengotow** [comment]
It's very unlikely that N1 / Electron will ever support Mac OS X 10.7 — the Atom team decided not to support it (https://github.com/atom/atom/issues/1967) in 2014 and it'd be pretty difficult to get a copy of Xcode that will build against the Mac OS X 10.7 SDK.
