### ISSUE TITLE
Cannot locate electron from /usr/bin/nylas. /usr/share/nylas/nylas works fine

### ISSUE THREAD

**Issue by jeffeb3** [nylas/N1#411]
Installed using the provided deb lubuntu 14.04:

sudo dpkg -i N1.deb

    >which nylas
    /usr/bin/nylas

    >nylas
    Cannot locate electron. Be sure you have run script/bootstrap first from /usr/bin
    *sidenote* not a super helpful message...

    >/usr/share/nylas/nylas
    # runs seemingly normally.

I think you probably meant to have /usr/bin/nylas be a soft link to /usr/share/nylas/nylas (seems nicer to my bin dir, to say the least). Because it's being ran from /usr/bin, it's not seeing the things it sees in /usr/share/nylas. Just a guess.

**Comment by mbilker** [comment]
This is because `/usr/bin/nylas` is the `N1.sh` script found in the base directory of the project (https://github.com/nylas/N1/blob/master/N1.sh). This script thinks the N1 project directory is `/usr/bin`, but since it cannot open Electron from `/usr/bin` it spits out the error (https://github.com/nylas/N1/blob/master/N1.sh#L63). Line 63 shows the error and `ELECTRON_PATH` is equal to `$N1_PATH/electron` and `N1_PATH=/usr/bin` because of `BASH_SOURCE`.

**Comment by mbilker** [comment]
I do believe /usr/bin/nylas should behave more like Atom's `atom.sh` script at `/usr/bin/atom` where it checks if there is an installed version and a built version in `/tmp` (different on other OS's).

**Comment by jeffeb3** [comment]
The atom script does seem to do the trick, because it knows where the actual atom, and electron are located. You could make your script smart enough to know that. But couldn't you just put the script in the location of the install, and then make the /usr/bin a link to that script? The script would always be in the install directory, so it would know where to find everything. It seems like that would be more flexible, because you would only need to generate a symlink when doing the install, and at that point, you would know best where it was. Seems like it would easily extend to user space installs, or different os installs (like suse, some stuff is in /opt).

**Comment by mbilker** [comment]
```
 ~  file /usr/bin/atom
/usr/bin/atom: Bourne-Again shell script, ASCII text executable
 ~  head /usr/bin/atom
#!/bin/bash

if [ "$(uname)" == 'Darwin' ]; then
  OS='Mac'
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  OS='Linux'
elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]; then
  OS='Cygwin'
else
  echo "Your platform ($(uname -a)) is not supported."
 ~  ls -l /usr/bin/atom
-rwxr-xr-x. 1 root root 3024 Nov  2 21:52 /usr/bin/atom
 ~ 
```

Notice how its not a symlink. I think this would be the job of a `.in` file like `Nylas.desktop.in`.

**Comment by mbilker** [comment]
It also only assumes its in `/usr/share/atom` is because the script checks `/usr/bin/../share/atom`.

**Comment by bengotow** [comment]
Hey @mbilker — it sounds like the issue here is that our ./N1.sh script is moved to /usr/bin/nylas and isn't really intended to be run in that context? Is the fix just to use the logic from Atom's `atom.sh`? Would love a PR on this one—we had someone else ask about it on the community channel today.

**Comment by mbilker** [comment]
@bengotow I will work on a PR for this. I do believe using Atom's launching logic will fix this. I think I commented on this before. Will try to dig my fixes up.

**Comment by pepa65** [comment]
Came here to report the same thing, that script/bootstrap isn't included (which is what is reported as the problem when running /usr/bin/nylas).
Having a symlink from /usr/share/nylas/nylas on /usr/bin works. (I don't know how necessary the script at /usr/bin is..?)

**Comment by mbilker** [comment]
It really isn't necessary. It finds the actual binary. It is like how Chrome has its binary in /usr/share but a script launches it because Chrome bases every other location based on the location of the main binary.

**Comment by joewilliams** [comment]
I have this issue as well on Ubuntu 14.04, this is my work around. Note that the menu icon when clicked doesn't seem to always work after this so I spin it off into the background.

`````````
$ sudo mv nylas nylas.old
$ sudo ln -fs /usr/share/nylas/nylas
$ nylas &
``````````

**Comment by bengotow** [comment]
Hey folks—this should be closed by @mbilker's pull request.
