### ISSUE TITLE
FileDownloadStore removes fulfilled download in _cleanupDownload before trigger

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#412]
In `src/flux/stores/FileDownloadStore.coffee`, I noticed in `_cleanupDownload` on line 233-236 that you trigger the store update callbacks after deleting the fulfilled event.

This prevents me from using the event to detect when an attachment download finished in my PGP plugin. The events completed events are not present in the `Object` so I cannot detect the change.

![2015-11-16-223448_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11202291/9da5ec8e-8cb4-11e5-8def-a6c873c61df7.png)

**Comment by mbilker** [comment]
Don't worry about the double logging, I placed 2 `console.log`'s in different places and forgot about one.

**Comment by mbilker** [comment]
Created a pull request, Travis running now.

**Comment by bengotow** [comment]
Hey! I think this has been addressed with your PR, gonna close this.

**Comment by mbilker** [comment]
Ahh yes it has. Thank you!
