### ISSUE TITLE
Ability to send from an email alias

### ISSUE THREAD

**Issue by liyaodong** [nylas/N1#414]
With inbox by gmail, I can setting my send by email account, because I have setting [Check email from other accounts with Gmail](https://support.google.com/mail/answer/21289?hl=en) feature, but I can't setting my send account with N1 client. 

Holp to add this feature, thanks !

**Comment by jstejada** [comment]
hi @liyaodong, we've added this to our open source backlog–feel free to track it here or upvote if you have a Trello account: https://trello.com/c/KO2UHr0i/24-send-using-aliases

**Comment by jstejada** [comment]
hey @liyaodong I'm merging this into #662
