### ISSUE TITLE
System Tray icon uses dark icon on active monitor

### ISSUE THREAD

**Issue by rahatarmanahmed** [nylas/N1#416]
N1 Version 0.3.23-94e0cb9 (0.3.23-94e0cb9)
OS X El Capitan

I've got 3 monitors and the dark OS X menubar theme enabled. On the monitor with the currently focused window, the system tray icon doesn't appear visible. If you click where it's supposed to be, it's actually there, but using the dark icon so it appears invisible. My other monitors show the white icon, however.

**Comment by jstejada** [comment]
thanks for reporting @rahatarmanahmed, we will fix this soon

**Comment by jdsimcoe** [comment]
:+1:

Screenshots for context:

![screen shot 2015-11-17 at 3 32 12 pm](https://cloud.githubusercontent.com/assets/275617/11228558/464320c2-8d42-11e5-8db0-108fb901420b.png)
![screen shot 2015-11-17 at 3 32 07 pm](https://cloud.githubusercontent.com/assets/275617/11228559/4656c7d0-8d42-11e5-8ae1-1bf85f2258bf.png)

**Comment by bengotow** [comment]
Hey @jdsimcoe — thanks for reporting this—it's been fixed in 3a16484d7dd530b0b618cd079ac54d68b1428554, will be included in the next update.
