### ISSUE TITLE
message.body removed when calling MessageBodyProcessor.resetCache() with unread email with undownloaded attachments

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#419]
Weird issue with unread mail with undownloaded attachments where the `this.props.message.body` and calling `MessageBodyProcessor.resetCache()` would set `this.props.message.body` to `""`.

This only occurs when the message is unread, even when the attachments are downloaded already.

Trying to work around the issue in my PGP plugin.

**Comment by mbilker** [comment]
Upon further investigation, `this.props.message.body` is intact after `MessageBodyProcessor.resetCache()`. After a page refresh, `this.props.message.body` becomes `""`.

**Comment by bengotow** [comment]
Hey @mbilker — I'll try to fix this tomorrow. Is there any code I could run to reproduce?

**Comment by mbilker** [comment]
I will push my code.

**Comment by mbilker** [comment]
Here is some code and a procedure:

From an unread message.
```
this.props.message.body = '<!DOCTYPE html><html><body>the body of the message</body></html>';
MessageBodyProcessor.resetCache();
console.log(this.props.message.body);
```
The body will print in the `console.log` statement, but if I check the body field after from the developer tools, it is `""`.

**Comment by mbilker** [comment]
My code is at https://github.com/mbilker/email-pgp/blob/master/lib/components/message-loader.es6#L205-L219

**Comment by mbilker** [comment]
Sorry, I didn't use the proper `MessageStore` method to process the message to display the modified body, and I misread `AutoloadImagesExtension`. I am creating my own fix now. Sorry about this.

**Comment by mbilker** [comment]
I based my new work on `AutoloadImage` to properly implement the interfaces needed to take care modifying a message's body.
