### ISSUE TITLE
Subfolders / Sublabels in the sidebar (tree view)

### ISSUE THREAD

**Issue by Envo** [nylas/N1#42]
I think it would be a huge UI improvement. Any plan on this? :)

**Comment by bengotow** [comment]
Hey! I agree this would be really great. I've added a card for it to our public package / feature ideas Trello board: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap. Feel free to upvote it there! I think it'd just be a UI change, so it should be fairly easy to get in.

**Comment by danielbayley** [comment]
+1!
