### ISSUE TITLE
Keep showing the console window and cannot enter the app

### ISSUE THREAD

**Issue by Voyga** [nylas/N1#420]
![image](https://cloud.githubusercontent.com/assets/9929523/11234943/c310a5fa-8e07-11e5-8752-1198feb90d85.png)

**Comment by mbilker** [comment]
Is this 0.3.23?

**Comment by bengotow** [comment]
Hi @Voyga — thanks for filing this. It looks like the root level of your home folder isn't owned by your user which is a bit strange, but it shouldn't be breaking this badly. I'll see if we can reproduce this today and I'll keep you posted.

**Comment by Voyga** [comment]
@mbilker It's `0.3.20-7a956cd`

**Comment by mbilker** [comment]
N1 version `0.3.36` is available. This issue should not be present in the new version.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
