### ISSUE TITLE
N1 menu bar for Mac

### ISSUE THREAD

**Issue by benlovell** [nylas/N1#421]
The menu bar icon and the unread count's font are not retina so look pretty awful next to the other retina entries on the menu bar. Are there any plans to address this?

Thanks for N1, I'm really enjoying using it! :heart:

**Comment by jstejada** [comment]
hi @benlovell , thanks for reporting. This has been fixed in https://github.com/nylas/N1/commit/3a16484d7dd530b0b618cd079ac54d68b1428554, it will be included in the next update.

**Comment by benlovell** [comment]
Thanks!
