### ISSUE TITLE
Spell checker sometimes doesn't read first character in word

### ISSUE THREAD

**Issue by g105b** [nylas/N1#423]
See attached screenshot.

![image](https://cloud.githubusercontent.com/assets/358014/11241762/55d4b894-8df5-11e5-8a36-7290a590d78d.png)

This happens rarely, but enough to notice. I haven't found out a way to reproduce, but I'm tracking it here in case anyone can shed some light on this.

Right clicking the underlined word gives me the options: December, remember, ember, embracer, embedder. If I choose December, the word becomes "DDecember", still underlined in red, but now with no spelling options.

![image](https://cloud.githubusercontent.com/assets/358014/11241800/9cd775c4-8df5-11e5-8173-a8e344c37044.png)

![image](https://cloud.githubusercontent.com/assets/358014/11241817/b6a363aa-8df5-11e5-9f89-4acff845cbac.png)

**Comment by jstejada** [comment]
hey @g105b we've fixed this and it will be available on the next release. Thanks!

**Comment by grinich** [comment]
I've hit this pretty reliably.

![image](https://cloud.githubusercontent.com/assets/92417/12149978/9d23d2ac-b45b-11e5-87f5-41141460cf0a.png)

![image](https://cloud.githubusercontent.com/assets/92417/12149981/a4276104-b45b-11e5-8416-d7b8a657cfb9.png)

Doesn't disappear ever.

**Comment by bengotow** [comment]
Hey folks—this should be resolved in 0.3.45 (we rewrote all the relevant code to avoid this and also the `doesn`'t scenario. Re-open if it pops up again!
