### ISSUE TITLE
Message body truncated or cut off

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#425]
When viewing an email about the new T-Mobile streaming conditions, the image loaded after the body was processed. This resulted in a truncated message body.

![2015-11-18-134808_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11250674/97b89392-8dfb-11e5-8d1f-2bb194642cdc.png)

**Comment by mbilker** [comment]
If you need the original message I am willing to share it. It doesn't contain much personal information.

**Comment by mbilker** [comment]
Still an issue in 0.3.34-beta.

**Comment by emorikawa** [comment]
@mbilker yes, if you see this happen again (or if you can find that email), can you hit "Report Issue: Rendering" from the hidden button between the timestamp and the reply dropdown. I'll take a look at it.

**Comment by mbilker** [comment]
Thanks @emorikawa. I have that email in my All Mail.

**Comment by emorikawa** [comment]
I believe this is fixed now cc @mbilker @markbao

**Comment by mbilker** [comment]
@emorikawa Recompiling now. Will see. I have other bugs to report with the latest master.

**Comment by mbilker** [comment]
Yes this fixes it.

**Comment by raknerak** [comment]
in which version it is fixed? I am using 0.4.5 b0ec335 but I have the same issue with this version.

**Comment by mbilker** [comment]
@raknerak Fixed in the 0.3.45. Could you post a screenshot?

**Comment by raknerak** [comment]
I reported over nlyas tool.
