### ISSUE TITLE
SMTP Verification Failing

### ISSUE THREAD

**Issue by chbachman** [nylas/N1#427]
Platform: Mac OS X 10.11
Nylas Version: 0.3.23-94e0cb9

I'm having trouble connecting to [my personal email](http://www.networksolutions.com/email-account/personal-email.jsp) with N1. 
Pastebin of Log: http://paste.ubuntu.com/13335827/

Applicable Part:
```
nylas-private-error-reporter.js:131 ErrorReporter: Shipping Logs. APIError
nylas-private-error-reporter.js:135 /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-private-ship-logs-task
task.js:50 [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
task.js:47 Running log ship: /var/folders/80/0phvlllx6f31c_zxjpxp7vth000102/T/, Nylas-N1-6339[.0-9]*.log$
task.js:47 No logs found to upload.
nylas-private-error-reporter.js:137 ErrorReporter: Shipped Logs.
```

I believe it has something to do with the non-standard response, due to other Mail applications saying "Cannot verify server identity, but working after that". However, I will admit that I am totally out of my depth here.

Hopefully this is something that N1 can support, however I understand if it would take too much time to support it.

Thank you for your time, and for this amazing mail client.

**Comment by mbilker** [comment]
Here you go #344, #153, #47. Known feature/issue. The Sync Engine (not N1) is responsible for connecting to the SMTP server, which trusts a certain set of certificates. It doesn't like self-signed ones or ones where the Common Name (CN) or Subject Alternative Names (SAN) doesn't match the domain name of the SMTP server.

**Comment by chbachman** [comment]
My apologies, I thought I had searched for the issue, I guess my Github-fu needs to be improved.
