### ISSUE TITLE
'webkitMovementX' is deprecated. Please use 'movementX' instead.

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#428]
In the image below, my developer console shows that a vendor-prefixed deprecated attribute is used, but is deprecated. I cannot find where that attribute is used in the code with a simple `grep -ri movementx .`

![2015-11-18-134808_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11260554/538a7a52-8e3a-11e5-8952-05ed3889cc8f.png)

EDIT: Forgot to add picture.

**Comment by bengotow** [comment]
Hey! I think this is coming out of Electron—it started happening after we upgraded Electron to 0.34.3 yesterday. I haven't found the source yet though...

**Comment by bengotow** [comment]
I think /somewhere/ in the codebase, we're duplicating an Event object by copying all it's key-value pairs. Trying to read webkitMovementX yields that error. I think we need something like this if statement to avoid copying that value into the new event: https://github.com/videojs/video.js/blob/master/src/js/utils/events.js#L240

**Comment by mbilker** [comment]
Okay. It is throwing the warning with underscore.js doing a copy.
