### ISSUE TITLE
Can't See Icon In OSX Menu Bar When Using OSX Dark Menu Bar

### ISSUE THREAD

**Issue by LiquidHelium** [nylas/N1#429]
The OSX icon in the Menu bar is always black, even if you are using the OSX dark menu bar, this means it's basically invisible (black on black), it should change to white if you are using the OSX dark menu bar like other OSX menu bar icons

**Comment by uncleserb** [comment]
+1

**Comment by artailicous** [comment]
I don't know but maybe this relates to #431 ?

**Comment by bengotow** [comment]
This has been fixed in master and will be corrected in the next release of N1. The menu bar icon is also retina on retina displays now.

**Comment by michaelcurry** [comment]
:+1: Hope the update comes out soon!

**Comment by schovi** [comment]
Good to hear!

**Comment by bengotow** [comment]
`0.3.25` should hit the auto-updaters in the next few minutes. Going to go ahead and close this. Cheers!
