### ISSUE TITLE
Loading Time exceeds 1 minute in Windows 10 64-bit.

### ISSUE THREAD

**Issue by artailicous** [nylas/N1#430]
It takes 1 minute and 19 seconds to load the Nylas app. By comparison Office Word 2016 takes around 12 seconds to load. And VLC media player take about 10 seconds. Both of which are 32 bit programs.

The system I report the loading time from:
Processor: AMD E-450 APU with Radeon™ HD Graphics 1.65 GHz
Installed memory (RAM) 4.00 GB (3.60 GB usable)
System type: 64-bit Operating System, x64-based processor

The ideal would be if the loading time were less then 9 seconds. Especially without heavy plugins.

**Comment by bengotow** [comment]
Hey @artailicous — yep, totally agree. It shouldn't take more than a few seconds (about ~2sec on my Mac). There must be something else going on here.

I'll do some testing with the latest Windows build and let you know if there's anything you can do to help profile the issue.

**Comment by mbilker** [comment]
I know a5256bd56a02ee82623079e7d92c8b8e8170002f heavily decreased loading times for me. I went from 30s load time to 3s in the debug mode. I use an SSD which helps a ton.

**Comment by mbilker** [comment]
That commit was not in the `0.3.23` release.

**Comment by bengotow** [comment]
Glad to hear that helped @mbilker — they did some great work in Atom to avoid re-compiling coffee/ES6 when the app launches. We'll push that out in the next release, we're just testing internally to make sure nothing broke with the move from Electron 0.29.2 => 0.34.3

**Comment by mbilker** [comment]
There is still the `ThemeManager` spec test that sometimes fails in Travis.

**Comment by grinich** [comment]
Does the latest version still load slowly?

**Comment by artailicous** [comment]
It loads much faster now, dear @grinich !
