### ISSUE TITLE
Pressing "use dark color scheme" creates issues

### ISSUE THREAD

**Issue by artailicous** [nylas/N1#431]
Especially if one want to remove the scheme right after. The the program stop responding. And if closing down, a reload of the app create a reset of settings. Meaning that one have to enter invitation code once more ect.

**Comment by artailicous** [comment]
It's actually not even possible to remove the dark color scheme once selected. Unchecking the box does not remove the scheme.

**Comment by artailicous** [comment]
![capture](https://cloud.githubusercontent.com/assets/6124885/11281498/2a80799c-8efb-11e5-85a0-8f465689b334.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6124885/11281500/2db6154a-8efb-11e5-8dde-ca48d517d4b8.PNG)

**Comment by jstejada** [comment]
hey @artailicous thanks for reporting this. This is probably unrelated to the dark menu bar on OSX. We will look into this. Thanks!

**Comment by bengotow** [comment]
Hey @artailicous — upon further investigation it looks like this and #430 are both impacted by disk read/write speed. When you change themes, the app needs to read theme CSS off the disk and it looks like those reads are either failing or taking so long they appear to have failed.

Do you have an SSD or a traditional spinning drive in your computer? I think replicating your filesystem read speed will allow us to reproduce this more easily and understand the scope of the issue.

**Comment by artailicous** [comment]
hey @bengotow, I do have a spinning drive. Disk drive says: HITACHI HTS723232A7A364. Here you can see it's performance: http://hdd.userbenchmark.com/SpeedTest/2190/HITACHI-HTS723232A7A364 .

**Comment by grinich** [comment]
@artailicous is this still happening for you?

**Comment by artailicous** [comment]
Everything works great @grinich !
