### ISSUE TITLE
New version not installing on OS X El Capitan

### ISSUE THREAD

**Issue by ansarizeeshan** [nylas/N1#435]
![screen shot 2015-11-20 at 9 24 33 am](https://cloud.githubusercontent.com/assets/7957173/11291642/92fe7f92-8f68-11e5-9548-3e0def42621a.png)

I recently got a notification to update N1 but whenever I clicked it closes.

**Comment by mbilker** [comment]
There should be a log file. Before you click the button, open up the Developer Tools from Developer -> Toggle Developer Tools and note the first line of the output, you may have to scroll up. That line should indicate the log file for the current process. Please upload the log file here using a gist or another text hosting service (pastie, pastebin, etc).

**Comment by bengotow** [comment]
Hi @ansarizeeshan — There was a bug in 0.3.23 that would prevent the app from quitting gracefully sometimes. Can you try force-quitting the app, and then re-launching it? It should allow you to click the Install button a few minutes after re-launching, and then it should install fine.

Let me know if that doesn't work!

**Comment by ansarizeeshan** [comment]
Now its working fine. Thanks

> On Nov 21 2015, at 5:10 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@ansarizeeshan](https://github.com/ansarizeeshan) — There was a bug in
0.3.23 that would prevent the app from quitting gracefully sometimes. Can you
try force-quitting the app, and then re-launching it? It should allow you to
click the Install button a few minutes after re-launching, and then it should
install fine.

>

> Let me know if that doesn't work!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/435#issuecomment-158558722).![](https://github.com/notifications/beac
on/AHlqtQcs9D1EIQ79ATASR60eszY3t8q-ks5pH6bmgaJpZM4GmG4X.gif)
