### ISSUE TITLE
Feature request: stack read mails in a conversion

### ISSUE THREAD

**Issue by jlpajares** [nylas/N1#437]
Greyed read emails in conversation view might be slightly narrower and stacked like in Gmail to avoid having to scroll in long conversations. Meanwhile maybe automatic scroll to the new mail would help.

**Comment by artailicous** [comment]
Yes this would be splendid, and let me add. That we should probebly compare to [Inbox by Gmail](https://www.youtube.com/watch?v=VCo3zZ0P4vU) in this regard.

**Comment by mbilker** [comment]
You mean like this?

![2015-11-20-075525_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11300329/24a9d7c8-8f5c-11e5-8d91-98470ff32d79.png)

**Comment by bengotow** [comment]
Hey folks—hmm, not sure I follow. We currently stack read messages if you have more than three. Is this what you're looking for?

![image](https://cloud.githubusercontent.com/assets/1037212/11310875/216ecf9e-8f81-11e5-9f56-10490a3c7559.png)

**Comment by artailicous** [comment]
This is how it looks in Inbox by Gmail, if someone want an invitation to take a closer look I have plenty.

![capture](https://cloud.githubusercontent.com/assets/6124885/11317296/4a5d9dbe-902a-11e5-835b-d76bc0e4f8ed.PNG)
Clicking on anything here will make you see more of that content. 
![capture2](https://cloud.githubusercontent.com/assets/6124885/11317297/4ef4e6e8-902a-11e5-835a-e373c5c65c45.PNG)
In the regular inbox archived emails do not show up, like they do here in the forum section.

This is basically material design as interpreted by Google. No need for it to be exactly like this.

**Comment by artailicous** [comment]
![capture3](https://cloud.githubusercontent.com/assets/6124885/11317351/5db9cd18-902c-11e5-9633-dcab33304abc.PNG)

The current design puts too much emphasis and focus on irrelevant content. An treat all mails equally in a conversation, this is not good. So yes @bengotow, that is much better!

**Comment by artailicous** [comment]
One example of this, that point torward a general design idea is the "4:06 am (a day ago)" for example. Here, one must ask, what do most people want to know in terms of time? Is it exact date, or an approximation? And if we know exact time on post, is exact time on posts nearby also perhaps relevant? Else there is no context to that information? Showing both is unfocused, and I would argue not really great design. The design should be a tool to help you filter the relevant information.

**Comment by jlpajares** [comment]
@bengotow exactly! I didn't realize that.

**Comment by bengotow** [comment]
Thanks @jlpajares — glad that's what you were looking for! @artailicous — we currently display unread messages in the thread expanded by default, and collapse read messages. More than three collapsed messages in a row become a "bundle" as in Gmail.
