### ISSUE TITLE
[Feature Request] Tag releases in Git so Arch Linux PKGBUILD can version packages correctly

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#438]
A typical Git/VCS-based user package in Arch Linux uses `git describe --long` to version the package to a specific version and Git commit hash. Currently, N1 is versioned, but the Git repository lacks tags to reference these releases.

**Comment by bengotow** [comment]
Hey @mbilker — you got it. We'll tag releases from now on. I've gone ahead and tagged the commit that was `0.3.23`. Thanks!
