### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by Blackrush** [nylas/N1#44]
Are there any plans related to calendar integrations ? If any, what the scope of the feature would be ?

**Comment by bengotow** [comment]
Hey @Blackrush — calendar integrations are definitely on the horizon. The Nylas Sync Engine actually supports calendars and events (Gmail, Exchange, and iCloud), and we're syncing them down to the app. They're just not displayed anywhere yet!

A full calendar is probably a ways off, but we'd love to have plugins that do light calendar integration (show you upcoming events on your calendar, quick event creation, etc.) If you have specific ideas I'd love for you to add them to the package ideas list on our Trello board:

The "Send Availability" example package also does some cool stuff with the calendar data already in the app: https://github.com/nylas/N1/tree/master/examples/N1-Send-Availability.

**Comment by ryanleesipes** [comment]
I realize this is closed, but I also like the idea of a full calendar. Popping into a browser or a different app for it seems unnecessary and is, frankly, not ideal. Plus N1 is so awesome I would love to see what you could do with a calendar app!

**Comment by stevemaughan** [comment]
I just need to be able to accept meeting invites sent to my IMAP account and have them added to my Google Calendar

**Comment by yehiasalam** [comment]
exactly, the only thing holding me back from switching from Outlook, I get an empty message on meeting requests
