### ISSUE TITLE
Support SSL self-signed certificates

### ISSUE THREAD

**Issue by JordanDoyle** [nylas/N1#442]
smtp.zoho.com:587, I can telnet into said host however after submitting the form when setting up the account, N1 hangs at "Adding account..." for an infinite amount of time

**Comment by JordanDoyle** [comment]
Quitting N1 with Cmd+Q allows me to open N1 to the main application and I can successfully send and receive email

**Comment by JordanDoyle** [comment]
Also can't add another (private) server which I think might be to do with the self-signed certificate. I can telnet into it, though.

**Comment by mbilker** [comment]
Self-signed certificates are not allowed. The Nylas Sync Engine checks certificates (#427, #344, #153, #47), though they are working on supporting more security configurations as stated in #344.

**Comment by EthanBlackburn** [comment]
Fixed in c5981d5a3084a04e97a0d73e66a64ab3ad63460d
