### ISSUE TITLE
process.env.NYLAS_HOME undefined during startup on Linux

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#445]
When I pulled a5256bd56a02ee82623079e7d92c8b8e8170002f from master, N1 crashes at https://github.com/nylas/N1/blob/master/static/index.js#L28 because `process.env.NYLAS_HOME` is undefined. If I do a `cat /proc/$PID/env | tr '\0' '\n'`, I see only the GPU process of N1 has the environment variable defined.

I do not remember how OS X handles environment variables, but on Linux the environment variables are not propagated between processes if the process is already a subprocess.

My hotfix is:
```
var app = require('remote').require('app');
var atomHome = path.join(app.getHomeDir(), '.nylas');
CompileCache.setHomeDirectory(atomHome);
```

**Comment by mbilker** [comment]
I left some commit comments, but I forgot to make an GH issue addressing the problem

**Comment by nivla** [comment]
Thanks, this solved my problem too.

**Comment by mbilker** [comment]
@nivla You are very welcome.

**Comment by jstejada** [comment]
thanks @mbilker, this is probably related https://github.com/atom/electron/issues/3306

**Comment by jstejada** [comment]
we'll push a fix really soon

**Comment by jstejada** [comment]
this is fixed on https://github.com/nylas/N1/commit/d759f6039b68f9cb2f1b8fbabe62635b579505fc
