### ISSUE TITLE
Searching is slow and inaccurate

### ISSUE THREAD

**Issue by thejouni** [nylas/N1#446]
Searching takes ages and when the search is finished I dont have the confidence that all messages were found. E.g. messages in folders/labels are rarely found. Also when searching by an email address, very rarely emails where that is the sender are found.

**Comment by bengotow** [comment]
Hi—N1 currently maps to your underlying provider's search (so for Gmail users, it's full Gmail search with support for things like `subject: foo`, and for others it's identical to the search provided by your webmail client). Unfortunately, some services like Outlook.com have pretty bad built-in search. In the future, we'll build our own search system on top of what's available from the provider, but it'll take a little while.
