### ISSUE TITLE
Print multiple messages as PDF

### ISSUE THREAD

**Issue by thejouni** [nylas/N1#447]
Usecase: Uber and similar services send their invoices as separate emails. I need to print (pdf) them all for accounting: printing them one by one is painfully slow task when there are 30-40 invoices per month. 

Solution: Search "invoices" -> select all -> "Save all as PDF" -> done

**Comment by g105b** [comment]
You're implying that there is a way to print individual messages? If so, could you let me know how you are achieving printing a message, for #508 ?

**Comment by mbilker** [comment]
This will likely require the print event to be forwarded to the `EventedIFrame`. I can do `window.print()` from the DevTools console, but this will print the whole page.
[output.pdf](https://github.com/nylas/N1/files/46766/output.pdf)

**Comment by jstejada** [comment]
yeah, we're working on adding a print option, it should be ready for our next release. I'm gonna go ahead and merge this into #508
