### ISSUE TITLE
View Menu: Duplicate Enter / Exit Full Screen items

### ISSUE THREAD

**Issue by qaid** [nylas/N1#45]
View menu is showing duplicate items, one of which shows keyboard shortcut.

![n1-duplicate-view-menu-items-1](https://cloud.githubusercontent.com/assets/2238082/10324631/66e29722-6c8b-11e5-821f-db2379603c28.png)

![n1-duplicate-view-menu-items-2](https://cloud.githubusercontent.com/assets/2238082/10324638/702bfcce-6c8b-11e5-921f-f38e937bd991.png)

**Comment by bengotow** [comment]
Wow this is super interesting—thanks for reporting @qaid. Are you running a compiled version from nylas.com/N1 or building from source? Can you make sure you're using Electron 0.29.2 and not a newer version? (Electron should be installed by running script/bootstrap.) 

There's supposed to be an attribute set on one of those menu items to toggle them visible / invisible based on whether the app is full screen.

Does it fix itself if you make the app fullscreen and then exit fullscreen mode?

**Comment by Envo** [comment]
I have this one too (running the compiled version from your site).

**Comment by qaid** [comment]
I'm running the compiled version from the site. (Haven't yet messed with nvm so that I can build the source locally; I'm running node v12.something.)

If I make the app fullscreen, I still get the duplicate menu items (showing "Exit Full Screen").

**Comment by bengotow** [comment]
Thanks - are you on El Capitan? Trying to reproduce now.

**Comment by qaid** [comment]
@bengotow indeed: El Cap.

**Comment by bengotow** [comment]
Hey folks—just wanted to follow up here. This has been identified as a bug in Electron, and is also causing the same behavior in the Atom text editor. You can track it here: https://github.com/atom/electron/issues/3038

**Comment by bengotow** [comment]
This has been fixed upstream in Electron.
