### ISSUE TITLE
Probably accidental "license": "Proprietary"

### ISSUE THREAD

**Issue by dcposch** [nylas/N1#452]
I noticed all the internal packages (`composer`, `attachments`, etc) have a `package.json` that specifies a "Proprietary" license.

I'm guessing this is by accident? All of N1 is GPL licensed, right?

**Comment by dcposch** [comment]
Related: https://github.com/nylas/N1/pull/453

**Comment by bengotow** [comment]
Thanks for the PR! I've changed the examples as well.
