### ISSUE TITLE
Labels did not sync with GMail

### ISSUE THREAD

**Issue by aixnr** [nylas/N1#456]
![screen shot 2015-11-24 at 7 24 33 pm](https://cloud.githubusercontent.com/assets/1288147/11384970/8777905a-92e2-11e5-8191-83f1eec2d652.png)

I made changes to the labels on GMail after connecting my email account to N1. I reloaded N1, tried quitting and opening the question back, and also I tried unlinking account and linking back, the labels didn't update to reflect changes I made on GMail.

How do I re-sync the GMail account?

**Comment by dkouvdis** [comment]
https://github.com/nylas/N1/issues/333

**Comment by dkouvdis** [comment]
Please confirm the new update had sorted your issue. Check the new update details via changelog

**Comment by bengotow** [comment]
Hey folks—label changes should be reflected properly now in N1, thanks to changes in the sync engine.

**Comment by aixnr** [comment]
Hi @bengotow. I just opened Nylas N1 on my laptop (OSX). I checked the labels, still the problem persists as of now. Am I missing something here? Is there any "sync" button, or just wait patiently?

As I posted above, the labels in N1 do not reflect what I have on my GMail. Also, there is addtional `\All` label.

**Comment by MaximSavin** [comment]
How is possible to re-sync the labels forced!?

I cleaned labels in Gmail, but in the application old labels still stayed ...

**Comment by eugv86** [comment]
Labels dont re-sync no matter what I do.
