### ISSUE TITLE
N1 Crashing and Removing Accounts

### ISSUE THREAD

**Issue by TheConnMan** [nylas/N1#457]
After closing the app and reopening it all accounts will be removed and the Getting Started screen is presented again. This occurred after I tried to install the Personal Level Indicators plugin and another couple times when I modified basic preferences and added another Gmail account. N1 seemed like it didn't like adding an additional account and closing the app when the first account was still syncing. Account syncing picked up for both accounts as soon as the accounts were reauthorized.

Windows 10 64-bit
N1 v0.3.23
Two Gmail accounts

**Comment by TheConnMan** [comment]
Another failure mode. After writing an email I got a "Can't save to drafts" error. Editing the light/dark theme was buggy as well (the checkbox was not accurate or toggling). Then I force closed the app, though the Feedback modal I had open would not force close. After reopening the app all accounts were removed.

**Comment by jstejada** [comment]
hey @TheConnMan are you still having these issues?

**Comment by TheConnMan** [comment]
Since v0.3.25 I haven't had any issues and haven't had any crashes.
