### ISSUE TITLE
Gmail Double Authentication

### ISSUE THREAD

**Issue by TheConnMan** [nylas/N1#458]
During the first OAuth request for a Gmail account N1 correctly redirects to the Gmail sign-in and authenticates. After the "You're All Set!" message nothing happens within N1, the "Sign in to Gmail in your browser" message persists. Clicking the back button on the N1 modal and adding the Gmail account again then successfully authenticates, prompting N1 to respond.

Windows 10 64-bit
N1 v0.3.23
Two Gmail accounts

**Comment by quangbahoa** [comment]
Same here.

**Comment by Muurtegel** [comment]
I noticed this as well with multiple Gmail accounts.
The second time it only asks for offline access.

I'm on OSX 10.11
N1 Version 0.3.23-94e0cb9 (0.3.23-94e0cb9)

**Comment by zorrobyte** [comment]
Same

**Comment by just2jays** [comment]
+1 with issue :P

**Comment by grinich** [comment]
Can you potentially record a screencast or animated gif? After authenticating, N1 should automatically detect the login credential and more to the next screen.

**Comment by TheConnMan** [comment]
I will try to replicate the issue tomorrow and record a gif if I can.

**Comment by TheConnMan** [comment]
I just added a second account and it did not require double authentication. Unless anyone else can replicate it this can be closed.

**Comment by jstejada** [comment]
I'm closing this, will reopen if it happens again.

**Comment by adi-** [comment]
I have the same issue. I cannot add my Gmail account to Nylas N1 without accepting "offline access". Is it really necessary? I am really aware of adding access rights to my data, stored somewhere in the server.
