### ISSUE TITLE
Cannot connect to mailserver (ZIMBRA)

### ISSUE THREAD

**Issue by syky27** [nylas/N1#459]
Hi, guys this email client looks sweet, but I am having trouble connecting to my mail server,
I am running Zimbra following version.

![screenshot 2015-11-25 03 05 39](https://cloud.githubusercontent.com/assets/2771802/11386519/48ef289e-9322-11e5-84de-bbb8ccd7771d.png)

I used exactly same settings as I use for Apple Mail.app it doesn't seem to work, the client says, 

> Please check that your SMTP settings are correct. 

OR

> Error connecting to the server.

I am positive that, that I am entering those credentials correctly because it works with other mail clients such as Mail.app or AirMail.

I am setting up my mailbox over IMAP/SMTP.

I would love to get any hints, there always possibility that I am doing something wrong on my side, but honestly I checked that like gazilion times, not to bug you about my stupidity, and now I have no idea why it is not working... :( 

Telnet : `$ telnet mail.theajty.com 587`

**Comment by syky27** [comment]
![screenshot 2015-11-25 03 05 39](https://cloud.githubusercontent.com/assets/2771802/11386513/35b2e4be-9322-11e5-8288-36e81784d67e.png)

**Comment by mbilker** [comment]
TLS/SSL certificate selfsigned?

**Comment by EthanBlackburn** [comment]
Hey syky27, it sounds this was due to a self-signed SSL certificate on your SMTP server. We've added support for this in https://github.com/nylas/sync-engine/commit/c5981d5a3084a04e97a0d73e66a64ab3ad63460d, so I'm going to close this issue. Please let us know if you continue to have issues authenticating

**Comment by syky27** [comment]
Hi, Downloaded Nylas from website one more time so I am not sure, if the build I have downloaded includes this fix, but I still get the same error.

Tnaks.

**Comment by syky27** [comment]
Do you need any more info from my side?

Thanks!

**Comment by EthanBlackburn** [comment]
That would be great -- are you using a self-signed SSL certificate?

**Comment by syky27** [comment]
Well, the the Zimbra runs on HTTPS, and there is no certificate. So the browser says, that you have reached unsecured ....

**Comment by syky27** [comment]
Yes I am using self-signed SSL Certificate. As you can see https://mail.theajty.cz

**Comment by syky27** [comment]
OK, so I got it finally working. The deal is.
```
PORT     STATE SERVICE
22/tcp   open  ssh
25/tcp   open  smtp
110/tcp  open  pop3
143/tcp  open  imap
389/tcp  open  ldap
443/tcp  open  https
465/tcp  open  smtps
587/tcp  open  submission
993/tcp  open  imaps
995/tcp  open  pop3s
7025/tcp open  vmsvc-2
8443/tcp open  https-alt
```

Those ports are open. 993 is SSL secured, 143 is not. To successfully add my account I had to choose 143 port SSL checked in UI, and smtp normally as is supposed to be. 

So I think that there might be going on something fishy about imap with ssl in Nylas N1.

**Comment by EthanBlackburn** [comment]
Thanks for the update. You're right, this is definitely an issue with IMAP over SSL not SMTP. I'll look into this and let you know when we have a patch available

**Comment by syky27** [comment]
Thanks.

> On Dec 1 2015, at 7:00 pm, Ethan Blackburn &lt;notifications@github.com&gt;
wrote:  

>

> Thanks for the update. You're right, this is definitely an issue with IMAP
over SSL not SMTP. I'll look into this and let you know when we have a patch
available

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/459#issuecomment-161048422).![](https://github.com/notifications/beac
on/ACpLWvzctypk776Slolj-4Xevp82Ph9Yks5pLde0gaJpZM4Go5GQ.gif)

**Comment by EthanBlackburn** [comment]
The issues you were having during authentication appear to have been because we were restricting poor SSL ciphers. We're no longer restricting ciphers, so could you try authenticating over SSL again?

**Comment by spang** [comment]
(please reopen if still an issue!)

**Comment by VEEC023** [comment]
Same Problem here. 

"Please check that your SMTP settings are correct"

Without SSL it works.
