### ISSUE TITLE
Unread Count Misrepresentation

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#460]
Arch Linux - 11/24/15
N1 master 2bd83f38ff65494f5a7b2acc2152b419d492102f or mbilker/N1@2f543907f78dbc39abd8c1385921d5e27af6105f

Recently, the sidebar fails to update correctly and I now experienced an unread count of -1 and an unread count of 10. The -1 unread count occurs on my laptop after I quickly archived many messages in rapid succession after skimming the content to see if they were interesting, one message had a thread count of 2.

![2015-11-24-204157_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11386627/1c58edb4-92f1-11e5-961e-6ce9a1c4782f.png)
Figure 1: Before reading, notice how the unread counter is less than the number of unread messages

![2015-11-24-204322_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11386630/1e86df74-92f1-11e5-8ccb-095345393066.png)
Figure 2: After reading and archiving, notice how the unread counter is -1

**Comment by jstejada** [comment]
hey @mbilker , yeah we're pushing a fix for this as of now

**Comment by mbilker** [comment]
Thanks @jstejada !

**Comment by bengotow** [comment]
Yep! Should be fixed in 121fb2482d570ce84982a4c682f7f4058bd7ee9e — let me know if you continue to have trouble.
