### ISSUE TITLE
Cannot create account with SMTP without login/password

### ISSUE THREAD

**Issue by schmurfy** [nylas/N1#467]
I am using an SMTP which is only available when I am physically connected to my network so there is no need for authentication but when I tried to configure it with N1 I get this error: `nylasEnv is not defined`.
If I enter a login and password it says `invalid credentials` and it is right since there is none xD

I tried this on a version downloaded today from the download button on the website (version 0.3.23-94e0cb9).

**Comment by visualcookie** [comment]
Duplicate with #47?

**Comment by schmurfy** [comment]
I saw the first one but it seemed rather vague and also turned into some kind of all in one bag, that is why I decided to create a separate focused issue but you can close it if you consider it a duplicate and I will add a comment on it.

**Comment by mbilker** [comment]
Ahh. N1 communicates with the Nylas Sync Engine remotely, which the default one is run by Nylas. If the remote server cannot access the SMTP server the connection will fail, and as you stated the SMTP server is only available on your local network.

You need to run your own instance of the Nylas Sync Engine locally to connect to the SMTP server.

**Comment by bengotow** [comment]
Hey @schmurfy — yep, @mbilker is correct. N1 is not compatible with SMTP / IMAP servers that are behind firewalls, on private networks / VPNs, or otherwise unavailable from the public internet. Unfortunately, this is a core design assumption of the sync engine and we won't be able to work around it. Sorry for the hassle!

**Comment by schmurfy** [comment]
One reason I tried it is that I feared from the description it was not a "real" email client but just a frontend, I am really sad I was correct :(

Any plan to have a standalone version at some point ?

Ps: having an unreachable smtp server has nothing to do with the error I get by the way (the undefined nylasEnv), it is obvious by the response time that the error is local.

**Comment by mbilker** [comment]
@schmurfy yep that is a local error. The reason it is not standalone is because the Nylas Sync Engine takes care of the interfacing with IMAP and other protocols to reduce bandwidth for Email. You can run your own instance of the Nylas Sync Engine, instructions are in the README.

**Comment by schmurfy** [comment]
Yes I know I can but that is far less convenient, too bad :/
