### ISSUE TITLE
Unread counts for all accounts

### ISSUE THREAD

**Issue by omidantilong** [nylas/N1#468]
The only thing stopping me from switching right now is the fact I have to manually move between mailboxes in the account dropdown to get their unread count. It would be cool to get an overview of each account at the top of the list - a bit like Thunderbird (see attachment)

Unfortunately I've picked a slow email day to mention this, but normally the unread count is displayed next to each of 5 accounts. 

I'm less fussed about a unified inbox, but this would be a deal breaker for me. 

Cheers!
 
<img width="214" alt="screen shot 2015-11-25 at 10 58 17" src="https://cloud.githubusercontent.com/assets/1922098/11395599/ea98c2b8-9363-11e5-81f5-5c38eb567483.png">

**Comment by jstejada** [comment]
hey @omidantilong , thanks for contributing! That's definitely doable, we are looking at ways to implement this into our UI.

**Comment by miguelcobain** [comment]
:+1:

**Comment by omidantilong** [comment]
Hey @jstejada, thanks for the response. That sounds great :)

**Comment by boborchard** [comment]
:+1: I'm 100% behind that. Has anyone started working on getting unread counts in the top switcher?

**Comment by sergeyklay** [comment]
:+1:

**Comment by kobak** [comment]
:+1:

**Comment by arehrlich** [comment]
Big thumbs up for this... much to difficult to search for the account that has an unread email.

**Comment by ThePsionic** [comment]
:+1:

**Comment by AdamasFR** [comment]
Yeah, it's the only thing I miss from Thunderbird! I was able to be sure I had no unread mail just by glacing at the screen. Now I have to manually open each account, a little pain in the butt.

**Comment by grinich** [comment]
This is coming very soon :)

**Comment by jstejada** [comment]
hey everyone! Merging this in to #537 since this is fixed on that branch. Stay tuned! Heading to beta shortly.
