### ISSUE TITLE
Can't run N1 version 0.3.25 on Linux

### ISSUE THREAD

**Issue by resilva87** [nylas/N1#469]
Hi guys,

It seems that running version 0.3.25 on Linux (Mint 17.2) is causing an error related to LinuxSUIDSandbox:

    [rsilva:~/Apps/N1] master ± bash N1.sh 
    [7219:1125/114429:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox!   See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
    Streaming log data to /tmp/Nylas-N1-7219.log
    Error opening app
    The app provided is not a valid electron app, please read the docs on how to write one:
    https://github.com/atom/electron/tree/master/docs

    Error: Cannot find module 'source-map-support'

Version 0.3.23 works fine.

**Comment by mbilker** [comment]
Have you run `script/bootstrap`.

**Comment by resilva87** [comment]
Hi @mbilker. Indeed, I had run the bootstrap script but the problem was happening. After deleting the directory, cloning the repo again and running bootstrap, it's working fine now.

Thanks!
