### ISSUE TITLE
Sent item editable

### ISSUE THREAD

**Issue by rdewolff** [nylas/N1#471]
Hi all

Am wondering why when I go in my "Sent" item (Gmail or Exchange) the mails are editable?

Is that a feature? A bug? At least that's very disturbing.

Thanks for your feedback!

Looking forward testing this nice mail client.

**Comment by jstejada** [comment]
hey @rdewolff, thanks for reporting. I can't seem to replicate. How are you managing to edit the sent messages?

**Comment by rdewolff** [comment]
hi @jstejada - well I simply click on the "Sent" folder and all the latest sent item are editable. Meaning if I click somewhere on the message, the cursor is blinking and I can type in any text.

Don't have access to the computer right now. Will make a screenshot tomorrow.

**Comment by rdewolff** [comment]
Have you been able to reproduce the bug? Is this resolved in the new build?

**Comment by rdewolff** [comment]
I have reinstalled the new version and tested again. Found more precision :

For testing, I have set up only my MS Exchange account.

There seems to be a big error : the server shows 656 drafts! Which I don't have if I login via the Outlook Web Access or when I open AirMail 2 for the same account. 

That's why in my sent folder there are so many "editable" content. The error reside in the draft folder I suppose?

I'd be happy to send you more information. Just let me know what you need. Could give you remote access to my machine for a little moment if that might help.

**Comment by rdewolff** [comment]
Any news on this bug?

**Comment by rdewolff** [comment]
@jstejada : have you been able to look more into it? Have you tried with Exchange accounts?

**Comment by rdewolff** [comment]
Example of the inbox view :

![screenshot_18_12_15_12_23](https://cloud.githubusercontent.com/assets/130704/11895909/8e1049fe-a582-11e5-984b-b4e8e1ed753c.png)

**Comment by khwerhahn** [comment]
Same for me. Its for Gmail though, not Exchange.

**Comment by jstejada** [comment]
hey @rdewolff thanks for the additional details, this is really helpful. Still haven't been able to replicate, but I'll get back to you soon

**Comment by rdewolff** [comment]
@jstejada if you need anything else, I'd be happy to provide. Just let me know what could help you!

**Comment by jstejada** [comment]
hey @rdewolff , could you send an email to support@nylas.com with your email address so we can look into this? Or use the help window (`?` button in the bottom right corner) to enter the support chat.

**Comment by rdewolff** [comment]
@jstejada done via (?) button.

**Comment by rdewolff** [comment]
Looking forward that bug to be fixed so I can test Nylas N1 deeper.

**Comment by jstejada** [comment]
hey @rdewolff, I'm going to merge this into #869
