### ISSUE TITLE
Combined Inbox view?

### ISSUE THREAD

**Issue by brianjking** [nylas/N1#472]
Is there a way to view multiple email accounts inboxes in a single view? If not, I hope this is coming! 

Thanks!

**Comment by rdewolff** [comment]
+1!

**Comment by jstejada** [comment]
hey @brianjking , thanks for contribuitng! "Unified inbox" is definitely on the roadmap. We've created a card for it on our open source Trello board, and you can track it there. Feel free to upvote it there if you've got a Trello account: http://trello.com/b/hxsqB6vx/n1-open-source-roadmap. Closing as a duplicate of #123

**Comment by brianjking** [comment]
@rdewolff Just upvoted, couldn't find the card initially so here's the link in case you want to help out too by submitting a vote! https://trello.com/c/5pIfWaN3

Thanks @jstejada

**Comment by rdewolff** [comment]
Thanks guys!
