### ISSUE TITLE
Displays mail from other mailbox

### ISSUE THREAD

**Issue by Muurtegel** [nylas/N1#473]
This is a bit hard to explain, so here's a screenshot to explain what I mean:

![screen shot 2015-11-25 at 16 42 18](https://cloud.githubusercontent.com/assets/1235583/11401767/68b84594-9394-11e5-8c1f-43d7af67ec35.png)

As you can see, there are no threads in this mailbox. What you see is my inbox, which is empty, and an email which is situated in my starred mailbox.

This what my starred mailbox looks like:
![screen shot 2015-11-25 at 16 41 59](https://cloud.githubusercontent.com/assets/1235583/11401795/9117a7d2-9394-11e5-91d7-63b1a2d11226.png)

I have 2 Gmail accounts in N1, this bug happened by switching between them. Here is how:

1. I open my starred mailbox in account 2, which contains 1 email
2. I switch to my other gmail account (account 1) which displays the inbox
3. I open the starred mailbox in account 1, which does not contain any messages
4. I switch back to gmail account 2, which displays my empty inbox, but also displays the email from the starred mailbox of account 2.

Additional information:
- When I switch from account 2 to account 1, I notice the issue which has been discussed here: https://github.com/nylas/N1/issues/433
- I'm on OSX 10.11
- I use Nylas N1 Version 0.3.23-94e0cb9 (0.3.23-94e0cb9)

If there is anything else I can send that might be helpful, let me know.

**Comment by Muurtegel** [comment]
Things just got a bit weirder when an email from April this year opened. 

I have no idea why this particular email opened as it's been buried in my inbox below tons of emails since.

**Comment by emorikawa** [comment]
Hi, we've re-done how the focused mail and focused sections work with work on the unified inbox. I believe it has also fixed this issue in the process. These changes will be rolled out on in a release soon.

**Comment by jstejada** [comment]
hey @Muurtegel, as evan mentioned, the way we manage the focus of messages has been redone and this should be fixed with our upcoming release. Feel free to reopen if the problem persists.
