### ISSUE TITLE
Search Not working on selected item in dropdown

### ISSUE THREAD

**Issue by GEverding** [nylas/N1#474]
Tried searching for a email subject in search bar and I couldn't select the item I wanted with my mouse. Tried using the arrow keys and was able to highlight the row I wanted but when I hit enter it didn't search for it. 

N1 Version: 0.3.23-94e0cb9 (0.3.23-94e0cb9)

**Comment by bengotow** [comment]
Hi @GEverding — we released an update a few minutes ago (0.3.25) that should fix this. Can you try in the latest version and see if you're still running into trouble?

**Comment by GEverding** [comment]
:+1: Looks good.
