### ISSUE TITLE
AccountSidebar failed propType

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#476]
Running master

```
Warning: Failed propType: Required prop `selected` was not specified in `AccountSidebarSection`. Check the render method of `AccountSidebar`.
Warning: Failed propType: Required prop `selected` was not specified in `AccountSidebarItem`. Check the render method of `AccountSidebarSection`.
```

I have not looked into the source, but I felt like reporting this since React warnings show up in debug mode.

**Comment by bengotow** [comment]
Hey @mbilker — good catch. I've fixed this in e0e6a288f1824ff24288b989a36c120bf729ddbc - looks like it wasn't actually required.
