### ISSUE TITLE
Exposed AWS Access and Secret Keys

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#48]
In src/tasks/ship-logs-task.coffee, the accessKeyId and secretKey for a AWS S3 bucket, specifically edgehill-client-logs. I did not attempt to retrieve or upload anything from the bucket as I consider it morally wrong. Are there appropriate access restrictions in place to allow this sensitive information to be stored in plain text in a public repository?

**Comment by bengotow** [comment]
Hey @mbilker thanks for pointing this out (and not trying to use them for anything malicious.) We're aware that they're included in the source and in the distributed versions of the app. Those credentials only give the client the ability to upload to that specific bucket, and not list contents or fetch files. The logs uploaded to that bucket are fed into Logstash, which allows us to monitor SQLite query performance and generate other aggregate metrics. It helps us identify performance regressions and things we can't see during development.

I don't think this is a security issue, but we should do more to make sure that sensitive data is never included in these logs, and we may need to remove the credentials from the app to prevent Amazon from automatically considering them compromised. Stay tuned—

**Comment by mbilker** [comment]
Thank you very much for the update. I only noticed it because its the only non-bundled source file I found.
