### ISSUE TITLE
App not launching in Windows 10

### ISSUE THREAD

**Issue by delixyr** [nylas/N1#480]
App not launching in windows 10
Stuck showing this
![ss2](https://cloud.githubusercontent.com/assets/4602841/11417491/a4a24f1a-943d-11e5-9369-eafd76b6c5a9.png)

![ss](https://cloud.githubusercontent.com/assets/4602841/11417456/5caf0ea0-943d-11e5-8e35-326585832b8a.png)

**Comment by IgorKvasn** [comment]
the same thing happened to me on windows 7 - I run the installer once again and it worked afterwards

**Comment by delixyr** [comment]
Even mine ran after a few launches..

**Comment by grinich** [comment]
Yikes! That's a lousy bug. Can anyone find steps to reproduce?

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
