### ISSUE TITLE
AccessDenied when downloading linux .deb

### ISSUE THREAD

**Issue by sgiraud01** [nylas/N1#482]
The download link of the linux release at [https://edgehill.s3-us-west-2.amazonaws.com/0.3.25-c174641/linux/x64/N1.deb]  give me an AccessDenied 

```
<Error>
<script id="tinyhippos-injected"/>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0216D9893D02F5E7</RequestId>
<HostId>
i2fTAK0AlaYMRW2oUPYz+AZb+wMwWs4IeS9KaIGPvAQXf5RRDeJgqN9k83llDwvjCif2SD87tcs=
</HostId>
</Error>
```

**Comment by wendannor** [comment]
Same here. I unfortunately cannot try out N1 on my Ubuntu yet ;-)

**Comment by THPubs** [comment]
Same problem here :-)

**Comment by microstudi** [comment]
Same here!

**Comment by soyuka** [comment]
Same :|

**Comment by sgiraud01** [comment]
This link is OK
https://edgehill.nylas.com/download?platform=linux

**Comment by grinich** [comment]
Fixed! You should be able to download via https://nylas.com/n1
