### ISSUE TITLE
Triggering Prefs from menu bar when app window closed causes app crash

### ISSUE THREAD

**Issue by uncleserb** [nylas/N1#484]
If the Nylas window is closed and you attempt to access `Preferences` from the Mac OS menu bar, Nylas will hang for a couple of seconds and will ultimately hard lock and close thus failing to display the in-app `Preferences`.

**Comment by jstejada** [comment]
also related to #481

**Comment by jstejada** [comment]
@uncleserb thanks! we've pushed a fix for this and will release soon

**Comment by uncleserb** [comment]
thanks for the quick fix @jstejada!
