### ISSUE TITLE
CardDav sync support

### ISSUE THREAD

**Issue by HLFH** [nylas/N1#487]
Hi,

We need CardDav sync support. It would also to sync and update contacts from N1 client to some CardDAV servers like ownCloud, Radicale, DAViCal...

Thanks,
HLFH

**Comment by bengotow** [comment]
Hey! The sync engine (https://github.com/nylas/sync-engine) doesn't currently support CardDav, and we don't plan to build a full contact management interface into N1 for quite a while. Going to go ahead and close this as a wont-fix for now, but pull requests are very welcome!
