### ISSUE TITLE
Clicking on Nylas N1's app icon on the OSX Dock closes the app

### ISSUE THREAD

**Issue by aixnr** [nylas/N1#488]
![untitled](https://cloud.githubusercontent.com/assets/1288147/11427128/af9ec006-942e-11e5-8b1d-afc23f42eea8.gif)

Hey there. I would like to report a bug here. After closing the app (not quitting it), clicking its icon on the OSX Dock triggers itself to quit, as you see above.

**Comment by louim** [comment]
I get the same problem since updating to the newest version: `Version 0.3.25-c174641 (0.3.25-c174641)` When clicking the rex "X" to close the main app window, clicking the app Icon will close the App.

**Comment by jstejada** [comment]
thanks for reporting! I'm merging into #481
