### ISSUE TITLE
No Keyboard Shortcut to Mark Email as Unread

### ISSUE THREAD

**Issue by matthewbassett** [nylas/N1#490]
Hi, thanks for the work on an excellent client.

I have my keyboard shortcuts to gmail, and I found an issue saying mark as read should be the same as gmail, however shift+i doesn't do anything for me. I am able to use e and y to archive an email, however I can't find any keyboard shortcut for mark as read. My apologies if I'm missing something obvious. Thank you!

**Comment by jstejada** [comment]
Hi @matthewbassett , I believe the shortcut you are looking for is Shift-u (https://support.google.com/mail/answer/6594?hl=en). Let me know if this works for you. Also make sure you have selected the Gmail shortcuts in our preferences page.

**Comment by jstejada** [comment]
hi @matthewbassett , you were right, the keyboard shortcuts were not working. We've pushed a fix for this and will be available on the next release.

**Comment by matthewbassett** [comment]
Bless you (: Thanks for a fantastic client

On Wed, Dec 2, 2015 at 1:47 AM Juan <notifications@github.com> wrote:

> Closed #490 <https://github.com/nylas/N1/issues/490>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylas/N1/issues/490#event-479242040>.
>
-- 
Thanks,

Matt
