### ISSUE TITLE
Linux: NYLAS_HOME undefined producing error at startup

### ISSUE THREAD

**Issue by romabysen** [nylas/N1#492]
When starting N1 the splash screen shows the debug console with the following message:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at Object.exports.setHomeDirectory (/usr/share/nylas/resources/app.asar/src/compile-cache.js:24:23)
    at setupWindow (file:///usr/share/nylas/resources/app.asar/static/index.js:28:16)
    at window.onload (file:///usr/share/nylas/resources/app.asar/static/index.js:86:5)
```
N1 never moves past this error, the splash screen stays forever.
N1 is installed from .deb downloaded today. OS is Ubuntu 15.10 64bit.

**Comment by sgiraud01** [comment]
I've the same here with the same configuration

**Comment by tswestendorp** [comment]
Same here.. Ubuntu 14.04.3 x64

**Comment by wendannor** [comment]
Same here with `Ubuntu 15.04 64-bit`

**Comment by soyuka** [comment]
It's because the env variable `NYLAS_HOME` does not exist. I'm able to run using:
```
NYLAS_HOME=/usr/share/nylas /usr/share/nylas/nylas
```

**Comment by tswestendorp** [comment]
Doesn't work here either
```$ NYLAS_HOME=/usr/share/nylas /usr/share/nylas/nylas 
Streaming log data to /tmp/Nylas-N1-20615.log
App load time: 344ms
(electron) terminate is deprecated. Use quit instead.```

**Comment by soyuka** [comment]
I have `return compileCache.setHomeDirectory(process.env.NYLAS_HOME);` in `setupCompileCache` (somewhere in the compiled file `/usr/share/nylas/resources/app.asar`). Exporting the env variable works to me on debian 8.

**Comment by sgiraud01** [comment]
Thanks you @soyuka 
NYLAS_HOME=/usr/share/nylas /usr/share/nylas/nylas  
It's OK for me. I've had the export in my /etc/profile

**Comment by sgiraud01** [comment]
I've switched !

**Comment by madfriend** [comment]
same on Ubuntu 14.04

**Comment by YugalXD** [comment]
same with me @tswestendorp

**Comment by ChristopheLux** [comment]
Kubuntu 15.10 64 bit
{"host":"xxx","timestamp":"2015-11-26T14:14:48.161Z","payload":{"stack":"ReferenceError: nylasEnv is not defined\n  at AnalyticsStore.identify (/usr/share/nylas/resources/app.asar/internal_packages/nylas-private-analytics/lib/analytics-store.js:165:30)\n  at AnalyticsStore.<anonymous> (/usr/share/nylas/resources/app.asar/internal_packages/nylas-private-analytics/lib/analytics-store.js:91:24)\n  at EventEmitter.eventHandler (/usr/share/nylas/resources/app.asar/src/flux/modules/reflux-coffee.js:197:27)\n  at emitOne (events.js:82:20)\n  at EventEmitter.emit (events.js:169:7)\n  at AccountStore.trigger (/usr/share/nylas/resources/app.asar/src/flux/modules/reflux-coffee.js:209:30)\n  at AccountStore.onSelectAccountId (/usr/share/nylas/resources/app.asar/src/flux/stores/account-store.js:183:19)\n  at AccountStore.onSelectAccountId (/usr/share/nylas/resources/app.asar/src/flux/stores/account-store.js:18:17)\n  at AccountStore.addAccountFromJSON (/usr/share/nylas/resources/app.asar/src/flux/stores/account-store.js:220:19)\n  at AccountStore.addAccountFromJSON (/usr/share/nylas/resources/app.asar/src/flux/stores/account-store.js:18:17)\n  at PageRouterStore._onAccountJSONReceived (/usr/share/nylas/resources/app.asar/internal_packages/onboarding/lib/page-router-store.js:67:20)\n  at PageRouterStore._onAccountJSONReceived (/usr/share/nylas/resources/app.asar/internal_packages/onboarding/lib/page-router-store.js:12:17)\n  at EventEmitter.eventHandler (/usr/share/nylas/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)\n  at EventEmitter.emit (/usr/share/nylas/resources/app.asar/node_modules/reflux/node_modules/eventemitter3/index.js:72:35)\n  at Function.module.exports.trigger (/usr/share/nylas/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)\n  at Object.functor [as accountJSONReceived] (/usr/share/nylas/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)\n  at AccountSettingsPage._onAccountReceived (/usr/share/nylas/resources/app.asar/internal_packages/onboarding/lib/account-settings-page.js:405:34)\n  at Object.success (/usr/share/nylas/resources/app.asar/internal_packages/onboarding/lib/account-settings-page.js:18:17)\n  at /usr/share/nylas/resources/app.asar/src/flux/edgehill-api.js:112:32\n  at tryCatcher (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/util.js:26:23)\n  at Promise._settlePromiseFromHandler (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/promise.js:507:31)\n  at Promise._settlePromiseAt (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/promise.js:581:18)\n  at Promise._settlePromiseAtPostResolution (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/promise.js:245:10)\n  at Async._drainQueue (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/async.js:128:12)\n  at Async._drainQueues (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/async.js:133:10)\n  at MutationObserver.Async.drainQueues (/usr/share/nylas/resources/app.asar/node_modules/bluebird/js/main/async.js:15:14)\n  at process._tickCallback (node.js:365:9)\n","message":"nylasEnv is not defined"}}
{"host":"xxx","timestamp":"2015-11-26T14:14:48.177Z","payload":{"stack":"ReferenceError: nylasEnv is not defined\n  at ErrorReporter.module.exports.ErrorReporter.getVersion (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:98:69)\n  at ErrorReporter.module.exports.ErrorReporter.reportError (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:89:25)\n  at ErrorReporter.module.exports.ErrorReporter.onDidThrowError (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:52:10)\n  at ErrorLogger.<anonymous> (/usr/share/nylas/resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:32:19)\n  at ErrorLogger.module.exports.ErrorLogger.notifyExtensions (/usr/share/nylas/resources/app.asar/src/error-logger.js:163:26)\n  at /usr/share/nylas/resources/app.asar/src/error-logger.js:182:14\n  at Emitter.module.exports.Emitter.emit (/usr/share/nylas/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)\n  at Atom.module.exports.Atom.emitError (/usr/share/nylas/resources/app.asar/src/atom.js:357:27)\n  at AccountSettingsPage._onAccountReceived (/usr/share/nylas/resources/app.asar/internal_packages/onboarding/lib/account-settings-page.js:408:14)\n  at Object.success (/usr/share/nylas/resources/app.asar/internal_packages/onboarding/lib/account-settings-page.js:18:17)\n  at /usr/share/nylas/resources/app.asar/src/flux/edgehill-api.js:112:32\n  at process._tickCallback (node.js:365:9)\nFrom previous event:\n  at Request._callback (/usr/share/nylas/resources/app.asar/src/flux/edgehill-api.js:102:47)\n  at Request.self.callback (/usr/share/nylas/resources/app.asar/node_modules/request/request.js:198:22)\n  at emitTwo (events.js:87:13)\n  at Request.emit (events.js:172:7)\n  at Request.<anonymous> (/usr/share/nylas/resources/app.asar/node_modules/request/request.js:1035:10)\n  at emitOne (events.js:82:20)\n  at Request.emit (events.js:169:7)\n  at IncomingMessage.<anonymous> (/usr/share/nylas/resources/app.asar/node_modules/request/request.js:962:12)\n  at emitNone (events.js:72:20)\n  at IncomingMessage.emit (events.js:166:7)\n  at endReadableNT (_stream_readable.js:889:12)\n  at doNTCallback2 (node.js:438:9)\n  at process._tickCallback (node.js:352:17)","message":"nylasEnv is not defined","__stackCleaned__":true}}

**Comment by soyuka** [comment]
Temporary fix :

```
sudo echo 'export NYLAS_HOME=/usr/share/nylas' >> /etc/environment
# logout/login back and there you go
```

**Comment by mbilker** [comment]
You sure you have 0.3.25? This issue was fixed in d759f6039b68f9cb2f1b8fbabe62635b579505fc, which made it into the 0.3.25 release.

**Comment by mbilker** [comment]
@ChristopheLux that is a different issue. Your error is:
```
ReferenceError: nylasEnv is not defined
 at AnalyticsStore.identify (/usr/share/nylas/resources/app.asar/internal_packages/nylas-private-analytics/lib/analytics-store.js:165:30)
 at AnalyticsStore. (/usr/share/nylas/resources/app.asar/internal_packages/nylas-private-analytics/lib/analytics-store.js:91:24
```

**Comment by mbilker** [comment]
@ChristopheLux unfortunately that is a private class and is not included in the open source version.

**Comment by jstejada** [comment]
hey guys, as @mbilker that was fixed with the latest release. Let me know if the problem persists in 0.3.25

**Comment by tudor07** [comment]
Same here on Ubuntu 15.04

**Comment by ChristopheLux** [comment]
@mbilker I don't know but i have downloaded the N1 client from the website and I am trying to connect to an Exchange Account (adding account in infinite loop never ending...that was mas issue as reported on issue  #132

**Comment by ChristopheLux** [comment]
In fact even with this error after restarting Nylas it is working...so the first sync was very very long....maybe good idea to have a kind of indicators of progress in the first sync

**Comment by mbilker** [comment]
@ChristopheLux click on the `Syncing...` text box and it should expand to show you individual numbers and progress bars for each part of the initial download.

**Comment by mbilker** [comment]
It appears `0.3.25` is not available for download. Sorry for doubting everyone.

**Comment by fontismd** [comment]
I've got the same problem on Elementary Freya (based on Ubuntu 14.04 LTS)
Just stuck on splash. Downloaded .deb yesterday.

**Comment by mbilker** [comment]
@fontismd unfortunately the deb for `0.3.25` is still not-accessible from Nylas' download link.

**Comment by alex-bender** [comment]
I have the same error as @tswestendorp has
```
$ NYLAS_HOME=/usr/share/nylas /usr/share/nylas/nylas                                                                                                                      
Streaming log data to /tmp/Nylas-N1-31058.log
App load time: 387ms
(electron) terminate is deprecated. Use quit instead.
```

**Comment by fontismd** [comment]
@mbilker any news as to when the .deb will be updated? Or any PPA added insteaD? 
Thank you !

**Comment by mbilker** [comment]
@fontismd They apparently have an APT repository, but the package isn't updated.

**Comment by El-Pingudo** [comment]
Same here running Elementary OS Freya (based on Ubuntu 14.04 LTS) . Can anyone advise how to remove Nylas using the command line? I am new to this. I will wait until a new version is released

**Comment by jstejada** [comment]
hey everyone -- this was indeed fixed in 0.3.25 but we had some issues building our .deb package. We've updated our apt repository and the download link with the latest build, 0.3.26, and you should be able to auto update to that version as well.
 let me know if you anyone keeps having this issue after updating, thanks!

**Comment by as-com** [comment]
@jstejada I'm getting a size mismatch error when trying to update through APT.

**Comment by mbilker** [comment]
I am spinning up a Debian Jessie VM to test this.

**Comment by mbilker** [comment]
@as-com hmm. Just checked now. It seems alright at http://apt.nylas.com/debian/pool/main/n/nylas/new-n1-deb.deb and the SHA256 hash matches the Packages manifest for `amd64` (`/var/lib/apt/lists/apt.nylas.com_...`).

**Comment by as-com** [comment]
I tried with Trusty. Perhaps it could have been a temporary caching issue.

I ended up just installing the deb manually.

**Comment by mbilker** [comment]
Possibly. Run `apt-get update` and then try installing.

**Comment by tswestendorp** [comment]
Size mismatch issue here too..

```# apt-get update -qq --fix-missing && apt-get -u --fix-missing dist-upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-image-3.13.0-67-generic linux-image-extra-3.13.0-67-generic
  linux-signed-image-3.13.0-67-generic
Use 'apt-get autoremove' to remove them.
The following packages will be upgraded:
  nylas
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 73,4 MB of archives.
After this operation, 2916 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://apt.nylas.com/ubuntu/ trusty/main nylas amd64 0.3.26 [73,4 MB]
Fetched 69,9 MB in 17s (4027 kB/s)                                             
E: Failed to fetch http://apt.nylas.com/ubuntu/pool/main/n/nylas/new-n1-deb.deb  Size mismatch```

**Comment by mbilker** [comment]
Must be the Ubuntu one is truncated

**Comment by jstejada** [comment]
cc @spang , also related to #522
