### ISSUE TITLE
Error while running script/bootstrap on Linux

### ISSUE THREAD

**Issue by YugalXD** [nylas/N1#493]
Node: v5.0.0
npm: v3.3.10

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/opt/N1/.npmrc" install --loglevel error --cwd=/opt/N1/build --ignoreStdout=true 

---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ "/opt/N1/build/node_modules/.bin/npm" --userconfig="/opt/N1/.npmrc" --target=0.10.40 install --loglevel error --cwd=/opt/N1/apm --ignoreStdout=true 

---> Flattening apm package tree
     This runs `npm dedupe` on apm's `npm` dependency.
     We use this to prevent paths over 260 characters on Windows.

     $ "/opt/N1/build/node_modules/.bin/npm" --userconfig="/opt/N1/.npmrc" --target=0.10.40 dedupe --cwd=/opt/N1/apm/node_modules/npm --ignoreStderr=true --ignoreStdout=true 

---> Cleaning apm via `apm clean`

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/N1/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/opt/N1/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by mbilker** [comment]
You need `libgit2`.
Fedora/CentOS/RedHat need `libgit2-devel libgnome-keyring-devel`.
Ubuntu needs `libgit2-dev build-essential git libgnome-keyring-dev`.

**Comment by mbilker** [comment]
It does look like you have development tools installed, which is good.

**Comment by YugalXD** [comment]
how could i solve this error.

**Comment by mbilker** [comment]
@YugalXD OS?

**Comment by YugalXD** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by mbilker** [comment]
```
sudo apt-get install libgit2-dev build-essential git libgnome-keyring-dev
```

**Comment by mbilker** [comment]
@YugalXD above.

**Comment by YugalXD** [comment]
done it but same error

**Comment by mbilker** [comment]
@YugalXD Output of command? If its the `../build/Release/git.node` then installing `libgit2-dev` should have fixed it. That's weird.

**Comment by YugalXD** [comment]
yugal@yugal-tech:/opt/N1$ script/bootstrap
Node: v5.0.0
npm: v3.3.10

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm`.
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/opt/N1/.npmrc" install --loglevel error --cwd=/opt/N1/build --ignoreStdout=true 



---> Installing apm
     This installs apm via N1's `npm`
     We use this local apm copy to install all N1 dependencies & packages

     $ "/opt/N1/build/node_modules/.bin/npm" --userconfig="/opt/N1/.npmrc" --target=0.10.40 install --loglevel error --cwd=/opt/N1/apm --ignoreStdout=true 



---> Flattening apm package tree
     This runs `npm dedupe` on apm's `npm` dependency.
     We use this to prevent paths over 260 characters on Windows.

     $ "/opt/N1/build/node_modules/.bin/npm" --userconfig="/opt/N1/.npmrc" --target=0.10.40 dedupe --cwd=/opt/N1/apm/node_modules/npm --ignoreStderr=true --ignoreStdout=true 



---> Cleaning apm via `apm clean`


module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/N1/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/opt/N1/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by YugalXD** [comment]
yugal@yugal-tech:/opt/N1$ sudo apt-get install libgit2-dev build-essential git libgnome-keyring-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
libgnome-keyring-dev is already the newest version.
libgit2-dev is already the newest version.
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by mbilker** [comment]
@YugalXD try `script/clean` then run `script/bootstrap`

**Comment by YugalXD** [comment]
worked with sudo when using opt DIR
