### ISSUE TITLE
List of accounts are not updated - minor bug

### ISSUE THREAD

**Issue by dkouvdis** [nylas/N1#495]
Hi all.

When I unlinked one account. It worked nicely as expected but the list in the windows tab did not update. Obviously it get updated after restarting the app.

Minor bug but maybe its important. See attachments for reference
OSX - 0.3.25-c174641

![screen shot 2015-11-27 at 12 58 33](https://cloud.githubusercontent.com/assets/2727196/11441990/37a9cc7c-9509-11e5-9887-019d38d2a11c.png)
![screen shot 2015-11-27 at 12 58 24](https://cloud.githubusercontent.com/assets/2727196/11441992/3befc534-9509-11e5-85fc-5d6623fb3903.png)

**Comment by grinich** [comment]
This should be fixed now! Please re-open if you have steps to reproduce.
