### ISSUE TITLE
Infinite Spawn for Preferences pane/view/window

### ISSUE THREAD

**Issue by ggamel** [nylas/N1#498]
This is an easily reproducible bug, but potentially *very* nasty for users.

# Steps to reproduce:

1. Open **Nylas N1.app** on OS X
2. Press `Cmd + ,` or select `Nylas N1 > Preferences`
3. Repeat **Step 2** over and over and over (seriously, go wild with this step)
4. Notice you're *stuck* in the Preferences view until you either **A)** repeatedly click the "< Inbox" (button?)" or **B)** hit `Esc` over and over and over

## Thoughts
It's as if N1 isn't checking, while you're already viewing Preferences, to verify whether Preferences is currently open. Therefore, of course, Preferences keeps being spawned over and over and over...

**Comment by jstejada** [comment]
thanks for reporting this @ggamel , we've fixed it and pushing it on the next release
