### ISSUE TITLE
N1 overwrites Atom's Package Manager link

### ISSUE THREAD

**Issue by grinich** [nylas/N1#499]
Reported via a user: 

After installing and using the app I found that is overwriting Atom's Package Manager link on OSX (maybe Linux also):

/usr/local/bin/apm -> /Applications/Nylas N1.app/Contents/Resources/app.asar/apm/node_modules/.bin/apm

Now I can't use it to manage Atom's packages from CLI.

**Comment by mbilker** [comment]
Also #39

**Comment by grinich** [comment]
ah didn't see that one. closing as dupe of #39
