### ISSUE TITLE
Pull from Gmail labels

### ISSUE THREAD

**Issue by dmvaldman** [nylas/N1#5]
I'm not sure how email is pulled locally, but when I access a gmail label that doesn't have any activity for a while there are no emails there. I'm guessing emails are pulled temporally (within past X days) and not by count (last X emails).

**Comment by dillonforrest** [comment]
Hey there @dmvaldman, thanks for downloading N1 and thanks for logging the issue! Sorry about the problem.

We got an overwhelming amount of downloads today, and our platform team is working to resolve our sync speed issues. Your mail should appear soon! Can you check in with us again later to let us know if you see progress?

**Comment by dmvaldman** [comment]
Problem persists. I don't think this is a "your servers are melting" issue. Just to clarify:

If I go to a gmail label where the most recent email should be from a few weeks ago, I see no email in Nylas. It's not even trying to fetch it.

Gmail labels with recent activity are there, but also only restricted to recent activity. I can't go backwards indefinitely through my history. Currently seems to be that around Sept 11th is the cutoff.

**Comment by jimeh** [comment]
Similar issue here, except I generally can't see any email before mid-September. The only view that contains anything from before 17th of September is All Mail, which has one email from the 15th of September, and one from the 3rd of September. Obviously I had tons of emails between the 3rd and 17th. It looks like All Mail is showing about 200-ish of the 100k emails I have.

Most views (Inbox, and all except two labels) show no more than the 15 most recent emails. And that's only if they're from within the past month. If there's no recent things in a label it's just empty.

**Comment by jos3k4** [comment]
I have also problems with the labels in addition to the problem with past emails also I don't have the pending to read number of mails on each label

**Comment by mbilker** [comment]
Should this issue be closed?

**Comment by bengotow** [comment]
Hey folks—these issues (labels not syncing, threads not appearing) have been fixed server side in the last month. Enjoy N1!
