### ISSUE TITLE
Ubuntu 14.04 LTS, N1 wont start

### ISSUE THREAD

**Issue by Troyhy** [nylas/N1#500]
I installed deb package and tried to start app, error console appears with this error:

  index.js:21 TypeError: Path must be a string. Received undefined
      at assertPath (path.js:8:11)
      at Object.posix.join (path.js:477:5)
      at Object.exports.setHomeDirectory (/usr/share/nylas/resources/app.asar/src/compile-cache.js:24:23)
      at setupWindow (file:///usr/share/nylas/resources/app.asar/static/index.js:28:16)
      at window.onload (file:///usr/share/nylas/resources/app.asar/static/index.js:86:5)handleSetupError @    index.js:21

**Comment by vdaniuk** [comment]
Ubuntu 15.04 and getting a same error. When trying to launch nylas from the terminal I get the following error: 
`
Can't find the Electron executable at /usr/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/bin or set the ELECTRON_PATH environment variable.
`

**Comment by tudor07** [comment]
Same here on Ubuntu 15.04. If i start it normally I get:

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8)
    at Object.posix.join (path.js:477)
    at Object.exports.setHomeDirectory (/usr/share/nylas/resources/app.asar/src/compile-cache.js:24)
    at setupWindow (index.js:28)
    at window.onload (index.js:86)

If i run it from terminal it works. I have env var NYLAS_HOME configured corectly.

**Comment by jstejada** [comment]
hey guys, merging this into #492

**Comment by retorquere** [comment]
Is this really a dupe of #492? N1 can't find electron here either (also 15.10). Installing electron using `sudo npm install electron-prebuilt -g` didn't help. I'm getting either 

```
$ nylas
Can't find the Electron executable at /usr/bin/electron/electron. Be sure you have run script/bootstrap first from /usr/bin or set the ELECTRON_PATH environment variable.
```

or, when I set ELECTRON_PATH to the electron binary:

```
$ nylas
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.35.2/docs

Error: Cannot find module '/usr/bin'
```

**Comment by kaxing** [comment]
Same problem, but if you launching N1 by clicking on the Icon(.desktop) will works just fine.

If you look into /usr/share/applications/nylas.desktop it uses this binary instead: /usr/share/nylas/nylas
That should be the one you can launch N1 from terminal.
But right now `nylas` will pointed to /usr/bin/nylas , I'm not sure if this is a mistake in packaging or by purpose.

**Comment by micooz** [comment]
@kaxing +1

**Comment by AhmedKamal20** [comment]
This worked for me : 
`sudo mv /usr/bin/nylas /usr/bin/nylas.old`
`sudo ln -s /usr/share/nylas/nylas /usr/bin/nylas`

**Comment by johnynsk** [comment]
+1, I have same problem
