### ISSUE TITLE
Auto Updater not present on Linux

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#503]
I noticed that there are many Linux issues present on Github, but I know many of them are fixed in recent versions of N1. Is it possible to re-work the Auto Update engine to check if the Linux version is current?

**Comment by mbilker** [comment]
Also, would it be possible to add a button to the `Help` menu to copy a standard set of information to make Github issues easier to diagnose?

**Comment by bengotow** [comment]
Hey @mbilker — we can definitely a Help menu in there. Unfortunately, on Linux we distribute updates via our own `apt-get` server at `apt.nylas.com`. I think we may just need to push the latest update to it.

**Comment by mbilker** [comment]
@bengotow Please tell the people at #492. They are very confused since the issue is fixed in `0.3.25`, but that release is not available on the N1 website. I didn't know there was a APT repository.

**Comment by jstejada** [comment]
hey @mbilker thanks for keeping up with this. I'm closing this now, I posted an update at #492 . Everything should be up to date now

**Comment by mbilker** [comment]
Thanks @jstejada ! I saw the update at #492 and it should make a lot of people happy.
