### ISSUE TITLE
Remembering Two Panel widths

### ISSUE THREAD

**Issue by mataal** [nylas/N1#504]
I use the two-panel mode, however, I adjust the ratio of width across the list and preview (I prefer the preview to be maximised). Easy to fix via click and drag. 

However, N1 forgets this the next time open the app. Any way to save this as an implicit preference across re-opens?

Version- Version 0.3.25-c174641 (0.3.25-c174641)
MacbookPro on OS X v10.11.1

**Comment by peeinears** [comment]
+1

**Comment by jamielovelace** [comment]
this would be pretty sweet +1

**Comment by jgerigmeyer** [comment]
+1

**Comment by grinich** [comment]
Hi @mataal -- i believe this is fixed in the latest version!

**Comment by tborychowski** [comment]
I'm on v0.3.32-b11131d (Ubuntu) and this is not fixed.

**Comment by jstejada** [comment]
merging into #833

**Comment by mataal** [comment]
It's fixed in Version 0.3.43-b95f1f7 (0.3.43-b95f1f7) on OS X

Thanks @grinich and team!
