### ISSUE TITLE
Feature Request: Print emails

### ISSUE THREAD

**Issue by g105b** [nylas/N1#508]
I need to print an email. Here is where I've looked for the option to print:

+ Right click the message (available options: Copy / Search Google for {text under cursor})
+ Right click message in inbox list (no options)
+ Buttons at top of message (Archive, Delete, Mark as unread, Star, Label, Show sidebar, Reply/Forward)
+ File menu _where I would expect to see a print option_ (New message, preferences, add account, close window, quit) _aren't close and quit the same?_
+ Edit menu (Undo, redo, cut, copy, paste, select all)
+ View (Toggle full screen, toggle menu bar _aha, maybe the print button is in the menu bar and it's hidden.......... nope toggling the menu bar has no noticeable effect... what is this menu bar that I'm supposedly toggling?)
+ Developer (loads of developer-specific options)
+ Help (version 0.3.20-6bbe930, Send feedback)

The version of N1 I'm using is installed from the standard DEB package, and I updated my system before submitting this request. I'm running Ubuntu 15.10 64 bit.

**Comment by jstejada** [comment]
hey @g105b , we're working on this and should be ready for our next release

**Comment by jstejada** [comment]
hey @g105b , this feature has been added and will be available in the upcoming release
