### ISSUE TITLE
Delete functionality for Gmail

### ISSUE THREAD

**Issue by ckluis** [nylas/N1#51]
The functionality for the gmail accounts is a little different than what I am used to with Exchange/Outlook.  When I click delete on an email -> it looks like it moves them from one folder to trash.  If I click delete on trash to clean it up -> it moves it back into the all mail section.

Deleting something from the inbox does not eliminate it from the all mail folder and vice versa.  

It feels like the delete key interaction pattern is broken.

**Comment by mbilker** [comment]
I second this, I would like to be able both delete and archive mail.

**Comment by jdsimcoe** [comment]
:+1:

**Comment by emorikawa** [comment]
This is in development now and almost done. Will update this thread when it lands!

**Comment by equinusocio** [comment]
:+1:

**Comment by jdsimcoe** [comment]
Trash doesn't seem to be working at all for me anymore.

**Comment by mbilker** [comment]
@jdsimcoe still works for me. It just relabels the emails to be put in the trash.

**Comment by jdsimcoe** [comment]
@mbilker I just can't see them anywhere from the interface. Where can I find them?

**Comment by mbilker** [comment]
@jdsimcoe I have been dragging emails into the trash label on the left pane in the main view.

**Comment by waynew** [comment]
If you have gmail keyboard shortcuts, <kbd>y</kbd> archives and <kbd>#</kbd> deletes (has the same effect of dragging the email over to the trash).

This is a missing feature for me, too.

**Comment by bengotow** [comment]
Hi folks—we now support "Trash" as well as "Archive" for Gmail accounts (as of 0.3.18) and 37e3fe0f4533ee5139cf0c27ee8cf9a008bc4ffe adds support for `y` (archive) and `#` (delete). Enjoy!
