### ISSUE TITLE
Colors of label not same

### ISSUE THREAD

**Issue by Alexey-Panov** [nylas/N1#510]
In GMAIL i used colors for labels, but in N1 it's not same. Looks like N1 use random or something else. It's annoying a little.

**Comment by bengotow** [comment]
hI @Alexey-Panov — unfortunately, Gmail doesn't share the color of labels via their API or the IMAP interface, and they allow you to change it so it's not an algorithm we can duplicate. If this changes, I'll let you know!

**Comment by lode** [comment]
Maybe http://stackoverflow.com/questions/9199716/gmail-label-colors-via-api can help?
