### ISSUE TITLE
First load fails on arch linux (installed deb manually), presents TypeError and Chrome Dev Console

### ISSUE THREAD

**Issue by noderat** [nylas/N1#512]
First time load on linux, manually installed deb, received chrome dev console with TypeError.

![Screenshot](http://i.imgur.com/1920HrU.png)

**Comment by spetz83** [comment]
I am getting the same error on Linux Mint 17.3 Cinnamon 64-bit

**Comment by jstejada** [comment]
hey guys, I'm merging into duplicate #492
