### ISSUE TITLE
Feature request: Paste as plain text (no formatting) - CMD+Shift+V

### ISSUE THREAD

**Issue by elado** [nylas/N1#515]
As you can do in Evernote and other Mac apps, CMD+Shift+V pastes text as complete plain text with no formatting at all.

**Comment by bengotow** [comment]
Hey! This is a great idea and should be easy for us to implement. I'll see if we can get it in to a future update.

**Comment by aneeshjajodia** [comment]
+1

**Comment by bengotow** [comment]
This has been fixed in 0.3.29. Enjoy!

**Comment by elado** [comment]
@bengotow CMD+Shift+V isn't working anymore on latest version (Version 0.4.47-3a2a94c (0.4.47-3a2a94c))
