### ISSUE TITLE
"Show badge on the app icon" toggle is broken

### ISSUE THREAD

**Issue by evanemolo** [nylas/N1#516]
The unread count badge appears on both dock and cmd-tab icon despite having the option unchecked. I am using version 0.3.25-c174641 (0.3.25-c174641) on Mac OS X El Capitan 10.11.1 (15B42).

I should note I do not have this issue with when I run N1 on Yosemite using another Mac.

**Comment by bengotow** [comment]
Hey @evanemolo — thanks for filing this. I've been able to reproduce and I'll see if we can get a fix in soon.

**Comment by evanemolo** [comment]
Hey @bengotow, I'm actually still having this issue (I am running Version 0.3.26-c1ce330 on Mac OS X El Capitan 10.11.1)
