### ISSUE TITLE
Settings for default download folder

### ISSUE THREAD

**Issue by uncleserb** [nylas/N1#517]
In the current version of N1, 0.3.26-c1ce330 (0.3.26-c1ce330), downloading an email attachment always prompts the `Save as` dialog to be positioned in the `User/Downloads` folder (on OS X).
It could be interesting to provide a user preference setting (possibly in `General` > `Attachments`) that would allow users to specify their preferred default download folder.

Thanks!

**Comment by egeogretmen** [comment]
This may be even better if it shows the last folder selected for download. Let's say attachments of an email should be in /folder1, then when the first attachment is downloaded to that folder, when I want to download the second attachment it may be useful to show /folder1 as the download folder

**Comment by markbao** [comment]
+1 for last folder selected for download per @egeogretmen. I'm downloading attachments from an email with 6 attachments and I have to navigate to the correct folder every time - bit frustrating!

**Comment by bengotow** [comment]
Hey folks! In 0.4.14, we made the "save attachment" dialog remember the last directory you saved into. I think this will largely resolve this issue and avoids adding another setting. Going to go ahead and close this - let us know if you have ideas for a better solution. Really trying to prevent Preferences from becoming a mess!

**Comment by uncleserb** [comment]
Sounds like a good compromise! Thanks @bengotow :)
