### ISSUE TITLE
Feature request: Define default archive folder/add 'archive' button for IMAP accounts

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#518]
I am using N1 with two IMAP accounts. Currently I cannot archive an e-mail with one click or shortcut, since N1 doesn’t know where to archive it to, I assume. I only have a move-to-folder button at the top. 
It would be great, as other clients do, to have the option to define default folders for the usual things like archive/trash/junk/sent and translate it to their usual names in the interface (Sent and Trash do show up in my top menu under 'Mailboxes', Junk as one of the folders; all three show up with an INBOX.* prefix derived from their IMAP names, i.e. 'Sent', 'Trash', 'Spam' and 'Archive'/'All Mail' would be great as labels for it).

**Comment by bengotow** [comment]
Hi @enoversum — thanks for reporting this. I think that this is related to #66. With Fastmail and some other providers, we don't properly assign folders to their canonical roles ("Archive", etc.) We should definitely add an option to choose an Archive folder, but the current version of our sync-engine /should/ assign any folder named "Archive" the `archive` role.

Could you do me a favor and open the Developer Tools in the app, and send me the output from running this command?

`JSON.stringify(require('nylas-exports').CategoryStore._categoryCache)`

That will print out all of the folders, with their display names (visible in the interface) and their canonical "names", which are used to determine whether they serve as your inbox, archive, etc. That'll help me report this to our sync engine team.

**Comment by enoversum** [comment]
Hey @bengotow , thanks for getting back on this one as well <3!
Yes, all folders show up like this (the INBOX.Sent folder is showing the right icon, being in the right place, same as [INBOX.]Trash). I named my Archive folder Archived, since my current e-mail client did require to have it named like this. So once I would rename it to Archive it should be recognised? Here you go, though I could possibly name those folders for you easily. Apart from the standard folders, I named some of them myself, as for the archive folder to fit into my current client, but they all start with INBOX.

`"{"enjsdk9nzz49xsat3zjyrnqft":{"client_id":"local-45630a82-22f3","server_id":"enjsdk9nzz49xsat3zjyrnqft","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"","display_name":"INBOX.Archived","id":"enjsdk9nzz49xsat3zjyrnqft"},"35drjbryu7kxqy7wsunp38c8s":{"client_id":"local-794e7d21-eb8d","server_id":"35drjbryu7kxqy7wsunp38c8s","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"","display_name":"INBOX.Archived.Kram","id":"35drjbryu7kxqy7wsunp38c8s"},"d4qh58aee5jmopognm6fyaxnf":{"client_id":"local-e7020fa9-302c","server_id":"d4qh58aee5jmopognm6fyaxnf","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"","display_name":"INBOX.Archived.Newsletter","id":"d4qh58aee5jmopognm6fyaxnf"},"82valwubwy7w8d0m9dpf8fdn0":{"client_id":"local-187b64f3-d926","server_id":"82valwubwy7w8d0m9dpf8fdn0","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"","display_name":"INBOX.Archived.Social","id":"82valwubwy7w8d0m9dpf8fdn0"},"3mmgwtpd6smu86kzx424ba05e":{"client_id":"local-ce19a07b-cf8d","server_id":"3mmgwtpd6smu86kzx424ba05e","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"","display_name":"INBOX.Important","id":"3mmgwtpd6smu86kzx424ba05e"},"b2f66y37q9bdigrm0hixvr3yu":{"client_id":"local-104fb340-89fc","server_id":"b2f66y37q9bdigrm0hixvr3yu","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"","display_name":"INBOX.Junk","id":"b2f66y37q9bdigrm0hixvr3yu"},"5sk82xecazreuevsx7vsllu4o":{"client_id":"local-da8ee1d5-83a6","server_id":"5sk82xecazreuevsx7vsllu4o","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"drafts","display_name":"INBOX.Drafts","id":"5sk82xecazreuevsx7vsllu4o"},"2014ffd5vw39ppi9wc2atl2e3":{"client_id":"local-bc739308-9148","server_id":"2014ffd5vw39ppi9wc2atl2e3","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"inbox","display_name":"INBOX","id":"2014ffd5vw39ppi9wc2atl2e3"},"3g2u3e69n5n5kqfejwa6k1yum":{"client_id":"local-edfc6242-85d5","server_id":"3g2u3e69n5n5kqfejwa6k1yum","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"sent","display_name":"INBOX.Sent","id":"3g2u3e69n5n5kqfejwa6k1yum"},"41kqnngx0h4c3mkfzcnpoxc8t":{"client_id":"local-63988146-cb7a","server_id":"41kqnngx0h4c3mkfzcnpoxc8t","object":"folder","account_id":"b0dxbpy18zfux2x9izsbi1m1e","name":"trash","display_name":"INBOX.Trash","id":"41kqnngx0h4c3mkfzcnpoxc8t"}}"`

**Comment by spang** [comment]
@enoversum Yup, I think it should work if you rename your Archived folder to Archive to use it with N1. Let us know if that doesn't work.

**Comment by enoversum** [comment]
@spang Of course, that works well. And since the 'other' client now finally allows for its archive to be named in a standard manner, I already renamed my archive folder and moved the sub-folders accordingly. Otherwise I would still struggle with it :wink: .
Still, folders still show in their IMAP manner in the interface, and thus easily get clipped in the sidebar. In the upper part where the standard folders reside, it says 'INBOX.Sent', 'INBOX.Archive' and 'INBOX.Trash', below at the additional folders it is like 'INBOX.Archive.Newsletter' which is really long and ugly. Also, 'INBOX.Junk', what I would assume amongst the standard folders, is down there. Any news on a fix for folder display for IMAP users (had been addressed some weeks ago already)?

**Comment by grinich** [comment]
@enoversum are you still seeing this? I believe we fixe the folder prefix issue.

**Comment by enoversum** [comment]
@grinich How can I see if it is resolved for accounts in N1? The client sticks to its known folder structure, so everything is still INBOX.Sent, INBOX.Archive.Subfolder.

What I observed as well is that N1 even sticks to some of its folders when folders on the server changed, possibly a local cache problem?, and ignores the folders being added/renamed after the account had been added to N1. 
Example: I changed my Archive folders name on the server (from **Archived** to the standard **Archive**) in mid December, and all sub-folders should then be Archive/Subfolder1, Archive/Subfolder2 and the likes. However, on one of my machines he still shows my old INBOX.Archive**d**.Subfolder3 instead of the new INBOX.Archive.Subfolder3, and of course only shows the mail that arrived until I renamed the folder back in December. I tried to remove and re-add the account, but it seems N1 still reads from a local cache, since all mail is there in an instant after re-adding the account.

**Comment by tartley** [comment]
A keymap for this action would be brilliant!

I'd like to use N1 using keyboard only, but currently I have to reach over to my mouse on average about every single second, literally, and the lack of this feature (and a keymap for it.) is the primary culprit.

Hugs hugs!

**Comment by jackiehluo** [comment]
Merging into #1457!
