### ISSUE TITLE
Mac OS X - Yosemite - App crash when sending email

### ISSUE THREAD

**Issue by stoge** [nylas/N1#519]
Hi,
I been experiencing occasional app crashes when I am trying to sent an email.
The app freezes and after a sec or two I get this "App crashed, reopen" window.
I'll attach a pic when available.

Thank you, for your awesome work!

**Comment by jstejada** [comment]
hi @stoge thanks for reporting this. Could you send us the logs from Console.app?

**Comment by stoge** [comment]
Hi again,

I've downloaded the newest version of N1 since my last post here.
I had the same issue,
Here is the output that appears in the "reopen" window -> http://pastebin.com/dnPwDG24
I am not sure if this is what you need, I don't know how to find the Console.app logs..I'll google it
Thank you again!

G.

**Comment by stoge** [comment]
Ok, I found the crash file

[Nylas_2015-12-02-141738_MacBook-Pro.crash.txt](https://github.com/nylas/N1/files/49708/Nylas_2015-12-02-141738_MacBook-Pro.crash.txt)

**Comment by bengotow** [comment]
Hi @stoge — thanks for the crash report, this is perfect. It looks like closing the window is triggering a computation of it's draggable regions, but after it's been closed. I'll file a ticket with Electron and see if we can get this fixed.

**Comment by stoge** [comment]
Glad I could help :D

**Comment by jstejada** [comment]
possibly related to #773

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.

**Comment by carpenterMD** [comment]
I'm having the same issue. It seems to only occur when I create a new draft. If I'm responding to an email it works just fine.
