### ISSUE TITLE
Linux: Fail to updade to latest version

### ISSUE THREAD

**Issue by alexandru-calinoiu** [nylas/N1#522]
Trying to update to latest version using apt or aptitude on ubuntu will show the following error:

```
E: Failed to fetch http://apt.nylas.com/ubuntu/pool/main/n/nylas/new-n1-deb.deb: Size mismatch
```

**Comment by Birssan** [comment]
Same here

**Comment by ginesr** [comment]
Same problem, Ubuntu 14.04 LTS

**Comment by link-webcreations** [comment]
Same here, 14.04 LTS

**Comment by vpakg** [comment]
I'm having the same problem, also 14.04 LTS. 
`Authentication failed`

**Comment by vpakg** [comment]
Just an update, update from the deb package and it should work. https://invite.nylas.com/download/

**Comment by jstejada** [comment]
have you tried running `apt-get-update` first?

**Comment by vpakg** [comment]
@jstejada speaking for myself, ran upt-get update, apt-get install --fix-missing (as suggested by terminal), tried running autoclean / autoremove...nothing solved the problem. However when upgrading from the dev package it was successful.

**Comment by spang** [comment]
We can reproduce this on our end. Hang tight, we'll get back with an update soon.

**Comment by spang** [comment]
We've resolved the issue. Please run `apt-get update` and try again. Thanks!
