### ISSUE TITLE
Hotmail not synching mails

### ISSUE THREAD

**Issue by nicoseb** [nylas/N1#523]
Hi,

When I first installed N1, I added my gmail account, no problems.
Then I added my hotmail account, which resulted in me getting an alert on my hotmail box that I had some weird activity going on (see this thread https://github.com/nylas/N1/issues/193).
I cleared the activity on my hotmail account, unlinked the account in N1 because that was not doing anything, but now when I link my hotmail account, there are no emails to be displayed, nothing get synchd excepted for my folders (empty though)...

Is there something special to do to fix this, or is there a way to really purge some local temp files related to my hotmail account so that when I link it again it really restarts the process from scratch or something?

Thank you,
Nick

**Comment by spang** [comment]
Hi @nicoseb,

In order to look into this, we'll need some more details about your account. Are you able to email support@nylas.com with the email address of the account in question which is having problems?

**Comment by nicoseb** [comment]
Hi @spang,

No worries, it works all of a sudden after a couple of weeks! haha.
My guess is that it took that long to download 10 years of emails... ;)

My exchange server account - work one - failed to sync after Hotmail worked, but deleting the account and reloading it fixed the issue!

Thank you

**Comment by spang** [comment]
Sweet! Glad to hear it!
