### ISSUE TITLE
Sorry, we could not reach the Nylas API at launch

### ISSUE THREAD

**Issue by aneeshjajodia** [nylas/N1#526]
I'm facing issues with opening the app on Mac.

Would be glad if someone can help me through this.

<img width="388" alt="screenshot 2015-12-01 21 40 57" src="https://cloud.githubusercontent.com/assets/1062704/11506233/5e620776-9874-11e5-8ddd-4a1c7d1fe2b0.png">

**Comment by Bugsbane** [comment]
I'm getting the same thing on Ubuntu 15.10. The log file only shows:
````
{"host":"MYHOSTNAME","timestamp":"2015-12-01T16:48:40.003Z","payload":["ActionBridge: onboarding Action Bridge Broadcasting: willMakeAPIRequest"]}
{"host":"MYHOSTNAME","timestamp":"2015-12-01T16:48:50.537Z","payload":["ActionBridge: onboarding Action Bridge Broadcasting: didMakeAPIRequest"]}
{"host":"MYHOSTNAME","timestamp":"2015-12-01T16:48:57.332Z","payload":["ActionBridge: onboarding Action Bridge Broadcasting: willMakeAPIRequest"]}
{"host":"MYHOSTNAME","timestamp":"2015-12-01T16:49:07.373Z","payload":["ActionBridge: onboarding Action Bridge Broadcasting: didMakeAPIRequest"]}
````

Obviously, I've replaced my host name.

**Comment by bengotow** [comment]
Hey folks—this message appears when N1 is unable to reach `https://invite.nylas.com/status` (to determine whether the invite system is in place—it's currently not.) Maybe you have a proxy or firewall in place?

**Comment by Bugsbane** [comment]
No proxy or firewall here. If I try to go to https://invite.nylas.com/status from my browser, I just get a page that says nothing but:

{
  "restricted": false
}

**Comment by bengotow** [comment]
Hey @Bugsbane — that's the correct response (the invite system is currently disabled, we just keep it in place in case we ever need it).

**Comment by Bugsbane** [comment]
So.... if that's the correct response then what's the problem? What info is needed to figure out why Nylas won't open?

**Comment by grinich** [comment]
None of us can repro this issue. @Bugsbane can you post a video or animated gif?

**Comment by Bugsbane** [comment]
It seems that it went away for me without me doing anything. I haven't updated Nylas or anything, but now Nylas opens fine. @aneeshjajodia , are you still getting it?

**Comment by octoxan** [comment]
Currently having the same issue...
