### ISSUE TITLE
Feature Request: Expose sync engine URI as runtime config item

### ISSUE THREAD

**Issue by tisjames** [nylas/N1#528]
Apologies if I've phrased this badly. I have the sync engine running on a server and consequently have built the N1 client as per the section "Running Against Open Source Sync Engine" in https://github.com/nylas/N1/blob/master/CONTRIBUTING.md . Building the client was necessitated by 
the need to point to the remote URI for my sync engine instance in nylas-api.coffee.

If this is a relatively common use-case, could the configuration required to point the N1 client to a sync engine instance be exposed through a config file loaded at runtime by the binary distributed (so, we'd get the full benefit  of what's described in "What is bundled in the N1 download, but not the GitHub repo?" and convenient client updates)

**Comment by mbilker** [comment]
From what I know only an Analytics engine.

**Comment by tisjames** [comment]
@mbilker Could you clarify what you mean?

**Comment by mbilker** [comment]
@tisjames https://github.com/nylas/N1/issues/492#issuecomment-160188519, which is actually my parsed version of https://github.com/nylas/N1/issues/492#issuecomment-160136365

**Comment by mbilker** [comment]
For the actual issue/request at hand, the `config.cson` file is in the `$HOME/.nylas` directory.

The directory is defined as `process.env.NYLAS_HOME` in `src/browser/main.coffee`.

**Comment by bengotow** [comment]
Hey! Closing this because I think we've addressed this with a new config option called `APIRoot`:

Replace env: "production" with env: "local" at the top level of the config. This tells N1 to look at localhost:5555 for the sync engine. If you've deployed the sync engine elsewhere, add the following block beneath env: "local":
```
syncEngine:
 APIRoot: http://mysite.com:5555
```

**Comment by mbilker** [comment]
@bengotow The correct `env` value is `custom` from https://github.com/nylas/N1/blame/9ef84e476a714ea9bf7071f9d80717f911884ae8/src/flux/nylas-api.coffee#L161-L163
