### ISSUE TITLE
N1 consumes 0.8-1.0% of CPU when idling

### ISSUE THREAD

**Issue by zdrummond** [nylas/N1#530]
![n1_energy_use](https://cloud.githubusercontent.com/assets/1627527/11508954/31e99286-9810-11e5-8344-524a38c24ce2.png)

Running on MacBook Pro (Retina, 15-inch, Late 2013), 16GB RAM
OSX 10.11.1

The App bursts up to 45% CPU, overall it eats a ton of Energy, which kicks in the fans and drains batteries. Until this is addressed, it is unusable to me.

**Comment by bengotow** [comment]
Hey @zdrummond — thanks for reporting this. Does N1 say "Syncing your mailbox..." in the bottom left? During initial sync, we download tons of mail data and it's unfortunately a CPU-intensive process. 

When the app is idling (finished syncing, just waiting for new mail), it definitely shouldn't consume this much energy.

**Comment by zdrummond** [comment]
It does say Syncing, I will let finish and see what it looks like.

That said, I still think sync-ing should be less impactful... ;)

**Comment by zdrummond** [comment]
Ok, it is better, but still registers as an App Using Significant Energy (my only app doing so)

![power_usage](https://cloud.githubusercontent.com/assets/1627527/11516052/0ba72072-9836-11e5-81a9-ce4d8e7a670c.png)

It has an average Energy Impact of 2.4, with spikes of 6. CPU of ~0.8-1.0% constant. Apple Mail and Outlook use 0% when idle.

**Comment by bengotow** [comment]
Hey @zdrummond — thanks for the response. 0.8-1% of CPU is still significant, but that's currently the baseline (same here for me.) I'm not actually sure what the app is doing—we need to do some Chromium profiling. We hold a connection open to the Nylas API, but I don't think that'd do that much damage.

I'm going to rename this and we'll leave it open until CPU usage in the idle state is improved.

**Comment by zdrummond** [comment]
👍

**Comment by wizonesolutions** [comment]
Same here; it's an app using significant energy, and I can feel it. Roughly 30 mins of usage (one Chrome tab plus Nylas in background) drained me from 93% to 76%. Worth mentioning that it didn't even jump over to discrete graphics, which is the usual cause. Happily sucking up battery on integrated.

**Comment by prakashwagle** [comment]
I am also facing same issue with my Mac book Pro. N1 is draining my battery had to switch back to Mail in OS X.

**Comment by jackiehluo** [comment]
Electron's made some speed improvements—let us know if you're still having this issue!
