### ISSUE TITLE
False Label number

### ISSUE THREAD

**Issue by csimonmoi** [nylas/N1#531]
I have a number "2" beside my Inbox email (Gmail) as if I had 2 new emails. THERE ARE NO new emails in the inbox, neither in Nylas app, nor in Gmail web application.
I uninstall and install it again, but nothing changed.

**Comment by joshvickerson** [comment]
I am also experiencing this issue. I have no emails in my inbox, but there is a 2 label next to inbox as if I have 2 new emails. Confirmed that my inbox is empty in the Gmail web client. Attached screenshot for reference:

![screen shot 2015-12-01 at 4 41 56 pm](https://cloud.githubusercontent.com/assets/2325487/11515430/dc1686d4-984b-11e5-8eb9-daa9e4e4bcf3.png)

It may be worth noting that this is a Google Apps account, not a regular Gmail account. Not sure how much of a difference that makes.

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this—it looks like there are some issues with new optimizations we added to avoid recalculating label counts constantly. I'm going to go ahead and merge this with #489
