### ISSUE TITLE
Missing Gmail Keyboard Shortcuts

### ISSUE THREAD

**Issue by nathanperetic** [nylas/N1#533]
It would be awesome if N1 could support the full set of [Gmail keyboard shortcuts](https://support.google.com/mail/answer/6594?hl=en) out of the box. In particular, I’m partial to 'gl' to jump between labels. See below image.

<img width="244" alt="screenshot 2015-12-01 15 18 05" src="https://cloud.githubusercontent.com/assets/944668/11512955/bf7dd7a0-983e-11e5-800a-853fc103cdbb.png">

**Comment by bengotow** [comment]
These actually work if you enable the "Gmail" shortcut set in preferences. (excluding Tasks and Label, I believe.) Make sure you're running the latest version of N1 (0.3.26)—I think they were added in 0.3.25. Feel free to re-open if it doesn't work!

We'll be adding these to the shortcut list in the preferences panel so they're more discoverable.
