### ISSUE TITLE
Add menu items for all email actions

### ISSUE THREAD

**Issue by MikeASchneider** [nylas/N1#534]
Everything you can do via a keyboard shortcut or through a button in the UI (reply, archive, star, etc.) should have a menu item. This makes keyboard shortcuts much easier to learn, as they're listed inline with the menu items.

![screen shot 2015-12-01 at 3 31 29 pm](https://cloud.githubusercontent.com/assets/934698/11513418/08812a0e-9841-11e5-9f14-ec1791a5c4c3.png)

**Comment by grinich** [comment]
We're looking to do this soon!

**Comment by grinich** [comment]
This is landing in the next release. :)
