### ISSUE TITLE
Quick Schedule Window contains no calendar

### ISSUE THREAD

**Issue by gcleveland** [nylas/N1#536]
The quick Schedule window has key elements to the right, but does not show the calendar info as intended. I've tried re-installing twice with no success.
Mac Os/x Yosemite Version 10.11.2 Beta (15C47a)
<img width="706" alt="screen shot 2015-12-01 at 21 22 17" src="https://cloud.githubusercontent.com/assets/3348484/11514756/0b44b13a-9872-11e5-9280-8f209a49589c.png">

**Comment by grinich** [comment]
Thanks for the bug report @gcleveland ! Can you open the Developer Tools console and see if there are any errors when opening this window?

**Comment by gcleveland** [comment]
Yeah theres 2:

  

/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:720
EACCES: permission denied, mkdir '/usr/local/bin'  
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:725
EACCES: permission denied, mkdir '/usr/local/bin'  

> On Dec 1 2015, at 10:04 pm, Michael Grinich &lt;notifications@github.com&gt;
wrote:  

>

> Thanks for the bug report [@gcleveland](https://github.com/gcleveland) ! Can
you open the Developer Tools console and see if there are any errors when
opening this window?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/536#issuecomment-161110067).![](https://github.com/notifications/beac
on/ADMYBIMIz6MsBnrKxix57wo-sqJAKq6dks5pLhEJgaJpZM4GspM5.gif)

**Comment by dregitsky** [comment]
Hey @gcleveland, thanks for checking that! It looks like those errors might be from the main window's console though - can you also open the Developer Tools console for the broken QuickSchedule window and check for errors?

In the meantime we've pushed a few fixes to QuickSchedule that may actually resolve the problem you're seeing. If you want to check, you can install the plugin from the latest code on master. Thanks!

**Comment by gcleveland** [comment]
Thanks, that seems to have fixed the window display error. But the links in
the invitation are not working. See below.  
  

The Quickschedule window is now showing...

but...

the app functionality doesn't seem to work. Please try and select a time slot.
When I tested it did not work.

Click on a time to schedule instantly:

WEDNESDAY, DEC 2ND

[ 3:00am-4:00am (WET) ](https://quickschedule.herokuapp.com/event/euclJ7yVlBmq
NBSqkSqE1ltZJ3m8WPOvNqTkK4sme2CqqJ7r1GWZOwI74Zu08okhZgXbCpknTsyGTyC0gfj0g9i23P
t0SF1TLI1ccmElWaJAa1MWUB0Py43hVVtENX5K)

[ 4:00am-5:00am (WET) ](https://quickschedule.herokuapp.com/event/YCyywQo6RWqM
gSZErSPXG04KiIzGCjjUHHkh1ceGZdhBdLeWQWDyKNL5AMzpwbhBIxXzdiTQffbXcrmCwedWkHlv87
bC0b3IjRCkYwC8MniTM7iNyKG5x4FTLeCLpiUX)

[ 5:00am-6:00am (WET) ](https://quickschedule.herokuapp.com/event/zoBBYFQaWq6p
gDRtdCnUUr3fyXWVG6qM7AssxtkIdBJQYSFARyxWY7jP1LoZeXqf0mDs7ohYWBQ6NzPsWgTV2M5kTZ
o8zmxBGCNp001isaVPgRPCiBxJdIHt7BJZHW1z)

[ 6:00am-7:00am (WET) ](https://quickschedule.herokuapp.com/event/W2qI5f05gqwb
xRGneNGh22Ti2umTKPXkCnzBvUjLTuTpHKBZcHEXBzLwmjxn5mHEO25uGe87UoZzNSNAG8In1AHuqu
6v6U9NLxgL4xTi4qj0ikgctsi2dqy9PIXOukgt)

[ 7:00am-8:00am (WET) ](https://quickschedule.herokuapp.com/event/De0KOZ3QS6jU
2xV9LgItvWVXBs65iwqaUyeMAgVUJP5pwb1AtvaSTL2mBqCOREE6ovStUAh0KFu9DEs706AXpLxDej
Y6akSXDRAojKZSyg8wbEwCJppXx7G7noJlfei6)

[ 8:00am-9:00am (WET) ](https://quickschedule.herokuapp.com/event/AGbXlqn6b45H
U7f1czMDu0aJGkHDwUuWkzWDGNMHSRjgvQu0S6txfPXvyWbJtkecut2UxKuf4ZJFBznjxWmbrmHfiW
jY6tbNdCWvXvB50H9oB0na086Mo2zZ1TUGyVx8)

[ 9:00am-10:00am (WET) ](https://quickschedule.herokuapp.com/event/ebGsoXbKHVm
egNgEV9AEoOcG65wdrfaRFGxyGlxImBAe3dRRwtC6Gbo74ghPVQKHDOcu1FV8niRTht37RaLPAR7l7
BfLGagnfocx5FqRxVVpSYTlerHPleMROCobdzG0)

  

> On Dec 2 2015, at 12:03 am, dregitsky &lt;notifications@github.com&gt;
wrote:  

>

> Hey [@gcleveland](https://github.com/gcleveland), thanks for checking that!
It looks like those errors might be from the main window's console though -
can you also open the Developer Tools console for the broken QuickSchedule
window and check for errors?

>

> In the meantime we've pushed a few fixes to QuickSchedule that may actually
resolve the problem you're seeing. If you want to check, you can install the
plugin from the latest code on master. Thanks!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/536#issuecomment-161136917).![](https://github.com/notifications/beac
on/ADMYBOdYJkq4P5wLyf2MG4ys8cEccJrpks5pLizTgaJpZM4GspM5.gif)

**Comment by dregitsky** [comment]
Sorry about that - there was an issue with the plugin's backend that caused things to fail intermittently. We just pushed a fix for it last night, so if you have a chance you can try QuickSchedule again and it should work for you. Thanks for reporting all these issues, and sorry for the trouble getting this to work!

**Comment by pattydaniels** [comment]
I'm having the same issue as bengotow was but I'm not sure why as it seems it should be fixed. What's the best way to get the most recent form of QuickSchedule running?
