### ISSUE TITLE
Feature request: Unified Inbox

### ISSUE THREAD

**Issue by allienworks** [nylas/N1#537]
For those who have multiple accounts (I'm using ~5 mail accounts simultaneously), it would be great to "unfold" the mail account <select>, so that all your mail accounts are visible by default (ideally with notifications of unread emails in each account). Having to browse through all the accounts to see any new unread emails is really time-consuming .)

**Comment by bogdanrn** [comment]
+1 to this. An unified inbox would be even better

**Comment by bengotow** [comment]
Hey folks—thanks, this is currently on the roadmap here: https://trello.com/c/5pIfWaN3/3-unified-inbox-view. It'll take a little while to implement because we support labels and unified inbox will allow you to select a mix of threads from Gmail / Exchange, etc. at the same time.

**Comment by allienworks** [comment]
Hmm, maybe I haven't made myself clear. Unified inbox will be nice, but I was talking about the same functionality as now, apart of email account switcher in the sidebar. It would still work the same way, e.g. when selecting account, only folders/tags for that concrete account will be displayed below..

But Unified inbox will be still better than current functionality .)

**Comment by kobak** [comment]
+1

**Comment by sergeyklay** [comment]
+1

**Comment by hebertialmeida** [comment]
+1

**Comment by ECMachado** [comment]
+1

**Comment by chrztoph** [comment]
+1

**Comment by tinybigstudio** [comment]
*1000

**Comment by fjarrett** [comment]
Tossing in a lazy :+1: for this. A unified inbox would rock my world.

Preferably similar to that of [Mailbox](https://www.mailboxapp.com/) (R.I.P.) and [Airmail](http://airmailapp.com/) :smiley:

**Comment by edek51** [comment]
+1

**Comment by gustafbystrom** [comment]
+1

**Comment by neutrinog** [comment]
+1

**Comment by niklasHagner** [comment]
This is by far the most upvoted idea on the Trello bard, but the issue keeps coming up again and again here on GitHub (https://github.com/nylas/N1/issues/8, https://github.com/nylas/N1/issues/123, https://github.com/nylas/N1/issues/472) 
@bengotow - you shoud probably should keep this one open, otherwise someone else will just post the same thing within a month ;)

**Comment by pdsullivan** [comment]
:+1: this would be a game changer :rocket:

**Comment by renaudmathieu** [comment]
+1

**Comment by tommydangerous** [comment]
+1, can't use until this is available

**Comment by xyoun** [comment]
+1

**Comment by enjrolas** [comment]
+1

**Comment by ThePsionic** [comment]
+1

On Tue, Jan 12, 2016 at 9:39 pm, enjrolas < notifications@github.com [notifications@github.com] > wrote:
+1

—
Reply to this email directly or view it on GitHub
[https://github.com/nylas/N1/issues/537#issuecomment-171047106] .[https://github.com/notifications/beacon/AAzZYHU9cvEmuozANs0Qfl3jEPV1xBLPks5pZVvjgaJpZM4Gsrtz.gif]

**Comment by Iain-Stevenson** [comment]
+1

**Comment by Iain-Stevenson** [comment]
With Unified accounts (assuming not just inbox work) please watch out for having control over address when sending new and replying in such as scenario. I don't want a default account address, I need to choose my outgoing identity very carefully to avoid confusing recipients.

**Comment by emorikawa** [comment]
Hey all, just wanted to update. 2/3 of our team are actively working on this right now! It's coming soon.

**Comment by tommydangerous** [comment]
^ Wowzer :+1: 

@emorikawa++

**Comment by michalpaszkowski** [comment]
+1 Yeah, that would make it real Mail.app killer

**Comment by Rudiney** [comment]
:+1:

**Comment by tito** [comment]
+1

Searching an alternative to mailbox!

**Comment by foxgeere** [comment]
Adding a huge +1 for this. At the very least I just want the badge count to show a total for all inboxes so at least I know I have an unread message in there 'somewhere' :) Very happy to hear it is being worked on. :)

**Comment by kenderson** [comment]
+1 would switch if this was available!

**Comment by grinich** [comment]
Coming very soon! :smile: Here's a preview... 

![image](https://cloud.githubusercontent.com/assets/92417/12661369/1981e27a-c5ce-11e5-8dcc-bfa0b3158314.png)

**Comment by Iain-Stevenson** [comment]
smashing :-)


Sent from my Sony Xperia™ smartphone

---- Michael Grinich wrote ----

Coming very soon! :smile: Here's a preview...

![image](https://cloud.githubusercontent.com/assets/92417/12661369/1981e27a-c5ce-11e5-8dcc-bfa0b3158314.png)


---

**Comment by agustifernandez** [comment]
Cool and needed!

**Comment by PhernandoPhelix** [comment]
Awesome!!!... =D

**Comment by kobak** [comment]
Great. It looks very nice. I keep hitting the update button, to have this feature asap. When shall we expect to have it?

**Comment by jweinstein** [comment]
+1

**Comment by neutrinog** [comment]
sweet!

**Comment by insane-dreamer** [comment]
Thanks, guys! With this feature I hope to be able to switch to Nylas.

**Comment by sethual** [comment]
@grinich any timeframe on when we will see the unified inbox? cant wait!

**Comment by bengotow** [comment]
Unified inbox is shipping this weekend in `0.4.4` and should hit the auto-updaters in the next few hours. Enjoy!

**Comment by tommydangerous** [comment]
Wowzer! Mind blown, can't wait!

**Comment by markbao** [comment]
Really fantastic work with this. Looks great and works perfectly. Thanks Nylas!

**Comment by sethual** [comment]
@markbao thanks! i am so excited lol made my weekend.

**Comment by tommydangerous** [comment]
Can I DL IT?!

**Comment by sethual** [comment]
@tommydangerous just download nylas regularly and then update it

**Comment by grinich** [comment]
![aweyea](https://cloud.githubusercontent.com/assets/92417/12869993/bf8a329a-cce4-11e5-83da-be7173aca77d.gif)
