### ISSUE TITLE
Git not reporting correct recent tag.

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#538]
I don't know if this is a Git repository issue or something else. When I run `git describe --tags --long` I get  `0.3.25` as the most recent tag, which I know isn't true. Command output:
```
 ~/N1 > git tag
0.3.23
0.3.25
0.3.26
 ~/N1 > git describe --long --tags
0.3.25-33-g439529c
```
It should display something like:
```
0.3.26-13-...
```

During my investigation after finding that out: it appears it is because the tag for `0.3.26` is 2 commits ahead of master (https://github.com/nylas/N1/tree/0.3.26).

**Comment by bengotow** [comment]
Hmm interesting—it looks like it's being picked up correctly by https://github.com/nylas/N1/releases. I think the `git describe` command may only return the latest tag on your current branch (master). We had to create a `0.3.26` branch to publish that release because lots of other new stuff is landing on master :-)

**Comment by mbilker** [comment]
The tag exists, and its a lightweight tag (doesn't matter in this case). Could you retag the commit? I think the commit hash may have changed because of other pushed changes.

**Comment by bengotow** [comment]
Hey! Talked with the team about this one. We created a 0.3.26 branch, cherry-picked a handful of commits on to it and released it. If we were to tag the corresponding commit on master, the "git history" from that tag would show you commits which weren't actually included in the release.

Hope that helps—we probably won't need release branches for every release, but they make it easy for small patches to go out while the team is working on bigger features that require more testing!

**Comment by mbilker** [comment]
Thanks @bengotow ! I will just deal with it for now, but thanks for the genuine interest and thoughtful response.
