### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by screendriver** [nylas/N1#543]
On the main page https://www.nylas.com/N1/ the big blue download link button in the middle of the page is broken. Only the download link in the upper right corner is working.

**Comment by bengotow** [comment]
Hey @screendriver — thanks for reporting this. It looks like this is an interaction with an ad blocker. It seems to work with AdBlock, but Disconnect.io causes problems. I'm actually not sure why it's blocking that button when the one in the top right works—we track both of those clicks with Google Analytics and Optimizely, but that's it.

**Comment by screendriver** [comment]
You are right. I am using [disconnect.me](http://disconnect.me/) which is **not** an AdBlocker. It "only" blocks elements that are trying to track me (for example Google Analytics).

So the solution is to whitelist nylas.com, then it works fine.
