### ISSUE TITLE
Feature request: Overriding fonts in incoming mail, choose reading font

### ISSUE THREAD

**Issue by Savemech** [nylas/N1#544]
Font, size, bold, italic, etc
sort of this
https://github.com/nylas/N1/issues/226
https://trello.com/c/RqLwnRpf/11-ability-to-change-font-sizes#
but that would be great, if we could tweak it from ui(and not only font size, because i got many mails from guys using lotus notes and these fonts looks dirty :hankey:  and messy  and idk whats going on :hushed: ) , not directly from config files, right?

**Comment by bengotow** [comment]
Hi @Savemech — are you interested in using different fonts in the composer when composing emails, or for the entire app?

**Comment by Savemech** [comment]
Both would be great, but i meaning about app only;
Well thats all because i'm from Mother Russia and basically you guys dont bother bout how different language looks like; so english only mails looks good; but cyrillic one looks bad(its different typo if you look sharp you will see); especially if sender specify font(i had a lot of people using IBM Lotus Notes) and mail from these guys looks especially shitty; so it wold be really great to override their font settings and setup own one, like menlo, helvetica, consolas or segoe ui

**Comment by grinich** [comment]
@Savemech can you post a screenshot of the bad typography

**Comment by xfishbonex** [comment]
@grinich the issue is that there are no support for Cyrillic characters in the Fakt font. So on Windows it replaced by some built-in font (Arial, I suppose) and looks terrible and out of style.
For details please find the screenshot attached.
![n1_cyr](https://cloud.githubusercontent.com/assets/16347198/11891765/a779251a-a572-11e5-8375-a5d2919704c5.png)

**Comment by Savemech** [comment]
@grinich Hi there, well i'm about to find out how's that happend, so i'm occasionally using MS RDP into host with N1, so somehow after few connects i was about to see at real HW, not through RDP,  raw non rendered via cleartype N1, without antialiasing etc..,  and its looks, meh; Meanwhile reopen solve this problem. But also, as mentioned few days ago another dude(huh he's comment gone? :octocat:  ) that is about RU-EN where font used in N1 haven't Cyrillic typos. And we're about to get something that used wide in my system, so i had SegoeUI(i think, cuz i'm not that guy detecting fonts by sharp eye only) instead N1 default.

**Comment by xfishbonex** [comment]
@Savemech I've opened [another issue] (https://github.com/nylas/N1/issues/810) to divide the UI bug and your feature request.

**Comment by Savemech** [comment]
@xfishbonex oh, thank you; hope see this feature implemented!
