### ISSUE TITLE
Notifications for All Accounts When Using Multiple Accounts

### ISSUE THREAD

**Issue by mehmetakiftutuncu** [nylas/N1#546]
I use 3 Gmail accounts and I don't receive notifications for the emails that I receive to my other 2 accounts. I only see new mails coming to the account that is currently selected in N1 as notifications. I can only see new mails on other accounts when I open N1 and switch to those accounts. As I understand, other accounts are not being regularly checked in the background. Notifications should work for all accounts, not just for the currently selected account. That's kind of the point don't you think? :)

**Comment by jwood803** [comment]
Was just going to report this as well. :]

I get the banner notification on all accounts, but the there isn't a count indicator on the icon in the dock if I don't have that account selected.

**Comment by mehmetakiftutuncu** [comment]
@jwood803 Good to know it's not just me who thought something was missing. :)

To clarify, I meant primarily the desktop notifications on OS X.

**Comment by bengotow** [comment]
This should be resolved by unified inbox, which is shipping this weekend in `0.4.4`. Enjoy!
