### ISSUE TITLE
(Feature Requests) Do not quit when click close button.

### ISSUE THREAD

**Issue by vuquanghai** [nylas/N1#547]
Hi. Thanks for the great email client!

I have a idea for a feature: I installed N1 0.3.26 on Ubuntu. When i click close button (x), the program quitted and do not run on background, the indicator on Unity pane also disappeared. So when i get a new email, i don't know that i have a new email until i open the program and reload inbox.

So, my idea is: 
- Could you guys make program still run on background? If that we can get new email and don't need to open program all the time.
- Could you add an option to minimize program to system tray on system startup?

Sorry for my bad English and i new with Github. If i mistake something, please forget it :)

**Comment by bengotow** [comment]
Hey! Thanks for posting this @vuquanghai — this actually just landed on master last night :-) The next release will stay open in the background on Linux / Win32, and you can quit it from the tray icon.

I'll leave this open until the release goes out. Thanks!
