### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by fhur** [nylas/N1#548]
Did a couple of tests, results are very similar:
Test:
- Close N1 (right click on icon  -> quit)
- Open N1 by clicking on the icon
Results:
Takes between 9 and 10 seconds for the "loading N1" box to appear and another extra 9 to 10 seconds for the inbox to show up.

Another concern is that when opening N1 I get absolutely no click feedback until 10 seconds, so at first I was not sure if the program was stuck or something.

**Comment by bengotow** [comment]
Hi @fhur — thanks for opening this. We're triaging some launch speed issues. Do you know if your computer has a traditional hard drive or an SSD? Also, what platform are you on?

**Comment by jorosmtz** [comment]
Hi Ben, I have a SSD Hard drive, and the start time is like fhur describe. I took time and the results: 10 seconds to open the app.

**Comment by mbilker** [comment]
On Linux I see around 1-2 seconds for the main window to pop up. It then takes around 5-8 seconds to load N1 from there. I run with debug flags under Linux from source build all on an old SSD.

**Comment by fhur** [comment]
Woopsie, my specs are:
<img width="236" alt="screen shot 2015-12-05 at 8 31 56 am" src="https://cloud.githubusercontent.com/assets/6452323/11607586/b1e9ed06-9b2a-11e5-9f76-d35e87fcf879.png">
with flash storage

**Comment by mbilker** [comment]
@fhur N1 0.3.26 is out with the caching feature for all packages. It should dramatically help with startup time.

**Comment by jstejada** [comment]
@fhur you should update to the latest version

**Comment by fhur** [comment]
@jstejada Update improved startup time. Thanks
