### ISSUE TITLE
Adding a mailbox...

### ISSUE THREAD

**Issue by parkersonik** [nylas/N1#549]
Good afternoon!
I have a problem with adding email from a corporate domain buratino.top.
Was added to the last option in the list IMAP / SMTP.
Gmail added without problems!
What am I doing wrong?

Options:
IMAP: mail@buratino.top 
login: office@buratino.top 
pass: правильный 
port: 143 
without ssl 

SMTP: mail@buratino.top 
login: office@buratino.top 
pass: правильный 
port: 25 
without ssl

**Comment by bengotow** [comment]
Hi @parkersonik — unfortunately, we don't support non-SSL IMAP / SMTP connections. If you're able to connect to your mail server via SSL, that will fix the issue.
