### ISSUE TITLE
Debian installer needs libgcrypt11 (no longer in stable debian)

### ISSUE THREAD

**Issue by fogzot** [nylas/N1#55]
The .deb package depends on libgcrypt11 but that packages doesn't exists in Debian anymore.
As a workaround it can be downloaded from the old stable "wheezy", i.e.,
    https://packages.debian.org/wheezy/amd64/libgcrypt11/download
but in its current state N1 can't be installed on any "new" Debian.

**Comment by mjs** [comment]
The same applies on any recent Ubuntu.

**Comment by anuragsoni** [comment]
In case anyone else needs this, you can get libgcrypt11 from their launchpad page for ubuntu and derivatives

https://launchpad.net/ubuntu/+source/libgcrypt11

**Comment by feryardiant** [comment]
@anuragsoni not available for ubuntu 15.04?

I'm on Kubuntu 15.04 and facing same issue, any solution?

**Comment by anuragsoni** [comment]
ubuntu 15.04 comes with libgcrypt20. You need to install libgcrypt11 from an older ubuntu version. 

http://www.webupd8.org/2015/04/fix-missing-libgcrypt11-causing-spotify.html

This blog explains that

**Comment by Fenntasy** [comment]
Is there an argument for specifically installing and old version ? I assume the new one have corrected bugs (but my assumption may not be correct). 

Is there a plan to make it work with the newer version ?

**Comment by Mountainerd** [comment]
I am in the same boat as @Fenntasy in that I would prefer to not install a crypto library from an older version to get this to work.

**Comment by bengotow** [comment]
Hey folks—unfortunately `libchromiumcontent` still uses `libgcrypt11`, so you'll need to install it to use any app that depends on it on Ubuntu 15 (N1, Spotify, Brackets, etc.) As soon as everything in our dependency chain has been updated to use the new version, we'll release an update. Sorry for the hassle—I don't know if there are underlying reasons this hasn't been done yet in Chromium.

**Comment by bengotow** [comment]
This has been fixed as of `0.3.26.` Enjoy!
