### ISSUE TITLE
Error while syncing mailbox

### ISSUE THREAD

**Issue by Federfleisch** [nylas/N1#551]
Hi there, I'm having an issue syncing my mailboxes: 

![error]
(https://i.gyazo.com/4534aafeead7302a00aae66ebd8ce39c.png)

Refreshing or relaunching doesn't help at all, it keeps coming again and again. I've also tried deleting an account and adding it again, without success...

**Comment by enoversum** [comment]
Just having since since the latest update which installed an hour ago. On both IMAP accounts that worked well beforehand.

**Comment by grinich** [comment]
This should be fixed now! Please re-open if you are still having issues.
