### ISSUE TITLE
Gmail spam folder isn't syncing

### ISSUE THREAD

**Issue by mitenka** [nylas/N1#552]
Hello. Spam folder seems empty in N1, but it's full of emails when I open my Inbox app.

**Comment by spang** [comment]
Hi @mitenka,

We sync the spam folder at lowest priority—so *after* every other folder in your email account. So it may be that you just need to hang tight and wait a little longer! If your account has fully synced and you're still not seeing your spam mail, please get in touch with support@nylas.com. :)
