### ISSUE TITLE
Feature Request: Paste support from Google Sheets?

### ISSUE THREAD

**Issue by dhighet** [nylas/N1#553]
I send out a lot of reports for work utilizing Google Sheets and Gmail, which allows me to copy paste the cells and their styling right into the body of the email. Unfortunately with N1, all of that information is removed and it is just pasted as plain text. Would it be possible to get support for this in the future?

**Comment by bengotow** [comment]
Hey @dhighet — definitely. We really need to fix HTML paste support. I'll see if we can get this improved in the next update.

**Comment by bengotow** [comment]
Paste from Google Sheets will work in 0.3.29!

**Comment by dhighet** [comment]
Fantastic! Works just as expected. Thank you!
