### ISSUE TITLE
Feature request: Report as spam

### ISSUE THREAD

**Issue by manzu** [nylas/N1#555]
for Gmail at least

**Comment by bengotow** [comment]
Hi @manzu — you can report email as spam by dragging it to "Spam" in the left sidebar. I'll push a fix in a few minutes so you can also apply the "Spam" label from the label picker.

**Comment by manzu** [comment]
and this type of spam "reporting" also notifies gmail that it's spam? or does it just perform a move?

**Comment by bengotow** [comment]
Yep—In Gmail, "Report as Spam" just moves the conversation to your Spam folder, which they then use to train the spam filter. Sometimes, Gmail does provide an extra alert that offers to "try to unsubscribe from the mailing list" - we aren't able to do that via their API unfortunately.
