### ISSUE TITLE
Feature Request: Linux Integration, email notifications.

### ISSUE THREAD

**Issue by gabacosta** [nylas/N1#557]
Please make it possible to get notifications inside Linux environments. A dedicated widget would be awesome .

**Comment by mbilker** [comment]
Zenity is required to receive notifications. I already receive them under both GNOME (Fedora), i3 (Arch Linux), and MATE (Debian).

**Comment by bengotow** [comment]
Hey! Thanks for the note @mbilker. @gabacosta, I've updated the preferences UI so that it displays a note about Zenity on Linux (b224347e10b216b2b8d47c9dd2e1200c825c8f6f). Hope that helps—feel free to re-open this if you continue having issues.

![image](https://cloud.githubusercontent.com/assets/1037212/11571601/124b847c-99b2-11e5-91bc-80e7c237e6d3.png)

**Comment by gkumar7** [comment]
I am running archlinux with gnome 3.18.2 and I don't seem to be receiving the desktop notifications. I have zenity 3.18.1.1-1 installed. I also have the preferences checked:

![zenity-notifications](https://cloud.githubusercontent.com/assets/5412836/12345970/466902fa-bb15-11e5-8fab-4acfe7a3e419.png)

**Comment by mbilker** [comment]
@gkumar7 Zenity is actually not required, but it is a basic implementation of `libnotify`. GNOME has one by default. Make sure `libnotify` is installed through `pacman`. 

Also try running this in the command line:
```
notify-send 'Hello world!' 'This is an example notification.' --icon=dialog-information
```

Information from https://wiki.archlinux.org/index.php/Desktop_notifications.
I use Arch Linux myself, but with the `i3` window manger, the MATE Notification Manager, and Zenity to display the notifications from the MATE Notification Manager.

**Comment by gkumar7** [comment]
@mbilker I have updated my original comment so that it is more clear. Please also refer to this issue: https://github.com/nylas/N1/issues/1030
