### ISSUE TITLE
Email Account Sidebar

### ISSUE THREAD

**Issue by ckluis** [nylas/N1#56]
![sidebar](https://cloud.githubusercontent.com/assets/917989/10367264/69c54292-6d9d-11e5-982e-20631ff0512a.jpg)

An icon-based sidebar with notifications per account would allow for easier understanding of volume in multi-account situations.

**Comment by jdsimcoe** [comment]
:+1: Also, in #60 I've opened a ticket for having the same keyboard account switching Shortcut that Slack uses:

https://github.com/nylas/N1/issues/60

**Comment by grinich** [comment]
please vote up here :) https://trello.com/c/teIoXFQh/41-account-switcher-with-keyboard-shortcut
