### ISSUE TITLE
Graphite appearance OS X UI settings

### ISSUE THREAD

**Issue by bigethan** [nylas/N1#561]
I've got my appearance settings set to 'graphite' which turns the window control buttons gray from their normal stoplight colors.  N1 doesn't respect this setting:

<img width="524" alt="screen shot 2015-12-03 at 9 12 48 am" src="https://cloud.githubusercontent.com/assets/627/11555139/4c684c30-999e-11e5-9179-d6aecdf718e1.png">

Finder's window controls when active:
<img width="148" alt="screen shot 2015-12-03 at 9 12 21 am" src="https://cloud.githubusercontent.com/assets/627/11555141/54ea289c-999e-11e5-868d-3bab26fe5abc.png">

N1's Window controls when active:
<img width="205" alt="screen shot 2015-12-03 at 9 12 03 am" src="https://cloud.githubusercontent.com/assets/627/11555153/693b4466-999e-11e5-8e6f-b7b6a8a9c8a5.png">

**Comment by bengotow** [comment]
This is correct—pull requests welcome!

**Comment by bigethan** [comment]
> pull requests welcome

 https://angel.co/nylas you have employees and $8 million dollars.  How much would you pay for a PR to fix this bug?

**Comment by grinich** [comment]
Hi @bigethan -- this isn't a priority bug for us to fix right now as it's only a cosmetic change experienced with those who have changed their UI defaults. If you'd like to see some of our prioritized features (that hundreds of users have vote up) check out the roadmap Trello board: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by jackiehluo** [comment]
Closing this issue for now since it's not in the scope of this project!

**Comment by olets** [comment]
I'd like to see this opened. Respecting system settings should be in the scope of this project
