### ISSUE TITLE
Quick Schedule email links broken

### ISSUE THREAD

**Issue by gcleveland** [nylas/N1#563]
The quick schedule app seems to create broken links.

![screen shot 2015-12-03 at 17 42 40](https://cloud.githubusercontent.com/assets/3348484/11568694/883e230a-99e5-11e5-90ac-0c812d74f606.png)
![screen shot 2015-12-03 at 17 43 11](https://cloud.githubusercontent.com/assets/3348484/11568695/885eea0e-99e5-11e5-9413-faacaeb05c5e.png)

**Comment by pattydaniels** [comment]
I have the same issue.

**Comment by bengotow** [comment]
Hey! This should be fixed in the next update. Cheers!
