### ISSUE TITLE
Press up or down on Preferences window causes message to load from selected mailbox

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#566]
When I wanted to test a change I made to the Preferences tab for my plugin, I accidentally clicked the up arrow key. This triggered the load of the first message in my Inbox (which was the primary view before opening Preferences). Clicking the `< Inbox` or hitting `Esc` caused the message to go away, and the Preferences window came back up.

I expect this shouldn't happen.

On another note, if I tab through a text box, the selection can land on some external and hidden UI components including the Search bar and trigger unwanted UI actions.

**Comment by bengotow** [comment]
This has been fixed, and we'll be generally refactoring the way these keybindings work next month to prevent this from happening again.
