### ISSUE TITLE
Slow writing

### ISSUE THREAD

**Issue by csimonmoi** [nylas/N1#568]
Hi
after your last update when I write in both my accounts a new email or I try to answer to, writing text is suddenly slow and blocked and right away it returns back... hiccup writing.
Hope this help.

**Comment by grinich** [comment]
Can you post a video or gif? What platform / OS are you on?

**Comment by grinich** [comment]
This should be faster now! Please re-open if you can reproduce @csimonmoi !

**Comment by csimonmoi** [comment]
Sorry I do not understand what your very short message does mean.

If you need my cooperation, please be more specific.

Thanks

  

  

  
  
  

![](https://dl.dropboxusercontent.com/u/1404158/Buddha.jpg?random=635852595474
556693)

|

**Claudio Simonelli**

Fondatore, Presidente e Maestro del  
Centro di Meditazione Dhamma Sukha** **  
**Sede Roma:** Shen Shan, Via Valsolda 45/F  
**Email Centro:** itadhammasukha@gmail.com  
**Skype: **itadhammasukha  
**Sito: **www.dhammasukha.altervista.org  
---|---  
  
_  
_

_  
_

_'__Se un uomo è infelice, sappia che lo è soltanto a causa di se stesso'_

** Epitteto    **

**  
**

**Nota Informativa:**

Questo messaggio di posta elettronica può contenere informazioni riservate,
pertanto è destinato solo a persone autorizzate alla ricezione. Se non si è il
destinatario specificato, non copiare, inoltrare o archiviare questo
messaggio. Se si è ricevuto questo messaggio per errore, si prega avvertire il
mittente ed eliminarlo completamente dal proprio computer.**  
**

> On Jan 8 2016, at 3:19 am, Michael Grinich &lt;notifications@github.com&gt;
wrote:  

>

> This should be faster now! Please re-open if you can reproduce
[@csimonmoi](https://github.com/csimonmoi) !

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/568#issuecomment-169867960).![](https://github.com/notifications/beac
on/APTadsHdxOeQ921bD369Hqy2zgjvQaH8ks5pXxQ9gaJpZM4Gu4r4.gif)
