### ISSUE TITLE
Can't build under Windows

### ISSUE THREAD

**Issue by MaxBareiss** [nylas/N1#57]
When I try to build under Windows (Win10 x64), `script\bootstrap` succeeds, but when I run `script\build` I get to here:

```
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less/lib/less/fs.js'

Running "download-electron" task

Running "build" task
Fatal error: Cannot copy non-existent build\resources\win\N1.sh to C:\Users\M\AppData\Local\Temp\nylas-build\Nylas\resources\cli\N1.sh
```

I'm running Node 0.10.40 and npm 1.4.28. Any ideas? I applied @solnj 's fix in issue #28 to make it build correctly with x64.

**Comment by solnj** [comment]
Try ``script\clean`` and then ``script\build`` again.

**Comment by MaxBareiss** [comment]
Worked, thanks!

**Comment by solnj** [comment]
@bengotow I think we got it working on 64-bit Windows! :)
