### ISSUE TITLE
SMTP without an account

### ISSUE THREAD

**Issue by rapha8l** [nylas/N1#570]
Hi,
On Debian, n1 version 0.3.26, on account creation, it's not possible to use SMTP without giving an account, which can be a problem on providers SMTP.
Thanks

Raphaël

**Comment by mbilker** [comment]
What do you mean "without" an account?

**Comment by bengotow** [comment]
Hi @rapha8l — To connect your account to N1, your SMTP and IMAP must require credentials and  authenticate over SSL. We don't have any plans to support open gateways or non-SSL connections, since the sync engine runs in the cloud and it'd be very insecure. Sorry!
