### ISSUE TITLE
Custom shortcuts not overriding default

### ISSUE THREAD

**Issue by spentacular** [nylas/N1#572]
I created two overrides to change my archive and trash shortcuts. My keymap.cson file currently looks like this:

```cson
'body':
  'delete': 'application:archive-item'
  'cmdctrl-delete': 'application:delete-item'
```

Is there something I'm missing that should be able to override them?

Thanks for y'alls awesome work!

**Comment by jstejada** [comment]
hey @spentacular , these are working for me. Are you still having trouble? What OS are you using?

**Comment by spentacular** [comment]
Hey @jstejada I'm using Version 0.3.32-b11131d and 10.11.2. I just checked any they still aren't working. Is there anything I need to do?

**Comment by jstejada** [comment]
so, what keys are you pressing? Are you pressing just backspace? or `fn + backspace`

**Comment by spentacular** [comment]
Doh, that is it! I wasn't aware of the need to press `fn`. Thanks!
