### ISSUE TITLE
Clicking "View" on notification does nothing

### ISSUE THREAD

**Issue by Bugsbane** [nylas/N1#573]
When a new email notification pops up and I click the "View" button, nothing happens.

n1 version 0.3.26-c1ce330 (I wish you'd put this info somewhere it could actually be copied, like in the help window...)

Ubuntu 15.10 with the Plasma / KDE workspace.

**Comment by bengotow** [comment]
Hey @mbilker — does this happen for you too? I'll try and get one of our Ubuntu boxes to reproduce this...

**Comment by mbilker** [comment]
@bengotow Hmm. I don't get a view button at all. When I click on the notification the message loads up in N1 though.

**Comment by mbilker** [comment]
I will send an email to myself to test.

**Comment by mbilker** [comment]
Yep. I get a Zenity notification in the top right hand corner of my screen. Clicking it causes N1 to open the message. In `i3` (the window manager I use) the workspace lights up red, indicating an urgent notification is present on a window in the workspace.

**Comment by Bugsbane** [comment]
This should probably be obvious, but just for the record, my window manager is Kwin 4:5.4.2-0ubuntu1

**Comment by mbilker** [comment]
Okay then.

**Comment by qba123** [comment]
same here...

Elementary OS 0.3.1

I got a notification, but when I click on it nothing happens

**Comment by mbilker** [comment]
@qba123 Hmm. Do you know the kind of notification system Elementary OS uses? From a quick Google search it appears they use their own system.

**Comment by qba123** [comment]
hmm maybe its "Pantheon Notify". How to change it on Zenity?

**Comment by mbilker** [comment]
I wouldn't suggest that quite yet. I will look into the issue. Pantheon Notify uses the standard Freedesktop Notification interface. Just giving you a status update.

**Comment by qba123** [comment]
yes, but earlier I had e-mail client "geary" and it was working (when I clicked on notification - message shows in geary)

**Comment by capitantrueno** [comment]
Same here... My system is Elementary OS 0.3.2 64-bit. When mail arrives, I got a notification, but when I click on it nothing happens.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
