### ISSUE TITLE
Sometimes mark as read button incorrectly shows "Mark as unread" instead of read. 

### ISSUE THREAD

**Issue by Bugsbane** [nylas/N1#574]
Steps to reproduce:
1. Select multiple emails, some read and some unread

Actual:
Mark as read/unread button at the top displays "Mark as unread" despite marking all emails as read when pushed.

Expected:
Mark as read/unread button correctly displays the name that matches what it will do, ie "Mark as read".

n1 version 0.3.26-c1ce330 (I wish you'd put this info somewhere it could actually be copied, like in the help window...)

Ubuntu 15.10 with the Plasma / KDE workspace.

**Comment by bengotow** [comment]
Hey @Bugsbane — good catch! Looks like the logic for determining the icon was inconsistent with what it actually did. I've fixed this in f509a41ce77b374baf47a5ab7a32434ead9e8d1f
