### ISSUE TITLE
One particular email always comes back as unread.

### ISSUE THREAD

**Issue by NaitoKenzo** [nylas/N1#575]
Hi there,

I've got an old email that I can't mark as read nor delete, or rather I can but it always comes back a few seconds later as unread. Here is a gif, as you can see it's driving me crazy:

![ufloez9tpd](https://cloud.githubusercontent.com/assets/5681827/11597920/18860854-9abf-11e5-83f9-2d2f18d1d0ae.gif)

Cheers, 

Kenzo

**Comment by mbilker** [comment]
I had the same issue. I eventually restarted.

**Comment by bengotow** [comment]
Hi @NaitoKenzo — it looks like the app is trying to make an API request to mark the thread as read and receiving a 400, which causes it to revert the change in the local database.

I'll look at our platform logs and see if we can track this down.

**Comment by NaitoKenzo** [comment]
You're right, the mailbox wasn't synching. I unlinked the account and then added it. Everything's back to normal. I don't know why the mailbox was disconnected though.

Cheers.

**Comment by polarity** [comment]
> I'll look at our platform logs and see if we can track this down.

wait, wait, wait.... what kind of api request. i thought this is an standalone email client?
