### ISSUE TITLE
N1 don't load email messages

### ISSUE THREAD

**Issue by paoloalmeida** [nylas/N1#576]
The app stay loading in all acounts, and don't load my email messages.
This error started today, yesterday seems normal.

Heelp :(

![screen recording 2015-12-04 at 04 40 pm](https://cloud.githubusercontent.com/assets/2863186/11597924/fbe8f54e-9aa5-11e5-9e91-ec36aa48af45.gif)

**Comment by mbilker** [comment]
Is there any sort of messages in the Activity Window, available under `Developer --> Open Activity Window`

**Comment by bengotow** [comment]
Hi @paoloalmeida — hmm, that's no good. It looks like the sqlite database the app uses may be locked or corrupted. Does it come back if you restart the app? Could you try launching N1 with this command from `Terminal.app` and see if any errors appear?

``` /Applications/Nylas\ N1.app/Contents/MacOS/Nylas --enable-logging```

**Comment by paoloalmeida** [comment]
Hi @bengotow and @mbilker,
I started the app with terminal, and show me this error:

![screen shot 2015-12-06 at 2 34 23 pm](https://cloud.githubusercontent.com/assets/2863186/11614338/e8da9610-9c26-11e5-866f-1928a4b5ee2e.png)

I understand what this error is with sqlite. How can I do for fix this? I'm trying reinstall the app... As soon I give the log in terminal to see if appear the same error..

Whatever, any suggestion?

Tks folks!!

**Comment by mbilker** [comment]
Hey. The SQLite database is corupted.

To Fix: Quit the app, then remove `~/.nylas` if you are on Linux or Mac OS X, `~` denotes the home folder, which is `/Users/<USER>` typically on Mac OS X and `/home/<USER>` typically on Linux.

**Comment by mbilker** [comment]
You will need to re-add all your accounts afterwards.

**Comment by paoloalmeida** [comment]
Hey @mbilker thanks so much man!
I did this steps, and worked for me. Hmm, but do you know what happened, for begin this error?

**Comment by mbilker** [comment]
@paoloalmeida I don't exactly know why this happens. SQLite databases can be corrupted by many things.

**Comment by brenov** [comment]
Hey @mbilker, here I have the same error, but I can't fix it with this solution
