### ISSUE TITLE
Ubuntu Indicator Icon not working

### ISSUE THREAD

**Issue by heavymetalalchemist** [nylas/N1#577]
I'm using N1 ver. 0.3.26 on Ubuntu 15.10 64-bit. Previously, there was an N1 indicator icon in the tray in the top-right corner of the Unity desktop, but it's been missing ever since I installed the newest version.

**Comment by romabysen** [comment]
Same for me but I think the issue is with something in a recent Ubuntu update because the indicator for Slack is also gone now.
