### ISSUE TITLE
Exchange Account Sync Stopped

### ISSUE THREAD

**Issue by twredberg** [nylas/N1#578]
Removed a folder from the left side of my exchange account. Since that operation. All syncing has stopped. No new messages received in over 5 hours.

![image](https://cloud.githubusercontent.com/assets/8644/11602490/a17eb406-9aa8-11e5-9b40-f423126a1ad3.png)

**Comment by lapin-b** [comment]
My mails are not syncing at all. I checked security challenges from my mail account and no security challenge. If I want to check my inbox, I have to reload the entire application.

**Comment by khalido** [comment]
Same. restarting the program restarts sync.

**Comment by twredberg** [comment]
I tried restart and re-installed. Still not updating.

**Comment by Squishier** [comment]
Having the same issue with an Exchange mailbox (on OSX, El Capitan). Have tried the following:

- Removed and re-added mailbox. Syncing worked briefly, then stopped. Error message: "An error occurred while syncing your mailbox. Syncing will resume in a moment..."
- Removed and reinstalled the application, re-adding the mailbox in the process. No new syncs. Same error message.
- Completely removed the application and all related files, reinstalled, re-added mailbox. No new sync. Same error message.

A test gmail account that receives all the mail forwarded from the Exchange account syncs just fine.

**Comment by kav-ya** [comment]
@twredberg, @Squishier - thanks for the report!
What's the email address associated with your problem accounts? We'll take a look.
Since this is personal information, please email support@nylas.com rather than posting here.
