### ISSUE TITLE
Feature Request: Option to preserve original mail content colors in dark mode

### ISSUE THREAD

**Issue by OscarGodson** [nylas/N1#579]
As requested, here's the email I sent that you asked to post on GitHub :)

> Hey just a slight suggestion on the dark theme. The dark theme makes the email body and stuff black and fonts different colors. This makes some emails look broken or not readable because you can never be sure what emails will contain. Gmail handles this by making everything a dark theme _except_ the email body. I made a quick mockup of what it would look like if you did this in Nylas

![example](https://cloud.githubusercontent.com/assets/20615/11603497/f0269f9a-9a96-11e5-8ffb-e25aba92045c.jpg)

**Comment by brettgerry** [comment]
Thanks for the suggestion, Oscar!

**Comment by bengotow** [comment]
Closing as dup of #945
