### ISSUE TITLE
Opening drafts crashes N1

### ISSUE THREAD

**Issue by sharadv1** [nylas/N1#581]
when i open a draft email it automatically defaults to full screen (for some reason there is no 2 pane view with drafts).  when i try to close the full screen draft email the program crashes every time.

**Comment by grinich** [comment]
@sharadv1 what do you mean the program crashes? do you have the main app open in full screen during this time?

**Comment by sharadv1** [comment]
crashes as in shuts down and OS X says the program has shut down unexpectedly. yes I have it on full screen.

Cheers,

Sharad

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
