### ISSUE TITLE
Filters plugin does not show up

### ISSUE THREAD

**Issue by sharadv1** [nylas/N1#582]
i added the filters plug in and it shows in the plugin view, but there is no filters mailbox or folder under which i can actually add and modify filters.

**Comment by mbilker** [comment]
The plugin is not configured correctly to use the `nylas-exports` version of React.

**Comment by mbilker** [comment]
It fails to load up at launch. Evident in the DevTools.

**Comment by mbilker** [comment]
Also, `Actions.deleteFilter, Actions.didPassivelyReceiveNewModels, Actions.saveFilter` are undefined and are not created anywhere. Paging @bengotow.

**Comment by mbilker** [comment]
Also #189

**Comment by jstejada** [comment]
yep, as mentioned in #189, the current filters package is a bit outdated, we're actually revamping the filters package and it will be available to play with very soon. sorry for the trouble! I'm going to merge this into #189

**Comment by mbilker** [comment]
Thanks @jstejada !
