### ISSUE TITLE
Upgrade apm to 1.4.0

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#583]
I saw that in the main atom/atom project there was an upgrade to apm 1.4.0. While this may not bring any improvements from what I can see.

The only reason I suggest an upgrade is because this is the version used in the stable version in the current version of Atom.

**Comment by bengotow** [comment]
Hey @mbilker — thanks for reporting this. We'll look into upgrading `apm` in the next major Electron version bump. We may be moving off of apm entirely in the future.

**Comment by mbilker** [comment]
Okay. That is a good call. I noticed `apm` integration is a wacky dealing with the command line.
