### ISSUE TITLE
formatting issue with certain emails

### ISSUE THREAD

**Issue by sharadv1** [nylas/N1#584]
certain emails have all of the text squeezed to the very right with one character per line
![screen shot 2015-12-04 at 8 35 57 pm](https://cloud.githubusercontent.com/assets/16161297/11606044/d6684600-9ac6-11e5-992b-a88489d6cd15.png)

**Comment by bengotow** [comment]
Hi @sharadv1 thanks for reporting this. If it's not too much trouble, could you forward this email to ben@nylas.com? (When you're composing the message, you can cut out the personally identifying information.) That'll make it a lot easier to add this to our test suite and fix it!

**Comment by grinich** [comment]
Or paste it here @sharadv1 !

**Comment by sharadv1** [comment]
I already sent it

Cheers,

Sharad

**Comment by grinich** [comment]
@sharadv1 I think we've fixed this. Please re-open if you are still having issues. Thanks!
