### ISSUE TITLE
Composer: Unable to override automatic numbered list styling

### ISSUE THREAD

**Issue by markbao** [nylas/N1#585]
In the composer, I'm not able to override the automatic list styling because of a bug.

When I type "1. ", it automatically creates an HTML numbered list. I hit backspace which undoes the automatic numbered list and makes it plain text again. Woo! Then I start typing and the next time I hit "space", it's converted into a numbered list again and my cursor goes to the beginning of the list item. Boo.

N1 Version 0.3.27-1c2a936 (0.3.27-1c2a936)
Mac OS X 10.11.1 (15B42)
Gmail

Demo:

![listbug](https://cloud.githubusercontent.com/assets/27594/11606219/4e820962-9ae7-11e5-868e-cc2d62aa8a7a.gif)

**Comment by emorikawa** [comment]
Hey, this was fixed in eb3223580b28411da82147842ce7e7304c39eaef
Affected bulleted lists too in #1064

**Comment by markbao** [comment]
Thank you!
