### ISSUE TITLE
Labeled emails not syncing

### ISSUE THREAD

**Issue by LuckyLuky** [nylas/N1#586]
Hi 

I've just installed client and noticed that labels from my Gmail account synced correctly, but they are all empty. When I open some of the labels, I get "No threads to display" message.

**Comment by bengotow** [comment]
Hi @LuckyLuky — thanks for downloading N1! When you first install the client, it may take some time for all of your messages to appear. Does it still say "Syncing your Mailbox..." in the lower left?

**Comment by LuckyLuky** [comment]
You're right, the message disappeared after a while but it looks like client still kept syncing. After running the client today, I waited for a while and now everything is synced right. Thanks for making this great app!
