### ISSUE TITLE
Different font style and size options for mails and signature. 

### ISSUE THREAD

**Issue by muraterd** [nylas/N1#587]

**Comment by rhoconlinux** [comment]
I second this proposal, this feature it is ideal for guys with low resolution screens (1366x768) in which the fonts are little bit too big for me. 

I tried to hack the UI settings by editing the font-size in the css files without success, probably cause there are lots of them :) . Any clue on where should I see to change the font size of the body of the emails? 

Thanks!

**Comment by jgindin** [comment]
Please make it easy to change basic font size. Even something like what Gmail has with "Comfortable", "Cozy" and "Compact".

Even after choosing "Cozy", I've hacked the Gmail CSS to make the font size smaller too ;-)

As a starting point, I'd be perfectly happy with a quick pointer to the CSS files to start mucking with!

**Comment by bengotow** [comment]
Hey folks! We're actually shipping an interface size option in an update tomorrow. Rather than changing font size specifically, we're opting to zoom the entire interface (see #699) because it's easier on theme developers. We may revisit the "cozy / compact" concept in the future though, depending on how well interface zoom solves the problem.

**Comment by jgindin** [comment]
#699 is definitely a step in the right direction. I'd still like things tighter ;-)

There's pointers to creating new plugins, but I didn't see any pointers to creating new themes?

**Comment by akmcbroom** [comment]
Yes, +1 for more compact list views

**Comment by darrenkenny** [comment]
I would love to have the option to be able to use a monospace font, of my choosing if possible, for the reading of messages - I work in an environment where people are often drawing small ASCII art type diagrams in their e-mails (we're a Unix house and old school) and not using monospace means that some things just look ridiculous. (plus at this point I find it easier to read quickly)

**Comment by bengotow** [comment]
Hey folks—the fonts have been shrunk further on master, and we've actually made the top bar narrower as well. If this is still an issue in the next release, feel free to re-open or create a separate issue!
