### ISSUE TITLE
Chinese character input interrupted for multiple character phrases

### ISSUE THREAD

**Issue by peeinears** [nylas/N1#590]
Mac 10.10.5
Nylas N1 Version 0.3.27-1c2a936 (0.3.27-1c2a936)

---

Desired behavior (from Mac Mail):
<img width="157" alt="screen shot 2015-12-05 at 3 04 18 pm" src="https://cloud.githubusercontent.com/assets/154428/11610812/924bf510-9b62-11e5-8dd4-6f449e14ced8.png">

Nylas behavior:
<img width="152" alt="screen shot 2015-12-05 at 3 11 31 pm" src="https://cloud.githubusercontent.com/assets/154428/11610813/a106058c-9b62-11e5-888b-3d8947aff04c.png">

It seems like when I begin typing the "hao" Nylas interprets a space and commits "ni" as english text, interrupting the normal multiple character suggestion.

**Comment by mbilker** [comment]
What happens in Chrome when you do this?

**Comment by peeinears** [comment]
@mbilker anywhere in chrome?

**Comment by peeinears** [comment]
<img width="273" alt="screen shot 2015-12-05 at 5 25 16 pm" src="https://cloud.githubusercontent.com/assets/154428/11611185/36c3bd00-9b75-11e5-869c-7ccf46ab3214.png">

**Comment by mbilker** [comment]
Ok. Do you have the Signatures text box available in the Preferences area of N1?

**Comment by peeinears** [comment]
@mbilker yes

**Comment by peeinears** [comment]
@mbilker works fine there. My suspicion is the spellchecker...

**Comment by mbilker** [comment]
Actually, its the same N1 React class so that won't work. It appears `ContentEditable` is the culprit here. Possibly the spellchecker is included.

**Comment by mbilker** [comment]
The `Contenteditable` class is a very complicated one since it emulates a `Textarea` element which is what the Github comment box is. It also supports extensions that would be harder to do under `Textarea`.

**Comment by peeinears** [comment]
@mbilker I see. Well, again, it **does** work in the `contenteditable` div in Signatures, so I don't think it's `contenteditable` alone. Must be something that the Reply `contenteditable` has that the Signatures `contenteditable` doesn't have (possibly spellcheck?).

**Comment by mbilker** [comment]
Hmm. Maybe you are right. I will dig up the source for the `Composer`.

**Comment by bengotow** [comment]
Hey @peeinears — yep, I think what's happening is that the spellchecker plugin (in the message composer, but not in the signature editor) is placing a <span> tag around the word it thinks is misspelled (`ni`). I think that is causing the multi-character substitution to fail. I'll see if we can fix this—we need to disable spellcheck for languages other than English, and that may fix this.

**Comment by bengotow** [comment]
(Related: #535)

**Comment by peeinears** [comment]
@bengotow Roger that. Ha, thought of a good test that seems to confirm spellcheck as the culprit, which is to use a character that in pinyin is also a valid english word (e.g. "pin"). Works in that case...

<img width="210" alt="screen shot 2015-12-05 at 5 59 52 pm" src="https://cloud.githubusercontent.com/assets/154428/11611275/05426434-9b7a-11e5-8ab2-2f25c4185224.png">

**Comment by bengotow** [comment]
@peeinears — thanks for verifying! This should be fixed in the next release by 9af40833accdc2beddf6fecad0a3e5261cfaffa9. We'll spellcheck in your current system language, and disable spellcheck entirely if we can't provide spellcheck yet.

**Comment by peeinears** [comment]
:+1:
