### ISSUE TITLE
Issue installing plugins

### ISSUE THREAD

**Issue by federicoiosue** [nylas/N1#592]
Hi,

when I try to manually install a plugin I follow the README: 

__From the menu, select `Developer > Install a Package Manually...`
   Choose the unzipped `n1-quickschedule-plugin` directory to install the plugin__

But I'm always getting [THIS](https://github.com/nylas/N1/blob/master/src/apm-wrapper.coffee#L210) error.
The folder is effectively copied into `~/.nylas/packages` directory but no `node_modules` with dependencies is available into it.

By performing `apm install --verbose` into the plugin folders I locally download all its dependencies but, when N1 is relaunched, the plugin is still not loaded. 
No related errors inside console log.
When trying to select `Developer > Open detailed log` nothing happens.

OS; Manjaro Linux
N1: version 0.3.26-c1ce330

**Comment by mbilker** [comment]
I noticed the same about the `Open detailed log`. Run `npm install` in the plugin folder.

**Comment by federicoiosue** [comment]
After a serie of attempt it worked by manually installing dependences with `apm`
