### ISSUE TITLE
Can't read bottom popup message while using dark theme

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#596]
I'm using Ubuntu 15.10. When using the dark theme the bottom popup messages are not easily readable. The background is white and the text is a light grey. I will attach a screenshot.
![screenshot from 2015-12-07 01-17-40](https://cloud.githubusercontent.com/assets/6756628/11620392/7d54f278-9c80-11e5-9049-2954a860b3d7.png)

**Comment by martinoj2009** [comment]
I was able to fix this by going into the developer mode and changing this:

.undo-redo .undo-redo-message-wrapper {
  flex: 1;
  flex-shrink: 1;
  margin-left: 16px;
  margin-right: 30px;
  color: #00000;   <=== I changed from #FFFFF to #00000
  overflow: hidden;
  text-overflow: ellipsis;
  text-align: left;

**Comment by martinoj2009** [comment]
This was in: /usr/share/nylas/resources/app.asar/internal_packages/undo-redo/stylesheets/undo-redo.less

**Comment by bengotow** [comment]
Hey @martinoj2009 — thanks for reporting this. I ended up changing the CSS slightly differently so it's based on the variables defined in the theme. 

![image](https://cloud.githubusercontent.com/assets/1037212/11642768/a15f9e7e-9cf4-11e5-9f39-d490e60ef6a7.png)

**Comment by martinoj2009** [comment]
Thanks @bengotow !
