### ISSUE TITLE
Not getting notifications or sound when receiving mail

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#597]
I'm on Ubuntu 15.10, I've checked the settings; however, when getting new mail I don't get any sound or notifications. I'm using the default Unity desktop.

I've tried sending multiple test e-mails with it: minimized, in the background, and in the foreground (didn't expect it to show one, but did expect a sound).

**Comment by bengotow** [comment]
Hey @martinoj2009 —can you try the solution in #573 (installing the Zenity package) and see if that works? We'll be adding a note about that in the next Linux release.

**Comment by martinoj2009** [comment]
That works @bengotow  thanks!
