### ISSUE TITLE
Can't select multiple emails with control key, but can with shift

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#598]
I'm using Ubuntu 15.10. I'm trying to select multiple e-mails so that I can delete e-mails in bulk. Maybe I'm doing it wrong, but when I select an e-mail and hold control I cannot highlight multiple e-mails, it just jumps to the last e-mail selected. I can select multiple e-mails when holding shift... but that doesn't help when the e-mails are spread out.

**Comment by bengotow** [comment]
Duplicate of #388
