### ISSUE TITLE
Add Account Switching keyboard shortcut

### ISSUE THREAD

**Issue by jdsimcoe** [nylas/N1#60]
Many apps like Slack have this via `cmd + shift + ]` or `cmd + shift + [` to move back and forth between accounts. Having this would it make it much easier navigating multiple accounts.

**Comment by ckluis** [comment]
+1

**Comment by wkoffel** [comment]
This is a crucial one for me too, great suggestion.

**Comment by pavelbinar** [comment]
:+1:

**Comment by theinterned** [comment]
:+1:

**Comment by grinich** [comment]
please vote up here: https://trello.com/c/teIoXFQh/41-account-switcher-with-keyboard-shortcut

**Comment by mattjared** [comment]
⌘1 and ⌘2 FTW. Thank you!
