### ISSUE TITLE
Show how many items were found in search results

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#601]
I'm using Ubuntu 15.10. It would be nice if somewhere in the window it would say how many items were found when searching e-mail.

**Comment by bengotow** [comment]
Hey @martinoj2009 — I'll talk to our sync-engine team and see what we can do! I'm not sure we get a total number back from all mail providers, but we should be able to get something in.

**Comment by martinoj2009** [comment]
Thanks @bengotow it's nice seeing this mail client come together.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
