### ISSUE TITLE
Can't delete selected mail in search results

### ISSUE THREAD

**Issue by martinoj2009** [nylas/N1#602]
I'm on Ubuntu 15.10. I'm unable to delete mail in my search results. When I search for all mail that contains "facebook" and select mail (single or multiple) I cannot delete that mail. There's no icons, nor does pressing the delete key work. 

May I also suggest an actions option, maybe I should make another "Issue" ticket for this. I'd like to have an actions/options drop down when searching. That way you can perform: delete, move, mark read, mark unread, etc in an easy drop down menu. Sooooo a for loop, or how ever you want to do it.

**Comment by bengotow** [comment]
Merging this in to #537 since this is fixed on that branch. Stay tuned! Heading to beta shortly.
