### ISSUE TITLE
OS X: Double-click to minimize

### ISSUE THREAD

**Issue by arnekolja** [nylas/N1#603]
Nylas N1 should behave like other native OS X apps and enable minimize-on-double-clicking-titlebar. :-)

**Comment by mbilker** [comment]
Not all native OS X do this. I know Chrome will expand or contract its window size when you do this.

**Comment by arnekolja** [comment]
Okay, I see. But usually almost all apps do. At least when setting the corresponding option in System Preferences.

**Comment by mbilker** [comment]
Ahh. So there is an option. I never knew that when I used OS X El Capitan.

**Comment by arnekolja** [comment]
Think default behavior is to do nothing. But I am one of those who always set this option right after installing OS X, so for me it's just like default :)

Sorry for the attached screenshot being in German. Hope it helps.

![bildschirmfoto 2015-12-07 um 17 05 53](https://cloud.githubusercontent.com/assets/178206/11631946/e0433dac-9d04-11e5-9fd4-58bfa802a96e.png)

**Comment by bengotow** [comment]
Ahh nice! I had no idea that was an option in Mac OS X @arnekolja. Unfortunately the /entire/ main window of N1 is HTML / CSS, even the traffic light icons. We'd need to detect this system setting and write the behavior ourselves, or extend the Electron desktop shell to allow us to mark a region as the titlebar. I'll see what we can do!

**Comment by bengotow** [comment]
Hey folks—I'm merging this in to #974 and updating that to reflect that you can choose this behavior.
