### ISSUE TITLE
Allow manual avatar (profile picture) selection and toggling on/off

### ISSUE THREAD

**Issue by tarrant** [nylas/N1#605]
I have my gravatar synced across multiple email addresses. Sadly this causes some confusion when using N1. It would be nice if I could either set it back to the generic service provider icon, or set a custom icon just in N1.

**Comment by fjarrett** [comment]
+1 for this!

I too use the same avatar across all of my accounts, but it seems like there should be an internal override within N1 to facilitate easy recognition of which account is which (such as using a company logo on my work account).

<img width="213" alt="multiple-accounts" src="https://cloud.githubusercontent.com/assets/522158/11803098/0584631c-a2bd-11e5-91de-3ee02e56f381.png">

**Comment by bengotow** [comment]
Hey folks—in `0.4.4`, we've rebuilt the left sidebar and no longer show avatars for your accounts, so this should be resolved. We might add avatars back in the future if we're able to find a better source of images.
