### ISSUE TITLE
Toggle Menu Bar does nothing on Ubuntu

### ISSUE THREAD

**Issue by Froglich** [nylas/N1#606]
As the title says, the "Toggle Menu Bar" menu item, under "View" does absolutely nothing.

To develop further:
Running Ubuntu 15.10 GNOME Edition
Running the .deb from nylas.com/n1

**Comment by bengotow** [comment]
Hey @Froglich — looks like you're right. I'm going to go ahead and cut that item until we have a chance to implement the behavior.
