### ISSUE TITLE
OS X: Downloaded app, added iCloud account. No Threads to Display

### ISSUE THREAD

**Issue by tt-tsquared** [nylas/N1#608]
Wanted to try out the app. I set up my .mac/iCloud account. The inbox just says 'No Threads to Display'. Only Drafts and Junk show any information. Everything else is empty. Hard to check out the app if doesn't display my email. There are thousands of emails in the Inbox.

**Comment by enoversum** [comment]
Well, I had the exact same situation when I first started, and found another thread telling me that with a big e-mail account (i.e. 'many' mails, whatever that may mean), it could take a moment to finally collect e-mails. And so it was in my case. It actually took a few days having it running in the background (with no obvious activity) until e-mails in my inbox popped up.

**Comment by bengotow** [comment]
Hey folks—thanks for checking out N1! Sync speed varies based on the type of account you're connecting, but it's not unreasonable for it to take days to build a cache of your entire mailbox. If you try another client like Mail.app or Thunderbird, you'll notice that it can also take days for your old messages to appear. My Gmail mailbox is about 6GB of data—a few million messages. There are connection limits on most IMAP servers, and messages have to be fetched in small batches. Such are the joys of old protocols :-)

That said, our sync engine should be prioritizing "Inbox" over your other folders like Junk, so I'll look into that. Our sync team (working on https://github.com/nylas/sync-engine) has been doing a lot of profiling over the last few months, and things should continue to get faster into next year. 

I should note that "initial sync speed" is also different from "incoming mail delay". We actually hold a separate connection open for the Inbox, so you should receive new mail in a few seconds or less, even while old mail is still being populated.

Hope that helps!

**Comment by tt-tsquared** [comment]
It is a failed UX if I can't see any of my mail and there's no indication it is fetching or doing anything. To me it looks broken and hence the bug report. Surely you could fetch something to show the user.. the last 100 messages or something. A progress view?

**Comment by bengotow** [comment]
Hey! Do you see a "Syncing your Mailbox..." message in the lower left of the main window? It should be there while your mail is syncing. Let me know if you don't see it—we can look at making something more obvious in the next update.

**Comment by tt-tsquared** [comment]
I fired up the app again and didn't see anything. I was poking around in the menus and after a few minutes my inbox loaded. Afer that the 'Syncing your Mailbox...' message could be seen. It wasn't there before though.
