### ISSUE TITLE
Ability to track packages inside N1 

### ISSUE THREAD

**Issue by zlatkobijelic** [nylas/N1#609]
If you receive a tracking number for a package, N1 would pick that up (as a link) and display the current status / location of the package by pulling from the carrier website. 

This would be a neat little add on / plugin.

**Comment by mbilker** [comment]
:+1: I like this idea. Kind of like Gmail's Inbox recognizes many properties of emails.

**Comment by bengotow** [comment]
Moving to https://trello.com/b/hxsqB6vx/n1-open-source-roadmap
