### ISSUE TITLE
What to do next?

### ISSUE THREAD

**Issue by ForumLiker** [nylas/N1#61]
Link does not work....
Where can I get the code? On the mailbox does not come
![2015-10-08 22-40-50](https://cloud.githubusercontent.com/assets/11502792/10377761/cfeafd6c-6e0d-11e5-9b9f-a6619c628f49.png)

**Comment by ateev** [comment]
[Here](https://github.com/nylas/N1/blob/master/internal_packages/onboarding/lib/token-auth-page.cjsx#L53) is the file. But the link works fine for me.

**Comment by bengotow** [comment]
Hey @ForumLiker — hmm, that blue link is meant to direct you to https://invite.nylas.com. If it's not working, let me know what platform you're on, and what your default browser is. It should open in Chrome / Firefox, etc. If it's an invite you're after, fill out the email form on that invite page and link your GitHub account, and we'll get one your way as soon as we can.

**Comment by ForumLiker** [comment]
@bengotow , Archlinux_x64 and Mozilla Firefox 41.0.1
How soon should come code on email?
