### ISSUE TITLE
OS X: retrieving emails extremely slow

### ISSUE THREAD

**Issue by tomgenoni** [nylas/N1#610]
I tried the app about a couple months ago and just reopened (and updated) to check out improvements. But it's still very, very slow to sync emails and for me is not usable. Issue #608 said it "took a few days" for his account to sync. What accounts for the delays?

**Comment by bengotow** [comment]
Hey @tomgenoni — thanks for checking out N1! Sync speed varies based on the type of account you're connecting, but it's not unreasonable for it to take days to build a cache of your entire mailbox. If you try another client like Mail.app or Thunderbird, you'll notice that it can also take days for them to download millions of messages. There are connection limits on most IMAP servers, and messages have to be fetched in small batches.

That said, N1 opens multiple IMAP connections to your mail provider and "initial sync" is very different from "incoming mail delay". We actually hold a separate connection open for the Inbox, so you should receive new mail in a few seconds or less (though that's still slow—it's something our sync team is actively profiling and working to improve.)

Hope that helps! If you can clarify which performance issues make it unusable, we can improve those.

**Comment by tomgenoni** [comment]
Thanks. I'm using it with a gmail account. Is it possible to just get the email headers of each file, populating the folder/label with the contents, and later populating the whole message? Not sure if that's what Mail does but regardless it loads (or appears to load) considerably faster.

**Comment by mbilker** [comment]
I noticed a week ago the time to receive was faster than it is now. I liked having the email show up in N1 within 5 seconds, now it is more like 1 minute.

**Comment by tomgenoni** [comment]
FWIW, I was just trying out Spark for iOS and from a virgin state it listed my 15,000+ gmail Archive almost instantly. It appeared to pull in the last 50 emails or so and loads additional batches as I scrolled. I found this to be the case with Mailbox too. I

**Comment by tomgenoni** [comment]
I'll mark this closed since you're already working on it.

**Comment by dirtyhenry** [comment]
I can only agree to this. I've been trying Nylas N1 for a week now and find it unusable for performance issues (for both fetching emails and throwing archiving/next message actions).

**Comment by DoWhileGeek** [comment]
+1, its quite annoying hearing my phone get the email a few minutes before the nylas client.

**Comment by mbilker** [comment]
@DoWhileGeek what provider is your mail from? I hear Nylas N1 ping me 5 seconds after my phone and watch notify me.

**Comment by DoWhileGeek** [comment]
@mbilker gmail.

**Comment by dirtyhenry** [comment]
I launched Nylas more than 10 minutes ago and it is only showing 5 of the ~40 messages from my Gmail inbox.

**Comment by yanivby** [comment]
Same here. Launched on OS X, retrieving my Google Apps Inbox is taking literally hours (my inbox has only 66 messages).

**Comment by coolgoose85** [comment]
Same here. Tried gmail today and it is taking hour to emails on mac as compared to outlook. Outlook was very very quick

**Comment by mahmoud1973** [comment]
Same here .. Slow like hell fetching only 16 emails in inbox / 40 in Junk. ( hotmail account ). I don't know why you guys waste our time with your app since you don't even have a sync button !! ( I read the faq answer and it's says nothing to solve my problem ! ) 

The app says ( Hooray! you are done! ) in my inbox and I do have 16 new emails waiting for the lazy N1 to fetch them up!!!!

I can't believe you guys made such a good app and then fail in the most important part ( syncing emails on time !!!!!! ) Sorry to say this but this is ridiculous!!

**Comment by Siceberg** [comment]
My partner sent a mail at 12:45, I got it in Nylas at 13:30. It's too long and
unacceptable.
Can I set up check new message frequency?
