### ISSUE TITLE
Feature Request: Empty trash button

### ISSUE THREAD

**Issue by ryanstubbs** [nylas/N1#611]
One thing missing from N1 that I've found in other mail clients is the option to empty trash, or delete messages permanently.

In N1, the option doesn't show at the top, when selecting emails in the trash - although the backspace shortcut works, but seems to just move it to the archive instead.

I'd love if this feature was considered for N1.

**Comment by bengotow** [comment]
Hey @ryanstubbs — thanks, closing this as a dup of #599. I think we'll definitely try to get this in sometime soon.
