### ISSUE TITLE
Reload is required after saving a plugin in developer mode. 

### ISSUE THREAD

**Issue by plingampally** [nylas/N1#614]
I've been following the directions posted here: https://nylas.com/N1/getting-started/ 
> Replace the code here to change what shows up in the sidebar. See your changes happen live when you save!

However, I only see my changes after forcing a reload. I'm developing on OSX 10.10, testing with Gmail. 
I just wanted to make sure I have my dev environment correctly setup, as the live-reload feature makes me more productive.

**Comment by mbilker** [comment]
Live reload feature doesn't really work at the moment. I develop the mbilker/email-pgp plugin and luckily the Compile Cache features allows my builds to load within 5 seconds. I also can test to see if some change I made prevents the plugin from loading at startup.

**Comment by aszkid** [comment]
As far as I can see this is still not implemented. Any pointers on where to look if I want to work on this?
