### ISSUE TITLE
Closing fullscreen feedback window results in black fullscreen

### ISSUE THREAD

**Issue by weissazool** [nylas/N1#615]
Version: 0.3.27-1c2a936
Platform: Mac desktop client

Steps to reproduce:

1. App in fullscreen mode
- Click on (?), which opens the chat window in another (mostly empty) fullscreen
- CMD-W to close the window
- Black screen

**Comment by jstejada** [comment]
merging into #773

**Comment by jstejada** [comment]
thanks for reporting this @weissazool , it should be fixed with https://github.com/nylas/N1/commit/504d0522272bdb57f361b22d2bca1c85153d5ac2
