### ISSUE TITLE
Composer undo/redo buggy on OS X

### ISSUE THREAD

**Issue by seaneking** [nylas/N1#618]
On OS X, `cmd + z` and `cmd + y` undo/redo the last _two_ changes, and the menu items (edit -> undo/redo) do nothing.

**OS X:** 10.11.1
**N1:**  0.3.27-1c2a936

**Comment by grinich** [comment]
Hi @seaneking -- I can't reproduce this. Can you attach a gif or movie with more info?

**Comment by seaneking** [comment]
Either I'm going crazy or this was inadvertently resolved in one of the recent updates, because I can't reproduce now either. Sorry for the false alarm.
