### ISSUE TITLE
Undo delete causes (1) unread on inbox that is empty

### ISSUE THREAD

**Issue by aubreypwd** [nylas/N1#619]
![](https://cldup.com/ox819Ey0Oy.png)

- Using Gmail (what I'm using) delete a message from inbox
- Undo using CMD + Z
- Delete the email again
- Remaining (1) unread (blue) count

When I deleted it, undid that, read it, then deleted it again, I still have a persistent *Inbox (1)* even though I have no messages in my inbox. 

Even after getting a new email (after the above), and deleting that message, it still persists.

**Comment by aubreypwd** [comment]
Removing/Re-adding account fixed this short-term.

**Comment by olofsellgren** [comment]
I have the same problem.

* Using Gmail (two accounts)
* Clicked the x on the "Inbox x" label on top of new message
* Clicked undo on notification at the bottom

Archived all messages so my inbox is empty but I still have 1 unread.
Tried removing/re-adding the account and restarting but i still have 1 unread with empty inbox.

**Comment by mbilker** [comment]
Version of N1?

**Comment by aubreypwd** [comment]
`0.3.27-1c2a936 (0.3.27-1c2a936)`

**Comment by olofsellgren** [comment]
0.3.27-1c2a936

**Comment by mbilker** [comment]
Huh. A new release is going out very soon (0.3.29). I wonder if the fix is included in that.

**Comment by harismahmood89** [comment]
Hopefully - its driving me crazy lol

**Comment by bengotow** [comment]
Hey folks—sorry this has taken a while to get out. It was fixed on master earlier this week and will be in the `0.3.29` release when it hits the auto-updaters later tonight. Enjoy!

**Comment by jstejada** [comment]
referencing #704
