### ISSUE TITLE
Inbox count is inaccurate

### ISSUE THREAD

**Issue by zacs** [nylas/N1#622]
Not sure if the 28 in this screenshot is supposed to indicate all messages in inbox, or just unread, but either way it is incorrect. I've only got a single mailbox, and can confirm that the 8 messages in the inbox are accurate, and I've restarted the app several times. Running `Version 0.3.27-1c2a936 (0.3.27-1c2a936)` -- let me know if there are some logs or debug steps I can help with. 

![image](https://cloud.githubusercontent.com/assets/27705/11664413/79c4907a-9d96-11e5-943d-69cdf281dc3e.png)

**Comment by connorjsmith** [comment]
Can you try toggling read/unread on a message and see if the number changes?

**Comment by zacs** [comment]
No change when I toggle, and weirdly the incorrect count goes up and down with the new mail. I have 6 more messages in my inbox than when I opened the issue, and the incorrect count has incorrectly gone +4. 

![image](https://cloud.githubusercontent.com/assets/27705/11668157/6c86112c-9daa-11e5-8ffa-b889033b414f.png)

**Comment by jstejada** [comment]
hey @zacs, thanks for reporting this. This issue should be fixed in our upcoming release, so I'm going to close this. If you continue having problems feel free to reopen it

**Comment by jstejada** [comment]
referencing #704
