### ISSUE TITLE
max width of message cuts off text even fully expanded

### ISSUE THREAD

**Issue by sharadv1** [nylas/N1#623]
i received a nicely formatted message.  when i open it i see that i have to scroll to the right to read everything as the width of the box isn't great enough.  even when i full screen the message it is still not wide enough and N1 just adds white space around the message without increasing the width of the actual message content.
![screen shot 2015-12-08 at 11 40 36 am](https://cloud.githubusercontent.com/assets/16161297/11666288/9993c75e-9da0-11e5-9ca5-764a09e6be30.png)

**Comment by connorjsmith** [comment]
Looks like a css issue. As fun (lol) as those are to debug, it should be relatively simple. +1 to fixing this soon

**Comment by raknerak** [comment]
+1

**Comment by FrasSmith** [comment]
+1 It would be much better if the message container was defined as a percentage of the width, not fixed width.

**Comment by balsagoth** [comment]
+1

**Comment by hallamoore** [comment]
This is done-pending-release, but merging into #1775 until the release!
