### ISSUE TITLE
Nylas interrupts restart

### ISSUE THREAD

**Issue by meyer** [nylas/N1#624]
I just updated from to OSX 10.11.1 to 10.11.2. The OS installer requested a reboot and N1 cancelled it. N1 wasn’t quitting with command-Q, so I had to force-quit the app. The app was completely responsive, just not quitting.

**N1 version:** 0.3.27-1c2a936

![here u go](https://cloud.githubusercontent.com/assets/13781/11668652/3a057dac-9dad-11e5-9587-04c515344f88.png)

**Comment by bengotow** [comment]
Hey! I believe this has been fixed upstream in Electron. If you continue having this issue in the latest versions, feel free to reopen.
