### ISSUE TITLE
collapsable list of labels

### ISSUE THREAD

**Issue by kobak** [nylas/N1#625]
I used to use a lot of labels. There is an option to create even more labels, but I'd like to collapse/hide the list of my current labels. 
![screen shot 2015-12-08 at 23 19 11](https://cloud.githubusercontent.com/assets/6200/11670472/4210c498-9e02-11e5-96c2-94d087ef1a88.png)

**Comment by sergeyklay** [comment]
:+1:

**Comment by mbilker** [comment]
:+1: as well

**Comment by bengotow** [comment]
Hey! Are you interested in hiding / showing the entire section of the sidebar, essentially? I think we could do something like this (screenshot from Tower) and add a Show / Hide option.

![image](https://cloud.githubusercontent.com/assets/1037212/11677962/6d3b4cf6-9df8-11e5-9583-4ed053080344.png)

**Comment by kobak** [comment]
I'm happy with any solution. :)

**Comment by howieweiner** [comment]
I too have many, many labels. Nylas looks great, but I keep going back to Gmail in the browser as i can hide all labels except those with unread mail, plus keep a few of my labels as always showing. It would be great to have this feature in Nylas too

Nice work so far!

**Comment by emorikawa** [comment]
We have a new unified inbox beta that allows the collapsing of messages on the sidebar. I think this will significantly help with this issue!
