### ISSUE TITLE
slow first sync

### ISSUE THREAD

**Issue by kobak** [nylas/N1#626]
I added a Gmail account and after 20 minutes, mails just started to start to show up slowly. Not an app, but a sync issue. I'm on a mac for the record. thanks.

**Comment by akar1nchan** [comment]
wish project developer add proxy function

**Comment by mbilker** [comment]
@akar1nchan Proxy to the Sync Engine?

**Comment by akar1nchan** [comment]
@mbilker yes, such as http/https or socks custom proxy.

**Comment by mbilker** [comment]
@akar1nchan Hmm. Sounds interesting. I know that the [NylasAPI](https://github.com/nylas/N1/blob/master/src/flux/nylas-api.coffee#L57-L112) makes use of the `request` node package to make requests. It appears the `request` library supports [proxies](https://github.com/request/request#proxies) from the GitHub documentation.

**Comment by bengotow** [comment]
Hi @kobak — thanks for filing this. Usually, our sync engine downloads your inbox first, followed by other important folders like Sent Mail and Important. It looks like there was a bug and we weren't prioritizing your Inbox folder. Our backend team is fixing this right now. Your inbox should eventually sync (if you poke around, it probably started with a bad folder, like Junk.) We'll get this fixed for new users ASAP.

**Comment by kobak** [comment]
Thanks for the reply and solution.
