### ISSUE TITLE
unread count for multiple accounts

### ISSUE THREAD

**Issue by kobak** [nylas/N1#627]
I just added multiple accounts. (moving from Mailbox) and realized, there is no unread count for all the accounts, I have to check each account one-by-one for new arrivals. 

Unread count for multiple accounts is needed and a unified inbox would be a great addition, too. Thanks.

**Comment by mbilker** [comment]
Dupe. #537 for unified inbox. #468 for unified unread count.

**Comment by kobak** [comment]
Sorry, I did a search for multiple accounts, not for unified. Sorry. Can be closed.

**Comment by mbilker** [comment]
You can close this yourself by clicking Comment and Close.

**Comment by kobak** [comment]
Not (yet) a power user on github. Getting there. Sorry.

**Comment by mbilker** [comment]
@kobak It's alright. We all start at the beginning.

**Comment by kobak** [comment]
:)
