### ISSUE TITLE
Allow to send email as another email address I own

### ISSUE THREAD

**Issue by Ehesp** [nylas/N1#63]
On the GMail web client, I'm able to add other accounts I own, and subsequently select that email address when sending mails.

Under:` Settings > Accounts and Import > Send mail as:`

Then I'm able to select that account:

![example](https://cloud.githubusercontent.com/assets/842078/10389023/99c03d98-6e66-11e5-85ec-9722b3872df3.png)

**Comment by iBeliever** [comment]
:+1:

**Comment by vladislavivanistsev** [comment]
:+1:

**Comment by laughedelic** [comment]
+1

**Comment by bengotow** [comment]
Hey folks—this is on the roadmap, feel free to upvote it over here if you've got a Trello account: https://trello.com/c/KO2UHr0i/24-send-using-aliases

**Comment by jstejada** [comment]
referencing #414
