### ISSUE TITLE
Unable to create a query for items in the inbox

### ISSUE THREAD

**Issue by paulyoung** [nylas/N1#630]
When adding this to a plugin `0` is logged. If I remove `where(...)`, then `5564` is logged.

```coffeescript
DatabaseStore
  .findAll(Thread)
  .where([Thread.attributes.labels.contains('inbox')])
  .then (threads) ->
    console.log threads.length
```

I'm using 0.3.27-1c2a936 on OS X El Capitan 10.11.1 (15B42) with Gmail accounts.

**Comment by bengotow** [comment]
Hey! Thanks for filing this—I think the issue here is that you need to pass a label Id:

```
category = CategoryStore.getStandardCategory('inbox')
DatabaseStore
  .findAll(Thread)
  .where([Thread.attributes.labels.contains(category.id)])
  .then (threads) ->
    console.log threads.length
```

Let me know if that helps! We should definitely think about making this more clear in the API. Feel free to ping me on our community slack channel as well.

**Comment by paulyoung** [comment]
Thanks for the explanation!

It would be helpful if these docs were updated to reflect that: https://github.com/nylas/N1/blob/7000a1c71b8b548f88ff0a03f9bf502916df4a4e/docs/Database.md#retrieving-models

I actually had to do a bit of digging after `tags` caused an error too.
