### ISSUE TITLE
Feature Request: Vim/Emacs keybindings

### ISSUE THREAD

**Issue by connorjsmith** [nylas/N1#633]
Because a mouse is overrated. Use `dd` to delete an email, `CTRL+W` to switch focus between panes. `?` and `/` to search within the pane, `hjkl` for movement within the pane. Don't think any web client (except minimally gmail) offers this and I know all the Linux people would love it.

Similar could be done for emacs, maybe implement a decent keybinding/remapping system so we can support dvorak and customized layouts

**Comment by mbilker** [comment]
I am a Linux person and mostly use the mouse. I am too lazy to learn keyboard layouts. I know mostly Atom's key layout.

If you want to implement your own keybindings, its in Preferences. It is a similar system to what Atom uses.

**Comment by connorjsmith** [comment]
I'll have to investigate just how much I can change in the cson file, ideally every action should be bindable to a key sequence.

**Comment by mbilker** [comment]
The file is `~/.nylas/keymap.cson`. It is the same style as Atom, but the binding names are different. I believe you can get them by `grep`ing through the source.

**Comment by bengotow** [comment]
Hey! We currently support the full set of Gmail extended key bindings, so it should be straightforward to add another template (like https://github.com/nylas/N1/blob/master/keymaps/templates/Gmail.cson). I just don't know what the intended bindings are. If you want to try creating that file, I'd love a pull request!

**Comment by bengotow** [comment]
Merging in #87

**Comment by a-b** [comment]
It would be great to toggle shortcut help `?` - the same way as Gmail works

![image](https://cloud.githubusercontent.com/assets/585662/11732392/890a11e0-9f58-11e5-946c-33fca49c3118.png)

**Comment by mbilker** [comment]
You can view the keybinds in N1 Preferences.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
