### ISSUE TITLE
Additional 'Single Panel' Layout

### ISSUE THREAD

**Issue by muteone2** [nylas/N1#634]
I'd like the ability to use a view like the double panel layout, but with the left side panel that is visible in both single and double layouts hidden (like apple mail [it's hide-able]).

**Comment by mbilker** [comment]
Possible since `display: none` could be set on the sidebar to not display it, and not over-complicate the UI rendering code.

**Comment by bengotow** [comment]
Hey! We've talked about making the left panel visible all the time (ala Gmail). I think we may change this in an upcoming update—stay tuned :)

**Comment by bengotow** [comment]
Closing as a dup of #101
