### ISSUE TITLE
Database deleting and replacing after latest master.

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#635]
Database in recent N1 version creates issues when upgrading from older version. Possibly related to JSON processing changes in recent commits.

**Reproduction Steps:**

1. Install N1 from master or 0.3.29 release and use a database from 0.3.27
2. Launch N1
3. Watch as N1 loads everything slowly.
4. CPU usage on one core is 100% and the logs repeat similar messages once a second across multiple N1 processes
5. Wait for the `N1 is not responding` message to appear

**Expected behavior:**

N1 loads normally and no weird database related events occur.

**Observed behavior:**

N1 would somewhat start and the UI would load with the 3 dots for loading the message list, but no UI action would complete. In the log files the messages relating to `sqlite` deletes, replace, and select operations would occurring.

**N1 version:** 0.3.29-c993a1f
**OS and version:** Arch Linux 2015.12.8

**Installed packages:**

email-pgp: git@github.com:mbilker/email-pgp.git (master)

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes

I renamed the `~/.nylas` to `~/nylas-old`. Copied over the `config.cson` file and `dev` folder to `~/.nylas` file. When I restarted N1 after that it worked just fine and redownloaded the messages into a fresh `edgehill.db` file.

[Nylas-N1-18481.zip](https://github.com/nylas/N1/files/56298/Nylas-N1-18481.zip)

If the Nylas team needs the `electron.db` file or my `~/.nylas` folder I am happy to provide it in a secure transport medium.

**Comment by mbilker** [comment]
Huh. I upgraded my desktop, but no issue present. Though It did appear to do a similar thing, but more humanely. It loaded up and started re-downloading emails, events, contacts, etc like you would see during the initial download after account setup.

**Comment by bengotow** [comment]
Hey @mbilker — any chance you ran https://github.com/nylas/N1/commit/e275f353c1b226d582db3d9bc67a6d7bd5132029? There was one commit where we accidentally changed the serialization of `JSONBlob` objects, which caused a bunch of exceptions at launch. It was rolled back and fixed in a different way in the next few commits.

I moved my home laptop from 0.3.26 to 0.3.29 and it seems to be OK. Looking at those log files, it looks like it started downloading your mail data again from scratch... Hmm...

**Comment by mbilker** [comment]
@bengotow Yes, I ran that... Sorry about that. It said 'Syncing your mailbox...' in the bottom left, but I couldn't click on it and I was getting frequent `N1 is not responding` warning messages.

**Comment by mbilker** [comment]
Also, I tried out the Atom bug report form. I did leave out screenshots since I forgot to take them.
