### ISSUE TITLE
Feature: Mark Multiple Emails as Read

### ISSUE THREAD

**Issue by noahbuscher** [nylas/N1#639]
It would be great to select multiple emails and mark as read. Or better yet, allow an entire folder to be marked as read (right-click dialog?).

**Comment by bengotow** [comment]
Hi @noahbuscher — you can shift select or command-select multiple items in the message list and click this button to toggle read / unread. Hope that helps!

![image](https://cloud.githubusercontent.com/assets/1037212/11702804/822d0d0c-9e8e-11e5-8a08-c1956f517ad5.png)

**Comment by noahbuscher** [comment]
Ah! Great - didn't notice that. Thanks. 😄
