### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by noahbuscher** [nylas/N1#640]
I may have some time to do this one as well. Many API doc links are 404's and the docs are fairly simple, to say the least.

Also, the annotated code, while a great idea, is not exhaustive and does not cover everything in the plugins.

**Comment by jstejada** [comment]
Hey @noahbuscher , thanks for mentioning this. This is definitely on our to do list, and we will restructure  and update the docs pretty soon.

**Comment by grinich** [comment]
@noahbuscher would love your help doing this!

**Comment by noahbuscher** [comment]
:+1:

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
