### ISSUE TITLE
Bug: Website Header Broken in Safari

### ISSUE THREAD

**Issue by noahbuscher** [nylas/N1#641]
It appears that the website header is broken in the latest build of Safari on El Capitan. Chrome looks fine. Not tested mobile or in Firefox.

Safari:
![](http://noah.li/16aU2+)

Chrome:
![](http://noah.li/1cfV5+)

**Comment by bengotow** [comment]
Aww man... thanks for filing this, I'm able to reproduce this. Looks like we're missing a `white-space: nowrap` on that nav. Will get this fixed.
