### ISSUE TITLE
Can't do a vagrant up

### ISSUE THREAD

**Issue by screendriver** [nylas/N1#642]
If an Android emulator is running you can't do a `vagrant up`

```bash
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 5555 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 5555, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
```

If the vagrant box is already running you can't start the Android emulator. Can I change the port? If yes: how do I tell N1 to connect to the given port?

**Comment by mbilker** [comment]
Should this be here or on the nylas/sync-engine repository?

**Comment by screendriver** [comment]
Good question :question: I don't know :confused:

**Comment by mbilker** [comment]
Don't know what?

**Comment by jstejada** [comment]
hey @screendriver, I think this issue is not pertaining to N1 so I'm going to close it. If you want to run the sync-engine locally, you should configure your VM to run it on a different port, or configure your Android Emulator to run on a different port.

**Comment by screendriver** [comment]
> Don't know what?

this

> Should this be here or on the nylas/sync-engine repository?

I didn't know where to post this issue.

> you should configure your VM to run on a different port

Ok. I will try it out.

**Comment by alexandru-calinoiu** [comment]
This is a limitation of vagrant, the android emulator and vagrant will try to use the same virtualization mechanist and it won't be possible.

You can work around it using genymotion for example http://stackoverflow.com/questions/16168799/android-emulator-and-virtualbox-cannot-run-at-same-time

**Comment by screendriver** [comment]
Oh ok. So it's not a simple port problem? Sad to hear. Then I have to try [genymotion](https://www.genymotion.com).

Thank you for that information :+1:

**Comment by mbilker** [comment]
@screendriver genymotion uses Virtualbox I thought?

**Comment by screendriver** [comment]
I don't know. I've never tried genymotion before.

**Comment by mbilker** [comment]
@screendriver I made an edit to my post.

**Comment by screendriver** [comment]
:+1:
