### ISSUE TITLE
N1 don't load email messages

### ISSUE THREAD

**Issue by vergani** [nylas/N1#643]
After configuring my exchange account in Nylas, my imap folders appears, but any message is showed.

![screenshot from 2015-12-09 08-54-13](https://cloud.githubusercontent.com/assets/5296727/11683516/722feb4a-9e52-11e5-9fef-136ec7468e80.png)

Thanks

**Comment by vergani** [comment]
This is the detailed log:

{"host":"supti-linux","timestamp":"2015-12-09T11:05:29.531Z","payload":["ActionBridge: default Action Bridge Received: db-store-trigger"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.113Z","payload":["0: PRAGMA main.page_size = 8192;"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.115Z","payload":["0: PRAGMA main.cache_size = 20000;"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.115Z","payload":["0: PRAGMA main.synchronous = NORMAL;"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.118Z","payload":["6: PRAGMA journal_mode = WAL;"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.118Z","payload":["8: PRAGMA user_version"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.121Z","payload":["0: SELECT `Folder`.`data` FROM `Folder`  WHERE `Folder`.`account_id` = '6hqr5joav85khjql3a9i2lgmp'  "]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.254Z","payload":["0: SELECT `Folder`.`data` FROM `Folder`  WHERE `Folder`.`account_id` = '6hqr5joav85khjql3a9i2lgmp'  "]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.256Z","payload":["0: SELECT `data` FROM `JSONObject` WHERE key = ? LIMIT 1"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.262Z","payload":["0: SELECT `data` FROM `JSONObject` WHERE key = ? LIMIT 1"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.281Z","payload":["0: SELECT `data` FROM `JSONObject` WHERE key = ? LIMIT 1"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.284Z","payload":["0: SELECT `data` FROM `JSONObject` WHERE key = ? LIMIT 1"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.299Z","payload":["1: SELECT COUNT(*) as count FROM `Message`  WHERE `Message`.`account_id` = '6hqr5joav85khjql3a9i2lgmp' AND `Message`.`draft` = 1  "]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.308Z","payload":["0: SELECT `Message`.`data`, IFNULL(`MessageBody`.`value`, '!NULLVALUE!') AS `body`  FROM `Message` LEFT OUTER JOIN `MessageBody` ON `MessageBody`.`id` = `Message`.`id` WHERE `Message`.`account_id` = '6hqr5joav85khjql3a9i2lgmp' AND `Message`.`draft` = 1  ORDER BY `Message`.`date` DESC LIMIT 100"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.310Z","payload":["0: SELECT `Contact`.`data` FROM `Contact`  WHERE `Contact`.`account_id` = '6hqr5joav85khjql3a9i2lgmp'  "]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.326Z","payload":["0: SELECT COUNT(*) as count FROM `Message`  WHERE `Message`.`draft` = 1 AND `Message`.`account_id` = '6hqr5joav85khjql3a9i2lgmp'  "]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.327Z","payload":["0: SELECT COUNT(*) as count FROM `Thread` INNER JOIN `Thread-Folder` AS `M8` ON `M8`.`id` = `Thread`.`id` WHERE `Thread`.`account_id` = '6hqr5joav85khjql3a9i2lgmp' AND `M8`.`value` = '2b4mz0k61xrf0zuflcdsiw6m5'  "]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:30.327Z","payload":["0: SELECT `Thread`.`data` FROM `Thread` INNER JOIN `Thread-Folder` AS `M8` ON `M8`.`id` = `Thread`.`id` WHERE `Thread`.`account_id` = '6hqr5joav85khjql3a9i2lgmp' AND `M8`.`value` = '2b4mz0k61xrf0zuflcdsiw6m5'  ORDER BY `Thread`.`last_message_received_timestamp` DESC LIMIT 100"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:32.413Z","payload":["ActionBridge: default Action Bridge Received: db-store-trigger"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:35.415Z","payload":["ActionBridge: default Action Bridge Received: db-store-trigger"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:38.419Z","payload":["ActionBridge: default Action Bridge Received: db-store-trigger"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:41.418Z","payload":["ActionBridge: default Action Bridge Received: db-store-trigger"]}
{"host":"supti-linux","timestamp":"2015-12-09T11:05:44.422Z","payload":["ActionBridge: default Action Bridge Received: db-store-trigger"]}

**Comment by mbilker** [comment]
Please put the log inside \`\`\` block.

**Comment by vergani** [comment]
mbilker, log updated

**Comment by mbilker** [comment]
Hmm. Nothing stands out in the log. Just a log of the SQL queries. What does the Activity Window show (`Developer -> Open Activity Window`)?

**Comment by bengotow** [comment]
Hi @vergani — thanks for filing this. Usually, our sync engine downloads your inbox first, followed by other important folders like Sent Mail and Important. It looks like there was a bug and we weren't prioritizing your Inbox folder because it's been localized into Portuguese. Our backend team is fixing this right now. Your inbox should eventually sync (if you poke around, it's probably off retrieving mail in your Junk folder or something like that.), and we'll get this fixed for people in the future!
