### ISSUE TITLE
Google calendar RSVP spamming inviter

### ISSUE THREAD

**Issue by vpakg** [nylas/N1#644]
When responding to a google calendar event through the email, inviters receive multiple emails with the same response. A co-worker invited me for two separate events and got 12 replies back (one each day) for each event with the same content.

Edit: Still happening as of this morning for an event that has already passed. 

![drk](https://cloud.githubusercontent.com/assets/4654583/11687663/f85135f0-9e55-11e5-8666-d5a66f748164.png)

**Comment by vpakg** [comment]
It seems to be happening every time I open the email, even though the even  has been delete from Google Calendar.

**Comment by grinich** [comment]
Hi @vpakg -- what N1 version are you using? This should be fixed as of last week. (There was a momentary bug.)

**Comment by vpakg** [comment]
Hi @grinich , I'm using version 0.3.26-c1ce330

**Comment by grinich** [comment]
I believe this was fixed in a release that erroneously wasn't pushed to the Linux update server. We'll be pushing a release in the next couple of days which will address this and more. 

Thanks and sorry for the hassle!
