### ISSUE TITLE
Issue: Keyboard shortcut to archive messages

### ISSUE THREAD

**Issue by prisonpolicy** [nylas/N1#645]
There should be a keyboard shortcut to archive messages.  (There is a button, but not clear way to access that from the keymap.cson file or Mac system settings.)

**Comment by noahbuscher** [comment]
You can with Cmd+Ctrl+E using the Apply Mail prefs :smile_cat: 

See [here](https://github.com/nylas/N1/blob/master/keymaps/templates/Apple%20Mail.cson#L12).

**Comment by prisonpolicy** [comment]
Brilliant. (And I think I can figure out how to find the names of other
commands.) Thank you.

> On Dec 9 2015, at 4:51 pm, Noah Buscher &lt;notifications@github.com&gt;
wrote:  

>

> You can with Cmd+Ctrl+E using the Apply Mail prefs ![:smile_cat:](https
://assets-cdn.github.com/images/icons/emoji/unicode/1f638.png)

>

> See [here](https://github.com/nylas/N1/blob/master/keymaps/templates/Apple%2
0Mail.cson#L12).

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/645#issuecomment-163405429).![](https://github.com/notifications/beac
on/AEYFgC-ZLhCK-dzVy7K7EGK5pkmZ1DGwks5pOJnOgaJpZM4GyHRu.gif)

**Comment by noahbuscher** [comment]
Sure!

**Comment by jstejada** [comment]
@noahbuscher thanks! I'm going to go ahead and close this issue
