### ISSUE TITLE
Select-all behaviour is causes issues in two panel mode

### ISSUE THREAD

**Issue by meyer** [nylas/N1#647]
Two things:
1. Hitting command-A brings up multi-select options, but doesn’t clear the message pane and corresponding options. I would think the message view should change to something informative about what is currently selected.
2. Hitting command-A selects message text as well as all visible messages.

Here’s a screenshot of both issues:
![image](https://cloud.githubusercontent.com/assets/13781/11700692/2c8533ce-9e80-11e5-96bc-e7a64050e746.png)

**Comment by grinich** [comment]
Definitely a bug. We're going to change a bunch of stuff around keybindings soon.

**Comment by emorikawa** [comment]
I'm merging this issue into #886. All of the select-all issues are related to an ongoing fix to better address keymaps and menus. We'll be updating #886 with the status of that fix.
