### ISSUE TITLE
Use External Theme W/O Dev Flags

### ISSUE THREAD

**Issue by noahbuscher** [nylas/N1#648]
Is there any way to enable an external theme without using dev flags? 

Asking as I just finished [this](http://github.com/noahbuscher/N1-Taiga) and would like users to be able to install it without much hassle.

**Comment by bengotow** [comment]
Hey @noahbuscher — that looks great! We definitely want people to be able to install it without enabling developer mode. I'll try installing this on a few machines this evening and see what's going on.

**Comment by noahbuscher** [comment]
Thank you! Just ping me if you need help with anything. :tada:

**Comment by bengotow** [comment]
Just a quick update—the theme loads fine for me without developer mode, but you do have to manually edit your config file to turn it on, even after "Enabling" it in the Plugins view.

We'l be revisiting the plugins interface soon to add support for themes. I'll keep you posted and see if we can make this easier soon!

**Comment by mbilker** [comment]
@noahbuscher Is there a roadmap for a dark mode? I really like the theme! The N1 official dark mode bugs me (I probably should submit my own PR's).

**Comment by noahbuscher** [comment]
@mbilker Definitely. For sure by this Saturday! :+1:

**Comment by mbilker** [comment]
@noahbuscher Alright! I need to pound a bug in my `email-pgp` plugin. Now with the recent N1 changes, I need to handle some new cases that prevent decryption. I digress sometimes.

**Comment by noahbuscher** [comment]
@mbilker I really want to build that snooze plugin but cross device compatibility would be such a headache. Also - I'm working on a Giphy plugin. Details soon. 😜

**Comment by mbilker** [comment]
@noahbuscher Ooh. A plugin I can test for encryption compatibility and how the `MessageBodyProcessor` can handle multiple plugins, and how the order matters for execution for my plugin.

**Comment by noahbuscher** [comment]
@mbilker Teamwork 🙌🏼

**Comment by mbilker** [comment]
@noahbuscher Yeah. I just have a lot of work to do on my plugin.

**Comment by noahbuscher** [comment]
@mbilker Yes - yours seems quite a bit more complex than the one I have in mind. I just need to run some API reqs and throw an img elem in the draft.

**Comment by mbilker** [comment]
@noahbuscher Pretty simple. The `Translate` example would be a good start.

**Comment by mbilker** [comment]
@noahbuscher My `Composer` extension would be good for that. https://github.com/mbilker/email-pgp/blob/master/lib/composer/composer-loader.es6 is the main file for changing the contents of the composer. Does not work on separate windows yet. Loaded in https://github.com/mbilker/email-pgp/blob/master/lib/main.es6#L47.

**Comment by noahbuscher** [comment]
@bengotow Ah! Thanks!

**Comment by noahbuscher** [comment]
@mbilker Thanks for the links! I'll check them out!

**Comment by mbilker** [comment]
@noahbuscher You are most certainly welcome.
