### ISSUE TITLE
Contractions are marked as misspellings

### ISSUE THREAD

**Issue by cperryk** [nylas/N1#649]
The title says it all!

https://www.dropbox.com/s/w7gj92nxtnqauq5/Screenshot%202015-12-09%2020.51.08.png?dl=0

**Comment by grinich** [comment]
For posterity: 
<img width="803" alt="screenshot 2015-12-09 20 51 08" src="https://cloud.githubusercontent.com/assets/92417/11763841/96270f36-a0cf-11e5-98b2-b6695e518d43.png">

**Comment by phoenixeliot** [comment]
More detail: It treats the part before the apostrophe as its own separate word. So these are marked correct: don't, won't, can't; but these are incorrect: doesn't, wasn't, shouldn't

**Comment by bengotow** [comment]
Hey! This should be fixed in the 0.3.45. Feel free to re-open if you encounter this issue again.
