### ISSUE TITLE
Linux download link is broken

### ISSUE THREAD

**Issue by prasannatsm** [nylas/N1#651]
Not able to access the linux download. The page says access denied / malformed XML.

**Comment by RealOrangeOne** [comment]
The page is actually an 'Access Denied' error from AWS, where I presume the `.deb` file is hosted. It would be nice if this could either be fixed, or added to a proper PPA for the distro.

**Comment by mbilker** [comment]
Or the deb posted to the GitHub releases page.

**Comment by sergeyklay** [comment]
+1 for PPA

**Comment by emorikawa** [comment]
This is fixed now. You can get the build here: https://invite.nylas.com/download/?platform=linux
Although we are planning a new release within the next few hours, so I'd recommend until waiting until later today.

**Comment by XescuGC** [comment]
For me it's happening the same but in OSX with the XLSX, it downloads them as malformed and there is no way to open them, I have to go to Gmail and download them from there.

N1 version: Version 0.4.5-b0ec335 (0.4.5-b0ec335)
OSX version: 10.10.5

Do i open a new Issue?

**Comment by mbilker** [comment]
@XescuGC Yes open a new issue. I think you misunderstood this issue. This issue is for the Linux download link on https://www.nylas.com/N1.

**Comment by XescuGC** [comment]
Sorry for the misunderstood :( #1240
