### ISSUE TITLE
unable to delete draft

### ISSUE THREAD

**Issue by csimonmoi** [nylas/N1#653]
I cannot delete drafts they are 8 and when I try to delete it says "Unable to delete drafts, restoring" and again they appear magically.
I had the same problem in my inbox, I could not delete 2 email. They appear unread, I touched them with my mouse they became "read" and suddenly appear back the blue point to indicate it was unread again. If I tried to delete them they appear again in my inbox.
What's happening?

**Comment by grinich** [comment]
@csimonmoi are you still having this issue?

**Comment by sebescudie** [comment]
hi,

Don't know if it's ok to comment on an old issue but i'm having the same problem as csimonmoi. Using version 0.3.45 on Win7/x64.

Thanks !

**Comment by grinich** [comment]
I'm going to close this as stale. Please re-open if this issue is still occurring in 0.4.25 and newer.
