### ISSUE TITLE
Show hyperlink targets on link/button rollover

### ISSUE THREAD

**Issue by jaymiethomas** [nylas/N1#655]
Feature request:
When assessing whether an email is genuine, I'll rollover the links for any calls to action to see which underlying domain the link is targeting.  As far as I can see, there's no way to currently do this in N1.

**Comment by bengotow** [comment]
Hey! If you hover over links, you should see something like in N1. It's possible that it's not working for some particular emails, though.

Also, do you see tooltips when you hover over buttons in the toolbar, like compose? It may be broken on your platform.

![image](https://cloud.githubusercontent.com/assets/1037212/11723236/264bd61e-9f22-11e5-9525-ba31537327ca.png)

**Comment by jaymiethomas** [comment]
Hey, thanks for that - yeah, I do with straight hyperlinks (I guess I wasn't being patient enough for them to appear!).  I'll check out button images next time I get an email with them in (shouldn't be long!).
