### ISSUE TITLE
Cannot send mails for Office 365 accounts

### ISSUE THREAD

**Issue by malcobev** [nylas/N1#658]
For Office 365 accounts, I add them as Outlook accounts. In this case all outgoing mails give an error & fail to send. 
![screenshot 2015-12-10 20 25 21](https://cloud.githubusercontent.com/assets/16242136/11718512/58e26bf6-9f7c-11e5-923f-9cc2294f74d8.png)

**Comment by spang** [comment]
Hi @malcobev, are you able to share what email address this affecting? (You can also email support@nylas.com if you don't want to post publically.) Has this happened on more than one account?

**Comment by jackiehluo** [comment]
Closing this issue for now since it should be fixed—let us know if it's not!
