### ISSUE TITLE
Reply/Forward icons should be left-aligned

### ISSUE THREAD

**Issue by MariusMasalar** [nylas/N1#659]
This is a design thing, but I think it would be preferable to have the Reply/Forward buttons have left-aligned text rather than right-aligned as in the screenshot:
![right-aligned-buttons](https://cloud.githubusercontent.com/assets/1610077/11728216/9a0305d0-9f56-11e5-859f-f3ceaf10b8bb.png)

Looks messy with the icons in different places, and left-aligning would be consistent with the Gmail interface as well.

**Comment by grinich** [comment]
:+1:
