### ISSUE TITLE
Feature Request: Send using email aliases

### ISSUE THREAD

**Issue by a-b** [nylas/N1#662]
This feature should allow user to use multiple email addressses under one Gmail accout.

![image](https://cloud.githubusercontent.com/assets/585662/11732546/199b77d4-9f5a-11e5-8acd-686cf6685210.png)

![image](https://cloud.githubusercontent.com/assets/585662/11732587/835b7d90-9f5a-11e5-8bdb-bce5721a2f8a.png)

**Comment by jstejada** [comment]
hey @a-b, thanks for contributing. we actually just landed an initial version of this, and it should be included soon in an upcoming release.

<img width="843" alt="aliases" src="https://cloud.githubusercontent.com/assets/1271509/11733110/3185f54a-9f5f-11e5-8c54-5ece3c9f207f.png">

![screenshot 2015-12-10 16 59 45](https://cloud.githubusercontent.com/assets/1271509/11733144/795fb5ae-9f5f-11e5-8cd2-cf216378a328.png)

**Comment by a-b** [comment]
Thanks!

**Comment by liyaodong** [comment]
Cool !!!

**Comment by bilby91** [comment]
+1

**Comment by sergeyklay** [comment]
:+1:

**Comment by digitalextremist** [comment]
:+1:

**Comment by grinich** [comment]
Closing because this is done!

**Comment by zlatkobijelic** [comment]
I was just thinking about this feature the other day, so glad to see this!!! Thanks!!!

**Comment by digitalextremist** [comment]
Woooooohooooooo

**Comment by vladislavivanistsev** [comment]
Great!

**Comment by matthewdewstowe** [comment]
Hello.  How does this work.  I am using the recent cleint on Mac.  I have an alias set up in my Gmail account but I cannot see it on the drop down.  Please advise.
