### ISSUE TITLE
Linux Spellchecker not loading language dictionary properly

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#663]
The `Spellchecker` under Linux requires the directory where the dictionaries are used. The `Spellchecker` by default sets the language to `en_US` when you initialize the class ([ref](https://github.com/atom/node-spellchecker/blob/master/lib/spellchecker.js#L23)), and the `Spellchecker` requires a second argument with the directory to the `hunspell` dictionaries under linux ([ref](https://github.com/atom/node-spellchecker/blob/master/lib/spellchecker.js#L8)). N1 sets the language on initialization of the `NylasSpellchecker` class ([ref](https://github.com/nylas/N1/blob/7d56b6828a223aace6f0d035eb48c68c533bf376/src/nylas-spellchecker.coffee#L8)), but fails to provide the second argument to the `Spellchecker::setLanguage` function ([ref](https://github.com/nylas/N1/blob/7d56b6828a223aace6f0d035eb48c68c533bf376/src/nylas-spellchecker.coffee#L29)).

**Reproduction Steps:**

1. Load N1 under Linux
2. Start typing jibberish.
3. Note the lack of red underlines.
4. In DevTools, a call to `$n.NylasSpellchecker.isMisspelled('hhh')` returns false, but:
```javascript
var spellcheck = new (require('spellchecker').Spellchecker);
spellcheck.setDictionary('en_US', '/usr/share/hunspell') === true; // Could use the hack method getDictionaryPath from node-spellchecker to get path internal to installed N1
spellcheck.isMisspelled('hhh') === true;
spellcheck.isMisspelled('hello') === false;
```

**Expected behavior:**

N1 marks incorrect words with red underlines similarly to Chrome's spellcheck.

**Observed behavior:**

N1 fails to load the dictionary file for spellcheck, and no words are marked as incorrect.

**Screenshots and GIFs**

![2015-12-10-225001_1280x800_scrot](https://cloud.githubusercontent.com/assets/1266541/11735575/b639dc44-9f90-11e5-91a8-6c849840488a.png)
![2015-12-10-224627_636x608_scrot](https://cloud.githubusercontent.com/assets/1266541/11735583/cc591cba-9f90-11e5-8a2f-4c9e354ec7c1.png)

**N1 version:** 0.3.29
**OS and version:** Arch Linux 2015.12.10

**Additional information:**

* Problem started happening recently, didn't happen in an older version of N1: Yes, but because of default setting to en_US, even for non English users.
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by mbilker** [comment]
Working on this over at [mbilker/N1@spellchecker-fix](https://github.com/mbilker/N1/tree/spellchecker-fix).

**Comment by mbilker** [comment]
Hmm. I need to take a look at the specs, my Travis linux failures after the `spellchecker-fix` merge into [mbilker/N1](https://github.com/mbilker/N1) are:
```
NylasSpellchecker
  when we don't recognize the language
    it always says words are spelled correctly
      Expected true to be false. (spec/spellchecker-spec.coffee:64:63)
    it never provides corrections
      Error: Bad argument
        Error: Bad argument
        at Error (native)
        at Object.getCorrectionsForMisspelling (/home/travis/build/mbilker/N1/node_modules/spellchecker/lib/spellchecker.js:41:57)
        at NylasSpellchecker.getCorrectionsForMisspelling (/home/travis/build/mbilker/N1/src/nylas-spellchecker.coffee:106:58)
        at NylasSpellchecker.getCorrectionsForMisspelling (/home/travis/build/mbilker/N1/src/nylas-spellchecker.coffee:3:59)
        at [object Object].<anonymous> (/home/travis/build/mbilker/N1/spec/spellchecker-spec.coffee:67:34)
  when we do recognize the language
    it provides options for misspelled words
      Expected [ 'asked', 'acidify', 'Assad' ] to equal [  ]. (spec/spellchecker-spec.coffee:96:80)
```

Which is weird how the `when we do recognize the language` error works under Mac OS X and provides no suggestions. I will investigate the `Bad Argument` error.

**Comment by emorikawa** [comment]
Hey @mbilker I cherry-picked your spellchecker-fix branch and landed them on master. Thanks for diving into that. We're putting together a couple of other changes for a patch release now and testing (on Linux too!).

**Comment by mbilker** [comment]
@emorikawa Thanks! I really wanted Travis to work, which was my motivation.
