### ISSUE TITLE
Use rubber banding for the list and email body

### ISSUE THREAD

**Issue by KrauseFx** [nylas/N1#665]
Use rubber banding scrolling effect for the list and email body

**Comment by bengotow** [comment]
Hey! Unfortunately I don't think this is possible in overflow regions in the Chromium Embedded Framework. If we're able to do it in the future, I'll let you know.

**Comment by bengotow** [comment]
Hey—just wanted to add, I think this is blocked on this Chromium ticket: https://code.google.com/p/chromium/issues/detail?id=546520&q=label%3Aos-mac&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&start=100. It supports rubber band scrolling for the document body, but not for scroll regions defined by divs with `overflow:scroll`, or iFrames.
