### ISSUE TITLE
New windows open on second display

### ISSUE THREAD

**Issue by martunta** [nylas/N1#667]
New windows (compose new email, add account) always open on second display (in two and three display setups). They always open on second display, regardless on which display main window of N1 is on - first, second or third.

I am using Ubuntu, issue appears both in 15.04 and 15.10.

**Comment by mbilker** [comment]
What is your primary display in Xorg? The NVIDIA drivers on my desktop allow for the main display to be set, which affects the location of indicators and the initial numbering of workspaces under `i3`.

I am at school right now and cannot access my desktop computer to see which workspace the windows appear.

**Comment by martunta** [comment]
it is the same behavior on laptop with dock/3 displays and intel video, and on desktop with nvida and 2 displays. It opens on second display according to Unity display settings, on both computers.

**Comment by bengotow** [comment]
Hey folks—closing this as a dup of #58. Really need to fix this, but I think we may still be blocked on Electron.
