### ISSUE TITLE
Fail to close feedback window on Ubuntu platform

### ISSUE THREAD

**Issue by PhoenixFlying** [nylas/N1#668]
Hi all,
I met this issue from time to time. When I just clicked down the "X" button on the feedback window, nothing happened but I could still normally close the main windows behind it. The Linux command "$ kill -9 PID" can help me to shut down the feedback window when the issue happened. I wonder if any other user has met the same problem?

Version: 0.3.29-1904c6f
Platform: Ubuntu 14.04.3 64bit LTS

**Comment by Froglich** [comment]
For me, pressing the X now closes the window (Ubuntu GNOME 15.10), however, choosing "Exit" from the menu closes the main window instead. Adding a new issue about this.

**Comment by jstejada** [comment]
merging into #773
