### ISSUE TITLE
Update hangs/fails to install (0.3.27 -> 0.3.29) on OSX Yosemite 

### ISSUE THREAD

**Issue by Joe8Bit** [nylas/N1#669]
Running 0.3.27 and attempting to install the 0.3.29 via both the 'Install Now' in the nagbar and the `File > Restart and Install Update` menu item and the install hangs and doesn't seem to complete.

This occurs both with and without Debug Flags on. With them on nothing is logged to the console. As far as I can see there's nothing logged in the various `/Nylas-N1-*.log` files that would indicate a failure (or anything related to installing the update, come to that) searched for via some inelegant and ignorant grep'ing. I would post these logs, but am unsure whether they contain PII or sensitive info so better to be safe than sorry!

```
OSX Yosemite 10.10.4
MacBook (Retina, 12-inch, Early 2015)
1.1 GHz Intel Core M
8 GB 1600 MHz DDR3
```

Video of bug: https://www.youtube.com/watch?v=la5pH1D8E4Y

**Comment by bengotow** [comment]
Hi @Joe8Bit — this is really strange... it seems like the app is failing to quit properly to begin the update process. Can you try clicking "Install Now" and then force-quitting the app, and let me know if that works? I'll see if I can reproduce this with 0.3.27.

**Comment by JesseObrien** [comment]
Can confirm I'm seeing the exact same bug.

```
OSX Yosmite 10.10.5
MacBook Pro (Retina, 13-inch, Mid 2014)
2.6 GHz Intel Core i5
Nylas Version 0.3.27-1c2a936 (0.3.27-1c2a936)
```

**Comment by Joe8Bit** [comment]
@bengotow interestingly, force quitting after hitting 'Install Now' had some effect

1. Hit 'Install Now' in `.27`
2. App psuedo-quits as before
3. Force quit app
4. It force quits without issue
5. Reopen app, the nag bar is gone (it showed up right away in the previous non-force-quit case). However the version is still `0.27`.
6. After 30 second the nag bar shows up again promoting me to upgrade to `0.29`

However, after clicking the nag bar again the app quits correctly (not the psuedo-quit) after reopening the app still hasn't updated to `0.29` and the 30 second delayed update nagbar thing happens again.

Is there any other debugging or logging I can do to assist?

**Comment by Joe8Bit** [comment]
After getting prompted for the 0.3.32 update, it updated as expected with no repeated of the above behaviour. Seems this has resolved itself. Closing the issue.
