### ISSUE TITLE
Non-English Spell Checker

### ISSUE THREAD

**Issue by csimonmoi** [nylas/N1#670]
Hi
You just released your last update and I do not see any spell checker function on my client. I do not see any red lines under my language (italian) but if I do some mistakes nothing happens and there is no check at all.
Another thing, if I am writing a new email, your client creates new drafts (not a single one, but 2 o 3) and after sending that email, drafts are still there and I have to delete them manually.
Thanks

**Comment by mbilker** [comment]
OS? Linux has issues that I am working on.

**Comment by csimonmoi** [comment]
<br  
Windows

> On Dec 11 2015, at 4:47 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> OS? Linux has issues that I am working on.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-163969369).![](https://github.com/notifications/beac
on/APTadl192esRMYArY3g-uGdPnrkOyiTUks5pOud5gaJpZM4GzjgU.gif)

**Comment by mbilker** [comment]
What version of Windows (7/8/8.1/10)? Version of N1 (visible under Help, not copyable right now)?

**Comment by csimonmoi** [comment]
Last one N1 version : 0.3.29

  

Windows 10

  

Thanks

  

> On Dec 11 2015, at 4:50 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> What version of Windows (7/8/8.1/10)? Version of N1 (visible under Help, not
copyable right now)?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-163970244).![](https://github.com/notifications/beac
on/APTadux_-m3T0FPGLS7dlfJuYeemf5F_ks5pOugtgaJpZM4GzjgU.gif)

**Comment by emorikawa** [comment]
@csimonmoi The lack of sqwiggles is likely due to us not detecting a dictionary for your language. On Windows we defer to the native [Windows Spell Checking API](https://msdn.microsoft.com/en-us/library/windows/desktop/hh869853(v=vs.85).aspx). That API lets us know what languages are available

You can see what languages you support by looking in:

`C:\Users\YourName\AppData\Roaming\Microsoft\Spelling`

On my computer I only have an `en-US` folder. I believe Windows sets these up when you configure your computer.

When I tested on my Windows 10 machine Italian was not in my list of supported languages. We recently changed the behaviour to disable spellcheck if we don't recognize the language. Before this change we would erroneously force an English dictionary on foreign speakers.

As far as the draft issue is concerned. We are addressing an issue related to multiple drafts being created.

**Comment by csimonmoi** [comment]
Hi thanks for your answer

as you can see in my snapshot attached here Italina laguage is in my machine,
in the folder you mentioned.  

But still does not work, in italian but in English too.

as a matter of fact I am writing right now in Nylas client and if I make a
mistake like this shfsdfdhfsdhfsdjh, nothing happens.

waiting for your reply.

Thanks

<br  

> On Dec 11 2015, at 9:01 pm, Evan Morikawa &lt;notifications@github.com&gt;
wrote:  

>

> [@csimonmoi](https://github.com/csimonmoi) The lack of sqwiggles is likely
due to us not detecting a dictionary for your language. On Windows we defer to
the native [Windows Spell Checking API](https://msdn.microsoft.com/en-
us/library/windows/desktop/hh869853\(v=vs.85\).aspx). That API lets us know
what languages are available

>

> You can see what languages you support by looking in:

>

> C:\Users\YourName\AppData\Roaming\Microsoft\Spelling

>

> On my computer I only have an en-US folder. I believe Windows sets these up
when you configure your computer.

>

> When I tested on my Windows 10 machine Italian was not in my list of
supported languages. We recently changed the behaviour to disable spellcheck
if we don't recognize the language. Before this change we would erroneously
force an English dictionary on foreign speakers.

>

> As far as the draft issue is concerned. We are addressing an issue related
to multiple drafts being created.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-164035086).![](https://github.com/notifications/beac
on/APTadlMzM1ka9p7TjFcvjRuMqQNdXHvIks5pOyMSgaJpZM4GzjgU.gif)

**Comment by dylntrnr** [comment]
After the latest update, I also have no spellchecker. I'm guessing this is because I have spanish and english setup as possible languages. How can I get Nylas to recognize the current language? Thank you.
<img width="359" alt="screen shot 2015-12-15 at 13 58 25" src="https://cloud.githubusercontent.com/assets/2652938/11822418/1409df30-a334-11e5-907b-e936d75a52b1.png">

**Comment by mbilker** [comment]
@dylntrnr in the Developer Tools (`Developer -> Toggle Developer Tools`), what is the result of `navigator.language` and `navigator.languages`?

Also, try the latest version of N1 (0.3.32-b11131d, [link for OS X](https://edgehill.s3-us-west-2.amazonaws.com/0.3.32-b11131d/darwin/x64/N1.dmg)) and see what the result is in the new version.

**Comment by csimonmoi** [comment]
Hi

even after last update (this morning) I have the same issue about spellchecker
in Italian  and in English (not at all any spellchecker). As you already know
from my snapshot I sent to you, my OS is Windows 10.

Thanks

<br  

  

  

> On Dec 16 2015, at 5:13 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> [@dylntrnr](https://github.com/dylntrnr) in the Developer Tools (Developer
-&gt; Toggle Developer Tools), what is the result of navigator.language and
navigator.languages?

>

> Also, try the latest version of N1 (0.3.32-b11131d, [link for OS
X](https://edgehill.s3-us-
west-2.amazonaws.com/0.3.32-b11131d/darwin/x64/N1.dmg)) and see what the
result is in the new version.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-164988088).![](https://github.com/notifications/beac
on/APTadtKwiYu5Jyec-_w_v4ekHw21rKTaks5pQNx0gaJpZM4GzjgU.gif)

**Comment by mbilker** [comment]
Could you please run in the developer tools and report the outputs of each command other than the first:
```
var sp = new (require('spellchecker').Spellchecker)(); // ignore the output of this command
sp.setDictionary(navigator.language);
sp.isMisspelled('gnocchi');
sp.isMisspelled('gnochi');
```

**Comment by mbilker** [comment]
Also, please give me the output of `navigator.language`.

**Comment by csimonmoi** [comment]
Hi

I am not a developer or whatsoever, I am only an end user. If you can give me
a little more help to lauch Developer Tool (Preferences &gt; Toggle Developer
Tools &gt; and then I see only a lot of stuff out there) commands.

  

<br  

Thanks

  

  

![](https://dl.dropboxusercontent.com/u/1404158/470115_10150684693547872_95049
1721_o.jpg?random=635852595474556693)

|

**_Claudio Simonelli_**

Fondatore, Presidente e Maestro del  
Centro di Meditazione Dhmma Sukha  
**Sede:** Centro Shen Shan, Via Valsolda 45/F  
**Skype: **itadhammasukha  
**Email Centro:** itadhammsukha@gmail.com  
**Sito: **www.dhammasukha.altervista.org  
---|---  
  
_  
_

_'Se un uomo è infelice, sappia che lo è soltanto a causa di se stesso'_  

     **Epitteto      
**

> On Dec 16 2015, at 3:43 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Also, please give me the output of navigator.language.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-165129621).![](https://github.com/notifications/beac
on/APTadggkREkpBnMxlEzQP1otJqjdpGY2ks5pQXAZgaJpZM4GzjgU.gif)

**Comment by mbilker** [comment]
Yes it is `Developer -> Toggle Developer Tools`. In there you should paste: ```
var sp = new (require('spellchecker').Spellchecker)();
sp.setDictionary(navigator.language);
sp.isMisspelled('gnocchi');
sp.isMisspelled('gnochi');
```

Then take a screenshot. It should not contain personal information, but if you are concerned, take a screenshot starting with `var sp` and ending with `');`.

**Comment by csimonmoi** [comment]
Hi there

sorry but Developer tools has MANY tools:

on top: Elements, Network, Sources, etc.

  

I thought you intended "Console" on bottom of the tool.

I pasted your commands in Console and the only word that popped up is "true".

Let me know if it is that what you intentend or pleas be more specific.

Thanks

<br  

  

  

  

> On Dec 16 2015, at 4:41 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Yes it is Developer -&gt; Toggle Developer Tools. In there you should paste:
```  
var sp = new (require('spellchecker').Spellchecker)();  
sp.setDictionary(navigator.language);  
sp.isMisspelled('gnocchi');  
sp.isMisspelled('gnochi');

>  
>  
>     Then take a screenshot. It should not contain personal information, but
if you are concerned, take a screenshot starting with `var sp` and ending with
`');`.

>  
>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-165148073).![](https://github.com/notifications/beac
on/APTadqRxmWB98wj_Z-n4h-Qmn0rccCvMks5pQX2RgaJpZM4GzjgU.gif)

**Comment by dylntrnr** [comment]
@mbilker After updating to the latest version english spell check is working. thank you

attached is the output in console 

<img width="561" alt="screen shot 2015-12-16 at 11 04 37" src="https://cloud.githubusercontent.com/assets/2652938/11847836/f87459e2-a3e4-11e5-8066-90696d7f0e84.png">

**Comment by csimonmoi** [comment]
<br  

Attached below what I think you think I had to do.

> On Dec 16 2015, at 4:41 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Yes it is Developer -&gt; Toggle Developer Tools. In there you should paste:
```  
var sp = new (require('spellchecker').Spellchecker)();  
sp.setDictionary(navigator.language);  
sp.isMisspelled('gnocchi');  
sp.isMisspelled('gnochi');

>  
>  
>     Then take a screenshot. It should not contain personal information, but
if you are concerned, take a screenshot starting with `var sp` and ending with
`');`.

>  
>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-165148073).![](https://github.com/notifications/beac
on/APTadqRxmWB98wj_Z-n4h-Qmn0rccCvMks5pQX2RgaJpZM4GzjgU.gif)

**Comment by mbilker** [comment]
@csimonmoi Thank You! That is telling me the backend of the spell checker is working properly. In the `Console` tab at the top of the Developer Tools, could you type `$n.NylasSpellchecker.languageAvailable`

**Comment by mbilker** [comment]
@csimonmoi thinking about it a little more. I don't know which command returned `true` so please rerun the commonds in the `Console` tab at the top of the Developer Tools. Thanks!

**Comment by jstejada** [comment]
hey @csimonmoi , is the spellchecker still not working for you?

**Comment by csimonmoi** [comment]
I tried what you suggest typing in the console:

  $n.NylasSpellchecker.languageAvailable

The result is "false".

No spell checker still, non in English, no in Italian.

Windows 10.

  

<br  

  

  

  

![](https://dl.dropboxusercontent.com/u/1404158/470115_10150684693547872_95049
1721_o.jpg?random=635852595474556693)

|

**_Claudio Simonelli_**

Fondatore, Presidente e Maestro del  
Centro di Meditazione Dhmma Sukha  
**Sede:** Centro Shen Shan, Via Valsolda 45/F  
**Skype: **itadhammasukha  
**Email Centro:** itadhammsukha@gmail.com  
**Sito: **www.dhammasukha.altervista.org  
---|---  
  
_  
_

_'Se un uomo è infelice, sappia che lo è soltanto a causa di se stesso'_  

     **Epitteto      
**

> On Dec 17 2015, at 12:49 am, Juan &lt;notifications@github.com&gt; wrote:  

>

> hey [@csimonmoi](https://github.com/csimonmoi) , is the spellchecker still
not working for you?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-165287430).![](https://github.com/notifications/beac
on/APTadmodbil9vhQV0yO1HhdU9Lch6VDjks5pQfAlgaJpZM4GzjgU.gif)

**Comment by kios** [comment]
I have the same problem in Windows 7 64-bit Spanish. with version 0.3.29, everything worked properly, sorry for my English, I only speak Spanish

**Comment by csimonmoi** [comment]
Hi team  
My system is Win 10 and sent you many request about spell checker which does
not work in Italina nor in English.

There are other issues in Win10:

  

When I open FOR THE FIRST TIME in the morning (after a shuddown) your program
the main window is not well positioned on the screen, and I have to  click to
minimize and then maximize again.

  

Same story about column width. If you close and reopen the program everything
is ok. But if you shutdown the computer and reopen the program after you boot
the computer up, then the width is not arranged as you chose last time.

Thanks

  

  
  
  

![](https://dl.dropboxusercontent.com/u/1404158/Buddha.jpg?random=635852595474
556693)

|

**Claudio Simonelli**

Fondatore, Presidente e Maestro del  
Centro di Meditazione Dhamma Sukha** **  
**Sede Roma:** Shen Shan, Via Valsolda 45/F  
**Email Centro:** itadhammasukha@gmail.com  
**Skype: **itadhammasukha  
**Sito: **www.dhammasukha.altervista.org  
---|---  
  
_  
_

_  
_

_'__Se un uomo è infelice, sappia che lo è soltanto a causa di se stesso'_

** Epitteto    **

**  
**

**Nota Informativa:**

Questo messaggio di posta elettronica può contenere informazioni riservate,
pertanto è destinato solo a persone autorizzate alla ricezione. Se non si è il
destinatario specificato, non copiare, inoltrare o archiviare questo
messaggio. Se si è ricevuto questo messaggio per errore, si prega avvertire il
mittente ed eliminarlo completamente dal proprio computer.**  
**

> On Jan 9 2016, at 10:18 am, Claudio Simonelli &lt;csimonmoi@gmail.com&gt;
wrote:  

>

> Hi Ben and tanks for your reply. My system is windows 10 not 8 and yes I
checked other languages even English and nothing at all. Thank you

>

> Il 08/Gen/2016 21:19, "Ben from N1"
&lt;[ben.gotow@n1.mail.intercom.io](mailto:ben.gotow@n1.mail.intercom.io)&gt;
ha scritto:  

>

>> __

>>

>> Hi Claudio - thanks for reaching out. On Windows 8+, N1 uses the Windows
Spell Check API. I know it supports a handful of languages, but it may not
support Italian. Are you able to spellcheck in other built-in Windows apps?  
>>  
>> ---  
>>  
>> \--  
>>  
>> **Ben** from N1  
>>  
>> * * *  
>>  
>> Powered by [**Intercom**](http://www.intercom.io/)  
>>  
>> On Thu, Jan 7, 2016 at 11:24 AM, "Claudio Simonelli"
&lt;[csimonmoi@gmail.com](mailto:csimonmoi@gmail.com)&gt; wrote:  

>>

>>> Hi

>>>

>>> yes my system is in Italian. I already made some controls with your team,
but nothing has been reported yet.

>>>

>>> Let me know if you need information or tests.

>>>

>>> Thank you

>>>

>>>  

>>>

>>> <https://dl.dropboxusercontent.com/u/1404158/Buddha.jpg?random=63585259547
4556693>

>>>

>>> **Claudio Simonelli**

>>>

>>> Fondatore, Presidente e Maestro del  
Centro di Meditazione Dhamma Sukha  
**Sede Roma:** Shen Shan, Via Valsolda 45/F  
**Email Centro:** [itadhammasukha@gmail.com](mailto:itadhammasukha@gmail.com)  
**Skype: **itadhammasukha  
**Sito: **[www.dhammasukha.altervista.org](http://www.dhammasukha.altervista.org)
>>>

>>> _'__Se un uomo è infelice, sappia che lo è soltanto a causa di se stesso'_

>>>

>>> ** Epitteto **

>>>

>>> **Nota Informativa:**

>>>

>>> Questo messaggio di posta elettronica può contenere informazioni
riservate, pertanto è destinato solo a persone autorizzate alla ricezione. Se
non si è il destinatario specificato, non leggere, copiare, inoltrare o
archiviare questo messaggio. Se si è ricevuto questo messaggio per errore, si
prega avvertire il mittente ed eliminarlo completamente dal proprio computer.

>>>

>>> On Wed, Jan 6, 2016 at 07:36 PM, "Christine Spang" &lt;[christine.spang@n1
.mail.intercom.io](mailto:christine.spang@n1.mail.intercom.io)&gt; wrote:  

>>>

>>>> Hi Claudio,

>>>>

>>>> N1 does spell-checking in the language your operating system is set to.
Is your Windows 10 system language set to Italian?

>>>>

>>>> On Wed, Jan 6, 2016 at 03:30 PM, "Claudio Simonelli"
&lt;[csimonmoi@gmail.com](mailto:csimonmoi@gmail.com)&gt; wrote:  

>>>>

>>>>> Hi still waiting your news about spell checker in Italian, in Windows
10.

>>>>>

>>>>> thanks  
>>  
>> ![intercom](https://via.intercom.io/o?h=61881de689f6ac971fc5a9b22e106af10b0
f278f-1674971626:56862010) ![](http://track.spe.intercom.io/q/v6eulgoC54aRmgTo
hRn8yw~~/AAAAAQA~/RgRYcp7SPkEIAGtGo9-S9Q1CCgAB0hmQVsYuZvdSE2NzaW1vbm1vaUBnbWFp
bC5jb20JUQQAAAAAR397ImNvbnZlcnNhdGlvbl9pZCI6IjE2NzQ5NzE2MjYiLCJpbnRlcmNvbV9tZX
NzYWdlX2lkIjoiMTgzMzU2MjMiLCJ1c2VyX2lkIjoiNTY1ODQ3MzE5ZGUwOTQ2Y2QxMDAwMGQ2Iiwi
YmluZGluZyI6Im5vdGlmaWNhdGlvbiJ9)

**Comment by bilby91** [comment]
I could never make the Spanish spell checker work on OS X. I have Spanish as a my secondary language in OS X preferences.

Running N1 0.3.45-3b5880e and OS X 10.11.1 (15B42).

Let me know if you need any debugging information.

**Comment by kakubei** [comment]
Same here on a Mac running Yosemite. I have the same result as dylntrnr:

    navigator.language
    "en-US"
    navigator.languages
    []

My OS is set to English, but I also have Spanish loaded under Language & Region. Nylas version is: Version 0.4.5-b0ec335 (0.4.5-b0ec335)

Any ideas?

**Comment by link0802** [comment]
Make multi language spellchecker on linux and N1 will be my primary email client :wine_glass: :wink:

**Comment by simonbcn** [comment]
I have same problem on Arch Linux with Spanish.

**Comment by mbilker** [comment]
@simonbcn Only English is supported at the moment on all Linux distributions

**Comment by mbilker** [comment]
I determined that Italian is not a default supported language on Windows and requires a language pack. It is possible to include the Hunspell spellchecker on Windows, but it is not the best solution and may not even work.

**Comment by mbilker** [comment]
Drawing from Slack's example with `node-spellchecker`, they force Hunspell on Linux and use the system dictionaries by default, which can be a large number of languages. On Mac OS X, they use the OS provided spellchecker because it is much better than Hunspell. On Windows 8 and above, they use the OS provided spellchecker even if it is missing dictionaries. On Windows 7 and below, they use Hunspell and download the dictionaries from http://slack-ssb-updates.s3.amazonaws.com/dictionaries and checks http://slack-ssb-updates.s3.amazonaws.com/dictionaries/RELEASES.

**Comment by csimonmoi** [comment]
Sorry but your spell checker does NOT work not only in Italian but in any
other language even English.

As now ... slfksfskdlfjdslfsl .... there is no correction at all.

Thanks anyway

  

  

  

**  
**

  
![](https://link.nylas.com/open/7gdajk7zlnpz9p3409q55s5ir/9d0ea0f62b4842a0a3d0
b0a444b008b0)

> On Mar 10 2016, at 5:10 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> I determined that Italian is not a default supported language on Windows and
requires a language pack. It is possible to include the Hunspell spellchecker
on Windows, but it is not the best solution and may not even work.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/670#issuecomment-194928647).![](https://github.com/notifications/beac
on/APTadoW6N0en1cBQ1gpdJJLBipGgiY9xks5psEKJgaJpZM4GzjgU.gif)

**Comment by mbilker** [comment]
It appears Slack doesn't check if the language exists on Windows or Mac OS X, because those API's are not implemented in `node-spellchecker`.

**Comment by jstejada** [comment]
merging into #1392
