### ISSUE TITLE
Saving an attachment crashes N1

### ISSUE THREAD

**Issue by jaycee** [nylas/N1#672]
This is on linux--ubuntu 15.10.

When I click to save an attachment, I get the normal save dialog and successfully download the attachment. However, immediately after my file browser (nautilus) opens and N1 hangs. N1 never returns from this state and has to be killed and restarted.

**Comment by mbilker** [comment]
Close Nautilus and N1 works fine. It seems it is with how N1 opens files that don't forward events to a main process, like links launching in an already started Chrome instance.

**Comment by grinich** [comment]
@jaycee Are you still experiencing this issue? Please re-open if you can reproduce. I think we fixed it.

**Comment by mbilker** [comment]
Nope. I can still reproduce this issue? Will try to take a video
