### ISSUE TITLE
(Feature Request) Add an option to open N1 on Ubuntu indicator and minimize at startup

### ISSUE THREAD

**Issue by vuquanghai** [nylas/N1#673]
Hi. I installed N1 0.3.29. The indicator works perfect, only 1 thing that bother me is: There are no option to open N1 directly on indicator. The indicator's options now are: New message, Preference, and quit N1. Everytime i got a new email, i have to open Dash, search for N1 then click to N1's icon in Dash in order to open N1. That so waste of times.

So my idea is: Could you guys add an option to open N1 directly from Indicator, beside New message, Preference, and quit N1?

Also, could you add an option to minimize N1 on startup? This could be helpful when i start system and do not need to minimize N1 manually.

Thanks for your hardwork to make a great email client :) !

**Comment by MedLabs** [comment]
+1
I was looking for this feature too

**Comment by jstejada** [comment]
hey @MedLabs -- thanks for posting this! we will definitely look into it.

**Comment by jstejada** [comment]
referencing #762
