### ISSUE TITLE
Feature Request: Multiple Sender Identities

### ISSUE THREAD

**Issue by digitalextremist** [nylas/N1#676]
One account can have multiple senders; each may have:

* Separate sender address ( required )
* Separate display name ( required )
* Separate SMTP ( optional )
* Separate Signature ( optional )

**Comment by bengotow** [comment]
Hi @digitalextremist — unfortunately, we don't plan to support separate SMTP gateways for the same account. However, we're working on Aliases (#662), and signatures landed in the most recent build. (Multi-signature support will also be included eventually.) Cheers!

**Comment by digitalextremist** [comment]
#662 does cover the majority of what I'm hoping for here, thank you.
