### ISSUE TITLE
More themes

### ISSUE THREAD

**Issue by riyadhalnur** [nylas/N1#679]
The current default theme dark/light seem old and drab. A revamped UI and support for themes would be nice. [Polymail](https://polymail.io/?ref=producthunt) looks great. I'm also a big fan of *Inbox* from Google.

**Comment by bengotow** [comment]
Hey! We'll definitely add more themes in the future. In the time being, you're welcome to create your own theme. There are already a few that are pretty nice, like this one: https://github.com/noahbuscher/N1-Taiga

**Comment by noahbuscher** [comment]
So weird you said this! Was just chatting about it in Slack...

![](http://noah.li/12794+)

I'll see what I can do. 😄

**Comment by riyadhalnur** [comment]
Cheers mate :beers:

**Comment by oldhickory30** [comment]
Love it!

**Comment by Jacob-Lucado** [comment]
Update on the Polymail theme?

**Comment by edipox** [comment]
Hi @bengotow 
Today I tried N1 in [elementary OS](http://elementary.io) and it didn't looked good:
![default](https://cloud.githubusercontent.com/assets/1580541/12380683/8645ea8e-bd57-11e5-8867-a362c173ba35.png)

So I've made those themes: https://github.com/edipox/elementary-nylas
I've shared them in the elementary comunity in google plus, but wanted you to know about it too
regards

**Comment by edipox** [comment]
@riyadhalnur @Jacob-Lucado I am working in a Taiga fork inspired in Polymail. Hope to get it at least for OS X in few hours

**Comment by grinich** [comment]
@edipox sounds awesome

**Comment by grinich** [comment]
BTW, I added your theme to the readme :)

**Comment by edipox** [comment]
@riyadhalnur @Jacob-Lucado @grinich Here it is: https://github.com/edipox/n1-ido

![ido-official](https://cloud.githubusercontent.com/assets/1580541/12407818/7e4c2f9a-be39-11e5-96e1-174dba8e5685.png)

**Comment by riyadhalnur** [comment]
@edipox both of them look great. kudos to your hard work :beers:

**Comment by oldhickory30** [comment]
When using the Polymail theme, and I'm in preferences I'm unable to return to the main widow without restarting Nylas. However, looks great!

**Comment by edipox** [comment]
@riyadhalnur Thank you :beers:

**Comment by edipox** [comment]
@oldhickory30 Thank you for your feed back, I've already added an issue about that. I hope to fix it today

**Comment by Jacob-Lucado** [comment]
@edipox  Thanks, there's a few issues; but minor. I'll fix it up.

**Comment by edipox** [comment]
@Jacob-Lucado thank you! Any help will be very welcome! Now I've fixed some issues: the activity section in the sidebar, preferences page and dropping items in the sidebar

**Comment by BraisDosGoros** [comment]
Great job, @edipox ! I've installed your n1-ido theme and it looks just great. I just can't get the message headers to look like they do in your screenshots, I mean like:
```
john@gmail.com
Hello there!
This is just to let you now that...
```

Instead of the default setting:
`john@gmail.com       Hello there!      This is just to let you know that...`

Is there anything I have to tweak? Thanks!

**Comment by edipox** [comment]
Hi @BraisDosGoros that changes depending on the window size or the size of the the message list section

**Comment by BraisDosGoros** [comment]
Thanks! And now I'm gonna dig a whole and hide in it forever... :-)

**Comment by RReverser** [comment]
@edipox Ido looks great, but... any chance for a dark version of it? I prefer to have almost all of my apps to be in dark as eyes hurt much less when working for a long time.

**Comment by LouWii** [comment]
It would be cool to have like a main list of all themes. Atom does that pretty well.

**Comment by dyrnade** [comment]
Hello guys, i just made a theme for experimenting.Here it is, https://github.com/dyrnade/N1-Darkish
