### ISSUE TITLE
Can't apply a label to a mail

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#681]
![toool](https://cloud.githubusercontent.com/assets/2344626/11758021/01d58c7c-a01b-11e5-9b5e-5715b64331e8.gif)

**Comment by mbilker** [comment]
Developer -> Open Activity Monitor. What is the status code of the most recent request after the attempt to set a label. If you need to post the image, please hide the URL's as they contain account information.

**Comment by grinich** [comment]
@bashok001 this definitely looks like a bug. if you can paste the trace, hopefully we can dig into it

**Comment by bashok001** [comment]
```40012:54:22  RunCopycurl -X PUT -d '{"labels":["ap085e9t9h6et6a9jg6rzm8oc","9154bepzj6yyy3me99au3cxzz","3qw3gw9hs0wylcu2ve56z9csn","local-bf6fa3c1-5798"]}' "https://xxxxx:@api.nylas.com/threads/yyyy"```

Status is 400

**Comment by bashok001** [comment]
Running the command gives this output..
```
{
  "message": "Invalid id: local-bf6fa3c1-5798",
  "type": "invalid_request_error"
}logout

[Process completed]
```

**Comment by bashok001** [comment]
@grinich @mbilker I would appreciate it if you let me know anything that needs to be censored out in the IDs posted above.

**Comment by mbilker** [comment]
@bashok001 nope. you censored out the right stuff that is personally identifiable.

**Comment by bashok001** [comment]
@mbilker I just installed N1 on another machine. Created a label which resulting in #680 and tried to apply it to a mail recreating this. So, now I am sure this is not just occurrence on one machine. FYI: Both of them are Macs with OSX Yosemite on one and El Capitan on another.

**Comment by mbilker** [comment]
@bashok001 Since this is classified as a Sync Engine bug. That means there isn't much you can do to fix the issue currently.

**Comment by jstejada** [comment]
@bashok001 this should be fixed in an upcoming release
