### ISSUE TITLE
Feature Request: Support 24-hour / military time

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#682]
It would be  great to be able to configure the time format from 12:00 to 24:00 hr. So that 11pm is 23:00Hr in Europe. Military time as my wife calls it.... (We are not that military here in Europe tho) :)) And additionally for calendar purposes, to be able to switch the first day of the week from monday to sunday.

**Comment by bengotow** [comment]
Hey! Great to hear from you @tinybigstudio — we can definitely get this in to a future release. I'm sure you're not the only one looking for 24-hour time!

**Comment by tinybigstudio** [comment]
Is this going to be fixed soon? thanks :)

**Comment by mbilker** [comment]
@tinybigstudio Nylas has a trello board for what they are working on: https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by felipesere** [comment]
I would like tackle this issue. 
Can someone point in the right directions? Which files (more or less) need editing or what could I grep for? Looking for "time" gave way too many results, as expected :smile:

**Comment by mbilker** [comment]
Look for Date usage. Like new Data(blah)

**Comment by colllin** [comment]
Is there an easy way to inherit this setting from the OS, instead of adding a new setting?

**Comment by mbilker** [comment]
@colllin not really. Electron is aimed at multi-platform support, where the settings interfaces differ. There even can be a lack of a centralized settings store under Linux.

There may be native modules available however that allow access. Electron already has a `nslog` native module that logs to `Console.app` under OS X.

**Comment by Cu8eR** [comment]
+1

**Comment by bengotow** [comment]
Hey folks—I think there are only a handful of places we format message and thread dates:

[For the message view]
https://github.com/nylas/N1/blob/unified-inbox/internal_packages/message-list/lib/message-timestamp.cjsx#L26

[For the conversation / drafts view]
https://github.com/nylas/N1/blob/unified-inbox/internal_packages/thread-list/lib/formatting-utils.cjsx#L8

What we need to do is add a config schema item to https://github.com/nylas/N1/blob/unified-inbox/src/config-schema.coffee#L56 under the "reading" section. Then it'll be automatically displayed in the app's preferences and you can query for it via `NylasEnv.config.get('core.reading.timeFormat')`.

**Comment by agat** [comment]
+1

**Comment by bengotow** [comment]
@ChrisKatsaras is gonna tackle this one. :+1:

**Comment by ChrisKatsaras** [comment]
:+1:

**Comment by GU5TAF** [comment]
Has there been any progress on this @ChrisKatsaras?
I could take a look if you don't have time to look into it?

**Comment by ChrisKatsaras** [comment]
Hey guys! Sorry for the delayed response! My team and I were successfully able to implement the 24 clock. I will be making a pull request soon which will hopefully meet the standards!

**Comment by mbilker** [comment]
@ChrisKatsaras Did you complete that PR? If so, please submit it!

**Comment by ChrisKatsaras** [comment]
@mbilker Unfortunately, due to the fact that N1 had an update shortly after we developed the 24hr clock our code was no longer functional. Our team is no longer able to complete the task at this time so I encourage someone else to take on this task.

**Comment by rudolphpienaar** [comment]
+1

Also the main reason I'm not using Nylas as my main email client.

**Comment by jathpala** [comment]
I have just submitted pull request #2622 which should address this. It builds on the previous work done by others. I think it now implements 24 hour time in all places where time is displayed.

**Comment by bengotow** [comment]
This has landed and will go out in the next release–
