### ISSUE TITLE
Change App Icon

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#683]
The Nylas N1 logo should be changed. This is a serious comment as it affects the user experience. It reminds me of a system alert in Mac. It deserves a differentiated logo that resembles email..Happy to contribute.

**Comment by bengotow** [comment]
Thanks—ideas or revisions are welcome. We feel this reflects other popular mail icons (Mailbox http://www.macupdate.com/images/icons256/51935.png etc.) but would love to see your take!

**Comment by tinybigstudio** [comment]
I love that you are so open to even change your logo... the essence of what feels "yours",  This says a lot about you. You have the right values to achieve anything and I hope you do. So far, you turned me from customer to involved designer, so... good job! :)

**Comment by noahbuscher** [comment]
@tinybigstudio You took the words out of my mouth. :ok:

**Comment by tinybigstudio** [comment]
I don´t know about you @noahbuscher but I am a UX designer totally sold to this project, bring it on!

**Comment by noahbuscher** [comment]
@tinybigstudio I just started working on this repo a few days ago. I just built [Taiga](http://github.com/noahbuscher/N1-Taiga) and am finishing up a GIF plugin tonight... 

![](http://noah.li/10c6Y+)

**Comment by tinybigstudio** [comment]
Hahaha, no!

Wind up my little friend...

At least paint the little world that you touch with a bit of RGB...

> On Dec 12 2015, at 5:20 am, Noah Buscher &lt;notifications@github.com&gt;
wrote:  

>

> [@tinybigstudio](https://github.com/tinybigstudio) I just started working on
this repo a few days ago. I just built
[Taiga](https://github.com/noahbuscher/N1-Taiga) and am finishing up a GIF
plugin tonight...

>

> [![](https://camo.githubusercontent.com/0b33d771cc1b7d411d5c82a12e38afb124dd
05b1/687474703a2f2f6e6f61682e6c692f31306336592b)](https://camo.githubuserconte
nt.com/0b33d771cc1b7d411d5c82a12e38afb124dd05b1/687474703a2f2f6e6f61682e6c692f
31306336592b)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/683#issuecomment-164111395).![](https://github.com/notifications/beac
on/AB_3bU-lWSV-qdWa3hVLFkLLd1M9RTZ6ks5pO6YngaJpZM4G0BgZ.gif)

**Comment by noahbuscher** [comment]
The gif plugin is pretty much done :tada: 

Please check out [Jiffy](http://noahbuscher.github.io/N1-Jiffy)

**Comment by bengotow** [comment]
Hey gang—closing this one for inactivity. Feel free to re-open or create another issue if you have more icon feedback.

**Comment by hudakdidit** [comment]
I've been using N1 for a week now and really like it! Nice job.

I use Atom Editor and its app icon looks _very_ similar at a quick glance. I just thought I'd point it out.

<img width="248" alt="fullscreen_6_22_16__5_18_pm" src="https://cloud.githubusercontent.com/assets/1223821/16288117/95a28f3e-389d-11e6-95ed-bda2803aa3f0.png">

**Comment by molstrangler** [comment]
The app icon on Windows 10 is square.

**Comment by paanvaannd** [comment]
I would like to see a square icon for other systems as well! I think the round one looks perfect, but alternate icons couldn't hurt :+)

I'm using square icons for everything else in my Dock so the N1 icon doesn't quite fit in with the rest for the time being for me...

![dock](https://cloud.githubusercontent.com/assets/16567134/17447036/4e16387e-5b1a-11e6-847e-2bbe7de15cfa.png)

@molstrangler, I'm a little confused about where the application icon is located within this project. Any chance you could direct me to the icon file directory in this project so I can start using the square Windows version instead? :+)
