### ISSUE TITLE
Consistency in buttons possition

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#685]
As a user, I expect all buttons and icons to be in the same place always, doesn´t matter if I select one, a few, or a lot of emails. Currently it´s inconsistent.

If I just select one email, the action buttons are at the right side, on the same position as my selected email. that´s ok.
![screen shot 2015-12-12 at 2 15 13](https://cloud.githubusercontent.com/assets/2094957/11759630/9a5559ae-a076-11e5-8730-0155e8a74462.png)

But if I select a few emails, I still see the hover/archive effect which is kind of ok. But when I select a few, all the buttons move to the left. and change position... that´s weird.

A better interactjon would be to maintain the bin and archive (wtf is archive btw?) at the same vertical position and the "clear selection" at the left when selecting several emails.

**Comment by grinich** [comment]
hi @tinybigstudio -- Archive moves the message to the archive folder, the same as Gmail, Outlook, iCloud, etc. 

These quick-action buttons actually only appear on hover. The action to archive multiple messages is at the top.

Thanks!
