### ISSUE TITLE
Increase max-width of sourcelist

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#687]
![screen shot 2015-12-12 at 2 44 04](https://cloud.githubusercontent.com/assets/2094957/11759739/686fa0da-a07a-11e5-8147-e5de1a9c49cd.png)

As a user I´d like to be able to move the left column so that some items don´t appear concatenated.

**Comment by grinich** [comment]
Great suggestion. Thanks!

**Comment by jstejada** [comment]
Merging this in to #537 since this is fixed on that branch. Stay tuned! Heading to beta shortly.
