### ISSUE TITLE
Inbox sort and order 101

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#688]
As a user, I don´t find a way to order my inbox, by latest, name, sender or subject. The program needs a small heading over the inbox that allows you to order by those subjects if you click on them. It could even dissapear on scroll down like a website...and appear on scroll up.

Said headings are very important.

**Comment by grinich** [comment]
Which specific headings?

We've found that all users actually just use search when looking for mail, with the exception of sorting by time.

**Comment by tinybigstudio** [comment]
On a second look, this seems probably not needed. Thanks.
(deleting this issue).

**Comment by jrhalchak** [comment]
I'm surprised this was closed so quickly.  Do other users not see this as a useful feature?  Sorting by sender name, date, read status, tagged.... all seem like basic necessity.  

For example I haven't checked my email in a few days so I'm using the unread filter on the left-hand side.  Obviously certain unread emails are more important than others.... one way to tell might be _who sent it_.  Additionally, what if I want to see the oldest ones first so I can see which important messages were sent first?
