### ISSUE TITLE
The app does not fit the screen resolution

### ISSUE THREAD

**Issue by krushireddy** [nylas/N1#692]
This happened just after I restarted the app to install "version 0.3.29-1904c6f (0.3.29-1904c6f)"

<img width="1440" alt="screen shot 2015-12-12 at 10 13 11 am" src="https://cloud.githubusercontent.com/assets/2978485/11760298/4f792730-a0bc-11e5-8a8f-70ebc0bf1ad4.png">
<img width="1440" alt="screen shot 2015-12-12 at 10 35 36 am" src="https://cloud.githubusercontent.com/assets/2978485/11760299/4f7d24e8-a0bc-11e5-948d-319a5fe615a7.png">

**Comment by grinich** [comment]
You mean it's too big?
