### ISSUE TITLE
Double click to respond or trash

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#696]
Based in some articles and claims and ..."facts", 80% or even 90% of users  who double click it´s either to respond or to trash an email. It could be a nice experiment where you test some users whose double click creates an action to delete or respond.

**Comment by grinich** [comment]
Hi @tinybigstudio -- our interactions are modeled after Mac Mail and Outlook. Our double-click is reserved in the future for opening a thread in a new window.

Thanks!
