### ISSUE TITLE
Refresh button: again

### ISSUE THREAD

**Issue by tinybigstudio** [nylas/N1#697]
Every time y use Nylas N1 (and my timeline based programs) I end up scrolling the mouse down to refresh (as in a phone) and then look for a refresh button.

**Comment by grinich** [comment]
hi @tinybigstudio -- N1 retrieves new mail via a streaming connecting to the sync engine, so new email is "pushed" to the app as soon as it's available. There isn't any polling, periodic checking for mail, etc. As soon as it's pulled through the sync engine, it's visible in the app.

In the future we may add more info about the sync state, but for no a refresh button would just be a no-op. 

Thanks for the feedback!
