### ISSUE TITLE
api reference link opn website broken

### ISSUE THREAD

**Issue by schmurfy** [nylas/N1#7]
This might not be the right place to report it but I have no idea where I should report it ;)

The api reference link here: https://www.nylas.com/N1/docs/ points to localhost which, obviously, does not do much.

**Comment by adamgoose** [comment]
This is fixed: https://www.nylas.com/N1/docs/APIReference.html

**Comment by kav-ya** [comment]
Thanks for the report; as noted above, this has been fixed =)
