### ISSUE TITLE
Allow left-most sidebar to be shrunk further

### ISSUE THREAD

**Issue by thorpj** [nylas/N1#700]
It would be useful, if this sidebar could be made smaller. That is currently the limit. Clearly it can be dragged further. 

Judging by the fact that my email address has already been shrunk (you know the abcdef@**...**) the client is capable of dealing with a situation where the text is longer than what the sidebar allows.

To add to that. Perhaps we should be able to hide the sidebar completely. I almost never use that sidebar, so it's taking up space for nothing 99% of the time. I'm sure i'm not the only person who realises this situation.

![capture](https://cloud.githubusercontent.com/assets/14038642/11765040/b7df6222-a183-11e5-95f1-8f2936c85025.PNG)

**Comment by tinybigstudio** [comment]
Not sure if that column should have a fixed width, as it is truncated for me at it´s widest width for example. A flexible column would be a better solution. 
![screen shot 2015-12-12 at 2 42 55](https://cloud.githubusercontent.com/assets/2094957/11768081/f65b7a46-a1b9-11e5-85a9-b4a374a3b24c.png)

**Comment by bengotow** [comment]
Hey folks—this sidebar can currently be resized from 165px to 210px (as long as you've made the window as a whole wide enough that other columns can shrink). We'll increase the range in the next update.

**Comment by thorpj** [comment]
@bengotow Will the range be between 210 and 0 px? Thanks

**Comment by phwconz** [comment]
Would love to be able to reduce to just account icons as was done by Sparrow.
![image](https://cloud.githubusercontent.com/assets/1782583/13728126/8f3ad4d2-e972-11e5-8b98-bbeccd04d054.png)

**Comment by bengotow** [comment]
Thanks! Now that we've changed the minimum size to something fairly small, I think the remainder of the discussion here is a dup of https://github.com/nylas/N1/issues/1517. Moving this there.
