### ISSUE TITLE
Fails to shut down  OS X 10.11.2, N1Version 0.3.29-1904c6f (0.3.29-1904c6f)

### ISSUE THREAD

**Issue by jimburke1** [nylas/N1#702]
when shut down from task bar or the dock, context menu in each case, the N1 program continues to run in the background, the only reliable method I've found to shut it down is force quit

**Comment by bengotow** [comment]
Hey @jimburke1 — next time this happens for you, could you take a look at `Console.app` and see if anything is appearing? We've been getting reports of the app hanging on quit, but we haven't been able to reproduce it yet.

**Comment by jimburke1** [comment]
still trying, now that we have an audience, its turned shy

**Comment by hap1o** [comment]
I think it may be related to the feedback, at least for me, even cmd + q doesn't end it and I noticed that the feedback menu was minimized, and I cannot close the windows at all.

**Comment by sbahr001** [comment]
It prevented me from installing an update. I had to force quit, and then everything started working. 
These are the following conditions of my computer:
Running Mac OS X 10.11.2
I was in the middle of a reply message, my computer had been in sleep mode for a few days. One sleep was a safe sleep as the battery was very low.

**Comment by jstejada** [comment]
merging into #773
