### ISSUE TITLE
Show unread counts for folders as well as inbox

### ISSUE THREAD

**Issue by MattSNZ** [nylas/N1#703]
This is one thing that I'm desperately missing from my email workflow as I heavily filter non-urgent email out of my inbox. But I still like to know that they're there for me to go read when I have a moment.

Similar to the Github folder below in Airmail, showing 3 unread messages:
![screen shot 2015-12-14 at 14 50 59](https://cloud.githubusercontent.com/assets/5117628/11771224/372fa516-a272-11e5-8130-e361d60f244e.png)

**Comment by jstejada** [comment]
hey @MattSNZ , thanks for contributing! you can actually already do this. If you go to Preferences -> General you should see an option "Show unread count for all folders/labels". 
<img width="409" alt="screenshot 2015-12-13 23 41 31" src="https://cloud.githubusercontent.com/assets/1271509/11775379/2b240dcc-a1f3-11e5-85ea-6f7dc0ab27ea.png">

**Comment by MattSNZ** [comment]
:facepalm:

Thanks!
