### ISSUE TITLE
Wrong unread email count

### ISSUE THREAD

**Issue by odeke-em** [nylas/N1#704]
This app is pretty awesome, thank you for working on it!

I've been using N1 for a month or so and one of my Gmail accounts' unread emails count has been consistently stuck at '3' even though I can't seem to find any unread emails.

### # N1 on OS X
<img width="206" alt="screen shot 2015-12-14 at 1 03 27 am" src="https://cloud.githubusercontent.com/assets/4898263/11775740/88926b2e-a1fe-11e5-9313-6d11980f54af.png">

### # On Gmail
<img width="197" alt="screen shot 2015-12-14 at 1 01 46 am" src="https://cloud.githubusercontent.com/assets/4898263/11775719/5767fb90-a1fe-11e5-9855-8ba3d2365a50.png">

**Comment by jstejada** [comment]
hey @odeke-em, thank you for reporting this! We are looking into it and will report back soon

**Comment by odeke-em** [comment]
Thank you @jstejada!

**Comment by jstejada** [comment]
thanks @odeke-em , this has been a tricky one. Still looking into it. I'm going to merge this into #759

**Comment by odeke-em** [comment]
Aye aye, thanks for taking a look at this @jstejada and for N1!

**Comment by alex-bender** [comment]
I have wrong email count too.
`$ Linux bender 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
Nylas version is the same `0.3.32-b11131d`

**Comment by dubbe** [comment]
Same for me, it's also stuck at 3 (if another unread it will bump to 4). 
Linux banks 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Nylas version is 0.3.36-e8239a9

**Comment by robertogradini** [comment]
Hi everyone! 

I've the same problem too.
```
ProductName:	Mac OS X
ProductVersion: 10.11.2
BuildVersion: 15C50
Nylas: `Version 0.3.43-b95f1f7 (0.3.43-b95f1f7)`
```
![screen shot 2016-01-14 at 11 17 08](https://cloud.githubusercontent.com/assets/245338/12321801/6cbb2d08-bab0-11e5-9e99-90a34142f588.png)
![screen shot 2016-01-14 at 11 15 14](https://cloud.githubusercontent.com/assets/245338/12321804/73d0c846-bab0-11e5-8ee5-298b91539089.png)

**Comment by kenderson** [comment]
Hi All!

Same problem here;

```
ProductName: Mac OS X
ProductVersion: 10.11.3
Version 0.4.5-b0ec335 (0.4.5-b0ec335)
```

**Comment by alex-bender** [comment]
Hello all
I was checking that issue and found out that there are really was unread messages.
So just try to scroll down until message appear.
It can take some time, but it worth.

**Comment by jstejada** [comment]
hi all, you can follow up on this issue at #759
