### ISSUE TITLE
Feature Request: Mark email as unread, as opposed to the whole thread

### ISSUE THREAD

**Issue by lwis** [nylas/N1#705]
When marking emails as unread, only the most recent email in the conversation should be marked as unread, rather than the whole thread. Maybe the whole thread could be an 'alt' click option?

**Comment by Cu8eR** [comment]
+1

**Comment by sergeyklay** [comment]
+1

**Comment by grinich** [comment]
We do the entire thread because that's what Gmail does when you click "mark as unread". I'm going to reopen [Mark Unread From Here](https://github.com/nylas/N1/issues/829) because that's a Gmail feature we haven't implemented.

**Comment by snarfen** [comment]
Any updates on this feature request?

**Comment by shaynem** [comment]
This is causing major issues for me.. is there any update to this?

**Comment by achekroud** [comment]
+1
