### ISSUE TITLE
Feature Request: shortcut for creating a new email while N1 is closed, tray notification is visible

### ISSUE THREAD

**Issue by naman** [nylas/N1#707]
It would be pretty useful for developers who want to send a quick email, or search for any mail.

 - Ctrl + Alt + Space (or alternative for OSX) for creating new mail.
 - another shortcut for opening the inbox or N1 window. 
 - shortcut quick mail search (small window)

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
