### ISSUE TITLE
FileDownloadStore _downloadDirectory assumes POSIX path

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#709]
From https://github.com/nylas/N1/blob/master/src/flux/stores/file-download-store.coffee#L118:

The path uses a path separator of `/` which isn't the default under Windows. I know the Node `path` module properly handles path separators between platforms.

**Comment by bengotow** [comment]
Hey @mbilker — hmm, you're definitely right but we haven't noticed this being a problem yet. Is there a way to reproduce a bug caused by this behavior? We can definitely use `require('path').sep` instead of the `/`

**Comment by mbilker** [comment]
@bengotow I didn't encounter a bug. I was reading the source before I realized I made a mistake in my own code, but I noticed the inclusion of a hard path. I guess Windows is flexible sometimes.
