### ISSUE TITLE
Snooze Mail / Postpone Returning to Inbox

### ISSUE THREAD

**Issue by lazywei** [nylas/N1#71]
Hi,

Is there any plan to support the "snooze" feature just like Mailbox or Inbox? That is, the user can set a time interval to snooze certain mails. When being snoozed, the mail goes to "archive" or whatever folder/label. Once the snooze time ending, the mail goes back to the inbox.

**Comment by emorikawa** [comment]
YES! That's exactly the type of thing we want to start building packages around. We're keeping ideas like this on our public Trello board here https://trello.com/c/xqktk3oL/17-snooze-mail to let the community vote on them while keeping our open issues at bay.

**Comment by mattcantstop** [comment]
Huge :+1: on this. It is the second biggest feature I am looking for in an email client. Only second to "hackable" which Nylas N1 already delivered on.

**Comment by samuelbeek** [comment]
Would love to see this! :+1:

**Comment by alexandru-calinoiu** [comment]
I know that it will be more helpfull to help out instead of just +1 how cool this feature will be, but at this time this is all I can do.

**Comment by lukehefson** [comment]
> I know that it will be more helpfull to help out instead of just +1 how cool this feature will be

Totally agree with this sentiment… sorry. But I also wanted to mention that Mailbox [has just announced](http://www.mailboxapp.com/faq/) that they are shutting down on February 26th, so there is probably a good potential for grabbing their users now.

**Comment by LiorNn** [comment]
Definitely would love a snooze feature. That's the only reason I used Mailbox

**Comment by oojacoboo** [comment]
lukehefson, like me!  I neeeeeed something NOW :)

**Comment by connorjsmith** [comment]
I take it that this would be meant to help keep your inbox count at 0? Similar to approach that mailbox takes

**Comment by oojacoboo** [comment]
Absolutely.  I have lots of emails that need follow-ups in a week or a month, or tomorrow, etc.  Having 50 emails in your inbox that need attention all the time is very distracting and makes it harder to get out of your inbox.  If you've already made the decision on an email, when a follow-up, or attention is needed on it, you don't want to see it again.  Seeing it again means your mind has to reprocess what it's about, then figure out if it's important to act on, or if you can act on it, at the moment.

**Comment by connorjsmith** [comment]
Sounds good, especially given that mailbox is shutting down. Gives us a good opportunity to snag a few vagrant users.

**Comment by oojacoboo** [comment]
Yep, I love what N1 is working on, but I can't use it until there is Snooze and preferably unified inbox.

I'm looking at polymail.io as well - still in beta though :/

**Comment by noahbuscher** [comment]
No promises, but just keep your eyes peeled over the next few days. :+1: 

I'll post updates here...

**Comment by oojacoboo** [comment]
:+1:

**Comment by jinjiachen** [comment]
i have tried just now and it doesnt work with aliyun mail, does it support aliyun?

**Comment by noahbuscher** [comment]
I'd prefer to make this as a plugin, but cannot find a way to modify the default inbox thread view (to hide the snoozed messages) based on the values in a custom data store.

Is this something that can be done with an external plugin, or would one have to edit the src? :confused:

**Comment by oojacoboo** [comment]
Noah, you should move the messages to an IMAP folder so it's portable across devices.  Then somehow modify/store metadata with the email.







.................................................................................................................................

Jacob Thomason

Ackoo Solutions, LLC  •  http://ackoo.com




Fax:  866.329.1596

Cell:  478.361.1263

**Comment by noahbuscher** [comment]
Ah! Great idea.

I spaced off x-device compatibility.

Though wound't a computer running N1 need to be active to change the state? If so, what would the point of storing the metadata be? Solely if the person was running two instances of N1?

Thanks. 😄

**Comment by oojacoboo** [comment]
Right, that's a potential issue.  However, does it matter if state changes if you're not checking it?

A mobile app is key here.  This is going to be a big issue going forward for N1 unless someone compiles to iOS soon.  I think the project should be seen as more platform agnostic.


...............................................
Jacob Thomason

**Comment by jstejada** [comment]
referencing #1179

**Comment by emorikawa** [comment]
I'm making this the master thread for Snoozing Mail.

See: #1179, #290, #312 as duplicates.

**Comment by markbao** [comment]
@jstejada Really looking forward to this.

What's the architecture behind this going to look like? Sounds like this and send later (@emorikawa) are going to need a backend on top of Gmail/Nylas. Will this be hosted at Nylas? Will it be open-source so that it can be self-hosted as well used by a (hypothetical) third-party mobile client?

**Comment by grinich** [comment]
@markbao we haven't totally figured it out yet. we're just trying to get a few of these features built before we know the generalized architecture for others too

**Comment by noahbuscher** [comment]
Oh! This is exciting!

**Comment by tommydangerous** [comment]
I NEED THIS!

**Comment by alairock** [comment]
This is the only thing left really that I am missing from a desktop client right now. I have it with Inbox by Google and Spark on my phone. I'd love to have a dedicated mail app for my mac. 

PS THANK YOU FOR GETTING US UNIFIED INBOX!

**Comment by tommydangerous** [comment]
:+1:

**Comment by tommydangerous** [comment]
Can we snooze yet?

**Comment by jstejada** [comment]
this has landed in the latest release! enjoy!

**Comment by tommydangerous** [comment]
Is there a shortcut to Snooze?

**Comment by ibalajiarun** [comment]
Is there a way to move snoozed emails to inbox manually?
