### ISSUE TITLE
 Bad package quality error on Ubuntu 15.10

### ISSUE THREAD

**Issue by dszmaj** [nylas/N1#710]
Ubuntu refuses to install actual downloaded deb package.

Lintian check results for /home/dominik/Pobrane/N1.deb:
E: nylas: control-file-has-bad-permissions postinst 0775 != 0755
E: nylas: control-file-has-bad-permissions postrm 0775 != 0755
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.

**Comment by mbilker** [comment]
This is very odd. What is `Lintian`? This looks like a permissions issue when building the package. I am able to install the package fine under Debian 8.

**Comment by mbilker** [comment]
Oh. Thank you posting your OS. It really helps with these kinds of errors.

**Comment by valtlfelipe** [comment]
Same issue on Ubuntu 14.04.

**Comment by bengotow** [comment]
Hey folks—this is pretty strange. Anyone know what causes `0755 != 0755`? We recently switched the linux builds to TravisCI instead of our custom-rolled Jenkins box, but it seems to work on some linux machines and not others? :-/

**Comment by mbilker** [comment]
@bengotow Hate to point this out. It's `0775 != 0755` not `0755 != 0755`. I am guessing the `umask` is set. A way to avoid this would be to `chmod` the control files in `script/mkdeb`.

**Comment by rockneila** [comment]
same issue on elementary OS 0.3.2

**Comment by kirtangajjar** [comment]
Same Issue

**Comment by mbilker** [comment]
Elementary OS uses APT to install packages, and is derived from Debian or Ubuntu. I will see about fixing this issue.

**Comment by mbilker** [comment]
That is really odd. I am using Debian Jessie in a VM and it updated just fine to `0.3.32`. My `/etc/apt/sources.list.d/nylas.list` contains `deb [arch=i386,amd64] http://apt.nylas.com/debian jessie main`. The SHA256 sum of the package is `9acee6b5cb3bd962f217af9e315d65d879532ba09e014ac874a07b3ddcaa35f4`.

**Comment by mbilker** [comment]
The control files have the correct file mode of `0644` for the `control` file and `0755` for the `postinst` and `postrm` files.

**Comment by bengotow** [comment]
Hi folks — can you try this build and see if it resolves the issue for you?

https://edgehill.s3.amazonaws.com/0.3.43-c8dcab5%2Flinux-deb%2Fx64%2FN1.deb

It should address the permissions issue - just want to check and make sure you don't encounter any other errors before we ship an update.

**Comment by rockneila** [comment]
no error on elementary OS
thank you solving the error

**Comment by mbilker** [comment]
FYI I never had this issue under Debian 8.

It appears to only show up when deb linter rules are enforced. The Ubuntu Software Center appears to enforce these rules.

**Comment by kamiller42** [comment]
No errors on Ubuntu 14.04 64-bit with 0.3.43-c8dcab5-linux-deb-x64-N1.deb.

**Comment by kamiller42** [comment]
I have to add that I removed my previously install, which was created using the bad deb, using Synaptic Package Manager (Complete Removal). Yet, when I installed the new .deb, my account information was still present, which is it did not perform a complete removal.

**Comment by mbilker** [comment]
@kamiller42 Removing the package will remove all of the application, but not its data. If you want to remove your data, delete `~/.nylas`. It is a hidden folder by default.
