### ISSUE TITLE
Sender Name Truncated if it contains the @ character

### ISSUE THREAD

**Issue by Sumukh** [nylas/N1#713]
This is a minor issue with how Nylas handles sender names. 

It seems like if there is a `@` character in the sender name (such as `<NYL@S nylas@nylas.com>`) the sender name would only be recognized as NYL

![image](https://cloud.githubusercontent.com/assets/882381/11805931/78ce6456-a2c4-11e5-84a1-e9c353566f52.png)

In the message body: 
![image](https://cloud.githubusercontent.com/assets/882381/11805953/9a649824-a2c4-11e5-8509-2b9b010eec67.png)

When expanded, it displays the full name. 

The full sender tag in this case was something along the lines of 
L@O 2012 <email@domain.com> 

This is on OSX with build 0.3.29-1904c6f 

I'm happy to poke around to try to see where the issue is. I suspect this is a regex pattern to handle cases of senders that do not provide a name field that greedily matches to the first `@`.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—it definitely sounds like we've got some parsing code that is being too aggressive. When the headers are collapsed, we call `contact.firstName()` to get something short to display (so it would say something like "Ben, Evan, Mark, L@O To: You").

If you could do some poking, there are test cases for that method here: https://github.com/nylas/N1/blob/stable/spec/models/contact-spec.coffee#L49. I think you should be able to add a new test case with name "L@O 2012" (I guess "firstName" should be "L@O"?) and run the tests with `./N1.sh --test`
