### ISSUE TITLE
Feature Request: Quick view attachments

### ISSUE THREAD

**Issue by davidmaneuver** [nylas/N1#714]
Just like in Apple Mail and Sparrow: Click the attachment and press space bar to quick view.

Would be a time saver.

**Comment by fjarrett** [comment]
+1

**Comment by Cu8eR** [comment]
+1

**Comment by ambarshante** [comment]
+1. Don't always want to download attachments. Have to go back to Gmail every time to view without downloading. Especially Word, Excel, PDF, and basic image types - JPG, PNG.

**Comment by mbilker** [comment]
@ambarshante If you want to solve part of the problem, you can set downloading of attachments to manual.

![2015-12-23-12-40-45_433x167](https://cloud.githubusercontent.com/assets/1266541/11981615/6992f844-a972-11e5-95f3-ebd349df5544.png)

**Comment by mbilker** [comment]
@ambarshante That can be found in `Preferences -> General` and all the way at the bottom of that page.

**Comment by ambarshante** [comment]
@mbilker Thanks! Already did that.

Just noticed that this also cause inline images to not get displayed - Issue #621 - at least for my work email which runs on Google Apps.

However, inline images are loading on my personal Gmail account - regardless of whether the Download Attachments option is set to Manually, or When Read.

**Comment by mbilker** [comment]
Inline images are usually HTML <img> elements. They are not bound by the
attachment message.

**Comment by nrutman** [comment]
+1

**Comment by jackiehluo** [comment]
Oh, just realized that this issue's a duplicate. Merging into #1086!
