### ISSUE TITLE
A new issue on the feedback window [Ubuntu 14.04]

### ISSUE THREAD

**Issue by PhoenixFlying** [nylas/N1#716]
![screenshot from 2015-12-16 15 09 41](https://cloud.githubusercontent.com/assets/12250549/11834405/1500dfa0-a407-11e5-8ae2-d7a9c02e4d54.png)

Hi all,
I made the N1 upgrade to the newest version just now, but something got worse on the feedback window and  the codes in this script didn't work properly (shown in the screenshot above). Maybe some new bugs occured. 

platform: Ubuntu 14.04 64bits

**Comment by PhoenixFlying** [comment]
The newest version of N1 seems to remove the menu bar and there is no menu option shown in the menu bar area of the main window. I don't know if it's a new feature of this software and maybe I should check out the upgrading log files to confirm it.

**Comment by sergeyklay** [comment]
+1 me too

**Comment by jstejada** [comment]
merging into #773

**Comment by jstejada** [comment]
reopening becasue this seems to be unrelated to #773.
@PhoenixFlying , what do you mean exactly by:
> N1 seems to remove the menu bar and there is no menu option shown in the menu bar area of the main window.

Can you send a screenshot?

**Comment by sergeyklay** [comment]
> N1 seems to remove the menu bar and there is no menu option shown in the menu bar area of the main window.

+1

@PhoenixFlying 

Try the following:
- Terminate application (see also in system tray)
- Remove `~/.nylas`
- Reinstall application
- Tun again

These steps helped me to solve this issue

**Comment by PhoenixFlying** [comment]
As you can see, the menu buttons don't appear in the menu bar area.
In normal window size, the menus were not shown on the top menu bar:
![screenshot from 2015-12-21 14 21 02](https://cloud.githubusercontent.com/assets/12250549/11926969/e2f37512-a803-11e5-95b1-9bb9f6353024.png)

In fullscreen size, the menus still disappeared:
![screenshot from 2015-12-21 14 21 23](https://cloud.githubusercontent.com/assets/12250549/11927387/236741c0-a807-11e5-951a-26be6443da4f.png)

This issue happened from time to time.

**Comment by PhoenixFlying** [comment]
@sergeyklay Thanks for your suggestion! ^O^  I'd like to try it when the issue comes next time.

**Comment by bengotow** [comment]
We've removed the feedback window in a recent update and replaced it with a (much more useful) knowledgebase, so this should be resolved. Cheers!
