### ISSUE TITLE
Wired behavior when using the Chinese input method RIME to write new message

### ISSUE THREAD

**Issue by whhone** [nylas/N1#717]
Wired behavior when using the Chinese input method RIME (http://rime.im) to compose a new message on Mac.

![screen shot 2015-12-16 at 12 27 52 am](https://cloud.githubusercontent.com/assets/1200104/11835922/df6e704e-a38b-11e5-9b77-5dc8f1d06737.png)

Typing in fields "Recipients" and "Subject" are fine.

**Comment by bengotow** [comment]
Hi @whhone — can you try this in the latest release 0.4.40? I think this has been fixed.

**Comment by jackiehluo** [comment]
Closing this issue for now since it should be fixed—let us know if it's not!
