### ISSUE TITLE
Feature Request: Attach a signature to an alias

### ISSUE THREAD

**Issue by jacobwegner** [nylas/N1#723]
Aliases were recently added to N1
* https://trello.com/c/KO2UHr0i
* https://github.com/nylas/N1/issues/234

I'd love to be able to attach a particular signature to a particular alias.  Right now, signatures can only be attached to an account.

Thanks for your consideration!

**Comment by jclusso** [comment]
+1

**Comment by jstejada** [comment]
merging into duplicate #848
