### ISSUE TITLE
Ubuntu theme 

### ISSUE THREAD

**Issue by ahmedlhanafy** [nylas/N1#727]
##Is there any plans to add support for an Ubuntu theme just like what you did with Windows?
Like this one
![Image of the theme]
(https://pbs.twimg.com/media/CSGseRiXAAEHLJm.png)

**Comment by mbilker** [comment]
Isn't Ubuntu starting to integrate more into GTK+3?

**Comment by ahmedlhanafy** [comment]
I don't care about their technology, the thing that I'm mentioning here is the look and feel only with CSS

**Comment by bengotow** [comment]
Hi @ahmedlhanafy — I think it'd be great to have an Ubuntu-style theme built in, but there are so many linux visual styles we'll never be able to make it match on all distros. We're slowly adding support for custom themes—there are a few already like http://noahbuscher.github.io/N1-Taiga/. Would love a PR or a new theme package!

**Comment by ahmedlhanafy** [comment]
I have created a quick theme for Ubuntu and here is its link https://github.com/ahmedlhanafy/Ubuntu-Ui-Theme-for-Nylas-N1
