### ISSUE TITLE
I can't download it

### ISSUE THREAD

**Issue by hp198410** [nylas/N1#73]
I  want to download the mac version.
and I go to the download page, type email, click OK button.

page show thank you, but I can not see any thing with download info.

how can i download it?

**Comment by frisinacho** [comment]
with that, you've subscribed to a list of invitations... now you must wait to your turn :stuck_out_tongue_winking_eye:

**Comment by hp198410** [comment]
3 days , I did not show any thing in my mailbox.

**Comment by adamdicarlo** [comment]
Why the list of invitations, though? That reminds me of Mailbox.app and implies that perhaps there's a backend this app requires—does the client require access to a specific proprietary backend?

**Comment by adamdicarlo** [comment]
Ah, it requires a backend... but the backend is open source! That is great to see. https://github.com/nylas/N1#running-locally

**Comment by cschermerhorn** [comment]
The invitations take time, just be patient.  Once you receive one, you will be bale to download the app.

**Comment by mbilker** [comment]
If you really don't want to wait, you can always spin up an instance of the Sync Engine.
