### ISSUE TITLE
Open Nylas first time

### ISSUE THREAD

**Issue by csimonmoi** [nylas/N1#731]
When you open client first time in Windows 10, it covers the bottom bar. So you have to click on the left top corner, minimize a bit and then maximize again. that solves.

**Comment by mbilker** [comment]
Is this still an issue in the latest version?

**Comment by mbilker** [comment]
Please reopen if it is.

**Comment by csimonmoi** [comment]
Hi

every issues are still there even in the new last update. Nothing changed for
previous issues in **Windows 10**:

  

  * no spell checker in italian, english or in whatever language;
  * when you open for first time your app the window is not perfectly centered and covers the Windows bottom bar;
  * no way to delete emails in "Sent"... they magically reappear;
  * no way to tell Windows 10 this is my favourite app for mail. It does not even appear in the list in settings.

hope this help, finally.

Thanks  

  

**  
**

> On Feb 10 2016, at 3:45 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Please reopen if it is.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/731#issuecomment-182174597).![](https://github.com/notifications/beac
on/APTadqXoGkAnUpilaHC0Un5PtbdVY_L2ks5pipvMgaJpZM4G3LMM.gif)
