### ISSUE TITLE
Missing icons after installing update

### ISSUE THREAD

**Issue by sergeyklay** [nylas/N1#732]
After update to the latest 0.3.32 release using Ubuntu Software Updater
![selection_006](https://cloud.githubusercontent.com/assets/1256298/11866270/a2d3d764-a4b2-11e5-97ff-6bec48a60998.png)

**Comment by bengotow** [comment]
Hi @sergeyklay — we've had a few reports of this happening on Linux. Do you know if the app was running when you installed the update? It unfortunately can't handle being moved or having paths change while it's open. Can you try restarting and see if that fixes the issue?

**Comment by sergeyklay** [comment]
@bengotow Hi! I've restarted many times. Unfortunately it didn't help. And yes, the N1 was launched during updating

**Comment by mbilker** [comment]
I can report this as well. I updated N1 while it was running, and N1 likely was confused by the ASAR archive not matching up.

**Comment by mbilker** [comment]
Restarting N1 did fix my issue.

**Comment by mbilker** [comment]
@sergeyklay have you tried quitting N1, removing N1 from the system, and then reinstalling N1. It shouldn't delete your data as your data is stored in `~/.nylas`.

**Comment by sergeyklay** [comment]
No, I'll try tomorrow at work

**Comment by mbilker** [comment]
@sergeyklay Alright then.

**Comment by sergeyklay** [comment]
@mbilker I've closed N1,  removed `~/.nylas` and reinstalled it. All ok. Thanks.
@bengotow Should I close this issue?

**Comment by jstejada** [comment]
hey guys, I think this is safe to close
