### ISSUE TITLE
Images not showing, get path instead

### ISSUE THREAD

**Issue by Yerlix** [nylas/N1#733]
Inline images inside an email are not downloaded I think.

![image](https://cloud.githubusercontent.com/assets/3891388/11834741/7e919384-a3cf-11e5-8c53-bdcca0d6baa2.png)

When I check the path, the folder nor the file exists.

I'm using OSX Yosemite (10.10.5) and N1 version 0.3.32

**Comment by awmartin** [comment]
I'm having this problem, too.

I'm interested in looking into fixing this myself. Anyone have a hint on where to look? Should inline images be extracted and added to the list of downloads (as attachments are)? On receive or on view?

**Comment by vpakg** [comment]
Using 0.3.36 on linux and still having this issue. Images won't show.

**Comment by nigeljyng** [comment]
I am having this problem as well. Using 0.3.45 on Windows 7

**Comment by jstejada** [comment]
hi all! I'm merging into duplicate #621
