### ISSUE TITLE
Kaspersky false-positive?

### ISSUE THREAD

**Issue by Laerte** [nylas/N1#734]
Hi, 

When a first attempt to install **N1**, i received a malware alert **PDM:Trojan.Win32.Generic** (Kaspersky removed the setup file), after this i download again file and installed the client without any alerts, do you guys use mirrors? This is a false positive? Below the screenshots took from Kaspersky after process.

![k1](https://cloud.githubusercontent.com/assets/5853172/11869827/d198f7cc-a4a9-11e5-89d2-230f255fa166.png)
![k2](https://cloud.githubusercontent.com/assets/5853172/11869838/f01a27ca-a4a9-11e5-9146-39637f94686d.png)

**Comment by bengotow** [comment]
Hey! We actually just got whitelisted by Kapersky last night, probably around the time you posted this issue. It might have gone through by the time you downloaded again. Cheers!

**Comment by surchs** [comment]
Same thing here with 360 Security (Trojan - HEUR/QVM41.1.Malware.Gen)

**Comment by iSimonWeb** [comment]
It is 8/2/2016 now, and Kaspersky Internet Security still see it as a malicious program.
Additionally I saw in the error log that the installer was trying to "burn to the ground" my Atom installation. JUST WHY?

**Comment by gr4h4n** [comment]
Just got the same error today, while installing N1. Do you have some suggestions why this is still the case ? 
Alert message was: PDM:Trojan.Win32.Generic was found in n1setup.exe

**Comment by iSimonWeb** [comment]
:+1: up
