### ISSUE TITLE
N1 reset my all account

### ISSUE THREAD

**Issue by khanshakeeb** [nylas/N1#735]
Hi,

Today when I have open my N1 it just reset all my configured account and ask me to start adding account again.

Kindly let me know what is wrong with N1.

Thanks

**Comment by grinich** [comment]
Hi @khanshakeeb --

What OS are you using? What email providers did you have connected?

**Comment by khanshakeeb** [comment]
I am using ubuntu14.04 and I was using Gmail accounts

**Comment by grinich** [comment]
We believe this behavior is due to a bug when the main disk reports that it is running out of space. Going to close and merge into #897
