### ISSUE TITLE
Feature Request: Menubar show/hide app

### ISSUE THREAD

**Issue by beachjustice** [nylas/N1#736]
An option for the menubar icon to open the app rather than a menu

**Comment by bengotow** [comment]
Hi @beachjustice — what platform are you using? Is this on Mac OS X? Unfortunately, we feel the current design (which opens a menu when you click the logo in the system status bar) is more consistent with OS X interface guidelines. We may add a global shortcut for bringing the app to the foreground though, which might achieve what your'e looking for!

**Comment by beachjustice** [comment]
Hi Ben, YEs, I am on OS X 10.11.

  

I know some apps have functionality where you can hold option while clicking
the menubar icon to see different options/behaviour,that could also be nice.
However, I can see the logic keeping it consistent with native OS X
behaviours.

  

> On Dec 17 2015, at 1:42 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@beachjustice](https://github.com/beachjustice) — what platform are you
using? Is this on Mac OS X? Unfortunately, we feel the current design (which
opens a menu when you click the logo in the system status bar) is more
consistent with OS X interface guidelines. We may add a global shortcut for
bringing the app to the foreground though, which might achieve what your'e
looking for!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/736#issuecomment-165543628).![](https://github.com/notifications/beac
on/APlTLna3rHaJ82x-zGossFORrhSoVxUPks5pQvl4gaJpZM4G3g_U.gif)
