### ISSUE TITLE
Spurious labels are showing up in N1 client

### ISSUE THREAD

**Issue by bashok001** [nylas/N1#737]
![screen shot 2015-12-17 at 9 53 19 am](https://cloud.githubusercontent.com/assets/2344626/11877417/06c31bfe-a4a4-11e5-970e-9958716986ba.png)

Yesterday,  I saw `\All` label. It disappeared but now I am seeing this `\Trash` label.

**Comment by jstejada** [comment]
merging into duplicate #744
