### ISSUE TITLE
Last Email in Inbox sometimes temporarily does not appear

### ISSUE THREAD

**Issue by rahatarmanahmed** [nylas/N1#738]
Version 0.3.32-b11131d (0.3.32-b11131d)
OS X El Capitan

Sorry about the vagueness of this issue, but I haven't pinpointed when this occurs. But occasionally when I open N1, I see that the very last email in my inbox isn't there. I notice this because when I archive one of the visible emails, the missing email reappears.

**Comment by bengotow** [comment]
Hey! You're definitely on to something— @jstejada and I were debugging an issue a few days ago where the unread count was off, and it turned out it was actually just that a thread was not being displayed at the bottom of the thread list. We'll dig in to this and see if we can get it fixed.

**Comment by grinich** [comment]
Going to close as stable. Please re-open if you have steps to repro.
