### ISSUE TITLE
Image blocking isn’t working consistently

### ISSUE THREAD

**Issue by meyer** [nylas/N1#739]
Due to my general paranoia, I use Little Snitch to keep an eye on incoming and outgoing requests on my MacBook Pro. Also due to my general paranoia, I like to keep images in emails from loading, which is why I’m a big fan of the ability to disable auto-loading of images:

![image](https://cloud.githubusercontent.com/assets/13781/11879112/3c4c3d96-a4ae-11e5-8246-c14207928b0e.png)

Big fan.

Occasional emails will trigger Little Snitch when an image isn’t caught by the regex. Is there a more reliable way to block images? It seems like the “Disable loading images” option should completely disable the `iframe`’s ability to connect to the network. I would dig into the code but I don’t really have time at the moment. Seems like Electron’s `webview` might be able to do a few things an `iframe` can’t?

Follow-up: Check out this weird bug I ran into yesterday. I haven’t been able to reproduce it again, but I did manage to GIF it. Every time I hit a key, all the images in the message were attempting to load, which was triggering Little Snitch.

![problemo2](https://cloud.githubusercontent.com/assets/13781/11879067/0bc434a8-a4ae-11e5-854b-6284a49715c2.gif)

**Comment by bengotow** [comment]
Hey @meyer — I definitely agree it'd be more robust to cut the message body off from the network entirely. Unfortunately the <webview> tag is as bit of a black box, and I think it'd prevent us from pulling sizing information out. I'll double check, though. (Webviews also run in their own processes in Chromium, which might have interesting performance implications...)

In the meantime, do you have any examples of message bodies that are triggering the alerts? I went through a bunch the last time we updated the "autoload images" regex and couldn't find any more.

Cheers—

Ben

**Comment by ssnepenthe** [comment]
I noticed it for the first time this morning...

N1 Version 0.3.32-b11131d (0.3.32-b11131d)
OS X 10.11.2
Type of account is gmail.

I recieved a message where a single image was being displayed even though i did not choose to show images.

On closer inspection, it looks like the image was set using the background attribute on a table element:

```
<table width="598" class="deviceWidth" height="403" border="0" cellspacing="0" cellpadding="0" background="https://services.google.com/fh/files/emails/bkg_billboard_v2.png" bgcolor="#42a0fc" style="-webkit-text-size-adjust: none; border-collapse: collapse !important; mso-table-lspace: 0pt !important; mso-table-rspace: 0pt !important; border: 0px; display:block;width:598px;  min-width:598px;">
```


![screen shot 2015-12-18 at 10 42 34 am](https://cloud.githubusercontent.com/assets/10903810/11903714/700ffe4a-a578-11e5-89e7-6069f5bb491a.png)

**Comment by bengotow** [comment]
Thanks @ssnepenthe — I've expanded the test suite for the autoload images plugins, and ensured that we look for images in any DOM attribute where they're allowed (src, background, placeholder, icon, poster, or srcset) as well as in CSS attributes. At the end of the day, I think we need to block network requests at a lower level, but we don't want to break things like iframe-based form submission (see Google Sheets emails, for example), so it'll be tricky to get right. Hopefully this will handle 99.9% of cases.
