### ISSUE TITLE
"Install New Theme" not working as expected

### ISSUE THREAD

**Issue by noahbuscher** [nylas/N1#740]
When I went to install a new theme with the latest update, I selected the directory, N1 stalled for 4-5 seconds, then a dialog came up saying something like "Package was installed. No reason to restart N1." Though it appears I did have to restart N1 as the theme was not applied and not in the themes dropdown. Did I read the message wrong, perhaps? :blush:

**Comment by bengotow** [comment]
Hmm—is there any chance there was an error in the console? Maybe you had another version of the same package / theme already installed?

**Comment by bengotow** [comment]
Also, make sure you select this directory (https://github.com/noahbuscher/N1-Taiga/tree/master/N1-Taiga) and not the one above it. Maybe that'd do it?

**Comment by noahbuscher** [comment]
I selected the correct directory, but I had debug flags enabled. I think perhaps because I already had the same theme in my `dev` packages directory that that is why it threw the error? I can try again and check the console logs in a bit here. :+1:

**Comment by bengotow** [comment]
Ahh I think that'd do it—having an existing package with the same name installed might make the installation a `no-op` essentially.

**Comment by noahbuscher** [comment]
Thanks for the clarification. :+1:
