### ISSUE TITLE
Feature Request: Search for labels

### ISSUE THREAD

**Issue by zellwk** [nylas/N1#743]
It'll be awesome if we could search for a label through the search field.

**Comment by mbilker** [comment]
Something like `label:blah` like what Gmail and GitHub allow for constraining searches is what I would like to see implemented.

**Comment by Cu8eR** [comment]
+1

**Comment by sergeyklay** [comment]
+1

**Comment by bengotow** [comment]
Hi folks—if your underlying account is a Gmail account, we actually forward the search query to Gmail so you can do `in:<label name>` and get the results you'd expect. We'll be revamping the search bar to make that more obvious sometime soon!

**Comment by zellwk** [comment]
Is this feature still working? I couldn't seem to get it to work on the latest version of Nylas

**Comment by arifb** [comment]
@zellwk No, it doesn't work, and this was a great feature of nylas (the forwarding of search query to gmail). Should be reopened.

**Comment by zellwk** [comment]
Can we reopen this?
