### ISSUE TITLE
Some domian on live.com service can not add new account to N1

### ISSUE THREAD

**Issue by iamlop** [nylas/N1#745]
Hi Nylas team,

           Thank you for amazing app but i have a small issue. I own of imageslum.net and use email service by http://domains.live.com but i can not add account to N1 after select outlook provider.

Thank you.

**Comment by jstejada** [comment]
hey @iamlop , maybe try using the IMAP option when setting up your account

**Comment by khamidou** [comment]
Hey @iamlop, I'm a backend engineer at Nylas. To add on what @jstejada said, you're using Windows Live Domains, which has been deprecated by Microsoft. It's very unlikely that we had support for this product in the future.

**Comment by SalahAdDin** [comment]
But, for now, we have problem with this, my mail is live.com, if i try login using @outlook.com i get credentials problems.
