### ISSUE TITLE
 Feature Request: RSS reader

### ISSUE THREAD

**Issue by sergeyklay** [nylas/N1#747]
It would be awesome if you could implement an RSS Reader, as is done in Thunderbird.

![selection_032](https://cloud.githubusercontent.com/assets/1256298/11890997/052a4960-a563-11e5-9c61-c149ed7442cd.png)

**Comment by jstejada** [comment]
hey @sergeyklay , this is a great idea for a plugin! Don't think it will be developed into core N1 functionality though
