### ISSUE TITLE
Feature Request: Use a beautiful screen for Inbox Zero status

### ISSUE THREAD

**Issue by fjarrett** [nylas/N1#748]
When you visit the Drafts view, and there aren't any messages, a beautiful screen with subtle animation is displayed. It's really nice, but I'm not yet sure why Drafts deserve so much fun? :stuck_out_tongue: 

It seems like this beautiful layout should really be used as an Inbox Zero view instead. I think there should be a screen the user can look forward to seeing at the end of a productive day.

<img width="1280" alt="inbox-zero" src="https://cloud.githubusercontent.com/assets/522158/11891056/779b769c-a520-11e5-8a91-e1a0b8106e84.png">

**Comment by mrkrstphr** [comment]
Very bummed that Inbox doesn't get this treatment, but other random folders do. I wanna get pumped when I delete that last email!

**Comment by hathix** [comment]
+1

**Comment by onbjerg** [comment]
I just reached Inbox Zero today. It was pretty anti-climatic and I almost feel like I want to fill up my inbox again. Are there any near-future plans to implement this?

**Comment by bengotow** [comment]
Hey folks! We shipped a handful of Inbox Zero animations in 0.4.19 and a few more are on the way. Going to go ahead and close this.
 
![image](https://cloud.githubusercontent.com/assets/1037212/14541951/787cb9ee-025a-11e6-8d4c-ff7e34cdfa59.png)
