### ISSUE TITLE
Gentoo package installer

### ISSUE THREAD

**Issue by sakshamsharma** [nylas/N1#749]
I'm a Gentoo user, and would love if N1 had an ebuild for Gentoo. I do see that a PKGBUILD is available for Arch Linux now. Would be great if Gentoo got an Ebuild soon too.

**Comment by mbilker** [comment]
@sakshamsharma There is an unofficial ebuild for Atom at https://github.com/aegypius/overlay/tree/master/app-editors/atom. I wonder if you could rewrite it for N1.

**Comment by mbilker** [comment]
I can try out Gentoo to try and write one for N1. I have been wanting to try out Gentoo for while.

**Comment by sakshamsharma** [comment]
Oh well I can surely try once I get some time. I've been wanting to try writing an ebuild since long. That seems like a nice place to start. Thanks :smile:
Do comment here if you submit an ebuild sometime, I'll do the same.

**Comment by mbilker** [comment]
Alright then.

**Comment by szymonpk** [comment]
Rough on the edges and I'm not entirely sure about dependencies, but it works for me:

**nylas-n1-0.4.5.ebuild**
```
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=5
inherit unpacker eutils

DESCRIPTION="N1"
HOMEPAGE="http://www.nylas.com/"

SRC_URI_AMD64="https://edgehill.s3-us-west-2.amazonaws.com/${PV}-b0ec335/linux-deb/x64/N1.deb"
SRC_URI="
        amd64? ( ${SRC_URI_AMD64} )
"

LICENSE=""
SLOT="0"
KEYWORDS="~amd64"

DEPEND="dev-vcs/git
    gnome-base/gconf
    x11-libs/gtk+:2
    virtual/udev
    dev-libs/libgcrypt
    x11-libs/libnotify
    x11-libs/libXtst
    dev-libs/nss
    dev-lang/python
    gnome-base/gvfs
    x11-misc/xdg-utils
"

S="${WORKDIR}"

RESTRICT="mirror"

src_unpack() {
    unpack_deb ${A}
}

src_install() {
    cp -R "${WORKDIR}/usr" "${D}" || die "install failed!" 
}
```

**Comment by mbilker** [comment]
That `EBUILD` takes the built N1 for Ubuntu. Does @sakshamsharma want an `EBUILD` for the open-source version?

**Comment by sakshamsharma** [comment]
Well as long as the binary is compatible with Gentoo, this should be fine. Although this is against the philosophy of Gentoo. Open source one would be the right way to do it. Besides, this requires the electron executable to be installed, which has been missed in the Ebuild. It's not in the official repos either, so I think that'd involve commands from the bootstrap script in /script/bootstrap.

Anyhow, Open source one should be the preferred one. Binaries may not always work.
I'm running quite busy right now, I can perhaps try in the coming few days to write an Ebuild if possible and submit.

**Comment by mbilker** [comment]
If you want to build the electron binary, go for it, but it is close to a full Chromium build. The build script downloads the prebuilt Electron binary so it isn't too bad, but it will build every component of N1 locally (minus a few proprietary components).

**Comment by jackiehluo** [comment]
Closing for now because it's not in the scope of this project!
