### ISSUE TITLE
Feature: Group emails by email sender

### ISSUE THREAD

**Issue by hivearts** [nylas/N1#75]
Hi All,

I am always seaching for great email client, but all of them is nothing special except unibox on osx for now.

I think open source is the way to make best email client ever.

Well first i will propose best feature which unibox have, it is group email view by email sender. Well all conversations with 1 person is in the same 'email'.

Best way to implement it is to make switch 'Group view' so users can view emails in standard view and grouped view.

**Comment by bengotow** [comment]
Hey @hivearts — this is a great idea. I haven't used "Group view" myself, but it sounds useful. You could definitely implement this as a plugin that adds a new view to the sidebar. It sounds like a simple approach would be to fetch the last ~1000 emails in the inbox, and then cluster them based on recipients. (Our database layer doesn't have the right indexes and columns to enable this sort of `GROUP BY`)

I'll add this to our open-source plugin ideas board on Trello—feel free to upvote it if you have a Trello account and track it there! https://trello.com/c/yFXp7vO7/19-inbox-view-where-messages-are-grouped-by-sender

**Comment by daki309** [comment]
@bengotow Is it possible to disable group view? I personally think that my inbox get's incredibly confusing when it's enabled!

**Comment by viraf** [comment]
Is this available in the released version? I am unable to get the group view
