### ISSUE TITLE
Bug: Email address is not valid if it contains an apostrophe

### ISSUE THREAD

**Issue by tomodwyer** [nylas/N1#754]
My work email address contains an apostrophe. I can send via the Gmail web interface to this account, but cannot send via Nylas N1. Emailing to an alias without an apostrophe works in both Nylas N1 and Gmail, which makes me assume the apostrophe is the problem.

## Steps to Reproduce:
1. Set up an email address with an apostrophe in the user name
2. Send an email using Gmail to new apostrophe email address to confirm it works
3. Enter this email address in the Nylas N1 recipient field
4. Press send and you receive the "Cannot Send" error

## Attachment:

![nylas-apostrophe](https://cloud.githubusercontent.com/assets/16018370/11894519/b025e692-a56f-11e5-9024-ca8bab93314d.png)

**Comment by bengotow** [comment]
Hi @tomodwyer — thanks for filing this. Looks like we were missing support a few characters in email addresses (including `'`). Should be fixed in the next release!
