### ISSUE TITLE
 Feature Request: Address book

### ISSUE THREAD

**Issue by sergeyklay** [nylas/N1#755]
It would be great if N1 could store address book locally (for example SQLite) and import from other services (eg. Gmail). I think it would be cool if I had the opportunity to work with address book - for example edit, create and search contacts.

**Comment by Cu8eR** [comment]
+1

**Comment by pat-riley** [comment]
+1

**Comment by makerax** [comment]
+1
The local address book could be the first step but I think that sync contacts is essential.

**Comment by g105b** [comment]
:+1: A really good feature, also would love to see Exchange/Gmail sync capability.

**Comment by Iain-Stevenson** [comment]
+1

**Comment by mbilker** [comment]
Merging into #1031

**Comment by adriangrantdotorg** [comment]
+1

**Comment by AleksandTheLosev** [comment]
+1

**Comment by leehblue** [comment]
+1

**Comment by Lyptik** [comment]
+1
