### ISSUE TITLE
Explanation needed: Getting spammed by you on the email address of my account.

### ISSUE THREAD

**Issue by atrull** [nylas/N1#756]
Dear Nylas,

I have received spam from you.

The subject was "New features, a Mailbox-inspired theme & more!"
Received: from mx30.a.outbound.createsend.com

I did not sign up for a service with you. I did not at any point knowingly give you the authors of the software my email address, let alone the permission to email me with it. It was not used in correspondence with you. I did not sign up for a service with you.

This email came from outside of my mail client. It was not 'inserted' into the inbox by N1. I was using thunderbird at the time anyway.

The only time my email address has come anywhere near anything bearing the Nylas name is when I put it into the settings of my account in the client - NOT your website, NOT your mailing list, NOT your service.

Please explain why I have been spammed ?

If I remove and add my account will the spam start again ? Please make these things clear. 

What makes you think you should sequester my email address out of my installation's config, to servers of yours, to then send me email ?

I have unsubscribed now, from what I don't know (I never signed up?) - if I add another account will I be spammed on that one too ? Is it once per installation or once per account, or once per both ?

What if the same mechanism was used to sequester my password or other private details ? I mean, that config is fairly close together. Often stored in the same location, database, etc.

Alex

**Comment by ioev** [comment]
Got the same email to a shared work email that I configured the email client to use.  Unsubscribed right away, but really don't appreciate being spammed to accounts that I haven't specifically asked to be.  It would be comforting to know if this email address can be purged from being stored on any remote servers by Nylas.

**Comment by grinich** [comment]
Hi folks. I work at Nylas.

Using N1 with the cloud sync engine (how it's configured by default) automatically adds you to the email update newsletter, which includes information about new features and plugins. 

Users who [run the sync engine themselves](https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine) aren't added to this list. (Note the Nylas sync engine is open source free software, also [available on GitHub](https://github.com/nylas/sync-engine).) 

If you'd like to read more about the architecture of N1 under the hood, [check out the N1 FAQ](https://nylas.com/n1/faq). 

Sorry about the duplicate messages. It seems you're in the group of users who have several accounts connected to N1. We overlooked this when sending out the newsletter, and for future news we're going to add a setting to specify a single account for the updates. 

Our team is a bunch of programmers working to make N1 better every month, and unfortunately not a team with lots of marketing experience. We hope that people who are experimenting with N1 want to hear about new developments, featured plugins, and our roadmap. But we definitely understand how annoying it can be to receive the same email multiple times!

You can obviously unsubscribe from the newsletter using the personalized link at the bottom of each message. If you'd like to discontinue using N1 with the cloud sync engine, please send a note to support@nylas.com from the email address you'd like us to delete. We can usually do this within a few hours.

**Comment by atrull** [comment]
Hi Grinich,

You've made it fairly non-obvious that you're defaulting to putting user's credentials and a cache of email somewhere other than on their own machine client or server. Most users do not read FAQs. Users who are used to the traditional kind of MUA/MTA, do not expect the mail client to do the things yours does. If your users are anything like me they are assuming a different behaviour to the default. But you seem so comfortable with that behaviour that it barely registers. Scares the fuck out of me. As per twitter I now have to change some of passwords because I trusted you when I shouldn't have. Think on that.

FWIW you may also want to try deliver updates of news via the app, rather than via sequestered email addresses, that way less personal information is stored on systems the user doesn't control (look at the thunderbird style which pops an email in the inbox ?). But given your default behaviour (all the pies! FEED ME SEYMOUR!) that is small chips compared to current behaviour.

While the client's interface is nice, the default behaviour and lack of obviousness are going to stop me from using it for the time being. It's fairly obvious you don't think this is a problem at all. The new normal et al. No doubt you'll get lots of users because of the slick interface but heaven forbid you ever get breached.

**Comment by grinich** [comment]
@atrull Thanks for the feedback. We'll work to make this more clear in the onboarding flow.

**Comment by crypticsymbols** [comment]
Yeah, I just noticed this. @grinich Are you saying that by using N1, our email addresses have been stored? By Nylas or a third party?

I'm extremely unhappy with this. 10/10 pissed, actually. A mail client should never, EVER offsite information of any sort without making it absolutely explicit that that is what's happening. Just so you know, I just changed all my email addresses with an extremely careful system of aliases and +addressing so I have control over who has my contact information. There is no service that I do not absolutely trust that has my actual, bare email address.

Well, or so I thought. Now I get to do it all over again. It only took me 20 hours.

IMHO, there is absolutely zero justification for this. Please contact me off-thread about getting my addresses removed from any and all systems they've been added to.

**Comment by atrull** [comment]
N1 client offsites *everything* by default @crypticsymbols - including your email address, passwords you put in and actual email contents (for indexing etc).

Prepare to start changing your passwords etc. Also that mail you never wanted anyone to see ? It's indexed on someone else's server now. Beg nicely for them to delete it without looking at it.

**Comment by grinich** [comment]
@crypticsymbols just send a note to support@nylas.com from the address(es) you'd like us to delete and we'll add them to the immediate deletion queue. You can also ping me directly via username@nylas.com. (Might be a bit slow this weekend since our small team is away for MLK holiday.)

There are a bunch of specific technical reasons for this client/server model that N1 uses, largely related to the heavy lifting of IMAP/SMTP/MIME/ActiveSync. It's the same model used by Mailbox, Microsoft Acompli/Outlook, and countless others. We thought that we've been pretty upfront about this in our FAQ and onboarding flow, but obviously not enough, which we're working to fix. Sorry for the pain of having to reconfigure your mail system. ( 

One of the core reasons we released the entire stack as open source free software (GPL/AGPL) was to encourage people to run it themselves and support the existing federated system of email. We think this is pretty unique-- Gmail, Outlook, iCloud... Even FastMail aren't open source. And with the demise of Thunderbird, there wasn't any solid open source option. We don't presume to think Nylas is close to that, but it's certainly something we'd like to strive towards. 

The sync engine is pretty easy to set up and is a modern stack you probably already know how to run. Maybe you can even hack on the internals! https://github.com/nylas/sync-engine

Since this isn't directly an N1 bug, I'm going to keep the issue closed. Please send feedback like this directly to our team via support@nylas.com

**Comment by crypticsymbols** [comment]
Classy. Real classy. Thanks for this bullshit dystopian problem I now have to spend my weekend fixing.
