### ISSUE TITLE
Feature Request: Ability to recall unread emails, Boomerang type automation.

### ISSUE THREAD

**Issue by greenspand** [nylas/N1#758]
Would be great if there would be a way to recall an unread email, just as in outlook.
Automation to send emails in batches, or based on workflows, maybe some kind of filters.
Also notifications and reminders regarding the created tasks would be awesome.
Cheers Team.

**Comment by bengotow** [comment]
Moving to https://trello.com/c/QA7uuNfs/61-ability-to-recall-unread-emails-boomerang-type-automation
