### ISSUE TITLE
Broken select style in standard theme

### ISSUE THREAD

**Issue by sergeyklay** [nylas/N1#760]
All selects like this:

![nylas_012](https://cloud.githubusercontent.com/assets/1256298/11899036/15e92fea-a5a5-11e5-9f4d-6cffa1b1f284.png)

Ubuntu 14.04.3 LTS
N1 0.3.32-b11131d

**Comment by jstejada** [comment]
hey @sergeyklay thanks for reporting this. What is wrong with it exactly?

**Comment by sergeyklay** [comment]
I can't reproduce error at home. Mb this is OS issues
