### ISSUE TITLE
Feature Request: Add Inbox link to the notification bar

### ISSUE THREAD

**Issue by dominikzogg** [nylas/N1#762]
in my point of view, it would be great if the notification icon got some entry points as inbox (sent...)

**Comment by jstejada** [comment]
hey @dominikzogg , thanks for conributing! I don't know what you mean exactly by entry points?

**Comment by dominikzogg** [comment]
Hello @jstejada, i mean the notification icon within statusbar, which got links to New mail and Settings. I would like to add Inbox for example

**Comment by jstejada** [comment]
oh ok, thanks!

**Comment by jstejada** [comment]
@dominikzogg , what OS are you running?

**Comment by dominikzogg** [comment]
Linux (Ubuntu)
Am 20.12.2015 10:15 nachm. schrieb "Juan" <notifications@github.com>:

**Comment by jstejada** [comment]
got it, I have 2 questions:
1. how do you open the notification bar menu? Do you do a right-click? or do you do a normal left click on the icon?
2. what happens when you left click the icon?
thanks!

**Comment by dominikzogg** [comment]
looks same on left and rigt click
- New Message
- Preferences
- Quit N1

**Comment by jstejada** [comment]
ok, thanks!

**Comment by jstejada** [comment]
ok, you should see this in an upcoming release

**Comment by dominikzogg** [comment]
@jstejada thank you
