### ISSUE TITLE
Registered to N1 newsletter without asking

### ISSUE THREAD

**Issue by AntoineTurmel** [nylas/N1#763]
I was wondering if adding a mail account into N1 automatically register you in your newsletter ?
Because I was not asked, and I tried to keep a certain mail box "spam" free...

**Comment by mbilker** [comment]
Hmm. Maybe. I got three newsletters and one was to an address I know I didn't register to the newsletter.

**Comment by jstejada** [comment]
They @AntoineTurmel! Yes, the newsletter is sent out to all email addresses that connect with N1, but if you don't want us to ever send the newsletter to a certain email address again, there's always an 'unsubscribe' link at the bottom of the email.

The goal of the newsletter is to keep our users up-to-date on changes and features, as well as highlight cool community created projects. Keep in mind that no data of any kind is ever sold, or used for advertising purposes. https://nylas.com/privacy-policy

Based on the question, it sounds like we can do a better job of making this point clear in the next newsletter, as well as highlight it in other places and look at other ways of keeping everyone updated.

Thanks!

**Comment by AntoineTurmel** [comment]
Ok good, I was wondering why I received this ;) Maybe a checkbox with subscribe to newsletter ?

**Comment by grinich** [comment]
@AntoineTurmel Yep, we're going to add that!
