### ISSUE TITLE
Keyboard shortcut for "Mark as spam"

### ISSUE THREAD

**Issue by jerzygangi** [nylas/N1#765]
Gmail has a keyboard shortcut where "!" marks an item as spam and removes it from your inbox. This is missing from the Nylas Gmail shortuct list.

**Comment by mataal** [comment]
+1

**Comment by orschiro** [comment]
Dear all, 

As a quick follow-up, can you add the information about `!` to the list of shortcuts below?

Thankfully,

~Robert

![Uploading **image.png…]()**
