### ISSUE TITLE
Copy and Paste loses line breaks

### ISSUE THREAD

**Issue by natemhanson** [nylas/N1#766]
When you copy an email body and paste it into an new compose window, it loses any line breaks it had. I realize that N1 doesn't do formatting, but that isn't formatting.

![screen shot 2015-12-18 at 11 19 21 am](https://cloud.githubusercontent.com/assets/6539048/11905141/74606b6e-a579-11e5-810d-32b1e345a9bf.png)

**Comment by abhikp** [comment]
It also loses tabs as well.

**Comment by jstejada** [comment]
thanks for reporting this folks! Merging into dupe #823
