### ISSUE TITLE
Account names don't change with a search query entered

### ISSUE THREAD

**Issue by jffrybrwn** [nylas/N1#767]
If you search for something and then try to switch accounts with a keyboard shortcut, the account folders change but the email address / account name at the top-right does not, and neither do the messages/results. My expectation would be that switching accounts would clear the query.

**Comment by jstejada** [comment]
@jffrybrwn thanks for reporting this! you mean top-left right?

**Comment by jffrybrwn** [comment]
Oh whoops—yes!

**Comment by bengotow** [comment]
This has been fixed in 608060ed6d954fc116973c8d999a5114d3027c8d (Dup #850). The intended behavior is to switch accounts and re-run the search in the other mailbox. (At least until we have unified inbox, accidentally searching in the wrong mailbox is a pretty common use case...) Cheers!
