### ISSUE TITLE
Add building instructions

### ISSUE THREAD

**Issue by ametaireau** [nylas/N1#77]
First and foremost, thanks for the great project N1 is. I'm currently using it and it's working pretty well for me.

However, when trying to install it, I was left without instructions about how to build it from scratch, with all its dependencies (the server part, etc). I think that would make the project a lot easier to contribute if there were clearly defined instructions about how to get started and hack.

**Comment by equinusocio** [comment]
:+1:

**Comment by bengotow** [comment]
Thanks for downloading N1 and trying it out. Over the last couple days I've been compiling feedback into instructions here: https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine

Can you take a look and see if there's anything we need to add to that page based on your experience setting things up?

Sorry - we weren't expecting the interest we've had in running the whole stack from scratch. Really been great to see! Hopefully we'll have complete documentation compiled together soon.
