### ISSUE TITLE
quick schedule email links broken

### ISSUE THREAD

**Issue by gcleveland** [nylas/N1#772]
ver 0.3.32 
safari
mac os/x 10.11.2

Still having the same problem with broken links in the schedule plugin.

<img width="578" alt="screen shot 2015-12-18 at 23 23 50" src="https://cloud.githubusercontent.com/assets/3348484/11909455/c47d63b2-a5de-11e5-8ec1-a49ef45ccad6.png">

**Comment by jstejada** [comment]
hey @gcleveland -- thanks for reporting this. Since we don't have a plugin manager in place you might need to uninstall and reinstall the plugin after updating N1

**Comment by gcleveland** [comment]
yes I tried that (twice), and unfortunately still no luck.

**Comment by dregitsky** [comment]
Hey @gcleveland, just to confirm, the failed links are from messages that were sent, right? The plugin makes links in the draft when you exit the calendar, but they aren't saved to the backend until the message is actually sent.

**Comment by gcleveland** [comment]
Yes that's correct, they were sent to another email address I own on a
different domain.

  

> On Dec 19 2015, at 1:00 am, dregitsky &lt;notifications@github.com&gt;
wrote:  

>

> Hey [@gcleveland](https://github.com/gcleveland), just to confirm, the
failed links are from messages that were sent, right? The plugin makes links
in the draft when you exit the calendar, but they aren't saved to the backend
until the message is actually sent.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/772#issuecomment-165929415).![](https://github.com/notifications/beac
on/ADMYBESBfPlr_IONpbtK-WfJm1yZtVOEks5pRKOUgaJpZM4G4gF5.gif)

**Comment by dregitsky** [comment]
Alright, thanks a lot for reporting this. We'll check into backend logs and try to track down the issue. If you've got a chance, can you send the full URL from a link that's failing?

**Comment by gcleveland** [comment]
https://quickschedule.herokuapp.com/event/slljhEWmOmW2Na1Ip6PTMTft9NdUlc1qn5Qsj0pVUUDjtjYIaKRFFAn5Bows8wRGv99PNxToTUIjboSzEvN96UL6w76Mle8cwhfdZg96yuxWyF4rRxh4xlcIzvtrhJTd <https://quickschedule.herokuapp.com/event/slljhEWmOmW2Na1Ip6PTMTft9NdUlc1qn5Qsj0pVUUDjtjYIaKRFFAn5Bows8wRGv99PNxToTUIjboSzEvN96UL6w76Mle8cwhfdZg96yuxWyF4rRxh4xlcIzvtrhJTd>

--
Grant Cleveland
Director, Breakthemold
e: grant.cleveland@breakthemold.co.uk
m: 07515376760
LinkedIn <http://uk.linkedin.com/in/grantcleveland>

**Comment by dregitsky** [comment]
Hey @gcleveland, thanks again for reporting this. It turns out there's a subtle bug where using QuickSchedule in a composer window (as opposed to a composer in the main window, like a reply) can result in broken links being sent. Failed requests to the QuickSchedule backend are also not handled well currently. We're working on a fix for both issues and should hopefully have it shipped with the next N1 update. Really sorry about this!

**Comment by grinich** [comment]
Should now be fixed!
