### ISSUE TITLE
Intercom Feedback Window Wont Close

### ISSUE THREAD

**Issue by gcleveland** [nylas/N1#773]
Once opened, the Intercom feedback window cannot be closed, and prevents the app from quitting.
Also creates an issue if open when upgrading.

Mac osx 10.11.2

**Comment by jstejada** [comment]
@gcleveland thanks for reporting this, gonna merge in a bunch of duplicates

**Comment by jstejada** [comment]
@gcleveland this should be fixed in an upcoming release
