### ISSUE TITLE
Feature Request: Ability to see source code of an email

### ISSUE THREAD

**Issue by lapin-b** [nylas/N1#774]
Sometimes, you get emails which lands in junks folder and you want to make sure it's really a junk. And for that, it'd be interesting to have a button which let you see the raw code of an email in the mail viewing part.

**Comment by noahbuscher** [comment]
I think this might be better suited for a plugin... This behavior seems like one that not many people (meaning average, non-power users) would take advantage of. At the worst, it could cause confusion and perhaps a bit of panic.

Trust me - if you ever been asked to help someone who accidentally popped open DevTools, you'll know what I mean. 😉

**Comment by mbilker** [comment]
The sync engine parses the emails and doesn't keep the raw email around. You can get the raw message from your mail provider most likely.

**Comment by mbilker** [comment]
I think you should file an issue over at [nylas/sync-engine](https://github.com/nylas/sync-engine).

**Comment by noahbuscher** [comment]
@mbilker Good point! I did not know that. :facepunch:

**Comment by mbilker** [comment]
And this sounds similar to nylas/sync-engine#239

**Comment by bengotow** [comment]
Hey folks! You can actually get the raw message already, via a special endpoint on the sync engine. We've been meaning to put a button or something into N1. Right now, you have to click between the timestamp and the message options. You'll get a (secret) dropdown with the option "Show Original". It might take a moment (it makes an API request) but you'll see everything.

![image](https://cloud.githubusercontent.com/assets/1037212/11911280/1ae98642-a5ce-11e5-92eb-9d8d3d4f1f1a.png)

**Comment by lapin-b** [comment]
@bengotow Thank you ^^ I never noticed the secret box

**Comment by mbilker** [comment]
@bengotow Thank you! That is quite interesting.

**Comment by dinamic** [comment]
Could we have this as regular button in 2016, please?

**Comment by IlyaSemenov** [comment]
@bengotow The entire header area does not respond to right click in the latest release (*Version 0.4.52-5c342df (0.4.52-5c342df)*). Any other way to view the message source?

**Comment by timdorr** [comment]
@IlyaSemenov If you click between the timestamp and the reply button like @bengotow showed, I'm seeing the secret menu pop up.

And yeah, I totally agree with @dinamic that this should be exposed in the UI somehow. Perhaps after you expand the full header details on the left?

**Comment by lashus** [comment]
Wow, year 2017 and still not implemented. Can I create PR for this? It shouldn't take long.

**Comment by dinamic** [comment]
@lashus, I would suggest creating a new issue for this as the current one is closed already.
