### ISSUE TITLE
Can't change password

### ISSUE THREAD

**Issue by jffrybrwn** [nylas/N1#776]
I changed my Gmail password and subsequently got this error:

<img width="434" alt="screen shot 2015-12-19 at 7 17 37 am" src="https://cloud.githubusercontent.com/assets/10054355/11913814/dbb872fa-a63e-11e5-8635-16c62e61f5d2.png">

despite the fact that my connection was working properly. Then I realized that there is no way to reauthenticate so I had to remove my account and it back again.

Also now my accounts are in the wrong order which matters to me for keyboard shortcut convenience. I'd like to be able to drag them up/down in the Settings > Accounts list.

**Comment by mbilker** [comment]
Reordering accounts is coming! If you really need to move the accounts around, you can move the account order in `~/.nylas/config.cson`.

**Comment by jstejada** [comment]
hey @jffrybrwn ! yes, you can manually reorder accounts modifying your `config.cson` file. For now I'm going to merge into #631

**Comment by jffrybrwn** [comment]
Sure, but it's worth noting that that error message is incongruent with the issue I was having i.e., good network, bad password.
