### ISSUE TITLE
Message appears bold as a new message when I reply..

### ISSUE THREAD

**Issue by oldhickory30** [nylas/N1#777]

**Comment by jstejada** [comment]
hi @oldhickory30 thanks for reporting. Can you provide a screenshot?

**Comment by oldhickory30** [comment]
Having a hard time replicating it, very inconstant. It appears in bold right
after the reply but then when I click away from the message,, the highlight
goes away, making a screenshot tough. I'll see what I can do.

> On Dec 19 2015, at 10:34 am, Juan &lt;notifications@github.com&gt; wrote:  

>

> hi [@oldhickory30](https://github.com/oldhickory30) thanks for reporting.
Can you provide a screenshot?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/777#issuecomment-166007090).![](https://github.com/notifications/beac
on/APa9IFATrTeFGHb0Xr84NRhTK0K4OoyKks5pRYy6gaJpZM4G4q2u.gif)

**Comment by jackiehluo** [comment]
Closing this issue for now since it should be fixed—let us know if it's not!
