### ISSUE TITLE
How do I select a set of messages?

### ISSUE THREAD

**Issue by scfcode** [nylas/N1#778]
I can search for a set of messages, cool, but I can't then select that set and carry out an operation on them (mark as read, or delete, seem to spring to mind)...

How do I do this in N1?

**Comment by jstejada** [comment]
hi @scfcode! You should be able to select a message by clicking on it (or clicking on the checkbox, depending on what view mode you have activated), and you can combine with the shift key to select several at a time. When you select a message you'll see buttons at the top with the actions you can apply to them.
