### ISSUE TITLE
Send and Archive

### ISSUE THREAD

**Issue by goughjustin** [nylas/N1#780]
Once of the features that keeps me using Sparrow Mail's desktop client (RIP) is the send and archive button.

**Comment by davidmaneuver** [comment]
+1

**Comment by davidpmccormick** [comment]
Is this feature available by keyboard shortcut? By default, I would like e.g. ⌘+ENTER to remain as 'send', but an option to send and archive would be good.

**Comment by HemalR** [comment]
Just discovered Nylas and loving it!

+1 for this being a keyboard shortcut (not at the expense of normal send though). Keep up the great work guys!
