### ISSUE TITLE
Syncback Actions Failing / Archive, Delete actions are not propagating to mail providers

### ISSUE THREAD

**Issue by joshvickerson** [nylas/N1#781]
Currently using build 0.3.32-b11131d (0.3.32-b11131d) and archiving threads doesn't actually archive them. They appear archived in N1 but remain unread and in my inbox in other clients (specifically, Outlook for iOS and Gmail web client).

Anything I can do to help debug this?

**Comment by bellebethcooper** [comment]
I have exactly the same setup and I'm having this issue as well.

**Comment by mbilker** [comment]
Huh, this is odd. They work properly for me. It should remove the Inbox label, which dumps the thread into the All Mail folder.

**Comment by bellebethcooper** [comment]
In N1 the Inbox label does seem to be removed from the archived emails. When I
look at Gmail on the web, the same emails don't have any labels, are still in
the inbox, and even show as being unread still.

> On Dec 21 2015, at 3:57 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Huh, this is odd. They work properly for me. It should remove the Inbox
label, which dumps the thread into the All Mail folder.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/781#issuecomment-166135123).![](https://github.com/notifications/beac
on/AEmkgU1ikYJx1XaZLYyDTA6TyczHVgCcks5pRtWRgaJpZM4G4up_.gif)

**Comment by mbilker** [comment]
@bellebethcooper Could you check the Activity Window (`Developer -> Open Activity Window`) to see what the response codes of the requests are after hitting Archive?

**Comment by bellebethcooper** [comment]
I'm getting 200s every time. Same for opening the email to mark it as read.  
<br  

  

[@BelleBCooper](http://www.twitter.com/bellebcooper), co-founder of Exist

> On Dec 21 2015, at 9:32 am, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> [@bellebethcooper](https://github.com/bellebethcooper) Could you check the
Activity Window (`Developer -> Open Activity Window`) to see what the response
codes of the requests are after hitting Archive?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/781#issuecomment-166159649).![](https://github.com/notifications/beac
on/AEmkgRA6Km28rErijOiFTm4ElMidXW35ks5pRyPrgaJpZM4G4up_.gif)

**Comment by mbilker** [comment]
@bellebethcooper Hmm. Then its some other part of the process that is causing this.

**Comment by omegahm** [comment]
I have the same issue for my gmail. It seems to be only the mails, that in gmail would go to e.g Social, Promotions, Updates, Forums; the special tabs.

It also seems like it doesn't mark mails without the inbox label as read, like I have a Github label, which skips the inbox. When reading mails in this label, they are marked as viewed in the app, but not on gmail.com.

**Comment by bellebethcooper** [comment]
Today I'm getting 400s every time I try to change labels, including as the process of archiving/removing the inbox label. Trying to archive an email doesn't work, they just pop back into my inbox every time.

**Comment by mbilker** [comment]
@bellebethcooper Could you copy the command in the `Requests` starting with `curl` tab to the Terminal and run the command the command.

If you would be so kind to publish the results here, and please strip out the authentication details from the link and the published link would be like `curl -X PUT -d '{"unread":false}' "https://xxx:@api.nylas.com/threads/xxx"`.

**Comment by mbilker** [comment]
@bellebethcooper The response will have a lot of personal information in it. Please take care to remove it. So the result to my previous command would be:
```json
{
    "account_id": "REDACTED",
    "draft_ids": [],
    "first_message_timestamp": 1450650201,
    "has_attachments": false,
    "id": "REDACTED",
    "labels": [
        {
            "display_name": "Important",
            "id": "REDACTED",
            "name": "important"
        },
        {
            "display_name": "All Mail",
            "id": "REDACTED",
            "name": "all"
        },
        {
            "display_name": "Inbox",
            "id": "REDACTED",
            "name": "inbox"
        }
    ],
    "last_message_received_timestamp": 1450755099,
    "last_message_timestamp": 1450755099,
    "message_ids": [
        "REDACTED",
        "REDACTED",
        "REDACTED",
        "REDACTED"
    ],
    "object": "thread",
    "participants": [
        {
            "email": "N1@noreply.github.com",
            "name": "nylas/N1"
        },
        {
            "email": "notifications@github.com",
            "name": "Mads Ohm Larsen"
        },
        {
            "email": "notifications@github.com",
            "name": "bellebethcooper"
        },
        {
            "email": "me@mbilker.us",
            "name": "Matt Bilker"
        }
    ],
    "snippet": "Today I'm getting 400s every time I try to change labels, including as the process of archiving/removing the inbox label. Trying to archive an email doesn't work, they just pop back into my i",
    "starred": false,
    "subject": "Re: [N1] Archiving Threads... Don't (#781)",
    "unread": false,
    "version": 19
}
```

**Comment by mbilker** [comment]
@bellebethcooper That is what the success result would look like. A error response would be like the following, but this is not the same error as I cannot replicate it:
```json
{
  "message": "Couldn't find thread `<REACTED>` ",
  "type": "invalid_request_error"
}
```

**Comment by bellebethcooper** [comment]
The request:

```
curl -X PUT -d '{"labels":["xxx1","xxx2","xxx3","local-xxx-b528"]}' "https://xxx:@api.nylas.com/threads/xxx"
```

The response:
```
{
  "message": "Invalid id: local-xxx-b528",
  "type": "invalid_request_error"
}
```

`xxx` replaces any sensitive info.

**Comment by mbilker** [comment]
@bellebethcooper Thank you. For some reason, it is trying to set the labels for a local thread (usually a draft). Do you have any drafts present in N1 or in the web UI for your mail provider?

**Comment by bellebethcooper** [comment]
I do. I have 3 showing in N1 and 8 (including those same 3) in Gmail web. The email I tried to archive when testing earlier does not have any drafts in its thread that I can see.

**Comment by mbilker** [comment]
@bellebethcooper Hmm. The drafts disparity between Gmail and N1 is separate issue. This is odd. Could you possibly try deleting the drafts and seeing what the response code is after trying to set labels on that email?

**Comment by bellebethcooper** [comment]
Hmm. I tried deleting the 3 drafts from N1. They're gone from the Drafts folder in N1 but they're still showing up in Gmail. In the activity window I had a 200 for one deletion and a 400 for each of the other two. After that I tried to archive the same email I was testing on before and it didn't work—got a 400.

**Comment by mbilker** [comment]
Hmm. I am going to cc @bengotow for this issue since he knows more regarding the Sync Engine and interaction with Gmail.

**Comment by bellebethcooper** [comment]
In case it helps: I removed my account from N1 and re-added it. The 3 drafts were back when I re-added the account and I'm getting 200s again when archiving messages now, but the changes I make in N1 are still not syncing back to my Gmail account.

**Comment by bellebethcooper** [comment]
Based on @omegahm's suggestion, I turned on bundling in my Gmail Inbox again (I had turned off all the bundling so my inbox behaved more like old-school Gmail). Now it seems like, with a small delay, N1 mark as read and archive actions are syncing to Gmail... at least for the moment. Hope that helps. Happy to share more details about my settings if it's useful.

**Comment by spang** [comment]
Hi folks,

Are any of you having issues with changes syncing back to Gmail able to email support@nylas.com with the email address that's having problems? This is usually indicative of account-specific sync problems that we need more info to address.

**Comment by abhikp** [comment]
Any update on this? Really hurts the inbox zero people like me.

**Comment by MarvinBurman** [comment]
Will this issue be fixed anytime soon? without a proper sync it is not very usable for gmail.

**Comment by mfid** [comment]
Not usable at all for me at the moment. Really hope things are worked out soon so I can get back to testing. Just not fit for purpose until then :disappointed:

**Comment by alex-lew** [comment]
Downloaded N1 today and also having sync problems. Love the app, but can't use it if archiving doesn't work :( 

Getting 200 responses for various actions (archiving, starring, etc.) in the Activity Window -- it's just not propagating to Gmail.

**Comment by bryan** [comment]
Still having this problem. Any fix coming up?

**Comment by abhikp** [comment]
My problem went away and is back again.

**Comment by emitstop** [comment]
This is still not fixed? :/

**Comment by keithmattix** [comment]
Still getting this....

**Comment by joshvickerson** [comment]
Yeah, this is still happening on occasion for me too. How can I help troubleshoot this further?

**Comment by bellebethcooper** [comment]
Noticing this again in the latest version after having no trouble for a while. I'm getting 200 every time I archive a message in Nylas, but the actions aren't propagating to Gmail.

**Comment by joshvickerson** [comment]
It's popped up a lot recently. #1430 and #2059 are duplicates of this issue.

**Comment by neerajdotname** [comment]
I'm facing the same issue for the last few days.

**Comment by davidcelis** [comment]
Yup, happening to me too

**Comment by mjchamplin** [comment]
Happening to me since updating to  0.4.45-7637265.

Really frustrating :(

**Comment by bellebethcooper** [comment]
I'm using version 0.4.45-7637265 (0.4.45-7637265) and today I went to inbox.google.com and turned off all bundling options in my settings, and now Nylas archive actions are propagating almost immediately to my Google Inbox account on the web. Not sure if the bundling change actually made a difference, but adjusting bundling settings fixed this issue for me last time, so it may be related.

**Comment by joshvickerson** [comment]
I did the same thing as @bellebethcooper and my archive actions are now propagating to gmail on the web, and Outlook on iOS properly.

**Comment by emorikawa** [comment]
Hey all,

This should largely be fixed for nearly everyone; however, we are still diagnosing why this is happening intermittently to a few users.

The underlying issue is with our cloud sync engine. When N1 requests any type of changing action (archiving, deleting, etc) we asynchronously attempt to update your underlying mail provider (Gmail, Exchange, etc) later. It's possible for our cloud's connection to Gmail to temporarily drop causing the actions to fail. We've also noticed that due to inefficiencies in the way mail rules are currently being performed, if you ask our API to move thousands of messages it may create a very long backlog of sync actions (some of which may fail).

We've also been actively working on improving our monitoring infrastructure to give us better insight into how often this is failing and for whom.

Thank you everyone for the reports so far. It really helps us find some specific accounts to diagnose. We'll continue to update this thread as we get to the bottom of some of these syncback edge cases.

**Comment by jstejada** [comment]
Another report of this incident: https://nylas.zendesk.com/agent/tickets/3037

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/tertius/status/745790336241274880

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/bendell/status/745757443079147521

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/atherkildsen/status/745663295269527552

**Comment by rawjam** [comment]
This is still a massive issue for me. Every single email i delete is affected by this (or certainly it seems that way). A couple of things happen.

1. About 50% of the time, the email I deleted just pops back up in my N1 inbox. I need to delete it a second time to have it persist. Sometimes, I even get emails I deleted weeks ago randomly popping back into my inbox.
2. Irrespective of whether I have to delete the email one, or twice (see point 1 above), in close to 90%+ of the times I delete something from my N1 inbox, if I then login to my Google Apps / gmail account (or Outlook on my iPhone etc), I can see all of the emails I thought i had deleted, just sitting there in my inboxes... clearly they were never actually deleted.

This is deeply frustrating. Not just daily, but every 15 minutes or so when I attempt to delete something.

Can someone help me?

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4411

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4003

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/3413

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4112

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4123

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4180

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4182

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4311

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4314

**Comment by rawjam** [comment]
Is this close to being fixed yet?

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/4848

@rawjam We're always working on it and have some fixes we're going to be trying—it happens to a small number of users at any given time whose actions get queued behind a large number of other actions (i.e., when one user tries to archive thousands of emails at once).

**Comment by jackiehluo** [comment]
Another incidence: https://twitter.com/andypngr/status/753692385712844800

**Comment by framerate** [comment]
Yeah I get less enamored with Nylas N1 when I open Gmail on my phone and see things sitting in my inbox that don't show up in Nylas and vice versa :/

**Comment by danielgolden** [comment]
I was experiencing this bug for months, but just a few minutes ago my stubborn and sticky message [just disappeared](https://cl.ly/gib8)! I'm good to go :))))

**Comment by bengotow** [comment]
Another report from zendesk: https://nylas.zendesk.com/agent/tickets/4926

**Comment by djdiaz** [comment]
I am seeing some of this as well. I am mainly seeing two problems: (1) Emails I delete from the inbox often pop up again shortly after they have been deleted, usually with no message content and a line of text saying the message content is not available. (2) Many (not all) emails I have deleted are never actually deleted in Gmail, but are simply archived. N1 v0.4.45-7637265 (and all earlier versions up to this point).

**Comment by HammyHavoc** [comment]
Any update on this? Really enjoy Nylas N1, but if it can't consistently do the basics of sending and receiving email then I'll have to look at other things for a daily-driver unfortunately.

**Comment by jackiehluo** [comment]
Another incidence: https://nylas.zendesk.com/agent/tickets/5231

**Comment by kfitz** [comment]
Having the same delete issues described by djdiaz above. I love Nylas N1 but this issue renders it unusable for me.

**Comment by rawjam** [comment]
It seems to be getting worse for me. Are there any updates on this? It's driving me mad :(

**Comment by joshvickerson** [comment]
As I mentioned in an earlier comment, as did @bellebethcooper, if you've ever used Google Inbox, even once just to try it out, it has settings for bundling email. As soon as I went in and turned those off, my sync actions worked perfectly.

Mentioning it again as our earlier comments seemed to largely be ignored. I would recommend checking Google Inbox settings as a first step in troubleshooting.

**Comment by rawjam** [comment]
Oh, i didn't see that.

I haven't used inbox before - not to my recollection anyway. But i've just gone in now and signed up. I've now set the bundle options all to 'off'. let's see if this works. Thanks.

**Comment by rawjam** [comment]
Although I appreciate you mentioned this earlier (i must have missed it), i do think this is potentially such an aggravating issue that i'm sure a number of your users will appreciate knowing how to fix. I would have loved to have seen an official message about this from Nylas months ago. Just a thought.

**Comment by kfitz** [comment]
The Inbox info is helpful -- and too buried in ensuing comments to be found in a lengthy thread, alas. But I have one Google Apps account for which Inbox has never been activated, and I'm having these issues in that account too, so that can't be the sum total of it.

**Comment by joshvickerson** [comment]
@rawjam: agreed, it's largely gone unanswered from Nylas, which is super frustrating.

If you still have issues after a couple hours, you may need to reinstall Nylas. If it comes to that, you'll need to also delete the hidden Nylas folder, ~/.nylas (on a Mac, not sure where the Windows equivalent is, possibly your User folder, but otherwise I imagine it's in AppData)

**Comment by rawjam** [comment]
Thanks @joshvickerson i'll give that a go if it comes back - no obvious signs yet.

**Comment by rawjam** [comment]
FYI, there's still an issue here. Items I have deleted (so far) are remaining deleted in Nylas but don't show as deleted when I view my inbox on Outlook or Gmail etc.

**Comment by jstejada** [comment]
Hi all, 

Going to close this issue and split it up into 2 separate issues so its easier to follow, because this one is getting too big.

- The original problem for this issue, syncback actions not propagating back to the provider, should already be solved, and if you are still seeing this, please email support@nylas.com

- There seems to be a new issue where archiving/snoozing/deleting immediately bounces back or reverting itself when you perform it. If you are experiencing that issue, please follow: #2725

- There seems to be another issue related to delete specifically not propagating to the provider, and or being archived. For that issue, follow: #2706

Those 2 final issues might be duplicates, but I'm not sure yet.

@rawjam, @kfitz, @HammyHavoc , @djdiaz
