### ISSUE TITLE
Cant Install New Themes

### ISSUE THREAD

**Issue by MrSassyBritches** [nylas/N1#782]
I click on "Install a theme" and when I select the Tiaga folder in my downloads it pops up an error message.

![image](https://cloud.githubusercontent.com/assets/7945291/11916767/96aad954-a6a3-11e5-801b-534791d8d84e.png)

I have tried installing it multiple times, and when i don't get this message the theme never shows up in the drop-down menu, and can't apply it.

I have also tried uninstalling N1 and reinstalling as well as all other plugins. No dice.

**Comment by mbilker** [comment]
That is odd because Taiga doesn't have a dependencies.

**Comment by MrSassyBritches** [comment]
You know what?! I feel silly, beacuse when i was installing this, i didnt select the right folder, i had to open the N1-Tiaga folder and inside is 2 other folders one named N1-Tiaga and one called _MACOSX. I just had to go one folder deeper. Im dumb :P

**Comment by MrSassyBritches** [comment]
how can i close this "issue"?

**Comment by mbilker** [comment]
Glad to know its working now @MrSassyBritches!
