### ISSUE TITLE
OS X quitting from Dock "Unexpectedly Quit" message

### ISSUE THREAD

**Issue by noahbuscher** [nylas/N1#784]
After quitting N1 from the OS X dock (_not_ force quitting) an error occasionally happens that says "N1 unexpectedly quit" even though I performed the operation.

Mind you, this does not occur every time I quit the app this way, and I can't seem to find the steps required to make it happen consistently.

**Comment by jstejada** [comment]
hey @noahbuscher , I think this might be related to #773 .

Is this happening when you have chrome dev tools open as a separate window, or when the feedback window open?

**Comment by bengotow** [comment]
This is no longer happening in 0.4.25. Not sure exactly when it got fixed but the Electron issue has been closed as well.
