### ISSUE TITLE
Feature Request: Multiple windows or tabs

### ISSUE THREAD

**Issue by wizonesolutions** [nylas/N1#786]
Don't see this on Trello, so asking here. The feature request is straightforward; I'd like to be able to more easily toggle between multiple accounts. I suppose this is similar to https://trello.com/c/nPeISFt6/22-show-unread-counts-from-other-accounts-somewhere-in-the-interface, but I don't show unread counts, so it'd be nice to have e.g. tabs and be able to Cmd-1, Cmd-2 etc. to those...and not have to re-sync every time I switch, etc.

**Comment by mbilker** [comment]
Currently, N1 is setup with an `AccountStore` that also points to the current user. While it is feasible to have multiple windows to show multiple accounts, it will take some major effort to re-architecture the app to handle multiple windows and accounts at the same time.

**Comment by grinich** [comment]
You can now do this in N1!
