### ISSUE TITLE
No "Sent Mail" view

### ISSUE THREAD

**Issue by MisterTea** [nylas/N1#790]
I don't see any way to view sent messages.  I have a "Sent Messages" folder but that is created by Thunderbird and N1 doesn't copy sent messages to that folder.  There's no "sent" category in the INBOX/Starred/Junk/... section.

**Comment by TLATER** [comment]
Same here. Neither of my IMAP accounts appear to retreive sent messages. I have a folder called INBOX.sent, but nothing is copied into it.

The email is sent properly (I hope), trying to mail myself resulted in no email in the sent directory but receiving it as usual.

**Comment by TomS-** [comment]
Same issue here. I pretty much can't use the client because of this reason as I was using it for work and need to be able to have an archive of sent emails.

**Comment by DeadEye0112** [comment]
Same here. All my IMAP accounts don't have Trash or Sent Items folders. This is annoying especially when you need to see a message you sent but where the recipient has not responded yet. There is nowhere I can find the sent message and then, I can't see if it has been read or not.

**Comment by bengotow** [comment]
Hey folks! Thanks for posting. To make this issue actionable for our backend team, can you post the email providers you're having trouble with (IMAP, Exchange, etc.), and a screenshot of the labels / folders you see in your webmail client? That'll help us figure out the issue and get it fixed.

**Comment by DeadEye0112** [comment]
Hi !
I'm using OVH mails with these settings :
- SMTP : ssl0.ovh.net
- IMAP : ssl0.ovh.net
The webmail is a Roundcube.

![2016-04-15 at 11 08](https://cloud.githubusercontent.com/assets/11258498/14556838/794c0dfc-02fa-11e6-81f8-956a08d4ff6a.png)

Here are the technical name of the folders and their label :
INBOX.INBOX.Drafts: Brouillons
INBOX.INBOX.Sent: Envoyés
INBOX.INBOX.Junk: Pourriels
INBOX.INBOX.Trash: Corbeille

This may be quite complicated to bind with these folders as there are probably hundreds ways to manage sent items and trash.

Apple Mail creates his own Sent Mail and Trash folders, that would be a simpler solution.
Another solution would be to check all remote folders and asks for the user to bind local folders to remote folders.
Best solution is probably to try to find the remote folders and bind on them if the remote folder name is similar to "Trash", "Sent Items" or whatever.

Anyway, thank you for the support ! (;

**Comment by cmoud94** [comment]
I have the same problem with my school mail. The webmail is Roundcube and I was forced to stop using nylas because of the sent mail wasn't shown in sent directory neither in nylas and on server.

Would be nice to see this fixed.

**Comment by bengotow** [comment]
We've narrowed this down and it looks like it's affecting approx. 2% of accounts linked with N1. Fix coming soon.

**Comment by soyuka** [comment]
Same issue here with Microsoft Exchange (mails aren't on the webmail either). Let me know if you need log data from somewhere.

**Comment by Analect** [comment]
@TomS- 
I'm having trouble getting 1&1 working with nylas. I can see that you are using this. Any chance you might be able to share your set-up (with sensitive data redacted, of course)?  Was using settings as per [this](http://help.1and1.co.uk/mail-c65093/1and1-mail-basic-c40987/getting-started-c43521/set-up-e-mail-clients-using-imap-or-pop3-a619070.html) link, but can't get to work.

**Comment by brooth** [comment]
Same issue here. N1 v0.4.45-7637265 for Ubuntu (16.04). Sent messages folder is empty

**Comment by TachyonRSA** [comment]
Same issue with Microsoft Exchange. Mails not showing sent on OWA either.

**Comment by jackiehluo** [comment]
Going to merge this into #1457!

**Comment by basma-b** [comment]
I found this solution [here](https://github.com/nylas/nylas-mail/issues/1457)

So ugly hack that work well, go to :
~/.nylas-mail/random_number.sqlite
open dabase with a [gui](https://apps.ubuntu.com/cat/applications/natty/sqlitebrowser/) when nylas is closed
open tables folders and add role to your folder (inbox, trash, sent, drafts, spam)
save database
restart nylas
