### ISSUE TITLE
No 'Inbox' view after update

### ISSUE THREAD

**Issue by webgurus** [nylas/N1#791]
After updating N1 to the latest, I can't see the inbox view anymore.

All the other views work for me. I've tried deleting the app and re-installing, but still the same.
![screen shot 2015-12-21 at 12 02 21](https://cloud.githubusercontent.com/assets/1938503/11928323/1f506944-a7db-11e5-9bfb-24479aa1bde7.png)

Can you let me know if this is fixed?

Thanks,
Marton

**Comment by mbilker** [comment]
You are on `0.3.32`? Can you check `Developer -> Toggle Developer Tools` and report any errors shown there?

**Comment by mbilker** [comment]
What happens if you use the Search field to search for a message? If you click on a message, does the message view show up?

**Comment by malcobev** [comment]
My Inbox is not updating after Dec 12th. I reloaded, restarted, etc., but no luck..!! And my 'Search' never worked ever since I first installed a month back.

**Comment by jstejada** [comment]
hey guys! Could you send the logs from the Developer Tools console and see if it's reporting any errors? Go to  `Developer -> Toggle Developer Tools` and select the console tab.

**Comment by grinich** [comment]
@webgurus I'm going to close this as stale. Please re-open if you can find steps to reproduce the issue!

**Comment by webgurus** [comment]
![screen shot 2016-01-27 at 18 45 58](https://cloud.githubusercontent.com/assets/1938503/12620808/7d71861c-c526-11e5-8d0d-1c0f5e9ac82b.png)

Sorry I was out of town.

This is the error.

**Comment by mbilker** [comment]
That console scrolls down a fair bit, could you screenshot more of it?

Paging @bengotow for log file help on OS X
