### ISSUE TITLE
Account added on one machine, cant add it on another machine

### ISSUE THREAD

**Issue by Pawamoy** [nylas/N1#793]
I am a student and I use N1 on two machines, my laptop and my computer at home.
I was able to add my university mail account in N1 on my laptop but not on my computer at home :scream: ! It says "Invalid credentials"...

The version on my laptop was 0.3.19 (I think) when I added the account. I upgraded to 0.3.32 and it is still working.

The version on my computer is 0.3.32.

Both systems are Ubuntu 14.

**Comment by bengotow** [comment]
Hi @Pawamoy — are you still running into this?

**Comment by Pawamoy** [comment]
Hi @bengotow, yes I just tried again and it still does not work.

My university mailserver settings are the following:

Incoming server: IMAP  
mailserver.u-strasbg.fr  
Port 993  
SSL/TLS  

Outgoing server: SMTP  
mailserver.u-strasbg.fr  
Port 587  
STARTTLS

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
