### ISSUE TITLE
Feature Request: Archive icon too similar to Trash icon.

### ISSUE THREAD

**Issue by colllin** [nylas/N1#794]
I find myself comparing them every time before I click one.

For reference, this is how Spark solves it:
![fullsizerender](https://cloud.githubusercontent.com/assets/185923/11935103/3008f7c8-a7c3-11e5-88c8-1a60da187948.jpg)

**Comment by mbilker** [comment]
So you are suggesting to make the trash icon turn red?

**Comment by colllin** [comment]
That seems to help. Also, their icons are slightly less similar to each other.

**Comment by mbilker** [comment]
@colllin Alright then. What OS do you use for N1?

**Comment by colllin** [comment]
OSX 10.11.2

**Comment by mbilker** [comment]
Thank you!

**Comment by mbilker** [comment]
@colllin So I did an small change. Here is with the background set:

![2015-12-21-22-45-20_359x57](https://cloud.githubusercontent.com/assets/1266541/11947445/d935dc46-a834-11e5-895d-8e2d5eb92de6.png)

Here is with the color changed:

![2015-12-21-22-50-43_379x74](https://cloud.githubusercontent.com/assets/1266541/11947472/46dfb140-a835-11e5-9904-4f6952321258.png)

**Comment by colllin** [comment]
Nice! To me those are both more clear than it is now. Do you think so?

**Comment by mbilker** [comment]
@colllin Yes. I believe the one with only the trash can red, not the background, is better if the color was a darker shade of red.

**Comment by mbilker** [comment]
@colllin How do you think this looks?

![2015-12-21-23-00-46_339x79](https://cloud.githubusercontent.com/assets/1266541/11947555/b05aef08-a836-11e5-9b4b-c0d987bcd8f6.png)

**Comment by colllin** [comment]
I think it's great. Are other people feeling the same way? It's also possible that I got used to the colored distinction in Spark and now I'm experiencing deprivation, whereas people who haven't used Spark might not be experiencing it. Do we have personal style sheets in N1? I'm totally willing to solve it that way if we don't want to make this change for everyone.

**Comment by grinich** [comment]
Hi folks-- I suggest this be implemented as an option plugin. We're really conservative about adding color to the interface at this time, but because N1 is open source, you can change anything you want! :smile: 

More info here: https://github.com/nylas/N1/pull/799#issuecomment-166700038

**Comment by colllin** [comment]
Color is only one solution.  The icons could also be redesigned, which would maintain your law of conservation of color, and help solve the design problem.

**Comment by grinich** [comment]
Going to close and leave this up to plugin developers to modify. (Go extensibility!)
