### ISSUE TITLE
Feature Request: Support for special-use folders (RFC 6154)

### ISSUE THREAD

**Issue by sergiosgc** [nylas/N1#796]
Currently, Nylas has hardcoded values for special use folders (Sent Items, Drafts, Archive, ...). It would be much better if the folders could be obtained from the special use IMAP extension: 
 http://www.faqs.org/rfcs/rfc6154.html

**Comment by mbilker** [comment]
Hey @sergiosgc! Thank you for the request. I would suggest also posting this request in [nylas/sync-engine](https://github.com/nylas/sync-engine) and referencing to this issue by including the following in your post:
```
nylas/N1#796
```

**Comment by grinich** [comment]
I think we already do this. Have you experienced something different? Please re-open with specifics to reproduce.
