### ISSUE TITLE
Running N1 crashes "not valid Electron app"

### ISSUE THREAD

**Issue by bnvk** [nylas/N1#80]
Running the `script/bootstrap` seems to complete fine (however, it did time out a couple times on installing the deps). But when running the app it crashes 

```
[user@dev N1]$ ./N1.sh --dev
[17906:1012/003214:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Streaming log data to /tmp/edgehill-17906.log
Error opening app
The app provided is not a valid electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/master/docs

Error: Cannot find module '../build/Release/nslog.node'
```

**Comment by bengotow** [comment]
Hey Brennan - based on the log output it looks like the app is missing dependencies (a module called nslog). Can you try running script/bootstrap again? It's non-destructive, so you should be able to run it again. At the very end, that script builds SQLite from source, so you'll see that go by with a few warnings when the script runs successfully.

**Comment by bnvk** [comment]
@bengotow thanks for the response. I deleted my repo and started from scratch and it booted up just fine now! Thanks :)
