### ISSUE TITLE
Feature request: reply from alias when sent to alias

### ISSUE THREAD

**Issue by superwillyfoc** [nylas/N1#800]
If an email was sent to an alias, replying to that email should by default use the alias as "from".

**Comment by fjarrett** [comment]
+1

In Gmail this setting is called:

> Reply from the same address the message was sent to

<img width="398" alt="gmail-default-reply-from" src="https://cloud.githubusercontent.com/assets/522158/11989674/89d8dbe6-a9c7-11e5-84ae-926fc9747400.png">

**Comment by bellebethcooper** [comment]
I'd also like the "reply from the same address the message was sent to" option, because currently my replies always come from my alias, even if they were sent to my normal email address.

**Comment by jgerigmeyer** [comment]
+1

**Comment by alexnederlof** [comment]
+1

**Comment by bengotow** [comment]
This was just implemented in https://github.com/nylas/N1/commit/324296eb1ca562f21acec0efc7bd9a5337099532 and should land in a release as early as tomorrow. Stay tuned!

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!

**Comment by arifb** [comment]
Hey! I'm on latest (0.4.19-d41e72c) and this behaviour is not working. Mail sent to alias email is replied from my default alias and not the alias that the mail was sent to.

Happy to open up a new issue if you'd prefer.

**Comment by bojanpopic** [comment]
Hi!
Any news about this? I'm running latest version at the moment 0.4.45-7637265 and this is still not working.
When an email arrives at bojan@alias.com and when I try to reply, I get "reply all" as an option, in From: field is my primary address and in CC: is bojan@alias.com.
