### ISSUE TITLE
Plugin Request: Grammarly Integration

### ISSUE THREAD

**Issue by joshkennedy** [nylas/N1#802]
Hey, team. I'm really loving N1 thus far. Bravo!

While it's not all that complicated to compose an email in one window and then paste it into N1, having a Grammarly (or similar) service integration would be neato. 

![](https://media.giphy.com/media/tTFs5hNtPA3MA/giphy.gif)

**Comment by mbilker** [comment]
Thank you @joshkennedy for the plugin idea! If Grammarly provides a publicly accessible then it is possibly to implement it through the new `ContenteditableExtension` API.

**Comment by yjlintw** [comment]
+1, this kind of feature would be helpful. Maybe we can combine it with LanguageTools?

**Comment by bengotow** [comment]
Moving to https://trello.com/c/gBSDIDTw/60-grammarly-integration

**Comment by paul-siteway** [comment]
👍
