### ISSUE TITLE
Feature Request: Allow user to select which folders to sync

### ISSUE THREAD

**Issue by caiotoon** [nylas/N1#803]
With the volume of emails received and historical data, it would be nice to being able to pick which folders to synchronize.

**Comment by bengotow** [comment]
Hey! Thanks for filing this - we've decided not to focus development of the sync engine on selective sync right now, but we may revisit it in the future if there's enough interest. In the meantime, I'm going to close this as a won't fix. Pull requests to both N1 and the sync engine are always welcome.
