### ISSUE TITLE
Feature Request: Mark Messages as Read Manually, instead of marking as read by default

### ISSUE THREAD

**Issue by ablumey** [nylas/N1#804]
I scroll through email and bounce between apps all day. I prefer to mark items as read manually once I've actually addressed whatever they're about. Is it possible to add a "manual" option to the "Reading" section of N1's options?

**Comment by tabascoterrier** [comment]
+1

**Comment by bengotow** [comment]
Hi @ablumey yep — we should definitely do this. Will be included in the next release!

**Comment by carlotrimarchi** [comment]
Any update about this?
