### ISSUE TITLE
Emoji doesn't show in unread subject line

### ISSUE THREAD

**Issue by grinich** [nylas/N1#806]
It seems the bold version of the font doesn't render emoji

![emoji](https://cloud.githubusercontent.com/assets/92417/11963880/a5c4d0a0-a89e-11e5-8777-868022ba44a8.gif)

Running 0.3.32 on OS X.

**Comment by mbilker** [comment]
@grinich This is with the Nylas Pro font correct?

**Comment by mbilker** [comment]
:gift: (just using this to copy)

**Comment by mbilker** [comment]
This is with the Nylas proprietary font correct?

**Comment by mbilker** [comment]
:gift:

**Comment by mbilker** [comment]
Hmm. It appears I cannot paste that emoji into the subject field of N1 or Gmail's web client.

**Comment by bengotow** [comment]
This appears to be a problem in Chrome as well. Emoji do not render at any font-weight except `normal`. 

(In the screenshot, there should be two beer emojis. The one between `font` and `weight` is missing.)

![image](https://cloud.githubusercontent.com/assets/1037212/12280471/f5c80338-b942-11e5-9050-46c4f72b7c99.png)

We may have to wait on upstream fixes to correct this. It appears we can provide other font files for font weight 600, but we can't render an existing font at a different weight.

**Comment by grinich** [comment]
Can we detect the emoji code point range and insert <span> tags to wrap them?

**Comment by grinich** [comment]
@jackiehluo think you could fix this? :smile:

**Comment by jackiehluo** [comment]
@grinich Down after these tests are written, emojis are pretty much my life at this point. :+1: You mean detecting the Unicode characters so that it renders in N1 as `<em>font </em>:beers:<em> weight</em>`?

**Comment by grinich** [comment]
yeah i think that would work. we may end up wanting to do something similar for characters that don't render in Fakt

**Comment by bengotow** [comment]
Hey @jackiehluo — this was fixed in d8459bb2cd00b19a21c049e38aa79a71e997730a, right?

**Comment by jackiehluo** [comment]
@bengotow Should cover a lot of emoji, but not all of them yet! I'll switch it for the other regex once that covers everything.

**Comment by bengotow** [comment]
Hey folks—this has shipped in `0.4.25`. It looks like there are some emoji which may not work, but the majority of common ones seem to be converting properly. Gonna go ahead and close this issue.

![image](https://cloud.githubusercontent.com/assets/1037212/14479806/227bb3a8-00d7-11e6-8251-524cc35e8e44.png)
