### ISSUE TITLE
Do not renew my mail inbox automaticly？

### ISSUE THREAD

**Issue by akar1nchan** [nylas/N1#813]
my inbox status still in yesterday...

**Comment by akar1nchan** [comment]
i think my network status is unstable.

i need  developers to add network proxy function , such as http/https proxy or socks proxy.

**Comment by mbilker** [comment]
Hey this is similar to #104. Currently the backend functions are done with Node's `request` library which supports proxies. The frontend images go through Chrome's downloader, which complicates the matter. This is being worked on.
