### ISSUE TITLE
annoying blinking of tray icon

### ISSUE THREAD

**Issue by sispus** [nylas/N1#814]
on ubuntu 14.04, tray icon is instantly dissapearing and appearing again. it tooks about half a second, it goes and comes again.

**Comment by mbilker** [comment]
Hey @sispus! What version of N1 are you running?

**Comment by sispus** [comment]
Hi,
It is 0.3.32-b11131d

By the way, how can I check new versions? I mean, easily :)

**Comment by jstejada** [comment]
@sispus when you open N1 it will automatically check for new updates. I'm closing this as stale, feel free to re open if you are still experiencing this issue.

**Comment by kerozoli** [comment]
I experiencing this bug on Ubuntu 16.04
