### ISSUE TITLE
"Reply All" replies to alias

### ISSUE THREAD

**Issue by mirisuzanne** [nylas/N1#816]
I'm using Version 0.3.32-b11131d with gmail on a Mac (El Capitan).

When an email is sent directly to my gmail address, and I am the only recipient, there is no "reply all" option, and everything works as expected.

When an email is sent to one of my aliases, with or without other recipients, "reply all" is available, and my alias is used in both the "from" field (expected) and also in the "CC" field (not expected).

**Comment by bengotow** [comment]
Hey! Wow this is a big one—thanks for filing this. I've fixed it in 8c965e4d7b32497c4e0cfd431ef1eadf08eb6e6e and we'll include it in the next release!
