### ISSUE TITLE
Trying to connect exchange exposed on localhost using Davmail

### ISSUE THREAD

**Issue by maxjerin** [nylas/N1#817]
I'm on Ubunut and using Davmail to connect to our OWA client to exposes exchange IMAP and SMTP on localhost to allow Mozilla Thunderbird to connect (works perfectly). I was trying to use the same settings on Nyla N1 but its not able to connect to localhost or 127.0.01 (no ssl). Does Nylas try to append the domain name from my email to the server name provided? Where are the logs located so that I can get some more information.

PS: I had to do the Davmail hack cause IT doesn't support Linux clients as workstations.

**Comment by mbilker** [comment]
Hey @maxjerin! Nylas N1 uses the Nylas Sync Engine to connect to mail servers, which the hosted (default) Sync Engine is hosted on AWS. If you want to connect to a mail server running on `localhost`, you must build and run the Sync Engine locally. The instructions for doing so are [here](https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine).

**Comment by maxjerin** [comment]
Thanks @mbilker, I'll give this a try

**Comment by bengotow** [comment]
Hi folks—yep, unfortunately we don't support mail servers that are hosted internally or hidden from the public internet. Running the sync engine locally will do the trick, but it's a good bit of work.

**Comment by maxjerin** [comment]
So I tried the above and am getting the following response. I'm not sure if it because its trying to to use an SSL connection by default because I don't need SSL.

vagrant@precise64:/vagrant/bin$ inbox-auth user.name@domain.com
IMAP account? [Y/n] Y
Password for user.name@domain.com (hidden): 
IMAP server host: 10.10.10.10
IMAP server port: 1143
SMTP server host: 10.10.10.10
SMTP server port: 1025
[ERROR] {"event": "Error instantiating IMAP connection", "host": "10.10.10.10", "level": "error", "account_id": null, "error": "abort('socket error: EOF',)", "timestamp": "2016-01-06T21:12:56.045991Z", "greenlet_id": 16034064, "email": "user.name@domain.com", "module": "inbox.auth.generic:79", "port": 1143}
[WARNING] {"latency": 71362, "modname": "__main__", "level": "warning", "timestamp": "2016-01-06T21:12:56.047494Z", "module": "contextlib:35", "funcname": "main", "greenlet_id": 16034064, "event": "Long transaction"}
Traceback (most recent call last):
  File "/usr/local/bin/inbox-auth", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/vagrant/bin/inbox-auth", line 61, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/vagrant/bin/inbox-auth", line 52, in main
    if auth_handler.verify_account(account):
  File "/vagrant/inbox/auth/generic.py", line 148, in verify_account
    conn = self.connect_account(account)
  File "/vagrant/inbox/auth/generic.py", line 69, in connect_account
    conn = IMAPClient(host, port=port, use_uid=True, ssl=(port == 993))
  File "/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py", line 145, in __init__
    self._imap = self._create_IMAP4(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py", line 154, in _create_IMAP4
    return ImapClass(self.host, self.port, **kwargs)
  File "/usr/lib/python2.7/imaplib.py", line 193, in __init__
    self.welcome = self._get_response()
  File "/usr/lib/python2.7/imaplib.py", line 928, in _get_response
    resp = self._get_line()
  File "/usr/lib/python2.7/imaplib.py", line 1023, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF

**Comment by mbilker** [comment]
@maxjerin That is odd. It is not trying SSL/TLS because the port does not equal 993. The socket to the IMAP server was closed, and hence the `socket error: EOF` error at the end. I am not familiar with the Sync Engine, but the error was not SSL/TLS.

**Comment by maxjerin** [comment]
@mbilker so I was able to get it to work (kinda). I had to install davmail on the vagrant instance and get it up and running. I also had to manually comment out the below lines from generic.py inside /inbox/auth

        if port ! = 993:

or else I kept getting the SSL error. I also had to delete the following cause it kept erroring for some reason

        try:
            # Check that SMTP settings work by establishing and closing and
            # SMTP session.
            smtp_client = SMTPClient(account)
            with smtp_client._get_connection():
                pass
        except Exception as exc:
            log.error('Failed to establish an SMTP connection',
                      email=account.email_address,
                      account_id=account.id,
                      error=exc)
            raise UserRecoverableConfigError("Please check that your SMTP "
                                             "settings are correct.")

I'm seeing some error in the sync engine saying "got more than 10000 bytes"

I think I'm going to give up on this. Thanks for all your help @mbilker, the UI seemed promising for all this work :). I'll wait for my IT to allow connections from N1 into the exchange.
