### ISSUE TITLE
Feature request : One click unsubscribe from newsletter

### ISSUE THREAD

**Issue by Bouzmine** [nylas/N1#818]
I'd like to be able to unsubscribe from a newsletter using one button.

**Comment by emorikawa** [comment]
This is a great idea, although something we likely won't implement in N1 core in favor of having a plugin that does this instead.

**Comment by bengotow** [comment]
Hey folks! Closing this because it's been built in a pretty great plugin: https://github.com/colinking/n1-unsubscribe
