### ISSUE TITLE
Disable the UI for adding an account in local/dev mode if it doesn't work. 

### ISSUE THREAD

**Issue by arthurlutz** [nylas/N1#82]
Am adding accounts via the procedure seen in the documentation (commands in the vagrant image, then editing cson config file), when the first account is enable and one can go into N1, the menu for adding accounts appears but doesn't not seem to function, is that a bug or a limitation of the self-hosted scenario ?

**Comment by grinich** [comment]
That's a limitation of the open source version-- it doesn't include the auth onboarding package that ties it to the hosted Nylas sync engine
