### ISSUE TITLE
Hover state in search results hides attachment icon

### ISSUE THREAD

**Issue by grinich** [nylas/N1#821]
![hoverstate](https://cloud.githubusercontent.com/assets/92417/11983010/f85be814-a964-11e5-86cd-59f474ff4d9d.gif)

Running 0.3.33b

**Comment by bengotow** [comment]
It looks like the date and attachment icon are being hidden behind a gradient where the "archive" / "trash", etc. quick actions should be. This should make a lot more sense once we fix #602 so I'm going to merge it into that.
