### ISSUE TITLE
Copy and Paste in composer loses line breaks and tabs

### ISSUE THREAD

**Issue by xasos** [nylas/N1#823]
When copying an email from N1 and pasting it somewhere else, it removes all newlines from the email.

**Comment by bengotow** [comment]
Hey @xasos — can you clarify where you're copying from and pasting to? Are you copying text from a composer or a message body? Pasting into N1 or another app? That'll help us reproduce this and fix.

**Comment by bellebethcooper** [comment]
@bengotow I've had this exact same bug when copying text from a sent email and pasting into a new email in N1, if that helps.

**Comment by xasos** [comment]
@bengotow I'm copying text from a composer window and pasting into another composer window in N1.

**Comment by xasos** [comment]
Update: This behavior is also happening when pasting into other text fields, such as the signature tab in Preferences

**Comment by bengotow** [comment]
Hi folks—sorry for the delay. We're wrapping up QA on a new release that fixes this problem. It was actually a one line change (329c6471817ee21b0f81051309868a2ed52af639). The update should be out tomorrow. Enjoy!
