### ISSUE TITLE
Stop using a DMG, because launching from it breaks the autoupdater

### ISSUE THREAD

**Issue by eag1** [nylas/N1#826]
N1 version 0.3.19 correctly displays bar prompting to upgrade to 0.3.32. After clicking install, N1 quits and nothing happens for at least 5 min. When N1 is manually opened back up again the following dialog appears:

![screen shot 2015-12-24 at 12 52 20 pm](https://cloud.githubusercontent.com/assets/7450386/11996962/7988055c-aa3d-11e5-9ea2-385f6151148e.png)

The version is still 0.3.19 and several seconds later the upgrade bar re-appears prompting to upgrade to the latest 0.3.32

If "cancel" is pressed on the dialog instead of "Add Helper", no autoupdate bar appears.

**Comment by bengotow** [comment]
Hmm, that's no good at all. Can you confirm that you have enough disk space for the update to install? I think there's an edge case where installation fails (with no obvious error) if you have < 300MB free. Is there anything interesting in Console.app?

**Comment by emorikawa** [comment]
I finally tracked this down. It's caused when people run N1 for the first time straight from the DMG. It's related to https://github.com/Squirrel/Squirrel.Mac/issues/163#issuecomment-195424008 and https://github.com/Squirrel/Squirrel.Mac/issues/151#issuecomment-195423529

**Comment by emorikawa** [comment]
There are a handful of very serious issues if people forever launch N1 directly from the .dmg

When was attempting to update N1, he got the following error:

<img width="532" alt="screen shot 2016-08-15 at 1 45 18 pm" src="https://cloud.githubusercontent.com/assets/489001/17679149/05f3a798-62ef-11e6-8cf9-a04a3625213f.png">

This is a known issue here: https://github.com/Squirrel/Squirrel.Mac/issues/148
Also see https://github.com/Squirrel/Squirrel.Mac/issues/151#issuecomment-195423529
and https://github.com/Squirrel/Squirrel.Mac/issues/163#issuecomment-195424008

**Comment by emorikawa** [comment]
We no longer serve the .dmg file. Mac users are instead given a .zip. See https://github.com/nylas/edgehill-server/commit/33d20c0ca1a24ffa254f90cee816aeee5991da60

For users that have already launched from the .dmg, we now automatically move to `/Applications`. See https://github.com/nylas/N1/commit/5231b4f556be1f31340cd07f26f037eb456a98d9

Users who unzip inside of `~/Downloads` (or anywhere else) will now get prompted to move N1 inside of `/Applications`. See https://github.com/nylas/N1/commit/5231b4f556be1f31340cd07f26f037eb456a98d9

**Comment by jackiehluo** [comment]
We've pushed an update that resolves this issue (0.4.51). Let us know if you run into any bugs!
