### ISSUE TITLE
“Star us on GitHub to get your invitation faster”? Eww, no thanks

### ISSUE THREAD

**Issue by adamdicarlo** [nylas/N1#83]
![screen shot 2015-10-12 at 10 22 03 am](https://cloud.githubusercontent.com/assets/97462/10433982/31842eda-70cb-11e5-8793-2002014b7500.png)

“Star Nylas/N1 on GitHub and we’ll get you an invitation code as soon as possible”

I guess this is the new “Like us on Facebook to ____”? :cry:

**Comment by adamdicarlo** [comment]
**Please reconsider this strategy.** It's kind of too late now, of course, that you've gotten 8445 stars that may have largely been made not in earnest, but just in attempts to get access more quickly.

**Comment by equinusocio** [comment]
you have to wait a bit and you will get the code :+1:

**Comment by bengotow** [comment]
Hey @adamdicarlo — thanks for checking out N1! Sorry about the waiting list. I was really hoping we wouldn't need the invitation system, but the load overwhelmed our servers last week. There's a big scaling project underway, and it should be gone by the end of the week.

Developers were a small fraction of total signups but a big focus of the release, so we wanted to give them access as quickly as possible. The GitHub auth allows us to tie your email address to your GitHub profile, and we coupled that to a bot that fetches `/stargazers` on the repo and then sorts the waiting list.

As far as I know, the only side-effect of the starring approach was being featured as a trending repo last week. I figured they were just fluff for the most part. I understand why this left a bad taste in your mouth and we'll reconsider this approach in the future. New signup volume is low and we expect to take the invite wall down soon, so we may not adjust the flow in these final few days.

Hope that helps—thanks for filing this and letting us know this isn't the best way to go.

**Comment by adamdicarlo** [comment]
@bengotow Thank you! I'm relieved to have received a thoughtful response.

**Comment by gburch** [comment]
I starred the day you released and I didn't receive a code. I figured I was tricked into starring.

**Comment by rscircus** [comment]
@bengotow, maybe be a bit more transparent about the real issues?

It irritated me, too.

The line of thought is: "Open Source and invitation codes? Err... what?"... and I think many dev minded won't even bother to check, if somebody raised an issue on that one-plus-one-ish behavior.
