### ISSUE TITLE
Saving UI layout state

### ISSUE THREAD

**Issue by ragunaru** [nylas/N1#833]
Currently N1 doesn't remember the state of the widths of the different panes you've set. It reverts back to whatever its defaults are every time you close and reopen the app. Mildly annoying to say the least.

Is that a feature or a bug?

**Comment by jstejada** [comment]
This was added in https://github.com/nylas/N1/commit/27cc46ed1f8456f1c69ee8a8eec33133b9e402d9 and will be available in the next update.
