### ISSUE TITLE
Cmd + k to create a link

### ISSUE THREAD

**Issue by adeloscope** [nylas/N1#836]
CMD+k gmail shortcut does not bring up hyperlink dialogue in message compose screen.

gmail account
mac 10.11.2
N1 Version 0.3.32-b11131d (0.3.32-b11131d)

**Comment by mbilker** [comment]
I am closing this because this isn't implemented and you made a Feature Request in #837.

**Comment by adeloscope** [comment]
I hear you.  Though I respectfully disagree. When I highlight something, I get the below pop-up.  If I click the hyperlink button it brings up the hyperlink dialogue box (already implemented).  All of the other buttons in this box have shortcuts (i.e. cmd+b, cmd+i).  All I'm suggesting is that cmd+k bring up the same dialogue that hitting the hyperlink button would already bring up (with curser already active in that box).

This is different than my feature request which is about creating a more interactive search mechanism as part of the hyperlink dialogue box.

<img width="229" alt="screen shot 2015-12-28 at 4 24 55 pm" src="https://cloud.githubusercontent.com/assets/2516022/12026475/93cf20e0-ad7f-11e5-9170-36d381a9a53c.png">
