### ISSUE TITLE
Feature Request: Edit Link Dialog Box (Cmd/Ctl-K)

### ISSUE THREAD

**Issue by adeloscope** [nylas/N1#837]
When using the cmd-k gmail style shortcut, or clicking the hyperlink button, a search function would come up similar to what happens in google docs.  This allows user to search for a url without needing to change contexts to the browser.  

What would be super double amazing with cherries on top would be functionality similar to http://tapslash.com/ but within the message compose window.

**Comment by mbilker** [comment]
Thank you for the feature request @adeloscope! This looks like an interesting feature that could be brought to N1.

I don't understand what you intended by a search function, but I saw a link tester that opens up a separate window with the link.

![2015-12-26-00-56-20_702x328](https://cloud.githubusercontent.com/assets/1266541/12005299/3a4a186e-ab6c-11e5-98d8-942be4a74100.png)

**Comment by adeloscope** [comment]
Hey!  Actually, the functionality I'm referring to is in google docs.  Not gmail.  Check it: 

<img width="671" alt="screen shot 2015-12-26 at 2 33 07 pm" src="https://cloud.githubusercontent.com/assets/2516022/12007860/ca0874e8-abdd-11e5-9ce3-45c7e0291f15.png">

**Comment by adeloscope** [comment]
oh, and just to clarify.  The reason I separated the cmd+k request, and this feature request, is that I see two ways of implementing this.  
(1) The vanilla way which just brings up a simple dialogue to paste and test a link.  Which already seems to be implemented in N1, just not shortcut driven.
(2) A more advanced feature which brings up an actual search box.  This could eventually be used to search for and embed all kinds of useful stuff.  Similar to https://mixmax.com/ or http://tapslash.com/

**Comment by grinich** [comment]
This is fixed!
