### ISSUE TITLE
Cannot change Account Label while updating mailbox

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#838]
I use 2 computers typically, a laptop and a desktop. The desktop client usually has an older copy of my mailbox on it and takes some time to update. I wanted to change my `Account Label` to not my email address, while the `Syncing your mailbox...` was occurring. I had the `Activity Window` open during this to monitor the progress of the mail sync.

I noticed the `Account Label` revert back to my email address whenever a batch of emails were processed by the client.

I expect this behavior to not occur and N1 allows me to set my `Account Label` while a mail sync is occurring.

**Comment by aizimmer** [comment]
I too am experiencing this bug. At the same time I am noticing that I cannot add a second account while the first one is still being synced. Not sure if the two are related or not.

All in all, though, fantastic job!

**Comment by bengotow** [comment]
Hey folks—this should be fixed in 0.3.45. Let me know if you run into this again!
