### ISSUE TITLE
Feature Request: Fuzzy/Intelligent Search for Address in Compose Message

### ISSUE THREAD

**Issue by adeloscope** [nylas/N1#842]
Would be awesome if, when searching for an address in the search or compose message box:

(1) The search was fuzzy.  For example, the name "Adam C. Hall" should turn up with "Adam Hall", "Hall", "Adam C Hall" (no period), etc...

(2) The search was intelligent.  Gmail does a decent job.  Recently used addresses should receive priority.  Address in the address book, as opposed to all contacts, should receive priority.  Frequently used address should receive priority.  etc.

**Comment by bengotow** [comment]
Hey! This would be really great. We currently do some basic filtering on name / email / domain in https://github.com/nylas/N1/blob/master/src/flux/stores/contact-store.coffee#L61. We'd definitely like to improve this in the future. If you have any ideas, pull requests are definitely welcome!

**Comment by bengotow** [comment]
Merging this into #896—it sounds like there's a bug in our implementation.
