### ISSUE TITLE
Bug: 100% memory consumption and 100% disk write

### ISSUE THREAD

**Issue by de-Mote** [nylas/N1#843]
v0.3.32
Windows
Using Gmail and Namecheap private email

Everytime I open Nylas, slowly but surely, it incrementally begins starting ~100 new processes that are around 27-28MB each and continues to do so until I kill the program. 
![2015-12-27_01-19-37](https://cloud.githubusercontent.com/assets/3811510/12009088/0947f08e-ac38-11e5-969c-679d3081531d.png)

![2015-12-27_01-34-58](https://cloud.githubusercontent.com/assets/3811510/12009143/655ccf0a-ac3a-11e5-8900-54b285bc82e1.png)
I'm guessing it's doing a lot of caching?

![2015-12-27_01-31-45](https://cloud.githubusercontent.com/assets/3811510/12009139/eeb9f12a-ac39-11e5-9c97-ddc5daa7cdb0.png)

Once it caps my memory it ends up causing other programs to swap out memory, page it to disk and consistently keeps my disk writing at 100%.

**Comment by mbilker** [comment]
Hmm. Thanks for the bug report @de-Mote. Do most of the processes have a similar command line with the `compile-cache` listed? If so, that narrows down where the issues stem from.

**Comment by de-Mote** [comment]
Yup, all the ones in the process tree.

**Comment by mbilker** [comment]
The file in question is https://github.com/nylas/N1/blob/b2f8b34a32d87f59c13a77d3a3d74cf5ca4c715b/src/task.coffee . I am now trying to determine why it keeps spawning more task handlers.

**Comment by mbilker** [comment]
@de-Mote Could you provide the full command line called for one of these child processes?

**Comment by de-Mote** [comment]
I'm not sure but I think this is it?

C:\Users\PJ\AppData\Local\nylas\app-0.3.32\nylas.exe --eval require('C:\\Users\\PJ\\AppData\\Local\\nylas\\app-0.3.32\\resources\\app.asar\\src\\compile-cache.js').setCacheDirectory('C:\\Users\\PJ\\.nylas\\compile-cache');
require('C:\\Users\\PJ\\AppData\\Local\\nylas\\app-0.3.32\\resources\\app.asar\\src\\task-bootstrap.js');

**Comment by mbilker** [comment]
@de-Mote Yes that is it.

**Comment by bengotow** [comment]
Wow—that's crazy. The only place we spawn separate processes (via Task) is to send crash reports to our servers. When something bad happens in the app, we spawn a process that POSTs the crash reports to our servers and then exits. Looks like A) something is causing an exception repeatedly and B) our tasks aren't exiting. I'll see what we can do!

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
