### ISSUE TITLE
Installation failed on Ubuntu1404

### ISSUE THREAD

**Issue by joinfok** [nylas/N1#846]
Hello!

I Try today N1 from .deb package, have detect installation breaking.
Debug from ubuntu software center:

Lintian check results for /tmp/mozilla_mozillaUser0/N1.deb:
E: nylas: control-file-has-bad-permissions postinst 0775 != 0755
E: nylas: control-file-has-bad-permissions postrm 0775 != 0755
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.

**Comment by jstejada** [comment]
merging into duplicate #710
