### ISSUE TITLE
menu dissapears on second launch

### ISSUE THREAD

**Issue by martunta** [nylas/N1#847]
Ubuntu 15.04, nylas 0.32, freshly downloaded

Menu is showed only on first launch, after that there is loading cursor for a while if you move cursor over the menu, but no menu shows up. Deleting .nylas folder does not help. 

 ~~There seems to be no way to get manu back.~~

p.s. There is only this Nylas icon with menu next to the clock, that lets to do new message, open preferences and quit the program.  ~~Maybe that is somehow related?~~

update:
Looks like it is related to two different ways you can close the window. If I close complete application using nylas icon in the right and choosing 'Quit N1', and then launching it again, then menu reappears. 
If I just close Nylas N1 window by clicking x on the window corner, and then relaunch it from Dash - then no menu. 

Looks like I have to avoid using native window closing control, until it is fixed, and it will be fine

**Comment by bengotow** [comment]
Hi @martunta — I think this is https://github.com/atom/electron/issues/4012. Going to close as a dup of https://github.com/nylas/N1/issues/911.

**Comment by martunta** [comment]
aha. could be. thanks for looking into it. 
p.s Though as this is number 847, then 911 is the dup of this, not vice versa :)
