### ISSUE TITLE
Feature Request: Signatures for aliases

### ISSUE THREAD

**Issue by rodduenez-wt** [nylas/N1#848]
It would be great if aliases could have their own signatures. Thanks!

**Comment by hieblmedia** [comment]
+1

**Comment by ZaidoR1** [comment]
I am missing this feature very much. It is very important. Thank you guys!

**Comment by jclusso** [comment]
+1

**Comment by jpgiago** [comment]
+1

**Comment by christopherg** [comment]
+1

**Comment by bwng** [comment]
+1

**Comment by fstrube** [comment]
+!

**Comment by jclusso** [comment]
this is literally like the only feature stopping me from not being g able to use nylas.

**Comment by supervalters** [comment]
+1

**Comment by ssyberg** [comment]
+1

**Comment by jrosen48** [comment]
+ 1

**Comment by meteakca** [comment]
+1

**Comment by jffrybrwn** [comment]
Yep, this would be more than helpful.

I just goofed up and sent the a signature for a different company to a prospect for my consultancy. Oops!

**Comment by sinaowolabi** [comment]
+1

**Comment by jclusso** [comment]
Any word on this?

**Comment by tteke** [comment]
+1

**Comment by cr0wmium** [comment]
+1

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/4932

**Comment by pamelawoodbrowne** [comment]
+1 This is crucial to adopting N1 as my default email client.

**Comment by jackiehluo** [comment]
Hey! We've pushed an update (`0.4.47`) that should allow signatures for aliases—let us know what you think! Thanks!
