### ISSUE TITLE
Using search tool disables account switching

### ISSUE THREAD

**Issue by fonnesbeck** [nylas/N1#850]
After entering a search term into the search tool, I am no longer able to switch among accounts. Pulling down the list of accounts and selecting a different one has no effect. The only way to restore behavior is to restart the app.

Running 0.3.32-b11131d (0.3.32-b11131d) on OS X 10.11.2

**Comment by bengotow** [comment]
Good find—I've fixed this and it'll be included in the next release. Thanks for filing the issue!
