### ISSUE TITLE
g-i Shortcut Does Not Work From Message View

### ISSUE THREAD

**Issue by adeloscope** [nylas/N1#854]
Would expect pressing g, then i in succession, when in message view, would switch to the inbox.
Gmail shortcuts are enabled.

gmail account
mac 10.11.2
N1 Version 0.3.32-b11131d (0.3.32-b11131d)

**Comment by mbilker** [comment]
I can confirm this issue. It does work in Gmail (as expected). I wonder if this is related to 37e3fe0f4533ee5139cf0c27ee8cf9a008bc4ffe.

**Comment by adeloscope** [comment]
Strange thing is that once in a blue moon it does work.  Have not found a repeatable pattern yet.

**Comment by waynew** [comment]
I noticed the same thing... oh, I think I see - if you are viewing a message that's in your inbox and hit g-i then it doesn't go to your inbox, but if you're viewing a message that's in another folder g-i *will*

**Comment by mbilker** [comment]
That would make sense @waynew. Since the message view is on top of the inbox view.

**Comment by mbilker** [comment]
I guess the code change would need to check the top of the view stack to see if it is the Inbox view.

**Comment by electrodaddy** [comment]
Have started using N1 today and this was the first thing I noticed. Hitting g-i is in my blood!

**Comment by jstejada** [comment]
Hi everyone, I haven't been able to replicate this. Are you still having this error on the latest version?

**Comment by bengotow** [comment]
I can confirm this has been fixed. Cheers!
