### ISSUE TITLE
Settings -> Keyboard dropdown on OS X crashes N1

### ISSUE THREAD

**Issue by adeloscope** [nylas/N1#855]
This is incredibly obscure, and not a priority to fix.  But...  it is repeatable on my system.  Settings -> Keyboard -> Text -> "for Double Quotes" dropdown menu
Causes N1 to crash.  
But ONLY when editing a message.
I told you it was obscure!! :)

gmail account
mac 10.11.2
N1 Version 0.3.32-b11131d (0.3.32-b11131d)

<img width="688" alt="screen shot 2015-12-28 at 5 22 15 pm" src="https://cloud.githubusercontent.com/assets/2516022/12027146/e22bb71e-ad87-11e5-9452-1ebd4b89cf29.png">

**Comment by bengotow** [comment]
Hey! Going to merge this into #895 - looks like it's the same issue.
