### ISSUE TITLE
Changing Account label will fail due to quick refresh

### ISSUE THREAD

**Issue by bobgrowth** [nylas/N1#856]
I would like to change my account label and it's hard to change it.
It will refresh quickly to previous name so I have to click somewhere else to stop it from refreshing.

I'm using a gmail account in Win10 64 bit
and the version of N1 is 0.3.32

**Comment by jstejada** [comment]
hey @bobgrowth thanks for reporting this. what do you mean by stop refreshing? do you mean while the mailbox is syncing like in this issue #838 ?

**Comment by bobgrowth** [comment]
Yes, it's just that I wasn't aware if the mailbox was syncing or not.

**Comment by mbilker** [comment]
Since this seems like a dupe of #838, I am closing this issue.
