### ISSUE TITLE
Can't delete a label (for GMAIL) created in nylas

### ISSUE THREAD

**Issue by Feichtmeier** [nylas/N1#857]
I created a label in nylas which I also saw in GMAIL but I can not delete it. It is light grey which indicates me (?) that it is somehow deleted but not completly. 

![image](https://cloud.githubusercontent.com/assets/15329494/12031433/2e6b8a44-ae0c-11e5-9088-64c590d0e8bb.png)

**Comment by bengotow** [comment]
Hi @Feichtmeier — has the label disappeared yet? Deleting Gmail labels can take a few minutes to propagate completely.

**Comment by Feichtmeier** [comment]
Hi! Thanks for your reply. Sadly it did not disappear :/ Maybe I reinstall it
later :) And see if it's gone after

> On Dec 29 2015, at 9:12 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@Feichtmeier](https://github.com/Feichtmeier) — has the label
disappeared yet? Deleting Gmail labels can take a few minutes to propagate
completely.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/857#issuecomment-167866726).![](https://github.com/notifications/beac
on/AOno1tT_cR_Cwkthfrxu3UvLvhgXlBQ_ks5pUuCSgaJpZM4G8NQu.gif)

**Comment by Feichtmeier** [comment]
No, even after reinstall the deleted label is still their and still "light"
grey.

  

  

> On Dec 29 2015, at 9:36 pm, Frederik F
&lt;frederik.feichtmeier@gmail.com&gt; wrote:  
Hi! Thanks for your reply. Sadly it did not disappear :/ Maybe I reinstall it
later :) And see if it's gone after

>

>> On Dec 29 2015, at 9:12 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>>

>> Hi [@Feichtmeier](https://github.com/Feichtmeier) — has the label
disappeared yet? Deleting Gmail labels can take a few minutes to propagate
completely.

>>

>> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/857#issuecomment-167866726).![](https://github.com/notifications/beac
on/AOno1tT_cR_Cwkthfrxu3UvLvhgXlBQ_ks5pUuCSgaJpZM4G8NQu.gif)

**Comment by jstejada** [comment]
@Feichtmeier, I believe this issue is related to #681 #680, and should be fixed in an upcoming release. For now though, I'm afraid you'll have to completely delete your `.nylas` folder to get that label to disappear.
