### ISSUE TITLE
Couldn't add Outlook with custom domain

### ISSUE THREAD

**Issue by miedzinski** [nylas/N1#859]
Hey,
I'm trying to add my Outlook account with custom domain to N1 with no success. Everything I get is `Error connecting to the server`, which isn't really meaningful.
On the other hand, connecting to Gmail (with custom domain as well) works like charm.
I am using N1 v0.3.32-b11131d from Debian testing repository.
Thanks.

**Comment by spang** [comment]
Hi @miedzinski,

Are you able to share what email address this is affecting? Is it an Outlook.com account, Office365, or custom Exchange deployment?

**Comment by miedzinski** [comment]
The same bug occurs on Windows version of Nylas, although I was able to add my email the classic IMAP/SMTP way (imap-mail.outlook.com/smtp-mail.outlook.com).
Regarding my account, I have added my domain to domains.live.com, which was the way to go prior to Office 365, I guess. As of today, they don't support managing custom domains, but still host old ones and I am able to access my outlook.com account bound with it.
Domain is mdzn.pl - if you can't find it in logs I can provide you my email address in more private manner (by emailing you).

**Comment by angelbotto** [comment]
i have the same problem :(

**Comment by mexxanit** [comment]
I have the same problem too. "Error connection to the server" . I try another mail app with same account settings it worked. Difference between them is requires authentication checkbox for outgoing server. I have Windows 8.1 and try to use IMAP/SMTP

**Comment by khamidou** [comment]
Hi,

We don't support Windows Live Custom Domains --- it's been deprecated by Microsoft too. **However**, there's a [workaround](https://nylas.zendesk.com/hc/en-us/articles/215684488-I-m-getting-Invalid-Credentials-when-connecting-a-Windows-Live-Domains-account) to be able to sync your account with N1.

k

**Comment by miedzinski** [comment]
Oh, I see. You could update the article on Zendesk though, because I'm getting different error in this case (`Error connecting to the server` vs `Invalid Credentials`). There is also another workaround, which I'm successfully using - simply configure N1 with IMAP account using `imap-mail.outlook.com:993` and `smtp-mail-outlook.com:587` and your regular credentials (username: your mail address, password: your mail password).

**Comment by fabriziodicandia** [comment]
miedzinski, I tried to manually add an outlook account through IMAP and SMTP, using the domains that you provided, but I keep receiving an error saying: "Invalid credentials. Please check that your IMAP username and password are correct". 
Of course the credentials are correct, so there's something else that I'm missing?

**Comment by miedzinski** [comment]
Well, I don't know much about Outlook, but maybe you have had registered your account in other way than me -- and you need to put different credentials or hit another server? I have registered my domain on domains.live.com and got mail account there.

**Comment by fabriziodicandia** [comment]
I found the problem.. I had to use the "App password" options to gain the access.. sorry for haven't updated the post and thanks!

**Comment by birkof** [comment]
Hey,

I had the same problem and I solve it by concatenating username with domain name, separated by "/". (Eg. domain/username)

(0-o)
