### ISSUE TITLE
Signatures from Gmail

### ISSUE THREAD

**Issue by zlatkobijelic** [nylas/N1#86]
Add signatures from Gmail automatically so that it does not have to be done manually.

**Comment by iBeliever** [comment]
:+1:

**Comment by BenjaminMcMurrich** [comment]
+1

**Comment by landerss0n** [comment]
+1

**Comment by vpakg** [comment]
@zlatkobijelic Is there a way to add signatures manually? Or do you mean actually copying and pasting for each email? I can't find in the preferences.

But yeah, having it automatically syncing would be great.

**Comment by zlatkobijelic** [comment]
@vpakg by manually I meant copy / paste yourself, sorry about the miscommunication. But yes automatic signatures directly from gmail would be great. Also adding a PGP option, there would be no reason to use the Mac mail app anymore. 👍

**Comment by grinich** [comment]
There actually isn't an API for signatures, so you'd have to copy and paste them.

Please vote-up this feature request on our roadmap Trello board! https://trello.com/b/hxsqB6vx/n1-open-source-roadmap

**Comment by vpakg** [comment]
Hey, I just want to share an update I got from Ben. 


Hi Victor—signatures are /almost/ ready to go. They're implemented in the open source project, and we just need to build an interface for editing them. Stay tuned!

--
Ben Gotow

**Comment by zlatkobijelic** [comment]
hey @vpakg the comment before you from @grinich mentioned that it was closed since there is no API for signatures.

**Comment by equinusocio** [comment]
Maybe integrating support for HTML signature would be great :+1:

**Comment by pascalvallet** [comment]
Any news for this request?

**Comment by vpakg** [comment]
Hey @pascalvallet , according to @bengotow on issue #347 , this should land with the next update.

**Comment by pascalvallet** [comment]
Fantastic !

On Wednesday, November 18, 2015, Victor <notifications@github.com> wrote:

> Hey @pascalvallet <https://github.com/pascalvallet> , according to
> @bengotow <https://github.com/bengotow> on issue #347
> <https://github.com/nylas/N1/issues/347> , this should land with the next
> update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylas/N1/issues/86#issuecomment-157608286>.
>


-- 

[image: United Nations International School] <http://www.unis.org>

Pascal Vallet | Director of Academic Technology
pvallet@unis.org | +1 347-238-5425

United Nations International School
+1 212-684-7400 Ext: 3037
24-50 FDR Drive New York, NY 10010-4046
http://www.unis.org | Book an appointment <https://www.vyte.in/pvallet.unis>

[image: 500px]  <https://www.vyte.in/pvallet.unis>[image: Twitter]
<https://twitter.com/pascalvalletfr>[image: Linkedin]
<https://www.linkedin.com/in/pvallet>

**Comment by zlatkobijelic** [comment]
I just had an update was that included?

**Comment by bengotow** [comment]
Hey folks—signatures are landing in a release today (0.3.26) but since there's no way to automatically pull them from Gmail, this thread is technically a "wontfix". Cheers!

**Comment by vpakg** [comment]
Beautiful, thanks for the update @bengotow
