### ISSUE TITLE
Inexplicable log entries after using N1

### ISSUE THREAD

**Issue by winks** [nylas/N1#860]
Hi,
I just downloaded and installed 0.3.32 and tested it by sending a mail from Account A to Account B (both on the same mail server)

Why is all email traffic relayed through a third-party mail server? (I found the IP mentioned in #47 as well)

Here are my postfix logs:
```
Dec 29 17:38:46 hostxxxxx dovecot: auth: Debug: client in: AUTH#0113#011PLAIN#011service=smtp#011nologin#011lip=x.x.x.x#011rip=52.32.74.203#011secured#011resp=<hidden>
Dec 29 17:38:46 hostxxxxx dovecot: auth: Debug: sql(user@example.org,52.32.74.203): query: SELECT '/home/vmail/'||maildir AS userdb_home, username AS user, password, '*:bytes='||quota AS userdb_quota_rule FROM mailbox WHERE username = 'user@example.org' AND active = TRUE
Dec 29 17:38:46 hostxxxxx dovecot: auth: Debug: client out: OK#0113#011user=user@example.org
Dec 29 17:38:47 hostxxxxx postfix/smtpd[4076]: 43A90CC4060E: client=ec2-52-32-74-203.us-west-2.compute.amazonaws.com[52.32.74.203], sasl_method=PLAIN, sasl_username=user@example.org
Dec 29 17:38:47 hostxxxxx postfix/cleanup[4088]: 43A90CC4060E: message-id=<e3dxnqaym3giuzif9sgzgnmrh-0@mailer.nylas.com>
Dec 29 17:38:47 hostxxxxx postfix/qmgr[2268]: 43A90CC4060E: from=<user@example.org>, size=905, nrcpt=1 (queue active)
```

Also, here's the `Received`-Header from Thunderbird:
```
from [127.0.0.1] (ec2-52-32-74-203.us-west-2.compute.amazonaws.com [52.32.74.203]) by mx.example.org (mail.example.org) with ESMTPSA id 43A90CC4060E for <xx@example.org>; Tue, 29 Dec 2015 17:38:47 +0100 (CET)
```

**Comment by bengotow** [comment]
Hi there - N1 is built on the Nylas Sync Engine which is a cloud-based mail sync system. You can find the source here: https://github.com/nylas/sync-engine, an FAQ describing why it's built this way here: https://www.nylas.com/N1/faq and security information here: nylas.com/security.

**Comment by winks** [comment]
Well, there should be a big fat warning on https://nylas.com/N1/ - but thanks for the quick reply.

**Comment by bengotow** [comment]
Hey folks! Just wanted to update this thread with some new information:

Originally (at the time of my first answer) Nylas Mail was OSS, but tied to the Nylas Cloud APIs which did the actual mail processing. Nylas had already written all the mail sync logic in Python, and N1 just leveraged that infrastructure.

The cloud strategy came with a lot of pitfalls, and in version 2.0 (April 2017) the entire mail-sync system was moved into the client and open sourced. (https://github.com/nylas/nylas-mail/tree/master/packages/client-sync). It's now much more like Thunderbird. There's a bit of cloud processing for snoozing / send later, etc., but it no longer syncs every email through the cloud.

**Comment by benbucksch** [comment]
Hey bengotow!

First off, great congratulations for this great email client. This is really a stunt you pulled off here. :+1: I like the result, from the screenshots and the reports I hear. Really, impressive work. I know how much talent, expertise, good judgment, bravery and (again) skill this takes. Congratulations.

However, before I could use it, it's an absolute requirement that no email and no metadata of any email ever goes to third party servers (that is, the IMAP and SMTP servers I configured).

I'm happy to hear that in version 2.0, you made architectural changes to do that. That's a very positive surprise. :+1:

Could the rest of the "cloud processing" also be removed, please?
