### ISSUE TITLE
Wrong sender showing in email thread

### ISSUE THREAD

**Issue by seanmangar** [nylas/N1#861]
I sent an email using my personal account, but it shows up as being sent from my work account in the email thread. I have checked on the mailing list and indeed it was sent from my personal account.
<img width="609" alt="screen shot 2015-12-29 at 22 01 08" src="https://cloud.githubusercontent.com/assets/6080053/12039244/1f2e62ce-ae78-11e5-9892-148465bed27c.png">

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
