### ISSUE TITLE
UX issue Multiple accounts.

### ISSUE THREAD

**Issue by Simcat** [nylas/N1#864]
Account list does not show which accounts have received messages. User has to visit each account to see if there is a message in the inbox.  #84

**Comment by mbilker** [comment]
Hey @Simcat, I totally agree with you. I have 3 accounts in N1 and I sometimes cannot tell if the notification disappears before I click on it. This can be implemented through a badge next to each account in the menu. How does that sound?

**Comment by Simcat** [comment]
Sounds perfect :) Thanks for your response.

> On Dec 29 2015, at 5:19 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Hey [@Simcat](https://github.com/Simcat), I totally agree with you. I have 3
accounts in N1 and I sometimes cannot tell if the notification disappears
before I click on it. This can be implemented through a badge next to each
account in the menu. How does that sound?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/864#issuecomment-167913978).![](https://github.com/notifications/beac
on/ABb3h40pPQxqGrqUirB-5mqqTt-vAweCks5pUyi2gaJpZM4G8lPe.gif)

**Comment by bengotow** [comment]
Hi folks—thanks for reporting this. I'm closing this as a dup of #841. This is coming very soon, along with unified inbox!

**Comment by Simcat** [comment]
Thanks!

> On Jan 26 2016, at 11:38 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi folks—thanks for reporting this. I'm closing this as a dup of
[#841](https://github.com/nylas/N1/issues/841). This is coming very soon,
along with unified inbox!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/864#issuecomment-175193945).![](https://github.com/notifications/beac
on/ABb3h5tJxjBjVcNM3tEZkhZaOjwSUmLKks5pd8LOgaJpZM4G8lPe.gif)
