### ISSUE TITLE
Setup animations flicker with a tiling window manager 

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#865]
I noticed this awhile ago and since I accidentally lost my `config.cson` file I had to re-setup N1. I noticed that the animations flicker as N1 expects to be in a constrained view. While this is a setup issue, it still is a bug and can confuse people to believe N1 isn't working correctly. I will try to provide a gif of this happening.

**Comment by mbilker** [comment]
I should mention the actual process works just fine. It is only the animations that look weird.

**Comment by bengotow** [comment]
This will be fixed in the next release. We're not going to resize the window anymore at all. Cheers!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we shipped `0.4.45` this afternoon which should resolve this issue. It should ship via the autoupdater in the next 24 hours, or you can download it directly from the Releases page. I'm going to ahead and close this—if you continue seeing the issue, feel free to comment and I'll re-open it!
