### ISSUE TITLE
Unknown label cannot be deleted

### ISSUE THREAD

**Issue by jk2K** [nylas/N1#867]
![image](https://cloud.githubusercontent.com/assets/4025839/12048382/a564e74e-af15-11e5-85a0-4195bd5982ab.png)

version: 0.3.32-b11131d (0.3.32-b11131d)

**Comment by jstejada** [comment]
hey @jk2K , thanks for reporting this. Do you know how you reached this scenario? Did this dialog appear out of the blue or were you trying to delete a label?

**Comment by jk2K** [comment]
![image](https://cloud.githubusercontent.com/assets/4025839/12059881/0500fdc6-af9f-11e5-9b9e-00840778f630.png)
I don't know where the label comes from
This dialog appeared when I'm trying to delete the label.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.

**Comment by jk2K** [comment]
the problem is solved after the update to latest version, thanks
