### ISSUE TITLE
Crash dialog box gets hidden behind grey window

### ISSUE THREAD

**Issue by jffrybrwn** [nylas/N1#868]
Whenever Nylas crashes, this is what I see.
<img width="860" alt="screen shot 2015-12-30 at 6 53 06 am" src="https://cloud.githubusercontent.com/assets/10054355/12050517/b09ae72c-aec4-11e5-8aeb-291a58c0f08b.png">
I'm still able to interact with the dialog box by pressing enter to restart the app, but sometimes the grey box persists after reloading.

**Comment by mbilker** [comment]
Thanks for the report @jffrybrwn. First of all, what is causing the crash? This is unusual as there aren't many reasons N1 would hang like this.

**Comment by jackiehluo** [comment]
Closing this issue for now since it should be fixed—let us know if it's not!
