### ISSUE TITLE
vim/mutt like keyboard shortcuts

### ISSUE THREAD

**Issue by seniorivn** [nylas/N1#87]
is it possible to make plugin that implements vim/mutt like keyboard shortcuts?

**Comment by LazerPanther** [comment]
:+1:

**Comment by slash686** [comment]
+1 for this feature

**Comment by stuartwesterman** [comment]
Actually, N1 already supports the standard gmail keyboard shortcuts, which share some similarities to vim.  I was delighted to find that some vim movement keys, and action keys, worked right out of the box with N1. (I of course had already enabled them with my gmail account)

**Comment by bengotow** [comment]
Hi folks—we currently have presets for Gmail, Mail.app and Outlook, and the Gmail one has been significantly expanded in 37e3fe0f4533ee5139cf0c27ee8cf9a008bc4ffe. We should now be able to implement just about any shortcut preset!

Is there a place I can find a vim/mutt keyboard shortcut reference? If someone wants to create a Mutt.cson file like https://github.com/nylas/N1/blob/master/keymaps/templates/Gmail.cson, we'd love a pull request to make that a default.

**Comment by bengotow** [comment]
Merging into #633
