### ISSUE TITLE
 Office365 Invalid Credentials  (as of  Office365 support #223 was closed)

### ISSUE THREAD

**Issue by Alculete** [nylas/N1#874]
When trying to add a O365 account I receive an error (Invalid credentials). Added server and username and didn't  work. I'm Using Ubuntu

**Comment by mbilker** [comment]
Thanks for the report @Alculete. As @bengotow said in #223, Office 365 is supported, but there are issues present with its support, and #171 is an example of this. What version of N1 are you using?

**Comment by spang** [comment]
Hi there, thanks for your report! This almost certainly means that you did not enter your username and password correctly. Please try again and make sure your credentials are correct. :)

(Note to @mbilker—Office365 and Outlook.com are actually distinct products offered by Microsoft—the latter being what used to be Hotmail before Microsoft acquired the product. They do both use Exchange ActiveSync behind the scenes to sync mail.)

**Comment by mbilker** [comment]
@spang Thank you for that! I didn't know that before.

**Comment by Alculete** [comment]
@mbilker I'm using the latest version for ubuntu
