### ISSUE TITLE
Add keyboard shortcuts set for Google Inbox

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#875]
It would be good to have a set of keyboard shortcuts that mimic Google Inbox (note: this is separate from Gmail). See here: https://inbox.google.com/

Some of these won't be implementable yet because the core functionality doesn't exist in N1 AFAIK (pinning/reminder notes, snoozing). Some things (like enter/u for expanding/collapsing a message inline) would have to be implemented a bit differently. Keys like [ would need to do several things (select currently focused email in the list, archive it, and advance to next item).

<img width="913" alt="screen shot 2015-12-30 at 5 20 49 pm" src="https://cloud.githubusercontent.com/assets/491376/12068480/0159e546-afc4-11e5-8e07-e49206991c1f.png">

**Comment by mbilker** [comment]
Thanks for the request @phoenixeliot! These are being made by @GMPolyakov in #876.

**Comment by mbilker** [comment]
The changes in #876 are merged into master. They should be available in the next release. Thanks for the request!
