### ISSUE TITLE
Gmail auth confusing when using multiple 'Persons' in Chrome

### ISSUE THREAD

**Issue by natarius** [nylas/N1#878]
I use the People feature in Chrome to keep my different persona's (privat, business, etc) seperate.

But I want access to some of the personas in N1. But when I oauth with Gmail in N1 it jumps to the last used chrome window which is confusing.

Other apps just open a Google account signup popup that lets me login with the account I want to connect with.

Here is a screenshot of what the Chrome person switching dialog looks like:
![screen shot 2015-12-31 at 5 28 00 pm](https://cloud.githubusercontent.com/assets/607331/12069293/7e6f4fce-afe4-11e5-956f-744bb1df29a1.png)

**Comment by bengotow** [comment]
Hi @natarius —thanks for filing this. We used to show Google's authentication screen right within N1, but we ran into a couple nasty edge cases. For some people with school/business Google Apps accounts, the auth redirects to their SSO provider, and sign in often generated an email saying "New Sign in from Safari" since the view was powered by webkit. We also had complaints that people couldn't use their password managers / saved passwords to go through the process quickly.

All and all, I think bouncing out to Chrome is a better experience most of the time, but I'll leave this open and hopefully we can revisit it in the future.

**Comment by grinich** [comment]
@natarius what does it look like when you click to add a Gmail account? Do you get the option to switch personas?

**Comment by natarius** [comment]
Nope I don't.

Chrome keeps my accounts completely separated 

—

**Comment by grinich** [comment]
What screen does it show when you click the gmail auth button? Does it immediately jump back to the app, or does it give you a window where you can switch personas?

**Comment by natarius** [comment]
it switches to my last used chrome window

**Comment by natarius** [comment]
@bengotow Thanks for getting back. These are some valid arguments. I think what tipped me off was that the OSX Google Drive app also uses the Google auth dialog...and so do most other apps that I remember. So I kinda expected that.

**Comment by mbilker** [comment]
I do not think it is possible to choose the Chrome window the authentication window opens. If you were to use the `open` command in Terminal with a URL, you will notice it opens in the default web browser with the last used window.

**Comment by mbilker** [comment]
@natarius Google Drive may do something with the Keychain to retrieve credentials that are shared between Chrome and Google Drive.

**Comment by natarius** [comment]
All they do is open a pop up with the Google auth dialog.

No magic.

And then you simply type in your email and password.

It's not super duper convinent since you don't have access to stored passwords...but at least you don't get weird messages or hook up the wrong account because of whatever last chrome window you had open 

—

**Comment by mbilker** [comment]
@natarius I will attempt to implement a `<webview>` to display the Chrome login dialog. It should be able to detect a Chrome authentication response.

**Comment by natarius** [comment]
Great. Let me know when you have something to try out

**Comment by bengotow** [comment]
Hey folks! Going to go ahead and close this one. All and all, folks seem pretty content with the app bouncing out to Gmail. We might revisit this in the future, but we'd like to focus efforts on new feature development and performance rather than the edge cases above. Cheers!
