### ISSUE TITLE
CONTRIBUTING.md incorrectly states you need an invite code

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#879]
CONTRIBUTING.md has these notes that should probably be removed, unless I'm missing something. AFAIK you no longer need an invite code.

> Note: You currently need an invitation code to use N1. You can request one here. If you reach out to our team, we can bump you to the front of the list so you can contribute to the project.

and

>The invitation flow allows us to control adoption of N1 and maintain a great experience for our users. However, the sync engine is open source and you can set it up yourself to begin using N1 immediately. Follow instructions on the sync engine repository.

and

>Once you have an invitation code:

**Comment by mbilker** [comment]
Thank you for reporting this @phoenixeliot! I created the PR #880 for this issue.
