### ISSUE TITLE
work exchange server - sync issues

### ISSUE THREAD

**Issue by drcjcarr** [nylas/N1#882]
I am having difficulty syncing with my work exchange server.  It says that it connected successfully but cannot sync. my exchange server thinks that it is trying to sync from a mobile device and it blocks that access. outlook 2016 allows my exchange account to sync but is blocking you guys. What do I need to do to get this fixed? Seems there needs to be a way to make the access not appear to be coming from an iphone.  Thanks!

Here is what I get in my email account when I try to sync:

Your phone won't be able to synchronize with the server via Exchange ActiveSync because of an access policy defined on the server.
 
Your device is currently in temporary quarantine.
If you are enrolling your device with MaaS360, this is a normal part of the activation process. Your device will be released from quarantine after final review by the Business Applications Team.
If have not recently enrolled your device with MaaS360, you must request an enrollment to be released from quarantine.
 
Information about your mobile phone:
Device model:	iPhone
Device type:	iPhone
Device ID:	22a0e6979d11447fb539f60d6e1ed7ca
Device OS:	
Device user agent:	python-EAS-Client 1.0
Device IMEI:	
Exchange ActiveSync version:	14.0
Device access state:	Blocked
Device access state reason:	Individual

**Comment by mbilker** [comment]
Hey @drcjcarr, and thanks for the report. The [sync engine](https://github.com/nylas/sync-engine) uses ActiveSync to connect to Exchange servers. The Nylas team reports that OWA support for Exchange is coming later.

You should also report this issue over at the [sync engine's issue page](https://github.com/nylas/sync-engine/issues).

**Comment by spang** [comment]
Hi there,

Unfortunately, the way to implement ActiveSync support is by authenticating as a mobile phone, and I'm not aware of a good alternative to doing this. If your Exchange setup does not support mobile devices, we can't support that account. Perhaps you can convince your Exchange admin to enable mobile device support? It's likely that Outlook desktop uses some undocumented/private protocol extension to sync.

**Comment by drcjcarr** [comment]
I'm not sure but the iphone app cloudmagic has a way of doing it as well.  I was told by someone that you guys were working on OWA support but they wanted me to post my question here.  Please advise.  Thanks!

**Comment by alexberry** [comment]
I really like the look of Nylas N1, however I had the same issue as @drcjcarr, in that my desktop account is treated as an activesync client... May I ask why nylas chose the activesync protocol over EWS? Most all servers that have activesync open to the world will have EWS open too, and EWS is a fully documented protocol that's designed to be used by desktop mail clients.

**Comment by drcjcarr** [comment]
Agreed @alexberry.  Airmail and clougmagic both use EWS which allows my email to come in.  Nylas is blocked from associating with my email server which makes it useless to me.  Please let us know if you change your mind.
