### ISSUE TITLE
Embedding links 

### ISSUE THREAD

**Issue by startrek456** [nylas/N1#883]
Hi 
I was trying to send an embedded link (highlighted the word and inserted the link) to a Dropbox file over nylas email. The link never shows up after the email is sent. Would be great if this could be fixed since I really like nylas email. 
Thanks

**Comment by grinich** [comment]
Hi @startrek456 -- can you be more specific about the steps to reproduce, or perhaps include a screencast?

**Comment by startrek456** [comment]
Thanks. I installed the latest update and this issue has been resolved.
