### ISSUE TITLE
N1 does not indicate when it is offline / not syncing mail

### ISSUE THREAD

**Issue by smacking** [nylas/N1#887]
Apple Mail does it with an icon. On Sparrow, for example, it's simply a "pull" to refresh, similar to how it works on iOS devices. I personally prefer this 2nd option. Not sure how it works on other Email clients.

On Nylas N1, which is really an awesome piece of software that I just felt in love with, It's really annoying to not be able to refresh e-mail. Makes me feel that I'm not controlling the experience :)

**Comment by mbilker** [comment]
N1's backend, the Sync Engine, uses push notifications for notifications of new mail. I do not know what happens for Exchange and IMAP clients.

This issue depends if the Sync Engine implements forced refresh and the implications it would have on rate limiting by the mail providers.

**Comment by spang** [comment]
This is more of an N1 UI request than a mail sync issue. I'll leave it to @ben to figure this out—ideally we want the seamless syncing to just work and for folks to never have to manually sync. N1 *could* manually sync to our backend if it wanted to right now.

**Comment by mbilker** [comment]
@spang Thanks for the update and clarification.

**Comment by grinich** [comment]
Honestly this button would just be a no-op. N1 automatically syncs and will re-connect if disconnected. One option is that we can implement something that shows if you're offline, just so you know that new mail is not being downloaded. Would that suffice?

**Comment by grinich** [comment]
@smacking the reason Apple Mail and Sparrow have this button is because they don't have a streaming API they can use. :wink:

**Comment by smacking** [comment]
Got it @grinich. Actually our CTO at Pixelmatters already explained me the technical reason behind the decision to don't have that button. I don't really have a strong argument to defend it, since it's just something that I "feel". It's just that thing that software is controlling me, instead of the opposite. Maybe it's just me.

In any case, having some kind of error saying that I'm offline or something wrong is going on, would definetely help. Slack does it well.

**Comment by bengotow** [comment]
Hey folks, I think this is related to #164. I'll see if we can improve offline status indicators in the future, so it's more clear whether N1 is actively syncing your mail.

**Comment by smacking** [comment]
that's right @bengotow! Sorry I didnt' saw that issue was already created.

**Comment by bengotow** [comment]
Hey! This was fixed in version 0.4.25, which will be hitting the auto-updaters soon. (If you want you can grab the update now on the Releases page.) Give it a spin, and feel free to re-open if you run into the issue again. Cheers—enjoy the update!

![image](https://cloud.githubusercontent.com/assets/1037212/14479787/f7e4256c-00d6-11e6-8a2e-21ecd270897c.png)

**Comment by lumeng** [comment]
I'm running 0.4.45. How does one force a mail syncing/updating?
