### ISSUE TITLE
Feature Request: Add sender icon to `MessageList`

### ISSUE THREAD

**Issue by smacking** [nylas/N1#888]
I was writing this down explaining the changes that I'd suggest, but actually, an image is better than a thousand words. Here's my suggestions to improve the list, visually:

Current Design: http://cl.ly/0m2K2Y2l0S3l
My Suggestion: http://cl.ly/0t2f090P121y

Basically, the main "issue" for me is that there isn't a clear distinction between each email on the current list. Everything seems to be the same. In my opinion, changing the height of the font size in the name of the Sender, and adding the correspondent thumbnail (like Sparrow does it) would make the experience way more personalized.

Thoughts?

**Comment by mbilker** [comment]
Thanks for the request @smacking! I like this request and seems more like Gmail's Inbox with icons for sender's it can determine icons for.

**Comment by bengotow** [comment]
This is definitely something we'd like to do in the future, though we need a more reliable source of avatars than we currently have. Gonna go ahead and merge this with #660 and add a comment with your mockups.
