### ISSUE TITLE
Fix "Change Folder" Gmail shortcut behaviour

### ISSUE THREAD

**Issue by joshuous** [nylas/N1#891]
Regarding the "Change Folder / Label" Gmail shortcut, the 'v' shortcut in N1 only appends a new label to the email and does not move it out of inbox. On Gmail, 'v' moves the email to a different label and removes the 'Inbox' label.

Is it possible to change the functionality of 'v' in N1 to match Gmail's?

**Comment by mbilker** [comment]
This is related to #881. While this one is for setting a label, both issues regard setting a label and moving the message into that label and removing the `Inbox` label.

**Comment by bengotow** [comment]
Closing as dup of #881 - we need a "Move to Category" in addition to an "Apply Category" action.
