### ISSUE TITLE
deepin system install n1 failed

### ISSUE THREAD

**Issue by zyfjeff** [nylas/N1#894]
Selecting the selected package nylas.
Reading the database... The system is currently installed with 123853 files and directories. )
Ready to unpack N1.deb...
Is unpacking NyLas (0.3.32)...
Dpkg-deb (process): unable to copy from the N1.deb archive members to decoding pipeline: unexpected end of file or stream end
Dpkg-deb: error: the child process is pasted back to the error state 2
Error during dpkg: processing archive N1.deb (--install):
Unable to'./usr/share/doc/nylas/copyright'copy extract files to'/usr/share/doc/nylas/copyright.dpkg-new': not expected end of file or the end of the stream
Handling triggers for lastore-daemon (0.9.14-1)...
Handling triggers for desktop-file-utils (0.22-1)...
Handling triggers for bamfdaemon (0.2.118-1+b1)...
/usr/share/applications/bamf.index Rebuilding...
Handling triggers for mime-support (3.59)...
There is an error in processing:

**Comment by mbilker** [comment]
Thanks for the report @zyfjeff! What is the result of `sha256sum` on the `N1.deb` file? This appears to be a malformed file error.

**Comment by mbilker** [comment]
There is N1 version 0.3.36 available at https://github.com/nylas/N1/releases/tag/0.3.36 for your platform.
