### ISSUE TITLE
Contact ranking for address book autocompletion is not working

### ISSUE THREAD

**Issue by natarius** [nylas/N1#896]
Huge bump on the road of switching email clients is that N1 doesn't automatically fetch everybody's contact (email + name) from my email history to make it available via auto complete when I start typing in the email address field.

Now I have to go back to Apple Mail or Gmail to get my regular email contacts one by one :(

**Comment by bengotow** [comment]
Hey @natarius —we actually do this already. There's actually an endpoint for `/contacts/rankings` on our backend. It seems it must not be working? I'll take a look.

**Comment by enoversum** [comment]
Yes, it does. Seems to be some more specific case in which it doesn’t work. Fine here on Windows with two IMAP accounts.

**Comment by bengotow** [comment]
Hmm thanks @enoversum — @natarius, are you using a Gmail account? Could you try going to Developer > Toggle Developer Tools in the main window and then typing this line on the console?

```
require('../src/flux/stores/contact-ranking-store')._value
```

It should print out a giant map of email => frequency.

**Comment by natarius** [comment]
Yes using 3 gmail accounts.

firing 

    require('../src/flux/stores/contact-ranking-store')._value 

returns 

    Object {}

Si that might be my problem :/

**Comment by bengotow** [comment]
Hi @natarius — thanks for the reply, that certainly narrows it down a bit! I'll see what's going on.

**Comment by natarius** [comment]
Awesome. Thanks :)

—

**Comment by bengotow** [comment]
This should be fixed in 0.4.4 - we rebuilt the contact caching quite a bit. Let me know if the issue persists and we can re-open this!

**Comment by natarius** [comment]
Will do. Thanks

> On Feb 6 2016, at 12:36 am, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> This should be fixed in 0.4.4 - we rebuilt the contact caching quite a bit.
Let me know if the issue persists and we can re-open this!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/896#issuecomment-180719975).![](https://github.com/notifications/beac
on/AAlEYwm3903rD6QzxoKqwAWzeEqyuVAtks5phagngaJpZM4G-UeR.gif)
