### ISSUE TITLE
Can not delete a label within N1

### ISSUE THREAD

**Issue by Catherine** [nylas/N1#898]
After creating a label in N1, then hitting delete, the label does not go away. The label is still listed as greyed out and it does not appear in Gmail when I look at my labels.
<img width="208" alt="screen shot 2016-01-04 at 5 25 43 pm" src="https://cloud.githubusercontent.com/assets/3717039/12102361/3ad10b6e-b308-11e5-8cd2-08b36d5bd302.png">

I have though, successfully created a new label within Gmail itself, have it visible in N1, then deleted it within Gmail and verified that it is no longer showing in N1.

**Comment by mbilker** [comment]
Thanks for the report @Catherine. If you close N1 and reopen N1, is the label still present in N1? I see this on my client when I delete a label. The greyed out status (typically) means the action is waiting for the Sync Engine to respond.

**Comment by Catherine** [comment]
@mbilker yes, quitting and reopening the application (multiple times I might add) does not cause the label to disappear.  It's been in the "sort of deleted" state for over a day now.  

Other info: I'm a mac user on El Capitan.

**Comment by jstejada** [comment]
Hi @Catherine , this should be fixed in our latest release. Let us know if the problem persists.

**Comment by Catherine** [comment]
@jstejada -- It tells me that I have the latest version, but the issue still persists. The labels are not going away.  I might just completely uninstall and reinstall to fix it, but just wanted to let you know that this ticket shouldn't necessarily be closed yet.
<img width="434" alt="screen shot 2016-01-07 at 6 32 19 pm" src="https://cloud.githubusercontent.com/assets/3717039/12186042/2f484dae-b56d-11e5-88b6-a12eb5a86500.png">

**Comment by huylv** [comment]
I'm using the latest version 0.4.25-a22631a (0.4.25-a22631a) and today, a label `\All` suddenly appeared out of nowhere. I couldn't delete it. Reinstalling didn't fix it. Please reopen this issue and investigate.
