### ISSUE TITLE
Bug: Message Count Stuck without any new messages

### ISSUE THREAD

**Issue by raguay** [nylas/N1#900]
Hi,

I have N1 setup with three Google accounts. Two of my accounts work fine, but the third one, and the one I use the most, always shows one unread message even with there are no messages in the inbox. It shows the "phantom" message in the menu bar icon, the left side mailbox list, and the dock icon. I am using Mac OS X 10.11.3 Beta.

**Comment by bengotow** [comment]
Hi @raguay — thanks for reporting this, we're looking into this issue in the next update. I'm going to go ahead and merge this with #759.

**Comment by wasd171** [comment]
Same problem, OS X 10.11.3, N1 0.4.5-b0ec335

**Comment by raguay** [comment]
The latest version (Version 0.4.5-b0ec335 (0.4.5-b0ec335)) fixed this for me.
I'm running OS X 10.11.4 Beta (15E33e).

> On Feb 8 2016, at 2:34 pm, Konstantin Nesterov
&lt;notifications@github.com&gt; wrote:  

>

> Same problem, OS X 10.11.3, N1 0.4.5-b0ec335

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/900#issuecomment-181240116).![](https://github.com/notifications/beac
on/ACX0x3-dRZ6hv_P5AZmnNnIp_oFbQ0kVks5piDySgaJpZM4G-mHG.gif)

**Comment by wasd171** [comment]
Still have it on N1 0.4.5-b0ec335 and OS X 10.11.4 beta (15E33e)

**Comment by wasd171** [comment]
Still have it on N1 0.4.5-b0ec335 and OS X 10.11.4 beta (15E49a)

Have tried to delete `~/.nylas`, but it won't help, there is still one spiritual unread message

**Comment by framerate** [comment]
I'm seeing this problem again as well on today's update.

**Comment by shawnlknight** [comment]
Seeing this as well.

**Comment by boogah** [comment]
Also seeing this.
