### ISSUE TITLE
No icon in Xubuntu 15.10

### ISSUE THREAD

**Issue by Mountainerd** [nylas/N1#901]
After installing, both the window button on the taskbar and the icon in the upper left revert to an unknown icon (white square). I have attempted adding the WMclass fix that seemed to work for GNOME users (I was hoping the answer was in some sort of GTK voodoo) but it did not fix the problem. The system tray icon is fine.

**Comment by mbilker** [comment]
Thanks for the report @Mountainerd. Does the icon revert to the unknown box **after launching** N1? Does it show the actual icon **after exiting** N1?

I will see if I can replicate the issue on my Arch Linux installation.

**Comment by Mountainerd** [comment]
@mbilker I am attaching a screen shot showing the app open and the menu open as well. You will see the menu shows the icon as it should (no manual intervention on my part) but the taskbar entry and the icon on the app itself are white squares. Hopefully this will clarify what I mean. Please let me know if you need any testing/assistance from me. 
![screenshot_2016-01-05_08-07-46](https://cloud.githubusercontent.com/assets/3386955/12118441/b45bb15c-b383-11e5-913c-b5e7bdb2d5da.png)

**Comment by mbilker** [comment]
Found the issue! It is at https://github.com/nylas/N1/blob/master/src/browser/nylas-window.coffee#L12.

N1 tries to find an icon in `/usr/share/nylas/resources/app.asar` at `build/resources/nylas.png`, which doesn't exist in the release build.

N1 also appears to stick the `nylas.png` in `/usr/share/pixmaps`, which should be in `/usr/share/icons/hicolor/{16x16,32x32,64x64,128x128,256x256,512x512}/apps/nylas.png`. The RPM build already does this in its `spec` file.

If you compile N1 from source and run it from the source directory via `./N1.sh` it will display the correct icon since it can find the path.

**Comment by bengotow** [comment]
Hey @mbilker —it looks like this was broken in a previous change. Want to address that second issue (the location of `nylas.png` and I'll take a look at the first issue? I think that path needs to match where files are placed in https://github.com/nylas/N1/blob/master/build/tasks/copy-files-for-build-task.coffee#L202

**Comment by mbilker** [comment]
Thanks @bengotow. The build script already copies the icon to `/nylas.png` as evident from the output of `asar list /usr/share/nylas/resources/app.asar`. The script needs to point to that image or something like what Atom does with a `/resources/atom.png` icon path.

**Comment by bengotow** [comment]
Yep sounds good—I've gone ahead and changed NylasWindow in d8a510326fae3d481e9dde2ccffcfbc70d502b73. We were also setting it on other platforms, which we shouldn't have been doing (makes the icon grainy on Windows)

**Comment by mbilker** [comment]
I will submit a PR for the second issue.

**Comment by mbilker** [comment]
Submitted a PR for the 2nd issue as #903.

**Comment by bengotow** [comment]
Awesome! That should take care of this. Cheers–

**Comment by Mountainerd** [comment]
I will confirm this as fixed in version 0.3.36 that I received via update. That's some quick turnaround!
