### ISSUE TITLE
Add Download all link to message view

### ISSUE THREAD

**Issue by gertjanwytynck** [nylas/N1#905]
It should be super handy if a user could download all attachments in one click. Or even more when there is a shortcut to download all the files.

**Comment by natarius** [comment]
+1

And also allow direct export to Apple OSX Photo app please :)

**Comment by bengotow** [comment]
This would be a great starter issue. When you click to download and save a single attachment, it fires the `Action.fetchAndSaveFile`, which is handled here: https://github.com/nylas/N1/blob/unified-inbox/src/flux/stores/file-download-store.coffee#L215. We'd want to create a similar action that prompted the user for a directory and then saves an array of Files into that folder.

**Comment by lashae** [comment]
+1

**Comment by grinich** [comment]
<img width="532" alt="screenshot_3_14_16__1_38_am" src="https://cloud.githubusercontent.com/assets/92417/13738968/8fc4954c-e985-11e5-9b0f-3edd2269dca7.png">

Should probably use the same treatment as this button: 
![image](https://cloud.githubusercontent.com/assets/92417/13738992/b454ccc4-e985-11e5-9265-d4e73dce60c7.png)

**Comment by bengotow** [comment]
Even if we do https://github.com/nylas/N1/issues/1712? We may not be able to fit text in it after that.

**Comment by sdewith** [comment]
<img width="549" alt="screen shot 2016-03-14 at 3 40 17 pm" src="https://cloud.githubusercontent.com/assets/13399516/13762316/5ccf1218-e9fb-11e5-9451-10af193405cd.png">

Design changes proposed to Attachments -- includes new arrow designs across the board and a 'download all' feature in a header that shows up when there's more than 1 attachment.

**Comment by davidzuercher** [comment]
+1 for the download all button on top of the attachments!

**Comment by bengotow** [comment]
Hey! This shipped in `0.4.19` a few minutes ago. You can grab the update by choosing "Check for Updates" from N1's application menu, or download the new version directly from the releases section of the project. Enjoy!
