### ISSUE TITLE
no unread mail count on folders 

### ISSUE THREAD

**Issue by Yerlix** [nylas/N1#907]
When using the mail rules to organize all my email into folders and subfolders, there is no display of unread email inside a folder.

**Comment by bengotow** [comment]
Hi @Yerlix — you can turn this on in Preferences > General. I think the option is called "Show unread counts for all folders / labels". Cheers! Feel free to re-open if that doesn't work. I'll see if we can make this more obvious in the future.

**Comment by Yerlix** [comment]
This works. I missed that, my bad.
Thanks for the quick reaction.

(maybe a more obvious solution would be good in the end, but reading all the text solved this for me as well)
