### ISSUE TITLE
Difficulty inputting Chinese characters

### ISSUE THREAD

**Issue by brettgerry** [nylas/N1#91]
A user is reporting that Chinese characters cannot be input because while typing, they are "interrupted".
See this for the see what is happening:
https://uploads.intercomcdn.com/i/o/2451028/fcfba025c9d47feefe812307/gif.gif

**Comment by jacobbubu** [comment]
Yes. I've encountered the same thing.

**Comment by emorikawa** [comment]
Duplicate of #62
