### ISSUE TITLE
Menu disappears in after reopening window - Ubuntu 15.10

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#911]
I am using Ubuntu 15.10. When I open Nylas, then close windows and open again, I will not show menu (File, Edit, View, Help). Submitted via -- https://app.intercom.io/a/apps/t7k2sjgy/inbox/unassigned/conversations/1674529239

**Comment by bengotow** [comment]
This appears to be a core Electron issue. Filing a bug there with a sample app.

**Comment by sholanozie** [comment]
@bengotow

Looks like this was fixed recently by the Electron team: https://github.com/atom/electron/pull/4581

**Comment by bengotow** [comment]
This was unblocked on Electron and should be fixed in the most recent release. Cheers!
