### ISSUE TITLE
Account Label input in preferences styles look wrong in Dark Mode

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#914]
Using  Elementary OS Freya 

![screenshot](https://cloud.githubusercontent.com/assets/1271509/12152531/1d26fa34-b46a-11e5-9e15-dfdc20f60291.png)

**Comment by gjuchault** [comment]
![image](https://cloud.githubusercontent.com/assets/678848/12152985/c5809a1c-b4b7-11e5-854a-0b5f3b5396bc.png)

Actually, just setting `border: 1px solid #xxxxxx;` solved it (on the `input`)

**Comment by bengotow** [comment]
Hey! I'm not sure exactly when this was fixed, but it looks OK now:

![image](https://cloud.githubusercontent.com/assets/1037212/14542037/e5d141e0-025a-11e6-9662-86ce376fb21e.png)

Thanks!
