### ISSUE TITLE
Labels list search box doesn't autofocus sometimes

### ISSUE THREAD

**Issue by bellebethcooper** [nylas/N1#916]
I can't figure out why this only happens sometimes—it seems random so far. When I hit "L" on my keyboard, the list of labels shows and there's a search box at the top. Sometimes it autofocuses the search box, as expected, but other times it's not focused, so typing a letter to filter my labels doesn't work.

I'm using N1 Version 0.3.36-e8239a9 (0.3.36-e8239a9) on El Capitan 10.11.2 (15C50)

**Comment by mbilker** [comment]
Thanks for the report @bellebethcooper. Focus issues are present in N1 and the team is working hard to track them down to squash the little buggers.

I have issues with the Composer not focusing, which is annoying.

**Comment by mbilker** [comment]
I just reproduced it on Linux running 0.3.36.

**Comment by bellebethcooper** [comment]
It seems like the same problem is affecting the search bar for messages. Both search bars take focus, then immediately lose it. I see the cursor pop in, then disappear, and I can't type anything in the box.

**Comment by mbilker** [comment]
I have the same issue except with another input box for my PGP plugin.

**Comment by bellebethcooper** [comment]
This appears to be fixed for me in Version 0.3.45-3b5880e (0.3.45-3b5880e).

**Comment by mbilker** [comment]
This is good! Thank you for noticing this!
