### ISSUE TITLE
Chinese Pinyin Input is not working correctly on Mac

### ISSUE THREAD

**Issue by matthewbassett** [nylas/N1#917]
Hi all!

odd issue I've noticed with pinyin input. I'm using version 0.3.36-e8239a9.
When inputting chinese pinyin, you generally write a sentence at a time before choosing the characters. In nylas, you would need to write one word and select the character for it at a time. in other applications I am able to write entire sentences before I need to choose the correct characters for the pinyin.
I suspect this has something to do with the way Nylas N1 performs its spelling corrections? but that's just a guess? Thanks again for a great client!

**Comment by mbilker** [comment]
Dupe of #590

**Comment by mbilker** [comment]
It is to do with spelling corrections and how N1 handles words in sentences.

**Comment by matthewbassett** [comment]
Thanks,

Sorry I missed the dupe... I swear I searched for it q:
