### ISSUE TITLE
Cannot redownload an attachment after a failed attachment download

### ISSUE THREAD

**Issue by yasharne** [nylas/N1#918]
If you get disconnected during downloading an attachment, you'll get an error `Unable to download XYZ Check your network connection and try again.`, but after that you wont be able do download that file anymore, it gives that error once you press save button

**Comment by bengotow** [comment]
Hey! Thanks for filing this - sorry it took so long to get addressed. We fixed the attachment download process in 0.4.14 so failed downloads are retried the next time you click the attachment or try to save / open it. Give the new version a shot and feel free to reopen if you're still experiencing the issue!

**Comment by ragnar321** [comment]
I think I'm still getting this issue on 0.4.19 - it downloads as a 0 byte file (but shows with the appropriate filesize in the body of the email). The file can be downloaded direct from gmail with no issue. 

All I seem to see in the activity log is:

20010:36:49  RunCopycurl -X GET "https://1XjLNqBydErsdlmG6Q9SOubTOXTwl4:@api.nylas.com/files/1vo6zxkl6a8q6w9ekokx5llst/download"

**Comment by shfitz** [comment]
I'm seeing the same behavior in 0.4.25-a22631a on OSX. If the initial download fails, all subsequent ones will as well.
