### ISSUE TITLE
Exchange email not viewable, notifications and composer work

### ISSUE THREAD

**Issue by jrcolroadom** [nylas/N1#919]
**TL;DR** I can send mail using the AD, but I just can not see or view my mail from the exchange server.

The issue here is with my Exchange account, after several tries, the account signs in to the Exchange server but it does not sync all the mail that I have on the server. I see the notifications from new mails but can not view the messages in the mailbox. Also, the "compose new mail" option accesses the mail contacts from the domain.

**Comment by jrcolroadom** [comment]
today i noticed that when i tried to check the mailbox from the Exchange account, there was just Stared and Drafts options, also the "Create a new folder" on check if they worked, and they did... but there is nothing about the actual mailbox ore any synced.

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
