### ISSUE TITLE
Invitation code. Where is he?

### ISSUE THREAD

**Issue by ForumLiker** [nylas/N1#92]
Hi. I pointed out several e-mail addresses, but the code does not come. Please share your Invitation code

**Comment by cyalins** [comment]
Please use the issue tracker for issues only! You'll need to be patient for the code

**Comment by ForumLiker** [comment]
ok

**Comment by mbilker** [comment]
Why is this reopened?

**Comment by bengotow** [comment]
Hi @ForumLiker thanks for your interest in N1. We're sending out invitation codes every day, and a major backend project is wrapping up which will allow us to send them out much faster. Sorry for the wait—stay tuned.
