### ISSUE TITLE
Opening Attachments

### ISSUE THREAD

**Issue by jcuenod** [nylas/N1#921]
Right now to open attachments they must first be downloaded to a folder from which we can open the file (maybe that's just true on Linux). It would be good if we could open attachments directly from within N1.

**Comment by bengotow** [comment]
Hi @jcuenod — can you try double-clicking the attachment? I'm not sure if it works on Linux, but that should open the files.

**Comment by jcuenod** [comment]
Well now I feel stupid. Yes it does work, I don't know why it doesn't work on single click though (only the little nested download button on the right does anything with single click). There's also no right click menu. I'm glad the feature already exists though. Thanks!
