### ISSUE TITLE
grunt not found during installation script

### ISSUE THREAD

**Issue by Son-kun** [nylas/N1#923]
After I run `node script/bootstrap` I get:
```shell
/bin/sh: 1: /home/son/n1_local/build/node_modules/.bin/grunt: not found
```
Script before try to use grunt create 3 other links:
```shell
acorn -> ../acorn/bin/acorn
commonize -> ../commoner/bin/commonize
regenerator -> ../regenerator/bin/regenerator
```

Any suggestion what can be wrong? Btw. its on virtual machine (VBox).

**Comment by mbilker** [comment]
Thanks for the report @Son-kun, but did `script/bootstrap` complete successfully? The bootstrap script installs Grunt at the path mentioned.

**Comment by Son-kun** [comment]
This occur during work script/bootstrap.

**Comment by mbilker** [comment]
What is the error?

**Comment by Son-kun** [comment]
That is all output after execute `node script/bootstrap`

```shell
Node: v5.4.0
npm: v3.3.12

---> Installing N1 build tools
     This goes inside the `build` folder and runs `npm install`
     It will use the system `npm` to bootstrap our own N1 npm.
     Our build tools (like Grunt) need to be compiled against Node via `npm
     Everything else needs to be compiled against Chromium with `apm`.

     $ npm --userconfig="/home/son/n1_local/.npmrc" install --loglevel error --cwd=/home/son/n1_local/build --ignoreStdout=true

/bin/sh: 1: /home/son/n1_local/build/node_modules/.bin/grunt: not found
```

**Comment by mbilker** [comment]
That is strange because it installs grunt during the `npm` run. Try running `script/bootstrap --no-quiet` to see if there are any errors during `script/bootstrap`.

**Comment by Son-kun** [comment]
After that i get additional line:
```shell
npm WARN EPACKAGEJSON nylas-build@ No license field.
/bin/sh: 1: /home/son/n1_local/build/node_modules/.bin/grunt: not found
```

**Comment by felipetavares** [comment]
Apparently, running the commands by hand works. Instead of running bootstrap, running:

```
 npm --userconfig="PATH_TO_N1/N1/.npmrc" install --cwd=PATH_TO_N1/N1/build
```

and the other commands one by one.

**Comment by mbilker** [comment]
@felipetavares that is weird

**Comment by felipetavares** [comment]
I'm trying it on a container. If I can reproduce it I will post detailed info.
