### ISSUE TITLE
Weirdness in [ and ] for Google Inbox shortcuts

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#924]
Referencing #876

For Google Inbox shortcuts, I think for [, "remove-and-next" is not quite the correct behavior. Not sure if the function should be improved, or a new one is necessary for simulating Inbox's behavior.

It's worth noting that in Google Inbox's way of operating, no keyboard shortcuts except # should ever trash an email.

This results in some weirdness when I hit [:
• It seems to advance in the wrong direction — in Inbox, [ goes to the next item in the list. In N1, it seems to go to the previous one in the list (the next one chronologically?)
• If I'm in the list view, [ archives the selected email and opens the next one. It should instead archive the email and advance to the next in the list without opening it.
• If the first item in the list is open or selected and I hit [, the same email will open/stay open. Hitting [ again will then move it to the trash. [ should never trash emails. Instead, hitting [ or ] at the end of a list should put me back in the list view.
• Items are sent to the Trash if you're viewing them in search results, regardless of if they were previously archived. Again, [ should never trash — and if something is already marked done (archived), it should just stay marked done, and the list should advance.

Behavior is slightly different in split-panel mode.
• Advancement happens correctly when the first item in the list is archived.

These are the same.
• Advancement still goes in the wrong direction
• Search results are still wrongly trashed

**Comment by phoenixeliot** [comment]
`e` also does not archive an email in single-panel list view unless it's marked with `x` first. `e` should archive the currently selected email without needing to mark it with `x`.

**Comment by emorikawa** [comment]
You're right! The `[` and `]` keys were reversed.

In Gmail if you push `e` without selecting something (via `x`) it does NOT archive. It does, however, give you a warning that `No conversations selected`.

**Comment by phoenixeliot** [comment]
Ah, but here we are mimicking Google Inbox, not Gmail :)
