### ISSUE TITLE
Copying and inserting inside composer window creates 2-space indentation

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#927]
I am not sure whether this is supposed to be a feature or a bug :wink: .

When I copy some text in the composer for the e-mail body and paste it somewhere into a new line, the text gets an indentation of two spaces on the first line. Is it meant this way? 

Speaking of the latest Windows version.

**Comment by bengotow** [comment]
Hi @enoversum — thanks for reporting this, super annoying indeed. This has been fixed in 329c6471817ee21b0f81051309868a2ed52af639 and will be included in the next release (wrapping up QA later today.)
