### ISSUE TITLE
Drag and drop attachments from N1 to browser

### ISSUE THREAD

**Issue by enoversum** [nylas/N1#928]
One feature that would surely upgrade our user experience would be the ability to drag and drop attachments to the explorer/a folder.

**Comment by enoversum** [comment]
Sorry, that is already possible, seems to have shipped recently, since last time I tried it didn’t work. 
Maybe a small add-on: I cannot drag files to browser windows (e.g. uploading a file). Would that be possible to enable?

**Comment by bengotow** [comment]
Hey! Hmm - what platform are you on? You can drag and drop files into composers to attach them to drafts (though not to other areas of the window like the thread list). It's possible it's broken on Linux though!

**Comment by enoversum** [comment]
No, exactly the other way around (see the original title of my thread here). Drag and attachment **from** N1 **to** the computer. Folders obviously now work, only dragging an attachment from N1 to a browser window (as other clients do support this, I would think this theoretically possible) isn’t doing anything :wink: .

**Comment by enoversum** [comment]
Sorry, missed that one: I am on Windows 10 x64.

**Comment by bengotow** [comment]
Oh I see what you mean—from N1 *to* Chrome / etc. You know, I've noticed I also can't drag from N1 to Slack, and I'm not 100% sure why. I'll see if we can get to the bottom of it. We may just be attaching files to the drag data incorrectly.

**Comment by bengotow** [comment]
Hi @enoversum — I think we fixed this in 0.3.43. It should work now, as long as the application you're dragging to supports the file type and N1 has downloaded the attachment (should always be the case, unless you've chosen to download them manually in Preferences.)

Can you see if it's resolved on Windows?

**Comment by enoversum** [comment]
Hi @bengotow , it kind of works :). When I drag a file into Chrome to open it, it succeeds. Trying to add it to a web app fails, at least in my two trials with Trello and Adobe Assets. 
Both are able to handle file dropping in order to create content. When I drop a file into a board in Trello, it creates a new card with the file as its attachment. When I drag it onto an existing or even open card, it gets attached to the chosen card. When I drop a file into Adobe Assets, it simply gets uploaded to the assets.
Now, with my 'old' e-mail client I could simply drag and drop my attachment onto the Trello or Adobe browser window and have it behave normally. When dragging from N1 to a Trello board, a card is being created containing the link to the file on my harddrive as the title, e.g. 'file:///C:/Users/Eno/.nylas/downloads/5m6smd4vzp8y0rmecj9gt68iu/ScreenClip%20[8].png?percent=100', while no attachment is being made. Dragging it onto a specific card shows the usual 'Drop files to upload' notice from Trello, but nothing is added to the card when dropping the file.
Adobe Assets also shows the file upload notice when I try to drop a file from N1, but afterwards tells me I couldn’t upload whole folders (which I didn’t, single file only). 

I hope this a little more detailed explanation helps ;):

**Comment by bengotow** [comment]
Hey @enoversum — thanks for the detailed explanation. I think this may be the best we can do given N1's roots in Chromium. I'm going to go ahead and close this, but I'll keep looking for ways we can improve this. I think the trick is that the drag/drop target needs to have filesystem access, but I'm not sure.
