### ISSUE TITLE
Japanese font is crumbling

### ISSUE THREAD

**Issue by kometchtech** [nylas/N1#931]
Craziness is the font that is specified when trying to view the Japanese mail, or seems to distort the view.

Environment: Windows 7 SP1 x64

Nylas N1
![nylas](https://cloud.githubusercontent.com/assets/5137077/12201623/bb11ddf4-b668-11e5-9f37-566da7a0e5f8.JPG)

Gmail
![gmail](https://cloud.githubusercontent.com/assets/5137077/12201625/c32ae4d6-b668-11e5-86d6-504b9c2bd285.JPG)

You can specify the font used to display is not?

My best regards.

**Comment by mbilker** [comment]
Thanks for the report @kometchtech. It appears the font is not antialiased; antialiasing should work.

**Comment by kometchtech** [comment]
@mbilker 
Immediately of reaction Thank you.

Font used to display the Japanese are like CJK fonts are not suitable for the display of Japanese.

Only anti-aliasing it would not be resolved.

**Comment by mbilker** [comment]
Thanks @kometchtech. I am looking into how Chrome displays Japanese characters better than N1.

**Comment by mbilker** [comment]
Forgot to ask, what platform are you running N1 on? Is it OS X, Linux, or Windows?

**Comment by kometchtech** [comment]
@mbilker Environment that has been confirmed is Windows.

**Comment by bengotow** [comment]
Thanks @kometchtech — I'll check this out. In message bodies, I believe we set `-webkit-font-smoothing: antialiased`. It may be causing the text to appear thinner and lighter than it should. Here's what it looks like on my Mac:

With Antialiasing (Current):
![image](https://cloud.githubusercontent.com/assets/1037212/12205166/c8b709e6-b5ed-11e5-87a6-5c1be131a701.png)

Default:
![image](https://cloud.githubusercontent.com/assets/1037212/12205172/d05d5240-b5ed-11e5-84d7-22a9b8a855f3.png)

The second one would be better?

**Comment by kometchtech** [comment]
Thank you. @bengotow 

Font smoothing is I think no problem.
The problem, is that correct Japanese font is not used in the display.

**Comment by mbilker** [comment]
I copied some text off of http://kadokawa.co.jp and fired off an email to myself. It seems to render just fine on my Linux machine.


![2016-01-08-12-31-35_491x353](https://cloud.githubusercontent.com/assets/1266541/12204797/931d9950-b604-11e5-8814-a7c75105fa25.png)

**Comment by mbilker** [comment]
This may be related to atom/atom#6214

**Comment by kometchtech** [comment]
Thank you for confirmation. @mbilker 

Linux rendering it looks like no problem.

**Comment by mbilker** [comment]
Okay. I investigated into this more. It appears to pick a default CJK rendering font I ripped onto my computer from the Windows 10 ISO; Chromium picked the Microsoft YaHei font in my case ([link](https://www.microsoft.com/typography/fonts/family.aspx?FID=350)). 

![2016-01-12-22-07-58_1279x780](https://cloud.githubusercontent.com/assets/1266541/12283926/43116c66-b979-11e5-923f-da274bbd512d.png)

**Comment by mbilker** [comment]
_Backstory: ran `fc-cache -fv` to flush and rebuild the font cache on my computer and I noticed `/usr/share/fonts/ttf-noto-fonts-cjk-ib` which reminded me of this issue._

It is pretty difficult to get to the view in the DevTools for the IFrame. I wish I could <kbd>Right Click</kbd> and click `Inspect Element` like in Chrome or Atom.

**Comment by jackiehluo** [comment]
Closing this issue for now since it should be fixed—let us know if it's not!
