### ISSUE TITLE
Drafts authored in Gmail not sending (commit 348aa69)

### ISSUE THREAD

**Issue by awmartin** [nylas/N1#932]
After checking out the latest master branch (commit 348aa69), N1 won't send drafts that were created in the Gmail interface. The following message results after clicking "Send."

<img width="547" alt="screen shot 2016-01-07 at 9 40 08 pm" src="https://cloud.githubusercontent.com/assets/57281/12188902/7cf0844e-b587-11e5-8cd3-2707b28f4c22.png">

Repro steps:

1. Go to gmail.com
2. Click "Compose" and author an email. Close the composer window.
3. Open N1. Wait until the drafts folder syncs.
4. Double-click the draft to open it in a separate window.
5. Click "Send."

Also, not all of the drafts will sync. It's not clear yet which ones will sync and why, but in N1, I have 3 drafts available, and in the Gmail interface, there are 5. The two missing were authored in Gmail.

It would be very good to have a better error message here for the user, or at least a dev log entry.

This also occurs in the current production release (Version 0.3.36-e8239a9).

**Comment by bengotow** [comment]
Hi @awmartin — we overhauled the way drafts are sent in 0.4.5. Could you try this again with your account and see if it's still an issue? I haven't been able to reproduce it yet.

**Comment by awmartin** [comment]
Looks like this has been resolved!
