### ISSUE TITLE
Draft windows lose focus on undo (cmd+z)

### ISSUE THREAD

**Issue by awmartin** [nylas/N1#934]
The message body field will lose focus when pressing cmd+z on a Mac.

Repro steps:

1. Create a new draft.
2. Edit the body of the message in the new composer window.
3. Press cmd+z to undo some of the typing.
4. The body field will have lost focus.

**Comment by emorikawa** [comment]
@awmartin Thanks for the repro steps. Yes, I'm seeing this too. We'll take a look into this today.

**Comment by emorikawa** [comment]
This was fixed on 99f6749 and will go out in the next release
