### ISSUE TITLE
Wrong element focused when clicking bottom of New Message window

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#935]
Mac OS 10.11.1
N1 Version 0.3.36-e8239a9
Gmail

When composing a New Message, if I click in the empty space below the text that has been typed, the focus is incorrectly chosen such that I can't type any new text.

The element that SHOULD be in focus:
`div.contenteditable`

The element that IS in focus is the ancestor ComposerWithWindowProps:
`div.key-commands-region.focused.message-item-white-wrap.composer-outer-wrap`

**Comment by bengotow** [comment]
Good catch - this should be fixed now. Technically, you can still interact with the buttons in the composer footer and blur the contenteditable, but it should behave as expected now I think.
