### ISSUE TITLE
Calendar.app brought to foreground when receiving event email

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#937]
Mac OS 10.11.1
N1 Version 0.3.36-e8239a9
Gmail

If I have Calendar.app open, whenever I receive an email with an event or event update, Calendar.app is brought to the foreground unexpectedly. Tested with Google Calendar events, where I was an invitee.

Correct behavior would be to push information to Calendar.app without pulling it to the foreground.

If Calendar.app isn't running at the time, it is not opened, and it does have the correct information at next launch.

**Comment by bengotow** [comment]
Hmm this is really strange—can you try downloading an .ics file from Chrome and see if Calendar.app comes to the foreground when the file finishes downloading? We don't attempt to open the attachments or send anything to Calendar.app—the app is just saving them to disk.

**Comment by phoenixeliot** [comment]
Downloading an ICS doesn't trigger anything. (from https://www.bridgetroll.org/events/238/event_sessions/366.ics)

Opening the file brings Calendar to the foreground and prompts me to add the event. (I do not see this prompt when I receive an event email)

**Comment by phoenixeliot** [comment]
Ack! Whoops, this was a misreport. I had Mail.app open as well (thought I didn't) and the bug is actually coming from Apple's own mail client. Guess I'll go file a report with them.

Looks like N1 is doing the right thing here.

**Comment by grinich** [comment]
![beer-dance](https://cloud.githubusercontent.com/assets/92417/12208549/4eb9ea2c-b602-11e5-9494-8466862133ba.gif)

**Comment by mbilker** [comment]
@grinich That is actually a cool gif.

**Comment by phoenixeliot** [comment]
Hah, love it.

One thing to note: The thing Apple Mail is *trying* to do, although it's being annoying while doing so, is pretty useful/nice. N1 does not push any calendar updates to Apple Calendar, so the event isn't updated/added automatically.

Might be nice to implement that, but if Apple is doing it wrong I suspect something would need to change in Calendar's API for that to happen without foregrounding Calendar.
