### ISSUE TITLE
Event accept/maybe/decline buttons flipping after fast clicks

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#938]
Mac OS 10.11.1
N1 Version 0.3.36-e8239a9
Gmail

In an email with an event invitation, if you click one of the "accept/maybe/decline" buttons, then quickly click another one, the clicked buttons will be selected correctly — then quickly flip between the two buttons again. It will end up on the correct state in the end.

Best guess is that each button is updating again when it gets a response from the server, and since each one is listening separately, it replays the state history from the last few seconds after you click, which is only noticeable if you clicked multiple buttons quickly.

![out](https://cloud.githubusercontent.com/assets/491376/12209211/691594a8-b606-11e5-9245-d400ab581f07.gif)

**Comment by grinich** [comment]
I'm going to close this as stale. Please open a new issue if this is still occurring.
