### ISSUE TITLE
Keyboard shortcuts don't work on drafts

### ISSUE THREAD

**Issue by phoenixeliot** [nylas/N1#939]
Mac OS 10.11.1
N1 Version 0.3.36-e8239a9
Gmail

Steps to reproduce:
1. Create a New Message
2. In the main panel, open the Drafts section
3. Select an email (eg, `x` with gmail shortcuts)
3. Hit the "Trash" keyboard shortcut (eg `#` with gmail shortcuts)

Actual results:
Nothing happens.

Expected results:
The draft should be trashed, possibly with a confirm prompt.

This occurs in both single-panel and two-panel modes.

Keyboard shortcuts also can't open drafts for editing. List navigation shortcuts do still work.

**Comment by jackiehluo** [comment]
Hey! A fix is shipping now in 0.4.40, which will be hitting the auto-updaters soon. (If you want, you can grab the update now on the Releases page.) Let us know if you're still experiencing the issue after trying it! Thanks!
