### ISSUE TITLE
Feature Request: Passphrase or user-input field for plugins

### ISSUE THREAD

**Issue by mbilker** [nylas/N1#942]
In my PGP plugin, I use a forked version of the [smalltalk](https://github.com/mbilker/smalltalk) library for a passphrase input field. It works great, but I am not sure if its style fits in with the rest of N1.

I request to have a user-input field available to plugins via the `nylas-exports` module. I would prefer to use an officially support version than to use a 3rd-party UI module and adapt its CSS to fit N1.

**Comment by bengotow** [comment]
Hey @mbilker — I'm not sure quite what you're looking for... can you just create an `<input type="text">`? We have enough base CSS that it should be styled to match the rest of the app.

**Comment by mbilker** [comment]
Okay. I am using a modified [smalltalk](https://github.com/mbilker/smalltalk) library and removed CSS to allow N1's styles to apply. Currently I am having focus issues where it focuses for a second and then focus is lost on the `<input />` element.

**Comment by bengotow** [comment]
Hmm - that's strange... Are you running on the latest master? We fixed a bug Friday evening that was causing the composer's body field to steal focus from composer extensions. Maybe that was it?

**Comment by mbilker** [comment]
No. The input box appears when opening a message to decrypt the message. This may be similar to #916.

**Comment by bengotow** [comment]
Hey @mbilker — I'm going to go ahead and close this one. Let me know if you continue having trouble with focus on the Slack channel and we can figure it out!
