### ISSUE TITLE
inbox counter says -1

### ISSUE THREAD

**Issue by artailicous** [nylas/N1#946]
It says -1 on the inbox. Also I realize now that it's partly Swedish and partly English. Inbox, Starred and Drafts are English (perhaps decided by the program itself as opposed to being synced?)
![capture](https://cloud.githubusercontent.com/assets/6124885/12218092/4b37167c-b715-11e5-90f6-7f0158f9c3bc.PNG)

**Comment by mbilker** [comment]
The program only decides the Drafts name, and the Inbox name reflects the mail account. However, the `-1` is not normal behavior.

**Comment by jstejada** [comment]
going to merge into duplicate #759
