### ISSUE TITLE
Allow for "send as" functionality

### ISSUE THREAD

**Issue by justinmccormick** [nylas/N1#95]
There doesn't seem to be a way to send email using an alias.

**Comment by Ehesp** [comment]
https://github.com/nylas/N1/issues/63

I got an email about this too - it's not implemented but on the feature list for upcoming updates.

**Comment by justinmccormick** [comment]
On the roadmap is good enough for me, as is the issue you opened before I did ;)

**Comment by vladislavivanistsev** [comment]
great!

**Comment by jstejada** [comment]
referencing #414
