### ISSUE TITLE
Feature Request: Default "reply" icon rather than "reply all"

### ISSUE THREAD

**Issue by matthieugomez** [nylas/N1#951]
When receiving an email with multiple recipients, I'd like the default reply arrow icon to be "Reply" (i.e. single arrow) rather than "Reply all" (i.e. double arrow). Could there be a setting for this?

**Comment by bengotow** [comment]
Hey @matthieugomez — you can now choose this under Preferences > General > Sending. Cheers!

**Comment by matthieugomez** [comment]
:clap:
