### ISSUE TITLE
Feature Request: Disable spellcheck

### ISSUE THREAD

**Issue by ghost** [nylas/N1#955]
I am one of those who do not need the spell checker in N1 because I also use other languages and spelling very bother me. Has anybody here a good idea how to disable the spelling in N1?

**Comment by jodldoe** [comment]
:+1:

**Comment by Bergg** [comment]
+1

**Comment by gislitg** [comment]
+1

**Comment by bherila** [comment]
It occurs to me that spell check should possibly be refactored out as a plugin?

**Comment by grinich** [comment]
I'm going to merge this into #1392 since that's how we'll fix the multilingual issue.
