### ISSUE TITLE
Integrated inbox

### ISSUE THREAD

**Issue by fameal** [nylas/N1#957]
Hey guys! I love Nylas N1 but I have multiple accounts (2 Gmail and 1 Exchange) and it's difficult to work with Nylas without and integrated inbox for all of them. Is this a possible new feature?

**Comment by Yerlix** [comment]
There is already an existing issue for this (also on the road map on Trello if I'm not mistaking)
https://github.com/nylas/N1/issues/537

**Comment by fameal** [comment]
You are totally right, it's on Trello also. Sorry for that, already voted up on Trello.
