### ISSUE TITLE
Send with no body message when there is a body

### ISSUE THREAD

**Issue by waynew** [nylas/N1#959]
Running Nylas 0.3.34 on Arch Linux (built from the git repo),

I'm using an Exchang account, and when I send emails it always asks if I want to send the message without a body - even though there is one.

![there is a body here!](https://www.dropbox.com/s/ooyn2rnpyuz2rfd/Screenshot%20from%202016-01-11%2011-33-56.png?dl=1)

I think that this might be the cause of the error:

        "stack": "TypeError: editableNode.querySelectorAll is not a function
    at Function.onContentChanged (/home/wayne/.nylas/packages/N1-Composer-Templates/lib/template-composer-extension.es6:112:35)
    at Contenteditable.atomicEdit (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:93:21)
    at Contenteditable.atomicEdit (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:1:1)
    at Contenteditable._runExtensionMethod (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:350:5)
    at Contenteditable._runExtensionMethod (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:1:1)
    at Contenteditable._runCallbackOnExtensions (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:325:7)
    at Contenteditable._runCallbackOnExtensions (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:1:1)
    at Contenteditable._onDOMMutated (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:256:6)
    at MutationObserver.<anonymous> (/home/wayne/programming/N1/src/components/contenteditable/contenteditable.cjsx:1:1)",

    "message": "editableNode.querySelectorAll is not a function"

**Comment by bengotow** [comment]
Hey! Ahh man—yep, it looks like that error would do the trick.  I'll take a look at this and let you know how it goes.

**Comment by mbilker** [comment]
**Off topic.** Hey its another `i3` user and an Arch Linux user! Did you perhaps use https://aur.archlinux.org/packages/n1-git?

**Comment by waynew** [comment]
@mbilker Yep, they're the best ;) No, I didn't - I actually didn't realize there was one, I think. It might be worthwhile usign that instead...

Something that may or may not be relevant: I'm pretty sure I updated from within N1 at one point (though I don't remember if sending emails ever worked on this machine). I tried doing a git update, thinking that it might have an effect, but... it didn't :(

**Comment by mbilker** [comment]
@waynew A git update for the cloned repository is `git pull`. I maintain the `n1-git` package for Arch Linux. Though it updates `pkgver` by the Git tag and commits from the Git tag.

**Comment by waynew** [comment]
@mbilker I went and installed the version from the AUR. I get the same problem when it comes to the `querySelectorAll is not a function`. Also (unrelated) got the `ELECTRON_PATH` problem, too, when running the `nylas` from `/usr/bin/nylas` as opposed to `/path/to/my/aur/n1-git/pkg/n1-git/usr/share/nylas/nylas` :P

**Comment by mbilker** [comment]
Actually, the binary is stored at `/usr/share/nylas/nylas`. My PR #593 to fix the `ELECTRON_PATH` has not been merged yet. The `querySelectorAll` issue is not known. Could you publish some screenshots of the error in DevTools?

**Comment by waynew** [comment]
Okay, so here's a mystery:

I'm still on 0.3.34 and it works. I don't know what in the world changed, but I'm not getting the error message, and when I send mail out, the body is now included.

I though it may have been because I restarted N1 from within N1, so I started it from the command line. Still worked.

Then I thought maybe it's because I started it using the absolute path to the nylas executable on the command line. Nope, *still* worked.

It works whether I just started it, or restarted from with N1. It works in debug, and not.

I cannot find a single configuration where I can reproduce this again. Maybe some library updated? ¯\_(ツ)_/¯

I can call this closed unless someone else can repro :P

**Comment by mbilker** [comment]
@waynew The example plugins were integrated into the core N1 application in the most recent version. If you upgrade to `0.3.43` (or master) the plugin will automatically be moved to the deprecated packages folder in `~/.nylas` and you can reenable the package from `Preferences -> Plugins`.

**Comment by emorikawa** [comment]
@waynew I'm pretty sure this was due to a malfunctioning plugin. We found that composer plugins that had errors could take down the whole thing! We've subsequently patched this to make sure that composer plugins are more isolated and that we have a better way to update the core ones.

I'm going to close this for now, but if this continues to happen in future releases, please let me know.

**Comment by shardulm94** [comment]
Was this fixed? I just did a fresh install of Nylas 0.4.52 and I still get this.

![nylas](https://cloud.githubusercontent.com/assets/6961317/18620330/20b71114-7dde-11e6-99ef-bd80eef6820a.png)
