### ISSUE TITLE
Supporting PGP / GnuPG 🔒🔑

### ISSUE THREAD

**Issue by Natim** [nylas/N1#96]
I need to sign my email before they are send as well as encrypting/decrypting mail I am exchanging with some people.

Do you have any plan on support GnuPG integration with N1?

**Comment by jneureuther** [comment]
:+1:

**Comment by jalcine** [comment]
[**@Natim**](https://github.com/Natim) commented on [Oct 17, 2015, 9:44 AM EDT](https://github.com/nylas/N1/issues/96#issue-111963798 "2015-10-17T13:44:46Z - Replied by Github Comment Enhancer"):
> I need to sign my email before they are send as well as encrypting/decrypting mail I am exchanging with some people.
> 
> Do you have any plan on support GnuPG integration with N1?

This was the first thing I was looking for when I saw this project, tbh. I wonder if [Keybase](https://keybase.io) could help here; it could begin with support for them and then abstract out to allow for local keys to be used.

Reference docs: https://keybase.io/docs/api/1.0

**Comment by gardner** [comment]
Dup was closed: https://github.com/nylas/N1/issues/19

If it were to remain open then FOSS developers would know it's a thing they can work on.

**Comment by gmontalvoriv** [comment]
There are many javascript libraries that can be used to implement such functionality using Nodejs like, [OpenPGPjs](http://openpgpjs.org/) and [gpg](https://github.com/drudge/node-gpg).

**Comment by jalcine** [comment]
Cool! Now let's a PR going :)

**Comment by alexanderadam** [comment]
Did anyone start [creating a plugin](https://github.com/nylas/N1/issues/19#issuecomment-146009198)?
And did everyone here [vote for the implementation](https://trello.com/c/pe6PPy2r/7-pgp-encryption-support)? :wink:

**Comment by bengotow** [comment]
Hey folks! Excited that there's a lot of community interest in GnuPG. We've been moving feature requests and plugin ideas to our [product roadmap Trello board](http://trello.com/b/hxsqB6vx/n1-open-source-roadmap) and there are almost 30 votes for it there! I'm happy to leave this issue open so we can keep the conversation going.

If anyone wants to pick up development of this, the team and I are happy to help out on the [community Slack channel](http://slack-invite.nylas.com/), but may not have time to work on it internally for a few months.

**Comment by grinich** [comment]
Also, the [n1-plugins repo](https://github.com/nylas/n1-plugins) might be a good place to get some code and start working on this

**Comment by danieljcosta** [comment]
+1 (y)

**Comment by joshumax** [comment]
:+1:

**Comment by esseti** [comment]
+1 for this.

**Comment by mbilker** [comment]
I am working on this. I have a decryption implementation working, but I am working on passphrase input and not stalling the UI with the decryption process with a 4096-bit key. String operations can be slow (>1000 ms delay).

**Comment by mbilker** [comment]
Also, I will sanitize my project and post it later on Github (in school at the moment).

**Comment by jalcine** [comment]
@mbilker Thank you for your work!

**Comment by alexanderadam** [comment]
@mbilker woah! Awesome, looking forward to your source! :+1:

**Comment by mbilker** [comment]
Currently working on it. Building a node worker to do decryption.

**Comment by danieljcosta** [comment]
Cooolll! Thank you. DC

**Comment by mbilker** [comment]
It's live. https://github.com/mbilker/email-pgp

**Comment by mbilker** [comment]
```
[17711:1109/235812:INFO:CONSOLE(267)] "[PGP] Decrypted message, 4579.6309710000005ms", source: /home/mbilker/.nylas/dev/packages/email-pgp/lib/message-loader.cjsx (267)
[17711:1109/235812:INFO:CONSOLE(272)] "[PGP] HTML found in decrypted, 0.085856ms", source: /home/mbilker/.nylas/dev/packages/email-pgp/lib/message-loader.cjsx (272)
```
Bottleneck is the decryption, which includes the decryption of secret key and decryption of actual message. Using a 2048-bit key will dramatically lower the time. I use a 4096-bit key.

**Comment by zlatkobijelic** [comment]
I am so glad to hear that people are working on this, I would love to switch away from my default Mac Mail app. I use **GPGTools.org** right now with Mac Mail and it works just fine, but I like the UI /UX of N1 much better. Please keep us posted on this progress.

**Comment by mbilker** [comment]
I will look into their UI/UX and think of better integration

> On Nov 14 2015, at 10:31 pm, Zlatko Bijelic &lt;notifications@github.com&gt;
wrote:  

>

> I am so glad to hear that people are working on this, I would love to switch
away from my default Mac Mail app. I use **GPGTools.org** right now with Mac
Mail and it works just fine, but I like the UI /UX of N1 much better. Please
keep us posted on this progress.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/96#issuecomment-156775849).![](https://github.com/notifications/beaco
n/ABNTbahTgtCDasvIFzdJ9DHEfyRg-ZWZks5pF_QdgaJpZM4GQuyR.gif)

**Comment by mbilker** [comment]
I am currently working on Keybase encryption. I am working on logging in through an external window and then saving the login (CSRF) token to the NylasEnv config, which is the same place the N1 account information is stored.

**Comment by Natim** [comment]
> Bottleneck is the decryption, which includes the decryption of secret key and decryption of actual message. Using a 2048-bit key will dramatically lower the time. I use a 4096-bit key.

Do you guys plan on using ServiceWorker to do that task in the background?
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by mbilker** [comment]
Hmm. I need to review the documentation. Currently I do it the Node way with a background process, but there is the expense of spawning the new process.

**Comment by deiu** [comment]
+1 this is the only missing feature that would have me switch to N1 full time.

**Comment by zlatkobijelic** [comment]
@deiu hahaa same here. I am now 80% N1 and 20% Mac Mail app (just because of PGP). Looking forward to this in the very near future.

**Comment by mbilker** [comment]
@zlatkobijelic thats cool. I am looking into GPGTools' source code to see how they parse messages.

**Comment by zlatkobijelic** [comment]
@mbilker maybe reaching out to https://github.com/lukele wouldn't be a bad idea. Seems to be the main contributor for GPGTools. They are also very responsive through twitter and their forums. 

Good luck @mbilker hope to see this working in the near future. I believe that many people will switch from Mac Mail to N1 once PGP is supported. 

Cheers!

**Comment by mbilker** [comment]
@zlatkobijelic Would something like the security message in [this screenshot](https://cms-assets.tutsplus.com/uploads/users/317/posts/23721/image/gpg-receive.jpg) be useful. I have a way to display this through a custom Message Header, and state is shared from the PGP Store I use and message bodies subscribe to listen to events.

**Comment by mbilker** [comment]
Hmm. I will continue to use #19 as the primary issue to address any concerns regarding PGP in N1. Please do not ask any more questions here.

**Comment by martijnvandijk** [comment]
Is it possible to integrate with gpg-agent? I use a smartcard for my private keys.

**Comment by mbilker** [comment]
Hmm. I might have to integrate gpg-wrapper from keybase then.

**Comment by NodokaMurmevent** [comment]
+1 need GPG

**Comment by sbrl** [comment]
@mbilker I use keybase too. If you need an invite to keybase I have a few spare.

I'll consider switching to N1, but only if / when it supports GPG. It's an absolute requirement of mine.

**Comment by mbilker** [comment]
Ahh. Okay. I am working on the encryption aspect of my plugin. I have pass-phrase input working, but I am thinking of using a GPG extension to decrypt as well.

**Comment by martijnvandijk** [comment]
I'm willing to test integration with gpg-agent. Just mention me here if you need anything!

**Comment by kanadskiy** [comment]
+1 N1 looks very promising but this feature is a hard prerequisite and the only thing keeping me on Thunderbird.

**Comment by mbilker** [comment]
@martijnvandijk The current iteration has an option to use GPG. I have it working with `gpg-agent`.

**Comment by enoversum** [comment]
@mbilker Hi there, I see you are moving forward in your development of the plugin. However, I downloaded it, put the folder to my packages and can see the plugin being enabled in settings. However, how can I actually use it? There is no option to decrypt, nor a way/settings to leave my key anywhere. Possibly not working on Windows in the latest build?
And yes, people are right. PGP is highly needed, so I am quite glad you are working on it :heart: !

**Comment by mbilker** [comment]
@enoversum Currently does not work on Windows. What do you normally use on Windows for PGP? I may target `kbpgp` as a fallback from GPG, but GPG is much faster than `kbpgp`.

**Comment by enoversum** [comment]
@mbilker I actually only used PGP in conjunction with Gmail and a js extension to support encryption/decription right within Chrome, and this dates back a few years. My main client (Mailbird) until I started to use Nylas didn’t and will not have that option anytime soon, so I basically did not use PGP since quite a while…
Do I get it right that I would have to install something third-party in order to enable PGP in Nylas?

**Comment by mbilker** [comment]
@enoversum No no. I need to reconfigure my plugin to accept storing keys for use with `kbpgp`.

**Comment by enoversum** [comment]
@mbilker Okay, good to know. If you need help with any testing and the likes just let me know :wink: .

**Comment by saif-azmi** [comment]
+1 Looking forward to this feature. Then I'll be using Nylas 100% :D

**Comment by grinich** [comment]
Hey everyone-- thanks for your patience! Just wanted to give you a heads up that we are actively working on this. Coming very, very soon. 😄 🚀 🔒 🔑 

<img width="304" alt="screen shot 2016-04-20 at 5 00 08 pm" src="https://cloud.githubusercontent.com/assets/92417/14758228/9feef98a-08b1-11e6-9d68-7b92c6480c22.png">

**Comment by blindgaenger** [comment]
@grinich Great to see this finally coming true! … Is it a new plugin or based on @mbilker 's work?

**Comment by NodokaMurmevent** [comment]
ho yes ! it's cool !

**Comment by pmatos** [comment]
Release that and I will be paying for the pro version! :)

**Comment by w4** [comment]
@grinich are you guys working with @mbilker and his GPG plugin? I'm sure he has some input.

**Comment by alexanderadam** [comment]
@grinich That. Is. Awesome!
Any branch or plugin repo where we could see progress etc?

**Comment by mbilker** [comment]
Yes it was inspired by my work, but it is not based on mine, except for some of the Keybase stuff. It is available from https://github.com/nylas/N1/tree/wip/keybase/internal_plugins/keybase.

**Comment by zlatkobijelic** [comment]
Great to see this coming to fruition.

**Comment by HammyHavoc** [comment]
Very excited for this, Nylas has a lot of potential. I can see a day where it's got as much plugin support as Thunderbird.

**Comment by Info-Screen** [comment]
Is this only PGP or also S/MIME?

**Comment by mbilker** [comment]
@Info-Screen The official implementation is only PGP.

**Comment by bengotow** [comment]
Hey folks! If you're interested in helping us user test the PGP + Keybase plugin we've been working on and live in the bay area, we'd love to hear from you! https://docs.google.com/a/nylas.com/forms/d/1U7sZS2yLdSLlV-J__a97YqFFbCcO4nOVtf5JFFrzYO0

**Comment by grinich** [comment]
Hi everyone-- I'm delighted to announce that we shipped PGP support today in version 0.4.45! It even comes with a free Keybase invite. 😄 💯 🚀 

Read more here: https://nylas.com/blog/pgp

We're actively working on signing messages as well as encrypting attachments. Please open new issues for those (and other) specific enhancements you'd like to see.

Thanks for your patience and support!

**Comment by Ehekatl** [comment]
@grinich not support gpg-agent ? Hope you can add smart card support, adding private key to keybase is not safe at all

**Comment by morachimo** [comment]
@grinich Congrats on the release, a huge selling point for me. Is there a reason why the released implementation is not compatible with GPGTools in Mac? It's a hassle to import every single contact. Is this in the near future?

**Comment by mbilker** [comment]
It uses kbpgp. Does not interact with GPG.

**Comment by joostrijneveld** [comment]
That seems like an odd choice.. What's the motivation behind bypassing `gpg-agent`?

**Comment by logandavis** [comment]
@morachimo @joostrijneveld Smarter key discovery and importing, including importing entire GPG keyrings, is definitely something we intend to add in the future. 

We didn't build this plugin to be tightly coupled with GPG for a handful of reasons. First, it adds a layer of complexity for users, and this plugin's overriding design principle was simplicity. To be frank, I think that a lot of the user-interface difficulties mentioned in our PGP blog post that scare people away from encryption can be blamed on the GPG command line tools. Second, we didn't want to require users to install GPG or GPG4WIN or anything like that to use this plugin. Third, Keybase's kbpgp (the library we used, because we wanted its close coupling with Keybase) doesn't (as far as I know) integrate with GPG, probably because they have their own CLI.

**Comment by Ehekatl** [comment]
@logandavis sure, kbpgp library does not integrate with gpg, but that shouldn't be the only choice, keybase client does support gpg, and since they are still alpha stage, how could kbpgp guarantee security ? I kind understand your choice to keep it simple, however the idea we using PGP are not for convenient. It's good to see Nylas bring a friendly pgp solution to everyone, hope you could also kindly concern add alternative way for decryption.
