### ISSUE TITLE
Calendar invite buttons are unresponsive

### ISSUE THREAD

**Issue by jstejada** [nylas/N1#960]
A user reported that the calendar buttons were unresponsive on OS X, N1 version 0.3.36-e8239a9

<img width="649" alt="cal_invite" src="https://cloud.githubusercontent.com/assets/1271509/12242303/2b1195b4-b84d-11e5-964c-2e3da341d8e0.png">

**Comment by bengotow** [comment]
I think that this may be due to #962, which was reported in Sentry. Going to merge in.
