### ISSUE TITLE
Shows wrong LinkedIn Profile

### ISSUE THREAD

**Issue by cllns** [nylas/N1#965]
I do not have a LinkedIn, but N1 finds a LinkedIn profile anyway. It shows that Job Title, Location, and Position, which are all wrong. The Job Title it finds is Senior Software Engineer. My Twitter profile has the word 'Software' in it, so maybe that's where it's coming from?

LinkedIn doesn't let you search by email, so guessing their profile will always be a moving target. It looks like you'd need to request from the person being shown, their [`r_contactinfo`](https://developer.linkedin.com/docs/fields/contact) to get their twitter account, which isn't really possible in this case.

I imagine it's easier to find the correct existing profile than to determine that a person doesn't have an account (unless they have a name that's not on LinkedIn). Still, I think there should be some threshold of confidence, where if the software is only, e.g. 10% sure, then it won't show info from the LinkedIn profile, because it might be wrong.

Version 0.3.36-e8239a9 (0.3.36-e8239a9)

**Comment by mbilker** [comment]
Thanks for the report @cllns. I swear there is another issue like this one regarding some emails like `contact@nylas.com`. I am trying to find it since these two issues are related.

This is because the Sync Engine confuses shared emails.

**Comment by cllns** [comment]
Thanks for the quick response!

My email is not shared, so I'm not sure it's related. It's also **@** a custom domain, and it's the only address on the domain.

**Comment by mbilker** [comment]
From what I remember, the issue lies with multiple senders for an email involving the person in question. If an email included that person's email in any field it may have been bundled into one larger `contactinfo` field.

I am still looking for the primary issue posting on N1's issue page as well as the Sync Engine's issue page.

**Comment by cllns** [comment]
Just realized I didn't mention that the person has the same first and last names as me. Not sure if that was obvious or not!

**Comment by mbilker** [comment]
Wow! That is not obvious, but odd indeed.

**Comment by cllns** [comment]
Yea, it also makes the problem harder to solve. 

Since N1 (or maybe the Sync engine?) reads the location from LinkedIn, maybe that should be compared with their twitter location? For example, my twitter shows my location correctly as Boulder, CO. Therefore, it should only show LinkedIn profiles where that matches?

**Comment by louim** [comment]
I think it's related to https://github.com/nylas/N1/issues/137. Nylas use an external service, and their info is sometime stale or wrong.

**Comment by standage** [comment]
I am experiencing a similar issue. The email <dstandag@indiana.edu> is an alias for <daniel.standage@gmail.com>, and that is correct. The other profile information has nothing to do with me though.

![screen shot 2016-03-01 at 2 22 42 pm](https://cloud.githubusercontent.com/assets/566823/13438971/648eb84c-dfb9-11e5-92b5-f83bba6d85d2.png)

**Comment by standage** [comment]
Ah yes, here it is. Someone on my LinkedIn profile with the same name.

![screen shot 2016-03-01 at 2 26 58 pm](https://cloud.githubusercontent.com/assets/566823/13439046/b9c3e184-dfb9-11e5-897a-a5c33754f285.png)

**Comment by standage** [comment]
To be clear, I never asked for it to link to my LinkedIn profile. I only provided my email (at gmail.com) and my aliases: N1 must have done the rest itself.

**Comment by louim** [comment]
You should be able to claim your data on https://www.fullcontact.com/ (the service used to generate the infos) and decide what you want to do with it.

**Comment by louim** [comment]
The direct link to claim your "profile" is: https://www.fullcontact.com/privacy/claim/

**Comment by bengotow** [comment]
Hey folks! There have been a lot of complaints about the quality of the sidebar data and we've switched data providers in the most recent update (0.4.14). I think this  largely resolve this issue, though it's always possible this data will be outdated or incorrect. In the future, we may try to build our own dataset so we can provide an way way to fix it or change it when it's wrong. Cheers!
