### ISSUE TITLE
Message-view breaks FROM info on small width

### ISSUE THREAD

**Issue by cllns** [nylas/N1#967]
When the message-view item is expanded and the column is at the minimum width, the 'From' breaks to the next line for me. This issue is based on the length of the sender's email and their name, but I have a relatively short name and email. Increasing the minimum width of that column is an option, but that just puts the problem off.
![screen shot 2016-01-11 at 17 06 48](https://cloud.githubusercontent.com/assets/632942/12251084/3cb39cea-b889-11e5-8306-12e1db0125c5.png) 
(Yes I sent that email to myself, for testing.)

An idea: Make it so the top-most line stays the same when expanded, so: **First** To: You, then the full from email and name can be on the next line, formatted the same as the To: line.

If that sounds like a good idea, I can try implementing. I don't know CoffeeScript well, or know React at all, so if someone else wants to take it, that's fine too :)

**Comment by bengotow** [comment]
Hy @cllns — we've redesigned this a bit in `0.4.4` and @jstejada addressed this wrapping bug. Let me know what you think, and feel free to re-open if you run into any issues.
