### ISSUE TITLE
Inline images

### ISSUE THREAD

**Issue by natarius** [nylas/N1#968]
Hey...would love to be able to add inline images

**Comment by electrodaddy** [comment]
Me too

**Comment by mbilker** [comment]
Thanks for the suggestion @natarius. Is this for the composer or for a plugin?

**Comment by natarius** [comment]
Composer

—

**Comment by mbilker** [comment]
Technically, the Composer already supports inline images. There is no way to insert them except by plugins and a src URL or a base64 encoded data URL.

**Comment by natarius** [comment]
I see. Any plans to add that feature in the future?  

  

Copy &amp; paste support as well as Drag &amp; drop would be nice :)

> On Jan 12 2016, at 8:54 pm, Matt Bilker &lt;notifications@github.com&gt;
wrote:  

>

> Technically, the Composer already supports inline images. There is no way to
insert them except by plugins and a src URL or a base64 encoded data URL.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/968#issuecomment-171167743).![](https://github.com/notifications/beac
on/AAlEYy96ZGFT-yUDRm9RwAbJqk6QKLnEks5pZdAdgaJpZM4HCzjx.gif)

**Comment by digitalmaster** [comment]
This is actually the only thing I still switch to gmail.com for. +1

**Comment by jonnale** [comment]
+1

**Comment by xgt001** [comment]
Can anyone tell me which plugin to use for the time being? :) Thanks!

**Comment by alordmg** [comment]
+1

**Comment by tschf** [comment]
This appears to be flagged on the Trello N1 roadmap board (Ideas Core N1). See https://trello.com/c/m9IFvC60/39-inline-images-in-composer

Looking forward to this - I'm all too frequently adding inline images.

**Comment by luctus** [comment]
I'd love to be able to paste inline images too!! +1

**Comment by edhatricksmith** [comment]
+1. It's unfortunate that I have to switch client to be able to do this.

**Comment by BlockNinja** [comment]
+1

Need this. Especially for work.

**Comment by AncientToaster** [comment]
Yep, this comes up all the time for me too.

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/4239

**Comment by mondras** [comment]
+1

**Comment by jackiehluo** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/5617

**Comment by digitalmaster** [comment]
Nylas is by far my fav client.... nothing else even comes close.. But really wish this one was prioritized 🙏

**Comment by hallamoore** [comment]
Another request: https://nylas.zendesk.com/agent/tickets/5887

**Comment by s2imon** [comment]
+1

**Comment by digitalmaster** [comment]
YESSS!!! Today's update finally ads inline image support! So happy had to let the world know! lol https://twitter.com/jBhackin/status/781914469731409920

**Comment by luctus** [comment]
OMG! Thanks!!

**Comment by jackiehluo** [comment]
Hey! We pushed a release today that should fix this issue (`0.4.56`). Let me know if that's not working! 🎉

**Comment by grinich** [comment]
so hot! 🔥

![dj-hotness](https://cloud.githubusercontent.com/assets/92417/19009276/a2b5bd84-8737-11e6-992c-2274f60b184b.gif)

**Comment by steven-murray** [comment]
This is not working for me on Ubuntu 16.04 and v2.0.15
