### ISSUE TITLE
Split view resets resized list after view change

### ISSUE THREAD

**Issue by marcvdm** [nylas/N1#97]
I currently have the split view option enabled but i have resized the email list way smaller. But when i go to the plugins view and then back to my inbox the split view resets and does not remember the width of the resized list.

**Comment by alexmic** [comment]
+1

**Comment by gabrielso** [comment]
:heavy_plus_sign:

**Comment by magalhas** [comment]
I've just experienced this as well.

**Comment by tobico** [comment]
+1

**Comment by wengwch** [comment]
+1

**Comment by jstejada** [comment]
merging into #833
