### ISSUE TITLE
Pasting inline images

### ISSUE THREAD

**Issue by electrodaddy** [nylas/N1#970]
Hi. I use TextExpander a lot. Formatting, HTML and images seem to be screwed up when using in N1. Can this be improved? Thanks!

**Comment by bengotow** [comment]
hey @electrodaddy — I think we can definitely improve this. Can you provide an example that doesn't look the way you'd expect that we can add to the tests? I think we allow most HTML as of version `0.3.36`, but we still format a few things out.

**Comment by electrodaddy** [comment]
Hi @bengotow - Here is the HTML that N1 received:

<p style="margin-bottom: 0px; font-stretch: normal; font-size: 13px; line-height: normal; font-family: Helvetica; color: rgb(35, 35, 35); min-height: 16px;"><br></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 13px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35);">--&nbsp;</p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35);"><b>Steve Kitch</b>&nbsp;| Audiomaster Ltd.</p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35);">Mastering Engineer</p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35); min-height: 12px;"><br></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(18, 85, 204);"><b>Phone:</b>&nbsp;<a>0800 99 89 565</a>&nbsp; | &nbsp;<a>+44 (0) 1935 280 321</a></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(18, 85, 204);"><b>Email:</b> <a href="mailto:steve@audiomaster.co.uk">steve@audiomaster.co.uk</a></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35);"><b>Office:</b> 10 Old Park Road, Exeter, Devon EX4 4EZ, UK</p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35); min-height: 12px;"><br></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(18, 85, 204);"><a href="http://www.audiomaster.co.uk/">http://www.audiomaster.co.uk</a>&nbsp;</p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35); min-height: 12px;"><br></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 12px; line-height: normal; font-family: Helvetica;"><img alt="audiomaster_email_logo.png"></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35); min-height: 12px;"><br></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35);">Follow us on twitter at&nbsp;<a href="http://www.twitter.com/audiomaster">twitter.com/audiomaster</a></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(18, 85, 204);">Add us on Facebook at&nbsp;<a href="http://www.facebook.com/audiomaster.co.uk">Facebook.com/audiomaster.co.uk&nbsp;</a></p><p style="margin-bottom: 0px; font-stretch: normal; font-size: 11px; line-height: normal; font-family: Arial; color: rgb(35, 35, 35);">Send your tracks instantly at&nbsp;<a href="http://www.audiomaster.co.uk/send">audiomaster.co.uk/send</a></p>

The image didn't make it. And the colour of some of the titles got changed.

**Comment by bengotow** [comment]
Hi @electrodaddy — thanks, I've been able to reproduce this. Looking into it now.

**Comment by bengotow** [comment]
It looks like the signature HTML that you attached (Sig_HTML.txt) contains those colors and doesn't include the image URL (the image tag is missing a `src`). When I render that HTML as an HTML file, it looks like this: https://dl.dropboxusercontent.com/u/4803975/input.html. It seems N1 is displaying it correctly based on that HTML.

**Comment by electrodaddy** [comment]
This was the HTML after N1 had processed it. Before it went in all the text was black and not blue. And in other mail apps I have then the image gets imported and used as an embedded/inline image.

**Comment by bengotow** [comment]
Oh I see - can you send me the HTML before you put it into N1? We don't currently support inline images, so using an image in your signature requires uploading the image to a server / service. The coloring is very strange though—would need to see what exactly the app is doing when you give it the original HTML.

**Comment by stephen-puiszis** [comment]
@bengotow is image support in emails a part of the roadmap? This seems to be a pretty important feature if you want to convert Gmail folks.

**Comment by jackiehluo** [comment]
Hey! We pushed a release today that should fix this issue (`0.4.56`). Let me know if that's not working!
