### ISSUE TITLE
Editing template before filling in fields reverts template upon send

### ISSUE THREAD

**Issue by smacking** [nylas/N1#975]
Video: http://cl.ly/2l2M043H2m1o

This is a MAJOR bug for persons like me that use Templates a lot. It already caused me problems.

**Comment by jstejada** [comment]
hey @smacking , thanks for reporting this. I think you're running an outdated version of the templates plugin. We'll automatically update our core plugins on the next release so you don't have to uninstall and reinstall the plugin. It's coming soon so hang tight.
If the issue persists after updating reopen this issue. Thanks!

**Comment by smacking** [comment]
What should I then do to update it to the latest version, @jstejada?

**Comment by jstejada** [comment]
we'll push a new release soon
