### ISSUE TITLE
Gmail delete shortcut # doesn't work on UK Mac keyboards

### ISSUE THREAD

**Issue by electrodaddy** [nylas/N1#976]
Gmail delete shortcut # doesn't work on UK Mac keyboards. When using gmail on web then you can enable custom shortcuts so I have D as delete. At the moment I can't delete using the keyboard! Any advice?

**Comment by mbilker** [comment]
Shortcuts can be overridden similarly to the Atom editor, but officially it isn't well supported. This feature is coming soon.

**Comment by electrodaddy** [comment]
Thanks @mbilker. I've seen that you can definite additional shortcuts in the shortcuts file. However I can't find any documentation on how to do this. Is there anything available?

**Comment by jstejada** [comment]
@electrodaddy , try taking a look at https://github.com/nylas/N1/blob/master/keymaps/templates/Gmail.cson or https://github.com/nylas/N1/blob/master/keymaps/templates/Google%20Inbox.cson for examples on defining new keymaps

**Comment by laughedelic** [comment]
And what about available commands to bind shortcuts to? For example I want to add keymaps for scrolling, but I don't know how to refer to these actions. 
Probably there is some relevant Electron documentation?

**Comment by jackiehluo** [comment]
If that's still happening, let us know—closing out of inactivity!
