### ISSUE TITLE
Reply All includes myself

### ISSUE THREAD

**Issue by linchpinstudios** [nylas/N1#977]
If I click reply all it is adding my address to the reply in the "CC" field. 

When replying all it should exclude my address from the recipient list.

**Comment by bengotow** [comment]
Hey @linchpinstudios — are you using any aliases with your account? Can you expand the message headers and see if / how your email address appears? That should help track this down.

**Comment by linchpinstudios** [comment]
It looks like it was the alias. The main address was actually an alias so the main address was missed. I added the Alias and it started working correctly.
