### ISSUE TITLE
Can't Enlarge/Reduce Text in Main Window

### ISSUE THREAD

**Issue by JohnSandel** [nylas/N1#979]
The text size of emails, in the main window's list-view, is hard for my old eyeballs to read. A simple Prefs setting for enlarging and reducing text would improve N1.

**Comment by bengotow** [comment]
Hi @JohnSandel — this is coming in the next update, which should be out today or tomorrow. Stay tuned! (Related: #699 )

**Comment by JohnSandel** [comment]
Yay! Thank you.
