### ISSUE TITLE
The package is of bad quality

### ISSUE THREAD

**Issue by lowson** [nylas/N1#980]
Hey Guys, got some issues with the current deb file the ubuntu is complaining about:

N1.deb:
E: nylas: control-file-has-bad-permissions postinst 0775 != 0755
E: nylas: control-file-has-bad-permissions postrm 0775 != 0755
N: Some overrides were ignored, since the tags were marked "non-overridable".
N: Use --verbose for more information.

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

Can we get the permissions set correctly?

**Comment by bengotow** [comment]
Closing as dup of #710 — we should get this fixed this week. Thanks!

**Comment by lowson** [comment]
Apologies on creating a dup, excited to start testing!

**Comment by bengotow** [comment]
Hi @lowson — can you try this build and see if it resolves the issue for you?

https://edgehill.s3.amazonaws.com/0.3.43-c8dcab5%2Flinux-deb%2Fx64%2FN1.deb

It should address the permissions issue - just want to check and make sure you don't encounter any other errors before we ship an update.

**Comment by lowson** [comment]
@bengotow sorry for the delay, tested on Ubuntu 14.04 and had no issues, looks good now
