### ISSUE TITLE
Add archiving on IMAP accounts

### ISSUE THREAD

**Issue by ThePsionic** [nylas/N1#983]
Suggestion: Add an archiving button on IMAP accounts by either moving the mail to an "Archive" folder or having the user set a folder to move archived mail into.

**Comment by ThePsionic** [comment]
I just realised that most of my IMAP accounts have an archive option, just one that's not (which is an outlook 365 account). Why this?

**Comment by jstejada** [comment]
Hi @ThePsionic , it's because Outlook doesn't have an archive folder by default. If you create a folder called Archive, the option to archive mail under your outlook account will appear. Hope this helps!

**Comment by ThePsionic** [comment]
It doesn't seem to be working. I made the folder and even restarted N1, but an archive option is still not available.
![screenshot_4](https://cloud.githubusercontent.com/assets/842080/12302777/46fcc484-ba27-11e5-9b5b-e4ff7e032f8f.png)

**Comment by jstejada** [comment]
Hey @ThePsionic , that looks good. If you give it a while our backend will update that folder to be the standard archive folder and it should work for you.

**Comment by abojchevski** [comment]
I am having a similar problem.


![selection_003](https://cloud.githubusercontent.com/assets/8150330/14118261/00ed4ce0-f5e9-11e5-8d5e-c31d1cdd3a29.png)

The archive button has not showed up after a while. How much time should I give to the backend?

**Comment by jstejada** [comment]
hey @abojchevski it should take that long, and the archive folder should appear at the top with the other main categories. Let me know if this is not the case.

**Comment by abojchevski** [comment]
@jstejada still no button so far.

**Comment by abojchevski** [comment]
@jstejada Managed to get it sorted out. I initially had "Archives" folder. I tried to rename the folder from the app (Archives -> Archive) but apparently that did not work and I had to create a new remote folder "Archive".
