### ISSUE TITLE
smtp laposte.net

### ISSUE THREAD

**Issue by bertrand47** [nylas/N1#984]
Hi,
I'm in France, i've no problem with Gmail, but with smtp.laposte.net, that usually works with SSL and Port 465 and "Please check that your SMTP settings are correct". Any idea ?

**Comment by bengotow** [comment]
Hi @bertrand47 - can you see if it might be any of these issues? https://nylas.zendesk.com/hc/en-us/articles/216118977-What-are-the-limitations-of-IMAP-SMTP-support-

**Comment by bertrand47** [comment]
thanks, but there is no answer to my problem

**Comment by bertrand47** [comment]
Since version 0.3.43-b95f1f7, this morning it works!
I put my mail address everywhere (label, user...).

**Comment by grinich** [comment]
glad to hear it! :)
