### ISSUE TITLE
Enable Proxy usage

### ISSUE THREAD

**Issue by juliengdt** [nylas/N1#985]
Is it possible to enable proxy usage directly trough Pref pane of N1 ?

Could be awesome if we will be able to use N1 in firms !

Cheers from France

![capture d ecran 2016-01-13 a 15 22 35](https://cloud.githubusercontent.com/assets/6575155/12296641/3ee2f8c2-ba09-11e5-981b-7a1ff2c6cf53.png)

![capture d ecran 2016-01-13 a 15 21 35](https://cloud.githubusercontent.com/assets/6575155/12296617/1c1b3fd4-ba09-11e5-933a-34e51bf79e34.png)

**Comment by mbilker** [comment]
This is related to #104
