### ISSUE TITLE
Email sync times out

### ISSUE THREAD

**Issue by rdebeasi** [nylas/N1#986]
I haven't used N1 in a while, and I just upgraded to the latest version and logged in. When I did so, I got the following message: "An error occurred while syncing your mailbox. Sync will resume in a moment...". Even after letting it resume a few times, I never got new messages in my inbox.

Next, I removed my account from N1, deleted the Nylas N1 directory from `~/Library`, re-added the account, and tried again. First, I got the same error, but with an empty inbox. Then, after a few attempts, I got old messages in my inbox, but the error persisted. Resuming the sync a few times didn't fix the problem.

For what it's worth, I'm using a Gmail for Work account (i.e., not one that ends in `@gmail.com.`).

I've attached screenshots of the logs.

Log with no emails:
![no-emails](https://cloud.githubusercontent.com/assets/1299370/12297469/53844f0c-b9db-11e5-89a3-af14732ba1f8.png)

Log after getting just old emails:
![old-emails](https://cloud.githubusercontent.com/assets/1299370/12297470/53898e5e-b9db-11e5-9c40-17b9c7e4a276.png)

[Here's the full activity log.](http://hastebin.com/ucetejejoy.curl)

After I restart N1, the issue persists. Here's a log from a fresh session:

```
ESOCKETTIMEDOUT | ESOCKETTIMEDOUT09:57:22  RunCopycurl -X GET "https://[key]:@api.nylas.com/events?limit=45&offset=30"
ESOCKETTIMEDOUT | ESOCKETTIMEDOUT09:57:22  RunCopycurl -X GET "https://[key]:@api.nylas.com/contacts?limit=45&offset=30"
ESOCKETTIMEDOUT | ESOCKETTIMEDOUT09:57:22  RunCopycurl -X GET "https://[key]:@api.nylas.com/drafts?limit=30&offset=0"
ETIMEDOUT | ETIMEDOUT09:56:09  RunCopycurl -X GET "https://[key]:@api.nylas.com/events?limit=45&offset=30"
ETIMEDOUT | ETIMEDOUT09:56:09  RunCopycurl -X GET "https://[key]:@api.nylas.com/contacts?limit=45&offset=30"
ETIMEDOUT | ETIMEDOUT09:56:09  RunCopycurl -X GET "https://[key]:@api.nylas.com/drafts?limit=30&offset=0"
```

N1 looks awesome, and I'm excited to be able to use it! Thanks so much in advance for your help.

**Comment by TheJefe** [comment]
Nylas is currently reporting degraded performance on their API servers. http://status.nylas.com/

**Comment by mikebianchini** [comment]
I'm seeing this same issue.

**Comment by rdebeasi** [comment]
The issue is listed as resolved on http://status.nylas.com/, but I'm still experiencing the same behavior as before, with the same timeout errors as before.

**Comment by rdebeasi** [comment]
This issue is still occurring for me. Why has the issue been closed?

**Comment by jujes** [comment]
me too: 

> An error occurred while syncing your mailbox. Sync will resume in a moment
