### ISSUE TITLE
Inbox search is very slow and often doesnt work. 

### ISSUE THREAD

**Issue by smessina3000** [nylas/N1#987]

**Comment by mbilker** [comment]
From #571 by @bengotow 

Unfortunately, N1 maps through to your underlying mail provider's search (usually IMAP) to execute the search query. For some reason, that is returning no results even for the exact subject phrase. Can you try searching for only the first 10-20 characters of the email subject and let me know fi that changes the results?

We'll implement our own full search eventually, but for now we're tied to whatever search results Exchange / Gmail / IMAP can provide.

**Comment by joesepi** [comment]
I have Gmail and Outlook accounts in N1. Gmail search is working fine. Outlook search gives me the progress indicator and then says "No threads to display." I am searching for one word that I know is in a bunch of emails: uncubed

This pretty much makes N1 unusable for me. :(

**Comment by dcrystalj** [comment]
same here. typing in search i get suggestions but hitting enter displays nothing then.

**Comment by JoanPlume** [comment]
+1

**Comment by raknerak** [comment]
+1

**Comment by mbilker** [comment]
Please stop with the +1's. Click Subscribe on the right.

**Comment by tartley** [comment]
On N1 I sometimes get no search results at all, depending on what my search term is. Retrying a search with no results will reliably continue to return no results.

@mbilker The same search from Thunderbird, and from a webmail UI (https://webmail.webfaction.com) finds everything fine.

I'm unsure precisely when Thunderbird does a server-side search versus searching local files, but I'm guessing the webmail UI must be using server-side search?

This is on an IMAP account.

The search term is a single word ("Sophie"), which is both the name part of a "From" contact, and the email address itself starts "Sophie.Tyler@..." and it is present in the body of the email.

When I'm typing "Sophie" in the N1 search box, I get some completion options, one of which is the email address of the Sophie I'm looking for ("Sophie.Tyler@..."). If I select that option and search, I still get no results.

**Comment by jstejada** [comment]
Hi everyone, there's 3 separate issue for this so I'm merging into a single one: #750
