### ISSUE TITLE
Feature Request: Show unread counts for labels

### ISSUE THREAD

**Issue by IVBakker** [nylas/N1#989]
![image](https://cloud.githubusercontent.com/assets/4979840/12299341/27ba5f14-ba0e-11e5-8e23-ac1461afcfe7.png)
 Vs 

![image](https://cloud.githubusercontent.com/assets/4979840/12299348/350a21d6-ba0e-11e5-8fc4-95ed4208e1ae.png)

**Comment by jstejada** [comment]
Hi @IVBakker , you can enable unread counts for all your labels by going to `Preferences -> General` and selecting `Show unread counts for all folders / labels`

**Comment by IVBakker** [comment]
Oh sorry thanks, why isn't it ON by default
