### ISSUE TITLE
[Windows] Unicode icon on startup page

### ISSUE THREAD

**Issue by luisrudge** [nylas/N1#99]
![image](https://cloud.githubusercontent.com/assets/941075/10626072/d4e978b6-7781-11e5-847d-6991d153cc05.png)

**Comment by bengotow** [comment]
Hi @luisrudge — thanks for filing this. Which version of Windows are you using? We can swap that out for an image, but it looks like it's working for a few folks on our team using Windows 7/8. Are you building from source or using the built version of the app?

**Comment by luisrudge** [comment]
win 10. fresh download from the website

**Comment by bengotow** [comment]
This has been fixed.
