### ISSUE TITLE
Update e-mails are being spammed

### ISSUE THREAD

**Issue by ThePsionic** [nylas/N1#991]
I currently have 11 e-mail accounts linked, which means I get 11 mails from you guys when a new version is released. I personally think only one is enough though, maybe something to look into.

**Comment by bengotow** [comment]
Hi @ThePsionic — whoa, sorry about that! In the latest update (0.3.43), we added an option to unsubscribe from the newsletter right within N1. The option is in the account preferences here:
![image](https://cloud.githubusercontent.com/assets/1037212/12303437/2b48cb7c-b9df-11e5-877b-6da9ccc0e8d2.png)

**Comment by ThePsionic** [comment]
Hah, it was fixed before it was even a problem :P thanks for that.
