### ISSUE TITLE
Turning off newsletters for one account turns it off for all accounts

### ISSUE THREAD

**Issue by ThePsionic** [nylas/N1#993]
Kind of a follow up to #991. When you turn off the checkbox for one account, all checkboxes are turned off. Turning one checkbox on turns all of them on, too.

**Comment by louim** [comment]
To add to that, it seems impossible to reenable one after that. The checkbox appear "checked", but coming back the preference it is still unchecked.

**Comment by ThePsionic** [comment]
Hm, I can't replicate that, it just acts as a global setting for me instead of
an account-specific one.

> On Jan 13 2016, at 7:29 pm, Louis-Michel Couture
&lt;notifications@github.com&gt; wrote:  

>

> To add to that, it seems impossible to reenable one after that. The checkbox
appear "checked", but coming back the preference it is still unchecked.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/993#issuecomment-171389135).![](https://github.com/notifications/beac
on/AAzZYP-OzQwQdI7uG3GE6agZdGZWtotAks5pZo7_gaJpZM4HEPU_.gif)

**Comment by bengotow** [comment]
Hey folks - I've been able to reproduce this and we're working on a fix. Sorry for the hassle.
