### ISSUE TITLE
Sending multiple emails when an email address is wrong

### ISSUE THREAD

**Issue by jmsulli6464** [nylas/N1#994]
When you send an email with an incorrect email(one that doesn't exist but has proper format) it will move email to draft and continue to try. It then sends the email to all the parties in the the list until you close nylas or you delete the draft
![screen shot 2016-01-13 at 11 24 12 am](https://cloud.githubusercontent.com/assets/16106817/12303667/d57c246e-b9e8-11e5-8a57-43db6e2b18f3.png)
![screen shot 2016-01-13 at 11 26 20 am](https://cloud.githubusercontent.com/assets/16106817/12303665/d254707a-b9e8-11e5-923f-6e775982a125.jpg)

**Comment by bengotow** [comment]
Whoa. Thank you for bringing this to our attention—our team is looking in to this and we'll keep you posted. What mail provider (Outlook / FastMail) are you using? It looks like our API must be returning an error even though the underlying "send" through your mail provider is succeeding.

**Comment by bengotow** [comment]
Hi @jmsulli6464 — just wanted to follow up. It looks like your SMTP server was responding with "Sending to at least one recipient failed", and N1 was re-sending the message over and over again, causing the valid recipients on the message to receive it over and over.

We've changed the behavior server-side so that N1 will /not/ send over and over, and we'll address this in a future update so that N1 will tell you essentially "Your message could not be sent to a@n.com but it was sent to the other recipients".

**Comment by jmsulli6464** [comment]
Thank you Ben,

  

You guys have an awesome client and i look forward to pulling it apart and
adding stuff to it

  

john

> On Jan 13 2016, at 4:07 pm, Ben Gotow &lt;notifications@github.com&gt;
wrote:  

>

> Hi [@jmsulli6464](https://github.com/jmsulli6464) — just wanted to follow
up. It looks like your SMTP server was responding with "Sending to at least
one recipient failed", and N1 was re-sending the message over and over again,
causing the valid recipients on the message to receive it over and over.

>

> We've changed the behavior server-side so that N1 will /not/ send over and
over, and we'll address this in a future update so that N1 will tell you
essentially "Your message could not be sent to [a@n.com](mailto:a@n.com) but
it was sent to the other recipients".

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nylas/N
1/issues/994#issuecomment-171466579).![](https://github.com/notifications/beac
on/APXFQQCgRzILJ8Gy1YFuc9hQABw4K50Cks5pZtA5gaJpZM4HEPm4.gif)
