### ISSUE TITLE
Smaller (narrower) toolbar (OS X)

### ISSUE THREAD

**Issue by m3adi3c** [nylas/N1#997]
I would love to have the option to make the toolbar (top bar) narrower. I find it huge now, it's wider than Safari's. Best thing would be to have the option, when choosing the icons to have in the toolbar, to have that option "Use small size" that most apps have. This way, when selecting that, all the icons and the toolbar get narrower.

**Comment by bengotow** [comment]
Hey @m3adi3c, thanks for downloading N1! I totally agree. We're planning to shrink the toolbar to match the standard for Mac apps, and our designer recently finished a smaller set of icons. I'll leave this open until that gets merged in.

In the meantime, `0.3.43` adds an "Interface Zoom" feature. If you feel like the entire app is too large, you might like the `80%` mode. It'll make the entire app 20% smaller - toolbars, icons, fonts, etc.

![image](https://cloud.githubusercontent.com/assets/1037212/12305876/b7ccf9fe-b9eb-11e5-9214-b6c3191d7b50.png)

**Comment by m3adi3c** [comment]
Thanks for the reply, @bengotow. Unfortunately, for my eyes, going to 80% is killer for the fonts. But it's good to know that you're on it. N1 is really great, I'm excited to see its further development!

**Comment by mbilker** [comment]
Did you want a smaller interface, but with the same sized fonts?

**Comment by m3adi3c** [comment]
I mainly want a smaller (narrower) top bar, with all its icons. I'm generally OK with the fonts and the other aspects of the interface. But the top bar is strikingly fat. :)

**Comment by bengotow** [comment]
This has landed! Still some tweaks to be made but we're getting close.
