### ISSUE TITLE
My mail won't sync at all - for one of my two accounts

### ISSUE THREAD

**Issue by grimen** [nylas/N1#999]
I cannot get Nylas sync my email for account `grimen@gmail.com` since Nov - my other Gmail account syncs. I don't get no error messages, and tried to remove, uninstall, clear caches, reinstall, readd the account and same thing - only mails from before November. Makes the client impossible to use in practice as you may understand.

**Comment by Sawsmith** [comment]
I have exactly the same problem. I would like to give N1 a try, but I've installed it twice now and it still won't sync. I have an outlook account - @hotmail.co.uk.

**Comment by tgpo** [comment]
Same. Happened after I installed the latest update.  I'm now running 0.3.43.

**Comment by mcescalante** [comment]
I am also seeing this issue on the latest build. I only have 2 gmails linked, 1 x Gmail and 1 x Google Apps. The 2nd (Google Apps) email in my list will not sync anymore.

**Comment by jackiehluo** [comment]
Hey! Closing this issue for now because it should be fixed—if it's not, email us at support@nylas.com!
